- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PartitionedFileWriter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartition.java
Currently, the sort-merge shuffle implementation uses a piece of direct memory as index entry cache for acceleration. This patch switches to heap memory instead to reduce the consumption of direct memory which can further reduce the possibility of OutOfMemoryError.
- Use heap memory instead of direct memory as index entry cache for sort-merge shuffle.
This change is already covered by existing tests, such as PartitionedFileWriteReadTest, SortMergeResultPartitionTest and BlockingShuffleITCase. …
> [FLINK-21778][network] Use heap memory instead of direct memory as index entry cache for sort-merge shuffle

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliClient.java
- flink-table/flink-sql-client/src/test/resources/sql/catalog_database.q
- flink-table/flink-sql-client/src/test/resources/sql/function.q
- flink-table/flink-sql-client/src/test/resources/sql/module.q
- flink-table/flink-sql-client/src/test/resources/sql/table.q
- flink-table/flink-sql-client/src/test/resources/sql/view.q
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/utils/PrintUtils.java
- flink-table/flink-table-common/src/test/java/org/apache/flink/table/utils/PrintUtilsTest.java
*Currently, SQL Client displays the column names when the return set of `SHOW MODULES` is empty:*
```
SHOW MODULES;
+-------------+
| module name |
+-------------+
0 row in set
!ok
```
*The output of `SHOW MODULES` could be improved by simply omit the column names header.*
- *`CliClient` add `callShowResult` and `callShowCurrentResult` method to unify the client execution of `SHOW` and `SHOW` statement.* …
> [FLINK-21774][sql-client] Do not display column names when return set is emtpy in SQL Client

- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/logical/CumulativeWindowSpec.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/logical/HoppingWindowSpec.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/logical/TumblingWindowSpec.java
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdWindowProperties.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalWindowJoin.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/optimize/program/FlinkChangelogModeInferenceProgram.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/rules/FlinkStreamRuleSets.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/rules/physical/stream/StreamPhysicalJoinRule.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/rules/physical/stream/StreamPhysicalTemporalJoinRule.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/rules/physical/stream/StreamPhysicalWindowJoinRule.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/utils/WindowJoinUtil.scala
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/join/WindowJoinTest.xml
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/join/WindowJoinTest.scala
This pull request aims to support streaming WindowJoin in planner.
- Introduce `StreamPhysicalWindowJoin`
- Update `FlinkChangelogModeInterenceProgram` and `FlinkRelMdWindowProperties` to take `StreamPhysicalWindowJoin` into consideration.
- Introduce `StreamPhysicalWindowJoinRule` to convert `FlinkLogicalJoin` to `StreamPhysicalWindowJoin` if join condition contains window starts equality of input tables and window ends equality of input tables.
- UT in `WindowJoinTest`. …
> [FLINK-19609][table-planner-blink] Support streaming window join in planner

- flink-tests/src/test/java/org/apache/flink/test/recovery/ProcessFailureCancelingITCase.java
The cancellation of the job may fail if the job termination finishes so quickly that the job has been cleaned up before the cancellation has been processed.
The cancellation is unnecessary anyway because the TM failure causes the job to fail and we explicitly forbid restarts.
As such we can just remove the cancel call.
> [FLINK-21610][tests] Do not attempt to cancel the job

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/BufferReaderWriterUtil.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/BufferWithChannel.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PartitionSortedBuffer.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PartitionedFileWriter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortBuffer.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartition.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PartitionSortedBufferTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PartitionedFileWriteReadTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionTest.java
Currently, the sort-merge shuffle implementation uses 4M unmanaged direct memory as cache for data writing. This patch replaces the cache with writev system call which can reduce the unmanaged direct memory usage without any performance loss.
- Remove the data writing cache in PartitionedFileWriter;
- Allocate a collection of network buffers as write buffer;
- Bulk write the data out when the write buffer is full.
This change is already covered by existing tests, such as PartitionedFileWriteReadTest, SortMergeResultPartitionTest and BlockingShuffleITCase. …
> [FLINK-21777][network] Replace the 4M data writing cache of sort-merge shuffle with writev system call

- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecUnion.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecUnion.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecUnion.java
- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/JsonSerdeCoverageTest.java
- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/UnionJsonPlanTest.java
- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/runtime/stream/jsonplan/UnionJsonPlanITCase.java
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/UnionJsonPlanTest_jsonplan/testUnion.out
Support json ser/de for StreamExecUnion
Support json ser/de for StreamExecUnion
*(example:)*
- *Added UnionJsonPlanITCase and UnionJsonPlanTest to validate the json ser/de for StreamExecUnion*
> [FLINK-21815][table-planner-blink] Support json ser/de for StreamExecUnion

- flink-core/src/main/java/org/apache/flink/core/memory/MemorySegment.java
- flink-core/src/test/java/org/apache/flink/testutils/ThrowOnDoubleMemoryFreeing.java
- flink-runtime/src/main/java/org/apache/flink/runtime/memory/MemoryManager.java
- flink-runtime/src/test/java/org/apache/flink/runtime/memory/MemoryManagerTest.java
The PR fixes releasing memory segments via `MemoryManager#release(Collection<MemorySegment>)`. Prior to the change the method did not check if the segments have been removed before, but it was freeing all segments nevertheless.
- Free segment only if it still exists in the `MemoryManager` allocated pages.
- Throw exception if a `HybridMemorySegment` is freed twice.
Added tests in `MemoryManagerTest` …
> [FLINK-21728] Do not release segments in MemoryManager#release(Collection<MemorySegment>) if they have been released

- flink-core/src/main/java/org/apache/flink/util/IterableUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/EdgeManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/topology/DefaultLogicalPipelinedRegion.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/topology/DefaultLogicalResult.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/topology/DefaultLogicalTopology.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/topology/DefaultLogicalVertex.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/topology/LogicalPipelinedRegion.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/topology/LogicalResult.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/topology/LogicalTopology.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/topology/LogicalVertex.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adapter/DefaultExecutionTopology.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adapter/DefaultExecutionVertex.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adapter/DefaultResultPartition.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/strategy/SchedulingExecutionVertex.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/strategy/SchedulingResultPartition.java
- flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ExecutionGraphTestUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adapter/DefaultExecutionTopologyTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adapter/DefaultExecutionVertexTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adapter/DefaultSchedulingPipelinedRegionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/strategy/TestingSchedulingExecutionVertex.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/strategy/TestingSchedulingResultPartition.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/strategy/TestingSchedulingTopology.java
*This PR introduces the optimization of the initialization of DefaultExecutionTopology.*
*Based on FLINK-21326, the consumedResults in DefaultExecutionVertex and consumers in DefaultResultPartition can be replaced with ConsumedPartitionGroup and ConsumerVertexGroup in EdgeManager.*
*The complexity of initializing DefaultExecutionTopology decreases from O(N^2) to O(N).*
*For more details, please check [FLINK-21328](https://issues.apache.org/jira/browse/FLINK-21328).*
- *Remove generic from LogicalTopology and its components*
- *Use iterators to implement SchedulingExecutionVertex#getConsumerPartitionGroups and SchedulingResultPartition#getConsumerVertexGroups*
- *Remove DefaultExecutionTopology#connectVerticesToConsumedPartitions, and replace connections between DefaultExecutionVertices …
> [FLINK-21328] Optimize the initialization of DefaultExecutionTopology

- flink-table/flink-sql-client/src/test/resources/sql/module.q
*This pull request adds a case in `CliClientITCase` to test `SHOW [FULL] MODULES` for the default core module.
- Add `SHOW MODULES` and `SHOW FULL MODULES` in `module.q`
This change is can be verified by running `CliClientITCase`. …
> [FLINK-21849][sql-client] Add default module test case for 'SHOW [FULL] MODULES'

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/deserializer/KafkaValueOnlyDeserializerWrapper.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceITCase.java
This pull request fixes bug of referencing uninitialized deserializer in ```ValueDeserializerWrapper``` when using ```KafkaRecordDeserializer#valueOnly```, which would lead to NPE at job compiling stage. 
- Keep the ```deserializeClass``` directly in the instance of ```ValueDeserializerWrapper``` as a member instead of storing the name of the class
- Add an IT case for testing value only deserializer.
- *Added integration tests for using ```KafkaRecordDeserializer#valueOnly``` to build a KafkaSource* …
> [FLINK-21160][connector/kafka] Fix bug of referencing uninitialized deserializer when using KafkaRecordDeserializer#valueOnly

- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecAggregateBase.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecGlobalGroupAggregate.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecGroupAggregate.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecLocalGroupAggregate.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecWindowAggregate.java
- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/GroupAggregateJsonPlanTest.java
- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/JsonSerdeCoverageTest.java
- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/runtime/stream/jsonplan/GroupAggregateJsonPlanITCase.java
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/GroupAggregateJsonPlanTest_jsonplan/testDistinctAggCalls[isMiniBatchEnabled=true].out
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/GroupAggregateJsonPlanTest_jsonplan/testSimpleAggCallsWithGroupBy[isMiniBatchEnabled=true].out
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/GroupAggregateJsonPlanTest_jsonplan/testSimpleAggWithoutGroupBy[isMiniBatchEnabled=true].out
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/GroupAggregateJsonPlanTest_jsonplan/testUserDefinedAggCalls[isMiniBatchEnabled=true].out
*This pr aims to support json serialization/deserialization for StreamExecLocalGroupAggregate and StreamExecGlobalGroupAggregate*
- *Introduce StreamExecAggregateBase*
- *Support StreamExecLocalGroupAggregate and StreamExecGlobalGroupAggregate json serialization/deserialization*
- *Extended GroupAggregateJsonPlanTest and GroupAggregateJsonPlanITCase which could verify the change* …
> [FLINK-21791][table-planner-blink] Support StreamExecLocalGroupAggregate and StreamExecGlobalGroupAggregate json serialization/deserialization

- flink-table/flink-table-common/src/main/java/org/apache/flink/table/data/binary/BinaryRowData.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/data/binary/NullAwareGetters.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/data/binary/SupportsAnyNull.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/join/interval/IntervalJoinFunction.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/join/stream/AbstractStreamingJoinOperator.java
Introduce SupportsAnyNull to BinaryRowData.
We should avoid force casting to implementation. It is better to rely on interface.
> [FLINK-21852][table] Introduce SupportsAnyNull to BinaryRowData

- docs/content.zh/docs/dev/table/sql/create.md
- docs/content/docs/dev/table/sql/create.md
add 'IF NOT EXISTS' to create table statement docs
add 'IF NOT EXISTS' to create table statement docs
- Dependencies (does it add or upgrade a dependency): (yes / no)no
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)no
- The serializers: (yes / no / don't know)no
- The runtime per-record code paths (performance sensitive): (yes / no / don't know)no
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / no / don't know)no
- The S3 file system connector: (yes / no / don't know)no
- Does this pull request introduce a new feature? (yes / no)no …
> [hotfix][docs]add 'IF NOT EXISTS' to create table statement

- azure-pipelines.yml
- flink-end-to-end-tests/run-nightly-tests.sh
- flink-end-to-end-tests/test-scripts/common_artifact_download_cacher.sh
- flink-end-to-end-tests/test-scripts/common_yarn_docker.sh
- flink-end-to-end-tests/test-scripts/docker-hadoop-secure-cluster/Dockerfile
- flink-end-to-end-tests/test-scripts/kafka-common.sh
- tools/azure-pipelines/build-apache-repo.yml
- tools/azure-pipelines/jobs-template.yml
This change aims to download and cache large E2E artifacts from archive.apache.org, to speed up subequent E2E tests. Instead of redownloading these files every time, they are downloaded to the ``e2e_artifact_cache`` folder and linked to where they are expected in the tests. Azure Pipelines will then cache these files, avoiding constant redownloading of hadoop, flink and confluent.
- E2E test scripts have been modified to persist/cache large artifacts used between tests. …
> [FLINK-21561] Predownload/Cache large E2E test artifacts

- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecWindowAggregate.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/keyselector/RowDataKeySelector.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/aggregate/window/SlicingWindowAggOperatorBuilder.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/aggregate/window/buffers/RecordsWindowBuffer.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/aggregate/window/buffers/WindowBuffer.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/aggregate/window/combines/CombineRecordsFunction.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/aggregate/window/processors/AbstractWindowAggProcessor.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/aggregate/window/processors/SliceSharedWindowAggProcessor.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/aggregate/window/processors/SliceUnsharedWindowAggProcessor.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/window/slicing/SlicingWindowOperator.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/window/slicing/SlicingWindowProcessor.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/typeutils/InternalTypeInfo.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/typeutils/WindowKeySerializer.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/util/WindowKey.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/util/collections/binary/AbstractBytesHashMap.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/util/collections/binary/AbstractBytesMultiMap.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/util/collections/binary/WindowBytesHashMap.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/util/collections/binary/WindowBytesMultiMap.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/operators/aggregate/window/SlicingWindowAggOperatorTest.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/typeutils/WindowKeySerializerTest.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/util/collections/binary/WindowBytesHashMapTest.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/util/collections/binary/WindowBytesMultiMapTest.java
Refactor SlicingWindowAggOperatorBuilder to accept serializer instead of LogicalType
Now SlicingWindowAggOperatorBuilder accept LogicalTypes, it is better to avoid LogicalTypes in runtime operators and functions.
Refactor SlicingWindowAggOperatorBuilder.
This change is a trivial reworkwithout any test coverage.
> [FLINK-21818][table] Refactor SlicingWindowAggOperatorBuilder to accept serializer instead of LogicalType

- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecTemporalJoin.java
Use type from RowDataKeySelector in StreamExecTemporalJoin
> [hotfix][table] Use type from RowDataKeySelector in StreamExecTemporalJoin

- docs/content.zh/docs/dev/dataset/overview.md
- flink-core/pom.xml
- flink-core/src/main/java/org/apache/flink/api/common/io/FileInputFormat.java
- flink-core/src/main/java/org/apache/flink/api/common/io/compression/ZStandardInputStreamFactory.java
- flink-core/src/test/java/org/apache/flink/api/common/io/GenericCsvInputFormatTest.java
Allow FileInputFormat to read files compressed in ZStandard format
Added ZStandard as stream input
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (don't know)
- The S3 file system connector: ( don't know)
- If yes, how is the feature documented? ( yes )
> [FLINK-20130][core] Add ZStandard to FileInputFormat

- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/KinesisPubsubClient.java
- flink-end-to-end-tests/flink-glue-schema-registry-test/src/main/java/org/apache/flink/glue/schema/registry/test/GSRKinesisPubsubClient.java
Fix error where GSR end to end test does not compile in IntelliJ.
Removed reference to AWS SDK classes that are shaded by Kinesis client by:
- Made `KinesisPubsubClient` more generic
- Delegate GSR Kinesis functionality to the `KinesisPubsubClient`
- Run Kinesis e2e tests
- Run GSR e2e tests
> [FLINK-21875][hotfix] Fix compilation error in IntelliJ for GSR test

- flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendTestBase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/testutils/statemigration/TestType.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyGroupedPriorityQueue.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java
KeyGroupedInternalPriorityQueue provides public methods that will be modifying the delegated state backend, so it has to be proxyed as well.
This change is partially cover by tests. Proper test coverage is not possible until we test reading from the changelog. Newly added `StateBackendTestBase#testKeyGroupedInternalPriorityQueue` ensures that at least the calls are properly delegated. …
> [FLINK-21831][state][changelog] Add missing delegation of KeyGroupedInternalPriorityQueue

- flink-runtime/src/main/java/org/apache/flink/runtime/state/heap/HeapRestoreOperation.java
```
In the new incremental mode, heap backend wraps KeyGroupsStateHandle
into IncrementalRemoteKeyedStateHandle. The latter don't compute
intersection because it is not directly aware of the offsets. So it just
returns a full keyrange if there is SOME intersection.
On recovery, unused keyGroups are filtered out by RocksDB state backend.
With this change, Heap state backend does the same.
```
The change is covered by existing IT cases. …
> [FLINK-21650] Skip KGs not belonging to this backend on restore (instead of failing)

- flink-runtime/src/main/java/org/apache/flink/runtime/state/StateBackendLoader.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogStateBackend.java
Now that we support constructing `ChangelogStateBackend` from API,  `loadChangelogStateBackend` is no longer the only place for delegating a statebackend.
Move the log to ChangelogStateBackend constructor instead.
> [hotfix] Put the delegating log to ChangelogStateBackend constructor

- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/processor/DeadlockBreakupProcessor.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/processor/ExecNodeGraphProcessor.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/processor/MultipleInputNodeCreationProcessor.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/processor/ProcessorContext.java
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/delegation/BatchPlanner.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/delegation/PlannerBase.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/delegation/StreamPlanner.scala
- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/processor/MultipleInputNodeCreationProcessorTest.java
*in FLINK-21041, we have introduced ExecNodeGraph to wrap the ExecNode topology. DAGProcessor is used for transforming ExecNodeGraph. Their names do not match. This pr aims to rename DAGProcessor to ExecNodeGraphProcessor.*
- *Rename DAGProcessor to ExecNodeGraphProcessor*
- *Rename DAGProcessContext to ProcessorContext*
- *Do some minor abstract in PlannerBase* …
> [FLINK-21890][table-planner-blink] Rename DAGProcessor to ExecNodeGraphProcessor

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveLookupTableSource.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveTablePartition.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveTableSource.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/JobConfWrapper.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/read/HiveBulkFormatAdapter.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/read/HiveCompactReaderFactory.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/read/HiveMapredSplitReader.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/read/HiveVectorizedOrcSplitReader.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/read/HiveVectorizedParquetSplitReader.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/util/HivePartitionUtils.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/util/JobConfUtils.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/util/HiveTypeUtil.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/functions/hive/conversion/HiveInspectors.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/PartitionMonitorTest.java
In order to support watermark for Hive connector (FLINK-21871), we need to extract time from the partition string values. However, currently `HiveTablePartition#partitionSpec` uses `Map<String, Object>` type to store the partition spec which is hard convert back to string values. Therefore, I propose to use the raw `Map<String, String>` type instead which is easier to convert into `Map<String, Object>` when needed.
- Update type of `HiveTablePartition#partitionSpec` from `Map<String, Object>` to `Map<String, String>`
This change is a trivial rework which can be covered by existing tests.
- The serializers: (yes / **no** / …
> [FLINK-21894][hive] Update type of HiveTablePartition#partitionSpec from Map<String, Object> to Map<String, String>

- flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/TableSourceITCase.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/functions/scalar/SourceWatermarkFunction.java
The `SOURCE_WATERMARK` function doesn't have concrete implementation. The eval() function should throw a meaningful exception message to indicate users the function should only be used in DDL to generate a watermark preserved from source system.
- Add `SOURCE_WATERMARK` `BuiltInFunctionDefinition`.
- Add `SourceWatermarkFunction` scalar function which throws exception in `eval()` method. 
- Add tests to verify the exception in `TableSourceITCase`.  …
> [FLINK-21899][table] Introduce SOURCE_WATERMARK built-in function to preserve watermark from source

- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/DeclarativeSlotManager.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/DeclarativeSlotManagerTest.java
The `DeclarativeSlotManager` accounts for the possibility of slot allocation confirmations coming in after the slot has already been freed or fully allocated (e.g., through a SlotReport) by checking whether there is still a pending request for that slot.
However, this only works properly if the slot was allocated.
If the slot was freed in the mean time then it could've already been re-assigned to another job, which result in an IllegalStateException once the confirmation arrives because a transition from Pending -> Allocation is not allowed if the JobIDs are not matching.
It can also happen that the slot is reassigned to the same job, which can result in a premature confirmation of the allocation.
To remedy this we now additionally record the AllocationID for pending allocations (although …
> [FLINK-21874][coordination] Ignore outdated slot allocation confirmations

- flink-connectors/flink-connector-hive/pom.xml
Adds the proper plugin version for `antlr3-maven-plugin` in `flink-connector-hive`.
This avoids build stability issues and clears some warnings.
The version is the latest released plugin version (released 2014) and the one my setup (default settings) picked automatically
in the absence of the proper version. Compilation and tests succeed with that version.
> [hotfix][build] Add missing antlr3 plugin version

- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManagerGateway.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/DeclarativeSlotManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/DefaultSlotTracker.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotTracker.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutorGateway.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/DeclarativeSlotManagerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/DefaultSlotTrackerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/utils/TestingResourceManagerGateway.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TestingTaskExecutorGateway.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TestingTaskExecutorGatewayBuilder.java
Based on #15288.
With this PR the RM issues a release call for all inactive slots to the TaskExecutor if the resource requirements have been set to 0.
This reset either happens via an explicit call from the JM in case of the default scheduler, or when the JobManager disconnects because the job has terminated globally.
To detect the latter case `RM#disconnectJobManager` now also accepts a job status.
When the requirements are set to 0 the DeclarativeSlotManager asks the SlotTracker for all task executors that have a slot for the job, and tells these TaskManagers via TM#freeInactiveSlots to free all slots not currently in use.
> [FLINK-21751] Eagerly issue release calls from RM if JM disconnects for terminal job 

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPool.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPoolTest.java
LocalBufferPool#checkAvailability may return wrong availability state of LocalBufferPool which may lead to the set of inconsistent availability state when LocalBufferPool#setNumBuffers is called. This patch fixes the issue.
- Fix wrong return value of LocalBufferPool#checkAvailability. …
> [FLINK-20547][network] Fix inconsistent availability issue of LocalBufferPool

- docs/content/docs/dev/datastream/event-time/generating_watermarks.md
This pull request completes the changes in docs started by https://github.com/apache/flink/pull/15142 by adding the `output` parameter to the `onEvent` and `onPeriodicEmit` signatures
- Update Scala examples in 'Generating Watermarks' documentation page
> [FLINK-21696][docs] Add output parameter in WatermarkGenerator scala sections

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/polling/AdaptivePollingRecordPublisher.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/polling/PollingRecordPublisher.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/polling/PollingRecordPublisherTest.java
Kinesis Polling consumer does not respect the `SHARD_GETRECORDS_INTERVAL_MILLIS` configuration. This means consumer will poll Kinesis without any delay, resulting in throttle. This bug was introduced with FLINK-18512.
* Move sleep logic from `AdaptivePollingRecordPublisher` to `PollingRecordPublisher`, to respect `SHARD_GETRECORDS_INTERVAL_MILLIS`
- `PollingRecordPublisherTest::testRunEmitsRunLoopTimeNanos`
This change is already covered by existing tests, such as:
- `ShardConsumerTest`
- `PollingRecordPublisherTest`
- Kinesis e2e Test …
> [FLINK-21661][kinesis] Fix fetch interval for polling consumer

- docs/deployment/metric_reporters.md
- docs/deployment/metric_reporters.zh.md
- flink-metrics/flink-metrics-datadog/src/main/java/org/apache/flink/metrics/datadog/DCounter.java
- flink-metrics/flink-metrics-datadog/src/main/java/org/apache/flink/metrics/datadog/DHistogram.java
- flink-metrics/flink-metrics-datadog/src/main/java/org/apache/flink/metrics/datadog/DMeter.java
- flink-metrics/flink-metrics-datadog/src/main/java/org/apache/flink/metrics/datadog/DMetric.java
- flink-metrics/flink-metrics-datadog/src/main/java/org/apache/flink/metrics/datadog/DSeries.java
- flink-metrics/flink-metrics-datadog/src/main/java/org/apache/flink/metrics/datadog/DatadogHttpReporter.java
- flink-metrics/flink-metrics-datadog/src/main/java/org/apache/flink/metrics/datadog/MetricMetaData.java
- flink-metrics/flink-metrics-datadog/src/main/java/org/apache/flink/metrics/datadog/StaticDMetric.java
- flink-metrics/flink-metrics-datadog/src/test/java/org/apache/flink/metrics/datadog/DatadogHttpClientTest.java
I created this PR by copying the files from master because due to the code reformat it would have been cumbersome to cherry pick individual commits. Changes included:
commit 313e20e8e03953a5e1cec9daa467f561ccfbd599Author: Chesnay Schepler <chesnay@apache.org>Date:   Tue Dec 8 16:20:29 2020 +0100
    [FLINK-20533][datadog] Add Histogram support
commit 38e424fd5fa7c4a6e6165921689a232a10e85bddAuthor: Chesnay Schepler <chesnay@apache.org>Date:   Tue Dec 8 16:16:02 2020 +0100
    [FLINK-20533][datadog] Encapsulate metric meta data        This allows us to use the 'MetricMetaData' container for histograms later on, which will not directly extend 'DMetric'.
commit ea317c20ac4ab76c9e71fb0c1aa8a104e7173057Author: Chesnay Schepler <chesnay@apache.org>Date:   Tue Dec 8 14:55:48 2020 +0100
    …
> [FLINK-20533][datadog][release-1.12] Backport flink-metrics-datadog changes from master

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/BufferReaderWriterUtil.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/BufferReaderWriterUtilTest.java
The wrong if condition in BufferReaderWriterUtil#writeBuffers may lead to data loss when bulk writing a large number of buffers into file. This patch fixes the issue.
- Fix the wrong if condition in BufferReaderWriterUtil#writeBuffers …
> [FLINK-21951][network] Fix the wrong if condition in BufferReaderWriterUtil#writeBuffers

- flink-core/pom.xml
- flink-core/src/main/java/org/apache/flink/api/common/functions/RuntimeContext.java
Remove @PublicEvolving from RuntimeContext.getJobID
to make the API more consistent.
The method is added to japicmp ignore list.
> [FLINK-21581][core] Remove @PublicEvolving from RuntimeContext.getJobID

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcher.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/ShardConsumer.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/RecordPublisher.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutRecordPublisher.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriber.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/polling/AdaptivePollingRecordPublisher.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/polling/PollingRecordPublisher.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcherTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/ShardConsumerFanOutTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/ShardConsumerTestUtils.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutRecordPublisherTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriberTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/polling/PollingRecordPublisherTest.java
This change merged the following changes from 1.12 to 1.13:
- FLINK-21933 Gracefully handle Interrupted exceptions in Kinesis EFO source consumer [#15347](https://github.com/apache/flink/pull/15347)
- FLINK-21661 Kinesis Polling consumer does not respect the SHARD_GETRECORDS_INTERVAL_MILLIS configuration. This means consumer will poll Kinesis without any delay, resulting in throttle. This bug was introduced with FLINK-18512 [#15157](https://github.com/apache/flink/pull/15157)
See related PR descriptions:
- [#15347](https://github.com/apache/flink/pull/15347)
- [#15157](https://github.com/apache/flink/pull/15157)
See related PR descriptions:
- [#15347](https://github.com/apache/flink/pull/15347)
- [#15157](https://github.com/apache/flink/pull/15157) …
> [FLINK-21661][FLINK-21993] Merge Kinesis bug fixes from 1.12.

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/utils/FlinkRelMdUtil.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdDistinctRowCountTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/utils/FlinkRelMdUtilTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/join/JoinITCase.scala
Fix Double.NaN result produced by FlinkRelMdUtil.numDistinctVals when domainSize is in range(0,1)
- add value check for FlinkRelMdUtil.numDistinctVals, entering old formula if matched
Added ut & it case
- Dependencies (does it add or upgrade a dependency): ( no )
- The public API, i.e., is any changed class annotated with @Public(Evolving): ( no )
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: ( no )
> [FLINK-21946] [table-planner-blink] FlinkRelMdUtil.numDistinctVals produces exceptional Double.NaN result when domainSize is in range(0,1)

- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/e2e/SchedulerBenchmarkBase.java
*When we are trying to add BenchmarkExecutor for benchmarks introduced in FLINK 21731, we find that the dependency of hamcrest is introduced into the benchmark by mistake. Since there's no hamcrest dependency in flink-benchmark, this will break the execution of scheduler benchmarks. Therefore, we need to remove this dependency from `SchedulerBenchmarkBase`.*
- *Remove usage of hamcrest in `SchedulerBenchmarkBase`*
- …
> [FLINK-21975] Remove hamcrest dependency from SchedulerBenchmarkBase

- flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendTestBase.java
This change includes two commits:
`[FLINK-21929][rocksdb][tests] Ensure to dispose state backend in StateBackendTestBase#testKeyGroupedInternalPriorityQueue finally` to fix FLINK-21929
`[FLINK-21929][statebackend][tests] Refactor StateBackendTestBase to ensure created keyed state backend could be disposed finally` to stabilize all state backend tests.  
- The S3 …
> [FLINK-21929][statebackend][tests] Ensure to dispose keyed state backend to avoid core dump

- docs/data/sql_functions.yml
- flink-python/pyflink/table/expressions.py
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/Expressions.java
- flink-table/flink-table-api-scala/src/main/scala/org/apache/flink/table/api/ImplicitExpressionConversions.scala
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/logical/LocalZonedTimestampType.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/functions/sql/FlinkSqlOperatorTable.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/functions/sql/SqlCurrentTimestampFunction.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/utils/InternalConfigOptions.java
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/CodeGeneratorContext.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/ExprCodeGenerator.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/GenerateUtils.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/calls/CurrentTimePointCallGen.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/calls/FunctionGenerator.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/delegation/BatchPlanner.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/delegation/PlannerBase.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/delegation/StreamPlanner.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/expressions/NonDeterministicTests.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/expressions/TemporalTypesTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/expressions/utils/ExpressionTestBase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/WindowTableFunctionTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CalcITCase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/MatchRecognizeITCase.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/functions/SqlDateTimeUtils.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/typeutils/LegacyInstantTypeInfo.java
* This pull request correct  temporal functions evaluation timepoint and function return type.
- Correct CURRENT_TIMESTAMP/NOW() functions' return type to TIMESTAMP_LTZ 
- Correct CURRENT_TIMESTAMP/CURRENT_TIME/CURRENT_DATE/NOW/LOCALTIME/LOCALTIMESTAMP functions' evaluation timepoint according to execution mode.
- Add function tests  in `NonDeterministicTests`
- …
> [FLINK-21713][table-api/table-planner] Correct function CURRENT_TIMESTAMP/CURRENT_TIME/CURRENT_DATE/NOW/LOCALTIME/LOCALTIMESTAMP

- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/FileBufferReaderITCase.java
This PR increases the ssl handshake timeout to avoid the exception that when the netty thread is blocked, the SSL handshake timeout might happen and cause the channel get closed, which further cause "connection reset by peer" or "CloseChannelException".
- 44bc558aa2f8216b37794d32b428d32e66bf3f3b increases the timeout.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: **no** …
> [FLINK-21416] increase the ssl handshake timeout to avoid connection reset/close in FileBufferReaderITCase

- docs/data/sql_functions.yml
- flink-python/pyflink/table/tests/test_expression.py
- flink-table/flink-table-api-scala/src/main/scala/org/apache/flink/table/api/ImplicitExpressionConversions.scala
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/functions/sql/FlinkSqlOperatorTable.java
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/calls/BuiltInMethods.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/calls/FunctionGenerator.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/expressions/time.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/expressions/TemporalTypesTest.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/functions/SqlDateTimeUtils.java
* This pull request change precision argument from optional to required in TO_TIMESTAMP_LTZ(numeric, precision)
-  change precision argument from optional to required in TO_TIMESTAMP_LTZ(numeric, precision)
Add tests to cover the change.
> [FLINK-21984][table-planner] Change precision argument from optional to required in TO_TIMESTAMP_LTZ(numeric, precision)

- flink-formats/flink-csv/pom.xml
- flink-formats/flink-json/pom.xml
* This pull request fix that flink-csv and flink-json does not package the format-common moudule
-  update the pom.xml for flink-csv and flink-json
- validate in local with `jar -tvf ` command, cover it in current e2e tests
> [hotfix][format] package format-common to flink-csv and flink-json

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/expressions/TemporalTypesTest.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/data/DecimalDataUtils.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/data/DecimalDataTest.java
Currently we has supported the cast conversion between Numeric type and TIMESTAMP_LTZ type, we suppose the numeric value e.g `Long type 1000L` as epoch seconds and then cast  to TIMESTAMP_LTZ, but the java.lang.Long is a conversion class of `LocalZonedTimestampType`  and treats as milliseconds.
To avoid the inconsistency, we disable it and encourage user to use `TO_TIMESTAMP_LTZ(numeric, precision)`.
-  Disable the cast conversion between Numeric type and TIMESTAMP_LTZ
- Add unit test to cover the cast conversion and function
-  …
> [FLINK-21978][table-planner] Disable cast conversion between Numeric type and TIMESTAMP_LTZ type

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParser.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserASTBuilder.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserAuthorizationParseUtils.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserContext.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserUtils.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/desc/CreateTableASDesc.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/desc/HiveParserCreateViewDesc.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/FromClauseASTParser.g
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveASTHintParser.g
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveASTLexer.g
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveASTParseDriver.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveASTParseUtils.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveASTParser.g
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserASTNode.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserASTNodeOrigin.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserBaseSemanticAnalyzer.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserDDLSemanticAnalyzer.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserErrorMsg.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserPTFInvocationSpec.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserStorageFormat.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/IdentifiersASTParser.g
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/SelectClauseASTParser.g
Add our own ASTNode. This is needed to support hive dialect for different hive versions.
- Add `HiveParserASTNode` and stop using hive's `ASTNode`.
Existing tests
> [FLINK-21888][hive] Maintain our own ASTNode class

- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/SemanticXidGenerator.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcXaSinkTestBase.java
- flink-core/src/main/java/org/apache/flink/api/common/functions/RuntimeContext.java
- flink-core/src/main/java/org/apache/flink/api/common/functions/util/RuntimeUDFContext.java
- flink-core/src/main/java/org/apache/flink/api/common/operators/CollectionExecutor.java
- flink-libraries/flink-cep/src/main/java/org/apache/flink/cep/operator/CepRuntimeContext.java
- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/runtime/SavepointRuntimeContext.java
- flink-runtime/src/main/java/org/apache/flink/runtime/iterative/task/AbstractIterativeTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/operators/util/DistributedRuntimeUDFContext.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/async/RichAsyncFunction.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/StreamingRuntimeContext.java
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/expressions/utils/ExpressionTestBase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/expressions/utils/ExpressionTestBase.scala
Make RuntimeContext.jobID non-optional.
> [FLINK-21626][core] Make RuntimeContext.jobID non-optional

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSourceBuilder.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSourceOptions.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/KafkaSourceEnumerator.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/SpecifiedOffsetsInitializer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReader.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceLegacyITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/enumerator/initializer/OffsetsInitializerTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReaderTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaConsumerTestBase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestEnvironment.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestEnvironmentImpl.java
- flink-core/src/main/java/org/apache/flink/api/connector/source/SplitEnumeratorContext.java
- flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/statemachine/StateMachineExample.java
- flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContext.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContextTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorTestBase.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/StreamMultipleInputProcessorFactory.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceOperatorStreamTask.java
This PR is co-authored with @becketqin.
This PR fixed a few bugs related to `KafkaSource`. See "Brief change log" for the list of bug fixes made in this PR.
Bug fixes:
- `KafkaSourceReader` should not commit offsets for partitions whose offsets have not been initialized.
- `SourceCoordinatorContext` should not log and fail job again if it receives InterruptedException after it is closed.
- `PartitionOffsetsRetrieverImpl.committedOffsets()` should handle the case without committed offsets.
- `SourceOperatorStreamTask` should check the committed offset first before using OffsetResetStrategy.
Usability improvements:
- Reduce the offset commit logging verbosity from INFO to DEBUG.
- `SourceOperatorStreamTask` should update the numRecordsOutCount metric
- `KafkaSourceEnumerator` should close …
> [FLINK-20114][connector/kafka,common] Fix a few KafkaSource-related bugs

- docs/content.zh/docs/dev/datastream/fault-tolerance/state.md
- docs/content/docs/dev/datastream/fault-tolerance/state.md
* Added missing state descriptor (AggregatingStateDescriptor) 
* Updated documentation for missing state descriptor (AggregatingStateDescriptor)
This change is already covered by existing tests since this only update to documentation …
> [hotfix][docs] Added missing state descriptor (AggregatingStateDescriptor) to docs

- flink-runtime-web/web-dashboard/src/app/share/common/dagre/node.component.ts
This seems to have been accidentally left over during the development. It unnecessarily pollutes the browser logs - values are being constantly printed to the console when the DAG is opened.
> [hotfix][ui] Remove unrelated UI backpressure console logs

- docs/content/docs/ops/state/savepoints.md
This is a simple fix for the documentation.
> [hotfix][doc] Do not refer to deprecated cancel-with-savepoint in the docs

- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/ExecNodeGraphJsonPlanGenerator.java
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/metadata/MetadataHandlerConsistencyTest.scala
*Reduce the ExecNode scan scope to improve performance when converting json plan to ExecNodeGraph*
- *Change the scan package from `org.apache.flink` to `org.apache.flink.table.planner.plan.nodes.exec` in ExecNodeGraphJsonPlanGenerator*
- *Do some code clean up*
- …
> [FLINK-22022][table-planner-blink] Reduce the ExecNode scan scope to improve performance when converting json plan to ExecNodeGraph

- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTaskTest.java
Backport of #15038 to 1.11
```
SourceStreamTaskTest.testStopWithSavepointShouldNotInterruptTheSource
is unstable because the latch  can be reset after triggering (while it`s
supposed to be reset before the test starts).
```
> [BP-1.11][FLINK-21515][tests] Fix testStopWithSavepointShouldNotInterruptTheSource

- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/output/SnapshotUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointOptions.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/PendingCheckpoint.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/CheckpointBarrier.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/serialization/EventSerializer.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/writer/SubtaskStateMapper.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointOptionsTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/PendingCheckpointTest.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamEdge.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraphGenerator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGenerator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/RecordWriterOutput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/partitioner/BroadcastPartitioner.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/partitioner/CustomPartitionerWrapper.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/partitioner/ForwardPartitioner.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/partitioner/GlobalPartitioner.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/partitioner/KeyGroupStreamPartitioner.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/partitioner/RebalancePartitioner.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/partitioner/RescalePartitioner.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/partitioner/ShufflePartitioner.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/partitioner/StreamPartitioner.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/OperatorChain.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorImpl.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/StreamGraphGeneratorTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorTest.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/partitioner/BinaryHashPartitioner.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointRescaleITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java
With #13845, unaligned checkpoints are rescalable. However, for pointwise connection we are losing certain implicit guarantees as outlined in FLINK-21936. Unless, we provide forward the keyed context to downstream operations, there is no easy way to rescale pointwise connections. Thus, this PR removes pointwise connections from unaligned checkpoint and thus allows the rescaling for arbitrary jobs at the cost of checkpoint barriers not being able to overtake pointwise buffers.
- Adding forced aligned checkpoints. These unaligned checkpoints or aligned checkpoints with timeout are turned into pure aligned checkpoints on pointwise connections. They are restored downstream.
- Adding `StreamEdge#supportsUnalignedCheckpoint` to all incoming edges iff a `StreamNode` has at least one pointwise …
> [FLINK-21945][streaming] Omit pointwise connections from checkpointing in unaligned checkpoints.

- flink-end-to-end-tests/test-scripts/test_table_shaded_dependencies.sh
- flink-table/flink-table-planner-blink/pom.xml
- flink-table/flink-table-planner-blink/src/main/resources/META-INF/NOTICE
- flink-table/flink-table-planner-blink/src/main/resources/META-INF/licenses/LICENSE.reflections
this is a hotfix adding org.reflections:reflections to include list of maven shade plugin just like how we treat com.ibm.icu:icu4j
Add org.reflections to include list of maven shade plugin
- *Manually verified the change by generate a json plan by TableEnvironmentInternal#getJsonPlan and then explain the plan json by TableEnvironmentInternal#explainJsonPlan.*
- The S3 …
> [FLINK-22020][table-planner-blink] Add org.reflections to include list of maven shade plugin

- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/deploying/DeployingTasksBenchmarkBase.java
*We find that the BlockingQueue that used to preserve `TaskDeploymentDescriptor`s which are never used later. Since a `TaskDeploymentDescriptor` would cost massive heap memory, it may introduce unnecessary garbage collection and make the result of benchmarks related to deployment unstable. Therefore, we think it's better to remove the redundant blocking queue in `DeployingTasksBenchmarkBase`.*
*For more details please check FLINK-22037.*
- *Remove the redundant `BlockingQueue` from `DeployingTasksBenchmarkBase`*
- The serializers: (yes / **no** / don't …
> [FLINK-22037][benchmark] Remove the redundant blocking queue from DeployingTasksBenchmarkBase

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/utils/RexNodeExtractor.scala
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/PushFilterIntoLegacyTableSourceScanRuleTest.xml
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/PushFilterIntoTableSourceScanRuleTest.xml
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/rules/logical/PushFilterIntoLegacyTableSourceScanRuleTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CalcITCase.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/data/conversion/DayTimeIntervalDurationConverter.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/data/conversion/YearMonthIntervalPeriodConverter.java
`PushFilterIntoLegacyTableSourceScanRule` will throw exception when faced with `INTERVAL` types, no matter it can be pushed down or not.
- Fix exception when PushFilterIntoLegacyTableSourceScanRule is faced with INTERVAL types
This change can be verified by running the added tests. …
> [FLINK-22021][table-planner-blink] Fix exception when PushFilterIntoLegacyTableSourceScanRule is faced with INTERVAL types

- flink-quickstart/flink-quickstart-java/src/main/resources/archetype-resources/pom.xml
- flink-quickstart/flink-quickstart-scala/src/main/resources/archetype-resources/pom.xml
The scala quickstarts now use the same jvm version as the `-target` as the main project; this ensures that the experience for scala users is identical to what we see when we write tests or use the APIs ourselves.
> [FLINK-21252][quickstarts][scala] Forward target java version

- docs/content.zh/docs/flinkDev/ide_setup.md
- docs/content/docs/flinkDev/ide_setup.md
The main objective here is to reference the patched google-java-format plugin which needs to be used and is attached in FLINK-21106. It also updates the IDE setup guide to a recent version of IntelliJ and makes some minor grammatical and typographical changes.
- Updates IDE setup guide …
> [Hotfix][docs] Update IDE setup

- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNSessionFIFOITCase.java
There is a problem when killing the application before the job finishes. The TaskManager might get killed first. The TaskManager then runs into issues before being actually killed as well which might. This resulted in the concrete case in connection refused error when connecting to the JobManager's blob server.
* The test is failing early now without cleanup
* The timeout was increased as the job itself looked like it was finishing without problems
No test was added as it's a test issue by itself. …
> [FLINK-21148][tests] Fixes instability in YARN's detached-mode ITCases

- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/tasks/AbstractInvokable.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
```
Don't release StreamTask network resources from TaskCanceller
Concurrent release could lead to race conditions.
```
The race condition is already covered by `UnalignedCheckpointITCase`.
> [FLINK-22050][runtime] Don't release StreamTask network resources from TaskCanceller

- azure-pipelines.yml
- tools/azure-pipelines/build-apache-repo.yml
This is the change in the docker image: https://github.com/rmetzger/flink-ci/commit/7ac4e285d89c306092d685be5fe1a0ca7d059e07
Essentially, we are using an official release of wagon-http again.
> [FLINK-16947][Azure] Use latest docker image for CI

- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorTest.java
1. Don't finish output channel state write in `testForceAlignedCheckpointResultingInPriorityEvents` as `FORCE_ALIGNED` checkpoint shouldn't have any channel state persisted.
1. Close SubtaskCheckpointCoordinator in tests to reveal any async failures occurring when writing channel state.
- If …
> [FLINK-22105][tests] Fix checkpoint id in testForceAlignedCheckpointResultingInPriorityEvents

- flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl
- flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/utils/ParserResource.java
- flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java
*(or)*
*(or)*
*(example:)*
- *Extended …
> [FLINK-17957] [table-api][parser] Forbidden syntax "CREATE SYSTEM FUNCTION" for sql parser

- docs/content.zh/docs/deployment/elastic_scaling.md
- docs/content/docs/deployment/elastic_scaling.md
With FLINK-21844, Reactive Mode now has the same behavior
when the same max parallelism as the "default" mode.
This also includes minor typos/ fixes.
Signed-off-by: austin ce <austin.cawley@gmail.com>
With FLINK-21844, Reactive Mode now has the same behavior when the same max parallelism as the "default" mode.
This also includes minor typos/ fixes.
* Update Elastic Scaling page with description of new behavior …
> [hotfix][docs] Fix max parallelism behavior for Reactive Mode

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParser.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserDDLSemanticAnalyzer.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectITCase.java
Currently hive dialect can silently ignore unsupported DDL features like hive's storage handler table. This PR is to make sure we throw a meaningful exception in such case.
- Make sure CREATE MATERIALIZED VIEW is handled by `HiveParserDDLSemanticAnalyzer`.
- In `HiveParserDDLSemanticAnalyzer`, throw exceptions for unsupported features.
- Make `HiveParserDDLSemanticAnalyzer` throw `ValidationException` instead of `SemanticException`, in order to follow flink's convention. Eventually we should make this change through out the hive parser.
- Simplify `HiveParserDDLSemanticAnalyzer` and remove some unnecessary code.
- Add test cases
Existing and added tests …
> [FLINK-22102][hive] Throw meaningful exceptions for unsupported DDLs

- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerComputeReactiveModeVertexParallelismTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
Ensure that the same max parallelism value is used as the default in the Adaptive Scheduler between submissions, even as the job scales in and out. Previously, the default was used as if it were specified by the user in the JobGraph, making it impossible to rescale from a configured maxP to the default.
The solution of passing a defaulting function is not the prettiest, but is easy enough to follow and can be removed once  the overall flow of parallelism-from-state is improved.
Closes FLINK-22084
Signed-off-by: austin ce <austin.cawley@gmail.com>
- Allow passing a function, used to compute the default max parallelism value for a vertex,
to the `SchedulerBase#computeVertexParallelismStore` method 
- Ran the `RescalingITCase` with …
> [FLINK-22084][runtime] Use a consistent default max parallelism in the Adaptive Scheduler

- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/join/temporal/TemporalRowTimeJoinOperator.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/operators/join/temporal/TemporalRowTimeJoinOperatorTest.java
This is a cherry pick back to release-1.12 branch.
> [BP-1.12][FLINK-21833][table-runtime-blink] Fix state of TemporalRowTimeJoinOperator increase unlimitedly even state ttl is enabled

- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/JdbcXaSinkFunction.java
At the point of snapshotting, there is not possible any prepared xas with trans id > the current checkpoint id
hence 
`rollbackPreparedFromCheckpoint` will always check and return;
remove this method in this hotfix.
> [hotfix] Remove unnecessary rollbackPreparedFromCheckpoint from JdbcXaSinkFunction.snapshot

- flink-python/pyflink/datastream/tests/test_data_stream.py
- flink-python/src/main/java/org/apache/flink/streaming/api/operators/python/PythonTimestampsAndWatermarksOperator.java
*This pull cherry-picks the patches reviewed in #15401.*
> [FLINK-21969][python] Invoke finish bundle method before emitting the max timestamp watermark in PythonTimestampsAndWatermarksOperator

- flink-core/src/main/java/org/apache/flink/api/common/state/StateTtlConfig.java
- flink-core/src/test/java/org/apache/flink/api/common/state/StateTtlConfigTest.java
[ahead pr](https://github.com/apache/flink/pull/10507)
At the moment, we allow zero value for the TTL incremental cleanup size.
Although technically zero value will not break the cleanup but practically there will be no cleanup.
We change cleanupSize to be strictly greater than zero to avoid confusion.
> [FLINK-15146][core][ttl] Fix check that incremental cleanup size must be greater than zero

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/expressions/MapTypeTest.scala
This pull request fixed a bug that there is duplicate code in generated code for map get, an it may lead to some exceptions such as  'Redefinition of local variable'.
remove the duplicate code in generated code for map get.
- org.apache.flink.table.planner.runtime.stream.sql.CalcITCase#testMapGet …
> [FLINK-22120] Remove duplicate code in generated code for map get

- docs/content/docs/ops/state/state_backends.md
Remove description of sync checkpoint mode of HashMapStateBackend as the constructor has been removed.
> [FLINK-22187][docs] Remove description of sync checkpoint mode of HashMapStateBackend

- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/filesystem/FileSystemOutputFormat.java
Fix INSERT INTO EMPTY VALUES, THROW FileNotFoundException
FileSystemOutputFormat use local File.delete is wrong. It should use FileSystemFactory to delete file.
> [FLINK-20230][table] FileSystemOutputFormat should delete file using FileSystemFactory

- flink-table/flink-table-planner-blink/src/main/java/org/apache/calcite/rex/RexSimplify.java
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/CalcTest.xml
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/CalcTest.xml
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/CalcTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/CalcTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CalcITCase.scala
In Calcite 1.26, expressions like `a = 1 OR a IS NULL` will be simplified to `SEARCH(a, [1, NULL])`. This is incorrect because searching for NULL is always false (this is a bug, fixed in CALCITE-4446).
This PR exclude `IS NULL` from `SEARCH` operators to solve this issue.
- Exclude IS NULL from SEARCH operators …
> [FLINK-22015][table-planner-blink] Exclude IS NULL from SEARCH operators

- flink-clients/src/main/java/org/apache/flink/client/deployment/executors/AbstractSessionClusterExecutor.java
If the future returned by `clusterClient.submitJob()` fails, then this failure is executed by a netty thread. This then causes `.whenComplete((ignored1, ignored2) -> clusterClient.close())` to also be run in the netty thread, which causes the shutdown to fail because netty can't be shutdown since a thread is still active.
> [FLINK-22184][client] Shutdown client outside of netty thread

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/NotifyCheckpointAbortedITCase.java
Unchanged backport of #15554.
`NotifyCheckpointAbortedITCase` implicitly assumes that abortion of chk-1 happens before sync phase of chk-2. If abortion is late, the mail that handles the abortion is never executed since the waitLatch blocks the mailbox thread. The latch in turn is never triggered as chk-1 is not aborted.
The fix is to move the wait latch on chk-2 into the source - the only operator that isn't checked for abortion. Thus, the deadlock cannot happen.
Test fix.
- The runtime per-record code paths (performance sensitive): (yes / **no /** don't know) …
> [FLINK-20816][tests] Fix race condition in NotifyCheckpointAbortedITCase. [1.12]

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/calcite/FlinkLogicalRelFactories.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/nodes/logical/FlinkLogicalValues.scala
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/ValuesTest.xml
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/ValuesTest.scala
`SELECT * FROM (VALUES 1, 2, 3) AS T (a) WHERE a = 1 and a = 2 ORDER BY a` will fail.
`FlinkLogicalValues` should deal with trait of empty values.
`ValuesTest.testEmptyValuesWithSort`
> [FLINK-22166][table] Empty values with sort willl fail

- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/ParquetColumnarRowInputFormat.java
- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/ParquetVectorizedInputFormat.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/ParquetColumnarRowInputFormatTest.java
In a VectorizedColumnBatch, the dictionary will be lazied deserialized. 
If there are multiple batches at the same time, there may be thread safety problems, because the deserialization of the dictionary depends on some internal structures.
We need set numBatchesToCirculate to 1 for ParquetColumnarRowInputFormat.
Set numBatchesToCirculate to 1 in `ParquetColumnarRowInputFormat`.
`ParquetColumnarRowInputFormatTest` …
> [FLINK-22202][parquet] Thread safety in ParquetColumnarRowInputFormat

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/CodeGenUtils.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/nodes/logical/FlinkLogicalAggregate.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CalcITCase.scala
Should throw a readable exception when group by Map type.
Throws "Collection type is not supported as a GROUP BY field." in `FlinkLogicalAggregate`.
`CalcITCase.testMapTypeGroupBy`
> [FLINK-17803][table] Should throw a readable exception when group by Map type

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java
`UnalignedCheckpointRescaleITCase` iterates over the checkpoints to return a completed one.
Currently, during the iteration the cluster isn't shut down so it can concurrently remove any files read.
With this change, cluster is shut down first and then checkpoint is collected.
- If yes, how …
> [FLINK-22197][tests] Shutdown cluster before collecting checkpoints

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/calcite/PreValidateReWriter.scala
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/common/PartialInsertTest.xml
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/common/PartialInsertTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/table/TableSinkITCase.scala
```
util.tableEnv.executeSql(
s"""
|create table partitioned_sink (
|  `a` INT,
|  `b` AS `a` + 1,
|  `c` STRING,
|  `d` STRING,
|  `e` DOUBLE,
|  `f` BIGINT,
|  `g` INT
|) PARTITIONED BY (`c`, `d`) with (
|  'connector' = 'values',
|  'sink-insert-only' = 'false'
|)
|""".stripMargin)
INSERT INTO sink (b,e,a,g,f,c,d) SELECT b,e,a,456,123,c,d FROM MyTable GROUP BY a,b,c,d,e
```
Not work.
Fix bug in `PreValidateReWriter`
`PartialInsertTest` …
> [FLINK-22167][table-planner] Partial insert not works when complex fields reorder

- docs/content/docs/connectors/datastream/jdbc.md
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/JdbcXaSinkFunction.java
MySQL supports XA transaction as global trans, and allows one xa trans open per connection. For JDBC exactly once sink, it needs at least two xa trans per connection (snapshot -> prepare trans; and then begin transaction)
Document the limitation for MySQL support.
For future improve, please refer to FLINK-22239
> [FLINK-21743] Document limitation of JdbcXaSinkFunction for MySQL support

- flink-connectors/flink-connector-kafka/pom.xml
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaChangelogTableITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableITCaseBase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableTestBase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/UpsertKafkaTableITCase.java
* This pull request use testcontainers for UpsertKafkaTableITCase to fix the hang tests in UpsertKafkaTableITCase reported in FLINK-21516 and FLINK-21431
* The reason of the hang cases is the test clients returned latest offset rather then earliest offset for test topic  after retry about 30 times(about 20 seconds),
we can reproduce this one by debugging or running N times in  IDE. The error line is 
```
if (newPartitionState.getOffset()
== KafkaTopicPartitionStateSentinel.EARLIEST_OFFSET) {
consumerTmp.seekToBeginning(
Collections.singletonList(newPartitionState.getKafkaPartitionHandle()));
newPartitionState.setOffset(
consumerTmp.position(newPartitionState.getKafkaPartitionHandle()) - 1);
// the expected offset is -1, but the returned offset is 10 which is wrong
```
Due to the root …
> [FLINK-21431][upsert-kafka] Use testcontainers for KafkaTable ITCase

- docs/content/docs/deployment/config.md
- docs/layouts/shortcodes/generated/all_jobmanager_section.html
- docs/layouts/shortcodes/generated/job_manager_configuration.html
- docs/layouts/shortcodes/generated/rest_v1_dispatcher.html
- docs/layouts/shortcodes/generated/web_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/JobManagerOptions.java
- flink-core/src/main/java/org/apache/flink/configuration/WebOptions.java
- flink-runtime-web/web-dashboard/src/app/pages/job/exceptions/job-exceptions.component.html
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/JobExceptionsHeaders.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/DefaultSchedulerTest.java
Minor changes to improve usability for [FLINK-6042](https://issues.apache.org/jira/browse/FLINK-6042) changes.
* `jobmanager.exception-history-size` is moved to `web.exception-history-size`
* the documentation was slightly extended
* some minor mistakes in the docs are fixed
Manual visual test of web UI …
> [FLINK-22144][runtime][runtime-web] Adds more documentation and moves option

- flink-runtime/src/main/java/org/apache/flink/runtime/io/AvailabilityProvider.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/UnionInputGate.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/UnionInputGateTest.java
The available notification of UnionInputGate is reset when the last gate with data is read independent of how many buffers are still available in the gate.
- Fix availability notification in UnionInputGate.
- Further, data notification is only triggered on the first non-priority event in Single/UnionInputGate.
Added UnionInputGate#testAvailability.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / …
> [FLINK-21992][network] Fix availability notification in UnionInputGate.

- flink-runtime/src/main/java/org/apache/flink/runtime/io/AvailabilityProvider.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/UnionInputGate.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/UnionInputGateTest.java
Unchanged backport of #15586.
The available notification of UnionInputGate is reset when the last gate with data is read independent of how many buffers are still available in the gate.
- Fix availability notification in UnionInputGate.
- Further, data notification is only triggered on the first non-priority event in Single/UnionInputGate.
Added `UnionInputGate#testAvailability`. …
> [FLINK-21992][network] Fix availability notification in UnionInputGate. [1.12]

- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorTest.java
Fixes an issue where outdated slot offer responses could result in slots being freed while they are still being offered to the JM in a new offer.
Each slot offer is now internally identified with an ID, and the response is only processed if this is matches the current slot offer counter.
> [FLINK-21859][coordination] Ignore outdated slot offer responses

- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/DeclarativeSlotManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/FineGrainedSlotManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotManagerImpl.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/ResourceManagerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/DeclarativeSlotManagerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/TestingSlotManager.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/TestingSlotManagerBuilder.java
Fixes an issue where the RM was reclaiming slots during the execution of a batch job when the job was switching to the next stage and temporarily reduced the requirements to 0.
Slots are now only reclaimed if the job is removed from the RM.
> [FLINK-22180][coordination] Only reclaim slots if job is removed 

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveSourceFileEnumerator.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/read/HiveTableInputFormat.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/TableEnvHiveConnectorITCase.java
Fix the issue that we can't read hive table/partition whose location contains comma character
- Escape the location path before creating input splits for hive table
- Add test case
Added test case
> [FLINK-20761][hive] Escape the location path when creating input splits

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/RescalingITCase.java
Tests occasionally fail on Azure, because it might happen that the job finishes before we take a savepoint. I added a latch that lets us wait until we are sure we took a savepoint correctly.
Tests pass on Azure
- If …
> [FLINK-21941] Make sure jobs do not finish before taking savepoint in RescalingITCase

- docs/content/docs/connectors/datastream/jdbc.md
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/JdbcSink.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcExactlyOnceSinkE2eTest.java
A trivial change to remove unnecessary argument in `JdbcSink`.
> [FLINK-22288][connectors / jdbc] Remove unnecessary argument in JdbcSink

- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/test/util/AbstractTestBase.java
- flink-tests/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterStopWithSavepointITCase.java
Harden the JobMasterStopWithSavepointITCase
- Increased timeouts (I run tests 10k times locally and they always pass)
- Added "Failling" state to an assertion, as we might not reach the "FAILED" state before that assertion
Tests pass
> [Flink-22248][Flink-22249] Harden JobMasterStopWithSavepointITCase

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/utils/RexNodeExtractor.scala
- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/plan/rules/logical/PushFilterIntoTableSourceScanRuleTestBase.java
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/PushFilterInCalcIntoTableSourceRuleTest.xml
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/PushFilterIntoLegacyTableSourceScanRuleTest.xml
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/PushFilterIntoTableSourceScanRuleTest.xml
`RexLiteral` could not contain null values in the past according to @dawidwys , however this is currently not true and will cause filter push down rules to throw exceptions when faced with NULL literals.
- RexNodeExtractor#visitLiteral now deal with NULL literals correctly. …
> [FLINK-22016][table-planner-blink] RexNodeExtractor#visitLiteral now deal with NULL literals correctly

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java
Reduce the log if not all tasks are RUNNING when checkpointing and change the log level to INFO to not interfere with the normal logs
- abbe63a31c4ba7f2709393c6add855e98065e32e changes the log
This change is verified via manual tests.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: **no**
- Does this pull request introduce a new feature? **no**
- If yes, how is the feature documented? **not applicable**
> [FLINK-22117] Reduce the logs if not all tasks are RUNNING when checkpointing

- docs/content.zh/docs/dev/datastream/operators/windows.md
- docs/content/docs/dev/datastream/operators/windows.md
* Remove reference to fold function 
* Removed deprecated fold function reference 
This change is documentation update and already covered by existing tests. …
> [hotfix][docs] Removed reference to fold in window function

- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/networking/NetworkFailureHandler.java
This PR updated NetworkFailureHandler to prevent closeOnFlush() from being called recursively. The test might hang indefinitely without this change.
This PR updated NetworkFailureHandler to prevent closeOnFlush() from being called recursively.
Verified that INFO level log would be printed by running `mvn test -Dtest=KafkaSourceLegacyITCase`. …
> [FLINK-22085][tests] Update NetworkFailureHandler to prevent closeOnFlush() from being called recursively

- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/factories/TestValuesRuntimeFunctions.java
…d for FromElementSourceFunctionWithWatermark
*Clear the watermark output per test. To reproduce this bug, please run `SourceWatermarkITCase` twice.*
> [FLINK-22338][table-planner] Clear watermark output when test finished for FromElementSourceFunctionWithWatermark

- docs/content.zh/docs/ops/state/state_backends.md
- docs/content/docs/ops/state/state_backends.md
This PR add doc description to tell that RocksDB would ignore java's equals/hashCode during comparing objects.
This PR add doc description to tell that RocksDB would ignore java's equals/hashCode during comparing objects.
> [FLINK-21073][docs] Mention that RocksDB would ignore java's equals/hashCode during comparing objects

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/HiveCatalog.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/catalog/hive/HiveCatalogTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/catalog/hive/HiveTestUtils.java
- flink-connectors/flink-connector-hive/src/test/resources/hive-site.xml
`HiveConf` automatically detects hive-site from classpath and stores the URL into static variable `hiveSiteURL`. This can cause problems if a user creates multiple HiveCatalog instances.
- Prevent HiveConf from storing `hiveSiteURL`. And look for hive-site from classpath when hive-conf-dir is not specified by ourselves.
- Add a test case
Existing and added test cases …
> [FLINK-22092][hive] Ignore static conf file URLs in HiveConf

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/utils/RexNodeExtractor.scala
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/PushFilterIntoLegacyTableSourceScanRuleTest.xml
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/PushFilterIntoTableSourceScanRuleTest.xml
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/rules/logical/PushFilterIntoLegacyTableSourceScanRuleTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CalcITCase.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/data/conversion/DayTimeIntervalDurationConverter.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/data/conversion/YearMonthIntervalPeriodConverter.java
merge  [FLINK-22021](https://github.com/apache/flink/pull/15424) to  Flink 1.12
PushFilterIntoLegacyTableSourceScanRule will throw exception when faced with INTERVAL types, no matter it can be pushed down or not.
Fix exception when PushFilterIntoLegacyTableSourceScanRule is faced with INTERVAL types
This change can be verified by running the added tests.
The public API, i.e., is any changed class annotated with @Public(Evolving): no
The runtime per-record code paths (performance sensitive): no
Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no
The S3 file system connector: no
Does this pull request introduce a …
> [FLINK-22021][table-planner-blink] Fix exception when PushFilterIntoLegacyTableSourceScanRule is faced with INTERVAL types  

- docs/content.zh/docs/flinkDev/ide_setup.md
- docs/content/docs/flinkDev/ide_setup.md
google-java-format plugin 1.7.0.6 was released
(see issue [#560](https://github.com/google/google-java-format/issues/560)). Hence, we do not
have to rely on the patched version of [FLINK-21106](https://issues.apache.org/jira/browse/FLINK-21106) anymore.
We needed the workaround due to a failure described in `FLINK-21106`.
Updated the logs accordingly.
* I tested the new plugin version on 
```
IntelliJ IDEA 2020.2.4 (Community Edition)
Build #IC-202.8194.7, built on November 24, 2020
Runtime version: 11.0.9+11-b944.49 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 8108M
Cores: 12
Non-Bundled Plugins: IdeaVIM, CheckStyle-IDEA, Lombook Plugin, com.dubreuia, google-java-format, org.intellij.scala
```
* I rebuild the logs verifying …
> [FLINK-21106][docs] Updates Flink docs to refer to the plugin's page

- flink-connectors/flink-connector-jdbc/pom.xml
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/JdbcExactlyOnceOptions.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/JdbcSink.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/JdbcBatchingOutputFormat.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/JdbcXaSinkFunction.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/SemanticXidGenerator.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/XaFacade.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/XaFacadeImpl.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/XaFacadePoolingImpl.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/XaGroupOps.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/XaGroupOpsImpl.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/XidGenerator.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/DbMetadata.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/JdbcTestBase.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/JdbcTestFixture.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcExactlyOnceSinkE2eTest.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcXaFacadeTestHelper.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcXaSinkMigrationTest.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcXaSinkTestBase.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/SemanticXidGeneratorTest.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/h2/H2XaResourceWrapper.java
Implement workaround for limitation of some XA-compliant databases
of a single XA-transaction per connection by pooling connections.
Docs need to be updated but can be done separately in FLINK-22289.
Update existing `JdbcExactlyOnceSinkE2eTest` to work against (containerized) postgresql.
> [FLINK-22239][jdbc] Support exactly-once (sink) for PgSql and MySql 

- flink-end-to-end-tests/run-nightly-tests.sh
- flink-end-to-end-tests/test-scripts/test_local_recovery_and_scheduling.sh
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointMetaData.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/checkpointing/CheckpointBarrierHandler.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceOperatorStreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorImpl.java
1. Fix `test_local_recovery_and_scheduling.sh` by increasing test timeout and add emit interval at sources
1. Ease further debug by logging the time checkpoint mail spent in the mailbox
> [FLINK-21329][tests] Increase timeout and delay in local test_local_recovery_and_scheduling.sh

- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/logical/utils/LogicalTypeCasts.java
Rename LogicalTypeCasts class variables in the castTo method. 
castTo parameter has a mistake name. It should be 'targetType'.
rename 'sourceType' to 'targetType'.
> [FLINK-22372][table] Rename LogicalTypeCasts class variables in the castTo method.

- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/EmbeddedRocksDBStateBackend.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBStateBackend.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBInitTest.java
Removes a new logging configuration from the `EmbeddedRocksDBStateBackend` that can cause a ClassNotFoundException if the TM uses a different logging configuration from the client.  …
> [FLINK-22369][rocksdb] RocksDB state backend might occur ClassNotFoundException when deserializing on TM side

- docs/layouts/shortcodes/generated/table_config_configuration.html
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/TableConfig.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/config/TableConfigOptions.java
- flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/api/TableConfigTest.java
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/util/python/PythonTableUtilsTest.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/window/assigners/TumblingWindowAssigner.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/util/TimeWindowUtil.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/operators/aggregate/window/SlicingWindowAggOperatorTest.java
* This pull request fix the bug that some time zone id like `UTC+8`, `UTC-10:00`  that `java.time.TimeZone` doesn't support and will treat as `UTC`, the may lead wrong value silently.
-  Throw proper Exception for this case.
- Add unit test to cover the change. …
> [FLINK-22349][table-api] Throw Exception for unsupported Zone ID instead of using wrong value.

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/RemoteInputChannel.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/RemoteInputChannelTest.java
Exception can be thrown for example if task is being cancelled. This was leading to
same buffer being recycled twice. Most of the times that was just leading to an
IllegalReferenceCount being thrown, which was ignored, as this task was being cancelled.
However on rare occasions this buffer could have been picked up by another task
after being recycled for the first time, recycled second time and being picked up
by another (third task). In that case we had two users of the same buffer, which
could lead to all sort of data corruptions. …
> [FLINK-20654] Fix double recycling of Buffers in case of an exception on persisting

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/calcite/PreValidateReWriter.scala
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/common/PartialInsertTest.xml
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/common/PartialInsertTest.scala
Fix `INSERT INTO partitioned_sink (e,a,g,f,c,d) SELECT e,a,456,123,c,d FROM MyTable GROUP BY a,b,c,d,e UNION ALL SELECT e,a,789,456,c,d FROM MyTable GROUP BY a,b,c,d,e`.
In the `PreValidateReWriter`, there is a match case, only `select` and `values` are in this match.
But in `SqlKind.QUERY`, there are lots of query types.
We can add recursion method to `PreValidateReWriter`, solve set queries and order by.
`PartialInsertTest` …
> [FLINK-22168][table] Partition insert can not work with union all

- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/InputOutputFormatVertex.java
The code comments in InputOutputFormatVertex are incorrect. It should be output.
change "input" to "output".
> [FLINK-22398][runtime]fix incorrect comments in InputOutputFormatVertex

- docs/content.zh/docs/dev/datastream/fault-tolerance/state.md
i found Chinese typos in  https://ci.apache.org/projects/flink/flink-docs-master/zh/docs/dev/datastream/fault-tolerance/state/  text content  "和 keyed state 类系"  Should be replaced with  "和 keyed state 类似"
change "和 keyed state 类系"  to "和 keyed state 类似"
- If …
> [FLINK-22384][docs]Chinese typos in "fault-tolerance/state/"  page

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointStatsSnapshot.java
- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/JobMasterServiceLeadershipRunnerFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ArchivedExecutionGraph.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/factories/DefaultJobMasterServiceProcessFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/JobGraphJobInformation.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ArchivedExecutionGraphTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/DefaultJobMasterServiceProcessTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterServiceLeadershipRunnerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/factories/TestingJobMasterServiceProcessFactory.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/factories/TestingJobMasterServiceProcessFactoryOld.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/CreatedTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/CreatingExecutionGraphTest.java
Ensures that various checkpointing-related settings are written into the `ArchivedExecutionGraph` when the job is in an `INITIALIZING` state, if checkpointing is enabled.
Previously we always nulled these fields, due to which the checkpoint handlers throw exceptions claiming checkpointing to be disabled.
> [FLINK-21659][coordination] Properly expose checkpoint settings for initializing jobs

- flink-connectors/flink-connector-cassandra/src/test/java/org/apache/flink/streaming/connectors/cassandra/CassandraConnectorITCase.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/RetryOnException.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/RetryOnFailure.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/RetryRule.java
- flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/RetryRuleTest.java
Beefs up the `RetryRule` to allow configuring retries per class, and subsequently sets up retries for the entire `CassandraConnectorITCase`.
To avoid inconsistent/unexpeced behaviors when combinding class-wide retries with expected exceptions, the latter are now properly handled by the retry rule (i.e., if they occur then we don't retry and just rethrow the exception).
The existing pattern of annotating single methods was not really viable for this case because various tests are inherited from a parent class, which we could only annotated by overriding each of them.
This seemed like annoying busy work, so I fixed the root issue instead.
> [FLINK-20723][cassandra][tests] Retry on NoHostAvailableException 

- docs/content/docs/connectors/datastream/jdbc.md
Fix typo in jdbc execution options
> [hotfix][docs] Fix typo in jdbc execution options

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperatorTest.java
Currently, AsyncWaitOperator directly put the input StreamElement into StreamElementQueue. But when object reuse is enabled, the StreamElement is reused, which means the element in StreamElementQueue will be modified. As a result, the output of AsyncWaitOperator might be wrong.
This pull request is aiming to fix this problem.
- initialize `isObjectReuseEnabled` flag in `AsyncWaitOperator#open()` from `ExecutionConfig`.
- deep copy input `StreamRecord` using serializer if `isObjectReuseEnabled` is true
add a test in `AsyncWaitOperatorTest` to verify state snapshot and restore is correct even if object reuse is enabled and the input record is mutable. …
> [FLINK-12351][DataStream] Fix AsyncWaitOperator to deep copy StreamElement when object reuse is enabled

- docs/data/sql_functions.yml
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/functions/aggfunctions/LagAggFunction.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecGlobalWindowAggregate.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecLocalWindowAggregate.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecWindowAggregate.java
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdColumnInterval.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalGlobalWindowAggregate.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalLocalWindowAggregate.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalWindowAggregate.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/utils/AggFunctionFactory.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/utils/AggregateUtil.scala
- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/functions/aggfunctions/LagAggFunctionTest.java
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdHandlerTestBase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/OverAggregateITCase.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/typeutils/LinkedListSerializer.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/typeutils/LinkedListSerializerTest.java
Fix "LEAD/LAG cannot work correctly in streaming mode".
`LeadLagAggFunction` is only works in batch mode with `OffsetOverFrame`.
In streaming mode, it will output wrong results.
- Add `LinkedListSerializer`.
- Fix wrong document for lead and lag.
- Pass isBounded to `AggFunctionFactory`.
- Implement `LagAggFunction`.
- Add Lag IT Case for streaming mode.
- OverAggregateITCase.testLagFunction
- OverAggregateITCase.testLeadFunction …
> [FLINK-19449][table-planner] LEAD/LAG cannot work correctly in streaming mode

- docs/content.zh/docs/ops/state/state_backends.md
We should remove async checkpoint description of state backends in Chinese documentation as FLINK-21935 had removed "state.backend.async" option. 
> [FLINK-22444][docs] Drop async checkpoint description of state backends in Chinese docs

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/BufferPool.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPool.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PipelinedResultPartition.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/NoOpBufferPool.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/UnpooledBufferPool.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PipelinedResultPartitionReleaseOnConsumptionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PipelinedSubpartitionWithReadViewTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/ResultPartitionFactoryTest.java
This bug was happening when a downstream tasks were failing over or being cancelled. If all
of the downstream tasks released subpartition views, underlying memory segments/buffers could
have been recycled, while upstream task was still writting some records.
The problem is fixed by adding the writer (result partition) itself as one more reference
counted user of the result partition
This change adds new test. …
> [FLINK-22424][network] Prevent releasing PipelinedSubpartition while Task can still write to it

- docs/content.zh/docs/dev/datastream/fault-tolerance/state.md
- docs/content/docs/dev/datastream/fault-tolerance/state.md
* Document correction 
* Removed duplicate `is` in doc 
- If yes, how is the feature documented? ( **not applicable** / docs / JavaDocs / not …
> [hotfix][docs] Removed duplicate 'is'

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/config/ConsumerConfigConstants.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcher.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutRecordPublisher.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutRecordPublisherConfiguration.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriber.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcherTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutRecordPublisherConfigurationTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriberTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/FakeKinesisFanOutBehavioursFactory.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/TestableKinesisDataFetcher.java
Pull in the following fixes from AWS fork:
* Fix issue where `KinesisDataFetcher.shutdownFetcher()` hangs ([issue](https://github.com/awslabs/amazon-kinesis-connector-flink/issues/23), [pull request](https://github.com/awslabs/amazon-kinesis-connector-flink/pull/24))
* Log error when shutting down Kinesis Data Fetcher ([issue](https://github.com/awslabs/amazon-kinesis-connector-flink/issues/22), [pull request](https://github.com/awslabs/amazon-kinesis-connector-flink/pull/25))
* Treating TimeoutException as Recoverable Exception ([issue](https://github.com/awslabs/amazon-kinesis-connector-flink/pull/28), [pull request](https://github.com/awslabs/amazon-kinesis-connector-flink/issues/21))
* Add time-out for acquiring subscription and passing events from network to source thread to prevent …
> [FLINK-22479][Kinesis][Consumer] Potential lock-up under error condition (Flink 1.13)

- docs/content.zh/docs/dev/table/sqlClient.md
- docs/content/docs/dev/table/sqlClient.md
- flink-clients/src/main/java/org/apache/flink/client/cli/CliFrontendParser.java
- flink-python/src/main/java/org/apache/flink/python/PythonOptions.java
Clarify docs. A follow up to http://apache-flink-user-mailing-list-archive.2336050.n4.nabble.com/Contradictory-docs-python-files-config-can-include-not-only-python-files-td43239.html
Clarify docs.
> [hotfix][python][docs] Clarify python.files option

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/config/ConsumerConfigConstants.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcher.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutRecordPublisher.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutRecordPublisherConfiguration.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriber.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcherTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutRecordPublisherConfigurationTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriberTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/FakeKinesisFanOutBehavioursFactory.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/TestableKinesisDataFetcher.java
Pull in the following fixes from AWS fork:
* Fix issue where `KinesisDataFetcher.shutdownFetcher()` hangs ([issue](https://github.com/awslabs/amazon-kinesis-connector-flink/issues/23), [pull request](https://github.com/awslabs/amazon-kinesis-connector-flink/pull/24))
* Log error when shutting down Kinesis Data Fetcher ([issue](https://github.com/awslabs/amazon-kinesis-connector-flink/issues/22), [pull request](https://github.com/awslabs/amazon-kinesis-connector-flink/pull/25))
* Treating TimeoutException as Recoverable Exception ([issue](https://github.com/awslabs/amazon-kinesis-connector-flink/pull/28), [pull request](https://github.com/awslabs/amazon-kinesis-connector-flink/issues/21))
* Add time-out for acquiring subscription and passing events from network to source thread to prevent …
> [FLINK-22479][Kinesis][Consumer] Potential lock-up under error condition (Flink 1.12)

- docs/content/docs/connectors/datastream/jdbc.md
> [FLINK-22289] Update JDBC XA sink docs

- flink-runtime-web/web-dashboard/src/app/pages/job/overview/backpressure/job-overview-drawer-backpressure.component.html
Previously (incorrectly) backpressure-level from the whole task was being displayed for
each of the subtasks.
There are no WebUI tests. Change was manually verified. …
> [FLINK-22489][webui] Fix displaying individual subtasks backpressure-level

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/ReleaseOnConsumptionResultPartition.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/UnpooledBufferPool.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/PartitionRequestQueueTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/ReleaseOnConsumptionResultPartitionTest.java
this is a backport of https://github.com/apache/flink/pull/15734
> 1.11 backport [FLINK-22424][network] Prevent releasing PipelinedSubpartition while Task can still write to it

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/config/ConsumerConfigConstants.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcher.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutRecordPublisher.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutRecordPublisherConfiguration.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriber.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcherTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutRecordPublisherConfigurationTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriberTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/FakeKinesisFanOutBehavioursFactory.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/TestableKinesisDataFetcher.java
Pull in the following fixes from AWS fork:
* Fix issue where `KinesisDataFetcher.shutdownFetcher()` hangs ([issue](https://github.com/awslabs/amazon-kinesis-connector-flink/issues/23), [pull request](https://github.com/awslabs/amazon-kinesis-connector-flink/pull/24))
* Log error when shutting down Kinesis Data Fetcher ([issue](https://github.com/awslabs/amazon-kinesis-connector-flink/issues/22), [pull request](https://github.com/awslabs/amazon-kinesis-connector-flink/pull/25))
* Treating TimeoutException as Recoverable Exception ([issue](https://github.com/awslabs/amazon-kinesis-connector-flink/pull/28), [pull request](https://github.com/awslabs/amazon-kinesis-connector-flink/issues/21))
* Add time-out for acquiring subscription and passing events from network to source thread to prevent …
> [FLINK-22479][Kinesis][Consumer] Potential lock-up under error condition (Flink 1.14)

- flink-tests/src/test/java/org/apache/flink/test/scheduling/AdaptiveSchedulerITCase.java
This addresses the following problem in the testStopWithSavepointFailOnFirstSavepointSucceedOnSecond() test.
Once all tasks are running, the test triggers a savepoint, which intentionally fails, because of a test exception in a Task's checkpointing method. The test then waits for the savepoint future to fail, and the scheduler to restart the tasks. Once they are running again, it performs a sanity check whether the savepoint directory has been properly removed. In the reported run, there was still the savepoint directory around.
The savepoint directory is removed via the PendingCheckpoint.discard() method. This method is executed using the i/o executor pool of the CheckpointCoordinator. There is no guarantee that this discard method has been executed when the job is running again (and the …
> [FLINK-22493] Increase test stability in AdaptiveSchedulerITCase.

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGate.java
```
Leaving a released channel enqueued may lead to
CancelTaskException which can prevent EndOfPartitionEvent
propagation and the job being stuck.
```
> [FLINK-22368] Deque channel after releasing on EndOfPartition

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGate.java
Backport of #15716 to 1.13
```Leaving a released channel enqueued may lead to
CancelTaskException which can prevent EndOfPartitionEvent
propagation and the job being stuck.
```
> [BP-1.13][FLINK-22368] Deque channel after releasing on EndOfPartition

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PrioritizedDeque.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGate.java
Backport of #15716 to 1.12
```Leaving a released channel enqueued may lead to
CancelTaskException which can prevent EndOfPartitionEvent
propagation and the job being stuck.
```
> [BP-1.12][FLINK-22368] Deque channel after releasing on EndOfPartition

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PipelinedSubpartition.java
After peeking last buffer, this last buffer could have been processed
and recycled by the task thread, before NetworkActionsLogger.traceRecover
would manage to check it's content causing IllegalReferenceCount exceptions.
Further more, this log seemed excessive and was accidentally added after
debugging session, so it's ok to remove it.
- …
> [FLINK-22548][network] Remove illegal unsynchronized access to PipelinedSubpartition#buffers

- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/Execution.java
- flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/SubtaskGatewayImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
This PR updated SubtaskGatewayImpl to specify the cause of sendEvent() failure when triggering task failover. This change is useful to understand why the event could not be sent.
This PR updated SubtaskGatewayImpl to specify the cause of sendEvent() failure when triggering task failover.
I manually updated SubtaskGatewayImpl::sendEvent(...) to set `failure = new FlinkException("some error")` and then run the test `KafkaSourceLegacyITCase#testOneToOneSources`. The test fails with the following stacktrace in the log:
```
...
Caused by: org.apache.flink.util.FlinkException: An OperatorEvent from an OperatorCoordinator to a task was lost. Triggering task failover to ensure consistency. Event: 'AddSplitEvents[[[B@23adb3ce]]', targetTask: Source: KafkaSource -> Map -> Map (1/5) - execution #1 …
```
> [FLINK-22488][hotfix] Update SubtaskGatewayImpl to specify the cause of sendEvent() failure when triggering task failover

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperatorTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskMailboxTestHarness.java
As long as the mailbox is blocked, timers are not cancelled, such that a completed element might still get a timeout.
The fix is to check the completed flag when the timer triggers.
Added `AsyncWaitOperatorTest#testTimeoutAfterComplete`. …
> [FLINK-22573][datastream] Fix AsyncIO calls timeout on completed element.

- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/operations/SqlToOperationConverter.java
- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/operations/SqlToOperationConverterTest.java
Modified the spelling error of word "constant" in source code.   As described in FLINK-22233.
- The description about ValidationException message in method org.apache.flink.table.planner.operations.SqlToOperationConverter#validateTableConstraint, change constaint to constraint.
- The description about ValidationException message in method org.apache.flink.table.planner.operations.SqlToOperationConverterTest#testCreateTableWithPrimaryKeyEnforced, change constaint to constraint.
- The description about ValidationException message in method org.apache.flink.table.planner.operations.SqlToOperationConverterTest#testAlterTableAddPkConstraintEnforced, change constaint to constraint. …
> [FLINK-22233][Table SQL / API]Modified the spelling error of word "constant" in source code

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperatorTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskMailboxTestHarness.java
Unchanged backport of #15836 (well squashed into 1 commit).
As long as the mailbox is blocked, timers are not cancelled, such that a completed element might still get a timeout.
The fix is to check the completed flag when the timer triggers.
Added `AsyncWaitOperatorTest#testTimeoutAfterComplete`. …
> [FLINK-22573][datastream] Fix AsyncIO calls timeout on completed element. [1.12]

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperatorTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskMailboxTestHarness.java
Unchanged backport of #15836 (well squashed into 1 commit).
As long as the mailbox is blocked, timers are not cancelled, such that a completed element might still get a timeout.
The fix is to check the completed flag when the timer triggers.
Added `AsyncWaitOperatorTest#testTimeoutAfterComplete`. …
> [FLINK-22573][datastream] Fix AsyncIO calls timeout on completed element. [1.13]

- pom.xml
1.12.3 is broken because Scala 2.12 artifacts are actually 2.11 artifacts. We now verify again against 1.12.2, and will later jump straight to 1.12.4 once it was released.
This does bear the risk that 1.12.4 may break APIs introduced in 1.12.3; ideally we make sure this doesn't happen by not touching any API.
> [FLINK-22557][build] Run japicmp against 1.12.2

- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/test/util/MiniClusterWithClientResource.java
- flink-tests/src/test/java/org/apache/flink/test/scheduling/ReactiveModeITCase.java
Stabilizes the ReactiveModeITCase by not checking what is actually being deployed, but just asking the JM with what parallelism it currently intends to run the job with.
> [FLINK-22406][coordination][tests] Stabilize ReactiveModeITCase

- flink-runtime/src/main/java/org/apache/flink/runtime/rpc/RpcEndpoint.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rpc/RpcEndpointTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rpc/akka/AkkaRpcActorTest.java
Several `RpcEndpoint` tests were verifying the handling of delays based via various `schedule*` methods by checking how long it took for a schedule unit to be exected
Such tests are well known to be unstable because it is not really possible to define sane upper bounds for how long it might take for the unit to be executed.
These tests have been reworked to instead check what delay is in the end passed to `MainThreadExecutable#scheduleRunAsync`.
> [FLINK-22419][coordination][tests] Rework RpcEndpoint delay tests

- flink-connectors/flink-connector-cassandra/pom.xml
- flink-connectors/flink-connector-elasticsearch5/pom.xml
- flink-connectors/flink-connector-kafka/pom.xml
- flink-dist/pom.xml
- flink-filesystems/flink-azure-fs-hadoop/pom.xml
- flink-filesystems/flink-fs-hadoop-shaded/pom.xml
- flink-filesystems/flink-oss-fs-hadoop/pom.xml
- flink-filesystems/flink-s3-fs-hadoop/pom.xml
- flink-filesystems/flink-s3-fs-presto/pom.xml
- flink-kubernetes/pom.xml
- flink-libraries/flink-gelly-scala/pom.xml
- flink-python/pom.xml
- flink-runtime/pom.xml
- flink-test-utils-parent/flink-test-utils/pom.xml
- pom.xml
Removes auto-generated maven metadata from all jars as this may accidentally bundle poms under incompatible licenses, and adds another exclusions for jboss schema files contained in flink-python.
> [FLINK-22555][build][python] Exclude leftover jboss files 

- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/join/window/WindowJoinOperator.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/join/window/WindowJoinOperatorBuilder.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/window/state/WindowListState.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/operators/join/window/WindowJoinOperatorTest.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/operators/rank/window/WindowRankOperatorTest.java
This pull request aims to introduce WindowJoinOperator and WindowJoinOperatorBuilder, which is second step of [FLINK-19606](https://issues.apache.org/jira/browse/FLINK-19606).
- Introduce `WindowJoinOperator` and `WindowJoinOperatorBuilder`
- Introduce `WindowListState`, it is a wrapper of `ListState` which is easier to update based on window namespace
- Add `WindowJoinOperatorTest` to test `WindowJoinOperator`.
- The runtime per-record code paths (performance sensitive): no)
- The S3 file …
> [FLINK-19606][table-runtime-blink] Introduce WindowJoinOperator and WindowJoinOperatorBuilder.

- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecWindowJoin.java
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalWindowJoin.scala
- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/WindowJoinJsonPlanTest.java
- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/runtime/stream/jsonplan/WindowJoinJsonITCase.java
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/WindowJoinJsonPlanTest_jsonplan/testEventTimeTumbleWindow.out
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/WindowJoinITCase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/utils/TestData.scala
The pull request aims to  introduce `StreamExecWindowJoin` and  window join it cases. This is the third step of [FLINK-19606](https://issues.apache.org/jira/browse/FLINK-19606).
- Introduce `StreamExecWindowJoin` which is exec node for WindowJoin
- Update  `StreamPhysicalWindowJoin` #translateToExecNode method
- *Added `WindowJoinITCase` which contains integration tests for windowJoin
- *Added  `WindowJoinJsonITCase` and `WindowJoinJsonPlanTest` which contains json validation …
> [FLINK-19606][table-runtime-blink] Introduce StreamExecWindowJoin and window join it cases

- flink-clients/src/test/java/org/apache/flink/client/program/PerJobMiniClusterFactoryTest.java
- flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/WebFrontendITCase.java
- flink-runtime/src/main/java/org/apache/flink/runtime/iterative/task/AbstractIterativeTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/iterative/task/IterationHeadTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/iterative/task/IterationIntermediateTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/iterative/task/IterationSynchronizationSinkTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/iterative/task/IterationTailTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/iterative/task/Terminable.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/tasks/AbstractInvokable.java
- flink-runtime/src/main/java/org/apache/flink/runtime/operators/BatchTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/operators/DataSinkTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/operators/DataSourceTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/TestingAbstractInvokables.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/CoordinatorEventsExactlyOnceITCase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorOperatorEventHandlingTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/testtasks/OnceBlockingNoOpInvokable.java
- flink-runtime/src/test/java/org/apache/flink/runtime/testutils/CancelableInvokable.java
- flink-runtime/src/test/scala/org/apache/flink/runtime/jobmanager/Tasks.scala
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
Prevent closing of network resources until mailbox processor is
shut down, so that emitting output from timer actions is possible.
Added `StreamTaskTest.testCancellationWaitsForActiveTimers`.
> [FLINK-21181][runtime] Wait for Invokable cancellation before releasing network resources

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/checkpointing/SingleCheckpointBarrierHandler.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/checkpointing/AlternatingCheckpointsTest.java
The active timeout did not take effect if it elapsed before the first
barrier arrived. The reason is that we did not reset the future for
checkpoint complete on barrier announcement. Therefore we considered the
completed status for the previous checkpoint when evaluating the timeout for
the current checkpoint.
- …
> [FLINK-22596][checkpoints] Active timeout is not triggered if there were no barriers

- flink-end-to-end-tests/test-scripts/common_yarn_docker.sh
In [FLINK-22566](https://issues.apache.org/jira/browse/FLINK-22566) we ran an issue where the TaskManager didn't come up immediately after spawning the YARN containers. There was no way to investigate the gap between the container transitioning into `RUNNING` state and the `TaskManager` starting to generate output.
The suspicion is that there's some infrastructure issue that is hidden. We're missing the NodeManager logs to investigate that. They are located on the worker nodes. This PR adds the extraction of logs located on the worker nodes.
* Moves log extraction and printing into its own functions
* calls these functions for the `master` and the `worker*` nodes
* ✅ Functions were tested locally
* ❌ we have to wait for some test runs to fail (like the [loop AzureCI …
> [FLINK-22566][test] Adds NodeManager log extraction to YARN-related e2e tests

- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/harness/GroupAggregateHarnessTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/harness/HarnessTestBase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/harness/OverAggregateHarnessTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/harness/TableAggregateHarnessTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/harness/WindowAggregateHarnessTest.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/aggregate/window/LocalSlicingWindowAggOperator.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/bundle/AbstractMapBundleOperator.java
fix NPE on bundle close when task failover after a failed task open and add case for current sql harness tests.
- add null check on finishBundle for AbstractMapBundleOperator
- add close without open case for current sql harness tests.
- Extended HarnessTest for close without open
> [FLINK-22604] [table-runtime-blink] fix NPE on bundle close when task failover after a failed task open

- flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/utils/SavepointTestBase.java
This PR is here to use the Flink CI capacity to quickly validate this.
> [hotfix] Disable broken savepoint tests tracked in FLINK-22067

- docs/content.zh/docs/dev/datastream/project-configuration.md
- docs/content/docs/dev/datastream/project-configuration.md
- pom.xml
- tools/releasing/NOTICE-binary_PREAMBLE.txt
Fixes CVE-2020-9488 and a layout issue a user runs into.
> [FLINK-22407][build] Bump log4j to 2.24.1

- flink-table/flink-table-planner-blink/src/main/java/org/apache/calcite/sql/SqlGroupedWindowFunction.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/expressions/PlannerWindowEnd.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/expressions/PlannerWindowStart.java
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/GroupWindowAggregateJsonPlanTest_jsonplan/testEventTimeTumbleWindow.out
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/GroupWindowAggregateJsonPlanTest_jsonplan/testProcTimeTumbleWindow.out
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/LegacyTableSourceTest.xml
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/MatchRecognizeTest.xml
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/agg/GroupWindowTest.xml
Add the following test case to org.apache.flink.table.planner.plan.stream.sql.agg.WindowAggregateTest to reproduce this bug.
```scala
@Test
def testSessionFunction(): Unit = {
val sql =
"""
|SELECT
|    COUNT(*),
|    SESSION_START(proctime, INTERVAL '15' MINUTE),
|    SESSION_END(proctime, INTERVAL '15' MINUTE)
|FROM MyTable
|    GROUP BY SESSION(proctime, INTERVAL '15' MINUTE)
""".stripMargin
util.verifyExecPlan(sql)
}
```
The produced plan is
```
Calc(select=[EXPR$0, CAST(w$start) AS EXPR$1, CAST(w$end) AS EXPR$2])
+- GroupWindowAggregate(window=[SessionGroupWindow('w$, proctime, 900000)], properties=[w$start, w$end, w$proctime], select=[COUNT(*) AS EXPR$0, start('w$) AS w$start, end('w$) AS w$end, proctime('w$) AS w$proctime])
+- Exchange(distribution=[single])
+- …
```
> [FLINK-22313][table-planner-blink] Redundant CAST in plan when selecting window start and window end in window agg

- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/functions/sql/SqlCumulateTableFunction.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/functions/sql/SqlHopTableFunction.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/functions/sql/SqlTumbleTableFunction.java
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/WindowTableFunctionTest.scala
Currently, the following query can run and no exception is thrown.
However, the second interval parameter (i.e. the offset parameter) is not supported yet. We should throw a exception for this.
```
select 
date_format(window_end, 'yyyy-MM-dd') as date_str,
date_format(window_end, 'HH:mm') as time_str,
count(distinct user_id) as uv
from table(tumble(table user_behavior, descriptor(ts), interval '10' minute, interval '1' day))
group by window_start, window_end;
```
- check parameter count in `checkOperandTypes` of window functions. 
- Added unit tests for `TUMBLE` , `HOP`, and `CUMULATE`. 
- The serializers: (yes / **no** / …
> [FLINK-22523][table-planner-blink] TUMBLE TVF should throw helpful exception when specifying second interval parameter

- flink-end-to-end-tests/test-scripts/common_yarn_docker.sh
Backport of [FLINK-22566](https://issues.apache.org/jira/browse/FLINK-22566) (see #15853 for further details). I cherry-picked [fd9acef](https://github.com/apache/flink/pull/15853/commits/fd9acef360db3c4eb0a333ce904ba84fe98840d2) and [5930f37](https://github.com/apache/flink/pull/15853/commits/5930f37301f77a48b946f14ba99236e12763a7e2).
> [BP-1.13][FLINK-22566][test] Adds NodeManager log extraction to YARN-related e2e tests

- docs/content.zh/docs/dev/datastream/sources.md
It is aimed to translate the page of "Data Sources" to Chinese, which is still in English currently.
Translate "docs/content.zh/docs/dev/datastream/sources.md" from English to Chinese.
> [FLINK-22364][doc] Translate the page of "Data Sources" to Chinese.

- tools/ci/java-ci-tools/src/main/java/org/apache/flink/tools/ci/licensecheck/JarFileChecker.java
- tools/ci/java-ci-tools/src/main/java/org/apache/flink/tools/ci/licensecheck/LicenseChecker.java
- tools/ci/java-ci-tools/src/main/java/org/apache/flink/tools/ci/licensecheck/NoticeFileChecker.java
- tools/ci/java-ci-tools/src/test/java/org/apache/flink/tools/ci/licensecheck/JarFileCheckerTest.java
With this PR the license checker searches all jar files we releases for files containing text fragments that indicate incompatible licenses. I have select a few licenses that I think we could maybe at some point run into.
There are a fair number of exclusions that filter out various false-positives. The DEPENDENCIES file by maven frequently contains forbidden fragments because of a dual-licensed dependency; similar things happen in LICENSE/NOTICE files, which may also contain additional hints for downloading optional components (which is permitted).
Dual-licensing strikes again in the javax/glassfish dependencies that we bundle.
For reviewing purposes it can be useful to revert 8f3d483d7432f2857035be07d8f54612cde18b57 and 06b3e26d9239e31e247588755fe649fec96c256a.
> [FLINK-22556][ci] Extend JarFileChecker to search for traces of incompatible licenses

- docs/layouts/shortcodes/generated/security_auth_kerberos_section.html
- docs/layouts/shortcodes/generated/security_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/SecurityOptions.java
- flink-yarn/src/main/java/org/apache/flink/yarn/Utils.java
- flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
Linked to [ISSUE](https://issues.apache.org/jira/browse/FLINK-21700#).
I want to support Flink Batch Action on Oozie.
As we know, Oozie will obtain HDFS/HBase delegation token using Hadoop proxy user mechanism before starting Flink submitter cli. If not, Flink will obtain delegation token again, this will cause exception.
Actually, Spark support disable fetching delegation token on Spark client, [related Spark doc](https://spark.apache.org/docs/latest/running-on-yarn.html#launching-your-application-with-apache-oozie).
So i think Flink should allow to disable fetching Hadoop delegation token on Yarn.
> [FLINK-21700][security] Add an option to disable credential retrieval on a secure cluster

- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/factories/datagen/RandomGeneratorVisitor.java
- flink-table/flink-table-api-java-bridge/src/test/java/org/apache/flink/table/factories/DataGenTableSourceFactoryTest.java
Fix DataGen SQL Connector does not support defining fields min/max option of decimal type field.
- *Fix the RandomGeneratorVisitor lost min / max option for decimal type.
- *Extended DataGenTableSourceFactoryTest to validate the fix*
> [FLINK-22640][datagen] Fix DataGen SQL Connector does not support defining fields min/max option of decimal type field.

- docs/content.zh/docs/dev/table/data_stream_api.md
- docs/content/docs/dev/table/data_stream_api.md
* Changed argument for toDataStream to Table
* Corrected argument for toDataStream …
> [hotfix][docs] Changed argument for toDataStream to Table

- flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/ddl/SqlCreateTable.java
- flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java
* Fix SqlCreateTable toString()/unparse() lose CONSTRAINTS and watermarks *
- *  42e9510  fix SqlCreateTable toString()/unparse() lose CONSTRAINTS and watermarks *
- *Added unit tests to verify function work as expected. * …
> [FLINK-22654][table] fix SqlCreateTable toString()/unparse() lose CONSTRAINTS and watermarks

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/DefaultCompletedCheckpointStore.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/DefaultCompletedCheckpointStoreTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/ZooKeeperCompletedCheckpointStoreMockitoTest.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/CheckpointStoreITCase.java
```
Ignoring such failures and running with an incomplete
set of checkpoints can lead to consistency violation.
Instead, transient failures should be mitigated by
automatic job restart.
```
- Updated `DefaultCompletedCheckpointStoreTest` to reflect new behavior
- Added `CheckpointStoreITCase` to ensure that failure on recovery is mitigated by job restart
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: yes …
> [FLINK-22502][checkpointing] Don't tolerate checkpoint retrieval failures on recovery

- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/functions/aggfunctions/MaxAggFunction.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/functions/aggfunctions/MinAggFunction.java
Fix comments in `MaxAggFunction.retractExpressions`, return `Expression[0]` is right.
```
See optimization in FlinkRelMdModifiedMonotonicity.
MaxAggFunction can ignore retraction message:
SQL: SELECT MAX(cnt), SUM(cnt) FROM (SELECT count(a) as cnt FROM T GROUP BY b)
The cnt is modified increasing, so the MAX(cnt) can ignore retraction message. But this
doesn't mean that the node won't receive the retraction message, because there are other
aggregate operators that need retraction message, such as SUM(cnt).
``` …
> [FLINK-12295][table] Fix comments in MinAggFunction and MaxAggFunction

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesHaServices.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesHaServicesTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/AbstractHaServices.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/HighAvailabilityServices.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/nonha/AbstractNonHaServices.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/zookeeper/ZooKeeperHaServices.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/AbstractHaServicesTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/TestingHighAvailabilityServices.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/TestingManualHighAvailabilityServices.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/zookeeper/ZooKeeperHaServicesTest.java
Backport of #15561 to `release-1.13`.
> [BP-1.13][FLINK-20695][ha] Clean ha data for job if globally terminated

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesHaServices.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesHaServicesTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/AbstractHaServices.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/HighAvailabilityServices.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/nonha/AbstractNonHaServices.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/zookeeper/ZooKeeperHaServices.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/AbstractHaServicesTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/TestingHighAvailabilityServices.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/TestingManualHighAvailabilityServices.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/zookeeper/ZooKeeperHaServicesTest.java
Backport of #15561 to `release-1.12`.
> [BP-1.12][FLINK-20695][ha] Clean ha data for job if globally terminated

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStore.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/Fabric8FlinkKubeClient.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/FlinkKubeClient.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/KubernetesClientTestBase.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/MixedKubernetesServer.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStoreITCase.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStoreTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/Fabric8FlinkKubeClientTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointsCleaner.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/DefaultCompletedCheckpointStore.java
- flink-runtime/src/main/java/org/apache/flink/runtime/persistence/PossibleInconsistentStateException.java
- flink-runtime/src/main/java/org/apache/flink/runtime/persistence/StateHandleStore.java
- flink-runtime/src/main/java/org/apache/flink/runtime/util/StateHandleStoreUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStore.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorFailureTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTestingUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/persistence/TestingLongStateHandleHelper.java
- flink-runtime/src/test/java/org/apache/flink/runtime/util/StateHandleStoreUtilsTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStoreTest.java
See detailed description in original PR #15832.
```
git cherry-pick c903d5420b 102a09d9a9 c74c671974 6b2f070cb8 4c7f59bea0
```
No conflicts appeared when cherry-picking the commits from PR #15832
> [BP-1.13][FLINK-22494][runtime] Introduce PossibleInconsistentStateException

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStore.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/Fabric8FlinkKubeClient.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/FlinkKubeClient.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/KubernetesClientTestBase.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/MixedKubernetesServer.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStoreITCase.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStoreTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/Fabric8FlinkKubeClientTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointsCleaner.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/DefaultCompletedCheckpointStore.java
- flink-runtime/src/main/java/org/apache/flink/runtime/persistence/PossibleInconsistentStateException.java
- flink-runtime/src/main/java/org/apache/flink/runtime/persistence/StateHandleStore.java
- flink-runtime/src/main/java/org/apache/flink/runtime/util/StateHandleStoreUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStore.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorFailureTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTestingUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/persistence/TestingLongStateHandleHelper.java
- flink-runtime/src/test/java/org/apache/flink/runtime/util/StateHandleStoreUtilsTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStoreTest.java
See detailed description in original PR #15832.
```
git cherry-pick c903d5420b 102a09d9a9 c74c671974 6b2f070cb8 4c7f59bea0
```
There was some conflict that needed to be resolved for `4c7f59bea0` resulting in [a0bfff8](https://github.com/apache/flink/commit/a0bfff801337de40a41fe919a7cc3a83ab909028)
> [BP-1.12][FLINK-22494][runtime] Introduce PossibleInconsistentStateException

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/optimize/program/FlinkChangelogModeInferenceProgram.scala
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/DeduplicateTest.xml
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/TableScanTest.xml
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/agg/GroupWindowTest.xml
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/DeduplicateTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/TableScanTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/agg/GroupWindowTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/GroupWindowITCase.scala
Now, Window operator already support consume retract streams in runtime module. The pr aims to consume retractions for window aggregate operator in planner module.
Fix Window Aggregate behavior in `FlinkChangelogModeInferenceProgram`.
UT/IT
> [FLINK-20487][table-planner-blink] Remove restriction on StreamPhysicalGroupWindowAggregate which only supports insert-only input node

- flink-end-to-end-tests/run-nightly-tests.sh
Enable Confluent Schema Registry e2e Test on jdk 11 nightly run
I ran the change on private azure with jdk11 enabled https://dev.azure.com/georgeryan1322/Flink/_build/results?buildId=374&view=logs&j=9401bf33-03c4-5a24-83fe-e51d75db73ef&t=72901ab2-7cd0-57be-82b1-bca51de20fba&l=149
- …
> [FLINK-22696] Enable Confluent Schema Registry e2e Test on jdk 11

- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/zookeeper/ZooKeeperHaServicesTest.java
Backport of #15954 to `release-1.13`.
> [BP-1.13][FLINK-22704][tests] Harden ZooKeeperHaServicesTest.testCleanupJobData

- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/SavepointRestoreSettings.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraphGenerator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/StreamGraphGeneratorTest.java
Make the configuration of SavepointSettings more uniform with other configuration options and be applied to the StreamGraph generated from StreamExecutionEnvironment. …
> [FLINK-22708][config] Propagate savepoint settings from StreamExecutionEnvironment to StreamGraph

- flink-table/flink-sql-parser-hive/src/main/codegen/includes/parserImpls.ftl
- flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl
- flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/dql/SqlRichExplain.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/operations/SqlToOperationConverter.java
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/calcite/FlinkPlannerImpl.scala
- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/operations/SqlToOperationConverterTest.java
- flink-table/flink-table-planner-blink/src/test/resources/explain/testExecuteSqlWithExplainInsert.out
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/sqlexec/SqlToOperationConverter.java
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/calcite/FlinkPlannerImpl.scala
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/sqlexec/SqlToOperationConverterTest.java
- flink-table/flink-table-planner/src/test/scala/resources/testExecuteSqlWithExplainInsert0.out
- flink-table/flink-table-planner/src/test/scala/resources/testExecuteSqlWithExplainInsert1.out
*(or)*
*(or)*
*(example:)*
- *Extended …
> [FLINK-22155][table-api][parser] fix explain insert or select two case,sql convert separate selection.

- flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/JobExceptionsHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/exceptionhistory/ExceptionHistoryEntry.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/job/JobExceptionsHandlerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/DefaultSchedulerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/exceptionhistory/ExceptionHistoryEntryTest.java
Additionally, I added a few Preconditions to the ExceptionHistoryEntry creation
to make the code more robust.
An `ExceptionHistoryEntry` referring to a local task failure can also have the
TaskManagerLocation not being set (e.g. in cases where the task is not deployed,
yet). The previous implementation failed in the REST endpoint in that case.
The Precondition checking the availability of the `TaskManagerLocation` was removed. The `ExceptionHistoryEntry.isGlobal` which is called before only checks the availability of the task name.
Additionally, I added some Preconditions to make the code more robust and added tests for these.
* A test was added to `JobExceptionsHandlerTest` to verify the issue 
* Additional tests were added to `ExceptionHistoryEntryTest` to test the Preconditions added …
> [FLINK-22688][runtime] Eases assertion on ExceptionHistoryEntry

- flink-clients/src/main/java/org/apache/flink/client/program/rest/RestClusterClient.java
- flink-clients/src/test/java/org/apache/flink/client/program/rest/RestClusterClientTest.java
- flink-end-to-end-tests/test-scripts/common.sh
- flink-end-to-end-tests/test-scripts/test_kubernetes_application.sh
- flink-end-to-end-tests/test-scripts/test_kubernetes_pyflink_application.sh
- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/MiniDispatcher.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMasterServiceLeadershipRunner.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobResult.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/TestingDispatcher.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterServiceLeadershipRunnerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/TestingJobManagerRunner.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/LeaderChangeClusterComponentsTest.java
> [BP-1.13][FLINK-22434] Store suspended execution graphs on termination to keep them accessible

- flink-clients/src/main/java/org/apache/flink/client/program/rest/RestClusterClient.java
- flink-clients/src/test/java/org/apache/flink/client/program/rest/RestClusterClientTest.java
- flink-end-to-end-tests/test-scripts/common.sh
- flink-end-to-end-tests/test-scripts/test_kubernetes_application.sh
- flink-end-to-end-tests/test-scripts/test_kubernetes_pyflink_application.sh
- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/MiniDispatcher.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobManagerRunnerImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobResult.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherJobTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/TestingDispatcher.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobManagerRunnerImplTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/TestingJobManagerRunner.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/LeaderChangeClusterComponentsTest.java
Backport of #15799 
@tillrohrmann Can you have another look at 5638689? I resolved a lot of conflicts for this commit
> [BP-1.12][FLINK-22434] Store suspended execution graphs on termination to keep them accessible

- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/DeclarativeSlotManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/FineGrainedSlotManager.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/DeclarativeSlotManagerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/FineGrainedSlotManagerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/FineGrainedSlotManagerTestBase.java
Modified version of #15904.
Slotmanagers register metrics in start(), but only unregister them in close().
This has 2 issues:
a) If the SM is restarted it cannot re-register the metrics because the old ones are still present; this isn't a critical problem (because the old ones still work) but it produces unnecessary logging noise
b) The metric may produce an NPE when accessed by a reporter during suspend().
> [FLINK-22725][coordination] SlotManagers unregister metrics in suspend()

- flink-table/flink-sql-client/src/test/resources/sql/table.q
- flink-table/flink-sql-parser/src/main/codegen/data/Parser.tdd
- flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl
- flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/ddl/SqlAlterTableReset.java
- flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/operations/SqlToOperationConverter.java
- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/operations/SqlToOperationConverterTest.java
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/api/TableEnvironmentTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/catalog/CatalogTableITCase.scala
This pull request supports `ALTER TABLE t RESET('key', ...)` syntax.
- Extend `Parser.tdd` and `parserImpls.ftl` templates to support syntax. Add `SqlAlterTableReset` to represent the SqlNode after parsing.
- Extend `SqlToOperationConverter` to convert `SqlAlterTableReset` to `AlterTableOptionsOperation` by first cloning the table options of the current resolved catalog table, and then removing the keys present in `SqlAlterTableReset`.
- Add a util method `OperationConverterUtils#extractTableOptionKeys`  to extract table option keys from `SqlAlterTableReset`.
- Added tests in `FlinkSqlParserImplTest` to verify parsing syntax correctly.
- Added cases in `SqlToOperatorConverterTest#testAlterTable` to verify operation transforming …
> [FLINK-22319][table][sql-client] Support RESET table option for ALTER TABLE statement

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliStatementSplitter.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/SqlClientTest.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientTest.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliStatementSplitterTest.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/parse/SetOperationParseStrategy.java
*this change is in order to use comments in the initialization script with '--' in the SQL Client*
*add cleanLine in CliStatementSplitter#splitContent*
*Modify the original test file CliStatementSplitterTest.java and CliClientTest.java* …
> [FLINK-22655]When using -i <init.sql> option to initialize SQL Client session It should be possible to annotate the script with --

- docs/layouts/shortcodes/generated/rocksdb_configurable_configuration.html
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBConfigurableOptions.java
Correct the applicability of some RocksDB related options as per operator
> [FLINK-22759][docs] Correct the applicability of some RocksDB related options as per operator

- docs/content/docs/connectors/datastream/kafka.md
This pull request adds documentation for Kafka new source.
- Add documentation for Kafka new source
> [FLINK-22722][docs/kafka] Add documentation for Kafka new source

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceOperatorStreamTask.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceOperatorStreamTaskTest.java
Calculate checkpointStartDelay for FLIP-27 sources
> [FLINK-22814][metrics] Calculate checkpointStartDelay for FLIP-27 sources

- flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroRowSerializationSchema.java
- flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/typeutils/AvroConversions.java
- flink-formats/flink-parquet/pom.xml
- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/ParquetAvroInputFormat.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/ParquetAvroInputFormatTest.java
Implement ParquetAvroInputFormat
new ParquetAvroInputFormatTest test both simple record and projected fields with simple record but sets parquet.avro.write-old-list-structure to true because AvroRowSerializationSchema does not work with parquet.avro.write-old-list-structure set to false 
- Dependencies (does it add or upgrade a dependency): yes, flink-parquet now depends on flink-avro
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes adds new API  (new input format)
- The serializers: not really, just make …
> [FLINK-21393] [formats] Implement ParquetAvroInputFormat

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliUtils.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliUtilsTest.java
*This pull request fixs sql-client can not create .flink-sql-history file when parent directory is a symbolic link.*
- *Add Unit Test for CliUtils.*
- *Fix bug: create directory based symbolic link throws exception.*
- *Added Unit Test for CliUtils.*
- Dependencies (does it add or upgrade a dependency): ( *no* )
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( *no* )
- The serializers: (  *no* )
- The runtime per-record code paths (performance sensitive): ( *no* )
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: ( *no* )
- The S3 file system connector: ( *no* )
- Does this pull request introduce a new feature? ( *no* )
- …
> [FLINK-22786][sql-client] sql-client can not create .flink-sql-history file

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/LocalInputChannel.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/TestTaskStateManager.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceOperatorStreamTaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTaskTestBase.java
This PR is fixing a bug of `checkpointStartDelay` being not set in `CheckpointMetrics` of `SourceStreamTask` and `SourceOperatorStreamTask`.
- If yes, how is the feature documented? (**not applicable** / docs / …
> [FLINK-22833][metrics] Set checkpointStartDelay in checkpoint metrics for SourceTasks

- flink-runtime/src/main/java/org/apache/flink/runtime/state/AbstractKeyedStateBackend.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/ConfigurableStateBackend.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/TestableKeyedStateBackend.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/FileStateBackendTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/HashMapStateBackendTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/MemoryStateBackendTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendTestBase.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogDelegateEmbeddedRocksDBStateBackendTest.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogDelegateFileStateBackendTest.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogDelegateHashMapTest.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogDelegateMemoryStateBackendTest.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/EmbeddedRocksDBStateBackendTest.java
Test issues were discovered during recovery implementation (#15420) and were extracted into a separate PR:
```
- Use ChangelogStateBackend on recovery in the relevant tests
- Discard state snapshot iff not null - changelog backend returns null if nothing was snapshotted (according to the contract)
- Add assumptions to state backend tests - e.g. changelog backend doesn't use the provided output stream factory
- Assert latency tracking on delegated backend - there is an explicit cast which fails for changelog backend
``` …
> [FLINK-22835] Adjust ChangelogStateBackend tests

- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/output/SnapshotUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointOptions.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/CheckpointBarrier.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/serialization/EventSerializer.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointOptionsTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PipelinedSubpartitionWithReadViewTest.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamEdge.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraphGenerator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/RecordWriterOutput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/OperatorChain.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceOperatorStreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorImpl.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/StreamGraphGeneratorTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/AlternatingCheckpointBarrierHandlerTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/InputProcessorUtilTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorTest.java
This is a backport of parts of  #16019 and #15294
Broadcast partitioning can not work with unaligned checkpointing. There are no guarantees that records are consumed at the same rate in all channels. This can result in some tasks applying state changes corresponding to a certain broadcasted event while others don't. 
In turn upon restore, it may lead to an inconsistent state. This is especially harmful to the most common pattern for using a broadcast pattern where only a single operator checkpoints its state and that state is copied over to all other operators on restore.
> [FLINK-22815][checkpointing][bp-1.11] Disable unaligned checkpoints for broadcast partitioning

- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/output/SnapshotUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointOptions.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/CheckpointBarrier.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/serialization/EventSerializer.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/writer/SubtaskStateMapper.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointOptionsTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/writer/SubtaskStateMapperTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PipelinedSubpartitionWithReadViewTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/ChannelStatePersisterTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/LocalInputChannelTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/RemoteInputChannelTest.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamEdge.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraphGenerator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/RecordWriterOutput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/partitioner/BroadcastPartitioner.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/OperatorChain.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceOperatorStreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorImpl.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/StreamGraphGeneratorTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/CheckpointedInputGateTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/InputProcessorUtilTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorTest.java
This is a backport of parts of #16019 and #15294
Broadcast partitioning can not work with unaligned checkpointing. There are no guarantees that records are consumed at the same rate in all channels. This can result in some tasks applying state changes corresponding to a certain broadcasted event while others don't.
In turn upon restore, it may lead to an inconsistent state. This is especially harmful to the most common pattern for using a broadcast pattern where only a single operator checkpoints its state and that state is copied over to all other operators on restore.
> [FLINK-22815][checkpointing][bp-1.12] Disable unaligned checkpoints for broadcast partitioning

- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/WindowRankITCase.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/rank/window/WindowRankOperatorBuilder.java
The pull request aims to a minor fix on rankEnd validation of WindowRank to support top1 
- A minor update in `WindowRankOperatorBuilder` to support top1 
- Add ITCase in WindowRankITCase
> [FLINK-22894][table-runtime-blink] Fix rankEnd validation of WindowRank to support top1

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveTableSink.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/sink/filesystem/Bucket.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/sink/filesystem/Buckets.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/filesystem/FileSystemTableSink.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/filesystem/stream/AbstractStreamingWriter.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/filesystem/stream/PartitionCommitPredicate.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/filesystem/stream/PartitionCommitTrigger.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/filesystem/stream/PartitionTimeCommitPredicate.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/filesystem/stream/PartitionTimeCommitTrigger.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/filesystem/stream/ProcTimeCommitPredicate.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/filesystem/stream/ProcTimeCommitTrigger.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/filesystem/stream/StreamingFileWriter.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/filesystem/stream/StreamingSink.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/filesystem/stream/StreamingFileWriterTest.java
*This pull request is to fix the issue that  although partition has committed, the file in this partition is still unready *
- *Add PartitionCommitTrigger in StreamingFileWriter to check the parition is committable or not*
- *close inprogress-file if the partition is committable when StreamingFileWriter is doing snapshotState*
- *Added tests to assert close and commit inprogress-file if the partition is committable  in StreamingFileWriterTest#testCommitFileWhenPartitionIsCommittableByProcessTime and StreamingFileWriterTest#testCommitFileWhenPartitionIsCommittableByPartitionTime*
- The …
> [FLINK-22472][filesystem] close file of partition when partition is committable

- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/ExtractionUtils.java
The `ClassReader` does not automatically close the given `InputStream`, so we need to do it manually.
> [FLINK-22734][table] Close input stream

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/NettyPartitionRequestClient.java
*For `NettyPartitionRequestClient#requestSubpartition`, when a channel is closed, the channel will throw a LocalTransportException with the error message "Sending the partition request to 'null' failed.". The message is confusing since we wouldn't know where the remote client connected to this channel locates, and we couldn't track down to that TaskExecutor and find out what happened.*
*In this situation, we need to log the address stored in `ConnectionID` instead of the null value in `ChannelFuture`. Users can located the destination TaskManager based on this remote address.*
- *Log the remote address stored in `ConnectionID` instead of null value in `ChannelFuture` when channel is closed in NettyPartitionRequestClient* …
> [FLINK-22284] Log the remote address when channel is closed in NettyPartitionRequestClient

- azure-pipelines.yml
- tools/azure-pipelines/build-apache-repo.yml
- tools/azure-pipelines/jobs-template.yml
- we now always setup the JDK, irrespective of what value `jdk` is set to
- the jdk parameter is now just an integer
- establishes a contract for images such that a given JDK Y can be used for builds, if the environment variable `JAVA_HOME_Y_X64` exists
> [FLINK-22939][azure] Generalize JDK switch

- tools/releasing/create_release_branch.sh
- tools/releasing/update_branch_version.sh
"update_branch_version" & "create_release_branch" scripts used for releasing unintentionally break other dependency versions if the Flink version exactly matches the dependency version. 
This PR uses "versions-maven-plugin" to properly update **only** the version of the project.
- *Use versions-maven-plugin to properly update versions*
This change is a trivial fix for the release scripts without any test coverage.
How to run the scripts (optional OLD_VERSION -> default value = current version):
OLD_VERSION=1.14-SNAPSHOT NEW_VERSION=1.14 ./releasing/update_branch_version.sh
OLD_VERSION=1.14-SNAPSHOT NEW_VERSION=1.14 ./releasing/create_release_branch.sh
How to see the change actually works:
Assuming being checked out on the current master branch, try changing "maven-dependency-analyzer" …
> [FLINK-19164][release] Use versions-maven-plugin to properly update versions

- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcExactlyOnceSinkE2eTest.java
> [BP-1.13][FLINK-22889][tests] Ignore JdbcExactlyOnceSinkE2eTest temporarily

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/common/CommonPhysicalLookupJoin.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/join/LookupJoinTest.scala
Currently LookupJoin would throw exception, when there is casting on field of temporal table, this pr fixes the way of extracting lookup keys.
- *ignore casting on interoperable type when extracting lookup keys*
- *Added test that validates that only cast on interoperable type would be ignored* …
> [FLINK-22454][table-planner-blink] only ignore casting on interoperable type when extracting lookup keys

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/utils/WindowEmitStrategy.scala
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/agg/GroupWindowTest.xml
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/agg/GroupWindowTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/GroupWindowITCase.scala
The pr aims to decouple window aggregate allow lateness with state ttl configuration
1. Introduce `table.exec.emit.allow-lateness` configuration (which is also @Experimental).
2. Use the value of `table.exec.emit.allow-lateness`  as allow-lateness for window and also keep the state ttl can still take effect when the new config is not set `table.exec.emit.allow-lateness`.
3. Fix bug: enable allow-lateness for window only when late-fire emit strategy is specified
- Updates `WindowEmitStrategy`
- Add UT in `GroupWindowTest`
- Add ITCase in `GroupWindowITCase`
- …
> [FLINK-21301][table-planner-blink] Decouple window aggregate allow lateness with state ttl configuration

- tools/azure-pipelines/build-apache-repo.yml
Since the docs have been migrated to hugo we no longer need ruby.
This PR is applicable to master and release-1.13.
> [FLINK-22952][azure] Remove Ruby usage

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/LookupJoinCodeGenerator.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/agg/AggsHandlerCodeGenerator.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/agg/batch/WindowCodeGenerator.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/LookupJoinITCase.scala
Currently lookup join condition with CURRENT_DATE fails to filter records. See FLINK-22730 for details. This PR fixes this issue.
- Add per record code when generating table function collector code for lookup joins
> [FLINK-22730][table-planner-blink] Add per record code when generating table function collector code for lookup joins

- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/ParquetInputFormat.java
- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/ParquetMapInputFormat.java
- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/ParquetPojoInputFormat.java
- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/ParquetRowInputFormat.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/ParquetInputFormatTest.java
[FLINK-21389] determine parquet schema from file instead of taking it from user
deprecate ParquetInputFormat constructors that take schema as parameter and create a constructor without parquet schema as parameter. Determine the schema from the file in the constructor instead
Added ParquetInputFormatTest for low level tests.
This change can be tested by ParquetInputFormatTest#testReadWithoutParquetSchemaSpecified()
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes deprecation …
> [FLINK-21389] determine parquet schema from file instead of taking it from user

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/table/descriptors/Kafka.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/table/descriptors/KafkaTest.java
This pull resquest fixes Kafka connector. There is a cast  problem when use properties method.
```
Properties props = new Properties();
props.put( "enable.auto.commit", "false");
props.put( "fetch.max.wait.ms", "3000");
props.put("flink.poll-timeout", 5000);
props.put( "flink.partition-discovery.interval-millis", false);
kafka = new Kafka()
.version("0.11")
.topic(topic)
.properties(props);
```
```
Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
Exception in thread "main" java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
```
- *change  (String) v  ----> String.valueOf() in Kafka.java*
> [FLINK-20318][Connector/kafka]Fix cast question for properies() method in kafka ConnectorDescriptor

- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecRank.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/rank/AbstractTopNFunction.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/rank/AppendOnlyFirstNFunction.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/rank/AppendOnlyTopNFunction.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/rank/RetractableTopNFunction.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/rank/UpdatableTopNFunction.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/operators/rank/AppendOnlyFirstNFunctionTest.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/operators/rank/AppendOnlyTopNFunctionTest.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/operators/rank/RetractableTopNFunctionTest.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/operators/rank/TopNFunctionTestBase.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/operators/rank/UpdatableTopNFunctionTest.java
Rank TTL should use enableTimeToLive of state instead of timer.
We should get rid of `maxIdleStateRetention`.
See https://issues.apache.org/jira/browse/FLINK-18556
- Use guava LRU Cache in Rank functions for expire ttl.
- Use enableTimeToLive of state instead of timer
- …
> [FLINK-22957][table-runtime] Rank TTL should use enableTimeToLive of state instead of timer

- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackend.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackendBuilder.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/snapshot/RocksDBSnapshotStrategyBase.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/snapshot/RocksFullSnapshotStrategy.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/snapshot/RocksIncrementalSnapshotStrategy.java
This pull request fix resource leak in `RocksIncrementalSnapshotStrategy` caused by `RocksDBStateUploader` not being closed.
- Add `close()` function  to `RocksDBSnapshotStrategyBase`  and `RocksIncrementalSnapshotStrategy`
- Add a call to `checkpointSnapshotStrategy.close()` in `RocksDBKeyedStateBackend#dispose()`
- org/apache/flink/contrib/streaming/state/RocksIncrementalCheckpointRescalingTest.java …
> [FLINK-23003][runtime] Fix resource leak in RocksIncrementalSnapshotStrategy

- flink-connectors/flink-connector-kinesis/pom.xml
- flink-connectors/flink-connector-kinesis/src/main/resources/META-INF/NOTICE
Update AWS SDK v1 and v2 and DynamoDB Streams Kinesis adapter to latest version
Bumped:
- AWS SDK v1 from `1.11.754` to `1.12.7`
- AWS SDK v2 from `2.13.52` to `2.16.86`
- DynamoDB Streams Kinesis Adapter from `1.5.0` to `1.5.3`
This change is already covered by existing unit/integration/e2e tests for Kinesis connector. …
> [FLINK-18182][kinesis] Updating to latest AWS SDK for Kinesis connector

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/BufferManager.java
Recycle floating buffer outside the lock to avoid deadlock
- The floting buffer is not recycle in `AvailableBufferQueue::addExclusiveBuffer()`, the released floting buffer is returned, and the caller will reclaim it outside the lock
- In `BufferManager::recycle()`, if the return value of `AvailableBufferQueue::addExclusiveBuffer()` is not null, the floating buffer(return value) is recycled
- In addition to `BufferManager::recycle()`, another place to call `AvailableBufferQueue::addExclusiveBuffer()` is `BufferManager::requestExclusiveBuffers()`. There should be no floating buffer released, so simply add an assertion
- Modify comments and add additional comments
- The …
> [FLINK-22946][runtime] Recycle floating buffer outside the lock to avoid deadlock

- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/AbstractStateChangeLogger.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/KvStateChangeLoggerImpl.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/PriorityQueueStateChangeLoggerImpl.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/KvStateChangeLoggerImplTest.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/PriorityQueueStateChangeLoggerImplTest.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/StateChangeLoggerTestBase.java
Write metadata before state changes (#15200) so that they can be applied on recovery (#15420).
See also [detailed design doc](https://docs.google.com/document/d/10c6hZsOVxzUjeCLPSDpKGyZOYHi73yd92lCqRs1CyUE/edit?usp=sharing).
- Added `PriorityQueueStateChangeLoggerImplTest` and `KvStateChangeLoggerImplTest`
- (better coverage will be possible in #15420 with recovery implemented) …
> [FLINK-22808][state/changelog] Log metadata

- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/utils/SystemResourcesCounterTest.java
If the SystemResourcesCounter runs into an exception then the tests loops infinitely.
> [FLINK-20891][metrics][tests] Check that thread is still alive

- flink-connectors/flink-connector-kinesis/pom.xml
- flink-connectors/flink-connector-kinesis/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-connector-kinesis/src/main/resources/org/apache/flink/kinesis/shaded/software/amazon/awssdk/global/handlers/execution.interceptors
- pom.xml
Fixing bad shading of AWS SDK config file resulting in errors when consuming from EFO. This is cause by the recent SDK upgrade: https://github.com/apache/flink/pull/16185
- Adding a custom `execution.interceptors` file that references the shaded `HttpChecksumRequiredInterceptor`
Running Flink job locally against AWS Kinesis Data Streams.
- If yes, …
> [FLINK-18182][kinesis] Fixing bad shading of AWS SDK config file

- flink-queryable-state/flink-queryable-state-client-java/src/main/java/org/apache/flink/queryablestate/client/QueryableStateClient.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/heap/HeapKeyedStateBackend.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/ttl/TtlStateFactory.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/ttl/mock/MockKeyedStateBackend.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackend.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionKeyedStateBackend.java
Currently, TtlStateFactory can only handle fixed type of state descriptors. As ValueStateDescriptor is not a final class and user could still extend it, however, TtlStateFactory cannot recognize the extending class.
This PR targets for enabling TTL state factory to handle extended state descriptors.
`TtlStateFactory` use `StateDescriptor#Type` to check what kind of state is. …
> [FLINK-23018][state] Enable TTL state factory to handle extended state descriptors

- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/filesystem/stream/compact/CompactFileWriter.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/filesystem/stream/compact/CompactFileWriterTest.java
* This pull request is to fix the issue that CompactFileWriter won't emit EndCheckpoint with Long.MAX_VALUE checkpointId even though the inputs end. *
- *Delete method notifyCheckpointComplete and override method commitUpToCheckpoint in CompactFileWriter*
- *In method commitUpToCheckpoint fo CompactFileWriter, it call super. commitUpToCheckpoint and emit EndCheckpoint *
- The S3 file …
> [FLINK-22993][filesystem] Fix the issue that CompactFileWriter won't emit EndCheckpoint with Long.MAX_VALUE checkpointId even though the inputs end.

- tools/ci/compile.sh
- tools/ci/java-ci-tools/src/main/java/org/apache/flink/tools/ci/suffixcheck/ScalaSuffixChecker.java
- tools/ci/verify_scala_suffixes.sh
Ports most parts of the scala checker to java and fixes existing issues along the way. We now parse the module name from the dependency-plugin line, and no longer use tee.
> [FLINK-22987][ci] Fix scala suffix check

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/CreditBasedPartitionRequestClientHandler.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/CreditBasedPartitionRequestClientHandlerTest.java
This PR fixes the bug that wrongly wrap the Netty connection reset exception as `LocalTransportException`.
- 6252cb5c4d9b3adfe3dcdba7d90aa7d1dc62575f fixes the bug.
This change could be verified via the added UT.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: **no**
- Does this pull request introduce a new feature? **no**
- If yes, how is the feature documented? **not applicable**
> [FLINK-21952][network] Make all the "Connection reset by peer" exception wrapped as RemoteTransportException

- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackendBuilder.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBStateDataTransfer.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/snapshot/RocksIncrementalSnapshotStrategy.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/EmbeddedRocksDBStateBackendTest.java
fix the thread leak in RocksDBStateUploader
- name the thread group in RocksDBStateDataTransfer's ExecutorService
- add `cleanUp()` in RocksDBSnapshotStrategyBase 
- invoke` checkpointSnapshotStrategy.cleanUp()` when RocksDBKeyedStateBackend `dispose`
- add test case `testDisposeCleanUpRocksDBStateDataTransferThread`  to Detected rocksDBStateDataTransfer thread leak
This change added tests and can be verified as follows: 
`testDisposeCleanUpRocksDBStateDataTransferThread` …
> [FLINK-22886][State Backends] fix Thread leak in RocksDBStateUploader

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/PartitionRequestClientFactory.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NeverCompletingChannelFuture.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/PartitionRequestClientFactoryTest.java
In current `PartitionRequestClientFactory#createPartitionRequestClient`, `ChannelFuture#await()` is invoked, thus to build a connection to remote synchronously.
But with the doc of `io.netty.util.concurrent.Future`[1] and its implementation `io.netty.channel.DefaultChannelPromise`[2], `ChannelFuture#await()` never throws when completed with failure. I guess what Flink needs is `ChannelFuture#sync()`.
[1]  https://netty.io/4.1/api/io/netty/util/concurrent/class-use/Future.html
[2] https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/DefaultChannelPromise.java
https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/concurrent/DefaultPromise.java
- Replace `ChannelFuture#await` with `ChannelFuture#sync` in `PartitionRequestClientFactory#connect` …
> [FLINK-23030][network] PartitionRequestClientFactory#createPartitionRequestClient should throw when network failure

- flink-mesos/src/main/java/org/apache/flink/mesos/runtime/clusterframework/MesosResourceManagerActorFactoryImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/concurrent/FutureUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/concurrent/akka/AkkaFutureUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaInvocationHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaRpcService.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rpc/akka/FencedAkkaInvocationHandler.java
- flink-runtime/src/main/scala/org/apache/flink/runtime/akka/AkkaUtils.scala
- flink-runtime/src/test/java/org/apache/flink/runtime/rpc/AsyncCallsTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rpc/RpcConnectionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rpc/RpcEndpointTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rpc/akka/AkkaRpcActorTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rpc/akka/AkkaRpcServiceTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rpc/akka/TimeoutCallStackTest.java
Small preemptive refactoring so that we can later move this method into another module more easily.
> [FLINK-23060] Move FutureUtils#toJava to separate class

- docs/layouts/shortcodes/generated/checkpointing_configuration.html
- docs/layouts/shortcodes/generated/common_state_backends_section.html
- flink-core/src/main/java/org/apache/flink/configuration/CheckpointingOptions.java
- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/BootstrapTransformation.java
- flink-python/pyflink/datastream/tests/test_stream_execution_environment_completeness.py
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraphBuilder.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/tasks/JobCheckpointingSettings.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/CheckpointStorageLoader.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/StateBackendLoader.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointSettingsSerializableTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/SchedulerTestingUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendLoadingTest.java
- flink-state-backends/flink-statebackend-changelog/pom.xml
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogStateBackend.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogStateBackendLoadingTest.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateBackendFactoryTest.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamConfig.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraph.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraphGenerator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGenerator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironmentComplexConfigurationTest.java
- flink-streaming-scala/src/main/scala/org/apache/flink/streaming/api/scala/StreamExecutionEnvironment.scala
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/utils/ExecutorUtils.java
This change provides configurations as well as APIs to configure ChangelogStateBackend. Base on the discussion before (https://lists.apache.org/thread.html/ra178ce29088b1da362d98a5a6d8c7be48051caf1637ee24261738217%40%3Cdev.flink.apache.org%3E) and the design doc (https://docs.google.com/document/d/13AaCf5fczYTDHZ4G1mgYL685FqbnoEhgo0cdwuJlZmw/edit?usp=sharing, see Option 3), we make a refined version of loading ChangelogStateBackend. Please check the brief change log below.
- Define consistent override and combination policy (flag + state backend) in different config levels.
- Differentiate explicitly the meaning of "enable flag" = true/false/unset.
- Hide ChangelogStateBackend from users.
This change added some test cases in ```ChangelogStateBackendLoadingTest```. Including tests for …
> [FLINK-22678] Configurations and user APIs for ChangelogStateBackend

- flink-dist/src/main/resources/flink-conf.yaml
Add execution checkpointing related configs in flink-conf.yaml. That may cause checkpoint failure according to the current configuration.
Execution checkpointing configs such as  execution.checkpointing.interval, execution.checkpointing.externalized-checkpoint-retention, execution.checkpointing.mode, etc are added in flink-conf.yaml.
This change is a trivial rework  without any test coverage. …
> [FLINK-22974][dist] Add execution checkpointing related configs in flink-conf.yaml

- flink-core/src/main/java/org/apache/flink/core/plugin/PluginLoader.java
- flink-tests/src/test/java/org/apache/flink/test/plugin/PluginLoaderTest.java
With this PR it will be possibly to load a plugin temporarily, for example within a single test that uses a MiniCluster.
> [FLINK-23029] Extend PluginLoader to allow closing ClassLoader

- flink-connectors/flink-connector-rabbitmq/pom.xml
- flink-connectors/flink-connector-rabbitmq/src/main/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSource.java
- flink-connectors/flink-connector-rabbitmq/src/main/java/org/apache/flink/streaming/connectors/rabbitmq/common/RMQConnectionConfig.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceITCase.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceTest.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/common/RMQConnectionConfigTest.java
This is a backport of #16023 (fixing FLINK-22698) to release-1.12 (just the new IT was slightly modified as the `getRestClusterClient` method does not exist in 1.12).
Please see #16023 for a detailed description.
> [BP-1.12][FLINK-22698][connectors/rabbitmq] Add deliveryTimeout to RabbitMQ source

- flink-connectors/flink-connector-rabbitmq/pom.xml
- flink-connectors/flink-connector-rabbitmq/src/main/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSource.java
- flink-connectors/flink-connector-rabbitmq/src/main/java/org/apache/flink/streaming/connectors/rabbitmq/common/RMQConnectionConfig.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceITCase.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceTest.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/common/RMQConnectionConfigTest.java
This pull request enables setting the next message delivery timeout in the RabbitMQ queueing consumer, allowing to properly stop the job in cases when no new message is available on the queue (issue [FLINK-22698](https://issues.apache.org/jira/browse/FLINK-22698)).
Currently, the issue described FLINK-22698 causes the job to never stop (gracefully via stop command) if there is no new data. Since the current behavior (no timeout) is causing trouble, this PR introduces setting a default value of 30s. The upper bound is dictated by the default Flink `client.timeout` (60s) - RMQ connector should not be the cause of CLI timeouts. The lower bound is related to CPU utilization - if set to some really low values (such as 1ms), it could start to have a noticeable effect (redundant queue check …
> [FLINK-22698][connectors/rabbitmq] Add deliveryTimeout parameter to RabbitMQ source

- flink-runtime/src/main/java/org/apache/flink/runtime/concurrent/Executors.java
- flink-runtime/src/main/java/org/apache/flink/runtime/concurrent/akka/AkkaFutureUtils.java
The DirectExecutionContext is only used by the AkkaFutureUtils. The goal is to further split runtime&scala code.
> [FLINK-23081] Move Executors#directExecutorContext to AkkaFutureUtils

- flink-connectors/flink-connector-jdbc/pom.xml
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/XaFacadeImpl.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcExactlyOnceSinkE2eTest.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcXaFacadeImplTest.java
1. Close pooled and physical connections in `XaFacadeImpl` (tolerate close errors for MySQL)
2. Harden test by adding MySql
3. Prevent sources from waiting on cancellation
4. Prevent sources from using a latch from a different attempt
> [FLINK-22462][jdbc] Fix connection leak and stabilize JdbcExactlyOnceSinkE2eTest

- flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/BootstrapTools.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/util/MetricUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaBootstrapTools.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaRpcServiceUtils.java
- flink-runtime/src/main/scala/org/apache/flink/runtime/akka/AkkaUtils.scala
- flink-runtime/src/test/java/org/apache/flink/runtime/clusterframework/BootstrapToolsTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rpc/akka/AkkaBootstrapToolsTest.java
- flink-runtime/src/test/scala/org/apache/flink/runtime/akka/AkkaUtilsTest.scala
Splits the BootstrapTools such that it is easier to move the akka-related parts into another module in the future.
> [FLINK-23061] Split BootstrapTools 

- flink-core/src/main/java/org/apache/flink/configuration/SecurityOptions.java
- flink-core/src/test/java/org/apache/flink/configuration/SecurityOptionsTest.java
- flink-mesos/src/main/java/org/apache/flink/mesos/util/MesosArtifactServerImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/blob/BlobClient.java
- flink-runtime/src/main/java/org/apache/flink/runtime/blob/BlobServer.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/HighAvailabilityServicesUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/NettyConfig.java
- flink-runtime/src/main/java/org/apache/flink/runtime/net/SSLUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/RestClientConfiguration.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/RestServerEndpointConfiguration.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaRpcServiceUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/history/HistoryServerUtils.java
- flink-runtime/src/main/scala/org/apache/flink/runtime/akka/AkkaUtils.scala
- flink-runtime/src/test/java/org/apache/flink/runtime/net/SSLUtilsTest.java
The SSLUtils contain a few methods that check whether certain SSL options are enabled while honoring a fallback "security.ssl.enabled" option.
These are required by RPC, network and REST components.
In order to be able to move our akka rpc stuff into a separate module it is necessary to move these to flink-core.
(There's also no good reason for them to be in flink-runtime in the first place)
> [FLINK-22992][security] Move SSLUtils#is*Enabled to SecurityOptions

- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/HighAvailabilityServicesUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rpc/RpcServiceUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaRpcServiceUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rpc/akka/AkkaRpcActorTest.java
Moves some generic methods required by flink-runtime into a separate class, such that the remaining parts can be moved into a separate flink-rpc-akka module in the future.
> [FLINK-23082] Split AkkaRpcServiceUtils

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/KubernetesClusterDescriptor.java
- flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/ClusterEntrypoint.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/HighAvailabilityServicesUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rpc/AddressResolution.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaRpcServiceUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerRunner.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/HighAvailabilityServicesUtilsTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderRetrievalTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskManagerRunnerConfigurationTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/util/AddressResolutionTest.java
- flink-runtime/src/test/scala/org/apache/flink/runtime/akka/AkkaUtilsTest.scala
- flink-tests/src/test/java/org/apache/flink/test/recovery/ProcessFailureCancelingITCase.java
With this PR the `AddressResolution` is a top-level class. The class is required by both the runtime for HA and by our akka code when creating RPC services.
This class will eventually be moved to flink-rpc-core, where it will be accessible to both flink-rpc-akka and flink-runtime.
> [FLINK-23087] Make AddressResolution a top-level class

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/BufferedUpsertSinkFunction.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/BufferedUpsertSinkFunctionTest.java
*Fix upsert-kafka produce duplicates when enable object reuse.*
- *Add tests in `BufferedUpsertSinkFunctionTest` to verify the results  if enable object reuse.* …
> [FLINK-23025][upsert-kafka] Fix upsert-kafka produce duplicates when enable object reuse

- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/SchedulerBenchmarkUtils.java
*In FLINK-22988, TestUtils are ported from Scala to Java. However, SchedulerBenchmarkBase in flink-benchmark calls this method when each benchmark teardowns. This make SchedulerBenchmarks not compiling, as FLINK-23078 says. To solve this issue, we'd like to wrap `TestingUtils.defaultExecutor().shutdownNow()` into `SchedulerBenchmarkUtil`. If this method is changed in the future, its reference must be fixed, too.*
- *Wrap `TestingUtils.defaultExecutor().shutdownNow()` into `SchedulerBenchmarkUtil`.*
This change only wraps the existing method. It needs no test case.
- The runtime …
> [FLINK-23078][benchmark] Add SchedulerBenchmarkUtils#shutdownTestingUtilDefaultExecutor

- flink-python/pyflink/fn_execution/coder_impl_fast.pyx
- flink-python/pyflink/fn_execution/operations.py
- flink-python/pyflink/table/tests/test_row_based_operation.py
*This pull request will fix the issue that the InternalRow as arguments in Python UDAF*
- *Fix the issue that the InternalRow as arguments in Python UDAF*
- *Change the original IT `test_flat_aggregate_list_view` to cover this patch* …
> [FLINK-23121][python] Fix the issue that the InternalRow as arguments in Python UDAF

- flink-dist/src/main/flink-bin/bin/flink-console.sh
Add variable expansion for FLINK_ENV_JAVA_OPTS in flink-console.sh similar to flink-daemon.sh, to make env.java.opts like "-Xlog:gc*:file=${FLINK_LOG_PREFIX}.gc.log" work properly in native kubernetes application mode.
- add `FLINK_ENV_JAVA_OPTS=$(eval echo ${FLINK_ENV_JAVA_OPTS})` before starting the JVM. …
> [FLINK-23057] add variable expansion for FLINK_ENV_JAVA_OPTS in flink-console.sh

- flink-runtime/src/main/java/org/apache/flink/runtime/rest/RestServerEndpoint.java
Replaces a netty 3 reference with our flink-shaded-netty version. This currently works on master because it uses the netty version provided by akka.
> [FLINK-23130][rest] Remove netty 3 reference

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/KafkaSourceEnumerator.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/subscriber/KafkaSubscriber.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/subscriber/KafkaSubscriberUtils.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/subscriber/PartitionSetSubscriber.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/subscriber/TopicListSubscriber.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/subscriber/TopicPatternSubscriber.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/enumerator/KafkaEnumeratorTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/enumerator/subscriber/KafkaSubscriberTest.java
- flink-core/src/test/java/org/apache/flink/api/connector/source/mocks/MockSplitEnumeratorContext.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorTest.java
- This pull request refactors the logic of partition discovery in ```KafkaSourceEnumerator```, and changes the interface ```KafkaSubscriber``` to separate topic description fetching and discover partition changes into two methods. 
- Rework the logic of partition discovery. Currently the flow of partition discovery is:
1. The worker thread fetches descriptions of subscribed topics/partitions, then hands over to coordinator thread
2. The coordinator thread filters out already discovered partitions (pending + assigned partitions), then invokes worker thread with callAsync to fetch offsets for new partitions 
3. The worker thread fetches offsets and creates splits for new partitions, then hands over new splits to coordinator thread
4. The coordinator thread marks these splits as pending and …
> [FLINK-22147][connector/kafka] Refactor partition discovery logic in Kafka source enumerator

- docs/content.zh/docs/dev/table/sql/alter.md
- docs/content.zh/docs/dev/table/sql/create.md
- docs/content.zh/docs/dev/table/sql/drop.md
- docs/content.zh/docs/dev/table/sql/use.md
- docs/content/docs/dev/table/sql/drop.md
- docs/content/docs/dev/table/sql/use.md
Improve documentation for pages of SQL. 
Correct wrong style in https://ci.apache.org/projects/flink/flink-docs-master/zh/docs/dev/table/sql/create/#create-function   section.
Correct wrong style in https://ci.apache.org/projects/flink/flink-docs-master/zh/docs/dev/table/sql/drop/#drop-function section.
Correct wrong style in https://ci.apache.org/projects/flink/flink-docs-master/zh/docs/dev/table/sql/alter/#alter-function section.
Add the description about drop catalog in the page of  https://ci.apache.org/projects/flink/flink-docs-master/docs/dev/table/sql/drop/ .
Correct 'catloag' of  https://ci.apache.org/projects/flink/flink-docs-master/zh/docs/dev/table/sql/use/#use-catloag
*A pure documentation work.*
Correct wrong style in …
> [FLINK-23028][docs] Improve documentation for pages of SQL.

- docs/content/docs/dev/table/concepts/versioned_tables.md
Fix the  Script of [Creating Versioned View Script](https://ci.apache.org/projects/flink/flink-docs-release-1.13/docs/dev/table/concepts/versioned_tables/#versioned-table-views)
* add "," to Line 3  to correctly pass the semantic check  
rate          DECIMAL(32, 10), …
> [FLINK-23157][docs] Versioned View's SQL Script was missing a "," at Line 3 which yields Could not execute SQL statement ERROR

- flink-runtime/src/test/java/org/apache/flink/runtime/util/RunnablesTest.java
Backport of #16261 to `release-1.13`.
> [BP-1.13][FLINK-23045][tests] Harden RunnablesTest by not relying on timeout 

- flink-runtime/src/test/java/org/apache/flink/runtime/util/RunnablesTest.java
Backport of #16261 to `release-1.12`.
> [BP-1.12][FLINK-23045][tests] Harden RunnablesTest by not relying on timeout 

- flink-end-to-end-tests/flink-streaming-kinesis-test/src/test/java/org/apache/flink/streaming/kinesis/test/KinesisTableApiITCase.java
- flink-end-to-end-tests/flink-streaming-kinesis-test/src/test/java/org/apache/flink/streaming/kinesis/test/model/Order.java
> [FLINK-22492][test] Use order-agnostic check in KinesisTableApiITCase. [1.13]

- docs/content.zh/docs/dev/table/concepts/time_attributes.md
- docs/content/docs/dev/table/concepts/time_attributes.md
* Create table uses time_ltz in the column name and it's expression which results in exception
* Create table uses time_ltz in the column name and it's expression which results in exception …
> [FLINK-23162][docs] Updated column expression which throws exception

- docs/data/sql_functions.yml
fix the incorrect description for `to_timestamp` udf.
- update document
This change is just doc update.
> [FLINK-22970][docs] The documentation for `TO_TIMESTAMP` UDF has an incorrect description

- flink-connectors/flink-connector-kinesis/pom.xml
- flink-connectors/flink-sql-connector-kinesis/pom.xml
- flink-connectors/flink-sql-connector-kinesis/src/main/resources/META-INF/NOTICE
Upgrade Guava dependency for Flink Connector Kinesis. The connector was using Guava 18.0 which is quite old and has been flagged by some security tools as noted in another ticket https://issues.apache.org/jira/browse/FLINK-22774 
This PR also makes the flink-sql-connector-kinesis use the Guava dependency transitively through the flink-connector-kinesis dependency.
- Bumped Guava for Flink Connector Kinesis from 18.0 (inherited from parent) to 29.0-jre
This change is already covered by existing tests, such as `FlinkKinesisProducerTest`. …
> [FLINK-23009][kinesis] Upgrade Guava for Flink Connector Kinesis

- flink-connectors/flink-sql-connector-kinesis/pom.xml
- flink-connectors/flink-sql-connector-kinesis/src/main/resources/META-INF/NOTICE
The `guava:failureaccess` dependency wasn't included in the flink-sql-connector-kinesis jar and this caused an e2e test failure in release branch 1.13. The other release branch is fixed in PR #16297. Applying the same changes here. This branch does not have the same e2e test, we should need to add a similar test covering the same path here too (not done in this PR).
- Include guava:failureaccess in sql-connector-kinesis pom
- Update NOTICE file …
> [FLINK-23009][kinesis] Include guava failureaccess in jar

- docs/content.zh/docs/deployment/cli.md
- docs/content/docs/deployment/cli.md
`-D` was not mentioned in the docs separately.
> [hotfix][docs] Mention -D argument for CLI

- tools/azure-pipelines/build-nightly-dist.yml
The deployment was timing out or failing a lot recently.
> [FLINK-23052][ci] Improve stability of maven snapshot deployment

- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/SchedulerBenchmarkBase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/SchedulerBenchmarkUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/deploying/DeployingDownstreamTasksInBatchJobBenchmark.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/deploying/DeployingTasksBenchmarkBase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/deploying/DeployingTasksInStreamingJobBenchmark.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/deploying/DeployingTasksInStreamingJobBenchmarkTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/e2e/CreateSchedulerBenchmark.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/e2e/SchedulerEndToEndBenchmarkBase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/e2e/SchedulingAndDeployingBenchmark.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/failover/FailoverBenchmarkBase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/failover/RegionToRestartInBatchJobBenchmark.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/failover/RegionToRestartInBatchJobBenchmarkTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/failover/RegionToRestartInStreamingJobBenchmark.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/failover/RegionToRestartInStreamingJobBenchmarkTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/partitionrelease/PartitionReleaseInBatchJobBenchmark.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/partitionrelease/PartitionReleaseInBatchJobBenchmarkTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/scheduling/InitSchedulingStrategyBenchmark.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/scheduling/InitSchedulingStrategyBenchmarkTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/scheduling/SchedulingBenchmarkBase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/scheduling/SchedulingDownstreamTasksInBatchJobBenchmark.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/scheduling/SchedulingDownstreamTasksInBatchJobBenchmarkTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/topology/BuildExecutionGraphBenchmark.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/topology/BuildExecutionGraphBenchmarkTest.java
*In FLINK-22988, TestUtils are ported from Scala to Java. However, SchedulerBenchmarkBase in flink-benchmark calls this method when each benchmark teardowns. This make SchedulerBenchmarks not compiling, as FLINK-23078 says. In #16250, we proposed to wrap `TestingUtils.defaultExecutor().shutdownNow()` into SchedulerBenchmarkUtil. In the discussion at https://github.com/apache/flink-benchmarks/pull/17, we decide to add a method called `teardown()` for each scheduler benchmark, and shutdown the executor in the `teardown()` method.*
- *Make all scheduler benchmarks inherit a base class called `SchedulerBenchmarkBase`*
- *Add `setup` method to `SchedulerBenchmarkBase` to setup the default executor*
- *Add `teardown` method to `SchedulerBenchmarkBase` to shutdown the default executor*
- *Add …
> [FLINK-23078][benchmark] Add SchedulerBenchmarkBase#teardown

- flink-python/src/main/java/org/apache/flink/client/python/PythonEnvUtils.java
- flink-python/src/main/java/org/apache/flink/python/util/ZipUtils.java
- flink-python/src/test/java/org/apache/flink/python/util/ZipUtilsTest.java
* This pull request fixes ZipUtils to handle properly for softlinks*
- *Fix ZipUtils*
- *Added test cases ZipUtilsTest*
- *Added tests ZipUtilsTest*
> [FLINK-23166][python] Fix ZipUtils to handle properly for softlinks

- docs/content.zh/docs/connectors/table/overview.md
- docs/content/docs/connectors/table/overview.md
*Fixed typos*
*Fixed typos*
*Fixed typos*
> [Hotfix][docs] Fixed typos.

- flink-connectors/flink-connector-base/pom.xml
> [FLINK-22964][connector/common] Exclude flink-core from connector-common dependencies. [1.13]

- flink-connectors/flink-connector-base/pom.xml
> [FLINK-22964][connector/common] Exclude flink-core from connector-common dependencies. [1.12]

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliStrings.java
- flink-table/flink-sql-client/src/test/resources/sql-client-help-command.out
- flink-table/flink-sql-client/src/test/resources/sql/misc.q
*SQL client shows the `SOURCE` command in `HELP`, but the `SOURCE` command doesn't exist. The prompting message for `SOURCE` command should be removed from `HELP`.*
- *`MESSAGE_HELP` remove the prompting message for `SOURCE` command.*
- *The expected output of `HELP` execution in `misc.q` removes the prompting message for `SOURCE` command.*
- …
> [FLINK-23017][sql-client] HELP in sql-client still shows the removed SOURCE functionality

- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/slotpool/SlotPoolImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultScheduler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ExecutionGraphRestartTest.java
This PR clear the pending requests in ExecutionSlotAllocator when a job is CANCELING or FAILING to avoid StackOverflowException when a large scale job is canceling or failing.
The pending requests in ExecutionSlotAllocator are not cleared when a job transitions to CANCELING or FAILING, while all vertices will be canceled and assigned slot will be returned. The returned slot is possible to be used to fulfill the pending request of a CANCELED vertex and the assignment will fail immediately and the slot will be returned and used to fulfilled another vertex in a recursive way. StackOverflow can happen in this way when there are many vertices, and fatal error can happen and lead to JM will crash.
We also tried to improve the call stack of slot assignment, but found it too complex to maintain …
> [FLINK-22945][runtime] Avoid StackOverflowException when a large scale job is canceling or failing

- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/rank/UpdatableTopNFunction.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/operators/rank/UpdatableTopNFunctionTest.java
See UpdatableTopNFunctionTest.testSortKeyChangesWhenOutputRankNumber 
```
expectedOutput.add(updateBeforeRecord("book", 3L, 16, 1L));
expectedOutput.add(updateAfterRecord("book", 2L, 11, 1L));
expectedOutput.add(updateBeforeRecord("book", 2L, 19, 2L));
expectedOutput.add(updateAfterRecord("book", 3L, 16, 2L));
It should collect the third record and then collect the second record.
```
This wrong order will lead to the wrong implementation of the downstream, because the records expected by the downstream has unique key, but the disorder here will lead to the data being deleted by mistake.
- Fix `UpdatableTopNFunction`, retract old row before collect new row.
`UpdatableTopNFunctionTest.testSortKeyChangesWhenOutputRankNumber ` …
> [FLINK-23142][table] UpdatableTopNFunction output wrong order in the same unique key

- docs/content.zh/docs/dev/table/tableApi.md
- docs/content/docs/dev/table/tableApi.md
Correct document syntax errors
Correct document syntax errors
- Does this pull request introduce a new feature?no
Now it is：
Should be：
> [FLINK-23200][docs] Correct document syntax errors

- flink-tests/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterITCase.java
Migrates the test to the MiniClusterResource, which automatically sets the rest bind port to 0.
> [FLINK-23196][tests] use MiniClusterResource

- docs/content.zh/docs/ops/metrics.md
- docs/content/docs/ops/metrics.md
Add document of latency tracking metrics for state accesses.
Add document of latency tracking metrics for state accesses.
> [FLINK-22528][docs] Document latency tracking metrics for state accesses

- docs/content/docs/connectors/datastream/kafka.md
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSource.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSourceOptions.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/metrics/KafkaSourceReaderMetrics.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReader.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReader.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/metrics/KafkaSourceReaderMetricsTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReaderTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReaderTest.java
- flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testutils/source/reader/TestingReaderContext.java
- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/metrics/testutils/MetricListener.java
- flink-test-utils-parent/flink-test-utils/src/test/java/org/apache/flink/metric/testutils/MetricListenerTest.java
This pull request adds offset metrics for Kafka source reader, and register metrics of Kafka consumer in Flink metric group
- Add ```KafkaSourceReaderMetrics``` for tracking metrics reported in KafkaSourceReader
- Register current consuming offset and committed offset metric
- Register KafkaConsumer's metrics in operator metric group
- Add a KafkaSourceOption to configure whether to register KafkaConsumer metrics
- Added unit test for the new ```KafkaSourceReaderMetrics```
- Added integration test for KafkaSourceReader to verify new metrics are reported correctly
- …
> [FLINK-22766][connector/kafka] Report offsets and Kafka consumer metrics in Flink metric group

- docs/content.zh/docs/concepts/flink-architecture.md
Fixed some mismatches in the translation pages.
// 1
JVM（`LocalEnvironment``）  should be   JVM（`LocalEnvironment`）
// 2
[``ExecutionEnvironment``]({{ site.javadocs_baseurl }}/api/java/)  should be   `ExecutionEnvironment`
> [FLINK-23225][doc-zh]Fixed some mismatches in the translation pages

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
We should close the channelIOExecutor which is used purely for restoring inputgates state from UC once we finish restoring. It will get rid off a dangling unnecessary thread pool during processing.
- Does this …
> [FLINK-23095][runtime] Close the channel unspilling thread pool after restore

- docs/content.zh/docs/libs/gelly/overview.md
- docs/content/docs/libs/gelly/overview.md
Fix the link for Page "docs/libs/gelly/overview"'
> [FLINK-23260][docs] Fix the link for Page "docs/libs/gelly/overview"

- flink-connectors/flink-connector-rabbitmq/src/main/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSource.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceTest.java
This pull request fixes a potential connection leak in RMQSource (issue FLINK-23182). Currently the RabbitMQ connection is not closed properly in the RMQSource connector in case of failures. This leads to a connection leak (we loose handles to still opened connections) that will last until the Flink TaskManager is either stopped or crashes.
- `Connection#close` is called in `RMQSource#open` in case of a failure
- All resources are closed properly in `RMQSource#close`, and in case there are multiple exceptions caught they are suppressed accordingly
- `RMQSourceTest#testResourceCleanupOnOpenFailure`, which tests whether the allocated resources all closed properly in case of a failure during initialization (in `RMQSource#open`)
- …
> [FLINK-23182][connectors/rabbitmq] Fix connection leak in RMQSource

- flink-connectors/flink-connector-rabbitmq/src/main/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSource.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceTest.java
This is a backport of #16333 (fixing FLINK-23182) to release-1.13. The fix is exactly the same as in #16333, just the unit tests had to be slightly adjusted. There is no `assertThrows` in junit 4.12, so an ExpectedException junit rule have been used instead (the logic remained the same though). 
Please see #16333 for a detailed description.
> [BP-1.13][FLINK-23182][connectors/rabbitmq] Fix connection leak in RMQSource

- flink-connectors/flink-connector-rabbitmq/src/main/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSource.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceTest.java
This is a backport of #16333 (fixing FLINK-23182) to release-1.12. The fix is exactly the same as in #16333, just the unit tests had to be slightly adjusted. There is no `assertThrows` in junit 4.12, so an ExpectedException junit rule have been used instead (the logic remained the same though).
Please see #16333 for a detailed description.
> [BP-1.12][FLINK-23182][connectors/rabbitmq] Fix connection leak in RMQSource

- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/ScalarOperatorsTest.scala
Currently code generation of unary plus and minus will not cast the result term to its desired type. This will cause compile error if the desired type is `short` or `byte`. Consider the following java code.
```java
short a = 1;
short b = -a;
```
This code will not compile as `-a` is of `int` type.
This PR fixes this issue by casting the result term.
- Fix compile error in code generation of unary plus and minus …
> [FLINK-23184][table-runtime] Fix compile error in code generation of unary plus and minus

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/expressions/ScalarOperatorsTest.scala
(This commit is cherry-picked from #16406)
Currently code generation of unary plus and minus will not cast the result term to its desired type. This will cause compile error if the desired type is `short` or `byte`. Consider the following java code.
```java
short a = 1;
short b = -a;
```
This code will not compile as `-a` is of `int` type.
This PR fixes this issue by casting the result term.
- Fix compile error in code generation of unary plus and minus …
> [FLINK-23184][table-runtime-blink] Fix compile error in code generation of unary plus and minus

- docs/layouts/shortcodes/generated/checkpointing_configuration.html
- docs/layouts/shortcodes/generated/common_state_backends_section.html
- flink-core/src/main/java/org/apache/flink/configuration/CheckpointingOptions.java
- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/runtime/SavepointTaskStateManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/TaskExecutorStateChangelogStoragesManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/TaskStateManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/TaskStateManagerImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/StateChangelogStorageFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/StateChangelogStorageLoader.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/inmemory/InMemoryStateChangelogStorageFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerRunner.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerServices.java
- flink-runtime/src/main/resources/META-INF/services/org.apache.flink.runtime.state.changelog.StateChangelogStorageFactory
- flink-runtime/src/test/java/org/apache/flink/runtime/state/TaskExecutorStateChangelogStoragesManagerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/TaskStateManagerImplTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/TestTaskStateManager.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/changelog/inmemory/StateChangelogStorageLoaderTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskManagerServicesBuilder.java
- flink-runtime/src/test/java/org/apache/flink/runtime/util/JvmExitOnFatalErrorTest.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogStateBackend.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/StateInitializationContextImplTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/StreamTaskStateInitializerImplTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/LocalStateForwardingTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
This pull request creates the storage for changelog state backend during task initialization. The changelog state backend will use the storage to create changelog reader and writer.
For more details, check [the doc](https://docs.google.com/document/d/10c6hZsOVxzUjeCLPSDpKGyZOYHi73yd92lCqRs1CyUE/edit?disco=AAAAMNoM4Cc)
- Add ```StateChangelogStorageFactory```, use ```PluginManager``` and ```ServiceLoader``` to load it.
- Add ```StateChangelogStorageLoader```. It loads all ```StateChangelogStorageFactory``` and create ```StateChangelogStorage``` based on configuration.
- Add ```StateChangelogStorage``` instance in ```JobTable.JobServices```
- Added tests in ```StateChangelogStorageLoaderTest``` for ```StateChangelogStorageFactory``` …
> [FLINK-21804][state/changelog] Create and wire changelog storage with state backend

- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java
```
Changelog backend creates delegating functions on recovery
so that user can later provide function code.
Some branches do not register delegates currently,
this change fixes it.
```
Existing tests with changelog enabled (e.g. ``testGroupWindowWithoutKeyInProjection` in org.apache.flink.table.planner.runtime.stream.table.GroupWindowTableAggregateITCase` - ) …
> [FLINK-23276][state/changelog] Fix missing delegation in getPartitionedState

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/StreamSourceContexts.java
* Remove unnecessary calls to `checkNotClosed`
* Make the `checkNotClosed` private to enable inlining
> [FLINK-23308] Optimize checks if SourceContext is closed

- flink-runtime/src/main/java/org/apache/flink/runtime/state/ttl/TtlStateFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/ttl/TtlValue.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/AbstractStateChangeLogger.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/KvStateChangeLoggerImpl.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/PriorityQueueStateChangeLoggerImpl.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/restore/ChangelogBackendLogApplier.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/KvStateChangeLoggerImplTest.java
```
Upon recovery, changelog backend creates underlying states to apply changes.
TTL config is not available at that moment, so states are currently created
regardless of job TTL settings.
This change stores TTL config along with metadata (in changelog); and
uses it on recovery.
Note: values are already serialized as TTL values and serializers as TTL seralizers
Note: upgrading TTL settings is not possible (see FLINK-23143)
```
Existing table-planner tests with changelog enabled, e.g. `testGroupAggregate` in `org.apache.flink.table.planner.runtime.stream.table.AggregateITCase`. …
> [FLINK-23277][state/changelog] Store and recover TTL metadata using changelog

- flink-formats/flink-avro-confluent-registry/src/test/java/org/apache/flink/formats/avro/registry/confluent/RegistryAvroRowDataSeDeSchemaTest.java
- flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroDeserializationSchema.java
- flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroRowDataDeserializationSchema.java
- flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/RegistryAvroDeserializationSchema.java
- flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroDeserializationSchemaTest.java
- flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroRowDataDeSerializationSchemaTest.java
- flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/CsvRowDataDeserializationSchema.java
- flink-formats/flink-csv/src/test/java/org/apache/flink/formats/csv/CsvRowDataSerDeSchemaTest.java
- flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonRowDataDeserializationSchema.java
- flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/canal/CanalJsonDeserializationSchema.java
- flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/JsonRowDataSerDeSchemaTest.java
- flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/canal/CanalJsonSerDeSchemaTest.java
This pull request aims to fix JIRA issue FLINK-20321.
Make deserialize(byte[]) method of following classes return null when argument is null, instead of throwing NPE. Test cases added.
1. AvroDeserializationSchema
2. AvroRowDataDeserializationSchema
3. RegistryAvroDeserializationSchema
4. CsvRowDataDeserializationSchema
5. JsonRowDataDeserializationSchema
This change added tests and can be verified via test cases.
- The public API, i.e., is any changed class annotated with @Public(Evolving): no …
> [FLINK-20321][formats] Fix NPE when using AvroDeserializationSchema to deserialize null input  in  1.12 version

- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java
The JobMasterTest.testMultipleStartsWork fails because we don't wait for the JobMaster
to finish its suspension before restarting the JobMaster. This can lead to ignoring the
underlying control START control message. This again can lead to a situation where we are
in the STOPPED state and try to send UnfencedMessage(startJobExecution) in JobMaster.start.
This commit fixes this problem by waiting on the suspension future to complete before restarting
the JobMaster.
> [FLINK-23164][tests] Harden JobMasterTest.testMultipleStartsWork

- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java
Backport of #16442 to `release-1.11`.
> [BP-1.11][FLINK-23164][tests] Harden JobMasterTest.testMultipleStartsWork

- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
The test DispatcherTest.testWaitingForJobMasterLeadership is unstable because it uses a
10 ms timeout to decide whether the JobMasterService has been created or not. On our CI
infrastructure this 10 ms can be too short to complete the future with JobStatus.INITIALIZING
which indicates that the JobMasterService has not been created. This commit hardens the
test by increasing the timeout to 200 ms and to increase the number of retries from 5 to 50.
> [FLINK-23076][tests] Harden DispatcherTest.testWaitingForJobMasterLeadership

- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CalcITCase.scala
This PR fixes FLINK-23290. When filter is a function call which returns null values, `NullPointerException` might happen.
- Fix `NullPointerException` when filter is a function call which returns null values
- The runtime per-record code paths (performance sensitive): **yes**
> [FLINK-23290][table-runtime] Fix NullPointerException when filter contains casting to boolean

- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/TestSink.java
- flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/SinkITCase.java
In the current test case, it is assumed that final cp will not happen, but this is not the case. This causes the current `TestSink` sometimes to commit "end of input", which will also cause `writerAndCommitterAndGlobalCommitterExecuteInStreamingMode`/`writerAndGlobalCommitterExecuteInStreamingMode` to occasionally fail. Since final cp is not deterministic, this change will filter out the string "end of input" committed by `GlobalCommitter`. In the future, after final cp ready, the verification will be restored.
This change is already covered by existing tests, such as *SinkITCase*. …
> [FLINK-23235][connector] Fix SinkITCase instability

- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/CalcCodeGenerator.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/CodeGeneratorContext.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/ExprCodeGenerator.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/agg/AggsHandlerCodeGenerator.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/agg/batch/HashAggCodeGenHelper.scala
This is the final step of FLINK-23007. This parent issue aims to solve the issue in one shot, that some methods of the generated Java code may grow beyond 64KB and reaches the limit of JVM.
In this final step we clean up and remove the old code split implementation.
- Remove the old code split implementation
This change is already covered by existing tests, such as `CodeSplitITCase`. …
> [FLINK-23150][table-planner] Remove the old code split implementation

- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/runtime/SavepointTaskStateManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/StateAssignmentOperation.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/TaskStateAssignment.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/TaskStateSnapshot.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/TaskStateManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/TaskStateManagerImpl.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/StateAssignmentOperationTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/TaskStateManagerImplTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/TestTaskStateManager.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/OperatorChain.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/StreamOperatorChainingTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/StreamSourceOperatorLatencyMetricsTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskExecutionDecorationTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorTest.java
For checkpoints after tasks finished, if some operators are fully finished, it would store a special state content in the checkpoint metadata. After recovery, the flag of whether the operator is fully finished should be passed to the task side so that these operator could skip execution (which would be implemented in the next PR).
- 213102836a80edeb968a37566f174b501de36028 passes the flag to the task.
This change added tests and can be verified via added ut. …
> [FLINK-21088][runtime][checkpoint] Pass the flag about whether a task is finished on restore on recovery

- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/slotpool/DeclarativeSlotPoolBridge.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/slotpool/DeclarativeSlotPoolService.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/DeclarativeSlotManager.java
Log why job requirements can't be fulfilled (how many TMs and slots are alive). Motivated by debugging test failures.
This is more of a proposal.
Sample log messages are shown below (using minicluster and failing one task -> TM).
```
2021-07-12 03:19:58,603 WARN Could not fulfill resource requirements of job 6cd8e69cfbb5ec959bac512dedce65f5. Free slots: 0 [DeclarativeSlotManager flink-akka.actor.default-dispatcher-2]
```
```
2021-07-12 03:19:58,617 INFO Source: Custom Source -> Map -> Sink: Unnamed (1/4) (a2c20aa32818dcfacb518af9c47afe76) switched from SCHEDULED to FAILED on [unassigned resource]. [ExecutionGraph flink-akka.actor.default-dispatcher-2]
java.util.concurrent.CompletionException: org.apache.flink.runtime.jobmanager.scheduler.NoResourceAvailableException: Could not acquire the …
```
> [hotfix][runtime] Log slot pool status if unable to fulfill job requirements

- docs/content.zh/docs/dev/datastream/operators/overview.md
- docs/content/docs/dev/datastream/operators/overview.md
* The datastream operators overview document refers to DataStreamStream which perhaps should be DataStream.
* The document refers to DataStreamStream but should refer to DataStream.
> [FLINK-23347][docs][datatream][operators] - Updated windowAll description

- tools/azure-pipelines/jobs-template.yml
The "e2e" builder in Azure pipelines builds Flink again on top of what the "compile" builder is already doing. This unnecessary duplicates a couple of checks that are enough to execute once and can be skipped via providing `-Dfast` (and `-Pskip-webui-build` as suggested by the review comments).
On my local machine with 32GB RAM, 8 physical cores and a fast NVMe SSD, the difference is pretty big:
```
time mvn clean install -Dscala-2.12 -DskipTests -pl flink-dist -am
time mvn clean install -Dscala-2.12 -DskipTests -Dfast -pl flink-dist -am
```
I looked at a couple of Azure Pipeline runs and it seems like this for the "Build Flink" task in the "e2e_ci" builder:
- without this PR: 29-33 min
- with `-Dfast`: 20-25 min
- with `-Dfast` and `-Pskip-webui-build`: 16-20min
- use `-Dfast` and …
> [FLINK-23312][ci] speed up compilation for e2e tests

- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/slotpool/DeclarativeSlotPoolBridge.java
A trivial change to avoid potential excessive logging in `DeclarativeSlotPoolBridge`.
> [hotfix] Avoid excessive logging in DeclarativeSlotPoolBridge

- flink-table/flink-table-code-splitter/src/main/antlr4/JavaLexer.g4
- flink-table/flink-table-code-splitter/src/main/antlr4/JavaParser.g4
- flink-table/flink-table-code-splitter/src/test/java/org/apache/flink/table/codesplit/JavaParserTest.java
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CodeSplitITCase.scala
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/generated/GeneratedCollectorWrapper.java
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/generated/GeneratedFunctionWrapper.java
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/generated/GeneratedResultFutureWrapper.java
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/aggregate/window/SlicingWindowAggOperatorTest.java
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/window/WindowOperatorTest.java
(When merging this PR, please keep the two commits separated.)
Currently due to the logic of code splitter, logs are full of errors like
```
2021-07-12T20:44:24.0059271Z line 221:17 missing ';' at '('
2021-07-12T20:44:24.0063922Z line 221:59 mismatched input ',' expecting ')'
2021-07-12T20:44:24.0070238Z line 221:80 mismatched input ',' expecting ';'
2021-07-12T20:44:24.0076791Z line 223:69 mismatched input ',' expecting ';'
2021-07-12T20:44:24.0079044Z line 224:33 mismatched input ',' expecting ';'
2021-07-12T20:44:24.0081798Z line 225:65 mismatched input ',' expecting ';'
2021-07-12T20:44:24.0088060Z line 226:16 mismatched input ',' expecting ';'
2021-07-12T20:44:24.0089917Z line 227:76 extraneous input ')' expecting ';'
2021-07-12T20:44:24.0792855Z line 385:17 missing ';' at '('
``` …
> [FLINK-23374][table-code-splitter] Clean up logs produced by code splitter

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/OperatorChain.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceOperatorStreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamOperatorWrapper.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTaskFinishedOnRestoreSourceInput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorImpl.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/LifeCycleMonitor.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/MultipleInputStreamTaskChainedSourcesCheckpointingTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/MultipleInputStreamTaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceOperatorStreamTaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskFinalCheckpointsTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskMailboxTestHarnessBuilder.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
This PR skips the execution for the operator subtasks that have fully finished when restarting. In detail:
1. For non-source operators, it would not call its lifecycle method like `open()/close()`, and it would not process any elements (since all its precedent tasks should have finished).
2. For sources, it would directly emit END_OF_INPUT on startup. The lifecycle of the corresponding operator would also be skipped.
3. The closed operator would not participate in any checkpoint related operations. 
- 90d12962dd8cd19577f6f056160be1e1fa7d1e58 skips the execution and checkpoints for all the operators.
- 44846ba69df46ec374ac9e9295ce923e9dec88f1 marks legacy source as finished on startup if needed.
- f7e049cbbaeb778948ef23deb4bec490c9d4bb27 marks new source as finished on startup if needed. …
> [FLINK-21089] Skip the execution of the fully finished operators after recovery

- docs/content.zh/docs/connectors/table/hbase.md
- docs/content/docs/connectors/table/hbase.md
code:flink-connectors/flink-connector-hbase-base/src/main/java/org/apache/flink/connector/hbase/options/HBaseOptions.java#L103
docment: https://github.com/apache/flink/blob/master/docs/content/docs/connectors/table/hbase.md#lookupcachemax-rows
The type of configuration `lookup.cache.max-rows` should be Long instead of Integer and the defaule value is wrong also.
Document and code are inconsistent. …
> [FLINK-22843][docs-zh]Document and code are inconsistent.

- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyGroupedPriorityQueue.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogMapState.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/StateChangeLoggingIterator.java
Ensure InternalPriorityQueue#iterator could be closed for changelog state-backend
Make `StateChangeLoggingIterator.java` as `CloseableIterator`.
This change is already covered by existing tests, such as `ChangelogDelegateEmbeddedRocksDBStateBackendTest#testKeyGroupedInternalPriorityQueue `
> [FLINK-23367][state] Ensure InternalPriorityQueue#iterator could be closed for changelog state-backend

- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/util/MetricUtils.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/MultipleInputStreamTaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/OneInputStreamTaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTaskTestBase.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTestHarness.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/TwoInputStreamTaskTest.java
Hides some constructor usages in tests.
> [FLINK-21771][metrics][tests] Replace StreamTaskTestHarness#TestTaskMetricGroup

- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/OperatorIOMetricGroup.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/OperatorMetricGroup.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperatorV2.java
Removes OperatorMetricGroup#parent() to prevent runtime code from relying on the group parent having a specific type.
Instead it now directly exposes the TaskIOMG, and the JobMG as a plain `MetricGroup`.
Later on we can remove the OperatorMG-internal reliance on the `parent` by explicitly passing in these objects.
> [FLINK-21766][metrics] Remove OperatorMetricGroup#parent()

- flink-core/src/main/java/org/apache/flink/api/common/typeinfo/Types.java
- flink-core/src/test/java/org/apache/flink/api/java/typeutils/runtime/PojoSerializerTest.java
- flink-core/src/test/java/org/apache/flink/api/java/typeutils/runtime/PojoSerializerUpgradeTestSpecifications.java
While working with the PojoSerializer a bit more, I noticed a couple of minor things that are off in the current tests:
- the test Pojo does not take dumm5 into account for hashCode and equals
- error messages are not so nice (and mix up the order of expected and actual values)
- hotfix typo in error message inside `Types.java`
- fix `PojoSerializerTest` user POJO not taking `dumm5` into account for `hashCode` and `equals`
- nicer error messages in `PojoSerializerTest` via hamcrest
- fix wrong parameter order in `assertSame()`
This change is a trivial rework / code cleanup without any new test coverage.
- The runtime …
> [FLINK-23311][tests] minor improvements around PojoSerializer tests

- flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/metrics/LogicalScopeProvider.java
- flink-metrics/flink-metrics-influxdb/src/main/java/org/apache/flink/metrics/influxdb/MeasurementInfoProvider.java
- flink-metrics/flink-metrics-jmx/src/main/java/org/apache/flink/metrics/jmx/JMXReporter.java
- flink-metrics/flink-metrics-prometheus/src/main/java/org/apache/flink/metrics/prometheus/AbstractPrometheusReporter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/FrontMetricGroup.java
Extracts the logical scope methods from the FrontMetricGroup into a separate interface living in flink-metrics-core, so that reporters wanting to make use of do not need a dependency on flink-runtime.
> [FLINK-21757][metrics] Add LogicalScopeProvider interface

- flink-metrics/flink-metrics-core/src/test/java/org/apache/flink/metrics/util/TestMetricGroup.java
Based on #15176 and #15179.
Adds a test MetricGroup implementation that will be used to replace various overly-complicated usages of runtime MetricGroup implementations.
> [FLINK-21759][metrics][tests] Add TestMetricGroup 

- flink-connectors/flink-connector-kafka/pom.xml
- flink-dist/pom.xml
- flink-dist/src/main/assemblies/plugins.xml
- flink-metrics/flink-metrics-jmx/pom.xml
- flink-metrics/flink-metrics-jmx/src/test/java/org/apache/flink/metrics/jmx/JMXReporterTest.java
Based on #15177 and #15178.
- deletes the `JMXJobManagerMetricTest` because it does not add value (the functionality of the reporter is tested separately, and the setup of reporters in the JM is covered by the JobManagerMetricsITCase)
- reworks the JMXReporterTest to work directly against the reporter
> [FLINK-21760][metrics][jmx] Remove flink-runtime dependency

- flink-metrics/flink-metrics-statsd/pom.xml
- flink-metrics/flink-metrics-statsd/src/test/java/org/apache/flink/metrics/statsd/StatsDReporterTest.java
Based on #15177.
- reworks the tests to work directly against the reporter
> [FLINK-21773][metrics][statsd] Remove flink-runtime dependency 

- flink-end-to-end-tests/flink-end-to-end-tests-common/pom.xml
- flink-end-to-end-tests/flink-metrics-reporter-prometheus-test/pom.xml
- flink-kubernetes/pom.xml
- flink-kubernetes/src/main/resources/META-INF/NOTICE
- flink-metrics/flink-metrics-datadog/pom.xml
- flink-metrics/flink-metrics-datadog/src/main/resources/META-INF/NOTICE
- flink-metrics/flink-metrics-influxdb/src/main/resources/META-INF/NOTICE
- pom.xml
This is the latest (and last) version for Okhttp 3.x .
Long-term we need to look into Okhttp 4 to avoid some IPv6 issues, but v4 unfortunately relies on the kotlin standard library which we haven't had to deal with so far.
> [FLINK-23395] Bump Okhttp to 3.14.9

- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/CheckpointBarrierTrackerTest.java
…ntBarrierOvertakesCancellationBarrier in order to make the test more stable
*PR fixes the test*
Test condition was changed
It test itself …
> [FLINK-23419][streaming] Fixed the condition in testNextFirstCheckpointBarrierOvertakesCancellationBarrier in order to make the test more stable

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectSinkFunction.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectSinkOperatorFactory.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/connectors/CollectDynamicSink.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/connectors/DynamicSinkUtils.java
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/delegation/PlannerBase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/TableSinkITCase.scala
Collect sink has a batch size which is currently not configurable. By the user request in FLINK-23352 we're making it configurable in this PR to support user with super large row size.
Note that these configuration are only available for table APIs. As we cannot read user config in data stream API, data stream users will have to write their own Java code to create collect sink explicitly if they want to configure these.
- Add configuration for batch size and socket timeout of collect sink
- …
> [FLINK-23352][streaming-java] Add configuration for batch size and socket timeout of collect sink

- flink-table/flink-table-planner/src/main/java/org/apache/calcite/sql/fun/SqlTimestampAddFunction.java
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/ScalarFunctionsTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CalcITCase.scala
Currently `TIMESTAMPADD(MINUTE, 10, CURRENT_TIMESTAMP)` will be deduced as `timestamp` type. However this should be `timestamp with local time zone` type. With this incorrect type, code generation will refuse to work.
This PR fixes this issue by copying and modifying the corresponding classes from Calcite.
- Fix return value deduction of TIMESTAMPADD function
- The S3 …
> [FLINK-22861][table-planner] Fix return value deduction of TIMESTAMPADD function

- flink-state-backends/flink-statebackend-rocksdb/pom.xml
Update FRocksDB to bump bzip2 dependency version
Update FRocksDB to bump bzip2 dependency version
> [FLINK-21411][rocksdb] Update FRocksDB to bump bzip2 dependency version

- flink-runtime-web/src/test/resources/rest_api_v1.snapshot
- flink-runtime-web/web-dashboard/src/app/interfaces/job-checkpoint.ts
- flink-runtime-web/web-dashboard/src/app/pages/job/checkpoints/job-checkpoints.component.html
- flink-runtime-web/web-dashboard/src/app/pages/job/checkpoints/job-checkpoints.component.ts
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointStatsSnapshot.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CompletedCheckpointStatsSummary.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CompletedCheckpointStatsSummarySnapshot.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/StatsSummary.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/StatsSummarySnapshot.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/TaskStateStats.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/DescriptiveStatisticsHistogram.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/DescriptiveStatisticsHistogramStatistics.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/checkpoints/CheckpointingStatisticsHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/checkpoints/TaskCheckpointStatisticDetailsHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/checkpoints/CheckpointingStatistics.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/checkpoints/StatsSummaryDto.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/checkpoints/TaskCheckpointStatisticsWithSubtaskDetails.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointStatsSnapshotTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointStatsTrackerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CompletedCheckpointStatsSummaryTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/StatsSummaryTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ArchivedExecutionGraphTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/messages/checkpoints/CheckpointingStatisticsTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/messages/checkpoints/TaskCheckpointStatisticsWithSubtaskDetailsTest.java
Add percentiles to checkpoint statistics to better understand backends and checkpointing behaviour.
In particular, compare checkpoint times when using different backends.
Percentiles are computed using histogram (from apache commons-math) which in turn is computed over a sliding window (size = 10000).
I used sliding window histogram because:
- no new dependencies (or algorithm implementations) required
- forcing out old values makes sense to me
I didn't use history.size as sliding window size as I think some users may need histograms but not long history.
With 10K values memory overhead is around 300Kb per job (4 arrays of 10K doubles).
- Added `CompletedCheckpointStatsSummaryTest.testQuantiles`, `StatsSummaryTest.testQuantile`, updated `ArchivedExecutionGraphTest.compareExecutionGraph`
- …
> [FLINK-23144][metrics] Add percentiles to checkpoint statistics

- docs/content.zh/docs/ops/state/checkpoints.md
The page url ：https://ci.apache.org/projects/flink/flink-docs-master/zh/docs/ops/state/checkpoints/
markdown： docs/content.zh/docs/ops/state/checkpoints.md
- A blank line should be added between lines 69 and 70.
```txt
L67 <div class="alert alert-warning">
L68  				<strong>注意:</strong> Checkpoint 目录不是公共 API 的一部分，因此可能在未来的 Release 中进行改变。
L69 </div>
L70 #### 通过配置文件全局配置
```
- The modification is shown below
```txt
<div class="alert alert-warning">
<strong>注意:</strong> Checkpoint 目录不是公共 API 的一部分，因此可能在未来的 Release 中进行改变。
</div>
```
> [FLINK-23432][docs] Solve the Markdown header failure issue

- flink-table/flink-table-planner-blink/src/main/java/org/apache/calcite/sql/fun/SqlTimestampAddFunction.java
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CalcITCase.scala
(This PR is cherry-picked from #16511)
Currently `TIMESTAMPADD(MINUTE, 10, CURRENT_TIMESTAMP)` will be deduced as `timestamp` type. However this should be `timestamp with local time zone` type. With this incorrect type, code generation will refuse to work.
This PR fixes this issue by copying and modifying the corresponding classes from Calcite.
- Fix return value deduction of TIMESTAMPADD function …
> [FLINK-22861][table-planner-blink] Fix return value deduction of TIMESTAMPADD function

- docs/content.zh/docs/deployment/cli.md
- docs/content/docs/deployment/cli.md
The relevant pages are as follows：
https://ci.apache.org/projects/flink/flink-docs-master/docs/deployment/cli/
https://ci.apache.org/projects/flink/flink-docs-master/zh/docs/deployment/cli/
The related documents are as follows：
docs/content/docs/deployment/cli.md
docs/content.zh/docs/deployment/cli.md
In these pages, conf/flink-config.yaml should be changed to conf/flink-conf.yaml
> [FLINK-23489][docs] Change flink-config.yaml to flink-conf.yaml

- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionDriver.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderretrieval/ZooKeeperLeaderRetrievalDriver.java
- flink-runtime/src/main/java/org/apache/flink/runtime/util/ZooKeeperUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/util/ZooKeeperUtilsTreeCacheTest.java
Replaces usages of the `NodeCache` with a `TreeCache`.
The core issue is that the `NodeCache` tries to ensure that the parents to the observed node exist. This can result in curator exceptions that crash the TM if concurrently the path is being deleted. Originally I tried to create a modified `NodeCache` implementation, but got a bad feeling when it came to maintaining said class.
I then looked at other curator caching recipes; the `PathChildrenCache` initially looked neat because it's very purpose is handling entire paths and not single nodes, but it has the same behavior as the `NodeCache` w.r.t. creating parents. 
Then I stumbled on the `TreeCache`, which after some experimenting turned out to be an incredibly flexible class. It _can_ create parent nodes, but its opt-in. It _can_ …
> [FLINK-22893][zookeeper] Replace NodeCache with TreeCache

- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/codegen/CodeSplitTest.java
This is a complementary pull request for FLINK-23007, where we add tests about code splitting for some generated classes to test code splitter with some real generated code.
- Add tests about code splitting for some generated classes …
> [FLINK-23364][table-planner] Add tests about code splitting for some generated classes

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/sort/MultiInputSortingDataInput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/sort/ObservableStreamTaskInput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/sort/SortingDataInput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/AbstractStreamTaskNetworkInput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/DataInputStatus.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/MultipleInputSelectionHandler.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/PushingAsyncDataInput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/StreamInputProcessor.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/StreamMultipleInputProcessor.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/StreamOneInputProcessor.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/StreamTaskExternallyInducedSourceInput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/StreamTaskSourceInput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/StreamTwoInputProcessor.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/recovery/RescalingStreamTaskNetworkInput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTaskFinishedOnRestoreSourceInput.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/sort/CollectionDataInput.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/sort/LargeSortingDataInputITCase.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/sort/MultiInputSortingDataInputsTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/sort/SortingDataInputTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/source/SourceOperatorEventTimeTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/StreamTaskNetworkInputTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
This commit separates internal and user facing versions of InputStatus.
User sources should never return e.g. the END_OF_RECOVERY status and
thus we need an internal status. …
> [FLINK-23474] Extract internal version of InputStatus

- docs/_includes/generated/resource_manager_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/ResourceManagerOptions.java
- flink-runtime/src/test/java/org/apache/flink/runtime/minicluster/MiniClusterITCase.java
This commit hardens the MiniClusterITCase.testHandleBatchJobsWhenNotEnoughSlot by configuring
a higher ResourceManagerOptions.STANDALONE_CLUSTER_STARTUP_PERIOD_TIME than JobManagerOptions.
SLOT_REQUEST_TIMEOUT. This ensures that the slot request times out instead of being failed by
the SlotManager.
> [FLINK-23417][tests] Harden MiniClusterITCase.testHandleBatchJobsWhenNotEnoughSlot

- flink-rpc/flink-rpc-akka-loader/pom.xml
- flink-rpc/flink-rpc-akka-loader/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaRpcSystemLoader.java
- flink-rpc/flink-rpc-akka-loader/src/test/java/org/apache/flink/runtime/rpc/akka/AkkaRpcSystemLoaderTest.java
The `AkkaRpcSystemLoader` no longer requires the configured tmp directory to be present. This just makes it easier to work with.
> [FLINK-23500][akka] Create tmp dir if it doesn't exist

- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/ScalarOperatorsTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/utils/ScalarOperatorsTestBase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/validation/ScalarOperatorsValidationTest.scala
Currently when comparing temporal type with invalid string literal, NullPointerException will be thrown as we'll first cast the string literal to the desired temporal type, resulting in a null value.
In this PR, when the string literal is not in a valid date/time/timestamp format, an exception with message "String xxx is not a valid date/time/timestamp" will be thrown, otherwise the comparison code will be generated as normal.
The comparison result will be null if either operand is null, and will be true/false if both operands are not null.
- Fix NullPointerException when comparing temporal type with invalid string literal
- The public …
> [FLINK-22985][table-runtime] Fix NullPointerException when comparing temporal type with invalid string literal

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/expressions/ScalarOperatorsTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/expressions/utils/ScalarOperatorsTestBase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/expressions/validation/ScalarOperatorsValidationTest.scala
(This PR is cherry-picked from #16462.)
Currently when comparing temporal type with invalid string literal, NullPointerException will be thrown as we'll first cast the string literal to the desired temporal type, resulting in a null value.
In this PR, when the string literal is not in a valid date/time/timestamp format, an exception with message "String xxx is not a valid date/time/timestamp" will be thrown, otherwise the comparison code will be generated as normal.
The comparison result will be null if either operand is null, and will be true/false if both operands are not null.
- Fix NullPointerException when comparing temporal type with invalid string literal
- Dependencies (does it add or …
> [FLINK-22985][table-runtime-blink] Fix NullPointerException when comparing temporal type with invalid string literal

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/agg/batch/HashWindowCodeGenerator.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/agg/batch/WindowCodeGenerator.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/GroupWindowITCase.scala
(This PR is cherry-picked from #16591.)
Currently generated code for window aggregate in batch jobs will not compile if the aggregation has no grouping keys or any named properties (such as tumble_start). This PR fixes this issue.
- Fix compile exception for window aggregate in batch jobs …
> [FLINK-19739][table-runtime-blink] Fix compile exception for window aggregate in batch jobs

- flink-state-backends/flink-statebackend-changelog/pom.xml
Fix FLINK-23534: 
```
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-versions) @ flink-statebackend-changelog ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.BannedDependencies failed with message:
Found Banned Dependency: org.apache.flink:flink-streaming-java_2.11:jar:1.14-SNAPSHOT
Found Banned Dependency: org.apache.flink:flink-streaming-java_2.11:test-jar:tests:1.14-SNAPSHOT
Found Banned Dependency: com.twitter:chill_2.11:jar:0.7.6
Found Banned Dependency: org.apache.flink:flink-scala_2.11:jar:1.14-SNAPSHOT
Found Banned Dependency: org.apache.flink:flink-dstl-dfs_2.11:jar:1.14-SNAPSHOT
Use 'mvn dependency:tree' to locate the source of the banned dependencies.
``` …
> [FLINK-23534] Fix flink-dstl-dfs version used in changelog statebackend

- flink-connectors/flink-connector-kinesis/pom.xml
- flink-connectors/flink-connector-kinesis/src/main/resources/META-INF/NOTICE
- flink-end-to-end-tests/flink-glue-schema-registry-test/pom.xml
- flink-end-to-end-tests/test-scripts/test_sql_client.sh
- flink-formats/flink-avro-glue-schema-registry/pom.xml
* Our current Kinesis dependencies (amazon-kinesis-client, amazon-kinesis-producer) depend on protobuf 2.6.1, which are affected by CVE-2015-5237.
- Updated com.amazonaws.amazon-kinesis-client from 1.11.2 to 1.14.1
- Updated com.amazonaws.amazon-kinesis-producer from 0.14.0 to 0.14.1
- Updated NOTICE files to deal with new version number
- The S3 file …
> [FLINK-19929] Upgrade Kinesis dependencies

- flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/source/abilities/SupportsReadingMetadata.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/data/utils/JoinedRowData.java
- flink-table/flink-table-common/src/test/java/org/apache/flink/table/data/utils/JoinedRowDataTest.java
This exposes `JoinedRowData` as public API. When implementing Table API connectors, the need to join `RowData` arises naturally from having to append metadata to the produced physical row. We should therefore make it easy for implementors to do so without relying on internal APIs.
This PR makes the class public, updates its documentation and adds some basic tests for it.
This change is already covered by existing tests. However, `JoinedRowDataTest` has also been added.
- The runtime per-record code paths (performance sensitive): "yes", but no actual runtime behavior has been changed …
> [FLINK-23537][table-common] Make JoinedRowData public

- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcExactlyOnceSinkE2eTest.java
- flink-connectors/flink-connector-jdbc/src/test/resources/log4j2-test.properties
1. Use `LogLevelRule` to enable debug logs for `JdbcExactlyOnceSinkE2eTest` (instead of `log4j2-test.properties` which isn't used in CI)
2. Configure MySQL lock wait timeout to make it clear if task cancellation or snapshot times out because of this
3. Log InnoDB and transactions statuses to see blocking transactions (every ~4s)
When running for ~20 minutes log size is ~110 Mb with #16523 applied (without the latter more than 1Gb).
Sample log output:
```
23346 [Thread-14] DEBUG org.apache.flink.connector.jdbc.xa.JdbcExactlyOnceSinkE2eTest$MySqlJdbcExactlyOnceSinkTestEnv$InnoDbStatusLogger [] - Blocked TRX
23394 [Thread-14] DEBUG org.apache.flink.connector.jdbc.xa.JdbcExactlyOnceSinkE2eTest$MySqlJdbcExactlyOnceSinkTestEnv$InnoDbStatusLogger [] - waiting_trx_id: 2117, waiting_pid: 48, …
```
> [FLINK-22889][tests] Improve logging in JdbcExactlyOnceSinkE2eTest

- flink-python/pom.xml
- flink-python/src/main/resources/META-INF/NOTICE
- pom.xml
* In order to support compilation with ARM (e.g. Apple M1 chip), we need to bump our Protobuf dependency to version 3.17.3.
- Updated com.google.protobuf:protobuf-java from 3.11.1 to 3.17.3
- Hardcoded version for plugin protoc-jar-maven-plugin:protoc-jar-maven-plugin since that's not in sync with com.google.protobuf:protobuf-java to the latest available version
- Updated NOTICE files to deal with new version number …
> [FLINK-23297] Upgrade Protobuf to 3.17.3

- flink-dist/src/main/flink-bin/bin/flink-daemon.sh
On macOS, I got the following errors from the stop-cluster.sh script:
```
❰robert❙/tmp/flink-1.14-SNAPSHOT❱✔≻ ./bin/start-cluster.sh
Starting cluster.
Starting standalonesession daemon on host MacBook-Pro-2.localdomain.
Starting taskexecutor daemon on host MacBook-Pro-2.localdomain.
❰robert❙/tmp/flink-1.14-SNAPSHOT❱✔≻ ./bin/stop-cluster.sh
Stopping taskexecutor daemon (pid: 50044) on host MacBook-Pro-2.localdomain.
tail: illegal option -- -
usage: tail [-F | -f | -r] [-q] [-b # | -c # | -n #] [file ...]
Stopping standalonesession daemon (pid: 49812) on host MacBook-Pro-2.localdomain.
tail: illegal option -- -
usage: tail [-F | -f | -r] [-q] [-b # | -c # | -n #] [file ...]
```
With this change any error message from the `tail` command gets swallowed, since this timeout operation is anyways …
> [FLINK-23546][dist] Supress error messages on macOS

- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionConnectionHandlingTest.java
Because starting curator is an asynchronous operation it can happen that curator has not yet connected to zookeeper when we restart the server, so the connection technically never gets suspended.
> [FLINK-23518][tests] Wait until curator has connected

- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/delegation/BatchPlanner.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/delegation/StreamPlanner.scala
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/utils/InternalConfigOptionsTest.java
* This pull request set the internal query-start configuration options when translate translate ExecNodeGraph to Transformation
- *Set the internal query-start configuration options when translate translate ExecNodeGraph to Transformation*
- *Add unit tests in  InternalConfigOptionsTest* …
> [FLINK-23571][table-planner] Set internal query-start options when translate ExecNodeGraph to Transformation

- flink-formats/flink-csv/src/test/java/org/apache/flink/formats/csv/CsvFilesystemBatchITCase.java
- pom.xml
This PR aims to fix FLINK-21569, where reading specific csv files will cause the job to hang forever. This is actually caused by a bug in Jackson (https://github.com/FasterXML/jackson-dataformats-text/issues/191), so we're upgrading flink-shaded-jackson version in this fix.
- Upgrade flink-shaded-jackson version to 2.12.1-13.0
This change added tests and can be verified by running the added tests. It can also be tested by hand with the following steps.
1. Download [this csv file](https://issues.apache.org/jira/secure/attachment/13021472/airports.csv).
2. Add the following test to a model which relies both on `flink-csv` and `flink-table-planner-blink`. For example the `flink-sql-client` module. Don't forget to change the file path in the DDL.
```java
public class MyTest {
@Test
public …
```
> [FLINK-21569] Upgrade flink-shaded-jackson version to 2.12.1-13.0

- docs/content.zh/docs/connectors/datastream/elasticsearch.md
Translate the page of "Elasticsearch Connector" into Chinese
The page url is "https://ci.apache.org/projects/flink/flink-docs-master/zh/docs/connectors/datastream/elasticsearch/".
Translate "flink/docs/content.zh/docs/connectors/datastream/elasticsearch.md"
- If yes, …
> [FLINK-23423][docs-zh] Translate the page of "Elasticsearch Connector" into Chinese

- docs/layouts/shortcodes/generated/rest_v1_dispatcher.html
- flink-runtime-web/src/test/resources/rest_api_v1.snapshot
- flink-runtime-web/web-dashboard/src/app/pages/job/overview/flamegraph/job-overview-drawer-flamegraph.component.html
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/JobVertexFlameGraphHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/WebMonitorEndpoint.java
- flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/threadinfo/JobVertexFlameGraph.java
This is the 1.13 backport of #16352 with only one change: regenerating the REST API snapshot for `RestAPIStabilityTest` for 1.13.
I'll wait until CI passes and will merge afterwards.
> [BP-1.13][FLINK-23102][rest] Return empty FlameGraph if feature is disabled

- azure-pipelines.yml
- tools/azure-pipelines/build-apache-repo.yml
```
≻ docker run --rm rmetzger/flink-ci:ubuntu-amd64-02878c6 java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```
> [FLINK-23562][CI] Update CI JDK to 1.8.0_292

- flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniCluster.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerClusterITCase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/testtasks/OnceBlockingNoOpInvokable.java
The AdaptiveSchedulerClusterITCase assumed that only 1 rescaling occurs, but an eager scheduler might do it twice (when the second initial tm offers its slots, once when the intended scale up/down occurs).
We now no longer do any counting of created instances, and instead query the execution graph for the used parallelism.
> [FLINK-23524][tests] Harden AdaptiveSchedulerClusterITCase

- flink-connectors/flink-connector-rabbitmq/src/main/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSource.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceITCase.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceTest.java
This pull request fixes the issue described in FLINK-23183. Currently the redelivered messages are not acknowledged properly upon connection failure (only applicable when autoAck is disabled). When used with a prefetch count in the consumer it may even lead to blocking the source from consuming any more messages.
In the suggested fix, all successfully consumed RMQ messages are be acknowledged, regardless of whether the message is ignored or processed further in the pipeline. In case of redelivered messages, `basicReject` is invoked to acknowledge the message immediately after it's received.
- `channel.basicReject` in `RMQSource` is called in case of already processed (and checkpointed) but redelivered messages (e.g. after the job failover)
This change added tests and can be verified as …
> [FLINK-23183][connectors/rabbitmq] Fix ACKs for redelivered messages in RMQSource

- flink-connectors/flink-connector-rabbitmq/src/main/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSource.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceITCase.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceTest.java
This is a backport of #16472 (fixing FLINK-23183) to release-1.13. The fix is exactly the same as in #16472.
Please see #16472 for a detailed description.
> [BP-1.13][FLINK-23183][connectors/rabbitmq] Fix ACKs for redelivered messages in RMQSource and add IT

- flink-connectors/flink-connector-rabbitmq/src/main/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSource.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceITCase.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceTest.java
This is a backport of #16472 (fixing FLINK-23183) to release-1.12. The fix is exactly the same as in #16472.
Please see #16472 for a detailed description.
> [BP-1.12][FLINK-23183][connectors/rabbitmq] Fix ACKs for redelivered messages in RMQSource and add IT

- docs/content.zh/docs/ops/metrics.md
- docs/content/docs/ops/metrics.md
fix the display format of parameter in ops/metrics.md
change the display format of some parameters as follow:
- 'inputFloatingBuffersUsage'
- 'inputExclusiveBuffersUsage'
- 'maxQueueLen'
- 'avgQueueLen'
- 'backPressuredTimeMsPerSecond'
- 'busyTimeMsPerSecond'
*(or)*
*(or)*
*(example:)*
- …
> [FLINK-23511][doc]fix the display format of parameter in ops/metrics.md

- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSource.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceEnumeratorState.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceEnumeratorStateSerializer.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceReader.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplit.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumerator.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitSerializer.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/SourceReaderFinishedEvent.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/SwitchSourceEvent.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceITCase.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceReaderTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumeratorTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitSerializerTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceTest.java
Initial implementation for hybrid source with support for fixed start position and runtime position conversion for an upfront defined source sequence. Can work with any FLIP-27 source.
Discussion: https://lists.apache.org/thread.html/r94057d19f0df2a211695820375502d60cddeeab5ad27057c1ca988d6%40%3Cdev.flink.apache.org%3E
Based on the previously shared prototype. Integration test with `MockBaseSource`. Unit tests to be added. Tested with `FileSource` and `KafkaSource` on Flink 1.12 cluster. This combination would be a candidate for future e2e test addition.
The design follows overall that outlined in https://cwiki.apache.org/confluence/display/FLINK/FLIP-150%3A+Introduce+Hybrid+Source except that no special interfaces are required for switching of underlying sources. …
> [FLINK-22670][FLIP-150][connector/common] Hybrid source baseline

- flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/threadinfo/JobVertexThreadInfoTracker.java
- flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/threadinfo/JobVertexThreadInfoTrackerBuilder.java
- flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/threadinfo/JobVertexThreadInfoTrackerTest.java
This pull request changes JobVertexThreadInfoTrackerTest#testCachedStatsCleanedAfterCleanupInterval so that unfortunate timings no longer lead to potential failures.
Before, if the provided JobVertexThreadInfoStats object was evicted from cache before we could fetch it, the test would fail. Now, we do not fetch it at all, but simply verify that one item was evicted from cache. 
- *JobVertexThreadInfoTracker can be instantiated with a provided Cache instance. If none is provided to JobVertexThreadInfoTrackerBuilder, it will use an identical one to that used so far*
- *testCachedStatsCleanedAfterCleanupInterval uses this to configure the cache to track statistics and verify the eviction*
- *unnecessary wait times in testCachedStatsCleanedAfterCleanupInterval and …
> [FLINK-23492][runtime] harden testCachedStatsCleanedAfterCleanupInterval

- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/JdbcExactlyOnceOptions.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/JdbcSink.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/XaFacade.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcExactlyOnceSinkE2eTest.java
Currently, JDBC XA sink creates/uses a connection per transaction.
This is to support databases with a single transaction-per-connection drivers.
However, it has an overhead and can lead to exceeding connection limits.
This change disables this feature by default and adds an option to enable it.
This is a trivial change without any test coverage.
- …
> [FLINK-23437][jdbc] Add an option to (dis)allow XA transaction multiplexing

- flink-tests/src/test/java/org/apache/flink/test/recovery/ProcessFailureCancelingITCase.java
This commit hardens the ProcessFailureCancelingITCase.testCancelingOnProcessFailure by increasing the
accepted heartbeat timeout.
> [BP-1.13][FLINK-22382][tests] Harden ProcessFailureCancelingITCase.testCancelingOnProcessFailure

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/factory/KubernetesJobManagerFactory.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/KubernetesJobManagerTestBase.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/KubernetesPodTestBase.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/factory/KubernetesJobManagerFactoryTest.java
This pull requests configs the deployment's annotations as pods' used when deploying with native kubernetes.
Brief change log
The Jobmanager deployment will pick up the annotations when using "kubernetes.jobmanager.annotations".
This change is already covered by existing tests, such as org.apache.flink.kubernetes.kubeclient.factory.KubernetesJobManagerFactoryTest.
Does this pull request potentially affect one of the following parts:
Anything that affects deployment or recovery: JobManager , Kubernetes
Documentation
Does this pull request introduce a new feature? (yes)
If yes, how is the feature documented? (docs)
"kubernetes.jobmanager.annotations" will also set the jobmanager deployment's annotations.
@wangyang0918 I recreated the …
> [FLINK-23587] Set Deployment's Annotation when using native kubernetes

- pom.xml
Update japicmp configuration for 1.13.2
> Update japicmp configuration for 1.13.2

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/util/MockStreamTask.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/util/MockStreamTaskBuilder.java
If there are no input gates, there is no point of calculating the throughput and running the debloater. At the same time, for SourceStreamTask using legacy sources and checkpoint lock, enqueuing even a single mailbox action can cause performance regression. This is especially visible in batch, with disabled checkpointing and no processing time timers.
Pending benchmark request:
http://codespeed.dak8s.net:8080/job/flink-benchmark-request/358 …
> [FLINK-23560][task] Fix performance regression by unnecessary throughput calculations

- docs/content.zh/docs/ops/metrics.md
- docs/content/docs/ops/metrics.md
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricNames.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/bufferdebloat/BufferDebloater.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
This PR depends on https://github.com/apache/flink/pull/16710
Add metrics for buffer debloating
Please check individual commits for the change log
Newly added metrics are tested in `StreamTaskTest#testBufferSizeRecalculationStartSuccessfully` …
> [FLINK-23408][task] Add metrics for buffer debloating

- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/DeliveryGuarantee.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/sink/DefaultKafkaSinkContext.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/sink/FlinkKafkaInternalProducer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/sink/KafkaCommittable.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/sink/KafkaCommittableSerializer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/sink/KafkaCommitter.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/sink/KafkaRecordSerializationSchema.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/sink/KafkaSink.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/sink/KafkaSinkBuilder.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/sink/KafkaTransactionLog.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/sink/KafkaWriter.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/sink/KafkaWriterState.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/sink/KafkaWriterStateSerializer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/sink/TransactionalIdFactory.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/sink/TransactionsToAbortChecker.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/sink/KafkaCommittableSerializerTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/sink/KafkaSinkITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/sink/KafkaTransactionLogITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/sink/KafkaWriterITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/sink/KafkaWriterStateSerializerTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/sink/TransactionIdFactoryTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/sink/TransactionToAbortCheckerTest.java
- flink-core/src/main/java/org/apache/flink/api/connector/sink/InitContextInitializationContextAdapter.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java
- flink-tests/src/test/java/org/apache/flink/test/util/TestUtils.java
This commit introduces a new KafkaSink which is based on FLIP-143.
Besides adding the new KafkaSink the PR has the following additional commits.
- ca1c2e6 to extract a test utility for finding the latest completed checkpoint of a job
- b640ffc introduces a utility to extract needed information from the Sink.InitContext to a SerializationSchema
The changes are covered by multiple unit tests and also integration tests against a real Kafka cluster. …
> [FLINK-22902] Port KafkaSink to FLIP-143

- docs/layouts/shortcodes/generated/checkpointing_configuration.html
- docs/layouts/shortcodes/generated/common_state_backends_section.html
- flink-core/src/main/java/org/apache/flink/configuration/CheckpointingOptions.java
- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogStorageFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniCluster.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/ChangelogStateHandleStreamImpl.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendTestBase.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/AbstractStateChangeLogger.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/KvStateChangeLoggerImpl.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/PriorityQueueStateChangeLoggerImpl.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/restore/ChangelogBackendLogApplier.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/KvStateChangeLoggerImplTest.java
- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/streaming/util/TestStreamEnvironment.java
- flink-tests/pom.xml
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/EventTimeWindowCheckpointingITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/ResumeCheckpointManuallyITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/StreamFaultToleranceTestBase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointStressITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java
- flink-tests/src/test/java/org/apache/flink/test/classloading/ClassLoaderITCase.java
- pom.xml
Randomize whether ChangelogStateBackend is used in tests.
The option was added previously (#16290)
but it wasn't possible to turn it on before merging DFS changelog writer.
The adjustments are:
- use FS DSTL in some tests with heavy load
- don't discard changelog private state to avoid snapshot invalidation on abortion - will be addressed in FLINK-23139
- don't use changelog if local recovery is enabled (which is not supported ATM)
- **fix in changelog backend to write default value along with meadata**
> [FLINK-23279][tests] Randomly use Changelog Backend in tests

- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/ScalarFunctionsTest.scala
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/data/binary/BinaryStringDataUtil.java
Currently hash functions like `MD5`, `SHA2`, etc. fails to compile if the argument is a varbinary value. This PR fixes this issue.
- Fix compile exception in hash functions with varbinary arguments
> [FLINK-23579][table-runtime] Fix compile exception in hash functions with varbinary arguments

- flink-python/pom.xml
using maven protobuf plugin will encount problem in a proxy networking
* use protocArtifact instead of protocVersion
> [FLINK-23661][build] Fix protobuf plugin proxy issue

- flink-metrics/flink-metrics-prometheus/src/test/java/org/apache/flink/metrics/prometheus/PrometheusReporterTaskScopeTest.java
- flink-metrics/flink-metrics-prometheus/src/test/java/org/apache/flink/metrics/prometheus/PrometheusReporterTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/TaskManagerMetricGroup.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/util/MetricUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/MetricRegistryImplTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/AbstractMetricGroupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/MetricGroupRegistrationTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/MetricGroupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/OperatorGroupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/TaskManagerGroupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/TaskManagerJobGroupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/TaskMetricGroupTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTestHarness.java
Modify all existing usages of the TaskManagerMG constructor to use the (moved) MetricUtils factory method, for consistency and to make constructor changes easier.
> [FLINK-23624][metrics] Migrate TaskManagerMG instatiations to factory method

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/ProcessingTimeServiceUtil.java
Currently late timers need to wait 1ms at least to be fired which may decrease the whole job's throughput. (see benchmarks in https://github.com/apache/flink-benchmarks/pull/25)
* In `InternalTimerServiceImpl.onProcessingTime(long)`, we fire all late timers(timer's timestamp < now() - 1ms) directly.
The benchmark uses [ProcessingTimerBenchmark.java](https://github.com/apache/flink-benchmarks/blob/master/src/main/java/org/apache/flink/benchmark/ProcessingTimerBenchmark.java).
Before the change:
```
Result "org.apache.flink.benchmark.ProcessingTimerBenchmark.fireProcessingTimers":
0.683 ±(99.9%) 0.010 ops/ms [Average]
(min, avg, max) = (0.659, 0.683, 0.730), stdev = 0.015
CI (99.9%): [0.673, 0.692] (assumes normal distribution)
Benchmark                                       Mode  Cnt …
```
> [FLINK-23208] let late processing timers fired immediately

- flink-metrics/flink-metrics-prometheus/src/test/java/org/apache/flink/metrics/prometheus/PrometheusReporterTaskScopeTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/TaskManagerJobMetricGroup.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/TaskMetricGroup.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/MetricGroupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/OperatorGroupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/TaskMetricGroupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/chaining/ChainedOperatorsMetricTest.java
Modify all existing usages of the TaskMG constructor to use runtime Apis, for consistency and to make constructor changes easier.
> [FLINK-23626] [Runtime / Metrics] Migrate all TaskMG instantiations to factory method

- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/pom.xml
- flink-end-to-end-tests/flink-end-to-end-tests-common/pom.xml
- flink-end-to-end-tests/flink-end-to-end-tests-hbase/pom.xml
- flink-end-to-end-tests/flink-glue-schema-registry-test/pom.xml
- flink-end-to-end-tests/flink-streaming-kinesis-test/pom.xml
- flink-table/flink-sql-parser-hive/pom.xml
- flink-table/flink-sql-parser/pom.xml
- flink-test-utils-parent/flink-connector-test-utils/pom.xml
- flink-test-utils-parent/flink-test-utils-junit/pom.xml
- flink-test-utils-parent/flink-test-utils/pom.xml
- flink-tests/src/test/java/org/apache/flink/test/junit5/JUnitJupiterTest.java
- pom.xml
This pull request introduces JUnit 5 dependencies into Flink project so that developers can write JUnit 5 style test cases. 
- Add ```junit-jupiter``` dependency in root pom
- Add ```junit-vintage-engine``` and ```junit-jupiter-migrationsupport``` dependency for supporting existing JUnit 4 test cases.
This change is already covered by all existing tests. …
> [FLINK-23255][test] Introduce JUnit 5 dependencies

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/MultipleInputStreamTaskChainedSourcesCheckpointingTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/MultipleInputStreamTaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskFinalCheckpointsTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/util/CompletingCheckpointResponder.java
New version of https://github.com/apache/flink/pull/16734 that I took over for rebasing, reviewing and merging.
This PR implements the logic that if enabled, tasks which read all the incoming data will wait for a notifyCheckpointComplete of a final checkpoint triggered after calling finish() on its operators.
The change is based on #16589, only the last commit (cba5a1c) is relevant.
Added tests in StreamTaskFinalCheckpointsTest. …
> [FLINK-23408] Waiting for final checkpoint completed before finishing a task

- docs/data/sql_functions.yml
- docs/data/sql_functions_zh.yml
Fix the mistake in "systemfunctions".
The documentation of the TRUNCATE SQL function states that "E.g. 42.324.truncate(2) to 42.34", which should be "42.32".
Some period in the document also lacks trailing spaces.
- The description of TRUNCATE SQL function has been modified in docs/data/sql_functions.yml and docs/data/sql_functions_zh.yml
- Add spaces  in docs/data/sql_functions_zh.yml where the specification requires 
- Dependencies (does it add or upgrade a dependency): ( no )
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( no ) …
> [FLINK-23615][docs] Fix the mistake in "systemfunctions"

- docs/content/docs/deployment/filesystems/azure.md
- docs/content/docs/deployment/filesystems/overview.md
- flink-core/src/main/java/org/apache/flink/core/fs/FileSystem.java
- flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AbstractAzureFSFactory.java
- flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AzureBlobStorageFSFactory.java
- flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AzureDataLakeStoreGen2FSFactory.java
- flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/SecureAzureBlobStorageFSFactory.java
- flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/SecureAzureDataLakeStoreGen2FSFactory.java
- flink-filesystems/flink-azure-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-azure-fs-hadoop/src/main/resources/META-INF/services/org.apache.flink.core.fs.FileSystemFactory
- flink-filesystems/flink-azure-fs-hadoop/src/test/java/org/apache/flink/fs/azurefs/AzureBlobStorageFSFactoryTest.java
- flink-filesystems/flink-azure-fs-hadoop/src/test/java/org/apache/flink/fs/azurefs/AzureDataLakeStoreGen2FSFactoryTest.java
- flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-oss-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-hadoop/src/main/java/org/apache/flink/fs/s3hadoop/HadoopS3AccessHelper.java
- flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE
- flink-filesystems/pom.xml
This pull request adds support for [abfs](https://hadoop.apache.org/docs/stable/hadoop-azure/abfs.html) to talk to ADLS Gen2 (Azure DataLake Gen2) storage accounts. These are newer storage account types that hierarchical namespaces, abfs takes advantage of this newer capability. Azure recommends using abfs for reading/writing to these newer storage accounts. 
- Upgrade the hadoop version to latest. Existing version that flink depends on doesn't have hadoop abfs implementation. 
- Added support for two new schemes (abfs:// and abfss://)
- Added english documentation. 
- Ran existing tests to make sure there are no regressions
- Added few trivial unit tests. File system implementations are really hard to test using unit tests. Existing filesystems unit tests seems to be super thin. 
- …
> [FLINK-18562] Support for Hadoop ABFS  for Azure Datalake Gen2 accounts

- flink-runtime-web/web-dashboard/src/app/pages/job/status/job-status.component.html
*When prompting a user to confirm a job cancellation currently we present a popup with text: "Calncel Job?" and decision options: Cancel or OK. These decision options were the default in the html layer, and it had been changed with this PR to "Yes" or "No"*
- *Added nzOkText="Yes" nzCancelText="No" to the html layer*
- Dependencies (does it add or upgrade a dependency): NO
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: NO
- The runtime per-record code paths (performance sensitive): NO
- Anything that affects deployment or recovery: NO
- The S3 file system connector: NO
- Does this pull request introduce a new feature? NO
> [FLINK-23692] Clarify text on Cancel Job confirmation buttons

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/RoundRobinOperatorStateRepartitioner.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/StateAssignmentOperationTest.java
This PR supports partition the partly finished broadcast state on restoring.
**The current repartition logic**
For the operator states, the state of each subtask composes of a list of `OperatorStateHandle`. An `OperatorStateHandle` represents an underlying file(`StreamStateHandle getDelegateStateHandle()`), inside the file there might be multiple states. Each state has a name and list of offset for its contained elements (`Map<String, StateMetaInfo> getStateNameToPartitionOffsets()`). 
Currently there are two cases:
If the parallelism is not change, then we only need to repartition the union list states. If there are indeed union list states, the current implementation will first acquire all the union list states and its underlying `StateMetaInfo` from all the subtasks into `Map<String, …
> [FLINK-23475][runtime][checkpoint] Supports repartition partly finished broacast states

- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBMemoryConfiguration.java
* Corrected RocksDBOptions reference in javadoc
* Updated RocksDBOptions reference in javadoc to point to FIX_PER_SLOT_MEMORY_SIZE as mentioned in the Jira ticket.
> [FLINK-23699] Fixed RocksDBOptions attribute reference

- flink-core/src/main/java/org/apache/flink/util/ExceptionUtils.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/SavepointITCase.java
Do not hide original exceptions in SavepointITCase
This is just a change in tests.
> [FLINK-23713][tests] Do not hide original exceptions in SavepointITCase

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/ShardConsumer.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/metrics/ShardConsumerMetricsReporter.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/DynamoDBStreamsDataFetcherTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/ShardConsumerTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/ShardConsumerTestUtils.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/polling/PollingRecordPublisherFactoryTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/polling/PollingRecordPublisherTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/metrics/ShardConsumerMetricsReporterTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/TestUtils.java
This pull request unregisters metrics reporting for closed shards in the Kinesis connector. This avoids confusing and incorrect aggregated metrics after resharding.
- ShardConsumerMetricsReporter has an unregister method
- ShardConsumer unregisters ShardConsumerMetricsReporter after consuming shard
- Added unit test that checks that the registered MetricGroup is closed after a shard completes.
- Manually verified the change by running a Kinesis Data Analytics app reading from a Kinesis stream with 1 shard then increasing the number of shards to 2, verifying that the metrics for the closed shard are zeroed in the Flink dashboard …
> [FLINK-23705][connectors/kinesis] Unregistering metric reporting for closed shards

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/sink/TwoPhaseCommitSinkFunction.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/functions/sink/TwoPhaseCommitSinkFunctionTest.java
Do not create transactions in TwoPhaseCommitSinkFunction after finish() is called. The reason is that after finish() is called, no more input is expected and hence no more transactions are needed.
The problem of creating transactions is that there would be one/or possibly several open transactions that would be never closed after the task finishes.
Introduce empty transaction holder; so that after sink function is closed, we will place empty transaction as a holder.
- add unit tests
- existing unit tests + ITTests. …
> [FLINK-23473][runtime] Do not create transaction in TwoPhaseCommitSinkFunction after finish

- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/tasks/AbstractInvokable.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/CoordinatorEventsExactlyOnceITCase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskAsyncCallTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TestTaskBuilder.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/checkpointing/CheckpointSequenceValidator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/checkpointing/ValidatingCheckpointHandler.java
- flink-tests/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTriggerSavepointITCase.java
With ENABLE_CHECKPOINTS_AFTER_TASKS_FINISH enabled, final checkpoint can deadlock (or timeout after very long time) if there is a race condition between selecting tasks to trigger checkpoint on and finishing tasks. FLINK-21246 was supposed to handle it, but it doesn't work as expected, because futures from:
org.apache.flink.runtime.taskexecutor.TaskExecutor#triggerCheckpoint
and
org.apache.flink.streaming.runtime.tasks.StreamTask#triggerCheckpointAsync
are not linked together. TaskExecutor#triggerCheckpoint reports that checkpoint has been successfully triggered, while StreamTask might have actually finished.
TODO: implement test
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / …
> [FLINK-23741][checkpointing] Properly decline triggerCheckpoint RPC if StreamTask is not running

- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/writer/RecordOrEventCollectingResultPartitionWriter.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/StreamMultipleInputProcessorFactory.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/StreamTwoInputProcessorFactory.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/FinishedOnRestoreInput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/FinishedOperatorChain.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/OneInputStreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/OperatorChain.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/RegularOperatorChain.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceOperatorStreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorImpl.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/StreamOperatorChainingTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/StreamSourceOperatorLatencyMetricsTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/MultipleInputStreamTaskChainedSourcesCheckpointingTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/MultipleInputStreamTaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/OneInputStreamTaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/OperatorChainTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceOperatorStreamTaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceTaskTerminationTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamMockEnvironment.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskExecutionDecorationTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskFinalCheckpointsTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskMailboxTestHarness.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskMailboxTestHarnessBuilder.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskSelectiveReadingTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/TestFinishedOnRestoreStreamOperator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/TwoInputStreamTaskTest.java
This PR provides a bug fixes for two bugs: FLINK-23708 and FLINK-23698
Add a various unit tests for missing test coverage
- The S3 file system connector: (yes / no ****/ don't know)
> [FLINK-23708][FLINK-23698][task] Re emit and pass watermarks in finished on restore tasks 

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointFailureManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointFailureReason.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/OperatorCoordinatorCheckpoints.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointFailureManagerTest.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/StreamTaskNetworkInput.java
- flink-tests/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterStopWithSavepointITCase.java
This PR supersedes https://github.com/apache/flink/pull/16637. It's adding a two commits on top of the original one.
This pull request make some kinds of failures be checked against CheckpointFailureManager and be deciding whether these errors should be just logged or checked against the number of tolerable failures and maybe fail the job. So it separate IO_EXCEPTION from TRIGGER_CHECKPOINT_FAILURE enum and add IO_EXCEPTION to the reason which will checked against the number of tolerable failures. With this we can let users perceived some unrecoverable error faster. Also it Migrate from EXCEPTION enum to IO_EXCEPTION because according to the code it is exactly IO_EXCEPTION.
- *Separate IO_EXCEPTION from TRIGGER_CHECKPOINT_FAILURE enum*
- *Add IO_EXCEPTION to identify the disk error and …
> [FLINK-23189][checkpoint] Count and fail the task in case of IOExceptions in CheckpointCoordinator

- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/InternalOperatorMetricGroup.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/UnregisteredMetricGroups.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/InternalOperatorGroupTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/MultipleInputStreamTaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/OneInputStreamTaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/TwoInputStreamTaskTest.java
Modify all existing usages of the OperatorMG constructor to use runtime Apis, for consistency and to make constructor changes easier.
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after master …
> [FLINK-23627] [Runtime / Metrics] Migrate all OperatorMG instantiations to factory method

- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/TimerGauge.java
- flink-runtime/src/main/java/org/apache/flink/runtime/throughput/ThroughputCalculator.java
- flink-runtime/src/test/java/org/apache/flink/runtime/throughput/ThroughputCalculatorTest.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
*PR should fix the performance drop after FLINK-23452 but the result is complicated. When I apply these changes right after the problematic commit I defenetelly see the improvement:
- http://codespeed.dak8s.net:8080/job/flink-benchmark-request/424/
- http://codespeed.dak8s.net:8080/job/flink-benchmark-request/425/
- http://codespeed.dak8s.net:8080/job/flink-benchmark-request/427/
But when I apply these changes on the last master(current branch). The improvement is not so obvious:
- http://codespeed.dak8s.net:8080/job/flink-benchmark-request/422/
- http://codespeed.dak8s.net:8080/job/flink-benchmark-request/423/
- http://codespeed.dak8s.net:8080/job/flink-benchmark-request/426/
I still think that this PR makes sense but perhaps we should continue our investigation at least for the …
> [FLINK-23560][runtime] Calculate absoluteTimeMillis only once for idle metric and throughput calculation.

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/config/ConsumerConfigConstants.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriber.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/proxy/KinesisProxyV2Factory.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/util/AwsV2Util.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutRecordPublisherTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriberTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/proxy/KinesisProxyV2FactoryTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/FakeKinesisFanOutBehavioursFactory.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/util/AwsV2UtilTest.java
Reduce/eliminate ReadTimeoutException from the EFO consumer
1. Request next record from the Flink source thread rather than the AWS SDK response thread. This means that there will always be space in the input buffer queue. The AWS SDK async response thread is no longer blocking on this queue. Backpressure is now applied by the Flink source thread rather than the AWS SDK thread.
2. Increase the Read Timeout (30s) to be higher than the maximum Shard subscription duration (5m) and enable TCP keep alive
This change is being merged across multiple Flink versions:
- 1.12: https://github.com/apache/flink/pull/16840 
- 1.13: https://github.com/apache/flink/pull/16841
- 1.14: https://github.com/apache/flink/pull/16839
1. Existing unit/e2e tests 
2. Added new unit tests
3. Manually verified using …
> [FLINK-23802][kinesis][efo] Reduce ReadTimeoutExceptions for Kinesis Consumer

- docs/content/docs/dev/datastream/fault-tolerance/serialization/types_serialization.md
- flink-core/src/main/java/org/apache/flink/api/common/typeinfo/TypeInfo.java
- flink-core/src/main/java/org/apache/flink/api/java/typeutils/TypeExtractor.java
- flink-core/src/test/java/org/apache/flink/api/java/typeutils/TypeInfoFactoryTest.java
*Allow @TypeInfo annotation on POJO field declarations.*
- *allow @TypeInfo annotation on POJO field *
- *add a testcase in TypeInfoFactoryTest.java*
- *change the function analyzePojo to make it can analyze POJO field  with @TypeInfo annotation*
This change is already covered by existing tests, such as *TypeInfoFactoryTest*.
*testWithFieldTypeInfoAnnotation*
- *Added unit test for POJO field declarations with @TypeInfo annotation* …
> [FLINK-12141] [API/Type Serialization System] Allow @TypeInfo annotation on POJO field declarations

- docs/layouts/shortcodes/generated/rocksdb_configurable_configuration.html
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/DefaultConfigurableOptionsFactory.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBConfigurableOptions.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateBackendConfigTest.java
This allows further tuning RocksDB's logger with the following three new parameters:
- `state.backend.rocksdb.log.max-file-size` sets the max log file size
- `state.backend.rocksdb.log.file-num` configures the number of logging files to keep
- `state.backend.rocksdb.log.dir` sets the directory of the logging files, e.g. to put these logs onto a (separate) volume that may not be local and is retained after container shutdown for debugging purposes
- add the options above to `RocksDBConfigurableOptions` with no default values (not changing the current behaviour and instead relying on RocksDB's defaults)
- extend `DefaultConfigurableOptionsFactory` to deal with the new option settings from configuration and via getters/setters
- extend `RocksDBStateBackendConfigTest` to verify valid and …
> [FLINK-23812][rocksdb] support configuring RocksDB logging

- docs/layouts/shortcodes/generated/core_configuration.html
- docs/layouts/shortcodes/generated/expert_class_loading_section.html
- flink-core/src/main/java/org/apache/flink/configuration/CoreOptions.java
Add FRocksDB packages to parent-first classloading patterns.
Change `ALWAYS_PARENT_FIRST_LOADER_PATTERNS` to add FRocksDB packages to parent-first classloading patterns.
> [FLINK-23649][rocksdb] Add FRocksDB packages to parent-first classloading patterns

- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBIncrementalCheckpointUtils.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBOperationUtils.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBResourceContainer.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBIncrementalRestoreOperation.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBResource.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateOptionTest.java
Remove unnecessary setTotalOrderForSeek for Rocks iterator
Remove unnecessary setTotalOrderForSeek for Rocks iterator and modify related tests.
This change is already covered by existing tests, such as `RocksDBStateOptionTest.java`.
> [FLINK-23789][rocksdb] Remove unnecessary setTotalOrderForSeek for Rocks iterator

- flink-table/flink-table-common/src/main/java/org/apache/flink/table/data/binary/BinarySection.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/data/binary/LazyBinaryFormat.java
`BinarySection` currently does not check if `MemorySegment[]` is null in its constructor. This might cause NullPointerException somewhere else and makes it harder to debug (as we don't know who sets the null value into `BinarySection`).
This PR added such null check.
- Add null check in BinarySection's constructor and pointTo method
- The runtime per-record code paths (performance sensitive): **MAYBE** …
> [FLINK-23289][table-common] Add null check in BinarySection's constructor and pointTo method

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/config/ConsumerConfigConstants.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriber.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/proxy/KinesisProxyV2Factory.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/util/AwsV2Util.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutRecordPublisherTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriberTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/proxy/KinesisProxyV2FactoryTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/FakeKinesisFanOutBehavioursFactory.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/util/AwsV2UtilTest.java
Reduce/eliminate ReadTimeoutException from the EFO consumer
1. Request next record from the Flink source thread rather than the AWS SDK response thread. This means that there will always be space in the input buffer queue. The AWS SDK async response thread is no longer blocking on this queue. Backpressure is now applied by the Flink source thread rather than the AWS SDK thread.
2. Increase the Read Timeout (30s) to be higher than the maximum Shard subscription duration (5m) and enable TCP keep alive
This change is being merged across multiple Flink versions:
- 1.12: https://github.com/apache/flink/pull/16840 
- 1.13: https://github.com/apache/flink/pull/16841
- 1.14: https://github.com/apache/flink/pull/16839
1. Existing unit/e2e tests 
2. Added new unit tests
3. Manually verified using …
> [FLINK-23802][kinesis][efo] Reduce ReadTimeoutExceptions for Kinesis Consumer (1.13)

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/config/ConsumerConfigConstants.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriber.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/proxy/KinesisProxyV2Factory.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/util/AwsV2Util.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutRecordPublisherTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriberTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/proxy/KinesisProxyV2FactoryTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/FakeKinesisFanOutBehavioursFactory.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/util/AwsV2UtilTest.java
Reduce/eliminate ReadTimeoutException from the EFO consumer
1. Request next record from the Flink source thread rather than the AWS SDK response thread. This means that there will always be space in the input buffer queue. The AWS SDK async response thread is no longer blocking on this queue. Backpressure is now applied by the Flink source thread rather than the AWS SDK thread.
2. Increase the Read Timeout (30s) to be higher than the maximum Shard subscription duration (5m) and enable TCP keep alive
This change is being merged across multiple Flink versions:
- 1.12: https://github.com/apache/flink/pull/16840 
- 1.13: https://github.com/apache/flink/pull/16841
- 1.14: https://github.com/apache/flink/pull/16839
1. Existing unit/e2e tests 
2. Added new unit tests
3. Manually verified using …
> [FLINK-23802][kinesis][efo] Reduce ReadTimeoutExceptions for Kinesis Consumer (1.12)

- docs/content.zh/docs/dev/table/sql/explain.md
- docs/content/docs/dev/table/sql/explain.md
*(or)*
*(or)*
*(example:)*
- *Extended …
> [FLINK-22844]Add doc to introduce ExplainDetails for EXPLAIN sytnax

- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/network/ClientTest.java
Removes all timeouts from the QS ClientTest, on the assumption that the reporter failure was just a fluke.
> [FLINK-23362][tests] Remove timeouts

- flink-connectors/flink-connector-hbase-2.2/src/main/java/org/apache/flink/connector/hbase2/source/HBaseRowDataAsyncLookupFunction.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperatorTest.java
Fix spelling mistakes for "async"
The 'aysnc' should be changed to 'async'.
1.  flink-connectors/flink-connector-hbase-2.2/src/main/java/org/apache/flink/connector/hbase2/source/HBaseRowDataAsyncLookupFunction.java
```txt
Line 111: 
hbase-aysnc-lookup-worker  ==>  hbase-async-lookup-worker
```
2. flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperatorTest.java
```txt
Line 949: 
AysncWaitOperator  ==> AsyncWaitOperator
```
> [FLINK-23844]Fix spelling mistakes for "async"

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/metrics/KafkaSourceReaderMetrics.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReader.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/metrics/KafkaSourceReaderMetricsTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReaderTest.java
This pull request fixes a bug that counter "commitsSucceeded" is increased per partition instead of per commit.
- Extract ```recordSucceededCommit``` as an individual method in ```KafkaSourceReaderMetrics```
- Invoke ```recordSucceededCommit``` in Kafka consumer commit callback
- Subscribe to two partitions in ```KafkaSourceReader```
- Commit offset only once, and "commitsSucceeded" should be 1 instead of 2 …
> [FLINK-23686][connector/kafka] Increase counter "commitsSucceeded" per commit instead of per partition

- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/CoordinatedSourceITCase.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/InternalSourceReaderMetricGroup.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java
In new `Sources`, timestamp-less records are emitted as records with timestamp `NO_TIMESTAMP`. That's retriggering metric registration in `InternalSourceReaderMetricGroup`.
- Use explicit flags to track lazy registration of metrics instead of magic value.
- Only forward timestamps to metric group when they are not `NO_TIMESTAMP`.
Added `org.apache.flink.connector.base.source.reader.CoordinatedSourceITCase#testMetricsWithoutTimestamp`. …
> [FLINK-23776][streaming] Fix handling of timestamp-less records in Source metrics.

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/BufferWritingResultPartition.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/ResultPartition.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/ResultPartitionTest.java
This patch fixes the network buffer leak when ResultPartition is released by closing all BufferBuilders.
cherry-pick from https://github.com/apache/flink/pull/16844.
- All BufferBuilders are closed in the BufferWritingResultPartition#close method;
- The TaskCanceler call the ResultPartition#fail method instead of the ResultPartition#close method because the close method can incur concurrency issue.
An existing test is modified to cover the scenario. …
> [FLINK-23724][network] Fix the network buffer leak when ResultPartition is released (cherry-pick)

- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/TableJdbcUpsertOutputFormat.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/internal/JdbcTableOutputFormatTest.java
Backport of #16895 to 1.13
```
...so that it is properly initializated after reconnection
```
- Added `JdbcTableOutputFormatTest.testDeleteExecutorUpdatedOnReconnect`
> [BP-1.13][FLINK-23813][connectors/jdbc] Update delete executor in TableJdbcUpsertOutputFormat

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSource.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/metrics/KafkaSourceReaderMetrics.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReader.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaWriterITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/metrics/KafkaSourceReaderMetricsTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReaderTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReaderTest.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/core/testutils/CommonTestUtils.java
- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/metrics/testutils/MetricListener.java
- flink-test-utils-parent/flink-test-utils/src/test/java/org/apache/flink/metric/testutils/MetricListenerTest.java
This pull requests add metric "numBytesIn" and "pendingRecords" for KafkaSource
- Register "numBytesIn" and "pendingRecords" for KafkaSource
- Create ```KafkaPartitionSplitReader``` and assign splits
- Fetch records and check if metrics work s expected …
> [FLINK-23801][connector/kafka] Report numBytesIn and pendingRecords in KafkaSource

- flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaUtils.java
Using the `RemoteActorRefProvider` directly appears to be discouraged nowadays, with the `ClusterActorRefProvider` being the intended replacement. While a migration is probably possible (because the `ClusterActorRefProvider` extends `RemoteActorRefProvider`, I'm not really comfortable doing this after the feature freeze, so we're disabling the warnings instead.
I have filed FLINK-23900 for investigating this for 1.15.
`remote.warn-about-direct-use` completely disables this warning:
https://github.com/akka/akka/blob/v2.6.15/akka-remote/src/main/scala/akka/remote/RemoteActorRefProvider.scala#L327
```
Using the 'remote' ActorRefProvider directly, which is a low-level layer. For most use cases, the 'cluster' abstraction on top of remoting is more suitable instead.
``` …
> [FLINK-23894][akka] Disable warning from RemoteActorRefProvider

- flink-clients/src/main/java/org/apache/flink/client/program/ContextEnvironment.java
- flink-clients/src/main/java/org/apache/flink/client/program/StreamContextEnvironment.java
Environments prints job execution results to stdout by default and provides a flag `suppressSysout` to disable the behavior. This flag is useful when submitting jobs through REST API or other programmatic approaches. However, JobExecutionResult is still printed when this flag is on, which looks like a bug to me.
Skip printing JobExecutionResult if suppressSysout is on.
This change is a trivial rework/code cleanup without any test coverage.
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes  …
> [FLINK-23868][Client] JobExecutionResult printed when suppressSysout is on

- flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkFactoryTest.java
- flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkITCase.java
- flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkTest.java
Backport of #16918 to `release-1.13`.
> [BP-1.13][FLINK-21538][tests] Set default parallelism to 4 for Elasticsearch6DynamicSinkITCase.testWritingDocuments

- flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkFactoryTest.java
- flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkITCase.java
- flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkTest.java
Backport of #16918 to `release-1.12`.
> [BP-1.12][FLINK-21538][tests] Set default parallelism to 4 for Elasticsearch6DynamicSinkITCase.testWritingDocuments

- flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkFactoryTest.java
- flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkITCase.java
- flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkTest.java
Backport of #16924 to `release-1.12.`
> [BP-1.12][FLINK-22333][tests] Harden Elasticsearch7DynamicSinkITCase.testWritingDocuments by setting parallelism to 4

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/async/RichAsyncFunction.java
* RichAsyncFunction does not support double counters but the message indicates "Long counters..."
* Corrected message to correspond to the counter type
> [FLINK-23910][streaming] Updated message to correspond to the counter type

- flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/sink/writer/FileSinkMigrationITCase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/testutils/CommonTestUtils.java
- flink-tests/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterStopWithSavepointITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/RescalingITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/SavepointITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/TimersSavepointITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointCompatibilityITCase.java
```
CommonTestUtils.waitForAllTaskRunning returns when all the subtasks are running AND
the job is running and not finished. However, with FLIP-147, subtasks may finish and
the job will still be running. So the method won't return and instead timeout.
This commit adds a flag to indicate whether to fail or proceed
when a finished sub-task is encountered.
```
[original discussion](https://github.com/apache/flink/pull/16773#discussion_r688532348)
> [FLINK-23811][tests] Handle finished subtasks in CommonTestUtils.waitForAllTaskRunning

- flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniClusterConfiguration.java
Backport of #16921 to `release-1.13`.
> [BP-1.13][FLINK-23906][tests] Increase the default akka.ask.timeout for the MiniCluster to 5 minutes

- flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniClusterConfiguration.java
Backport of #16921 to `release-1.12`.
> [BP-1.12][FLINK-23906][tests] Increase the default akka.ask.timeout for the MiniCluster to 5 minutes

- docs/content/docs/connectors/datastream/hybridsource.md
Initial documentation for HybridSource (introduced in https://github.com/apache/flink/pull/15924).
> [FLINK-22791][docs] Documentation for HybridSource

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableTestBase.java
This pull request set Kafka broker configuration ```log.retention.ms``` to -1 in ```KafkaTableTestBase``` to prevent deleting records with explicitly assigned timestamp.
- Add environment variable ```KAFKA_LOG_RETENTION_MS=-1``` to KafkaContainer to set broker config ```log.retention.ms``` to -1 …
> [FLINK-22198][connector/kafka] Disable log deletion on Kafka broker in KafkaTableTestBase

- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/main/java/org/apache/flink/tests/util/kafka/KafkaContainerClient.java
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SQLClientSchemaRegistryITCase.java
This PR aims at improving the pass rate of SQLClientSchemaRegistryITCase(an unstable e2e test case).
- Remove 120 seconds limitation of the test. Due to the complexity of this e2e case, the old time limitation will make the case fail easily. Besides, after removing the limit, if this test fails, we can get its meaningful logs instead of a single timeout error.
- Use ClassRule instead of Rule to reuse created containers which will save resources and time.
- Increate max waiting time of some functions to make it easier to success.
- This change is already covered by existing tests, such as SQLClientSchemaRegistryITCase.
- The …
> [FLINK-23556][tests] Make SQLClientSchemaRegistryITCase more stable

- docs/content.zh/docs/dev/table/sql/queries/hints.md
- docs/content/docs/dev/table/sql/queries/hints.md
- docs/layouts/shortcodes/generated/table_config_configuration.html
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/config/TableConfigOptions.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlToOperationConverterTest.java
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/catalog/CatalogTableITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/catalog/CatalogViewITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/LegacySinkTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/LegacyTableSourceTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/TableSinkTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/TableSourceTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/hint/OptionsHintTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/LegacyTableSourceITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/TableSinkITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/TableSourceITCase.scala
*The table option `table.dynamic-table-options.enabled` is used to enable the `OPTIONS` hint used to specify table options dynamically, which default value is false. It's recommended to modify the default value of `table.dynamic-table-options.enabled` to true.*
- *Modify the default value of `TableConfigOptions.TABLE_DYNAMIC_TABLE_OPTIONS_ENABLED` to true.*
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** …
> [FLINK-23755][table] Modify the default value of table.dynamic-table-options.enabled to true

- docs/content/docs/connectors/datastream/jdbc.md
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/JdbcXaSinkFunction.java
Update JDBC exactly once sink docs (see also commits):
- remove explicit list of JDBC drivers as dialects are only used in Table API
- add more datasource building examlpes
- clarify withTransactionPerConnection usage and some DB-specific settings
**note** Chinese version not updated (significantly outdated).
> [FLINK-23876][docs] Update JDBC XA Sink docs

- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceReader.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumerator.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceReaderTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumeratorTest.java
This change will ensure that the sources that are contained in `HybridSource` can receive `notifyCheckpointComplete` and `notifyCheckpointAborted`. Found this issue with `KafkaSouce` which would not commit offsets.
Added unit tests and verified with internal deployment.
> [FLINK-24010][connector/common] HybridSourceReader delegates checkpoint notifications

- docs/content.zh/docs/dev/table/sql/queries/window-tvf.md
- docs/content/docs/dev/table/sql/queries/window-tvf.md
The pr adds documentation for window TVF offset.
window-tvf.md
> [FLINK-23055][docs][table] Add documentation for window tvf offset.

- docs/content.zh/docs/deployment/elastic_scaling.md
Translated the "Elastic Scaling" page into Chinese.
Translated the "Elastic Scaling" page into Chinese.
This change is a translation without any test coverage.
> [FLINK-23899][docs-zh] Translate the "Elastic Scaling" page into Chinese

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/BufferListener.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPool.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/BufferManager.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPoolTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/RemoteInputChannelTest.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java
Fix the bug that buffer listeners may not be notified when recycling buffers.
Previously, the buffer listener will be removed from the listener queue when notified and then it will be added to the listener queue again if it needs more buffers. However, if some buffers are recycled meanwhile, the buffer listener will not be notified of the available buffers. For example:
1. Thread 1 calls LocalBufferPool#recycle().
2. Thread 1 reaches LocalBufferPool#fireBufferAvailableNotification() and listener.notifyBufferAvailable() is invoked, but Thread 1 sleeps before acquiring the lock to registeredListeners.add(listener).
3. Thread 2 is being woken up as a result of notifyBufferAvailable() call. It takes the buffer, but it needs more buffers.
4. Other threads, return all buffers, including this …
> [FLINK-23466][network] Fix the bug that buffer listeners may not be notified when recycling buffers

- flink-filesystems/flink-azure-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE
This removes some entries from NOTICE files which are no longer included.
> [FLINK-24027][filesystems] Remove excessive dependencies from NOTICE files

- docs/layouts/shortcodes/generated/state_backend_configuration.html
- docs/layouts/shortcodes/generated/state_backend_latency_tracking_section.html
- flink-core/src/main/java/org/apache/flink/configuration/StateBackendOptions.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/metrics/LatencyTrackingAggregatingState.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/metrics/LatencyTrackingListState.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/metrics/LatencyTrackingMapState.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/metrics/LatencyTrackingReducingState.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/metrics/LatencyTrackingStateConfig.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/metrics/LatencyTrackingValueState.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/metrics/StateLatencyMetricBase.java
Expose state name as varibale if enable state latency tracking.
Add new configuration `state.backend.latency-track.state-name-as-variable` to expose the state name as metrics variable.
> [FLINK-23519][metrics] Expose state name as varibale if enable state latency tracking

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPool.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/NetworkBufferPool.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPoolDestroyTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPoolTest.java
Previously, The buffer listeners are not notified when the the local buffer pool receives available notification from the global pool. This may cause potential deadlock issue:
1. A LocalBufferPool is created but there is no available buffers in the global NetworkBufferPool.
2. The LocalBufferPool registers an available buffer listener to the global NetworkBufferPool.
3. The BufferManager requests buffers from the LocalBufferPool but no buffer is available. As a result, it registers an available buffer listener to the LocalBufferPool.
4. A buffer is recycled to the global NetworkBufferPool and the LocalBufferPool is notified about the available buffer.
5. The LocalBufferPool requests the available buffer from the global NetworkBufferPool but the registered available buffer listener of …
> [FLINK-24035][network] Guarantee that the LocalBufferPool is initialized with one buffer

- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecOverAggregate.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecPythonOverAggregate.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecTemporalSort.java
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/OverAggregateITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/TemporalSortITCase.scala
* Fix `StreamExecOverAggregate` and `StreamExecTemporalSort` operators didn't support LocalZonedTimestampType
- Use `LogicalTypeChecks#isRowtimeAttribute()` utils to check the rowtime attribute
* Add ITCase to test the two operators.
> [FLINK-24081][table-planner] Fix StreamExecOverAggregate and StreamExecTemporalSort operator didn't support LocalZonedTimestampType

- flink-runtime/src/test/java/org/apache/flink/runtime/net/SSLUtilsTest.java
This is a simple change in tests that throws the original exception instead of failing with JUnit assertion if OpenSSL was not found.
> [FLINK-23468][test] Do not hide original exception if SSL is not available

- docs/content.zh/docs/dev/table/concepts/timezone.md
- docs/content/docs/dev/table/concepts/timezone.md
- docs/content/docs/dev/table/concepts/versioned_tables.md
* Add  first class subject for page `versioned table` and `Timezone`
* Add  first class subject for page `versioned table` and `Timezone`
> [FLINK-24085][docs] Add  first class subject for page `versioned table` and `Timezone`

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/testutils/KafkaSingleTopicExternalContext.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/PulsarTestContext.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/cases/MultipleTopicConsumingContext.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/cases/SingleTopicConsumingContext.java
- flink-test-utils-parent/flink-connector-testing/src/main/java/org/apache/flink/connectors/test/common/external/ExternalContext.java
- flink-test-utils-parent/flink-connector-testing/src/main/java/org/apache/flink/connectors/test/common/testsuites/SourceTestSuiteBase.java
This pull request resolves the error in the connector testing framework, when comparing the result with data in different splits. When achieving your own `ExternalContext`, the records in different splits returned by method `generateTestData` should be judged not as equal by method `equlas`.
- add the `splitIndex` parameter to the method `generateTestData`
- modify the tests and the implements for `ExternalContext`, make sure generated records in different splits by `generateTestData` be judged not as equal
- …
> [FLINK-23971][tests] fix connector testing framework error when compare records in different splits

- docs/content.zh/docs/deployment/metric_reporters.md
- docs/content/docs/deployment/metric_reporters.md
- flink-core/src/main/java/org/apache/flink/configuration/ConfigConstants.java
- flink-metrics/flink-metrics-prometheus/src/test/java/org/apache/flink/metrics/prometheus/PrometheusReporterTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricRegistryImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/ReporterSetup.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/FrontMetricGroup.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/ReporterScopedSettings.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/ReporterSetupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/FrontMetricGroupTest.java
To add a configuration for additional variables reported by the metric reporters, in a generic fashion.
* ReporterSetup and FrontMetricGroup have enhanced logic to parse and apply the configuration, respectively.
Functionality verification is covered by unit tests. …
> [FLINK-17495][metrics] Add additional variables config for metric reporters

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/DataStream.java
- flink-streaming-scala/src/main/scala/org/apache/flink/streaming/api/scala/DataStream.scala
* The printToErr methods doc indicates it writes to standard output stream
* Corrected javadoc to indicate that printToErr writes to standard error stream
> [FLINK-24042] Corrected the description of stderr in DataStream java doc

- docs/content.zh/docs/dev/datastream/fault-tolerance/state.md
- docs/content/docs/dev/datastream/fault-tolerance/state.md
Remove notice that pyflink does not support state TTL.
> [FLINK-24106][docs] Remove notice that pyflink does not support state TTL

- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/slotpool/AllocatedSlotPool.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/slotpool/DeclarativeSlotPool.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/slotpool/DefaultAllocatedSlotPool.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/slotpool/DefaultDeclarativeSlotPool.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/DefaultAllocatedSlotPoolTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/DefaultDeclarativeSlotPoolTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/TestingPhysicalSlotPayload.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/allocator/SharedSlotTest.java
When a slot is released in the `DefaultDeclarativeSlotPool` then the pool returns a `ResourceCounter` describing which requirements said slots were fulfilling, such that the `DeclarativeSlotPoolBridge` can then reduce the requirements accordingly.
The pool however did not take into account that the released slot may already be free; in that case the requirements were already reduced previously (at the time the slot was freed); according to the returned `ResourceCounter` the slot was nevertheless still fulfilling the previous requirement, which lead to a requirement reduction being applied twice.
The pool now checks for all slots that are released whether they are currently reserved or not, and only determines the fulfilled requirements for the reserved ones.
To determine whether a slot …
> [FLINK-24005][coordination] Only return fulfilled requirements for reserved slots

- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecOverAggregate.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecPythonOverAggregate.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecTemporalSort.java
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/OverAggregateITCase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/TemporalSortITCase.scala
* Fix `StreamExecOverAggregate` and `StreamExecTemporalSort` operators didn't support LocalZonedTimestampType
- Use `LogicalTypeChecks#isRowtimeAttribute()` utils to check the rowtime attribute
* Add ITCase to test the two operators.
> [FLINK-24081][table-blink-planner] Fix StreamExecOverAggregate and StreamExecTemporalSort operator didn't support LocalZonedTimestampType

- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerServices.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/slot/DefaultTimerService.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/slot/TimerService.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskSubmissionTestEnvironment.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/slot/DefaultTimerServiceTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotTableImplTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/slot/TestingTimerService.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/slot/TestingTimerServiceBuilder.java
`TaskSlotTableImplTest#runDeactivateSlotTimeoutTest` checks that the timeout is cancelled by asserting that a future is _not_ canceled in a given time-frame. These kind of assertions (of something _not_ happening) tend to be unstable because there is no good measure for how long you need to wait.
Instead the test was refactored to check that `TimerService#unregisterTimeout` is called instead. Several refactorings were made to make this possible, and existing tests for the TimerService were cleaned up and extended.
> [FLINK-24058][coordination][tests] Harden TaskSlotTableImplTest#runDeactivateSlotTimeoutTest

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/SavepointITCase.java
- flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/TimestampITCase.java
SavepointITCase#waitUntilAllTasksAreRunning is querying the REST API, but did not account for the possibility of requests failing due to leader elections being in progress. If the startup of the cluster was slow the test ended up failing.
We now use the RestClusterClient to submit these requests which automatically retries in this case.
> [FLINK-24047][tests] Retry if leader election is in progress

- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/OneInputStreamTaskTestHarness.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTestHarness.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/TwoInputStreamTaskTestHarness.java
Old test harness should no longer be used and any new code should be using StreamTaskMailboxTestHarness
This is change in tests.
- If yes, how is the feature documented? (**not applicable /** docs / JavaDocs / not …
> [hotfix][test] Clearly mark old TestHarness classes as deprecated

- docs/layouts/shortcodes/generated/all_taskmanager_section.html
- docs/layouts/shortcodes/generated/task_manager_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/TaskManagerOptions.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerConfiguration.java
Backport of #16995 to `release-1.13`.
> [BP-1.13][FLINK-22002][tests] Let taskmanager.slot.timeout fall back to akka.ask.timeout

- docs/content.zh/docs/dev/datastream/application_parameters.md
Translate the page of "Handling Application Parameters " into Chinese
The page url of "Handling Application Parameters" is https://ci.apache.org/projects/flink/flink-docs-release-1.13/zh/docs/dev/datastream/application_parameters/.
The markdown file can be found in flink/docs/content.zh/docs/dev/datastream/application_parameters.md in English.
Brief change log
Translate 'flink/docs/content.zh/docs/dev/datastream/application_parameters.md'.
Does this pull request potentially affect one of the following parts:
The public API, i.e., is any changed class annotated with @public(Evolving): no …
> [FLINK-23242][docs-zh] Translate the page of "Handling Application Parameters" into Chinese

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointRequestDecider.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/DataSetMetaInfo.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/ChannelStatePersister.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/RemoteInputChannel.java
- flink-runtime/src/main/java/org/apache/flink/runtime/memory/MemoryManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/memory/SharedResources.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointRequestDeciderTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/memory/SharedResourcesTest.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliInputView.java
We are a collaborative group of researchers from JetBrains Research and Oregon State University, and we are testing our data-driven [plugin](https://github.com/JetBrains-Research/data-driven-type-migration), which is based on the IntelliJ's [Type Migration](https://www.jetbrains.com/help/idea/type-migration.html) framework and adjusts it using custom structural-replace templates that express the adaptations required to perform the type changes.
I want to apply several type changes using it and open the PR, thus introducing primitive functional interfaces in order to prevent unnecessary boxing (like `BooleanSupplier` instead of `Supplier<Boolean>`, `OptionalInt` instead of `Optional<Integer>`, `Predicate<T>` instead of `Function<T, Boolean>`, etc.), since it can affect the performance of …
> [FLINK-23907] Type Migration: introducing primitive functional interfaces

- flink-runtime-web/web-dashboard/src/app/pages/job/overview/chart/job-overview-drawer-chart.component.html
Fixed the problem that the metrics are too long to display in the metrics select box by adding title for select box options.
- flink-runtime-web/web-dashboard/src/app/pages/job/overview/chart/job-overview-drawer-chart.component.html
> [FLINK-24023][runtime-web] The names of metrics are incomplete

- docs/content/docs/dev/datastream/fault-tolerance/checkpointing.md
- flink-python/pyflink/datastream/checkpoint_config.py
- flink-python/pyflink/datastream/tests/test_check_point_config.py
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/CheckpointConfig.java
This PR adds python API and updates the docs for setting the tolerable number of checkpoint failures.
- If yes, how is the feature documented? (not applicable / **docs** / **JavaDocs** / not documented)
> [FLINK-23916][python][docs] Expose in python and update the documentation how to set tolerable checkpoint failure number

- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSource.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceEnumeratorState.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceEnumeratorStateSerializer.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceReader.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplit.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumerator.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitSerializer.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/SwitchedSources.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceReaderTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumeratorTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitSerializerTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/mocks/MockBaseSource.java
Restore from savepoint fails due to deserialization of underlying splits before the underlying enumerator has been restored (details in JIRA). With this change deserialization will be deferred and be explicit in the HybridSource enumerator/reader.
Existing tests don't cover restore from savepoint (ITCase performs recovery from initial state). Deserialization of HybridSplit and enumerator checkpoint covered by unit test. Changes verified with internal deployment. Planning to add unit test that just deserializes HybridSourceSplit before merging.
> [FLINK-24064][connector/common] HybridSource restore from savepoint

- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/SingleThreadMultiplexSourceReaderBase.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/fetcher/SingleThreadFetcherManager.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcher.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherManager.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherTest.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSource.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReader.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReader.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/fetcher/KafkaSourceFetcherManager.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceTestUtils.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReaderTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReaderTest.java
This pull request fixes a bug that empty split is only unassigned from KafkaConsumer but not be cleaned up in SplitFetcher.
- Add a set for tracking splits discovered empty at ```KafkaPartitionSplitReader#handleSplitsChanges```
- Mark empty splits in the set above as finished in ```KafkaPartitionSplitReader#fetch```
- Assign an empty split to ```KafkaPartitionSplitReader``` 
- Make a fetch and check if the empty split is added to finished split in the returning ```RecordsWithSplitIds``` …
> [FLINK-23773][connector/kafka] Mark empty splits as finished to cleanup states in SplitFetcher

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectResultFetcher.java
Some users may encounter a warning message with `FlinkJobNotFoundException` when using `DataStream#collect` or `TableResult#collect`. This is because a collecting request is sent when the job is not running. See FLINK-24088 for more details.
These messages are actually harmless but for a cleaner log we change the logging level of this type of exception from warn to debug in this PR.
- Log FlinkJobNotFoundException in debug instead of warn level in CollectResultFetcher for a cleaner log
- …
> [FLINK-24088][streaming] Log FlinkJobNotFoundException in debug instead of warn level in CollectResultFetcher for a cleaner log

- docs/content.zh/docs/dev/table/tableApi.md
- docs/content/docs/dev/table/tableApi.md
* Table API join documentation for Java has missing end quote after table name
* Fixed missing quote 
> [FLINK-24172][tableapi][docs] - Fixed missing quote for join examples

- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/PartiallyFinishedSourcesITCase.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/event/CheckpointCompletedEvent.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/event/CheckpointStartedEvent.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/event/InputEndedEvent.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/event/OperatorFinishedEvent.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/event/OperatorStartedEvent.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/event/TestCommandAckEvent.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/event/TestEvent.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/event/WatermarkReceivedEvent.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/graph/MultiInputTestOperator.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/graph/OneInputTestStreamOperator.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/graph/TestEventSource.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/graph/TwoInputTestStreamOperator.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/validation/DrainingValidator.java
Fix test stability issue FLINK-24162 by
checking MAX_WATERMARK per attempt in FLIP-147 tests.
```
Adjust DrainingValidator to validate subtask events if:
- finished normally, last attempt
- finished normally, recovered, finished - both attempts must emit MAX_WATERMARK and end input
Skip if task wasn't finished and the attempt failed (by any subtask).
```
In addition, parameterize to test with full and region failover strategy
(currently depends on scheduler). …
> [FLINK-24162][tests] Check MAX_WATERMARK per attempt in FLIP-147 tests

- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/BuiltInMethods.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/FunctionGenerator.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/ScalarFunctionsTest.scala
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/SqlFunctionUtils.java
`ROUND` SQL function accepts any numeric type as the first input argument. However when the first argument is of `TINYINT` / `SMALLINT` / `FLOAT` type the generated code fails to compile as we haven't implemented the round function for these types.
- Fix compile exception for ROUND function with some numeric input arguments …
> [FLINK-23612][table-runtime] Fix compile exception for ROUND function with some numeric input arguments

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/FlinkKafkaInternalProducer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaCommitter.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaWriter.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/Recyclable.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaCommitterTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaSinkITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaWriterITCase.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesCheckpointIDCounter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointIDCounter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/StandaloneCheckpointIDCounter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/ZooKeeperCheckpointIDCounter.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/SinkOperator.java
Producer can leak if there are interruptions during cancellation while the producer tries to orderly abort transactions.
- Harden KafkaSinkITCase and active FLIP-147
- Fix committer bugs with active FLIP-147 (duplicate `SinkWriter#prepareCommit`)
- Make closing of committer and Kafka writer/committer more reliable by not failing on first exception
- 3 smaller fixes in KafkaWriter/Committer.
Added test with concurrent checkpoints to KafkaWriterITCase.
Most fixes cover issues exposed by existing tests.
- The runtime per-record code paths (performance sensitive): (yes / **no** / …
> [FLINK-24131][datastream/kafka] Reliably shutdown producer

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaChangelogTableITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/UpsertKafkaTableITCase.java
This pull request set Kafka broker configuration log.retention.ms to -1 in KafkaTableTestBase to prevent deleting records with explicitly assigned timestamp.
- Add additional property "log.retention.ms = -1" to KafkaServer config …
> [FLINK-22198][connector/kafka] Disable log deletion on Kafka broker in Kafka table connector tests

- pom.xml
This version uses http5 as the default transport, which is not affected by the race condition we run into.
https://github.com/testcontainers/testcontainers-java/issues/3531
> [FLINK-22971][tests] Bump testcontainers to 1.16.0

- flink-docs/pom.xml
* Update org.jsoup.jsoup to 1.14.2 to address GHSA-m72m-mhq2-9p6c
* Update org.jsoup.jsoup dependency to 1.14.2
* This change is a trivial rework / code cleanup without any test coverage. …
> [FLINK-24181] Bump JSoup to 1.14.2

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaWriter.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/metrics/KafkaSourceReaderMetrics.java
This pull request changes the implementation of updating ```numBytesIn/Out``` metric in Kafka connector to handle the counter correctly in chained operator scenario.
- Use increment of bytes consumed/produced for updating numBytesIn/Out in Kafka connector
- If yes, how …
> [FLINK-24126][connector/kafka] Use increment of bytes consumed/produced for updating numBytesIn/Out in Kafka connector

- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnTestBase.java
- flink-yarn-tests/src/test/resources/log4j2-test.properties
- tools/ci/log4j.properties
We struggled to investigate [FLINK-23611](https://issues.apache.org/jira/browse/FLINK-23611) due to missing Flink logs. It appears that something went wrong with the Flink cluster. The stop signal wasn't retrieved by the YARN Session Cluster thread for some reason which made the test wait forever for the thread to finish.
The tests are executed on AzureCI through `tools/ci/test_controller.sh` which implements a watchdog mechanism that checks the logs (`stdout` and `mvn-*.log`) for new content and kills the test if there's no output for a given amount of time (900s). YARN does produce regular logs, though, through the `org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ResourceLocalizationService` logger. These log messages are generated every 10 minutes:
```
22:51:31,785 …
```
> [FLINK-23611][yarn-tests] Disables log message to enable watchdog functionality

- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnTestBase.java
- flink-yarn-tests/src/test/resources/log4j2-test.properties
- tools/ci/log4j.properties
Backport for #16989 
Copied from original PR:
We struggled to investigate [FLINK-23611](https://issues.apache.org/jira/browse/FLINK-23611) due to missing Flink logs. It appears that something went wrong with the Flink cluster. The stop signal wasn't retrieved by the YARN Session Cluster thread for some reason which made the test wait forever for the thread to finish.
The tests are executed on AzureCI through `tools/ci/test_controller.sh` which implements a watchdog mechanism that checks the logs (`stdout` and `mvn-*.log`) for new content and kills the test if there's no output for a given amount of time (900s). YARN does produce regular logs, though, through the `org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ResourceLocalizationService` logger. These log messages …
> [BP-1.14][FLINK-23611][yarn-tests] Disables log message to enable watchdog functionality

- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnTestBase.java
- flink-yarn-tests/src/test/resources/log4j2-test.properties
- tools/ci/log4j.properties
Backport for #16989 
Copied from original PR:
We struggled to investigate [FLINK-23611](https://issues.apache.org/jira/browse/FLINK-23611) due to missing Flink logs. It appears that something went wrong with the Flink cluster. The stop signal wasn't retrieved by the YARN Session Cluster thread for some reason which made the test wait forever for the thread to finish.
The tests are executed on AzureCI through `tools/ci/test_controller.sh` which implements a watchdog mechanism that checks the logs (`stdout` and `mvn-*.log`) for new content and kills the test if there's no output for a given amount of time (900s). YARN does produce regular logs, though, through the `org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ResourceLocalizationService` logger. These log messages …
> [BP-1.13][FLINK-23611][yarn-tests] Disables log message to enable watchdog functionality

- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnTestBase.java
- flink-yarn-tests/src/test/resources/log4j2-test.properties
- tools/ci/log4j.properties
Backport for #16989 
Copied from original PR:
We struggled to investigate [FLINK-23611](https://issues.apache.org/jira/browse/FLINK-23611) due to missing Flink logs. It appears that something went wrong with the Flink cluster. The stop signal wasn't retrieved by the YARN Session Cluster thread for some reason which made the test wait forever for the thread to finish.
The tests are executed on AzureCI through `tools/ci/test_controller.sh` which implements a watchdog mechanism that checks the logs (`stdout` and `mvn-*.log`) for new content and kills the test if there's no output for a given amount of time (900s). YARN does produce regular logs, though, through the `org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ResourceLocalizationService` logger. These log messages …
> [BP-1.12][FLINK-23611][yarn-tests] Disables log message to enable watchdog functionality

- docs/content.zh/docs/dev/table/sql/queries/joins.md
- docs/content/docs/dev/table/sql/queries/joins.md
* This pull request fix the notes of SQL Temporal Join example in documentation
-  Fix the notes
> [FLINK-24115][docs] Fix outdated SQL Temporal Join example

- NOTICE
Adds the aws-java-sdk NOTICE to the source NOTICE, because we have copied classes from said project.
> [FLINK-24183][legal] Add aws-java-sdk-s3 to source NOTICE

- flink-connectors/flink-connector-elasticsearch5/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-elasticsearch6/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-elasticsearch7/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-hbase-1.4/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-hbase-2.2/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-kinesis/src/main/resources/META-INF/NOTICE
- flink-dist/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-azure-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-oss-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE
- flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE
- flink-formats/flink-sql-avro/src/main/resources/META-INF/NOTICE
- flink-streaming-java/pom.xml
- flink-table/flink-table-planner/src/main/resources/META-INF/NOTICE
- pom.xml
* Update commons-compress to 1.21 due to CVE-2021-35517
* Updated other apache.commons dependencies to latest version
* Separate commits for addressing the commons-compress update and the other apache.commons updates …
> [FLINK-24034] Upgrade commons-compress to 1.21 and other apache.commons updates

- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/src/reader/FileRecordFormat.java
these records together do not consume too "much" memory.
This pull request improves the java doc by fixing the sentence.
- *adding the missing word "much" for the java doc of FileRecordFormat#RECORDS_PER_FETCH*
This change is a trivial rework / java doc cleanup without any test coverage.
> [hotfix][docs] Fix sentence by adding one word: 

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaWriter.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/metrics/KafkaSourceReaderMetrics.java
> [BP-1.14][FLINK-24126][connector/kafka] Use increment of bytes consumed/produced for updating numBytesIn/Out in Kafka connector

- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcExactlyOnceSinkE2eTest.java
...to tolerate occasional long XA PREPARE executions in MySQL
> [FLINK-22889][tests] Increase timeouts in JdbcExactlyOnceSinkE2eTest

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReaderTest.java
- flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testutils/source/reader/SourceReaderTestBase.java
Make SourceReaderTestBase.NUM_SPLITS to be overridden in the implementations to help other connectors like [Pravega](https://github.com/pravega/flink-connectors/) use this base class to test the function of the FLIP-27 source.
- Remove the `final` constraint in `SourceReaderTestBase.NUM_SPLITS` and initialize in a `BeforeClass` method
- Change the `TOTAL_NUM_RECORDS` into a method `getTotalNumRecords()`
- Change the internal implementations accordingly
> Note: this would be a breaking change for outside connectors which already extends `SourceReaderTestBase`
- The …
> [FLINK-24059][Connectors/Common] Allow SourceReaderTestBase.NUM_SPLITS to be overridden

- .idea/vcs.xml
This PR modifies the vcs.xml to include any changes that _my_ IDE makes automatically. It fixes a formatting issues, removes the license (which is unnecessary because it's not part of the source release), and it adds the git subdirectory for the documentation.
> [FLINK-24031] Extend vcs.xml

- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcExactlyOnceSinkE2eTest.java
> [BP-1.14][FLINK-22889][tests] Increase timeouts in JdbcExactlyOnceSinkE2eTest

- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/metadata/FlinkMetadata.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/metadata/FlinkRelMetadataQuery.java
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/metadata/FlinkDefaultRelMetadataProvider.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdUniqueKeys.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdUpsertKeys.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalOverAggregate.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/optimize/StreamCommonSubGraphBasedOptimizer.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/schema/IntermediateRelTable.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdHandlerTestBase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdUpsertKeysTest.scala
Cherry-pick #16096
For fix FLINK-20374, we need to resolve streaming computation disorder. we need to introduce a change log upsert keys, this is not unique keys.
```
/**
* Determines the set of change log upsert minimal keys for this expression. A key is
* represented as an {@link org.apache.calcite.util.ImmutableBitSet}, where each bit position
* represents a 0-based output column ordinal.
*
* <p>Different from the unique keys: In distributed streaming computing, one record may be
* divided into RowKind.UPDATE_BEFORE and RowKind.UPDATE_AFTER. If a key changing join is
* connected downstream, the two records will be divided into different tasks, resulting in
* disorder. In this case, the downstream cannot rely on the order of the original key. So in
* this case, it has unique keys in the …
```
> [FLINK-22901][table-planner-blink] Introduce getUpsertKeys in FlinkRelMetadataQuery

- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/SingleThreadMultiplexSourceReaderBase.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/fetcher/SingleThreadFetcherManager.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcher.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherManager.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherTest.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSource.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReader.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReader.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/fetcher/KafkaSourceFetcherManager.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceTestUtils.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReaderTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReaderTest.java
Unchanged backport of #16870 on release-1.13
> [BP-1.13][FLINK-23773][connector/kafka] Mark empty splits as finished to cleanup states in SplitFetcher

- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/tasks/AbstractInvokable.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/tasks/TaskInvokable.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
Previously there was a potential race condition in disabling interrupts while closing resources.
It used be guarded by a volatile variable, but there might have been a race condition when:
1. interrupter thread first checked the shouldInterruptOnCancel flag
2. shouldInterruptOnCancel flag switched to false as Task/StreamTask entered cleaning up phase
3. interrupter issued an interrupt while Task/StreamTask are closing/releasing resources, potentially causing a memory leak
It would be very difficult to provide a test coverage for this bug. …
> [FLINK-24184][task] Introduce lock to guard against race conditions around shouldInterruptOnCancel

- docs/content.zh/docs/dev/table/sql/set.md
Translate "SET Statements" page of "SQL" into Chinese
https://ci.apache.org/projects/flink/flink-docs-master/docs/dev/table/sql/set/
docs/content.zh/docs/dev/table/sql/set.md
> [FLINK-24219][doc]Translate "SET Statements" page of "SQL" into Chinese

- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/SingleThreadMultiplexSourceReaderBase.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/fetcher/SingleThreadFetcherManager.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcher.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherManager.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherTest.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSource.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReader.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReader.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/fetcher/KafkaSourceFetcherManager.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceTestUtils.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReaderTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReaderTest.java
Unchanged backport of #16870 on release-1.14
> [BP-1.14][FLINK-23773][connector/kafka] Mark empty splits as finished to cleanup states in SplitFetcher

- docs/content.zh/docs/connectors/table/datagen.md
- docs/content/docs/connectors/table/datagen.md
- flink-table/flink-sql-client/src/test/resources/sql/table.q
- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/connector/datagen/table/DataGenConnectorOptions.java
- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/connector/datagen/table/DataGenConnectorOptionsUtil.java
- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/connector/datagen/table/DataGenTableSourceFactory.java
- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/connector/datagen/table/DataGenVisitorBase.java
- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/connector/datagen/table/RandomGeneratorVisitor.java
- flink-table/flink-table-api-java-bridge/src/test/java/org/apache/flink/table/factories/DataGenTableSourceFactoryTest.java
Introduce a `max-past` duration option for timestamp type fields. If the `max-past` is specified, it will resolve a past timestamp relative to the current timestamp of the local machine.
You can use it to achieve the out-of-order effect.
- Add a `max-past` option for timestamp types in datagen connector.
- Added test that validates that the `max-past` option is available.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: …
> [FLINK-22275][table] Support random past for timestamp types in datagen connector

- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/PulsarSourceEnumerator.java
Use stick key consumer in Key_Shared subscription. This would make sure Pulsar won't treat the Flink reader as a shared consumer.
This fix https://github.com/apache/pulsar/pull/12035
- Change consumer type in `PulsarSourceEnumerator`
This change is already covered by existing tests, such as `PulsarSourceKeySharedE2ECase` in [another PR](https://github.com/apache/flink/pull/17271). …
> [FLINK-24283][connector/pulsar] Use stick key consumer in Key_Shared subscription.

- docs/content/docs/connectors/datastream/kafka.md
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSource.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSourceBuilder.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSourceOptions.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/OffsetsInitializerValidator.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/ReaderHandledOffsetsInitializer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/SpecifiedOffsetsInitializer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReader.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReader.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/KafkaDynamicSource.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceBuilderTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceTestUtils.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReaderTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaDynamicTableFactoryTest.java
This pull request adds a configuration for KafkaSource for disabling offset commit on checkpoint, and add sanity checks on `group.id`
- Add config for disabling offset commit on checkpoint
- Add sanity checks on `group.id`. If `group.id` is not specified, offset commit on checkpoint will be disabled
- Remove auto-generated group id in Kafka table source
- Added integration tests for using Kafka source without group ID
- Added test validating KafkaSourceBuilder capturing corrupted configurations (enabled offset commit manually but missing group id)
- Added test in Kafka table source for validating offset commit is disabled without group id …
> [FLINK-24277][connector/kafka] And configuration for committing offset on checkpoint and disable it if group ID is not specified

- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriter.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/RequestEntryWrapper.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/ArrayListAsyncSink.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/AsyncSinkBaseITCase.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterTest.java
*User stories:*
* As a Sink user, I’d like to configure the batch size for items to send to the destination at once (e.g. “flush if there are x number of items in the batch”)
* As a Sink user, I’d like to configure the batching logic so that I can flush the batch of requests based on time period (e.g. “flush every 2 seconds”)
* As a Sink user I’d like to specify the number of bytes for the batch of requests to be flushed (e.g. ”submit the batch after the total number of bytes in it is above 1KB”) 
* As a Sink developer, I’d like to use the configuration mechanism provided to allow Sink users to configure my Sink implementation
*Context:*
The AsyncSinkWriter currently has a static batch size. We’d like to allow Sink users to specify what batch size they would like to use as they are in a …
> [FLINK-24234][connectors] FLIP-171: Adding Time & Byte Size Based Flushing to Async Sink Writer

- docs/layouts/shortcodes/generated/execution_config_configuration.html
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/config/ExecutionConfigOptions.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecSink.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecSink.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecSink.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/utils/RankProcessStrategy.java
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalJoin.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalSink.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/rules/logical/CalcRankTransposeRule.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/rules/logical/TemporalJoinRewriteWithUniqueKeyRule.scala
- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/factories/TestValuesRuntimeFunctions.java
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/TableSinkTest.xml
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/join/JoinTest.xml
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/TableSinkTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/join/JoinTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/TableSinkITCase.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/sink/SinkUpsertMaterializer.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/operators/sink/SinkUpsertMaterializerTest.java
Cherry-pick #16239
After FLINK-22901.
We can use upsert keys to fix upsert join, upsert rank, and upsert sink.
- For join and rank: if input has no upsert keys, do not use upsert optimization.
- For upsert sink: if input has unique keys but no upsert keys, we need add a materialize operator to produce upsert records.
- Join should use upsert keys instead of unique keys to do upsert
- Rank should use upsert keys instead of unique keys to do upsert
- TemporalJoin should use upsert keys instead of unique keys to do upsert
- Introduce materialize operator to produce upsert records before sink.
- UpsertTest
- UpsertITCase
- The …
> [FLINK-23054][table-blink] Correct upsert optimization by upsert keys

- docs/content.zh/docs/ops/metrics.md
- docs/content/docs/deployment/memory/network_mem_tuning.md
- docs/content/docs/ops/metrics.md
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricNames.java
Fixed a typo in a metric name.
> [hotfix] Fix a typo in 'estimatedTimeToConsume(r)BuffersMs'

- flink-connectors/flink-connector-pulsar/pom.xml
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/topic/TopicRange.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/topic/range/FixedRangeGenerator.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/PulsarTestContext.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/PulsarTestEnvironment.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/PulsarTestSuiteBase.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/cases/MultipleTopicTemplateContext.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/PulsarRuntime.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/PulsarRuntimeOperator.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/container/PulsarContainerRuntime.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/mock/PulsarMockRuntime.java
- flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/flink/FlinkContainerTestEnvironment.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/pom.xml
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/PulsarSourceOrderedE2ECase.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/PulsarSourceUnorderedE2ECase.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/cases/ExclusiveSubscriptionContext.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/cases/FailoverSubscriptionContext.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/cases/KeySharedSubscriptionContext.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/cases/SharedSubscriptionContext.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/common/FlinkContainerWithPulsarEnvironment.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/common/KeyedPulsarPartitionDataWriter.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/common/UnorderedSourceTestSuiteBase.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/resources/log4j2-test.properties
- flink-end-to-end-tests/pom.xml
Write a test application using Pulsar Source and execute it in distributed fashion. Check fault-tolerance by crashing and restarting a TM.
Ideally, we test different subscription modes and sticky keys in particular.
* Change the testutils in pulsar connector for using in container.
* Create pulsar e2e tests which supports four types of subscription.
- *Added integration tests for end-to-end tests from pulsar to flink. …
> [FLINK-23969][connector/pulsar] Create e2e tests for pulsar connector.

- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamConfigChainer.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
*This PR resolves the problem with closing the OutputFlusher when an exception happens before the task restore.*
- *New method `init` for RecordWriter created*
- *Moved the INITIALIZING transition under cleanUp try-catch block*
- *Added tests for initialization of RecordWriter *
- *Added test for check closing of OutputFlusher from Task* …
> [FLINK-11250][runtime] Added method init for RecordWriter for initialization resources(OutputFlusher) outside of constructor

- flink-end-to-end-tests/flink-streaming-kafka-test/src/main/java/org/apache/flink/streaming/kafka/test/KafkaExample.java
- flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/statemachine/KafkaEventsGeneratorJob.java
- flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/statemachine/StateMachineExample.java
- flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/statemachine/kafka/EventDeSerializationSchema.java
- flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/statemachine/kafka/KafkaStandaloneGenerator.java
> [BP-1.14][FLINK-24292][connectors/kafka] Use KafkaSink in examples instead of FlinkKafkaProducer

- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/enumerator/topic/TopicRangeTest.java
Backport of #17159
* The randomizer was removed from the test
> [BP-1.14][FLINK-24129][connectors-pulsar] Harden TopicRangeTest.rangeCreationHaveALimitedScope.

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorTest.java
> [FLINK-24300][bp-1.14] SourceOperator#getAvailableFuture reuses future

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorTest.java
Callers of SourceOperator#getAvailableFuture might call the method
multiple times even if the returned future does not complete. Before the
commit each we were creating a new combined future from the
SourceReader#isAvailable and the forcedStop one. If the underlying
SourceReader#isAvailable has not changed this operation is unnecessary.
What is even worse each such operation adds another entry onto the
source reader's availability future stack which caused performance
regression.
The commit reuses the combined future if the underlying
SourceReader#isAvailable future has not changed.
Added a test `org.apache.flink.test.streaming.runtime.SourceNAryInputChainingITCase#testIdlingSource` …
> [FLINK-24300] SourceOperator#getAvailableFuture reuses future

- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/snapshot/RocksIncrementalSnapshotStrategy.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/snapshot/RocksIncrementalSnapshotStrategyTest.java
*This pull is to adapt FLINK-23949’s unit test in Flink 1.12*
- *https://issues.apache.org/jira/browse/FLINK-23949*
- *https://github.com/apache/flink/pull/16969*
- The serializers:  no 
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: yes 
> FLINK-23949 adapt to Flink1.12

- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/AbstractStateChangeLogger.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/KvStateChangeLoggerImpl.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/PriorityQueueStateChangeLoggerImpl.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/StateChangeLogger.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/restore/ChangelogBackendLogApplier.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/restore/ChangelogBackendRestoreOperation.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/restore/StateID.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogPqStateTest.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/KvStateChangeLoggerImplTest.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/PriorityQueueStateChangeLoggerImplTest.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/StateChangeLoggerTestBase.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/TestChangeLoggerKv.java
This PR optimizes writing of state changes in `ChangelogKeyedStateBackend`.
Currently, state name and type are written with every change.
With this change, only a short ID of state is written every time; the mapping from this ID to name and type is written before the first write.
The change is split into three commits to ease reviewing. They could be squashed together upon merging.
An alternative approach would be to sort changes in each write batch and write common part once.
That would minimize writing of keys and namespaces.
However, it has some drawbacks:
- writing again in every batch
- more complex writer interface - it must be aware of ns/keys as well as serializers (they differ per call because different state of of the same backend have different serializers)
- more complex …
> [FLINK-22944][state] Optimize writing state changelog

- docs/content.zh/docs/connectors/table/upsert-kafka.md
- docs/content/docs/connectors/table/upsert-kafka.md
The current Table API upsert-kafka docs page wrongly links to the DataStream kafka connector for available metadata, however, it should link to the Table API kafka connector instead.
- fix links in the English and Chinese docs pages
> [hotfix][docs] fix link from upsert-kafka to kafka Table(!) connector

- flink-runtime/src/main/java/org/apache/flink/runtime/rest/FileUploadHandler.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/MultipartUploadResource.java
This PR adds a defense mechanism against https://github.com/netty/netty/issues/11668.
If the CRLF prefix of a multipart delimiter is split across 2 chunks an exception is thrown because Netty incorrectly treats CR as data.
If CR is the last byte of the current chunk, then we pessimistically assume that this case occurred.
We exclude the trailing CR from the current chunk, and add it to the front of the next received chunk.
> [FLINK-24197] Guard against CLRF being split across chunks

- flink-core/src/main/java/org/apache/flink/util/NetUtils.java
- flink-core/src/test/java/org/apache/flink/util/NetUtilsTest.java
- flink-examples/flink-examples-streaming/src/test/java/org/apache/flink/streaming/test/socket/SocketWindowWordCountITCase.java
- flink-runtime/src/main/java/org/apache/flink/runtime/blob/BlobServer.java
- flink-runtime/src/test/java/org/apache/flink/runtime/blob/TestingFailingBlobServer.java
- flink-runtime/src/test/java/org/apache/flink/runtime/net/ConnectionUtilsTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/RestClientTest.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectSinkFunction.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/experimental/SocketStreamIterator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/functions/sink/SocketClientSinkTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/functions/source/SocketTextStreamFunctionTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/collect/CollectSinkOperatorCoordinatorTest.java
- flink-test-utils-parent/flink-test-utils/src/test/java/org/apache/flink/networking/EchoServer.java
When running on JDK11 [JDK-8237858](https://bugs.openjdk.java.net/browse/JDK-8237858) can cause SocketTimeoutExceptions to be thrown during
ServerSocket.accept() calls, even when configured with an infinite timeout.
This change works around this issue by catching these erroneous exceptions
and retrying indefinitely.
- Added `acceptWithoutTimeout` method to `NetUtils` that calls `ServerSocket.accept()` and suppresses `SocketTimeoutException`s. Added a unit test to cover the new method.
- Migrated all `ServerSocket.accept()` calls to use `acceptWithoutTimeout`, with exception to the `EchoServer` test as it sets an explicit timeout.
- Added unit test to verify `acceptWithoutTimeout` suppresses `SocketTimeoutException`s.
- Most …
> [FLINK-24156][runtime/network] Catch erroneous SocketTimeoutExceptions and retry

- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
Resolves an issue where the dispatcher was logging the last restart cause for canceled/finished jobs, which is quite confusing behavior.
> [FLINK-24340] Only print exception if job failure/suspension

- docs/content.zh/docs/deployment/filesystems/s3.md
- docs/content/docs/deployment/filesystems/s3.md
Document fix described in [FLINK-24159](https://issues.apache.org/jira/browse/FLINK-24159).
alter the checkpoint directory in document of [entropy-injection-for-s3-file-systems](https://ci.apache.org/projects/flink/flink-docs-master/docs/deployment/filesystems/s3/#entropy-injection-for-s3-file-systems)  to "s3://my-bucket/_entropy_/checkpoints/dashboard-job/" (make entropy key at start of keys).
Not needed. …
> [FLINK-24159][docs][Runtime/Checkpointing] document of entropy injection may mislead users

- flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroRowDeserializationSchema.java
* The variable actualSchema is declared but not used.
* Removed unused variable.
> [hotfix][flink-avro] Use local actual schema variable

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/KubernetesResourceManagerDriver.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/Fabric8FlinkKubeClient.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/FlinkKubeClient.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/KubernetesResourceManagerDriverTest.java
*(or)*
*(or)*
*(example:)*
- *Extended …
> [FLINK-24315][k8s] Throw exception in failing watching pods

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/KubernetesResourceManagerDriver.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/Fabric8FlinkKubeClient.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/FlinkKubeClient.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/KubernetesResourceManagerDriverTest.java
*(or)*
*(or)*
*(example:)*
- *Extended …
> [BP-1.14][FLINK-24315][k8s] Throw exception in failing watching pods

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/KubernetesResourceManagerDriver.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/Fabric8FlinkKubeClient.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/FlinkKubeClient.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/KubernetesResourceManagerDriverTest.java
*(or)*
*(or)*
*(example:)*
- *Extended …
> [BP-1.13][FLINK-24315][k8s] Throw exception in failing watching pods

- docs/layouts/shortcodes/generated/checkpointing_configuration.html
- docs/layouts/shortcodes/generated/common_state_backends_section.html
- flink-core/src/main/java/org/apache/flink/configuration/CheckpointingOptions.java
- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogOptions.java
- flink-python/pyflink/datastream/stream_execution_environment.py
- flink-python/pyflink/datastream/tests/test_stream_execution_environment.py
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogStateBackendLoadingTest.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironmentComplexConfigurationTest.java
- flink-streaming-scala/src/main/scala/org/apache/flink/streaming/api/scala/StreamExecutionEnvironment.scala
- pom.xml
This reverts commits:
- d6bccd13190f0dbb2505b4512a38ae71b3d78195
- b4c385e41832f16e39d5cbe4fb69ead9bbe077b2
- 67dd4932133d74d88666433d4d8aa4a6cbc94c78
> [FLINK-23950] Revert [FLINK-23738][state] to re-enable ChangelogBackend

- docs/content.zh/docs/connectors/datastream/pulsar.md
- docs/content/docs/connectors/datastream/pulsar.md
Correct the pulsar connector document.
- Remove the explicit requirement of `flink-connector-base`
- Add the missing `StartCursor` in the English document.
> [hotfix][docs] Remove the explicit requirement of flink-connector-base in pulsar connector document

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/PendingCheckpoint.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/ManualCheckpointITCase.java
The checkpoint stats are updated after the corresponding future for a
checkpoint is completed. Therefore we might retrieve the old stats that
do not reflect the just completed checkpoint yet. In this commit we do
retry until we reach the desired number of checkpoints. …
>  [FLINK-24374] Retry querying for checkpoint stats 

- flink-core/src/main/java/org/apache/flink/api/connector/sink/SinkWriter.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/AbstractCommitterHandler.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/BatchCommitterHandler.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterHandler.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/ForwardCommittingHandler.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/NoopCommitterHandler.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/SinkOperator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperatorTest.java
Before this change, if no committer was after the SinkWriter in the pipeline preCommit was never called. With this change, preCommit is now called as well but the return values are discarded as before.
- Call the passed lambda in NoopCommitHandler 
- Added a test to ensure that preCommit is called if the Sink is configured without a commiter
- …
> [FLINK-24371][datastream] Call preCommit on SinkWriter although no committer is available

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/resources/KubernetesPod.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/resources/KubernetesPodTest.java
*(or)*
*(or)*
*(example:)*
- *Extended …
> [FLINK-24380][k8s] Terminate the pod if it failed

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/resources/KubernetesPod.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/resources/KubernetesPodTest.java
*(or)*
*(or)*
*(example:)*
- *Extended …
> [BP-1.14][FLINK-24380][k8s] Terminate the pod if it failed

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/resources/KubernetesPod.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/resources/KubernetesPodTest.java
*(or)*
*(or)*
*(example:)*
- *Extended …
> [BP-1.13][FLINK-24380][k8s] Terminate the pod if it failed

- flink-end-to-end-tests/test-scripts/kafka-common.sh
- flink-end-to-end-tests/test-scripts/test_confluent_schema_registry.sh
- flink-end-to-end-tests/test-scripts/test_pyflink.sh
- flink-end-to-end-tests/test-scripts/test_sql_client.sh
* Upgrade the used Confluent Platform OSS version in the Bash end-to-end tests to remove Scala 2.11 reference and match with used Kafka version in the tests according to https://docs.confluent.io/platform/current/installation/versions-interoperability.html
* Bumped Confluent Platform OSS version to match with the Kafka version that's used by the test
* Using Scala 2.12 version instead of Scala 2.11 version, which now matches with Kafka (which already uses 2.12), unless the needed Confluent Platform OSS version is 6.x: then it will use the available version (there are no separate Scala versions as of version 6)
* Since Confluent Platform was renamed from `oss` to `community`, also updated the URL
- Dependencies (does …
> [FLINK-24410] Upgrade Confluent Platform OSS version in end-to-end tests

- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionDriver.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderretrieval/ZooKeeperLeaderRetrievalDriver.java
- flink-runtime/src/main/java/org/apache/flink/runtime/util/ZooKeeperUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderretrieval/ZooKeeperLeaderRetrievalConnectionHandlingTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderretrieval/ZooKeeperLeaderRetrievalTest.java
Backport of #17150 to `release-1.14`.
> [BP-1.14][FLINK-24117][HA]Remove unHandledErrorListener in ZooKeeperLeaderElectionDriver and ZooKeeperLeaderRetrievalDriver

- flink-rpc/flink-rpc-akka-loader/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaRpcSystemLoader.java
- flink-rpc/flink-rpc-akka-loader/src/main/java/org/apache/flink/runtime/rpc/akka/CleanupOnCloseRpcSystem.java
- flink-rpc/flink-rpc-akka-loader/src/test/java/org/apache/flink/runtime/rpc/akka/FallbackAkkaRpcSystemLoader.java
- flink-rpc/flink-rpc-akka-loader/src/test/resources/META-INF/services/org.apache.flink.runtime.rpc.RpcSystemLoader
- flink-rpc/flink-rpc-core/src/main/java/org/apache/flink/runtime/rpc/RpcSystem.java
- flink-runtime/pom.xml
- flink-test-utils-parent/flink-test-utils/pom.xml
This PR adds a fallback loader for the akka rpc system, primarily for running tests in the IDE after a clean rebuild _in the IDE_. In that scenario the jars expected by the default loader are not present (in fact no jar is...).
This new loader will invoke maven to fetch the dependencies of flink-rpc-akka, and construct a classloader from them.
This is very much just a band-aid. It is only for Flink developers and you need to explicitly opt-in (aka, you (and users) cannot affected accidentally).
> [FLINK-24367][tests] Add FallbackAkkaRpcSystemLoader 

- flink-rpc/flink-rpc-akka-loader/pom.xml
We now copy the rpc-akka jar in package phase. This allows developers to run `mvn clean compile/test` (and anything in-between) as we no longer require the jar to be present.
> [FLINK-24445][build] Copy rpc-akka jar in package phase

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReader.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReaderTest.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/core/testutils/CommonTestUtils.java
The test `KafkaSourceReaderTest.testOffsetCommitOnCheckpointComplete` is flaky according to the test failure history in [FLINK-20928](https://issues.apache.org/jira/browse/FLINK-20928). This PR attempts to fix this flaky test.
Here are the problems with the existing code that could explain why the test is flaky:
1) The test calls `KafkaSourceReader.notifyCheckpointComplete(...)` once and expects the offset commit to be successful. 
2) However, `KafkaSourceReader.notifyCheckpointComplete(...)` does not guarantee the offset commit to be successfully. This is because it calls `KafkaConsumer.commitAsync(...)` just once and won't retry even if the commit fails with an retriable exception.
3) During in the test, if the coordinator is temporarily unavailable due to e.g. coordinator movement or …
> [FLINK-20928] Fix flaky test by retrying notifyCheckpointComplete until either commit success or timeout

- flink-table/flink-table-code-splitter/src/main/java/org/apache/flink/table/codesplit/JavaCodeSplitter.java
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/InputFormatCodeGenerator.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CodeSplitITCase.scala
Currently `VALUES` clause are implemented using `switch` java statements. However the java code splitter module does not handle `switch` statements. To enable code splitting for `VALUES` clause, this PR changes the implementation from `switch` to `if`.
- Enable code splitting for large number of VALUES clause. …
> [FLINK-24408][table-planner] Enable code splitting for large number of VALUES clause

- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/ScalarOperatorsTest.scala
(This PR is cherry-picked from #17497)
Currently when comparing timestamp_ltz type with random strings a NullPointerException will be thrown. This PR fixes this bug.
- Fix NullPointerException when comparing timestamp_ltz with random string …
> [FLINK-24563][table-planner] Fix NullPointerException when comparing timestamp_ltz with random string

- flink-tests/pom.xml
Removes a dependency to simplify the dependency graph. From now on you only need to build flink-runtime-web when dealing with flink-dist/flink-docs.
> [FLINK-24720][tests] Remove flink-runtime-web dependency

- pom.xml
Run scalastyle in the same phase as other source QA plugins like checkstyle/spotless. This makes it easier to run locally because you don't have to go through the packaging step again.
> [FLINK-24699][build] Run scalastyle in validate phase

- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/DeduplicateFunctionHelper.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/window/RowTimeWindowDeduplicateOperatorBuilder.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/window/combines/RowTimeDeduplicateRecordsCombiner.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/window/processors/RowTimeWindowDeduplicateProcessor.java
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/deduplicate/window/RowTimeWindowDeduplicateOperatorTest.java
This pull request aims to implement streaming row time window deduplicate operator
- Add `RowTimeDeduplicateRecordsCombiner` which stores the first/last records of incremental input records into the window state
- Add `RowTimeWindowDeduplicateProcessor` for rowtime window deduplicate.
- Add `RowTimeWindowDeduplicateOperatorBuilder` to build a SlicingWindowOperator for row time window deduplicate.
- Add harness test `RowTimeWindowDeduplicateOperatorTest` …
> [FLINK-23015][table-runtime-blink] Implement streaming window Deduplicate operator

- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/filesystem/FileSystemTableSink.java
Currently the output format created in `FileSystemTableSink#createBulkWriterOutputFormat` only finishes the `BulkWriter` and does not close the output stream. This will cause some problems with some file systems for example HDFS.
- Close output stream in batch SQL file sink. …
> [FLINK-24728][table-runtime] Close output stream in batch SQL file sink

- docs/content/docs/connectors/datastream/kafka.md
This pull request fixes documentation examples for the kafka producer by replacing the SimpleStringSchema with KafkaSerializationSchema
- A new KafkaSerializationSchema is created with basic topic and record content filling
- A newly created KafkaSerializationSchema is passed as the serialization schema to the FlinkKafkaProducer constructor
This change does not affect any tests since it is an update to the documentation.
- The S3 …
> [FLINK-24509][docs] Add kafka serializer to producer examples

- flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaInvocationHandler.java
- flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/AkkaRpcActorTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/heartbeat/HeartbeatManagerImpl.java
- flink-tests/src/test/java/org/apache/flink/test/recovery/TaskManagerProcessFailureBatchRecoveryITCase.java
Fixes an issue where issues during the deserialization of RPC messages were silently ignored. We now forward the error to the returned future instead.
@tillrohrmann Could you take a look?
> [FLINK-24706][rpc] Forward deserialization errors to returned future

- flink-rpc/flink-rpc-akka/pom.xml
Maven does not properly resolve `dependencyManagement` entries if the parent/child module declare one for the same dependency with different properties being used in the `artifactId.` Our builds were only as expected because we were accidentally using the plain `scala.binary.version` property for `parser-combinators.`
Hence we unfortunately need to use the same property names, which should however not cause issues in the future (if say, a 2.13 profile is introduced), because the properties defined in the child take precedence.
> [FLINK-24609][akka][build] Use same Scala properties as root pom

- flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaInvocationHandler.java
- flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/ContextClassLoadingSettingTest.java
We now use the Flink ClassLoader to deserialize the message payload. This should be safe because this serialization only occurs for results from the Flink layer, not the Akka RPC layer (where the Akka classloader would be required for deserialization).
> [FLINK-24550][rpc] Use ContextClassLoader for message deserialization 

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointStatsTracker.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraphBuilder.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointStatsTrackerTest.java
The CheckpointCoordinatorConfiguration was unnecessarily stored in the CheckpointStatsTracker. We can store it directly in the ExecutionGraph instead.
This simplifies the tracker, and opens up the possibility to reuse the tracker across execution graphs for FLINK-21510.
> [FLINK-24748] Remove CheckpointStatsTracker#getJobCheckpointingConfiguration

- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/harness/RankHarnessTest.scala
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/UpdatableTopNFunction.java
Fix the exception when the input record loses monotonicity on the sort key field of UpdatableTopNFunction
This change is already covered by RankHarnessTest
> [FLINK-24704][table] Fix exception when the input record loses monotonicity on the sort key field of UpdatableTopNFunction

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorDeActivator.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/JobStatusListener.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/GloballyTerminalJobStatusListener.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/SchedulerTestingUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerBuilder.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
The error is not currently used anywhere and makes it harder to add more uses of the interface.
Specifically I want to extend the AdaptiveScheduler to send the status updates, but doing that in a generic fashion without having to touch all scheduler states isn't currently possible because the existence of a failure cause is an implementation detail of the satte.
> [FLINK-24770] Remove error from JobStatusListener

- docs/content/docs/ops/rest_api.md
- docs/layouts/shortcodes/generated/rest_v1_dispatcher.html
- flink-clients/src/main/java/org/apache/flink/client/program/rest/RestClusterClient.java
- flink-clients/src/test/java/org/apache/flink/client/program/rest/RestClusterClientSavepointTriggerTest.java
- flink-runtime-web/src/test/resources/rest_api_v1.snapshot
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/savepoints/SavepointHandlers.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/savepoints/SavepointTriggerRequestBody.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/savepoints/stop/StopWithSavepointRequestBody.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/job/savepoints/SavepointHandlersTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/job/savepoints/StopWithSavepointHandlersTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/messages/SavepointHandlerRequestBodyTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/messages/job/savepoints/SavepointTriggerRequestBodyTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/messages/job/savepoints/StopWithSavepointTriggerRequestBodyTest.java
With this PR users can provide the triggerId when triggering a (stop-with-)savepoint. This effectively allows users to safely retry a savepoint operation within the caching interval.
The runtime already handles this appropriately.
> [FLINK-24208][rest] Support user-supplied Savepoint triggerId

- flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/flink/FlinkDistribution.java
- flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/flink/FlinkResourceSetup.java
- flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/flink/JarAddition.java
- flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/flink/JobSubmission.java
- flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/flink/LocalStandaloneFlinkResource.java
- flink-end-to-end-tests/flink-end-to-end-tests-scala/pom.xml
- flink-end-to-end-tests/flink-end-to-end-tests-scala/src/main/java/org/apache/flink/tests/scala/JavaJob.java
- flink-end-to-end-tests/flink-end-to-end-tests-scala/src/main/java/org/apache/flink/tests/scala/JavaJobWithKryoSerializer.java
- flink-end-to-end-tests/flink-end-to-end-tests-scala/src/main/java/org/apache/flink/tests/scala/NonPojo.java
- flink-end-to-end-tests/flink-end-to-end-tests-scala/src/main/java/org/apache/flink/tests/scala/NonPojoSerializer.java
- flink-end-to-end-tests/flink-end-to-end-tests-scala/src/main/scala/org/apache/flink/tests/scala/ScalaJob.scala
- flink-end-to-end-tests/flink-end-to-end-tests-scala/src/test/java/org/apache/flink/tests/scala/ScalaFreeITCase.java
- flink-end-to-end-tests/flink-end-to-end-tests-scala/src/test/resources/log4j2-test.properties
- flink-end-to-end-tests/pom.xml
This PR adds an e2e test for the Scala-free job execution.
It covers cases where the flink-scala jar was removed from lib/ and:
a) a Java job is run
b) a Java job is run with a custom KryoSerializer (for completeness sake because we touched Kryo)
c) Scala 2.11 is manually added to lib/, after which Scala job is run that uses the Java APIs.
> [FLINK-24603][e2e] Add test for Scala-free Flink 

- flink-connectors/flink-connector-elasticsearch5/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-elasticsearch6/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-elasticsearch7/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-kinesis/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-azure-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE
- flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE
- flink-formats/flink-sql-avro/src/main/resources/META-INF/NOTICE
- flink-kubernetes/src/main/resources/META-INF/NOTICE
- flink-python/src/main/resources/META-INF/NOTICE
- flink-table/flink-table-planner/pom.xml
- flink-table/flink-table-planner/src/main/resources/META-INF/NOTICE
- pom.xml
* Update multiple Jackson dependencies to the latest version
* Excluded module-info.class from Table API JAR
- The runtime per-record code paths (performance sensitive): (yes / no / **don't know**) …
> [FLINK-24715][connectors][filesystems][formats] Update multiple Jackson dependencies to v2.13.0

- flink-formats/flink-avro-glue-schema-registry/pom.xml
- flink-formats/flink-json-glue-schema-registry/pom.xml
- pom.xml
* Update testcontainers dependency to the latest version for various improvements
* Updated POM
* Excluded org.jetbrains:annotations from com.kjetland:mbknor-jackson-jsonschema to address dependency convergence on glue-schema-registry:
```
Dependency convergence error for org.jetbrains:annotations:13.0 paths to dependency are:
+-org.apache.flink:flink-json-glue-schema-registry_2.12:1.15-SNAPSHOT
+-com.kjetland:mbknor-jackson-jsonschema_2.12:1.0.39
+-org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.3.50
+-org.jetbrains.kotlin:kotlin-stdlib:1.3.50
+-org.jetbrains:annotations:13.0
and
+-org.apache.flink:flink-json-glue-schema-registry_2.12:1.15-SNAPSHOT
+-org.testcontainers:junit-jupiter:1.16.2
+-org.testcontainers:testcontainers:1.16.2
+-org.rnorth.duct-tape:duct-tape:1.0.8 …
```
> [FLINK-24740][testinfrastructure] Update testcontainers dependency to v1.16.2

- flink-core/src/main/java/org/apache/flink/util/function/CachingSupplier.java
- flink-core/src/test/java/org/apache/flink/util/function/CachingSupplierTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraphBuilder.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultExecutionGraphFactory.java
- flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/TestingDefaultExecutionGraphBuilder.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerClusterITCase.java
The AdaptiveScheduler now reuses the CheckpointStatsTracker for each ExecutionGraph created during rescaling. This resolves the issue of metric collisions as they are now only registered once, and has the additional benefit that we now retain the checkpoint history after a rescaling.
> [FLINK-24749][coordination] Reuse CheckpointStatsTracker 

- docs/content.zh/docs/connectors/datastream/kafka.md
- docs/content/docs/connectors/datastream/kafka.md
There is no setDeliveryGuarantee method in KafkaRecordSerializationSchemaBuilder class, but it is in KafkaSinkBuilder class and the method is setDeliverGuarantee
change setDeliveryGuarantee(DeliveryGuarantee.AT_LEAST_ONCE) to setDeliverGuarantee(DeliveryGuarantee.AT_LEAST_ONCE) …
> [hotfix][docs]fix kafka datastream connector mistake

- flink-connectors/flink-connector-jdbc/pom.xml
* Update Postgres and Postgres test dependencies to latest version, currently used by JDBC connector
* Updated dependencies in POM …
> [FLINK-24719][jdbc] Update Postgres test dependencies to 0.13.4

- tools/azure-pipelines/create_build_artifact.sh
Exclude javadocs and the runtime-web node[_modules] directory from the CI compile artifact.
This reduces the amount of data that needs to be fetched to about a third.
Before:
```
Download statistics:
Total Content: 1,565.1 MB
Physical Content Downloaded: 469.4 MB
Compression Saved: 1,095.7 MB
```
After:
```
Download statistics:
Total Content: 410.3 MB
Physical Content Downloaded: 151.6 MB
Compression Saved: 258.7 MB
```
> [FLINK-24796][ci] Reduce size of compile build artifact

- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerRunner.java
This PR fix the bug of TM cannot exit after Metaspace OOM. You can get more details in JIRA.
When Metaspace OOM, call terminateJVM() directly.
> [FLINK-24401][runtime] Fix the bug of TM cannot exit after Metaspace OOM

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/RemoteInputChannel.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGate.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/InputChannelTestUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/LocalInputChannelTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/RemoteInputChannelTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateTest.java
*This PR fixes IllegalStateException during  new buffer size announcement when the channel is released already*
- *Ignore announcement new buffer size if the channel is released*
- *Added new test in LocalInputChannelTest*
- Does …
> [FLINK-24738][runtime] Ignoring buffer size announcement if the channel is released already

- flink-dist/src/main/resources/META-INF/NOTICE
- pom.xml
* Update commons-cli dependency to latest available version
* Bumped commons-cli:commons-cli:1.4 to commons-cli:commons-cli:1.5.0 …
> [FLINK-24798][cli] Bump commons-cli to v1.5.0

- flink-filesystems/flink-s3-fs-presto/pom.xml
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE
* Update hadoop-apache2 dependency for Presto Hadoop
* Upgraded com.facebook.presto.hadoop:hadoop-apache2 from 2.7.3-1 to 2.7.4-9 …
> [FLINK-24665][s3] Update Presto Hadoop dependency to v2.7.4-9

- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/harness/RankHarnessTest.scala
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/RetractableTopNFunction.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/UpdatableTopNFunction.java
This pr cherry-pick FLINK-24704 & FLINK-24654  from master to release-1.14
Fix the exception when the input record loses monotonicity on the sort key field of UpdatableTopNFunction
This change is already covered by RankHarnessTest
> [FLINK-24704][table] Fix exception when the input record loses monotonicity on the sort key field of UpdatableTopNFunction 

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateCheckpointWriter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestExecutorImpl.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/ttl/mock/MockKeyedStateBackend.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/ttl/mock/MockKeyedStateBackendBuilder.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/ttl/mock/MockOperatorStateBackend.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/ttl/mock/MockStateBackend.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointFailureHandlingITCase.java
Fix error handling in `ChannelStateCheckpointWriter`.
The change is split into 4 commits to ease reviewing;
before merging they should be squashed.
Added `UnalignedCheckpointFailureHandlingITCase`.
> [FLINK-24667][runtime] Fix error handling in ChannelStateCheckpointWriter

- flink-clients/src/main/java/org/apache/flink/client/program/DefaultPackagedProgramRetriever.java
- flink-clients/src/test/java/org/apache/flink/client/program/DefaultPackagedProgramRetrieverTest.java
Backport of #14891 to `release-1.14`.
> [BP-1.14][FLINK-21289][deployment] FIX missing load pipeline.classpaths in application mode, for both k8s and yarn

- flink-connectors/flink-connector-rabbitmq/pom.xml
- flink-connectors/flink-sql-connector-rabbitmq/src/main/resources/META-INF/NOTICE
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/util/DockerImageVersions.java
* Update RabbitMQ Java client to the latest available version
* Updated com.rabbitmq:amqp-client from 5.9.0 to 5.13.1 …
> [FLINK-24816][rabbitmq] Bump amqp-client to v5.13.1

- pom.xml
* Update Powermock to the latest available version (currently v2.0.9) …
> [FLINK-24828][tests][testinfrastructure] Bump Powermock to v2.0.9

- flink-connectors/flink-connector-jdbc/pom.xml
* Update JDBC test dependencies to the latest versions
* Bumped org.mariadb.jdbc:mariadb-java-client from 2.5.4 to 2.7.4
* Bumped mysql:mysql-connector-java from 8.0.20 to 8.0.27 …
> [FLINK-24771][jdbc][tests] Bump test dependencies mariadb-java-client to 2.7.4 and mysql-connector-java to 8.0.27

- flink-python/pyflink/pyflink_gateway_server.py
- pom.xml
* Bump maven-dependency-plugin to latest available version (3.2.0)
* Updated POM to use new version 3.2.0
* Changed outdated version used in PyFlink also to 3.2.0 …
> [FLINK-24827][buildsystem] Bump maven-dependency-plugin to v3.2.0

- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceTest.java
Fix RMQSourceTest.testRedeliveredSessionIDsAck that fails on azure due to a race condition, described in [FLINK-23696](https://issues.apache.org/jira/browse/FLINK-23696)
Fix the unit test by moving the asserts into a synchronized code block. …
> [FLINK-23696][connectors/rabbitmq] Fix RMQSourceTest.testRedeliveredSessionIDsAck

- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceTest.java
This is a backport of #17708 (fixing FLINK-23696) to release-1.13. The fix is exactly the same as in #17708.
Please see #17708 for a detailed description.
> [BP-1.13][FLINK-23696][connectors/rabbitmq] Fix RMQSourceTest.testRedeliveredSessionIDsAck

- docs/content.zh/docs/connectors/datastream/kinesis.md
- docs/content/docs/connectors/datastream/kinesis.md
- flink-connectors/flink-connector-kinesis/pom.xml
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/util/UniformShardAssigner.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/util/UniformShardAssignerTest.java
Add UniformShardAssigner to assign Kinesis shards to subtasks. This algorithm takes advantage of the Kinesis hash-key space that each shard occupies. By default, each shard is assigned an equal-sized range of hash-key space. And UpdateShardCount (with `UNIFORM_SCALING`) tries to preserve this. So we can nicely assign shards to subtasks by mapping through hash-key space.
However, some users may have customized how shards are distributed, such that they occupy ranges of hash-key space that vary greatly in size. For such users, the default shard assignment will likely work better. Hence, I have not changed the default here.
Please refer to the Jira ticket for a longer write-up, including performance comparison with the default assigner.
- Add UniformShardAssigner
- Unit testing for above
- …
> [FLINK-24639][kinesis] Add UniformShardAssigner

- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/src/AbstractFileSource.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/src/FileSource.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/src/impl/FileRecordFormatAdapter.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/src/reader/FileRecordFormat.java
- flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/src/impl/TestIntReader.java
The FileRecordFormat and StreamFormat have too much commons. This makes user confused. The main motivation for removing it is the inherent design flaw in the batching of FileRecordFormat: StreamFormat can guarantee that only a certain amount of memory is being used (unless a single record exceeds that already), but FileRecordFormat can only batch by the number of records. By removing FileRecordFormat, we relay the responsibility of implementing the batching to the format developer; they need to use BulkFormat and find a better way than batch by number of records.
- marked FileRecordFormat and FileRecordFormatAdapter as @Deprecated.
- refactored the relevant usages.
- updated javadoc.
This change only marked some classes as deprecated and update relevant comments without any test coverage. …
> [FLINK-24741]Deprecate FileRecordFormat

- flink-connectors/flink-connector-kafka/pom.xml
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/FlinkKafkaInternalProducer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaProducer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internals/FlinkKafkaInternalProducer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internals/metrics/KafkaMetricMutableWrapper.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internals/metrics/KafkaMetricWrapper.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/enumerator/KafkaEnumeratorTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaProducerITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaConsumerTestBase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestEnvironmentImpl.java
- flink-connectors/flink-sql-connector-kafka/src/main/resources/META-INF/NOTICE
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/pom.xml
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/KafkaSourceE2ECase.java
- flink-examples/flink-examples-build-helper/flink-examples-streaming-state-machine/src/main/resources/META-INF/NOTICE
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/util/DockerImageVersions.java
With dropping Scala 2.11 we can now finally upgrade our Kafka dependencies which is very important to ensure the stability of our tests because we were missing a few years of Kafka fixes.
- Bump Kafka version to 2.8
All tests are still passing …
> [FLINK-24765][kafka] Bump Kafka version to 2.8

- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarOrderedPartitionSplitReader.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarPartitionSplitReaderBase.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarUnorderedPartitionSplitReader.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarOrderedPartitionSplitReaderTest.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarPartitionSplitReaderTestBase.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarUnorderedPartitionSplitReaderTest.java
This pull request fix data loss when using flink pulsar source.
- Add invalid **CompletableFuture** cancel when poll messages.
- Add simple pulsar source e2e test
- The serializers: (don't know)
> [FLINK-24733][connector/pulsar] Data loss in pulsar source when using shared mode

- flink-runtime-web/web-dashboard/src/app/pages/job/exceptions/job-exceptions.component.html
- flink-runtime-web/web-dashboard/src/app/pages/job/job.module.ts
The dropdown menu introduced by [FLINK-21867](https://issues.apache.org/jira/browse/FLINK-21867) was not visualized due to missing imports. This issue is not present on `master`. It got fixed already as part of [903185d72c](https://github.com/apache/flink/commit/903185d72c#diff-b076916fff7fedff49389f5a54ec236ef413a1a43bc6a7b95406266d9fb12fe7R31). I added missing Modules to the imports to fix that.
* Adds tooltip, select and icon modules
* Updates the corresponding HTML code accordingly
This change was tested manually. …
> [FLINK-24874][runtime-web] Fixes missing dropdown menu introduced in FLINK-21867

- pom.xml
* Dependency updates for com.sun.xml.bind:jaxb-impl and com.sun.xml.bind:jaxb-core …
> [FLINK-24724][buildsystem] Update Sun XML Bind dependencies to v3.0.2

- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/State.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
The AdaptiveScheduler now informs the JobStatusListener of all state transitions. The current behavior of only reporting terminal states is surprising, and I intend to later hook into these notifications to capture the state timestamps directly in the AdaptiveScheduler for the job lifecycle metrics (FLINK-24775).
This change also sets up a contract that `State#getJobStatus` must return a constant value.
> [FLINK-24774] Adaptive scheduler notifies listeners for all job state transitions

- flink-runtime/src/test/java/org/apache/flink/runtime/rpc/RpcEndpointTest.java
Currently, `RpcEndpointTest.testCallAsyncTimeout` submits a task that is expected to time out,
but the timeout is not guaranteed: the time the main thread sleep can still be less than the
other thread waits for it for timeout.
This change makes the main thread to wait for a signal (latch) to enforce timeout
(the signel is only sent when the test finishes). …
> [FLINK-22419] Wait unlimited in RpcEndpointTest.testCallAsyncTimeout

- flink-runtime/src/test/java/org/apache/flink/runtime/rpc/RpcEndpointTest.java
> [BP-1.13][FLINK-22419] Wait unlimited in RpcEndpointTest.testCallAsyncTimeout

- flink-runtime/src/test/java/org/apache/flink/runtime/rpc/RpcEndpointTest.java
> [BP-1.12][FLINK-22419] Wait unlimited in RpcEndpointTest.testCallAsyncTimeout

- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/DispatcherCachedOperationsHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/async/CompletedOperationCache.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherCachedOperationsHandlerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/async/CompletedOperationCacheTest.java
With this PR we no longer check the result of a previous operation when a new one is trigger under the same key. This made error-handling more complicated and, in the case of application clusters, could lead to an early shutdown.
> [FLINK-24887][rest] Triggers do not check previous result 

- docs/layouts/shortcodes/generated/state_backend_configuration.html
- docs/layouts/shortcodes/generated/state_backend_latency_tracking_section.html
- flink-core/src/main/java/org/apache/flink/configuration/StateBackendOptions.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/metrics/LatencyTrackingStateConfigTest.java
*Enabling the `state.backend.latency-track.state-name-as-variable` by default could help improve the usablility of state access latency.*
- *Update the default value of the `state.backend.latency-track.state-name-as-variable` option to true.*
- *Update the `testDefaultEnabledLatencyTrackingStateConfig` test case in `LatencyTrackingStateConfigTest` to verify the default value of `state.backend.latency-track.state-name-as-variable` is true.* …
> [FLINK-24784][runtime] Enable state.backend.latency-track.state-name-as-variable by default

- flink-connectors/flink-file-sink-common/pom.xml
As example flink-connector-files brings flink-core with compile scope via flink-file-sink-common.
> [FLINK-24869][BuildSystem] flink-core should be provided in flink-file-sink-common

- flink-metrics/flink-metrics-prometheus/src/test/java/org/apache/flink/metrics/prometheus/PrometheusReporterTaskScopeTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/TaskManagerJobMetricGroup.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/TaskManagerMetricGroup.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/UnregisteredMetricGroups.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/TaskExecutorStateChangelogStoragesManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/NettyShuffleEnvironmentTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/InternalOperatorGroupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/MetricGroupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/TaskManagerGroupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/TaskManagerMetricGroupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/TaskMetricGroupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/chaining/ChainedOperatorsMetricTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/OneInputStreamTaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTestHarness.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/TwoInputStreamTaskTest.java
Release `TaskManagerJobMetricGroup﻿` on last job slot release to avoid issues when using it with `StateChangelogStorage`, which is released on last slot release (please see ticket description for more details).
- added `TaskExecutorTest.testReleasingJobResources`
- added `TaskManagerMetricGroupTest`
> [FLINK-24864][metrics] Release TaskManagerJobMetricGroup with the last slot rather than task

- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/FsStreamingSinkITCaseBase.scala
The test CsvFilesystemStreamSinkITCase.testPart times out on AZP.
```
2021-11-08T16:36:28.6542078Z Nov 08 16:36:28 org.junit.runners.model.TestTimedOutException: test timed out after 20 seconds
2021-11-08T16:36:28.6561998Z Nov 08 16:36:28 	at java.io.ObjectOutputStream.putFields(ObjectOutputStream.java:463)
2021-11-08T16:36:28.6581789Z Nov 08 16:36:28 	at java.util.Locale.writeObject(Locale.java:2156)
2021-11-08T16:36:28.6601916Z Nov 08 16:36:28 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-11-08T16:36:28.6621871Z Nov 08 16:36:28 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-11-08T16:36:28.6632222Z Nov 08 16:36:28 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) …
```
> [FLINK-24839][fs-connector] Increase Timeout of FsStreamingSinkITCaseBase to 240

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/KubernetesResourceManagerDriver.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/ExternalServiceDecorator.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/InternalServiceDecorator.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/factory/KubernetesJobManagerFactory.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesJobManagerParameters.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesParameters.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesTaskManagerParameters.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/KubernetesUtils.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/ExternalServiceDecoratorTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/InternalServiceDecoratorTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/factory/KubernetesJobManagerFactoryTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/parameters/AbstractKubernetesParametersTest.java
The PR is meant to use the minimal selector to select jobManager and taskManger pod.
> [FLINK-24631][Kubernetes]Use minimal selector to select jobManager and taskManager pod

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/KubernetesResourceManagerDriver.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/ExternalServiceDecorator.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/InternalServiceDecorator.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/factory/KubernetesJobManagerFactory.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesJobManagerParameters.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesParameters.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesTaskManagerParameters.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/KubernetesUtils.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/ExternalServiceDecoratorTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/InternalServiceDecoratorTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/factory/KubernetesJobManagerFactoryTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/parameters/AbstractKubernetesParametersTest.java
Backport #17685 to release-1.14.
> [BP-1.14][FLINK-24631][k8s] Use a stable subset of labels to select jobManager and taskManager pods

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/KubernetesResourceManagerDriver.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/ExternalServiceDecorator.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/InternalServiceDecorator.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/factory/KubernetesJobManagerFactory.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesJobManagerParameters.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesParameters.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesTaskManagerParameters.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/KubernetesUtils.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/ExternalServiceDecoratorTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/InternalServiceDecoratorTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/factory/KubernetesJobManagerFactoryTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/parameters/AbstractKubernetesParametersTest.java
Backport #17685 to release-1.13.
> [BP-1.13][FLINK-24631][k8s] Use a stable subset of labels to select jobManager and taskManager pods

- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/BatchingStateChangeUploader.java
- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogOptions.java
- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogStorage.java
- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/StateChangeUploader.java
- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/UploadThrottle.java
- flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/BatchingStateChangeUploaderTest.java
- flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/TestingStateChangeUploader.java
- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/runtime/SavepointTaskStateManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/StateChangelogStorage.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
Propagate back-pressure from changelog storage to (stream) task (record processing and checkpoionting).
The 1st commit replaces failing with blocking caller on reaching the limit.
The 2nd commit adds availability provider to StreamTask, so it shouldn't block in most cases. Checkpointing will still block.
The change wasn't benchmarked yet.
- `BatchingStateChangeUploaderTest.testBackPressure`
- `BatchingStateChangeUploaderTest.testInterruptedWhenBackPressured` …
> [FLINK-23381][state] Back-pressure on reaching state change to upload limit

- flink-end-to-end-tests/run-nightly-tests.sh
There's going to be a parsing issue reported if no parameter is passed due to
the if condition being rendered to [ == '1' ]. Adding the quotes fixes this
problem.
This is not really an issue in CI because we always pass a parameter. The `README.md`, though, still states calling this script without a parameter which reveals the issue.
Fixing this issue removes the warning that is printed when calling `flink-end-to-end-tests/run-nightly-tests.sh` without a parameter:
```
$ FLINK_DIR=build-target/ ./flink-end-to-end-tests/run-nightly-tests.sh
[...]
==============================================================================
Running bash end-to-end tests
==============================================================================
flink-end-to-end-tests/run-nightly-tests.sh: line 268: [: …
```
> [hotfix][e2e] Adds missing quotes

- docs/layouts/shortcodes/generated/deployment_configuration.html
- flink-clients/src/main/java/org/apache/flink/client/deployment/application/ApplicationDispatcherBootstrap.java
- flink-clients/src/test/java/org/apache/flink/client/deployment/application/ApplicationDispatcherBootstrapTest.java
- flink-core/src/main/java/org/apache/flink/configuration/DeploymentOptions.java
*Add a configuration option that allows to keep the cluster running after the application finishes in application mode. The default value is set to false (meaning that the cluster will shut down), so current behavior is unaffected.*
- *Added config option execution.shutdown-on-application-finish*
- *Refactored code in ApplicationDispatcherBootstrap and corresponding tests to make it easier to understand/modify and reduce duplication*
- *Added unit tests in ApplicationDispatcherBootstrapTest that verify cluster shutdown is not called if the configuration option is enabled*
- *Can be tested manually by starting a job in application mode with the new config option enabled, then cancelling the job. The cluster and Web UI stay alive and …
> [FLINK-24113] Add configuration option to disable automatic shutdown in application mode

- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraphBuilder.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultExecutionGraphFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/JobStatusStore.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
- flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/TestingDefaultExecutionGraphBuilder.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/JobStatusStoreTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
Based on #17722.
The down-/up-/restartTime metrics are now setup in the schedulersinstead of the ExecutionGraph, similar to the numRestart metrics.
To this end the AdaptiveScheduler now maintains its own set of state timestamps, according to the job state transitions that the scheduler advertises (i.e., they are not based on the ExecutionGraph).
This prevents collisions upon rescaling as they are now only registered once.
> [FLINK-24775][coordination] move JobStatus-related metrics out of ExecutionGraph

- docs/content.zh/docs/deployment/elastic_scaling.md
- docs/content.zh/docs/ops/metrics.md
- docs/content/docs/deployment/elastic_scaling.md
- docs/content/docs/ops/metrics.md
Applicable once #17735 is merged.
Updates the documentation w.r.t. metric limitations of the adaptive scheduler.
> [FLINK-24876][docs] Remove metrics limitation of Adaptive Scheduler

- flink-runtime-web/pom.xml
Upgrade frontend-maven-plugin to fix compilation issue on Apple M1
- change plugin version in pom.xml
Verified by compilation.
> [FLINK-24964] Upgrade frontend-maven-plugin

- flink-end-to-end-tests/test-scripts/common_docker.sh
> [BP-1.14][FLINK-24937][e2e] Return correct exit code in build_image

- flink-end-to-end-tests/test-scripts/common_docker.sh
> [FLINK-24937][e2e] Return correct exit code in build_image

- docs/content/docs/deployment/overview.md
- docs/content/docs/deployment/resource-providers/native_kubernetes.md
- docs/content/docs/deployment/resource-providers/standalone/docker.md
- docs/content/docs/deployment/resource-providers/standalone/kubernetes.md
- docs/content/docs/deployment/resource-providers/standalone/overview.md
- docs/content/docs/deployment/resource-providers/yarn.md
Backport of https://github.com/apache/flink/pull/17678
> [FLINK-24739][BP-1.14] Highlight the fact that the Application Mode excpects user jars to be bundled with the Flink distribution.

- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/stats/FlinkStatistic.scala
```
[ERROR] FlinkStatistic.scala:146: error: Int does not take parameters
[ERROR]     if (builder.nonEmpty && builder.length() > 2) {
```
> [FLINK-24991] FlinkStatistic compiles on later Scala versions

- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/utils/StreamingWithStateTestBase.scala
The `subSequence` method is no longer available for arrays.
The code in question was rewritten to just work on strings.
> [FLINK-24992] StreamingWithStateTestBase compiles on later Scala versions

- pom.xml
Use 3.2.4 on Java11+ for compatibility reasons.
> [FLINK-24989][build] Bump shade-plugin to 3.2.4

- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/utils/InMemoryLookupableTableSource.scala
The UserDefinedFunctionHelper validates that a given function is public.
The InMemory[Async]LookupFunction classes are not public however. Probably some Java<->Scala interplay that causes this to not be detected at this time.
> [FLINK-24990][tests] Make InMemory[Async]LookupFunction public

- pom.xml
Provides an opt-in switch to compile to Java 17 bytecode, similar to the java11-target profile.
Note that so far I have not tested at all what happens if you _don't_ use this profile with Java 17 (i.e., compile to Java 8).
> [FLINK-25005][build] Add java17-target profile

- flink-connectors/flink-connector-hbase-1.4/pom.xml
- flink-connectors/flink-connector-hbase-2.2/pom.xml
- flink-connectors/flink-connector-hbase-base/pom.xml
- flink-connectors/flink-connector-hive/pom.xml
- flink-end-to-end-tests/pom.xml
In FLINK-18455 we changed the java11 profile to also activate for all later Java versions. We only touched the root pom however, and forgot the other java11 profiles.
> [FLINK-24981][build] Fix profile activations for JDK 12+

- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateDownloaderTest.java
Anonymous StreamStateHandle classes are not allowed by the StateHandleSerializationTest.
> [FLINK-24986][tests] Replace anonymous StreamStateHandle class

- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/BatchingStateChangeUploader.java
- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/ChangelogStorageMetricGroup.java
- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogStorage.java
- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogStorageFactory.java
- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/RetryingExecutor.java
- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/StateChangeFsUploader.java
- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/StateChangeUploader.java
- flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/BatchingStateChangeUploaderTest.java
- flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/ChangelogStorageMetricsTest.java
- flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/FsStateChangelogStorageTest.java
- flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/RetryingExecutorTest.java
- flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/UnregisteredChangelogStorageMetricGroup.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/TaskManagerJobMetricGroup.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/TaskExecutorStateChangelogStoragesManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/StateChangelogStorageFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/StateChangelogStorageLoader.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/inmemory/InMemoryStateChangelogStorageFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/CollectingMetricsReporter.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/MetricRegistryImplTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/AbstractMetricGroupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/TaskMetricGroupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/TaskExecutorStateChangelogStoragesManagerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/changelog/inmemory/StateChangelogStorageLoaderTest.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogStateBackendTestUtils.java
Add metrics for Changelog uploader.
`BatchingStateChangeUploader`:
- Queue size (num requests)
- Logs per upload
- Attempts per upload
`StateChangeFsUploader`:
- Errors count
- Requests count
- Requests size
- Requests latency
These components are shared across tasks on TM (per job).
See [design doc](https://docs.google.com/document/d/1k5WkWIYzs3n3GYQC76H9BLGxvN3wuq7qUHJuBPR9YX0/edit?usp=sharing).
Added `ChangelogStorageMetricsTest`
- …
> [FLINK-23486][state][metrics] Add metrics for the Changelog uploader

- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/filesystem/LimitableBulkFormat.java
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/filesystem/LimitableBulkFormatTest.java
Exceptions in `ParquetFileSystemITCase.testLimitableBulkFormat`
```
2021-11-03T22:10:11.5215786Z Nov 03 22:10:11 Caused by: java.lang.IllegalStateException: Trying to access closed classloader. Please check if you store classloaders directly or indirectly in static fields. If the stacktrace suggests that the leak occurs in a third party library and cannot be fixed immediately, you can disable this check with the configuration 'classloader.check-leaked-classloader'.
2021-11-03T22:10:11.5217523Z Nov 03 22:10:11 	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$SafetyNetWrapperClassLoader.ensureInner(FlinkUserCodeClassLoaders.java:164)
2021-11-03T22:10:11.5218577Z Nov 03 22:10:11 	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$SafetyNe …
```
> [FLINK-24763][fs-connector] LimitableReader should swallow exception when reached limit

- docs/content/docs/connectors/table/jdbc.md
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/options/JdbcLookupOptions.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/table/JdbcConnectorOptions.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/table/JdbcDynamicTableFactory.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/table/JdbcRowDataLookupFunction.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/table/JdbcDynamicTableFactoryTest.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/table/JdbcLookupTestBase.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/table/JdbcRowDataLookupFunctionTest.java
Ideally, in case of cache miss for a key, or with null value fetch for key, key shouldn't be cached, however empty result query should also be in the scope, so including an extra optional parameter to configure same
empty check on row list will make sure for database read for empty data for the key
This change is a trivial check / code fix without any test coverage. …
> [FLINK-24861][connector][jdbc] Fix false cache lookup for empty data

- flink-table/flink-sql-parser-hive/pom.xml
- flink-table/flink-sql-parser/pom.xml
- flink-table/flink-table-planner/pom.xml
- pom.xml
* Update JUnit5 dependency to the latest available version (5.8.1)
* Updated reference in POM
* Excluding org.apiguardian:apiguardian-api from `flink-sql-parser` and `flink-sql-parser-hive` since JUnit5 contains a newer version of this dependency …
> [FLINK-24832][tests][testinfrastructure] Update JUnit5 to v5.8.1

- flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskCancelAsyncProducerConsumerITCase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/testutils/MiniClusterExtension.java
- flink-runtime/src/test/java/org/apache/flink/runtime/util/BlobServerExtension.java
- flink-runtime/src/test/java/org/apache/flink/runtime/zookeeper/ZooKeeperExtension.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/core/testutils/AllCallbackWrapper.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/core/testutils/CustomExtension.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/core/testutils/EachCallbackWrapper.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/executor/TestExecutorExtension.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/SharedObjectsExtension.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/extensions/retry/RetryExtension.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/extensions/retry/RetryTestExecutionExtension.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/extensions/retry/strategy/AbstractRetryStrategy.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/extensions/retry/strategy/RetryOnExceptionStrategy.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/extensions/retry/strategy/RetryOnFailureStrategy.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/extensions/retry/strategy/RetryStrategy.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/logging/LoggerAuditingExtension.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/util/LogLevelExtension.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/util/TestLoggerExtension.java
- flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/RetryOnExceptionExtensionTest.java
- flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/RetryOnFailureExtensionTest.java
- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/streaming/util/StreamCollectorExtension.java
- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/test/util/MiniClusterWithClientExtension.java
This pull request provides some junit5 extensions to replace the existed junit4 rules.
- Add corresponding extensions for the existed junit4 rules. The extensions are named in a format of `xxxxExtension.java`, and replace the word _Resource_ to _Extension_ if the rule's filename is like `xxxResource.java`, e.g. `MiniClusterResource.java` corresponds to `MiniClusterExtension.java`.
- Add `CustomExtension`, `AllCallbackWrapper` and `EachCallbackWrapper` for the rules that is both used as `@Rule` and `@ClassRule`. 
- Add retry extension in junit5, whose behavior is different from the `RetryRule`.
- Add `TestLoggerExtension` to replace `TestLogger` …
> [FLINK-24627][tests] add some Junit5 extensions to replace the existed Junit4 rules

- flink-connectors/flink-connector-hbase-1.4/pom.xml
- flink-connectors/flink-connector-hbase-2.2/pom.xml
The setting had no effect since Java 8 and is actively rejected in Java 17.
The remainder of the `argLine` parameter seemed unnecessary as well.
> [FLINK-24979][build][hbase] Remove MaxPermSize setting 

- azure-pipelines.yml
- tools/azure-pipelines/build-apache-repo.yml
- tools/ci/compile.sh
- tools/ci/maven-utils.sh
The variable is misleading because it is used for maven arguments, while MAVEN_OPTS is passed by maven to the JVM.
> [FLINK-24984][ci] Rename MAVEN_OPTS variable

- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPoolDestroyTest.java
The stacktrace layout of a blocking thread is slightly different on Java 17, causing `isInBlockingBufferRequest` to always return false.
IIRC the total depth increased by one.
> [FLINK-24985][tests] Relax assumptions of stacktrace layout

- azure-pipelines.yml
- tools/azure-pipelines/build-apache-repo.yml
This allows us to run the compile/tests phases with Java 17. E2E tests are a separate issue.
Here's the corresponding Dockerfile:
```
FROM chesnay/flink-ci:base
RUN wget -q https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.1%2B12/OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz
RUN tar -C /usr/lib/jvm -xzf OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz
RUN echo "JAVA_HOME_17_X64=/usr/lib/jvm/jdk-17.0.1+12" >> /etc/environment
ENV JAVA_HOME_17_X64 "/usr/lib/jvm/jdk-17.0.1+12"
```
> [FLINK-24996][ci] Update CI image to contain Java 17

- flink-core/src/main/java/org/apache/flink/api/java/typeutils/RowTypeInfo.java
- flink-core/src/main/java/org/apache/flink/api/java/typeutils/runtime/RowSerializer.java
- flink-core/src/test/java/org/apache/flink/api/common/typeutils/TypeSerializerUpgradeTestBase.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/sink/TwoPhaseCommitSinkFunction.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/typeutils/LinkedListSerializer.java
Before this commit, some serializers handled the version information
incorrectly in the corresponding serializer snapshot which could lead
during eager instantiation that the wrong version of the serializer
was used to deserialize the data.
- Reenable serializer upgrade tests to **always** test serialization and restoration
- Update all serializers that were handling the version incorrectly
- Updated tests are all passing …
> [FLINK-24858][core] Prevent version mismatches in TypeSerializers

- docs/content.zh/docs/dev/table/sqlClient.md
- docs/content/docs/dev/table/sqlClient.md
Fix the spelling error of "parallism" in the document of SQL client.
- Replace "parallism" to  "parallelism"  in the document of SQL client.
> [FLINK-24922][docs]Fix spelling errors in the word "parallism"

- docs/content.zh/docs/dev/table/sqlClient.md
- docs/content/docs/dev/table/sqlClient.md
Fix the spelling error of "parallism" in the document of SQL client.
- Replace "parallism" to  "parallelism"  in the document of SQL client.
> [FLINK-24922][docs] Backport fix spelling errors in the word "parallism"

- flink-connectors/flink-connector-base/pom.xml
- flink-connectors/flink-connector-elasticsearch5/pom.xml
- flink-connectors/flink-connector-files/pom.xml
- flink-connectors/flink-connector-hive/pom.xml
- flink-connectors/flink-connector-kinesis/pom.xml
- flink-connectors/flink-sql-connector-elasticsearch6/pom.xml
- flink-connectors/flink-sql-connector-elasticsearch7/pom.xml
- flink-connectors/flink-sql-connector-hbase-1.4/pom.xml
- flink-connectors/flink-sql-connector-hbase-2.2/pom.xml
- flink-connectors/flink-sql-connector-kafka/pom.xml
- flink-connectors/flink-sql-connector-kinesis/pom.xml
- flink-connectors/flink-sql-connector-rabbitmq/pom.xml
- flink-end-to-end-tests/flink-streaming-kinesis-test/pom.xml
- flink-examples/flink-examples-build-helper/flink-examples-streaming-gcp-pubsub/pom.xml
- flink-examples/flink-examples-build-helper/flink-examples-streaming-state-machine/pom.xml
- flink-examples/flink-examples-build-helper/flink-examples-streaming-twitter/pom.xml
- flink-filesystems/flink-fs-hadoop-shaded/pom.xml
- flink-filesystems/flink-oss-fs-hadoop/pom.xml
- flink-filesystems/flink-s3-fs-hadoop/pom.xml
- flink-filesystems/flink-s3-fs-presto/pom.xml
- flink-formats/flink-sql-avro-confluent-registry/pom.xml
- flink-formats/flink-sql-avro/pom.xml
- flink-python/pom.xml
- flink-rpc/flink-rpc-akka-loader/pom.xml
- flink-table/flink-table-code-splitter/pom.xml
- flink-table/flink-table-planner/pom.xml
- pom.xml
In 3.2.2 a bug was fixed in the `shade-plugin` where it was creating empty test jars if `shadeTestJar` was set to `true` and no prior `test-jar` was generated by the `maven-jar-plugin.`
This fix caused the license check to fail, because it was setup to ignore empty test jars (as they are not interesting). Now that the test jars contained stuff (and I think even transitive dependencies), it expected a `NOTICE` file.
However, we don't actually need/want the `shade-plugin` to shade the test-jars. It results in additional overhead in the build process, and it is highly advisable to not rely on those jars, because it is very easy to use them the wrong way as they do not come automatically with the transitive (and relocated) dependencies.
As such this PR disables the shading of tests jars, with …
> [FLINK-25039][build] Disable shading of test jar by default

- flink-end-to-end-tests/test-scripts/common.sh
- flink-end-to-end-tests/test-scripts/common_ssl.sh
* There are multiple occurrences of the Bash based `Streaming File Sink s3 end-to-end test stalled on azure` failing. After analysis, all failures have in common that git clone of flink-shaded is failing. This PR introduces a retry mechanism in case a git clone fails. 
* Added retry mechanism to git clone of flink-shaded …
> [FLINK-24971][tests] Adding retry mechanism in case git clone fails

- docs/layouts/shortcodes/generated/rocksdb_configurable_configuration.html
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBConfigurableOptions.java
Correct the description of RocksDB's background threads for flush and compaction.
> [FLINK-25067][doc] Correct the description of RocksDB's background threads for flush and compaction

- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/AsyncSinkBase.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/AsyncSinkBaseBuilder.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriter.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/ArrayListAsyncSink.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/AsyncSinkBaseITCase.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterTest.java
https://github.com/apache/flink/pull/17345#discussion_r756760460
Introduced maxRecordSizeInBytes and changed the behaviour of flushOnBufferSizeInBytes
changed name of flushOnBufferSizeInBytes to maxBufferSizeInBytes
and
new unit tests
- Dependencies (does it add or upgrade a dependency): (yes / no)n
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)y
- The serializers: (yes / no / don't know)n
- The runtime per-record code paths (performance sensitive): (yes / no / don't know)n …
> [FLINK-24227][connectors] Async Base Sink Hotfix - Introduced maxRecordSizeInBytes and changed the behaviour of flushOnBufferSizeInBytes

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaProducerITCase.java
hardening the test on the old releases with retry rules, the issue has been solved after bumping Kafka to 2.8.1.
- Test cases will be retried 2 time (total runs 3) before failing
This change is a trivial rework to add retry rule of one unit test case. …
> [FLINK-21214][kafka/IT] add retry rule

- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/ParquetFileSystemITCase.java
ignore this test.
created FLINK-25071 for finding the unstable reason and re-open it.
> [FLINK-24763][parquet] Ignore ParquetFileSystemITCase.testLimitableBulkFormat

- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBResourceContainer.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBResourceContainerTest.java
FLINK-20496 introduce partitioned index & filter to Flink. However, RocksDB only support new full format of filter in this feature, and we need to replace previous filter if user enabled. Previous implementation use reflection to get the filter and we could use API to get that after upgrading RocksDB to `6.20.3-ververica-1.0`.
- Use `BlockBasedTableConfig#filterPolicy()` to get filter in `RocksDBResourceContainer#overwriteFilterIfExist()`
This change is a trivial rework, and already covered by existing test  `RocksDBResourceContainerTest#testGetColumnFamilyOptionsWithPartitionedIndex()`. …
> [FLINK-23798][state] Avoid using reflection to get filter when partition filter is enable

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaChangelogTableITCase.java
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalSink.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/optimize/program/FlinkChangelogModeInferenceProgram.scala
- flink-table/flink-table-planner/src/test/resources/META-INF/services/org.apache.flink.table.factories.Factory
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/RankTest.xml
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/agg/AggregateTest.xml
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/join/JoinTest.xml
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/RankTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/agg/AggregateTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/join/JoinTest.scala
The root cause of this case is `FlinkChangelogModeInferenceProgram` didn't consider  the case when sink's primary key differs from input's upsert keys when infer required `ChangeLogMode` from sink node.
So we should add releated logic to `FlinkChangelogModeInferenceProgram` and also update upsertMaterialization process in `StreamPhysicalSink`
update the logic of `FlinkChangelogModeInferenceProgram` and `StreamPhysicalSink`
Streaming sql's `RankTest`, `AggregateTest` and `JoinTest` …
> [FLINK-20370][table] part1: Fix wrong results when sink primary key is not the same with query result's changelog upsert key

- flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/streaming/connectors/cassandra/CassandraSink.java
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/table/KeyExtractor.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/JdbcOutputFormat.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/KafkaDynamicSink.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/ReducingUpsertSink.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/SinkBufferFlushMode.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/ReducingUpsertWriterTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/UpsertKafkaTableITCase.java
- flink-core/src/main/java/org/apache/flink/util/function/SerializableFunction.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/TestingOperatorCoordinator.java
- flink-runtime/src/test/java/org/apache/flink/runtime/util/SerializableFunction.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/DataStream.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/DataStreamSink.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/KeyedStream.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectStreamSink.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/transformations/LegacySinkTransformation.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/translators/LegacySinkTransformationTranslator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/datastream/DataStreamSinkTest.java
- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/connector/datagen/table/types/DataGeneratorMapper.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecLegacySink.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecLegacySink.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecLegacySink.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecSinkITCase.java
When migrating the buffered Kafka upsert sink to the unified Sink a few problems were discovered i.e. input lambdas were not serializable, unified sinks did not work with the DataStreamSink Provider.
With this PR the points should be addressed. 
- Make input lambdas serializable 
- Differentiate in DataStreamSink between legacy and unified sinks transformation to support both in the DataStreamSinkProvider
- Added ITCase to cover the functionality of the buffered KafkaUpsert sink.
- Added a test to verify that unified sinks work with the DataStreamSinkProvider.
- The runtime …
> [FLINK-24596][kafka] Fix buffered KafkaUpsert sink

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaProducerITCase.java
Unfortunately, the Kafka version bump did not fully resolve the flakiness of the FlinkKafkaProducerITCase so we apply the fix of https://issues.apache.org/jira/browse/FLINK-21214 to retry the failed cases because we highly suspect the non-dockerized test setup.
Once we have fully removed the FlinkKafkaProducer and all APIs are migrated to the KafkaSink we can also remove the test old test infrastructure.
We do not see any of the failures with regard to the dockerized test environments.
- Add two retries on failure for all tests in FlinkKafkaProducerITCase
Change only affects test code.
- The serializers: (yes / **no** / don't …
> [FLINK-21214][kafka/IT] Add retry rule for FlinkKafkaProducerITCase

- flink-end-to-end-tests/run-nightly-tests.sh
Resolves an issue where Java e2e tests could categorically ignore the contents of the cache, if the cache contents exceeded the TTL.
Because the azure caches are immutable we are not able to update the creation date of the contained entries.
The TTL has now been disabled. Given that the set of cache artifacts should only change if the tests are modified, this shouldn't pose a problem.
> [FLINK-25112][tests] Remove cache-ttl for Java e2e tests

- flink-end-to-end-tests/test-scripts/elasticsearch-common.sh
* The Elasticsearch test download Elasticsearch binaries. To harden the test, we retry if the download fails. This PR refactors the Elasticsearch test to use the cache for Bash based e2e tests.
* Refactored Elasticsearch Bash e2e test to use get_artifact function. …
> [FLINK-25092][tests][elasticsearch] Refactor test to use artifact cacher

- flink-end-to-end-tests/test-scripts/common_docker.sh
* The Docker test git clones the Flink Docker repo. To harden the test, we should retry if git clone fails, as we have seen with other tests. With #17881 a retry function was introduced. This PR refactors the Docker test to use this retry function. 
* Refactored Docker Bash e2e test to use retry function …
> [FLINK-25093][tests] Refactor test to use retry function for cloning Flink docker repo

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/BoundedMultiInput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/BoundedOneInput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/StreamOperator.java
We clarify contracts of Bounded(One/Multi)Input interfaces. Especially
adding a warning none of those interfaces should be used for commiting
side effects. …
> [FLINK-21467][docs] Clarify javadocs of Bounded(One/Multi)Input interfaces

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaConsumerTestBase.java
Before this commit the RetryRule actually prevented retries of tests
inheriting from KafkaConsumerTestBase. Now, the retries are handled by
KafkaTestBase and all subclasses have the same retry behaviour.
- Remove unused retry rule from KafkaConsumerTestBase
I manually invoked an exception and hit the timeout of a test in KafkaITCase to verify the test is retried. …
> [FLINK-25134][test] Remove unused RetryRule from KafkaConsumerTestBase

- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/utils/SerializableConfiguration.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/ParquetFileSystemITCase.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/utils/SerializableConfigurationTest.java
SerializableConfiguration load resources from ClassLoader lead to many unstable tests:
https://issues.apache.org/jira/browse/FLINK-24763
https://issues.apache.org/jira/browse/FLINK-25102
But this is not necessary, because from serialization, the resources to be read are already serialized into properties.
- SerializableConfiguration should not load resources
- Enable ParquetFileSystemITCase.testLimitableBulkFormat
`SerializableConfigurationTest` …
> [FLINK-25071][parquet] SerializableConfiguration should not load resources

- pom.xml
(cherry picked from commit 8176d5809e2b13c465662706e3df343b2d4f9028)
Backport of https://github.com/apache/flink/pull/17646
> [FLINK-24740][BP-1.13][testinfrastructure] Update testcontainers dependency to the latest version

- docs/layouts/shortcodes/generated/rocksdb_configurable_configuration.html
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBConfigurableOptions.java
FLINK-15068 disabled the RocksDB's local LOG due to previous RocksDB cannot limit the local log files.
After we upgraded to newer RocksDB version, we can then enable RocksDB log again.
Change every predefined options for RocksDB, setting log level to INFO and limiting the log file size.
> [FLINK-23791] Enable RocksDB info log by default

- docs/content.zh/docs/connectors/datastream/file_sink.md
- docs/content/docs/connectors/datastream/file_sink.md
-  What should be quoted here is writerProperties Shouldn't be is writerProps
-  I checked all versions and found that 1.11 version and above need to be modified here
- Please use cherry-pick to fix all branches involved in the problem （1.11 +  and Chinese documents ）
- [Official website document FileSink orc compression attribute reference error --- issue](https://issues.apache.org/jira/projects/FLINK/issues/FLINK-25091?filter=reportedbyme)
> [FLINK-25091] change Official website document "FileSink" orc compression attribute reference error

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/CheckpointConfig.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/environment/CheckpointConfigFromConfigurationTest.java
This enables the user to pass in the checkpoint directory through the Flink
configuration again. This fixes an issue that was introduced by [FLINK-19463](https://issues.apache.org/jira/browse/FLINK-19463).
This fixes an issue where the checkpoint directory couldn't be set anymore through the Flink configuration. See a more detailed description in the ticket [FLINK-24506](https://issues.apache.org/jira/browse/FLINK-24506)
* Adds the `state.checkpoints.dir` to `CheckpointConfig.configure`
* A test was added to the corresponding `CheckpointConfigFromConfigurationTest` …
> [FLINK-24506][config] Adds checkpoint directory to CheckpointConfig

- flink-core/src/main/java/org/apache/flink/util/concurrent/SeparateThreadExecutor.java
- flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/WebSubmissionExtension.java
- flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/handlers/JarMessageParameters.java
- flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/handlers/JarRunHandler.java
- flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/handlers/JarUploadHandler.java
- flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/WebSubmissionExtensionTest.java
Use a dedicated thread to run each jar, so that pooled threads can't keep references to user-code (e.g., in a ThreadLocal).
> [FLINK-25022][rest] Run jars in separate threads

- flink-connectors/flink-connector-kinesis/pom.xml
- If a package depended on both `flink-connector-aws-base` and `flink-connector-kinesis`, there would be a duplication of the classes from the first from the shaded JAR of the second
- This change relocates classes from `flink-connector-aws-base` in the shaded JAR of `flink-connector-kinesis`
- The `pom.xml` of `flink-connector-kinesis` has been updated to relocate used classes from `flink-connector-aws-base` …
> [FLINK-24227][connectors/kinesis] Relocated flink-connector-aws-base in flink-connector-kinesis shaded jar

- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/DefaultConfigurableOptionsFactory.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/PredefinedOptions.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBResourceContainer.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBResource.java
Now flink setIncreaseParallelism (the most we can do for the rocksdb backend background threads) seems like can do little thing for flink rocksdb tuning. It can't change the flush threads. It's necessary to make rocksdb configuration flexible. This change will replace setIncreaseParallelism with setMaxBackgroundJobs. …
> [FLINK-25163] replace setIncreaseParallelism with setMaxBackgroundJobs.

- docs/content/docs/connectors/datastream/elasticsearch.md
- docs/content/docs/connectors/table/elasticsearch.md
This PR updates the docs pages for the elasticsearch connector sink for the new unified sink API implementation introduced in FLINK-24324 and FLINK-24325.
This change is a documentation update.
gs  - only docs
> [FLINK-24326][docs][connectors] Update elasticsearch sink pages with new unified sink API (FLIP-143) implementation

- docs/content.zh/docs/dev/datastream/operators/asyncio.md
- docs/content/docs/dev/datastream/operators/asyncio.md
Sometimes, a user overrides AsyncFunction#timeout() with an empty method or with only logging code. This causes the timeout does not signal back to the framework and job stuck especially when using orderedWait(). This change to make the doc clear on this.
- updated the doc to make it clear
This change is a trivial doc improvement. …
> [FLINK-24686][doc] Make doc clear on AsyncFunction#timeout() overriding

- docs/content.zh/docs/connectors/table/hive/hive_read_write.md
- docs/content/docs/connectors/table/hive/hive_read_write.md
* Update to temporal join section docs for hive connector
* Update to temporal join section docs for hive connector
> [hotfix][docs][hive] - Minor update to temporal join section

- flink-jepsen/project.clj
- flink-jepsen/src/jepsen/flink/db.clj
Jepsen 0.1.19 is smarter when it comes to detecting already installed dependencies, where unnecessary retries to install something can result in errors.
This also required a Clojure upgrade to 1.10.0. Later patch releases are not compatible with Jepsen.
The Jepsen upgrade had an odd and undocumented behavioral change where DB#teardown is called at the start of the test, presumably to clean up stuff from previous runs. However, both our dbs and jepsen-zookeeper fail if the db hasn't been setup yet. To save time we just catch exceptions that occur during the teardown, log them, and continue as if nothing happened.
I have run the tests locally to ensure they still pass.
> [FLINK-25180][tests] Upgrade Jepsen to 0.1.19

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/KafkaDynamicTableFactory.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaDynamicTableFactoryTest.java
This PR replaces codepath where a ConfigOption is used as a key lookup in a Map of Strings with the correct lookup using the Configuration object built from the Map. It looks like the code was working implicitly before because the ConfigOption got cast to a String.
This change is already covered by existing tests, such as KafkaDynamicTableFactoryTest#testPrimaryKeyValidation
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / **no***) …
> [FLINK-24977][connectors/kafka] Replace ConfigOption lookup in Map<Sring, String> object with proper lookup in Configuration object

- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/ActionRequestFailureHandler.java
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/ElasticsearchSinkFunction.java
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/RequestIndexer.java
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/util/RetryRejectedExecutionFailureHandler.java
- flink-connectors/flink-connector-elasticsearch6/src/main/java/org/apache/flink/streaming/connectors/elasticsearch6/ElasticsearchSink.java
- flink-connectors/flink-connector-elasticsearch6/src/main/java/org/apache/flink/streaming/connectors/elasticsearch6/RestClientFactory.java
- flink-connectors/flink-connector-elasticsearch7/src/main/java/org/apache/flink/streaming/connectors/elasticsearch7/ElasticsearchSink.java
- flink-connectors/flink-connector-elasticsearch7/src/main/java/org/apache/flink/streaming/connectors/elasticsearch7/RestClientFactory.java
This pull request deprecates the old Elasticsearch connectors in favor of the new, FLIP-143 compliant one …
> [FLINK-24372][connectors/elasticsearch] Deprecate old (pre FLIP-143) Elasticsearch connector

- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/src/reader/TextLineFormat.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/read/HiveBulkFormatAdapter.java
- flink-formats/flink-orc/src/main/java/org/apache/flink/orc/OrcColumnarRowFileInputFormat.java
This is linked to [this PR](https://github.com/apache/flink/pull/17839). It adds deprecation notices on the old format names for the users.
As discussed R: @AHeise
> [FLINK-24859][doc][formats] Make new formats name coherent: introduce previous names classes to indicate deprecation to the users

- flink-core/src/test/java/org/apache/flink/testutils/TestFileSystem.java
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/FileSystemITCaseBase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/FileSystemTestCsvITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/StreamFileSystemTestCsvITCase.scala
This PR adds tests for the change in #17638.
- Add tests to ensure SQL file sink closes all created files
> [FLINK-24728][tests] Add tests to ensure SQL file sink closes all created files

- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/AbstractChangelogState.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/AbstractStateChangeLogger.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyGroupedPriorityQueue.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogState.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/PeriodicMaterializationManager.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/StateChangeLogger.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogDelegateEmbeddedRocksDBStateBackendTest.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogDelegateFileStateBackendTest.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogDelegateHashMapTest.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogDelegateMemoryStateBackendTest.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogPqStateTest.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogStateBackendTestUtils.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/TestChangeLoggerKv.java
After materialization is added in FLINK-21357, a snapshot is composed of 
"the materialized part" + "the changelog part", where the changelog part relies on metadata to replay the log during recovery. So we need to add metadata after materialization.
FLINK-23170 includes discussions of where and when should such metadata be added. Here we add metadata right after materialization is triggered each time.
Unit tests.
> [FLINK-23170] Write metadata after materialization

- flink-connectors/flink-connector-hbase-2.2/src/test/java/org/apache/flink/connector/hbase2/HBaseConnectorITCase.java
there are multiple failing tests during CI only happened for `hbase2`. The potential reason might be some race conditions while running the CI on azure. This PR adds some additional checks and explicitly method calls to make sure the result has been fetched before doing the assertions. Local checks haven been done multiple times and none failing test happened.
- add check of row count after insert
- explicitly call await() for batch select
This change is a trivial rework / test case improvement.
- The runtime per-record code paths (performance sensitive): (yes / **no** / don't …
> [FLINK-24077][hbase2/HBaseConnectorITCase] fix flaky tests

- docs/layouts/shortcodes/generated/rest_v1_dispatcher.html
- docs/layouts/shortcodes/generated/savepoint_config_configuration.html
- flink-clients/src/main/java/org/apache/flink/client/cli/CliFrontendParser.java
- flink-clients/src/test/java/org/apache/flink/client/cli/CliFrontendRunTest.java
- flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/handlers/JarRunHandler.java
- flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/handlers/JarRunRequestBody.java
- flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/handlers/JarRunHandlerParameterTest.java
- flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/handlers/JarRunRequestBodyTest.java
- flink-runtime-web/src/test/resources/rest_api_v1.snapshot
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/Checkpoints.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/RestoreMode.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/SavepointConfigOptions.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/SavepointRestoreSettings.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultExecutionGraphFactory.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointMetadataLoadingTest.java
- flink-table/flink-sql-client/src/test/resources/sql/set.q
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/SavepointITCase.java
This PR adds a `RestoreMode` flag to be passed along with savepoint path. It determines the way a snapshot should be restored from. If a `CLAIM` mode is specified Flink will take ownership of the initial snapshot and will treat it as if it was created as a regular checkpoint and it might delete it at a certain point in time.
* Added tests for passing the flag in CLI
* Added tests for passing the flag in REST API
* Added tests in SavepointITCase for the `CLAIM` behaviour …
> [FLINK-25155] Implement claim snapshot mode

- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/ExecutionGraphInfo.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/exceptionhistory/RootExceptionHistoryEntry.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/DefaultJobMasterServiceProcessTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/ExecutionGraphInfoTest.java
The `ExecutionGraphInfo` was not initialized properly if a failure happened during the initialization phase. The failure was stored in the `ArchivedExecutionGraph` but not in the `Collection` of `RootExceptionHistoryEntry` elements.
Instead of providing an empty list, a `RootExceptionHistoryEntry` is added if the passed `ExecutionGraph` contains a failure.
I extended the `DefaultJobMasterServiceProcessTest` to cover the `JobInitializationError` case and introduced `ExecutionGraphInfoTest`. …
> [FLINK-25096][runtime] Fixes empty exception history for JobInitializationException

- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/ExecutionGraphInfo.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/exceptionhistory/RootExceptionHistoryEntry.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/DefaultJobMasterServiceProcessTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/ExecutionGraphInfoTest.java
1.14 Backport for #17967
I cherry-picked [0eb7465](https://github.com/apache/flink/commit/0eb74658ac07e773adf79f55315d6d023af8058b) had to update the tests reverting the `assertj` asserts and imports.
> [BP-1.14][FLINK-25096] Fixes empty exception history for JobInitializationException

- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/ExecutionGraphInfo.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/exceptionhistory/RootExceptionHistoryEntry.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/DefaultJobMasterServiceProcessTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/ExecutionGraphInfoTest.java
1.13 Backport for #17967 
I cherry-picked [7ac7db2](https://github.com/apache/flink/commit/7ac7db2966f39a281692b6cf8c48700b7173bcc9) from the corresponding 1.14 backport PR #18035 but still had to fix some imports (junit4 instead of junit5, guava18 instead of guava30)
> [BP-1.13][FLINK-25096] Fixes empty exception history for JobInitializationException

- flink-connectors/flink-connector-hbase-2.2/src/test/java/org/apache/flink/connector/hbase2/HBaseConnectorITCase.java
there are multiple failing tests during CI only happened for `hbase2`. The potential reason might be some race conditions while running the CI on azure. This PR adds some additional checks and explicitly method calls to make sure the result has been fetched before doing the assertions. Local checks haven been done multiple times and none failing test happened.
- add check of row count after insert
- use `MiniClusterWithClientResource` as a `ClassRule`
This change is a trivial rework / test case improvement.
- The runtime per-record code paths (performance sensitive): (yes / **no** …
> [FLINK-24077][hbase2/HBaseConnectorITCase] fix flaky tests backport to 1.14

- flink-connectors/flink-connector-hbase-2.2/src/test/java/org/apache/flink/connector/hbase2/HBaseConnectorITCase.java
there are multiple failing tests during CI only happened for `hbase2`. The potential reason might be some race conditions while running the CI on azure. This PR adds some additional checks and explicitly method calls to make sure the result has been fetched before doing the assertions. Local checks haven been done multiple times and none failing test happened.
- add check of row count after insert
- use `MiniClusterWithClientResource` as a `ClassRule`
This change is a trivial rework / test case improvement.
- The runtime per-record code paths (performance sensitive): (yes / **no** …
> [FLINK-24077][hbase2/HBaseConnectorITCase] fix flaky tests backport to 1.13

- flink-connectors/flink-connector-hbase-2.2/src/test/java/org/apache/flink/connector/hbase2/HBaseConnectorITCase.java
there are multiple failing tests during CI only happened for `hbase2`. The potential reason might be some race conditions while running the CI on azure. This PR adds some additional checks and explicitly method calls to make sure the result has been fetched before doing the assertions. Local checks haven been done multiple times and none failing test happened.
- add check of row count after insert
- use `MiniClusterWithClientResource` as a `ClassRule`
This change is a trivial rework / test case improvement.
- The runtime per-record code paths (performance sensitive): (yes / **no** …
> [FLINK-24077][hbase2/HBaseConnectorITCase] fix flaky tests backport to 1.12

- docs/content.zh/docs/dev/dataset/transformations.md
- docs/content/docs/dev/dataset/transformations.md
> [hotfix][docs] Fix typo in textLines parameter for Map transformation

- pom.xml
- tools/releasing/NOTICE-binary_PREAMBLE.txt
Update log4j2 version to 2.15.0 , because log4j2 have a RCE zero day.
- *update  log4j2 version to 2.15.0 in parent pom*
> [FLINK-25240][core] update log4j2 version to 2.15.0

- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/TestingJobManagerRunner.java
Deduplicate jobs in the jobs overview to prevent a job appearing twice, as both SUSPENDED and RUNNING.
Jobs that are in progress take precedence.
> [FLINK-20195][coordination] Deduplicate jobs for overview

- flink-runtime/src/main/java/org/apache/flink/runtime/state/heap/KeyGroupPartitionedPriorityQueue.java
*The comment "@param <PQ> type type of sub-queue used for each key-group partition." should be "@param <PQ> the type of sub-queue used for each key-group partition." in KeyGroupPartitionedPriorityQueue.  Fix the small word error.*
- *Change the word 'type' to the word 'the'* …
> [FLINK-23937][Documentation] Fix PQ comment in KeyGroupPartitionedPriorityQueue

- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/AbstractDispatcherTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
Do not create an archive for suspended jobs, as this would eventually lead to multiple archive attempts which we currently do not support.
This is a quick-fix which we can safely backport; a proper solution where we archive jobs multiple times would require more time.
> [FLINK-24232][coordination] Skip history server archiving for suspended jobs

- docs/content.zh/docs/dev/datastream/project-configuration.md
- docs/content/docs/dev/datastream/project-configuration.md
- pom.xml
- tools/releasing/NOTICE-binary_PREAMBLE.txt
Update log4j dependency to version 2.16.0. This version removes message lookups and disables JNDI by default and results in a hardening of the default behaviour and configuration. 
* Updated log4j2 dependency in main POM
* Updated version number in NOTICE-binary_PREAMBLE
- If yes, …
> [FLINK-25295][core] Update log4j2 dependency to 2.16.0

- docs/content.zh/docs/dev/datastream/project-configuration.md
- docs/content/docs/dev/datastream/project-configuration.md
- pom.xml
- tools/releasing/NOTICE-binary_PREAMBLE.txt
Backport of https://github.com/apache/flink/pull/18100
> [FLINK-25295][BP 1.14][core] Update log4j2 dependency to 2.16.0

- docs/content.zh/docs/dev/datastream/project-configuration.md
- docs/content/docs/dev/datastream/project-configuration.md
- pom.xml
- tools/releasing/NOTICE-binary_PREAMBLE.txt
Backport of https://github.com/apache/flink/pull/18100
> [FLINK-25295][BP 1.13][core] Update log4j2 dependency to 2.16.0

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/proxy/KinesisProxy.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/proxy/KinesisProxyTest.java
High-volume Kinesis consumers can sporadically get Connect errors when connecting to the Kinesis endpoint.
Current behavior is to consider this a fatal error, causing Flink to roll back to previous checkpoint. However retries will typically lead to success, so this patch causes connect errors to be considered recoverable.
- Make ConnectTimeoutException recoverable
- Unit test for above
- New unit test
- Applying this patch has allowed one of our Flink jobs to run continuously, instead of failing several times per day. …
> [FLINK-24580][Connectors/Kinesis] Make ConnectTimeoutException recoverable

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaUtil.java
The order of log levels in the `createKafkaContainer` method was wrong causing incorrect log levels to be applied.
- fixed the log level hierarchy
This change is a trivial rework / code cleanup without any test coverage. To confirm it works please edit the log4j2-test.properties and confirm the log output of the started container for any unit test starting the testcontainer. …
> [FLINK-25326][connectors/kafka] Fix application of log levels in KafkaUtils.createKafkacontainer

- flink-core/src/test/java/org/apache/flink/testutils/TestFileSystem.java
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/FileSystemITCaseBase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/FileSystemTestCsvITCase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/StreamFileSystemTestCsvITCase.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/filesystem/FileSystemTableSink.java
(This PR is cherry-picked from #17638 and #17655)
Currently the output format created in `FileSystemTableSink#createBulkWriterOutputFormat` only finishes the `BulkWriter` and does not close the output stream. This will cause some problems with some file systems for example HDFS.
- Close output stream in batch SQL file sink.
- The S3 file …
> [FLINK-24728][table-runtime-blink] Close output stream in batch SQL file sink

- flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/connector/elasticsearch/ElasticsearchUtil.java
- flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchWriterITCase.java
- flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/connector/elasticsearch/sink/Elasticsearch6SinkITCase.java
- flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/connector/elasticsearch/table/Elasticsearch6DynamicSinkITCase.java
- flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch6/ElasticsearchSinkITCase.java
- flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/connector/elasticsearch/sink/Elasticsearch7SinkITCase.java
- flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/connector/elasticsearch/table/Elasticsearch7DynamicSinkITCase.java
- flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch7/ElasticsearchSinkITCase.java
This PR limits the memory allocation of the Elasticsearch testcontainers to prevent them getting OOM killed in the CI
* (re-)enabled Elasticsearch tests using testcontainers
* created `MemoryRestrictedElasticsearchContainer` helper class with a 2GB memory limit
* updated existing tests to use the new helper class for both Elasticsearch v6 and v7
This change can be verified by running the affected tests from the commit. …
> [FLINK-25223][connectors/elasticsearch] Limit Elasticsearch testcontainer memory allocation

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSource.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReader.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaRecordEmitter.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReader.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/fetcher/KafkaSourceFetcherManager.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReaderTest.java
This pull request moves record deserializing in KafkaSource from SplitFetcher to RecordEmitter to support object-reusing deserializer
- Move record deserializing from `KafkaPartitionSplitFetcher` to `KafkaRecordEmitter`
- Added cases for testing KafkaSource with deserializer enabling object reuse. …
> [FLINK-25132][connector/kafka] Move record deserializing from SplitFetcher to RecordEmitter to support object-reusing deserializer

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveDynamicTableFactory.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/HiveCatalogLock.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/HiveConfOptions.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/client/HiveMetastoreClientWrapper.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveRunnerITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/catalog/hive/factories/TestLockTableSinkFactory.java
- flink-connectors/flink-connector-hive/src/test/resources/META-INF/services/org.apache.flink.table.factories.Factory
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogLock.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/RequireCatalogLock.java
Introduce `CatalogLock` for connectors, source & sink can use this lock to do some global sync.
```
/**
* An interface that allows source and sink to use global lock to some transaction-related things.
*/
@Internal
public interface CatalogLock extends Closeable {
/** Run with catalog lock. The caller should tell catalog the database and table name. */
<T> T runWithLock(String database, String table, Callable<T> callable) throws Exception;
/** Factory to create {@link CatalogLock}. */
interface Factory extends Serializable {
CatalogLock create();
}
} 
```
And we need a interface to set lock to source&sink by catalog:
```
/**
* Source and sink implement this interface if they require {@link CatalogLock}.
*/
@Internal
public interface RequireCatalogLock {
void …
```
> [FLINK-25173][table][hive] Introduce CatalogLock and implement HiveCatalogLock

- docs/content.zh/docs/dev/datastream/project-configuration.md
- docs/content/docs/dev/datastream/project-configuration.md
- pom.xml
- tools/releasing/NOTICE-binary_PREAMBLE.txt
> [FLINK-25375] [BP-1.13] Update log4j2 dependency to 2.17.0 to address

- docs/content.zh/docs/dev/datastream/project-configuration.md
- docs/content/docs/dev/datastream/project-configuration.md
- pom.xml
- tools/releasing/NOTICE-binary_PREAMBLE.txt
> [FLINK-25375] [BP-1.14] Update log4j2 dependency to 2.17.0 to address
