- docs/content/docs/connectors/datastream/jdbc.md
Fixed a minor change within the wording / grammar surrounding executing JDBC batches documentation.
> [FLINK-21885] [documentation] Fixed Minor Typo in JDBC Batch Execution Criteria

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliClient.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/SqlCommandParser.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/SqlCommandParserTest.java
- flink-table/flink-sql-client/src/test/resources/sql/table.q
- flink-table/flink-sql-parser-hive/src/main/codegen/includes/parserImpls.ftl
- flink-table/flink-sql-parser-hive/src/test/java/org/apache/flink/sql/parser/hive/FlinkHiveSqlParserImplTest.java
- flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl
- flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/api/TableEnvironmentTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/batch/BatchTableEnvironmentTest.scala
*Introduce DESC grammar in sql parser, Combine DESC and DESCRIBE commands in sql client module*
-  d7865d94cd80e126bc0c2e69036ac43e5da0a729 *Introduce DESC grammager in sql parser, Remove DESC COMMAND from sql client module*
-  508be62bbbf9ef2485dd84f22555f8b0530fe225 *add tests in TableEnvironmentTest#testDescribeTableOrView and table.q*
- *Added tests in FlinkSqlParserImplTest and FlinkHiveSqlParserImplTest to verify syntax support.*
- *Change tests in SqlCommandParserTest to verify parser DESC syntax with sql parser* …
> [FLINK-21847][flink-sql-parser] Introduce DESC grammar in sql parser

- flink-streaming-java/src/main/java/org/apache/flink/streaming/experimental/CollectSink.java
[FLINK-21814](https://issues.apache.org/jira/browse/FLINK-21814)
When the connection exception occurs, I don't know the host and port corresponding to the exception. So, I can't quickly locate the problem machine when the exception occurs
Add the host and port corresponding to the exception to the exception output …
> [FLINK-21814] [API / DataStream] Add the error info of the Exception

- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientTest.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/TestingExecutor.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/TestingExecutorBuilder.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/local/LocalExecutorITCase.java
- flink-table/flink-sql-client/src/test/resources/sql/catalog_database.q
*This is just do some code clean before unify the parser. Move the SHOW VIEWS test from the CliClientTest into CliClientITCase. It also removes some usesless codes*
> [FLINK-21887][sql-client] Add SHOW VIEWS test in CliClientITCase

- docs/content.zh/docs/connectors/table/datagen.md
- docs/content.zh/docs/connectors/table/elasticsearch.md
- docs/content.zh/docs/connectors/table/hbase.md
- docs/content.zh/docs/connectors/table/print.md
- docs/content.zh/docs/connectors/table/upsert-kafka.md
- docs/content/docs/connectors/table/elasticsearch.md
[FLINK-18384](https://issues.apache.org/jira/browse/FLINK-18384)
Translate "Elasticsearch SQL Connector" page into Chinese.
* Translate "Elasticsearch SQL Connector" page into Chinese, the doc file is located in 'flink/docs/content.zh/docs/connectors/table/elasticsearch.md'.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / **no** / …
> [FLINK-18384][docs] translate "Elasticsearch SQL Connector" page into Chinese

- docs/content.zh/docs/connectors/table/jdbc.md
[FLINK-21838](https://issues.apache.org/jira/browse/FLINK-21838)
Retranslate "JDBC SQL Connector" page into Chinese.
* Retranslate "JDBC SQL Connector" page into Chinese, the doc file is located in 'docs/content.zh/docs/connectors/table/jdbc.md'. …
> [FLINK-21838][docs] retranslate "JDBC SQL Connector" page into Chinese

- docs/content.zh/docs/dev/table/sql/describe.md
- docs/content/docs/dev/table/sql/describe.md
*Add documentation for the DESC statement syntax*
- *Add documentation for the DESC statement syntax*
- docs change, no need to verify
> [FLINK-21892][doc] Add documentation for the DESC statement syntax

- docs/layouts/shortcodes/generated/mesos_task_manager_configuration.html
- flink-mesos/src/main/java/org/apache/flink/mesos/runtime/clusterframework/LaunchableMesosWorker.java
- flink-mesos/src/main/java/org/apache/flink/mesos/runtime/clusterframework/MesosTaskManagerParameters.java
- flink-mesos/src/test/java/org/apache/flink/mesos/runtime/clusterframework/MesosResourceManagerDriverTest.java
- flink-mesos/src/test/java/org/apache/flink/mesos/runtime/clusterframework/MesosTaskManagerParametersTest.java
Mesos tasks can be run with a specific user. We add an option to override
it, by default it will be the same user as jobmanager.
Set unix user to mesos tasks for taskmanagers running in mesos. This is very useful for mesos resource management, especially when it comes to some specific system resource access control.
This change added unit tests par parsing the mesos user config …
> [FLINK-21506] [mesos] Option for mesos task user

- docs/content.zh/docs/connectors/table/hive/hive_read_write.md
- docs/content/docs/connectors/table/hive/hive_read_write.md
> [FLINK-21930][DOC]fix hive dim doc  replace o to order

- flink-core/src/main/java/org/apache/flink/api/common/time/Deadline.java
- flink-core/src/main/java/org/apache/flink/util/ExceptionUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateCheckpointWriter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestDispatcherImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestExecutorImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriterImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/SequentialChannelStateReaderImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/logger/NetworkActionsLogger.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/util/LogLevelRule.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointRescaleITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java
To debug FLINK-20654, we need all network buffers to be logged.
- Adds a junit rule to change log levels for specific logs (currently only for log4j2 loggers).
- Switches `NetworkActionsLogger` to `TRACE` in `UnalignedCheckpointITCase` and `UnalignedCheckpointRescaleITCase`.
Manually verified locally and on AZP. …
> [FLINK-20654][tests] Forcing network action logger on TRACE for Unaligned Checkpoint ITCases.

- docs/content.zh/docs/connectors/table/kafka.md
[FLINK-21917](https://issues.apache.org/jira/browse/FLINK-21917)
Add back missing zh kafka.md doc
* Add back missing zh "Apache Kafka SQL Connector" doc, the doc file is located in 'docs/content.zh/docs/connectors/table/kafka.md'.
* Ref [#13876](https://github.com/apache/flink/pull/13876)
- Dependencies (does it add or upgrade a dependency): (yes / ***no***)
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / ***no***)
- The serializers: (yes / ***no*** / don't know)
- The runtime per-record code paths (performance sensitive): (yes / ***no*** / don't know) …
> [FLINK-21917][docs] Add back missing zh kafka.md doc

- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/utils/ParquetRecordReader.java
> [hotfix][formats] Fix exception message

- flink-dist/src/main/flink-bin/conf/log4j-cli.properties
Some hive classes are in the `org.apache.hadoop` package and their logs are printed to the console appender. We should make sure hive logs go to the file appender instead.
- Add a hive logger in the log4j conf file and print the logs to file appender.
NA
NA
> [FLINK-21590][conf][log4j] Avoid hive logs in the SQL client console

- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/EndStatementSetOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/StatementSetOperation.java
> [hotfix] Create parent interface for begin/end statement set operation.

- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SQLClientKafkaITCase.java
- flink-end-to-end-tests/flink-end-to-end-tests-hbase/src/test/java/org/apache/flink/tests/util/hbase/SQLClientHBaseITCase.java
- flink-end-to-end-tests/run-nightly-tests.sh
I increased the timeout for download cache entries and reenabled `SQLClientHBaseITCase` test.
>  [FLINK-21103] Increased TTL for download cache entries 

- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/StreamingKafkaITCase.java
Reenable StreamingKafkaITCase with added timeout.
> [FLINK-21556] Add timeout to StreamingKafkaITCase 

- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/module/hive/HiveModuleTest.java
Fix HiveModuleTest for 1.2.1
- Update the num of built-in functions for 1.2.1
Manually verified all tests with 1.2.1
NA
NA
> [FLINK-22103][hive] Fix HiveModuleTest for 1.2.1

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java
This is a trivial change to fix `UnalignedCheckpointRescaleITCase` instability.
> [FLINK-21880][tests] Ignore incomplete checkpoints in UnalignedCheckpointRescaleITCase

- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/CoordinatedSourceRescaleITCase.java
Unchanged backport of #15503.
The test may fail because of unnecessarily restrictive checks.
- Ease checks
Test change
> [FLINK-21873][connector/common] Harden CoordinatedSourceRescaleITCase by checking exceptions more leniently.

- flink-connectors/flink-sql-connector-hive-1.2.2/pom.xml
- flink-connectors/flink-sql-connector-hive-1.2.2/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-hive-1.2.2/src/main/resources/META-INF/licenses/LICENSE.antlr
- flink-connectors/flink-sql-connector-hive-2.2.0/pom.xml
- flink-connectors/flink-sql-connector-hive-2.2.0/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-hive-2.2.0/src/main/resources/META-INF/licenses/LICENSE.antlr
- flink-connectors/flink-sql-connector-hive-2.3.6/pom.xml
- flink-connectors/flink-sql-connector-hive-2.3.6/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-hive-2.3.6/src/main/resources/META-INF/licenses/LICENSE.antlr
- flink-connectors/flink-sql-connector-hive-3.1.2/pom.xml
- flink-connectors/flink-sql-connector-hive-3.1.2/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-hive-3.1.2/src/main/resources/META-INF/licenses/LICENSE.antlr
Include `antlr-runtime` into hive connector uber jars, since it's needed by the hive dialect. The antlr version is 3.5.2 which matches the anrlt parser we added.
- Include `antlr-runtime` in the uber jars
- Update NOTICE and license files
Manually verified hive dialect can be used from SQL client with the uber jars. …
> [FLINK-22107][hive] Include antlr into hive connector uber jars

- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/JdbcXaSinkFunction.java
Fix the release version 
1.11 -> 1.13
> [hotfix] Fix the release version for JdbcXaSinkFunction

- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/formats/raw/RawFormatSerializationSchema.java
Fix raw format exception info with unsupported type.
no need to verify
> [hotfix][table] Fix the exception info of raw format

- docs/content.zh/docs/dev/datastream/operators/windows.md
- docs/content/docs/dev/datastream/operators/windows.md
Just add missed parenthesis into doc demo code for better compile understanding.
> Add missed parenthesis into doc demo code.

- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/expressions/DecimalTypeTest.scala
> [FLINK-17371][table-runtime] Open testDefaultDecimalCasting case in DecimalTypeTest

- flink-tests/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterStopWithSavepointITCase.java
This PR reenables the JobMasterStopWithSavepointIT and adjusts the test so that it passes with changes that happened since it was last run.  
Moreover in the course of debugging the test I realized the result of `Task#triggerCheckpointAsync` is ignored. I added a hotfix commit that fixes it. I considered two ways of fixing it.
1. Changing the result type to `void`
2. Actually returning the future
I decided against option 1. because of the logic in `MultipleInputStreamTask`. So far the whole logic there has been ignored. If that's ok, we could remove it and change the return type to void.
All tests work including `JobMasterStopWithSavepointITCase` …
> [FLINK-21031] Reenable JobMasterStopWithSavepointIT

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/NotifyCheckpointAbortedITCase.java
`NotifyCheckpointAbortedITCase` implicitly assumes that abortion of chk-1 happens before sync phase of chk-2. If abortion is late, the mail that handles the abortion is never executed since the waitLatch blocks the mailbox thread. The latch in turn is never triggered as chk-1 is not aborted.
The fix is to move the wait latch on chk-2 into the source - the only operator that isn't checked for abortion. Thus, the deadlock cannot happen.
Test fix.
- The runtime per-record code paths (performance sensitive): (yes / **no /** don't know) …
> [FLINK-20816][tests] Fix race condition in NotifyCheckpointAbortedITCase.

- flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroFileFormatFactory.java
This replaces a lambda implementation with an explicit anonymous class as otherwise serialization issues can occur. See also FLINK-20147 or FLINK-18006 for similar issues / fixes.
- Replace lambda in `AvroFileFormatFactory` with anonymous class …
> [FLINK-21012][format-avro] Replace lambda with anonymous class to prevent serialization issue

- flink-core/src/main/java/org/apache/flink/api/common/io/DefaultInputSplitAssigner.java
- flink-core/src/main/java/org/apache/flink/api/common/io/LocatableInputSplitAssigner.java
- flink-core/src/main/java/org/apache/flink/core/fs/FileSystem.java
- flink-runtime/src/main/java/org/apache/flink/runtime/externalresource/ExternalResourceUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGate.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/DeclarativeSlotManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/ExecutionGraphHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/CheckpointStorageLoader.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerRunner.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectResultFetcher.java
A collection of various issues around logging. Each commit is self-contained and addresses a separate issue.
> [FLINK-22069] Reduce various logging issues

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliTableauResultView.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliTableauResultViewTest.java
- flink-table/flink-sql-client/src/test/resources/sql/catalog_database.q
- flink-table/flink-sql-client/src/test/resources/sql/insert.q
- flink-table/flink-sql-client/src/test/resources/sql/select.q
- flink-table/flink-sql-client/src/test/resources/sql/statement_set.q
*Use `PrintUtils#printAsTableauForm` to calculate column width in batch mode..*
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not …
> [FLINK-22169][sql-client] Beautify the CliTableauResultView when print

- docs/content/docs/ops/debugging/flame_graphs.md
This is a trivial documentation change.
> [FLINK-22236][docs] Document opt-in behavior of FlameGraph

- docs/content.zh/docs/deployment/config.md
- docs/content/docs/deployment/config.md
- flink-python/pyflink/datastream/checkpoint_config.py
- flink-python/pyflink/datastream/tests/test_check_point_config.py
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/CheckpointConfig.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamConfig.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGenerator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceOperatorStreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTask.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/MultipleInputStreamTaskChainedSourcesCheckpointingTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/MultipleInputStreamTaskTest.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointCompatibilityITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java
This PR revises the newly added APIs for unaligned checkpoint.
- Switch from long (millis) to `Duration` to align with option.
- Adding Python functions.
- Fixes docs.
- Added trivial tests for python API.
- 
- If …
> [FLINK-22290][checkpointing] Polishing unaligned checkpoint API.

- flink-connectors/flink-connector-jdbc/pom.xml
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/JdbcExactlyOnceOptions.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/JdbcSink.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/JdbcBatchingOutputFormat.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/JdbcXaSinkFunction.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/SemanticXidGenerator.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/XaFacade.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/XaFacadeImpl.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/XaFacadePoolingImpl.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/XaGroupOps.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/XaGroupOpsImpl.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/XidGenerator.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/DbMetadata.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/JdbcTestBase.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/JdbcTestFixture.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcExactlyOnceSinkE2eTest.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcXaFacadeTestHelper.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcXaSinkMigrationTest.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcXaSinkTestBase.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/SemanticXidGeneratorTest.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/h2/H2XaResourceWrapper.java
> [BP-1.13][FLINK-22239][jdbc] Support exactly-once (sink) for PgSql and MySql

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGenerator.java
remove redundant config#setCheckpointStorage.
- remove redundant config#setCheckpointStorage.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper:  no
> [hotfix] remove redundant config#setCheckpointStorage.

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/PendingCheckpointStats.java
fix typo, assign processedData to currentProcessedData rather than currentPersistedData.
fix typo, assign processedData to currentProcessedData rather than currentPersistedData.
> [hotfix] fix typo, assign processedData to currentProcessedData rather than currentPersistedData.

- docs/content.zh/docs/connectors/table/filesystem.md
*Translate "Filesystem SQL Connector" page into Chinese*
*Translate "Filesystem SQL Connector" page into Chinese*
The screen shot for the translated chinese page are as following：
> [FLINK-18199] [chinese-translation]: translate FileSystem SQL Connector page into Chinese

- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/factories/TestValuesTableFactory.java
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/CalcITCase.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/typeutils/MapDataSerializer.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/typeutils/MapDataSerializerTest.java
This is a cherry-pick for [FLINK-21247](https://github.com/apache/flink/pull/15569).
> [FLINK-21247][table] Fix problem in MapDataSerializer#copy when there exists custom MapData

- docs/content.zh/docs/dev/table/concepts/timezone.md
- docs/content/docs/dev/table/concepts/timezone.md
*Translate timezone page into Chinese*
- Translate timezone page into Chinese
- doc change, no need to vierfy 
> [FLINK-22428][docs][table] Translate timezone page into Chinese

- docs/content.zh/docs/deployment/resource-providers/standalone/kubernetes.md
- docs/content/docs/deployment/resource-providers/standalone/kubernetes.md
Reactive Mode can currently only be used with (standalone) Kubernetes and proper standalone deployments. Use of reactive mode with standalone deployments is already documented in the docs, this PR adds a section to the (standalone) K8s docs about Reactive Mode.
I decided against providing a full step-by-step guide for using Reactive Mode on K8s, because it would be a duplication of the already existing guide.
Alternatively, we could also publish the reactive mode blog post soon after the release (with a bit more details on how to deploy Flink exactly) and link to it from the docs.
> [FLINK-22495][docs] Add Reactive Mode section to K8s

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateCheckpointWriter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestDispatcherImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriterImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/RecoveredChannelStateHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/Buffer.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/logger/NetworkActionsLogger.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/CheckpointedResultSubpartition.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PipelinedSubpartition.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/RemoteInputChannel.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateCheckpointWriterTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestDispatcherImplTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestDispatcherTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriterImplTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/testutils/ExpectedTestException.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointStressITCase.java
This PR adds extra test coverage for unaligned checkpoints.
> [FLINK-22232][tests] Add UnalignedCheckpointsStressITCase

- flink-table/flink-sql-parser/src/main/resources/org.apache.flink.sql.parser.utils/ParserResource.properties
…createSystemFunctionOnlySupportTemporary describe message.
*(or)*
*(or)*
*(example:)*
- *Added integration tests for …
> [FLINK-22250] flink sql parser module ParserResource.properties lack createSystemFunctionOnlySupportTemporary describe message.

- docs/content.zh/docs/dev/table/common.md
- docs/content/docs/dev/table/common.md
Fix the incorrect Java groupBy clause in Table API docs by adding right parentheses.
> [FLINK-22524][docs] Fix the incorrect Java groupBy clause in Table API docs

- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/util/collections/binary/BytesMap.java
Currently, queries using `BytesMap` will print a lot of verbose INFO level logs. We should avoid this, otherwise, useful information will be submerged.
- `LOG.info` to `LOG.debug`.  …
> [FLINK-22522][table-runtime-blink] BytesHashMap prints many verbose INFO level logs

- flink-python/src/main/java/org/apache/flink/python/util/ZipUtils.java
Correctly format the exception messages in ZipUtils.
Add the right space in the exception messages.
> [hotfix][python] Format exception message in ZipUtils

- docs/content.zh/docs/dev/table/sql/queries/joins.md
- docs/content/docs/dev/table/sql/queries/joins.md
Fix typo in documentation `docs/content.zh/docs/dev/table/sql/queries/joins.md`.
- If yes, how is the feature documented? (**not applicable** …
> [hotfix][docs] Fix typo.

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/CreditBasedSequenceNumberingViewReader.java
> modify annotation

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PipelinedSubpartition.java
This is a back port of https://github.com/apache/flink/pull/14240
> (1.11) [FLINK-20383][runtime] Fix race condition in notification. 

- docs/content.zh/docs/dev/table/sqlClient.md
- docs/content/docs/dev/table/sqlClient.md
From https://ci.apache.org/projects/flink/flink-docs-release-1.13/docs/dev/table/sqlclient/:
```
(snip)
CREATE CATALOG MyCatalog
WITH (
'type' = 'hive'
);
USE MyCatalog;
......
```
The statement `USE MyCatalog' should be 'USE CATALOG MyCatalog'
> [FLINK-22581][docs] Keyword 'CATALOG' is missing in sql client doc

- flink-connectors/flink-connector-kinesis/pom.xml
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumer.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisITCase.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/KinesaliteContainer.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/KinesisPubsubClient.java
- flink-end-to-end-tests/run-nightly-tests.sh
(Slightly adjusted backport of #15826)
During stop-with-savepoint cancel is called under lock in legacy sources. Thus, if the fetcher is trying to emit a record at the same time, it cannot obtain the checkpoint lock. This behavior leads to a deadlock while cancel awaits the termination of the fetcher.
- The fix is to mostly rely on the termination inside the run method. As a safe-guard, close also awaits termination where close is always caused without lock.
- Adding ITCase that covers the behavior.
- Added FlinkKinesisITCase. …
> [FLINK-17170][kinesis] Fix deadlock during stop-with-savepoint. [1.12]

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSourceBuilder.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSourceOptions.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/KafkaSourceEnumerator.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/SpecifiedOffsetsInitializer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReader.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/enumerator/initializer/OffsetsInitializerTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReaderTest.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/StreamMultipleInputProcessorFactory.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceOperatorStreamTask.java
Backport of https://github.com/apache/flink/pull/15161
> [release-1.12][FLINK-20114][connector/kafka,common] Fix a few KafkaSource-related bugs

- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/AllVerticesIterator.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ArchivedExecutionGraph.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java
*Generalize AllVerticesIterator.java*
*Generalize AllVerticesIterator.java*
- Code-Cleanup
- org.apache.flink.runtime.executiongraph.AllVerticesIterator & org.apache.flink.runtime.executiongraph.ArchivedExecutionGraph.AllVerticesIterator
- Code-Cleanup
- org.apache.flink.runtime.executiongraph.AllVerticesIterator & org.apache.flink.runtime.executiongraph.ArchivedExecutionGraph.AllVerticesIterator …
> [FLINK-22609][runtime] Generalize AllVerticesIterator.java

- docs/content.zh/docs/dev/datastream/sources.md
- docs/content/docs/dev/datastream/sources.md
* Fix broken image link
* Corrected image link in sources
- If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / …
> [hotfix][docs] Fixed broken image link

- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java
The problem is that the DefaultLeaderRetrievalService for the ResourceManager is reused by
the JobMaster. Since the DefaultLeaderRetrievalService is only usable once, this means that
the JobMaster can only be started once even though the JobManagerRunnerImpl restarts it in
case of a regained leadership.
> [BP-1.11][FLINK-22597] Make JobMaster restartable

- flink-clients/src/test/java/org/apache/flink/client/program/PerJobMiniClusterFactoryTest.java
- flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/WebFrontendITCase.java
- flink-runtime/src/main/java/org/apache/flink/runtime/iterative/task/AbstractIterativeTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/iterative/task/IterationHeadTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/iterative/task/IterationIntermediateTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/iterative/task/IterationSynchronizationSinkTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/iterative/task/IterationTailTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/iterative/task/Terminable.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/tasks/AbstractInvokable.java
- flink-runtime/src/main/java/org/apache/flink/runtime/operators/BatchTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/operators/DataSinkTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/operators/DataSourceTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/TestingAbstractInvokables.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/CoordinatorEventsExactlyOnceITCase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorOperatorEventHandlingTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/testutils/CancelableInvokable.java
- flink-runtime/src/test/scala/org/apache/flink/runtime/jobmanager/Tasks.scala
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
> [BP-1.12][FLINK-21181][runtime] Wait for Invokable cancellation before releasing network resources

- flink-clients/src/test/java/org/apache/flink/client/program/PerJobMiniClusterFactoryTest.java
- flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/WebFrontendITCase.java
- flink-runtime/src/main/java/org/apache/flink/runtime/iterative/task/AbstractIterativeTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/iterative/task/IterationHeadTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/iterative/task/IterationIntermediateTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/iterative/task/IterationSynchronizationSinkTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/iterative/task/IterationTailTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/iterative/task/Terminable.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/tasks/AbstractInvokable.java
- flink-runtime/src/main/java/org/apache/flink/runtime/operators/BatchTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/operators/DataSinkTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/operators/DataSourceTask.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/TestingAbstractInvokables.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/CoordinatorEventsExactlyOnceITCase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorOperatorEventHandlingTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/testtasks/OnceBlockingNoOpInvokable.java
- flink-runtime/src/test/java/org/apache/flink/runtime/testutils/CancelableInvokable.java
- flink-runtime/src/test/scala/org/apache/flink/runtime/jobmanager/Tasks.scala
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
> [BP-1.13][FLINK-21181][runtime] Wait for Invokable cancellation before releasing network resources

- docs/content/docs/dev/datastream/fault-tolerance/checkpointing.md
- flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsStateBackend.java
Signed-off-by: Yishuang Lu <luystu@gmail.com>
1. Fix the typo in checkpointing.md
2. Fix the typo in the javadoc of FsStateBackend.java
1. Fix the typo in checkpointing.md
2. Fix the typo in the javadoc of FsStateBackend.java
yes
- Dependencies (does it add or …
> [FLINK-22667][docs]Add the missing slash in the file system url of documentation

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/DefaultCompletedCheckpointStore.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/DefaultCompletedCheckpointStoreTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/ZooKeeperCompletedCheckpointStoreMockitoTest.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/CheckpointStoreITCase.java
> [BP-1.13][FLINK-22502][checkpointing] Don't tolerate checkpoint retrieval failures on recovery

- docs/content.zh/docs/connectors/datastream/kafka.md
- docs/content.zh/docs/connectors/datastream/kinesis.md
- docs/content/docs/connectors/datastream/kafka.md
- docs/content/docs/connectors/datastream/kinesis.md
This pull request adds documentation for Glue Schema Registry(GSR)-Flink integration and updates with the latest GSR version.
- Documentation of Flink-Kafka and Flink-Kinesis is updated to introduce GSR integration
- GSR version is updated to 1.0.2
- Using `avro` plugin to converter `.asvc` file to Java POJO class. …
> [FLINK-22515][docs] Add documentation for GSR-Flink Integration

- flink-end-to-end-tests/run-nightly-tests.sh
- flink-end-to-end-tests/test-scripts/common_kubernetes.sh
- flink-end-to-end-tests/test-scripts/container-scripts/kubernetes-pod-template.yaml
- flink-end-to-end-tests/test-scripts/test_kubernetes_application_ha.sh
Backport of #14172 to `release-1.13`.
> [BP-1.13][FLINK-19545][e2e] Add e2e test for native Kubernetes HA

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/DefaultCompletedCheckpointStore.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/DefaultCompletedCheckpointStoreTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/ExecutionGraphCheckpointCoordinatorTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/TestingCheckpointIDCounter.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/TestingCheckpointRecoveryFactory.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/TestingCompletedCheckpointStore.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/ZooKeeperCompletedCheckpointStoreMockitoTest.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/CheckpointStoreITCase.java
> [BP-1.12][FLINK-22502][checkpointing] Don't tolerate checkpoint retrieval failures on recovery

- flink-end-to-end-tests/run-nightly-tests.sh
- flink-end-to-end-tests/test-scripts/test_local_recovery_and_scheduling.sh
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointMetaData.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/checkpointing/CheckpointBarrierHandler.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceOperatorStreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorImpl.java
> [BP-1.13][FLINK-21329][tests] Increase timeout and delay in local test_local_recovery_and_scheduling.sh

- flink-end-to-end-tests/run-nightly-tests.sh
- flink-end-to-end-tests/test-scripts/test_local_recovery_and_scheduling.sh
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointMetaData.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/CheckpointBarrierHandler.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceOperatorStreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorImpl.java
> [BP-1.12][FLINK-21329][tests] Increase timeout and delay in local test_local_recovery_and_scheduling.sh

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/CheckpointStoreITCase.java
Adaptive scheduler doesn't currently retry after failures on recovery.
> [FLINK-22692][tests] Disable CheckpointStoreITCase with adaptive scheduler

- docs/content.zh/docs/dev/table/functions/udfs.md
- docs/content/docs/dev/table/functions/udfs.md
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/expressions/resolver/rules/ExpandColumnFunctionsRule.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/expressions/resolver/rules/StarReferenceFlatteningRule.java
- flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/expressions/resolver/ExpressionResolverTest.java
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/table/CalcITCase.scala
Support (*) as parameter of UDFs in Table API, it will be expanded as all columns of the table.
- An unittest case in ExpressionResolverTest.
> [FLINK-22451][table] Support (*) as parameter of UDFs in Table API

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/CheckpointStoreITCase.java
> [BP-1.13][FLINK-22692][tests] Disable CheckpointStoreITCase with adaptive scheduler

- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/HighAvailabilityServices.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/nonha/AbstractNonHaServices.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/TestingManualHighAvailabilityServices.java
Backport of #15969 to `release-1.13`.
> [BP-1.13][FLINK-22721][ha] Add default implementation for HighAvailabilityServices.cleanupJobData

- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/factories/TestValuesRuntimeFunctions.java
It is frequently to see `ConcurrentModificationException` when using `values` sink these days. This PR is aiming to fix this problem.
```
java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
at java.util.HashMap$ValueIterator.next(HashMap.java:1474)
at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
at java.util.ArrayList.addAll(ArrayList.java:583)
at org.apache.flink.table.planner.factories.TestValuesRuntimeFunctions.lambda$getResults$0(TestValuesRuntimeFunctions.java:108)
at java.util.HashMap$Values.forEach(HashMap.java:981)
at org.apache.flink.table.planner.factories.TestValuesRuntimeFunctions.getResults(TestValuesRuntimeFunctions.java:108)
at org.apache.flink.table.planner.factories.TestValuesTableFactory.getResults(T …
```
> [FLINK-22203][table-runtime-blink] Fix ConcurrentModificationException for testing values sink functions

- docs/content.zh/docs/connectors/datastream/kafka.md
- docs/content/docs/connectors/datastream/kafka.md
Correct document syntax errors
Correct document syntax errors
*(or)*
*(or)*
*(example:)*
- *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, …
> [FLINK-22713][docs] Correct document syntax errors

- docs/content.zh/docs/deployment/config.md
- docs/content/docs/deployment/config.md
**This change is a trivial rework / code cleanup without any test coverage.**
*(or)*
*(or)*
*(example:)*
- …
> [FLINK-22659]Adding execution.checkpointing.interval to Flink Doc

- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisITCase.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/KinesisPubsubClient.java
Unchanged backport of #16002.
The test relies on a few elements remaining pending after stop-with-savepoint, however that can only be guaranteed heuristically: We cannot block task thread or else the respective savepoint will not succeed but we also cannot add infinite input as it's an IT test against Kinesis. Here, the fix is to add much more elements to Kinesis stream. An optimized sendMessage on the test client ensures timely setup. …
> [FLINK-22613][tests] Fix FlinkKinesisITCase.testStopWithSavepoint. [1.13]

- pom.xml
* Upgrade to latest JUnit4 version
* Verify by running all tests
- Dependencies (does it add or upgrade a dependency): (**yes** / no) - test dependency only
> [FLINK-22778] Upgrade to JUnit 4.13

- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
This changes hardens the DispatcherTest#testJobStatusIsShownDuringTermination
by ignoring the JobMaster shutdown exception when querying for the
expected job status.
> [FLINK-22756] Ignore leadership future termination during testing

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliOptionsParser.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/SqlClientTest.java
This is a cherry-pick back to 1.13 branch.
> [BP][FLINK-22795][sql-client] Throw better exception when executing remote SQL file in SQL Client

- docs/content.zh/docs/dev/table/sql/queries/over-agg.md
- docs/content/docs/dev/table/sql/queries/over-agg.md
* Corrected backtick
* Added missing closing backtick …
> [hotfix][docs] Corrected markup backtick

- docs/content.zh/docs/connectors/table/overview.md
- docs/content/docs/connectors/table/overview.md
* Corrected artifactId element in pom 
* Corrected artifactId element in pom  …
> [hotfix][docs] Corrected artifactId element in example

- docs/content.zh/_index.md
*Translate 'Apache Flink Documentation' index page to Chinese.*
*Translate 'Apache Flink Documentation' index page to Chinese.*
*A pure translation work about documentation.*
*Translate 'Apache Flink Documentation' index page to Chinese.* …
> [FLINK-22854][docs-zh] Translate 'Apache Flink Documentation' index page to Chinese.

- docs/content/docs/dev/table/concepts/versioned_tables.md
Minimal correction on Creating Versioned Table Script, adding the missing "," to line 7 to the below script https://ci.apache.org/projects/flink/flink-docs-release-1.13/docs/dev/table/concepts/versioned_tables/#versioned-table-sources
The SQL Script was
CREATE TABLE products (
product_id STRING,
product_name STRING,
price DECIMAL(32, 2),
update_time TIMESTAMP(3) METADATA FROM 'value.source.timestamp' VIRTUAL,
PRIMARY KEY (product_id) NOT ENFORCED
WATERMARK FOR update_time AS update_time
) WITH (...);
where Line 7 ,  "PRIMARY KEY (product_id) NOT ENFORCED" did not have a "," at the end which results below error if copying this script directly into sql client
[ERROR] Could not execute SQL statement. Reason:
org.apache.flink.sql.parser.impl.ParseException: Encountered "WATERMARK" at line 7, …
> [FLINK-22905][docs] Versioned Table's SQL Script was missing a "," at Line 7 which yields Could not execute SQL statement ERROR

- azure-pipelines.yml
- flink-end-to-end-tests/run-nightly-tests.sh
- flink-end-to-end-tests/test-scripts/common_docker.sh
- flink-end-to-end-tests/test-scripts/common_kubernetes.sh
- tools/azure-pipelines/build-apache-repo.yml
- tools/azure-pipelines/build-nightly-dist.yml
- tools/azure-pipelines/build-python-wheels.yml
- tools/azure-pipelines/jobs-template.yml
Azure currently shows warnings because the ubuntu-16.04 image will be deprecated in September. This change will update our CI to ubuntu-20.04 (= ubuntu-latest on Azure).
I chose not to use ubuntu-latest to avoid surprises by Azure updating the version underneath.
> [FLINK-22856][Azure] Upgrade to ubuntu-20.04

- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/FileArchivedExecutionGraphStoreTest.java
Before this commit it was possible that the minicluster shutdown
happened before the resource manager rpc endpoint was available.
This led to an rpc exception failing the test.
> [BP-1.12][FLINK-22908] Wait until cluster is started before testing shutdown

- docs/content.zh/docs/dev/table/sql/queries/overview.md
- docs/content/docs/dev/table/sql/queries/overview.md
*Add instructions for using the " ' " escape syntax of SQL client*
*Add instructions for using the " ' " escape syntax of SQL client*
*Add instructions for using the " ' " escape syntax of SQL client*
*A pure documentation work.* …
> [FLINK-22934][docs] Add instructions for using the " ' " escape syntax of SQL client

- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/factories/TestValuesRuntimeFunctions.java
At present, each task does its own upsert. We need to simulate the external connector and use the global map to do the upsert.
This will reduce bugs from global upsert. …
> [FLINK-22899][table] ValuesUpsertSinkFunction needs to use global upsert

- flink-connectors/flink-connector-kinesis/pom.xml
- flink-connectors/flink-sql-connector-kinesis/pom.xml
- flink-connectors/flink-sql-connector-kinesis/src/main/resources/META-INF/NOTICE
Upgrade Guava dependency for Flink Connector Kinesis. The connector was using Guava 18.0 which is quite old and has been flagged by some security tools as noted in another ticket https://issues.apache.org/jira/browse/FLINK-22774 
This PR also makes the flink-sql-connector-kinesis use the Guava dependency transitively through the flink-connector-kinesis dependency.
- Bumped Guava for Flink Connector Kinesis from 18.0 (inherited from parent) to 29.0-jre
This change is already covered by existing tests, such as `FlinkKinesisProducerTest`. …
> [FLINK-23009][kinesis] Upgrade Guava for Flink Connector Kinesis

- docs/content/docs/deployment/config.md
Add table of contents to the configuration page, as it is quite unwieldy without it.
> [FLINK-22873][config][docs] Add ToC

- flink-java/src/main/java/org/apache/flink/api/java/DataSet.java
Very little PR about javadoc fixes.
R: @pnowojski PTAL
> [hotfix][docs] Fix groupBy() javadocs

- flink-connectors/flink-connector-rabbitmq/pom.xml
- flink-connectors/flink-connector-rabbitmq/src/main/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSource.java
- flink-connectors/flink-connector-rabbitmq/src/main/java/org/apache/flink/streaming/connectors/rabbitmq/common/RMQConnectionConfig.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceITCase.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceTest.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/common/RMQConnectionConfigTest.java
This is a backport of #16023 (fixing FLINK-22698) to release-1.13. 
Please see #16023 for a detailed description.
> [BP-1.13][FLINK-22698][connectors/rabbitmq] Add deliveryTimeout to RabbitMQ source

- flink-connectors/flink-connector-jdbc/pom.xml
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/XaFacadeImpl.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcExactlyOnceSinkE2eTest.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcXaFacadeImplTest.java
> [BP-1.13][FLINK-22462][jdbc] Fix connection leak and stabilize JdbcExactlyOnceSinkE2eTest

- docs/content.zh/docs/dev/table/sql/alter.md
- docs/content.zh/docs/dev/table/sql/create.md
- docs/content.zh/docs/dev/table/sql/drop.md
- Fix document format
- 'Alter Chinese document format repair
- If yes, how is the feature documented? (**not applicable** / docs / JavaDocs …
> [hotfix][docs] ' Chinese document' Format repair

- flink-core/src/main/java/org/apache/flink/configuration/CoreOptions.java
This will allow us to load a separate scala version for Akka.
> [FLINK-23131][conf] Remove scala from PLUGIN_ALWAYS_PARENT_FIRST_LOADER_PATTERNS

- flink-end-to-end-tests/flink-streaming-kinesis-test/src/test/java/org/apache/flink/streaming/kinesis/test/KinesisTableApiITCase.java
- flink-end-to-end-tests/flink-streaming-kinesis-test/src/test/java/org/apache/flink/streaming/kinesis/test/model/Order.java
KinesisTableApiITCase may fail as the query doesn't impose any ordering and a reorder may happen.
- Use order-agnostic check in KinesisTableApiITCase.
Test fix. …
> [FLINK-22492][test] Use order-agnostic check in KinesisTableApiITCase.

- flink-core/src/main/java/org/apache/flink/api/common/typeinfo/Types.java
- flink-core/src/main/java/org/apache/flink/api/java/typeutils/PojoTypeInfo.java
I came by this, so I updated the javadoc.
R: @zentol would you mind taking a look to that tiny PR ?
> [hotfix][docs] Merge the two Flink POJO definitions to make the definition uniform

- docs/content.zh/docs/dev/table/sql/queries/window-tvf.md
- docs/content/docs/dev/table/sql/queries/window-tvf.md
* Description and markup update
* Description and markup update
- If yes, how is the feature documented? (**not applicable** / docs / …
> [hotfix][docs] Updated description of HOP and CUMULATE parameters

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/source/ContinuousFileReaderOperator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/ChainingOutput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/OperatorChain.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/WatermarkGaugeExposingOutput.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/StreamSourceOperatorLatencyMetricsTest.java
- flink-tests/pom.xml
- flink-tests/src/test/java/org/apache/flink/test/streaming/api/functions/source/ContinuousFileReaderOperatorITCase.java
Currently, `ContinuousFileReaderOperator` closes the following chained operator on reaching `endOfInput`.
- Make sure that everything is closed where it's owned - not more or less.
Added ContinuousFileReaderOperatorITCase. …
> [FLINK-20888][runtime] Close outputs in OperatorChain.

- flink-connectors/flink-connector-base/pom.xml
Connectors get shaded into the user jar and as such should contain no unnecessary dependencies to flink. However, connector-base is exposing `flink-core` which then by default gets shaded into the user jar. Except for 6MB of extra size, the dependency also causes class loading issues, when `classloader.parent-first-patterns` does not include `o.a.f`.
Fix is to make `flink-core` provided in `connector-base`.
Manually verified 2 affected connectors. …
> [FLINK-22964][connector/common] Exclude flink-core from connector-common dependencies.

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/source/ContinuousFileReaderOperator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/ChainingOutput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/OperatorChain.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/WatermarkGaugeExposingOutput.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/StreamSourceOperatorLatencyMetricsTest.java
- flink-tests/pom.xml
- flink-tests/src/test/java/org/apache/flink/test/streaming/api/functions/source/ContinuousFileReaderOperatorITCase.java
> [FLINK-20888][runtime] Close outputs in OperatorChain. [1.12]

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/source/ContinuousFileReaderOperator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/ChainingOutput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/OperatorChain.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/WatermarkGaugeExposingOutput.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/StreamSourceOperatorLatencyMetricsTest.java
- flink-tests/pom.xml
- flink-tests/src/test/java/org/apache/flink/test/streaming/api/functions/source/ContinuousFileReaderOperatorITCase.java
> [FLINK-20888][runtime] Close outputs in OperatorChain. [1.13]

- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcExactlyOnceSinkE2eTest.java
```
Currently, the test job makes too many attempts with little progress and
eventually times out.
Too many attempts are made because each checkpoint can be failed by any
FailingMapper that reaches its randomly chosen threshold. And if some
subtask becomes back-pressured then any of three others will likely fail
the checkpoint, reverting the progress.
This change makes sources to pause for the checkpoint confirmation; and
fixes static fields so that it runs more reliably in a loop locally.
```
> [FLINK-22462][tests] Fix JdbcExactlyOnceSinkE2eTest by pausing emission until checkpoint confirmed

- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcExactlyOnceSinkE2eTest.java
> [BP-1.13][FLINK-22462][tests] Fix JdbcExactlyOnceSinkE2eTest by pausing emission until checkpoint confirmed

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/RescalingITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/SavepointITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/TimersSavepointITCase.java
*Fixing the tests with triggerSavepoint*
- *Added awaiting of all tasks running before triggering savepoint *
It tests itself
> [FLINK-22593][tests] Waiting all tasks running before triggerSavepoint

- docs/content.zh/docs/connectors/datastream/pubsub.md
- docs/content/docs/connectors/datastream/pubsub.md
To fix sample code so that it actually uses the variable it created.
-Fixed variable names …
> [Hotfix][Docs] Fix variable name in PubSub sample code

- docs/content.zh/docs/learn-flink/etl.md
*Fix Flink Chinese doc learn-flink/etl transformation.svg display issue*
- *Update Flink Chinese doc learn-flink/etl transformation.svg link*
> [FLINK-23226][docs-zh] Fix Flink Chinese doc learn-flink/etl transformation.svg display issue

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/StreamSource.java
To fix broken javadoc inline link.
Fixed javadoc inline link …
> [hotfix][javadocs] Fix broken inline link

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/AbstractSinkWriterOperator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperatorTestBase.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/util/AbstractStreamOperatorTestHarness.java
> [FLINK-23248][datastream] Close SinkWriter when calling dispose

- docs/content.zh/docs/dev/table/common.md
- docs/content/docs/dev/table/common.md
* Updated explain output to show blink planner output
* Updated explain output to show blink planner output …
> [FLINK-23256][docs][table] - Updated explain output to that of blink planner

- docs/content.zh/docs/dev/table/sql/queries/joins.md
- docs/content/docs/dev/table/sql/queries/joins.md
Impove description of Regular Joins section
Impove description of Regular Joins section
This change is a documentation improve without any test coverage.
> [FLINK-23270][docs] Impove description of Regular Joins section

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/mailbox/MailboxProcessor.java
Ensures the `MailboxProcessor#processMail` does not return if the default method is unavailable.
We should check benchmark results with the changes to check the performance impact of the additional boolean check on the hot path.  …
> [FLINK-23220] MailboxProcessor should wait for default action available even if there are no mails

- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorTest.java
> [BP-1.12][FLINK-22105][tests] Fix checkpoint id in testForceAlignedCheckpointResultingInPriorityEvents

- docs/content.zh/docs/ops/debugging/application_profiling.md
Translate "Application Profiling & Debugging" pages into Chinese.
The page url is `https://ci.apache.org/projects/flink/flink-docs-master/zh/docs/ops/debugging/application_profiling`.
translate ` flink/docs/content.zh/docs/ops/debugging/application_profiling.md`
> [FLINK-23222]Translate page 'Application Profiling & Debugging' into Chinese

- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogStateBackend.java
```
Motivation:
1. ChangelogBackend.savpoint() currently simply delegates to
the underlying backend, so the snapshot doesn't contain
non-materialized state
2. Enable migration to ChangelogBackend from savepoints
3. Some tests create savepoints directly using underlying backends
and then try to recover a regular job from them. This fails with
ChangelogBackend enabled.
```
`SavepointWriterITCase` and other tests fail without these changes if changelog backend is enabled. …
> [FLINK-23278][state/changelog] Allow recovery without non-materialized state

- docs/content.zh/docs/dev/datastream/scala_api_extensions.md
Translate "Scala API Extensions" pages into Chinese.
The page url is https://ci.apache.org/projects/flink/flink-docs-release-1.13/zh/docs/dev/datastream/scala_api_extensions/
- *translate flink/docs/content.zh/docs/dev/datastream/scala_api_extensions.md*
  - Dependencies (does it add or upgrade a dependency): no
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): no
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
  - The S3 file system connector: no 
  - Does this pull request introduce a new …
> [FLINK-23109]Translate "Scala API Extensions" pages into Chinese

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorRestoringTest.java
If we restore from a checkpoint with finished vertices there are certain
graph modifications that are not supported. Usesrs can not add a running
operator followed by a finished one. We throw an exception if we
identify such case.
Moreover so far we do not support vertices with part of the chain
finished. This might happen if the chainning changes before the restore.
We throw an exception in that case as well.
Added tests in `CheckpointCoordinatorRestoringTest` …
> [FLINK-23021] Check for illegal job graph modifications with finished operators

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PipelinedSubpartition.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PipelinedSubpartitionWithReadViewTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/LocalInputChannelTest.java
This PR picks https://github.com/apache/flink/pull/16366 to Release 1.13
> [FLINK-23223] Notifies if there are available data on resumption for pipelined subpartition

- docs/content/docs/connectors/datastream/kafka.md
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSource.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSourceOptions.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/metrics/KafkaSourceReaderMetrics.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReader.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReader.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/metrics/KafkaSourceReaderMetricsTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReaderTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReaderTest.java
- flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testutils/source/reader/TestingReaderContext.java
- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/metrics/testutils/MetricListener.java
- flink-test-utils-parent/flink-test-utils/src/test/java/org/apache/flink/metric/testutils/MetricListenerTest.java
This pull request back-ports:
- #15974 
- #16115
> [BP-1.13][FLINK-22722 / FLINK-22766][connector/kafka] Add docs and metrics for Kafka new source

- docs/content.zh/docs/connectors/datastream/kafka.md
- docs/content/docs/connectors/datastream/kafka.md
* Corrected idleness name
* Corrected idleness name
> [hotfix][docs][kafka] Corrected idleness name

- tools/azure-pipelines/jobs-template.yml
This is a backport of #16427 to Flink 1.11
> [FLINK-23312][ci] speed up compilation for e2e tests (1.11 backport)

- tools/azure-pipelines/jobs-template.yml
This is a backport of #16427 to Flink 1.12
> [FLINK-23312][ci] speed up compilation for e2e tests (1.12 backport)

- tools/azure-pipelines/jobs-template.yml
This is a backport of #16427 to Flink 1.13
> [FLINK-23312][ci] speed up compilation for e2e tests (1.13 backport)

- docs/content.zh/docs/dev/table/functions/systemFunctions.md
- docs/data/sql_functions.yml
- docs/data/sql_functions_zh.yml
- docs/layouts/shortcodes/sql_functions_zh.html
Translate "System Functions" page of "Functions" into Chinese, and fix some wrong descriptions in the English version
- Translate the "System Functions" page of "Functions" into Chinese
- Fix some wrong descriptions in the English version
This change is a trivial rework/code cleanup without any test coverage. …
> [FLINK-16093][docs-zh]Translate "System Functions" page of "Functions" into Chinese

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/checkpointing/CheckpointBarrierHandler.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/checkpointing/CheckpointBarrierTracker.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/checkpointing/SingleCheckpointBarrierHandler.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/checkpointing/AlternatingCheckpointsTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/checkpointing/CheckpointBarrierTrackerTest.java
Backport of https://github.com/apache/flink/pull/16361
> [Flink-23201][bp-1.13] Calculate the alignment time only for the last checkpoint

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/CheckpointBarrierHandler.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/CheckpointBarrierTracker.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/SingleCheckpointBarrierHandler.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/CheckpointBarrierTrackerTest.java
*Backport of  https://github.com/apache/flink/pull/16361*
> [Flink-23201][bp-1.12] Calculate the alignment time only for the last checkpoint

- flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/component/DefaultDispatcherResourceManagerComponentFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/JobManagerMetricGroup.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/util/MetricUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/JobManagerGroupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/JobManagerJobGroupTest.java
> [FLINK-21775][metrics] Migrate JobManagerMG instatiations to factory method

- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/JobManagerJobMetricGroup.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
> [FLINK-21776][metrics] Migrate JobManagerJobMG instatiations to factory method

- flink-dist/pom.xml
- flink-dist/src/main/assemblies/plugins.xml
- flink-docs/pom.xml
- flink-metrics/flink-metrics-influxdb/pom.xml
- flink-metrics/flink-metrics-influxdb/src/test/java/org/apache/flink/metrics/influxdb/InfluxdbReporterTest.java
- flink-metrics/flink-metrics-influxdb/src/test/java/org/apache/flink/metrics/influxdb/MeasurementInfoProviderTest.java
Based on #15177.
- reworks the tests to work directly against the reporter
> [FLINK-21761][metrics][influxdb] Remove flink-runtime dependency 

- flink-metrics/flink-metrics-slf4j/pom.xml
- flink-metrics/flink-metrics-slf4j/src/test/java/org/apache/flink/metrics/slf4j/Slf4jReporterTest.java
Based on #15177.
- reworks the tests to work directly against the reporter
> [FLINK-21772][metrics][slf4j] Remove flink-runtime dependency 

- flink-metrics/flink-metrics-dropwizard/pom.xml
- flink-metrics/flink-metrics-dropwizard/src/test/java/org/apache/flink/dropwizard/ScheduledDropwizardReporterTest.java
- flink-metrics/flink-metrics-dropwizard/src/test/java/org/apache/flink/dropwizard/metrics/DropwizardFlinkHistogramWrapperTest.java
Based on #15177.
Restructures tests, primarily to simplify them by a large degree.
> [FLINK-21764][metrics][dropwizard] Remove flink-runtime dependency 

- flink-dist/pom.xml
- flink-dist/src/main/assemblies/plugins.xml
- flink-docs/pom.xml
- flink-end-to-end-tests/flink-metrics-reporter-prometheus-test/pom.xml
- flink-metrics/flink-metrics-prometheus/pom.xml
> [FLINK-21762][metrics][prometheus] Remove flink-runtime dependency 

- flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/flink/FlinkContainer.java
- flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/flink/FlinkDistribution.java
- flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/flink/SQLJobSubmission.java
*Remove the usage of the yaml file in the `SQLJobSubmission`.*
> [FLINK-23455][e2e] Remove the usage of the yaml file in SQLJobSubmission

- flink-end-to-end-tests/test-scripts/kafka_sql_common.sh
- flink-end-to-end-tests/test-scripts/test_sql_client.sh
*Remove the usage of the YAML file in SQL Client end to end tests.*
> [FLINK-23446][e2e] Refactor SQL Client end to end tests

- flink-end-to-end-tests/test-scripts/test_pyflink.sh
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/context/DefaultContext.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/local/LocalContextUtils.java
*Remove usage of the YAML file in pyflink.sh. *
> [FLINK-23467][e2e] Remove usage of the YAML file in pyflink.sh

- docs/content.zh/docs/connectors/datastream/overview.md
- docs/content.zh/docs/dev/python/table/python_table_api_connectors.md
- docs/content.zh/release-notes/flink-1.8.md
- docs/content.zh/release-notes/flink-1.9.md
- docs/content/docs/dev/python/table/python_table_api_connectors.md
- docs/content/release-notes/flink-1.8.md
- docs/content/release-notes/flink-1.9.md
> [hotfix][docs] Fix typos that Flink is miswritten as Fink

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorImpl.java
Try best to ensure all operators and state manager handle the checkpoint complete notification
Change the logic to handle checkpoint complete notification.
> [FLINK-23471][checkpoint] Try best to ensure all operators and state manager handle the checkpoint complete notification

- flink-dist/src/main/resources/META-INF/NOTICE
- flink-end-to-end-tests/flink-glue-schema-registry-test/pom.xml
- flink-formats/flink-avro-glue-schema-registry/pom.xml
- flink-runtime/pom.xml
- pom.xml
Bumps lz4-java to the latest version, for general fixes and improvements.
> [FLINK-23447][build] Bump lz4-java to 1.8.0

- flink-connectors/flink-connector-elasticsearch5/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-connector-kinesis/pom.xml
- flink-connectors/flink-connector-kinesis/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-connector-twitter/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-elasticsearch6/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-elasticsearch7/src/main/resources/META-INF/NOTICE
- flink-end-to-end-tests/flink-glue-schema-registry-test/pom.xml
- flink-filesystems/flink-azure-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-oss-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-hadoop/pom.xml
- flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-presto/pom.xml
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE
- pom.xml
* Flink is still using org.apache.httpcomponents.httpclient:4.5.3 and org.apache.httpcomponents.httpclient:4.5.9. Those versions are impacted by CVE-2020-13956 (though Flink is not impacted by it). The latest available version is 4.5.13
- Updated httpclient dependencies from 4.5.3 and 4.5.9 to 4.5.13
- Updated NOTICE files to deal with new version number
- Anything that affects deployment or recovery: no …
> [FLINK-23438] Bump httpclient from 4.5.3 and 4.5.9 to 4.5.13

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliClient.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliStrings.java
- flink-table/flink-sql-client/src/test/resources/sql-client-help-command.out
- flink-table/flink-sql-client/src/test/resources/sql/misc.q
*Supplement 'HELP' command prompt message for SQL-Cli.*
*Supplement 'HELP' command prompt message for SQL-Cli.*
*Supplement 'HELP' command prompt message for SQL-Cli.* …
> [FLINK-22860][table sql-client] Supplement 'HELP' command prompt message for SQL-Cli.

- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceITCase.java
- flink-connectors/flink-connector-rabbitmq/src/test/resources/log4j2-test.properties
- Capture RabbitMQ container log output to ease triaging and increase handshake timeout
> [FLINK-23322][connectors/rabbitmq] Increase RMQSource handshake timeout tolerating network congestions

- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/DefaultSchemaResolver.java
- flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/SchemaResolutionTest.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/api/Schema.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/Column.java
*Support column comment in Schema and ResolvedSchema*
- Support column comment in Schema and ResolvedSchema
such as
-  testSchemaResolution  in SchemaResolutionTest .
-  testUnresolvedSchemaString  in SchemaResolutionTest .
-  testResolvedSchemaString  in SchemaResolutionTest .
I only made small change in SchemaResolutionTest.  …
> [FLINK-22936] Support column comment in Schema and ResolvedSchema

- flink-filesystems/flink-s3-fs-presto/pom.xml
- pom.xml
Adds error messages in case on of the bannedDependencies rules is triggered, to make the violation easier to understand/fix.
> [FLINK-23517][build] Add error messages for bannedDependencies rules

- docs/content.zh/docs/dev/table/tableApi.md
Translate "Table API" page of "Table API & SQL" into Chinese.
The page url is https://ci.apache.org/projects/flink/flink-docs-master/zh/dev/table/tableApi.html
- *translate flink/docs/content.zh/docs/dev/table/tableApi.md*
> [FLINK-16090] Translate "Table API" page of "Table API & SQL" into Chinese

- docs/layouts/shortcodes/artifact.html
*Fix wrong words in the document. Avoid the problem of lib introduction failure when users use it.*
Application Development -> DataStream API -> Testing -> "classifer"
- *change classifer to classifier*
- The S3 file system connector: (yes / no …
> [FLINK-23569][Documentation]The Testing page of the documentation has a word error

- docs/content.zh/docs/connectors/datastream/kafka.md
- docs/content.zh/docs/connectors/datastream/kinesis.md
- docs/content.zh/docs/connectors/datastream/streamfile_sink.md
- docs/content.zh/docs/deployment/advanced/external_resources.md
- docs/content.zh/docs/deployment/config.md
- docs/content.zh/docs/deployment/memory/mem_migration.md
- docs/content.zh/docs/deployment/memory/mem_tuning.md
- docs/content.zh/docs/dev/dataset/iterations.md
- docs/content.zh/docs/dev/datastream/event-time/generating_watermarks.md
- docs/content.zh/docs/dev/datastream/fault-tolerance/queryable_state.md
- docs/content.zh/docs/dev/datastream/fault-tolerance/serialization/custom_serialization.md
- docs/content.zh/docs/dev/table/common.md
- docs/content.zh/docs/ops/state/checkpoints.md
- docs/content.zh/docs/ops/state/savepoints.md
- docs/content.zh/docs/ops/state/state_backends.md
- docs/content/docs/connectors/datastream/kinesis.md
- docs/content/docs/deployment/advanced/external_resources.md
- docs/content/docs/deployment/config.md
- docs/content/docs/deployment/memory/mem_migration.md
- docs/content/docs/deployment/memory/mem_tuning.md
- docs/content/docs/dev/dataset/iterations.md
- docs/content/docs/dev/datastream/event-time/generating_watermarks.md
- docs/content/docs/dev/datastream/fault-tolerance/queryable_state.md
- docs/content/docs/ops/state/savepoints.md
*(or)*
*(or)*
*(example:)*
- *Extended …
> [FLINK-23463][doc] Replace the <div> tag with ShortCodes in document

- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/table/JdbcRowDataLookupFunction.java
* Corrected exception variable name
* Corrected variable name
- The serializers:  no 
- The S3 file system connector:  no 
> [hotfix][connector][jdbc] Corrected exception variable name

- flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/BatchingStateChangeUploaderTest.java
Fix flaky `BatchingStateChangeUploaderTest.testDelay`
by explicitly checking and triggering scheduled tasks
instead of waiting.
> [FLINK-23634][tests] Explicitly trigger scheduled tasks

- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/DefaultSchedulerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/TestExecutionVertexOperationsDecorator.java
Hardens the test by removing a sleep.. Instead we wait for a certain number of events to occur.
> [FLINK-23610][tests] Harden DefaultSchedulerTest

- docs/content.zh/docs/connectors/datastream/streamfile_sink.md
- docs/content.zh/docs/dev/datastream/testing.md
- docs/content/docs/connectors/datastream/file_sink.md
- docs/content/docs/connectors/datastream/streamfile_sink.md
- docs/content/docs/dev/datastream/testing.md
- docs/layouts/shortcodes/artifact.html
*Update the maven dependency of the File Sink page in the document.
There is a problem with some maven dependencies in the documentation. Chinese and English documentation is not consistent. Some maven dependencies are not available.*
- *Update maven dependencies* …
> [FLINK-23570][Documentation] Update the maven dependency of the File Sink page in the document

- flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/SqlPartitionUtils.java
- flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/package-info.java
* Fixed typo.
* Fixed typo.
* Fixed typo.
> [Hotfix][flink-sql-parser] Fixed typo.

- flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/BootstrapTools.java
> [hotfix][runtime] Fix log info

- flink-connectors/flink-connector-jdbc/pom.xml
- flink-python/pom.xml
- deduplicate postgresql dependency in flink-connector-jdbc (another `provided` one with a different version exists)
- deduplicate antrun-plugin in flink-python
> [FLINK-23644][build] Resolve maven warnings

- docs/content.zh/docs/dev/datastream/event-time/built_in.md
Error translation in "Builtin Watermark Generators" page https://ci.apache.org/projects/flink/flink-docs-master/zh/docs/dev/datastream/event-time/built_in/.
Error translation located in 'flink/docs/content.zh/docs/dev/datastream/event-time/built_in.md'.
This change is already covered by existing tests, such as *(please describe tests)*.appens correctly. …
> [FLINK-23701][docs] Fix Error translation in "Builtin Watermark Generators" page

- docs/content.zh/docs/dev/table/tableApi.md
- docs/content/docs/dev/table/tableApi.md
* Corrected unionAll  doc
* Corrected unionAll doc
> [hotfix][table][api][unionAll] - Corrected unionAll operator doc

- flink-filesystems/flink-azure-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-oss-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-hadoop/src/main/java/org/apache/flink/fs/s3hadoop/HadoopS3AccessHelper.java
- flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE
- flink-filesystems/pom.xml
Upgrading shaded hadoop to 3.3.1 exhibited HADOOP-17771.
- Downgrade to hadoop 3.2.2
Already covered as this is PR is fixing test failures.
- If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / …
> [FLINK-23722][fs] Downgrade shaded hadoop to 3.2.2 to avoid HADOOP-17771.

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/sink/KafkaSinkITCase.java
- flink-connectors/flink-connector-kafka/src/test/resources/log4j2-test.properties
Before this change, multiple variables were changed across thread barriers without proper synchronization. The change introduces proper synchronization to alleviate the seen problem.
- Use volatile variable for counting emitted records
- Use lock to synchronize snapshotting and writing. …
> [FLINK-23678][tests] Harden KafkaSinkITCase#testWriteRecordsToKafkaWithExactlyOnceGuarantee

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliClient.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientTest.java
*Fix SqlClient doesn't response correctly to Signal.INT*
*Sqlclient would interupt the Executor when receive Signal.INT before ResultView opening*
*Added test case in **org.apache.flink.table.client.cli.CliClientTest.testCancelExecutionInteractiveMode***
> [FLINK-23645][Table SQL / Client] Fix SqlClient doesn't response correctly to Signal.INT

- docs/content.zh/docs/ops/state/state_backends.md
FLINK-11634: https://issues.apache.org/jira/browse/FLINK-11634
Translate "State Backends" page into Chinese
Translate page: https://ci.apache.org/projects/flink/flink-docs-master/docs/ops/state/state_backends/
> [FLINK-11634][docs] Translate "State Backends" page into Chinese

- docs/content.zh/docs/dev/dataset/zip_elements_guide.md
*Translate the 'Zipping Elements in a DataSet' page inito Chinese*
*Translate the 'Zipping Elements in a DataSet' page inito Chinese*
*Translate the 'Zipping Elements in a DataSet' page inito Chinese* …
> [FLINK-23716][docs-zh] Translate the 'Zipping Elements in a DataSet' page inito Chinese

- docs/content/docs/connectors/table/kafka.md
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/DeliveryGuarantee.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/sink/KafkaRecordSerializationSchema.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/sink/KafkaSinkBuilder.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/sink/KafkaTransactionLog.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/sink/KafkaWriter.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/BufferedUpsertSinkFunction.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/DynamicKafkaRecordSerializationSchema.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/KafkaConnectorOptions.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/KafkaConnectorOptionsUtil.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/KafkaDynamicSink.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/KafkaDynamicTableFactory.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/UpsertKafkaDynamicTableFactory.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaDynamicTableFactoryTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/UpsertKafkaDynamicTableFactoryTest.java
- flink-connectors/flink-connector-kafka/src/test/resources/log4j2-test.properties
- Migrate Table API Kafka connector to use FLIP-143 KafkaSink
Internally the KafkaDynamicSink translates now to the newly introduced KafkaSink. Only the buffered-upsert sink will fallback to the old FlinkKafkaProducer which we will have to address as followup.
- Adapted the existing tests to do the translation
- Introduced new tests for new conditional logic i.e. transactionalPrefix/deliverGuarantee depedency …
> [FLINK-23639][connectors/kafka] Migrate Table API Kafka connector to use FLIP-143 KafkaSink

- docs/content/docs/deployment/resource-providers/yarn.md
There is the following line in page `Deployment/Resource Providers/Yarn`:
```
[测试](\{{< downloads >}})
```
I think it was introduced by mistake.
- `docs/content/docs/deployment/resource-providers/yarn.md`
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / …
> [FLINK-23736] [docs] Delete unnecessary test line in page `Deployment/Resource Providers/Yarn`

- docs/content.zh/docs/dev/datastream/overview.md
- docs/content/docs/dev/datastream/overview.md
> [hotfix][docs] Fix typo in datastream api

- docs/layouts/shortcodes/generated/checkpointing_configuration.html
- docs/layouts/shortcodes/generated/common_state_backends_section.html
- flink-core/src/main/java/org/apache/flink/configuration/CheckpointingOptions.java
- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogOptions.java
- flink-python/pyflink/datastream/stream_execution_environment.py
- flink-python/pyflink/datastream/tests/test_stream_execution_environment.py
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogStateBackendLoadingTest.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironmentComplexConfigurationTest.java
- flink-streaming-scala/src/main/scala/org/apache/flink/streaming/api/scala/StreamExecutionEnvironment.scala
- pom.xml
...as it won't make it to the upcoming release.
> [FLINK-23738][state] Hide ChangelogBackend public API and config options

- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientTest.java
…ionInteractiveMode
*Fix the unstable test `CliClientTest`. The main reason why it is unstable is because we use the main thread to observe the client thread whether is interrupted. However, the worker thread will clear the INTERUPTED flag and continue its execution. Although we raise the signal we may find the flag is cleared or not set. I think we should check whether the client can continue process the commands after the interruption rather than the thread status here.*
> [FLINK-23744][sql-client] Fix unstable CliClientTest

- flink-metrics/flink-metrics-prometheus/src/test/java/org/apache/flink/metrics/prometheus/PrometheusReporterTaskScopeTest.java
- flink-metrics/flink-metrics-prometheus/src/test/java/org/apache/flink/metrics/prometheus/PrometheusReporterTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/TaskManagerJobMetricGroup.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/InternalOperatorGroupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/MetricGroupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/TaskMetricGroupTest.java
Modify all existing usages of the TaskManagerJobMG constructor to use runtime Apis, for consistency and to make constructor changes easier.
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after master …
> [FLINK-23625] [Runtime / Metrics] Migrate all TaskManagerJobMG instantiations to factory method

- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/CoordinatedSourceITCase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/testutils/InMemoryReporter.java
- flink-runtime/src/test/java/org/apache/flink/runtime/testutils/InMemoryReporterRule.java
- flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/SinkITCase.java
Some metrics are only unregistered after the test case has already finished.
That means that metrics from test case A can spill into test case B using the same mini cluster.
- Synchronize accesses in InMemoryReporter.
- Use unique operator names for metric tests. 
Stabilizing existing tests. …
> [FLINK-23785][tests] Stabilize metric tests.

- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/StreamTaskTimerTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTestHarness.java
*This PR fixes the test StreamTaskTimerTest.testOpenCloseAndTimestamps*
- *Waiting for all threads which should be triggered during the task start before spawning the new thread for the test*
- If yes, …
> [FLINK-23680][streaming] Wait until all expected threads would be triggered in testOpenCloseAndTimestamps

- docs/content.zh/docs/deployment/resource-providers/standalone/kubernetes.md
Translate "deployment/resource-providers/standalone/kubernetes.md" page into Chinese
> [FLINK-13092][docs-zh] Translate "deployment/resource-providers/standalone/kubernetes.md" page into Chinese

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/BufferWritingResultPartition.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/ResultPartition.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/ResultPartitionTest.java
This patch fixes the network buffer leak when ResultPartition is released by closing all BufferBuilders.
- All BufferBuilders are closed in the BufferWritingResultPartition#close method;
- The TaskCanceler call the ResultPartition#fail method instead of the ResultPartition#close method because the close method can incur concurrency issue.
An existing test is modified to cover the scenario. …
> [FLINK-23724][network] Fix the network buffer leak when ResultPartition is released

- flink-runtime-web/web-dashboard/src/app/interfaces/job-exception.ts
- flink-runtime-web/web-dashboard/src/app/pages/job/exceptions/job-exceptions.component.html
- flink-runtime-web/web-dashboard/src/app/pages/job/exceptions/job-exceptions.component.less
- flink-runtime-web/web-dashboard/src/app/pages/job/exceptions/job-exceptions.component.ts
https://issues.apache.org/jira/browse/FLINK-21867
> [FLINK-21867][runtime-web] Expose concurrent exceptions in Web UI.

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcher.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcherTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/TestableKinesisDataFetcher.java
FlinkKinesisConsumer#cancel() (inside KinesisDataFetcher#shutdownFetcher()) shouldn't be interrupting source thread. Otherwise, as described in FLINK-23527, network stack can be left in an invalid state and downstream tasks can encounter deserialisation errors.
- Use a future for a soft wakeup during cancellation.
Added a test that verifies that cancellation still works. Testing that no `InterruptedException` is thrown proved to be impossible. …
> [FLINK-23528][kinesis] Do not interrupt main thread during cancellation.

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/MetricUtil.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaWriter.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaWriterITCase.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/InternalSinkWriterMetricGroup.java
This PR adds the FLIP-33 metrics numBytesOut and currentSendTime to the FLIP-143 KafkaWriter.
- 01de3e6 adds a test util to properly assert on operator io metrics
Added two tests verifying that both metrics are correctly emitted. …
> [FLINK-23838][connectors/kafka] Implement FLIP-33 metrics for KafkaSink

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaTransactionLog.java
Before this PR we simply used KafkaConsumer#subcribe(topic) to read from
the transaction log topic. Unfortunately, this has the downside that not
all partitions are immediately assigned to the consumer. This could
cause an IllegalStateException when trying to access the latest offset
of a not yet assigned partition.
Now the partitions are fetched once and the consumer is assigned to all
of them immediately.
- Change KafkaConsumer#subscribe(topic) to KafkaConsumer#assign(partitionList)
- I ran the failing test 3 x 20 and did not see any failures anymore …
> [FLINK-23866][connectors/kafka] Statically assign partitions when reading transaction log topic

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaRecordSerializationSchema.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaRecordSerializationSchemaBuilder.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaSerializerWrapper.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaRecordSerializationSchemaBuilderTest.java
Add a builder to cover the construction of common KafkaRecordSerializationSchemas.
- Added tests with example serialization
- If yes, how is the feature documented? (not applicable / docs / **JavaDocs** / not documented)
>  [FLINK-23640][connectors/kafka] Add KafkaRecordSerializationSchemaBuilder to cover common serialization scenarios

- flink-runtime/src/main/java/org/apache/flink/runtime/jobmanager/OnCompletionActions.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/DefaultJobMasterServiceProcess.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobAlreadyDoneException.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMasterServiceLeadershipRunner.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/DefaultJobMasterServiceProcessTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterServiceLeadershipRunnerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/utils/JobMasterBuilder.java
Backport of #16894 onto `release-1.13` branch.
> [BP-1.13][FLINK-23871][Runtime/Coordination] Dispatcher should handle finishing job exception when recover

- docs/content.zh/docs/deployment/finegrained_resource.md
- docs/content/docs/deployment/finegrained_resource.md
Claim that the slot allocation result might not be optimal
*(or)*
*(or)*
*(example:)*
- *Added integration tests for …
> [FLINK-23893][docs] Add limitation of fine grained resource management

- docs/content/docs/connectors/datastream/hybridsource.md
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSource.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceEnumeratorState.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceEnumeratorStateSerializer.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceReader.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplit.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumerator.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitSerializer.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/SourceReaderFinishedEvent.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/SwitchSourceEvent.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceITCase.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceReaderTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumeratorTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitSerializerTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceTest.java
Backport of https://github.com/apache/flink/pull/15924
See https://lists.apache.org/thread.html/rb122520f43637a48e5b92f5d20cf05eedf15f5f7e4e1d7b557173561%40%3Cdev.flink.apache.org%3E
> [release-1.13][FLINK-22670][FLIP-150][connector/common] Hybrid source baseline

- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/test/util/TestBaseUtils.java
> [FLINK-23968][tests] Remove unused code from TestBaseUtils

- .idea/vcs.xml
In FLINK-24013, we support link for FLINK-XXX to JIRA issue in IDEA git log display. However, the FLIP-XXX is also processed in the same way which leads to a wrong link, e.g. FLIP-33 is linked to https://issues.apache.org/jira/browse/FLIP-33.
Change the `issueRegexp` to fully match `FLINK-` `FLIP-` prefix and direct to different link.
Verified in my local IDEA.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / …
> [FLINK-24026][misc] Fix FLIP-XXX link can't be recognized correctly by IDEA

- flink-end-to-end-tests/flink-queryable-state-test/src/main/java/org/apache/flink/streaming/tests/queryablestate/QsStateProducer.java
Backport of #17027 to `release-1.13`.
> [BP-1.13][FLINK-23954][tests] Fix e2e test test_queryable_state_restart_tm.sh

- flink-end-to-end-tests/flink-queryable-state-test/src/main/java/org/apache/flink/streaming/tests/queryablestate/QsStateProducer.java
Backport of #17027 to `release-1.12`.
> [BP-1.12][FLINK-23954][tests] Fix e2e test test_queryable_state_restart_tm.sh

- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/runner/DefaultDispatcherRunner.java
Backport of #17033 to `release-1.14`.
> [BP-1.14][FLINK-23947] Improve logging of granting/revoking leadership in DefaultDispatcherRunner

- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/runner/DefaultDispatcherRunner.java
Backport of #17033 to `release-1.13`.
> [BP-1.13][FLINK-23947] Improve logging of granting/revoking leadership in DefaultDispatcherRunner

- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/runner/DefaultDispatcherRunner.java
Backport of #17033 to `release-1.12`.
> [BP-1.12][FLINK-23947] Improve logging of granting/revoking leadership in DefaultDispatcherRunner

- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceReader.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumerator.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceReaderTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumeratorTest.java
cherry pick https://github.com/apache/flink/pull/17006
> [FLINK-24010][connector/common] HybridSourceReader/Enumerator delegate checkpoint notifications

- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceReader.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumerator.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceReaderTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumeratorTest.java
Cherry pick of https://github.com/apache/flink/pull/17006
> [release-1.13][FLINK-24010][connector/common] HybridSourceReader/Enumerator delegate checkpoint notifications

- docs/content/docs/connectors/datastream/kafka.md
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaSink.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaSinkBuilder.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaWriter.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaSinkITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaWriterITCase.java
> [FLINK-23664][docs] Add docs for KafkaSink [1.14]

- flink-tests/src/test/java/org/apache/flink/test/streaming/api/FileReadingWatermarkITCase.java
> [FLINK-23351][tests] Harden FileReadingWatermarkITCase by counting watermarks after source operator finishes [1.14]

- docs/content/docs/connectors/datastream/kafka.md
- docs/content/docs/connectors/datastream/overview.md
- docs/content/docs/connectors/datastream/streamfile_sink.md
- docs/content/docs/ops/metrics.md
Add metric description to Kafka source (see FLIP-33, FLIP-179).
> [FLINK-23817][docs] Add metric description to Kafka source.

- docs/content/docs/connectors/datastream/kafka.md
- docs/content/docs/connectors/datastream/overview.md
- docs/content/docs/connectors/datastream/streamfile_sink.md
- docs/content/docs/ops/metrics.md
> [FLINK-23817][docs] Add metric description to Kafka source. [1.14]

- docs/content.zh/docs/internals/filesystems.md
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaConsumer.java
- flink-core/src/main/java/org/apache/flink/api/common/JobStatus.java
- flink-core/src/main/java/org/apache/flink/api/common/state/ValueState.java
- flink-core/src/main/java/org/apache/flink/core/fs/FileSystem.java
- flink-java/src/main/java/org/apache/flink/api/java/DataSet.java
- flink-java/src/main/java/org/apache/flink/api/java/operators/CrossOperator.java
- flink-python/pyflink/common/job_status.py
- flink-python/pyflink/datastream/connectors.py
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/ResultPartitionType.java
- flink-runtime/src/main/java/org/apache/flink/runtime/registration/RegisteredRpcConnection.java
- flink-runtime/src/main/java/org/apache/flink/runtime/registration/RetryingRegistration.java
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/LegacyTableSourceITCase.scala
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/sort/BinaryExternalSorter.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/types/PlannerTypeUtils.java
Fix small typo in Javadocs
- Fix small typo in ValueState Javadocs
- change `null` to `{@code null}`
- fix typo: loose(s) -> lose(s)
> [docs] Fix small typo in ValueState Javadocs

- docs/layouts/shortcodes/generated/all_taskmanager_section.html
- docs/layouts/shortcodes/generated/task_manager_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/TaskManagerOptions.java
Backport of #16995 to `release-1.14`.
> [BP-1.14][FLINK-22002][tests] Let taskmanager.slot.timeout fall back to akka.ask.timeout

- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/Execution.java
- flink-tests/src/test/java/org/apache/flink/test/recovery/AbstractTaskManagerProcessFailureRecoveryTest.java
- flink-tests/src/test/java/org/apache/flink/test/recovery/TaskManagerProcessFailureBatchRecoveryITCase.java
Backport of #17107 to `release-1.14`.
> [BP-1.14][FLINK-24091][tests] Harden TaskManagerProcessFailureBatchRecoveryITCase

- docs/content/docs/try-flink/datastream.md
- docs/content/docs/try-flink/table_api.md
This pull request improves the 'Try Flink' documentation by making the tutorial easier to follow.
- *The 'Running in an IDE' subsection is moved to the Prerequisites section*
- *A sentence in the Table API Example was fixed*
> [hotfix][docs] Try Flink Improvements

- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/sort/LimitOperator.java
Signed-off-by: TennyZhuang <zty0826@gmail.com>
Clean code in `LimitOperator`
- Remove useless collector in LimitOperator
No
> [FLINK-24158][runtime] Remove useless collector in LimitOperator

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/ProcessingTimeServiceUtil.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/StreamTaskTimerTest.java
*PR fixes the checkScheduledTimestamps test*
- *Removed usage of currentTimeMillis without a shift in checkScheduledTimestamps because it leaded to instability* …
> [FLINK-23960][streaming] checkScheduledTimestamps changed according to semantic of the calculation processing time delay 

- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/DeclarativeSlotManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/DefaultResourceTracker.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/FineGrainedSlotManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/JobScopedResourceTracker.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/ResourceTracker.java
*(or)*
*(or)*
*(example:)*
- *Extended …
> [FLINK-23912] Remove unnecessary "Clearing resource requirements of job" in SlotManager

- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSource.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceEnumeratorState.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceEnumeratorStateSerializer.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceReader.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplit.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumerator.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitSerializer.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/SwitchedSources.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceReaderTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumeratorTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitSerializerTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/mocks/MockBaseSource.java
Backport https://github.com/apache/flink/pull/17111
> [release-1.13][FLINK-24064][connector/common] HybridSource restore from savepoint

- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSource.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceEnumeratorState.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceEnumeratorStateSerializer.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceReader.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplit.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumerator.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitSerializer.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/SwitchedSources.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceReaderTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumeratorTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitSerializerTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/mocks/MockBaseSource.java
Backport https://github.com/apache/flink/pull/17111
> [release-1.14][FLINK-24064][connector/common] HybridSource restore from savepoint

- flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendTestBase.java
Ensure to close and dispose created keyed-statebackend in StateBackendTestBase to avoid JVM crash.
Change `StateBackendTestBase`.
> [FLINK-23983][tests] Ensure to close and dispose created keyed-statebackend in StateBackendTestBase

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/IgnoreInFlightDataITCase.java
PR fixes the IgnoreInFlightData test in case when the first attempt fails
- *Added timeout for test*
- *Added increasing checkpoint interval for the each next attemp*
- *Added throwing the stopping exception for all checkpoints not only first one* …
> [FLINK-24069][tests] Fail IgnoreInFlightData test when there is not enough data for it for all checkpoints not only the first one 

- docs/content/docs/dev/table/sql/queries/window-topn.md
* Fixed SQL example statement for Window Top-N after Windowing TVF
* Updated SQL statement …
> [hotfix][docs] Update Window TopN SQL example

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/KeyContext.java
This pull request modify KeyContext comment work spelling error.
org.apache.flink.streaming.api.operators.KeyContext interface annotation word spelling  error. modify from Inteface to Interface. …
> [FLINK-24165][API/DataStream]Modify the spelling mistakes of the comment word.

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/FlinkKafkaInternalProducer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaCommitter.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaWriter.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/Recyclable.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaCommitterTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaSinkITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaWriterITCase.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesCheckpointIDCounter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointIDCounter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/StandaloneCheckpointIDCounter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/ZooKeeperCheckpointIDCounter.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/SinkOperator.java
> [FLINK-24131][datastream/kafka] Reliably shutdown producer [1.14]

- flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/flink/FlinkContainer.java
- flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/flink/FlinkContainerTestEnvironment.java
- flink-runtime/src/test/java/org/apache/flink/runtime/testutils/CommonTestUtils.java
- flink-test-utils-parent/flink-connector-testing/src/main/java/org/apache/flink/connectors/test/common/environment/MiniClusterTestEnvironment.java
This pull request changes the behavior of detecting TaskManager termination in ```MiniClusterTestEnvironment``` to make the test more stable.
- Use `RestClient` to detect if the TaskManager has been terminated in test environments …
> [FLINK-23807][connector/testing-framework] Use RestClient to detect TaskManager failure in test environments

- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/PartiallyFinishedSourcesITCase.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/event/CheckpointCompletedEvent.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/event/CheckpointStartedEvent.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/event/InputEndedEvent.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/event/OperatorFinishedEvent.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/event/OperatorStartedEvent.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/event/TestCommandAckEvent.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/event/TestEvent.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/event/WatermarkReceivedEvent.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/graph/MultiInputTestOperator.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/graph/OneInputTestStreamOperator.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/graph/TestEventSource.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/graph/TwoInputTestStreamOperator.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/validation/DrainingValidator.java
> [BP-1.14][FLINK-24162][tests] Check MAX_WATERMARK per attempt in FLIP-147 tests

- pom.xml
Signed-off-by: slinkydeveloper <francescoguard@gmail.com>
Fix build with newer Maven versions.
- Replaced usage of `highest-dir` with `directory-of`
This change is already covered by existing tests, such as Maven build, which should fail in case the variable is not set properly
> [FLINK-24170] [build] Replace usage of directory-maven-plugin with directory-of goal

- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/network/AbstractServerTest.java
*This pull request for fix AbstractServerTest.testServerInitializationFailure falls due to port conflict*
* Catch server1 port occupied exception in testServerInitializationFailure test*
> [FLINK-24203][runtime][tests] Resolve AbstractServerTest fails due to port conflict

- flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/flink/FlinkContainer.java
- flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/flink/FlinkContainerTestEnvironment.java
- flink-runtime/src/test/java/org/apache/flink/runtime/testutils/CommonTestUtils.java
- flink-test-utils-parent/flink-connector-testing/src/main/java/org/apache/flink/connectors/test/common/environment/MiniClusterTestEnvironment.java
> [BP-1.14][FLINK-23807][connector/testing-framework] Use RestClient to detect TaskManager failure in test environments

- docs/content.zh/docs/deployment/filesystems/azure.md
- docs/content.zh/docs/deployment/filesystems/overview.md
Translate the documentation changes that were made in this PR to chinese [https://github.com/apache/flink/pull/16559/](https://github.com/apache/flink/pull/16559/)
- Translate the content related to https://github.com/apache/flink/pull/16559/ in `flink/docs/content.zh/docs/deployment/filesystems/azure.md`
- Translate the content related to https://github.com/apache/flink/pull/16559/ in `flink/docs/content.zh/docs/deployment/filesystems/overview.md`
- Correct the bold display of the 50th line in `flink/docs/content.zh/docs/deployment/filesystems/overview.md` …
> [FLINK-23462] [docs-zh] Translate the abfs documentation to chinese

- docs/content.zh/docs/connectors/datastream/pulsar.md
- docs/content/docs/connectors/datastream/pulsar.md
- docs/layouts/shortcodes/generated/pulsar_admin_configuration.html
- docs/layouts/shortcodes/generated/pulsar_client_configuration.html
- docs/layouts/shortcodes/generated/pulsar_consumer_configuration.html
- docs/layouts/shortcodes/generated/pulsar_source_configuration.html
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/config/PulsarOptions.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/PulsarSourceOptions.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/config/PulsarSourceConfigUtils.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarOrderedPartitionSplitReader.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarUnorderedPartitionSplitReader.java
- flink-docs/pom.xml
- flink-docs/src/main/java/org/apache/flink/docs/configuration/ConfigOptionsDocGenerator.java
Add document for new `flink-connnector-pulsar`.
* Changed exist config option descriptions.
* Add new config option document.
* Add a new connector document.
> [FLINK-23864][docs] Add pulsar connector document

- docs/content.zh/docs/connectors/datastream/pulsar.md
- docs/content/docs/connectors/datastream/pulsar.md
- docs/layouts/shortcodes/generated/pulsar_admin_configuration.html
- docs/layouts/shortcodes/generated/pulsar_client_configuration.html
- docs/layouts/shortcodes/generated/pulsar_consumer_configuration.html
- docs/layouts/shortcodes/generated/pulsar_source_configuration.html
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/config/PulsarOptions.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/PulsarSourceOptions.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/config/PulsarSourceConfigUtils.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarOrderedPartitionSplitReader.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarUnorderedPartitionSplitReader.java
- flink-docs/pom.xml
- flink-docs/src/main/java/org/apache/flink/docs/configuration/ConfigOptionsDocGenerator.java
Unchanged backport of [#17188](https://github.com/apache/flink/pull/17188).
> [FLINK-23864][docs] Add pulsar connector document [1.14]

- docs/content.zh/docs/dev/table/sql/jar.md
Translate "JAR Statements" page of "SQL" into Chinese
https://ci.apache.org/projects/flink/flink-docs-master/docs/dev/table/sql/jar/
docs/content.zh/docs/dev/table/sql/jar.md
> [FLINK-24221][doc]Translate "JAR Statements" page of "SQL" into Chinese

- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcExactlyOnceSinkE2eTest.java
> [BP-1.14][FLINK-22889][tests] Increase timeouts in JdbcExactlyOnceSinkE2eTest

- docs/content.zh/docs/dev/table/sql/load.md
- docs/content/docs/dev/table/sql/load.md
Translate "LOAD Statements" page of "SQL" into Chinese
https://ci.apache.org/projects/flink/flink-docs-master/docs/dev/table/sql/load/
docs/content.zh/docs/dev/table/sql/load.md
> [FLINK-24217][doc]Translate "LOAD Statements" page of "SQL" into Chinese

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/PartitionRequestClientFactory.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/PartitionRequestClientFactoryTest.java
*This PR removes the test because it is too expensive stabilize it while the test itself is not so helpful*
- *Test was removed*
This is the fix of the test
- If yes, how is the feature documented? (not applicable / docs …
> [FLINK-24133][core] Network failure test replaced by comment in the code due to high expense of stabilizing such low important test

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaSinkBuilder.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/KafkaDynamicSink.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaChangelogTableITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableTestBase.java
- flink-end-to-end-tests/flink-confluent-schema-registry/src/main/java/org/apache/flink/schema/registry/test/TestAvroConsumerConfluent.java
Migrate all format tests from FlinkKafkaProducer to KafkaSink
All tests passed locally
> [FLINK-24281][connectors/kafka] Migrate all format tests from FlinkKafkaProducer to KafkaSink

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaSinkBuilder.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/KafkaDynamicSink.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaChangelogTableITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableTestBase.java
- flink-end-to-end-tests/flink-confluent-schema-registry/src/main/java/org/apache/flink/schema/registry/test/TestAvroConsumerConfluent.java
> [BP-1.14][FLINK-24281][connectors/kafka] Migrate all format tests from FlinkKafkaProducer to KafkaSink

- docs/content/docs/dev/datastream/project-configuration.md
[FLINK-24248](https://issues.apache.org/jira/browse/FLINK-24248 )
Add
```
compile "org.apache.flink:flink-clients_${scalaBinaryVersion}:${flinkVersion}"
```
to the Gradle section of the Project Configuration page
- Dependencies (does it add or upgrade a dependency): (yes /  **no**)
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes /  **no**)
- The serializers: (yes /  **no** / don't know)
- The runtime per-record code paths (performance sensitive): (yes /  **no** / don't know)
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes /  **no** / don't know)
- The S3 file system connector: (yes /  **no** / don't …
> [FLINK-24248][docs]update Gradle dependency

- flink-connectors/flink-connector-pulsar/pom.xml
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/topic/TopicRange.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/topic/range/FixedRangeGenerator.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/PulsarTestContext.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/PulsarTestEnvironment.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/PulsarTestSuiteBase.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/cases/MultipleTopicTemplateContext.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/PulsarRuntime.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/PulsarRuntimeOperator.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/container/PulsarContainerRuntime.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/mock/PulsarMockRuntime.java
- flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/flink/FlinkContainerTestEnvironment.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/pom.xml
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/PulsarSourceOrderedE2ECase.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/PulsarSourceUnorderedE2ECase.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/cases/ExclusiveSubscriptionContext.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/cases/FailoverSubscriptionContext.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/cases/KeySharedSubscriptionContext.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/cases/SharedSubscriptionContext.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/common/FlinkContainerWithPulsarEnvironment.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/common/KeyedPulsarPartitionDataWriter.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/common/UnorderedSourceTestSuiteBase.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/resources/log4j2-test.properties
- flink-end-to-end-tests/pom.xml
Unchanged backport of [#17271](https://github.com/apache/flink/pull/17271).
> [FLINK-23969][connector/pulsar] Create e2e tests for pulsar connector. [1.14]

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTask.java
*fix a typo*
*(or)*
*(or)*
*(example:)*
- *Manually verified …
> [Hotfix][streaming] Fix a typo.

- flink-python/tox.ini
*This pull request updates the version of grpcio in tox.ini.*
> [FLINK-24287][python][tests] Update grpcio version in tox.ini

- docs/content/docs/connectors/datastream/kafka.md
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSource.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSourceBuilder.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSourceOptions.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/OffsetsInitializerValidator.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/ReaderHandledOffsetsInitializer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/SpecifiedOffsetsInitializer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReader.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReader.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceBuilderTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReaderTest.java
Unchanged back-port of #17276 on release-1.13
> [BP-1.13][FLINK-24277][connector/kafka] Add configuration for committing offset on checkpoint and disable it if group ID is not specified

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSource.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSourceBuilder.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSourceOptions.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/OffsetsInitializerValidator.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/ReaderHandledOffsetsInitializer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/SpecifiedOffsetsInitializer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReader.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReader.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceBuilderTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReaderTest.java
Unchanged back-port of #17276 on release-1.12
> [BP-1.12][FLINK-24277][connector/kafka] Add configuration for committing offset on checkpoint and disable it if group ID is not specified

- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/FlinkCalciteSqlValidator.java
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/calcite/FlinkPlannerImpl.scala
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/calcite/FlinkCalciteSqlValidatorTest.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/MergeTableLikeUtilTest.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/utils/PlannerMocks.java
Signed-off-by: slinkydeveloper <francescoguard@gmail.com>
Disable UPSERT INTO as discussed here: https://issues.apache.org/jira/browse/FLINK-22942
* Disabled upsert into adding a check in the `FlinkCalciteSqlValidator#validateInsert` override
* Added a test
- Added unit test that execute an `UPSERT INTO` query expecting the proper exception message
- …
> [FLINK-22942] [sql/planner] Disable UPSERT INTO statement

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointFailureManager.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointFailureManagerTest.java
*This PR fixes the situation when the checkpoint exception happens during the checkpoint initialization and doesn't call the CheckpintFailureManager*
- *Calling the CheckpointFailureManager even if the checkpointId is unknown*
*(example:)*
- *Expanded testTriggerCheckpointAfterIOException test* …
> [FLINK-24344][runtime] Calling the CheckpointFailureManager even if the exception happens during the checkpoint initialization

- docs/data/sql_functions.yml
- docs/data/sql_functions_zh.yml
- flink-python/pyflink/table/expression.py
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java
Add document for special char in JSON_VALUE and JSON_QUERY
https://issues.apache.org/jira/browse/FLINK-24271
Add document for special char in JSON_VALUE and JSON_QUERY
document  …
> [FLINK-24271][docs] Add document for special char in JSON_VALUE and JSON_QUERY

- flink-core/src/main/java/org/apache/flink/api/connector/sink/SinkWriter.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/AbstractCommitterHandler.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/BatchCommitterHandler.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterHandler.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/ForwardCommittingHandler.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/NoopCommitterHandler.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/SinkOperator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperatorTest.java
> [FLINK-24371][datastream] Call preCommit on SinkWriter although no committer is available

- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/CheckpointBarrierTrackerTest.java
…an using the constant value
*This PR fixes the test*
- *Calculating maximum alignment time rather than using the constant value*
This is a test
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / …
> [FLINK-24200][streaming] Calculating maximum alignment time rather than using the constant value

- flink-end-to-end-tests/test-scripts/common_ha.sh
- flink-end-to-end-tests/test-scripts/test_ha_datastream.sh
- flink-end-to-end-tests/test-scripts/test_ha_per_job_cluster_datastream.sh
Backport of #17137 to `release-1.14`.
> [BP-1.14][FLINK-21853][e2e] Harden common_ha.sh#ha_tm_watchdog 

- flink-end-to-end-tests/test-scripts/common_ha.sh
- flink-end-to-end-tests/test-scripts/test_ha_datastream.sh
- flink-end-to-end-tests/test-scripts/test_ha_per_job_cluster_datastream.sh
Backport of #17137 to `release-1.13`.
> [BP-1.13][FLINK-21853][e2e] Harden common_ha.sh#ha_tm_watchdog

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/FlinkKafkaInternalProducerITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaSinkITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaTransactionLogITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaUtil.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaWriterITCase.java
> [FLINK-24612][connectors/kafka] Configure Kafka test container log levels accordingly to test logger

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/windowing/triggers/ContinuousEventTimeTrigger.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/windowing/triggers/ContinuousProcessingTimeTrigger.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/windowing/ContinuousProcessingTimeTriggerTest.java
let ContinuousProcessingTimeTrigger fire at the end of the window
https://issues.apache.org/jira/browse/FLINK-20443
let ContinuousProcessingTimeTrigger fire at the end of the window
This time I added a test method for testing ContinuousProcessingTimeTrigger is triggered at the end of the window. …
> [FLINK-20443][API/DataStream] ContinuousProcessingTimeTrigger doesn't fire at the end of the window

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/windowing/triggers/ContinuousEventTimeTrigger.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/windowing/triggers/ContinuousProcessingTimeTrigger.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/windowing/ContinuousProcessingTimeTriggerTest.java
https://github.com/apache/flink/pull/17106#pullrequestreview-793911533
backport to release 1.14
@AHeise
> [FLINK-20443][API/DataStream] ContinuousProcessingTimeTrigger doesn't fire at the end of the window 

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/throughput/BufferDebloater.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateBuilder.java
- flink-runtime/src/test/java/org/apache/flink/runtime/throughput/BufferDebloaterTest.java
*This PR adds debug logs for BufferDebloater*
- *Added log with intermediate parameters for calculation of new buffer size*
No need for logs.
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / …
> [FLINK-24658][runtime] Added debug logs for BufferDebloater

- flink-clients/src/main/java/org/apache/flink/client/deployment/application/ClassPathPackagedProgramRetriever.java
- flink-clients/src/test/java/org/apache/flink/client/deployment/application/ClassPathPackagedProgramRetrieverTest.java
Backport of #14891 to `release-1.13`.
> [BP-1.13][FLINK-21289][deployment] FIX missing load pipeline.classpaths in application mode, for both k8s and yarn

- flink-connectors/flink-connector-nifi/pom.xml
* Update NiFi client to latest version
* Updated POM file to include latest version (currently v1.14.0) …
> [FLINK-24825][nifi] Update nifi-site-to-site-client to v1.14.0

- flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/BufferTimeoutITCase.java
This PR ignores testDisablingBufferTimeout test.
- *Ignored testDisablingBufferTimeout*
It is test
> [hotfix][tests] Ignoring testDisablingBufferTimeout test

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateCheckpointWriter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestExecutorImpl.java
> [BP-1.13][FLINK-24667][runtime] Fix error handling in ChannelStateCheckpointWriter

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateCheckpointWriter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestExecutorImpl.java
> [BP-1.14][FLINK-24667][runtime] Fix error handling in ChannelStateCheckpointWriter

- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceTest.java
This is a backport of #17708 (fixing FLINK-23696) to release-1.14. The fix is exactly the same as in #17708.
Please see #17708 for a detailed description.
> [BP-1.14][FLINK-23696][connectors/rabbitmq] Fix RMQSourceTest.testRedeliveredSessionIDsAck

- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarOrderedPartitionSplitReader.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarPartitionSplitReaderBase.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarUnorderedPartitionSplitReader.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarOrderedPartitionSplitReaderTest.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarPartitionSplitReaderTestBase.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarUnorderedPartitionSplitReaderTest.java
This is a backport of #17643 (fixing FLINK-24733) to release-1.14. The fix is exactly the same as in #17643.
Please see #17643 for a detailed description.
> [BP-1.14][FLINK-24733][connector/pulsar] Data loss in pulsar source when using shared mode

- docs/content.zh/docs/flinkDev/ide_setup.md
- docs/content/docs/flinkDev/ide_setup.md
Add guidance to solve the package sun.misc does not exist
> [FLINK-24755][doc]Add guidance to solve the package sun.misc does not exist

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaCommitter.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaCommitterTest.java
Unhandled exceptions during committing usually imply that data is lost.
We should not only log and continue processing but fail the job to give
the user the choice of what should be done.
- Collect unhandled exceptions of all failed committables and rethrow the suppressed exception after committing is finished
- Added a test to verify the exception is thrown if unhandled …
> [FLINK-24773][kafka] Fail job if unhandled exception occurs during committing

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/metrics/KafkaSourceReaderMetrics.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReaderTest.java
> [FLINK-24409][kafka] Fix collection of KafkaSourceReaderMetrics for topics containing periods

- flink-end-to-end-tests/test-scripts/common_docker.sh
Let the `build_image` in `common_docker.sh` return correct exit code. This will make `retry_times build_image` could work normally.
* [FLINK-24937][e2e] Return correct exit code in build_image
* All the existing tests should pass …
> [FLINK-24937][e2e] Return correct exit code in build_image

- docs/content/docs/deployment/overview.md
- docs/content/docs/deployment/resource-providers/native_kubernetes.md
- docs/content/docs/deployment/resource-providers/standalone/docker.md
- docs/content/docs/deployment/resource-providers/standalone/kubernetes.md
- docs/content/docs/deployment/resource-providers/standalone/overview.md
- docs/content/docs/deployment/resource-providers/yarn.md
https://issues.apache.org/jira/browse/FLINK-24739
> [FLINK-24739] Highlight the fact that the Application Mode excpects user jars to be bundled with the Flink distribution.

- docs/content/docs/deployment/overview.md
- docs/content/docs/deployment/resource-providers/native_kubernetes.md
- docs/content/docs/deployment/resource-providers/standalone/docker.md
- docs/content/docs/deployment/resource-providers/standalone/kubernetes.md
- docs/content/docs/deployment/resource-providers/standalone/overview.md
- docs/content/docs/deployment/resource-providers/yarn.md
BP of https://github.com/apache/flink/pull/17678
> [FLINK-24739][BP-1.13] Highlight the fact that the Application Mode excpects user jars to be bundled with the Flink distribution.

- flink-core/pom.xml
Adds support for various JDK17 stuff & solves IllegalAccess issues.
> [FLINK-24988][build] Upgrade lombok to 1.18.22

- docs/content.zh/docs/dev/table/sql/queries/joins.md
- docs/content/docs/dev/table/sql/queries/joins.md
…nction documentation
correct the example and link for temporal table function documentation.
*(or)*
*(or)*
*(example:)*
- *Added test that …
> [FLINK-24958][docs]correct the example and link for temporal table function documentation

- flink-connectors/flink-connector-elasticsearch7/src/main/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchWriter.java
- flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchWriterITCase.java
This change introduces a methods for test that will block until all records have been acknowledged by Elasticsearch. This fixes test instabilities that were caused by flaky timeout settings.
**Only ab1fe6e89640d5ebc7c2f8329fdfb1ff22694b49 has to be reviewed, the other commits are part of https://github.com/apache/flink/pull/17538**
- *Implement `ElasticsearchWriter#blockingFlushAllActions` method and update tests in `ElasticsearchWriterITCase` to use it instead of timeouts 
This change is already covered by existing tests, such as tests in ElasticsearchWriterITCase. …
> [FLINK-24583] [connectors/elasticsearch] Improve test stability by blocking until ES has acknowledged all records

- flink-examples/flink-examples-table/src/test/java/org/apache/flink/table/examples/java/functions/AdvancedFunctionsExampleITCase.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/casting/RowToStringCastRule.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/casting/CastRulesTest.java
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/CompositeAccessTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/RowTypeTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/SqlExpressionTest.scala
[FLINK-24802](https://issues.apache.org/jira/browse/FLINK-24802) Improve cast ROW to STRING
Add a space after the comma when casting ROW to string.
This change is already covered by existing tests, such as *CastRulesTest.java*.
> [FLINK-24802][Table SQL/Planner] Improve cast ROW to STRING

- docs/content.zh/docs/dev/table/sql/queries/window-agg.md
- docs/content.zh/docs/dev/table/sql/queries/window-join.md
- docs/content.zh/docs/dev/table/sql/queries/window-topn.md
- docs/content.zh/docs/dev/table/sql/queries/window-tvf.md
- docs/content/docs/dev/table/sql/queries/window-agg.md
- docs/content/docs/dev/table/sql/queries/window-join.md
- docs/content/docs/dev/table/sql/queries/window-topn.md
- docs/content/docs/dev/table/sql/queries/window-tvf.md
The pr adds documentation for Window deduplication.
- Window-agg.md
- Window-join.md
- Window-topn.md
- Window-tvf.md
> [FLINK-24760][docs] Update user document for batch window tvf

- flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/CsvFileSystemFormatFactory.java
This pull request removes the duplicated code in `org.apache.flink.formats.csv.CsvFileSystemFormatFactory`.
- Remove duplicated code.
- If yes, how …
> [hotfix][csv] Remove duplicate code.

- flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
This PR just make the output log canonical, so it's a minor improvement.
As the title described, it remove the tail separator when outputting yarn queue names.
Original output log:
```
2021-11-19 16:17:26,678 WARN  org.apache.flink.yarn.YarnClusterDescriptor                  [] - The specified queue 'p4' does not exist. Available queues: p0, p1, p2,
```
After:
```
2021-11-19 16:17:26,678 WARN  org.apache.flink.yarn.YarnClusterDescriptor                  [] - The specified queue 'p4' does not exist. Available queues: "p0, p1, p2"
```
- Remove the tail separator when outputting yarn queue names
- Dependencies (does it add or upgrade a dependency): (__no__) …
> [FLINK-24963] Remove the tail separator when outputting yarn queue names

- .gitignore
*(or)*
*(or)*
*(example:)*
- *Extended …
> [Hotfix][git] Add 'flink-python/.idea/' into .gitignore file.

- .github/PULL_REQUEST_TEMPLATE.md
- flink-connectors/flink-connector-pulsar/pom.xml
- pom.xml
For more details about this PR, check out: https://lists.apache.org/thread/33t7hz8w873p1bc5msppk65792z08rgt
Changes:
* Add assertj in the dependency management
* Add our code quality guide link in the "verifying this change" section of the PR template
> [FLINK-25061][tests] Add assertj in flink-parent and link the code quality guide in the PR template 

- flink-end-to-end-tests/test-scripts/common.sh
- flink-end-to-end-tests/test-scripts/common_ssl.sh
> [FLINK-24971][BP-1.13] Adding retry mechanism in case git clone fails

- flink-end-to-end-tests/test-scripts/common.sh
- flink-end-to-end-tests/test-scripts/common_ssl.sh
Backport of https://github.com/apache/flink/pull/17881
> [FLINK-24971][BP-1.12] Adding retry mechanism in case git clone fails

- flink-end-to-end-tests/test-scripts/common.sh
- flink-end-to-end-tests/test-scripts/common_ssl.sh
> [FLINK-24971][BP-1.14] Adding retry mechanism in case git clone fails

- flink-connectors/flink-connector-cassandra/src/test/java/org/apache/flink/streaming/connectors/cassandra/CassandraConnectorITCase.java
This PR lowers consistency expectancy from ONE to ANY in write operations to avoid waiting for a replica write acknowledge in ITest. This consistency level is only available on write, so we need to create one builder for reading and one for writing. Some sinks are used for both reading and writing (in committer tests, and in base class tests), in that case, reading builder (with consistency set to ONE) is used.
This should remove the timeout flakiness error. As said in the ticket, we need to monitor the ITest for some weeks to acknowledge that there is no more write timeouts.
Hi @zentol, I saw your name in the commit history, can you please take a look?
> [FLINK-22775][connectors][cassandra][test] Lower consistency expectation in write operations to avoid waiting for replica acknowledge

- docs/content/docs/dev/datastream/fault-tolerance/serialization/schema_evolution.md
* The section was titled `Schema Migration Limiations`
* Corrected section title
> [hotfix][datastream][docs]

- docs/content.zh/docs/dev/datastream/fault-tolerance/state.md
- docs/content/docs/dev/datastream/fault-tolerance/state.md
> [FLINK-24310][doc]Use >= instead of == to cover the downscaling scenario

- docs/content.zh/docs/connectors/table/jdbc.md
- docs/content/docs/connectors/table/jdbc.md
The pr updates documentation for `lookup.cache.caching-missing-key` config in jdbc connector 
- *jdbc.md*
> [FLINK-25065][docs] Update  document for jdbc connector

- flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/streaming/connectors/cassandra/CassandraSink.java
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/KeyExtractor.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/JdbcOutputFormat.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/KafkaDynamicSink.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/ReducingUpsertSink.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/SinkBufferFlushMode.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/ReducingUpsertWriterTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/UpsertKafkaTableITCase.java
- flink-core/src/main/java/org/apache/flink/util/function/SerializableFunction.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/TestingOperatorCoordinator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/DataStream.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/DataStreamSink.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/KeyedStream.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectStreamSink.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/transformations/LegacySinkTransformation.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/translators/LegacySinkTransformationTranslator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/datastream/DataStreamSinkTest.java
- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/connector/datagen/table/types/DataGeneratorMapper.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecLegacySink.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecLegacySink.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecLegacySink.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecSinkITCase.java
> [FLINK-24596][kafka] Fix buffered KafkaUpsert sink

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaProducerITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestBase.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/RetryOnException.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/RetryOnFailure.java
All tests based on our legacy Kafka infrastructure fail quite frequently due to various connectivity issues when communicating with the brokers. All our future tests for the unified sources and sinks are based on dockerized tests where we do not see any of the issues. So to ease the maintenance/deprecation of the old tests we add a retry rule for all tests based on the KafkaTestBase class.
- Add retry rule to `KafkaTestBase`
- Tests still pass …
> [FLINK-15493][test] Add retry rule for all tests based on KafkaTestBase

- flink-end-to-end-tests/test-scripts/elasticsearch-common.sh
(cherry picked from commit 5eeef8371ed0e726f737547bfd888d0d66cb3ab5)
Backport of https://github.com/apache/flink/pull/17941
> [FLINK-25092][BP-1.14][tests][elasticsearch] Refactor test to use artifact cacher

- flink-end-to-end-tests/test-scripts/elasticsearch-common.sh
(cherry picked from commit 5eeef8371ed0e726f737547bfd888d0d66cb3ab5)
Backport of https://github.com/apache/flink/pull/17941
> [FLINK-25092][BP-1.13][tests][elasticsearch] Refactor test to use artifact cacher

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/ExecutionAttemptMappingProvider.java
Backport of https://github.com/apache/flink/pull/17946
> [FLINK-24919][runtime] Getting vertex only under synchronization

- pom.xml
Dependency update for japicmp-maven-plugin as build with jdk17 fails with
```
java.security.PrivilegedActionException: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:573)
at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.<clinit>(Injector.java:197)
at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:81)
at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:125)
at com.sun.xml.bind.v2.runtime.reflect.Accessor$GetterSetterReflection.optimize(Accessor.java:402)
at com.sun.xml.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransdu …
```
> [FLINK-25161][buildsystem] update jaxb-impl dependency for japicmp-maven-plugin

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/CheckpointConfig.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/environment/CheckpointConfigFromConfigurationTest.java
Backport for PR #17972 excluding the assertj changes.
> [BP-1.13][FLINK-24506][config] Adds checkpoint directory to CheckpointConfig

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/CheckpointConfig.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/environment/CheckpointConfigFromConfigurationTest.java
Backport for PR #17972 excluding the assertj changes.
> [BP-1.14][FLINK-24506][config] Adds checkpoint directory to CheckpointConfig

- docs/content.zh/docs/connectors/datastream/file_sink.md
- docs/content/docs/connectors/datastream/file_sink.md
Backport of https://github.com/apache/flink/pull/17950
> [FLINK-25091][BP-1.14] Change ORC compression attribute reference error in FileSink docs

- docs/content.zh/docs/connectors/datastream/file_sink.md
- docs/content/docs/connectors/datastream/file_sink.md
> [FLINK-25091][BP-1.13] Change ORC compression attribute reference error in FileSink docs

- docs/dev/connectors/file_sink.md
- docs/dev/connectors/file_sink.zh.md
> [FLINK-25091][BP-1.12] Change ORC compression attribute reference error in FileSink docs 

- docs/content/docs/connectors/table/jdbc.md
* Updated text in key handling section
* Corrected text
> [hotfix][jdbc][docs] - Updated key handling section text

- docs/content.zh/docs/connectors/table/elasticsearch.md
- docs/content/docs/connectors/table/elasticsearch.md
Trivial change adding a missing semicolon to make a query valid
> [hotfix][docs][connectors] Add missing semicolon to make the query valid

- flink-core/src/main/java/org/apache/flink/core/fs/ClosingFSDataOutputStream.java
Make variable naming appropriate
Make variable naming appropriate
yes
> [FLINK-25153] Inappropriate variable naming

- docs/layouts/shortcodes/generated/execution_checkpointing_configuration.html
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/CoordinatedSourceRescaleITCase.java
- flink-end-to-end-tests/flink-datastream-allround-test/src/main/java/org/apache/flink/streaming/tests/DataStreamAllroundTestJobFactory.java
- flink-end-to-end-tests/flink-local-recovery-and-allocation-test/src/main/java/org/apache/flink/streaming/tests/StickyAllocationAndLocalRecoveryTestJob.java
- flink-python/pyflink/datastream/checkpoint_config.py
- flink-python/pyflink/datastream/tests/test_check_point_config.py
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/CheckpointConfig.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/ExecutionCheckpointingOptions.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/environment/CheckpointConfigFromConfigurationTest.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/RegionFailoverITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/ResumeCheckpointManuallyITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointCompatibilityITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java
BP of https://github.com/apache/flink/pull/17893
The documentation changes using DescribedEnum were skipped because it does not exist in 1.13
> [FLINK-24987][BP 1.13] Enhance ExternalizedCheckpointCleanup

- flink-connectors/flink-connector-cassandra/src/test/java/org/apache/flink/streaming/connectors/cassandra/CassandraConnectorITCase.java
This PR is the backport to release 1.13 of [this PR](https://github.com/apache/flink/pull/17849)
R: @zentol
> [FLINK-22775][cassandra][tests] Lower write consistency level to ANY backport to 1.13

- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperatorTest.java
This PR fixes the import of guava in AsyncWaitOperatorTest
> [FLINK-24846][streaming] Guava import fix in AsyncWaitOperatorTest

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaUtil.java
> [FLINK-25326][connectors/kafka] Fix application of log levels in KafkaUtils.createKafkacontainer (backport)

- flink-connectors/flink-connector-jdbc/pom.xml
Current `flink-connector-jdbc-tests.jar` does not contain class files.  This PR enables a proper tests jar build, similar to `files-connector-files-tests.jar`.
A trivial change to `pom.xml`.
- Dependencies (does it add or upgrade a dependency):  no 
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`:  no 
- The serializer:  no
> [FLINK-23375][connector/jdbc] Build proper JDBC test jar.

- pom.xml
`Stabilize the builds until the issue is resolved`
cc: @pnowojski , @curcur
> [FLINK-25399][tests] Disable changelog backend in tests

- flink-clients/src/test/java/org/apache/flink/client/deployment/application/ApplicationDispatcherBootstrapITCase.java
- flink-clients/src/test/java/org/apache/flink/client/testjar/BlockingJob.java
https://issues.apache.org/jira/browse/FLINK-25271
Fixes a flaky test.
> [FLINK-25271][clients] Harden the ApplicationDispatcherBootstrapITCase.

- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/StateChangeFsUploader.java
Current uploader implementation would close stream and fsStream one by one, which lead to fsStream closed twice. However, not all file systems support to close same output stream twice.
Modify `StateChangeFsUploader.java`.
> [FLINK-25429][state] Avoid to close output streams twice during uploading changelogs

- docs/content.zh/docs/dev/table/sql/queries/window-tvf.md
- docs/content/docs/dev/table/sql/queries/window-tvf.md
The pr updates documentation for individual window table-value function
- Window-tvf.md
> [FLINK-24772][docs] Update documentation for individual window table-value function

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGate.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/TimerGauge.java
- flink-runtime/src/main/java/org/apache/flink/runtime/throughput/ThroughputCalculator.java
- flink-runtime/src/test/java/org/apache/flink/runtime/throughput/ThroughputCalculatorTest.java
This PR fixes the invocation of throughput calculator methods from different threads.
- *Calling ThroughputCalculator#resumeMeasurement from mailbox thread only*
No new tests since only refactoring were done.
- If yes, …
> [FLINK-25454][runtime] Pause and resume time for throughput calculator only from one thread. 

- docs/content.zh/docs/dev/table/data_stream_api.md
- docs/content/docs/dev/table/data_stream_api.md
[hotfix][docs] Fix typo in name for data_stream_api.md
> [hotfix][docs] Fix typo in name for data_stream_api.md

- flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/ddl/SqlCreateTable.java
Fix typo in org.apache.flink.sql.parser.ddl.SqlCreateTable
- Fix typo in org.apache.flink.sql.parser.ddl.SqlCreateTable
> [hotfix] [javadocs] Fix typo in org.apache.flink.sql.parser.ddl.SqlCreateTable

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReader.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReaderTest.java
KafkaPartitionSplitReaderTest is missing the test case when startingOffset is COMMITTED_OFFSET.
Add using committed offsets test cases for KafkaPartitionSplitReader
- If yes, how is the feature documented? (not applicable …
> [FLINK-25510][Connectors / Kafka][tests] Add using committed offsets test cases for KafkaPartitionSplitReader

- flink-connectors/flink-connector-jdbc/pom.xml
Backport of https://github.com/apache/flink/pull/18301
> [FLINK-25576][BP 1.13][Connectors][JDBC] Upgrade com.h2database:h2 to 2.0.206

- flink-connectors/flink-connector-jdbc/pom.xml
Backport of https://github.com/apache/flink/pull/18301
> [FLINK-25576][BP 1.14][Connectors][JDBC] Upgrade com.h2database:h2 to 2.0.206

- flink-connectors/flink-connector-hive/src/main/resources/META-INF/NOTICE
- flink-formats/flink-sql-parquet/src/main/resources/META-INF/NOTICE
- flink-formats/pom.xml
*(or)*
*(or)*
*(example:)*
- *Extended …
> [FLINK-22602][Formats][Parquet] Upgrade Parquet dependency to 1.12.2

- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/PulsarSourceBuilder.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/cursor/start/MessageIdStartCursor.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/reader/source/PulsarOrderedSourceReader.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/reader/source/PulsarUnorderedSourceReader.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/PulsarSourceBuilderTest.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/enumerator/PulsarSourceEnumeratorTest.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/source/PulsarOrderedSourceReaderTest.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/source/PulsarSourceReaderTestBase.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/source/PulsarUnorderedSourceReaderTest.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarOrderedPartitionSplitReaderTest.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarPartitionSplitReaderTestBase.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/PulsarTestCommonUtils.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/extension/SubType.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/extension/TestOrderlinessExtension.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/PulsarRuntimeOperator.java
Enhance the pulsar source unit test for the following classes
- PulsarSourceReader
- PulsarPartitionSplitReader
- PulsarSourceEnumerator
- PulsarSourceBuilder
One bug fix with this test enhancement:
1. [BUG FIX] Fix overflow when stopCursor is latest and use exclusive start cursor .
2. Added tests for Ordered and Unordered version of PulsarSourceReader and PulsarPartitionSplitReader
3. Improved tests for PulsarSourceEnumerator and PulsarSourceBuilder
Local Test failed due to a test failure not related to this change, see if that can pass in the CI. …
> [FLINK-25044][testing][Pulsar Connector] Add More Unit Test For Pulsar Source

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/CommittableMessage.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/CommittableMessageSerializer.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/CommittableMessageTypeInfo.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/CommittableSummary.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/CommittableWithLineage.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/WithPostCommitTopology.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/WithPreCommitTopology.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/WithPreWriteTopology.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/connector/sink2/CommittableMessageSerializerTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/connector/sink2/CommittableMessageTypeInfoTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/connector/sink2/IntegerSerializer.java
- flink-tests/src/test/java/org/apache/flink/test/completeness/TypeSerializerTestCoverageTest.java
This PR marks the second part of API changes of FLIP-191 https://issues.apache.org/jira/browse/FLINK-25555 introducing the interfaces used to execute arbitrary topologies before and after the sink writer and committer.
- Introduce mixin interfaces to construct a topology sink
- Add committable message classes to clarify the exchange
Primarily the PR consists of API changes
- Added a test to verify the serialization of the committable messages …
> [FLINK-25570][streaming] Add topology extension points to Sink V2

- docs/content.zh/docs/connectors/datastream/elasticsearch.md
- docs/content.zh/docs/connectors/table/elasticsearch.md
- docs/content/docs/connectors/datastream/elasticsearch.md
Update Chinese version document of Elasticsearch sink interface related to [FLINK-24326](https://issues.apache.org/jira/browse/FLINK-24326) (#17930)
- Translate `docs/content.zh/docs/connectors/datastream/elasticsearch.md`
- Translate `docs/content.zh/docs/connectors/table/elasticsearch.md`
- Trivial fix of `docs/content/docs/connectors/datastream/elasticsearch.md`
This is a document update.
Please build docs locally to verify document content and syntax.
```
cd docs
./build_docs.sh -p
```
Then you can preview `http://localhost:1313` in the local browser.
- …
> [FLINK-25589][docs][connectors] Update Chinese version of Elasticsearch connector docs

- flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorProvider.java
These guards do not work properly and hide the actual failure causes.
> [FLINK-25611][core] Remove CoordinatorExecutorThreadFactory thread creation guards

- flink-connectors/flink-connector-cassandra/pom.xml
- flink-connectors/flink-connector-kafka/pom.xml
- flink-connectors/flink-connector-pulsar/pom.xml
- flink-python/pom.xml
- pom.xml
Backport of #18343 to `release-1.14`.
> [BP-1.14][FLINK-25633] Set locale to en-US to avoid ambiguous decimal formattings

- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/PulsarTestContext.java
- flink-test-utils-parent/flink-connector-testing/src/main/java/org/apache/flink/connectors/test/common/utils/TestDataMatchers.java
1. change the pulsar IT to generate fixed test data
2. change the TestDataMatcher to validate both size and data.
1. change the pulsar IT to generate fixed test data
2. change the TestDataMatcher to validate both size and data.
- others : No
- No doc is needed
> [FLINK-23944][test][pulsar] 1. change the Matcher to validate both size and data 2. pulsar IT test generate deterministic data

- flink-runtime/src/main/java/org/apache/flink/runtime/state/TaskExecutorStateChangelogStoragesManager.java
The method is called from the shutdown hook and must be thread-safe.
The change is relateively simple and related to concurrency so covering it doesn't seem worth the effort.
> [FLINK-25678][runtime] Make TaskExecutorStateChangelogStoragesManager.shutdown thread-safe

- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/reader/fetcher/PulsarFetcherManagerBase.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/reader/source/PulsarSourceReaderBase.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/source/SourceOperatorEventTimeTest.java
Those are two small hotfixes authored by @AHeise extracted from his PoC of FLIP-182 https://github.com/AHeise/flink/pull/2, in order to do a code review and run azure.
> [hotfix][source][pulsar] Two small hotfix commits from FLIP-182 PoC branch

- flink-runtime/src/main/java/org/apache/flink/runtime/state/TaskExecutorStateChangelogStoragesManager.java
> [BP-1.14]FLINK-25678][runtime] Make TaskExecutorStateChangelogStoragesManager.shutdown thread-safe

- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
Fixes an issue where the collection passed to the `MultipleJobsDetails` constructor is not serializable.
> [FLINK-25732][coordination] Pass serializable collection

- flink-dist/pom.xml
Include Changelog jars into dist/opt.
> [FLINK-25739][dist] Include Changelog to flink-dist jar

- flink-connectors/flink-connector-aws-kinesis-data-streams/src/main/java/org/apache/flink/connector/kinesis/sink/KinesisDataStreamsSinkWriter.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriter.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/ArrayListAsyncSink.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterTest.java
Changing `submitRequests`  in `AsyncSinkWriter` to accept `List` instead of a `Collection`
- Changed `submitRequests`  in `AsyncSinkWriter` to accept `List` instead of a `Collection`.
- Changed Implementations in tests and `KinesisDataStreams` to meet the change.
- The S3 file system connector: don't know
- If yes, …
> [FLINK-25811][hotfix][connector/base] changing failed requests handler to accept  List in AsyncSinkWriter

- flink-dist/pom.xml
- flink-dist/src/main/assemblies/bin.xml
- flink-dist/src/main/assemblies/opt.xml
- pom.xml
Zookeeper/Netty/ASM were pinned to 14.0 as they require code changes, which will be done in follow-up PRs.
> [FLINK-25773][build] Upgrade to flink-shaded 15.0

- docs/static/generated/rest_v1_dispatcher.yml
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/checkpoints/CheckpointStatistics.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/checkpoints/SubtaskCheckpointStatistics.java
using '@class' causes swagger to generate a client that cannot be compiled
This is technically a breaking change, but since this field is not documented it should be fine.
> [FLINK-25808][rest][docs] JsonTypeInfo property uses valid java identier

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableTestBase.java
This pull request fix the test `KafkaTableITCase.testStartFromGroupOffsetsLatest`.
- Add some sleep time before adding new data, make sure the reading latest offsets operation happen before it
> [FLINK-25753][tests] Fix KafkaTableITCase.testStartFromGroupOffsetsLatest

- flink-core/pom.xml
- flink-core/src/main/java/org/apache/flink/api/java/ClosureCleaner.java
- flink-core/src/main/java/org/apache/flink/api/java/typeutils/TypeExtractionUtils.java
- flink-core/src/test/java/org/apache/flink/api/common/typeutils/ClassRelocator.java
- flink-scala/pom.xml
- flink-scala/src/main/scala/org/apache/flink/api/scala/ClosureCleaner.scala
- flink-table/flink-table-common/pom.xml
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/ExtractionUtils.java
- pom.xml
> [FLINK-24978][build] Upgrade ASM to 9.2 

- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/MiniDispatcher.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/JobDispatcherITCase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/MiniDispatcherTest.java
Backport of #18296 onto `release-1.14`.
> [BP-1.14][FLINK-25486][Runtime/Coordination] Fix the bug that flink will lost state when zookeeper leader changes

- docs/_layouts/base.html
> [FLINK-25880][BP 1.0][Docs] Implement Matomo in Flink documentation

- docs/_layouts/base.html
> [FLINK-25880][BP 1.1][Docs] Implement Matomo in Flink documentation

- docs/_layouts/base.html
> [FLINK-25880][BP 1.2][Docs] Implement Matomo in Flink documentation

- docs/_layouts/base.html
> [FLINK-25880][BP 1.3][Docs] Implement Matomo in Flink documentation

- docs/_layouts/base.html
> [FLINK-25880][BP 1.4][Docs] Implement Matomo in Flink documentation

- docs/_layouts/base.html
> [FLINK-25880][BP 1.5][Docs] Implement Matomo in Flink documentation

- docs/_layouts/base.html
> [FLINK-25880][BP 1.6][Docs] Implement Matomo in Flink documentation

- docs/_layouts/base.html
> [FLINK-25880][BP 1.8][Docs] Implement Matomo in Flink documentation

- docs/_layouts/base.html
> [FLINK-25880][BP 1.7][Docs] Implement Matomo in Flink documentation

- docs/_layouts/base.html
> [FLINK-25880][BP 1.9][Docs] Implement Matomo in Flink documentation

- docs/_layouts/base.html
> [FLINK-25880][BP 1.10][Docs] Implement Matomo in Flink documentation

- docs/_layouts/base.html
Initial backport of #18577, using the unchanged backport of https://github.com/apache/flink/pull/18585
> [FLINK-25880][BP 1.11][Docs] Implement Matomo in Flink documentation

- docs/layouts/_default/baseof.html
Unchanged backport of https://github.com/apache/flink/pull/18577
> [FLINK-25880][BP 1.14][Docs] Implement Matomo in Flink documentation

- docs/layouts/_default/baseof.html
> [FLINK-25880][BP 1.13][Docs] Implement Matomo in Flink documentation

- flink-clients/src/main/java/org/apache/flink/client/program/rest/RestClusterClient.java
- flink-clients/src/test/java/org/apache/flink/client/program/rest/RestClusterClientTest.java
Fix the problem that RestClusterClient gets stuck on submitting job with local user artifact.
- Change how Path is constructed to support local file path with scheme.
- Added test that validates that local file path with scheme is supported.
> [FLINK-25685][rest] RestClusterClient supports uploading local file path with scheme

- flink-connectors/flink-connector-aws-kinesis-firehose/src/main/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkBuilder.java
- flink-connectors/flink-connector-aws-kinesis-firehose/src/test/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkBuilderTest.java
KinesiFirehoseSinkBuilder inserts wrong http protocol format.
- change default protocol inserted to be String as required by sdk client.
- *Added unit tests for assertion of correct protocol added*
- Dependencies (does it add or upgrade a dependency): (yes / no) n
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no) n
- The serializers: (yes / no / don't know) n
- The runtime per-record code paths (performance sensitive): (yes / no / don't know) n
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know) n
- The S3 file system connector: (yes / no / don't know)n
- 
- Does this pull request introduce a new feature? (yes / no) n …
> [FLINK-25949][connector/firehose] Fixing wrong Http protocol default value for kinesisfirehoseSinkBuilder

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/GlobalCommitterOperator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/StandardSinkTopologies.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/transformations/SinkTransformation.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/transformations/SinkV1Adapter.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/translators/SinkTransformationTranslator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/connector/sink2/GlobalCommitterOperatorTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SinkTransformationTranslatorTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/transformations/SinkV1AdapterTest.java
- flink-table/flink-table-common/src/test/java/org/apache/flink/table/connector/sink/TestManagedSink.java
- flink-table/flink-table-common/src/test/java/org/apache/flink/table/connector/sink/TestManagedSinkCommitter.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/batch/sql/CompactManagedTableITCase.java
- flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/SinkITCase.java
This PR implements the previous GlobalCommitter as a Sink V2 post-commit topology. 
- Implement custom operator for the GlobalCommitter and expose it through the `StandardSinkTopologies`
- Enabled/Added tests for the SinkTranslation to ensure the GlobalCommitter is part of the pipeline after the translation
- Added tests for the operator to handle the committing …
> [FLINK-25726][streaming] Add Global Committer as post commit topology

- docs/layouts/partials/docs/inject/menu-after.html
- docs/static/js/track-search-terms.js
Unchanged backport of https://github.com/apache/flink/pull/18581
> [FLINK-25879][BP 1.14][Docs] Track used search terms in Matomo

- docs/layouts/partials/docs/inject/menu-after.html
- docs/static/js/track-search-terms.js
Unchanged backport of https://github.com/apache/flink/pull/18581
> [FLINK-25879][BP 1.13][Docs] Track used search terms in Matomo

- flink-end-to-end-tests/run-nightly-tests.sh
- flink-end-to-end-tests/test-scripts/common.sh
- flink-end-to-end-tests/test-scripts/common_artifact_download_cacher.sh
- flink-end-to-end-tests/test-scripts/common_s3.sh
- flink-end-to-end-tests/test-scripts/elasticsearch-common.sh
- flink-end-to-end-tests/test-scripts/kafka-common.sh
- flink-end-to-end-tests/test-scripts/test_azure_fs.sh
- flink-end-to-end-tests/test-scripts/test_resume_externalized_checkpoints.sh
- tools/ci/test_controller.sh
- tools/releasing/create_binary_release.sh
- tools/releasing/create_release_branch.sh
- tools/releasing/create_snapshot_branch.sh
- tools/releasing/create_source_release.sh
- tools/releasing/update_branch_version.sh
- tools/releasing/update_japicmp_configuration.sh
> [FLINK-25041][BP 1.13][e2e] Improve error handling for missing environment variables in E2E tests

- docs/content.zh/docs/dev/datastream/operators/joining.md
- docs/content/docs/dev/datastream/operators/joining.md
Improve document quality
Fix the java example in interval-join: make it correct and consistent with scala.
> [hotfix][docs] Fix the java example of `Interval Join`

- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/FileSystemConnectorOptions.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/FileSystemTableFactory.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/FileSystemTableSink.java
- flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/sink/writer/FileWriterBucketTest.java
- flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/table/stream/StreamingFileWriterTest.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveTableSink.java
Change-Id: Ica8ba43307476198c4f525ac40a54ab862b58ea7
Support inactivityInterval config in table api
- *Add SINK_ROLLING_POLICY_INACTIVITY_INTERVAL table config*
- *Support file inactive check when rolling which has been already supported in datastream api*
> [FLINK-25484][connectors/filesystem] Support inactivityInterval config in table api

- flink-connectors/flink-connector-aws-kinesis-data-streams/src/main/java/org/apache/flink/connector/kinesis/sink/KinesisDataStreamsSink.java
- flink-connectors/flink-connector-aws-kinesis-data-streams/src/main/java/org/apache/flink/connector/kinesis/sink/KinesisDataStreamsSinkElementConverter.java
- flink-connectors/flink-connector-aws-kinesis-data-streams/src/main/java/org/apache/flink/connector/kinesis/sink/KinesisDataStreamsSinkWriter.java
- flink-connectors/flink-connector-aws-kinesis-data-streams/src/main/java/org/apache/flink/connector/kinesis/table/KinesisDynamicSink.java
- flink-connectors/flink-connector-aws-kinesis-data-streams/src/test/java/org/apache/flink/connector/kinesis/table/KinesisDynamicTableSinkFactoryTest.java
- flink-connectors/flink-connector-aws-kinesis-firehose/src/main/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSink.java
- flink-connectors/flink-connector-aws-kinesis-firehose/src/main/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkElementConverter.java
- flink-connectors/flink-connector-aws-kinesis-firehose/src/main/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkWriter.java
- flink-connectors/flink-connector-aws-kinesis-firehose/src/main/java/org/apache/flink/connector/firehose/table/KinesisFirehoseDynamicSink.java
- flink-connectors/flink-connector-aws-kinesis-firehose/src/test/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkWriterTest.java
- flink-connectors/flink-connector-aws-kinesis-firehose/src/test/java/org/apache/flink/connector/firehose/table/KinesisFirehoseDynamicTableFactoryTest.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/AsyncSinkBase.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriter.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/ElementConverter.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/ArrayListAsyncSink.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/TestSinkInitContext.java
This PR migrates the connectors based on the AsyncSink to the new decompose Sink interfaces. 
- Migrate AsyncSink to StateFulSink and remove all unnecessary methods.
- All existing tests still pass and no new feature is added …
> [FLINK-25574][connectors/async] Migrate AsyncSink connectors to decomposed SinkV2

- docs/content.zh/docs/connectors/datastream/formats/avro.md
- docs/content.zh/docs/connectors/datastream/formats/azure_table_storage.md
- docs/content.zh/docs/connectors/datastream/formats/hadoop.md
- docs/content.zh/docs/connectors/datastream/formats/mongodb.md
- docs/content.zh/docs/connectors/datastream/formats/parquet.md
- docs/content.zh/docs/connectors/datastream/formats/text_files.md
- docs/content.zh/docs/connectors/table/downloads.md
- docs/content.zh/docs/connectors/table/filesystem.md
- docs/content.zh/docs/connectors/table/formats/overview.md
- docs/content.zh/docs/deployment/filesystems/gcs.md
- docs/content.zh/docs/dev/datastream/execution/execution_configuration.md
- docs/content.zh/docs/dev/python/environment_variables.md
- docs/content.zh/docs/dev/python/python_config.md
- docs/content.zh/docs/dev/table/sourcesSinks.md
- docs/content.zh/docs/dev/table/sql/describe.md
- docs/content.zh/docs/dev/table/sql/explain.md
- docs/content.zh/docs/dev/table/sql/jar.md
- docs/content.zh/docs/dev/table/sql/queries/joins.md
- docs/content.zh/docs/dev/table/sql/queries/overview.md
- docs/content.zh/docs/dev/table/sql/reset.md
- docs/content.zh/docs/dev/table/sql/set.md
- docs/content.zh/docs/ops/batch/blocking_shuffle.md
- docs/content.zh/docs/ops/state/checkpointing_under_backpressure.md
- docs/content.zh/docs/ops/state/task_failure_recovery.md
Fix various redirects in the chinese docs, such that we only redirect if the users accessed a chinese url.
> [FLINK-26187][docs] Chinese docs only redirect for chinese urls

- pom.xml
https://junit.org/junit5/docs/current/user-guide/#extensions-registration-automatic
> [FLINK-26218] Enable JUnit 5 Automatic Extension Detection

- flink-metrics/flink-metrics-statsd/src/test/java/org/apache/flink/metrics/statsd/StatsDReporterFactoryTest.java
- flink-metrics/flink-metrics-statsd/src/test/java/org/apache/flink/metrics/statsd/StatsDReporterTest.java
- flink-metrics/flink-metrics-statsd/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Based on https://github.com/apache/flink/pull/18817.
> [FLINK-26215][statsd] Migrate tests to JUnit5 

- flink-metrics/flink-metrics-slf4j/src/test/java/org/apache/flink/metrics/slf4j/Slf4jReporterTest.java
- flink-metrics/flink-metrics-slf4j/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Based on https://github.com/apache/flink/pull/18817.
> [FLINK-26219][slf4j] Migrate tests to JUnit5 

- flink-end-to-end-tests/test-scripts/common.sh
- flink-end-to-end-tests/test-scripts/common_ha.sh
- flink-end-to-end-tests/test-scripts/queryable_state_base.sh
- flink-end-to-end-tests/test-scripts/test_cli.sh
- flink-end-to-end-tests/test-scripts/test_pyflink.sh
- flink-end-to-end-tests/test-scripts/test_rocksdb_state_memory_control.sh
- tools/ci/controller_utils.sh
- tools/ci/maven-utils.sh
1.14 backport of PR #18806 by just cherry-picking the changes:
```
git cherry-pick 92faffa858c1fdd469eaf6c52d4fa14d90d4d09d a88a666ad794a66b8007cec3c34a34a3d1cb866f
```
> [BP-1.14][FLINK-26105][e2e] Fixes log file extension

- flink-end-to-end-tests/test-scripts/common.sh
- flink-end-to-end-tests/test-scripts/common_ha.sh
- flink-end-to-end-tests/test-scripts/queryable_state_base.sh
- flink-end-to-end-tests/test-scripts/test_cli.sh
- flink-end-to-end-tests/test-scripts/test_pyflink.sh
- flink-end-to-end-tests/test-scripts/test_rocksdb_state_memory_control.sh
- tools/ci/controller_utils.sh
- tools/ci/maven-utils.sh
1.13 backport of PR #18806 by just cherry-picking the changes:
```
git cherry-pick 92faffa858c1fdd469eaf6c52d4fa14d90d4d09d a88a666ad794a66b8007cec3c34a34a3d1cb866f
```
> [BP-1.13][FLINK-26105][e2e] Fixes log file extension

- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/embedded/PulsarEmbeddedRuntime.java
Fixes an issue where we inexplicably setup the PulsarService to call Runtime#halt in some cases.
> [FLINK-26192][pulsar] Remove call to Runtime#halt

- docs/content.zh/docs/connectors/datastream/pulsar.md
Fix issue-[FLINK-24407](https://issues.apache.org/jira/browse/FLINK-24407).
Pulsar connector chinese document has two links to Pulsar document location incorrectly.
- just modify pulsar connector chinese document.
> [FLINK-24407][doc-zh]Pulsar connector chinese document link to Pulsar document location incorrectly.

- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/JobDispatcherITCase.java
*Fix the unstable test JobDispatcherITCase which may return unexpected initial checkpoint stats in race condition.*
- *Wait until the latest restored checkpoint is not null.*
- *Override the method notifyCheckpointAbortAsync to avoid the job's failure by accident. *
> [FLINK-25992][Runtime/Coordination, Tests]  For stability, wait until the latest restored checkpoint is not null to avoid race condition

- flink-connectors/flink-connector-aws-base/src/main/java/org/apache/flink/connector/aws/util/AWSGeneralUtil.java
- flink-connectors/flink-connector-aws-base/src/test/java/org/apache/flink/connector/aws/testutils/AWSServicesTestUtils.java
- flink-connectors/flink-connector-aws-kinesis-data-streams/src/test/java/org/apache/flink/connectors/kinesis/testutils/KinesaliteContainer.java
- flink-connectors/flink-connector-aws-kinesis-firehose/src/test/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkITCase.java
Introduces own event loop group whenever we create an http client for the aws sdk clients in integration tests. The issue was found https://github.com/apache/flink/pull/18553#issuecomment-1035369952.
Also reverts the Ignoring of the Firehose https://github.com/apache/flink/pull/18712.
ntroduces new event loop group on creation of http client in `KinesisFirehoseITCase`.
This change is already covered by existing tests, `KinesisFirehoseITCase`. …
> [FLINK-26064][connector/firehose][connector/kinesis] Using separate event loop group for firehose IT test.

- docs/content.zh/docs/dev/table/sql/queries/with.md
> [FLINK-26152] [docs] Translate the page of SQL/queries/WITH clause

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/AbstractStreamingCommitterHandler.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/StreamingCommitterHandlerTest.java
With the introduction of retries of failed committables we should not
simply forward all committables but check their status. Only
committables that have been committed successfully should be forwarded.
Remove failed committables from the committables that are forwarded.
- Adjusted the retry test to ensure that no committables are forwarded in a failure case. …
> [FLINK-26304][streaming] Do not forward failed committables

- docs/content.zh/docs/connectors/datastream/pubsub.md
- docs/content/docs/connectors/datastream/pulsar.md
- Added descriptions on a user asked question.
This is a doc only change
Doc only change
Doc only change
> [FLINK-26159][doc] add description for MAX_FETCH_RECORD related question

- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/PulsarSourceBuilder.java
Modify the documentation of Bounded StopCursor
This is a doc only change
Doc only change
- doc only change
> [FLINK-26160][pulsar][doc] update the doc of setUnboundedStopCursor()

- .github/PULL_REQUEST_TEMPLATE.md
> [hotfix][typos] Typos in PULL_REQUEST_TEMPLATE.md

- docs/content.zh/docs/dev/table/sqlClient.md
- docs/content/docs/dev/table/sqlClient.md
* SQL Client document improvements 
* Updated doc.
- If yes, how is the feature documented? (not applicable
> [hotfix][sqlclient][docs] Improved sql client docs

- flink-runtime/src/main/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStore.java
- flink-runtime/src/test/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStoreTest.java
This serves as a 1.14 backport for PR #18919 
The cherry-pick only caused some minor import conflict due to the upgrade from curator4 to curator5
See the parent PR's description for further details
> [BP-1.14][FLINK-26285] Fixes an inconsistency

- docs/content/docs/connectors/datastream/filesystem.md
Looks like you left something unchanged in the docs. I updated it for you. …
> [hotfix] [docs] Typo in filesystem.md

- docs/content.zh/docs/connectors/datastream/elasticsearch.md
- docs/content/docs/connectors/datastream/elasticsearch.md
Fix typo in java code demo of ES stream connector page for release-1.14
Fix typo in java code demo of ES stream connector page for release-1.14
- …
> [Hotfix][doc] Fix typo in java code demo of ES stream connector page for release-1.14

- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManager.java
> [hotfix] Remove unused method in resourcemanager

- docs/data/sql_functions.yml
backport of https://github.com/apache/flink/pull/17872 on release-1.13
No changes for Chinese version since it was added only since 1.14 https://issues.apache.org/jira/browse/FLINK-16093
> [BP-1.13][hotfix][docs][table] Fix docs for SHA1

- docs/data/sql_functions.yml
- docs/data/sql_functions_zh.yml
backport of https://github.com/apache/flink/pull/17872 on release-1.14
> [BP-1.14][hotfix][docs][table] Fix docs for SHA1

- docs/content/docs/ops/state/savepoints.md
* minor improvements to savepoint docs
see commits
> [hotfix] improvements to savepoint docs

- docs/content.zh/docs/connectors/table/firehose.md
- docs/content/docs/connectors/table/firehose.md
Adding documentation for Kinesis Firehose table api.
- Added new Docs for Kinesis firehose in table folder.
- Dependencies (does it add or upgrade a dependency):no
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper:no
- If yes, how is the feature documented?  docs
> [FLINK-26398][docs] Adding docs for Kinesis Firehose table api

- docs/content/docs/deployment/elastic_scaling.md
fixing the documentation for https://issues.apache.org/jira/browse/FLINK-25277
> [FLINK-22255][documentation] add note to documentation

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/Checkpoint.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointStatsTracker.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/Checkpoints.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointsCleaner.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CompletedCheckpoint.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CompletedCheckpointStats.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/EmbeddedCompletedCheckpointStore.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/FailedCheckpointStats.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/PendingCheckpoint.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/PendingCheckpointStats.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/StandaloneCompletedCheckpointStore.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorFailureTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorMasterHooksTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorRestoringTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointStateRestoreTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointStatsTrackerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CompletedCheckpointStoreTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CompletedCheckpointTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/DefaultCompletedCheckpointStoreTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/DefaultCompletedCheckpointStoreUtilsTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/PendingCheckpointStatsTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/PendingCheckpointTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/StandaloneCompletedCheckpointStoreTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/ZooKeeperCompletedCheckpointStoreTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/SchedulerUtilsTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/stopwithsavepoint/StopWithSavepointTerminationHandlerImplTest.java
Report completed checkpoint to statistic only after the completed checkpoint is added to the store.
- *Report statistic after all checkpoint finalization steps*
- *Report failed checkpoint if the storing completed checkpoint fails*
- *Expanded tests in CheckpointCoordinatorTest and CheckpointCoordinatorFailureTest with asserting of statistic* …
> [FLINK-25958][runtime] Report completed checkpoint to statistic only after the completed checkpoint is added to the store.

- docs/content.zh/docs/dev/table/sql/create.md
- docs/content.zh/docs/dev/table/sql/overview.md
- docs/content/docs/dev/table/sql/create.md
- docs/content/docs/dev/table/sql/overview.md
update sql create and sql overview documents.
- add catalog into supported create statement list.
> [hotfix][docs] update contents of sql create, and sql overview

- flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskTest.java
*Added extra debug logs for TaskTest*
> [FLINK-15550][runtime] Debug logging for TaskTest

- docs/content.zh/docs/ops/metrics.md
- docs/content/docs/ops/metrics.md
Fix HTML in ops/metrics.md (Rendering of HTML was broken due to misplaced newline)
Fix 'Note' paragraph and adapt to style to other 'Note' paragraphs of the rest of the document.
Verified locally with IDE-integrated markdown renderer
Only docs affected
> [hotfix][docs] Fix HTML formatting in ops/metrics.md

- flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniCluster.java
- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/streaming/util/TestStreamEnvironment.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/ChangelogPeriodicMaterializationITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/ChangelogPeriodicMaterializationRescaleITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/ChangelogPeriodicMaterializationTestBase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/SavepointFormatITCase.java
- flink-tests/src/test/java/org/apache/flink/test/util/TestUtils.java
Add ITCase for periodic materialization in Changelog state backend.
This verifies that checkpointing works correctly for Changelog state backend with materialized state / non-materialized state.
- Add ITCase called `ChangelogPeriodicMaterializationITCase`
- Added test `ChangelogPeriodicMaterializationITCase` …
> [FLINK-25143][test] Add ITCase for periodic materialization

- flink-connectors/flink-connector-cassandra/src/test/java/org/apache/flink/streaming/connectors/cassandra/CassandraConnectorITCase.java
> [FLINK-25771][connectors][Cassandra][test] Raise the Cassandra driver timeouts at the Cluster level

- docs/content.zh/docs/try-flink/datastream.md
This is to translate changes made in #17140 into Chinese. Also to address comment made in https://github.com/apache/flink/pull/19009#pullrequestreview-905796730
Translate "Running in an IDE" section.
This change is a trivial doc change without any test coverage.
NA.
NA.
> [hotfix][doc] Chinese translation of "Running in an IDE"

- docs/content.zh/docs/dev/datastream/execution_mode.md
- docs/content.zh/docs/dev/datastream/operators/overview.md
- docs/content/docs/dev/datastream/execution_mode.md
Update wrong links in the datastream/execution_mode.md page.
Update wrong links in the datastream/execution_mode.md page.
Update wrong links in the datastream/execution_mode.md page. …
> [FLINK-25800][docs] Update wrong links in the datastream/execution_mode.md page.

- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerClusterITCase.java
1.15 backport of parent PR #19075
> [FLINK-26500][BP-1.15][runtime][test] Increases the deadline to wait for parallelism

- docs/content.zh/docs/dev/datastream/execution_mode.md
- docs/content.zh/docs/dev/datastream/operators/overview.md
- docs/content/docs/dev/datastream/execution_mode.md
> [BP-1.15][docs] Update wrong links in the datastream/execution_mode.md page. 

- docs/content.zh/docs/dev/datastream/execution_mode.md
- docs/content.zh/docs/dev/datastream/operators/overview.md
- docs/content/docs/dev/datastream/execution_mode.md
> [BP-1.14][docs] Update wrong links in the datastream/execution_mode.md page.

- flink-table/flink-table-common/src/main/java/org/apache/flink/table/data/RowData.java
I found a doc error that it should be position instead of type.
3434897fc4707240e27650d457b7e86250e7e36f
Just a hotfix , no need to add test.
> [hotfix][javadocs] Fix the doc content in the createFieldGetter method of RowData

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/CustomSinkOperatorUidHashes.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/DataStream.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/DataStreamSink.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/transformations/SinkTransformation.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/translators/SinkTransformationTranslator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SinkTransformationTranslatorTest.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecSink.java
> [BP-1.15][FLINK-26613][streaming] Allow setting operator uid hashes for predefined sink operators

- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/FileSystemJobResultStore.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/FileSystemJobResultStoreTestInternal.java
> [FLINK-26698][BP-1.15][runtime] Uses the actual basePath instance instead of only the path of Path instance

- docs/content.zh/docs/connectors/datastream/formats/parquet.md
- docs/content/docs/connectors/datastream/formats/parquet.md
backport the AvroParquet doc to 1.15. For more information please refer to #19083
> [FLINK-26604][doc] backport the AvroParquet doc to 1.15

- docs/data/sql_functions.yml
- docs/data/sql_functions_zh.yml
Looks like it's a typo, fix me if i'm wrong, it's confused.
*(or)*
*(or)*
*(example:)*
- *Added integration …
> [hotfix] Fix doc about temporal functions

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/context/SessionContext.java
- flink-table/flink-sql-client/src/test/resources/sql/set.q
Currently, remove jar statement doesn't remove the corresponding jars in pipeline.jars, which should be fixed.
Replacing session dependencies instead of merging them into the new dependencies in remove-jar statements. …
> [BP-1.14][FLINK-26618] Fix pipeline.jars not aligned with remove-jar statement

- docs/content.zh/docs/concepts/time.md
- docs/content/docs/concepts/time.md
1.15 BP for parent PR https://github.com/apache/flink/pull/19127
> [BP-1.15][hotfix][docs] Fix the broken link for late events/lateness

- docs/content.zh/docs/concepts/time.md
- docs/content/docs/concepts/time.md
1.14 BP for parent PR https://github.com/apache/flink/pull/19127
> [BP-1.14][hotfix][docs] Fix the broken link for late events/lateness

- docs/data/sql_functions.yml
- docs/data/sql_functions_zh.yml
Backport of #18936 for 1.14.
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment …
> [hotfix][bp-1.14][docs] Fix doc for interval of years

- docs/data/sql_functions.yml
- docs/data/sql_functions_zh.yml
Backport of #18936 for 1.15.
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment …
> [hotfix][bp-1.15][docs] Fix doc for interval of years

- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchWriter.java
- flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchWriterITCase.java
- flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/connector/elasticsearch/sink/TestEmitter.java
Add recordSend metric to elasticsearch sink
Increment the recordsSend counter for every request that is generated by the user from a single record.
Added a test to verify the counter increases …
> [FLINK-26633][elasticsearch] Add recordSend metric to elasticsearch sink

- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/strategy/SchedulingStrategyUtils.java
Remove unnecessary method.
- Remove unnecessary method.
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not …
> [hotfix][runtime] Remove unnecessary method.

- docs/content/docs/connectors/datastream/elasticsearch.md
- docs/content/docs/connectors/table/elasticsearch.md
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchSink.java
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchSinkBuilderBase.java
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/table/ElasticsearchConnectorOptions.java
- flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchSinkBuilderBaseTest.java
- flink-connectors/flink-connector-elasticsearch6/src/main/java/org/apache/flink/connector/elasticsearch/sink/Elasticsearch6SinkBuilder.java
- flink-connectors/flink-connector-elasticsearch7/src/main/java/org/apache/flink/connector/elasticsearch/sink/Elasticsearch7SinkBuilder.java
Backport of #19035, commit is identical
> [FLINK-26281][connectors/elasticsearch] setting default delivery guarantee to AT_LEAST_ONCE

- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriter.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/TestSinkInitContext.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/sink/writer/FileWriter.java
- flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/sink/writer/FileWriterTest.java
> [FLINK-26420][Connector] use numRecordsSendCounter backport to 1.15

- docs/content/docs/connectors/table/elasticsearch.md
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/AbstractTimeIndexGenerator.java
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/ElasticsearchConfiguration.java
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/ElasticsearchConnectorOptions.java
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/ElasticsearchValidationUtils.java
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/IndexGenerator.java
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/IndexGeneratorBase.java
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/IndexGeneratorFactory.java
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/KeyExtractor.java
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/RequestFactory.java
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/RowElasticsearchSinkFunction.java
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/StaticIndexGenerator.java
- flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/IndexGeneratorFactoryTest.java
- flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/KeyExtractorTest.java
- flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/TestContext.java
- flink-connectors/flink-connector-elasticsearch6/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6Configuration.java
- flink-connectors/flink-connector-elasticsearch6/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSink.java
- flink-connectors/flink-connector-elasticsearch6/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkFactory.java
- flink-connectors/flink-connector-elasticsearch6/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
- flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkFactoryTest.java
- flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkITCase.java
- flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkTest.java
- flink-connectors/flink-connector-elasticsearch7/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7Configuration.java
- flink-connectors/flink-connector-elasticsearch7/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSink.java
- flink-connectors/flink-connector-elasticsearch7/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkFactory.java
- flink-connectors/flink-connector-elasticsearch7/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
- flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkFactoryTest.java
- flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkITCase.java
- flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkTest.java
This is the 1.15 backport of #19146.
> [FLINK-26638][connnectors/elasticsearch] Revert Table API implementation to SinkFunction

- flink-core/src/main/java/org/apache/flink/api/common/operators/MailboxExecutor.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/mailbox/MailboxDefaultAction.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/mailbox/MailboxProcessor.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/mailbox/TaskMailbox.java
Fix some typos while reading the mailbox code. 
- fix the wrong local variable name in MailboxProcessor
- fix some typos in java doc
> [hotfix][streaming] rename local variable name and fix some typos

- flink-container/src/test/java/org/apache/flink/container/entrypoint/StandaloneApplicationClusterConfigurationParserFactoryTest.java
- flink-container/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
- flink-table/flink-table-api-java-bridge/src/test/java/org/apache/flink/table/factories/PrintSinkFactoryTest.java
[JUnit5 Migration] Module: flink-container
[JUnit5 Migration] Module: flink-container
- If yes, how is the feature documented? (**not applicable** …
> [FLINK-26758][container][JUnit5 Migration] Module: flink-container

- flink-external-resources/flink-external-resource-gpu/src/test/java/org/apache/flink/externalresource/gpu/GPUDiscoveryScriptTest.java
- flink-external-resources/flink-external-resource-gpu/src/test/java/org/apache/flink/externalresource/gpu/GPUDriverTest.java
- flink-external-resources/flink-external-resource-gpu/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
[JUnit5 Migration] Module: flink-external-resources
- org.apache.flink.externalresource.gpu.GPUDriverTest
- org.apache.flink.externalresource.gpu.GPUDiscoveryScriptTest …
> [FLINK-26747][flink-external-resource-gpu][JUnit5 Migration] Module: flink-external-resources

- flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/ChangelogStateHandleStreamImpl.java
Cherry Pick to branch release-1.15
> [FLINK-26766][Runtime/StateBackends] Fix ChangelogStateHandleStreamImpl#getIntersection

- flink-connectors/flink-connector-aws-kinesis-firehose/pom.xml
- flink-connectors/flink-connector-aws-kinesis-streams/pom.xml
- flink-connectors/flink-connector-elasticsearch6/pom.xml
- flink-connectors/flink-connector-elasticsearch7/pom.xml
- flink-connectors/flink-connector-files/pom.xml
- flink-connectors/flink-connector-hive/pom.xml
- flink-connectors/flink-connector-kafka/pom.xml
- flink-connectors/flink-connector-pulsar/pom.xml
- flink-connectors/flink-sql-connector-aws-kinesis-firehose/pom.xml
- flink-connectors/flink-sql-connector-aws-kinesis-streams/pom.xml
- flink-connectors/flink-sql-connector-hbase-1.4/pom.xml
- flink-connectors/flink-sql-connector-hbase-2.2/pom.xml
- flink-connectors/flink-sql-connector-kafka/pom.xml
- flink-connectors/flink-sql-connector-kinesis/pom.xml
- flink-end-to-end-tests/flink-end-to-end-tests-aws-kinesis-firehose/pom.xml
- flink-end-to-end-tests/flink-end-to-end-tests-aws-kinesis-streams/pom.xml
- flink-end-to-end-tests/flink-streaming-kinesis-test/pom.xml
- flink-formats/flink-orc/pom.xml
- flink-formats/flink-parquet/pom.xml
- tools/ci/compile.sh
- tools/ci/shade.sh
**Unchanged** backport of https://github.com/apache/flink/pull/19131
> [FLINK-26701][connectors] Revert FLINK-25927 apart from adding connector-base to flink-dist

- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchWriter.java
- flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchWriterITCase.java
- flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/connector/elasticsearch/sink/TestEmitter.java
> [BP-1.15][FLINK-26633][elasticsearch] Add recordSend metric to elasticsearch sink

- flink-python/dev/lint-python.sh
This PR fixes Sphinx check failure when running `dev/lint-python.sh`, which is caused by newly released Jinja2.
- Add `Jinja2<3.1.0` in Sphinx installation method
> [FLINK-26855][python] Fix Sphinx check failure caused by Jinja2 dependency

- flink-formats/flink-avro-confluent-registry/src/test/java/org/apache/flink/formats/avro/registry/confluent/CachedSchemaCoderProviderTest.java
- flink-formats/flink-avro-confluent-registry/src/test/java/org/apache/flink/formats/avro/registry/confluent/ConfluentSchemaRegistryCoderTest.java
- flink-formats/flink-avro-confluent-registry/src/test/java/org/apache/flink/formats/avro/registry/confluent/RegistryAvroFormatFactoryTest.java
- flink-formats/flink-avro-confluent-registry/src/test/java/org/apache/flink/formats/avro/registry/confluent/RegistryAvroRowDataSeDeSchemaTest.java
- flink-formats/flink-avro-confluent-registry/src/test/java/org/apache/flink/formats/avro/registry/confluent/debezium/DebeziumAvroFormatFactoryTest.java
- flink-formats/flink-avro-confluent-registry/src/test/java/org/apache/flink/formats/avro/registry/confluent/debezium/DebeziumAvroSerDeSchemaTest.java
- flink-formats/flink-avro-confluent-registry/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Update the `flink-formats/flink-avro-confluent-registry` module to AssertJ and JUnit 5 following the [JUnit 5 Migration Guide](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit)
I used the https://github.com/slinkydeveloper/assertj-migrator as the starting point
- The S3 …
> [FLINK-26736][tests][JUnit5 migration] flink-avro-confluent-registry

- docs/data/sql_functions.yml
- docs/data/sql_functions_zh.yml
- flink-python/pyflink/table/expressions.py
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/Expressions.java
This pull request correct the wrong description of RAND_INTEGER function.
Document update. …
> [FLINK-26395][docs] Correct the wrong description of RAND_INTEGER.

- flink-connectors/flink-connector-base/pom.xml
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/SourceReaderBase.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/splitreader/SplitReader.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/SourceReaderBaseTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceITCase.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/source/SourceOperatorEventTimeTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/source/TestingSourceOperator.java
Unchanged backport on release-1.15 of #18790
> [BP-1.15][FLINK-26018][connector/common] Create per-split output on split addition in SourceOperator

- flink-connectors/flink-connector-base/pom.xml
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/SourceReaderBase.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/splitreader/SplitReader.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/SourceReaderBaseTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceITCase.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/source/SourceOperatorEventTimeTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/source/TestingSourceOperator.java
Unchanged back port on release-1.14 of #18790
> [BP-1.14][FLINK-26018][connector/common] Create per-split output on split addition in SourceOperator

- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricRegistryImpl.java
Small refactoring to deduplicate code.
> [FLINK-26849][metrics] Deduplicate metric (un)registration logic

- flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/metrics/Counter.java
- flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/metrics/Gauge.java
- flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/metrics/Histogram.java
- flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/metrics/Meter.java
- flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/metrics/Metric.java
- flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/metrics/MetricType.java
- flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/metrics/reporter/AbstractReporter.java
- flink-metrics/flink-metrics-datadog/src/main/java/org/apache/flink/metrics/datadog/DatadogHttpReporter.java
- flink-metrics/flink-metrics-dropwizard/src/main/java/org/apache/flink/dropwizard/ScheduledDropwizardReporter.java
- flink-metrics/flink-metrics-influxdb/src/main/java/org/apache/flink/metrics/influxdb/AbstractReporter.java
- flink-metrics/flink-metrics-jmx/src/main/java/org/apache/flink/metrics/jmx/JMXReporter.java
- flink-metrics/flink-metrics-prometheus/src/main/java/org/apache/flink/metrics/prometheus/AbstractPrometheusReporter.java
- flink-metrics/flink-metrics-prometheus/src/test/java/org/apache/flink/metrics/prometheus/PrometheusReporterTest.java
Adds a MetricType enum and adjust all reporters to make use of it.
> [FLINK-26850][metrics] Add Metric#getMetricType

- docs/content.zh/docs/connectors/datastream/pulsar.md
- docs/content/docs/connectors/datastream/pulsar.md
- docs/layouts/shortcodes/generated/pulsar_producer_configuration.html
- docs/layouts/shortcodes/generated/pulsar_sink_configuration.html
- flink-docs/src/main/java/org/apache/flink/docs/configuration/ConfigOptionsDocGenerator.java
…ulsar source documentation.
Add Chinese and English version of Pulsar Sink.
- add pulsar sink to the auto doc generation configuration.
- generate 2 config options file
Yes
> [FLINK-26028][Connector/pulsar] add sink documentation; change some source documentation

- docs/content.zh/docs/connectors/datastream/pulsar.md
- docs/content/docs/connectors/datastream/pulsar.md
- docs/layouts/shortcodes/generated/pulsar_producer_configuration.html
- docs/layouts/shortcodes/generated/pulsar_sink_configuration.html
- flink-docs/src/main/java/org/apache/flink/docs/configuration/ConfigOptionsDocGenerator.java
This is a backport PR for https://github.com/apache/flink/pull/19056
> [Backport 1.15][FLINK-26028] Add pulsar sink documentation

- docs/data/sql_functions.yml
- docs/data/sql_functions_zh.yml
- flink-python/pyflink/table/expressions.py
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/Expressions.java
Unchanged backport of https://github.com/apache/flink/pull/19104 on release-1.14
> [BP-1.14][FLINK-26395][docs] Correct the wrong description of SQL function: RAND_INTEGER

- flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/CsvRowDataDeserializationSchema.java
The `csvSchema` field was wrongly initialized.
> [hotfix] Fix CsvRowDataDeserializationSchema constructor

- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/BuiltInAggregateFunctionTestBase.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/aggregate/JsonObjectAggFunction.java
Previously, when the Json aggregation is taking place, and id
JsonOnNull.NULL is selected, which means that we still want to emit
a `null` JSON node, .i.e `{.... "myField" : null ... }` when no values
get accumulated, we used a null `StringData` object. When
`state.backend.changelog.enabled` is enabled, the contents of the map
accumulating the aggregated records, gets serialized leading to NPE,
since `null` is not supported by `StringDataSerilizer`.
To solve this, we instead create a StringData with an empty `byte[]`,
which denotes the null, and when the aggregation ends and we create
the final JSON result, we check for a `byte[]` of `length` `0` in
order to write the JSON `null` node.
- Change the parent class: …
> [FLINK-26092][table-runtime] Fix `JSON_OBJECTAGG` when emitting `NULL`

- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/MetricRegistryImplTest.java
- migrate to junit5
- remove unused configurations
- remove unused reporter implementations
- rename remaining reporter implementations
- remove use of static fields within reporters
- remove timeouts
> [FLINK-26885][metrics][tests] Cleanup MetricRegistryImplTest 

- flink-connectors/flink-connector-elasticsearch-base/pom.xml
- flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/ElasticsearchSinkTestBase.java
- flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/testutils/SourceSinkDataTestKit.java
- flink-connectors/flink-connector-elasticsearch6/pom.xml
- flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkITCase.java
- flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch6/ElasticsearchSinkITCase.java
- flink-connectors/flink-connector-elasticsearch7/pom.xml
- flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkITCase.java
- flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch7/ElasticsearchSinkITCase.java
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>
The Elasticsearch 6/7 connectors still use deprecated transport client for integration tests. This is not really necessary and brings a lot of dependencies, the HighLevelRestClient is fully sufficient and could be used as drop-in replacement. The change affects only tests.
Transport client was removed, replaced with HighLevelRestClient.
This change is already covered by existing tests, such as *(please describe tests)*:
- `flink-connector-elasticsearch6` integration tests 
- `flink-connector-elasticsearch7` integration tests …
> [FLINK-25961] [connectors/elasticsearch] Remove transport client from Elasticsearch/7 connectors (tests only)

- flink-runtime/src/main/java/org/apache/flink/runtime/state/KeyGroupRangeOffsets.java
Improve the info message when restoring keyed state backend to avoid too long message.
From 
`
7183 [OverAggregate[4] -> Calc[5] -> SinkConversion[6] -> Sink: Unnamed (2/4)#1] INFO  org.apache.flink.runtime.state.heap.HeapRestoreOperation [] - Starting to restore from state handle: KeyGroupsStateHandle{groupRangeOffsets=KeyGroupRangeOffsets{keyGroupRange=KeyGroupRange{startKeyGroup=8192, endKeyGroup=16383}, offsets=[6837, 6877, 6917, 6957, 6997, 7037, 7077, 7117, 7157, 7197, 7237, 7277, 7317, 7357, 7397, 7437, 7477, 7517, 7557, 7597, 7637, 7677, 7717, 7757, 7797, 7837, 7877, 7917, 7957, 7997, 8037, 8077, 8117, 8157, 8197, 8237, 8277, 8317, 8357, 8397, 8437, 8477, 8517, 8557, 8597, 8637, 8677, 8717, 8757, 8797, 8837, 8877, 8917, 8957, 8997, 9037, 9077, 9117, 9157, 9197, 9237, 9277, 9317, …
> [FLINK-26575][checkpoint] Improve the info message when restoring keyed state backend

- docs/content/docs/connectors/datastream/filesystem.md
Update documentation for [Add Aliyun OSS recoverable writer](https://github.com/apache/flink/pull/19072)
> [FLINK-11388][docs][oss]Update docs for OSS Recoverable writer

- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java
This is a 1.15 backport for the parent PR #19195
> [FLINK-26798][BP-1.15][runtime] Hardens JobManagerTest against unexpected heartbeat

- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java
This is a 1.14 backport for the parent PR #19195
> [FLINK-26798][1.14][runtime] Hardens test against unexpected heartbeat

- docs/content.zh/docs/dev/datastream/fault-tolerance/serialization/custom_serialization.md
*There is a link redirection problem in the Chinese document of ’Custom Serialization for Managed State‘.
When I wanted to click on the link of 'type serialization framework' in the Chinese document to get more information, the page jumped to 404, but when I checked the English document, I found that turn to correct page. So i fix the link of 'type serialization framework' in the Chinese document.*
- Modify the link of 'type serialization framework' in custom_serialization.md which under content.zh turn to 404 page.
This change is a trivial rework / …
> [hotfix][doc]There is a link redirection problem in the Chinese document of ‘custom_serialization’

- flink-state-backends/flink-statebackend-rocksdb/pom.xml
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/benchmark/RescalingBenchmark.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/benchmark/RescalingBenchmarkBuilder.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/benchmark/RescalingBenchmarkTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/util/AbstractStreamOperatorTestHarness.java
*This pull request introduces benchmarks to evaluate the performance of rescaling.
For more details please check [FLINK-23399](https://issues.apache.org/jira/browse/FLINK-23399).*
- *Introduces a benchmark that evaluates the performance of rescaling from state.*
*This change added the unit test `RescalingBenchmarkTest`.*
- The serializers: (yes / *no* / don't know) …
> [FLINK-23399][state] Add a benchmark for rescaling

- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/ZKCheckpointIDCounterMultiServersTest.java
- tools/ci/log4j.properties
1.15 backport of parent PR #19199
> [FLINK-26797][BP-1.15][runtime] Hardens ZKCheckpointIDCounterMultiServersTest

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/client/HiveShimLoader.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/client/HiveShimV238.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/client/HiveShimV239.java
Support Hive 2.3.8 and 2.3.9.
BTW, according to https://www.mail-archive.com/dev@hive.apache.org/msg142515.html, the branch 2.3 is still supported by Hive PMC, we should keep eyes on Hive release.
Support Hive 2.3.8 and 2.3.9.
*(or)*
*(or)*
*(example:)*
- …
> [FLINK-26739] Support Hive 2.3.8 and 2.3.9

- docs/content.zh/docs/deployment/metric_reporters.md
- docs/content/docs/deployment/metric_reporters.md
- flink-core/src/main/java/org/apache/flink/configuration/MetricOptions.java
> [FLINK-26886][metrics][docs] Documented pull/push tag/identifier reporter behavior

- pom.xml
newer version no longer require dependency resolution
> [FLINK-27026][build] Upgrade checkstyle plugin

- flink-core/src/main/java/org/apache/flink/util/IOUtils.java
*The word "Premeture" is misspelled in the IOUtils.java file of flink-core.*
- *Modify spelling error in IOUtils.java file of flink-core.*
*This change is a trivial rework / code cleanup without any test coverage.*
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no)
> [hotfix] Modify spelling error in IOUtils.java

- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
* Fix instability of StreamTaskTest#testMailboxMetricsScheduling
* Remove assertion for latency measurement from StreamTaskTest#testMailboxMetricsScheduling as it
causes instability and is already covered in StreamTaskTest#testMailboxMetricsMeasurement.
This change is already covered by existing tests, such as:
* StreamTaskTest#testMailboxMetricsScheduling
* StreamTaskTest#testMailboxMetricsMeasurement
- Dependencies (does it add or upgrade a dependency):  __no__
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: __no__
- The serializers: __no__ 
- The runtime …
> [FLINK-27042][metrics] Fix instability of StreamTaskTest#testMailboxMetricsScheduling

- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/typeutils/ArrayDataSerializer.java
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/typeutils/ArrayDataSerializerTest.java
Allow customized types for ArrayDataSerializer#copy, instead of throwing a cast exception.
- Added a test case for customized ArrayData types. …
> [FLINK-25238][table-runtime] Allow customized types for ArrayDataSerializer#copy

- docs/content/docs/dev/configuration/overview.md
depends on: https://github.com/apache/flink-web/pull/504
> [FLINK-25897][docs] Update gradle quickstart quide to gradle 7.3.3

- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/typeutils/ArrayDataSerializer.java
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/typeutils/ArrayDataSerializerTest.java
Backport #19316 to release-1.14
cc @gyfora 
*(or)*
This change is …
> [BP-1.14][FLINK-25238][table-runtime] Fix ArrayDataSerializer#copy for customized types

- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/typeutils/ArrayDataSerializer.java
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/typeutils/ArrayDataSerializerTest.java
Backport #19316 to 1.15
cc @gyfora 
*(or)*
This change is already …
> [BP-1.15][FLINK-25238][table-runtime] Fix ArrayDataSerializer#copy for customized types

- flink-core/src/main/java/org/apache/flink/api/java/typeutils/runtime/PojoSerializer.java
- flink-core/src/main/java/org/apache/flink/api/java/typeutils/runtime/RuntimeSerializerFactory.java
Fix concurrent modification exception.
Fix concurrent modification exception.
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not …
> [FLINK-26835][serialization] Fix concurrent modification exception

- docs/content.zh/docs/connectors/datastream/kafka.md
- docs/content/docs/connectors/datastream/kafka.md
This is a 1.15 backport of PR [https://github.com/apache/flink/pull/19375](https://github.com/apache/flink/pull/19375)
[FLINK-27088][Documentation] Fix the example of using StringDeserializer for deserializing Kafka message value as string
This pull request fixed the example of using StringDeserializer for deserializing Kafka message value as string.
- Replacing StringSerializer with StringDeserializer …
> [FLINK-27088][BP-1.15][Documentation] Fix the example of using StringDeserializer for deserializing Kafka message value as string

- docs/content.zh/docs/connectors/table/hive/hive_catalog.md
- docs/content/docs/connectors/table/hive/hive_catalog.md
* As it's not supported to use yaml in SQL CLI, the documatation about how to create hive catalog in SQL CLI is out of date.
The pr is to correct the usage.
*
- *modify the hive_catalog.md*
> [FLINK-24940] [docs] correct usage about how to create Hive catalog via Flink SQL CLI

- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTest.java
> [FLINK-26993][tests] Wait until checkpoint was actually triggered

- docs/content.zh/docs/connectors/table/hive/hive_catalog.md
- docs/content/docs/connectors/table/hive/hive_catalog.md
Backport for https://github.com/apache/flink/pull/17829
*(or)*
*(or)*
*(example:)*
- *Manually …
> [FLINK-24940][docs] Correct usage about how to create Hive catalog via  Flink SQL CLI

- docs/content/docs/dev/table/config.md
Following the work on [FLINK-16835] update the docs accordingly to
mention the use of `EnvironmentSettings` and that `TableEnvironement`
related configuration can also be set in `flink-conf.yaml`.
- Update docs for `TableEnvironment` configuration
- Update examples for instantiating `TableEnvironment` using `EnvironmentSettings`.
This change is only docs related without the need of any test coverage. …
> [FLINK-27111][table][docs] Update docs regarding TableEnvironment configuration

- flink-docs/src/test/java/org/apache/flink/docs/configuration/ConfigOptionsDocGeneratorTest.java
- flink-docs/src/test/java/org/apache/flink/docs/configuration/ConfigOptionsDocsCompletenessITCase.java
- flink-docs/src/test/java/org/apache/flink/docs/rest/OpenApiSpecGeneratorTest.java
- flink-docs/src/test/java/org/apache/flink/docs/rest/RestAPIDocGeneratorTest.java
- flink-docs/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
[flink-docs] [JUnit5 Migration] Module: flink-docs
[flink-docs] [JUnit5 Migration] Module: flink-docs …
> [FLINK-27143][flink-docs] [JUnit5 Migration] Module: flink-docs

- flink-table/flink-sql-parser/src/main/resources/org.apache.flink.sql.parser.utils/junit-platform.properties
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/BuiltInFunctionTestBase.java
- flink-table/flink-table-planner/src/test/resources/junit-platform.properties
This PR tries to address the concurrent test instabilities, found in https://issues.apache.org/jira/browse/FLINK-26979 and https://issues.apache.org/jira/browse/FLINK-27131. The solution here might not be definitive and might not solve the linked issues, but it should improve over the existing situation.
See commit description for details
> [hotfix][table] Address the concurrent test instabilities

- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/AbstractDispatcherTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherCleanupITCase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/TestingDispatcher.java
1.15 backport of parent PR #19353
> [FLINK-27050][BP-1.15][runtime][tests] Removes default RpcSystem instance

- docs/content.zh/docs/dev/datastream/operators/windows.md
- docs/content/docs/dev/datastream/operators/windows.md
Fix wrong indentation in doc dev/datastream/operators/windows.md
https://nightlies.apache.org/flink/flink-docs-master/docs/dev/datastream/operators/windows/#processwindowfunction
Due to special char the current indentation of ProcessWindowFunction in doc dev/datastream/operators/windows.md is wrong. It's not very visible in the source code. However, if you visit the formatted doc ([e.g.](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/datastream/operators/windows/#processwindowfunction)), you will see the wrong indentation. It can be fixed by using spaces in the example code.
- Dependencies (does it add or upgrade a dependency): (yes / no) **no** …
> [FLINK-27278][docs] Fix wrong indentation in windows docs

- docs/content.zh/docs/dev/table/config.md
- docs/content/docs/dev/table/config.md
https://issues.apache.org/jira/browse/FLINK-27121
Translate "Configuration#overview" paragraph and the code example in "Application Development > Table API & SQL" to Chinese
PR: https://github.com/apache/flink/pull/19387
> [FLINK-27121][docs-zh]Translate "Configuration#overview" paragraph and the code example in "Application Development > Table API & SQL" to Chinese

- docs/content.zh/docs/dev/table/types.md
- docs/content/docs/dev/table/types.md
Misprints in types.md
dataytes => datatypes
> [docs][typos] Misprint in types.md

- docs/content.zh/docs/dev/table/concepts/overview.md
Accidentally broke https://github.com/apache/flink/pull/19488 while in the process of merging, so this PR is to restore that broken situation and give credits to [snailHumming](https://github.com/snailHumming)
> [hotfix][docs-zh] Improving Chinese translation for Table concepts overview documentation

- docs/content.zh/docs/ops/metrics.md
- docs/content/docs/ops/metrics.md
fix typo issue in metrics
fix typo issue in metrics …
> [FLINK-27163][docs] fix typo issue in metrics doc

- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/agg/batch/AggCodeGenHelper.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/table/AggregationITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/UserDefinedAggFunctions.scala
Support code gen for aggregate function with empty parameter. Currently, if the aggregate function doesn't have any parameter, the code generated can't be complied.
1. concat externalAccTerm and  operandTerms together to generate aggParametersCode.
Added test in [AggregationITCase.scala](https://github.com/apache/flink/compare/master...luoyuxia:support-agg-function-with-empty-parameter?expand=1#diff-aa794e47c3b5d4ffa68662e05a7ebeb919eb8ef93c16771cffba0b937ff4a00e)#testAggregateEmptyDataSets …
> [FLINK-27145][table] Support code gen for aggregate function with empty parameter

- docs/content.zh/docs/ops/state/state_backends.md
- docs/content/docs/ops/state/state_backends.md
JobManagerStateBackend changed to JobManagerCheckpointStorage
JobManagerStateBackend changed to JobManagerCheckpointStorage …
> [FLINK-27315][docs] Fix the demo of MemoryStateBackendMigration

- flink-metrics/flink-metrics-prometheus/pom.xml
- flink-metrics/flink-metrics-prometheus/src/main/java/org/apache/flink/metrics/prometheus/AbstractPrometheusReporter.java
- flink-metrics/flink-metrics-prometheus/src/test/java/org/apache/flink/metrics/prometheus/PrometheusPushGatewayReporterTest.java
- flink-metrics/flink-metrics-prometheus/src/test/java/org/apache/flink/metrics/prometheus/PrometheusReporterTaskScopeTest.java
- flink-metrics/flink-metrics-prometheus/src/test/java/org/apache/flink/metrics/prometheus/PrometheusReporterTest.java
- flink-metrics/flink-metrics-prometheus/src/test/java/org/apache/flink/metrics/prometheus/TestUtils.java
General cleanup in the prometheus reporter code base. Removes various warnings, simplifies some tests and reduces dependencies on runtime-internals.
> [FLINK-23659][metrics][prometheus] Cleanup code

- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/writer/topic/TopicMetadataListener.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/subscriber/impl/BasePulsarSubscriber.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/subscriber/impl/TopicListSubscriber.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/topic/TopicNameUtils.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/sink/writer/topic/TopicMetadataListenerTest.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/enumerator/subscriber/PulsarSubscriberTest.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/PulsarRuntimeOperator.java
This is a backport PR for #19092.
> [BK-1.15][FLINK-26645][Connector/pulsar] Support subscribe only one topic partition

- flink-formats/flink-csv/src/test/java/org/apache/flink/formats/csv/TableCsvFormatITCase.java
JsonPlanTestBase is not intended to be used for testing connectors and formats. This PR removes this dependency.
> [hotfix][test][formats] Detach TableCsvFormatITCase from JsonPlanTestBase

- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/MiniDispatcher.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/MiniDispatcherTest.java
1.15 backport of parent PR #19567
> [FLINK-27382][BP-1.15][runtime] Moves cluster shutdown to when the job cleanup is done in job mode

- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableSourceITCase.java
- flink-libraries/flink-gelly-examples/src/test/java/org/apache/flink/graph/test/examples/MusicProfilesITCase.java
- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/test/util/TestBaseUtils.java
- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnTestBase.java
> [FLINK-27453][tests] Cleanup TestBaseUtils 

- flink-runtime/src/test/java/org/apache/flink/runtime/state/testutils/StateAssertions.java
- flink-state-backends/flink-statebackend-heap-spillable/src/test/java/org/apache/flink/runtime/state/heap/CopyOnWriteSkipListStateMapBasicOpTest.java
- flink-state-backends/flink-statebackend-heap-spillable/src/test/java/org/apache/flink/runtime/state/heap/CopyOnWriteSkipListStateMapComplexOpTest.java
- flink-state-backends/flink-statebackend-heap-spillable/src/test/java/org/apache/flink/runtime/state/heap/CopyOnWriteSkipListStateMapTestUtils.java
- flink-state-backends/flink-statebackend-heap-spillable/src/test/java/org/apache/flink/runtime/state/heap/OnHeapLevelIndexHeaderTest.java
- flink-state-backends/flink-statebackend-heap-spillable/src/test/java/org/apache/flink/runtime/state/heap/SkipListKeyComparatorTest.java
- flink-state-backends/flink-statebackend-heap-spillable/src/test/java/org/apache/flink/runtime/state/heap/SkipListSerializerTest.java
- flink-state-backends/flink-statebackend-heap-spillable/src/test/java/org/apache/flink/runtime/state/heap/SkipListUtilsTest.java
- flink-state-backends/flink-statebackend-heap-spillable/src/test/java/org/apache/flink/runtime/state/heap/TestAllocator.java
- flink-state-backends/flink-statebackend-heap-spillable/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Migrate heap-spillable statebackend tests to junit5.
> [FLINK-27470][state][tests] Migrate test to JUnit5

- docs/content.zh/docs/connectors/datastream/formats/hadoop.md
- docs/content.zh/docs/dev/dataset/hadoop_compatibility.md
- docs/content/docs/connectors/dataset/formats/hadoop.md
- docs/content/docs/connectors/datastream/formats/hadoop.md
Trivial misprint fix class name for `ExecutionEnvironment` class in 
docs/content.zh/docs/connectors/datastream/formats/hadoop.md
docs/content.zh/docs/dev/dataset/hadoop_compatibility.md
docs/content/docs/connectors/dataset/formats/hadoop.md
docs/content/docs/connectors/datastream/formats/hadoop.md
`ExecutionEnvironmen` => `ExecutionEnvironment`
> [hotfix][docs] Misprint in docs for ExecutionEnvironment class

- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/test/util/SecureTestEnvironment.java
- flink-yarn-tests/src/test/java/org/apache/flink/yarn/CliFrontendRunWithYarnTest.java
- flink-yarn-tests/src/test/java/org/apache/flink/yarn/UtilsTest.java
- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNApplicationITCase.java
- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNFileReplicationITCase.java
- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNHighAvailabilityITCase.java
- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNITCase.java
- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNSessionCapacitySchedulerITCase.java
- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNSessionFIFOITCase.java
- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNSessionFIFOSecuredITCase.java
- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnConfigurationITCase.java
- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnPrioritySchedulingITCase.java
- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnTestBase.java
- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnTestBaseTest.java
- flink-yarn-tests/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
[JUnit5 Migration] Module: flink-yarn-test
[JUnit5 Migration] Module: flink-yarn-test …
> [FLINK-26496][flink-yarn-test] [JUnit5 Migration] Module: flink-yarn-test

- flink-formats/flink-sql-avro-confluent-registry/pom.xml
Unchanged backport of https://github.com/apache/flink/pull/19635
> [FLINK-27442][BP 1.14][Formats][Avro Confluent] Add Confluent repo to module flink-sql-avro-confluent-registry

- flink-formats/flink-sql-avro-confluent-registry/pom.xml
Unchanged backport of https://github.com/apache/flink/pull/19635
> [FLINK-27442][BP 1.15][Formats][Avro Confluent] Add Confluent repo to module flink-sql-avro-confluent-registry

- docs/data/sql_functions.yml
This is a trivial PR correcting description for `value1 IS DISTINCT FROM value2` in docs
> [FLINK-24820][table][docs] Wrong description in documentation for IS DISTINCT FROM

- docs/content.zh/docs/dev/table/sql/queries/window-join.md
- docs/content/docs/dev/table/sql/queries/window-join.md
The doc of FULL JOIN example is incorrect and not consistent with the real output, `L.window_start` and `L.window_end` will become NULL while join condition not matched.
Use `COALESCE` to ensure that every entry of resultset has non-null `window_start` and `window_end` value.
No
> [hotfix][doc] Fix the mismatch result in Window Join example

- docs/content.zh/docs/connectors/datastream/pulsar.md
- docs/content/docs/connectors/datastream/pulsar.md
**A few lines(about java11) in  Chinese pulsar document are redundant.**
**English document：**
**Chinese document：**
Delete redundant lines in pulsar.md.
> [hotfix][docs-zh] Delete redundant lines in pulsar.md

- docs/content.zh/docs/try-flink/datastream.md
translate section "Running in an IDE"
> [hotfix] [docs]  Add missing translation in datastream.md

- docs/content/docs/connectors/datastream/kafka.md
…ception in docs
Multiple users were seeing a problem during metrics registration of the underlying KafkaConsumer of the KafkaSource. This PR adds a section to the KafkaSource documentation that explains the situation and provides guidance about how to resolve it.
- Add triage docs sections to KafkaSource and include InstanceAlreadyExistsException explanation
Docs only change …
> [FLINK-27480][kafka] Explain possible metrics InstanceAlreadyExistsException in docs

- docs/content.zh/docs/dev/table/types.md
Translate the new CAST documentation to Chinese
-  Adjust some lines in the docs/content.zh/docs/dev/table/types.md to ensure that this page is consistent with the English version.
-  Translate the new CAST documentation to Chinese.
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment with large payloads …
> [FLINK-26588][docs]Translate the new CAST documentation to Chinese

- flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/async/AsyncIOExample.java
fix comment typos in `AsyncIOExample.java`
illustrates -> illustrate
no
> [hotfix] Fix comment typos in AsyncIOExample

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internals/metrics/KafkaMetricMutableWrapper.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/internals/metrics/KafkaMetricMutableWrapperTest.java
> [FLINK-27487][kafka] Only forward measurable Kafka metrics and ignore others

- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/PulsarSourceBuilder.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/subscriber/impl/BasePulsarSubscriber.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/subscriber/impl/TopicListSubscriber.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/topic/TopicNameUtils.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/enumerator/subscriber/PulsarSubscriberTest.java
This is a backport PR for #19092
> [BK-1.14][FLINK-26645][Connector/pulsar] Support subscribe only one topic partition/

- docs/content/docs/dev/datastream/application_parameters.md
Currently, it is using both `parameters` and `parameter`. for example below codes are mixed using both.
```java
ParameterTool parameters = // ...
parameter.getRequired("input");
parameter.get("output", "myDefaultValue");
parameter.getLong("expectedCount", -1L);
parameter.getNumberOfParameters();
```
Just change to `parameters` to be consistent. Also updated the rest of the doc to be consistent.
Fix "parameters" in the doc.
*(or)* …
> [hotfix][docs] fix "parameters"

- flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroFormatFactoryTest.java
- flink-formats/flink-compress/src/test/java/org/apache/flink/formats/compress/CompressWriterFactoryTest.java
- flink-formats/flink-compress/src/test/java/org/apache/flink/formats/compress/CompressionFactoryITCase.java
- flink-formats/flink-csv/src/test/java/org/apache/flink/formats/csv/CsvFormatFactoryTest.java
- flink-formats/flink-csv/src/test/java/org/apache/flink/formats/csv/CsvRowDataSerDeSchemaTest.java
- flink-formats/flink-csv/src/test/java/org/apache/flink/formats/csv/CsvRowDeSerializationSchemaTest.java
- flink-formats/flink-csv/src/test/java/org/apache/flink/formats/csv/RowCsvInputFormatSplitTest.java
- flink-formats/flink-csv/src/test/java/org/apache/flink/formats/csv/RowCsvInputFormatTest.java
- flink-formats/flink-hadoop-bulk/src/test/java/org/apache/flink/formats/hadoop/bulk/AbstractFileCommitterTest.java
- flink-formats/flink-hadoop-bulk/src/test/java/org/apache/flink/formats/hadoop/bulk/HadoopPathBasedPartFileWriterTest.java
- flink-formats/flink-hadoop-bulk/src/test/java/org/apache/flink/formats/hadoop/bulk/HadoopPathBasedPendingFileRecoverableSerializerMigrationTest.java
- flink-formats/flink-hadoop-bulk/src/test/java/org/apache/flink/streaming/api/functions/sink/filesystem/HadoopPathBasedBulkFormatBuilderTest.java
- flink-formats/flink-orc/src/test/java/org/apache/flink/orc/OrcColumnarRowInputFormatTest.java
- flink-formats/flink-orc/src/test/java/org/apache/flink/orc/OrcColumnarRowSplitReaderTest.java
- flink-formats/flink-orc/src/test/java/org/apache/flink/orc/OrcFileSystemFilterTest.java
- flink-formats/flink-orc/src/test/java/org/apache/flink/orc/OrcFileSystemITCase.java
- flink-formats/flink-orc/src/test/java/org/apache/flink/orc/OrcSplitReaderUtilTest.java
- flink-formats/flink-orc/src/test/java/org/apache/flink/orc/util/OrcBulkWriterTestUtil.java
- flink-formats/flink-orc/src/test/java/org/apache/flink/orc/writer/OrcBulkRowDataWriterTest.java
- flink-formats/flink-orc/src/test/java/org/apache/flink/orc/writer/OrcBulkWriterFactoryTest.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/ParquetColumnarRowInputFormatTest.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/ParquetFileSystemITCase.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/avro/AvroParquetFileReadITCase.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/avro/AvroParquetStreamingFileSinkITCase.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/protobuf/ParquetProtoStreamingFileSinkITCase.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/row/ParquetRowDataWriterTest.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/vector/ParquetColumnarRowSplitReaderTest.java
- flink-formats/flink-sequence-file/src/test/java/org/apache/flink/formats/sequencefile/SequenceStreamingFileSinkITCase.java
- flink-formats/flink-sequence-file/src/test/java/org/apache/flink/formats/sequencefile/SerializableHadoopConfigurationTest.java
This PR fixes and grandfathers #19425
> [FLINK-27185][connectors][formats] Convert format modules to assertj 

- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDeserializeExceptionTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDynamicTableFactoryTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveLookupJoinITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveOutputFormatFactoryTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveRunnerITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveSourceITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableFactoryTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableSinkITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableSourceITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/PartitionMonitorTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/TableEnvHiveConnectorITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/read/HiveInputFormatPartitionReaderITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/read/HivePartitionFetcherTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/read/HiveTableFileInputFormatTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/util/HiveConfUtilsTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/catalog/hive/HiveCatalogDataTypeTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/catalog/hive/HiveCatalogHiveMetadataTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/catalog/hive/HiveCatalogUdfITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/catalog/hive/factories/HiveCatalogFactoryTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/catalog/hive/util/HiveTableUtilTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/functions/hive/HiveGenericUDAFTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/functions/hive/HiveGenericUDFTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/functions/hive/HiveGenericUDTFTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/functions/hive/HiveSimpleUDFTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/module/hive/HiveModuleFactoryTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/module/hive/HiveModuleTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/planner/delegation/hive/HiveASTParserTest.java
Cherry-picked commits from https://github.com/apache/flink/pull/19660 to get the individual changes merged faster
> [FLINK-27185][connectors] Convert connector-hive module to assertj

- flink-connectors/flink-connector-cassandra/src/test/java/org/apache/flink/streaming/connectors/cassandra/CassandraConnectorITCase.java
- flink-connectors/flink-connector-cassandra/src/test/java/org/apache/flink/streaming/connectors/cassandra/CassandraSinkBaseTest.java
- flink-connectors/flink-connector-cassandra/src/test/java/org/apache/flink/streaming/connectors/cassandra/CassandraTupleWriteAheadSinkTest.java
Cherry-picked commits from https://github.com/apache/flink/pull/19660 to get the individual changes merged faster
> [FLINK-27185][connectors] Convert connector-cassandra module to assertj

- flink-runtime/src/main/java/org/apache/flink/runtime/util/ZooKeeperUtils.java
ZooKeeperUtils.deleteZNode implements a retry loop that is not necessary for curator version 4.0.1+. We can use idempotent delete since we already upgraded Curator to 5.2.0.
- *Delete retry mechanism from ZooKeeperUtils.deleteZNode*
This change is already covered by existing tests, such as ZooKeeperUtilsWriteLeaderInformationTest#testDeleteZNode().
- If …
> [FLINK-25950][Runtime] Delete retry mechanism from ZooKeeperUtils.deleteZNode

- pom.xml
Temporarily disables the jboss repository, as it is currently down.
> [FLINK-27751][build] Disable jboss repository

- docs/content.zh/docs/libs/cep.md
- **This is the English document：**
- **This is the Chinese document：**
-  **Fix the formatting errors of some Chinese documents.**
- **This change is a trivial rework / code cleanup without any test coverage.**
- Dependencies (does it add or upgrade a dependency): ( **no** )
> [hotfix][docs-zh] Fix the formatting errors of some Chinese documents.

- docs/static/generated/rest_v1_dispatcher.yml
- flink-docs/src/main/java/org/apache/flink/docs/rest/OpenApiSpecGenerator.java
Make sure the spec uses enum references for all endpoints, as otherwise a separate class is generated for each of them.
> [FLINK-27818][rest][docs] Model enums as references

- docs/content.zh/docs/ops/state/checkpointing_under_backpressure.md
- docs/content/docs/ops/state/checkpointing_under_backpressure.md
Update the doc of aligned checkpoint timeout.
Update the doc of aligned checkpoint timeout.
> [FLINK-27825][docs] Update the doc of aligned checkpoint timeout

- flink-python/pyflink/datastream/__init__.py
Add pulsar comments in the datastream package
- *Add pulsar comments in __init__.py of the datastream package*
- Does this pull request introduce a new feature? (no
- If yes, how is the feature documented? (PyDocs)
> [FLINK-27924][python][docs] Add pulsar comments in the datastream package

- flink-end-to-end-tests/flink-end-to-end-tests-sql/pom.xml
- flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/codegen/PlannerScalaFreeITCase.java
- flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/resources/log4j2-test.properties
- flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/resources/scala_free_e2e.sql
- flink-end-to-end-tests/flink-sql-client-test/src/main/java/org/apache/flink/table/toolbox/CountAggFunction.java
- flink-end-to-end-tests/pom.xml
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/agg/ImperativeAggCodeGen.scala
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/util/SingleElementIterator.java
This is a cherry-pick back to release-1.15 branch.
> [BP-1.15][FLINK-27606][table] Fix CompileException when using UDAF with merge() method

- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/RetractableTopNFunction.java
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/rank/RetractableTopNFunctionTest.java
This is a cherry-pick back to the release-1.14 branch.
> [BP-1.14][FLINK-27418][table-planner] Fix topN retraction for previously deleted record

- flink-runtime-web/src/main/resources/META-INF/NOTICE
- flink-runtime-web/web-dashboard/package-lock.json
- flink-runtime-web/web-dashboard/package.json
FLINK-25714
Remove necessary runtime-web dependency **@ant-design/icons-angular** after upgrading **ng-zorro-antd**
- Upgrade ng-zorro-antd from 13.0.1 to 13.2.2
- Remove @ant-design/icons-angular from `package.json`
> [FLINK-25714][runtime-web] upgrade ng-zorro-antd and remove unnecessary dependency

- flink-runtime-web/web-dashboard/src/app/pages/job/checkpoints/job-checkpoints.component.html
- flink-runtime-web/web-dashboard/src/app/pages/job/checkpoints/job-checkpoints.component.ts
fix checkpoint interval in WebUI , which is described in [FLINK-27734](https://issues.apache.org/jira/browse/FLINK-27734)
> [FLINK-27734][web] Fix checkpoint interval in WebUI

- flink-end-to-end-tests/flink-end-to-end-tests-sql/pom.xml
- flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/codegen/PlannerScalaFreeITCase.java
Fix failed end-to-end-tests-sql CI test
Brief change log
Fix failed end-to-end-tests-sql CI test
Does this pull request potentially affect one of the following parts:
Dependencies (does it add or upgrade a dependency): (no)
The public API, i.e., is any changed class annotated with @Public(Evolving): (no)
The serializers: (no)
The runtime per-record code paths (performance sensitive): (no)
Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: ( no)
The S3 file system connector: ( no )
Documentation
Does this pull request introduce a new feature? (no)
If yes, how is the feature documented? (not documented)
> [FLINK-27968][E2E] Fix failed end-to-end-tests-sql CI test

- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterTest.java
- One of the integration tests (checkLoggedSendTimesAreWithinBounds) of AsyncSinkWriterTest has been reported to fail intermittently on build pipeline causing blocking of new changes.
- The failing test tests sending times for batch with a tight margin and using multiple batches, hence the test was unstable and was changed.
- updated `checkLoggedSendTimesAreWithinBounds` test to be with 20ms time margin and to send 1 single batch.
- success rate of test up from 98% to 100%. …
> [FLINK-27756] Setting Batches sent to 1 and extending sending margin in checkLoggedSendTimesAreWithinBounds test

- docs/content.zh/docs/dev/table/common.md
- docs/content/docs/dev/table/common.md
Update outdated code in the example, for more details please see [FLINK-27544 on jira](https://issues.apache.org/jira/browse/FLINK-27544?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=17533584#comment-17533584).
Edit example code in common.md in content\docs\dev\table and content.zh\docs\dev\table.
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no) no 
- The serializers: (yes …
> [FLINK-27544][docs]Example code in 'Structure of Table API and SQL Programs' is out of date and cannot run.

- docs/content.zh/docs/deployment/ha/kubernetes_ha.md
- docs/content.zh/docs/deployment/resource-providers/standalone/kubernetes.md
- docs/content/docs/deployment/ha/kubernetes_ha.md
- docs/content/docs/deployment/resource-providers/standalone/kubernetes.md
- docs/layouts/shortcodes/generated/common_high_availability_section.html
- docs/layouts/shortcodes/generated/high_availability_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/HighAvailabilityOptions.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesHighAvailabilityRecoverFromSavepointITCase.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/factory/KubernetesJobManagerFactoryTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesJobManagerParametersTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/HighAvailabilityServicesUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmanager/HighAvailabilityMode.java
A small user-experience improvement.
> [FLINK-27808][ha] Allow "kubernetes" as HA_MODE

- flink-yarn/src/main/java/org/apache/flink/yarn/cli/FlinkYarnSessionCli.java
We need to change the order of statements to avoid a race condition (see https://issues.apache.org/jira/browse/FLINK-24960).
> [FLINK-24960][yarn-tests] change order of statements to avoid race condition

- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/aggfunctions/SingleValueAggFunction.java
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/AggFunctionFactory.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/AggregateITCase.scala
To support `CharSingleValueAggFunction` in case of `CHAR` type. 
Add `CharSingleValueAggFunction ` for case `CHAR`.
Added test in `AggregateITCase.scala#testGroupBySingleValue`
- If yes, how is the feature documented?  NA
> [FLINK-27006][Table SQL / API] Support CharSingleValueAggFunction

- docs/content.zh/docs/dev/table/types.md
Translate the "Data Type" section of "Data Types" in to Chinese.
*(or)*
*(or)*
*(example:)*
- …
> [FLINK-27290][docs-zh]Translate the "Data Type" section of "Data Types" in to Chinese.

- tools/ci/java-ci-tools/src/main/java/org/apache/flink/tools/ci/licensecheck/NoticeFileChecker.java
With this PR the output of the license checker is grouped by module and severity, hopefully making the problems easier to understand.
> [FLINK-28175][ci] Improve license checker output

- flink-end-to-end-tests/flink-glue-schema-registry-json-test/src/test/java/org/apache/flink/glue/schema/registry/test/json/GlueSchemaRegistryJsonKinesisITCase.java
Disabling Flaky  GlueSchemaRegistryJsonKinesisITCase test to unblock build CI
-Disabled GlueSchemaRegistryJsonKinesisITCase test
- Dependencies (does it add or upgrade a dependency): n
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: n
- The serializers: n
- The runtime per-record code paths (performance sensitive):n)
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: n
- The S3 file system connector:n
- Does this pull request introduce a new feature? n
> [FLINK-28169] Disabling Flaky  GlueSchemaRegistryJsonKinesisITCase test to unblock build CI

- docs/content.zh/docs/deployment/memory/network_mem_tuning.md
Translate the doc of overdraft buffers
Translate the doc of overdraft buffers
> [FLINK-26762][docs-zh] Translate the doc of overdraft buffers

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserCalcitePlanner.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserUtils.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserBaseSemanticAnalyzer.java
- flink-connectors/flink-connector-hive/src/test/resources/query-test/sub_query.q
To fix "unexpected correlate variable $cor0" exception using hive dialect.
Add variables when create LogicFilter.
Added sub_query.q contains the sql that will throw exception before this fix.
> [FLINK-26361][hive] Create LogicalFilter with CorrelationId to fix "unexpected correlate variable" exception when using Hive dialect

- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/config/PulsarClientFactory.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/config/PulsarConfiguration.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/PulsarSinkBuilder.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/config/PulsarSinkConfigUtils.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/writer/PulsarWriter.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/PulsarSourceBuilder.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/config/PulsarSourceConfigUtils.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/sink/PulsarSinkITCase.java
This is a backport PR for #19285.
> [BK-1.15][FLINK-26931][Connector/pulsar] Make the producer name and consumer name unique in Pulsar

- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/config/PulsarClientFactory.java
Address spotless violation when merging backport https://github.com/apache/flink/pull/19430
> [hotfix][connector][pulsar] Address Spotless violation from FLINK-26931

- flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/batch/connectors/cassandra/CassandraOutputFormatBase.java
- flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/batch/connectors/cassandra/CassandraPojoOutputFormat.java
- flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/batch/connectors/cassandra/CassandraRowOutputFormat.java
- flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/batch/connectors/cassandra/CassandraTupleOutputFormat.java
- flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/streaming/connectors/cassandra/CassandraPojoSink.java
- flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/streaming/connectors/cassandra/CassandraRowSink.java
- flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/streaming/connectors/cassandra/CassandraScalaProductSink.java
- flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/streaming/connectors/cassandra/CassandraSinkBase.java
- flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/streaming/connectors/cassandra/CassandraTupleSink.java
Please read the comments in the ticket that concluded to adding more details and recommendations regarding the issue.
R: @AHeise
> [FLINK-26793][documentation] Add recommendations about the write timeout to the javadoc of Cassandra sink and output format

- flink-end-to-end-tests/test-scripts/test_kubernetes_pyflink_application.sh
- flink-end-to-end-tests/test-scripts/test_pyflink.sh
- flink-end-to-end-tests/test-scripts/test_pyflink_yarn.sh
- flink-python/dev/lint-python.sh
*This pull request will clean up python environment after e2e tests*
- *Clean up python environment after e2e tests*
- *Original tests*
> [FLINK-28355][python][e2e] Clean up python environment after e2e tests

- docs/content.zh/docs/connectors/table/kafka.md
- docs/content/docs/connectors/datastream/kafka.md
- docs/content/docs/connectors/table/kafka.md
Unchanged back port of #19904 on release-1.14
> [BP-1.14][FLINK-27865][docs] Add example for configuring SASL and SSL in Kafka DataStream and SQL connector

- docs/content.zh/docs/connectors/datastream/kafka.md
- docs/content.zh/docs/connectors/table/kafka.md
- docs/content/docs/connectors/datastream/kafka.md
- docs/content/docs/connectors/table/kafka.md
> [BP-1.15][FLINK-27865][docs] Add example for configuring SASL and SSL in Kafka DataStream and SQL connector

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraph.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamNode.java
- flink-tests/src/test/java/org/apache/flink/test/streaming/api/datastream/FinishedSourcesWatermarkITCase.java
This is 1.14 backport of https://github.com/apache/flink/pull/20158
> [FLINK-28357][datastream] Disallow null elements in StreamNode#typeSerializersIn (1.14)

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraph.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamNode.java
- flink-tests/src/test/java/org/apache/flink/test/streaming/api/datastream/FinishedSourcesWatermarkITCase.java
This is 1.15 backport of https://github.com/apache/flink/pull/20158
> [FLINK-28357][datastream] Disallow null elements in StreamNode#typeSerializersIn (1.15) 

- docs/content/docs/flinkDev/ide_setup.md
The settings layout changed in the newer IntelliJ versions. This hotfix updates the docs to incorporate the up-to-date instructions.
> [hotfix][docs] Update code formatting instructions for newer IntelliJ versions.

- docs/content/docs/connectors/datastream/kafka.md
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/OffsetsInitializer.java
> [BP-1.14][FLINK-28454][kafka][docs] Fix the wrong timestamp unit of KafkaSource

- docs/content.zh/docs/deployment/resource-providers/standalone/overview.md
Fix formatting in Chinese doc:
https://nightlies.apache.org/flink/flink-docs-master/zh/docs/deployment/resource-providers/standalone/overview/
> [hotfix][docs] Fix formatting in Chinese doc

- docs/content.zh/docs/connectors/datastream/kafka.md
- docs/content/docs/connectors/datastream/kafka.md
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/OffsetsInitializer.java
> [BP-1.15][FLINK-28454][kafka][docs] Fix the wrong timestamp unit of KafkaSource

- flink-core/src/main/java/org/apache/flink/configuration/StateChangelogOptionsInternal.java
- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/BootstrapTransformation.java
- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/StateBootstrapTransformation.java
- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/runtime/SavepointEnvironment.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/JobGraph.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGenerator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
Some methods in the `flink-runtime` module want to use `StreamConfig.ENABLE_CHANGE_LOG_STATE_BACKEND `constant(in `flink-streaming-java` module), but `flink-runtime` should not depend on `flink-streaming-java`.  This pr moves the changelog flag to `flink-core`.
See this [discussion](https://github.com/apache/flink/pull/19907#discussion_r902485780) for more details.
- move `ENABLE_CHANGE_LOG_STATE_BACKEND` from `StreamConfig` to `org.apache.flink.api.common.ExecutionConfig`
- …
> [FLINK-28286][state] move 'enablechangelog' constant to flink-core module

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaCommitter.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaCommitterTest.java
The goal of this PR is to address a memory leak where the Kafka Producer does not get cleaned up after kafka commit is successful.
[7304f9d](https://github.com/charles-tan/flink/commit/7304f9dd3c2c65dd985f5de831496b091b58b556): recycles producer after successful kafka commit by adding a finally block to the existing try/catch.
[3d68e4e](https://github.com/apache/flink/commit/3d68e4e004d6c958c16c92ce8b5e4969183987ae): adds unit test
[c5fead3](https://github.com/apache/flink/pull/20205/commits/c5fead358fb70596a6363c443953a9f9ab8db6cc): removes finally block so that we don't recycle producer in the case of `RetriableException`
Manually verified the change by running a 1 node cluster with 1 JobManagers and 1 TaskManagers, running the following job for several hours without any memory issues: …
> [FLINK-28250][Connector/Kafka] Fix exactly-once Kafka Sink out of memory

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaCommitter.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaCommitterTest.java
The goal of this PR is to address a memory leak where the Kafka Producer does not get cleaned up after kafka commit is successful. This PR is a backported fix for Flink version 1.15, the original PR can be found [here](https://github.com/apache/flink/pull/20205).
[FLINK-28250][Connector/Kafka] Fix exactly-once Kafka Sink out of memory
Manually verified the change by running a 1 node cluster with 1 JobManagers and 1 TaskManagers, running the following job for several hours without any memory issues:
```
public class FlinkTest {
public void main(String[] args) throws Exception {
StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
KafkaSource<String> source = KafkaSource.<String>builder()
.setBootstrapServers("localhost:9092")
.setTopics("input") …
```
> [FLINK-28250][Connector/Kafka] Fix exactly-once Kafka Sink out of memory (backport for 1.15)

- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/ExprCodeGenerator.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala
To support `is_distinct_from` with Hive dialect.
Add the implementation for `is_distinct_from` in [ExprCodeGenerator.scala](https://github.com/apache/flink/pull/19315/files#diff-2a1762af3f6bd3f984cdf27261f217384278f302437c632f32f35a60ffa1e624).
Added test involving with is_distinct_from in [HiveDialectQueryITCase.java](https://github.com/apache/flink/pull/19315/files#diff-fb5fc4106e27e27f9968e59b643003444fd40af58aa2f147ac301009b53a47ca)#testDistinctFrom …
> [FLINK-27013][hive] Hive dialect supports is_distinct_from

- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/collector/TableFunctionCollector.java
The reset on the underlying collector of TableFunctionCollector is unnecessary and confusing. We can remove it. 
- Remove unnecessary reset on underlying collector of TableFunctionCollector
> [hotfix][table] Remove unnecessary reset on underlying collector of TableFunctionCollector

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeSubpartitionReader.java
*Remove the unused field in SortMergeSubpartitionReader*
- *Remove the unused field in SortMergeSubpartitionReader*
This change is a trivial code cleanup without any test coverage. …
> [FLINK-28550][network] Remove the unused field in SortMergeSubpartitionReader

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartition.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionTest.java
*Remove the data flush in SortMergeResultPartition because it is useless.*
- *Remove the data flush in SortMergeResultPartition because it is useless.*
This change is already covered by existing tests, such as *SortMergeResultPartitionTest*. …
> [FLINK-28514][network] Remove data flush in SortMergeResultPartition

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/util/HiveTypeUtil.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/functions/hive/conversion/HiveInspectors.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/module/hive/HiveModule.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/module/hive/udf/generic/HiveGenericUDFInternalInterval.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserTypeCheckProcFactory.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/SqlFunctionConverter.java
- flink-connectors/flink-connector-hive/src/test/resources/query-test/interval.q
To support interval type in Hive dialect
- Add data mapping in [HiveTypeUtil.java](https://github.com/apache/flink/compare/master...luoyuxia:FLINK-27996-3?expand=1#diff-52250ee5b9eac198cd2214a6915f8a8fb36b937d40eef19c4c722da0543a1f13). Hive's `INTERVAL_YEAR_MONTH` / `INTERVAL_DAY_TIME` is mapped to `DataTypes.INTERVAL(DataTypes.MONTH())` / `DataTypes.INTERVAL(DataTypes.SECOND(3))`
- Add converter in [HiveInspectors.java](https://github.com/apache/flink/compare/master...luoyuxia:FLINK-27996-3?expand=1#diff-7f266ee3e0c8c8cb156abd229fa76acefdb59a0a02360d51888a1304de02ef9b) between Hive's data and Flink's data. Hive's `HiveIntervalYearMonth`/ `HiveIntervalDayTime` should be converted to `Period`/`Duration`  , and the vice verse.
- Port Hive's `internal_interval` function …
> [FLINK-27996][hive] Hive dialect supports interval type

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/BufferHeader.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/BufferReaderWriterUtil.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/BufferReaderWriterUtilTest.java
*(This is a small code refactor which also can be reused by following PRs.  Extract header fields of Buffer into a BufferHeader class for blocking shuffle file IO)*
- *Extract header fields of Buffer into a BufferHeader class for blocking shuffle file IO*
This change is already covered by existing tests, such as *BufferReaderWriterUtilTest*.
- Dependencies (does it add or upgrade a dependency): (yes / (**no**)
- …
> [FLINK-28556][refactor] Extract header fields of Buffer into a BufferHeader class for blocking shuffle file IO

- docs/content.zh/docs/dev/datastream/fault-tolerance/serialization/types_serialization.md
- docs/content/docs/dev/datastream/fault-tolerance/serialization/types_serialization.md
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumerTest.java
- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/types/PojoTestUtils.java
- flink-test-utils-parent/flink-test-utils/src/test/java/org/apache/flink/types/PojoTestUtilsTest.java
Adds a simple utility for users to check whether their types satisfy the POJO requirements.
> [FLINK-28636][tests] Add utility for checking POJO compliance

- flink-runtime/src/main/java/org/apache/flink/runtime/state/heap/CopyOnWriteStateMap.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/heap/CopyOnWriteStateTable.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/heap/CopyOnWriteStateTableTest.java
This pull request makes the state serializer in `StateMap` could be updated when the `RegisteredKeyValueStateBackendMetaInfo` in `StateTable` has been changed.
- Also update state serializer in `CopyOnWriteStateTable#setMetaInfo`
- Added `CopyOnWriteStateTableTest#testSerializerAfterMetaInfoChanged`
> [FLINK-26853][state] Update state serializer in StateMap when metaInfo changed

- flink-runtime-web/web-dashboard/src/app/pages/job/checkpoints/job-checkpoints.component.html
This pull request fixes the problem that the checkpoint details page of the Flink Dashboard shows blank after the job triggers savepoint.
- *Correct the problem that the checkpoint size shown in the Checkpoint Tab should be read from `lastest.savepoint.checkpointed_size`. (Following figure shows the return value of the checkpoint API.)* …
> [FLINK-28577][runtime-web] Fix the null error of reading checkpointed_size in Checkpoint Tab

- docs/content.zh/docs/ops/metrics.md
- docs/content/docs/ops/metrics.md
This pull request adding more details about state latency tracking in the metric documentation.
- Added "State Access Latency" in metric.md
This change is a trivial work about documentation without any test coverage.
> [FLINK-24787][docs] Add more details of state latency tracking documentation

- docs/content.zh/docs/dev/table/types.md
[FLINK-27292](https://issues.apache.org/jira/browse/FLINK-27292)
Translate the "Data Type Extraction" section of "Data Types" to Chinese.
Translate the "Data Type Extraction" section of "Data Types" to Chinese, the doc file is located in
'docs/content.zh/docs/dev/table/types.md'
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / …
> [FLINK-27292][docs-zh] Translate the "Data Type Extraction" section of "Data Types" to Chinese

- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java
Fix unstable test for HiveDialectQueryITCase#testInsertDirectory
Wait the inserting finish before querying the table.
- If yes, how is the feature documented?  N/A
> [FLINK-28795][hive] Fix unstable test for HiveDialectQueryITCase#testInsertDirectory

- flink-filesystems/flink-oss-fs-hadoop/pom.xml
- flink-filesystems/flink-oss-fs-hadoop/src/main/resources/META-INF/NOTICE
Upgrade the Aliyun OSS SDK version to 3.13.2 
Upgrade the Aliyun OSS SDK version to 3.13.2 and the associated dependencies to the right versions.
This change does not include any code changes, but we should run regression tests. In order to run tests, someone need to have his own Aliyun access key id and access key secret. Then, set environment variables below：
`export ARTIFACTS_OSS_ENDPOINT=<Aliyun OSS endpoint to connect to>`
`export ARTIFACTS_OSS_BUCKET=<Your bucket>`
`export ARTIFACTS_OSS_ACCESS_KEY=<Your access key id>`
`export ARTIFACTS_OSS_SECRET_KEY=<Your access secret>`
These tests are skipped by default.
- The …
> [FLINK-28801][fs] Bump OSS SDK to 3.13.2

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParser.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectITCase.java
To support variable substitution for sql statement while using Hive dialect.
Substitute the variable with actual value in sql statement while using Hive dialect before really parse it.
Additional test in [HiveDialectITCase.java](https://github.com/apache/flink/compare/master...luoyuxia:FLINK-26371?expand=1#diff-748a9fa63f15b3bd3ea5426a5b42179cadee77ecf3359c83f846aedb27d96871)#testStatementVariableSubstitution …
> [FLINK-26371][hive] Support variable substitution for sql statement while using Hive dialect

- docs/content.zh/docs/ops/state/state_backends.md
- docs/content/docs/ops/state/state_backends.md
This pull request updates the documentation about changing changelog from enabling to disabling.
- Update `state_backends.md`
This change is a documentation update without any test coverage.
> [FLINK-23252][state/changelog] [docs] Update the docs about disabling changelog

- flink-core/src/main/java/org/apache/flink/api/common/functions/util/PrintSinkOutputWriter.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/sink/PrintSink.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/functions/PrintSinkTest.java
Adds an updated version of the PrintSinkFunction for the new sink interfaces.
> [FLINK-28865] Add new PrintSink 

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/ChangelogRecoveryITCaseBase.java
This pull request fixes unstable ChangelogRecoverySwitchStateBackendITCase#testSwitchFromEnablingToDisablingWithRescalingOut
- Modified ChangelogRecoveryITCaseBase#getAllStateHandleId
This change is a trivial rework  without any test coverage.
> [FLINK-28898][state/changelog] Fix unstable ChangelogRecoverySwitchStateBackendITCase#testSwitchFromEnablingToDisablingWithRescalingOut

- flink-core/src/main/java/org/apache/flink/configuration/ConfigOptions.java
https://issues.apache.org/jira/browse/FLINK-28783
> [FLINK-28783] [flink-core] Class ConfigOptions's example code have error.

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/RescaleCheckpointManuallyITCase.java
Refactor `RescaleCheckpointManuallyITCase`.
- Modify `NotifyingDefiniteKeySource` to wait for checkpoints to complete.
- Make job fail artificially, to retain completed checkpoint.
- Modify the logic of emitting elements in `SubtaskIndexFlatMapper`.
This change is already covered by existing tests, such as  `RescaleCheckpointManuallyITCase`.
- …
> [FLINK-28626][tests]Fix unstable RescaleCheckpointManuallyITCase

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserCalcitePlanner.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserDMLHelper.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserRexNodeConverter.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserSqlFunctionConverter.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java
To make Hive dialect support comparing boolean type with numeric/string type.
-  When it invovles with comparsion betwen boolean type and numeric/string type, delegate it to Hive's udf.
Added a  specifc sql statement in [HiveDialectQueryITCase.java](https://github.com/apache/flink/compare/master...luoyuxia:compare_boolean_int?expand=1#diff-fb5fc4106e27e27f9968e59b643003444fd40af58aa2f147ac301009b53a47ca)[#testAdditionalQueries](https://github.com/apache/flink/pull/19182/files#diff-fb5fc4106e27e27f9968e59b643003444fd40af58aa2f147ac301009b53a47caR159) to verify this fix. Without this fix, the test will fail.
- The runtime …
> [FLINK-26771][Hive] Fix incomparable exception between boolean type and numeric type in Hive dialect

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/endpoint/hive/util/ThriftObjectConversions.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/endpoint/hive/util/ThriftObjectConversionsTest.java
- tools/azure-pipelines/build-apache-repo.yml
To fix 'Table.INDEX_TABLE' not found in the Hive3 error (It's because hive3 removed this table type).
- fix reference of enum constants of TableType to literal string.
This change is already covered by existing tests, such as `ThriftObjectConversionsTest#testHiveTableTypeToFlinkTableKind`. …
> [FLINK-28855][hive] Fix 'Table.INDEX_TABLE' not found in the Hive3

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/client/HiveMetastoreClientWrapper.java
To fix the issue of opening HiveCatalog for Hive3
- Lazy initialize `Hive` insteading of initialize it while creating.
Verify it in local Hive3 env. …
> [FLINK-28913][hive] Fix fail to open HiveCatalog when it's for hive3

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveASTParseUtils.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java
To fix  assert exception when specific join hint in union statement
When encounter a query hint token,  skip it directly just like what [Hive does](https://github.com/apache/hive/blob/master/ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java#L408). 
Added sql `select /*+ mapjoin(dest) */ foo.x from foo join dest on foo.x = dest.x union all select /*+ mapjoin(dest) */ foo.x from foo join dest on foo.y = dest.y` which will introuce the exception reported in the jira if without this fix. …
> [FLINK-27386][hive] Fix assert exception when specific join hint in union statement

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/module/hive/HiveModule.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/module/hive/udf/generic/HiveGenericUDFToDecimal.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserDMLHelper.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserRexNodeConverter.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserUtils.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/module/hive/HiveModuleTest.java
To fix the exception for casting timestamp to decimal in Hive dialect
- Add a custome udf `flink_hive_to_decimal ` to convert other datatypes include timestamp to decimal
- When it's for insert timestamp to decimal, make it to be a `RexCall` to call function `flink_hive_to_decimal`
Added test in `HiveDialectQueryITCase#testCastTimeStampToDecimal` …
> [FLINK-27015][hive] Fix exception for casting timestamp to decimal in Hive dialect

- docs/data/sql_functions.yml
- docs/data/sql_functions_zh.yml
*fix incorrect description of function dayofmonth*
> [FLINK-28780][docs] fix incorrect description of function dayofmonth.

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParser.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java
To fix non-multi insert statement fall into multi insert logic in Hive dialect
-  Make the check for multi dest insert more strict
Added query `with cte as (select * from src) select * from cte` which will fail for it will be mistaken as multi dest insert without this fix.
- Does this …
> [FLINK-28956][hive] Fix non-multi insert statement fall into multi insert logic in Hive dialect

- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
- Fix the task class typo.
- Fix the task class typo.
> [hotfix][flink-runtime] Fix the task class typo.

- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarPartitionSplitReaderTestBase.java
This is a backport PR for https://github.com/apache/flink/pull/20567.
> [BK-1.14][FLINK-27917][Connector/Pulsar] Fix message assert error in PulsarUnorderedPartitionSplitReaderTest

- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarPartitionSplitReaderTestBase.java
This is a backport PR for https://github.com/apache/flink/pull/20567.
> [BK-1.15][FLINK-27917][Connector/Pulsar] Fix message assert error in PulsarUnorderedPartitionSplitReaderTest

- docs/content.zh/docs/dev/datastream/sources.md
- docs/content/docs/dev/datastream/sources.md
- flink-core/src/main/java/org/apache/flink/api/connector/source/ReaderOutput.java
- flink-core/src/main/java/org/apache/flink/api/connector/source/SourceReader.java
- flink-core/src/main/java/org/apache/flink/api/connector/source/SourceReaderContext.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java
* Review and polish of FLIP-27 related documentation and website.
* No major rewriting, minor English grammar fixes.
* Checking that code samples are up-to-date with current API (English and Chinese). …
> [FLINK-29036][docs] Review and update sources.md and javadoc

- docs/content.zh/docs/deployment/resource-providers/standalone/docker.md
- docs/content/docs/deployment/resource-providers/standalone/docker.md
- docs/content/docs/deployment/resource-providers/standalone/overview.md
Does not include modifications to the chinese `overview.md` because it's seriously out-of-sync.
> [FLINK-28841][scripts][docs] Document dynamic properties support

- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/PeriodicMaterializationManager.java
- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/streaming/util/TestStreamEnvironment.java
> [BP-1.15][FLINK-28976][state] Don't add extra delay to the 1st materialization

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStore.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStoreTest.java
> [BP-1.15][FLINK-28265][k8s] Make KubernetesStateHandleStore#addEntry idempotent

- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStoreTest.java
Fix the unstable k8s test `testAddAndLockShouldNotThrowAlreadyExistExceptionWithSameContents`
* Already covered by the existing UT …
> [FLINK-29105][k8s] Fix the unstable k8s test 'testAddAndLockShouldNotThrowAlreadyExistExceptionWithSameContents'

- flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/header/operation/CancelOperationHeaders.java
- flink-table/flink-sql-gateway/src/test/resources/sql_gateway_rest_api_v1.snapshot
*Fix the failed test by updating the test resource. I also modify the CancelOprationHeaders. It should be POST rather than PUT because user can only cancel operation once if users send multiple cancel opertion request.*
> [FLINK-29121][sql-gateway] Fix failed SqlGatewayRestAPIStabilityTest

- flink-formats/flink-protobuf/pom.xml
This issue is similar to #16738 and we should using maven protobuf plugin will encount problem in a proxy networking on flink-protobuf module too.
- *use protocArtifact instead of protocVersion* …
> [FLINK-29062][build] Fix protobuf plugin proxy issue on flink-protobuf module.

- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/schema/PulsarSchema.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/common/schema/PulsarSchemaTest.java
This is a backport PR for https://github.com/apache/flink/pull/20698.
> [BK-1.15][FLINK-28609][Connector/Pulsar] PulsarSchema didn't get properly serialized

- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/schema/PulsarSchema.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/common/schema/PulsarSchemaTest.java
This is a backport PR for https://github.com/apache/flink/pull/20698.
> [BK-1.14][FLINK-28609][Connector/Pulsar] PulsarSchema didn't get properly serialized

- docs/content.zh/docs/dev/table/sourcesSinks.md
[FLINK-28121]Translate "Extension Points" and "Full Stack Example" in  "User-defined Sources & Sinks" page
*(or)*
*(or)*
*(example:)*
- *Added test that validates that TaskInfo is …
> [FLINK-28121][docs-zh]Translate "Extension Points" and "Full Stack Example" in  "User-defined Sources & Sinks" page

- docs/content/docs/connectors/datastream/overview.md
FileSystem is also a source, but the overview list indicates that it can only be used as a sink.
Update overview.md to indicate that FileSystem can also be used as a source.
> [hotfix][docs] typo fix: FileSystem is also a source

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/endpoint/hive/HiveServer2Endpoint.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/endpoint/hive/util/HiveJdbcParameterUtils.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveSetProcessor.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/endpoint/hive/HiveServer2EndpointITCase.java
To fix HiveServer2 Endpoint can not set variable correctly.
-  Call method `HiveSetProcessor#setVariable` to set variable.
UT in `HiveServer2EndpointITCase#testOpenSessionWithConfig`. …
> [FLINK-28938][hive] Fix HiveServer2 Endpoint can not set variable correctly

- docs/content/docs/internals/task_lifecycle.md
> [hotfix] [docs] Fix typo in internals/task_lifecycle

- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/InternalCacheMetricGroup.java
- flink-table/flink-table-common/src/test/java/org/apache/flink/table/connector/source/lookup/cache/DefaultLookupCacheTest.java
- flink-table/flink-table-common/src/test/java/org/apache/flink/table/connector/source/lookup/cache/InterceptingCacheMetricGroup.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestValuesTableFactory.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/CachingLookupFunction.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/fullcache/CacheLoader.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/fullcache/LookupFullCache.java
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/functions/table/fullcache/LookupFullCacheTest.java
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/functions/table/fullcache/TestCacheLoader.java
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/functions/table/fullcache/inputformat/FullCacheTestInputFormat.java
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/functions/table/fullcache/inputformat/InputFormatCacheLoaderTest.java
This pull request introduces more tests for recently added feature with full caching lookup and adds missing metrics
- Added metrics `hitCounter` and `missCounter`
- Fixed concurrent metrics creation 
- Added unit tests for `LookupFullCache` and `InputFormatCacheLoader`
- `LookupFullCacheTest`
- `InputFormatCacheLoaderTest` …
> [FLINK-28948][table] Increase test coverage for lookup full caching + fix metrics

- flink-runtime-web/web-dashboard/src/app/pages/job/overview/subtasks/job-overview-drawer-subtasks.component.html
FLINK-29180
Reorder the tabs in subtasks for better usability.
Show subtask metrics as default tab in vertex detail.
> [FLINK-29180] fix: show subtask metrics as default in vertex detail

- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/ProjectSnapshotTransposeRule.java
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/FlinkBatchRuleSets.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/FlinkStreamRuleSets.scala
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestValuesTableFactory.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/rules/logical/ProjectSnapshotTransposeRuleTest.java
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/join/LookupJoinTest.xml
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/LookupJoinJsonPlanTest_jsonplan/testJoinTemporalTableWithProjectionPushDown.out
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/ProjectSnapshotTransposeRuleTest.xml
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/join/TemporalJoinTest.xml
> [FLINK-29138][table-planner] fix project can not be pushed into lookup source

- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/ProjectSnapshotTransposeRule.java
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/FlinkBatchRuleSets.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/FlinkStreamRuleSets.scala
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestValuesTableFactory.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/rules/logical/ProjectSnapshotTransposeRuleTest.java
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/join/LookupJoinTest.xml
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/LookupJoinJsonPlanTest_jsonplan/testJoinTemporalTableWithProjectionPushDown.out
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/ProjectSnapshotTransposeRuleTest.xml
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/join/TemporalJoinTest.xml
> [BP-1.14][FLINK-29138][table-planner] fix project can not be pushed into lookup source

- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/aggfunctions/SumAggFunction.java
*fix redundant computations in SumAggFunction*
> [FLINK-29182][table] fix redundant computations in SumAggFunction.

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserRexNodeConverter.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserSqlFunctionConverter.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java
To fix the divide by zero exception in Hive dialect
when the operand is `/`, make it call Hive's `GenericUDFOPDivide` for better consistent to Hive in case of dividing by zero.
Add sql `select 1 / 0` for dividing by zero.
> [FLINK-27017][hive] Fix divide by zero exception in Hive dialect

- docs/content.zh/docs/dev/table/sql/create.md
- docs/content/docs/dev/table/sql/create.md
Add document for CREATE FUNCTIOn USING JAR feature
Add document for CREATE FUNCTIOn USING JAR feature
> [FLINK-29022][docs][table] Add document for CREATE FUNCTIOn USING JAR feature

- flink-clients/src/main/java/org/apache/flink/client/FlinkPipelineTranslationUtil.java
- flink-clients/src/main/java/org/apache/flink/client/StreamGraphTranslator.java
- flink-clients/src/main/java/org/apache/flink/client/cli/CliFrontend.java
- flink-clients/src/main/java/org/apache/flink/client/deployment/application/executors/EmbeddedExecutor.java
- flink-clients/src/main/java/org/apache/flink/client/deployment/executors/AbstractJobClusterExecutor.java
- flink-clients/src/main/java/org/apache/flink/client/deployment/executors/AbstractSessionClusterExecutor.java
- flink-clients/src/main/java/org/apache/flink/client/deployment/executors/LocalExecutor.java
- flink-clients/src/main/java/org/apache/flink/client/deployment/executors/PipelineExecutorUtils.java
- flink-clients/src/test/java/org/apache/flink/client/cli/CliFrontendPackageProgramTest.java
- flink-clients/src/test/java/org/apache/flink/client/program/ClientTest.java
- flink-clients/src/test/java/org/apache/flink/client/program/DefaultPackagedProgramRetrieverTest.java
- flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/codegen/UsingRemoteJarITCase.java
- flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/resources/scalar_udf_e2e.sql
- flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/runtime/OperatorIDGeneratorTest.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraph.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGenerator.java
- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/test/util/MiniClusterPipelineExecutorServiceLoader.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/ChangelogRecoveryITCaseBase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/RescaleCheckpointManuallyITCase.java
This is a cherry-pick back to release-1.16 branch
> [FLINK-28897][runtime] Fix bug of failed to generate JobGraph when using UDF and enable checkpoint

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internals/KafkaConsumerThread.java
This pull request fixes an unstable case after upgrading Kafka clients version to 3.2.1, that KafkaConsumer#commitAsync might throw WakeupException
- Retry KafkaConsumer#commitAsync on WakeupException in KafkaConsumerThread
This change is already covered by existing FlinkKafkaConsumer tests
- The S3 file system connector: (yes …
> [FLINK-29153][connector/kafka] Retry KafkaConsumer#commitAsync on WakeupException in KafkaConsumerThread

- flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaRpcService.java
- flink-rpc/flink-rpc-core/src/main/java/org/apache/flink/runtime/rpc/RpcService.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rpc/TestingRpcService.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/coordination/OperatorEventSendingCheckpointITCase.java
> [FLINK-29248][rpc] Remove RpcService#fenceRpcServer

- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/runner/JobDispatcherLeaderProcessFactoryFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/runner/SessionDispatcherLeaderProcess.java
BP of https://github.com/apache/flink/pull/20787 on release-1.15
> [BP-1.15][FLINK-29223][coordination] Add missing output info for jobs already reached terminal state

- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/runner/JobDispatcherLeaderProcessFactoryFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/runner/SessionDispatcherLeaderProcess.java
BP of https://github.com/apache/flink/pull/20787 on release-1.16
> [BP-1.16][FLINK-29223][coordination] Add missing output info for jobs already reached terminal state

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internals/KafkaConsumerThread.java
Unchanged backport of #20764 on release-1.16
> [BP-1.16][FLINK-29153][connector/kafka] Retry KafkaConsumer#commitAsync on WakeupException in KafkaConsumerThread

- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/FileSystemJobResultStoreFileOperationsTest.java
*rename FileSystemJobResultStoreTestInternal to FileSystemJobResultStoreFileOperationsTest*
- *rename FileSystemJobResultStoreTestInternal to FileSystemJobResultStoreFileOperationsTest for naming convention and surefire plugin to run the test*
This change changed one test class for naming convention and can be verified as follows:
- *mvn clean verify* …
> [FLINK-28902][tests] rename FileSystemJobResultStoreTestInternal to FileSystemJobResultStoreFileOperationsTest

- docs/content.zh/docs/dev/table/catalogs.md
- docs/content.zh/docs/dev/table/sourcesSinks.md
- docs/content.zh/docs/dev/table/sql/create.md
- docs/content.zh/docs/dev/table/sql/jar.md
- docs/content/docs/dev/table/catalogs.md
- docs/content/docs/dev/table/sourcesSinks.md
- docs/content/docs/dev/table/sql/jar.md
Updating Jar statement document
Updating Jar statement document
> [FLINK-29023][docs][table] Updating Jar statement document

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParser.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserDDLSemanticAnalyzer.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectITCase.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/FunctionCatalog.java
To fix class not found exception for creating temporary function using jar with Hive dialect
-  If it's for creating temporary function, first try to register the resources.
Modified test in `HiveDialectITCase#testCreateFunctionUsingJar`. …
> [FLINK-29185][hive] fix class not found exception for creating temporary function using jar with Hive dialect

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/context/SessionContext.java
- flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/context/SessionContext.java
To optimize the error message in Flink SQL Client when try to switch to Hive dialect.
when user want  to hive dialect and throw a validation exception in sql client and gateway, note user to first swap libs for hive dialect in error message.
Verify locally, the error in Flink SQL Client is likes:
Using Beeline to connect to Flink's HiveServer2 Endpoint is likes: …
> [FLINK-29045][sqlclient] Optimize error message in Flink SQL Client when try to switch to Hive dialect

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveOperationExecutor.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParser.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveSetProcessor.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserDDLSemanticAnalyzer.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/context/SessionContext.java
- flink-table/flink-sql-client/src/test/resources/sql/set.q
- flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/context/SessionContext.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/FunctionCatalog.java
Backport commits to release-1.16
> [BP-1.16][FLINK-29191][FLINK-29222][FLINK-29045][FLINK-29185][hive] Backport commits to release-1.16

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/endpoint/hive/HiveServer2Endpoint.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/endpoint/hive/HiveServer2Schemas.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/endpoint/hive/util/ThriftObjectConversions.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/endpoint/hive/HiveServer2EndpointITCase.java
- flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/SqlGatewayServiceImpl.java
> [FLINK-29228][hive] Align the schema of the HiveServer2 getMetadata with JDBC 

- docs/content.zh/docs/connectors/table/hbase.md
- docs/content.zh/docs/connectors/table/jdbc.md
- docs/content/docs/connectors/table/hbase.md
- docs/content/docs/connectors/table/jdbc.md
> [BP-1.16][FLINK-29389][docs] Update documentation of JDBC and HBase lookup table for new caching options

- flink-dist/src/main/flink-bin/bin/jobmanager.sh
- flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/flink/FlinkDistribution.java
- flink-end-to-end-tests/flink-end-to-end-tests-common/src/test/java/org/apache/flink/dist/DynamicParameterITCase.java
- flink-end-to-end-tests/flink-end-to-end-tests-common/src/test/resources/log4j2-test.properties
- flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/ClusterEntrypoint.java
- tools/ci/log4j.properties
Backport of #20474, needed for backporting #20710
> [backport][FLINK-28733][scripts] jobmanager.sh supports dynamic parameters

- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/SavepointReader.java
Deduplicate code to ease further changes down the line.
> [FLINK-28453][state-processor] Deduplicate code

- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/jsonplan/JsonPlanGenerator.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/CreatingExecutionGraph.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StateTrackingMockExecutionGraph.java
- flink-tests/src/test/java/org/apache/flink/test/scheduling/ReactiveModeITCase.java
> [FLINK-22243[bp-1.16] Reactive Mode parallelism changes are not shown in the Web UI

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/proxy/KinesisProxy.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/proxy/KinesisProxyTest.java
This PR addresses [FLINK-29476](https://issues.apache.org/jira/browse/FLINK-29476).
A new test is added.
> [FLINK-29476][connector][kinesis] Retry connection termination with EOFException

- tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/licensecheck/NoticeFileChecker.java
- tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/utils/deploy/DeployParser.java
- tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/utils/notice/NoticeContents.java
- tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/utils/notice/NoticeParser.java
- tools/ci/flink-ci-tools/src/test/java/org/apache/flink/tools/ci/licensecheck/NoticeFileCheckerTest.java
- tools/ci/flink-ci-tools/src/test/java/org/apache/flink/tools/ci/utils/deploy/DeployParserTest.java
- tools/ci/flink-ci-tools/src/test/java/org/apache/flink/tools/ci/utils/notice/NoticeParserTest.java
- tools/maven/suppressions.xml
Adds tests for various parts of the NoticeFileChecker. This required a few refactorings.
> [FLINK-29510] Add tests for NoticeFileChecker

- docs/data/sql_functions.yml
- docs/data/sql_functions_zh.yml
- Add the `dayofweek` function description.
- Add the `dayofweek` function description.
- Dependencies (does it add or upgrade a dependency): (`no`)
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (`no`)
- The serializers: (`no`)
- The runtime per-record code paths (performance sensitive): (`no`)
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (`no`)
- The S3 file system connector: (`no`)
- Does this pull request introduce a new feature? (`no`)
- If yes, how is the feature documented? (`not applicable`)
> [hotfix][table] Add the `dayofweek` function description.

- docs/content.zh/docs/deployment/finegrained_resource.md
- docs/content.zh/docs/deployment/speculative_execution.md
- docs/content.zh/docs/learn-flink/datastream_api.md
- docs/content/docs/dev/python/datastream_tutorial.md
- Fixed some typos of docs.
- Fixed some typos of docs. …
> [hotfix][docs]Fixed some typos of docs.

- docs/content.zh/docs/dev/table/sql/create.md
- docs/content/docs/dev/table/sql/create.md
cp ctas document from master to release-1.16
> [FLINK-29020][docs] Add document for CREATE TABLE AS SELECT

- docs/layouts/shortcodes/generated/rest_v1_dispatcher.html
- docs/layouts/shortcodes/generated/rest_v1_sql_gateway.html
- flink-docs/src/main/java/org/apache/flink/docs/rest/RestAPIDocGenerator.java
Removes leading/trailing empty lines in request/response blocks.
Before:
After:
> [FLINK-29568][rest][docs] Remove whitespace 

- docs/content.zh/docs/deployment/elastic_scaling.md
- docs/content/docs/deployment/elastic_scaling.md
Update docuemntation to the current state
> [FLINK-22243] Remove adaptive scheduler Web UI limitation from docs

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/read/HivePartitionFetcherContextBase.java
This pull request solve the problem that the latest data cannot be read under the createtime configuration in the hive dimension table.
solve the problem that the latest data cannot be read under the createtime configuration in the hive dimension table
no …
> [FLINK-27384][hive] Fix the modified partitions are missed in temporal table with create-time mode

- docs/content.zh/docs/connectors/table/hive/overview.md
- docs/content.zh/docs/dev/table/hive-compatibility/hive-dialect/alter.md
- docs/content.zh/docs/dev/table/hive-compatibility/hive-dialect/create.md
- docs/content.zh/docs/dev/table/hive-compatibility/hive-dialect/drop.md
- docs/content.zh/docs/dev/table/hive-compatibility/hive-dialect/insert.md
- docs/content.zh/docs/dev/table/hive-compatibility/hive-dialect/overview.md
- docs/content.zh/docs/dev/table/hive-compatibility/hive-dialect/queries/join.md
- docs/content.zh/docs/dev/table/hive-compatibility/hive-dialect/queries/lateral-view.md
- docs/content.zh/docs/dev/table/hive-compatibility/hive-dialect/queries/sub-queries.md
- docs/content.zh/docs/dev/table/hive-compatibility/hive-dialect/queries/transform.md
- docs/content/docs/connectors/table/hive/overview.md
- docs/content/docs/dev/table/hive-compatibility/hive-dialect/alter.md
- docs/content/docs/dev/table/hive-compatibility/hive-dialect/create.md
- docs/content/docs/dev/table/hive-compatibility/hive-dialect/drop.md
- docs/content/docs/dev/table/hive-compatibility/hive-dialect/insert.md
- docs/content/docs/dev/table/hive-compatibility/hive-dialect/overview.md
- docs/content/docs/dev/table/hive-compatibility/hive-dialect/queries/join.md
- docs/content/docs/dev/table/hive-compatibility/hive-dialect/queries/lateral-view.md
- docs/content/docs/dev/table/hive-compatibility/hive-dialect/queries/sub-queries.md
- docs/content/docs/dev/table/hive-compatibility/hive-dialect/queries/transform.md
Add a section for moving planner jar in Hive dependencies page, and fix some typos in the docs.
-  Add a section for moving planner jar in Hive dependencies page
- Fix some typos in docs releated to Hive dialect
N/A
- If …
> [FLINK-29350][hive] Add a section for moving planner jar in Hive dependencies page

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParser.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserCalcitePlanner.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserDMLHelper.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserQBMetaData.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserUtils.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserBaseSemanticAnalyzer.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserQB.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserQBParseInfo.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserSemanticAnalyzer.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserUnparseTranslator.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/FromClauseASTParser.g
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserDDLSemanticAnalyzer.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserLoadSemanticAnalyzer.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java
> [FLINK-29337][hive] Fix fail to query non-hive table in Hive dialect

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGenerator.java
The serialization was parallelized in FLINK-26675. Adding the OperatorCoordinator instances concurrently occasionally caused problems with instances being dropped.
This is a 1.16 backport of PR #21019 . The parent PR was approved. No conflicts appeared during backport.
> [BP-1.16][FLINK-29576][runtime] Collects serialized OperatorCoordinators before adding them to JobVertex

- docs/content/docs/dev/datastream/operators/asyncio.md
Correct grammar in documentation
- Dependencies (does it add or upgrade a dependency): NO
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: NO
- The serializers: NO
- The runtime per-record code paths (performance sensitive): NO
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: NO
- The S3 file system connector: NO
- Does this pull request introduce a new feature? NO
> [hotfix] [docs] correct grammar

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorSerializer.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperatorTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorSerializerTest.java
Before this change during recovery for the CommitableCollector we
initialized the SubtaskCommittableManager always with the initial
checkpoint id (1) but the holding CheckpointCommittable with the
checkpoint id in state. This could lead to that the emitted
CommittableWithLinages update SubtaskCommittableManagers that they do
not belong to cause "Unknown subtask for <id>" failures.
Initialize the SubtaskCommittableManagers with the recovered checkpointId.
- Added a new test to the CommittableCollectorSerializerTest verifying that the persisted checkpointId is used to create the SubtaskCommittableManagers
- Adapted the CommitterOperatorTest#restore to also ensure that the emitted committables align with the emitted committable summary …
> [FLINK-29512][streaming] Align the checkpointId of recovered CommittableWithLinages with the CommittableSummary

- README.md
- docs/content/_index.md
- flink-connectors/flink-connector-hbase-base/src/main/java/org/apache/flink/connector/hbase/util/HBaseTableSchema.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSourceBuilder.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/cursor/StartCursor.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/cursor/StopCursor.java
- flink-core/src/main/java/org/apache/flink/api/connector/source/Source.java
- flink-core/src/main/java/org/apache/flink/api/connector/source/SplitEnumerator.java
While learning and reviewing the code around Flink sources, I collected some typos and minor English grammar fixes.
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`:  **no**
- The serializers:  **no**
- The runtime per-record code paths (performance sensitive):  **no**
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper:  **no**
- …
> [hotfix][docs] Fix minor grammar and spelling mistakes

- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/PartitionLoader.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserTypeCheckProcFactory.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java
> [FLINK-29590][hive] Fix literal issue in Hive dialect

- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionReadSchedulerTest.java
*When the allReaders queue is empty, creating a new reader will trigger the IO Scheduling thread to read data. If the data reading is completed, the running state will be set to false. If the state is asserted at this time, the test will fail.*
- *Using ManuallyTriggeredScheduledExecutorService for io scheduling task to avoid race condition. * …
> [FLINK-29641] SortMergeResultPartitionReadSchedulerTest#testCreateSubpartitionReader is not stable.

- flink-connectors/flink-connector-pulsar/pom.xml
> [BP-1.16][FLINK-28960][Connector/Pulsar] Add jaxb-api back to pulsar-client-all dependencies

- flink-connectors/flink-connector-pulsar/pom.xml
> [BP-1.15][FLINK-28960][Connector/Pulsar] Add jaxb-api back to pulsar-client-all dependencies

- flink-connectors/flink-connector-pulsar/pom.xml
> [BP-1.14][FLINK-28960][Connector/Pulsar] Add jaxb-api back to pulsar-client-all dependencies

- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/cursor/MessageIdUtils.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/cursor/start/MessageIdStartCursor.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/cursor/stop/MessageIdStopCursor.java
> [BP-1.15][FLINK-29613][Connector/Pulsar] Fix wrong batch size assertion

- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/cursor/MessageIdUtils.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/cursor/start/MessageIdStartCursor.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/cursor/stop/MessageIdStopCursor.java
> [BP-1.16][FLINK-29613][Connector/Pulsar] Fix wrong batch size assertion

- flink-connectors/flink-sql-connector-elasticsearch6/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-elasticsearch7/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-kinesis/src/main/resources/META-INF/NOTICE
Proposal for the backport of [FLINK-29638] to 1.16
> [BP-1.16][FLINK-29638] Update NOTICE for elastic and kinesis connectors

- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/SavepointWriter.java
The reading/creation of the Savepoint metadata was identical between the method pairs.
> [FLINK-29659][state-processor] Deduplicate code

- docs/content.zh/docs/dev/datastream/operators/joining.md
- docs/content/docs/dev/datastream/operators/joining.md
> [hotfix] Fix joining.md typo

- docs/content.zh/docs/dev/datastream/operators/joining.md
- docs/content/docs/dev/datastream/operators/joining.md
> [hotfix][backport-1.16] Fix joining.md docs typo 

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CompletedCheckpointStore.java
Improve logging in CompletedCheckpointStore
This change is a trivial rework without any (new) test coverage.
> [FLINK-29157][doc] Clarify the contract between CompletedCheckpointStore and SharedStateRegistry

- flink-core/src/test/java/org/apache/flink/core/fs/FileSystemBehaviorTestSuite.java
- flink-core/src/test/java/org/apache/flink/core/fs/local/LocalFileSystemBehaviorTest.java
- flink-filesystems/flink-azure-fs-hadoop/src/test/java/org/apache/flink/fs/azurefs/AzureFileSystemBehaviorITCase.java
- flink-filesystems/flink-hadoop-fs/src/test/java/org/apache/flink/runtime/fs/hdfs/HadoopLocalFileSystemBehaviorTest.java
- flink-filesystems/flink-hadoop-fs/src/test/java/org/apache/flink/runtime/fs/hdfs/HdfsBehaviorTest.java
- flink-filesystems/flink-oss-fs-hadoop/src/test/java/org/apache/flink/fs/osshadoop/HadoopOSSFileSystemBehaviorITCase.java
- flink-filesystems/flink-s3-fs-hadoop/src/test/java/org/apache/flink/fs/s3hadoop/HadoopS3FileSystemBehaviorITCase.java
- flink-filesystems/flink-s3-fs-presto/src/test/java/org/apache/flink/fs/s3presto/PrestoS3FileSystemBehaviorITCase.java
The FileSystemBehaviorTestSuite in flink-core has an implementation in most modules in flink-filesystems.  All of these implementations (one for each filesystem) should be migrated together.
For the tests that can be locally, I verified that no tests were deleted.  Some of the tests have changed their names. 
Especially note the technique of the inner class in `AzureFileSystemBehaviorITCase`: The https scheme tests are always performed, but the static inner class should repeat the tests with http support only if the best effort check succeeds. …
> [FLINK-28542][tests][JUnit5 Migration] FileSystemBehaviorTestSuite

- docs/content.zh/docs/dev/table/data_stream_api.md
- docs/content/docs/dev/table/data_stream_api.md
Refine code examples in data_stream_api
* Fix variable names to make code example cleaer
* Make it clear different examples in the same code block
* Add necessary package import so code example is runnable
* Update both zh and en docs …
> [hotfix][doc] Refine code examples in data_stream_api

- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableSourceStatisticsReportTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/module/hive/HiveModuleTest.java
Fix the test fest failure for hive3
- update the expected build-in function number as hive3.1.3 add a new function [HIVE-22241](https://issues.apache.org/jira/browse/HIVE-22241)
- delete the hack test check logic for hive3 since hive3 upgrade orc version [HIVE-24316](https://issues.apache.org/jira/browse/HIVE-24316) which should fix the issue of orc.
Existing test.
The success test in Hive3 is in https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=42731&view=results
- …
> [FLINK-29831][hive] fix test failure for hive3

- flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/RetryOnExceptionTest.java
- flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/RetryOnFailureTest.java
1.16 backport PR for change included in parent PR #20805
> [BP-1.16][FLINK-27740][test] Revert JUnit5 migration for RetryOnFailureTest

- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/extensions/retry/strategy/RetryOnExceptionStrategy.java
- flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/RetryOnExceptionExtensionTest.java
- flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/RetryOnFailureExtensionTest.java
1.16 backport PR for parent PR #20805
> [BP-1.16][FLINK-29198][test] Fail after maximum RetryOnException

- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/extensions/retry/strategy/RetryOnExceptionStrategy.java
- flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/RetryOnExceptionExtensionTest.java
- flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/RetryOnFailureExtensionTest.java
1.15 backport PR for parent PR #20805
> [BP-1.15][FLINK-29198][test] Fail after maximum RetryOnException

- docs/content.zh/docs/dev/table/sql/queries/joins.md
- docs/content/docs/dev/table/sql/queries/joins.md
update example code and description of event time temporal join.
- add `INTERVAL` subtraction into the example code
- update the description
This change is a trivial doc update without any test coverage.
> [hotfix][doc] add `INTERVAL` subtraction into the example and update the related description

- docs/content.zh/docs/connectors/table/kafka.md
- docs/content/docs/connectors/table/kafka.md
We used some HTML tag in the documentation which does not interpret Markdown format nicely. This fixes this by replacing with Markdown tags.
We used some HTML tag in the documentation which does not interpret Markdown format nicely. This fixes this by replacing with Markdown tags. …
> [FLINK-29920][doc] Minor reformat Kafka connector documentation

- docs/layouts/shortcodes/connector_artifact.html
> [FLINK-29979][docs] Only render connector artifact for stable releases

- docs/content.zh/docs/ops/metrics.md
- docs/content/docs/ops/metrics.md
Fix wrong Scala syntax
Fix wrong scala syntax in a code snippet.
- Fix wrong scala syntax in a code snippet.
> [docs][hotfix] Fix wrong scala syntax in a code snippet
