apache/flink

docs/content/docs/libs/cep.md
*(or)*
*(or)*
*(example:)*
- *Extended …
=> [hotfix][docs] libs cep Remove redundant sentences

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/sort/BytesKeyNormalizationUtil.java
The MIN value should be -128 and max value is 127
Change the Byte min and max values in the description
=> [hotfix] [FLINK-28341] [streaming-java] Change the MIN and MAX value for Byte data type

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveLookupTableSource.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveTableSource.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveLookupJoinITCase.java
To fix the lookup join fail with Hive table as lookup table source
Implement `copy` method in `HiveLookupTableSource`.
Added test `HiveLookupJoinITCase` …
=> [FLINK-29992][hive] fix lookup join fail with Hive table as lookup table source

docs/content.zh/release-notes/flink-1.16.md, docs/content/release-notes/flink-1.16.md
* Mention system metrics dependencies update in release note.
=> [FLINK-30016][docs] Mention system metrics dependencies update

azure-pipelines.yml, flink-yarn/pom.xml, flink-yarn/src/test/java/org/apache/flink/yarn/YarnFileStageTestS3ITCase.java, tools/azure-pipelines/build-apache-repo.yml
With the minimum hadoop version being raised we no longer need to make the dependency on hadoop-aws conditional.
=> [FLINK-28165][yarn] Inline 'include_hadoop_aws' profile

flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/co/IntervalJoinOperatorTest.java, flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/IntervalJoinITCase.java
This PR aims to solve the issue presented here:https://issues.apache.org/jira/browse/FLINK-29387
Fix unstable  test `IntervalJoinITCase.testIntervalJoinSideOutputRightLateData` and `IntervalJoinITCase. testIntervalJoinSideOutputLeftLateData ` which could be failed when watermark sequence between two streams can not be guranted.
Now, testing late data with the test Harness `KeyedTwoInputStreamOperatorTestHarness` to guranted watermark sequence.
- *Move late data test case from `IntervalJoinITCase` to `IntervalJoinOperatorTest`*
Existing tests already cover this change, and it can pass them successfully.
The tests are:
org.apache.flink.streaming.api.operators.co.IntervalJoinOperatorTest.testLateData …
=> [FLINK-29387][tests] fix unstable late test for interval join

tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/licensecheck/NoticeFileChecker.java, tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/utils/shade/ShadeParser.java, tools/ci/flink-ci-tools/src/test/java/org/apache/flink/tools/ci/licensecheck/NoticeFileCheckerTest.java, tools/ci/flink-ci-tools/src/test/java/org/apache/flink/tools/ci/utils/shade/ShadeParserTest.java
~~Based on #20067.~~
Similar to #20053, just for the shade plugin parsing logic.
=> [FLINK-28202][ci] Generalize utils around shade plugin 

docs/layouts/shortcodes/generated/rest_v1_dispatcher.html, docs/static/generated/rest_v1_dispatcher.yml, flink-runtime-web/src/test/resources/rest_api_v1.snapshot, flink-runtime/src/main/java/org/apache/flink/runtime/messages/webmonitor/JobDetails.java
Remove custom serializer so we can properly document the `JobDetails` response.
=> [FLINK-29423][rest] Remove custom JobDetails serializer

tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/utils/dependency/DependencyParser.java, tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/utils/deploy/DeployParser.java, tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/utils/shade/ShadeParser.java, tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/utils/shared/ParserUtils.java, tools/ci/flink-ci-tools/src/test/java/org/apache/flink/tools/ci/utils/deploy/DeployParserTest.java
This is just a code cleanup, dedplicating the parsing loops of 3 different plugin parsers (while also making the regex patterns a bit more consistent).
=> [FLINK-30044][ci] Deduplicate plugin parser loops

docs/content.zh/docs/connectors/table/overview.md, docs/content/docs/connectors/table/overview.md
In the Supported Connectors [section](https://nightlies.apache.org/flink/flink-docs-master/docs/connectors/table/overview/#supported-connectors), the graph shows that the Filesystem connector supports the lookup source. Actually, it doesn't.
So I want to remove this description.
- The documentation in the Supported Connectors section.
- The serializers: (yes / no / don't know) no 
- The runtime per-record code paths (performance sensitive): (yes / no / don't know) no  …
=> [FLINK-30180][docs] Remove the description of Filesystem supporting for the lookup in the Supported Connectors section

flink-runtime/src/main/java/org/apache/flink/runtime/security/modules/HadoopModuleFactory.java
1.16 backport PR for PR #21382
=> [BP-1.16][FLINK-30133][hadoop] Changes log level and make log message more descriptive.

flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerRunner.java
=> [BP-1.15][FLINK-26037][coordination] TMRunner waits for metric registry shutdown

flink-formats/flink-hadoop-bulk/src/test/java/org/apache/flink/formats/hadoop/bulk/HadoopPathBasedPartFileWriterTest.java
1.16 backport PR for parent PR #20755
=> [BP-1.16][FLINK-29092][Connectors/Test] Use one bucket assigner

flink-formats/flink-hadoop-bulk/src/test/java/org/apache/flink/formats/hadoop/bulk/HadoopPathBasedPartFileWriterTest.java
1.15 backport PR for parent PR https://github.com/apache/flink/pull/20755
=> [BP-1.15][FLINK-29092][Connectors/Test] Use one bucket assigner

docs/content.zh/docs/deployment/ha/zookeeper_ha.md, docs/content/docs/deployment/ha/zookeeper_ha.md, flink-dist/pom.xml, flink-dist/src/main/assemblies/bin.xml, flink-dist/src/main/assemblies/opt.xml, flink-end-to-end-tests/run-nightly-tests.sh, flink-end-to-end-tests/test-scripts/common.sh, flink-end-to-end-tests/test-scripts/test_ha_datastream.sh, flink-end-to-end-tests/test-scripts/test_ha_per_job_cluster_datastream.sh
Reverts FLINK-13417 and FLINK-16350 since it's no longer required to bundle 2 different clients.
We'll upgrade to 3.7 in FLINK-29420.
=> [FLINK-30237][coordination] Only bundle single ZK client

docs/layouts/shortcodes/generated/rest_v1_dispatcher.html, docs/static/generated/rest_v1_dispatcher.yml, flink-runtime-web/src/test/resources/rest_api_v1.snapshot, flink-runtime/src/test/java/org/apache/flink/runtime/rest/compatibility/CompatibilityRoutines.java, flink-table/flink-sql-gateway/src/test/resources/sql_gateway_rest_api_v1.snapshot, pom.xml
Second attempt. Identical changes to #21227.
=> [FLINK-29862] Upgrade to flink-shaded 16.1

flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobServerCleanupTest.java
1.16 backport PR for parent PR #21428
=> [BP-1.16][FLINK-30138][runtime][test] Increases timeout to essentially wait forever for an expected Exception to be thrown

flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobServerCleanupTest.java
1.15 backport PR for parent PR #21428
=> [BP-1.15][FLINK-30138][runtime][test] Increases timeout to essentially wait forever for an expected Exception to be thrown 

flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/sink/PulsarSinkITCase.java, flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/function/ControlSource.java, flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/PulsarRuntimeOperator.java
1.16 backport PR for parent PR #21252
=> [BP-1.16][FLINK-29830][Connector/Pulsar] Create the topic with schema before consuming messages in PulsarSinkITCase. (#21252)

flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/sink/PulsarSinkITCase.java, flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/function/ControlSource.java, flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/PulsarRuntimeOperator.java
1.15 backport PR for parent PR #21252
=> [BP-1.15][FLINK-29830][Connector/Pulsar] Create the topic with schema before consuming messages in PulsarSinkITCase. (#21252)

flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointStressITCase.java
The `Files.walk` fails with `NoSuchFileException` if files are deleted during the iteration. Since it is the possible situation for us we should just ignore it error. More precisely we should iterate only over not deleted files which can be done by `Files.walkFileTree`
- *Files.walk replaced by Files.walkFileTree*
There are changes only in test …
=> [FLINK-28766][tests] Safe iterate over checkpoint files in order to avoid exception during parallel savepoint deletion

flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/physical/stream/WatermarkAssignerChangelogNormalizeTransposeRuleTest.xml
FLINK-28988 fixed the incorrectly filter pushdown issue, but when merged into master it affects a related test case (added by FLINK-29781 recently), this pr will fix this fail case.
=> [hotfix][table-planner] fix tests for FLINK-28988 merged(no code conflict with latest master but a related test case failed)

flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointStressITCase.java
1.16 backport for PR #21440
No conflicts occurred during cherry-picking:
```
git cherry-pick 1ddaa2a460dd8def96742d0d94b1a86df4ae9c81 9e1cefe250972b213ac69322531a4de69ca0e1a6 
[FLINK-28766-1.16 6496a7830d9] [FLINK-28766][tests] Safe iterate over checkpoint files in order to avoid exception during parallel savepoint deletion
Author: Anton Kalashnikov <akalash.dev@gmail.com>
Date: Thu Dec 1 15:06:26 2022 +0100
1 file changed, 39 insertions(+), 14 deletions(-)
[FLINK-28766-1.16 c4cee9930b4] [hotfix][tests] Fixed checkstyle of UnalignedCheckpointStressITCase
Author: Anton Kalashnikov <akalash.dev@gmail.com>
Date: Thu Dec 1 15:18:09 2022 +0100
1 file changed, 14 insertions(+), 16 deletions(-)
```
=> [BP-1.16][FLINK-28766][tests] Safe iterate over checkpoint files in order to avoid exception during parallel savepoint deletion

flink-runtime-web/web-dashboard/src/app/pages/job/configuration/job-configuration.component.html, flink-runtime-web/web-dashboard/src/app/pages/job/configuration/job-configuration.component.less
FLINK-29925
Fix job configuration table ui
=> [FLINK-29925] fix: improve configuration tables' column widths

docs/content.zh/docs/connectors/table/jdbc.md, docs/content/docs/connectors/table/jdbc.md
Link https://issues.apache.org/jira/browse/FLINK-30357.
=> [FLINK-30357][doc] Wrong link in connector/jdbc doc.

flink-core/src/main/java/org/apache/flink/util/FatalExitExceptionHandler.java, flink-core/src/main/java/org/apache/flink/util/concurrent/ThreadUtils.java
1.16 backport PR for parent PR #21463
=> [BP-1.16][FLINK-30299][core] Adds thread dump creation to FatalExitExceptionHandler

flink-core/src/main/java/org/apache/flink/util/FatalExitExceptionHandler.java, flink-core/src/main/java/org/apache/flink/util/concurrent/ThreadUtils.java
1.15 backport PR for parent PR #21463
=> [BP-1.15][FLINK-30299][core] Adds thread dump creation to FatalExitExceptionHandler

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserDDLSemanticAnalyzer.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/AlterTableChangeOperation.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/AlterTableOptionsOperation.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/Catalog.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/TableChange.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlToOperationConverter.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlToOperationConverterTest.java
*Introduce TableChange to represent ALTER TABLE SET/RESET syntax*
- *Introduce TableChange API*
- *Add Catalog method to alter table with table changes.*
- *Use AlterTableChangeOperation to represents set/reset*
Add change in SqlToOperationConverter to make sure the Operation contains the expected changes. …
=> [FLINK-30493][table-api] Introduce TableChange to SET/RESET options

flink-clients/src/main/java/org/apache/flink/client/cli/CliFrontend.java, flink-clients/src/test/java/org/apache/flink/client/cli/CliFrontendITCase.java
Flink now throws exception in command line tools:
```
$ flink
...
java.lang.IllegalArgumentException: 1 > 0
at java.base/java.util.Arrays.copyOfRange(Arrays.java:3990)
at java.base/java.util.Arrays.copyOfRange(Arrays.java:3950)
at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1170)
```
In this PR I've fixed it.
Fixed the exception.
* New unit test
* Manually, build Flink and start `flink` command. The tool must print usage.
- …
=> [FLINK-30429][client] Fix IllegalArgumentException when no argument in flink executable

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/FlinkFilterJoinRule.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/physical/stream/ChangelogModeInferenceTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/physical/stream/WatermarkAssignerChangelogNormalizeTransposeRuleTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/join/TemporalJoinTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/rules/physical/stream/ChangelogModeInferenceTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/TemporalJoinITCase.scala
this is a backport pr for FLINK-28988 to release-1.16
=> [bp-1.16][FLINK-28988] Don't push filters down into the right table for temporal join

flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNSessionCapacitySchedulerITCase.java
1.16 backport PR of parent PR #21583
=> [BP-1.16][FLINK-30539][tests] Removes timeout from YARNSessionCapacitySchedulerITCase

flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNSessionCapacitySchedulerITCase.java
1.15 backport PR of parent PR #21583
=> [BP-1.15][FLINK-30539][tests] Removes timeout from YARNSessionCapacitySchedulerITCase

flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/SqlGatewayRestEndpoint.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/handler/statement/CompleteStatementHandler.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/header/statement/CompleteStatementHeaders.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/message/statement/CompleteStatementRequestBody.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/message/statement/CompleteStatementResponseBody.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/SqlGatewayServiceImpl.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/operation/OperationExecutor.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/utils/Constants.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/rest/StatementRelatedITCase.java, flink-table/flink-sql-gateway/src/test/resources/sql_gateway_rest_api_v2.snapshot
Add completeStatement REST API in the SQL Gateway.
- Add `CompleteStatementHandler`, `CompleteStatementHeaders`, `CompleteStatementRequestBody` and `CompleteStatementResponseBody`.
- Add `StatementRelatedITCase`.
- Update `sql_gateway_rest_api_v2.snapshot`.
- `StatementRelatedITCase`
- Existed `SqlGatewayRestAPIStabilityTest`. …
=> [FLINK-28796] Add completeStatement REST API in the SQL Gateway

docs/content/docs/concepts/flink-architecture.md
- Fix minor typo in flink-architecture docs
=> [hotfix] [docs] Fix minor typo in flink-architecture docs

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/endpoint/hive/util/OperationExecutorFactory.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/endpoint/hive/HiveServer2EndpointITCase.java, flink-table/flink-sql-gateway-api/src/main/java/org/apache/flink/table/gateway/api/results/ResultSet.java, flink-table/flink-sql-gateway-api/src/main/java/org/apache/flink/table/gateway/api/results/ResultSetImpl.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/SqlGatewayServiceImpl.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/operation/OperationExecutor.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/operation/OperationManager.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/result/NotReadyResult.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/result/ResultFetcher.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/rest/OperationRelatedITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/rest/serde/ResultInfoJsonSerDeTest.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/SqlGatewayServiceITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/SqlGatewayServiceStatementITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/operation/OperationManagerTest.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/result/ResultFetcherTest.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/utils/SqlGatewayServiceTestUtil.java
Currently, the `ResultSet` only contains Schema and data for execution result, witch is not enough for Client to display necessary information. So we need to add more fields to improve 'ResultSet'.
We can refactor the ResultSet to an interface and hide the detail of implementation of ResultSet, such as how to Ser/De the data in ResultSet.
- Change `ResultSet` to an interface and add new necessary methods.
- Implement `ResultSetImpl`.
- Add tests for new methods.
- All the tests in `SqlGatewayServiceITCase`.
- …
=> [FLINK-29950] Refactor ResultSet to an interface

flink-table/flink-sql-client/bin/sql-client.sh, flink-table/flink-sql-client/pom.xml
New design of SQL client will depend on the sql-gateway module. So add the jar to the jar path in starting script.
- Modify `sql-client.sh`.
- Modify pom.
=> [FLINK-30509][sql-client] Add sql-gateway dependency in sql-client

docs/README.md, docs/setup_docs.sh
Unchanged backport of https://github.com/apache/flink/pull/19815
=> [BP 1.16][FLINK-27731][Documentation][Build] Remove Hugo Modules code

docs/setup_docs.sh
Unchanged backport of https://github.com/apache/flink/pull/19815
=> [BP 1.15][FLINK-27731][Documentation][Build] Remove Hugo Modules code

flink-core/src/main/java/org/apache/flink/api/common/functions/AbstractRichFunction.java
Remove redundant char
*(or)*
This change is already covered by …
=> Remove redundant char

docs/content.zh/docs/dev/table/hive-compatibility/hive-dialect/alter.md, docs/content/docs/dev/table/hive-compatibility/hive-dialect/alter.md
=> [hotfix][docs][table] Fix typo in flink hive-dialect doc

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecSink.java
* modifies `applySinkProvider` function to accept clssloader 
* use the classloader to set context for current thread in `applySinkProvider`
```
/usr/lib/flink/bin/sql-client.sh -j /usr/lib/hudi/hudi-flink-bundle.jar
Setting HBASE_CONF_DIR=/etc/hbase/conf because no HBASE_CONF_DIR was set.
Using the result of 'hadoop classpath' to augment the Hadoop classpath: /etc/hadoop/conf:/usr/lib/hadoop/lib/*:/usr/lib/hadoop/.//*:/usr/lib/hadoop-hdfs/./:/usr/lib/hadoop-hdfs/lib/*:/usr/lib/hadoop-hdfs/.//*:/usr/lib/hadoop-mapreduce/.//*:/usr/lib/hadoop-yarn/lib/*:/usr/lib/hadoop-yarn/.//*:/etc/tez/conf:/usr/lib/tez/hadoop-shim-0.10.2-amzn-0.jar:/usr/lib/tez/hadoop-shim-2.8-0.10.2-amzn-0.jar:/usr/lib/tez/lib:/usr/lib/tez/LICENSE:/usr/lib/tez/LICENSE-BSD-3clause:/usr/lib/tez/LICENSE-CDDLv1.1-GPLv2_withC …
```
=> [FLINK-30377][table-planner] applySinkProvider use ClientWrapperClassLoader while extracting Type from KeyedStream

flink-dist/src/main/resources/META-INF/NOTICE, flink-state-backends/flink-statebackend-rocksdb/pom.xml
Bump frocksdbjni to 6.20.3-ververica-2.0
- Bump frocksdbjni to 6.20.3-ververica-2.0
- Update NOTICE file in flink-dist
This change is already covered by existing RocksDB state backeend‘s tests.
- Does …
=> [FLINK-24932][state] Bump frocksdbjni to 6.20.3-ververica-2.0

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserDMLHelper.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectITCase.java
To fix the wrong behavior for insert overwrite with Hive dialect when the table name contains uppercase character.
When decide it's overwrite or not, we should use the lowercase of the table name.
Add test in `HiveDialectITCase#testInsertOverwrite`. …
=> [FLINK-30567][hive] Fix wrong behavior for insert overwrite with Hive dialect when the table contains uppercase character 

flink-connectors/flink-sql-connector-hive-3.1.3/pom.xml, flink-connectors/flink-sql-connector-hive-3.1.3/src/main/resources/META-INF/NOTICE
To fix the class not found issue for flink hive3 connector
- include `org.apache.thrift:libfb303` in pom.xml 
Verify it by manually.
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not …
=> [FLINK-29878][hive] Include libfb303 to fix fail to use flink-sql-connector-hive-3.1.3

flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/endpoint/hive/HiveServer2EndpointITCase.java, flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/SqlClient.java, flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliStrings.java, flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/Executor.java, flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/ExecutorImpl.java, flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/local/DefaultContextUtils.java, flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/local/SingleSessionManager.java, flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientITCase.java, flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/local/ExecutorImplITCase.java, flink-table/flink-sql-client/src/test/resources/sql/function.q, flink-table/flink-sql-client/src/test/resources/sql/set.q, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/SqlGateway.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/context/DefaultContext.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/context/SessionContext.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/operation/OperationExecutor.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/session/SessionManager.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/session/SessionManagerImpl.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/SqlGatewayServiceITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/session/SessionManagerImplTest.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/utils/SqlGatewayServiceExtension.java
*Introduce a specical `SessionManager` for the sql-client embedded mode, which require less resources and add Handler for REMOVE JAR statement.*
This change is already covered by existing tests, such as *CliClientITCase*. …
=> [FLINK-30692][sql-client] Introduce SingleSessionManager to support REMOVE JAR syntax

docs/layouts/shortcodes/generated/batch_execution_configuration.html, docs/layouts/shortcodes/generated/expert_scheduling_section.html, flink-core/src/main/java/org/apache/flink/configuration/BatchExecutionOptions.java
In [FLINK-30686](https://issues.apache.org/jira/browse/FLINK-30686) we refined the adaptive batch configuration. However, the key of a configuration item `SPECULATIVE_ENABLED` has been modified incorrectly. According to flip-283, it should be modified to `execution.batch.speculative.enabled`.
Fix the configuration key SPECULATIVE_ENABLED to `execution.batch.speculative.enabled`. …
=> [FLINK-30889][conf] Fix the key of configuration SPECULATIVE_ENABLED.

docs/content.zh/docs/dev/table/sql/explain.md, docs/content/docs/dev/table/sql/explain.md
This pull request adds documentation for `EXPLAIN PLAN_ADVICE` statement.
Add doc.
- Does this pull request introduces a new feature? Yes
=> [FLINK-30673][docs][table] Add documentation for "EXPLAIN PLAN_ADVICE" statement

flink-runtime/src/main/java/org/apache/flink/runtime/state/StateUtil.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBStateUploader.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/snapshot/RocksDBSnapshotStrategyBase.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/snapshot/RocksIncrementalSnapshotStrategy.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/snapshot/RocksNativeFullSnapshotStrategy.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateUploaderTest.java
Backport the FLINK-30461 to release-1.16
=> [bp-1.16][FLINK-30461][checkpoint] Fix the bug that the shared files will remain forever after the rocksdb incremental checkpoint exception

docs/content.zh/docs/dev/table/sourcesSinks.md, docs/content/docs/dev/table/sourcesSinks.md, flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/source/abilities/SupportsRowLevelModificationScan.java
Add the doc for Delete/Update API.
- Add description in `docs/dev/table/sourcessinks/#source-abilities`/`docs/dev/table/sourcessinks/#sink-abilities` for the interfaces required to support delete/update. 
Verify it manually. …
=> [FLINK-30666][doc] Add document for Delete/Update API

flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/itcases/HAQueryableStateFsBackendITCase.java, flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/itcases/HAQueryableStateRocksDBBackendITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/LeaderElectionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/leaderretrieval/ZooKeeperLeaderRetrievalTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/testutils/ZooKeeperTestUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/ZooKeeperUtilsTreeCacheTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/zookeeper/ZooKeeperExtension.java, flink-runtime/src/test/java/org/apache/flink/runtime/zookeeper/ZooKeeperResource.java, flink-runtime/src/test/java/org/apache/flink/runtime/zookeeper/ZooKeeperTestEnvironment.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/EventTimeWindowCheckpointingITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/ResumeCheckpointManuallyITCase.java, flink-tests/src/test/java/org/apache/flink/test/runtime/leaderelection/ZooKeeperLeaderElectionITCase.java, flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNHighAvailabilityITCase.java
1.15 backport PR of parent PR #20378
=> [BP-1.15][FLINK-28523][tests] Increase Zookeeper session timeouts

flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/ResultPartitionTest.java
Back-port FLINK-28326 to release-1.16.
=> [BP-1.16][FLINK-28326][test] fix unstable test testIdleAndBackPressuredTime.

flink-clients/src/test/java/org/apache/flink/client/deployment/application/ApplicationDispatcherBootstrapTest.java
1.15 backport for parent PR #21869
=> [BP-1.15][FLINK-30910][runtime] Making test wait for stop to be called before finishing the bootstrap operation (#21869)

flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/ExecutorImplITCase.java
*Don't print the interrupted exception to the `System.out`.*
=> [FLINK-30940][sql-client] Redirect the interrupted exception to the log

flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ExecutionGraphPartitionReleaseTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/TestingComponentMainThreadExecutor.java
1.17 backport PR of parent PR #21887
=> [BP-1.17][FLINK-30944] Fix thread leak in ExecutionGraphPartitionReleaseTest. 

flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ExecutionGraphPartitionReleaseTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/TestingComponentMainThreadExecutor.java
1.16 backport PR of parent PR #21887
=> [BP-1.16][FLINK-30944] Fix thread leak in ExecutionGraphPartitionReleaseTest. 

flink-table/flink-sql-client/src/test/resources/sql/set.q
*Fix unstable ctas test in CliClientITCase*
=> [FLINK-30640][sql-client] Fix unstable ctas test in CliClientITCase

flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/TableITCase.scala
`TableITCase#testCollectWithClose` has a small possibility of failing due to incorrect testing method. This PR fixes this issue. See comments of  FLINK-25813 for more details.
- Fix unstable test TableITCase#testCollectWithClose
This change is already covered by existing tests, such as `TableITCase#testCollectWithClose`. …
=> [FLINK-25813][table-planner] Fix unstable test TableITCase#testCollectWithClose

flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/TableITCase.scala
1.17 backport for parent PR #18893
=> [BP-1.17][FLINK-25813][table-planner] Fix unstable test TableITCase#testCollectWithClose

flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/TableITCase.scala
1.16 backport for parent PR #18893
=> [BP-1.16][FLINK-25813][table-planner] Fix unstable test TableITCase#testCollectWithClose

flink-table/flink-table-planner/pom.xml
This pr is aims to alleviate the CI OOM problem mentioned in issue: https://issues.apache.org/jira/browse/FLINK-18356.
Setting maven property `flink.resueForks` to false in table planner module can only reduce the frequency of oom error, but can't solve this problem.
- change the `pom.xml` in table planner module.
This pr need to run CI for multiple times to verify that the CI OOM problem will not frequently happen. …
=> [FLINK-31082][table-planner] Setting maven property 'flink.resueForks' to false in table planner module

docs/README.md
=> [hotfix] Build docs script already contains inits

flink-table/flink-table-planner/pom.xml
This pr is a fix up pr for `FLINK-31082`, which aims to alleviate the CI OOM problem mentioned in issue: https://issues.apache.org/jira/browse/FLINK-18356 in release-1.17.
Setting maven property flink.resueForks to false in table planner module can only reduce the frequency of oom error, but can't solve this problem.
- change `pom.xml` in table planner module. …
=> [FLINK-31082][table-planner] Fixups for setting maven property 'flinkresueForks' to false in table planner module in right way

docs/content.zh/docs/dev/table/sql-gateway/overview.md, docs/content/docs/dev/table/sql-gateway/overview.md
To improve version info shown in the doc of SQL Gateway. It should change with the flink version instead of a constant value 
`1.16-SNAPSHOT`.
Replace `1.16-SNAPSHOT` with `{{< version >}}` which wil then change with the flink version;
Verify it locally. …
=> [FLINK-31130][doc] Improve version info shown in the doc of SQL Gateway

docs/content/docs/connectors/table/hive/hive_read_write.md
*Fix document link problem and typo.*
=> [FLINK-31175][doc] Fix link doesn't work in hive_read_write doc

flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/DefaultContextUtils.java, flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/SqlClientTest.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/SqlGateway.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/context/DefaultContext.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/utils/SqlGatewayServiceExtension.java
*Cherry pick the #21974 to master.*
=> Cherry pick FLINK-31136 to master

docs/content.zh/docs/dev/table/sql-gateway/overview.md, docs/content/docs/dev/table/sql-gateway/overview.md, flink-table/flink-sql-gateway-api/src/main/java/org/apache/flink/table/gateway/api/config/SqlGatewayServiceConfigOptions.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/header/session/GetSessionConfigHeaders.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/header/session/TriggerSessionHeartbeatHeaders.java
correct the description of sql gateway configuration:
1.sql-gateway.session.idle-timeout 、sql-gateway.session.check-interval  description in SqlGatewayServiceConfigOptions 
2.GetSessionConfigHeaders  and TriggerSessionHeartbeatHeaders class description
remove the 'or negative value' description and correct the class description
*(or)*
*(or)*
This change added tests and can be verified as …
=> [FLINK-31176][sql-gateway] correct the description of sql gateway configuration

flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
Fix the bug that SteamTask skip handle exception during restoring.
Fix the bug that SteamTask skip handle exception during restoring.
- Manually verified locally …
=> [FLINK-29816][streaming] Fix the bug that StreamTask doesn't handle exception during restoring

flink-runtime/src/main/java/org/apache/flink/runtime/security/modules/HadoopModule.java, flink-runtime/src/main/java/org/apache/flink/runtime/security/token/hadoop/HBaseDelegationTokenProvider.java, flink-runtime/src/main/java/org/apache/flink/runtime/security/token/hadoop/HadoopFSDelegationTokenProvider.java, flink-runtime/src/main/java/org/apache/flink/runtime/security/token/hadoop/KerberosLoginProvider.java, flink-runtime/src/test/java/org/apache/flink/runtime/security/modules/HadoopModuleTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/security/token/hadoop/KerberosLoginProviderITCase.java, flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
Unchanged backport of https://github.com/apache/flink/pull/22009
=> [FLINK-31109][BP 1.17][Yarn] Support Hadoop proxy user when delegation token fetch is disabled

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/ArrayDistinctFunction.java
*Fix possible bug of array_distinct.*
*as talked here https://github.com/apache/flink/pull/19623, we should use builtin expressions/functions. because the sql semantic is different from  java equals*
- unit test
=> [FLINK-31237][table] Fix possible bug of array_distinct.

flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
BP for release 1.17  
Fix the bug that StreamTask doesn't handle exception during restoring
BP for release 1.17  
Fix the bug that StreamTask doesn't handle exception during restoring …
=> [FLINK-29816][streaming][BP-release-1.17] Fix the bug that StreamTask doesn't handle exception during restoring

flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
BP for release 1.16  
Fix the bug that StreamTask doesn't handle exception during restoring
BP for release 1.16  
Fix the bug that StreamTask doesn't handle exception during restoring …
=> [FLINK-29816][streaming][BP-release-1.16] Fix the bug that StreamTask doesn't handle exception during restoring

docs/content.zh/docs/connectors/table/formats/csv.md
*I find some errors in Format Options.And I will fix it.*
Fix errors in Format Options.
- The S3 file system connector:(no)
=> [FLINK-31257][docs-zh] Fix errors in “CSV Formats" page

flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionTest.java
Backport FLINK-29884 to release-1.16.
=> [BP-1.16][FLINK-29884][test] Fix flaky test SortMergeResultPartitionTest.testRelease

docs/layouts/shortcodes/generated/execution_config_configuration.html
- Dependencies (does it add or upgrade a dependency): (yes / no) no 
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) no
=> [docs][hotfix] correct label in config configuration

flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/ExecutorImpl.java, flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/ExecutorImplITCase.java
*The failed tests are because the Executor receives the results before checking the interrupted flag. So we let the server return the results until the Executor finishes its exception processing.*
=> [FLINK-30978][sql-client] Fix ExecutorImpl#testInterruptException hangs

flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/TestJobExecutor.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/command/SharedTestCommandDispatcher.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/command/TestCommandDispatcher.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/command/TestCommandDispatcherImpl.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/graph/TestEventSource.java
=> [BP-1.16][FLINK-31133][tests] Prevent timeouts in PartiallyFinishedSourcesITCase

flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/TestJobExecutor.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/command/SharedTestCommandDispatcher.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/command/TestCommandDispatcher.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/command/TestCommandDispatcherImpl.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/graph/TestEventSource.java
=> [BP-1.17][FLINK-31133][tests] Prevent timeouts in PartiallyFinishedSourcesITCase

flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/TestJobExecutor.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/command/SharedTestCommandDispatcher.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/command/TestCommandDispatcher.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/command/TestCommandDispatcherImpl.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/graph/TestEventSource.java
=> [BP-1.15][FLINK-31133][tests] Prevent timeouts in PartiallyFinishedSourcesITCase

flink-runtime/src/test/java/org/apache/flink/runtime/net/ConnectionUtilsTest.java
*fix ConnectionUtilsTest.testFindConnectingAddressWhenGetLocalHostThrows swallows IllegalArgumentException*
- *make the timeout of ServerSocket be zero*.
=> [FLINK-31298] fix ConnectionUtilsTest.testFindConnectingAddressWhenGetLocalHostThrows swallows IllegalArgumentException

flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/operation/OperationManager.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/utils/SqlCancelException.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/operation/OperationManagerTest.java
Cherry-pick the fix #22127 to the master
=> [FLINK-31351][sql-gateway] Don't stop the stuck thread by force

flink-runtime/src/test/java/org/apache/flink/runtime/net/ConnectionUtilsTest.java
fix ConnectionUtilsTest.testFindConnectingAddressWhenGetLocalHostThrows swallows IllegalArgumentException
=> [FLINK-31298] backport to branch release-1.16

flink-runtime/src/test/java/org/apache/flink/runtime/net/ConnectionUtilsTest.java
fix ConnectionUtilsTest.testFindConnectingAddressWhenGetLocalHostThrows swallows IllegalArgumentException
=> [FLINK-31298] backport to branch release-1.17

docs/content.zh/docs/dev/table/sql/queries/overview.md
Translate "Overview" page of "Querys" into Chinese
Translate /dev/table/sql/queries/overview.md
Translate /dev/table/sql/queries/overview.md
=> [FLINK-30748][docs]Translate "Overview" page of "Querys" into Chinese

docs/content.zh/docs/connectors/table/hbase.md, docs/content/docs/connectors/table/hbase.md
Fix wrong key 'lookup.cache.caching-missing-key' in 'hbase.md'.
=> [FLINK-31437][docs] Fix wrong key 'lookup.cache.caching-missing-key' in 'hbase.md'.

flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/join/NestedLoopJoinTest.xml
This pr is aims to fix NestedLoopJoinTest.testLeftOuterJoin failed in Flink-1.16.2 with unexpected plan after cherry-pick FLINK-31273 from release-1.17.1.
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no 
=> [FLINK-31477][table-planner] Fix NestedLoopJoinTest.testLeftOuterJoin failed with unexpected plan

flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/pom.xml, flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SQLClientSchemaRegistryITCase.java, flink-formats/flink-avro-confluent-registry/pom.xml, flink-formats/flink-sql-avro-confluent-registry/pom.xml, flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE, flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/licenses/LICENSE.zstd-jni
Unchanged backport of https://github.com/apache/flink/pull/22191
=> [FLINK-31485][BP 1.17][Confluent Avro] Change packaging of Avro Confluent Schema Registry

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/ExecutableOperationContextImpl.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ExecutableOperation.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/CreateCatalogFunctionOperation.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/CreateCatalogOperation.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/CreateDatabaseOperation.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/CreateOperation.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/CreateTableOperation.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/CreateTempSystemFunctionOperation.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/CreateViewOperation.java
The PR continues the work started at https://github.com/apache/flink/pull/22175
This PR does this for CreateOperations.
- Migrate `CreateOperations` to extend `ExecutableOperation` and move it's execution logic out from `TableEnvironmentImpl`. …
=> [FLINK-31504][table] Move execution logic of CreateOperation out from TableEnvironmentImpl

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlNodeToOperationConversion.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlNodeConverter.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlNodeConverters.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlQueryConverter.java
Introduce `SqlQueryConverter` and move the conversion logic of query `SqlNode` -> `PlannerQueryOperation` to it.
Note that the conversion is complex for query SqlNodes because it's unclear what the specific query SqlNode classes are. But they should all belong to the `SqlKind.QUERY`. Therefore, we can introduce a new mapping path for the SqlKind. 
- Add a default method `Optional<EnumSet<SqlKind>> supportedSqlKinds()` for `SqlNodeConverter`, which returns empty by default. 
- `SqlNodeConverters` supports registering `SqlNodeConverter`, which implements this method. 
- `SqlNodeConverters` will first lookup `SqlNodeConverter` by class of `SqlNode`, and fallback to `SqlKind` of `SqlNode` if not found. 
- Introduce `SqlQueryConverter` which matches SqlNodes with `SqlKind.QUERY` and converts …
=> [FLINK-31514][table-planner] Move query SqlNode conversion logic to SqlQueryConverter

flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectITCase.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/catalog/hive/HiveCatalogHiveMetadataTest.java, tools/azure-pipelines/build-apache-repo.yml
To fix `HiveCatalogHiveMetadataTest#testCreateTableWithConstraints` failure in Hive3
Change the datatype of `z` in `testCreateTableWithConstraints` to `nullable`,
Sucessful [build](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=47414&view=logs&j=e60d5d3b-2e2f-5bb7-484a-16135ea73209&t=9363ed9e-7ac2-5835-c98d-4fdb89b19329) for flink-connector-hive  with Hive3.
The test failure is related to FLINK-29618 …
=> [FLINK-31531][hive] Fix HiveCatalogHiveMetadataTest&HiveDialectITCase failure in Hive3

flink-tests/src/test/java/org/apache/flink/test/state/ChangelogRescalingITCase.java
`ChangelogRescalingITCase` [failed](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=47369&view=logs&j=a57e0635-3fad-5b08-57c7-a4142d7d6fa9&t=2ef0effc-1da1-50e5-c2bd-aab434b1c5b7&l=10238) on `1.17` with `FileNotFoundException` after restore attempt from chk-73.
At the same time, the log contained a message that chk-74 was not deleted. Meaning chk-74, not chk-73 was the latest checkpoint.
This is caused by not properly waiting for job termination in `ChangelogRescalingITCase.checkpointAndCancel`.
This PR fixes that by check job status in a loop.
=> [FLINK-31527][tests] Stabilize ChangelogRescalingITCase

docs/content.zh/_index.md, docs/content.zh/release-notes/flink-1.17.md, docs/content/_index.md, docs/content/release-notes/flink-1.17.md
This pull request adds release note for version 1.17.
- Add release note for 1.17
This change is a doc-only without test coverage. …
=> [FLINK-31157][release] Add release note for version 1.17

docs/content.zh/_index.md, docs/content.zh/release-notes/flink-1.17.md, docs/content/_index.md, docs/content/release-notes/flink-1.17.md
=> [BP-1.17][FLINK-31157][release] Add release note for version 1.17

docs/content.zh/docs/ops/upgrading.md, docs/content/docs/ops/upgrading.md
=> [BP-1.17][FLINK-31149][docs] Update compatibility matrix for release 1.17

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/utils/OperationConverterUtils.java
cleanup unused private methods in OperationConverterUtils, because called public methods has been removed in
#21522 
cleanup unused private methods in OperationConverterUtils
Trivial cleanup, no need test case.
=> [FLINK-31574][table-planner] Cleanup unused private methods in OperationConverterUtils

flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
Take back the following submitted changes:
db3a0a59519b279d016489e1bf29927a4f62a6ed
1993ad0c968efa60ad5071e8472f630b247251f0
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`:  (no)
- The serializers:  (no)
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper:  (no)
- The S3 file system connector:  (no)
- Does this pull request introduce a new feature?  (no)
=> [hotfix] Revert some unexpected changes.

docs/config.toml
We missed deprecating the 1.15 logs
=> [FLINK-31567][docs] Deprecates 1.15 docs.

flink-runtime-web/web-dashboard/src/app/services/job-manager.service.ts, flink-runtime-web/web-dashboard/src/app/services/metrics.service.ts, flink-runtime-web/web-dashboard/src/app/services/task-manager.service.ts
Backport https://issues.apache.org/jira/browse/FLINK-31541 to release-1.17.
=> [BP-1.17][FLINK-31541][ui] encode request params to support special characters in metrics name.

flink-end-to-end-tests/pom.xml, pom.xml
* Update Testcontainers to latest version
* Updated version in POM
- Kernetes/Yarn, ZooKeeper: no
=> [FLINK-28347][Test infrastructure] Update testcontainers dependency to v1.17.6

flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcExactlyOnceSinkE2eTest.java
Stabilize JdbcExactlyOnceSinkE2eTest
- Remove job checkpoint configuration, default to cluster configuration
- Change FailingMapper from random failure to expected failure, this allow to confirm the test behaviour …
=> [FLINK-31525][tests] Stabilize JdbcExactlyOnceSinkE2eTest

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/HsDataView.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/HsSubpartitionConsumer.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/HsSubpartitionConsumerMemoryDataManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/HsSubpartitionFileReaderImpl.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/HsFileDataManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/HsSubpartitionConsumerMemoryDataManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/HsSubpartitionFileReaderImplTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/HsSubpartitionMemoryDataManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/TestingHsDataView.java
Backport FLINK-31626 to release-1.17
=> [BP-1.17][FLINK-31626] HsSubpartitionFileReaderImpl should recycle skipped read buffers.

flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/DispatcherGateway.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMasterGateway.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/utils/TestingJobMasterGateway.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/utils/TestingJobMasterGatewayBuilder.java
Extends the support of querying/updating resource requirements to the Dispatcher layer.
=> [FLINK-31468] Add mechanics to the Dispatcher for handling job resource requirements

docs/content.zh/docs/connectors/dataset/formats/azure_table_storage.md, docs/content/docs/connectors/dataset/formats/azure_table_storage.md
*Fix the broken links in docs for Azure Table Storage*
- *Fix the broken links in docs for Azure Table Storage* …
=> [FLINK-31688][docs] Fix the broken links in docs for Azure Table Storage

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPool.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPoolTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/TestingBufferListener.java
Backport FLINK-31293 to release-1.17.
=> [BP-1.17][FLINK-31293] LocalBufferPool request overdraft buffer only when no available buffer and pool size is reached.

flink-dist/pom.xml, flink-end-to-end-tests/flink-high-parallelism-iterations-test/pom.xml, flink-examples/flink-examples-batch/pom.xml, flink-examples/flink-examples-build-helper/flink-examples-streaming-state-machine/pom.xml, flink-examples/flink-examples-streaming/pom.xml, flink-fs-tests/pom.xml, flink-tests/pom.xml, flink-walkthroughs/flink-walkthrough-datastream-java/src/main/resources/archetype-resources/pom.xml, flink-yarn-tests/pom.xml
Remove an unused dependency on the scala apis, and cleans up related scala build stuff, including some suffixes!
=> [FLINK-31728][examples] Remove scala api dependency

docs/static/generated/rest_v1_dispatcher.yml, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/FlameGraphTypeQueryParameter.java
Backport of https://github.com/apache/flink/pull/22358
=> [BP-1.17][FLINK-31738] Prevent name clash in generated clients

flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/CsvFileFormatFactory.java, flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/CsvReaderFormat.java
When reading the code, I found 2 typo errors and improved the lambada expression.
This PR will improve this part of the content.
Modify typo error And Improve lambada expression.
*(example:)*
- *Manually verified the change by running a 4 node cluster with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.* …
=> [FLINK-31761] Fix Some Typo And Improve lambda expressions.

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPool.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPoolTest.java
Backport FLINK-31763 to release-1.17.
=> [BP-1.17][FLINK-31763][runtime] Convert requested buffers to overdraft buffers when pool size is decreased

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPool.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPoolTest.java
Backport FLINK-31763 to release-1.16.
=> [BP-1.16][FLINK-31763][runtime] Convert requested buffers to overdraft buffers when pool size is decreased

docs/content.zh/docs/deployment/ha/kubernetes_ha.md, docs/content.zh/docs/deployment/ha/zookeeper_ha.md, docs/content.zh/docs/deployment/resource-providers/native_kubernetes.md, docs/content/docs/deployment/ha/kubernetes_ha.md, docs/content/docs/deployment/ha/zookeeper_ha.md, docs/content/docs/deployment/resource-providers/native_kubernetes.md
Backport e61fedda to release-1.17.
=> [BP-1.17][hotfix] Fix some broken links in docs

pom.xml
This is a cherry-pick backport of https://github.com/apache/flink/pull/22430
=> [BP-1.17][FLINK-31859][build] Update cyclonedx-maven-plugin from 2.7.3 to 2.7.7

docs/config.toml, docs/layouts/shortcodes/sql_connector_download_table.html, docs/setup_docs.sh
Backport FLINK-30378 and FLINK-31758 to fix incorrect doc
=> [BP-1.16][hotfix] Backport FLINK-30378 and FLINK-31758 to fix incorrect doc

flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/operation/OperationExecutor.java
Backport FLINK-31398 to release-1.17.
=> [BP-1.17][FLINK-31398][sql-gateway] OperationExecutor is no longer set context classloader when executing statement.

flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/fetcher/PauseOrResumeSplitsTask.java
*Fix the wrong name of PauseOrResumeSplitsTask#toString in connector fetcher*
*Fix the wrong name of PauseOrResumeSplitsTask#toString in connector fetcher*
This change is a typo fix without any test coverage.
=> [FLINK-31878][connectors] Fix the wrong name of PauseOrResumeSplitsTask#toString

flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/network/ClientTest.java
*Fix the unstable test ClientTest#testRequestUnavailableHost.*
- *Migrate ClientTest to JUnit5*
- *Fix the unstable test ClientTest#testRequestUnavailableHost*
This change is a trivial test fix without any test coverage.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yno)
=> [FLINK-31897] Fix the unstable test ClientTest#testRequestUnavailableHost

flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/network/ClientTest.java
Bach port to 1.17, the PR has been reviewed at https://github.com/apache/flink/pull/22471.
Fix the unstable test ClientTest#testRequestUnavailableHost.
- *Fix the unstable test ClientTest#testRequestUnavailableHost.*
This change is a test fix without any test coverage.
=> [FLINK-31897][Backport 1.17] Fix the unstable test ClientTest#testRequestUnavailableHost

flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/network/ClientTest.java
Bach port to 1.16, the PR has been reviewed at https://github.com/apache/flink/pull/22471.
Fix the unstable test ClientTest#testRequestUnavailableHost.
- *Fix the unstable test ClientTest#testRequestUnavailableHost.*
This change is a test fix without any test coverage.
=> [FLINK-31897][Backport 1.16] Fix the unstable test ClientTest#testRequestUnavailableHost

flink-queryable-state/flink-queryable-state-client-java/src/test/java/org/apache/flink/queryablestate/client/state/ImmutableAggregatingStateTest.java, flink-queryable-state/flink-queryable-state-client-java/src/test/java/org/apache/flink/queryablestate/client/state/ImmutableListStateTest.java, flink-queryable-state/flink-queryable-state-client-java/src/test/java/org/apache/flink/queryablestate/client/state/ImmutableMapStateTest.java, flink-queryable-state/flink-queryable-state-client-java/src/test/java/org/apache/flink/queryablestate/client/state/ImmutableReducingStateTest.java, flink-queryable-state/flink-queryable-state-client-java/src/test/java/org/apache/flink/queryablestate/client/state/ImmutableValueStateTest.java
Migrate flink-queryable-state-client testsD to JUnit5
=> [FLINK-31876][QS] Migrate flink-queryable-state-client tests to JUnit5

docs/content/docs/deployment/overview.md
this PR is fixing broken link for [Ververica platform](https://www.ververica.com/platform).
- Anything that affects deployment or recovery: no
=> [hotfix][docs] Fix link to Ververica Platform

flink-runtime-web/web-dashboard/src/app/pages/job/overview/detail/job-overview-drawer-detail.component.html, flink-runtime-web/web-dashboard/src/app/pages/job/overview/detail/job-overview-drawer-detail.component.ts
https://issues.apache.org/jira/browse/FLINK-32000
=> [FLINK-32000][webui] Expose max parallelism in the vertex detail drawer.

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPool.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/NetworkBufferPool.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/metrics/NettyShuffleMetricFactory.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPoolTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/NetworkBufferPoolTest.java
Backport FLINK-31764 to release-1.16.
=> [BP-1.16][FLINK-31764][runtime] Get rid of numberOfRequestedOverdraftMemorySegments in LocalBufferPool.

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PartitionedFile.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PartitionedFileWriter.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PartitionedFileWriteReadTest.java
Backport FLINK-32027 to release-1.17.
=> [BP-1.17][FLINK-32027][runtime] Fix the potential concurrent reading bug of index file for SortMergeShuffle.

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PartitionedFile.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PartitionedFileWriter.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PartitionedFileWriteReadTest.java
Backport FLINK-32027 to release-1.16.
=> [BP-1.16][FLINK-32027][runtime] Fix the potential concurrent reading bug of index file for SortMergeShuffle.

flink-core/src/main/java/org/apache/flink/util/concurrent/FutureUtils.java, flink-core/src/test/java/org/apache/flink/util/concurrent/FutureUtilsTest.java
1.17 backport PR for PR #22544.
=> [BP-1.17][FLINK-32029][core] Adds fallback error handling to FutureUtils.handleUncaughtException.

flink-core/src/main/java/org/apache/flink/util/concurrent/FutureUtils.java, flink-core/src/test/java/org/apache/flink/util/concurrent/FutureUtilsTest.java
1.16 backport PR for PR #22544 . The change was cherry-picked from the related 1.17 backport PR #22561 without conflicts. Therefore, reviewing one of the two backport PRs is good enough
=> [BP-1.16][FLINK-32029][core] Adds fallback error handling to FutureUtils.handleUncaughtException.

flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/DecimalITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/table/DecimalITCase.scala
*Migrate DecimalITCase to JUnit5 to resolve the unstable test issues*
- *Migrate DecimalITCase to JUnit5 to resolve the unstable test issues*
This change is a test update without any test coverage.
=> [FLINK-32048][tests] Migrate DecimalITCase to JUnit5 to resolve the unstable test issues

flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/NettyShuffleMaster.java
*Avoid creating tiered internal shuffle master before enabling the tiered storage*
- *Avoid creating tiered internal shuffle master before enabling the tiered storage*
This change is already covered by existing tests, such as *ShuffleMasterTest*.
=> [FLINK-32094][network] Avoid creating tiered internal shuffle master before enabling the tiered storage

docs/layouts/shortcodes/generated/yarn_config_configuration.html, flink-core/src/main/java/org/apache/flink/api/common/state/OperatorStateStore.java, flink-optimizer/src/main/java/org/apache/flink/optimizer/dag/OptimizerNode.java, flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/ResourceTracker.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointStatsCountsTest.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/AllWindowedStream.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/WindowedStream.java, flink-streaming-scala/src/main/scala/org/apache/flink/streaming/api/scala/AllWindowedStream.scala, flink-streaming-scala/src/main/scala/org/apache/flink/streaming/api/scala/KeyedStream.scala, flink-streaming-scala/src/main/scala/org/apache/flink/streaming/api/scala/WindowedStream.scala, flink-yarn/src/main/java/org/apache/flink/yarn/configuration/YarnConfigOptions.java
=> [hotfix] Fix typos of comment

docs/content/docs/dev/table/sql/unload.md
Unload.md wrongly writes UNLOAD operation as LOAD operation
Change LOAD to UNLOAD
=> [hotfix][docs] Change LOAD to UNLOAD in Unload.md

flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceReaderTest.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumeratorTest.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/enumerator/KafkaEnumeratorTest.java, flink-formats/flink-avro-confluent-registry/src/test/java/org/apache/flink/formats/avro/registry/confluent/CachedSchemaCoderProviderTest.java, flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroOutputFormatTest.java, flink-libraries/flink-cep/src/test/java/org/apache/flink/cep/operator/CEPOperatorTest.java, flink-runtime/src/main/java/org/apache/flink/runtime/operators/hash/CompactingHashTable.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/hash/CompactingHashTableTest.java, flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/mock/Whitebox.java
https://issues.apache.org/jira/browse/FLINK-31972
=> [FLINK-31972][tests] Remove powermock whitebox usages

flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CalcITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CodeSplitITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CorrelateITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CorrelateITCase2.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/LegacyLimitITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/LegacyTableSourceITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/Limit0RemoveITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/LimitITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/MiscITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/MultipleInputITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/OverAggregateITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/PartitionableSinkITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/PartitionableSourceITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/RankITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/SetOperatorsITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/SortLimitITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/TableScanITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/TableSinkITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/TableSourceITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/UnionITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/UnnestITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/ValuesITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/WindowTableFunctionITCase.scala, flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/extensions/parameterized/ParameterizedTestExtension.java
*Migrate the subclasses of BatchAbstractTestBase in runtime.batch.sql to JUnit5.*
- *Migrate the subclasses of BatchAbstractTestBase in runtime.batch.sql to JUnit5*
This change is a test migration without any test coverage.
=> [FLINK-32058][tests] Migrate the subclasses of BatchAbstractTestBase in runtime.batch.sql to JUnit5

flink-clients/src/test/java/org/apache/flink/client/program/ClientTest.java, flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/table/batch/compact/BatchPartitionCommitterSinkTest.java, flink-core/src/test/java/org/apache/flink/api/common/io/InputStreamFSInputWrapperTest.java, flink-fs-tests/src/test/java/org/apache/flink/hdfstests/ContinuousFileProcessingTest.java, flink-python/src/test/java/org/apache/flink/python/metric/process/FlinkMetricContainerTest.java, flink-python/src/test/java/org/apache/flink/table/runtime/arrow/sources/ArrowSourceFunctionTestBase.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobCacheGetTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/disk/iomanager/AsynchronousFileIOChannelTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/hash/HashTableTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/MultipartUploadResource.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/job/metrics/AggregatingMetricsHandlerTestBase.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/job/metrics/MetricsHandlerTestBase.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/JvmExitOnFatalErrorTest.java, flink-tests/src/test/java/org/apache/flink/test/state/BackendSwitchSpecs.java
Remove a bunch of mocks that are painfully unnecessary.
=> [FLINK-32149][tests] Remove trivial mockito usages

flink-end-to-end-tests/flink-sql-client-test/src/test/java/SqlClientITCase.java
(cherry picked from commit 4595762f974f03bdf5a4c3d42e211c3a24604bd4)
=> [FLINK-30257][BP 1.17] fix SqlClientITCase#testMatchRecognize

flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/AggregateITCaseBase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/AggregateITCase.scala, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/aggregate/LagAggFunction.java
Slove the Initial Value Problem of LagAggregation
dermine if the default value needs to be converted from non-null to null
org/apache/flink/table/table/planner/runtime/stream/sql/AggregateITCase#testLagAggFunction
=> [FLINK-31967][table-runtime] Fix LAG function get NPE when the input type is not null

docs/content.zh/docs/deployment/overview.md, docs/content/docs/deployment/overview.md
Simple doc update.
- Updates Cloudera related vendor solutions
=> [FLINK-32174][docs] Update Cloudera related product under vendor solutions

docs/content.zh/docs/deployment/overview.md, docs/content/docs/deployment/overview.md
=> [bp-1.17][FLINK-32174][docs] Update Cloudera related product under vendor solutions

docs/content.zh/docs/deployment/overview.md, docs/content/docs/deployment/overview.md
=> [bp-1.16][FLINK-32174][docs] Update Cloudera related product under vendor solutions

flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/handlers/JarRunHandler.java, flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/handlers/JarRunHandlerParameterTest.java
Backports [FLINK-31812](https://issues.apache.org/jira/browse/FLINK-31812) to release-1.17.
=> [BP-1.17][FLINK-31812][api] Transform savepoint path to null if empty in body

flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/operation/OperationExecutor.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/AbstractSqlGatewayStatementITCase.java, flink-table/flink-sql-gateway/src/test/resources/sql/insert.q, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java
This PR is cherry-picked from commit 83ba6b5348cbffb26e8d1d5ce6e8d6bb1994e3bc.
See #22703
See #22703
=> [FLINK-32219][sql-client] Fix SqlClient hangs when executing EXECUTE PLAN statement

docs/content.zh/docs/dev/table/sourcesSinks.md, docs/content/docs/dev/table/sourcesSinks.md
To fix the typo in the document of User-defined Sources & Sinks
Verify it by manually.
=> [FLINK-30919][docs] Fix typo for the sink ability part in the document of User-defined Sources & Sinks

docs/content.zh/docs/dev/table/sql/delete.md, docs/content.zh/docs/dev/table/sql/overview.md, docs/content.zh/docs/dev/table/sql/update.md, docs/content/docs/dev/table/sql/delete.md, docs/content/docs/dev/table/sql/overview.md, docs/content/docs/dev/table/sql/update.md
=> [BP-1.17][FLINK-31774][doc] Add document for delete and update statement (#22398)

flink-end-to-end-tests/flink-end-to-end-tests-hive/src/test/java/org/apache/flink/tests/hive/containers/HiveContainer.java
To fix the failure of HiveITCase.
Set the directory to create the Hive table to be readable & writable & exec by all to avoid the permission denied exception.
(the commit is actual  [6ba4b2](https://github.com/apache/flink/pull/22679/commits/6ba4b237a0d7e8b1f7b571c7d408f533ea8d9aff) from the #22679, but miss it while squashing these commits in the pr)
Existing tests …
=> [FLINK-32294][e2e] Fix HiveITCase failure

flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/RetryingExecutorTest.java
- Add exception handling machnism to make the exception visiable when RetryingExecutorTest#testDiscardOnTimeout timeouts
- Catch the exception and assert
=> [FLINK-26515][test] Add exception handling for RetryingExecutorTest#testDiscardOnTimeout

tools/azure-pipelines/e2e-template.yml
Have wget download all files from the directory and filter out the one we need with a pattern.
=> [FLINK-32238][ci] Stable libssl download

flink-rpc/flink-rpc-akka/pom.xml, flink-rpc/flink-rpc-akka/src/main/resources/META-INF/NOTICE
These dependencies are not required.
=> [FLINK-32304] Reduce rpc-akka dependency footprint

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TieredStorageNettyServiceImpl.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TieredStorageResultSubpartitionView.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/NoOpMasterAgent.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/TierFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/memory/MemoryTierFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/memory/MemoryTierProducerAgent.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/memory/MemoryTierSubpartitionProducerAgent.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/TestingTieredStorageMemoryManager.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TestingNettyConnectionWriter.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TestingTieredStorageNettyService.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TieredStorageResultSubpartitionViewTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/memory/MemoryTierProducerAgentTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/memory/MemoryTierSubpartitionProducerAgentTest.java
*Implement the memory tier producer for the tiered storage.*
- *Implement the memory tier producer for the tiered storage.*
=> [FLINK-31641][network] Implement the memory tier producer for the tiered storage

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/StateAssignmentOperation.java
*Fix incorrect comments of channel input state redistribution.*
- *Fix incorrect comments of channel input state redistribution.*
=> [hotfix][state] Fix incorrect comments of channel input state redistribution.

tools/azure-pipelines/build-apache-repo.yml, tools/azure-pipelines/jobs-template.yml, tools/ci/compile.sh
Additionally disables the python tests on Java 17 due to FLINK-32327.
=> [FLINK-32369][ci] Setup Java 17 cron build 

flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesCheckpointIDCounterTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionDriverTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStoreTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesTestFixture.java
1.16 backport PR for parent PR #22809
=> [BP-1.16][FLINK-32368][test] Fixes wrong interface implementation in KubernetesTestFixture

flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/sink/abilities/SupportsTruncate.java
Introduce `SupportsTruncate` interface.
Introduce `SupportsTruncate` interface.
N/A
- The serializers: (yes / no ****/ don't know)
=> [FLINK-32233][table] Introduce SupportsTruncate interface

flink-dist/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE, flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE, pom.xml
1.17 backport for parent PR #22815
=> [BP-1.17][FLINK-32371][build] Bump snappy-java to 1.1.10.1

azure-pipelines.yml, tools/azure-pipelines/build-apache-repo.yml, tools/azure-pipelines/build-nightly-dist.yml, tools/azure-pipelines/e2e-template.yml, tools/azure-pipelines/jobs-template.yml
Unchanged back port of #22858 on release-1.17
=> [BP-1.17][FLINK-32392][ci] Invalidate Maven repo cache on Azure every year to reduce its disk usage

flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/DefaultSchedulerTest.java
Fixes test `DefaultSchedulerTest#testTriggerCheckpointAndCompletedAfterStore` that was using the wrong executor to acknowlege a checkpoint. This is a followup to #22793 that uncovered the test problem.
Use correct main thread executor to acknowledge CP in the test to avoid the assertion about calling from the wrong thread.
Rerun the fixed test. …
=> [FLINK-32441] Fix DefaultSchedulerTest#testTriggerCheckpointAndCompletedAfterStore

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/BufferWithChannel.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortBasedDataBuffer.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortBuffer.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/shuffle/TieredResultPartition.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/BufferAccumulator.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/HashBufferAccumulator.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/SortBufferAccumulator.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/TieredStorageProducerClient.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/TieredStorageSortBuffer.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/TestingBufferAccumulator.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/HashBufferAccumulatorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/SortBufferAccumulatorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/TieredStorageSortBufferTest.java
*Implement the SortBufferAccumulator for the tiered storage*
- *Implement the SortBufferAccumulator for the tiered storage*
This change will add tests.
=> [FLINK-32283][network] Implement the SortBufferAccumulator for the tiered storage

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlToOperationConverter.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/hint/OptionsHintTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/hint/OptionsHintTest.scala
This is a backport pr for release-1.17
=> [FLINK-32447][table-planner] Fix missing table hints when they inside a view referenced by an external query

flink-python/pyflink/table/catalog.py, flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/procedure/ProcedureContext.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/annotation/ProcedureHint.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/annotation/ProcedureHints.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/Catalog.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/exceptions/ProcedureNotExistException.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/procedures/Procedure.java
Add base interfaces for call procedure proposed in https://cwiki.apache.org/confluence/display/FLINK/FLIP-311%3A+Support+Call+Stored+Procedure
Add base interfaces
N/A …
=> [FLINK-32351][table] Introduce base interfaces for call procedure

flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/Catalog.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogTable.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/DefaultCatalogTable.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/ResolvedCatalogTable.java
*Introduce base interfaces for time travel. *
- Add getTable(ObjectPath, long timestamp)  method in Catalog interface.
- Add getSnapshot() method in CatalogBaseTable.
Just introduce some interface declarations, testing may not be necessary at the moment.
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)   
=> [FLINK-32473] Introduce base interfaces for time travel

flink-end-to-end-tests/run-nightly-tests.sh
=> [FLINK-32370][tests] Ignore logged exceptions in JDBC driver e2e test

flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
The idea is that you can define a helper method that returns a base builder which you can further customize.
=> [FLINK-32359][tests] Accept mandatory args in constructor

flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesHaServicesFactory.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesMultipleComponentLeaderElectionHaServices.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesMultipleComponentLeaderElectionHaServicesFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/AbstractHaServices.java, flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/HighAvailabilityServicesUtils.java, flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/zookeeper/ZooKeeperClientHAServices.java, flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/zookeeper/ZooKeeperMultipleComponentLeaderElectionHaServices.java, flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/ZooKeeperMultipleComponentLeaderElectionDriver.java, flink-runtime/src/main/java/org/apache/flink/runtime/util/ZooKeeperUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/AbstractHaServicesTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/leaderretrieval/ZooKeeperLeaderRetrievalTest.java, flink-tests/src/test/java/org/apache/flink/test/runtime/leaderelection/ZooKeeperLeaderElectionITCase.java
* https://github.com/apache/flink/pull/22844
* === THIS PR === FLINK-32409
* …
=> [FLINK-32409][runtime] Makes DefaultLeaderElectionService not rely on MultipleComponentLeaderElectionDriverAdapter anymore

docs/content.zh/docs/dev/table/sqlClient.md, docs/content/docs/dev/table/sqlClient.md
=> [hotfix][docs] Fix incorrect example of user-defined function.

flink-runtime/src/main/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStore.java
=> [FLINK-31035] add warn info to user when NoNodeException happend

tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/licensecheck/JarFileChecker.java
Add one more filter to suppress false positive.
Trivial.
Semantically. I don't find a way to run the check locally properly..
=> [FLINK-32585] Filter javax.xml.bind:jaxb-api false positive for Pulsar connector

flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackendTest.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogStateDiscardTest.java, flink-test-utils-parent/flink-test-utils/pom.xml, flink-test-utils-parent/flink-test-utils/src/test/java/org/apache/flink/state/benchmark/RescalingBenchmark.java, flink-test-utils-parent/flink-test-utils/src/test/java/org/apache/flink/state/benchmark/RescalingBenchmarkBuilder.java, flink-test-utils-parent/flink-test-utils/src/test/java/org/apache/flink/state/benchmark/RescalingBenchmarkTest.java, flink-test-utils-parent/flink-test-utils/src/test/java/org/apache/flink/state/benchmark/StateBackendBenchmarkUtils.java, flink-test-utils-parent/flink-test-utils/src/test/java/org/apache/flink/state/benchmark/StateBackendBenchmarkUtilsTest.java
- Supports ChanglogStateBackend Benchmark. Will also prepare a related pr in flink-benchmarks repo.
- Move benchmark utils from rocksdb repo to flink-test-util.
- Add Changelog supports in StateBenchmarkBase.
This change is already covered by existing tests, such as `StateBackendBenchmarkUtilsTest`.
=> [FLINK-23484][benchmark] Supports base benchmark for ChangelogStateBackend

docs/data/sql_functions.yml, docs/data/sql_functions_zh.yml, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/rules/logical/WrapJsonAggFunctionArgumentsRuleTest.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/WrapJsonAggFunctionArgumentsRuleTest.xml
This is a backport pr of FLINK-32457's subtask-1
=> [FLINK-32457][table-planner] Add test cases of unsupported usage for JSON_OBJECTAGG & JSON_ARRAYAGG and also update docs

docs/content/docs/dev/table/tableApi.md
scan is misspelled as scane
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (don't know)
- The S3 file system connector: (don't know)
=> [hotfix][docs] fix typo in table api operations

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/physical/stream/StreamPhysicalGroupAggregateRule.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/physical/stream/StreamPhysicalWindowAggregateRule.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/WindowUtil.scala, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/agg/WindowAggregateTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/agg/WindowAggregateTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/WindowAggregateITCase.scala
This is a backport pr of FLINK-32578 to release-1.17
=> [FLINK-32578][table-planner] Fix wrong plan which group by window time columns on a proctime window operator may result hang for ever

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/GenericInMemoryCatalogStore.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/GenericInMemoryCatalogStoreFactory.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/GenericInMemoryCatalogStoreFactoryOptions.java, flink-table/flink-table-api-java/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/GenericInMemoryCatalogStoreFactoryTest.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/GenericInMemoryCatalogStoreTest.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/AbstractCatalogStore.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogDescriptor.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogStore.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/CatalogStoreFactory.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/FactoryUtil.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/factories/CatalogStoreFactoryTest.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/factories/FactoryUtilTest.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/factories/TestCatalogStoreFactory.java, flink-table/flink-table-common/src/test/resources/META-INF/services/org.apache.flink.table.factories.Factory
*Introduce some base interfaces for CatalogStore*
- *Introduce CatalogStore Interface*
- *Introduce CatalogStoreFactory for create CatalogStore*
- *Introduce GenericInMemoryCatalogStore and GenericInMemoryCatalogStoreFactory*
Add some unit test to test InMemoryCatalogStore and InMemoryCatalogStoreFactory …
=> [FLINK-32428][table] Introduce base interfaces for CatalogStore

docs/data/sql_functions.yml, docs/data/sql_functions_zh.yml, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/WrapJsonAggFunctionArgumentsRule.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/JsonAggregationFunctionsITCase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/rules/logical/WrapJsonAggFunctionArgumentsRuleTest.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/WrapJsonAggFunctionArgumentsRuleTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/SortAggITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/AggregateITCase.scala
cp  FLINK-32456 to  release-1.17
=> [FLINK-32456][table-planner] Support JSON_OBJECTAGG & JSON_ARRAYAGG use with other aggregate functions

flink-end-to-end-tests/test-scripts/common_kubernetes.sh, tools/ci/maven-utils.sh
1.17 backport of parent PR #23042
=> [BP-1.17][FLINK-32632][test] Fixes Minikube/cri-dockerd issue

flink-end-to-end-tests/test-scripts/common_kubernetes.sh, tools/ci/maven-utils.sh
1.16 backport of parent PR https://github.com/apache/flink/pull/23042
=> [BP-1.16][FLINK-32632][test] Fixes Minikube/cri-dockerd issue

docs/layouts/shortcodes/generated/all_taskmanager_network_section.html, docs/layouts/shortcodes/generated/netty_shuffle_environment_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/NettyShuffleEnvironmentOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/NettyShuffleEnvironment.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/NettyShuffleServiceFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/ResultPartitionFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/InputGateSpecUtils.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/common/TieredStorageConfiguration.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/shuffle/TieredInternalShuffleMaster.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/shuffle/TieredResultPartition.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/shuffle/TieredResultPartitionFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/NettyShuffleMaster.java, flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/NettyShuffleUtils.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/NettyShuffleEnvironmentConfiguration.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/ResultPartitionBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/ResultPartitionFactoryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/GateBuffersSpecTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/shuffle/TieredResultPartitionTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/benchmark/SingleInputGateBenchmarkFactory.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/benchmark/StreamNetworkBenchmarkEnvironment.java, flink-tests/src/test/java/org/apache/flink/test/runtime/HybridShuffleITCase.java
*Introduce the configurations for tiered storage*
- *Introduce the configurations for tiered storage.*
=> [FLINK-31643][network] Introduce the configurations for tiered storage

docs/content.zh/docs/dev/table/sql/show.md, docs/content/docs/dev/table/sql/show.md
Add doc for show procedures statement.
Add doc for show procedures statement.
=> [FLINK-32460][doc] Add doc for show procedures statement

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/security/token/HiveServer2DelegationTokenProvider.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/security/token/HiveServer2DelegationTokenReceiver.java, flink-connectors/flink-connector-hive/src/main/resources/META-INF/services/org.apache.flink.core.security.token.DelegationTokenProvider, flink-connectors/flink-connector-hive/src/main/resources/META-INF/services/org.apache.flink.core.security.token.DelegationTokenReceiver, flink-connectors/flink-connector-hive/src/main/resources/META-INF/services/org.apache.hadoop.security.token.TokenIdentifier, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/security/token/HiveServer2DelegationTokenProviderITCase.java, flink-connectors/flink-connector-hive/src/test/resources/test-hive-delegation-token/hive-site.xml, flink-runtime/src/main/java/org/apache/flink/runtime/hadoop/HadoopUserUtils.java, flink-runtime/src/main/java/org/apache/flink/runtime/security/token/hadoop/HadoopFSDelegationTokenProvider.java, flink-runtime/src/test/java/org/apache/flink/runtime/hadoop/HadoopUserUtilsITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/security/token/hadoop/HadoopFSDelegationTokenProviderITCase.java
Add Hive delegation token support
Add HiveDelegationTokenProvider
Add HiveDelegationTokenReceiver
Add HiveDelegationTokenProvider into the META-INFO service registration
Add HiveDelegationTokenReceiver into the META-INFO service registration
As done for Hbase in https://github.com/apache/flink/pull/21140, manually tests on Yarn, detailed: [Test Gist](https://gist.github.com/jiaoqingbo/99564342ab6576869cfe1961a9e76ed4) …
=> [FLINK-32223][runtime][security] Add Hive delegation token support

docs/content.zh/docs/dev/datastream/event-time/generating_watermarks.md, docs/content/docs/dev/datastream/event-time/generating_watermarks.md, flink-core/src/main/java/org/apache/flink/api/common/eventtime/WatermarkStrategy.java
Remove the beta for watermark alignment at doc
=> [FLINK-32705][connectors/common] Remove the beta for watermark alignment

flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java
The `AdaptiveScheduler` requires resources to be available before starting the job. The previous version of the test didn't provide these resources which left the scheduler in `WaitingForResources` state. That stage doesn't perform checkpoint creation for obvious reasons.
* Adds test resources to test
* Test run with `AdaptiveScheduler` enabled performed. …
=> [FLINK-32662][test] Fixes JobMasterTest#testRetrievingCheckpointStats with the AdaptiveScheduler

docs/layouts/shortcodes/generated/all_jobmanager_section.html, docs/layouts/shortcodes/generated/job_manager_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/JobManagerOptions.java
Fix typo in JobManagerOptions，change Dictionary to Directory
=> [hotfix] Fix typo in JobManagerOptions

flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/ParquetVectorizedInputFormat.java, flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/ParquetColumnarRowInputFormatTest.java
From the improvement [FLINK-23715](https://issues.apache.org/jira/browse/FLINK-23715), Flink use a collection named `unknownFieldsIndices` to track the nonexistent fields, and it is kept inside the `ParquetVectorizedInputFormat`, and applied to all parquet files under given path.
However, some fields may only be nonexistent in some of the historical parquet files, while exist in latest ones. And based on `unknownFieldsIndices`, flink will always skip these fields, even thought they are existing in the later parquets. As a result, the value of all  fields will become empty when they are nonexistent in some historical parquet files.
This PR is going to make `unknownFieldsIndices` separate for each ParquetReader.
- *Make `unknownFieldsIndices` as a member variable of ParquetReader, which is …
=> [FLINK-29527][formats/parquet] Make unknownFieldsIndices work for single ParquetReader

flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/src/FileSourceTextLinesITCase.java
Fix FLINK-32144, fix the unstable tests in `FileSourceTextLinesITCase`
=> [FLINK-32144][connector/filesystem][test] Create a new minicluser instead of using MiniClusterExtension in tests that would kill JM/TM

flink-rpc/flink-rpc-akka-loader/src/main/java/org/apache/flink/runtime/rpc/pekko/PekkoRpcSystemLoader.java
Seems that we have not replaced the `flink-rpc-akka` module with `flink-rpc-pekko`, but the hint message has pointed to it. When we execute the command following the hint, the exception raises.
```
[ERROR] Could not find the selected project in the reactor: flink-rpc/flink-rpc-pekko
```
- Replace the "flink-rpc-pekko" in hint message with "flink-rpc-akka"
- …
=> [hotfix] Revert the hint message back to akka

docs/content.zh/docs/dev/table/sql/truncate.md, docs/content/docs/dev/table/sql/truncate.md
Add doc for truncate table statement
Add doc for truncate table statement
This change is a docs work without any test coverage.
=> [FLINK-32287][docs] Add doc for truncate table statement

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogManagerTest.java
Currently `CatalogManager` can load catalog from `CatalogStore`, but we cannot perform ddl for the loaded catalog. This pr aims to support these operations.
- Add catalog loaded from `CatalogStore` to `catalogs` in `CatalogManager`
- Get catalog from method `getCatalog` instead of `catalogs.get` for operations such as ddl and list tables/views
- Added test case `CatalogManagerTest.testExistingCatalogInStore` …
=> [FLINK-32747][table] Fix ddl operation for catalog which is loaded from CatalogStore

docs/content.zh/docs/dev/table/catalogs.md, docs/content/docs/dev/table/catalogs.md
*Add doc for catalog store*
* Add doc for catalog store* 
- If yes, how is the feature documented? ( docs)
=> [FLINK-32653][docs] Add doc for catalog store

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectSinkOperatorCoordinator.java
1.17 backport PR of parent PR #23180. No conflicts encountered while backporting.
=> [BP-1.17][FLINK-32751][runtime] Refactors close handling to CollectSinkOperatorCoordinator

flink-annotations/src/main/java/org/apache/flink/FlinkVersion.java
The PR is aiming to fix the failing build
=> [hotfix] Apply spotless

flink-runtime/src/test/java/org/apache/flink/runtime/rpc/TestingRpcGateway.java, flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/WebMonitorEndpointTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/history/ArchivedJsonTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/history/HistoryServerUtilsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/retriever/LeaderGatewayRetrieverTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/retriever/impl/RpcGatewayRetrieverTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/threadinfo/ThreadInfoRequestCoordinatorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/threadinfo/VertexThreadInfoTrackerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStoreTest.java
[FLINK-32857][JUnit5 Migration] Migrate the webmonitor and zookeeper packages of flink-runtime module to junit5
=> [FLINK-32857][JUnit5 Migration] Migrate the webmonitor and zookeeper packages of flink-runtime module to junit5

flink-runtime/src/test/java/org/apache/flink/runtime/testutils/PseudoRandomValueSelectorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/testutils/TestJvmProcess.java, flink-runtime/src/test/java/org/apache/flink/runtime/testutils/statemigration/TestType.java, flink-runtime/src/test/java/org/apache/flink/runtime/throughput/BufferDebloaterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/throughput/BufferSizeEMATest.java, flink-runtime/src/test/java/org/apache/flink/runtime/throughput/ThroughputCalculatorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/throwable/ThrowableClassifierTest.java
[FLINK-32856][JUnit5 Migration] Migrate the testutils, throughput and throwable packages of flink-runtime module to junit5
=> [FLINK-32856][JUnit5 Migration] Migrate the testutils, throughput and throwable packages of flink-runtime module to junit5

flink-runtime/src/test/java/org/apache/flink/runtime/memory/MemoryManagerConcurrentModReleaseTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/memory/MemoryManagerSharedResourcesTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/memory/MemoryManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/memory/MemorySegmentSimpleTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/memory/OpaqueMemoryResourceTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/memory/SharedResourcesTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/memory/UnsafeMemoryBudgetTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/messages/CheckpointMessagesTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/messages/GenericMessageTester.java, flink-runtime/src/test/java/org/apache/flink/runtime/messages/WebMonitorMessagesTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/messages/checkpoint/DeclineCheckpointTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/messages/webmonitor/MultipleJobsDetailsTest.java
[FLINK-32845][JUnit5 Migration] Migrate the memory and messages packages of flink-runtime module to junit5
=> [FLINK-32845][JUnit5 Migration] Migrate the memory and messages packages of flink-runtime module to junit5

flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/DefaultJobLeaderServiceTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/DefaultJobTableTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/NettyShuffleEnvironmentConfigurationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorExecutionDeploymentReconciliationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorMemoryConfigurationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorOperatorEventHandlingTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorPartitionLifecycleTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorRecoveryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorResourceUtilsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorSlotLifetimeTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorSubmissionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskManagerRunnerStartupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskManagerRunnerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/partition/PartitionTableTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/slot/DefaultTimerServiceTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/slot/FileSlotAllocationSnapshotPersistenceServiceTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotTableImplTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotTest.java
[FLINK-32855][flink-runtime][JUnit5 Migration] Module: The taskexecutor package of flink-runtime
[flink-runtime][JUnit5 Migration] Module: The taskexecutor package of flink-runtime
[flink-runtime][JUnit5 Migration] Module: The taskexecutor package of flink-runtime …
=> [FLINK-32855][flink-runtime][JUnit5 Migration] Module: The taskexecutor package of flink-runtime

flink-runtime/src/test/java/org/apache/flink/runtime/metrics/util/MetricUtilsTest.java
- Fix typo in MetricUtilsTest
- Update the parameter types of startRemoteMetricsRpcService in javadocs of `MetricUtilsTest#testStartMetricActorSystemRespectsThreadPriority()`
his change only affects the JavaDocs of the method
=> [hotfix][docs] Update the parameter types of startRemoteMetricsRpcService in javadocs

flink-connectors/flink-sql-connector-hive-2.3.9/pom.xml, flink-connectors/flink-sql-connector-hive-3.1.2/pom.xml
This is a backport for version 1.16. Please see #23166
=> [BP-1.16][FLINK-32760][Connectors/Hive] Reshade shaded parquet in flink-sql-connector-hive

flink-connectors/flink-sql-connector-hive-2.3.9/pom.xml, flink-connectors/flink-sql-connector-hive-3.1.3/pom.xml
This is a backport for version 1.17. Please see #23166
=> [BP-1.17][FLINK-32760][Connectors/Hive] Reshade shaded parquet in flink-sql-connector-hive

flink-connectors/flink-sql-connector-hive-2.3.9/pom.xml, flink-connectors/flink-sql-connector-hive-3.1.3/pom.xml
This is a backport for version 1.18. Please see #23166
=> [BP-1.18][FLINK-32760][Connectors/Hive] Reshade shaded parquet in flink-sql-connector-hive

flink-end-to-end-tests/test-scripts/common_kubernetes.sh
See https://github.com/apache/flink/pull/23235. This is backport for 1.18.
=> [BP-1.18][FLINK-32869][e2e] Fix Kubernetes tests on aarch64

flink-end-to-end-tests/test-scripts/common_kubernetes.sh
See https://github.com/apache/flink/pull/23235. This is backport for 1.17.
=> [BP-1.17][FLINK-32869][e2e] Fix Kubernetes tests on aarch64

flink-end-to-end-tests/test-scripts/common_kubernetes.sh
See https://github.com/apache/flink/pull/23235. This is backport for 1.16.
=> [BP-1.16][FLINK-32869][e2e] Fix Kubernetes tests on aarch64

flink-runtime/src/test/java/org/apache/flink/runtime/minicluster/MiniClusterITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/net/ConnectionUtilsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/net/SSLUtilsTest.java
Migrate minicluster and net related tests under flink-runtime module to junit5
Migrate  minicluster and net related tests under flink-runtime module to junit5
- Dependencies (does it add or upgrade a dependency): no 
=> [FLINK-32846][runtime][JUnit5 Migration] The minicluster and net package of flink-runtime module

flink-dist/src/main/flink-bin/kubernetes-bin/kubernetes-session.sh, flink-dist/src/main/flink-bin/yarn-bin/yarn-session.sh
Support env.java.opts.all & env.java.opts.cli config for starting Session cluster CLIs.
Append JVM args set by env.java.opts.all & env.java.opts.cli which are read from the flink-conf files.
Manually verified the change by running the relevant scripts. …
=> [FLINK-32980][scripts] Support env.java.opts.all & env.java.opts.cli config for starting Session cluster CLIs

flink-end-to-end-tests/run-nightly-tests.sh, flink-end-to-end-tests/test-scripts/test_streaming_examples.sh, flink-examples/flink-examples-build-helper/flink-examples-streaming-state-machine/pom.xml, flink-examples/flink-examples-streaming/pom.xml, flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/join/WindowJoin.java
Fix the issue that 4 out of 7 (MatrixVectorMul & Iteration & SessionWindowing & TopSpeedWindowing) Flink streaming examples cannot run because datagen connector is not packaged into the jars.
Package datagen connector into the self-contained example jars using Maven shade plugin.
- Verified that these examples in a local standalone cluster.
- Verified that the final jar does not contain any other classes besides connector-datagen and the target test classes.
- Added integrated tests to verify if all examples can be submitted successfully and verified that the tests failed before the fix and succeeded after the fix.
- The runtime …
=> [FLINK-32821][examples] Include flink-connector-datagen for streaming examples

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectSinkOperatorCoordinator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/SocketConnection.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/collect/CollectSinkOperatorCoordinatorTest.java
1.18 backport for parent PR #23296
=> [BP-1.18][FLINK-32751][collect] Fixes race condition between close and request handling processes in CollectSinkOperatorCoordinator

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/reuse/ScanReuser.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/reuse/ScanReuserUtils.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/optimize/ScanReuseTest.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/optimize/ScanReuseTest.xml
In class `ScanReuser`, we will re-build watermark spec after projection push down. However, for current code, it will get wrong index while try to find index in new source type.
- Adding ut tests
- Adding ut tests
- If yes, how is the feature documented? no docs
=> [FLINK-32952][table-planner] Fix scan reuse with readable metadata and watermark push down get wrong watermark error

flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobClientTest.java
Fix too strict exception evaluation in `BlobClientTest.testSocketTimeout` that was introduced unintentionally during the JUni4 -> JUnit5 migration.
Reverted the logic to use `ExceptionUtils` as it was before.
=> [FLINK-32987][tests] Fix exception handling for BlobClientTest.testSocketTimeout

docs/content.zh/docs/dev/python/faq.md, docs/content/docs/dev/python/faq.md, docs/static/downloads/setup-pyflink-virtual-env.sh
Fix the dead link to setup-pyflink-virtual-env.sh in https://nightlies.apache.org/flink/flink-docs-release-1.14/docs/dev/python/faq/
JIRA: FLINK-23632
Add back setup-pyflink-virtual-env.sh to fix dead link.
Manually built the document by running hugo locally. The script can be downloaded from the homepage. …
=> [FLINK-23632][docs] Fix the setup-pyflink-virtual-env.sh link

flink-end-to-end-tests/run-nightly-tests.sh, flink-end-to-end-tests/test-scripts/test_streaming_examples.sh, flink-examples/flink-examples-build-helper/flink-examples-streaming-state-machine/pom.xml, flink-examples/flink-examples-streaming/pom.xml, flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/join/WindowJoin.java
Backport for PR https://github.com/apache/flink/pull/23212
=> [BP-1.18][FLINK-32821][examples] Include flink-connector-datagen for streaming examples

docs/content.zh/docs/dev/table/catalogs.md, docs/content/docs/dev/table/catalogs.md
Fix doc for catalog modification listener
- Fix doc for catalog modification listener …
=> [FLINK-32968][table] Fix doc for catalog modification listener

flink-tests/src/test/java/org/apache/flink/test/checkpointing/CheckpointAfterAllTasksFinishedITCase.java
Fix the CheckpointAfterAllTasksFinishedITCase.testFailoverAfterSomeTasksFinished fails
- Make the test wait for all subtasks to be finished.
=> [FLINK-32996][Tests] Fix the CheckpointAfterAllTasksFinishedITCase.testFailoverAfterSomeTasksFinished fails

docs/layouts/shortcodes/generated/sql_client_configuration.html, docs/layouts/shortcodes/generated/table_config_configuration.html, flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/config/SqlClientOptions.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/config/TableConfigOptions.java
improve the option description with more precise content
-  SqlClientOptions
-  TableConfigOptions
=> [FLINK-30025][doc] improve the option description with more precise content

flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/aggfunctions/AggFunctionTestBase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/aggfunctions/BatchApproxCountDistinctAggFunctionTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/aggfunctions/FirstLastValueAggFunctionWithOrderTestBase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/aggfunctions/FirstValueAggFunctionWithOrderTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/aggfunctions/FirstValueAggFunctionWithoutOrderTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/aggfunctions/FirstValueWithRetractAggFunctionWithOrderTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/aggfunctions/FirstValueWithRetractAggFunctionWithoutOrderTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/aggfunctions/LagAggFunctionTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/aggfunctions/LastValueAggFunctionWithOrderTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/aggfunctions/LastValueAggFunctionWithoutOrderTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/aggfunctions/LastValueWithRetractAggFunctionWithOrderTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/aggfunctions/LastValueWithRetractAggFunctionWithoutOrderTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/aggfunctions/ListAggWithRetractAggFunctionTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/aggfunctions/ListAggWsWithRetractAggFunctionTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/aggfunctions/MaxWithRetractAggFunctionTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/aggfunctions/MinWithRetractAggFunctionTest.java
[FLINK-33031][table-planner][JUnit5 Migration] Module: flink-table-planner (AggFunctionTestBase)
JUnit5 Migration Module: flink-table-planner (AggFunctionTestBase)
=> [FLINK-33031][table-planner][JUnit5 Migration] Module: flink-table-planner (AggFunctionTestBase)

docs/content/docs/dev/table/catalogs.md, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/FileCatalogStoreFactoryOptions.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CommonCatalogOptions.java
Add some details to the catalog store docs.
- Some minor restructuring.
- Added file system details.
- Added separate configuration section for better visibility.
- More details config options descriptions.
=> [BP-1.18][FLINK-32796][docs] Extend catalog store documentation

docs/content/docs/dev/table/catalogs.md, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/FileCatalogStoreFactoryOptions.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CommonCatalogOptions.java
Add some details to the catalog store docs.
- Some minor restructuring.
- Added file system details.
- Added separate configuration section for better visibility.
- More details config options descriptions.
=> [FLINK-32796][docs] Extend catalog store documentation

docs/content.zh/docs/deployment/advanced/failure_enrichers.md, docs/content/docs/deployment/advanced/failure_enrichers.md
[https://issues.apache.org/jira/browse/FLINK-31889](https://issues.apache.org/jira/browse/FLINK-31889)
FailureEnrichers documentation
=> [FLINK-31889] Add documentation for implementing/loading enrichers

flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/utils/JavaUserDefinedAggFunctions.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/AggregateITCase.scala, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/typeutils/TypeCheckUtils.java
cherry-pick from master
cp pr
- If yes, how is the feature documented?  no docs
=> [FLINK-33063][table-runtime] Fix udaf with complex user defined pojo object throw error while generate record equaliser

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/GreatestLeastFunctionsITCase.java
This is a cherry-pick bakport of https://github.com/apache/flink/pull/23345 to 1.16
=> [BP-1.16][FLINK-33010][table] GREATEST/LEAST should work with other functions as input 

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/GreatestLeastFunctionsITCase.java
This is a cherry-pick backport of https://github.com/apache/flink/pull/23345 to 1.17
=> [BP-1.17][FLINK-33010][table] GREATEST/LEAST should work with other functions as input

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/GreatestLeastFunctionsITCase.java
This is a cherry-pick bakport of https://github.com/apache/flink/pull/23345 to 1.18
=> [BP-1.18][FLINK-33010][table] GREATEST/LEAST should work with other functions as input

flink-runtime/src/test/java/org/apache/flink/runtime/query/KvStateLocationRegistryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/query/KvStateLocationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/query/KvStateRegistryTest.java
Migrate flink-runtime/query tests to JUnit5.
=> [FLINK-32848][tests][JUnit5 migration] Migrate flink-runtime/query tests to JUnit5

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointStatsTracker.java
This adds a DEBUG level log message that contains all checkpoint stats on every completed/failed checkpoint. A stop-gap solution until we come up with a proper way to expose those stats as metrics somewhere (FLINK-23411).
I manually checked log output in some of the ITCases:
```
8299 [jobmanager-io-thread-10] DEBUG org.apache.flink.runtime.checkpoint.CheckpointStatsTracker [] - CheckpointStatistics (for jobID=cf70776f3762dd273961bd57a2dbdc62, jobName=Flink Streaming Job) dump = {"className":"completed","id":2,"status":"COMPLETED","is_savepoint":false,"savepointFormat":null,"trigger_timestamp":1694452019812,"latest_ack_timestamp":1694452019823,"checkpointed_size":0,"state_size":0,"end_to_end_duration":11,"alignment_buffered":0,"processed_data":0,"persisted_data":0,"num_subtasks":10,"num_ack …
```
=> [FLINK-33071][metrics,checkpointing] Log a json dump of checkpoint statistics when checkpoint completes or fails

flink-runtime/src/test/java/org/apache/flink/runtime/shuffle/NettyShuffleUtilsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/shuffle/ShuffleMasterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/shuffle/ShuffleServiceLoaderTest.java
Migrate flink-runtime/shuffle tests to JUnit5.
=> [FLINK-32848][tests][JUnit5 migration] Migrate flink-runtime/shuffle tests to JUnit5

flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ExecutionGraphTestUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/FinalizeOnMasterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/DescriptiveStatisticsHistogramTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/MetricRegistryImplTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/ReporterSetupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/ThresholdMeterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/TimerGaugeTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/dump/MetricDumpSerializerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/dump/MetricDumpTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/dump/MetricQueryServiceTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/filter/DefaultMetricFilterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/AbstractMetricGroupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/FrontMetricGroupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/InternalOperatorGroupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/JobManagerGroupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/JobManagerJobGroupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/JobManagerOperatorGroupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/MetricGroupRegistrationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/MetricGroupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/TaskIOMetricGroupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/TaskManagerGroupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/TaskManagerJobGroupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/TaskManagerMetricGroupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/TaskMetricGroupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/util/MetricUtilsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/utils/SystemResourcesCounterTest.java
Migrate metrics related tests under flink-runtime module to junit5
Migrate  metrics related tests under flink-runtime module to junit5
- Dependencies (does it add or upgrade a dependency): no 
=> [FLINK-32846][runtime][JUnit5 Migration] The metrics package of flink-runtime module

docs/content.zh/docs/deployment/overview.md, docs/content/docs/deployment/overview.md
- https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/deployment/overview/#vendor-solutions …
=> [hotfix][docs] Update KDA to MSF in vendor solutions docs (1.15)

docs/content.zh/docs/deployment/overview.md, docs/content/docs/deployment/overview.md
- https://nightlies.apache.org/flink/flink-docs-release-1.17/docs/deployment/overview/#vendor-solutions …
=> [hotfix][docs] Update KDA to MSF in vendor solutions docs (1.17)

docs/content.zh/docs/deployment/overview.md, docs/content/docs/deployment/overview.md
- https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/deployment/overview/#vendor-solutions …
=> [hotfix][docs] Update KDA to MSF in vendor solutions docs (1.16)

docs/content.zh/docs/deployment/overview.md, docs/content/docs/deployment/overview.md
- https://nightlies.apache.org/flink/flink-docs-release-1.18/docs/deployment/overview/#vendor-solutions …
=> [hotfix][docs] Update KDA to MSF in vendor solutions docs (1.18)

docs/content.zh/docs/deployment/overview.md, docs/content/docs/deployment/overview.md
- https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/overview/#vendor-solutions …
=> [hotfix][docs] Update KDA to MSF in vendor solutions docs

flink-fs-tests/src/test/java/org/apache/flink/hdfstests/HDFSTest.java, flink-runtime/src/main/java/org/apache/flink/runtime/blob/BlobStoreService.java, flink-runtime/src/main/java/org/apache/flink/runtime/blob/FileSystemBlobStore.java, flink-runtime/src/main/java/org/apache/flink/runtime/blob/VoidBlobStore.java, flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/ClusterEntrypoint.java, flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/AbstractHaServices.java, flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/HighAvailabilityServices.java, flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/nonha/AbstractNonHaServices.java, flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniCluster.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobCacheCorruptionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobCacheRecoveryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobCacheRetriesTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobCacheSuccessTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobServerCorruptionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobServerGetTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobServerRecoveryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/AbstractDispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/entrypoint/ClusterEntrypointTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/execution/librarycache/BlobLibraryCacheRecoveryITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/AbstractHaServicesTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/TestingHighAvailabilityServices.java, flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/TestingHighAvailabilityServicesBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedHaServicesTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/nonha/standalone/StandaloneHaServicesTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/leaderretrieval/ZooKeeperLeaderRetrievalTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/ResourceManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskManagerRunnerConfigurationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskManagerRunnerStartupTest.java, flink-tests/src/test/java/org/apache/flink/test/recovery/JobManagerHAProcessFailureRecoveryITCase.java, flink-tests/src/test/java/org/apache/flink/test/recovery/ProcessFailureCancelingITCase.java
[FLINK-32445][runtime] Refactor BlobStoreService's closeAndCleanupAllData to cleanupAllData
We might want to refactor BlobStore.closeAndCleanupAllData: It doesn't close any resources (and doesn't need to). Therefore, renaming the interfaces method to cleanAllData seems to be more appropriate.
This enables us to remove redundant code in AbstractHaServices.closeAndCleanupAllData and AbstractHaServices.close …
=> [FLINK-32445][runtime] Refactor BlobStoreService's closeAndCleanupAllData to cleanupAllData

docs/layouts/shortcodes/generated/akka_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/AkkaOptions.java
Replace Akka with Pekko in the description of "pekko.ssl.enabled"
This change is a trivial rework on config description.
=> [FLINK-33205][config] Replace Akka with Pekko in the description of "pekko.ssl.enabled"

docs/layouts/shortcodes/generated/environment_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/CoreOptions.java, flink-dist/src/main/flink-bin/bin/config.sh, flink-dist/src/main/flink-bin/conf/log4j-cli.properties, flink-dist/src/main/flink-bin/conf/log4j-console.properties, flink-dist/src/main/flink-bin/conf/log4j-session.properties, flink-dist/src/main/flink-bin/conf/log4j.properties, flink-dist/src/main/flink-bin/conf/logback-console.xml, flink-dist/src/main/flink-bin/conf/logback-session.xml, flink-dist/src/main/flink-bin/conf/logback.xml
Make root logger level configurable for better usability.
Introduce a new config `env.log.level` that defines the level of the root logger with a default value of `INFO`.
Verified by starting clusters with different config values and checking the logs in the log output.
- Does this …
=> [FLINK-33166][core][config] Make root logger level configurable

flink-architecture-tests/flink-architecture-tests-base/src/test/java/PredicatesTest.java
This is a minor checkstyle violation fix
=> [hotfix] Fix predicates test imports

pom.xml
1.18 backport of parent PR #23529
=> [BP-1.18][FLINK-33291][build] Sets the enforced range for Maven and JDK within the release profile

flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientTest.java
[FLINK-33116][tests] Fix CliClientTest.testCancelExecutionInteractiveMode fails with NPE
```shell
Sep 18 02:26:15 02:26:15.743 [ERROR] org.apache.flink.table.client.cli.CliClientTest.testCancelExecutionInteractiveMode  Time elapsed: 0.1 s  <<< ERROR!
Sep 18 02:26:15 java.lang.NullPointerException
Sep 18 02:26:15 	at org.apache.flink.table.client.cli.CliClient.closeTerminal(CliClient.java:284)
Sep 18 02:26:15 	at org.apache.flink.table.client.cli.CliClient.close(CliClient.java:108)
Sep 18 02:26:15 	at org.apache.flink.table.client.cli.CliClientTest.testCancelExecutionInteractiveMode(CliClientTest.java:314)
Sep 18 02:26:15 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
```
The CliClient is not thread-safe: The close call fails with a NullPointerException …
=> [FLINK-33116][tests] Fix CliClientTest.testCancelExecutionInteractiveMode fails with NPE

flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientTest.java
[FLINK-33116][tests] Fix CliClientTest.testCancelExecutionInteractiveMode fails with NPE
```shell
Sep 18 02:26:15 02:26:15.743 [ERROR] org.apache.flink.table.client.cli.CliClientTest.testCancelExecutionInteractiveMode  Time elapsed: 0.1 s  <<< ERROR!
Sep 18 02:26:15 java.lang.NullPointerException
Sep 18 02:26:15 	at org.apache.flink.table.client.cli.CliClient.closeTerminal(CliClient.java:284)
Sep 18 02:26:15 	at org.apache.flink.table.client.cli.CliClient.close(CliClient.java:108)
Sep 18 02:26:15 	at org.apache.flink.table.client.cli.CliClientTest.testCancelExecutionInteractiveMode(CliClientTest.java:314)
Sep 18 02:26:15 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
```
The CliClient is not thread-safe: The close call fails with a NullPointerException …
=> [FLINK-33116][tests][release-1.18] Fix CliClientTest.testCancelExecutionInteractiveMode fails with NPE

tools/azure-pipelines/build-apache-repo.yml
1.18 backport for parent PR #23571
=> [BP-1.18][FLINK-33342][ci] Adds target version to Java 17 CI build

docs/content.zh/docs/dev/table/data_stream_api.md, docs/content/docs/dev/table/data_stream_api.md
SQL：SELECT UPPER(f0) FROM InputTable，so the result should be in uppercase.
=> [hotfix][docs] Fix query results in data_stream_api

flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java
1.17 backport for parent PR #23578
=> [BP-1.17][FLINK-33346][runtime][test] Removes timeout

flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java
1.18 backport for parent PR #23578
=> [BP-1.18][FLINK-33346][runtime][test] Removes timeout

docs/content.zh/_index.md, docs/content.zh/release-notes/flink-1.18.md, docs/content/_index.md, docs/content/release-notes/flink-1.18.md
Unchanged backport of #23527 on release-1.18
=> [BP-1.18][FLINK-33274][release] Add release note for version 1.18

flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerConfiguration.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotTable.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotTableImpl.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorOperatorEventHandlingTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorSubmissionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotTableImplTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/slot/TestingTaskSlotTable.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/slot/ThreadSafeTaskSlotTable.java
[FLINK-27432][runtime] Replace Time with Duration in TaskSlotTable
[FLINK-27432][runtime] Replace Time with Duration in TaskSlotTable
=> [FLINK-27432][runtime] Replace Time with Duration in TaskSlotTable

flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/rest/OperationRelatedITCase.java
[FLINK-32661][sql-gateway] Fix unstable OperationRelatedITCase.testOperationRelatedApis
The operation execution is asynchronous and the status will only be updated from Pending to Running after calling from the runBefore method.
```
Jul 20 04:23:49 org.opentest4j.AssertionFailedError: 
Jul 20 04:23:49 
Jul 20 04:23:49 Expecting actual's toString() to return:
Jul 20 04:23:49   "PENDING"
Jul 20 04:23:49 but was:
Jul 20 04:23:49   "RUNNING"
Jul 20 04:23:49 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Jul 20 04:23:49 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
Jul 20 04:23:49 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
Jul 20 04:23:49 	at …
```
=> [FLINK-32661][sql-gateway] Fix unstable OperationRelatedITCase.testOperationRelatedApis

docs/data/sql_functions_zh.yml
Fix typo in function documentation
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end …
=> [FLINK-33393][doc] Fix typo in function documentation

flink-end-to-end-tests/test-scripts/common_kubernetes.sh
*(We could make CI fail earlier when download fails.)*
- *modify common_kubernetes.sh*
=> [FLINK-32107] [Tests] Kubernetes test failed because ofunable to establish ssl connection to github on AZP

flink-end-to-end-tests/test-scripts/common_kubernetes.sh
* Backport of https://github.com/apache/flink/pull/23528 to release-1.18，We could make CI fail earlier when download fails.*
- * modify common_kubernetes.sh；retry*
*This change is already covered by existing tests.*
=>  [BP-1.18][FLINK-32107][Tests]  Kubernetes test failed because ofunable to establish ssl connection to github on AZP

flink-end-to-end-tests/test-scripts/common_kubernetes.sh
* Backport of https://github.com/apache/flink/pull/23528 to release-1.17，We could make CI fail earlier when download fails.*
- *modify common_kubernetes.sh；retry and make CI fail earlier*
- *This change is already covered by existing tests.*
=> [BP-1.17][FLINK-32107][Tests] Kubernetes test failed because ofunable to establish ssl connection to github on AZP

pom.xml
The PR to upgrade testcontainers to 1.19.1
pom.xml
=> [FLINK-33300] Upgrade testcontainers from 1.18.3 to 1.19.1

flink-runtime-web/web-dashboard/src/app/interfaces/job-exception.ts, flink-runtime-web/web-dashboard/src/app/interfaces/job-vertex.ts, flink-runtime-web/web-dashboard/src/app/pages/job/exceptions/job-exceptions.component.html, flink-runtime-web/web-dashboard/src/app/pages/job/overview/subtasks/job-overview-drawer-subtasks.component.html, flink-runtime-web/web-dashboard/src/app/pages/job/overview/subtasks/job-overview-drawer-subtasks.component.ts, flink-runtime-web/web-dashboard/src/app/pages/job/overview/taskmanagers/job-overview-drawer-taskmanagers.component.html, flink-runtime-web/web-dashboard/src/app/pages/job/overview/taskmanagers/job-overview-drawer-taskmanagers.component.ts
Update Web UI to adopt the new "endpoint" field in REST API introduced in [FLINK-33147](https://issues.apache.org/jira/browse/FLINK-33147).
Update Web UI to adopt the new "endpoint" field in REST API in the following places:
- Job vertex subtask details
- Job vertex task manager details
- Job exceptions
Manually verified the change in a local cluster setup.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** …
=> [FLINK-33148] Update Web UI to adopt the new "endpoint" field in REST API

tools/azure-pipelines/jobs-template.yml, tools/ci/stage.sh
1.18 backport PR of parent PR #23712
=> [BP-1.18][FLINK-33276][ci] Merges connect_1 and connect_2 stages into a single one

pom.xml
Updating the japicmp base version. Verification of API changes happened in FLINK-32927
=> [BP-1.18][FLINK-32913][tests] Updates base version for japicmp check

flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTemporalJoinITCase.java
[FLINK-33551] Fix HiveTemporalJoinITCase.testProcTimeTemporalJoinHiveTable nightly CI fails
During the migration of Junit5, some of the remaining codes were not deleted, resulting in the problem.
https://github.com/apache/flink/pull/23349/files#diff-1e88862e59ad54f8c596e5e56f126fec6a09768bee986c9547d14d2add1e048bR109-R112
```mvn test -Phadoop3-tests,hive3 -Dflink.hadoop.version=3.2.3 -Dtest=org.apache.flink.connectors.hive.HiveTemporalJoinITCase``` …
=> [FLINK-33551][Connectors/Hive] Fix HiveTemporalJoinITCase.testProcTimeTemporalJoinHiveTable nightly CI fails

docs/layouts/shortcodes/connector_artifact.html, docs/layouts/shortcodes/py_connector_download_link.html, docs/layouts/shortcodes/sql_connector_download_table.html
Unchanged backport of https://github.com/apache/flink/pull/23730
=> [FLINK-33567][BP 1.18] Only display connector download links if its available

docs/layouts/shortcodes/connector_artifact.html, docs/layouts/shortcodes/py_connector_download_link.html, docs/layouts/shortcodes/sql_connector_download_table.html
Unchanged backport of https://github.com/apache/flink/pull/23730
=> [FLINK-33567][BP 1.17] Only display connector download links if its available

docs/config.toml
*Fix missing 1.18 doc link in https://nightlies.apache.org/flink/flink-docs-master/*
- *Fix missing 1.18 doc link*
This change is a  doc fix without any test coverage. …
=> [FLINK-33537][docs] Fix missing 1.18 doc link

pom.xml
Remove unnecessary notes element in pom file
=> [hotfix][build] Remove unnecessary notes element in pom file

docs/layouts/shortcodes/connector_artifact.html
Fix issue in `connector_artifact` shortcode causing generation of corrupted layout when used in combination with `tabs`.
Removed indentations fixing generation of corrupted doc layout.
Can be verified by building the documentation locally.
=> [FLINK-33589][docs] Fix connector_artifact to prevent generation of broken layout

docs/content/docs/ops/monitoring/checkpoint_monitoring.md
fix typo in the docs
This change is a trivial typo fix without any test coverage.
=> [hotfix][docs] fix typo in checkpoint_monitoring.md

flink-optimizer/src/main/java/org/apache/flink/optimizer/operators/AbstractJoinDescriptor.java, flink-optimizer/src/main/java/org/apache/flink/optimizer/operators/CoGroupDescriptor.java, flink-optimizer/src/main/java/org/apache/flink/optimizer/operators/OperatorDescriptorDual.java
remove duplicated code
This change is already covered by existing tests, such as `CoGroupGlobalPropertiesCompatibilityTest`.
=> [hotfix][optimizer] remove duplicated code

flink-optimizer/src/main/java/org/apache/flink/optimizer/operators/OperatorDescriptorDual.java
fix the spotless violation
GitHub PR
=> [hotfix][doc] fix spotless violation

docs/content.zh/docs/dev/datastream/fault-tolerance/checkpointing.md
fix link in the checkpointing doc
This change is a trivial doc fix without any test coverage.
=> [hotfix][doc] fix checkpoints link in checkpointing

flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/LocalInputPreferredSlotSharingStrategyTest.java
- [hotfix][Junit5 Migration] Upgrade the LocalInputPreferredSlotSharingStrategyTest to junit5
In order to simply the review of https://github.com/apache/flink/pull/23635 , and reuse some tests with LocalInputPreferredSlotSharingStrategyTest, I upgrade the LocalInputPreferredSlotSharingStrategyTest to junit5 in this hotfix PR.
=> [hotfix][Junit5 Migration] Upgrade the LocalInputPreferredSlotSharingStrategyTest to junit5

docs/content.zh/docs/dev/datastream/fault-tolerance/checkpointing.md
update doc in Chinese for 1. checkpoint storage, 2. unaligned checkpoints, 3. checkpoints with finished tasks
=> [FLINK-33651][Runtime][doc] update state checkpoins doc in Chinese 

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java
- Regarding the processing of JobName, `StreamExecutionEnvironment` ensures that the logic of `executeAsync` and `execute` is consistent.
This change has already taken effect in `execute`. …
=> [FLINK-33643][runtime] Allow StreamExecutionEnvironment's executeAsync API to use default JobName

flink-end-to-end-tests/flink-end-to-end-tests-sql/pom.xml, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/codegen/CreateTableAsITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/codegen/PlannerScalaFreeITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/codegen/SqlITCaseBase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/codegen/UsingRemoteJarITCase.java
Fix unstable tests of flink-end-to-end-tests-sql module
MINI-BATCH may exceed the latency of time, resulting result is unstable.
We made some modifications on the test, and the materialized final result was checked to avoid this problem.
Other problems caused by the same cause:
- [FLINK-31033]
- [FLINK-31141]
- [FLINK-32269] …
=> [FLINK-31339][tests] Fix unstable tests of flink-end-to-end-tests-sql module

.mvn/wrapper/maven-wrapper.properties, azure-pipelines.yml, docs/content.zh/docs/dev/configuration/maven.md, tools/azure-pipelines/build-apache-repo.yml, tools/azure-pipelines/build-nightly-dist.yml, tools/azure-pipelines/e2e-template.yml, tools/ci/maven-utils.sh
1.18 backport of parent PR #23689
=> [BP-1.18][FLINK-33501][ci] Makes use of Maven wrapper

flink-end-to-end-tests/flink-end-to-end-tests-sql/pom.xml, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/codegen/CreateTableAsITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/codegen/PlannerScalaFreeITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/codegen/SqlITCaseBase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/codegen/UsingRemoteJarITCase.java
Fix unstable tests of flink-end-to-end-tests-sql module
MINI-BATCH may exceed the latency of time, resulting result is unstable.
We made some modifications on the test, and the materialized final result was checked to avoid this problem.
Other problems caused by the same cause:
- [FLINK-31033]
- [FLINK-31141]
- [FLINK-32269] …
=> [BP-1.18][FLINK-31339][table][tests] Comparing with materialized result when mini-batch enabled to fix unstable sql e2e tests

flink-end-to-end-tests/flink-end-to-end-tests-sql/pom.xml, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/codegen/CreateTableAsITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/codegen/PlannerScalaFreeITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/codegen/SqlITCaseBase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/codegen/UsingRemoteJarITCase.java
Fix unstable tests of flink-end-to-end-tests-sql module
MINI-BATCH may exceed the latency of time, resulting result is unstable.
We made some modifications on the test, and the materialized final result was checked to avoid this problem.
Other problems caused by the same cause:
- [FLINK-31033]
- [FLINK-31141]
- [FLINK-32269] …
=> [BP-1.17][FLINK-31339][table][tests] Comparing with materialized result when mini-batch enabled to fix unstable sql e2e tests

docs/config.toml
Update flink doc version for 1.17.2 release
- change flink doc version
=> [hotfix][docs] Update minor version for 1.17.2 release

flink-architecture-tests/flink-architecture-tests-production/src/test/resources/archunit.properties, flink-architecture-tests/flink-architecture-tests-test/src/test/resources/archunit.properties, flink-connectors/flink-connector-base/src/test/resources/archunit.properties
=> [hotfix] improve comments in archunit.properties in common modules

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/RexNodeExtractor.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/utils/NestedProjectionUtilTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/utils/RexNodeExtractorTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/utils/RexNodeRewriterTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/utils/RexNodeTestBase.scala
Fix a bug that RexNodeExtractor#extractConjunctiveConditions throws an Exception when handle binary literal
cast `ByteString` to `byte[]` in RexNodeToExpressionConverter#visitLiteral
- Added a new test `testExtractCnfCondition` in `RexNodeExtractorTest`
=> [FLINK-33313][table] fix RexNodeExtractor#extractConjunctiveConditions throws an Exception when handle binary literal

flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/ParquetTimestampITCase.java, flink-table/flink-table-planner/src/test/resources/restore-tests/stream-exec-group-aggregate_1/group-aggregate-distinct-mini-batch/plan/group-aggregate-distinct-mini-batch.json, flink-table/flink-table-planner/src/test/resources/restore-tests/stream-exec-group-aggregate_1/group-aggregate-distinct/plan/group-aggregate-distinct.json, flink-table/flink-table-planner/src/test/resources/restore-tests/stream-exec-group-aggregate_1/group-aggregate-simple-mini-batch/plan/group-aggregate-simple-mini-batch.json, flink-table/flink-table-planner/src/test/resources/restore-tests/stream-exec-group-aggregate_1/group-aggregate-simple/plan/group-aggregate-simple.json, flink-table/flink-table-planner/src/test/resources/restore-tests/stream-exec-group-aggregate_1/group-aggregate-udf-with-merge-mini-batch/plan/group-aggregate-udf-with-merge-mini-batch.json, flink-table/flink-table-planner/src/test/resources/restore-tests/stream-exec-group-aggregate_1/group-aggregate-udf-with-merge/plan/group-aggregate-udf-with-merge.json, flink-table/flink-table-planner/src/test/resources/restore-tests/stream-exec-group-aggregate_1/group-aggregate-udf-without-merge-mini-batch/plan/group-aggregate-udf-without-merge-mini-batch.json, flink-table/flink-table-planner/src/test/resources/restore-tests/stream-exec-group-aggregate_1/group-aggregate-udf-without-merge/plan/group-aggregate-udf-without-merge.json, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/FsStreamingSinkITCaseBase.scala
*Fix GroupAggregate Restore Test*
- This commit ca1c7ce48127472a7c7965099f8a7227549f09df has updated the logic to generate the primary key name while generating the compiled plan
- This commit updates/regenerates the plans to have updated primary key names
- Related commit: 193b1c68976cdfbd66147278f23d7d427d9b5562
- *Existing restore tests verify the change*
- The S3 file …
=> [FLINK-33782] Fix GroupAggregate restore tests

flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/ByteBufUtilsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/CancelPartitionRequestTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/ClientTransportErrorHandlingTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/CreditBasedPartitionRequestClientHandlerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/CreditBasedSequenceNumberingViewReaderTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyBufferPoolTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyClientServerSslTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyClientTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyConnectionManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyMessageClientDecoderDelegateTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyMessageClientSideSerializationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyMessageServerSideSerializationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyPartitionRequestClientTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyServerFromPortRangeTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyTestUtil.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/PartitionRequestClientFactoryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/PartitionRequestQueueTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/PartitionRequestServerHandlerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/ServerTransportErrorHandlingTest.java
[FLINK-32850][flink-runtime][JUnit5 Migration] The io.network.netty package of flink-runtime module
[FLINK-32850][flink-runtime][JUnit5 Migration] The io.network.netty package of flink-runtime module
=> [FLINK-32850][flink-runtime][JUnit5 Migration] The io.network.netty package of flink-runtime module

flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/table/AggregateTest.scala
*Replace the usage of deprecated org.apache.flink.table.api.internal.BaseExpressions#cast(TypeInformation) with cast(DataType)*
* Cleanup usage of deprecated org.apache.flink.table.api.internal.BaseExpressions#cast(TypeInformation) *
* original unit test *
=> [FLINK-33779][table] Cleanup usage of deprecated BaseExpressions#cast

flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/CheckpointBarrierTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/reader/AbstractReaderTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/serialization/CheckpointSerializationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/serialization/EventSerializerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/serialization/PagedViewsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/serialization/SpanningRecordSerializationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/serialization/SpanningWrapperTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/writer/BroadcastRecordWriterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/writer/RecordWriterDelegateTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/writer/SubtaskStateMapperTest.java
[FLINK-32850][flink-runtime][JUnit5 Migration] The io.network.api package of flink-runtime module
[FLINK-32850][flink-runtime][JUnit5 Migration] The io.network.api package of flink-runtime module
=> [FLINK-32850][flink-runtime][JUnit5 Migration] The io.network.api package of flink-runtime module

flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterThrottlingTest.java
This pull request updates `AsyncSinkThrottlingTest` to use concurrent `TestSinkInitContextAnyThreadMailbox` due the concurrent nature of the test and to address CI stability issues.
- Updated  `AsyncSinkThrottlingTest` to use concurrent `TestSinkInitContextAnyThreadMailbox`
This change is a trivial rework for test suite, changes are verified by rerunning tests in debug mode. …
=> [FLINK-31472][Connectors/Base] Update AsyncSink Throttling test to use concurrent mailbox

flink-end-to-end-tests/test-scripts/common_ssl.sh
1.18 backport of parent PR #23961
No conflicts appeared during backport
=> [BP-1.18][FLINK-33902][ci] Adds -legacy to openssl command

flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/DefaultJobLeaderIdServiceTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/ResourceManagerHATest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/ResourceManagerJobMasterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/ResourceManagerPartitionLifecycleTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/ResourceManagerServiceImplTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/ResourceManagerTaskExecutorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/ResourceManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/StandaloneResourceManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/WorkerResourceSpecTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/active/ActiveResourceManagerFactoryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/active/ActiveResourceManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/active/WorkerCounterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/AbstractFineGrainedSlotManagerITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/BiDirectionalResourceToRequirementMappingTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/DeclarativeSlotManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/DefaultResourceTrackerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/DefaultSlotTrackerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/FineGrainedSlotManagerDefaultResourceAllocationStrategyITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/FineGrainedSlotManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/FineGrainedSlotManagerTestBase.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/FineGrainedTaskManagerRegistrationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/JobScopedResourceTrackerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotManagerUtilsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotStatusReconcilerTest.java
[runtime][JUnit5 Migration] The resourcemanager package of flink-runtime module
[runtime][JUnit5 Migration] The resourcemanager package of flink-runtime module …
=> [FLINK-32849][runtime][JUnit5 Migration] The resourcemanager package of flink-runtime module

flink-core/src/main/java/org/apache/flink/configuration/DelegatingConfiguration.java, flink-core/src/test/java/org/apache/flink/configuration/DelegatingConfigurationTest.java
The patch is BP for https://github.com/apache/flink/pull/24001
- Marked prefix as @Nonnull and adapted assignment about prefix  
- Fixed bug about methods removeKey & removeConfig
- DelegatingConfigurationTest#testRemoveKeyOrConfig
- Does this pull request introduce a new feature? (yes …
=> [FLINK-33947][configuration] Fix bugs about prefix attribute in the DelegatingConfiguration class.

flink-python/tox.ini
*This pull request will fix mypy error*
- *ignore google package import error*
- *current mypy tests*
=> [FLINK-34012][python] Fix mypy error

docs/content/docs/connectors/table/formats/overview.md
=> [hotfix][docs][table formats] Add protobuf format info to overview page

tools/azure-pipelines/debug_files_utils.sh, tools/azure-pipelines/uploading_watchdog.sh
1.18 backport for parent PR #24061
No conflicts appeared during backport.
=> [BP-1.18][FLINK-34047][ci] Makes uploading_watchdog.sh support Azure Pipelines and GitHub Actions

flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/ExprCodeGenerator.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/BridgingFunctionGenUtil.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/HashcodeITCase.java
Took over https://github.com/apache/flink/pull/23118 to cover the change with narrower scoped tests.
Added tests in HashcodeITCase …
=> [FLINK-32815] Implement internal HASHCODE function

tools/azure-pipelines/debug_files_utils.sh
1.18 backport PR for parent PR #23964 
No conflicts appeared during the backport.
=> [BP-1.18][FLINK-33906][ci] Makes debug files available for both, AzureCI and GitHub Actions

flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterTest.java
Refactor `checkLoggedSendTimesAreWithinBounds` for Async Sink, the test introduced static upper bound that was violated due to mailbox executer delays causing multiple CI fails.
The new test format introduces artificial delay prior to send calculation and uses test measured times as upper bounds.
- refactor `checkLoggedSendTimesAreWithinBounds` test case in `AsyncSinkWiterTest` …
=> [FLINK-27756] Refactor Async Sink send gauge test

flink-end-to-end-tests/test-scripts/test_file_sink.sh
1.18 backport PR for parent PR #24131
=> [BP-1.18][FLINK-34150][ci] Enables local file sink e2e tests in general CI setups

flink-end-to-end-tests/test-scripts/test_file_sink.sh
1.17 backport PR for parent PR https://github.com/apache/flink/pull/24131
=> [BP-1.17][FLINK-34150][ci] Enables local file sink e2e tests in general CI setups

pom.xml
Update japicmp configuration for 1.18.1
=> [FLINK-33844][doc] Update japicmp configuration for 1.18.1

docs/config.toml
=> [FLINK-33850][doc] Update minor version for 1.18.1 release

flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/table/TableAggregateITCase.scala
This PR fixes the unstable test case `TableAggregateITCase.testFlagAggregateWithOrWithoutIncrementalUpdate`. 
I attempted to reproduce the failure, but I have been unsuccessful in replicating the issue in the local environment. However, upon inspecting the table's maven log, I did identify some common attributes shared by the failed cases. It is worth noting that all the failures occurred when the state backend type was set to `HEAP`. 
I suspect that the issue may have arisen because I performed two checks within a single test case. This is likely problematic because the HEAP uses a shared statebackend directory within the test, whereas RocksDB generates a distinct one each time. Modifying the test should be able to resolve this issue.
```
18:30:10,490 [jobmanager-io-thread-21] INFO …
```
=> [FLINK-34115][table-planner] Fix unstable TableAggregateITCase.testFlagAggregateWithOrWithoutIncrementalUpdate

flink-table/flink-table-common/src/main/java/org/apache/flink/table/annotation/ArgumentHint.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/annotation/FunctionHint.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/annotation/ProcedureHint.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/BaseMappingExtractor.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/DataTypeExtractor.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/DataTypeTemplate.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/ExtractionUtils.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/FunctionSignatureTemplate.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/FunctionTemplate.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/TypeInferenceExtractor.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/extraction/TypeInferenceExtractorTest.java, flink-table/flink-table-planner/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java, flink-table/flink-table-planner/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/RexSetSemanticsTableCall.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/inference/OperatorBindingCallContext.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/inference/TypeInferenceOperandChecker.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlProcedureCallConverter.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/logical/FlinkLogicalTableFunctionScan.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestProcedureCatalogFactory.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlNodeToCallOperationTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/FunctionITCase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/ProcedureITCase.java
*1. Declare a new ArgumentHint to specify the name, type, and whether it is optional for an argument.
*2. Support named parameters for functions.
*3. Support named parameters for procedures.
- ntroduce a new ArgumentHint annotation
- Support named parameters for functions 
- Support named parameters for producers
test cases in FunctionITCase and ProcedureITCase to verify named parameters.
- Does …
=>  [FLINK-34055][table] Introduce a new annotation for named parameters 

docs/content.zh/docs/dev/table/hive-compatibility/hive-dialect/show.md, docs/content/docs/dev/table/hive-compatibility/hive-dialect/show.md
Fix typo in document
- Fix typo in document
N/A
N/A
N/A
=> [FLINK-34231][doc] fix typo in doc

docs/content.zh/docs/dev/table/functions/systemFunctions.md, docs/data/sql_functions.yml, docs/data/sql_functions_zh.yml
This pull request update the document sql_functions_zh.yml .
- Modify the sql_functions_zh.yml and sql_functions.yml 
This change is a document change without any test coverage.
=> [FLINK-31511][doc-zh] Update the document sql_functions_zh.yml and fix some parts in sql_functions.yml

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/transformations/SourceTransformationWrapper.java
Bugfix for FLINK-33263. Update the flink shaded guava version used in `SourceTransformationWrapper` to 32.
- Update the flink shaded guava version used in `SourceTransformationWrapper` to 32.
This change added tests and can be verified through CI progress. …
=> [FLINK-33263][bugfix][table-planner] Update the flink shaded guava version used to 32

flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/DefaultSlotPoolServiceSchedulerFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Executing.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerClusterITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
https://issues.apache.org/jira/browse/FLINK-33976
=> [FLINK-33976] AdaptiveScheduler cooldown period should be taken from JobManager's configuration

docs/content/docs/flinkDev/ide_setup.md
Make doc file ide_setup.md format better after e48abd38
=> [hotfix] Make doc ide_setup.md format better for code formatting

docs/content.zh/docs/deployment/ha/overview.md
[FLINK-26369][doc-zh] Translate the part zh-page mixed with not be translated.
=> [FLINK-26369][doc-zh] Translate the part zh-page mixed with not be translated.

docs/content.zh/docs/dev/table/sql/queries/hints.md, docs/content/docs/dev/table/sql/queries/hints.md
This pr is aims to update the query hint docs to clarify the resolution of conflicts in kv hint and list hint.
- update the query hint docs to clarify the resolution of conflicts in kv hint and list hint.
- The S3 file system connector:no
=> [FLINK-34034][docs] Update the query hint docs to clarify the resolution of conflicts in kv hint and list hint

flink-core/src/main/java/org/apache/flink/util/ExecutorUtils.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/resources/KubernetesLeaderElector.java
There was a test failure in [this build](https://github.com/XComp/flink/actions/runs/7745486791/job/21121947504#step:14:7309) which was testing FLINK-34333 (the 1.18 backport of FLINK-34007). `KubernetesLeaderElectorITCase.testMultipleKubernetesLeaderElectors` failed with the following error:
```
18:38:52,290 [KubernetesLeaderElector-ExecutorService-thread-1] ERROR io.fabric8.kubernetes.client.extended.leaderelection.LeaderElector [] - Exception occurred while releasing lock 'ConfigMapLock: default - kubernetesleaderelectoritcase-configmap-2e3f2dee-c41e-4f6f-830e-426018db34
a7 (406ed8e6-5cc6-4777-81b3-2ca706b83d72)' on cancel
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [ConfigMap]  with name: …
```
=> [FLINK-34007][k8s] Add graceful shutdown to KubernetesLeaderElector

flink-end-to-end-tests/test-scripts/test_file_sink.sh
1.18 backport PR for parent PR #24244
=> [BP-1.18][FLINK-34324][test] Makes all s3 related operations being declared and called in a single location

flink-core/src/main/java/org/apache/flink/api/connector/sink2/Sink.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperatorTestBase.java
[FLINK-34337][core] Sink.InitContextWrapper should implement metadataConsumer method
Sink.InitContextWrapper should implement metadataConsumer method.
If the metadataConsumer method is not implemented, the behavior of the wrapped WriterInitContext's metadataConsumer will be lost. …
=> [FLINK-34337][core] Sink.InitContextWrapper should implement metadataConsumer method

.github/actions/job_init/action.yml, flink-end-to-end-tests/test-scripts/test-runner-common.sh
1.18 backport PR of parent PR #24277
=> [BP-1.18][FLINK-34360][ci] Adds cleanup to job_init action

.github/actions/job_init/action.yml, flink-end-to-end-tests/test-scripts/test-runner-common.sh
1.19 backport PR of parent PR https://github.com/apache/flink/pull/24277
=> [BP-1.19][FLINK-34360][ci] Adds cleanup to job_init action

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/allocator/SlotSharingSlotAllocator.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/allocator/SlotSharingSlotAllocatorTest.java
Backporting FLINK-33960 to 1.18
=> [FLINK-33960][Scheduler] Fix the bug that Adaptive Scheduler doesn't respect the lowerBound when one flink job has more than 1 tasks

flink-runtime/src/test/java/org/apache/flink/runtime/testutils/CommonTestUtils.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/AutoRescalingITCase.java
Backporting FLINK-34200 to 1.19
=> [FLINK-34200][test] Fix the bug that AutoRescalingITCase.testCheckpointRescalingInKeyedState fails occasionally

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointStatsTracker.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultExecutionGraphFactory.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorFailureTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorMasterHooksTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTestingUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointStatsTrackerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/TestingDefaultExecutionGraphBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/job/checkpoints/AbstractCheckpointStatsHandlerTest.java
=> [FLINK-34344] Pass JobID to CheckpointStatsTracker

flink-formats/flink-protobuf/src/test/java/org/apache/flink/formats/protobuf/ProtobufSQLITCase.java, flink-formats/flink-protobuf/src/test/java/org/apache/flink/formats/protobuf/ProtobufSQLITCaseTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/batch/sql/CompactManagedTableITCase.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/utils/BatchTestBase.scala
=> [1.19][FLINK-34422][test] BatchTestBase uses MiniClusterExtension

flink-formats/flink-protobuf/src/test/java/org/apache/flink/formats/protobuf/VeryBigPbProtoToRowITCase.java
The integration test configuration enables a bigger for test execution.
Renames tests.
=> [FLINK-34403][ci] Transforms VeryBigPbProtoToRowTest into an integration test

flink-clients/src/main/java/org/apache/flink/client/cli/CliFrontendParser.java
fix typo, update pipelne to pipeline
*(or)*
*(or)*
*(example:)*
- …
=> [Hotfix] fix typo for pipelne

.github/actions/job_init/action.yml, .github/workflows/template.flink-ci.yml
1.18 backport for parent PR #24304
=> [FLINK-34418][ci] Adds volume mount to gain more disk space

docs/setup_docs.sh
Integrate mongodb v1.1 docs after mongodb connector v1.1.0 released
=> [hotfix][docs] Integrate mongodb v1.1 docs

docs/setup_docs.sh
[hotfix] Integrate mongodb v1.1 docs
=> [hotfix] Integrate mongodb v1.1 docs

docs/content.zh/docs/connectors/table/overview.md, docs/content/docs/connectors/table/overview.md
Update the versions of mongodb supported by mongodb-connector
Currently, we are using mongodb-driver version 4.7.2. 
https://www.mongodb.com/docs/drivers/java/sync/current/compatibility/
For mongo-driver version 4.7.2, theoretically, it supports mongodb server versions below 3.6. 
However, it has not undergone rigorous testing. 
Additionally, mongo-driver version 4.8 and above will no longer support mongodb versions below 3.6. 
Therefore, we declare the minimum supported version of mongodb server as 3.6. …
=> [hotfix][docs] Update the versions of mongodb supported by mongodb-connector

docs/content.zh/docs/connectors/table/overview.md, docs/content/docs/connectors/table/overview.md
Update the versions of mongodb supported by mongodb-connector
Currently, we are using mongodb-driver version 4.7.2. 
https://www.mongodb.com/docs/drivers/java/sync/current/compatibility/
For mongo-driver version 4.7.2, theoretically, it supports mongodb server versions below 3.6. 
However, it has not undergone rigorous testing. 
Additionally, mongo-driver version 4.8 and above will no longer support mongodb versions below 3.6. 
Therefore, we declare the minimum supported version of mongodb server as 3.6. …
=> [BP-1.19][hotfix][docs] Update the versions of mongodb supported by mongodb-connector

docs/content.zh/docs/connectors/table/overview.md, docs/content/docs/connectors/table/overview.md
Update the versions of mongodb supported by mongodb-connector
Currently, we are using mongodb-driver version 4.7.2. 
https://www.mongodb.com/docs/drivers/java/sync/current/compatibility/
For mongo-driver version 4.7.2, theoretically, it supports mongodb server versions below 3.6. 
However, it has not undergone rigorous testing. 
Additionally, mongo-driver version 4.8 and above will no longer support mongodb versions below 3.6. 
Therefore, we declare the minimum supported version of mongodb server as 3.6. …
=> [BP-1.18][hotfix][docs] Update the versions of mongodb supported by mongodb-connector

docs/content.zh/docs/connectors/table/overview.md, docs/content/docs/connectors/table/overview.md
Update the versions of mongodb supported by mongodb-connector
Currently, we are using mongodb-driver version 4.7.2. 
https://www.mongodb.com/docs/drivers/java/sync/current/compatibility/
For mongo-driver version 4.7.2, theoretically, it supports mongodb server versions below 3.6. 
However, it has not undergone rigorous testing. 
Additionally, mongo-driver version 4.8 and above will no longer support mongodb versions below 3.6. 
Therefore, we declare the minimum supported version of mongodb server as 3.6. …
=> [BP-1.17][hotfix][docs] Update the versions of mongodb supported by mongodb-connector

docs/README.md
The configuration parameter docs generation is documented in two places in different ways:
[docs/README.md:62](https://github.com/apache/flink/blob/5c1e9f3b1449cb77276d578b344d9a69c7cf9a3c/docs/README.md#L62) and [flink-docs/README.md:44](https://github.com/apache/flink/blob/7bebd2d9fac517c28afc24c0c034d77cfe2b43a6/flink-docs/README.md#L44).
We should align config option generation documentation.
remove the corresponding command from docs/README.md and refer to flink-docs/README.md for the documentation
- …
=> [FLINK-33241][doc] Align config option generation documentation for Flink's config documentation.

docs/content.zh/docs/libs/state_processor_api.md
Translate docs/content.zh/docs/libs/state_processor_api.md into Chinese
Translate docs/content.zh/docs/libs/state_processor_api.md into Chinese
=> [FLINK-32443][docs-zh] Translate "State Processor API" page into Chinese

docs/content.zh/docs/dev/table/functions/udfs.md, docs/content.zh/docs/dev/table/procedures.md, docs/content/docs/dev/table/functions/udfs.md, docs/content/docs/dev/table/procedures.md
*Add doc of named parameters*
- *Add doc of named parameters*
Add doc , no need to test. 
=> [BP-1.19][FLINK-34265][doc] Add the doc of named parameters (#24260)

flink-core/src/main/java/org/apache/flink/util/TernaryBoolean.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/EmbeddedRocksDBStateBackend.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBIncrementalCheckpointUtils.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/EmbeddedRocksDBStateBackendTest.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateBackendConfigTest.java
Hotfix for Backend parameter handling and code deduplication
=> [hotfix] Fix configuration through TernaryBoolean in EmbeddedRocksDBStateBackend.

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/FlinkCalcMergeRule.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/FlinkLimit0RemoveRule.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/JoinTableFunctionScanToCorrelateRule.java
=> [FLINK-34492][table] Fix comment link when migrate calcite rules from scala to java

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/PlannerCallProcedureOperation.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestProcedureCatalogFactory.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/ProcedureITCase.java
1.18 backport for parent PR  #24397
=> [BP-1.18][FLINK-34517][table]fix environment configs ignored when calling procedure operation

flink-core/src/main/java/org/apache/flink/api/dag/Transformation.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/delegation/BatchPlanner.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/delegation/PlannerBase.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/delegation/StreamPlanner.scala, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/TableScanTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/TableScanTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/TableTestBase.scala
This pull request removes redundant transformation verification logic and use `ExplainDetail.JSON_EXECUTION_PLAN` to    verify the parallelism instead.
- Remove `verifyTransformation` method and corresponding logic.
- Use `util.verifyExplain(query, ExplainDetail.JSON_EXECUTION_PLAN)` to verify the parallelism instead.
This change added tests and can be verified through `TableScanTest.scala#testSetParallelismForSource`. …
=> [FLINK-33263][bugfix][table-planner] Remove redundant transformation verification logic.

docs/layouts/shortcodes/generated/kubernetes_config_configuration.html, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/configuration/KubernetesConfigOptions.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesJobManagerParameters.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/services/HeadlessClusterIPService.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/KubernetesJobManagerTestBase.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/InternalServiceDecoratorTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesJobManagerParametersTest.java
Flink currently supports adding Annotations to the Rest Service (with the configuration key:
kubernetes.rest-service.annotations). 
This PR adds a new configuration key: kubernetes.internal-service.annotations  to allow the same functionality for the internal service. 
- New configuration key: "kubernetes.internal-service.annotations"  is added
- Configuration value is used in intenal-service creation
- Documentation is added …
=> [FLINK-34429] [flink-kubernetes] Adding K8S Annotations to Internal Service

flink-streaming-java/src/test/java/org/apache/flink/streaming/environment/ExecutorDiscoveryAndJobClientTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/experimental/SocketStreamIteratorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/graph/StreamGraphCoLocationConstraintTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/graph/StreamingJobGraphGeneratorNodeHashTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/graph/TranslationTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/graph/WithMasterCheckpointHookConfigTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/util/AbstractStreamOperatorTestHarnessTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/util/LatencyStatsTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/util/MockDeserializationSchema.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/util/MockSerializationSchema.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/util/ProcessFunctionTestHarnessesTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/util/StreamTaskUtil.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/util/TestHarnessUtil.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/util/keys/ArrayKeySelectorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/util/retryable/AsyncRetryStrategiesTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/util/typeutils/FieldAccessorTest.java
[FLINK-25544][streaming][JUnit5 Migration] The util,graph,experimental,environment package of module flink-stream-java
[JUnit5 Migration] The util,graph,experimental,environment package of module flink-stream-java
=>  [FLINK-25544][streaming][JUnit5 Migration] The util,graph,experimental,environment package of module flink-stream-java

flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBResourceContainer.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateBackendConfigTest.java
Backporting #23922 to release-1.17
=>  [FLINK-33798][statebackend/rocksdb] automatically clean up rocksdb logs when the task exited.

flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBResourceContainer.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateBackendConfigTest.java
Backporting https://github.com/apache/flink/pull/23922 to release-1.18
=>  [FLINK-33798][statebackend/rocksdb] automatically clean up rocksdb logs when the task exited. 

flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTaskTest.java
[FLINK-33816][streaming] Fix unstable test SourceStreamTaskTest.testTriggeringStopWithSavepointWithDrain
[FLINK-33816][streaming] Fix unstable test SourceStreamTaskTest.testTriggeringStopWithSavepointWithDrain
=> [FLINK-33816][streaming] Fix unstable test SourceStreamTaskTest.testTriggeringStopWithSavepointWithDrain

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java
Unexpected error can be for example NPE
This
=> [hotfix] In case of unexpected errors do not loose the primary failur

flink-tests/src/test/java/org/apache/flink/test/misc/JobIDLoggingITCase.java
=> [FLINK-34643][tests] Fix JobIDLoggingITCase

docs/content.zh/_index.md, docs/content.zh/release-notes/flink-1.19.md, docs/content/_index.md, docs/content/release-notes/flink-1.19.md
This is a backport pr of FLINK-34593.
=> [FLINK-34593][release] Add release note for version 1.19

.github/workflows/docs.yml
Build 1.19 docs in GitHub Action and mark 1.19 as stable in docs
=>  [FLINK-34716][release] Build 1.19 docs in GitHub Action and mark 1.19 as stable in docs

flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/inmemory/InMemoryStateChangelogWriter.java, flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/AutoRescalingITCase.java
Changelog state backend supports local rescaling: 
The local snapshot is considered complete when there is at least one successful materialization after rescaling.
- Don't add partial local handles to the snapshot state after rescaling.
- Randomly enable changelog for `AutoRescalingITCase`
This change is already covered by existing tests, such as:
- `AutoRescalingITCase` …
=> [FLINK-34667][state/changelog] Changelog state backend supports local rescaling

pom.xml
=> [BP-1.19][hotfix] Fix maven property typo in root pom.xml

pom.xml
1.18 backport for PR https://github.com/apache/flink/pull/24535
=> [BP-1.18][hotfix] Fix maven property typo in root pom.xml

pom.xml
This is japicmp configuration update for master branch
=> [FLINK-34707][tests] Update base version for japicmp check

flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/RetryingExecutorTest.java
=> [FLINK-26515][tests] Fix RetryingExecutorTest

flink-tests/src/test/java/org/apache/flink/test/misc/JobIDLoggingITCase.java
`JobIDLoggingITCase` currently fails when running with `enable-adaptive-scheduler` maven profile because AdaptiveScheduler logs things differently.
This PR configures the environment to always use AdaptiveScheduler and adjusts the assertions accordingly.
=> [FLINK-34643] Use AdaptiveScheduler in JobIDLoggingITCase

flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/RetryingExecutorTest.java
=> [BP-1.18][FLINK-26515][tests] Fix RetryingExecutorTest

docs/layouts/shortcodes/config_file.html, docs/layouts/shortcodes/config_file_zh.html
Backporting FLINK-34956 to 1.19
=> [FLINK-34956][doc] Fix the config type wrong of Duration

flink-dist/src/main/resources/META-INF/NOTICE, flink-end-to-end-tests/flink-sql-client-test/pom.xml, flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE, flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE, flink-formats/flink-sql-avro/src/main/resources/META-INF/NOTICE, flink-python/pom.xml, flink-table/flink-table-planner/src/main/resources/META-INF/NOTICE, pom.xml
Backporting #24580 to 1.18. 
cc @slfan1989
=> [BP-1.18][FLINK-34955] Upgrade commons-compress to 1.26.0.

.github/PULL_REQUEST_TEMPLATE.md
1.18 backport PR for parent PR #24615
=> [BP-1.18][FLINK-35000][build] Updates link to test code convention in pull request template

flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnConfigurationITCase.java
ContainerId.getId() It is a deprecated method. Use getContainerId instead.
org.apache.hadoop.yarn.api.records#getContainerId
```
/**
* Get the lower 32 bits of identifier of the <code>ContainerId</code>,
* which doesn't include epoch. Note that this method will be marked as
* deprecated, so please use <code>getContainerId</code> instead.
* @return lower 32 bits of identifier of the <code>ContainerId</code>
*/
@Public
@Deprecated
@Unstable
public abstract int getId();
/**
* Get the identifier of the <code>ContainerId</code>. Upper 24 bits are
* reserved as epoch of cluster, and lower 40 bits are reserved as
* sequential number of containers.
* @return identifier of the <code>ContainerId</code>
*/
@Public
@Unstable
public abstract long getContainerId();
```
- *The TaskInfo …
=> [hotfix] Fix YARN ContainerId.getId Deprecated Used.

flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
=> [hotfix] Log Job ID when task is failed externally

flink-tests/src/test/java/org/apache/flink/test/checkpointing/ChangelogRecoveryITCase.java
As described in https://github.com/apache/flink/pull/22669#issuecomment-1593370772, It is best for the materialization Interval to be greater than checkpoint interval, this PR increases the materialization Interval of ChangelogRecoveryITCase#testMaterialization to work around the unstable test.
- Increase the materialization Interval of ChangelogRecoveryITCase#testMaterialization
This change is already covered by existing tests: ChangelogRecoveryITCase#testMaterialization. …
=> [FLINK-28440][State/changelog] Hotfix! Increase the materialization Interval of ChangelogRecoveryITCase#testMaterialization

docs/layouts/shortcodes/generated/checkpoint_file_merging_section.html, docs/layouts/shortcodes/generated/checkpointing_configuration.html, flink-annotations/src/main/java/org/apache/flink/annotation/docs/Documentation.java, flink-core/src/main/java/org/apache/flink/configuration/CheckpointingOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerBuilder.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/CheckpointStorageWorkerView.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/TaskExecutorFileMergingManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/TaskExecutorFileMergingManagerTest.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
Introduce cluster-level file merging related configurations.
- Add `state.checkpoints.file-merging.*` configurations.
`ConfigOptionsYamlSpecTest`.
=> [FLINK-32440][checkpoint] Introduce file merging configurations

flink-core/src/test/java/org/apache/flink/configuration/ConfigOptionTest.java, flink-core/src/test/java/org/apache/flink/configuration/ConfigUtilsTest.java, flink-core/src/test/java/org/apache/flink/configuration/ConfigurationConversionsTest.java, flink-core/src/test/java/org/apache/flink/configuration/ConfigurationParsingInvalidFormatsTest.java, flink-core/src/test/java/org/apache/flink/configuration/ConfigurationTest.java, flink-core/src/test/java/org/apache/flink/configuration/ConfigurationUtilsTest.java, flink-core/src/test/java/org/apache/flink/configuration/CoreOptionsTest.java, flink-core/src/test/java/org/apache/flink/configuration/FilesystemSchemeConfigTest.java, flink-core/src/test/java/org/apache/flink/configuration/GlobalConfigurationTest.java, flink-core/src/test/java/org/apache/flink/configuration/MemorySizePrettyPrintingTest.java, flink-core/src/test/java/org/apache/flink/configuration/MemorySizeTest.java, flink-core/src/test/java/org/apache/flink/configuration/ParentFirstPatternsTest.java, flink-core/src/test/java/org/apache/flink/configuration/ReadableWritableConfigurationTest.java, flink-core/src/test/java/org/apache/flink/configuration/RestOptionsTest.java, flink-core/src/test/java/org/apache/flink/configuration/SecurityOptionsTest.java, flink-core/src/test/java/org/apache/flink/configuration/StructuredOptionsSplitterEscapeTest.java, flink-core/src/test/java/org/apache/flink/configuration/StructuredOptionsSplitterTest.java, flink-core/src/test/java/org/apache/flink/configuration/UnmodifiableConfigurationTest.java, flink-core/src/test/java/org/apache/flink/configuration/YamlParserUtilsTest.java, flink-core/src/test/java/org/apache/flink/configuration/description/DescriptionHtmlTest.java
Changes:
- Module: flink-core with,Package: Configuration migrate to junit5
=> [FLINK-25537][JUnit5 Migration] Module: flink-core with,Package: Configuration

flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterThrottlingTest.java
Refactor `AsyncSinkWriterThrottlingTest` to flush when reaching batch sizes without changing processing time. The changes of processing time are in fact not needed for this test and are causing flakiness due to reference of timer call back from external thread.
- refactored `AsyncSinkWriterThrottlingTest` to send all batch data without change in timer service.
- The serializers:no …
=> [FLINK-31472] Remove external timer service reference from AsyncSinkThrottling Test

docs/content.zh/docs/ops/metrics.md, docs/content/docs/ops/metrics.md, docs/layouts/shortcodes/generated/job_event_store_configuration.html, docs/layouts/shortcodes/generated/metric_configuration.html, docs/layouts/shortcodes/generated/rest_v1_dispatcher.html, docs/static/generated/rest_v1_dispatcher.yml, flink-core/src/main/java/org/apache/flink/configuration/MetricOptions.java, flink-runtime-web/src/test/resources/rest_api_v1.snapshot, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/metrics/JobManagerOperatorMetricsHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/legacy/metrics/MetricStore.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/metrics/JobManagerOperatorMetricsHeaders.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/metrics/JobManagerOperatorMetricsMessageParameters.java, flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/WebMonitorEndpoint.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/job/metrics/JobManagerOperatorMetricsHandlerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/legacy/metrics/MetricFetcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/legacy/metrics/MetricStoreTest.java
Expose JobmanagerOperatorMetrics via REST API: https://cwiki.apache.org/confluence/display/FLINK/FLIP-417%3A+Expose+JobManagerOperatorMetrics+via+REST+API
- Create new REST API for `.../coordinator-metrics`
- Extended integration test for Metrics REST APIs …
=> [FLINK-34444] Initial implementation of JM operator metric rest api

flink-core/src/main/java/org/apache/flink/api/common/ExecutionConfig.java, flink-core/src/main/java/org/apache/flink/configuration/ExecutionOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateRequestBuffer.java, flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionControllerTest.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperatorV2.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironmentTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/InternalTimerServiceAsyncImplTest.java
As part of the async execution model of disaggregated state management, this PR introduce async execution configurations.
- Add async execution configurations in `ExecutionOptions`
- Add related getter/setter in `ExecutionConfig`
- StreamExecutionEnvironmentTest#testAsyncExecutionConfiguration …
=> [FLINK-35026][runtime][config] Introduce async execution configurations

docs/content.zh/docs/ops/state/checkpoints.md
=> [hotfix][docs] Fix typo in checkpoints documentation

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/optimize/StreamCommonSubGraphBasedOptimizer.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/FlinkRexUtil.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/optimize/MiniBatchOptimizationTest.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/TableTestBase.scala
This is 1.19 backport for commit b1544e4e513d2b75b350c20dbb1c17a8232c22fd
=> [BP-1.19][FLINK-32622][table-planner] Optimize mini-batch assignment (#23470)

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/PlannerCallProcedureOperation.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestProcedureCatalogFactory.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/ProcedureITCase.java
1.19 backport for parent PR #24397
=> [BP-1.19][FLINK-34517][table]fix environment configs ignored when calling procedure operation

flink-connectors/flink-connector-datagen/src/main/java/org/apache/flink/connector/datagen/functions/FromElementsGeneratorFunction.java, flink-filesystems/flink-oss-fs-hadoop/src/main/java/org/apache/flink/fs/osshadoop/writer/OSSCommitter.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/checkpointing/BarrierAlignmentUtilTest.java, flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/testsuites/SourceTestSuiteBase.java
This pull request is to show more info in some logs, which helps a lot when debugging in production environment
=> [FLINK-35270]Enrich information in logs, making it easier for debugging

flink-end-to-end-tests/test-scripts/common_s3_minio.sh, flink-end-to-end-tests/test-scripts/common_ssl.sh, flink-end-to-end-tests/test-scripts/test_file_sink.sh
1.19 backport for parent PR #24465
=> [BP-1.19][FLINK-34324][ci] Replaces AWS-based S3 e2e tests with Minio-backed version

flink-end-to-end-tests/test-scripts/common_s3_minio.sh, flink-end-to-end-tests/test-scripts/common_ssl.sh, flink-end-to-end-tests/test-scripts/test_file_sink.sh
1.18 backport for parent PR #24465
=> [BP-1.18][FLINK-34324][ci] Replaces AWS-based S3 e2e tests with Minio-backed version

flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/DefaultShuffleMasterSnapshotContext.java, flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/EmptyShuffleMasterSnapshot.java, flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/NettyShuffleMaster.java, flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/ShuffleMaster.java, flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/ShuffleMasterSnapshot.java, flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/ShuffleMasterSnapshotContext.java
Extend ShuffleMaster to support snapshot and restore state.
Extend shuffleMaster to support batch snapshot as follows:
1. Add method supportsBatchSnapshot to identify whether the shuffle master supports taking snapshot in batch scenarios
2. Add method snapshotState and restoreState to snapshot and restore the shuffle master's state. …
=> [FLINK-33986][runtime] Extend ShuffleMaster to support snapshot and restore state.

flink-runtime/src/main/java/org/apache/flink/runtime/state/OperatorStateRestoreOperation.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/filemerging/SegmentFileStateHandle.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java, flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/streaming/util/TestStreamEnvironment.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/ChangelogRecoveryITCaseBase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/RestoreUpgradedJobITCase.java, flink-tests/src/test/java/org/apache/flink/test/state/ChangelogCompatibilityITCase.java, flink-tests/src/test/java/org/apache/flink/test/state/ChangelogRecoveryCachingITCase.java, flink-tests/src/test/java/org/apache/flink/test/state/ChangelogRescalingITCase.java
This pr integrates snapshot file-merging with existing ITCases by enabling file-merging in TestStreamEnvironment randomly.
- Enable file-merging in `TestStreamEnvironment` randomly.
This change is a trivial rework, already covered by existing IT tests. …
=> [FLINK-32092][tests] Integrate snapshot file-merging with existing ITCases

docs/content.zh/docs/ops/upgrading.md, docs/content/docs/ops/upgrading.md
This pull requests updates the snapshot compatibility matrix for release 1.19.
Update compatibility matrix to include Flink 1.19 release
This is a doc-only change.
=> [FLINK-35383][docs] Update compatibility matrix for 1.19 release

docs/content.zh/docs/ops/batch/recovery_from_job_master_failure.md, docs/content/docs/ops/batch/recovery_from_job_master_failure.md
Add documents for batch job recovery from jobMaster failover.
Add documents for batch job recovery from jobMaster failover.
The updated document is shown in the figure:
Chinese version:
English version:
- Does …
=> [FLINK-35399][doc] Add documents for batch job recovery from jobMaster failover.

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/utils/DynamicPartitionPruningUtils.java
This is BP to 1.19 PR for 87b7193846090897b2feabf716ee5378bcd7585b
=> [BP-1.19][FLINK-34379][table] Fix adding catalogtable logic

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/utils/DynamicPartitionPruningUtils.java
This is BP to 1.18 PR for https://github.com/apache/flink/commit/87b7193846090897b2feabf716ee5378bcd7585b
=> [BP-1.18][FLINK-34379][table] Fix adding catalogtable logic

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/utils/DynamicPartitionPruningUtils.java
This is BP to 1.17 PR for https://github.com/apache/flink/commit/87b7193846090897b2feabf716ee5378bcd7585b
=> [BP-1.17][FLINK-34379][table] Fix adding catalogtable logic

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/StateAssignmentOperation.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/StateAssignmentOperationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/StateHandleDummyUtil.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/recovery/RescalingStreamTaskNetworkInput.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointRescaleITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java
backport of https://github.com/apache/flink/pull/24857
=> [1.19][FLINK-35351][checkpoint] Fix fail during restore from unaligned checkpoint with custom partitioner

flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptivebatch/BatchJobRecoveryTest.java
Fix unstable BatchJobRecoveryTest.
This change is already covered by existing tests BatchJobRecoveryTest.
=> [FLINK-35483][runtime] Fix unstable BatchJobRecoveryTest.

flink-table/flink-table-common/src/main/java/org/apache/flink/table/utils/print/TableauStyle.java
refactoring to template method to separate concerns
This change is already covered by existing tests, such as TableauStyleTest.
=> [hotfix][table] refactoring to template method to separate concerns

docs/layouts/shortcodes/generated/yarn_config_configuration.html, flink-filesystems/flink-hadoop-fs/src/main/java/org/apache/flink/runtime/util/HadoopUtils.java, flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java, flink-yarn/src/main/java/org/apache/flink/yarn/configuration/YarnConfigOptions.java, flink-yarn/src/test/java/org/apache/flink/yarn/YarnClusterDescriptorTest.java, flink-yarn/src/test/java/org/apache/flink/yarn/token/TestYarnAMDelegationTokenProvider.java, flink-yarn/src/test/java/org/apache/flink/yarn/token/TestYarnAMDelegationTokenReceiver.java, flink-yarn/src/test/resources/META-INF/services/org.apache.flink.core.security.token.DelegationTokenProvider, flink-yarn/src/test/resources/META-INF/services/org.apache.flink.core.security.token.DelegationTokenReceiver
Make hdfs token fetched by custom delegation token provider pass to yarn am.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper:no 
=> [FLINK-35525][yarn] Add a token services configuration to allow obtained token to be passed to Yarn AM

docs/layouts/shortcodes/generated/checkpointing_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/CheckpointingOptions.java
Simple documentation improvement.
N/A
N/A
- Does this pull request introduce a new feature? (yes / N/A)
- If yes, how is the feature documented? (not applicable / N/A / JavaDocs / not documented)
=> [hotfix] Improve execution.checkpointing.unaligned.interruptible-timers.enabled documentation

docs/content.zh/docs/ops/metrics.md, docs/content/docs/ops/metrics.md, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/AcrossCheckpointFileMergingSnapshotManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingMetricGroup.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerBuilder.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/WithinCheckpointFileMergingSnapshotManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/TaskExecutorFileMergingManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingMetricsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerTestBase.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/TaskExecutorFileMergingManagerTest.java
Add file size and file count metrics for file-merging.
- Add `logicalFileCount`, `logicalFileSize`, `physicalFileCount`, `physicalFileSize` metrics.
- `FileMergingMetricsTest` …
=> [FLINK-32091][checkpoint] Add file size metrics for file-merging

docs/layouts/shortcodes/generated/security_configuration.html, docs/layouts/shortcodes/generated/security_ssl_section.html, flink-core/src/main/java/org/apache/flink/configuration/SecurityOptions.java, flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/pekko/CustomSSLEngineProvider.java, flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/pekko/PekkoUtils.java, flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/pekko/PekkoUtilsTest.java, flink-runtime/src/main/java/org/apache/flink/runtime/net/SSLUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/net/SSLUtilsTest.java
Additional configuration options for internal and REST SSL setup.
* SSL configuration option for internal and REST SSL keystore/truststore type
* Use new option when initializing SSLHandlerFactory
* Extend CustomSSLEngineProvider used by Pekko
- Unit tests to ensure new configuration options can be picked up
- Manually verified the change by running a cluster using a BKS keystore and truststore that is not available by default.
- The S3 file …
=> [FLINK-35371][security] Add configuration for SSL keystore and truststore type

flink-core/src/test/java/org/apache/flink/core/fs/InitOutputPathTest.java
PR #24881 introduce some issue during the migration to junit5, temporarily revert the changes to `InitOutputPathTest` file.
=> [FLINK-35601][test] Revert the junit5 migration of InitOutputPathTest

flink-connectors/flink-hadoop-compatibility/pom.xml, flink-core/pom.xml, flink-formats/flink-avro/pom.xml, flink-fs-tests/pom.xml, flink-libraries/flink-cep/pom.xml, flink-runtime/pom.xml, flink-scala/pom.xml, flink-streaming-java/pom.xml, flink-table/flink-table-runtime/pom.xml, flink-test-utils-parent/flink-migration-test-utils/README.md, flink-test-utils-parent/flink-migration-test-utils/pom.xml, flink-tests-java17/pom.xml, flink-tests/pom.xml
=> [FLINK-35539][tests] Fix artifactId of flink-migration-test-utils module

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/wmassigners/WatermarkAssignerOperator.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/wmassigners/WatermarkAssignerOperatorTest.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/wmassigners/WatermarkAssignerOperatorTestBase.java
This is a 1.18 backport of: https://github.com/apache/flink/pull/24941
=> [1.18][FLINK-34252][table] Fix lastRecordTime tracking in WatermarkAssignerOperator

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/wmassigners/WatermarkAssignerOperator.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/wmassigners/WatermarkAssignerOperatorTest.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/wmassigners/WatermarkAssignerOperatorTestBase.java
This is a 1.19 backport of: https://github.com/apache/flink/pull/24941
=> [1.19][FLINK-34252][table] Fix lastRecordTime tracking in WatermarkAssignerOperator

flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/handler/materializedtable/scheduler/CreateEmbeddedSchedulerWorkflowHandler.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/message/materializedtable/scheduler/CreateEmbeddedSchedulerWorkflowRequestBody.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/materializedtable/MaterializedTableManager.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/workflow/EmbeddedWorkflowScheduler.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/workflow/WorkflowInfo.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/workflow/scheduler/EmbeddedQuartzScheduler.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/workflow/EmbeddedSchedulerRelatedITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/workflow/QuartzSchedulerUtilsTest.java, flink-table/flink-sql-gateway/src/test/resources/sql_gateway_rest_api_v3.snapshot, flink-table/flink-table-common/src/test/java/org/apache/flink/table/factories/utils/FactoryMocks.java, flink-test-utils-parent/flink-table-filesystem-test-utils/src/main/java/org/apache/flink/connector/file/table/TestFileSystemTableSource.java, flink-test-utils-parent/flink-table-filesystem-test-utils/src/main/java/org/apache/flink/table/file/testutils/TestFileSystemTableFactory.java, flink-test-utils-parent/flink-table-filesystem-test-utils/src/test/java/org/apache/flink/table/file/testutils/TestFileSystemTableFactoryTest.java
*Bugfix for TestFileSystem Connector and optimize code for embedded scheduler*
- *Fix TestFileSystem Connector error setting execution mode*
- *Remove unnecessary parameter customScheduleTime for embedded scheduler*
=> [FLINK-35659][testutils] Fix TestFileSystem Connector error setting execution mode

flink-end-to-end-tests/flink-end-to-end-tests-common/pom.xml, flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/flink/FlinkDistribution.java, flink-end-to-end-tests/flink-sql-gateway-test/pom.xml, flink-end-to-end-tests/flink-sql-gateway-test/src/test/java/org/apache/flink/table/gateway/SqlGatewayE2ECase.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/WorkflowSchedulerFactoryUtil.java
*Add e2e test case for materialized table. * 
- *Add e2e test for materialized table*
This is a e2e test, and no need to verify.
=> [FLINK-35479][e2e] Add end-to-end test for materialized table

docs/content.zh/docs/dev/table/sql/describe.md, docs/content.zh/docs/dev/table/sql/job.md, docs/content/docs/dev/table/sql/describe.md, docs/content/docs/dev/table/sql/job.md
*Add doc for syntax DESCRIBE JOB <JOB_ID>*
- *add doc for en and zh*
This pr is no need to test.
- Does this pull request introduce a new feature? 
=> [FLINK-35271][doc] Add doc for syntax DESCRIBE JOB <JOB_ID>

flink-connectors/flink-connector-hive/pom.xml, flink-formats/flink-parquet/pom.xml, flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/reader/NestedColumnReader.java
- fix parquet flink-runtime dependency version
- optimize put null flags logics
- relocation exclude three flink-runtime class.
This change is already covered by existing tests, such as org.apache.flink.formats.parquet.vector.ParquetColumnarRowSplitReaderTest
- The public API, …
=> [hotfix][parquet] fix dependences and variable name problems in FLINK-35702

flink-datastream/src/test/java/org/apache/flink/datastream/impl/context/DefaultProcessingTimeManagerTest.java, flink-formats/flink-avro-confluent-registry/src/test/java/org/apache/flink/formats/avro/registry/confluent/debezium/DebeziumAvroFormatFactoryTest.java, flink-formats/flink-csv/src/test/java/org/apache/flink/formats/csv/DataStreamCsvITCase.java, flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/utils/SerializableConfigurationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/hooks/MasterHooksTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/ResultPartitionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/TestingSubpartitionCreatedViewReader.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/UnionResultSubpartitionViewTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/file/DiskIOSchedulerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/ComponentClosingUtilsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/EventReceivingTasks.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/MockStateWithoutExecutionGraphContext.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStDBOperationTestBase.java, flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliTableauResultViewTest.java, flink-table/flink-sql-gateway-api/src/test/java/org/apache/flink/table/gateway/api/utils/MockedSqlGatewayService.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestUpdateDeleteTableFactory.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/BuiltInAggregateFunctionTestBase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecSinkITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/RestoreUpgradedJobITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/SavepointFormatITCase.java, flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/RecordAttributesPropagationITCase.java, tools/maven/checkstyle.xml
Change org.jetbrains.annotations.NotNull to javax.annotation.Nonnull
Change org.jetbrains.annotations.NotNull to javax.annotation.Nonnull
- If yes, …
=> [FLINK-35733] Change org.jetbrains.annotations.NotNull to javax.annotation.Nonnull

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveBatchScheduler.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveBatchSchedulerTest.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/translators/SinkTransformationTranslator.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SinkTransformationTranslatorITCaseBase.java
[BP-1.20][FLINK-35731][runtime] Fix incorrect parallelism configured detection for Sink V2.
[BP-1.20][FLINK-35731][runtime] Fix incorrect parallelism configured detection for Sink V2.
=> [BP-1.20][FLINK-35731][runtime] Fix incorrect parallelism configured detection for Sink V2.

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveBatchScheduler.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveBatchSchedulerTest.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/translators/SinkTransformationTranslator.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SinkTransformationTranslatorITCaseBase.java
[BP-1.19][FLINK-35731][runtime] Fix incorrect parallelism configured detection for Sink V2.
[BP-1.19][FLINK-35731][runtime] Fix incorrect parallelism configured detection for Sink V2.
=> [BP-1.19][FLINK-35731][runtime] Fix incorrect parallelism configured detection for Sink V2.

flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/InternalOperatorMetricGroup.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperatorV2.java
(cherry picked from commit 615d19735b0691b57262a110e6078c3488349f5a)
BP for 1.19 of https://github.com/apache/flink/pull/25021
=> [BP-1.19][FLINK-35750][runtime/metrics] Fix that the latency marker metrics aren't updated after failover.

flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/InternalOperatorMetricGroup.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperatorV2.java
(cherry picked from commit 615d19735b0691b57262a110e6078c3488349f5a)
BP for 1.20 of https://github.com/apache/flink/pull/25021
=> [BP-1.20][FLINK-35750][runtime/metrics] Fix that the latency marker metrics aren't updated after failover.

flink-runtime/src/main/java/org/apache/flink/runtime/blob/BlobServer.java
=> [FLINK-35786] Fix NPE BlobServer / shutdownHook

docs/content.zh/docs/dev/datastream/fault-tolerance/checkpointing.md, docs/content/docs/dev/datastream/fault-tolerance/checkpointing.md, flink-core/src/main/java/org/apache/flink/configuration/CheckpointingOptions.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/ExecutionCheckpointingOptions.java
1.18 backport for parent PR https://github.com/apache/flink/pull/25048
No conflicts appeared during backport.
- Updates the file-merging options in documents.
=> [BP-1.20][hotfix][checkpoint] Rename file-merging options in documents

flink-runtime/src/main/java/org/apache/flink/runtime/blob/BlobServer.java
=> [BP-1.19][FLINK-35786] Fix NPE BlobServer / shutdownHook

docs/content.zh/docs/dev/datastream/fault-tolerance/checkpointing.md, docs/content/docs/dev/datastream/fault-tolerance/checkpointing.md, flink-core/src/main/java/org/apache/flink/configuration/CheckpointingOptions.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/ExecutionCheckpointingOptions.java
https://issues.apache.org/jira/browse/FLINK-34482 renamed options for checkpointing, but the file-merging documents are not updated. This PR updates the file-merging options in documents.
- Updates the file-merging options in documents. …
=> [hotfix][checkpoint] Rename file-merging options in documents

docs/content/docs/dev/configuration/connector.md
Fix broken link to "Anatomy of the Flink distrubution" documentation in dev/configuration/connector.
Fix broken link to "Anatomy of the Flink distrubution" documentation in dev/configuration/connector.
This change is already covered by existing tests, such as verifying the link locally.
=> [hotfix] [docs] Fix broken link to "Anatomy of the Flink distribution" in dev/configuration/connector

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalWindowAggregate.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/WindowUtil.scala, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/agg/WindowAggregateTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/agg/WindowAggregateTest.scala
This is a backport pr to fix FLINK-35816.
=> [FLINK-35816][table-planner] Non-mergeable proctime tvf window aggregate needs to fallback to group aggregate

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalWindowTableFunction.scala, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/WindowTableFunctionTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/WindowTableFunctionTest.scala
This is a BP for https://github.com/apache/flink/pull/25079
=> [FLINK-35829][table-planner] The requireWatermark property of StreamPhysicalWindowTableFunction needs to check the window's time type

flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/InternalOperatorMetricGroup.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperatorV2.java
(cherry picked from commit 615d19735b0691b57262a110e6078c3488349f5a)
BP for 1.18 of https://github.com/apache/flink/pull/25021
=> [BP-1.18][FLINK-35750][runtime/metrics] Fix that the latency marker metrics aren't updated after failover.

flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/InternalOperatorMetricGroup.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperatorV2.java
(cherry picked from commit 615d19735b0691b57262a110e6078c3488349f5a)
BP for 1.17 of https://github.com/apache/flink/pull/25021
=> [BP-1.17][FLINK-35750][runtime/metrics] Fix that the latency marker metrics aren't updated after failover.

flink-table/flink-table-planner/src/main/java/org/apache/calcite/sql2rel/RelDecorrelator.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/FlinkFilterProjectTransposeRule.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/CalcTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/CalcTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/CalcTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/CalcTest.scala
This is a backport pr of #25068
=> [FLINK-35804][table-planner] Fix incorrect calc merge during decorrelate phase

flink-tests/src/test/java/org/apache/flink/test/checkpointing/SnapshotFileMergingCompatibilityITCase.java
Currently, the IT cases of file-merging check the existence of files under the checkpoint directory to make sure all the previous files are cleaned as expected. However due to FLINK-28927, FLINK-28984 (or other remaining issues), the cp directory may not be totally cleaned. Thus file-merging IT test may produce an error.
Before those issues get resolved, this PR make the IT cases only check the existence of JM recognized files instead of any file under the checkpoint directory.
- Verifying code in `SnapshotFileMergingCompatibilityITCase`.
- Run `SnapshotFileMergingCompatibilityITCase` …
=> [FLINK-35843][test] Check only JM acknowledged files in file-merging IT cases

flink-tests/src/test/java/org/apache/flink/test/checkpointing/SnapshotFileMergingCompatibilityITCase.java
Like the title said, make file-merging test tolerate the scenario that source does not produce any record.
- Change the verifying code in `SnapshotFileMergingCompatibilityITCase`, instead of checking there is any file under shared directory, currently it checks every single state handle's file path.
This PR change the test itself. …
=> [FLINK-35835][test] Make file-merging test tolerate the scenario that source does not produce any record

flink-tests/src/test/java/org/apache/flink/test/checkpointing/SnapshotFileMergingCompatibilityITCase.java
BP #25090 and #25116
- `SnapshotFileMergingCompatibilityITCase`
Run `SnapshotFileMergingCompatibilityITCase`
=> [BP-1.20][Test] Fix tests about file-merging

flink-core/src/main/java/org/apache/flink/configuration/TaskManagerOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmanager/scheduler/SlotSharingGroup.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/AbstractSlotSharingStrategy.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/ExecutionSlotSharingGroup.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/LocalInputPreferredSlotSharingStrategy.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/TaskBalancedPreferredSlotSharingStrategy.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/AbstractSlotSharingStrategyTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/LocalInputPreferredSlotSharingStrategyTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/MergingSharedSlotProfileRetrieverTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/SharedSlotTestingUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/SlotSharingExecutionSlotAllocatorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/TaskBalancedPreferredSlotSharingStrategyTest.java
- Support tasks balancing at slot level for Default Scheduler
- *Introduce BalancedPreferredSlotSharingStrategy to support tasks balancing at slot level.*
- *Expose the configuration item to switch tasks balancing at slot level for Default Scheduler.*
- *`org.apache.flink.runtime.scheduler.BalancedPreferredSlotSharingStrategyTest`*
- The runtime per-record code paths (performance sensitive): (yes / no / **don't know**) …
=> [FLINK-33386][runtime] Support tasks balancing at slot level for Default Scheduler

flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/slotpool/DeclarativeSlotPoolBridge.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/slotpool/SlotPool.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/DeclarativeSlotPoolBridgeBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/DeclarativeSlotPoolBridgePreferredAllocationsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/DeclarativeSlotPoolBridgeRequestCompletionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/DeclarativeSlotPoolBridgeResourceDeclarationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/DeclarativeSlotPoolBridgeTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/SlotPoolInteractionsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/SlotPoolUtils.java
Migrate the Time to Duration for SlotPool in the minimum scope
Migrate the Time to Duration for SlotPool in the minimum scope
- If yes, …
=> [hotfix][scheduler] Migrate the Time to Duration for SlotPool in the minimum scope

docs/content.zh/docs/ops/upgrading.md, docs/content/docs/ops/upgrading.md
Backporting FLINK-35678 to 1.20.
=> [FLINK-35678][doc] Update compatibility matrix for 1.20 release

flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcher.java, flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherManager.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherManagerTest.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherTest.java, flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/test/util/TestUtils.java
This patch changes the `SplitFetcher` in the base implementation of the new source to delay the closure of `SplitReader` to until all the previous emitted records are processed. This is because some of the previously emitted records may have not been processed by the main thread when the SplitFetcher is shutting down. In that case, closing the `SplitReader` may corrupt those unprocessed records.
This patch adds a package private method to the `SplitFetcher` which is not exposed to the end user. And the public API signature and behavior exposed to the end users does not change. Personally I feel it it not necessary to have a FLIP. But I am not opposed to have one if others feel strong.
The patch only contains one commit. It does the following:
1. Add a countdown latch to the split fetcher. …
=> FLINK-35924: delay the SplitReader closure to until all the emitted records are processed.

.mvn/wrapper/maven-wrapper.properties, mvnw, mvnw.cmd
JIRA: [FLINK-33503](https://issues.apache.org/jira/browse/FLINK-33503)
[FLINK-33503](https://issues.apache.org/jira/browse/FLINK-33503) enabled us to add checksum checks for the Maven wrapper binaries along the update from 3.1.0 to 3.2.0.
But there seems to be an issue with verifying the wrapper's checksum under windows (see [MVRAPPER-103](https://issues.apache.org/jira/browse/MWRAPPER-103)). After MVRAPPER-103 is resolved in 3.3.0, we should upgrade Maven wrapper to 3.3.0 or later to enable the feature to verify the wrapper's checksum. 
This PR did:
1. Upgrade Maven wrapper to the latest 3.3.2 version to include more bug fixes.
2. Update the `wrapperSha256Sum` for `maven-wrapper-3.3.2.jar`
3. Update the mvnw auto-generated script in v3.3.2.
- Upgrade Maven wrapper to the latest 3.3.2 …
=> [FLINK-33607][build] Updates Maven wrapper version and enables checksum verification for Maven wrapper

flink-runtime-web/web-dashboard/src/app/pages/job/overview/watermarks/job-overview-drawer-watermarks.component.html, flink-runtime-web/web-dashboard/src/app/pages/job/overview/watermarks/job-overview-drawer-watermarks.component.ts
To facilitate the observation of Watermark conditions among different Subtasks, the UI supports sorting by Watermark.
Add sorting functionality to the Watermark table header
=> [FLINK-36127][web] support sort watermark

docs/content.zh/docs/deployment/filesystems/s3.md, docs/content/docs/deployment/filesystems/s3.md
Document s5cmd. Depends on #25228, please take a look here just at the last commit `[FLINK-35773] Document s5cmd`
N/A
N/A
=> [FLINK-35773][docs]  Document s5cmd

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/AppendOnlyFirstNFunction.java
*Reduce one state query in the AppendOnlyFirstNFunction and optimize the processing performance for large states.*
- *Query the state only once.*
- *Change "currentRank += 1" to "currentRank++".*
This change is already covered by existing tests, such as *AppendOnlyFirstNFunctionTest*. …
=> [FLINK-35988][table]Reduce the number of state queries in the AppendOnlyFirstNFunction

flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/InternalKeyedState.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBListGetRequest.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBPutRequest.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBSingleGetRequest.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStGeneralMultiGetOperation.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStInnerTable.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStListIterator.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStListState.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateExecutor.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateRequestClassifier.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStWriteBatchOperation.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ListDelimitedSerializer.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStDBOperationTestBase.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStGeneralMultiGetOperationTest.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStWriteBatchOperationTest.java
Async List State for ForSt state backend
This change added tests under existing test classes.
=> [FLINK-35389][State/ForSt] Async list state

flink-core/src/main/java/org/apache/flink/core/fs/ICloseableRegistry.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/CompositeKeySerializationUtils.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/RegisteredStateMetaInfoBase.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/EmbeddedRocksDBStateBackend.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBIncrementalCheckpointUtils.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackend.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackendBuilder.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBOperationUtils.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBWriteBatchWrapper.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBFullRestoreOperation.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBHandle.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBHeapTimersFullRestoreOperation.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBIncrementalRestoreOperation.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBRestoreResult.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBRecoveryTest.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBTestUtils.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBWriteBatchWrapperTest.java
PR contains multiple improvements and bug fixes for Clip/IngestDB recovery
=> [FLINK-35580] Improvements and fix ingestDB recovery mode related bugs

docs/config.toml
- Add 1.20 to the list of previous versions.
- Local documentation build.
=> [FLINK-36234][Docs] Add 1.20 to PreviousDocs list

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateRequest.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateRequestBuffer.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateRequestContainer.java, flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/MockStateExecutor.java, flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/MockStateRequestContainer.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/InternalKeyedStateTestBase.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ContextKey.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStInnerTable.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStListState.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStMapState.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateRequestClassifier.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStValueState.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStDBOperationTestBase.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateExecutorTest.java
Store namespace in `StateRequest` and `contextKey` eagerly, to ensure that the namespace has not been changed during serialization.
- Add`namespace` field for `contextKey` and `StateRequest`. …
=> [FLINK-36243][state/forst] Store namespace in contextKey

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystem.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystemTest.java
This PR makes `ForStFlinkFileSystem` write misc file in local filesystem.
- Add logic to determine where to write files based on file suffixes in `ForStFlinkFileSystem`
- `ForStFlinkFileSystemTest#testMiscFileInLocal` …
=> [FLINK-35927][state/forst] Make ForStFlinkFileSystem write misc file in local filesystem

flink-runtime/src/test/java/org/apache/flink/runtime/OperatorIDPairTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/StateAssignmentOperationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/VertexFinishedStateCheckerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinatorSchedulerTest.java
Hotfix for https://github.com/apache/flink/pull/25267
=> [FLINK-36001][state] Hotfix for OperatorIDPairTest missing header

flink-yarn/src/test/java/org/apache/flink/yarn/YarnFileStageTestS3ITCase.java
This PR fixes [FLINK-36258](https://issues.apache.org/jira/browse/FLINK-36258): testRecursiveUploadForYarnS3n failed due to no AWS Credentials provided. In this [PR](https://github.com/apache/flink/pull/25302/files#diff-8614cdbd44bb18064e8b6733b913fa21258487624491e76ac0332a777a77e632L111):
https://github.com/apache/flink/blob/bf393918e5c2a81d4dc49ee82e7019f38f64b517/flink-yarn/src/test/java/org/apache/flink/yarn/YarnFileStageTestS3ITCase.java#L111
we remove the deprecated string configs, and also remove this line to set `HDFS_SITE_CONFIG` in `YarnFileStageTestS3ITCase`, but didn't configure it with environment variable `HADOOP_CONF_DIR`. This PR fixes it by setting it correctly.
Replace the original `HDFS_SITE_CONFIG` config with the env variable`HADOOP_CONF_DIR`.
This change is already …
=> [FLINK-36258][config] set `HADOOP_CONF_DIR` to config hadoop in YarnFileStageTestS3ITCase

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStConfigurableOptions.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStOptions.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateExecutor.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateExecutorTest.java
This PR makes read/write state requests execute in different executors.
- Add `EXECUTOR_READ_IO_PARALLELISM` and `EXECUTOR_WRITE_IO_PARALLELISM` options.
- Make read/write state requests execute in different executors.
This change is already covered by existing tests `ForStStateExecutorTest`. …
=> [FLINK-36321][state/forst] Execute read/write state request in different executors

flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/UnifiedSinkMigrationITCase.java
UnifiedSinkMigrationITCase assumed that we also commit partial batches of committables. However, that was never the intend and fixed in FLINK-25920. This commit adjusts the test.
=> [hotfix] Fix UnifiedSinkMigrationITCase

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStConfigurableOptions.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStOptions.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateExecutor.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateExecutorTest.java
This PR supports dispatch state requests in task thread.
- Add `state.backend.forst.executor.inline-coordinator` to allow dispatching state requests in task thread.
This change is already covered by existing tests `ForStStateExecutorTest`.
=> [FLINK-36373][state/forst] Support dispatch state requests in task thread

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java, flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamingRuntimeContext.java, flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/StreamingRuntimeContextTest.java
We don't support state v1 when enabling async state processing, or state v2 when disabling async state processing. This PR gives user a more friendly error or warn message for it.
- Error message when using wrong async operator with state api (api v1 with async processing, or api v2 without async processing).
- Warn message when using `AsyncKeyedStateBackendAdaptor`
- The S3 file …
=> [FLINK-36376] More friendly error or warn message for misconfigured statebackend with async state processing

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateRequestType.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/AbstractAggregatingState.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractAggregatingStateTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractKeyedStateTestBase.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStAggregatingState.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateRequestClassifier.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStDBOperationTestBase.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateExecutorTest.java
Implement Aggregating Async State API for ForStStateBackend
- *Deser/ser for Aggregating state*
- *Build put/get request*
`ForStStateExecutorTest` and `InternalAggregatingStateTest` for testing get and put operation.
=> [FLINK-34975][state/forst] Implement Aggregating Async State API for ForStStateBackend

flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateExecutorTest.java
Compile error due to creating invoker from one PR and modifying the signature by another PR.
=> [hotfix] Compile error of ForStStateExecutor

flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE, flink-formats/flink-sql-avro/src/main/resources/META-INF/NOTICE, pom.xml
Bump Avro dependency version from 1.11.3 to 1.11.4
Bump Avro dependency version from 1.11.3 to 1.11.4 in pom and NOTICE
=> [FLINK-36420][Formats/Avro] Bump avro from 1.11.3 to 1.11.4

docs/content/docs/deployment/advanced/logging.md, flink-dist/src/main/resources/config.yaml
Make it easier to discover the configuration that was added in FLINK-33166 / #23476.
This will help users when troubleshooting to increase logging level.
=> Add docs and config entry for default log level config setting

flink-tests/src/test/java/org/apache/flink/test/recovery/SimpleRecoveryITCaseBase.java
Fix unstable test case SimpleRecoveryITCaseBase#testFailedRunThenSuccessfulRun
=> [FLINK-36444] Fix unstable test case SimpleRecoveryITCaseBase#testFailedRunThenSuccessfulRun

.gitignore
*Add .java-version to git ignore*
=> [FLINK-36447][misc] Add .java-version to git ignore

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStMapState.java
This PR removes string.format() in critical path in ForSt map state.
- Remove string.format() in `ForStMapState#buildDBPutRequest`
- The runtime per-record code paths (performance sensitive): (yes)
- The S3 file …
=> [hotfix][state/forst] Remove string.format() in critical path

docs/layouts/shortcodes/generated/rest_v1_dispatcher.html, docs/static/generated/rest_v1_dispatcher.yml, flink-tests/src/test/java/org/apache/flink/test/misc/CustomSerializationITCase.java
=> [hotfix][doc] Update rest documentation

flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/FileSystemTableSource.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/connector/file/table/FileSystemTableSourceWithPartitionsITCase.java
=> [FLINK-30899][connector/filesystem] Fix FileSystemTableSource incorrectly selecting fields on partitioned tables

flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointRescaleITCase.java
Fix IllegalAccessError in UnalignedCheckpointRescaleITCase during JDK17 runs.
This pull request attempts to run Flink CI in jdk 17 by modifying the ci envrionment, and the ci result can be found at: https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=62957&view=logs&j=af184cdd-c6d8-5084-0b69-7e9c67b35f7a. …
=> [FLINK-36350][tests] Fix IllegalAccessError in UnalignedCheckpointRescaleITCase during JDK17 runs

flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGenerator.java, flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/util/ChainedOperatorHashInfo.java, flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/util/ChainedSourceInfo.java, flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/util/JobVertexBuildContext.java, flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/util/OperatorChainInfo.java, flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/util/OperatorInfo.java
Refactor the StreamGraphGenerator by introducing the JobVertexBuildContext to make more methods reusable. 
- Introduce the JobVertexBuildContext to store context information during the JobVertex build process.
- Change methods in StreamGraphGenerator that may be reused to public static.
This is just a code refactoring and does not require new test cases. …
=> [FLINK-36335][runtime] Improving Method Reusability in StreamGraphGenerator with JobVertexBuildContext

docs/content.zh/docs/dev/table/sql/describe.md, docs/content/docs/dev/table/sql/describe.md, flink-table/flink-sql-client/src/test/resources/sql/function.q, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/operation/OperationExecutor.java, flink-table/flink-sql-parser/src/main/codegen/data/Parser.tdd, flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl, flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/dql/SqlRichDescribeFunction.java, flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/dql/SqlRichDescribeTable.java, flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/ContextResolvedFunction.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/FunctionCatalog.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/DescribeFunctionOperation.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlDescribeFunctionConverter.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlNodeConverters.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/calcite/FlinkPlannerImpl.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlOtherOperationConverterTest.java
This PR introduces `DESCRIBE FUNCTION` syntax, allowing users to describe the metadata of a given function. The design for this is covered under FLIP-465: https://cwiki.apache.org/confluence/display/FLINK/FLIP-465%3A+Introduce+DESCRIBE+FUNCTION
- Add `Parser` support for the next syntax
- Add `FunctionDefinition` as a new optional parameter for `ContextResolvedFunction`
- The bulk of the implementation logic is in `DescribeFunctionOperation`
- Added end to end tests in `flink-table/flink-sql-client/src/test/resources/sql/function.q`
- Added unit tests in `FlinkSqlParserImplTest` and `SqlOtherOperationConverterTest` …
=> [FLINK-35822] Introduce DESCRIBE FUNCTION

flink-core/src/main/java/org/apache/flink/core/security/FlinkSecurityManager.java
Backport of https://github.com/apache/flink/pull/25495.
=> [1.19][FLINK-36511] Prevent StackOverflow in FlinkSecurityManager

flink-core/src/main/java/org/apache/flink/core/security/FlinkSecurityManager.java
Backport of https://github.com/apache/flink/pull/25495.
=> [1.20][FLINK-36511] Prevent StackOverflow in FlinkSecurityManager

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java, flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperator.java, flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperatorV2.java, flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/AbstractAsyncStateStreamOperatorV2Test.java
This PR leverages Epoch Manager to handle the `LatencyMarker`/`RecordAttribute` emitting under async execution model.
- Implement `AbstractAsyncStateStreamOperator#reportOrForwardLatencyMarker`
- Implement `AbstractAsyncStateStreamOperator#processRecordAttributes`
This change can be verified by `AsyncExecutionControllerTest#testEpochManager`. …
=> [FLINK-35031][runtime] LatencyMarker/RecordAttribute emitting under async execution model

flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/catalog/hive/HiveCatalogGenericMetadataTest.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/catalog/hive/HiveCatalogHiveMetadataTest.java, flink-python/pyflink/table/catalog.py, flink-python/pyflink/table/tests/test_catalog.py, flink-python/pyflink/util/exceptions.py, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/ContextResolvedModel.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/GenericInMemoryCatalog.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/listener/AlterModelEvent.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/listener/CreateModelEvent.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/listener/DropModelEvent.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogManagerTest.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogTestBase.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/GenericInMemoryCatalogTest.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/Catalog.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogModel.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogPropertiesUtil.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/DefaultCatalogModel.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/DefaultResolvedCatalogModel.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/ResolvedCatalogModel.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/TemporaryOperationListener.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/exceptions/ModelAlreadyExistException.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/exceptions/ModelNotExistException.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/catalog/CatalogPropertiesUtilTest.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/catalog/CatalogTest.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/TableEnvironmentTest.scala
[## What is the purpose of the change
Catalog changes to support model resource
* Add `CatalogModel` related resource
* Add model CRUD operations in `CatalogManager` and `Catalog`
Unit test added
](https://media.giphy.com/media/KJ1f5iTl4Oo7u/giphy-downsized-large.gif)
=> [FLINK-35016] catalog changes for model resource

flink-rpc/flink-rpc-akka/pom.xml, flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/pekko/ActorSystemBootstrapTools.java, flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/pekko/PekkoUtils.java, flink-rpc/flink-rpc-akka/src/main/resources/META-INF/NOTICE
Updates Pekko dependency to 1.1.2 which in turn upgrades Netty 3 to 4 (addressing [FLINK-29065](https://issues.apache.org/jira/browse/FLINK-29065) and removing several CVEs from Flink). Pekko 1.1 also upgrades other dependencies such as slf4j and Jackson. For more details see the [Pekko 1.1 release notes](https://pekko.apache.org/docs/pekko/current/release-notes/releases-1.1.html).
- Update Pekko version from 1.0.1 to 1.1.2
- Replace Pekko Netty 3 dependency with flink-shaded Netty 4
- Update Netty imports in `ActorSystemBootstrapTools` and `PekkoUtils`
- Update NOTICE file
This change is covered by existing tests in flink-rpc. …
=> [FLINK-36510][rpc] bump pekko to 1.1.2, remove netty 3

flink-rpc/flink-rpc-akka/pom.xml, flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/pekko/ActorSystemBootstrapTools.java, flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/pekko/PekkoUtils.java, flink-rpc/flink-rpc-akka/src/main/resources/META-INF/NOTICE
Updates Pekko dependency to 1.1.2 which in turn upgrades Netty 3 to 4 (addressing [FLINK-29065](https://issues.apache.org/jira/browse/FLINK-29065) and removing several CVEs from Flink). Pekko 1.1 also upgrades other dependencies such as slf4j and Jackson. For more details see the [Pekko 1.1 release notes](https://pekko.apache.org/docs/pekko/current/release-notes/releases-1.1.html). CC @ferenc-csaky :smile:
- Update Pekko version from 1.0.1 to 1.1.2
- Replace Pekko Netty 3 dependency with flink-shaded Netty 4 (and test-scoped direct Netty 4 dependency)
- Update Netty imports in `ActorSystemBootstrapTools` and `PekkoUtils`
- Update NOTICE file
This change is covered by existing tests in flink-rpc. …
=> [FLINK-36510][rpc] bump pekko to 1.1.2, remove netty 3 (backport to release-1.20)

pom.xml
Speed up the spotless.
JIRA: https://issues.apache.org/jira/browse/FLINK-36542
- Upgrade spotless-maven-plugin version to 2.35.0,  enable upToDateChecking by default.
Use ` mvn spotless:apply` or ` mvn spotless:check` to verify.
- Dependencies (does it add or upgrade a dependency):  yes
=> [FLINK-36542] Bump spotless-maven-plugin version to 2.35.0

docs/setup_docs.sh
Add docs for new Opensearch connector release
In fact docs are same for both v1 and v2, so just referencing to one branch (also references to multiple branches are not supported here IIRC)
=> [FLINK-35140][docs] Update Opensearch connector docs for 1.2.0 and 2.0.0 releases

flink-table/flink-sql-parser/pom.xml
This PR will remove the log4j dependency from the **fmpp-maven-plugin**
In the maven package - flink-sql-parser, the fmpp-maven-plugin has a dependency of xbean-reflect, which in-turn has a dependency of log4j jar 1.12. We can exclude this dependency from xbean-reflect. Attaching details below:
https://mvnrepository.com/artifact/org.apache.xbean/xbean-reflect/3.4
https://github.com/apache/flink/blob/master/flink-table/flink-sql-parser/pom.xml
- Does this pull request introduce a new feature? NO
=> [FLINK-35999] Migrate from fmpp-maven-plugin to drill-fmpp-maven-plugin

flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/EmbeddedRocksDBStateBackend.java
Add constructors for o.a.f.contrib.streaming.state.EmbeddedRocksDBStateBackend to maintain interface compatibility.
Add ```EmbeddedRocksDBStateBackend(boolean enableIncrementalCheckpointing)``` and  ```EmbeddedRocksDBStateBackend(TernaryBoolean enableIncrementalCheckpointing)``` …
=> [FLINK-4602][State] Add constructors for o.a.f.contrib.streaming.state.EmbeddedRocksDBStateBackend to maintain interface compatibility.

flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinator.java, flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinatorHolder.java, flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/RecreateOnResetOperatorCoordinator.java, flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinator.java, flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContext.java, flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorProvider.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/MockOperatorCoordinatorContext.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorAlignmentTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContextTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorTestBase.java, flink-tests/src/test/java/org/apache/flink/test/misc/JobIDLoggingITCase.java
Log JobID from the SourceCoordinator
Log JobID from the SourceCoordinator
Adds a couple of assertions to the `JobIDLoggingITCase` …
=> [FLINK-36624][checkpointing] Log JobID from the SourceCoordinator

flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java
Log jobID in TaskExecutor#failTask
Log jobID in TaskExecutor#failTask
None directly, that's a simple change only in logging which is non trivial to test. 
Regardless of that, bugs caused by this changed would have been detected via a multitude of ITCases.
- The serializers: (yes / no ****/ don't know) …
=> [FLINK-36099][task] Log jobID in TaskExecutor#failTask

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/FlinkRelBuilder.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/hint/FlinkHints.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/EventTimeTemporalJoinRewriteRule.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/physical/stream/WatermarkAssignerChangelogNormalizeTransposeRule.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/calcite/LogicalWatermarkAssigner.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/calcite/WatermarkAssigner.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/logical/FlinkLogicalWatermarkAssigner.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalWatermarkAssigner.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/physical/stream/StreamPhysicalWatermarkAssignerRule.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/hints/stream/StateTtlHintTest.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/hints/stream/StateTtlHintTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/ProjectWatermarkAssignerTransposeRuleTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/TableTestBase.scala
This is a cherry-pick of https://github.com/apache/flink/commit/4101316ef37d3a7082bff57cb732f4e9e0349d09
=> [BP-1.19][FLINK-36417][table] Add support for hints in WatermarkAssigner

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/FlinkRelBuilder.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/hint/FlinkHints.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/EventTimeTemporalJoinRewriteRule.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/physical/stream/WatermarkAssignerChangelogNormalizeTransposeRule.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/calcite/LogicalWatermarkAssigner.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/calcite/WatermarkAssigner.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/logical/FlinkLogicalWatermarkAssigner.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalWatermarkAssigner.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/physical/stream/StreamPhysicalWatermarkAssignerRule.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/hints/stream/StateTtlHintTest.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/hints/stream/StateTtlHintTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/ProjectWatermarkAssignerTransposeRuleTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/TableTestBase.scala
This is a cherry-pick of https://github.com/apache/flink/commit/4101316ef37d3a7082bff57cb732f4e9e0349d09
=> [BP-1.20][FLINK-36417][table] Add support for hints in WatermarkAssigner

docs/setup_docs.sh
Update AWS docs for v5.0
Update AWS docs for v5.0
=> [FLINK-36668][docs] Update AWS docs for v5.0

docs/setup_docs.sh
Update AWS docs for v5.0
Update AWS docs for v5.0
=> Update AWS docs for v5.0

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraphGenerator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/partitioner/ForwardForConsecutiveHashPartitioner.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/partitioner/StreamPartitioner.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/translators/SinkTransformationTranslator.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SinkTransformationTranslatorITCaseBase.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SinkV1TransformationTranslatorITCase.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperatorTestBase.java, flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/SinkITCase.java
=> [FLINK-36287] Disallow UC for inner sink channels [1.20]

flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraphBuilder.java
Remove DefaultExecutionGraph's jobType  (added with https://github.com/apache/flink/pull/24718)
Remove DefaultExecutionGraph's jobType,  because it can get it from jobInformation
n/a …
=> [hotfix] Remove DefaultExecutionGraph's jobType

docs/content.zh/docs/dev/datastream/operators/process_function.md, docs/content.zh/docs/dev/table/data_stream_api.md, docs/content.zh/docs/dev/table/sourcesSinks.md, docs/content.zh/docs/try-flink/datastream.md, docs/content/docs/dev/datastream/operators/process_function.md, docs/content/docs/dev/table/data_stream_api.md, docs/content/docs/dev/table/sourcesSinks.md, docs/content/docs/try-flink/datastream.md
=> [FLINK-35977][doc] Missing an import in datastream.md [1.20 backport]

docs/content.zh/docs/dev/datastream/operators/process_function.md, docs/content.zh/docs/dev/table/data_stream_api.md, docs/content.zh/docs/dev/table/sourcesSinks.md, docs/content.zh/docs/try-flink/datastream.md, docs/content/docs/dev/datastream/operators/process_function.md, docs/content/docs/dev/table/data_stream_api.md, docs/content/docs/dev/table/sourcesSinks.md, docs/content/docs/try-flink/datastream.md
This is a backport of https://github.com/apache/flink/pull/25153
=> [FLINK-35977][doc] Missing an import in datastream.md [1.19 backport]

docs/setup_docs.sh
=> [FLINK-35136][docs] Bump HBase connector docs version to v4.0

flink-runtime-web/pom.xml
Contribute-to: https://issues.apache.org/jira/browse/FLINK-36739
This pull request raises the version of the NodeJS module which is a pre-requisite to upgrade dependencies in order to address vulnerabilities in Runtime/WebFrontend component. 
There will be another PR to fix vulnerabilities once this is merged.
NodeJS is v22.11.0/Npm is 10.9.0
The Flink UI should be accessible without any difference
- Does …
=> [FLINK-36739] [WebFrontend] Update the NodeJS to v22.11.0 (LTS)

flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/header/session/ConfigureSessionHeaders.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/header/statement/CompleteStatementHeaders.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/util/SqlGatewayRestAPIVersion.java, flink-table/flink-sql-gateway/src/test/resources/sql_gateway_rest_api_v4.snapshot
*Bump up the SQL Gateway REST API verison.*
=> [FLINK-36756][sql-gateway] Bump up the sql gateway rest version

flink-dist/src/main/resources/config.yaml
Do not use deprecated configs in example config.yaml. Currently, in the example `flink-dist/src/main/resources/config.yaml`, we provided some deprecated configs to guide users to set checkpoints/savepoints. We should update with the new configs.
ref: 1. FLIP-406: https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=284789560
2. https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/config/#checkpointing
- Use `execution.checkpointing.incremental` instead of the deprecated `state.backend.incremental`
- Use `execution.checkpointing.dir` instead of the deprecated `state.checkpoints.dir`
- Use `execution.checkpointing.savepoint-dir` instead of the deprecated `state.savepoints.dir` …
=> [hotfix][config] Do not use deprecated configs in example config.yaml

flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/sink/compactor/CompactorOperatorTest.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/GlobalCommitterOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/StandardSinkTopologies.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/SupportsPreCommitTopology.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraphGenerator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/transformations/GlobalCommitterTransform.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManager.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManagerImpl.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollector.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/translators/GlobalCommitterTransformationTranslator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/translators/SinkTransformationTranslator.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/connector/sink2/CommittableSummaryAssert.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/connector/sink2/CommittableWithLineageAssert.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/connector/sink2/GlobalCommitterOperatorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/connector/sink2/SinkV2Assertions.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SinkTransformationTranslatorITCaseBase.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SinkV1TransformationTranslatorITCase.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SinkV2TransformationTranslatorDeprecatedITCase.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SinkV2TransformationTranslatorITCase.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperatorTestBase.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkTestUtil.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperatorTestBase.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/TestSinkV2.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManagerImplTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorSerializerTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/SubtaskCommittableManagerTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/deprecated/TestSinkV2.java
=> [FLINK-36379] Improve (Global)Committer with UC disabled [1.19]

flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/application/Printer.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/application/ScriptExecutor.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/operation/OperationExecutor.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/result/ResultFetcher.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/AbstractSqlGatewayStatementITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/AbstractSqlGatewayStatementITCaseBase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/application/PrinterTest.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/application/ScriptExecutorITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/result/ResultFetcherTest.java, flink-table/flink-sql-gateway/src/test/resources/application/comment.q, flink-table/flink-sql-gateway/src/test/resources/application/error.q, flink-table/flink-sql-gateway/src/test/resources/sql/begin_statement_set.q, flink-table/flink-sql-gateway/src/test/resources/sql/call_procedure.q, flink-table/flink-sql-gateway/src/test/resources/sql/catalog_database.q, flink-table/flink-sql-gateway/src/test/resources/sql/statement_set.q, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableResultImpl.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableResultUtils.java
*Introduce an executor to run the script.*
- *Introduce printer to print the statement and results on the console.*
- *Introduce executor to run the statement one by one*
- *Introduce printer test to verify the style.*
- *Introduce ScriptExecutorITCase to verify the execution results: the input contains all kinds of statements*
- The serializers: (yes / **no** / …
=> [FLINK-36757][sql-gateway] Introduce ScripExecutor to run the script

README.md
As we have dropped the support for Java 8.
=> [hotfix] Remove Java 8 in README

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/catalog/SqlCatalogViewTable.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/catalog/JavaCatalogTableTest.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/catalog/JavaCatalogTableTest.xml
Fix Views so that they may have time attributes.
Added a unit test
=> [FLINK-36883] Adapt time attributes from the VIEWs query

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/catalog/SqlCatalogViewTable.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/catalog/JavaCatalogTableTest.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/catalog/JavaCatalogTableTest.xml
backport of https://github.com/apache/flink/pull/25779
=> [FLINK-36883] Adapt time attributes from the VIEWs query (#25779)

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java, flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/AbstractAsyncStateStreamOperatorV2Test.java
The watermark status is not properly handle in async state processing. It is emitted to downstream synchronously, while the watermarks will respect the ongoing timer processing. That should be fixed and aligned.
- Rewrite `processWatermarkStatus` in `AbstractAsyncStateStreamOperatorV2`  and `AbstractAsyncStateStreamOperator`, making watermark status also respect the timers.
- The S3 file …
=> [FLINK-36892][Runtime] Properly handle the watermark status within async state processing

docs/content/docs/dev/datastream/fault-tolerance/serialization/third_party_serializers.md, docs/content/docs/dev/datastream/fault-tolerance/serialization/types_serialization.md
Fix document error on how to programmatically configure serialization.
Since the type of `PipelineOptions.SERIALIZATION_CONFIG` is `ConfigOption<List<String>>`, we should provide a list of String when programmatically configuring it.
This change is just a doc fix.
Not applied.
=> [FLINK-36904] Fix document error on how to programmatically configure serialization

flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveBatchSchedulerFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/DefaultBatchJobRecoveryHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/NettyShuffleMaster.java, flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/ShuffleMaster.java, flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/ShuffleMasterSnapshotUtil.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptivebatch/BatchJobRecoveryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/shuffle/ShuffleMasterSnapshotUtilTest.java
[FLINK-36873][runtime] Adapting batch job progress recovery to Apache Celeborn.
Adapting batch job progress recovery to Apache Celeborn.
This change added tests and can be verified by ShuffleMasterSnapshotUtilTest
- If …
=> [FLINK-36873][runtime] Adapting batch job progress recovery to Apache Celeborn.

flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveExecutionPlanSchedulingContextTest.java
[FLINK-36921][runtime] Fix unstable AdaptiveExecutionPlanSchedulingContextTest
=> [FLINK-36921][runtime] Fix unstable AdaptiveExecutionPlanSchedulingContextTest

flink-runtime/src/test/java/org/apache/flink/streaming/util/asyncprocessing/AsyncKeyedMultiInputStreamOperatorTestHarness.java, flink-runtime/src/test/java/org/apache/flink/streaming/util/asyncprocessing/AsyncKeyedOneInputStreamOperatorTestHarness.java, flink-runtime/src/test/java/org/apache/flink/streaming/util/asyncprocessing/AsyncKeyedTwoInputStreamOperatorTestHarness.java, flink-runtime/src/test/java/org/apache/flink/streaming/util/asyncprocessing/AsyncProcessingTestUtil.java
#25802 introduces three test harnesses for async state processing. However, when there is a failure on any async thread, the test thread itself will keep `get()` the future result. This PR exposes the inner exception to the future and make the test fast fail with root cause print.
- Make the `MockEnvironment` accept any external exception. The configure goes in the constructor of three test harnesses.
- Let any execution of task thread check the env exception, as well as check the exception after. (Only after is not enough since the task and test thread runs in parallel).
This change added tests and can be verified manually: throws exception in the `triggerAction` of `EpochManager#onNonRecord` and see if there is any exception in test. …
=> [FLINK-35904][test] Enhance test harness for async state processing with fast fail

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateExecutor.java
Wait for the ForSt state executor to shutdown when disposing.
- Wait when `ForStStateExecutor#shutdown`
This change is a trivial rework and already covered by existing tests.
=> [FLINK-36961][state/forst] Wait for the ForSt state executor to shutdown when disposing

flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/connector/source/DataStreamScanProvider.java
This is a subtask of [[FLINK-36476](https://issues.apache.org/jira/browse/FLINK-36476)](https://issues.apache.org/jira/browse/FLINK-36476) Remove all deprecated methods under public APIs in table modules
Remove deprecated method
=> [FLINK-36490][TABLE API] Remove the deprecated method in DataStreamScanProvider

flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/connector/sink/DataStreamSinkProvider.java
This is a subtask of [[FLINK-36476](https://issues.apache.org/jira/browse/FLINK-36476)](https://issues.apache.org/jira/browse/FLINK-36476) Remove all deprecated methods under public APIs in table modules
Remove deprecated method …
=> [FLINK-36491][TABLE API] Remove the deprecated method in DataStreamSinkProvider

docs/content.zh/docs/dev/table/functions/udfs.md, docs/content/docs/dev/table/functions/udfs.md
Unmodified backport of https://github.com/apache/flink/pull/23439 to 1.20
=> [FLINK-33117][table][docs] Fix scala example in udfs page

flink-core/src/main/java/org/apache/flink/util/FileUtils.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/application/ScriptRunner.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/application/ScriptRunnerITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/utils/MockHttpServer.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/application/SqlDriver.java
*Add a SqlDriver to load the ScriptRunner to execute the script. It supports to read file from remote filesystem or http(s) service.*
- *Introduce the driver to load the specified runner and script in the external system.*
- *Introduce a runner to load the required environment to run the tests.*
- *Added integration tests to run script in the filesystem or http server.*
- *Added integration tests to run script .* …
=> [FLINK-36758][sql-gateway] Introduce driver to load the application in application mode

flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/IntermediateDataSetID.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveBatchSchedulerFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveExecutionHandlerFactory.java, flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGenerator.java, flink-tests/src/test/java/org/apache/flink/test/scheduling/JMFailoverITCase.java
[FLINK-36850][runtime] Disable adaptive batch execution when batch job progress recovery is enabled
- Support IntermediateDataSetID generated from source JobVertexID and consumer stream node id.
- Disable adaptive batch execution when batch job progress recovery is enabled
This change is already covered by existing tests JMFailoverITCase
- The …
=> [FLINK-36850][runtime] Disable adaptive batch execution when batch job progress recovery is enabled

flink-table/flink-table-common/src/main/java/org/apache/flink/table/expressions/CallExpression.java
[FLINK-36500] https://issues.apache.org/jira/browse/FLINK-36500 Remove all deprecated methods in CallExpression
Removed all deprecated methods in CallExpression
- If yes, how is the feature documented? not applicable 
-
=> [FLINK-36500][table-common] Remove all deprecated methods in CallExpression

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystem.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/FileMappingManager.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/MappingEntry.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/restore/ForStIncrementalRestoreOperation.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/FileMappingManagerTest.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystemTest.java
Not all file systems currently support `Symbolic Link`, such as `FAT32`, `ISO9660` and so on. `Fast Link` is a `Symbolic Link` designed specifically for **Disaggregated State Storage(ForSt)**, even if the underlying layer file system does not support `Symbolic Link`. on the basis of `Symbolic Link`, `Fast link` will also provide the file ownership management(claim and no-claim) in the future.
This pr implements fast link for ForStFileSystem.
- Introduce `FileMappingManager` to manager the file mapping in ForStFileSystem.
- Adapt `ForStFileSystem` to `FileMappingManager`  
- `FileMappingManagerTest`
This change is already covered by existing tests:
- `ForStStateBackendV2Test#testAsyncStateBackendScaleUp`
- …
=> [FLINK-36935][state/forst] Implement fast link for ForStFileSystem

docs/layouts/shortcodes/generated/environment_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/ConfigConstants.java, flink-core/src/main/java/org/apache/flink/configuration/CoreOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/ContaineredTaskManagerParameters.java, flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java, flink-yarn/src/test/java/org/apache/flink/yarn/UtilsTest.java, flink-yarn/src/test/java/org/apache/flink/yarn/YarnClusterDescriptorTest.java
Make Flink on YARN honor `env.java.home`.
Inject JM/TM JAVA_HOME environment variable with the value of `env.java.home` for YARN.
Added UTs on YARN env setting.
- If yes, how is the feature documented? (**not applicable** …
=> [FLINK-22091][yarn] Make Flink on YARN honor env.java.home

docs/content.zh/docs/dev/table/materialized-table/statements.md, docs/content/docs/dev/table/materialized-table/statements.md
*Fix examples in materialized table docs.*
- *Fix examples in materialized table docs*
- If yes, how is the feature documented? (It's a document pr)
=> [FLINK-37014][doc] Fix examples in materialized table docs

docs/content.zh/docs/dev/table/materialized-table/statements.md, docs/content/docs/dev/table/materialized-table/statements.md
1.20 backport of [PR](https://github.com/apache/flink/pull/25904)
=> [BP-1.20][FLINK-37014][doc] Fix examples in materialized table docs

flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/WatermarkITCase.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/generated/GeneratedWatermarkGeneratorSupplier.java
Unmodified backport of https://github.com/apache/flink/pull/25921 to 1.19
=> [FLINK-37025] Fix generating watermarks in SQL on-periodic (#25921)

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/sql/FlinkSqlOperatorTable.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/FunctionITCase.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/DynamicFunctionPlanTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/DynamicFunctionPlanTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/MatchRecognizeTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/NonDeterministicDagTest.xml
Enabled dynamic time-related functions to be called with or without parenthesis
- Add function call syntax for dynamic functions
- Update planner tests with function call
- Add testDynamicDatetimeFunctions and testDynamicDatetimeFunctionsAreEqual
- Added testDynamicDatetimeFunctions and testDynamicDatetimeFunctionsAreEqual to test all modified functions
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: don't know …
=> [FLINK-36910][table] Add function call syntax support to time-related dynamic functions

flink-clients/src/test/java/org/apache/flink/client/program/artifact/ArtifactFetchManagerTest.java
Backport of https://github.com/apache/flink/pull/24931.
=> [BP-1.19][FLINK-35512][tests] Do not depend on the `flink-clients` jar in `ArtifactFetchManagerTest`

docs/content.zh/docs/ops/metrics.md, docs/content/docs/ops/metrics.md, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateBackend.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystem.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/BundledCacheLimitPolicy.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/CacheLimitPolicy.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/FileBasedCache.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/SizeBasedCacheLimitPolicy.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/SpaceBasedCacheLimitPolicy.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStExtension.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStResourceContainerTest.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateBackendConfigTest.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystemTest.java
This pr introduces metrics for forst cache.
- Add metrics for `FileBasedCache`.
- `ForStFlinkFileSystemTest#testSstFileInCache`
=> [FLINK-36899][state/forst] Introduce metrics for forst cache

docs/layouts/shortcodes/generated/optimizer_config_configuration.html, flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/DefaultStreamGraphContext.java, flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/StreamGraphContext.java, flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/util/ImmutableStreamEdge.java, flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/util/StreamEdgeUpdateRequestInfo.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptivebatch/StreamGraphOptimizerTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/DefaultStreamGraphContextTest.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/config/OptimizerConfigOptions.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/processor/AdaptiveJoinProcessor.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/delegation/BatchPlanner.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/utils/AdaptiveBatchAbstractTestBase.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/adaptive/AdaptiveJoinTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/adaptive/AdaptiveJoinTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/adaptive/AdaptiveBroadcastJoinITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/adaptive/AdaptiveJoinITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/adaptive/AdaptiveSkewedJoinITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/join/JoinITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/utils/AdaptiveBatchTestBase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/utils/BatchTableEnvUtil.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/utils/BatchTestBase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/TableTestBase.scala, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/strategy/AdaptiveBroadcastJoinOptimizationStrategy.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/strategy/AdaptiveJoinOptimizationUtils.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/strategy/AdaptiveSkewedJoinOptimizationStrategy.java
The AdaptiveSkewedJoinOptimizationStrategy is responsible for adjusting the StreamGraph for the skewed join operators at the runtime stage before the scheduling of the AdaptiveJoin operator. 
- Introduce configuration options for adaptive skewed join optimization. 
- Modify AdaptiveJoinProcessor to support adaptive skewed join optimization.
- Improve StreamGraphContext to provide the capability to modify the IntraInputKeyCorrelation of stream edge.
- Introduce the AdaptiveSkewedJoinOptimizationStrategy. …
=> [FLINK-36629][table-planner] Introducing the AdaptiveSkewedJoinOptimizationStrategy

docs/content/docs/dev/datastream/fault-tolerance/serialization/custom_serialization.md, docs/content/docs/dev/datastream/fault-tolerance/serialization/types_serialization.md
Remove Scala contents in serialization doc as Scala API has been removed. The Chinese document is intentionally not touched, I'll sync the latest content there after finishing recent serialization changes.
Merely doc changes.
Not applicable.
Not applicable.
=> [FLINK-37015][doc] Remove Scala contents in serialization doc

flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/source/abilities/SupportsProjectionPushDown.java
Remove all deprecated method SupportsProjectionPushDown#applyProjection
Remove all deprecated method SupportsProjectionPushDown#applyProjection
This change is a simple code cleanup without any specific usage.
- If yes, …
=> [FLINK-36499][table]Remove deprecated method `SupportsProjectionPushDown#applyProjection`

docs/content.zh/docs/ops/metrics.md, docs/content/docs/ops/metrics.md, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateRequestBuffer.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java, flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AbstractStateIteratorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionControllerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractAggregatingStateTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractKeyedStateTestBase.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractReducingStateTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/StateBackendTestV2Base.java, flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/InternalTimerServiceAsyncImplTest.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateTestBase.java
Add metrics for AsyncExecutionController.
- Add metrics for AsyncExecutionController.
- Add AEC section in `metrics.md`
- AsyncExecutionControllerTest#testBasicRun()
=> [FLINK-35405][runtime] Add metrics for AsyncExecutionController

flink-python/src/main/java/org/apache/flink/streaming/api/operators/python/process/timer/TimerRegistrationAction.java, flink-python/src/main/java/org/apache/flink/streaming/api/runners/python/beam/BeamPythonFunctionRunner.java
TimerRegistrationAction in unregisteredTimers is not cleaned up properly after the timers are registered, especially for processing time timers. This will cause all TimerRegistrationAction to be accumulated in JVM and eventually OOM.
- add logic to clean up TimerRegistrationAction from the unregisteredTimers list in TimerRegistrationAction.run() after the timer is registered. 
- add logic to synchronize modification to unregisteredTimers between grpc thread and main thread.
- *Manually verified the change by running a stress …
=> [FLINK-37168][python] clean up TimerRegistrationAction in unregisteredTimers list after timers are registered

docs/setup_hugo.sh
When running the local build_docs command, there's an error on mac
`./build_docs.sh: line 41: /usr/local/bin/hugo: cannot execute binary file: Exec format error`
This is because the setup_hugo script only install the binary for linux. We should update it so it checks if the OS is mac and download the mac binaries
- *Update setup_hugo script so it downloads mac binaries if OS is darwin*
Logic for linux is the same. Tested this for mac locally. …
=> [FLINK-37176][docs] Support mac binary for setup_hugo.sh

pom.xml
Correct version string of maven-enforcer-plugin requireJavaVersion in release profile.
- Correct version string of maven-enforcer-plugin requireJavaVersion in release profile.
=> [FLINK-37189] Correct version string of maven-enforcer-plugin requireJavaVersion in release profile

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/QueryOperationCatalogView.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/catalog/JavaCatalogTableTest.java
When working on https://github.com/apache/flink/commit/6748cd0659a1f30579aa66d179ef3c649ac7439c I missed a case which resulted in wrong column names in `SHOW CREATE VIEW`
Added a test …
=> [FLINK-37098] Fix UnresolvedSchema of QueryOperationCatalogView

.github/workflows/nightly-trigger.yml, flink-annotations/src/main/java/org/apache/flink/FlinkVersion.java
=> [FLINK-37035][release] Add new version 2.1 and update GHA nightly build versions

.github/workflows/docs.yml
=> [FLINK-37035][release] Build doc for release-2.0 branch

docs/content/docs/deployment/memory/mem_tuning.md
Backport of https://github.com/apache/flink/pull/26043
=> [BP-2.0][FLINK-37099][docs] Document memory/performance considerations and config possibilities for Netty4

docs/content/docs/deployment/memory/mem_tuning.md
1.20 backport of https://github.com/apache/flink/pull/26043
=> [BP-1.20][FLINK-37099][docs] Document memory/performance considerations and config possibilities for Netty4

docs/content/docs/deployment/memory/mem_tuning.md
1.19 backport of https://github.com/apache/flink/pull/26043
=> [BP-1.19][FLINK-37099][docs] Document memory/performance considerations and config possibilities for Netty4

flink-dist/src/main/resources/META-INF/NOTICE, flink-state-backends/flink-statebackend-rocksdb/pom.xml
Bump frocksdbjni to 8.10.0-ververica-1.0
- Update pom.xml of flink-statebackend-rocksdb
=> [FLINK-35578][state/rocksdb] Bump frocksdbjni to 8.10.0-ververica-1.0

flink-dist/src/main/resources/META-INF/NOTICE, flink-state-backends/flink-statebackend-rocksdb/pom.xml
This is a backport PR to 2.0 for https://github.com/apache/flink/pull/26033
Bump frocksdbjni to 8.10.0-ververica-1.0
- Update pom.xml of flink-statebackend-rocksdb
=> [BP-2.0][FLINK-35578][state/rocksdb] Bump frocksdbjni to 8.10.0-ververica-1.0

docs/content/docs/ops/state/task_failure_recovery.md
A minor typo fix in task_failure_recovery.md's java example code, the Duration is mispelled Durartion.
Doc change
=> [hotfix] [docs] Fix code typo in task_failure_recovery.md

docs/content.zh/docs/dev/datastream/fault-tolerance/serialization/custom_serialization.md, docs/content.zh/docs/dev/datastream/fault-tolerance/serialization/third_party_serializers.md, docs/content.zh/docs/dev/datastream/fault-tolerance/serialization/types_serialization.md
Update Chinese doc on serialization to reflect the latest changes in Flink 2.0.
Synced from the English version of the doc.
Built doc locally:
=> [FLINK-36905] Update Chinese doc on serialization to reflect the latest changes in Flink 2.0

flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/Column.java
Fix for https://issues.apache.org/jira/browse/FLINK-37098?focusedCommentId=17921143&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17921143
Since I can not reproduce the original problem. Do you mind checking if this makes the trick @afedulov ?
=> [hotfix] Mark Column#rename internal

docs/data/sql_functions.yml, docs/data/sql_functions_zh.yml
Backport of https://github.com/apache/flink/pull/26091
We currently have no examples for some functions in the documentation. 5 examples of these are unhex, btrim, percentile, translate and ETL. This PR adds examples to these.
Upon merging, I'll create another ticket for the chinese translation. 
- Added one example for each of the functions
- Checked docs locally …
=> [FLINK-37239][docs][backport] Add examples for unhex, btrim, translate, elt and percentile

flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
Change `Dispatcher#requestMultipleJobDetails` returned job details list to be ordered deterministically with job start time.
- Change return of  `Dispatcher#requestMultipleJobDetails` to be an ordered list using job start time.
- Adopt DipsatcherTest accordingly
- Added Unit tests to `DispatcherTest`
- Verified using local cluster setup …
=> [FLINK-37258][runtime] Return Ordered Job list on Disptacher#requestMultipleJobDetails

flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/sideoutput/SideOutputExample.java, flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/socket/SocketWindowWordCount.java, flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/statemachine/StateMachineExample.java, flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/windowing/GroupedProcessingTimeWindowExample.java, flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/windowing/SessionWindowing.java, flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/windowing/TopSpeedWindowing.java, flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/wordcount/WordCount.java, flink-examples/flink-examples-streaming/src/test/java/org/apache/flink/streaming/test/StreamingExamplesITCase.java, flink-examples/flink-examples-streaming/src/test/java/org/apache/flink/streaming/test/socket/SocketWindowWordCountITCase.java
This PR adds a word count example for async state usage.
- Introduce `AsyncStateWordCount` to flink-example module.
=> [FLINK-37268][example] Use async state in flink-examples-streaming

flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/AdaptiveGraphManager.java, flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/StreamEdge.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/AdaptiveGraphManagerTest.java
[BP-2.0][FLINK-37284][runtime] Fix ForwardForConsecutiveHashPartitioner cannot be chained in Adaptive batch.
=> [BP-2.0][FLINK-37284][runtime] Fix ForwardForConsecutiveHashPartitioner cannot be chained in Adaptive batch.

flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/sideoutput/SideOutputExample.java, flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/socket/SocketWindowWordCount.java, flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/statemachine/StateMachineExample.java, flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/windowing/GroupedProcessingTimeWindowExample.java, flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/windowing/SessionWindowing.java, flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/windowing/TopSpeedWindowing.java, flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/wordcount/WordCount.java, flink-examples/flink-examples-streaming/src/test/java/org/apache/flink/streaming/test/StreamingExamplesITCase.java, flink-examples/flink-examples-streaming/src/test/java/org/apache/flink/streaming/test/socket/SocketWindowWordCountITCase.java
Backport to 2.0 for https://github.com/apache/flink/pull/26117.
This PR adds async state usage to flink-examples-streaming module.
- Enable async state in `SideOutputExample`, `SocketWindowWordCount`, `StateMachineExample`, `xxxWindowExample` …
=> [BP-2.0][FLINK-37268][example] Use async state in flink-examples-streaming 

docs/content.zh/docs/dev/table/materialized-table/deployment.md, docs/content.zh/docs/dev/table/materialized-table/overview.md, docs/content.zh/docs/dev/table/materialized-table/quickstart.md, docs/content/docs/dev/table/materialized-table/deployment.md, docs/content/docs/dev/table/materialized-table/overview.md, docs/content/docs/dev/table/materialized-table/quickstart.md
BP https://github.com/apache/flink/pull/26073
*Add doc for Submitting Refresh Job of Materialized Table to Yarn/K8s*
- *Add doc for Submitting Refresh Job of Materialized Table to Yarn/K8s*
No need to verify as this pr only contains document change.
=> [BP-2.0][FLINK-37187][doc] Add doc for submitting Materialized Table refresh job to Yarn/K8s

docs/content.zh/docs/deployment/config.md, docs/content/docs/deployment/config.md
[BP-2.0][FLINK-37150][doc] Update flink configuration file documentation.
=> [BP-2.0][FLINK-37150][doc] Update flink configuration file documentation.

flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendTestBase.java
BP for https://github.com/apache/flink/pull/26094
=> [BP-1.20][FLINK-37241][runtime] Remove Mockito usage from StateBackendTestBase.

flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendTestBase.java
BP for https://github.com/apache/flink/pull/26094
=> [BP-2.0][FLINK-37241][runtime] Remove Mockito usage from StateBackendTestBase.

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/datatransfer/DataTransferStrategyBuilder.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/datatransfer/ForStStateDataTransfer.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/snapshot/ForStIncrementalSnapshotStrategy.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/snapshot/ForStNativeFullSnapshotStrategy.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/snapshot/ForStSnapshotStrategyBase.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/datatransfer/DataTransferStrategyTest.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/datatransfer/ForStStateDataTransferTest.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/snapshot/ForStIncrementalSnapshotStrategyTest.java
Fix the case when ForSt encounters the first full checkpoint with IncrementalCheckpoint is enabled.
- ```ForStIncrementalSnapshotStrategy``` skips throwing an exception if it encounters FORWARD sharingFilesStrategy  but there are no previous snapshots to reuse.
- ForStIncrementalSnapshotStrategyTest#testIncrementalCheckpointWithFirstBeingFull …
=> [FLINK-37335][state/forst] Handle the first full checkpoint for ForSt IncrementalSnapshotStrategy.

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/datatransfer/DataTransferStrategyBuilder.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/datatransfer/ForStStateDataTransfer.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/snapshot/ForStIncrementalSnapshotStrategy.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/snapshot/ForStNativeFullSnapshotStrategy.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/snapshot/ForStSnapshotStrategyBase.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/datatransfer/DataTransferStrategyTest.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/datatransfer/ForStStateDataTransferTest.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/snapshot/ForStIncrementalSnapshotStrategyTest.java
Fix the case when ForSt encounters the first full checkpoint with IncrementalCheckpoint is enabled.
- ```ForStIncrementalSnapshotStrategy``` skips throwing an exception if it encounters FORWARD sharingFilesStrategy  but there are no previous snapshots to reuse.
- ForStIncrementalSnapshotStrategyTest#testIncrementalCheckpointWithFirstBeingFull …
=> [BP-2.0][FLINK-37335][state/forst] Handle the first full checkpoint for ForSt IncrementalSnapshotStrategy. 

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java
[hotfix][runtime] Remove the unused SchedulerBase#transitionToScheduled method
[hotfix][runtime] Remove the unused SchedulerBase#transitionToScheduled method
- Does this pull request introduce a new feature? (yes …
=> [hotfix][runtime] Remove the unused SchedulerBase#transitionToScheduled method

docs/content.zh/docs/deployment/adaptive_batch.md, docs/content.zh/docs/deployment/elastic_scaling.md, docs/content/docs/deployment/adaptive_batch.md, docs/content/docs/deployment/elastic_scaling.md
[FLINK-37149][doc] Add documents for adaptive batch execution.
[FLINK-37149][doc] Add documents for adaptive batch execution.
The english page like this: …
=> [FLINK-37149][doc] Add documents for adaptive batch execution.

flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/canal/CanalJsonDeserializationSchema.java, flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/debezium/DebeziumJsonDeserializationSchema.java, flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/maxwell/MaxwellJsonDeserializationSchema.java, flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/ogg/OggJsonDeserializationSchema.java, flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/canal/CanalJsonSerDeSchemaTest.java, flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/debezium/DebeziumJsonSerDeSchemaTest.java, flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/maxwell/MaxwellJsonSerDerTest.java, flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/ogg/OggJsonSerDeSchemaTest.java
Enabling the ignore-parse-errors parameter does not skip exceptions caused by the format of the emitted data.
- Enabling the ignore-parse-errors parameter does not skip exceptions caused by the format of the emitted data.
*(example:)*
- *CanalJsonSerDeSchemaTest#testIgnoreParseErrors*
- *DebeziumJsonSerDeSchemaTest#testIgnoreParseErrors*
- *MaxwellJsonSerDerTest#testIgnoreParseErrors*
- *OggJsonSerDeSchemaTest#testIgnoreParseErrors* …
=> [FLINK-36549][formats] Fix using the ignore-parse-errors parameter in Debezium/Canal/Maxwell/Ogg JSON results in unexpected data loss

docs/content.zh/docs/deployment/adaptive_batch.md, docs/content.zh/docs/deployment/elastic_scaling.md, docs/content/docs/deployment/adaptive_batch.md, docs/content/docs/deployment/elastic_scaling.md
[BP-2.0][FLINK-37149][doc] Add documents for adaptive batch execution.
[BP-2.0][FLINK-37149][doc] Add documents for adaptive batch execution.
- If yes, how is the feature documented? (not applicable / **docs** / JavaDocs …
=> [BP-2.0][FLINK-37149][doc] Add documents for adaptive batch execution.

flink-filesystems/flink-oss-fs-hadoop/pom.xml, flink-filesystems/flink-oss-fs-hadoop/src/main/resources/META-INF/NOTICE
[FLINK-35724][oss] Bump OSS SDK to 3.17.4
[FLINK-35724][oss] Bump OSS SDK to 3.17.4 …
=> [FLINK-35724][oss] Bump OSS SDK to 3.17.4

flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherManager.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherManagerTest.java
This a revert for commit https://github.com/apache/flink/commit/fdf9b292b0db87b8639da1337d04c4ef570e5ca1
since after that commit there is no any successful master build
links to all failure CIs could be found at FLINK-37373
just revert
existing ci
=> Revert "[FLINK-36585][connector/common] SplitFetcherManager.close() should not chain runnables to the element queue future in a tight loop.

docs/data/sql_functions.yml, flink-python/pyflink/table/expressions.py, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/Expressions.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/ExprCodeGenerator.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/ExpressionReducer.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/JsonGenerateUtils.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/JsonObjectCallGen.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/JsonFunctionsITCase.java
We already added support for [JSON inside JSON_OBJECT](https://github.com/apache/flink/pull/26022) and now want to support it the same way for JSON_ARRAY, which is another building block for JSON in Flink. This will behave similar to what we did for JSON_OBJECT, see PR: https://github.com/apache/flink/pull/26022.
Example:
```
jsonArray(JsonOnNull.NULL, json('{"value": 42}'))
JSON_ARRAY(JSON('{"value": 42}'))
// [{"value":42}]
```
This enables declaring a SQL string that contains existing JSON as valid JSON an element of JSON_ARRAY.
- *Update code to enable calling json in json_array*
- *Update expression reducer to not reduce json calls* 
- *Add tests for json function in json array*
- *Update docs*
This change added tests for multiple uses cases of the function. …
=> [FLINK-37374][table] Add the built-in function JSON for JSON_ARRAY

flink-table/flink-sql-client/bin/sql-client.sh
*No need to add sql client jar. Because sql client is only used to compile the SQL and don't need to upload as job dependencies.*
=> [FLINK-37337][sql-client] No need to add sql-client jar as job dependencies

flink-python/dev/build-wheels.sh, flink-python/pyproject.toml
The `build_wheels.sh` in the [nightlies](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=66304&view=logs&j=d15e2b2e-10cd-5f59-7734-42d57dc5564d&t=4a86776f-e6e1-598a-f75a-c43d8b819662) were failing due to an error in the script (`deactivate` vs `source deactivate`). This PR fixes this error.
The wheel builds on Github Actions were also failing for a [different reason](https://github.com/apache/flink/actions/runs/13557536683/job/37894613821#step:6:490), as `pyproject.toml` defined the setuptools requirement as `setuptools>=75.8`, but the minimum version supported by this is Python 3.9, not 3.8. I've corrected this to `setuptools>=75.3`, which is valid for 3.8 and is also what we use in the [dev-requirements](https://github.com/apache/flink/blob/master/flink-python/dev/ …
=> [FLINK-37397][python] Fix deactivate error build-wheel.sh script

flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/legacy/metrics/MetricStore.java
[BP-2.0][FLINK-36172][runtime] Optimize transient metric cleanup
=> [BP-2.0][FLINK-36172][runtime] Optimize transient metric cleanup

docs/content.zh/docs/dev/datastream-v2/context_and_state_processing.md, docs/content/docs/dev/datastream-v2/context_and_state_processing.md
BP for https://github.com/apache/flink/pull/26233
=> [BP-2.0][FLINK-37148][docs] Update DataStream V2 documents for StateManager#getState and StateManager#getStateOptional methods

docs/content.zh/docs/dev/datastream/fault-tolerance/state_v2.md, docs/content.zh/docs/ops/state/disaggregated_state.md, docs/content/docs/dev/datastream/fault-tolerance/state_v2.md, docs/content/docs/ops/state/disaggregated_state.md
Some of the labels in docs are broken, this PR fixes that.
=> [hotfix][docs] Fix label format in docs for state v2

docs/content.zh/docs/dev/datastream/fault-tolerance/state_v2.md, docs/content.zh/docs/ops/state/disaggregated_state.md, docs/content/docs/dev/datastream/fault-tolerance/state_v2.md, docs/content/docs/ops/state/disaggregated_state.md
Backporting #20195 and #26255 to 2.0
=> [BP-2.0][docs] backports two fixes about documentation

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackendBuilder.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/datatransfer/CopyDataTransferStrategy.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/FileMappingManager.java
To fix the bug that ForSt does not inherit uploaded SST files from restored checkpoints.
- Register materializedSstFiles during restorations
- Skip incorrect file-reusing in ```DataTransferStrategy```
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes )
=> [FLINK-37367][state/forst] Make ForSt inherit uploaded SST files after restorations.

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackendBuilder.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/datatransfer/CopyDataTransferStrategy.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/FileMappingManager.java
To fix the bug that ForSt does not inherit uploaded SST files from restored checkpoints.
- Register materializedSstFiles during restorations
- Skip incorrect file-reusing in ```DataTransferStrategy```
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes )
=> [BP-2.0][FLINK-37367][state/forst] Make ForSt inherit uploaded SST files after restorations.

flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/AbstractAggregatingState.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractAggregatingStateTest.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBMapEntryIterRequest.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBMapKeyIterRequest.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBMapValueIterRequest.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStMapState.java
Backporting #26245 and #26246 to release-2.0
=> [BP-2.0][state/forst] Backport commits about forst state to 2.0

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateBackend.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/sync/ForStSyncKeyedStateBackendBuilder.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateBackendTest.java
Make incremental checkpoint configurable for ForSt State Backend.
- Add setter for  `incremental checkpoint` in `ForStSyncKeyedStateBackendBuilder`
- Add `ForStStateBackendTest#testConfiguration`
=> [FLINK-37434][state/forst] Make incremental checkpoint configurable in ForStSyncKeyedStateBackend

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateBackend.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/sync/ForStSyncKeyedStateBackendBuilder.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateBackendTest.java
Make incremental checkpoint configurable for ForSt State Backend.
- Add setter for ` incremental checkpoint`
=> [BP-2.0][FLINK-37434][state/forst] Make incremental checkpoint configurable in ForStSyncKeyedStateBackend

docs/content/docs/dev/table/sql/queries/joins.md
Fix a typo in Join doc
- Fix a typo in Join doc
=> [FLINK-37381] [doc] Fix typo in Join document

flink-runtime/src/main/java/org/apache/flink/streaming/api/transformations/OneInputTransformation.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/JobGraphGeneratorTestBase.java
Throw an exception when enableAsyncState() for synchronous operators.
- Override `OneInputTransformation#enableAsyncState()`
- `JobGraphGeneratorTestBase#testEnableAsyncStateForSyncOperatorThrowException`
=> [FLINK-37458][datastream] Forbid enableAsyncState() for synchronous operators

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/sync/ForStSyncKeyedStateBackend.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/AutoRescalingITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/EventTimeWindowCheckpointingITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/KeyedStateCheckpointingITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/RescaleCheckpointManuallyITCase.java
This reverts commit 6099697b501d58d08deb9154f77cb81e46117fd6.
Since ForSt makes existing ITCases not stable.
-  reverts commit 6099697b501d58d08deb9154f77cb81e46117fd6.
=> Revert "[FLINK-37158][tests] Introduce ForSt to existing ITCases

docs/content.zh/_index.md, docs/content.zh/release-notes/flink-2.0.md, docs/content/_index.md, docs/content/release-notes/flink-2.0.md
*Add release note for 2.0.0 release.*
=> [FLINK-37432][release] Add release note for release 2.0

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/agg/AggsHandlerCodeGenerator.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/codegen/agg/AggTestBase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/AggregateITCaseBase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/AggregateITCase.scala
This is a backport of [#26296](https://github.com/apache/flink/pull/26296) to release-2.0
=> [FLINK-30687][table] Fix wrong result of agg with fiter which references first input column

.github/workflows/docs.yml
Should be merged after 2.0.0 announced.
=> [FLINK-37491][release] Build 2.0 docs in GitHub Action and mark 2.0 as stable in docs

flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/SchemaResolutionTest.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/ResolvedSchema.java
backport of https://github.com/apache/flink/pull/26350
=> [FLINK-37557][bp 2.0] Fix ResolvedSchema#getPrimaryKeyIndexes

flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/SchemaResolutionTest.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/ResolvedSchema.java
backport of: https://github.com/apache/flink/pull/26350
=> [FLINK-37557][bp-1.20] Fix ResolvedSchema#getPrimaryKeyIndexes

pom.xml
Update japicmp configuration for 2.0.0.
=> [FLINK-37493][release] Update japicmp configuration for 2.0.0

flink-metrics/flink-metrics-otel/pom.xml, flink-metrics/flink-metrics-otel/src/main/resources/META-INF/NOTICE
=> [FLINK-37556][metrics][otel][BP-2.0] Add missing dependencies for OpenTelemetry

flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/concurrent/pekko/ActorSystemScheduledExecutorAdapter.java
Replacing manual comparison logic with Long.compare method for better readability and maintainability
=> [hotfix] Replacing manual comparison logic with Long#compare

flink-runtime/src/main/java/org/apache/flink/runtime/state/RegisteredStateMetaInfoBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/metainfo/StateMetaInfoSnapshot.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/RegisteredKeyAndUserKeyValueStateBackendMetaInfo.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/RegisteredKeyValueStateBackendMetaInfo.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/metainfo/StateMetaInfoSnapshotEnumConstantsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/RegisteredKeyValueStateBackendMetaInfoV2Test.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateMigrationTest.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateTestBase.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStTestUtils.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/snapshot/ForStIncrementalSnapshotStrategyTest.java
Add userKeySerializer in RegisteredKeyValueStateBackend V2
- If ForSt uses mapState, the userKeySerializer information will be saved during the process of snapshot.
- When ForSt is restoring the state, if the key of mapState changes, a StateMigrationException will be thrown. …
=> [FLINK-37569] Add userKeySerializer in RegisteredKeyValueStateBackend V2

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackendBuilder.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/snapshot/ForStNativeFullSnapshotStrategy.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/snapshot/ForStSnapshotStrategyBase.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/sync/ForStSyncKeyedStateBackend.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/AutoRescalingITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/EventTimeWindowCheckpointingITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/KeyedStateCheckpointingITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/RescaleCheckpointManuallyITCase.java
- Use ResourceGuard to make sure snapshot quit before ForSt disposal
- Enable ForSt in existing ITCases(Recover https://github.com/apache/flink/pull/26000).
- Acquire resources from `ResourceGuard` when `enableFileDeletions`, wait `ResourceGuard` before ForSt disposing.
- Remove some useless code from `ForStSnapshotStrategyBase`
- Recover https://github.com/apache/flink/pull/26000
- `EventTimeWindowCheckpointingITCase`
- `RescaleCheckpointManuallyITCase` …
=> [FLINK-37597] Use ResourceGuard to make sure snapshot quit before ForSt disposal

flink-end-to-end-tests/flink-end-to-end-tests-table-api/pom.xml, flink-end-to-end-tests/flink-end-to-end-tests-table-api/src/main/java/org/apache/flink/table/test/async/AsyncScalarFunctionExample.java, flink-end-to-end-tests/flink-end-to-end-tests-table-api/src/test/java/org/apache/flink/table/test/async/AsyncScalarFunctionTest.java, flink-end-to-end-tests/pom.xml, flink-table/flink-table-planner-loader/src/main/java/org/apache/flink/table/planner/loader/PlannerModule.java
BP https://github.com/apache/flink/pull/26390
=> [BP 1.20][FLINK-35117][Table SQL/Planner] Add commons-text to allowed classloader list

flink-end-to-end-tests/flink-end-to-end-tests-table-api/pom.xml, flink-end-to-end-tests/flink-end-to-end-tests-table-api/src/main/java/org/apache/flink/table/test/async/AsyncScalarFunctionExample.java, flink-end-to-end-tests/flink-end-to-end-tests-table-api/src/test/java/org/apache/flink/table/test/async/AsyncScalarFunctionTest.java, flink-end-to-end-tests/pom.xml, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/planner/loader/PlannerModule.java
BP https://github.com/apache/flink/pull/26390
=> [BP 2.0][FLINK-35117][Table SQL/Planner] Add commons-text to allowed classloader list

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackendBuilder.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/snapshot/ForStNativeFullSnapshotStrategy.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/snapshot/ForStSnapshotStrategyBase.java
Backport  https://github.com/apache/flink/pull/26392 to release-2.0
- Acquire resources from `ResourceGuard` when `enableFileDeletions`, wait `ResourceGuard` before ForSt disposing.
- Remove some useless code from `ForStSnapshotStrategyBase`
- Recover https://github.com/apache/flink/pull/26000 …
=> [BP-2.0][FLINK-37597][state/forst] Use ResourceGuard to make sure snapshot quit before ForSt disposal

flink-python/pyflink/table/types.py
Fixes wrong PyFlink documentation of the INT datatype size from 2 byte to 4 byte.
- Changes PyFlink documenation.
=> [hotfix] [docs] Fix size of PyFlink INT 

docs/content.zh/docs/ops/state/disaggregated_state.md, docs/content/docs/ops/state/disaggregated_state.md, docs/layouts/shortcodes/generated/forst_configuration.html, docs/layouts/shortcodes/generated/state_backend_forst_section.html, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackendBuilder.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStOptions.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateBackend.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/sync/ForStPriorityQueueConfig.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/sync/ForStSyncKeyedStateBackend.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/sync/ForStSyncKeyedStateBackendBuilder.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateBackendTest.java
Backport https://github.com/apache/flink/pull/26412 to release-2.0
This PR makes ForSt Sync mode support remote storage and provide `state.backend.forst.sync.enforce-local`.
- Add `state.backend.forst.sync.enforce-local` to `ForStOptions`.
- Set remote directory for `ForStSyncKeyedStateBackend` when configured.
- Remove some useless code in `ForStSyncKeyedStateBackend.java`
- ForStStateBackendTest#testCreateKeyedStateBackend …
=> [BP-2.0][FLINK-37620][state/forst] ForSt Sync mode support remote storage

flink-runtime/src/main/java/org/apache/flink/streaming/api/datastream/KeyedStream.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/DataStreamTest.java
This PR adds async state support for `process()` in Datastream API
- Make `KeyedStream#process()` use `AsyncKeyedProcessOperator` when async state is enabled.
- `DataStreamTest#testAsyncKeyedStreamKeyedProcessTranslation` …
=> [FLINK-37623][datastream] Async state support for process() in Datastream API

docs/setup_docs.sh
=> [1.20][FLINK-37664][docs] Integrate Kudu connector docs

docs/setup_docs.sh
=> [1.19][FLINK-37664][docs] Integrate Kudu connector docs

flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStAsyncAndSyncCompatibilityTest.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateMigrationTest.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStTestUtils.java
Add unit tests for state compatibility between ForStKeyeStateBackend and ForStSyncKeyeStateBackend
This PR is mainly designed to facilitate compatibility verification after the upcoming feature of switching between ForStSyncKeyeStateBackend and ForSyAsynchronous KeyeStateBackend.
Due to the current inability to switch between ForStSyncKeydStateBackend and ForSyAsynchronous KeydStateBackend, an Exception will be caught in UT first, and once it is supported later, the correctness of the State data will continue to be verified. …
=> [FLINK-37554] Add unit tests for state compatibility between ForStKeyeStateBackend and ForStSyncKeyeStateBackend

flink-runtime/src/main/java/org/apache/flink/streaming/api/datastream/KeyedStream.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/DataStreamTest.java
Backport https://github.com/apache/flink/pull/26419 to release-2.0
This PR adds async state support for `process()` in Datastream API
- Make `KeyedStream#process()` use `AsyncKeyedProcessOperator` when async state is enabled.
- `DataStreamTest#testAsyncKeyedStreamKeyedProcessTranslation` …
=> [BP-2.0][FLINK-37623][datastream] Async state support for process() in Datastream API

flink-core/src/main/java/org/apache/flink/util/TimeUtils.java, flink-core/src/test/java/org/apache/flink/util/TimeUtilsTest.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStConfigurableOptions.java, flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateBackendConfigTest.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/state/rocksdb/RocksDBConfigurableOptions.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/state/rocksdb/RocksDBResourceContainer.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/state/rocksdb/RocksDBStateBackendConfigTest.java
state.backend.rocksdb.compaction.filter.query-time-after-num-entries & state.backend.rocksdb.compaction.filter.periodic-compaction-time are added, but they cannot work due to ignorant of RocksDB CANDIDATE_CONFIGS.
- Add two configs into CANDIDATE_CONFIGS for RocksDB & ForSt State Backend
- TimeUtils#parseDuration supports to parse ISO-8601 duration format which will work for configurations configured by Duration#toString
- Added test "TimeUtilsTest#testParseDurationISO8601"
- Added test "RocksDBStateBackendConfigTest#testConfigurePeriodicCompactionTime" & "RocksDBStateBackendConfigTest#testConfigureQueryTimeAfterNumEntries"
- Added test "ForStStateBackendConfigTest#testConfigurePeriodicCompactionTime" & …
=> [FLINK-37668][state] Make compaction filter related config take effect for RocksDBStateBackend & ForStStateBackend

flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamOperatorStateHandler.java
[hotfix][runtime] Polish check hints and lines calling for StreamOperatorStateHandler#snapshotState.
[hotfix][runtime] Polish check hints and lines calling for StreamOperatorStateHandler#snapshotState. …
=> [hotfix][runtime] Polish check hints and lines calling for StreamOperatorStateHandler#snapshotState.

docs/content/docs/connectors/table/overview.md, docs/setup_docs.sh
=> [BP-1.19][FLINK-37197][docs] Update MongoDB docs for 2.0.0 release

docs/content/docs/connectors/table/overview.md, docs/setup_docs.sh
=> [BP-1.20][FLINK-37197][docs] Update MongoDB docs for 2.0.0 release

docs/setup_docs.sh
This PR updates jdbc connector v3.3 in docs.
=> [hotfix] Use jdbc connector v3.3 in docs

docs/setup_docs.sh
This PR updates jdbc connector version to v3.3 in docs.
=> [hotfix] Update jdbc connector version to v3.3 in docs

flink-core/src/main/java/org/apache/flink/api/java/typeutils/runtime/PojoSerializer.java
When the value to deserialize is an untagged subclass of the declared POJO type, Flink loads its acutal class every time using Class.forName, which is inefficient. We can cache the subclasses to speed up.
We tested on a production job, and the result is promising:
- Flame graph before the optim (Class.forName highlighted in green): 
- Flame graph after the optim (Subclass cache access highlighted in green): 
Add subclass cache for PojoSerializer.
This change is already covered by existing `PojoSubclassSerializerTest`. …
=> [FLINK-37680][serializer] Add subclass cache for PojoSerializer

flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/ClusterEntrypointUtils.java
[hotfix][runtime] Remove the redundant 'format' calling.
[hotfix][runtime] Remove the redundant 'format' calling.
- The usage is covered by 
```
public static void checkArgument(
boolean condition,
@Nullable String errorMessageTemplate,
@Nullable Object... errorMessageArgs)
```
- The S3 file …
=> [hotfix][runtime] Remove the redundant 'format' calling.

docs/content.zh/docs/dev/datastream/sinks.md, docs/content/docs/dev/datastream/sinks.md
This PR addresses trivial document issuses of Data Sinks of DataStream API V1 as below (both English and Chinese).
* Fix broken GitHub link syntax to StatefulSinkWriter
* Fix wrong image of SupportsPreCommitTopology
=> [hotfix][docs] Fix some issue in DataStream API (V1) / Data Sinks

flink-formats/flink-sql-parquet/src/main/resources/META-INF/NOTICE, flink-formats/pom.xml
=> [BP-2.0][FLINK-37760][format] Bump parquet from 1.15.1 to 1.15.2

flink-connectors/flink-connector-hive/src/main/resources/META-INF/NOTICE, flink-formats/flink-sql-parquet/src/main/resources/META-INF/NOTICE, flink-formats/pom.xml
=> [BP-1.19][FLINK-37760][format] Bump parquet from 1.15.1 to 1.15.2

flink-connectors/flink-connector-hive/src/main/resources/META-INF/NOTICE, flink-formats/flink-sql-parquet/src/main/resources/META-INF/NOTICE, flink-formats/pom.xml
=> [BP-1.20][FLINK-37760][format] Bump parquet from 1.15.1 to 1.15.2

docs/setup_docs.sh
*Update reference branch/version for es connector. V4.0 branch is the first release for flink 2.x.*
- *Update reference branch/version for es connector*
=> [FLINK-37767][doc] Update reference branch/version for es connector

flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStGeneralMultiGetOperationTest.java
[hotfix][test] Remove redundant keywords and lines for ForStGeneralMultiGetOperationTest.java
[hotfix][test] Remove redundant keywords and lines for ForStGeneralMultiGetOperationTest.java …
=> [hotfix][test] Remove redundant keywords and lines for ForStGeneralMultiGetOperationTest.java

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/IndexedInputGate.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGate.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/InputGateWithMetrics.java, flink-runtime/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java, flink-runtime/src/test/java/org/apache/flink/streaming/runtime/io/MockIndexedInputGate.java, flink-runtime/src/test/java/org/apache/flink/streaming/runtime/io/MockInputGate.java, flink-runtime/src/test/java/org/apache/flink/streaming/runtime/io/checkpointing/AlignedCheckpointsMassiveRandomTest.java, flink-tests/src/test/java/org/apache/flink/test/runtime/HybridShuffleITCase.java
https://issues.apache.org/jira/browse/FLINK-37783
=> [FLINK-37783] Auto-disable buffer debloating for tiered shuffle.

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/IndexedInputGate.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGate.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/InputGateWithMetrics.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/MockIndexedInputGate.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/MockInputGate.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/checkpointing/AlignedCheckpointsMassiveRandomTest.java, flink-tests/src/test/java/org/apache/flink/test/runtime/HybridShuffleITCase.java
BP for https://github.com/apache/flink/pull/26548
=> [BP-1.19][FLINK-37783] Auto-disable buffer debloating for tiered shuffle.

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/IndexedInputGate.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGate.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/InputGateWithMetrics.java, flink-runtime/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java, flink-runtime/src/test/java/org/apache/flink/streaming/runtime/io/MockIndexedInputGate.java, flink-runtime/src/test/java/org/apache/flink/streaming/runtime/io/MockInputGate.java, flink-runtime/src/test/java/org/apache/flink/streaming/runtime/io/checkpointing/AlignedCheckpointsMassiveRandomTest.java, flink-tests/src/test/java/org/apache/flink/test/runtime/HybridShuffleITCase.java
BP for https://github.com/apache/flink/pull/26548
=> [BP-2.0][FLINK-37783] Auto-disable buffer debloating for tiered shuffle.

flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
The current implementation of the ApplicationSubmissionContextReflector class has significant code duplication across the methods used for reflection, which makes it harder to maintain and extend. Each method for setting values in ApplicationSubmissionContext retrieves and invokes methods separately, leading to repetitive error handling and logging.
* Redundant try-catch blocks for method retrieval (getMethod()), each method has its own error handling and logging.
* The reflection logic for invoking methods is repeated in each setter method (setApplicationTags, setApplicationNodeLabel, etc.).
* Lack of centralized method invocation or retrieval, making future modifications cumbersome and prone to errors.
This refactor ensures that any future updates to method invocation logic are easier …
=> [FLINK-37718] Refactor ApplicationSubmissionContextReflector to centralize method retrieval and invocation.

docs/layouts/shortcodes/generated/all_jobmanager_section.html, docs/layouts/shortcodes/generated/expert_scheduling_section.html, docs/layouts/shortcodes/generated/job_manager_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/JobManagerOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/allocator/AllocatorUtil.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/allocator/DefaultSlotAssigner.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/allocator/SlotSharingSlotAllocator.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/allocator/StateLocalitySlotAssigner.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/allocator/DefaultSlotAssignerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/allocator/SlotSharingSlotAllocatorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/allocator/TestSlotInfo.java
[FLINK-33977][runtime] Adaptive scheduler may not minimize the number of TMs during downscaling
- Migrate the assertion lines to assertj APIs in StateLocalitySlotAssignerTest
- Correct the semantic of TestingSlot#getTaskManagerLocation
- Adaptive scheduler may not minimize the number of TMs during downscaling
StateLocalitySlotAssignerTest#testMinimalTaskExecutorsAfterRescale …
=> [FLINK-33977][runtime] Adaptive scheduler may not minimize the number of TMs during downscaling

flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/state/rocksdb/RocksDBKeyedStateBackendBuilder.java
Report s5cmd cancellation in a nicer way
Partially covered by tests. Logging changes are not tested.
=> [FLINK-37807][s3][rocksdb] Report s5cmd cancellation in a nicer way

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalMultiJoin.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/optimize/program/FlinkChangelogModeInferenceProgram.scala
Add StreamPhysicalMultiJoin to changelog inference program.
Updated FlinkChangelogModeInferenceProgram to support the StreamPhysicalMultiJoin. This involves three parts
- What kinds of changes will the multi join produce? -> Update ModifyKindSet
- How should the multi join handle UPDATEs? -> UpdateKind Optimization
- How should the multi join handle DELETEs? DeleteKind Optimization
This change only updates the inferance program but we don't use it yet. Tests will be added as soon as we can use it/test it. …
=> [FLINK-37945][table] Add StreamPhysicalMultiJoin to inference program

docs/content.zh/docs/dev/table/sql/explain.md, docs/content/docs/dev/table/sql/explain.md
fix SQL syntax of page: Application Development -> Table API & SQL -> SQL -> EXPLAIN
Document page link:
https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/sql/explain/
related files:
docs/content/docs/dev/table/sql/explain.md
docs/content.zh/docs/dev/table/sql/explain.md
It's obvious that SQL statements for java and python are wrong except scala code.
=> [FLINK-37946][doc] fix sql syntax of page Table API & SQL EXPLAIN

flink-python/pyflink/table/tests/jsonplan/testGetJsonPlan.out, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/ExecNode.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/ExecNodeBase.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/CompiledPlanSerdeUtil.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/ResolvedCatalogModelJsonDeserializer.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/ResolvedCatalogTableJsonDeserializer.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/ResolvedCatalogTableJsonSerializer.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/ResolvedSchemaJsonDeserializer.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/ResolvedSchemaJsonSerializer.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/TableDistributionJsonDeserializer.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/serde/ExecNodeVersionUpgradeSerdeTest.java, flink-table/flink-table-planner/src/test/resources/jsonplan/testGetJsonPlan.out, flink-table/flink-table-planner/src/test/resources/jsonplan/testSinkTableWithHints.out, flink-table/flink-table-planner/src/test/resources/jsonplan/testSourceTableWithHints.out, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/PythonCalcJsonPlanTest_jsonplan/testPythonCalc.out, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/PythonCalcJsonPlanTest_jsonplan/testPythonFunctionInWhereClause.out, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/PythonCorrelateJsonPlanTest_jsonplan/testJoinWithFilter.out, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/PythonCorrelateJsonPlanTest_jsonplan/testPythonTableFunction.out, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/PythonGroupAggregateJsonPlanTest_jsonplan/tesPythonAggCallsWithGroupBy.out, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/PythonGroupWindowAggregateJsonPlanTest_jsonplan/testEventTimeHopWindow.out, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/PythonGroupWindowAggregateJsonPlanTest_jsonplan/testEventTimeSessionWindow.out, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/PythonGroupWindowAggregateJsonPlanTest_jsonplan/testEventTimeTumbleWindow.out, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/PythonGroupWindowAggregateJsonPlanTest_jsonplan/testProcTimeHopWindow.out, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/PythonGroupWindowAggregateJsonPlanTest_jsonplan/testProcTimeSessionWindow.out, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/PythonGroupWindowAggregateJsonPlanTest_jsonplan/testProcTimeTumbleWindow.out, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/PythonOverAggregateJsonPlanTest_jsonplan/testProcTimeBoundedNonPartitionedRangeOver.out, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/PythonOverAggregateJsonPlanTest_jsonplan/testProcTimeBoundedPartitionedRangeOver.out, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/PythonOverAggregateJsonPlanTest_jsonplan/testProcTimeBoundedPartitionedRowsOverWithBuiltinProctime.out, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/PythonOverAggregateJsonPlanTest_jsonplan/testProcTimeUnboundedPartitionedRangeOver.out, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/PythonOverAggregateJsonPlanTest_jsonplan/testRowTimeBoundedPartitionedRowsOver.out
The PR makes it to not write empty lists to compiled plans
also added a test to ExecNodeVersionUpgradeSerdeTest
=> [FLINK-37957][table] Do not write empty lists to compiled plan

flink-runtime/src/test/java/org/apache/flink/streaming/util/KeyedTwoInputStreamOperatorTestHarness.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecDeltaJoin.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalDeltaJoin.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/optimize/StreamNonDeterministicUpdatePlanVisitor.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/physical/stream/DeltaJoinRewriteRule.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/DeltaJoinUtil.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/ExecNodeMetadataUtil.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/LookupJoinUtil.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestValuesRuntimeFunctions.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/DeltaJoinTest_jsonplan/testJsonPlanWithTableHints.out, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/DeltaJoinTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/DeltaJoinTest_jsonplan/testJsonPlanWithTableHints.out, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/DeltaJoinTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/DeltaJoinITCase.scala, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/CachingAsyncLookupFunction.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/keyselector/BinaryRowDataKeySelector.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/keyselector/EmptyRowDataKeySelector.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/keyselector/GenericRowDataKeySelector.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/keyselector/RowDataKeySelector.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/StreamingDeltaJoinOperatorFactory.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/TableAbstractCoUdfStreamOperator.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/deltajoin/AsyncDeltaJoinRunner.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/deltajoin/StreamingDeltaJoinOperator.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/lookup/RetryableAsyncLookupFunctionDelegator.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/lookup/keyordered/TableAsyncExecutionController.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/join/deltajoin/StreamingDeltaJoinOperatorTest.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/join/lookup/keyordered/TableAsyncExecutionControllerTest.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/utils/HandwrittenSelectorUtil.java
Implement delta join operator.
- *Implement delta join operator in Runtime and Planner.*
- *Add DeltaJoinITCase and StreamingDeltaJoinOperatorTest.*
Existent tests and new added tests can verify this change.
=> [FLINK-37898][table] Implement delta join operator

flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestValuesModelFactory.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/table/AsyncMLPredictITCase.java
Test fix
Test fix
Existing test pass
=> [FLINK-38019] fix ml predict test

.github/workflows/docs.yml
=> [FLINK-38010][release] Build doc for release-2.1 branch

flink-table/flink-table-common/src/main/java/org/apache/flink/table/api/Schema.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/api/SchemaTest.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/catalog/TestSchemaResolver.java
Fix Schema.Builder#fromResolvedSchema dropping comments
Fix Schema.Builder#fromResolvedSchema dropping comments
Added UT
- The S3 file system connector: (yes / **no /** don't know)
=> [FLINK-38041] Fix Schema.Builder#fromResolvedSchema dropping comments

.github/workflows/community-review.sh
Makes small improvements in the `community-review.sh` script.
- Standardize formatting and expression usage
- Add functionality to detect existing labels on PRs, so we do not reapply the same in every run.
(separated into 2 commit with the intent of rebase and merge)
=> [hotfix] Community review script improvements

docs/content.zh/docs/deployment/event_reporters.md, docs/content.zh/docs/deployment/trace_reporters.md, docs/content.zh/docs/ops/events.md, docs/content.zh/docs/ops/rest_api.md, docs/content.zh/docs/ops/traces.md, docs/content/docs/deployment/event_reporters.md, docs/content/docs/deployment/trace_reporters.md, docs/content/docs/ops/events.md, docs/content/docs/ops/rest_api.md, docs/content/docs/ops/traces.md, flink-core/src/main/java/org/apache/flink/configuration/TraceOptions.java, flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/events/Events.java, flink-metrics/flink-metrics-otel/src/main/java/org/apache/flink/events/otel/OpenTelemetryEventReporter.java, flink-metrics/flink-metrics-otel/src/test/java/org/apache/flink/events/otel/OpenTelemetryEventReporterITCase.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/DefaultCheckpointStatsTracker.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/JobStatusListener.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/failover/ExecutionFailureHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/JobFailureMetricReporter.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/metrics/AllSubTasksRunningOrFinishedStateTimeMetrics.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/metrics/DeploymentStateTimeMetrics.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/metrics/ExecutionStatusMetricsRegistrar.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/DefaultCheckpointStatsTrackerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/failover/ExecutionFailureHandlerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/utils/JobMasterBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/metrics/AllSubTasksRunningOrFinishedStateTimeMetricsTest.java
Report a bunch of system events and document events reporting system
Please check individual commit messages.
Every commit adds it's own set of tests to verify the change. …
=> [FLINK-37560][FLINK-37561][events] Report a bunch of system events and document events reporting system

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperator.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperatorTest.java
This is a backport pr to 2.1 branch
=> [BP-2.1][FLINK-38082][datastream] Avoid unexpected retries when user async function invokes completeExceptionally #26790 #26791

flink-models/flink-model-openai/pom.xml, flink-models/flink-model-openai/src/main/resources/META-INF/NOTICE
Cherry-pick fix https://github.com/apache/flink/commit/c187ebefe7da1d54a2bcef5ecc6f43e86314661e
=> [FLINK-38068][model] Build uber jar for open-ai model (#26770)

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/DataTypeFactoryImpl.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/api/DataTypes.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/DataTypeFactory.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/BaseMappingExtractor.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/DataTypeExtractor.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/DataTypeTemplate.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/TypeTransformations.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/transforms/ConversionClassTransformation.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/logical/StructuredType.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/utils/DataTypeUtils.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/utils/DataTypeUtilsTest.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/connectors/DynamicSinkUtils.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/DataTypeJsonSerializer.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/StructuredFunctionsITCase.java
Backport of #26784 for `release-2.1` branch.
N/A
N/A
=> [FLINK-38090][table] Align data type of inline structured types for TableResult.collect()

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/DataTypeFactoryImpl.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/logical/utils/LogicalTypeDuplicator.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/LogicalTypeDuplicatorTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/serde/LogicalTypeJsonSerdeTest.java
=> [FLINK-38103][table] Fix error for inline structured types in DataTypeFactory

flink-python/pyproject.toml, flink-python/setup.py
=> [FLINK-38121][python] Limit the version of pyarrow to <21.0.0

docs/layouts/shortcodes/generated/execution_config_configuration.html, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/config/ExecutionConfigOptions.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/AsyncScalarUtil.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/AsyncCalcTestPrograms.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/table/AsyncCalcITCase.java
Changes config name `table.exec.async-scalar.buffer-capacity` to `table.exec.async-scalar.max-concurrent-operations`.  Uses `withDeprecatedKeys` to support the old name.
- Renames config
- …
=> [FLINK-38140] Changes AsyncScalarFunction config from buffer-capacity to max-concurrent-operations

flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/StreamTaskTimerITCase.java
Move StreamTaskTimerITCase to new Source V2.
- Migrated InfiniteTestSource to DataGeneratorSource.
All tests in StreamTaskTimerITCase were adapted to use Source V2
=> [FLINK-32695] [Tests] Migrated StreamTaskTimerITCase to new Source V2.

flink-runtime/src/test/java/org/apache/flink/streaming/util/AbstractStreamOperatorTestHarness.java
To be used in https://github.com/apache/flink-benchmarks/pull/106
=> [FLINK-38199] Allow to specify output in AbstractStreamOperatorTestHarness

flink-tests/src/test/java/org/apache/flink/test/scheduling/ReactiveModeITCase.java
This PR migrates DummySource and FailOnParallelExecutionSource in ReactiveModeITCase from the deprecated legacy SourceFunction API to the modern FLIP-27 Source API.
- Removed DummySource class that implemented the deprecated SourceFunction interface
- Removed FailOnParallelExecutionSource class that implemented the deprecated RichParallelSourceFunction interface
This change is already covered by existing tests in ReactiveModeITCase:
- testScaleUpOnAdditionalTaskManager() - verifies reactive scaling up works with new source
- testScaleDownOnTaskManagerLoss() - verifies reactive scaling down works with new source
- testJsonPlanParallelismAfterRescale() - verifies job graph parallelism updates correctly
- testScaleLimitByMaxParallelism() - verifies maxParallelism=1 constraint is enforced
All …
=> [FLINK-32695] [Tests] ReactiveModeITCase-NewSource-Migration

flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/MultiJoinSemanticTests.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/MultiJoinTestPrograms.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/StreamingMultiJoinOperator.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/state/MultiJoinStateViews.java
Simplify and set row kind once to avoid manipulating row kind multiple times and changing state
- Set state once in operator before finishing processRecord
- Add tests
- Added semantic test
=> [FLINK-38219][table-runtime] Set row kind once before state manipulation

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecMultiJoin.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/JoinToMultiJoinRule.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/MultiJoinSemanticTests.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/MultiJoinTestPrograms.java
When analyzing join conditions to check if we can merge a join into a multi join we were only considering TableSource but we can also have other sources.
- Added Values and TableFunctionScan as sources
- Add semantic test with null join keys
- Add semantic test with null join keys
=> [FLINK-38220][table-planner] Add Values and TableFunctionScan as sources

flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/catalog/CatalogTableITCase.scala
Add ITCase to for testing the sensitive information has been hidden when creating source and sink table
- Added testSensitiveInfoMasking() to CatalogTableITCase 
The public API, i.e., is any changed class annotated with @Public(Evolving): no
The runtime per-record code paths (performance sensitive): no
Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
The S3 file system connector: no
=> [FLINK-38255][table][tests] Add ITCase to verify sensitive table option redaction

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/datatransfer/CopyDataTransferStrategy.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/datatransfer/DataTransferStrategyTest.java
```release-2.0``` backport of  ([#26700](https://github.com/apache/flink/pull/26700))
=> [BP-2.0][FLINK-37868][state/forst] Respect the `maxTransferBytes` when using path copying in ForSt

mvnw
(cherry picked from commit d95f0567c57f375719cba012df74669b921998d9)
=> [FLINK-37181][1.20][build] Fix MacOS sha256sum tool compile error

mvnw
Cherry picked from d95f0567c57f375719cba012df74669b921998d9
=> [FLINK-37181][2.0][build] Fix MacOS sha256sum tool compile error

flink-dist/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE, flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE, flink-table/flink-table-planner/pom.xml, pom.xml, tools/ci/google-mirror-settings.xml
Bump commons-lang3 to version 3.18.0 to mitigate [CVE-2025-48924](https://nvd.nist.gov/vuln/detail/CVE-2025-48924)
Dependency version update of commons-lang3 from 3.12.0 to 3.18.0
=> [FLINK-38193] Bump commons-lang3 to version 3.18.0

flink-dist/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE, flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE, pom.xml
Bump commons-lang3 to version 3.18.0 to mitigate [CVE-2025-48924](https://nvd.nist.gov/vuln/detail/CVE-2025-48924)
Basically cherry-picks https://github.com/apache/flink/pull/26869 into `release-2.0`
Dependency version update of commons-lang3 from 3.12.0 to 3.18.0
- …
=> [FLINK-38193] Cherry-pick Bump commons-lang3 to version 3.18.0 into release-2.0

docs/content.zh/docs/deployment/overview.md, docs/content/docs/deployment/overview.md
* Add Confluent to the list of vendors
This PR supersedes https://github.com/apache/flink/pull/26688
* Docs update …
=> [FLINK-37697][Documentation] Adding Confluent to vendors list

flink-python/dev/dev-requirements.txt, flink-python/pom.xml, flink-python/setup.py, flink-python/src/main/resources/META-INF/NOTICE
Since pemja 0.6 introduce some incompatible changes, we backport the bugfix from pemja 0.6 to pemja 0.5.5. This pull request will upgrade pemja to 0.5.5
- Upgrade pemja to 0.5.5
=> [FLINK-38332][python] Bump pemja to 0.5.5

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/RelTimeIndicatorConverter.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/MultiJoinSemanticTests.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/MultiJoinTestPrograms.java
There's an issue when materializing time attributes for MultiJoin: we were using the row type instead of the combined list of joined field types. The solution is simple: we need to init the materializer with a list of all fields from all inputs, not just the rows from each one.
- Call getFieldTypeList for each input
- Add semantic test
- Added semantic test …
=> [FLINK-38379][table] Adjust visitMultiJoin in RelTimeIndicatorConverter to use fields and not rows

flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/history/HistoryServer.java, flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/history/HistoryServerTest.java
- BP for FLINK-38344
- Fix the bug that The local files of the HistoryServer may risk never being deleted.
In the HistoryServer constructor, first clear all files in the historyserver.web.tmpdirdirectory before proceeding with the original initialization logic. This ensures that the local files marked for cleanup—based on HistoryServerArchiveFetcher#cachedArchivesPerRefreshDirectory—are free from leaks. …
=> [FLINK-38344][runtime-web] Fix the bug that The local files of the HistoryServer may risk never being deleted.
