flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/StateChangeFormat.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/metadata/MetadataV2V3SerializerBase.java
Avoid improper sanity check on read bytes on DataInputStream#read(byte[]). 
Java doc already said `An attempt is made to read as many as len bytes, but a smaller number may be read, possibly zero.`
Avoid improper sanity check on read bytes on DataInputStream#read(byte[]).
- If yes, …
=> [FLINK-25446][state] Avoid improper sanity check on read bytes on DataInputStream#read(byte[])

flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/catalog/PostgresCatalogTest.java
fix a method name typo in  postgres unit test.
- *change tesArrayDataTypes to testArrayDataTypes in PostgresCatalogTest class*
=> [hotfix][connector-jdbc] Fix a method name typo in postgres unit test.

flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogDelegateEmbeddedRocksDBStateBackendTest.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogDelegateFileStateBackendTest.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogDelegateHashMapTest.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogDelegateMemoryStateBackendTest.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogStateBackendTestUtils.java
ChangelogKeyedStateBackend#keyValueStatesByName would store wrapped state, such as TTL state or latency tracking state. It will throw exception on initMaterialization if wrapped:
~~~java
for (InternalKvState<K, ?, ?> changelogState : keyValueStatesByName.values()) {
checkState(changelogState instanceof ChangelogState);
((ChangelogState) changelogState).resetWritingMetaFlag();
}
~~~
- Correct the logic in changelog keyed state backend.
- Added test `testMaterializedRestoreWithWrappedState` …
=> [FLINK-25465][state] Correct the logic of materizating wrapped changelog state

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/FlinkRexUtil.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/RelExplainUtil.scala
*Fix Idea Scala plugin can not compile RexExplainUtil, see the description in FLINK-25474*
- *Use Multiline String in RexExplainUtil#overAggregationToString method* …
=> [FLINK-25474][table-planner] Fix Idea Scala plugin can not compile RexExplainUtil

flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/RecordWriterOutput.java
This is a simple hotfix that explicitly narrows down what exceptions can be wrapped to unchecked in RecordWriterOutput.
=> [FLINK-21186][network] Wrap IOException in UncheckedIOException in RecordWriterOutput

docs/content.zh/docs/ops/metrics.md, docs/content/docs/ops/metrics.md, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/BufferWritingResultPartition.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricNames.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/TimerGauge.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/TaskIOMetricGroup.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/ResultPartitionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/TimerGaugeTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/TaskIOMetricGroupTest.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
Currently back pressured/busy metrics tell the user whether task is blocked/busy and how much % of the time it is blocked/busy. But they do not tell how for how long single block event is lasting. It can be 1ms or 1h and back pressure/busy would be still reporting 100%.
In order to improve this, we could provide two new metrics:
`maxSoftBackPressureTime`
`maxHardBackPressureTime`
The max would be reset to 0 periodically or on every access to the metric (via metric reporter). Soft back pressure would be if task is back pressured in a non blocking fashion (StreamTask detected in availability of the output). Hard back pressure would measure the time task is actually blocked.
In order to calculate those metrics I'm proposing to split the already existing `backPressuredTimeMsPerSecond` into …
=> [FLINK-25414][metrics] Provide metrics to measure how long task has been blocked

flink-connectors/flink-connector-pulsar/pom.xml, flink-formats/flink-parquet/pom.xml
This is a proposal to fix the Flink build on Apple Silicon.
I'll look into the CI failure once I've time (I'm happy for suggestions ;) ).
@AHeise What do you think about the `flink-parquet` dependency changes?
=> [FLINK-23230] Fix protoc dependency for Apple Silicon / m1 support

docs/content.zh/docs/dev/datastream/event-time/generating_watermarks.md, docs/content/docs/dev/datastream/event-time/generating_watermarks.md
This PR supersedes https://github.com/apache/flink/pull/18175 and https://github.com/apache/flink/pull/18200 provided by @wangzhuoz
Remove duplicate dot in docs/content.zh/docs/dev/datastream/event-time/generating_watermarks.md and docs/content/docs/dev/datastream/event-time/generating_watermarks.md
* Updated documentation to remove duplicate and unnecessary dot
- The …
=> [hotfix][docs] Remove duplicate dot in generating_watermarks.md

flink-walkthroughs/flink-walkthrough-datastream-scala/src/main/resources/archetype-resources/pom.xml
[hotfix][flink-walkthrough] Fix typo in name for archetype-resources/pom.xml
=> [hotfix][flink-walkthrough] Fix typo in name for archetype-resources/pom.xml

docs/content.zh/docs/dev/datastream/project-configuration.md, docs/content/docs/dev/datastream/project-configuration.md, flink-dist/src/main/resources/META-INF/NOTICE, pom.xml
* Update slf4j-api from 1.7.15 to 1.7.32
* Updated POM, license file and other references to outdated version
=> [FLINK-25460][core] Update slf4j-api dependency to 1.7.32

flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogWriter.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/StateChangelogWriter.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/inmemory/InMemoryStateChangelogWriter.java, flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogStateBackendTestUtils.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/StateChangeLoggerTestBase.java
Truncate state changelog upon backend materialization.
I.e. add missing call `stateChangelogWriter.truncate` from `ChangelogKeyedStateBackend.updateChangelogSnapshotState`.
Add assertion to `ChangelogStateBackendTestUtils.materialize` used in materialization tests.
=> [FLINK-25261][state] Truncate changelog upon materialization

flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/JdbcOutputFormat.java
DEFAULT_FLUSH_MAX_SIZE and DEFAULT_FLUSH_INTERVAL_MILLS is useless in JdbcBatchingOutputFormat class. 
- *Delete DEFAULT_FLUSH_MAX_SIZE and DEFAULT_FLUSH_INTERVAL_MILLS is useless in JdbcBatchingOutputFormat class.* …
=> [FLINK-25239][connector/jdbc] Delete useless variables

flink-clients/src/test/java/org/apache/flink/client/program/ClientTest.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestEnvironmentImpl.java, flink-core/src/main/java/org/apache/flink/util/FileLock.java, flink-core/src/main/java/org/apache/flink/util/NetUtils.java, flink-python/src/main/java/org/apache/flink/client/python/PythonEnvUtils.java, flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/network/ClientTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyClientServerSslTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyConnectionManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyPartitionRequestClientTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyTestUtil.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/PartitionRequestClientFactoryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorSubmissionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorTest.java, flink-tests/src/test/java/org/apache/flink/test/runtime/IPv6HostnamesITCase.java
…with "Address already in use"
Fixed the issue that FlinkKafkaProducerMigrationTest fails with "Address already in use".
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestEnvironmentImpl.java
=> [FLINK-22821][core] Stabilize NetUtils#getAvailablePort in order to avoid wrongly allocating any used ports

docs/content.zh/docs/dev/python/datastream/intro_to_datastream_api.md, docs/content/docs/dev/python/datastream/intro_to_datastream_api.md
This PR fixes the problem with the Python DataStream API documentation page variable "t_env" being written as "table". On this page: https://nightlies.apache.org/flink/flink-docs-master/docs/dev/python/datastream/intro_to_datastream_api/ …
=> [hotfix][docs] Fix incorrect Python tableEnvironment attribute reference

docs/content.zh/docs/connectors/table/hive/hive_read_write.md, docs/content/docs/connectors/table/hive/hive_read_write.md, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/ContinuousHiveSplitEnumerator.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveLookupTableSource.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveOptions.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveSource.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveSourceBuilder.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveSourceFileEnumerator.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveTablePartitionSplits.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveTableSource.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/MRSplitsGetter.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/read/HiveInputFormatPartitionReader.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/read/HiveTableInputFormat.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/PartitionMonitorTest.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/read/HiveInputFormatPartitionReaderITCase.java
*If there are many hive partitions, creating splits will take much time, for example, up to ten minutes. This mr speeds up the process by multi threads for different partitions.*
- *Add class MRSplitsGetter to create splits by multi thread.*
- *Add class HiveTablePartitionSplits to wrap hive partition and the corresponding inputSplits.*
- *Transfer flinkConf to init MRSplitsGetter's thread num.*
- *Adapt the related calls.*
This change is already covered by existing tests, such as HiveTableSourceITCase. …
=> [FLINK-25010][Connectors/Hive] Speed up hive's createMRSplits by multi thread

docs/content.zh/docs/connectors/table/filesystem.md, docs/content/docs/connectors/table/filesystem.md, flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/DefaultPartTimeExtractor.java, flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/FileSystemConnectorOptions.java, flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/FileSystemTableFactory.java, flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/PartitionTimeExtractor.java, flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/stream/PartitionTimeCommitPredicate.java, flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/table/stream/StreamingFileWriterTest.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveTableSource.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/read/HivePartitionFetcherContextBase.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/FsStreamingSinkITCaseBase.scala
Now, only supports yyyy-mm-dd hh:mm:ss, we can add a new time-extractor kind to support yyyyMMdd in a single partition field
https://issues.apache.org/jira/browse/FLINK-24758
1. add partition.time-extractor.formatter-pattern to allow user to speify DateTimeFormatter
```
CREATE TABLE MyUserTable (
column_name1 INT,
column_name2 STRING,
...
part_name1 INT,
part_name2 STRING
) PARTITIONED BY (part_name1, part_name2) WITH (
'connector' = 'filesystem',           -- required: specify the connector
...
'partition.time-extractor.formatter-pattern' = 'yyyyMMdd',
...
)
```
org.apache.flink.table.planner.runtime.stream.FsStreamingSinkITCaseBase#testBasicDate
- The public API, …
=> [FLINK-24758][Connectors / FileSystem]  filesystem sink: add partitiontime-extractor.formatter-pattern to allow user to speify DateTimeFormatter

flink-connectors/flink-connector-pulsar/pom.xml, flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/PulsarSourceOrderedE2ECase.java, flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/PulsarSourceUnorderedE2ECase.java
Add resource file to the test jar to avoid find not found exception and re-enable pulsar e2e tests due to FLINK-25210
- enable Pulsar e2e tests
- add `containers/txnStandalone.conf` in the packages jar files. …
=> [FLINK-25210][pulsar][e2e][tests] add resource file to test jar

azure-pipelines.yml, docs/content.zh/docs/deployment/filesystems/gcs.md, docs/content.zh/docs/deployment/resource-providers/yarn.md, docs/content.zh/docs/dev/dataset/hadoop_compatibility.md, docs/content/docs/connectors/dataset/formats/hadoop.md, docs/content/docs/connectors/datastream/formats/hadoop.md, docs/content/docs/deployment/filesystems/gcs.md, docs/content/docs/deployment/resource-providers/yarn.md, docs/content/docs/dev/dataset/hadoop_map_reduce.md, flink-end-to-end-tests/test-scripts/common_yarn_docker.sh, flink-end-to-end-tests/test-scripts/docker-hadoop-secure-cluster/Dockerfile, flink-end-to-end-tests/test-scripts/docker-hadoop-secure-cluster/README.md, flink-jepsen/src/jepsen/flink/flink.clj, flink-yarn-tests/README.md, pom.xml, tools/azure-pipelines/build-apache-repo.yml
Now the Hadoop version of Flink is 2.4.1, but mostly the flink runtime env classpath has higher Hadoop version. It means when we want to use some feature in the higher version Hadoop, we need to use reflection which is so hard to maintain.
=> [FLINK-25224][filesystem] Bump Hadoop version to 2.8.4

docs/content.zh/docs/connectors/table/elasticsearch.md, docs/content/docs/connectors/table/elasticsearch.md, flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/table/ElasticsearchConfiguration.java, flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/table/ElasticsearchDynamicSink.java, flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/table/ElasticsearchDynamicSinkFactoryBase.java, flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/connector/elasticsearch/ElasticsearchUtil.java, flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/connector/elasticsearch/table/ElasticsearchDynamicSinkBaseITCase.java, flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/connector/elasticsearch/table/ElasticsearchDynamicSinkFactoryBaseTest.java
add sink parallelism option in Elasticsearch connector.
- Inspired by JDBC and Kafka connector, add a 'sink.parallelism' option, and using SinkProvider#of(sink, sinkParallelism) to set parallelism.
- *Added test that validates that parallelism option is valid* …
=> [FLINK-25141][connector/elasticsearch][docs] Add sink parallelism option

flink-python/src/main/java/org/apache/flink/table/executor/python/ChainingOptimizingExecutor.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/delegation/Executor.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/utils/ExecutorMock.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/factories/TestManagedTableFactory.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/delegation/DefaultExecutor.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/delegation/PlannerBase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/TableSinkTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/TableSinkTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/TableTestBase.scala
*In the past, many users encountered the problem that the sink did not output because they did not open the checkpoint. For the managed table: The planner will throw an exception if the checkpoint is not turned on. (Later we can add public connector interface, including Filesystem, Hive, Iceberg, Hudi need it). `PlannerBase` adds the check whether the managed table sink is enabled to checkpointing.*
- *`PlannerBase` adds the `checkManagedTableCheckpointing` to check whether the managed table sink is enabled to checkpointing. If the managed table sink disables checkpointing, this could throw the `TableException`.*
- The …
=> [FLINK-25178][table] Throw exception when managed table sink needs checkpointing

flink-quickstart/flink-quickstart-java/src/main/resources/archetype-resources/src/main/java/DataStreamJob.java, flink-quickstart/flink-quickstart-scala/src/main/resources/archetype-resources/src/main/scala/DataStreamJob.scala
The PR fixes 2 misprints in 
_flink-quickstart/flink-quickstart-java/src/main/resources/archetype-resources/src/main/java/DataStreamJob.java_
and
_flink-quickstart/flink-quickstart-scala/src/main/resources/archetype-resources/src/main/scala/DataStreamJob.scala_
`begining` => `beginning`
`fromSequece` => `fromSequence`  
(The existing method is called `fromSequence` https://github.com/apache/flink/blob/d08a1d0f4035485283f10611113d4d0fc0a8aaca/flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java#L1095)
- The …
=> [hotfix][quickstarts] Fix misprints in DataStreamJob.java and DataStreamJob.scala

flink-core/src/main/java/org/apache/flink/api/common/state/CheckpointListener.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/testutils/BinaryOperatorTestBase.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/testutils/DriverTestBase.java, flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/StateChangeLogger.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/DataStreamUtils.java, flink-streaming-scala/src/main/scala/org/apache/flink/streaming/api/scala/AllWindowedStream.scala, flink-streaming-scala/src/main/scala/org/apache/flink/streaming/api/scala/WindowedStream.scala
*I found some spelling errors,  Some 'note that' words was written as 'not that' and som 'now that' words was written as 'no that' .  If not corrected, it may cause misunderstandings*
- b3736ea54f18c499c3c4d8bbf24bbce17e02adbc  
Just a hotfix , no need to add test. 
=> [hotfix][doc] fix typo of 'note that' and 'now that' 

docs/content.zh/docs/dev/table/types.md, docs/content/docs/dev/table/types.md
Trivial misprint fix `Data Type Extraction` of 
_docs/content.zh/docs/dev/table/types.md_
and
_docs/content/docs/dev/table/types.md_
`INVERVAL` => `INTERVAL`
=> [hotfix][docs] Fix type name for INTERVAL in Data Type Extraction section of types.md

flink-connectors/flink-connector-jdbc/pom.xml
* Update com.h2database:h2 to latest version, 2.0.206
* Updated POM with new version number
=> [FLINK-25576][Connectors][JDBC] Upgrade com.h2database:h2 to 2.0.206

docs/content.zh/docs/connectors/table/formats/avro-confluent.md, docs/content/docs/connectors/table/formats/avro-confluent.md, docs/data/sql_connectors.yml, docs/layouts/shortcodes/sql_download_table.html
This PR fixes missing dependency instructions for the Table API connector doc pages on "Confluent Avro Format" and "Avro Format".
- extend Hugo shortcode for `sql_download_table` to support multiple maven artifacts for a single connector
- "Confluent Avro Format" page:
- add the dependency to `flink-avro`
- add a note on having Confluent's maven repository in your build files as well
- "Avro Format":
- fix maven dependency to point to `flink-avro` and not `flink-sql-avro` which is shaded and should only be used by the SQL client
I built and verified at the rendered docs site locally …
=> [FLINK-25362][docs] fix incorrect dependencies in Table Confluent/Avro docs

flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestEnvironmentImpl.java
This pull request disables log deletion in KafkaTestEnvironmentImpl to prevent records from being deleted during test run
- Set broker property "log.retention.ms" to -1 in KafkaTestEnvironmentImpl
This change is already covered by existing Kafka connector tests. …
=> [FLINK-25280][connector/kafka] Disable log deletion in KafkaTestEnvironmentImpl to prevent records from being deleted during test run

docs/content.zh/docs/ops/metrics.md, docs/content/docs/ops/metrics.md, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricNames.java, flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/active/ActiveResourceManager.java
The number of TaskManagers whose status is Pending should be reported. In the case of insufficient resources, let the external sense as soon as possible.
- Add indicator name numPendingTaskManagers
- Report the number of unregistered taskManagers after the worker registration is successful
=>  [FLINK-25190] Actively report the number of TaskManagers that have not yet been registered with JobManager

docs/content.zh/docs/deployment/cli.md, docs/content/docs/deployment/cli.md
There is a typo in following docs
https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/cli/#submitting-pyflink-jobs
- *change 'entry' to 'entry point' in the description of '--py' option*
None
=> [hotfix][python][docs] Fix typo in a description of submitting option.

docs/content.zh/docs/ops/state/checkpointing_under_backpressure.md
Translate "Checkpointing under backpressure" page into Chinese
The page url is "https://ci.apache.org/projects/flink/flink-docs-master/zh/docs/ops/state/checkpointing_under_backpressure/".
Translate "flink/docs/content.zh/docs/ops/state/checkpointing_under_backpressure.md" …
=> [FLINK-24694][docs-zh] Translate "Checkpointing under backpressure" page into Chinese

flink-connectors/flink-connector-aws-base/src/main/java/org/apache/flink/connector/aws/util/AWSGeneralUtil.java, flink-connectors/flink-connector-aws-base/src/test/java/org/apache/flink/connector/aws/util/AWSGeneralUtilTest.java, flink-end-to-end-tests/flink-glue-schema-registry-avro-test/src/test/java/org/apache/flink/glue/schema/registry/test/GSRKinesisPubsubClient.java, flink-end-to-end-tests/flink-glue-schema-registry-avro-test/src/test/java/org/apache/flink/glue/schema/registry/test/GlueSchemaRegistryAvroKinesisITCase.java, flink-end-to-end-tests/flink-glue-schema-registry-json-test/pom.xml, flink-end-to-end-tests/flink-glue-schema-registry-json-test/src/test/java/org/apache/flink/glue/schema/registry/test/json/GSRKinesisPubsubClient.java, flink-end-to-end-tests/flink-glue-schema-registry-json-test/src/test/java/org/apache/flink/glue/schema/registry/test/json/GlueSchemaRegistryJsonKinesisITCase.java, flink-formats/flink-avro-glue-schema-registry/pom.xml, flink-formats/flink-avro-glue-schema-registry/src/main/java/org/apache/flink/formats/avro/glue/schema/registry/GlueSchemaRegistryInputStreamDeserializer.java, flink-formats/flink-avro-glue-schema-registry/src/main/java/org/apache/flink/formats/avro/glue/schema/registry/GlueSchemaRegistryOutputStreamSerializer.java, flink-formats/flink-avro-glue-schema-registry/src/test/java/org/apache/flink/formats/avro/glue/schema/registry/GlueSchemaRegistryAvroDeserializationSchemaTest.java, flink-formats/flink-avro-glue-schema-registry/src/test/java/org/apache/flink/formats/avro/glue/schema/registry/GlueSchemaRegistryAvroSchemaCoderTest.java, flink-formats/flink-avro-glue-schema-registry/src/test/java/org/apache/flink/formats/avro/glue/schema/registry/GlueSchemaRegistryAvroSerializationSchemaTest.java, flink-formats/flink-avro-glue-schema-registry/src/test/java/org/apache/flink/formats/avro/glue/schema/registry/GlueSchemaRegistryInputStreamDeserializerTest.java, flink-formats/flink-avro-glue-schema-registry/src/test/java/org/apache/flink/formats/avro/glue/schema/registry/GlueSchemaRegistryOutputStreamSerializerTest.java, flink-formats/flink-json-glue-schema-registry/pom.xml, flink-formats/flink-json-glue-schema-registry/src/main/java/org/apache/flink/formats/json/glue/schema/registry/GlueSchemaRegistryJsonSchemaCoder.java, flink-formats/flink-json-glue-schema-registry/src/test/java/org/apache/flink/formats/json/glue/schema/registry/GlueSchemaRegistryJsonDeserializationSchemaTest.java, flink-formats/flink-json-glue-schema-registry/src/test/java/org/apache/flink/formats/json/glue/schema/registry/GlueSchemaRegistryJsonSchemaCoderTest.java, flink-formats/flink-json-glue-schema-registry/src/test/java/org/apache/flink/formats/json/glue/schema/registry/GlueSchemaRegistryJsonSerializationSchemaTest.java
- Fixing Glue Schema Registry integration tests for Azure CI build
- Glue Schema Registry avro and json format construct AWS Credential Provider using property map
- Updated e2e tests to pass AWS keys into client correctly
- Added new unit tests to verify custom AWS Credential Provider is used
- Manually ran integration tests locally
- Dependencies (does it add or upgrade a dependency): yes (guava update) …
=> [FLINK-25107][formats/gsr] Adding support to define AWS Credential Provider from property map

flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/main/java/org/apache/flink/tests/util/kafka/KafkaContainerClient.java, flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SQLClientSchemaRegistryITCase.java
This pull request fixes the broken `SQLClientSchemaRegistryITCase` which possibly read records from a topic that is not set up on broker.
- Wait until the consuming topic is ready before polling records in KafkaContainerClient#readMessages
This change is already covered by existing `SQLClientSchemaRegistryITCase`. …
=> [FLINK-25209][tests] Wait until the consuming topic is ready before polling records in KafkaContainerClient#readMessages

docs/content.zh/docs/connectors/table/formats/parquet.md, docs/content/docs/connectors/table/formats/parquet.md
Add document for array,map,row types support for parquet row writer.
=> [FLINK-25179] Add document for composite types support for parquet

flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestEnvironmentImpl.java
Unchanged backport of #18311 on release-1.14
=> [BP-1.14][FLINK-25280][connector/kafka] Disable log deletion in KafkaTestEnvironmentImpl to prevent records from being deleted during test run

flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestEnvironmentImpl.java
Unchanged backport of #18311 on release-1.13
=> [BP-1.13][FLINK-25280][connector/kafka] Disable log deletion in KafkaTestEnvironmentImpl to prevent records from being deleted during test run

flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaCommitterTest.java
testRetryComittableORetriableError is taking over an hour on CI runs. We want to speed up the test.
The issue is that `FlinkInternalKafkaProducer` has a closing timeout of 1 hour if it was not in a transaction. This PR forces the producer to shutdown immediately to prevent idleness.
- force immediate closing of the producer
* CI run for test_ci_build kafka_gelly should be significantly faster. Compare with previous runs (> 1hr) …
=> [FLINK-25531][connectors/kafka] Force immediate shutdown of FlinkInternalKafkaProducer to speed up testRetryComittableOnRetriableError

flink-core/src/main/java/org/apache/flink/core/memory/MemorySegmentProvider.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPool.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/NetworkBufferPool.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/BufferManager.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/BufferPoolFactoryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPoolTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/NetworkBufferPoolTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/InputChannelTestUtils.java
This PR tries to fix the issues caused by FLINK-24035. More specifically, there are two issues, the first one is the deadlock caused by acquiring the 'factoryLock' in NetworkBufferPool and the other is the incorrect decreasing of the required segments of NetworkBufferPool. Both issues occur during exception handling of requesting segments. Actually, when reserving memory segments for LocalBufferPool, there is no need to modify the value of required segments. As a result, there is no need to acquire the 'factoryLock'. This PR fixes the issues by removing the required segments decreasing logic together with the 'factoryLock' acquiring during exception handling of requesting segments in NetworkBufferPool.
- Avoid locking 'factoryLock' for LocalBufferPool#reserveSegments method.
This change …
=> [FLINK-25407][network] Fix the issues caused by FLINK-24035

flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/pom.xml, flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SQLClientKafkaITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SQLClientSchemaRegistryITCase.java, flink-end-to-end-tests/test-scripts/test_confluent_schema_registry.sh, flink-end-to-end-tests/test-scripts/test_pyflink.sh, flink-end-to-end-tests/test-scripts/test_sql_client.sh, flink-formats/flink-avro-confluent-registry/pom.xml, flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE, flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/util/DockerImageVersions.java
The Flink codebases uses Kafka Client and Confluent Platform in multiple places:
- AVRO Confluent Schema Registry
- Flink end-to-end tests (Bash e2e tests)
- Flink end-to-end tests common (Java e2e tests)
- SQL AVRO Confluent Schema Registry
- Flink Test Utils
- Flink Tests
The used versions are currently not in sync, which could result in unexpected results. 
* Updated `flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/pom.xml` from Confluent Platform 5.5.2 to 6.2.2 and Kafka Client from 2.4.1 to 2.8.1
* Updated `flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SQLClientKafkaITCase.java` and `flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/StreamingKafkaITCase.java …
=> [FLINK-25504][Kafka] Upgrade Kafka Client to 2.8.1 and Confluent Platform to 6.2.2

flink-connectors/flink-connector-hbase-1.4/pom.xml, flink-connectors/flink-connector-hbase-2.2/pom.xml, flink-connectors/flink-connector-kinesis/pom.xml, flink-end-to-end-tests/flink-glue-schema-registry-avro-test/pom.xml, flink-end-to-end-tests/flink-glue-schema-registry-json-test/pom.xml, flink-end-to-end-tests/flink-streaming-kinesis-test/pom.xml
All modules now use the surefire version defined in the root pom.
=> [FLINK-25613][build] Sync surefire versions

flink-annotations/src/main/java/org/apache/flink/FlinkVersion.java
The upcoming version to be released need to exist already in master so that
when the new release branch is created from master the version of the release
is already there.
Follows: #18340
=> [hotfix][flink-annotations] Add v1.15 as the next Flink version to master

flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/legacy/utils/ArchivedExecutionConfigBuilder.java
*The parameter of the ArchivedExecutionConfigBuilder.setMaxParallelism() is error*
*fix the error parameter* …
=> [hotfix][tests] Fix the error parameter

flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/ChangelogStateHandleStreamImpl.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/snapshot/RocksIncrementalSnapshotStrategy.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/PartiallyFinishedSourcesITCase.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/TestJobExecutor.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/command/TestCommand.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/command/TestCommandDispatcherImpl.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/graph/OneInputTestStreamOperator.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/graph/OneInputTestStreamOperatorFactory.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/graph/TestEventSource.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/graph/TestJobBuilders.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/IncrementalStateReuseAfterFailureITCase.java
After FLINK-25395, shared (incremental) state can be re-used
by state backends regardless of the confirmation by JM.
JM will only discard it on checkpoint subsumption or job termination.
However, state can also be discarded by TM in case of failures:
- AsyncCheckpointRunnable.cleanup
- StreamOperatorStateHandler.snapshotState
- SubtaskCheckpointCoordinatorImpl.cleanup
Those cleanups might render previous checkpoints invalid.
This change fixes it by:
1. Reverting changes to RocksDB incremental snapshotting (i.e. re-upload state unless it was confirmed by JM)
1.  Removing discard calls from the changelog state handle (this may leave more orphaned state artefacts on DFS; this issue will be addressed later)
- added `IncrementalStateReuseAfterFailureITCase` that reproduces the original …
=> [FLINK-25395][state] Fix TM error handling when uploading shared state

flink-connectors/flink-connector-kinesis/pom.xml, flink-connectors/flink-connector-kinesis/src/main/resources/META-INF/NOTICE
* Update Amazon Kinesis Client dependency
* Update NOTICE file
=> [FLINK-25657][Kinesis] Upgrade com.amazonaws:amazon-kinesis-client dependency from 1.14.1 to 1.14.7

flink-connectors/flink-connector-cassandra/pom.xml, flink-connectors/flink-connector-kafka/pom.xml, flink-python/pom.xml, pom.xml
Backport of #18343 to `release-1.13`.
=> [BP-1.13][FLINK-25633] Set locale to en-US to avoid ambiguous decimal formattings

flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/KafkaDynamicSource.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaDynamicTableFactoryTest.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableITCase.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableTestUtils.java, flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/core/testutils/FlinkAssertions.java
This PR provides the way to change the 'auto.offset.reset' for kafka table source when use 'group-offsets' startup mode .
When 'auto.offset.reset' is set, the 'group-offsets' startup mode will use the provided auto offset reset strategy, or else 'none' reset strategy in order to be consistent with the DataStream API.
- When 'auto.offset.reset' is set, the 'group-offsets' startup mode will use the provided auto offset reset strategy, or else 'none' reset strategy as default
- Added test that validates that the 'auto.offset.reset' is set for kafka consumers
- …
=> [FLINK-24697][flink-connectors-kafka] add auto.offset.reset configuration for group-offsets startup mode

docs/layouts/shortcodes/generated/kubernetes_config_configuration.html, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/configuration/KubernetesConfigOptions.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/InitJobManagerDecorator.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/InitTaskManagerDecorator.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesJobManagerParameters.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesTaskManagerParameters.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/KubernetesUtils.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/entrypoint/KubernetesWorkerResourceSpecFactoryTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/KubernetesJobManagerTestBase.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/KubernetesTaskManagerTestBase.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/InitJobManagerDecoratorTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/InitTaskManagerDecoratorTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesJobManagerParametersTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesTaskManagerParametersTest.java
The purpose of this PR is to allow the user to configure the Taskmanager's and Jobmanager's CPU and Memory limits when deploying Flink using the Kubernetes Resource provider.
The "kubernetes.jobmanager.cpu.limit-factor" will calculate the CPU limit of the Jobmanager using the following formula: jobmanager cpu * limit-factor. The "kubernetes.taskmanager.cpu.limit-factor" will do the same for the Taskmanager.
The same logic applies to "kubernetes.taskmanager.memory.limit-factor" and "kubernetes.jobmanager.memory.limit-factor" 
- Added the "kubernetes.jobmanager.cpu.limit-factor" config option to configure the Jobmanager's limit CPU when using the Kubernetes resource provider.
- Added the "kubernetes.taskmanager.cpu.limit-factor" config option to configure the Taskmanager's limit CPU when …
=> [FLINK-15648][flink-kubernetes] Support to configure limit for CPU & memory

docs/layouts/shortcodes/generated/kubernetes_config_configuration.html, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/configuration/KubernetesConfigOptions.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/InitJobManagerDecorator.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/InitTaskManagerDecorator.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/AbstractKubernetesParameters.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesParameters.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/Constants.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/InitJobManagerDecoratorTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/InitTaskManagerDecoratorTest.java
*kubernetes.flink.log.dir is useless and could be replaced with env.log.dir.Support the old configuration for rolling upgrades*
- *```config.sh``` Compatible 'kubernetes.flink.log.dir' configuration，but 'env.log.dir' has priority*
*NO*
*YES*
- Dependencies (does it add or upgrade a dependency): (no ) …
=>  [FLINK-24334][Deployment/Kubernetes] Configuration 'kubernetes.flink.log.dir' compatible

flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CodeSplitITCase.scala
FLINK-18356 aims to enforce memory limits for Docker containers, however failure tests in `CodeSplitITCase` will produce deep exception stack which may exceed this limit.
This PR removes the failure test (we can determine the failure by hand when constructing the test cases). I've run this fix based on #18368 on [azure](https://dev.azure.com/tsreaper96/Flink/_build/results?buildId=320&view=results) and it does not fail on flink-table module, which validates this fix.
- Remove failure test in CodeSplitITCase to avoid deep exception stack
- The runtime …
=> [FLINK-25681][table-planner] Remove failure test in CodeSplitITCase to avoid deep exception stack

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamEdge.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraph.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamNode.java, flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/TimestampITCase.java
Previously, if there was a node that was self-unioned with itself,
it was creating a situation with two identical StreamEdges. Both
with the same partitioning, from the same source node to the same
target node.
This was causing issues when constructing output collectors and
picking the correct RecordWriters, as StreamTask was not able to
uniquely identify given StreamEdge and was assigning the same
RecordWriter to both of the edges. As a result all stream elements
were sent twice through the same RecordWriter. It was actually pretty
harmless apart of calculating the combined watermark downstream,
since all watermarks were always comming just from one single
edge/inputgate, and the unused edges were always stuck with
min watermark.
As a solution we are making sure that StreamEdges are …
=> [FLINK-25199][network] Make sure StreamEdges are unique

flink-connectors/flink-connector-cassandra/src/test/java/org/apache/flink/streaming/connectors/cassandra/CassandraConnectorITCase.java
This is to avoid the flakiness of the `CassandraConnectorITCase#test*Pojo*` tests due to retrials that try to recreate an already created (and potentially populated) table. This is the quick version that still uses Junit4 and `RetryRule` to quickly fix the Cassandra flakiness issue. The version that uses `RetryExtension` needs a migration of cassandra tests to junit5 and some parent tests are in flink-streaming and mutualized so it would be done in a next PR.
I also added a commit to replace all string literals by constants to avoid existing copy/paste.
R: @tillrohrmann 
CC: @zentol
=> [FLINK-25674] Add drop tables to be idempotent in case of retrials and the related test

docs/layouts/shortcodes/generated/kubernetes_config_configuration.html, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/configuration/KubernetesConfigOptions.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/InitJobManagerDecorator.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/InitTaskManagerDecorator.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/AbstractKubernetesParameters.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesParameters.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/Constants.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/InitJobManagerDecoratorTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/InitTaskManagerDecoratorTest.java
Backport #17503 to release-1.13.
=> [BP-1.13][FLINK-24334][k8s] Set FLINK_LOG_DIR environment for JobManager and TaskManager pod if configured via options

docs/layouts/shortcodes/generated/kubernetes_config_configuration.html, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/configuration/KubernetesConfigOptions.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/InitJobManagerDecorator.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/InitTaskManagerDecorator.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/AbstractKubernetesParameters.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesParameters.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/Constants.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/InitJobManagerDecoratorTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/InitTaskManagerDecoratorTest.java
Backport #17503 to release-1.14.
=> [BP-1.14][FLINK-24334][k8s] Set FLINK_LOG_DIR environment for JobManager and TaskManager pod if configured via options

docs/content.zh/docs/dev/table/sql/queries/window-agg.md, docs/content/docs/dev/table/sql/queries/window-agg.md
Aliases need to be used under Cascading Window Aggregation, otherwise an error will be reported, but there is no such thing in the documentation, so I fixed it
Fix errors in documentation, add aliases
=> [hotfix][docs]fix flink sql Cascading Window TVF Aggregation exception

docs/layouts/shortcodes/generated/kubernetes_config_configuration.html, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/KubernetesClusterDescriptor.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/KubernetesResourceManagerDriver.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/cli/KubernetesSessionCli.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/configuration/KubernetesConfigOptions.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/configuration/KubernetesResourceManagerDriverConfiguration.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/entrypoint/KubernetesEntrypointUtils.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/entrypoint/KubernetesResourceManagerFactory.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/Fabric8FlinkKubeClient.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/FlinkKubeClient.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/InitJobManagerDecorator.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/InitTaskManagerDecorator.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/AbstractKubernetesParameters.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/resources/KubernetesService.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/Constants.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/KubernetesUtils.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/KubernetesResourceManagerDriverTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/Fabric8FlinkKubeClientTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/TestingFlinkKubeClient.java, flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/ClusterEntrypoint.java, flink-runtime/src/main/java/org/apache/flink/runtime/util/ResourceManagerUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/ResourceManagerUtilsTest.java, flink-yarn/src/main/java/org/apache/flink/yarn/YarnResourceManagerDriver.java
Provide hostnetwork network mode for jobs running in native kubernetes mode to obtain better performance in unmanaged clusters(for session mode)
When a job is running in session mode, you can start the hostnetwork mode by configuring "kubernetes.hostnetwork.enabled=true". After it is turned on, the pod of JobManager and TaskManager will use the host network instead of the third-party CNI plug-in.
1. Use a random port when starting a session
2. Update the targetPort of the corresponding ports of InternalService and ExternalService to the real value whenever the session starts successfully 
The session and job are started when "kubernetes.hostnetwork.enabled=true" is configured. When the task is running normally, the JobManager is killed. After the JobManager is automatically started, the …
=> [FLINK-24947] Support hostNetwork for native K8s integration on session mode

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/metadata/MetadataV2V3SerializerBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/CheckpointBoundKeyedStateHandle.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/IncrementalKeyedStateHandle.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/ChangelogStateBackendHandle.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/ttl/mock/MockKeyedStateBackend.java, flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java, flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogStateBackend.java, flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/PeriodicMaterializationManager.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackendTest.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogStateBackendTestUtils.java
```
When triggering materialization, Changelog backend uses fake
checkpoint ID to obtain a (materialized) snapshot.
That same ID must be used when proxying checkpoint
completion/abortion notifications to the nested backend.
On recovery, nested backend might read lastCompletedCheckpointID
from its snapshot; in particular, when enabling changelog, which
may cause inconsistency.
This change:
- adds a mapping from checkpoint to materializationID
- stores materializationID in checkpoint metadata
- selects max materializationID on recovery (to handle upscaling)
```
Added `ChangelogKeyedStateBackendTest.testCheckpointConfirmation`.
- …
=> [FLINK-25524] Fix ChangelogStateBackend.notifyCheckpointComplete

docs/content.zh/docs/ops/rest_api.md, docs/content/docs/ops/rest_api.md, docs/layouts/shortcodes/generated/rest_v1_dispatcher.html, docs/static/generated/rest_v1_dispatcher.yml, flink-docs/README.md, flink-docs/pom.xml, flink-docs/src/main/java/org/apache/flink/docs/rest/OpenApiSpecGenerator.java, flink-docs/src/test/java/org/apache/flink/docs/rest/OpenApiSpecGeneratorTest.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/async/AsynchronousOperationResult.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/json/SerializedThrowableSerializer.java, pom.xml
This PR adds a generator for an experimental OpenAPI specification for the REST API. This can be used to generate clients in various languages.
The spec is mostly generated from our `MessageHeaders`, with some tweaks where necessary. Most of it should be correct, but there may be bugs, particularly for the more special endpoints (e.g., those accepting file uploads).
To generate the spec we use `swagger`.
In order for swagger to pick up our jackson annotations we need a flink-shaded version of swagger that relocates jackson. See [this](https://github.com/apache/flink-shaded/pull/102) flink-shaded draft. This means that CI _will not pass_.
I had to add annotations to the `AsynchronousOperationResult` because swagger noticed these getters; it's just a difference in behavior to our current …
=> [FLINK-14954][rest] Add OpenAPI spec generator

flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriter.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterTest.java
Fixing reversed insertion of failed requests in `AsyncSinkBase`.
- fixed implementation of `completeRequest` function in `AsyncSinkWriter`.
- Added unit test to capture previous behavior.
=> [FLINK-24041][connector] Fixing reversed insertion of failed requests

docs/content.zh/docs/dev/table/sql/queries/match_recognize.md, docs/content/docs/dev/table/sql/queries/match_recognize.md
* The match recognize functions were displayed with triple backticks in the table.
* Updated docs to use <code>...</code> like in other tables in the docs.
- The S3 file …
=> [FLINK-25763][match-recognize][docs] Updated docs to use code tag consistent with other tables

flink-connectors/flink-file-sink-common/src/main/java/org/apache/flink/streaming/api/functions/sink/filesystem/InProgressFileWriter.java
This PR is trivial, nothing but fixing a typo in `InProgressFileWriter`
`InProgressFileWriter`
- a element => an element
This change is a trivial rework/code cleanup without any test coverage. …
=> [hotfix][filesystem] Fix the typo in InProgressFileWriter

flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/KafkaSourceEnumerator.java, flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/OffsetsInitializer.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/enumerator/KafkaEnumeratorTest.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/enumerator/initializer/OffsetsInitializerTest.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestBase.java
`AdminClient.listOffsets` is provided in Kafka 2.7, In the future more `OffsetSpce` types will be added to it, for example, OffsetSpec.MaxTimestampSpec is added in Kafka 3.0.0. so it's better to substitute `KafkaConsumer` with `AdminClient`.
- Substitute KafkaConsumer with AdminClient in OffsetsInitializer
- Substitute KafkaConsumer with AdminClient in FlinkKafkaConsumer
- Totally remove KafkaConsumer from KafkaSourceEnumerator.
This change is already covered by existing tests `OffsetsInitializerTest`. …
=> [FLINK-25368][connectors/kafka] Substitute KafkaConsumer with AdminClient when getting offsets

docs/content.zh/docs/ops/metrics.md, docs/content/docs/ops/metrics.md, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPool.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/NetworkBufferPool.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/metrics/NettyShuffleMetricFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/NettyShuffleUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/NetworkBufferPoolTest.java
Right now, if exclusive buffers for the input channel and one buffer for each subpartition would be allocated on start successfully but there would be not enough memory for the rest of the buffers(floating buffers, rest buffers for subpartitions), then we see nothing in the log about that(as I understand).
So first of all, we need to check what logs we have right now about situations when flink doesn't have enough memory for all configured buffers. And if we have nothing (or not enough) we should add such a log.
Added a dedicated unit test
Manually tested in an end to end example. …
=> [FLINK-25590][metrics] Introduce RequestedMemoryUsage and log warnings if usage exceeds 100%

flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/table/KeyExtractor.java
This is a trivial PR removing private `KeyExtractor.ColumnWithIndex` non-used class
=> [FLINK-25754] Drop KeyExtractor.ColumnWithIndex

flink-connectors/flink-connector-hive/pom.xml, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/HiveCatalog.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/util/HiveTableUtil.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/catalog/hive/HiveCatalogITCase.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/catalog/hive/HiveCatalogTest.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/ManagedTableListener.java
This PR aims to let `HiveCatalog` support Flink's managed table. More details can be found at [FLIP-188](https://cwiki.apache.org/confluence/display/FLINK/FLIP-188%3A+Introduce+Built-in+Dynamic+Table+Storage)
This PR contains two commits.
- 5c2d53d2 migrate `HiveCatalogTest` and `HiveCatalogITCase` to use assertJ
- d7dc483a let hive support Flink's managed table
-   enable `HiveCatalog#supportsManagedTable`
-   inject `connector = 'default'` for `HiveCatalog#createTable` and remove `connector = 'default'` for `HiveCatalog#getTable`
-  disallow `alter table` changing the catalog table type between `HIVE_TABLE`, `FLINK_MANAGED_TABLE` and `FLINK_NON_MANAGED_TABLE.`
- Extend `HiveCatalogTest` to verify table parameters and options when …
=> [FLINK-25312][hive] HiveCatalog supports Flink's managed table

flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AbstractAvroBulkFormat.java, flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroFileFormatFactory.java, flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroBulkFormatTestUtils.java
FLINK-24565 ports avro format to BulkReaderFormatFactory. However the implementation leaves some states into the format factory itself. These states should be in the readers.
- Move states of AbstractAvroBulkFormat into its reader …
=> [FLINK-25861] Move states of AbstractAvroBulkFormat into its reader

flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/Execution.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/CreatingExecutionGraph.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraphDeploymentTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraphDeploymentWithSmallBlobCacheSizeLimitTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ExecutionVertexDeploymentTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/RemoveCachedShuffleDescriptorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/ExecutionGraphToInputsLocationsRetrieverAdapterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/SchedulerBenchmarkUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/deploying/DeployingDownstreamTasksInBatchJobBenchmark.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/deploying/DeployingTasksInStreamingJobBenchmark.java
Enforce that executions cannot be transitioned from CREATED -> DEPLOYING by skipping the SCHEDULED state.
=> [FLINK-25707] AdaptiveScheduler transitions executions to scheduled 

flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java
```
The notification currently causes an exception and adds complexity.
It's also not necessary, unlikely to be delivered (because of the
difference in checkpoint/materialization intervals) and unlikely to be
utilized (it will arrive only after the nested snapshot has completed
and most likely do the same GC as in completion notification).
``` …
=> [FLINK-25816][state] Remove checkpoint abortion notification of notify backend

docs/content.zh/docs/deployment/config.md, docs/content.zh/docs/ops/metrics.md, docs/content.zh/docs/ops/state/state_backends.md, docs/content/docs/deployment/config.md, docs/content/docs/ops/metrics.md, docs/content/docs/ops/state/state_backends.md, docs/layouts/shortcodes/generated/fs_state_changelog_configuration.html, flink-docs/pom.xml, flink-docs/src/main/java/org/apache/flink/docs/configuration/ConfigOptionsDocGenerator.java
Add documentation for State Changelog (FLIP-158):
- state-backends
- configuration
- metrics
- Dependencies (does it add or upgrade a dependency): yes (internal: flink-docs -> flink-dstl-dfs)
- If yes, how is the feature documented? see above
=> [FLINK-25024][docs] Add Changelog backend docs

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorGateway.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/TaskStateSnapshot.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/SequenceNumber.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/StateChange.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/rpc/RpcCheckpointResponder.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/JobMasterTester.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/utils/TestingJobMasterGateway.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/ttl/mock/MockKeyedStateBackend.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/ttl/mock/MockKeyedStateBackendBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/ttl/mock/MockStateBackend.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackendTest.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/StateHandleReuseITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointFailureHandlingITCase.java
```
CheckpointCoordinator doesn't expect to receive the same object more than once:
in production environment, state handles are (de)serialized while sending via RPC.
However, in tests, local RPC may be used, without (de)serialization. This causes
test failures when using state backends which re-use objects (e.g. materialized
state of ChangelogStateBackend).
Using the same KeyedStateHandle *object* should be allowed for backends.
This change makes RpcCheckpointResponder serialize TaskStateSnapshot when
sending to JM from TM.
```
Added `StateHandleReuseITCase`
- …
=> [FLINK-25479][rpc] Serialize TaskStateSnapshot when sending to JM from TM

flink-runtime/src/main/java/org/apache/flink/runtime/rest/FileUploadHandler.java, pom.xml
Based on #18463.
The new netty version contains a proper fix for the CLRF issue, so we can remove our safeguard again.
=> [FLINK-25016][build] Upgrade to Netty 4.1.70 

flink-connectors/flink-connector-cassandra/pom.xml, flink-connectors/flink-connector-cassandra/src/test/java/org/apache/flink/streaming/connectors/cassandra/CassandraConnectorITCase.java
`NoHostAvailableException` happens despite the 3 retrials that were set. So I'm raising the timeouts for all the requests to Cassandra testContainer.
R: @tillrohrmann 
CC: @zentol
=> [FLINK-25771][connectors][Cassandra][test] Raise all read/write/miscellaneous requests timeouts

flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/StreamMultipleInputProcessor.java
This is a draft PR to solve:
> Let's assume we have two inputs, one is flipping between available/unavailable status, the other is continuously unavailable. Now per each StreamMultipleInputProcessor#getAvailableFuture call, we will create one CompletableFuture<?> anyInputAvailable, referenced by TWO instances CompletableFuture$UniRun, for inputProcessors[i].getAvailableFuture() from each of the inputs. anyInputAvailable will be returned, and it will be completed by first input sooner or later, waking up SteamTask in the process. That's fine. Now the problem is that each of those anyInputAvailable instance will be in this scenario referenced forever by the second input's inputProcessors[i].getAvailableFuture(). As long as the second input is not available, we are keep building up the …
=> [FLINK-25728][task] Solve potential memory leaks in StreamMultipleInputProcessor

flink-connectors/flink-connector-cassandra/pom.xml, flink-connectors/flink-connector-cassandra/src/test/java/org/apache/flink/streaming/connectors/cassandra/CassandraConnectorITCase.java
This is the backport to 1.13 of [this already merged PR](https://github.com/apache/flink/pull/18509)
R: @fapaul as you reviewed the original PR
=> [FLINK-25771][connectors][Cassandra][test] Raise all read/write/miscellaneous requests timeouts. Backport to 1.13

flink-end-to-end-tests/run-nightly-tests.sh, flink-end-to-end-tests/test-scripts/common.sh, flink-end-to-end-tests/test-scripts/common_artifact_download_cacher.sh, flink-end-to-end-tests/test-scripts/common_s3.sh, flink-end-to-end-tests/test-scripts/elasticsearch-common.sh, flink-end-to-end-tests/test-scripts/kafka-common.sh, flink-end-to-end-tests/test-scripts/test_azure_fs.sh, flink-end-to-end-tests/test-scripts/test_resume_externalized_checkpoints.sh, tools/azure-pipelines/cache_docker_images.sh, tools/ci/test_controller.sh, tools/releasing/create_binary_release.sh, tools/releasing/create_release_branch.sh, tools/releasing/create_snapshot_branch.sh, tools/releasing/create_source_release.sh, tools/releasing/update_branch_version.sh, tools/releasing/update_japicmp_configuration.sh
There are several points where the E2E tests check that an environment variable is nonempty before proceeding with the tests, such as the `E2E_TARBALL_CACHE`. Usually, this results in a friendly error message stating "You have to export the E2E Tarball Cache as E2E_TARBALL_CACHE".
However, if running the scripts with nounset during development, this results in an `E2E_TARBALL_CACHE: unbound variable` error, which is less friendly to the user.
This PR changes these instances to use parameter expansion for these variables, so that even with nounset, the user recieves the friendly error message for a missing environment variable.
- *E2E test script error handling for unbound environment variables has been improved*
This change is a trivial …
=> [FLINK-25041][e2e] Improve error handling for missing environment variables in E2E tests

flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/NetworkBufferPoolTest.java
Use `CheckedThread#sync` to fail the test if the thread has crashed, instead of waiting for a timeout.
=> [FLINK-25819][tests] Improve error reporting

flink-tests/src/test/java/org/apache/flink/test/recovery/TaskManagerProcessFailureStreamingRecoveryITCase.java
https://issues.apache.org/jira/browse/FLINK-25564
Leave cleanup to rule, to avoid flaky test.
This PR only changes a test.
=> [FLINK-25564][flink-tests] leave cleanup to rule

docs/layouts/_default/baseof.html
* This PR removes the current Google Analytics web analytics tracking from the Flink documentation and replaces it with the ASF hosted Matomo installation, as discussed on the Dev mailing list https://lists.apache.org/thread/kv0mf1y9cq4cdsf4jkq3gb6jo7b81cq3
* ef12918d1aa00b4c529f34a5a7ed6a1edd79c920 Removes Google Analytics implementation
* 0b1ad7917d4839b0226cb874702ed4089a91e706 Adds Matomo setup. This was previously done for flink-web via https://github.com/apache/flink-web/pull/502 and https://github.com/apache/flink-web/pull/503
* You can inspect the network traffic in your browser using the Developer Tools. Right now, you'll see calls being made to the google-analytics.com domain. When checking ef12918d1aa00b4c529f34a5a7ed6a1edd79c920 you'll see that these calls are no longer made. …
=> [FLINK-25880][Docs] Implement Matomo in Flink documentation

docs/_layouts/base.html
Backport of #18577 - Had to re-implement the changes due to this version and the ones before that were using Jekyll instead of Hugo
=> [FLINK-25880][BP 1.12][Docs] Implement Matomo in Flink documentation

docs/layouts/shortcodes/generated/deployment_configuration.html, flink-clients/src/main/java/org/apache/flink/client/program/MutatedConfigurationException.java, flink-clients/src/main/java/org/apache/flink/client/program/StreamContextEnvironment.java, flink-clients/src/test/java/org/apache/flink/client/program/ClientTest.java, flink-clients/src/test/java/org/apache/flink/client/program/StreamContextEnvironmentTest.java, flink-clients/src/test/java/org/apache/flink/client/testjar/ForbidConfigurationJob.java, flink-core/src/main/java/org/apache/flink/configuration/DeploymentOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/ConfigurationNotAllowedMessage.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java
This PR adds an option to disable programmatic configurations in a user program when running with the Application mode. In case, the option is enabled program changing the configuration will result in a failed job.
By default, this configuration is turned off to not break existing setups.
This subsumes #17995 
- Introduce a new exception for failures during the execution of the user jar
- Allow the storing of failed jobs without a submission
Added tests to verify the exception is thrown in the correct scenarios and the job result is retrievable after the exception was thrown.
- …
=> [FLINK-25206] Add configuration option to disable configuration in user programs

docs/content/docs/connectors/table/filesystem.md
This fixes a mistake in the docs when working on https://github.com/apache/flink/pull/18176 
* Fix filesystem directory watching docs
=> [hotfix][docs][connector/files] Fix directory watching docs

docs/layouts/partials/docs/inject/menu-after.html, docs/static/js/track-search-terms.js
This is depending on https://github.com/apache/flink/pull/18577 being merged first to get Matomo loaded in the Flink documentation
* This tracks the internal search terms that users are using on the Flink documentation and sends these to Matomo
* Added Javascript debounce function to track when a user is done with typing in his search term (currently set to 2 seconds)
* This is depending on https://github.com/apache/flink/pull/18577 being merged, right now it would return an error on `paq` not being found because Matomo is not yet loaded in. When that is merged, you will see a call being made to `https://matomo.privacy.apache.org` when a search term is entered and no change is made after 2 seconds …
=> [FLINK-25879][Docs] Track used search terms in Matomo

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/Checkpoints.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointMetadataLoadingTest.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBStateUploader.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/snapshot/RocksIncrementalSnapshotStrategy.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateUploaderTest.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/SavepointFormatITCase.java
Incremental savepoints do not reuse sst files from previous checkpoints.
At this point they re-upload those files. Moreover they do not register
its files as reusable by future checkpoints. Lastly, all sst files are
created in the EXCLUSIVE scope with relative paths, which makes the
savepoint relocatable.
Added tests:
* SavepointFormatITCase
- …
=> [FLINK-25745] Support RocksDB incremental native savepoints 

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/MultipleFuturesAvailabilityHelper.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/StreamMultipleInputProcessor.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorIdleTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorTestContext.java
SourceOperator.SourceOperatorAvailabilityHelper is prone to the same type of memory leak as FLINK-25728. Every time new CompletableFuture.any is created:
```
currentCombinedFuture =
CompletableFuture.anyOf(forcedStopFuture, sourceReaderFuture);
return currentCombinedFuture;
```
Such future is never garbage collected, because forcedStopFuture will keep a reference to it. This will eventually lead to a memory leak, or force stopping might take very long time to complete. …
=> [FLINK-25827][task] Fix potential memory leak in SourceOperator when using CompletableFuture.anyOf

flink-table/flink-table-planner/pom.xml
Streamline the table-planner shade-plugin configuration to again use the default `shade-flink` execution, which is covered by the license checker. This is just a remnant from the development that wasn't re-visited.
I've verified that the contents of the generated jars is identical.
=> [FLINK-25947][build] Simplify shade-plugin configuration

flink-core/src/main/java/org/apache/flink/api/java/typeutils/runtime/PojoSerializer.java, flink-core/src/test/java/org/apache/flink/api/common/typeutils/TypeSerializerUpgradeTestBase.java
In order to support Pojo schema migration, we added a new ctor to the
PojoSerializer, which uses data extracted from a snapshot. However the
duplicate method still used the old ctor which tries to recreate parts
of the data from the current context.
We should use the same ctor as we use for schema migration in the
duplicate methods. We must make sure though all serializers are properly
duplicated.
Tests in `PojoSerializerUpgradeTest` pass (I added a call to TypeSerializer#duplicate)
- Anything …
=> [FLINK-21752] NullPointerException on restore in PojoSerializer 

flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/DefaultJobManagerRunnerRegistry.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/OnMainThreadJobManagerRunnerRegistry.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/cleanup/DispatcherResourceCleanerFactory.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobServerCleanupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/AbstractDispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DefaultJobManagerRunnerRegistryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherFailoverITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/TestingDispatcher.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/cleanup/TestingResourceCleanerFactory.java
Refactored the tests around cleanup collecting cleanup-relevant tests in `DispatcherResourceCleanupTest`
* Makes `BlobServerClenupTest` based on JUnit5 and AssertJ and adds cleanup-related tests
* `DispatcherResourceCleanupTest` is refactored to only rely on the cleanup without testing the downstream CleanableResources. Testing that the right components are cleaned is tested in `DispatcherResourceCleanerFactoryTest`.  The actual cleanup for each component is then tested in the corresponding component tests.
* Additionally, I added test cases in `DispatcherResourceCleanerFactoryTest` for verifying that the `JobResult` is marked as dirty before the cleanup and clean after the cleanup
The PR itself is just tests …
=> [FLINK-25953][FLINK-25954] Updates and reorganizes tests around Dispatcher cleanup

flink-end-to-end-tests/test-scripts/common_kubernetes.sh
This PR is trying to print the previous logs of restarted pod. It is very useful to debug the failed K8s related e2e tests(e.g. FLINK-25839).
=> [FLINK-25839][e2e] Print the previous logs of restarted pod for k8s e2e tests

flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogWriter.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/inmemory/InMemoryStateChangelogWriter.java, flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogDelegateHashMapInMemoryTest.java
Materialization.upTo is suppoed to be exclusive boundary. This is true for the DFS-based writer, but not for InMemory one.
This change:
- makes "exclusiveness" excplicit by adding `.next()` to `writer.lastAppendedSqn` in the Changelog backend
- makes `lastAppendedSqn` deterministic in the DFS-based writer by remembering the last returned value if needed
Added `ChangelogDelegateHashMapInMemoryTest`
- …
=> [FLINK-25492][state/changelog] Fix materialization boundary for InMemoryStateChangelogWriter

flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionJobVertex.java, flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/CoordinatorStore.java, flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/CoordinatorStoreImpl.java, flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinator.java, flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinatorHolder.java, flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/RecreateOnResetOperatorCoordinator.java, flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinator.java, flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorProvider.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ExecutionJobVertexTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/MockOperatorCoordinatorContext.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinatorHolderTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/ExecutingTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorTestBase.java
In order to allow `SourceCoordinators`s from different `Source`s (for example two different Kafka sources, or Kafka and Kinesis) to align watermarks, they have to be able to exchange information/aggregate watermarks from those different Sources. To enable this, we need to provide some CoordinatorStore concept, that would be a thread safe singleton. …
=> [FLINK-24439][source] Introduce CoordinatorStore

flink-core/src/main/java/org/apache/flink/core/fs/EntropyInjectingFileSystem.java, flink-core/src/main/java/org/apache/flink/core/fs/EntropyInjector.java, flink-core/src/test/java/org/apache/flink/core/fs/EntropyInjectorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStreamFactoryTest.java
We treat all filesystems that extend from EntropyInjectingFileSystem as
if they always inject entropy. However, we support returning null from
EntropyInjectingFileSystem#getEntropyInjectionKey which translates to
disabled entropy injections. In such cases we should support savepoints
relocation by creating relative paths for exclusive files.
Added tests in:
* `FsCheckpointStreamFactoryTest`
* `EntropyInjectorTest` …
=> [FLINK-25952] Savepoints on S3 are not relocatable even if entropy injection is not enabled

flink-clients/src/test/java/org/apache/flink/client/deployment/application/ApplicationDispatcherBootstrapITCase.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/DefaultCompletedCheckpointStoreUtils.java, flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/ApplicationStatus.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/DispatcherServices.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/JobDispatcherFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/SessionDispatcherFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/cleanup/CheckpointResourcesCleanupRunner.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/cleanup/CheckpointResourcesCleanupRunnerFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/cleanup/CleanupRunnerFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/DefaultCompletedCheckpointStoreUtilsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/DefaultSchedulerCheckpointCoordinatorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/PerJobCheckpointRecoveryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/TestingCheckpointIDCounter.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/TestingCompletedCheckpointStore.java, flink-runtime/src/test/java/org/apache/flink/runtime/clusterframework/ApplicationStatusTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/AbstractDispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherFailoverITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/MiniDispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/TestingDispatcher.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/TestingJobManagerRunnerFactory.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/TestingJobMasterServiceLeadershipRunnerFactory.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/cleanup/CheckpointResourcesCleanupRunnerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/cleanup/TestingCleanupRunnerFactory.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/runner/DefaultDispatcherRunnerITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
This PR is related to [FLIP-194](https://cwiki.apache.org/confluence/display/FLINK/FLIP-194%3A+Introduce+the+JobResultStore) and based on PR #18626 . It's labeled as a draft as long as PR #18626 isn't merged into `master` because the diff contains the PR #18626 changes as well.
This change introduces a `JobManagerRunner` implementation taking care of the cleanup of a otherwise finished job.
* makes certain `Testing*` implementations more general to make testing of the new functionality easier
* Moves extraction of `state.checkpoints.num-retained` from `SchedulerUtils` into `DefaultCompletedCheckpointStoreUtils` (which is renamed into `CompletedCheckpointStoreUtils`) to align with the new use case for this functionality
* Makes `ApplicationStatus` <-> `JobStatus` mapping (partially) …
=> [FLINK-25955][runtime] Introduces `JobManagerRunner` implementation for cleanup

flink-core/src/main/java/org/apache/flink/api/java/typeutils/runtime/kryo/KryoSerializer.java
When scala is not on the classpath and Kryo is used the KryoSerializer logs a full ClassNotFoundException as a warning.
Since this is now an expected situation it should logged on info. The exception should only be logged if debug logging is enabled.
=> [FLINK-25956][kryo] Remove noisy warnings

docs/assets/_custom.scss, docs/content.zh/docs/ops/metrics.md, docs/content/docs/ops/metrics.md, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/Execution.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionStateUpdateListener.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionVertex.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/InternalExecutionGraphAccessor.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultExecutionGraphFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/ExecutionGraphFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/metrics/DeploymentStateTimeMetrics.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/metrics/JobStatusMetrics.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/metrics/MetricsRegistrar.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/metrics/StateTimeMetric.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/TestingDefaultExecutionGraphBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/DefaultExecutionGraphFactoryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/ExecutingTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/metrics/DeploymentStateTimeMetricsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/metrics/JobStatusMetricsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/metrics/StateTimeMetricTest.java
FLINK-23976 added standardized metrics for capturing how much time we spend in each JobStatus. However, certain states in practice consist of several stages; for example the RUNNING state also includes the deployment of tasks.
To get a better picture on where time is spent I propose to add new metrics that capture the deployingTime based on the execution states. This will additionally get us closer to a proper uptime metric, which ideally will be runningTime - various stage time metrics.
A job is considered to be deploying,
for batch jobs, if no task is running and at least one task is being deployed
for streaming jobs, if at least one task is being deployed
The semantics are different for batch/streaming jobs because they differ in terms of how they make progress. For a streaming job all …
=> [FLINK-25888] Capture time that the job spends on deploying tasks

flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/JdbcSink.java, flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/JdbcOutputFormat.java, flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/JdbcXaSinkFunction.java, flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcExactlyOnceSinkE2eTest.java, flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcXaSinkTestBase.java
This PR continues work done in https://github.com/apache/flink/pull/15674 and addresses the remaining comments.
=> [FLINK-22311] [connector/jdbc] Validate maxRetries for XA Sink

docs/content.zh/docs/ops/rest_api.md, docs/content/docs/ops/rest_api.md, docs/layouts/shortcodes/ref_static.html
Adds a new short code for referring to static resources (because `ref` always points into content/).
=> [FLINK-26046][rest][docs] Fix link to OpenAPI spec

flink-end-to-end-tests/run-nightly-tests.sh, flink-end-to-end-tests/test-scripts/common.sh, flink-end-to-end-tests/test-scripts/common_artifact_download_cacher.sh, flink-end-to-end-tests/test-scripts/common_s3.sh, flink-end-to-end-tests/test-scripts/elasticsearch-common.sh, flink-end-to-end-tests/test-scripts/kafka-common.sh, flink-end-to-end-tests/test-scripts/test_azure_fs.sh, flink-end-to-end-tests/test-scripts/test_resume_externalized_checkpoints.sh, tools/azure-pipelines/cache_docker_images.sh, tools/ci/test_controller.sh, tools/releasing/create_binary_release.sh, tools/releasing/create_release_branch.sh, tools/releasing/create_snapshot_branch.sh, tools/releasing/create_source_release.sh, tools/releasing/update_branch_version.sh, tools/releasing/update_japicmp_configuration.sh
=> [FLINK-25041][BP 1.14][e2e] Improve error handling for missing environment variables in E2E tests

flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaWriter.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaWriterITCase.java, flink-core/src/main/java/org/apache/flink/api/connector/sink2/Sink.java
In Table Store, we want to get the offsets of kafka writer, only the offset returned by the callback inside the KafkaWriter is accurate, so we need this callback mechanism.
This ticket wants to add metadataConsumer to InitContext in Sink:
```
/**
* Returns a metadata consumer, the {@link SinkWriter} can publish metadata events of type
* {@link MetaT} to the consumer. The consumer can accept metadata events in an asynchronous
* thread, and the {@link Consumer#accept} method is executed very fast.
*/
default <MetaT> Optional<Consumer<MetaT>> metadataConsumer() {
return Optional.empty();
}
```
SinkWriter can get this consumer, and publish metadata to the consumer implemented by table store sink.
- Introduce metadataConsumer method
- KafkaWriter get metadataConsumer …
=> [FLINK-25696][datastream] Introduce metadataConsumer to InitContext in Sink

flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroFileFormatFactory.java
Currently `BulkDecodingFormat` of avro does not also implement `ProjectableDecodingFormat` and the reader will have to read unused columns.
This PR implements `ProjectableDecodingFormat` to optimize reading from avro files.
- Implement `ProjectableDecodingFormat` for avro `BulkDecodingFormat`.
This change is already covered by existing tests, such as `AvroFilesystemITCase#testProjectPushDown`.
- Does this …
=> [FLINK-26001][avro] Implement ProjectableDecodingFormat for avro BulkDecodingFormat

flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinator.java, flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContext.java, flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorProvider.java, flink-runtime/src/main/java/org/apache/flink/runtime/source/event/ReportedWatermarkEvent.java, flink-runtime/src/main/java/org/apache/flink/runtime/source/event/WatermarkAlignmentEvent.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorAlignmentTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorTestBase.java
Announce and combine latest watermarks across SourceOperators
This change adds a dedicated unit test for the new feature.
=> [FLINK-24440][source] Announce and combine latest watermarks across SourceOperators

docs/content.zh/docs/connectors/datastream/filesystem.md, docs/content/docs/connectors/datastream/filesystem.md, flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/avro/AvroParquetRecordFormat.java, flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/avro/AvroParquetStreamingFileSinkITCase.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java
Replace deprecated class, update doc, and fix typos
- Refactoring - replace the deprecated `ParquetAvroWriters` with the `AvroParquetWriters`
- Update doc to use `AvroParquetWriters`
- typos fix in `StreamExecutionEnvironment`
This change is a code and doc cleanup without any test coverage. …
=> [hotfix][docs] replace deprecated class and fix typos

flink-connectors/flink-connector-aws-kinesis-firehose/src/test/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkITCase.java
https://issues.apache.org/jira/browse/FLINK-26064
Disabling the test until the underlying issues are resolved. It seems to be some combination of ThreadLocals / ServiceLoader / Classloading issues deep down in AWS SDK, so it might take some time to address.
Context:
https://github.com/apache/flink/pull/18553#discussion_r802466514
=> [FLINK-26064] Temporarily disable KinesisFirehoseSinkITCase.

flink-connectors/flink-sql-connector-pulsar/pom.xml, flink-connectors/flink-sql-connector-pulsar/src/main/resources/META-INF/NOTICE, flink-connectors/pom.xml, flink-python/pyflink/datastream/connectors.py, flink-python/pyflink/datastream/tests/test_connectors.py, tools/ci/java-ci-tools/src/main/java/org/apache/flink/tools/ci/licensecheck/JarFileChecker.java
Support Pulsar source connector in Python DataStream API.
- *Introduce PulsarSource in PyFlink DataStream API*
- *Introduce PulsarDeserializationSchema, PulsarSourceBuilder, StartCursor, StopCursor and SubscriptionType class to set PulsarSource*
- *Add  a sql pulsar connector maven module that shaded the DataStream pulsar connector*
- *Added  test_pulsar_source in test_connectors.py*
- …
=> [FLINK-25530][python][connector/pulsar] Support Pulsar source connector in Python DataStream API.

flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/translators/SinkTransformationTranslator.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/StreamGraphGeneratorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/util/TestExpandingSink.java
Parallelism of a transformation with default parallelism(-1) is set when transforming, using the default parallelism set in the environment. However, in SinkExpander#expand, the environment parallelism is set to -1 at the entrance, to verify if the parallelism of a expanded transformation is set. The environment parallelism will be restored when exiting the method, but at present the transform is called within this scope. If the parallelism of a sink is not set, the parallelism of the sink transformation and all transformations expanded from it will not be handled, so the JobGraph generated will have vertices with -1 parallelism, causing the assertion failure in AdaptiveScheduler.
This pr fixes the bug by putting the restoring of the environment parallelism ahead of transforming the sink …
=> [FLINK-25937] Restore the environment parallelism before transforming in SinkExpander#expand.

docs/content.zh/docs/connectors/datastream/nifi.md, docs/content/docs/connectors/datastream/nifi.md, flink-connectors/flink-connector-nifi/src/main/java/org/apache/flink/streaming/connectors/nifi/NiFiSink.java, flink-connectors/flink-connector-nifi/src/main/java/org/apache/flink/streaming/connectors/nifi/NiFiSource.java
* Mark NiFi connector as deprecated so they can be removed in the next Flink release
* Added `@Deprecated` annotation to both `NiFiSource` and `NiFiSink`
=> [FLINK-26072][Connectors][NiFi] Mark NiFi Source and Sink as deprecated

docs/layouts/shortcodes/generated/all_jobmanager_section.html, docs/layouts/shortcodes/generated/job_manager_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/JobManagerOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/cleanup/DefaultResourceCleaner.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/cleanup/DispatcherResourceCleanerFactory.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherCleanupITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/TestingDispatcher.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/cleanup/DefaultResourceCleanerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/cleanup/DispatcherResourceCleanerFactoryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/cleanup/TestingRetryStrategies.java, flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/retriever/impl/RpcGatewayRetrieverTest.java
We want to make the cleanup try to run infinitely until the cleanup is resolved.
* Adds `FutureUtils.retryWithDelay` in `DefaultResourceCleaner`
* `DefaultResourceCleanerTest` was extended to cover the retry mechanism
=> [FLINK-25433][runtime] Adds retry mechanism to DefaultResourceCleaner

flink-connectors/flink-connector-jdbc/pom.xml
* Upgrade com.h2database:h2 to 2.1.210 to address CVE-2022-23221
* Updated POM
=> [FLINK-25785][Connectors][JDBC] Upgrade com.h2database:h2 to 2.1.210

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/metadata/MetadataV2V3SerializerBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/DirectoryKeyedStateHandle.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/IncrementalRemoteKeyedStateHandle.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/KeyGroupsStateHandle.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/KeyedStateHandle.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/StateHandleID.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/ChangelogStateBackendHandle.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/ChangelogStateHandleStreamImpl.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/inmemory/InMemoryChangelogStateHandle.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/StateHandleDummyUtil.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/metadata/CheckpointTestUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/metadata/MetadataV3SerializerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/ChangelogTestUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/IncrementalRemoteKeyedStateHandleTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/KeyGroupsStateHandleTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/SharedStateRegistryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/ttl/mock/MockKeyedStateBackend.java, flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java, flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogStateBackend.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
Correct the state register logic of ChangelogStateBackendHandle.
- Refactor register logic of `ChangelogStateBackendHandleImpl`.
- Added SharedStateRegistryTest#testRegisterChangelogStateBackendHandles
=> [FLINK-25478][chaneglog] Correct the state register logic of ChangelogStateBackendHandle

flink-connectors/flink-connector-aws-kinesis-data-streams/pom.xml, flink-connectors/flink-connector-aws-kinesis-data-streams/src/main/java/org/apache/flink/connector/kinesis/sink/KinesisDataStreamsSink.java, flink-connectors/flink-connector-aws-kinesis-data-streams/src/main/java/org/apache/flink/connector/kinesis/sink/KinesisDataStreamsSinkWriter.java, flink-connectors/flink-connector-aws-kinesis-data-streams/src/main/java/org/apache/flink/connector/kinesis/sink/KinesisDataStreamsStateSerializer.java, flink-connectors/flink-connector-aws-kinesis-data-streams/src/test/java/org/apache/flink/connector/kinesis/sink/KinesisDataStreamsStateSerializerTest.java, flink-connectors/flink-connector-aws-kinesis-firehose/src/main/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSink.java, flink-connectors/flink-connector-aws-kinesis-firehose/src/main/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkWriter.java, flink-connectors/flink-connector-aws-kinesis-firehose/src/main/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseStateSerializer.java, flink-connectors/flink-connector-aws-kinesis-firehose/src/test/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkWriterTest.java, flink-connectors/flink-connector-aws-kinesis-firehose/src/test/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseStateSerializerTest.java, flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/AsyncSinkBase.java, flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriter.java, flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterStateSerializer.java, flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/BufferedRequestState.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/ArrayListAsyncSink.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterStateSerializerTest.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterTest.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterTestUtils.java
- Adding buffered requests in snapshot state of `AsyncSinkWriter` and its implementation so that the writers can resume the buffered requests when restoring from a checkpoint/savepoint.
- Added `BufferedRequestsState` in `flink-connector-base`.
- Added `AsyncSinkWriterStateSerializer` in `flink-connector-base`.
- implemented `AsyncSinkWriterStateSerializer` in both `flink-connector-aws-kinesis-data-streams` and `flink-connector-aws-kinesis-firehose`.
- Added unit tests for new serializer class. …
=> [FLINK-25943][connector/common] Add buffered requests to snapshot state in AsyncSyncWriter.

flink-connectors/flink-connector-jdbc/pom.xml
(cherry picked from commit 8488b9e110baec5ed31c3e62d72ff3eceaab721c)
Signed-off-by: martijnvisser <martijn@2symbols.com>
Backport of https://github.com/apache/flink/pull/18605
=> [FLINK-25785][BP 1.14][Connectors][JDBC] Upgrade com.h2database:h2 to 2.1.210

flink-connectors/flink-connector-jdbc/pom.xml
(cherry picked from commit 8488b9e110baec5ed31c3e62d72ff3eceaab721c)
Signed-off-by: martijnvisser <martijn@2symbols.com>
Backport of https://github.com/apache/flink/pull/18605
=> [FLINK-25785][BP 1.13][Connectors][JDBC] Upgrade com.h2database:h2 to 2.1.210

flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogWriter.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/ChangelogStorageMetricsTest.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/FsStateChangelogWriterSqnTest.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/FsStateChangelogWriterTest.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/StateChangelogWriter.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/inmemory/InMemoryStateChangelogWriter.java, flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogStateBackendTestUtils.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/StateChangeLoggerTestBase.java
The current semantics of `ChangelogWriter.lastAppendedSqn` doesn't allow 
to distinguish between initial empty and non-empty states.
This results in wrong SQN passed to `truncate` and `persist` methods.
This change solves this by replacing `lastAppendedSqn` with `nextSqn`.
It essentially moves the responsibility to call `sqn.next()` on materialization
from backend to writer which has the knowledge of whether there were any changes or not. 
`ProcessingTimeWindowCheckpointingITCase` …
=> [FLINK-25987][state/changelog] Replace lastSqn with nextSqn()

flink-core/src/main/java/org/apache/flink/api/common/state/StateDescriptor.java, flink-core/src/test/java/org/apache/flink/api/common/state/StateDescriptorTest.java
Enable state descriptor to handle StateTtlConfig#DISABLED.
Modify current implementation to let state descriptor could handle `StateTtlConfig.DISABLED`.
Added StateDescriptorTest#testStateTTlConfig
=> [FLINK-25466][state] Enable state descriptor to handle StateTtlConfig#DISABLED

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/CodeGenUtils.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/ScalarOperatorsTest.scala, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/NumericUtils.java
Currently generated Java code for equality checking does not consider boxed Java types. This PR fixes this issue.
- Boxed numeric type should be considered when generating code for equality checking
=> [FLINK-25227][table-runtime] Boxed numeric type should be considered when generating code for equality checking

flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/JobCancellationFailedException.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/cleanup/CheckpointResourcesCleanupRunner.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/cleanup/CheckpointResourcesCleanupRunnerFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMasterServiceLeadershipRunner.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherCleanupITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/TestingDispatcher.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/TestingJobManagerRunnerRegistry.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/cleanup/CheckpointResourcesCleanupRunnerTest.java
The introduction of the JobResultStore changes the dependencies
during cleanup a bit. The job's result is written to the JobResultStore
after it reaches a globally terminated state. The job cleanup
for the different components (including the JobManagerRunnerRegistry)
happens independently from each other.
With this commit we switch to relying on the entry in the JobResultStore
for cancellation. This is the ground-truth for globally-terminated jobs
now.
* Extends `Dispatcher.cancelJob` to check the `JobResultStore` for entries
* A unit test was added to cover this code branch …
=> [FLINK-25974] Makes job cancellation rely on JobResultStore entry

flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/source/NoOpTimestampsAndWatermarks.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/source/ProgressiveTimestampsAndWatermarks.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/source/SourceOutputWithWatermarks.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/source/TimestampsAndWatermarks.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/source/WatermarkToDataOutput.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorAlignmentTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorTestContext.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/source/CollectingDataOutput.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/source/SourceOutputWithWatermarksTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/source/TestingSourceOperator.java
This PR integrates with FLINK-24440 and it implements `SourceOperator` level handling of watermark alignment.
This PR adds a dedicated unit test for the `SourceOperator` changes. …
=> [FLINK-24441][source] Block SourceOperator when watermarks are out of alignment

flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/streaming/util/TestStreamEnvironment.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/SavepointFormatITCase.java
The test vaildates corrects types of state handles created by savepoint. For NATIVE savepoints, it expects IncrementalRemoteKeyedStateHandle and KeyGroupsStateHandle.
However, with changelog those will be wrapped into ChangelogStateBackendHandle and the test fails.
This change explicitly controls whether changelog is enabled or disabled and adjusts expectations accordingly. …
=> [FLINK-26093][tests] Adjust SavepointFormatITCase for ChangelogStateBackend

flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/translators/SinkTransformationTranslator.java
During the transformations adjustment, we need to keep any potential customized parallelism value. This can be achieved by setting the environment parallelism to be ExecutionConfig.PARALLELISM_DEFAULT before adjusting transformations and restoring it back after it. Considering the high cohesion from design perspective, the logic of changing the environment parallelism should be as close as possible to the transformation adjustment.
- move the logic of changing the environment parallelism into the `adjustTransformations()` method
- add comprehensive javadoc and single line comments to describe the reason of doing it.
This change is covered by StreamGraphGeneratorTest and UpsertKafkaTableITCase. …
=> [hotfix][datastream] move the change and restore of env parallelism into the adjusTransformations method.

flink-core/src/test/java/org/apache/flink/api/connector/source/mocks/MockSourceReader.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorAlignmentTest.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/source/NoOpTimestampsAndWatermarks.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/source/ProgressiveTimestampsAndWatermarks.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/source/TimestampsAndWatermarks.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/source/WatermarkToDataOutput.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorAlignmentTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/MultipleInputStreamTaskTest.java
This PR accounts for idleness when reporting the last watermark status for the alignment purposes.
Added tests for source operators and coordinators. …
=> [FLINK-25982] Support idleness with watermark alignment

flink-python/pyflink/datastream/tests/test_stream_execution_environment_completeness.py, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/LocalStreamEnvironment.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java, flink-streaming-scala/src/test/scala/org/apache/flink/streaming/api/scala/StreamingScalaAPICompletenessTest.scala
The check of areExplicitEnvironmentsAllowed in the StreamExecutionEnvironment should not depend on the ExecutionEnvironment
- Rebuild the check that only depends on StreamExecutionEnvironment itself.
This change is already covered by existing tests, such as LocalStreamEnvironmentITCase. …
=> [FLINK-25906][streaming] check explicit env allowed on StreamExecutionEnvironment own.

flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/runtime/SavepointEnvironment.java, flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/HighAvailabilityServicesUtils.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/tasks/TaskOperatorEventGateway.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMasterOperatorEventGateway.java, flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/CoordinationRequestHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/rpc/RpcTaskOperatorEventGateway.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/utils/TestingJobMasterGateway.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/CoordinatorEventsExactlyOnceITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorOperatorEventHandlingTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/NoOpTaskOperatorEventGateway.java
Currently, the communitcation between Operator and Coordiator is sigle-way. That means, after Operator sending a message to Coordiator, it can't wait to get the response message. In some senarios, the Operator may need to retrieve some information stored in the Coordinator. Thus, it would be great if we can have a two-way communication.
- Add `sendRequestToCoordinator(..)` interface to `TaskOperatorEventGateway` which accepts a request and returns a response future. The `TaskOperatorEventGateway` can be obtained by opereator used to communicate with coordinator.  
- Add `sendRequestToCoordinator` iterface to `JobMasterOperatorEventGateway` as the RPC method for Task to JM. JobMaster implement the interface to handover the request to correspond OperatorCoordinator. 
- Users' …
=> [FLINK-26077][runtime] Support operators send request to Coordinator and return a response

docs/content.zh/docs/deployment/resource-providers/native_kubernetes.md, docs/content.zh/docs/deployment/resource-providers/standalone/overview.md, docs/content.zh/docs/deployment/resource-providers/yarn.md, docs/content.zh/docs/ops/debugging/debugging_classloading.md, docs/content/docs/deployment/resource-providers/native_kubernetes.md, docs/content/docs/deployment/resource-providers/standalone/overview.md, docs/content/docs/deployment/resource-providers/yarn.md, docs/content/docs/ops/debugging/debugging_classloading.md
Document how to use the usrlib to load code in the user code class loader
272b759c65511b88aab0cc322b38033e89f9f945 Document how to use the usrlib to load code in the user code class loader
docs, no tests.
=> [FLINK-25053][docs] Document how to use the usrlib to load code in the user code class loader

flink-core/src/main/java/org/apache/flink/core/fs/FileSystem.java, flink-filesystems/flink-s3-fs-base/pom.xml, flink-filesystems/flink-s3-fs-base/src/test/java/org/apache/flink/fs/s3/common/HAJobRunOnMinioS3StoreITCase.java, flink-filesystems/flink-s3-fs-base/src/test/java/org/apache/flink/fs/s3/common/MinioTestContainer.java, flink-filesystems/flink-s3-fs-base/src/test/java/org/apache/flink/fs/s3/common/MinioTestContainerTest.java, flink-filesystems/flink-s3-fs-hadoop/pom.xml, flink-filesystems/flink-s3-fs-hadoop/src/test/java/org/apache/flink/fs/s3hadoop/HAJobRunOnHadoopS3FileSystemITCase.java, flink-filesystems/flink-s3-fs-presto/pom.xml, flink-filesystems/flink-s3-fs-presto/src/test/java/org/apache/flink/fs/s3presto/HAJobRunOnPrestoS3FileSystemITCase.java, flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/FileSystemJobResultStore.java, flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/AbstractHAJobRunITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/FileSystemJobResultStoreTestInternal.java, flink-test-utils-parent/flink-test-utils-junit/pom.xml, flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/core/testutils/TestContainerExtension.java, flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/util/DockerImageVersions.java
`FileSystem` implementations based on object stores like S3 do not support directories. `FileSystem.getFileStatus` fails with a `FileNotFoundException` in such a case. This also happens despite the fact that `FileSystem.mkdirs` doesn't fail.
Additionally, I created FLINK-26061 as a follow-up to cover the inconsistency of the `FileSystem` contract.
* Removes directory check from `FileSystemJobResultStore` since it's actually obsolete
* Adds MinioTestContainer to test the change
* A ITCase was added that runs a job with HA enabled and backed by S3 using the newly added Minio TestContainer
* `MinioTestContainerTest` was added to test rudimentary functionality of the `MinioTestContainer` …
=> [FLINK-26015] Fixes object store bug

flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/cleanup/CheckpointResourcesCleanupRunner.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ArchivedExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/factories/DefaultJobMasterServiceProcessFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ArchivedExecutionGraphTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/DefaultJobMasterServiceProcessTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterServiceLeadershipRunnerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/TestingJobManagerRunner.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/factories/TestingJobMasterServiceProcessFactory.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/factories/TestingJobMasterServiceProcessFactoryOld.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/ExecutionGraphInfoTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/CreatedTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/CreatingExecutionGraphTest.java
This PR serves as a collection of minor changes that didn't make it in other PRs (due to being forgotten or for the purpose of not spoiling the diff of these PRs too much)
* FLINK-25973: Renaming of the `ArchivedExecutionGraph.createFromInitializingJob` since its purpose changed. It's now reflecting what it does not where it is used.
* FLINK-25978: Removal of obsolete tests in `DispatcherTest`. Check the commit message to see what tests are there to cover this corresponding code paths.
* FLINK-26017: Adding a log message for marking a job as dirty.
No tests were added or updated to cover these changes since there are basic refactorings, removals, or only-log-message-related. …
=> [FLINK-25973][FLINK-25978][FLINK-26017] Applies minor code changes that didn't make it in any of the other JRS-related PRS

flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/DefaultJobManagerRunnerRegistry.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/JobManagerRunnerRegistry.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/OnMainThreadJobManagerRunnerRegistry.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/cleanup/DefaultResourceCleaner.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/cleanup/DispatcherResourceCleanerFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/cleanup/GloballyCleanableResource.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/cleanup/LocallyCleanableResource.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherCleanupITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/TestingJobManagerRunnerRegistry.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/cleanup/DispatcherResourceCleanerFactoryTest.java
I missed adding the `GloballyCleanableResource` to `JobManagerMetricGroup` and adding it to the `DispatcherResourceCleanerFactory` under global cleanup resources. This would cause the `JobManagerMetricGroup` not being cleaned up after a global cleanup.
* Removes `GloballyCleanableResource` interface from `JobManagerRunnerRegistry`
* Creates utility method in `DispatcherResourceCleanerFactory` converting a local cleanup to a global cleanup and uses it for the `JobManagerRunnerRegistry`
* Adds `JobManagerMetricGroup` to `DispatcherResourceCleanerFactory`'s `ResourceCleaner` instantiation for global cleanup
* The corresponding tests `DispatcherResourceCleanerFactory` was updated to cover the functionality …
=> [FLINK-26117] Adds GloballyCleanableResource to JobManagerMetricGroup

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/co/IntervalJoinOperator.java
Condition 'currentWatermark != Long.MIN_VALUE' covered by subsequent condition 'timestamp < currentWatermark' 
org.apache.flink.streaming.api.operators.co.IntervalJoinOperator#isLate
```java
private boolean isLate(long timestamp) {
long currentWatermark = internalTimerService.currentWatermark();
return currentWatermark != Long.MIN_VALUE && timestamp < currentWatermark;
} 
```
if currentWatermark == Long.MIN_VALUE, timestamp < currentWatermark it's also return false, so condition currentWatermark != Long.MIN_VALUE is unnecessary
We can use the following code directly
```java
private boolean isLate(long timestamp) {
long currentWatermark = internalTimerService.currentWatermark();
return timestamp < currentWatermark;
} 
```
remove unnecessary condition
This change is already covered by …
=> [FLINK-25980][datastream] remove unnecessary condition

docs/content/docs/deployment/resource-providers/standalone/docker.md
This change improves the documentatino of running Flink using docker-compose. In particular, it adds an example using the SQL Client.
- add example for running a session cluster with sql-client using docker-compose 
- drop documentation of docker swarm because it has lost relevance
- restructure docker docs a bit to give the page a bit more structure
- build the docs
=> [FLINK-25532] Improve Documentation of Flink Docker-Compose

flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterStateSerializer.java
`AsyncSinkWriterStateSerializer` is annotated `@Internal`, however downstream modules need to extend this class. Therefore it should be marked `@PublicEvolving`.
- `AsyncSinkWriterStateSerializer` swtiched from `@Internal` to `@PublicEvolving` …
=> [FLINK-26119][connectors/common] AsyncSinkWriterStateSerializer to @PublicEvolving

flink-dist/src/main/resources/flink-conf.yaml, flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/flink/container/FlinkContainersBuilder.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/FlinkConfMountDecorator.java, flink-runtime/src/main/java/org/apache/flink/runtime/net/ConnectionUtils.java, flink-yarn/src/main/java/org/apache/flink/yarn/entrypoint/YarnEntrypointUtils.java
The purpose of this change is to configure Flink, by default, to bind the RPC endpoints for the TM/JM to localhost rather than an externally facing network interface, for security reasons.
This PR depends on https://github.com/apache/flink-docker/pull/103, hence the odd addition here: https://github.com/apache/flink/commit/2aa4a2360b8e89744bb4f97f43f3a645c0eb4681#diff-f61beaac8a23a775d8b61a4e8348998c219a3ea080ff6a0ef14fdb088fd27b16R51 which will be removed if/when that PR is merged.
- *Bound the JobManager and TaskManager host-addresses in flink-conf.yaml to localhost*
- The runtime …
=> [FLINK-24474] Bind Jobmanager and Taskmanager RPC host addresses to localhost by default

flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/PulsarSourceITCase.java
Temporarily disable scale up/down tests to unblock CI.
=> [FLINK-26177][tests] Disable PulsarSourceITCase rescaling tests temporarily

docs/content.zh/docs/ops/state/state_backends.md, docs/content/docs/ops/state/state_backends.md, flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogStateBackend.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/utils/LegacyStatefulJobSavepointMigrationITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/utils/StatefulJobSavepointMigrationITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/utils/StatefulJobWBroadcastStateMigrationITCase.java, flink-tests/src/test/java/org/apache/flink/test/migration/TypeSerializerSnapshotMigrationITCase.java, flink-tests/src/test/java/org/apache/flink/test/state/ChangelogCompatibilityITCase.java, flink-tests/src/test/java/org/apache/flink/test/state/operator/restore/AbstractOperatorRestoreTestBase.java, flink-tests/src/test/java/org/apache/flink/test/util/TestUtils.java, flink-tests/src/test/scala/org/apache/flink/api/scala/migration/StatefulJobSavepointMigrationITCase.scala, flink-tests/src/test/scala/org/apache/flink/api/scala/migration/StatefulJobWBroadcastStateMigrationITCase.scala
```
Private state of non-changelog checkpoints is not registered
with the SharedStateRegistry on recovery.
Therefore, after recovering in CLAIM mode it will be discarded
as soon as the initial checkpoint is subsumed.
This change disallows recovery by checking handle types during
Changelog backend creation.
```
Added `ChangelogCompatibilityITCase`. …
=> [FLINK-26079][state/changelog] Disallow recovery from non-changelog checkpoints

flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriter.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterTest.java
Add support for `AsyncSink` to downscale with state. `AsyncSinkWriter` can be restored from multiple `BufferedRequestState`
- `AsyncSinkWriter` now handles multiple `BufferedRequestState`
- Added defaults to test `AsyncSinkWriter` to reduce complexity of test (in separate commit)
- `AsyncSinkWriterTest::testRestoreFromMultipleStates`
- The serializers: yes (state serializer) …
=> [FLINK-26118][connectors/common] Add support for AsyncSink to downscale with state

flink-rpc/flink-rpc-akka/pom.xml, flink-rpc/flink-rpc-akka/src/main/resources/META-INF/NOTICE, flink-rpc/flink-rpc-akka/src/main/resources/META-INF/licenses/LICENSE.scala
Unused dependency. It was used in the past when we had actor implementations in Scala and accidentally carried it forward.
=> [FLINK-26189][build] Remove bundling of grizzled-slf4j from rpc-akka

flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/pom.xml, flink-test-utils-parent/flink-connector-test-utils/pom.xml
This pull request remove building a separate jar for the `flink-connector-test-utils` module.
- Remove building a separate jar for `flink-connector-test-utils` module
- `flink-end-to-end-tests` uses the normal jar
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper:no
=> [FLINK-25289][hotfix] use the normal jar in flink-end-to-end-tests instead of a separate one

flink-connectors/flink-connector-elasticsearch-base/pom.xml, flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/testutils/ElasticsearchContainerUtil.java, flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkITCase.java, flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch6/ElasticsearchSinkITCase.java, flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkITCase.java, flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch7/ElasticsearchSinkITCase.java
To get to the root cause of FLINK-25698 and FLINK-26111 we need to retrieve the logs from Elasticsearch itself to do any meaningful analysis.
- Introduced a utility class to create Elasticsearch containers that pass log output to the tests logger
This change is already covered by existing tests, such as Elasticsearch IT Cases
- The S3 file …
=> [FLINK-25698][connectors/elasticsearch] Enable logging for Elasticsearch containers

flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/FlinkKafkaInternalProducerITCase.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaWriterITCase.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceBuilderTest.java
The tests in the Kafka connector are mixing different versions of junit together, which prevents the `TestLoggerExtension` / the `TestLogger` class from working properly. This makes debugging test instabilities very difficult.
- change Jupiter tests to use `TestLoggerExtension`
- change Junit 4 tests to use `TestLogger`
This change is already covered by existing tests, such as the ones modified. …
=> [FLINK-26195][connectors/kafka] hotfix logging issues due to mixed junit versions

flink-end-to-end-tests/flink-stream-state-ttl-test/src/main/java/org/apache/flink/streaming/tests/StubStateBackend.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/StateBackend.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsStateBackend.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/hashmap/HashMapStateBackend.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/memory/MemoryStateBackend.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/EmbeddedRocksDBStateBackend.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBStateBackend.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/SavepointFormatITCase.java, flink-tests/src/test/java/org/apache/flink/test/state/ChangelogCompatibilityITCase.java
Depending on the Changelog materialization interval, `SavepointFormatITCase`
might fail if IncrementalRemoteKeyedStateHandle is included.
The immediate reason is that shared state isn't registered for savepoints;
therefore, `PlaceholderStreamStateHandle`s are not replaced with the actual state.
At a higher level, NATIVE savepoints are not supported by changelog and should not be tested.
This PR
1) adds validation in `StreamTask` to prevent triggering NATIVE savepoints (similar to NO_CLAIM)
2) exlucdes the combination from `SavepointFormatITCase` …
=> [FLINK-26165][tests] Don't test NATIVE savepoints with Changelog enabled

flink-end-to-end-tests/flink-elasticsearch6-test/src/main/java/org/apache/flink/streaming/tests/Elasticsearch6SinkExample.java, flink-end-to-end-tests/flink-elasticsearch7-test/src/main/java/org/apache/flink/streaming/tests/Elasticsearch7SinkExample.java
We want to update the Elasticsearch E2E Tests to use the new unified Sink API instead of the old one.
- Updated ElasticsearchXExample for ES6&7
- Minor code cleanup
This change is already covered by existing tests, such as E2E Tests (`test_streaming_elasticsearch.sh`)
- Dependencies (does it add or upgrade a dependency): (yes / **no***) …
=> [FLINK-26185] Update Elasticsarch E2E Tests to use new unified Sink interface

flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Canceling.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/CreatingExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Executing.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Failing.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/FailureResult.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/FailureResultUtil.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Restarting.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StateTransitions.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StateWithExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StopWithSavepoint.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/exceptionhistory/ExceptionHistoryEntry.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/exceptionhistory/RootExceptionHistoryEntry.java, flink-runtime/src/main/java/org/apache/flink/runtime/util/BoundedFIFOQueue.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/CancelingTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/CreatingExecutionGraphTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/ExecutingTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/FailingTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/MockStateWithExecutionGraphContext.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/RestartingTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StateTrackingMockExecutionGraph.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StateWithExecutionGraphTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StopWithSavepointTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/exceptionhistory/ExceptionHistoryEntryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/exceptionhistory/TestingAccessExecution.java
https://issues.apache.org/jira/browse/FLINK-21439
Add exception history to Adaptive Scheduler
- Add convenience methods to ExecutionGraph
- AdaptiveSchedulerTest#testExceptionHistoryWithGlobalFailure
- AdaptiveSchedulerTest#testExceptionHistoryWithTaskFailure
- AdaptiveSchedulerTest#testExceptionHistoryWithTaskConcurrentFailure …
=> [FLINK-21439][runtime] Exception history adaptive scheduler

flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/ChangelogStateBackendHandle.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/changelog/ChangelogStateBackendHandleTest.java
In `ChangelogStateBackendHandleImpl` constructor, `materializationID` and `persistedSizeOfThisCheckpoint` are mixed up.
Added `ChangelogStateBackendHandleTest`
=> [FLINK-26231][state/changelog] Fix ChangelogStateBackendHandle constructor

flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroFileFormatFactory.java
As discussed with @slinkydeveloper in #18657 , this hotfix add comments to explain why current implementation of projection pushdown works for avro bulk format.
- Add comments to explain why projection pushdown works for avro bulk format …
=> [hotfix][avro] Add comments to explain why projection pushdown works for avro bulk format

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/CodeGeneratorContext.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CodeSplitITCase.scala
Although we've introduced a dedicated code splitter module in FLINK-23007 there are still some corner cases. For example, current code splitter cannot handle long constructor code.
`IN` filters with a constant set will generate an operator which constructs the set in the class constructor, so for a large IN filter its generator code may become too long to be compiled. This PR fixes this issue by moving the code for set constructing to a dedicated method.
I'm not going to handle long constructor code for the code splitter because it is sort of hard to pick out which part of the constructor code can be split out. For example, `final` class members must be assigned in the constructor, not in other methods, so we just can't move all constructor code into another method.
- Fix bug: generated …
=> [FLINK-25491][table-planner] Fix bug: generated code for a large IN filter can't be compiled

flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/CodeGenUtils.scala, flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala, flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/expressions/ScalarOperatorsTest.scala, flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/functions/NumericUtils.java
Currently generated Java code for equality checking does not consider boxed Java types. This PR fixes this issue.
- Boxed numeric type should be considered when generating code for equality checking
=> [FLINK-25227][table] Boxed numeric type should be considered when generating code for equality checking

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/FileSystemLookupFunction.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveLookupJoinITCase.java
*Fix lookup join bug when reading hive columnar storage tables.  *
- *When building the cache, generate cache key after copy the RowData from columnar RowData in case of different key reference the same memory*
*Unit tests*
- *Add test in [HiveLookupJoinITCase.java] to test lookup join with columnar table and make sure there is enough records to make sure the ParquetVectorizedInputFormat will read at least two batch to reproduce the error* …
=> [FLINK-26016][hive] Fix FileSystemLookupFunction can't build correct cache when reading columnar storage table

flink-core/src/main/java/org/apache/flink/api/common/time/Deadline.java, flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/ComponentClosingUtils.java, flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/RecreateOnResetOperatorCoordinator.java, flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/ExecutorNotifier.java, flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinator.java, flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContext.java, flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorProvider.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/ComponentClosingUtilsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/ExecutorNotifierTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorTestBase.java, flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/core/testutils/ManuallyTriggeredScheduledExecutorService.java
Currently the closing sequence of the `OperatorCoordinator` does not swallow the exceptions thrown in the middle. So when exception is thrown in the middle, the rest of the closing sequence will be skipped. This patch makes the closing sequence of `OperatorCoordinator` more robust by swallowing the exception thrown in the middle, and also retries interrupting the threads in case the the closing sequence is blocked multiple times.
Some of the methods, such as `closeQuietly()`, in the `IOUtils` seem better to be put in `ComponentClosingUtils`. Will do that in a separate PR. 
0dfe9b7 Add util methods to shutdown executor services.
1cb9f56 Make OperatorCoordinator closure more robust.
This change added the following unit tests:
1. `ComponentClosingUtilsTest` class.
2. …
=> [FLINK-24607] Make OperatorCoordinator closing sequence more robust.

flink-end-to-end-tests/flink-end-to-end-tests-pulsar/pom.xml, flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/PulsarSourceOrderedE2ECase.java, flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/common/FlinkContainerWithPulsarEnvironment.java
We exclude the jaxb-api in `pulsar-client-all` after upgrading to latest Pulsar. This would cause the class not found issue on Java 11. The JAXB APIs are considered to be Java EE APIs and therefore are no longer contained on the default classpath in Java SE 9. In Java 11, they are completely removed from the JDK.
- Add the jaxb-api dependency.
- Disable the `PulsarSourceOrderedE2ECase` test on Java 11 for direct buffer memory error.
This change is already covered by existing tests, such as `PulsarSourceUnorderedE2ECase`. …
=> [FLINK-26210][connector/pulsar] Fix the jaxb-api missing for Pulsar connector on Java 11

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/GlobalCommitterOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperatorFactory.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperatorFactory.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManagerImpl.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollector.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/translators/SinkTransformationTranslator.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/connector/sink2/CommittableSummaryAssert.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperatorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperatorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManagerImplTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorTest.java
Before this commit the SinkWriter and Committer operators emitted
committables on endInput. This was troublesome because by doing so the
checkpointId was set to effectively null/Long.MAX_VALUE because
the emission was not part of any checkpoint. With the completion of
FLIP-143 all jobs in streaming mode have a final checkpoint when they
transition to finish so we can rely on the normal checkpoint mechanism
and only need endInput for the batch execution.
- CommitterOperator **only** emit on notifyCheckpointComplete in streaming mode
- GlobalCommitter **only** emit on notifyCheckpointComplete in streaming mode
- SinkWriter **only** emit on preSnapshotBarrier  in streaming mode
- Adjusted existing tests to verify the behaviour
- KafkaSinkITCase is now stable (ran 20 times locally without …
=> [FLINK-25941][streaming] Only emit committables with Long.MAX_VALUE as checkpoint id in batch mode

flink-core/src/main/java/org/apache/flink/core/execution/JobClient.java
=> [FLINK-26299] Reintroduce old JobClient#triggerSavepoint,stopWithSavepoint methods

flink-core/src/main/java/org/apache/flink/api/common/eventtime/WatermarksWithWatermarkAlignment.java
Change the scope of `WatermarksWithWatermarkAlignment` so that it does not pop up in autocompletion.
=> [hotfix] Change the scope of WatermarksWithWatermarkAlignment

flink-runtime/src/test/java/org/apache/flink/runtime/leaderretrieval/ZooKeeperLeaderRetrievalConnectionHandlingTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/zookeeper/ZooKeeperExtension.java
We experienced some unstable ZooKeeper tests. This test belongs to the same group. See further details on the investigation effort in FLINK-26121.
* Refactors test to use utility method for common functionality:
* Instantiating the `QueueLeaderElectionListener`
* Closing the driver
* Add a method for cleaning up the queue after the test passed
* Nothing added to test the behavior …
=> [FLINK-26121] Adds queue cleanup to `ZooKeeperLeaderRetrievalConnectionHandlingTest`

docs/content.zh/docs/connectors/table/hive/hive_read_write.md, docs/content/docs/connectors/table/hive/hive_read_write.md
`Time interval unit label 'm' does not match any of the recognized units: DAYS: (d | day | days), HOURS: (h | hour | hours), MINUTES: (min | minute | minutes), SECONDS: (s | sec | secs | second | seconds), MILLISECONDS: (ms | milli | millis | millisecond | milliseconds), MICROSECONDS: (µs | micro | micros | microsecond | microseconds), NANOSECONDS: (ns | nano | nanos | nanosecond | nanoseconds)`
‘1 m’ is misleading when we used, which is not  correct.
- Does this pull request introduce a new feature? (yes )
- If yes, how is the feature documented? ( docs / JavaDocs )
=> [FLINK-26320][DOC]update hive doc for 1 m->1 min

docs/content/docs/connectors/datastream/formats/csv.md
This PR adds documentation for the DataStream CSV format.
This change is a trivial addition to the documentation without any test coverage.
=> [FLINK-26342][docs][formats] Add DataStream documentation for the CSV format

flink-clients/src/main/java/org/apache/flink/client/cli/CliFrontendParser.java, flink-clients/src/test/java/org/apache/flink/client/cli/CliFrontendRunTest.java
Add shorthand option for restoreMode
```
-rm,--restoreMode <arg>                    Defines how should we restore
from the given savepoint.
Supported options: [claim -
claim ownership of the savepoint
and delete once it is subsumed,
no_claim (default) - do not
claim ownership, the first
checkpoint will not reuse any
files from the restored one,
legacy - the old behaviour, do
not assume ownership of the
savepoint files, but can reuse
some shared files.
``` …
=> [FLINK-26354] -restoreMode should be --restoreMode and should have a shorthand

flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/testutils/KafkaUtil.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaInternalProducerITCase.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaProducerITCase.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaConsumerTestBase.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestBase.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestEnvironment.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestEnvironmentImpl.java, flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/util/DockerImageVersions.java
This pull request uses KafkaContainer to rewrite the existing unstable KafkaTestEnvironment, which was previously based on in-memory Kafka. 
- Reimplement KafkaTestEnvironment with KafkaContainer
This change is already covered by all existing Kafka connector tests. …
=> [FLINK-25249][connector/kafka] Reimplement KafkaTestEnvironment with KafkaContainer

flink-runtime/src/main/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStore.java, flink-runtime/src/test/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStoreTest.java
This inconsistency was introduced by `c3a6b51` as part of changes done for FLINK-19543. It should be, anyway, fixed for consistency reasons.
This issue never appeared because of the following reasons:
* getAllAndLock is only called by the CompletedCheckpoint
recovery which happens during the recovery of a job (i.e.
after failover)
* the removal happens through releaseAndTryRemove which can
be called in the following places:
* through DefaultCompletedCheckpointStore.addCheckpointAndSubsumeOldestOne
That happens after a job is already recovered and running
* through DefaultCompletedCheckpointStore.shutdown
...where it's only called if the job reached a
globally-terminal state (i.e. it's not subject to
job recovery)
* through DefaultJobGraphStore.globalCleanupAsync
...which is also only …
=> [FLINK-26285] Fixes an inconsistency 

flink-runtime/src/main/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStore.java, flink-runtime/src/test/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStoreTest.java
This serves as a 1.13 backport for PR #18919 
The cherry-pick only caused some minor import conflict due to the upgrade from `curator4` to `curator5` and `guava18` to `guava30`
See the parent PR's description for further details
=> [BP-1.13][FLINK-26285] Fixes an inconsistency

flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/avro/AvroParquetReaders.java, flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/avro/AvroParquetRecordFormat.java, flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/avro/AvroParquetWriters.java, flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/avro/ParquetAvroWriters.java, flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/avro/AvroParquetRecordFormatTest.java
Add FLINK API annotations to public classes.
- add annotations
- optimize some javadoc
This change is a trivial  code cleanup without any test coverage.
=> [FLINK-26357][format] add FLINK API annotations

flink-runtime/src/main/java/org/apache/flink/runtime/persistence/StateHandleStore.java, flink-runtime/src/main/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStore.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/ZooKeeperCompletedCheckpointStoreITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/persistence/TestingLongStateHandleHelper.java, flink-runtime/src/test/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStoreTest.java
The `ZooKeeperStateHandleStore` cleanup is not repeatable: The ZK node is deleted removing the `StateHandle` metadata before discarding the `StateHandle` itself. If the deletion of the `StateHandle` fails, there is no way to determine the location for a subsequent cleanup anymore.
We fixed this by introducing another child node collecting all the lock child nodes. A state node now has the following structure:
* `/<name>` - root node referencing the actual `StateHandle`
* `/<name>/locks` - The locks child which contains all the lock nodes. This child node is `PERSISTENT` like the parent node to prevent the node going away automatically after all connections are cleared. We want to do the cleanup explicitly.
* `/<name>/locks/<lock-child>` - A node referencing to a single ZK connection. This …
=> [FLINK-26284] Introduces mark-for-deletion state in ZooKeeperStateHandleStore

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/NettyShuffleServiceFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/NettyConnectionManager.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/SharedPoolNettyShuffleServiceFactory.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java
Tests that extend from UnalignedCheckpointTestBase create a lot of
MiniClusters. E.g. the rescale it case creates 72 tests * 2 clusters
(pre & post rescale). Direct buffers allocated by netty are freed during
the GC.
At the same time Flink uses PooledBufferAllocator, where we return used
buffers earlier and we do not need to wait for GC to kick in. The idea
to make the test more stable is to reuse a single NettyBufferPool for
all clusters that are started in those tests. That way we can reuse
buffers that were previously allocated and we do not need to wait until
they are freed.
Lastly as a note. This should not be an issue in production setups, as
we do not start multiple shuffle environments in a single JVM process
(TM).
???
- Dependencies (does it add or upgrade a dependency): (yes / …
=> [FLINK-25026] UnalignedCheckpointRescaleITCase.shouldRescaleUnalignedCheckpoint fails on AZP

docs/content.zh/docs/deployment/config.md, docs/content/docs/deployment/config.md, docs/layouts/shortcodes/generated/all_jobmanager_section.html, docs/layouts/shortcodes/generated/cleanup_configuration.html, docs/layouts/shortcodes/generated/exponential_delay_cleanup_strategy_configuration.html, docs/layouts/shortcodes/generated/fixed_delay_cleanup_strategy_configuration.html, docs/layouts/shortcodes/generated/job_manager_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/CleanupOptions.java, flink-core/src/main/java/org/apache/flink/configuration/JobManagerOptions.java, flink-core/src/main/java/org/apache/flink/configuration/RestartStrategyOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/cleanup/CleanupRetryStrategyFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/cleanup/DispatcherResourceCleanerFactory.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/cleanup/CleanupRetryStrategyFactoryTest.java
The goal is to align the user experience for retry functionality. I created a follow-up ticket FLINK-26359 to cover the actual alignment in the code.
* Introduced `CleanupOptions` similar to `RestartOptions` to give a consistent user experience.
* Adds `CleanupRetryStrategyFactory` covering the configuration extraction to create the right `RetryStrategy` instance
* Updated docs
* `CleanupRetryStrategyFactoryTest` is added to cover all different options …
=> [FLINK-26331] Make cleanup retry strategy configurable similar to how the task restart is configurable

docs/content.zh/docs/concepts/glossary.md, docs/content.zh/docs/deployment/ha/overview.md, docs/content.zh/docs/deployment/overview.md, docs/content/docs/concepts/glossary.md, docs/content/docs/deployment/ha/overview.md, docs/content/docs/deployment/overview.md
*Adds some extra documentation for the new JobResultStore (used for persisting globally terminated job results) and the new repeatable resource cleanup behavior.*
- *Updated documentation to include description of JobResultStore and repeatable resource cleanup.*
- code cleanup without any test coverage. …
=> [FLINK-26296] Add missing documentation for JobResultStore and repeatable resource cleanup strategy

docs/content.zh/docs/dev/datastream/fault-tolerance/checkpointing.md, docs/content.zh/docs/ops/state/checkpoints.md, docs/content/docs/dev/datastream/fault-tolerance/checkpointing.md, docs/content/docs/ops/state/checkpoints.md
Trivial docs fix: `enableExternalizedCheckpoints` was deprecated in favor of `setExternalizedCheckpointCleanup`.
=> [hotfix] Fix deprecated method call in the docs

flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceLegacyITCase.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaITCase.java
The CI failures from FLINK-26387 and FLINK-26393 are blocking many people. To prevent failure of almost all builds while we are looking for the root cause we want to disable the `testBrokerFailure` tests for now.
- disabled `testBrokerFailure` in `KafkaSourceLegacyITCase` and `KafkaITCase` …
=> [FLINK-26387][connectors/kafka] Disable testBrokerFailure in ITCase tests

flink-runtime-web/web-dashboard/package-lock.json, flink-runtime-web/web-dashboard/package.json
* This PR updates two Javascript packages `karma` and `follow-redirects` to a later version to address security findings in those. To avoid unnecessary PRs, I've created one PR to update both of them at the same time, via two separate commits. 
* 76e29ad6a7da6add1acab5d57813986b61e9ea80 updates karma
* f2dfe92d769bdbba5ca9407f35bed8505ae71cd3 updates follow-redirects …
=> [FLINK-26430][FLINK-26429][runtime-web] Bump Karma and follow-redirects to address security findings

tools/ci/log4j.properties
1.14 backport of PR #18846 
No conflicts observed during cherry-pick.
=> [BP-1.14][FLINK-26223] Updates log4j configuration

tools/ci/log4j.properties
1.13 backport of PR #18846 
No conflicts observed during cherry-pick.
=> [BP-1.13][FLINK-26223] Updates log4j configuration

flink-clients/src/main/java/org/apache/flink/client/cli/CliFrontendParser.java, flink-clients/src/test/java/org/apache/flink/client/cli/CliFrontendSavepointTest.java, flink-clients/src/test/java/org/apache/flink/client/cli/CliFrontendStopWithSavepointTest.java
```
Action "savepoint" triggers savepoints for a running job or disposes existing ones.
Syntax: savepoint [OPTIONS] <Job ID> [<target directory>]
"savepoint" action options:
-d,--dispose <arg>       Path of savepoint to dispose.
-j,--jarfile <jarfile>   Flink program JAR file.
-t,--type <arg>          Describes the binary format in which a savepoint
should be taken. Supported options: [canonical - a
common format for all state backends, allow for
changing state backends, native = a specific
format for the chosen state backend, might be
faster to take and restore from.
```
```
Action "stop" stops a running program with a savepoint (streaming jobs only).
Syntax: stop [OPTIONS] <Job ID>
"stop" action options:
-d,--drain                           Send MAX_WATERMARK before taking the
savepoint …
```
=> [FLINK-26353] flink stop --help does not list --type option

flink-dist/src/main/resources/flink-conf.yaml, flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/flink/container/FlinkContainersBuilder.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/FlinkConfMountDecorator.java, flink-yarn/src/main/java/org/apache/flink/yarn/entrypoint/YarnEntrypointUtils.java
See https://issues.apache.org/jira/browse/FLINK-24474
As we have changed the `taskmanager.bind-host` to `localhost`, we also need to set the `taskmanager.host` (the advertised address) to `localhost`.
=> [FLINK-24474] set default for taskmanager.host

flink-runtime-web/web-dashboard/src/@types/d3-tip/index.d.ts, flink-runtime-web/web-dashboard/src/app/share/common/editor/auto-resize.directive.ts, flink-runtime-web/web-dashboard/src/app/share/common/editor/editor-config.ts, flink-runtime-web/web-dashboard/src/app/utils/strong-type.ts
Adds missing license headers to WebUI source files so that rat-plugin can be upgraded to 0.13. Unblocks FLINK-26302 (#18881)
- Adds missing license headers to WebUI source files …
=> [FLINK-26352][runtime-web] Add missing license headers to WebUI source files

flink-end-to-end-tests/flink-metrics-availability-test/src/test/java/org/apache/flink/metrics/tests/MetricsAvailabilityITCase.java
1.14 backport for parent PR #18952 . No conflicts observed during cherry-picking:
```
$ git cherry-pick 6e7d5dbd1bca3c4435c121d3216bd13a5a17e095
```
=> [BP-1.14][FLINK-26407][end-to-end-tests] Increase timeouts for MetricsAvailabilityITCase.

flink-end-to-end-tests/flink-metrics-availability-test/src/test/java/org/apache/flink/metrics/tests/MetricsAvailabilityITCase.java
1.13 backport for parent PR #18952 . No conflicts observed during cherry-picking:
```
$ git cherry-pick 6e7d5dbd1bca3c4435c121d3216bd13a5a17e095
```
=> [BP-1.13][FLINK-26407][end-to-end-tests] Increase timeouts for MetricsAvailabilityITCase.

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointFailureManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointStatsCounts.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointStatsTracker.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/PendingCheckpoint.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointStatsCountsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointStatsTrackerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/PendingCheckpointTest.java
Improve logic after checkpoint trigger fails
1. show root cause if trigger checkpoint fails before creating PendingCheckpoint
2. Increase numberOfFailedCheckpoints if trigger checkpoint fails before creating PendingCheckpoint
3. initializeCheckpointLocation after create PendingCheckpoint
- *Add IOExceptionCheckpointIDCounter to check if the numberOfFailedCheckpoints can be increased when getCheckpointId throw IOException*
- *Check if create PendingCheckpoint when initializeCheckpointLocation throw IOException*
- *Check incrementFailedCheckpointsWithoutInProgress in CheckpointStatsCountsTest and CheckpointStatsTrackerTest* …
=> [FLINK-26049][checkpoint] Improve logic after checkpoint trigger fails

docs/content.zh/docs/dev/table/sql/show.md, docs/content/docs/dev/table/sql/show.md, flink-table/flink-sql-client/src/test/resources/sql/catalog_database.q, flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl, flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/dql/SqlShowTables.java, flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/TableEnvironment.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ShowTablesOperation.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlToOperationConverter.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlToOperationConverterTest.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/TableEnvironmentTest.scala
Support enhanced `show tables` syntax like `show tables from catalog1.db1 like 't%'`
* SHOW TABLES [ ( FROM | IN ) [catalog.]db ] [ [NOT] LIKE regex_pattern ]
flink-table/flink-sql-client/src/test/resources/sql/catalog_database.q
- If yes, how is the feature documented? yes
=> [FLINK-25631][table] Support enhanced `show tables` syntax

docs/content.zh/docs/ops/metrics.md, docs/content/docs/ops/metrics.md, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointStatsTracker.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointStatsTrackerTest.java
After [FLINK-25557](https://issues.apache.org/jira/browse/FLINK-25557), the meaning of previous metric lastCheckpointSize has been changed to last completed full checkpoint size. We could introduce another metric `lastCheckpointFullSize` to represent the meaning of last completed full checkpoint size and let lastCheckpointSize stay as it was.
- Make the meaning of lastCheckpointSize stay as before.
- Introduce a new `lastCheckpointFullSize`
`CheckpointStatsTrackerTest` …
=> [FLINK-26464][metrics] Make the meaning of lastCheckpointSize stay as before

flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaWriter.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaSinkITCase.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaWriterITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/KafkaSinkE2ECase.java, flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/metrics/groups/SinkWriterMetricGroup.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricNames.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/InternalSinkWriterMetricGroup.java, flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/testsuites/SinkTestSuiteBase.java, flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/SinkMetricsITCase.java
We found that the new sink v2 interface will have a wrong numRecordsOut metric for the sink writers. We send a fixed number of records to the source, but the numRecordsOut of the sink continues to increase by the time.
The problem is that both the `SinkWriterOperator` and the `KafkaWriter` are using the same counter metric for counting the outgoing records. Same records sent by the `SinkWriterOperator` to the post topology and written by the `KafkaWriter` to the downstream system will be count twice in the same counter metric.
-  define new counters in `SinkWriterMetricGroup`
-  replace the shared counter used in `KafkaWriter` with new counters
-  update `KafkaWriterITCase`
-  enable `KafkaSinkITCase` and `KafkaSinkE2ECase` again …
=> [FLINK-26126][kafka] fix numRecordsOut metric error

flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/PeriodicMaterializationManager.java
When the task is cancelled, AsyncCheckpointRunnables are cancelled as well.
Cancellation exception can reach PeriodicMaterializationManager.
When the failure limit is reached, it invokes asyncExceptionHandler.handleAsyncException, which fails the job.
ChangelogITCase (FLINK-25143)
=> [FLINK-26455][state/changelog] Don't fail on materialization cancellation

flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContext.java, flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorProvider.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/MockOperatorCoordinatorContext.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContextTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorTestBase.java
Properly fail the job when `SplitEnumeratorContext.runInCoordinatorThread()` throws an exception instead of failing the whole `JobManager`.
Introduce `FailJobExceptionHandler` that calls `context.failJob()`. Call it when `SplitEnumeratorContext.runInCoordinatorThread()` throws an exception by changing `CoordinatorExecutorThreadFactory` error handler.
Introduce a new `ThreadPoolExecutor` test utility to gain access to the underlying thread and use it to wait for the handler to process the exception before asserting.
`SourceCoordinatorContextTest#testExceptionInRunnableFailsTheJob()`
- The …
=> [FLINK-23843][runtime] Properly fail the job when SplitEnumeratorContext.runInCoordinatorThread() throws an exception

pom.xml
Skips the logging of exclusions, making the plugin less verbose.
=> [FLINK-26302][build] Upgrade rat-plugin to 1.13

docs/content.zh/docs/connectors/table/overview.md, docs/content/docs/connectors/table/overview.md
* The example in table connector proctime [table connector](https://nightlies.apache.org/flink/flink-docs-master/docs/connectors/table/overview/#proctime-attributes) section has missing comma
```
CREATE TABLE MyTable (
MyField1 INT,
MyField2 STRING,
MyField3 BOOLEAN
MyField4 AS PROCTIME() -- declares a proctime attribute
) WITH (
```
* Updated example 
- The S3 file …
=> [FLINK-26099][table][connector][docs] Corrected example in proctime attribute section

flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContext.java, flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorProvider.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/MockOperatorCoordinatorContext.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContextTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorTestBase.java
This serves as a 1.14 backport of PR #18610. Only minor import conflicts during the cherry-picking of [02d9bec](https://github.com/apache/flink/commit/02d9bec4d251c09a1e75eb4d5c6edb751293c54e)
```
git cherry-pick 02d9bec4d251c09a1e75eb4d5c6edb751293c54e
```
=> [BP-1.14][FLINK-23843][runtime] Properly fail the job when SplitEnumeratorContext.runInCoordinatorThread() throws an exception.

flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContext.java, flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorProvider.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/MockOperatorCoordinatorContext.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContextTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorTestBase.java
This serves as a 1.13 backport of PR #18610. Only minor import conflicts during the cherry-picking of [02d9bec](https://github.com/apache/flink/commit/02d9bec4d251c09a1e75eb4d5c6edb751293c54e)
```
git cherry-pick 02d9bec4d251c09a1e75eb4d5c6edb751293c54e
```
=> [BP-1.13][FLINK-23843][runtime] Properly fail the job when SplitEnumeratorContext.runInCoordinatorThread() throws an exception.

docs/README.md, docs/content/docs/dev/configuration/advanced.md, docs/content/docs/dev/configuration/connector.md, docs/content/docs/dev/configuration/maven.md, docs/content/docs/dev/configuration/overview.md, docs/content/docs/dev/configuration/testing.md, docs/content/docs/dev/table/sourcesSinks.md, docs/layouts/shortcodes/artifact_gradle.html, docs/layouts/shortcodes/artifact_tabs.html
This is a followup of https://github.com/apache/flink/pull/18353
It includes improvements to the documentation for the table-planner-loader story, in several parts of the doc, and it also includes additional improvements to other related project configuration docs, such as the new `Running and packaging` and changes to the connectors page. 
Also added two new shortcodes
=> [FLINK-25129][docs] Improvements to the table-planner-loader related docs

flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/BatchingStateChangeUploadScheduler.java, flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogStorage.java, flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogWriter.java, flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/RetryingExecutor.java, flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/StateChangeFsUploader.java, flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/StateChangeUploadScheduler.java, flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/StateChangeUploader.java, flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/UploadThrottle.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/BatchingStateChangeUploadSchedulerTest.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/ChangelogStorageMetricsTest.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/FsStateChangelogWriterSqnTest.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/FsStateChangelogWriterTest.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/RetryingExecutorTest.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/TestingStateChangeUploader.java
depends on #18931
When an attempt of an already completed upload task succeeds,
the uploaded state is currently not discarded.
- BatchingStateChangeUploadSchedulerTest.testRetryOnTimeout
- RetryingExecutorTest.testDiscardOnTimeout
=> [FLINK-26485][state/changelog] Discard unnecessarily uploaded state

flink-runtime-web/web-dashboard/src/@types/d3-tip/index.d.ts
This backport for #18951 was necessary despite the rat plugin update not being backported to `release-1.14` because we still should have all `*.ts` files with the proper Apache header.
Cherry-picked from the parent #18951 :
```
$ git cherry-pick 932934aabb55a048da390ee804f4e55ab974ff2e
```
Manually verified that there are no other `*.ts` files without the Apache header in `flink-runtime-web/web-dashboard/src`:
```
find flink-runtime-web/web-dashboard/src -name "*.ts" -exec sh -c 'echo '{}'; grep -c "Licensed to the Apache Software Foundation (ASF) under one" '{} \; | grep -B1 0
``` …
=> [BP-1.14][FLINK-26352][runtime-web] Add missing license headers to WebUI source files

docs/content/docs/ops/metrics.md, flink-connectors/flink-connector-aws-kinesis-firehose/src/main/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkWriter.java, flink-connectors/flink-connector-aws-kinesis-firehose/src/test/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkWriterTest.java, flink-connectors/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/sink/KinesisStreamsSinkWriter.java, flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaWriter.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaWriterITCase.java, flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/metrics/groups/SinkWriterMetricGroup.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricNames.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/InternalSinkWriterMetricGroup.java, flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/SinkMetricsITCase.java
After introducing new metrics in SinkWriterMetricGroup that all include the word Send it makes sense to also rename the numRecordsOutErrors to the numRecordsSendErrors.
The best way would be probably to deprecate numRecordsOutError and introduce numRecordsSendError. So we can remove numRecordsOutError with 1.16.
- introduce new metric `numRecordsSendErrorsCounter`, deprecate `numRecordsOutErrorsCounter`.
- deprecate `numRecordsOutErrorsCounter`, replace it with `numRecordsSendErrorsCounter` in Kafka, Kinesis firehose, Kinesis connectors.
This change is already covered by existing tests, such as `SinkMetricsITCase`,  `KafkaWriterITCase`, `KinesisFirehoseSinkWriterTest`. …
=> [FLINK-26492][metric] deprecate umRecordsOutErrorsCounter

flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/FileSystemJobResultStore.java
The `FileSystemJobResultStore` does not close the `OutputStream` when writing the JobResult into the file. This PR fixes the issue.
* Adds try block around the `OutputStream` usage
=> [FLINK-26555][runtime] Adds closing and flushing to OutputStream

flink-core/src/test/java/org/apache/flink/core/fs/FileSystemBehaviorTestSuite.java, flink-filesystems/flink-s3-fs-base/src/main/java/org/apache/flink/fs/s3/common/AbstractS3FileSystemFactory.java, flink-filesystems/flink-s3-fs-presto/src/main/java/org/apache/flink/fs/s3presto/FlinkS3PrestoFileSystem.java, flink-filesystems/flink-s3-fs-presto/src/main/java/org/apache/flink/fs/s3presto/S3FileSystemFactory.java
We've observed a bug in the `PrestoS3FileSystem.delete` implementation where the recursive delete isn't implemented properly to handle errors (see [PrestoDB issue #17416](https://github.com/prestodb/presto/issues/17416)). This prevents `BlobStore` items to be deleted as part of a repeated cleanup.
A new `PrestoS3FileSystem` is introduced that implements the recursive delete to work around the bug for now.
* `PrestoS3FileSystem` adds recursive deletion logic that handles errors properly
* Adds tests for `exists` and `delete` to `FileSystemBehaviorTestSuite`
* The tests needed to run manually because they won't run on CI. For this, a Docker Minio container was started:
```
docker run \
-p 9000:9000 \
-p 9001:9001 \
-v /tmp/minio/data2:/data \
-e "MINIO_ROOT_USER=minio" \
-e …
```
=> [FLINK-26484][fs] FileSystem.delete is not implemented consistently

flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FileStateHandle.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/filesystem/FileStateHandleTest.java
`FileStateHandle.discardState` didn't handle cases where the `FileSystem` implementation used the return value to indicate an error during deletion. This made the cleanup logic not recognize the failure.
* Updates `FileStateHandle.discardState` implementation
* Introduces `TestingFileSystem`
* Adds tests to `FileStateHandleTest` to cover both deletion code paths. …
=> [FLINK-26450][fs] Adds error handling to FileStateHandle.discardState

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointFailureManager.java
After [FLINK-26049], all failed checkpoint would print message with `Failed to trigger checkpoint...`, this is extremely strange as most failures do not happen during the trigger phase.
We could change the inforamtion to `Failed to complete checkpoint...` as the fail to trigger exception would also print in the warning message.
Change the warning information.
- …
=> [FLINK-26550][checkpoint] Correct the information of checkpoint failure

flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/cleanup/DefaultResourceCleaner.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/cleanup/DispatcherResourceCleanerFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/FileSystemJobResultStore.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/cleanup/DefaultResourceCleanerTest.java
The retryable cleanup works but does not reveal the actual error which makes it harder to identify the error. This PR fixes it.
* `DefaultResourceCleaner.Builder` method signatures for adding cleanups are extended to also require a label that is passed. The label should be unique to make each cleanup identifyable in the logs.
* A test was added to check the uniqueness of the label
* The logging was verified manually by running the `DefaultResourceCleanerTest` methods with logging enabled …
=> [FLINK-26494][runtime] Cleanup does not reveal exceptions

docs/content/docs/dev/table/types.md, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/casting/RawToBinaryCastRule.java
This PR adds documentation for the new TRY_CAST and describes the various changes related to casting in 1.15, including a matrix of the supported cast tuples.
=> [FLINK-26125][docs][table] Add new documentation for the CAST changes in 1.15

flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogStateBackend.java, flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/PeriodicMaterializationManager.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogStateBackendTestUtils.java
Currently, all tasks perform materialization rougly at the same time.
This creates a spike in state deletion requests from JM to DFS.
That can delay new checkpoints because of how JM IO tasks are scheduled:
- every deletion is a separate task in the IO thread pool queue
- the queue is FIFO (unbounded)
- the default number of threads in the pool equals number of cores
- so the new checkpoint has to wait for an available thread to initialize its location
Note, that while the checkpoint is waiting, it's already "triggered" on JM, but not broadcasted to any TM.
This PR introduces a random delay in materialization. That delay spreads deletions more evenly. …
=> [FLINK-26306][state/changelog] Randomly offset materialization

flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/avro/AvroParquetFileReadITCase.java, flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/avro/AvroParquetRecordFormatTest.java
There was an issue while chaning the AvroParquetFileReadITCase to read reflect data from parquet file created with generic record schema. The reason is that user schema used in test is defined only for Avro GenericRecord. In order to make it support reflect record read, a namespace is required, so that the program is able to find the class to do reflection.
I have updated the user schema and add one UT to cover this case. Thanks for pointing it out.
- introduce a local User class 
- add namespace into the user schema
- add one UT to cover this scenario
This change is already covered by existing tests, such as AvroParquetRecordFormatTest. …
=> [FLINK-26349][AvroParquet][test] add test cases for reading reflect records from parquet file created with generic record schema.

flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/types/ResourceProfile.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/slotpool/DefaultDeclarativeSlotPool.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/DefaultDeclarativeSlotPoolTest.java
To allow recovered TMs to eagerly re-offer their slots we allowed the registration of slots without a matching requirement if the job is currently restarting.
All slots that the pool accepts are mapped to a certain requirement, in order to determine whether sufficient slots were received yet. If a slot is reserved for a requirement that does not coincide with the mapping the pool come up with, then the mapping and requirements are changed accordingly to ensure we still request sufficient slots.
This leads to issues with slots that were accepted without a matching requirement. Those were mapped to the actual resource profile of the slot (to fit into the book-keeping). With the above logic in place this could lead to a specific resource requirement being added, which the remaining JM …
=> [FLINK-26547][coordination] No requirement adjustments for unmatched slots

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/casting/RawToBinaryCastRule.java
Reintroducing the change removed by https://github.com/apache/flink/commit/d212b83fddb53f2ec0363b6c08cd3cabb3c02990
=> [hotfix][table-planner] RawToBinaryCastRule can fail

flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderRetrievalDriverTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingRetrievalBase.java, flink-runtime/src/test/java/org/apache/flink/runtime/leaderretrieval/SettableLeaderRetrievalServiceTest.java
There currently exists a race condition during `ZooKeeperLeaderElectionTest.testLeaderShouldBeCorrectedWhenOverwritten`, which is caused by `TestingRetrievalBase.offerToLeaderQueue` assigning a value to the base's leader, which happens because of multiple threads offering to the leader queue and this assignment is not synced.
This assignment is not necessary as `waitForNewLeader` and `waitForEmptyLeaderInformation` already assign the leader by polling the blocking queue, which `offerToLeaderQueue` adds to.
This NPE occurs consistently every 20-30 retries of the test. With this fix, I am unable to reproduce the NPE across 1000+ retries.
- *Fixed race condition caused by unsynchronized leadership assignment in TestingRetrievalBase* …
=> [FLINK-24538][runtime][tests] Fix race condition when offering information to leader event queue in TestingRetrievalBase

flink-runtime/src/main/java/org/apache/flink/runtime/client/DuplicateJobSubmissionException.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
The Application and Job Mode rely on the `JobResultStore` for recovery. Nothing will be recovered if the job is in dirty state but globally terminated. That will just trigger the cleanup. But we didn't cover the case where there's a clean entry in the `JobResultStore`. This lead to the Application just terminating successfully without any indication to the user that the job didn't run.
~This PR changes the behavior in a way that a `DuplicateJobSubmissionException` with a meaningful error message is thrown instead.~
This PR adds a warning in cases where an job with an ID is submitted that refers to an already globally-terminated and cleaned job.
* Adds check and log message in `Dispatcher.submitJob`
* Adds test in `DispatcherTest` to cover the log message path
- Dependencies (does it add …
=> [FLINK-26583][runtime] Make the Flink cluster fail if the job ID is listed as globally-terminated and cleaned

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecSink.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/TableSinkTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/TableSinkTest.scala
FLINK-20370 fix the wrong result when sink primary key is not the same with query and introduced a new auto-keyby sink's primary key strategy for append stream if the sink's parallelism differs from input stream's.
But still exists one case to be solved:
for a changelog stream, its changelog upsert key same as sink's primary key, but sink's parallelism changed by user (via those sinks which implement the `ParallelismProvider` interface, e.g., KafkaDynamicSink), we should fix it.
And a minor change: keyby canbe omitted when sink has single parallism (because none partitioner will cause worse disorder)
update the logic of applyKeyBy in `CommonExecSink`
Streaming sql's `TableSinkTest` newly added test cases …
=> [FLINK-26534][table-planner] shuffle by sink's primary key should cover the case that input changelog stream has a different parallelism

flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderRetrievalDriverTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingRetrievalBase.java, flink-runtime/src/test/java/org/apache/flink/runtime/leaderretrieval/SettableLeaderRetrievalServiceTest.java
Cherry-picked fix from parent PR #19041 without conflicts.
=> [BP-1.14][FLINK-24538][runtime][tests] Fix race condition when offering information to leader event queue in TestingRetrievalBase

flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/SinkMetricsITCase.java
Fix the flaky test in SinkMetricsITCase. The previous check solution could not provide the guaranty of getting the correct metrics.
Since the target metric `numRecordsSend` for this test case is initialized in `SinkWriterMetricGroup` via parent `OperatorMetricGroup` and the SinkMetricsITCase is working on the abstract layer of `OperatorMetricGroup`, there is no direct access to the `SinkWriterMetricGroup` and to the `numRecordsSend` counter.
- check the metric by getting the numRecordsSend metric from `InMemoryReporter` and cast it to `Counter`
This change is to fix a flaky test.
- The serializers: (yes / …
=> [FLINK-26532][metrics][test] using the numRecordsSend counter to get the correct metric

flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniCluster.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/ExecutionGraphInfoStoreTestUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/minicluster/TestingMiniCluster.java, flink-tests/src/test/java/org/apache/flink/test/runtime/leaderelection/ZooKeeperLeaderElectionITCase.java
Related to https://issues.apache.org/jira/browse/FLINK-25235
Re-enabling test
=> [FLINK-25235][tests] re-enable zookeeper test

flink-runtime/src/test/java/org/apache/flink/runtime/leaderretrieval/ZooKeeperLeaderRetrievalConnectionHandlingTest.java
The test fails due to a flaky test. That results in an empty address being observed by the listener first which causes the `NullPointerException`
* Adds null check
* hotfix: Removes `CompletableFuture`
* `ZooKeeperLeaderRetrievalConnectionHandlingTest` succeeds still
=> [FLINK-26596][runtime] Adds leadership loss handling

docs/content.zh/docs/libs/state_processor_api.md, docs/content/docs/libs/state_processor_api.md
Fix documentation problem described in [FLINK-24274](https://issues.apache.org/jira/browse/FLINK-24274) for 1.14.
Adjust parameter order in documentation of State Processor API.
Not needed.
=> [FLINK-24274][docs] Wrong parameter order in documentation of State Processor API (for 1.14)

flink-connectors/flink-connector-aws-kinesis-firehose/pom.xml, flink-connectors/flink-connector-aws-kinesis-streams/pom.xml, flink-connectors/flink-connector-elasticsearch6/pom.xml, flink-connectors/flink-connector-elasticsearch7/pom.xml, flink-connectors/flink-connector-files/pom.xml, flink-connectors/flink-connector-hive/pom.xml, flink-connectors/flink-connector-kafka/pom.xml, flink-connectors/flink-connector-pulsar/pom.xml, flink-connectors/flink-sql-connector-aws-kinesis-firehose/pom.xml, flink-connectors/flink-sql-connector-aws-kinesis-streams/pom.xml, flink-connectors/flink-sql-connector-hbase-1.4/pom.xml, flink-connectors/flink-sql-connector-hbase-2.2/pom.xml, flink-connectors/flink-sql-connector-kafka/pom.xml, flink-connectors/flink-sql-connector-kinesis/pom.xml, flink-dist/pom.xml, flink-end-to-end-tests/flink-end-to-end-tests-aws-kinesis-firehose/pom.xml, flink-end-to-end-tests/flink-end-to-end-tests-aws-kinesis-streams/pom.xml, flink-end-to-end-tests/flink-streaming-kinesis-test/pom.xml, flink-formats/flink-orc/pom.xml, flink-formats/flink-parquet/pom.xml, tools/ci/compile.sh, tools/ci/shade.sh
`flink-connector-base` was previously inconsistently used in connectors (directly shaded in some and transitively pulled in via `flink-connector-files` which was itself shaded in the table uber jar). FLINK-24687 moved `flink-connector-files` out from the `flink-table` uber jar. This commit implements a combined approach for ensuring a smooth transition for both Flink users and for external connector developers, as outlined in this :
- all internal Flink connectors that depend on `flink-connector-base` now shade and relocate it
- for compatibility, until external developers implement the same change, `flink-connector-base` is also included into `flink-dist`
The rationale behind this combined approach was discussed [here](https://lists.apache.org/thread/hhjoc9hobs6h5pydr0623no2l36r6n6r).
- …
=> [FLINK-25927][connectors] Make flink-connector-base dependency usage consistent across all connectors 

flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerClusterITCase.java
* Makes test more flexible to run on slower machines by increasing the wait period
* Increased the deadline for the wait period
=> [FLINK-26500][runtime][test] Increases the deadline to wait for parallelism

flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerClusterITCase.java
1.14 backport for parent PR #19075 . No conflicts observed while cherry-picking `41c24e3959eb6c079bb87c2273e04ada53e5178f`
=> [BP-1.14][FLINK-26500][runtime][test] Increases the deadline to wait for parallelism

flink-runtime/src/test/java/org/apache/flink/runtime/leaderretrieval/ZooKeeperLeaderRetrievalConnectionHandlingTest.java
This is a missed-out 1.14 backport of PR #18844 only including the actually test fix.
We experienced some ZK connection issue which resulted in a
SUSPEND and a RECONNECT event which were not handled and,
therefore, stayed in the queue blocking a thread for the
second event (because the capacity of the internally used
ArrayBlockingQueue is set to 1). Shutting down the driver
initiates a shutdown of the ExecutorService which is used
for the listeners internally (see
ZooKeeperLeaderRetrievalDriver.close()). The blocking thread
will cause a fatal error through an InterruptedException.
The test will fail due to the fatal error in the end.
Cleaning unhandled events at the end of the test run fix the
issue. Additionally, the tests were aligned by moving generic
code into a helper method.
* Adds …
=> [FLINK-26121][BP-1.14][runtime] Adds clearUnhandledEvents() method

flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/output/SnapshotUtils.java, flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/output/SnapshotUtilsTest.java
Make state-processor-api support increment checkpoint write.
=> [FLINK-25528][state-processor-api] state processor api do not support increment checkpoint

flink-connectors/flink-connector-cassandra/src/test/java/org/apache/flink/streaming/connectors/cassandra/CassandraConnectorITCase.java
I took a look at the history of flaky test and found that:
**testCassandraBatchTupleFormat failure** https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=32816&view=results
**testCassandraScalaTuplePartialColumnUpdate** failure https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=32571&view=resultstestCassandraScalaTuplePartialColumnUpdate
**testCassandraTableSink failure** https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=32272
They fail because the keyspace does not exist while executing create table (in before) whereas the keyspace is created in before class. My guess it that drop tables (in after) is not atomic and drops the keyspace in between. Hence my commit for making it atomic.
The other failures I see are timeouts in only …
=> [FLINK-25771][connectors][Cassandra][tests][flaky] Remove testRetrialAndDropTables and make drop tables atomic

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointFailureManager.java
Avoid to print stack trace for checkpoint trigger failure if not all tasks are started. This is somehow like FLINK-22117.
Consider to avoid to print stack trace for checkpoint trigger failure if not all tasks are started.
=> [FLINK-26650][checkpoint] Avoid to print stack trace for checkpoint trigger failure if not all tasks are started

flink-runtime/src/main/java/org/apache/flink/runtime/state/InternalPriorityQueue.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/InternalTimerServiceImpl.java, flink-tests/src/test/java/org/apache/flink/test/state/ChangelogRescalingITCase.java
Key group is logged so that state changes can be re-distributed or shuffled.
It is currently obtained from keyContext for remove() operations.
However, keyContext is not updated when dequeing or processing time timers.
This causes re-scaling to fail if:
1. there is materialized state
1. there are remove operations
1. wrong key group was recorded for those operations
1. those groups fall into a different backend as a result of re-scaling
- `ChangelogRescalingITCase`
- Verified manually on a standalone cluster
-  …
=> [FLINK-26063][runtime] Set current key before polling next PQ element

flink-connectors/flink-connector-base/pom.xml, flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/SourceReaderBase.java, flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/splitreader/SplitReader.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/SourceReaderBaseTest.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceITCase.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/source/SourceOperatorEventTimeTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/source/TestingSourceOperator.java
This PR fixes a bug when multiple splits are assigned to a source operator, records from the first fetch of the first split might mistakenly push watermark forward so that records from other splits are treated as late event. 
- Fix typo of variable in SourceOperator
- Create per-split output on split addition in SourceOperator
- Added unit test for per-split watermark in source operator
- Added IT case for testing `SourceReaderBase` working together with `SourceOperator` on per-split watermark
- Added IT case for KafkaSource for testing per-split watermark
- The …
=> [FLINK-26018][connector/common] Create per-split output on split addition in SourceOperator

flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/Fabric8FlinkKubeClient.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/KubernetesClientTestBase.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/Fabric8FlinkKubeClientTest.java
When creating Task Manager (TM) Pod, the fabric client will query the Kubernetes deployment to set owner reference for the TM pod. However, repeating to querying the deployment each time is unnecessary which will waste a lot of time.
This change solves this problem by introducing an AtomicReference for Kubernetes deployment.
Save the master deployment reference as a field of Fabric8FlinkKubeClient when the method "createTaskManagerPod()" is called for the first time and then get it directly in the following invocation.
This change can be tested by:
Fabric8FlinkKubeClientTest#testCreateTwoTaskManagerPods
This test will fail before this PR due to getting deployment more than once.
- Dependencies (does it add or upgrade a dependency): (yes / no) no. …
=> [FLINK-25648][Kubernetes] Avoid redundant to query Kubernetes deployment when creating task manager pods

flink-core/src/main/java/org/apache/flink/configuration/ConfigConstants.java, flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java, flink-yarn/src/test/java/org/apache/flink/yarn/YarnClusterDescriptorTest.java
Fix the minor bug when locating `usrlib` with `ClusterEntrypointUtils#tryFindUserLibDirectory` as it will return a wrong usrlib if environment variable `FLINK_LIB_DIR` is pre-configured in the YARN cluster. To get rid of this wrong behavior, this PR sets `FLINK_LIB_DIR` to 'lib' under working dir in YARN containers for JM.
- Add a ConfigConstant `DEFAULT_FLINK_LIB_DIR`.
- Set FLINK_LIB_DIR to 'lib' under working dir in JM containers(i.e. YARN's application master container). Note, this PR does not set such env in TM (i.e. YARN's worker containers) as `tryFindUserLibDirectory` will only be used in ClusterEntrypoint in JM containers to generate JobGraph.
Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: …
=> [FLINK-26030][yarn] Set FLINK_LIB_DIR to 'lib' under working dir in YARN containers

flink-runtime/src/test/java/org/apache/flink/runtime/leaderretrieval/ZooKeeperLeaderRetrievalConnectionHandlingTest.java
This is a 1.14 backport of PR #19066 
If the ZK connection is flaky, we might collect another
ZK connection loss. This is now handled properly.
* Adds `null` check to condition
=> [FLINK-26596][BP-1.14][runtime][test] Adds leadership loss handling

flink-runtime-web/web-dashboard/.eslintrc.js, flink-runtime-web/web-dashboard/.prettierrc
Normally I'm developing on linux based system but sometimes reviewing on Windows based machines. Compile blows up in the following way:
```
[INFO] d:\projects\flink\flink-runtime-web\web-dashboard\src\@types\d3-flame-graph\index.d.ts
[INFO]    1:3   error  Delete `â??`  prettier/prettier
...
```
The following git config hacks it around:
```
core.eol=lf
core.autocrlf=input
```
but it would be good to make it work out of the box so changed prettier formatter config to auto detect the newline.
Here is how auto behaves:
`"auto" - Maintain existing line endings (mixed values within one file are normalised by looking at what’s used after the first line)`
Changed prettier formatter config to auto detect the newline.
Flink compile on linux + windows. …
=> [FLINK-26166][runtime-web] Add auto newline detection to prettier formatter

flink-runtime/src/test/java/org/apache/flink/runtime/util/TestingTaskManagerRuntimeInfo.java
Previously, the tmpWorkingDirectory was created in the current working
directory, and as a result there were directories created in the root
directories of the modules, i.e. `flink-table/flink-table-planner` which
were not cleaned up with `mvn clean`.
The behavior was introduced with: https://github.com/apache/flink/pull/18083
`EmbeddedRocksDBStateBackend#lazyInitializeForJob`:
```
if (localRocksDbDirectories == null) {
initializedDbBasePaths = new File[] {env.getTaskManagerInfo().getTmpWorkingDirectory()};
} else {
....
```
=> [FLINK-26418][runtime][test] Use java.io.tmpdir for tmpWorkingDir

docs/content/docs/connectors/datastream/elasticsearch.md, docs/content/docs/connectors/table/elasticsearch.md, flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchSink.java, flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchSinkBuilderBase.java, flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/table/ElasticsearchConnectorOptions.java, flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchSinkBuilderBaseTest.java, flink-connectors/flink-connector-elasticsearch6/src/main/java/org/apache/flink/connector/elasticsearch/sink/Elasticsearch6SinkBuilder.java, flink-connectors/flink-connector-elasticsearch7/src/main/java/org/apache/flink/connector/elasticsearch/sink/Elasticsearch7SinkBuilder.java
The default delivery guarantee of the Elasticsearch sink should be AT_LEAST_ONCE as it was the case in 1.14 for upgradability/consistency reasons.
Chinese docs have to be updated still.
- made AT_LEAST_ONCE the default delivery guarantee 
- updated english docs 
This change is already covered by existing tests, such as ElasticsearchXSinkITCase, E2E Tests
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / …
=> [FLINK-26281][connectors/elasticsearch] setting default delivery guarantee to AT_LEAST_ONCE

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/CustomSinkOperatorUidHashes.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/DataStream.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/DataStreamSink.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/transformations/SinkTransformation.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/translators/SinkTransformationTranslator.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SinkTransformationTranslatorTest.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecSink.java
Since the topology has changes between Flink 1.14 and 1.15 it might
happen that stateful upgrades are not possible if no pior operator uids
were set. With this commit, users can set operator uid hashes for the
respective operators.
- Add a parameter to `DataStream#sinkTo` to pass operator uid hashes`
- Set the operator uid hashes for `Writer`, `Committer`, `GlobalCommitter` during `SinkTransformation` translation
Added a test to verify the respective sink operators have the uid hash set.
- …
=> [FLINK-26613][streaming] Allow setting operator uid hashes for predefined sink operators

docs/content.zh/docs/connectors/datastream/formats/parquet.md, docs/content/docs/connectors/datastream/formats/parquet.md
Update the document based on the feedback of release test task FLINK-26301.
- remove redundant content of bounded and unbounded data
- add description of mvn dependency for reading Avro records
- new description of using namespace in schema for reading reflect records
This change is a trivial document update.
- The S3 file …
=> [FLINK-26604][doc] add more information for Avro records support and clean up redundant content of bounded and unbounded data

docs/content/docs/ops/state/savepoints.md
*Modify the grammar mistakes in savepoints.md*
- *Change the sentence "The legacy is mode is how Flink worked until 1.15." to "The legacy mode is how Flink worked until 1.15."*
=> [FLINK-26693][Documentation] Modify the grammar mistakes in savepoint

flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/FileSystemJobResultStore.java, flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/FileSystemJobResultStoreTestInternal.java
The issue before the fix was, that using getPath would strip
off the scheme information which causes problems in situations
where the FileSystem is not the default FileSystem.
* removes `getPath` from path construction methods
* Added unit tests for verifying that the constructed paths' parent matches the basePath …
=> [FLINK-26698][runtime] Uses the actual basePath instance instead of only the path of Path instance

flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriter.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterTest.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/TestSinkInitContext.java, flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/sink/writer/FileWriter.java, flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/sink/writer/FileWriterTest.java
This is the follow-up PR of #18825. We found that the new sink v2 interface will have a wrong numRecordsOut metric for the sink writers. We send a fixed number of records to the source, but the numRecordsOut of the sink continues to increase by the time. 
- replace the records out counter with the records send counter in `FileWriter`
-  replace the records and byte out counter with the records and byte send counter in `AsyncSinkWriter`
-  migrate `FileWriterTest` and `AsyncSinkWriterTest` to AssertJ
This change is already covered by existing tests, such as `FileWriterTest` and `AsyncSinkWriterTest`.
- The serializers: (yes / …
=> [FLINK-26420][Connector] use numRecordsSendCounter

flink-connectors/flink-connector-aws-kinesis-firehose/pom.xml, flink-connectors/flink-connector-aws-kinesis-streams/pom.xml, flink-connectors/flink-connector-elasticsearch6/pom.xml, flink-connectors/flink-connector-elasticsearch7/pom.xml, flink-connectors/flink-connector-files/pom.xml, flink-connectors/flink-connector-hive/pom.xml, flink-connectors/flink-connector-kafka/pom.xml, flink-connectors/flink-connector-pulsar/pom.xml, flink-connectors/flink-sql-connector-aws-kinesis-firehose/pom.xml, flink-connectors/flink-sql-connector-aws-kinesis-streams/pom.xml, flink-connectors/flink-sql-connector-hbase-1.4/pom.xml, flink-connectors/flink-sql-connector-hbase-2.2/pom.xml, flink-connectors/flink-sql-connector-kafka/pom.xml, flink-connectors/flink-sql-connector-kinesis/pom.xml, flink-end-to-end-tests/flink-end-to-end-tests-aws-kinesis-firehose/pom.xml, flink-end-to-end-tests/flink-end-to-end-tests-aws-kinesis-streams/pom.xml, flink-end-to-end-tests/flink-streaming-kinesis-test/pom.xml, flink-formats/flink-orc/pom.xml, flink-formats/flink-parquet/pom.xml, tools/ci/compile.sh, tools/ci/shade.sh
With the introduction of [FLINK-25927](https://issues.apache.org/jira/browse/FLINK-25927), every connector now relocates connector-base to better support connectors compatibility with different Flink versions. Unfortunately, not all classes in connector-base are only used by connector but some are supposed to be used inside the user jar directly i.e. DeliveryGuarantee, HybridSource...
Because of the relocation, the existing imports for those classes are broken.
=> [FLINK-26701] Revert FLINK-25927 apart from adding connector-base to flink-dist

flink-connectors/flink-connector-jdbc/pom.xml, flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/catalog/PostgresCatalogTestBase.java, flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/catalog/factory/JdbcCatalogFactoryTest.java, flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/xa/JdbcExactlyOnceSinkE2eTest.java, flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/util/DockerImageVersions.java
PostgreSQL tests were executed based on an embedded database.  This has issues on some systems (Mac) and blocked work on FLINK-25926. This PR migrates these tests to Testcontainers.
This PR modifies the existing tests setup. …
=> [FLINK-26716][test][connectors/jdbc] Migrate PostgreSQL tests to Testcontainers

docs/content.zh/docs/learn-flink/datastream_api.md, docs/content.zh/docs/learn-flink/event_driven.md, docs/content.zh/docs/learn-flink/fault_tolerance.md, docs/content.zh/docs/learn-flink/streaming_analytics.md
Compared English with Chinese version, the orders of articles locates in TOC for docs learn Flink are different.
- docs/content.zh/docs/learn-flink/datastream_api.md
- docs/content.zh/docs/learn-flink/event_driven.md
- docs/content.zh/docs/learn-flink/fault_tolerance.md
- docs/content.zh/docs/learn-flink/streaming_analytics.md
- Does …
=> [FLINK-26381][docs] Wrong document order of Chinese version

docs/content.zh/docs/connectors/datastream/formats/parquet.md
Translate datastream/formats/parquet.md page into Chinese.
Translate datastream/formats/parquet.md page into Chinese.
A pure documentation task.
- The public API, i.e., is any changed class annotated with @Public(Evolving): (yes / **no**)
- The serializers: (yes / **no**) …
=> [FLINK-25797][docs-zh] Translate datastream/formats/parquet.md page into Chinese.

flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/context/SessionContext.java, flink-table/flink-sql-client/src/test/resources/sql/set.q
Currently, `remove jar` statement doesn't remove the corresponding jars in pipeline.jars, which should be fixed.
- Replacing session dependencies instead of merging them into the new dependencies in remove-jar statements. …
=> [FLINK-26618][sql-client] Fix Remove-Jar statement not effective

docs/content.zh/docs/concepts/time.md, docs/content/docs/concepts/time.md
jus a simple fix on a broken reference.
fix the broken reference in these docs.
run a local build and check the broken reference fixed.
=> [hotfix][docs] Fix the broken link for late events/lateness

flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStore.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStoreTest.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmanager/DefaultJobGraphStore.java, flink-runtime/src/main/java/org/apache/flink/runtime/persistence/StateHandleStore.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmanager/DefaultJobGraphStoreTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStoreTest.java
This is a 1.15 backport of parent PR #19121 which was approved. Cherry-picking the commits didn't produce any conflicts
=> [FLINK-26690][BP-1.15][runtime] Makes globalCleanupAsync call the removal even if the JobGraph is not put into the JobGraphStore, yet

flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStore.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStoreTest.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmanager/DefaultJobGraphStore.java, flink-runtime/src/main/java/org/apache/flink/runtime/persistence/StateHandleStore.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmanager/DefaultJobGraphStoreTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStoreTest.java
This can happen if cleanup is triggered after a
failover of a dirty JobResultStore entry (i.e. of
a globally-terminated job). In that case, no
recovery of the JobGraph happens and, therefore, no
JobGraph is added to the internal addedJobGraphs
collection.
There's no need to check the `addedJobGraphs` because `StateHandleStore.releaseAndTryRemove` was made idempotent in FLINK-26284 and FLINK-26286. Removing a non-existing JobID from the `DefaultJobGraphStore.addedJobGraphs` works without problems as well.
But it required to update the `KubernetesStateHandleStore.releaseAndTryRemove`. That one failed before if nothing was updated. The problem with this implementation is that the returning `Optional.empty` results in the downstream callback retrieving `updated=false`. That is true for cases …
=> [FLINK-26690][runtime] Makes globalCleanupAsync call the removal even if the JobGraph is not put into the JobGraphStore, yet

flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContext.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContextTest.java
fix the error message thrown by SourceCoordinatorContext
> fix the error message `SourceCoordinatorContext`
> provide more message for test in `SourceCoordinatorContextTest`
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after master …
=> [FLINK-26723][runtime]fix the error message thrown by SourceCoordinatorContext

flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/context/SessionContext.java, flink-table/flink-sql-client/src/test/resources/sql/set.q
Currently, remove jar statement doesn't remove the corresponding jars in pipeline.jars, which should be fixed.
Replacing session dependencies instead of merging them into the new dependencies in remove-jar statements. …
=> [BP-1.15][FLINK-26618] Fix pipeline.jars not aligned with remove-jar statement

flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveLookupJoinITCase.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/filesystem/FileSystemLookupFunction.java
*Fix lookup join bug when reading hive columnar storage tables.  *
- *When building the cache, generate cache key after copy the RowData from columnar RowData in case of different key reference the same memory*
*Unit tests*
- *Add test in [HiveLookupJoinITCase.java] to test lookup join with columnar table and make sure there is enough records to make sure the ParquetVectorizedInputFormat will read at least two batch to reproduce the error* …
=> [FLINK-26016][hive][BP-1.14] Fix FileSystemLookupFunction does not produce correct results when hive table uses columnar storage

docs/content.zh/docs/learn-flink/datastream_api.md, docs/content.zh/docs/learn-flink/event_driven.md, docs/content.zh/docs/learn-flink/fault_tolerance.md, docs/content.zh/docs/learn-flink/streaming_analytics.md
Unchanged backport of https://github.com/apache/flink/pull/19010 on release-1.14
=> [BP-1.14][FLINK-26381][docs] Wrong document order of Chinese version

docs/content.zh/docs/learn-flink/datastream_api.md, docs/content.zh/docs/learn-flink/event_driven.md, docs/content.zh/docs/learn-flink/fault_tolerance.md, docs/content.zh/docs/learn-flink/streaming_analytics.md
Unchanged backport of https://github.com/apache/flink/pull/19010 on release-1.15
=> [BP-1.15][FLINK-26381][docs] Wrong document order of Chinese version

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/windowing/windows/TimeWindow.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/windowing/TimeWindowTest.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/window/TimeWindow.java
Co-authored-by: Lin WanNi <linwanniderz@foxmail.com>
Co-authored-by: Guo YuanFang <1650213825@qq.com>
[https://issues.apache.org/jira/browse/FLINK-26334](https://issues.apache.org/jira/browse/FLINK-26334)
The goal of this PR is to fix the bug that:  the element couldn't be assigned to the correct window-start, if it's *timestamp - offset + windowSize < 0*.
This bug located at _org.apache.flink.streaming.api.windowing.windows.TimeWindow_ .
This problem will be triggered by the negative timestamp, and is caused by the calculation method of remainder in the JAVA compiler. 
Specifically, when we try to calculate the window-start of an incoming element,  if _timestamp - offset + windowSize < 0_, based on the current calculation formula for window-start, **the element will be right shifted to …
=> [FLINK-26334][datastream] Fix getWindowStartWithOffset in TimeWindow.java

flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/writer/topic/TopicMetadataListener.java, flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/topic/TopicNameUtils.java, flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/sink/writer/topic/TopicMetadataListenerTest.java
This PR tries to fix the[FLINK-26642](https://issues.apache.org/jira/browse/FLINK-26642)
Pulsar Sink should support partitioned and non-partitioned topics.
=> [FLINK-26642][connector/pulsar] Fix support for non-partitioned topic

flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/writer/topic/TopicMetadataListener.java, flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/topic/TopicNameUtils.java, flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/sink/writer/topic/TopicMetadataListenerTest.java
This PR tries to fix the[FLINK-26642](https://issues.apache.org/jira/browse/FLINK-26642)
Pulsar Sink should support partitioned and non-partitioned topics.
Release-1.15 also has this problem. This PR pick the relevant commit.
@fapaul PTAL
=> [BP-1.15][FLINK-26642][connector/pulsar] Fix support for non-partitioned topic for Release-1.15

docs/content.zh/docs/ops/metrics.md, docs/content/docs/ops/metrics.md, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/DescriptiveStatisticsHistogram.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricNames.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/TaskIOMetricGroup.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/mailbox/MailboxProcessor.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/mailbox/TaskMailbox.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/mailbox/TaskMailboxImpl.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/mailbox/TaskMailboxProcessorTest.java
* Add the following metrics to TaskIOMetricGroup:
* mailbox latency metric backed by DescriptiveStatisticsHistogram
* throughput metric backed by a MeterView
* mailbox size metric backed by Gauge
* Added metrics to TaskIOMetricGroup
* Extended StreamTask to schedule mailbox latency measurements using a timer
* Extended MailboxProcessor to count processed mails for throughput measurement
* Added size method to TaskMailbox interface
- Extended existing test method TaskMailboxProcessorTest#testRunDefaultActionAndMails to verify mail/throughput counting
- Added test method StreamTaskTest#testMailboxMetrics to verify timer-based latency measurement and queue size metric
- The change has been verified manually/visually in Web UI:
- …
=> [FLINK-26279][runtime] Add mailbox delay and throughput metrics

flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogStorage.java, flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogWriter.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/BatchingStateChangeUploadSchedulerTest.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/ChangelogStorageMetricsTest.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/FsStateChangelogStorageTest.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/FsStateChangelogWriterSqnTest.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/FsStateChangelogWriterTest.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/StateChangelogStorage.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/inmemory/InMemoryStateChangelogStorage.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/TaskExecutorStateChangelogStoragesManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/changelog/inmemory/StateChangelogStorageLoaderTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/changelog/inmemory/StateChangelogStorageTest.java, flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogStateBackend.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackendTest.java
This is an alternative version of #19050 that solves the problem using `MailboxExecutor`.
```
When a task thread tries to schedule an upload, it might wait for available capacity.
Capacity is released by the uploading thread on upload completion.  After releasing,
it must notify the task thread about the completion.
Both task and uploading thread acquire FsStateChangelogWriter.lock. That causes
a deadlock if uploader releases capacity insufficient for task thread to proceed.
This change removes the lock and makes uploader thread to use mailbox actions.
```
`FsStateChangelogStorageTest.testDeadlockOnUploadCompletion`
- The …
=> [FLINK-26592][state/changelog] Use mailbox in FsStateChangelogWriter instead of a lock

flink-runtime/src/main/java/org/apache/flink/runtime/metrics/DescriptiveStatisticsHistogramStatistics.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/DescriptiveStatisticsHistogramTest.java
Percentile serialization doesn't work properly (see MATH-1642), so instead of serialize the data array and lazily initialize the Percentile as needed.
=> [FLINK-25904][metrics] Lazily initialize Percentile

flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientITCase.java, flink-table/flink-sql-client/src/test/resources/sql/view.q, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/schema/ExpandingPreparingTable.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/TableEnvironmentTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/hint/OptionsHintTest.scala
This PR aims to throw an explicit exception when querying a view with hints to improve user experience. Currently, the hints on view are swallowed quietly during the planning phase without any trace, and users complain that the hints don't work on view. 
- Add check on `ExpandingPreparingTable` to throw a `ValidationException`
- A monitor fix for `CliClientITCase` to correct the assertion order for expected and actual
- `TableEnvironmentTest#testQueryViewWithHints`
- `OptionHintsTest#testOptionsHintOnTableApiView` and `#testOptionsHintOnSQLView`
-  Add test case in `view.q`, which can be verified by running `CliClientITCase` …
=> [FLINK-26495][table-planner] Prohibit hints(dynamic table options) on view

flink-filesystems/flink-hadoop-fs/src/test/java/org/apache/flink/runtime/fs/hdfs/AbstractHadoopRecoverableWriterExceptionITCase.java, flink-filesystems/flink-hadoop-fs/src/test/java/org/apache/flink/runtime/fs/hdfs/AbstractHadoopRecoverableWriterITCase.java, flink-filesystems/flink-s3-fs-hadoop/src/test/java/org/apache/flink/fs/s3hadoop/HadoopS3RecoverableWriterExceptionITCase.java, flink-filesystems/flink-s3-fs-hadoop/src/test/java/org/apache/flink/fs/s3hadoop/HadoopS3RecoverableWriterITCase.java
Add abstract test classes for recoverable writers(s3/oss)
**add abstract test classes for recoverable writers(s3/oss)**
Run tests under flink-s3-fs-hadoop by setting environments below:
`export IT_CASE_S3_BUCKET=<Your bucket>`
`export IT_CASE_S3_ACCESS_KEY=<Your access key id>`
`export IT_CASE_S3_SECRET_KEY=<Your access secret>`
- The S3 file …
=> [FLINK-11388][fs]add abstract test classes for recoverable writers(s3/oss)

docs/content/docs/connectors/table/elasticsearch.md, flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/AbstractTimeIndexGenerator.java, flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/ElasticsearchConfiguration.java, flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/ElasticsearchConnectorOptions.java, flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/ElasticsearchValidationUtils.java, flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/IndexGenerator.java, flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/IndexGeneratorBase.java, flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/IndexGeneratorFactory.java, flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/KeyExtractor.java, flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/RequestFactory.java, flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/RowElasticsearchSinkFunction.java, flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/StaticIndexGenerator.java, flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/IndexGeneratorFactoryTest.java, flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/KeyExtractorTest.java, flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/TestContext.java, flink-connectors/flink-connector-elasticsearch6/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6Configuration.java, flink-connectors/flink-connector-elasticsearch6/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSink.java, flink-connectors/flink-connector-elasticsearch6/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkFactory.java, flink-connectors/flink-connector-elasticsearch6/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkFactoryTest.java, flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkITCase.java, flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkTest.java, flink-connectors/flink-connector-elasticsearch7/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7Configuration.java, flink-connectors/flink-connector-elasticsearch7/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSink.java, flink-connectors/flink-connector-elasticsearch7/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkFactory.java, flink-connectors/flink-connector-elasticsearch7/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkFactoryTest.java, flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkITCase.java, flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkTest.java
Because users depend on the `ActionFailureHandler` we need to revert the Table API implementation of the Elasticsearch Sink back to the SinkFunction one. This is only transitory but necessary for 1.15
- Reverted changes to TableAPI modules back to SinkFunction based one
- Backported FLINK-24571 (`now()`function in dynamic indexes)
- Updated connector docs for Table API
- Added the tests from the old SinkFunction-based module
- Anything …
=> [FLINK-26638][connnectors/elasticsearch] Revert Table API implementation to SinkFunction

flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/async/OperationKey.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/AsynchronousJobOperationKey.java
These are used in some RPC calls for triggering savepoints and must be serializable in case the request was sent from a standby JM.
=> [FLINK-26779][rest] OperationKey implements Serializable

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/ManagedTableListener.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/factories/TableFactoryUtil.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/delegation/PlannerBase.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/connector/file/table/LegacyTableFactory.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/stream/sql/LegacyTableFactoryTest.java, flink-table/flink-table-planner/src/test/resources/META-INF/services/org.apache.flink.table.factories.TableFactory, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/LegacyTableFactoryTest.xml
Fix the bug, Managed table breaks:
```
CREATE TABLE T (a INT) WITH ('type'='legacy');
INSERT INTO T VALUES (1); 
```
This case can be misinterpreted as a managed table, which the user might expect to be resolved by the legacy table factory.
- Move `isLegacyConnectorOptions` to `TableFactoryUtil`.
- `ManagedTableListener.isManagedTable` should exclude legacy connector.
- `LegacyTableFactoryTest`. …
=> [FLINK-26805][table] Managed table breaks legacy connector without 'connector.type'

flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/ChangelogStateHandleStreamImpl.java
This pull request fix mistake in ChangelogStateHandleStreamImpl#getIntersection. (described in FLINK-26766)
correct getIntersection method from compute intersection between parameter keyGroupRange and itself to compute intersection between parameter keyGroupRange and ChangelogStateHandleStreamImpl inner one.
=> [FLINK-26766][Runtime/StateBackends] Fix ChangelogStateHandleStreamImpl#getIntersection

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/AppendOnlyFirstNFunction.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/rank/AppendOnlyFirstNFunctionTest.java
fix the wrong result when AppendOnlyFirstNFunction with offset and without rank number.
update the process logic in AppendOnlyFirstNFunction
AppendOnlyFirstNFunctionTest.testConstantRankRangeWithOffset
=> [FLINK-26819][table-runtime] Fix wrong results when AppendOnlyFirstNFunction with offset and without rank number

docs/content.zh/docs/dev/table/sql/queries/deduplication.md, docs/content/docs/dev/table/sql/queries/deduplication.md
order_time should be order_id in the table creation statement.
=> [hotfix][doc] fix typo in sql doc.

flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/Fabric8FlinkKubeClient.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/FlinkKubeClient.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/Fabric8FlinkKubeClientTest.java
The only issue where we can run into this right now is where the k8s API returns 404 which is quite unlikely to happen. But still it's good to have the implementation harden for such cases.
The `deleteConfigMapByLabels` implementation couldn't be tested like that due to a bug in the fabric8 code: See issue [fabric8io/kubernetes-client issue #3982](https://github.com/fabric8io/kubernetes-client/issues/3982)
Added evaluation around the delete return value.
* Added tests for non-existing ConfigMap deletion (not related to the change)
* Added test for error case where the HTTP request responding with 404 which is the only case where the delete returns `false`
* Disabled the test that's not working because of issue mentioned above
- The …
=> [FLINK-26695][runtime] Evaluation of deleteConfigMap's return value added

flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesCheckpointIDCounter.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesCheckpointIDCounterTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesHighAvailabilityTestBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointIDCounter.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/DeactivatedCheckpointIDCounter.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/StandaloneCheckpointIDCounter.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/ZooKeeperCheckpointIDCounter.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/cleanup/CheckpointResourcesCleanupRunner.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTriggeringTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointIDCounterTestBase.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/TestingCheckpointIDCounter.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/ZooKeeperCheckpointIDCounterITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/DefaultSchedulerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
1.15 backport of PR #19191 No conflicts appeared during backport:
```
git cherry-pick ccd98ac920969204576161ac9a23e9660f6014e1 9d5feafa7d0d652ff58e9c067afd914fbee9abd0
```
=> [FLINK-26741][BP-1.15][runtime] The CheckpointIDCounter.shutdown method should work idempotently

flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesCheckpointIDCounter.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesCheckpointIDCounterTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesHighAvailabilityTestBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointIDCounter.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/DeactivatedCheckpointIDCounter.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/StandaloneCheckpointIDCounter.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/ZooKeeperCheckpointIDCounter.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/cleanup/CheckpointResourcesCleanupRunner.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTriggeringTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointIDCounterTestBase.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/TestingCheckpointIDCounter.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/ZooKeeperCheckpointIDCounterITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/DefaultSchedulerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
We should make sure that the shutdown mechanism works idempotently. Additionally, errors should be propagated. Returning a CompletableFuture as the result object of the shutdown matches the general pattern we're using for cleanup tasks that are then handled downstream.
* Modified `CheckpointIDCounter.shutdown` method signature
* Refactored `ZooKeeperIDCounter` to make cleanup being handled asynchronously properly
* Tests were added to `ZooKeeperIDCounterITCase` and 
`KubernetesCheckpointIDCounterTest` …
=> [FLINK-26741][runtime] The CheckpointIDCounter.shutdown method should work idempotently

docs/content.zh/docs/ops/state/savepoints.md, docs/content/docs/ops/state/savepoints.md
Added chinese documentation for the RestoreMode
This is a change to documentation
=> [FLINK-26700][docs] Document restore mode in chinese

flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/ChangelogStorageMetricsTest.java
There is a race condition in ChangelogStorageMetricsTest.testAttemptsPerUpload:
- the assertion is made as soon as upload (future) is completed
- the histogram is updated after completing the upload (on success)
Moving assertion out of try/close block solves the problem.
=> [FLINK-26809][tests] Assert histogram state after stopping the uploader

flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/BatchingStateChangeUploadSchedulerTest.java
`BatchingStateChangeUploadSchedulerTest.testRetryOnTimeout` might fail if all attempts time out before 
the check is performed and the underlying uploader is unblocked.
This change increases the difference between those timings, so that the check is much faster.   …
=> [FLINK-26615][tests] Fix timings in BatchingStateChangeUploadSchedulerTest.testUploadTimeout

flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/TimestampsAndWatermarksOperator.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/TimestampsAndWatermarksOperatorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/util/OneInputStreamOperatorTestHarness.java
The lifecycle/scope of WatermarkStatus is tightly coupled with watermarks. Upstream watermarks are cut off in the TimestampsAndWatermarksOperator and therefore watermark statuses should be cut off as well.
Added tests in:
* `TimestampsAndWatermarksOperatorTest` …
=> [FLINK-26708] TimestampsAndWatermarksOperator should not propagate WatermarkStatus

flink-filesystems/flink-oss-fs-hadoop/src/main/java/org/apache/flink/fs/osshadoop/FlinkOSSFileSystem.java, flink-filesystems/flink-oss-fs-hadoop/src/main/java/org/apache/flink/fs/osshadoop/OSSAccessor.java, flink-filesystems/flink-oss-fs-hadoop/src/main/java/org/apache/flink/fs/osshadoop/OSSFileSystemFactory.java, flink-filesystems/flink-oss-fs-hadoop/src/main/java/org/apache/flink/fs/osshadoop/writer/OSSCommitter.java, flink-filesystems/flink-oss-fs-hadoop/src/main/java/org/apache/flink/fs/osshadoop/writer/OSSRecoverable.java, flink-filesystems/flink-oss-fs-hadoop/src/main/java/org/apache/flink/fs/osshadoop/writer/OSSRecoverableFsDataOutputStream.java, flink-filesystems/flink-oss-fs-hadoop/src/main/java/org/apache/flink/fs/osshadoop/writer/OSSRecoverableMultipartUpload.java, flink-filesystems/flink-oss-fs-hadoop/src/main/java/org/apache/flink/fs/osshadoop/writer/OSSRecoverableSerializer.java, flink-filesystems/flink-oss-fs-hadoop/src/main/java/org/apache/flink/fs/osshadoop/writer/OSSRecoverableWriter.java, flink-filesystems/flink-oss-fs-hadoop/src/test/java/org/apache/flink/fs/osshadoop/HadoopOSSRecoverableWriterExceptionITCase.java, flink-filesystems/flink-oss-fs-hadoop/src/test/java/org/apache/flink/fs/osshadoop/HadoopOSSRecoverableWriterITCase.java, flink-filesystems/flink-oss-fs-hadoop/src/test/java/org/apache/flink/fs/osshadoop/OSSTestUtils.java, flink-filesystems/flink-oss-fs-hadoop/src/test/java/org/apache/flink/fs/osshadoop/writer/OSSRecoverableFsDataOutputStreamTest.java, flink-filesystems/flink-oss-fs-hadoop/src/test/java/org/apache/flink/fs/osshadoop/writer/OSSRecoverableMultipartUploadTest.java, flink-filesystems/flink-oss-fs-hadoop/src/test/java/org/apache/flink/fs/osshadoop/writer/OSSRecoverableSerializerTest.java
OSS offers persistence only after uploads or multi-part uploads complete. In order to make streaming uses OSS as sink, we should implement a Recoverable writer. This writer will snapshot and store multi-part upload information and recover from those information when failure occurs.
**- add OSS recoverable writer**
This implementation adds some tests to test logic of recoverable writer. However, in order to run these tests, someone need to have his own Aliyun access key id and access key secret. Then, set environment variables below：
`export ARTIFACTS_OSS_ENDPOINT=<Aliyun OSS endpoint to connect to>`
`export ARTIFACTS_OSS_BUCKET=<Your bucket>`
`export ARTIFACTS_OSS_ACCESS_KEY=<Your access key id>`
`export ARTIFACTS_OSS_SECRET_KEY=<Your access secret>`
These tests are skipped by default.
- …
=> [FLINK-11388][fs] Add Aliyun OSS recoverable writer

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/throughput/BufferDebloater.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/throughput/BufferDebloaterTest.java
This is a simple hotfix improving debug logs for BufferDebloater
No changes in tests.
=> [hotfix][task] Add task name to BufferDebloater logging

docs/content.zh/docs/deployment/metric_reporters.md, docs/content/docs/deployment/metric_reporters.md, docs/layouts/shortcodes/generated/influxdb_reporter_configuration.html, docs/layouts/shortcodes/generated/metric_configuration.html, docs/layouts/shortcodes/generated/metric_reporters_section.html, docs/layouts/shortcodes/generated/prometheus_push_gateway_reporter_configuration.html, docs/layouts/shortcodes/include_reporter_config.html, flink-annotations/src/main/java/org/apache/flink/annotation/docs/Documentation.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestBase.java, flink-core/src/main/java/org/apache/flink/configuration/ConfigConstants.java, flink-core/src/main/java/org/apache/flink/configuration/MetricOptions.java, flink-docs/src/main/java/org/apache/flink/docs/configuration/ConfigOptionsDocGenerator.java, flink-docs/src/test/java/org/apache/flink/docs/configuration/ConfigOptionsDocsCompletenessITCase.java, flink-end-to-end-tests/flink-metrics-reporter-prometheus-test/src/test/java/org/apache/flink/metrics/prometheus/tests/PrometheusReporterEndToEndITCase.java, flink-metrics/flink-metrics-influxdb/src/main/java/org/apache/flink/metrics/influxdb/InfluxdbReporterOptions.java, flink-metrics/flink-metrics-jmx/src/test/java/org/apache/flink/runtime/jobmanager/JMXJobManagerMetricTest.java, flink-metrics/flink-metrics-prometheus/src/main/java/org/apache/flink/metrics/prometheus/PrometheusPushGatewayReporterOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/ReporterSetup.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/MetricRegistryImplTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/ReporterSetupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/AbstractMetricGroupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/MetricGroupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/testutils/InMemoryReporter.java
The first commit extends the SuffixOption to include a key prefix that is also written into the generated html file.
This allows us to use the same file for documenting the fully-qualified option (prefix + suffix) or just the suffix option (e.g., as a list of parameters that a reporter accepts).
The second commits consolidates generic reporter options as ConfigOptions in the MetricOptions. The previously used ConfigConstants have been deprecated.
=> [FLINK-26851][metrics] Properly model reporter options as ConfigOptions

flink-core/src/main/java/org/apache/flink/api/connector/source/ExternallyInducedSourceReader.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/checkpoint/ExternallyInducedSource.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/StreamTaskExternallyInducedSourceInput.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceOperatorStreamTask.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceOperatorStreamTaskTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTaskTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTaskTestBase.java
=> [FLINK-25256][streaming] Externally induced sources replay barriers received over RPC instead of inventing them out of thin air. [1.15]

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/writer/SubtaskStateMapper.java
fix bug in code comment of SubtaskStateMapper.RANGE
The code comments for SubtaskStateMapper.RANGE are as follows:
```
* <p>Example:<br>
* old assignment: 0 -> [0;43); 1 -> [43;87); 2 -> [87;128)<br>
* new assignment: 0 -> [0;64]; 1 -> [64;128)<br>
* subtask 0 recovers data from old subtask 0 + 1 and subtask 1 recovers data from old subtask 0
* + 2
```
The correct code comment should be：
```
* <p>Example:<br>
* old assignment: 0 -> [0;43); 1 -> [43;87); 2 -> [87;128)<br>
* new assignment: 0 -> [0;64]; 1 -> [64;128)<br>
* subtask 0 recovers data from old subtask 0 + 1 and subtask 1 recovers data from old subtask 1
* + 2
```
**subtask 1 should recovers data from old subtask 1 + 2，not from old subtask 0 + 2** …
=>  [FLINK-26629][runtime] fix bug in code comment of SubtaskStateMapper.RANGE

docs/content.zh/docs/deployment/elastic_scaling.md
*In setence "- 配置 `jobmanager.scheduler: AdpaptiveBatch`", the word AdaptiveBatch is spelling wrong which may confuse the users.*
- *Modify spelling error in elastic_scaling.md*
=> [hotfix][doc] Modify spelling error in elastic_scaling.md

flink-runtime/src/test/java/org/apache/flink/runtime/testutils/CommonTestUtils.java, flink-tests/src/test/java/org/apache/flink/test/state/ChangelogCompatibilityITCase.java, flink-tests/src/test/java/org/apache/flink/test/state/ChangelogRescalingITCase.java, flink-tests/src/test/java/org/apache/flink/test/util/TestUtils.java
```
Using dedicated API has the following advantages over looking for checkpoints on FS:
- less prone to NoSuchFileException
- less brittle because file layout is not a declared API
- less IO usage
```
=> [FLINK-26794][tests] Use API to access job checkpoints in IT cases

flink-core/src/main/java/org/apache/flink/api/connector/source/ExternallyInducedSourceReader.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/checkpoint/ExternallyInducedSource.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/StreamTaskExternallyInducedSourceInput.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceOperatorStreamTask.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceOperatorStreamTaskTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTaskTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTaskTestBase.java
Externally induced sources are currently ill-defined and have a lot of unnecessary limitations. This PR addresses it by explicitly only holding back checkpoint barriers until the external source induces it. 
While this approach seemingly limits the way externally induce sources work (they can't trigger a checkpoint on their own anymore), it actually explicitly supports the only plausible way. Sources simply can't trigger a checkpoint on their own - the checkpoint coordinator needs to track it and multiple sources need the coordinator to work at all (or else they deadlock).
- Externally induced sources replay barriers received over RPC instead of inventing them out of thin air.
- Clarify the contract.
- Migrate related tests to JUnit5 and AssertJ.
Expanded the original unit test to check …
=> [FLINK-25256][streaming] Externally induced sources replay barriers received over RPC instead of inventing them out of thin air. 

flink-tests/src/test/java/org/apache/flink/test/checkpointing/RescaleCheckpointManuallyITCase.java
Fix unstable `RescaleCheckpointManuallyITCase` via ensuring contents of state within SubtaskIndexFlatMapper are all included in the last checkpoint.
Fix unstable `RescaleCheckpointManuallyITCase`.
=> [FLINK-26882][tests] Fix unstable RescaleCheckpointManuallyITCase

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/GreatestLeastFunctionsITCase.java
Previously, `LEAST` and `GREATEST` functions would return primitive
types in the generated code implementing their logic, producing issues
for operators applied on top of them, and most importantly comparison
operators, i.e.:
```
f0 INT, f1 INT
SELECT GREATEST(f0, f1) = GREATEST(f0, f1)
```
would return `FALSE`, since the generated code would return `Integer`
instead of `int`, as the result of `GREATEST`, and the `=` operator
on `Integer` objects would return false, even if the actual integer
value of them was the same.
- Change code generation for `LEAST`/`GREATEST` to return primitive types instead of boxed, (null is already handled correctly with the use of `nullTerm`s.
- Added more tests in `GreatestLeastFunctionsITCase`
- …
=> [FLINK-25227][table-planner] Fix LEAST/GREATEST to return primitives

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/GreatestLeastFunctionsITCase.java
Previously, `LEAST` and `GREATEST` functions would return primitive
types in the generated code implementing their logic, producing issues
for operators applied on top of them, and most importantly comparison
operators, i.e.:
```
f0 INT, f1 INT
SELECT GREATEST(f0, f1) = GREATEST(f0, f1)
```
would return `FALSE`, since the generated code would return `Integer`
instead of `int`, as the result of `GREATEST`, and the `=` operator
on `Integer` objects would return false, even if the actual integer
value of them was the same.
- Change code generation for `LEAST`/`GREATEST` to return primitive types instead of boxed, (null is already handled correctly with the use of `nullTerm`s.
- Added more tests in `GreatestLeastFunctionsITCase`
- …
=> [FLINK-25227][BP-1.15][table-planner] Fix LEAST/GREATEST to return primitives

docs/content.zh/docs/connectors/datastream/elasticsearch.md, docs/content/docs/connectors/datastream/elasticsearch.md
(cherry picked from commit 9a3524008c4a2d955ccafb6e2ece39db37c2e3df)
This is an unchanged backport of https://github.com/apache/flink/pull/19200
=> [FLINK-26281][BP 1.15][connectors/elasticsearch] Improve documentation

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StopWithSavepoint.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/stopwithsavepoint/StopWithSavepointStoppingException.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/SavepointITCase.java, flink-tests/src/test/java/org/apache/flink/test/scheduling/AdaptiveSchedulerITCase.java
This is an equivalent of #19198 for adaptive scheduler
Run `org.apache.flink.test.checkpointing.SavepointITCase#testStopWithSavepointFailsOverToSavepoint` with adaptive scheduler enabled.
- The runtime per-record code paths (performance sensitive): (yes / **no /** don't know) …
=> [FLINK-26923] Do not trigger global failover if failed during commiting side-effects during stop-with-savepoint for adaptive scheduler

flink-runtime/src/test/java/org/apache/flink/runtime/rest/RestServerSSLAuthITCase.java
Fix clinet typo in RestServerSSLAuthITCase class in tests section in `flink-runtime` module
Replace clinet in the constructor of the RestServerSSLAuthITCase class with client
- The runtime per-record code paths (performance sensitive): (no / don't know) …
=> [hotfix][runtime][tests] Modify spelling error in RestServerSSLAuthITCase.java

flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/CsvRowDataDeserializationSchema.java
The `csvSchema` field was wrongly initialized.
=> [hotfix] Fix CsvRowDataDeserializationSchema constructor

flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestEnvironmentImpl.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableTestBase.java
This pull request removes unnecessary Docker network creation in Kafka connector tests.
- Remove unnecessary Docker network creation in Kafka connector tests
This change is already covered by existing Kafka connector tests. …
=> [FLINK-26928][connector/kafka] Remove unnecessary Docker network creation in tests

flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java
`testJobFailureWhenTaskExecutorHeartbeatTimeout` failed due to a heartbeat
being processed during the test. The missing payload of the test
implementation caused an unexpected error. Increasing the heartbeat
interval to a higher value should prevent this test from failing
because of an unexpected heartbeat.
* Increased the heartbeat interval. This won't prevent the initial heartbeat (which is ok, because no Executions are scheduled, yet) but let's the next heartbeat being scheduled long time in the future.  …
=> [FLINK-26798][runtime] Hardens test against unexpected heartbeat

flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestEnvironmentImpl.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableTestBase.java
Unchanged back port of #19282 on release-1.15
=> [BP-1.15][FLINK-26928][connector/kafka] Remove unnecessary docker network creation in tests and close network on shutdown()

flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaDynamicTableFactoryTest.java, flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/AkkaRpcActorTest.java, flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/core/testutils/FlinkAssertions.java
This PR improves a bit the assertion error when using `anyCauseMatches`.
It also removes the `containsCause` method, which is a misleading (as `contains` is used in assertj lingo to refer to search in a list through equality) and was agreed to not be introduced here https://github.com/apache/flink/pull/17932#pullrequestreview-819921970
=> [hotfix][test-utils-junit] Improve assertion errors

flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/ZKCheckpointIDCounterMultiServersTest.java, tools/ci/log4j.properties
There was a connection issue again with ZK that supposedly caused the IDCounter to be incremented once too often.
* I fixed the issue in the same way it was done in FLINK-26120.
* Additionally, I extended the ci log4j properties to log also request handling on the ZK server side
A CI run with a forced ZK test failure was added temporarily to verify the log4j configuration changes. …
=> [FLINK-26797][runtime] Hardens ZKCheckpointIDCounterMultiServersTest

flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/ZKCheckpointIDCounterMultiServersTest.java, tools/ci/log4j.properties
1.14 backport of parent PR #19199
=> [FLINK-26797][BP-1.14][runtime] Hardens ZKCheckpointIDCounterMultiServersTest

flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/config/PulsarClientFactory.java, flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/config/PulsarConfiguration.java, flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/PulsarSinkBuilder.java, flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/config/PulsarSinkConfigUtils.java, flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/writer/PulsarWriter.java, flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/PulsarSourceBuilder.java, flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/config/PulsarSourceConfigUtils.java, flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/sink/PulsarSinkITCase.java
Fix the bug of using same producer name and consumer name in pulsar connector. Pulsar would treat them as same instance which causes failure.
- Make producer name unique.
- Make consumer name unique.
- Better auth params setting.
This change is already covered by existing tests, such as `PulsarSinkITCase`. …
=> [FLINK-26931][Connector/pulsar] Make the producer name and consumer name unique in Pulsar

tools/azure-pipelines/jobs-template.yml, tools/ci/stage.sh
The libraries profile spends more time on setting up the environment than actually running tests. Merge it with Core for more efficiency.
=> [FLINK-26994][ci] Merge Core/Libraries CI profiles

flink-connectors/flink-connector-cassandra/pom.xml, flink-connectors/flink-connector-kafka/pom.xml, flink-connectors/flink-connector-pulsar/pom.xml, flink-python/pom.xml, pom.xml
Removes unnecessary special surefire configurations and models as much as possible as environment variables to make things easier to extend.
=> [FLINK-27024][build] Cleanup surefire configuration

flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/writer/topic/TopicMetadataListener.java, flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/subscriber/impl/BasePulsarSubscriber.java, flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/subscriber/impl/TopicListSubscriber.java, flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/topic/TopicNameUtils.java, flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/sink/writer/topic/TopicMetadataListenerTest.java, flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/enumerator/subscriber/PulsarSubscriberTest.java, flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/PulsarRuntimeOperator.java
Fix FLINK-26645: When users specify only consume from 1 partition but the source consumes from all partitions.
- changed TopicListSubscriber implementation.
- added a test case to validate it has been fixed.
- run PulsarSubscriberTest#subscribeOnePartitionOfMultiplePartitionTopic()
No
No
=> [FLINK-26645][Connector/Pulsar] Fix Pulsar source subscriber consume from all partitions when only subscribed to 1 partition

docs/layouts/shortcodes/generated/metric_configuration.html, docs/layouts/shortcodes/generated/metric_reporters_section.html, flink-core/src/main/java/org/apache/flink/configuration/ConfigurationUtils.java, flink-core/src/main/java/org/apache/flink/configuration/MetricOptions.java, flink-end-to-end-tests/test-scripts/common.sh, flink-end-to-end-tests/test-scripts/test_resume_externalized_checkpoints.sh, flink-end-to-end-tests/test-scripts/test_resume_savepoint.sh, flink-end-to-end-tests/test-scripts/test_rocksdb_state_memory_control.sh, flink-end-to-end-tests/test-scripts/test_stateful_stream_job_upgrade.sh, flink-end-to-end-tests/test-scripts/test_stream_state_ttl.sh, flink-metrics/flink-metrics-prometheus/src/test/java/org/apache/flink/metrics/prometheus/PrometheusReporterTest.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricRegistryImpl.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/ReporterSetup.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/filter/DefaultMetricFilter.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/filter/MetricFilter.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/ReporterScopedSettings.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/MetricRegistryImplTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/filter/DefaultMetricFilterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/FrontMetricGroupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/MetricGroupTest.java
This PR introduces 2 new configuration options that allow users to define filters for each reporter that control whether a given metric is passed to the reporter or not.
Effectively this allows the user to select the metrics to be reported.
=> [FLINK-21585][metrics] Add options for in-/excluding metrics 

flink-runtime/src/main/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStore.java, flink-runtime/src/test/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStoreTest.java
This livelock can happen in situations where an entry was marked
for deletion but is not deleted, yet. There's actually no reason to retry 
in case of a concurrent deletion. See FLINK-26987's description for 
further analysis
* Removes the goto statement
* Adds a test to cover that case (this test would run into an infinite loop with the old implementation) …
=> [FLINK-26987][runtime] Fixes getAllAndLock livelock

flink-runtime/src/main/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStore.java, flink-runtime/src/test/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStoreTest.java
This is a 1.15 backport of PR #19327
=> [FLINK-26987][BP-1.15][runtime] Fixes getAllAndLock livelock

docs/content.zh/docs/connectors/datastream/formats/parquet.md
Unchanged backport of https://github.com/apache/flink/pull/18646
=> [FLINK-25797][BP 1.15][Docs] Translate datastream/formats/parquet.md page into Chinese

flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaSink.java, flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaSinkBuilder.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaSinkBuilderTest.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaDynamicTableFactoryTest.java
Introduce setProperty method to KafkaSinkBuilder to align it with source builder.
- *Added setProperty method*
Added KafkaSinkBuilderTest to test new functionality + modified existing tests to cover this 
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: Yes
- Does this pull request introduce a new feature? yes 
- If yes, how is the feature documented?  javadoc
=> [FLINK-26368] [kafka] Add setProperty method to KafkaSinkBuilder

flink-core/src/main/java/org/apache/flink/core/fs/local/LocalDataOutputStream.java, flink-core/src/test/java/org/apache/flink/core/fs/local/LocalFileSystemTest.java, flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/FileSystemJobResultStore.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/SnappyStreamCompressionDecorator.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/StreamCompressionDecorator.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/UncompressedStreamCompressionDecorator.java, flink-runtime/src/main/java/org/apache/flink/runtime/util/ForwardingOutputStream.java, flink-runtime/src/main/java/org/apache/flink/runtime/util/NonClosingOutputStreamDecorator.java
The `writeValue` calls close by default internally. Calling flush afterwards
could cause errors. It's also not really necessary. OutputStream.flush does
not guarantee persistence according to its JavaDoc. In contrast, calling
close does guarantee it.
Some FileSystem implementations fail when calling flush on a closed OutputStream (e.g. HDFS).
To cover this behavior in the tests, we added this check to the `LocalDataOutputStream`.
* Removes the flush call: The data is persisted as part of the `OutputStream.close` call as stated in the [JavaDoc](https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/ObjectMapper.html#writeValue(java.io.OutputStream,%20java.lang.Object))
* Added asserts to `LocalDataOutputStream` to cover this behavior in tests.
* Adds unit …
=> [FLINK-26957][runtime] Removes flush in FileSystemJobResultStore.createDirtyResultInternal

flink-core/src/main/java/org/apache/flink/core/fs/local/LocalDataOutputStream.java, flink-core/src/test/java/org/apache/flink/core/fs/local/LocalFileSystemTest.java, flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/FileSystemJobResultStore.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/SnappyStreamCompressionDecorator.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/StreamCompressionDecorator.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/UncompressedStreamCompressionDecorator.java, flink-runtime/src/main/java/org/apache/flink/runtime/util/NonClosingOutputStreamDecorator.java
1.15 backport (excluding some minor hotfix commits) for parent PR #19304
=> [FLINK-26957][BP-1.15][runtime] Removes flush in FileSystemJobResultStore.createDirtyResultInternal 

flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java
There's no guarantee that the cleanup is initiated synchronously.
=> [FLINK-27047][tests] Remove timeouts

flink-formats/flink-avro-glue-schema-registry/src/test/java/org/apache/flink/formats/avro/glue/schema/registry/GlueSchemaRegistryAvroDeserializationSchemaTest.java, flink-formats/flink-avro-glue-schema-registry/src/test/java/org/apache/flink/formats/avro/glue/schema/registry/GlueSchemaRegistryAvroSchemaCoderTest.java, flink-formats/flink-avro-glue-schema-registry/src/test/java/org/apache/flink/formats/avro/glue/schema/registry/GlueSchemaRegistryAvroSerializationSchemaTest.java, flink-formats/flink-avro-glue-schema-registry/src/test/java/org/apache/flink/formats/avro/glue/schema/registry/GlueSchemaRegistryInputStreamDeserializerTest.java, flink-formats/flink-avro-glue-schema-registry/src/test/java/org/apache/flink/formats/avro/glue/schema/registry/GlueSchemaRegistryOutputStreamSerializerTest.java, flink-formats/flink-avro-glue-schema-registry/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension, flink-formats/flink-json-glue-schema-registry/src/test/java/org/apache/flink/formats/json/glue/schema/registry/GlueSchemaRegistryJsonDeserializationSchemaTest.java, flink-formats/flink-json-glue-schema-registry/src/test/java/org/apache/flink/formats/json/glue/schema/registry/GlueSchemaRegistryJsonSchemaCoderTest.java, flink-formats/flink-json-glue-schema-registry/src/test/java/org/apache/flink/formats/json/glue/schema/registry/GlueSchemaRegistryJsonSerializationSchemaTest.java, flink-formats/flink-json-glue-schema-registry/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Update the `flink-formats/flink-avro-glue-schema-registry` and `flink-formats/flink-json-glue-schema-registry` module to AssertJ and JUnit 5 following the [JUnit 5 Migration Guide](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit)
This was an easy change: it was already based on AssertJ …
=> [FLINK-27046][tests][JUnit5 migration] flink-X-glue-schema-registry

flink-python/pyflink/datastream/tests/test_data_stream.py
[FLINK-27068] test_keyed_min_and_max and test_keyed_min_by_and_max_by failed in py36,37
This PR will fix it.
- Set parallelism to 1 in unit test case to avoid the deterministic introduced of order.
Passed in pytest (Local env)、flake8
=> [FLINK-27068][python][tests] Fix test_keyed_min_and_max and test_keyed_min_by_and_max_by failed in py36,37

flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/connector/datagen/table/DataGenTableSource.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/table/DataGeneratorConnectorITCase.java
Support limit push down in DATAGEN connector.
- Support limit push down in DATAGEN connector.
Apply `LIMIT` in datagen table query, see `DataGeneratorConnectorITCase#testLimit`.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / **don't know**) …
=> [FLINK-25379][connectors] Support limit push down in DATAGEN connector

flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/table/IndexGeneratorFactory.java, flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/IndexGeneratorFactory.java, flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/connector/elasticsearch/table/IndexGeneratorTest.java, flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/IndexGeneratorFactoryTest.java
Dynamic indexes generated by the `IndexGeneratorFactory` ignore the local timezone and emit UTC timezone information instead. This PR fixes the issue by using the local timezone instead.
This PR will also need to be backported to 1.15
- Changed behavior for Sink-based and SinkFunction-based connector
- Added/Adjusted tests
This change is already covered by existing tests, such as `testDynamicIndexDefaultFormatTimestampWithLocalTimeZone` and the newly introduced test …
=> [FLINK-26810][connectors/elasticsearch] Use local timezone for TIMESTAMP_WITH_LOCAL_TIMEZONE fields in dynamic index

flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/table/IndexGeneratorFactory.java, flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/IndexGeneratorFactory.java, flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/connector/elasticsearch/table/IndexGeneratorTest.java, flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/IndexGeneratorFactoryTest.java
Unchanged backport of #19302 for 1.15
=> [FLINK-26810][connectors/elasticsearch] Use local timezone for TIMETAMP_WITH_LOCAL_TIMEZONE fields in dynamic index

flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/logging/TestLoggerResource.java, flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/logging/TestLoggerResourceTest.java
Fix and test behavior of TestLoggerResource when multiple logger are used simultaneously.
See https://issues.apache.org/jira/browse/FLINK-26710
- run TestLoggerResourceTest
=> [FLINK-26710] fix TestLoggerResource

flink-clients/src/main/java/org/apache/flink/client/program/rest/RestClusterClient.java, flink-core/src/main/java/org/apache/flink/util/concurrent/FutureUtils.java, flink-core/src/test/java/org/apache/flink/util/concurrent/FutureUtilsTest.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/RescalingITCase.java
=> [FLINK-27122] Remove FutureUtils#retryWithDelay variants without RetryStrategy

docs/content.zh/docs/ops/metrics.md, docs/content/docs/ops/metrics.md
Fix metric type of ChangelogStorage.uploadQueueSize in document.  see : [FLINK-27105](https://issues.apache.org/jira/browse/FLINK-27105)
=> [FLINK-27105][docs] fix ChangelogStorage.uploadQueueSize metric type

flink-connectors/flink-connector-jdbc/pom.xml, flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/dialect/psql/PostgresTypeMapper.java, flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/converter/PostgresRowConverter.java, flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/catalog/PostgresCatalogITCase.java
* Update PostgreSQL to the latest available version to address CVE-2022-21724 and GHSA-673j-qm5f-xpv8
* Updated POM
=> [FLINK-25926][Connectors][JDBC] Update org.postgresql:postgresql to 42.3.3

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/PendingCheckpoint.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/PendingCheckpointTest.java
CheckpointCoordinator.isTriggering can not be reset if a checkpoint expires while the checkpointCoordinator task is queuing in the SourceCoordinator executor. Once the issue happens the job can never recover until restarted. This PR is fixing this issue.
- Throw timeout exception if the checkpoint completable future expires. The timeout is same as the checkpoint timeout.
Tests will be added later.
- Does …
=> [FLINK-26394] CheckpointCoordinator.isTriggering can not be reset in a particular case.

flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/mailbox/MailboxMetricsController.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/mailbox/MailboxProcessor.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/mailbox/TaskMailboxProcessorTest.java
* Fix performance regression from mailbox latency measuement
* __Note:__ The performance implications, i.e., recovery of performance values, are documented in https://issues.apache.org/jira/browse/FLINK-26864. (Please review the performance results in the linked issue.) 
* Trigger mailbox latency measurement from `MailboxProcessor` class instead from `StreamTask` class. This way, measurement can be initiated selectively only when mails are executed which is, in particular, on any non-poison mail.
* To resolve cyclic dependencies between `MailboxProcessor` which starts mailbox measurement with `StreamTask` which holds references to `MailboxExecutor` and `TimerServices` that are both needed for scheduling mailbox latency measurements an additional class `MailboxMetricsController` is …
=> [FLINK-26864][metrics] Fix performance regression from mailbox latency measuement

flink-runtime-web/web-dashboard/src/app/app.interceptor.ts
```
- don't hide after a timeout (was: 4.5s)
- expand the message box
```
This allows for example to clearly see what the arguments the program is missing on submission.
=> [FLINK-27150][runtime-web] Improve error message rendering

docs/layouts/shortcodes/generated/rocksdb_configurable_configuration.html, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/EmbeddedRocksDBStateBackend.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBConfigurableOptions.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBIncrementalCheckpointUtilsTest.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateBackendConfigTest.java
*`state.backend.rocksdb.restore-overlap-fraction-threshold` is used to control how to restore a state handle, different thresholds can affect the performance of restoring. Currently, the default value is 0.75,  this PR wants to change the default value to 0.*
Here is a comparison between `0` and `0.75` based on [rescaling benchmark](https://github.com/apache/flink-benchmarks/pull/23).  Since `deleteRange()` takes less time than creating a new RocksDB instance and then scan-and-put the records,  we can see that threshold `0` is much better than `0.75`.
  | rescale type | number of keys | key len | value len | state size | delete type | overlap threshold | time(ms/op)
-- | -- | -- | -- | -- | -- | -- | -- | --
1 | 1->2 | 10M | 96 | 128 | ~=2.2GB | native deleteRange | 0 | 1811.478 ± 82.262 …
=> [FLINK-26757][state] Change the default value of state.backend.rocksdb.restore-overlap-fraction-threshold to 0

flink-python/src/test/java/org/apache/flink/streaming/api/utils/ByteArrayWrapperSerializerTest.java
The removed case was overly expensive, able to consume 1gb of heap space on it's own.
=> [FLINK-27035][python][tests] Reduce memory usage of ByteArrayWrapperSerializerTest

flink-end-to-end-tests/run-nightly-tests.sh, flink-tests/pom.xml, pom.xml, tools/ci/compile.sh, tools/ci/test_controller.sh
This property no longer provides any value because not only has it been identical to flink.forkCount for as long as I can remember, various other modules now contain tests that are likely even heavier than flink-tests.
=> [FLINK-27224][build] Drop 'flink.forkCountTestPackage' property

flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/AbstractDispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherCleanupITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/TestingDispatcher.java
Having a default RpcSystem in TestingDispatcher.Builder
caused threads being spawned without cleanup. Instead, we
should rely on the RpcSystem instance provided by the test.
* Removed the default instance from TestingDispatcher.Builder and made it a required parameter through the `build` method
* Running a test manually in a loop and checking that there are no threads left hanging, e.g. in `DispatcherCleanupResourcesTest`:
```
@Test
public void foo() throws Exception {
for (int i = 0; i < 100; i++) {
setup();
testDuplicateJobSubmissionDoesNotDeleteJobMetaData();
teardown();
}
System.out.println("Stop the debugger here");
}
```
- …
=> [FLINK-27050][runtime] Removes default RpcSystem instance

flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/MiniDispatcher.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
Prevents the main thread from doing a potentially long running operation, moving it instead to the io executor.
Needed to adjust some tests to rely on the runner termination future instead of the job result future, as the latter does not guarantee that the runner is cleaned up, which is required for these tests to pass because the mocked JMRunner doesn't implement all required methods (and if the runner is terminated then the dispatcher handles everything).
This was previously fine because the job execution, job termination and runner termination happened synchronously by virtue of all futures already being completed and us never switching executors.
=> [FLINK-27140][coordination] Write job result in ioExecutor 

flink-filesystems/flink-s3-fs-presto/pom.xml, flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE
* Updated presto to the latest version due to GSON bug
- Updated prosto library to `.272`
- The S3 file system connector: yes 
=> [FLINK-25694][FileSystems][S3] Upgrade Presto to resolve GSON/Alluxio Vulnerability

docs/content.zh/docs/dev/configuration/overview.md
[FLINK-27120](https://issues.apache.org/jira/browse/FLINK-27120)  "Gradle" tab of "Application Development > Project Configuration > Overview" to Chinese.
related [PR](https://github.com/apache/flink/pull/18609).
=> [FLINK-27120][docs-zh] Translate "Gradle" tab of development > conf > overview

flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/Execution.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionVertex.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultScheduler.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ExecutionVertexTest.java
Prevents loss of information that is critical to local recovery due to evictions from the execution history.
Previously a fast restart loop on TM loss could result in local recovery never kicking in because all the information was lost.
Instead we store the last (al)location in the vertex.
=> [FLINK-27222][coordination] Decouple last (al)location from execution history

docs/content.zh/docs/connectors/datastream/pubsub.md
We can see from the above picture that compared with the English document, the Chinese document has a part that is irrelevant to the content.
Fix "Google Cloud PubSub" Chinese page under "DataStream Connectors"
=> [hotfix][docs-zh] Fix "Google Cloud PubSub" Chinese page under "DataStream Connectors"

docs/content.zh/docs/ops/state/state_backends.md, docs/content/docs/ops/state/state_backends.md
Translate ChangelogBackend documentation to chinese.
- Dependencies (does it add or upgrade a dependency): yes (internal: flink-docs -> flink-dstl-dfs)
- If yes, how is the feature documented? (see above)
=> [FLINK-25867][docs] translate ChangelogBackend documentation to chinese

flink-table/flink-sql-parser-hive/pom.xml, flink-table/flink-sql-parser/pom.xml
AFAICT these are just unnecessary, and were likely just copied from elsewhere.
=> [FLINK-27250][sql][build] Remove custom surefire config

flink-connectors/flink-connector-hive/pom.xml
These are unnecessary and we can improve testing times.
=> [FLINK-27252][hive][build] Remove surefire fork settings

docs/content/docs/connectors/datastream/filesystem.md
in filesystem.md, flink comes with four built-in BulkWriter factories, in fact, the list has five.
in filesystem.md, flink comes with four built-in BulkWriter factories, in fact, the list has five.
yes
=> [FLINK-27265][docs] Flink comes with five built-in BulkWriter factories instead of the mentioned four in filesystem.md.

flink-connectors/flink-connector-cassandra/pom.xml, flink-dist/pom.xml, flink-kubernetes/pom.xml
reuseForks is true by default so some settings are redundant. flink-dist contains no unit tests that would justify disabling reuseForks.
=> [FLINK-27225][build] Remove redundant reuseForks settings 

flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestBase.java, flink-metrics/flink-metrics-jmx/src/test/java/org/apache/flink/runtime/jobmanager/JMXJobManagerMetricTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/ReporterSetupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/AbstractMetricGroupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/MetricGroupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/util/TestReporter.java
Configuring the reporter factory class is the recommended way to configure a reporter.
=> [FLINK-24236] Migrate tests to factory approach

flink-connectors/flink-connector-cassandra/pom.xml
The test-scoped dependency is unnecessary. For production we use the transitive netty dependency, whose version is controlled via the netty-bom in the parent pom.
=> [FLINK-27229][cassandra][build] Remove test netty dependency

flink-connectors/flink-hadoop-compatibility/pom.xml, flink-connectors/flink-hcatalog/pom.xml, flink-end-to-end-tests/flink-end-to-end-tests-scala/pom.xml, flink-end-to-end-tests/flink-quickstart-test/pom.xml, flink-examples/flink-examples-batch/pom.xml, flink-examples/flink-examples-streaming/pom.xml, flink-examples/flink-examples-table/pom.xml, flink-libraries/flink-cep-scala/pom.xml, flink-libraries/flink-gelly-examples/pom.xml, flink-libraries/flink-gelly-scala/pom.xml, flink-scala/pom.xml, flink-streaming-scala/pom.xml, flink-table/flink-table-api-scala-bridge/pom.xml, flink-table/flink-table-api-scala/pom.xml, flink-table/flink-table-planner/pom.xml, flink-tests/pom.xml, pom.xml
Resolves the issue of spotless no longer working when being run in sub-directories by explicitly configuring the scala settings (specifically the path to the config file) in each module that has scala code.
This PR supports all the usual developer workflows, like calling `mvn spotless:[check|apply]` or `mvn install`, in both the parent and sub-directories.
=> [FLINK-27232][build] Explicitly configure scalafmt in each module (the boring version)

flink-contrib/flink-connector-wikiedits/src/test/java/org/apache/flink/streaming/connectors/wikiedits/WikipediaEditsSourceTest.java, flink-contrib/flink-connector-wikiedits/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Migrate tests to JUnit5
Migrate tests to JUnit5
=> [FLINK-27267][contrib] Migrate tests to JUnit5

flink-table/flink-sql-client/pom.xml, flink-table/flink-sql-client/src/main/resources/META-INF/NOTICE
The PR updates jline3 to 3.21.0
It brings a number of features which could be used in FLIP-189
like rgb 
support in style (could be used for prompts and highlighting)
line numbers support in prompt continuation
autopairing, display hints during completion
This is just a version update, so only existing tests …
=> [FLINK-25109][Table SQL/Client] Update jline3 to 3.21.0

docs/content.zh/docs/dev/table/sqlClient.md, docs/content/docs/dev/table/sqlClient.md
This pull request fix table name inconsistency problem in sqlClient.md.
fix table name inconsistency problem in sqlClient.md.
yes
=> [FLINK-27298][Docs] Change the used table name in the SQL Client documentation to the correct name

flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/sink/FileSinkCompactionSwitchITCase.java, flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/sink/FileSinkITBase.java, flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/sink/writer/FileSinkMigrationITCase.java, flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/util/JobManagerWatermarkTrackerTest.java, flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroExternalJarProgramITCase.java, flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniClusterConfiguration.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/FileExecutionGraphInfoStoreTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/MemoryExecutionGraphInfoStoreITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/FileBufferReaderITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/minicluster/MiniClusterITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/CoordinatorEventsExactlyOnceITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/shuffle/ShuffleMasterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorITCase.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/coordination/OperatorEventSendingCheckpointITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/CheckpointRestoreWithUidHashITCase.java, flink-tests/src/test/java/org/apache/flink/test/runtime/DefaultSchedulerLocalRecoveryITCase.java, flink-tests/src/test/java/org/apache/flink/test/runtime/JobGraphRunningUtil.java, flink-tests/src/test/java/org/apache/flink/test/runtime/SchedulingITCase.java, flink-tests/src/test/java/org/apache/flink/test/scheduling/PipelinedRegionSchedulingITCase.java
- migrates some tests to MiniClusterResources (where it was easy to do so)
- introduces MiniClusterConfiguration#withRandomPorts
- this gives us a single point where we can configure ports in the future
=> [FLINK-27287][tests] Use random ports 

flink-connectors/flink-connector-elasticsearch6/pom.xml, flink-connectors/flink-connector-elasticsearch7/pom.xml, flink-connectors/flink-connector-hbase-1.4/pom.xml, flink-connectors/flink-connector-hbase-2.2/pom.xml, flink-connectors/flink-connector-kafka/pom.xml, flink-connectors/flink-connector-pulsar/pom.xml, flink-kubernetes/pom.xml
Chances are these forkCount settings have just been carried forward for years and copied into new modules.
They are likely unnecessary, and just result in slower CI.
=> [FLINK-27325][build] Remove custom forkCount settings

docs/content.zh/docs/deployment/metric_reporters.md, docs/content/docs/deployment/metric_reporters.md, docs/layouts/shortcodes/generated/metric_configuration.html, docs/layouts/shortcodes/generated/metric_reporters_section.html, flink-core/src/main/java/org/apache/flink/configuration/MetricOptions.java, flink-end-to-end-tests/flink-metrics-reporter-prometheus-test/src/test/java/org/apache/flink/metrics/prometheus/tests/PrometheusReporterEndToEndITCase.java, flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/metrics/reporter/InstantiateViaFactory.java, flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/metrics/reporter/InterceptInstantiationViaReflection.java, flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/metrics/reporter/MetricReporter.java, flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/metrics/reporter/MetricReporterFactory.java, flink-metrics/flink-metrics-datadog/src/main/java/org/apache/flink/metrics/datadog/DatadogHttpReporter.java, flink-metrics/flink-metrics-datadog/src/main/java/org/apache/flink/metrics/datadog/DatadogHttpReporterFactory.java, flink-metrics/flink-metrics-graphite/src/main/java/org/apache/flink/metrics/graphite/GraphiteReporter.java, flink-metrics/flink-metrics-graphite/src/main/java/org/apache/flink/metrics/graphite/GraphiteReporterFactory.java, flink-metrics/flink-metrics-influxdb/src/main/java/org/apache/flink/metrics/influxdb/InfluxdbReporter.java, flink-metrics/flink-metrics-influxdb/src/main/java/org/apache/flink/metrics/influxdb/InfluxdbReporterFactory.java, flink-metrics/flink-metrics-jmx/src/main/java/org/apache/flink/metrics/jmx/JMXReporter.java, flink-metrics/flink-metrics-jmx/src/main/java/org/apache/flink/metrics/jmx/JMXReporterFactory.java, flink-metrics/flink-metrics-prometheus/src/main/java/org/apache/flink/metrics/prometheus/PrometheusPushGatewayReporter.java, flink-metrics/flink-metrics-prometheus/src/main/java/org/apache/flink/metrics/prometheus/PrometheusPushGatewayReporterFactory.java, flink-metrics/flink-metrics-prometheus/src/main/java/org/apache/flink/metrics/prometheus/PrometheusReporter.java, flink-metrics/flink-metrics-prometheus/src/main/java/org/apache/flink/metrics/prometheus/PrometheusReporterFactory.java, flink-metrics/flink-metrics-slf4j/src/main/java/org/apache/flink/metrics/slf4j/Slf4jReporter.java, flink-metrics/flink-metrics-slf4j/src/main/java/org/apache/flink/metrics/slf4j/Slf4jReporterFactory.java, flink-metrics/flink-metrics-statsd/src/main/java/org/apache/flink/metrics/statsd/StatsDReporter.java, flink-metrics/flink-metrics-statsd/src/main/java/org/apache/flink/metrics/statsd/StatsDReporterFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/ReporterSetup.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/ReporterSetupTest.java
Based on #17228.
Metric reporters can currently be instantiated in one of 2 ways:
a) the reporter class is loaded via reflection
b) the reporter factory is loaded via reflection/ServiceLoader (aka, plugins)
All reporters provided by Flink use the factory approach, and it is preferable because it supports plugins. The plugin approach also has been available 1.11, and I think it's fair to deprecate the old approach by now.
=> [FLINK-27206][metrics] Deprecate reflection-based reporter instantiation 

flink-table/flink-sql-parser-hive/pom.xml, flink-table/flink-sql-parser-hive/src/test/java/org/apache/flink/sql/parser/hive/FlinkHiveSqlParserImplTest.java, flink-table/flink-sql-parser-hive/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension, flink-table/flink-sql-parser/pom.xml, flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/CreateTableLikeTest.java, flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkDDLDataTypeTest.java, flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java, flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlUnParserTest.java, flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/ReservedKeywordTest.java, flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/TableApiIdentifierParsingTest.java, flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/TestRelDataTypeFactory.java, flink-table/flink-sql-parser/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Update the flink-table/flink-sql-parser and flink-table/flink-sql-parser-hive modules to AssertJ and JUnit 5 following the [JUnit 5 Migration Guide](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit) …
=> [FLINK-25548][flink-sql-parser] Migrate tests to JUnit5

flink-architecture-tests/flink-architecture-tests-production/pom.xml
got "javadoc: error - class file for org.junit.platform.commons.annotation.Testable not found" error while performing javadoc-plugin.
- change the junit-jupiter dependency scope to compile
mvn javadoc:javadoc works without error. …
=> [FLINK-27167][test] fix javadoc issue

docs/content.zh/docs/dev/table/types.md, docs/content/docs/dev/table/types.md
1.14 backport PR of parent PR https://github.com/apache/flink/pull/17505. Cherry-picking worked without conflicts.
=> [BP-1.14][hotfix][docs] Misprint in types.md

docs/content.zh/docs/dev/table/types.md, docs/content/docs/dev/table/types.md
1.15 backport PR of parent PR https://github.com/apache/flink/pull/17505. Cherry-picking worked without conflicts.
=> [BP-1.15][hotfix][docs] Misprint in types.md

docs/content.zh/docs/ops/metrics.md, docs/content/docs/ops/metrics.md, flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/BatchingStateChangeUploadScheduler.java, flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/ChangelogStorageMetricGroup.java, flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/RetryingExecutor.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/BatchingStateChangeUploadSchedulerTest.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/ChangelogStorageMetricsTest.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/RetryingExecutorTest.java
As [FLINK-27187](https://issues.apache.org/jira/browse/FLINK-27187) discussed, add changelog storage metric "totalAttemptsPerUpload" representing the total number distributions of attempts per upload. 
- add totalAttemptsPerUpload to ChangelogStorageMetricGroup
- RetryingExecutor record total attempts and update totalAttemptsPerUpload with it
- *Added test ChangelogStorageMetricGroup.testTotalAttemptsPerUpload() that validates that totalAttemptsPerUpload calculate correctly* …
=> [FLINK-27187][state/changelog] Add changelog storage metric totalAttemptsPerUpload

flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplit.java
HybridSourceSplit's wrappedSplit should use Arrays.hashCode because wrappedSplit has been changed from `SourceSplit` object to serialized wrappedBytes array.
Correct HybridSourceSplit hashCode method.
This change is already covered by existing tests, such as `HybridSourceSplitSerializerTest`, `HybridSourceSplitEnumeratorTest`. …
=> [FLINK-27381][connector/common] Use Arrays.hashcode for HybridSourceSplit wrappedSplitBytes

flink-clients/src/main/java/org/apache/flink/client/deployment/application/ApplicationDispatcherBootstrap.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java
With this change, the job won't be terminated until the archiving of its ExecutionGraphInfo finishes.
- *Added unit tests that validates that the waiting works well.* …
=> [FLINK-24491][runtime] Make the job termination wait until the archiving of ExecutionGraphInfo finishes

flink-runtime/src/test/java/org/apache/flink/runtime/metrics/ReporterSetupTest.java, flink-runtime/src/test/resources/META-INF/services/org.apache.flink.metrics.reporter.MetricReporterFactory
This reduces noise in other tests/modules that use reporters.
=> [FLINK-24222] Migrate ReporterSetupTest to ContextClassLoaderExtension 

flink-filesystems/flink-azure-fs-hadoop/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-fs-hadoop-shaded/pom.xml, flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-oss-fs-hadoop/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-s3-fs-base/pom.xml, flink-filesystems/flink-s3-fs-hadoop/src/main/java/org/apache/flink/fs/s3hadoop/HadoopS3AccessHelper.java, flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE, flink-filesystems/pom.xml
Flink currently uses Hadoop version 3.2.2 for the Flink filesystem implementations. Upgrading this to version 3.3.2 would provide users the features listed in [HADOOP-17566](https://issues.apache.org/jira/browse/HADOOP-17566)
* Update POM file and NOTICE files …
=> [FLINK-27308][Filesystem][S3] Update the Hadoop implementation for filesystems to 3.3.2

flink-end-to-end-tests/run-nightly-tests.sh, pom.xml, tools/ci/compile.sh, tools/ci/test_controller.sh
Additionally mark TaskExecutorRecoveryTest as an ITCase due to memory consumption and starting up TaskManagers
Purpose of this change is to decrease build times via increasing forkCounts.
Covered by existing test base.
- …
=> [FLINK-27209][build] Half the memory and double forkCount for running unit tests

tools/azure-pipelines/jobs-template.yml, tools/ci/stage.sh
Move as much out of misc as possible, and balance the 2 connectors profiles.
-> runtime
* gelly
* statebackends
* dstl
* queryable-state
-> connectors -> connectors_1
* remaining filesystems/formats
* hbase
-> kafka/gelly -> connectors_2
* pubsub
* pulsar
* rabitmq
* aws
-> misc
* architecture-tests
=> [FLINK-27228][ci] Redistributed modules across CI profiles 

tools/maven/checkstyle.xml
Removes several checkstyle rules that afaict are covered by spotless. The goal is to reduce redundancy and avoid situations where the plugins might disagree in the future.
=> [FLINK-20808][build] Remove redundant checkstyle rules

flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaInvocationHandler.java, flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/TimeoutCallStackTest.java
To support the gradual migration of components to Duration we should allow the RpcTimeout annotation to also be used for Duration timeouts.
=> [FLINK-27431][rpc] Allow RpcTimeouts to be specified as Duration

docs/content.zh/docs/ops/metrics.md, docs/content/docs/ops/metrics.md, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/util/SystemResourcesCounter.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/util/SystemResourcesMetricsInitializer.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/utils/SystemResourcesCounterTest.java, flink-tests/src/test/java/org/apache/flink/runtime/metrics/SystemResourcesMetricsITCase.java, pom.xml
* Upgrade oshi-core to version 6.1.5 (according to FLINK-24804) which resolves one issue of building and testing Flink on Apple M1 (see FLINK-25505)
- Simply adapted to changed interface
- Update docs accordingly
- Fix calculation of CPU load to include steal time according to oshi-core docs: *"To calculate overall Idle time using this method, include both Idle and IOWait ticks. Similarly, IRQ, SoftIRQ and Steal ticks should be added to the System value to get the total. System ticks also include time executing other virtual hosts (steal)."*
* Tests have been in place covering the changes as we …
=> [FLINK-24804][FLINK-25505] Upgrade oshi-core to version 6.1.5

flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/MiniDispatcher.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
1.14 Backport PR of parent PR #19275
The commit `b3a9dcb` was cherry-picked but required some bigger changes because of the changes we applied to the Dispatcher in 1.15.
* The tests from the parent PR were added but required some refactoring
=> [BP-1.14][FLINK-24491][runtime] Make the job termination wait until the archiving of ExecutionGraphInfo finishes

flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/AkkaRpcActorHandshakeTest.java, flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/AkkaRpcActorOversizedResponseMessageTest.java, flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/AkkaRpcActorTest.java, flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/AkkaRpcServiceTest.java, flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/ContextClassLoadingSettingTest.java, flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/RemoteAkkaRpcActorTest.java, flink-rpc/flink-rpc-core/src/main/java/org/apache/flink/runtime/rpc/RpcUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/AbstractDispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherCleanupITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/MiniDispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterPartitionReleaseTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/ResourceManagerJobMasterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/ResourceManagerPartitionLifecycleTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/ResourceManagerServiceImplTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/ResourceManagerTaskExecutorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/ResourceManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rpc/AsyncCallsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rpc/FencedRpcEndpointTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rpc/RpcEndpointTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorExecutionDeploymentReconciliationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorPartitionLifecycleTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/retriever/impl/RpcGatewayRetrieverTest.java, flink-tests/src/test/java/org/apache/flink/test/recovery/JobManagerHAProcessFailureRecoveryITCase.java, flink-tests/src/test/java/org/apache/flink/test/recovery/ProcessFailureCancelingITCase.java
These methods are only used in tests. We could remove the timeouts (easing [FLINK-27426](https://issues.apache.org/jira/browse/FLINK-27426)), and should annotate them with @VisibleForTesting.
=> [FLINK-27427][rpc] Remove timeouts from RpcUtils#terminate*

flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaInvocationHandler.java, flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaRpcService.java, flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaRpcServiceConfiguration.java, flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/FencedAkkaInvocationHandler.java, flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/AkkaRpcActorHandshakeTest.java, flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/AkkaRpcActorTest.java, flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/AkkaRpcServiceTest.java, flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/ContextClassLoadingSettingTest.java, flink-rpc/flink-rpc-core/src/main/java/org/apache/flink/runtime/rpc/FencedMainThreadExecutable.java, flink-rpc/flink-rpc-core/src/main/java/org/apache/flink/runtime/rpc/FencedRpcEndpoint.java, flink-rpc/flink-rpc-core/src/main/java/org/apache/flink/runtime/rpc/MainThreadExecutable.java, flink-rpc/flink-rpc-core/src/main/java/org/apache/flink/runtime/rpc/RpcEndpoint.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/dump/MetricQueryService.java, flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/active/ActiveResourceManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerConfiguration.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/TestingDispatcher.java, flink-runtime/src/test/java/org/apache/flink/runtime/rpc/AsyncCallsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rpc/FencedRpcEndpointTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rpc/RpcEndpointTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/slot/ThreadSafeTaskSlotTable.java
Based on #19592.
Migrates the RPC system internals to use Duration instead of Time. The only exception is the special timeout handling for the RPC interfaces, which will be done later (as that requires touching all the runtime components).
=> [FLINK-27426][rpc] Migrate RPC system internals to Duration 

flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/MiniDispatcher.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/MiniDispatcherTest.java
In job mode, we triggered the shutdown as soon as the job reached a globally terminal state. This was fine in 1.14- because we didn't do any promises on the cleanup anyway. With 1.15, we introduced retries for cleanup which results in the final termination taking longer. During cluster shutdown the ResourceManager is informed about deregistering the cluster which results in the workers being shutdown in case of active RMs (i.e. k8s and YARN). See further details in FLINK-26772 (parent issue of this issue).
* removed overwriting of `Dispatcher#jobReachedTerminalState` in `MiniDispatcher`
* Introduced new method that is called when the job reached a globally terminal state which then gets implemented by `MiniDispatcher`
* I extended existing tests to verify that the shutdown happens after …
=> [FLINK-27382][runtime] Moves cluster shutdown to when the job cleanup is done in job mode

flink-runtime-web/web-dashboard/src/app/pages/job/overview/accumulators/job-overview-drawer-accumulators.component.html, flink-runtime-web/web-dashboard/src/app/pages/job/overview/backpressure/job-overview-drawer-backpressure.component.html, flink-runtime-web/web-dashboard/src/app/pages/job/overview/subtasks/job-overview-drawer-subtasks.component.html, flink-runtime-web/web-dashboard/src/app/pages/job/overview/taskmanagers/job-overview-drawer-taskmanagers.component.html, flink-runtime-web/web-dashboard/src/app/pages/job/overview/watermarks/job-overview-drawer-watermarks.component.html
Fixes hidden scrollbar for some UI elements, where CSS calculate was based on a percentage. The current Angular version has a bug, so in those cases the scrollbar is hidden and scrolling is not possible.
Relevant Angular issue: https://github.com/NG-ZORRO/ng-zorro-antd/issues/3090
Changed `calc ( X% ...)` to `calc( Xvh ...)`, which solves this problem.
Prepare a Flink job with a number of Accumulators that cannot fit to the tab, so scrolling is required. After running the job, the "Accumulators" tab has no scrollbar. The CSS can be changed in the browser, so it can be modified on the fly to try out the fix. …
=> [FLINK-27441][webfrontend] fix "nzScroll" calculations

.github/workflows/docs.sh, docs/setup_docs.sh
* Fix the currently broken documentation build pipeline
* Use different Git command (which is supported by the installed Git version on the Docker image)
* Upgrading Hugo and making sure that this is added to the PATH by extracting it to `/usr/local/bin` …
=> [FLINK-27485][Documentation][Build] Fix the documentation build pipeline

flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroRowDeserializationSchema.java
A small change to (deprecated) AvroRowDeserializationSchema to handle the conversion of a negative micros long value to `java.sql.Timestamp`
This was exposed in `AvroRowDeSerializationSchemaTest.testSpecificDeserializeFromSchemaSeveralTimes` when the test is run with local time zone with negative offset. 
micros: `-28799876544`
ts: `1969-12-31 16:00:00.123456`
=> [FLINK-27465] Handle conversion of negative long to timestamp in AvroRowDeserializationSchema

docs/content.zh/docs/ops/state/savepoints.md
Update Chinese documentation regarding FLIP-203
=> [FLINK-26052][docs-zh] Document savepoint format

docs/content.zh/docs/deployment/overview.md, docs/content/docs/deployment/overview.md
- Fix the inaccessible huawei cloud  link.
- Change the inaccessible https://www.huaweicloud.com/en-us/product/cs.html link in the "docs/content/docs/deployment/overview.md" to https://www.huaweicloud.com/intl/zh-cn/product/cs.html . 
- Change the inaccessible https://www.huaweicloud.com/en-us/product/cs.html link in the "docs/content.zh/docs/deployment/overview.md" to https://www.huaweicloud.com/intl/zh-cn/product/cs.html .  …
=> [hotfix][docs] Fix the inaccessible huawei cloud  link.

docs/layouts/shortcodes/generated/kubernetes_config_configuration.html, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/configuration/KubernetesConfigOptions.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/FlinkKubeClientFactory.java
This Pr is meant to add option to set user agent for kubeclient.
This PR is a minor change without test case
=> [FLINK-27461] Add option to set userAgent for kubeclient

docs/content.zh/docs/dev/datastream/fault-tolerance/broadcast_state.md
- **This is the English document：**
- **This is the Chinese document：**
- **According to the 2 pictures above, we can clearly find that the Chinese document is not formatted correctly.**
- Fix the formatting errors of some Chinese documents.
- The public API, i.e., is any changed class annotated with @Public(Evolving): (**no**) …
=> [hotfix][docs] Fix the formatting errors of some Chinese documents.

flink-kubernetes/src/main/java/org/apache/flink/kubernetes/KubernetesClusterDescriptor.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/KubernetesResourceManagerDriver.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/cli/KubernetesSessionCli.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/entrypoint/KubernetesEntrypointUtils.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/Fabric8FlinkKubeClient.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/FlinkKubeClient.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/ExternalServiceDecorator.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/resources/KubernetesService.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/services/ClusterIPService.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/services/LoadBalancerService.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/services/NodePortService.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/services/ServiceType.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/KubernetesUtils.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/KubernetesClientTestBase.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/Fabric8FlinkKubeClientTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/TestingFlinkKubeClient.java
This pull request is meant to improve the implementation of `Fabric8FlinkKubeClient#getRestEndpoint`. It's mainly done threes things
- Refactor the FlinkKubeClient interface `getService` and `updateServiceTargetPort` to deal with service name directly which will eliminate the unnecessary enum of `KubernetesService.ServiceType`.
- Port `Fabric8FlinkKubeClient#getRestEndpoint` method to the specific service type subclass
- Remove the implicit behavior to use the Service externalIP as the address of the Endpoint which is the purpose of [FLINK-17232](https://issues.apache.org/jira/browse/FLINK-17232).  I think it can be safely removed as i comments in the jira. Please correct me if I'm wrong. Or If I need to create a separate pull request for that issue, please let me know.
This change is …
=> [FlINK-26112][k8s]Port getRestEndpoint method to the specific service type subclass

flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internals/metrics/KafkaMetricMutableWrapper.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/internals/metrics/KafkaMetricMutableWrapperTest.java
… others
With the upgrade to Kafka 2.8, we introduced a regression in the metrics of our Kafka connector. Previously, we relied on a now deprecated and in the future removed method to forward the metrics of the `KafkaConsumer` and `KafkaProducer` to Flink's metric system. This PR implements the original logic that only measurable metrics are displayed and all other metrics are `0.0`. 
Check the type of the returned metric value and only cast to Double if possible.
Added a test that creates a KafkaConsumer and KafkaProducer and tried to retrieve all available metric values.
- The …
=> [FLINK-27487][kafka] Only forward measurable Kafka metrics and ignore others

docs/content.zh/docs/dev/dataset/examples.md
- Fix two inaccessible links in the Chinese documentation.
- Fix two inaccessible links in the Chinese documentation.
=> [hotfix][docs-zh] Fix two inaccessible links.

flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/typeutils/GenericRecordAvroTypeInfo.java, flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/typeutils/SerializableAvroSchema.java, flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/typeutils/AvroGenericRecordTypeInfoTest.java, flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/typeutils/AvroSerializerLargeGenericRecordTest.java, flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/utils/AvroTestUtils.java
- Change to GenericRecordAvroTypeInfo.class and SerializableAvroSchema.class so that type info of avro schema greater than 65535 characters could be serialized
Added unit test to validate that large Avro schema is correctly de/serialized …
=> [FLINK-27255] [flink-avro] flink-avro does not support ser/de of large avro schema

docs/content/docs/deployment/resource-providers/yarn.md
Fix yarn doc page display error.
This change is a doc fix without any test coverage. This error was introduced in https://github.com/apache/flink/pull/18450
=> [FLINK-27563][docs] Fix yarn doc page display error.

docs/content/release-notes/flink-1.15.md
This PR will let Flink user be aware of changes of metrics e.g. `numRecordsSend`, `numRecordsOutErrors`, etc.
- add the description of using `numRecordsSend` and deprecating `numRecordsOutErrors`
GitHub PR
=> [hotfix][doc] add content for using numRecordsSend and deprecating numRecordsOutErrors

docs/content.zh/docs/connectors/datastream/kafka.md, docs/content/docs/connectors/datastream/kafka.md, flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaSinkBuilder.java, flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/KafkaDynamicSink.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaSinkITCase.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/testutils/KafkaSinkExternalContext.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaChangelogTableITCase.java
The builders method for setting the delivery guarantee in the Kafka connector is misspelled. We want to fix the spelling.
- Implemented `setDeliveryGuarantee` method with correct spelling
- Deprecated misspelled `setDeliverGuarantee` method to allow future removal
- Fixed doc pages
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** / …
=> [hotfix][connectors/kafka] Fix spelling of setDeliveryGuarantee method

docs/layouts/shortcodes/generated/rest_v1_dispatcher.html, docs/static/generated/rest_v1_dispatcher.yml, flink-core/src/main/java/org/apache/flink/api/common/ArchivedExecutionConfig.java, flink-runtime-web/src/test/resources/rest_api_v1.snapshot, flink-runtime-web/web-dashboard/src/app/interfaces/job-checkpoint.ts, flink-runtime-web/web-dashboard/src/app/pages/job/checkpoints/job-checkpoints.component.html, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/AccessExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ArchivedExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraphBuilder.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/checkpoints/CheckpointConfigHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/checkpoints/CheckpointConfigInfo.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/legacy/utils/ArchivedExecutionConfigBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/legacy/utils/ArchivedExecutionGraphBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/messages/checkpoints/CheckpointConfigInfoTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StateTrackingMockExecutionGraph.java
This PR wants to add two fields:
- changelog_storage
- changelog_periodic_materialization_interval
into the checkpoints-config response, and show these fields on web UI when changelog is enabled.
- *Add `changelog_storage` and `changelog_periodic_materialization_interval` to rest api*
- *Add `changelog_storage` and `changelog_periodic_materialization_interval` to web ui*
- `RestAPIStabilityTest` …
=> [FLINK-27260][Runtime/REST] Expose changelog configurations in Rest API and Web UI

flink-python/setup.py
Bundle test utility classes into the PyFlink package to make users write test cases easily.
- *set `pyflink.testing` package `into setup.py` *
Change build script, no test case.
- The runtime per-record code paths (performance sensitive): (xno)
=> [FLINK-27421][python] Bundle test utility classes

flink-end-to-end-tests/flink-connector-gcp-pubsub-emulator-tests/src/test/resources/log4j2-test.properties, flink-end-to-end-tests/flink-end-to-end-tests-aws-kinesis-firehose/src/test/resources/log4j2-test.properties, flink-end-to-end-tests/flink-end-to-end-tests-aws-kinesis-streams/src/test/resources/log4j2-test.properties, flink-end-to-end-tests/flink-glue-schema-registry-avro-test/src/test/resources/log4j2-test.properties, flink-end-to-end-tests/flink-glue-schema-registry-json-test/src/test/resources/log4j2-test.properties, flink-end-to-end-tests/flink-streaming-kinesis-test/src/test/resources/log4j2-test.properties
Logging the Bash E2E tests uses a lot of disk space. This PR disables all logging by default. It should only be enabled in case of debugging. 
* Set all logging to OFF instead of INFO (which is for debugging)
=> [FLINK-24433][Tests][Buildsystem] Prevent running out of disk space

flink-connectors/flink-connector-aws-kinesis-firehose/src/test/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkBuilderTest.java, flink-connectors/flink-connector-aws-kinesis-firehose/src/test/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkElementConverterTest.java, flink-connectors/flink-connector-aws-kinesis-firehose/src/test/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkITCase.java, flink-connectors/flink-connector-aws-kinesis-firehose/src/test/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkTest.java, flink-connectors/flink-connector-aws-kinesis-firehose/src/test/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkWriterTest.java, flink-connectors/flink-connector-aws-kinesis-firehose/src/test/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseStateSerializerTest.java, flink-connectors/flink-connector-aws-kinesis-firehose/src/test/java/org/apache/flink/connector/firehose/table/KinesisFirehoseDynamicTableFactoryTest.java, flink-connectors/flink-connector-aws-kinesis-firehose/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Update the flink-connector-aws-kinesis-firehose module to AssertJ and JUnit 5 following the [JUnit 5 Migration Guide](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit)
Use JUnit5 and AssertJ in tests instead of JUnit4 …
=> [FLINK-27566][tests] Migrate module flink-connector-aws-kinesis-firehose to JUnit5

tools/azure-pipelines/free_disk_space.sh
* This PR removes additionally pre-installed packages on the Azure VMs to clean-up more diskspace before starting the E2E tests
* Remove installed packages
- The S3 file …
=> [FLINK-24433][Tests][Buildsystem] Remove additional pre-installed packages to clean up more diskspace

flink-end-to-end-tests/flink-end-to-end-tests-elasticsearch6/pom.xml
This PR removes an unnecessary slf4j dependency causing a lot of unwanted log output in the Elasticsearch6End2EndCase test.
- removed slf4j dependency …
=> [FLINK-27649][connectors/elasticsearch] Remove slf4 dependency causing unwanted log output

flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/AsyncLookupJoinITCase.scala
FLINK-12351 already fix the copy issue in AsyncWaitOperator, so we should cover testing for both object reuse enabled and disabled for AsyncLookupJoinITCase.
Add objectReuse parameter for AsyncLookupJoinITCase.
This change is already covered by existing test: AsyncLookupJoinITCase.
=> [hotfix][table] Add objectReuse parameter for AsyncLookupJoinITCase.

flink-connectors/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/sink/KinesisStreamsSinkBuilderTest.java, flink-connectors/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/sink/KinesisStreamsSinkITCase.java, flink-connectors/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/sink/KinesisStreamsStateSerializerTest.java, flink-connectors/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/table/KinesisDynamicTableSinkFactoryTest.java, flink-connectors/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/table/RowDataFieldsKinesisPartitionKeyGeneratorTest.java, flink-connectors/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/table/util/KinesisProducerOptionsMapperTest.java, flink-connectors/flink-connector-aws-kinesis-streams/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Update the flink-connector-aws-kinesis-streams module to AssertJ and JUnit 5 following the [JUnit 5 Migration Guide](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit)
- If yes, how …
=> [FLINK-27567][tests] Migrate module flink-connector-aws-kinesis-streams to JUnit5

docs/layouts/shortcodes/generated/rocksdb_configurable_configuration.html, flink-end-to-end-tests/test-scripts/common.sh, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBConfigurableOptions.java
Move RocksDB's log location to /tmp for e2e tests to avoid too many logs in e2e artifacts.
Configure `state.backend.rocksdb.log.dir` when starting the cluster.
=> [FLINK-27433][tests] Relocate RocksDB's log back to its own database dir

flink-formats/flink-compress/src/test/java/org/apache/flink/formats/compress/CompressWriterFactoryTest.java, flink-formats/flink-compress/src/test/java/org/apache/flink/formats/compress/CompressionFactoryITCase.java, flink-formats/flink-compress/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Update the `flink-formats/flink-compress` module to AssertJ and JUnit 5 following the [JUnit 5 Migration Guide](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit)
This is a small one, but I didn't see any module to logically group it with. …
=> [FLINK-27059][tests][JUnit5 migration] flink-compress

flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/connector/elasticsearch/sink/ElasticsearchSinkBuilderBase.java
fix typo
- *Fix typo of ElasticsearchSinkBuilderBase#setConnectionPassword comment*
=> [hotfix][connector/elasticsearch] Fix typo of ES comment

flink-end-to-end-tests/flink-end-to-end-tests-common-elasticsearch/src/main/java/org/apache/flink/streaming/tests/ElasticsearchSinkE2ECaseBase.java
* Disable Elasticsearch disk allocation decider. Elasticsearch by default goes into read-only mode when the disk usage is above 85%. On the Azure E2E tests, this is quite common.
We therefore disable the entire disk allocation decider, as documented on https://www.elastic.co/guide/en/elasticsearch/reference/6.2/disk-allocator.html
* Disable Elasticsearch disk allocation decider by passing through the right config flag. …
=> [FLINK-24433][Connector][Elasticsearch] Disable Elasticsearch disk allocation decider

flink-architecture-tests/flink-architecture-tests-production/pom.xml
Backport of #19541 (cherry picked from commit 45afc031a222ec8ff1b02fb9a1d8b2826e43dc4f)
=> [FLINK-27167][test] change the junit-jupiter dependency scope to compile

flink-connectors/flink-connector-aws-base/pom.xml, flink-connectors/flink-connector-aws-base/src/test/java/org/apache/flink/connector/aws/table/util/AWSOptionsUtilTest.java, flink-connectors/flink-connector-aws-base/src/test/java/org/apache/flink/connector/aws/table/util/AsyncClientOptionsUtilsTest.java, flink-connectors/flink-connector-aws-base/src/test/java/org/apache/flink/connector/aws/util/AWSAsyncSinkUtilTest.java, flink-connectors/flink-connector-aws-base/src/test/java/org/apache/flink/connector/aws/util/AWSGeneralUtilTest.java, flink-connectors/flink-connector-aws-base/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Update the flink-connector-aws-base  module to AssertJ and JUnit 5 following the [JUnit 5 Migration Guide](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit)
- The S3 file system connector: ( no  ) …
=> [FLINK-27561][tests] Migrate flink-connector-aws-base to JUnit5

flink-connectors/flink-file-sink-common/pom.xml, flink-connectors/flink-file-sink-common/src/test/java/org/apache/flink/streaming/api/functions/sink/filesystem/OutputStreamBasedPartFileRecoverableMigrationTest.java, flink-connectors/flink-file-sink-common/src/test/java/org/apache/flink/streaming/api/functions/sink/filesystem/bucketassigners/DateTimeBucketAssignerTest.java, flink-connectors/flink-file-sink-common/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Update the flink-file-sink-common module to AssertJ and JUnit 5 following the [JUnit 5 Migration Guide](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit)
- Does this pull request introduce a new feature? (no ) …
=> [FLINK-27669][tests] Migrate flink-file-sink-common to JUnit5

flink-table/flink-table-api-scala/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension, flink-table/flink-table-api-scala/src/test/scala/org/apache/flink/table/api/ExpressionsConsistencyCheckTest.scala, flink-table/flink-table-api-scala/src/test/scala/org/apache/flink/table/api/ImplicitConversionsTest.scala, flink-table/flink-table-api-scala/src/test/scala/org/apache/flink/table/expressions/ObjectToExpressionScalaTest.scala, flink-table/flink-table-api-scala/src/test/scala/org/apache/flink/table/types/extraction/DataTypeExtractorScalaTest.scala, flink-table/flink-table-api-scala/src/test/scala/org/apache/flink/table/types/extraction/TypeInferenceExtractorScalaTest.scala
Update the flink-table-api-scala module to AssertJ and JUnit 5 following the [JUnit 5 Migration Guide](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit) …
=> [FLINK-27673][tests] Migrate flink-table-api-scala to JUnit5

flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/sink/PulsarSinkITCase.java, flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/PulsarSourceITCase.java
* Disable Pulsar tests on JDK 11 since Pulsar doesn't yet support JDK 11 fully
* Disabled tests
- The serializers: (no
=> [FLINK-27680][Connector][Pulsar] Disable PulsarSinkITCase and PulsarSourceITCase on JDK 11

flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaSinkBuilder.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaSinkBuilderTest.java
Fix checking of bootstrapServers when already provided in producer Properties
- *If the user provides bootstrapServers in the producer Properties, even if he does not use the setBootstrapServers method, the relevant check will no longer have a null exception*
- *The sanityCheck method is provided to put the checked code together* …
=> [FLINK-27174][connector/kafka] Fix checking of bootstrapServers when already provided in producer Properties

flink-table/flink-table-api-java-bridge/src/test/java/org/apache/flink/connector/datagen/table/types/DecimalDataRandomGeneratorTest.java, flink-table/flink-table-api-java-bridge/src/test/java/org/apache/flink/table/api/bridge/java/internal/StreamTableEnvironmentImplTest.java, flink-table/flink-table-api-java-bridge/src/test/java/org/apache/flink/table/factories/BlackHoleSinkFactoryTest.java, flink-table/flink-table-api-java-bridge/src/test/java/org/apache/flink/table/factories/CsvTableSinkFactoryTest.java, flink-table/flink-table-api-java-bridge/src/test/java/org/apache/flink/table/factories/DataGenTableSourceFactoryTest.java, flink-table/flink-table-api-java-bridge/src/test/java/org/apache/flink/table/sources/CsvTableSourceTest.java, flink-table/flink-table-api-java-bridge/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension, flink-table/flink-table-common/src/test/java/org/apache/flink/table/sources/TableSourceTestBase.java
Update the flink-table-api-java-bridge module to AssertJ and JUnit 5 following the [JUnit 5 Migration Guide](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit) …
=> [FLINK-27698][tests][table] Migrate flink-table-api-java-bridge to JUnit5

flink-python/dev/lint-python.sh
Some logs are in the wrong location, we need to move them to the inside of the 'if' statement.
- *Move log of lint-python.sh to the inside of 'if' statement*
=> [FLINK-27694][python][build] Move lint-python log location

docs/layouts/shortcodes/generated/security_auth_kerberos_section.html, docs/layouts/shortcodes/generated/security_configuration.html, flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumerTest.java, flink-core/src/main/java/org/apache/flink/configuration/SecurityOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/ClusterEntrypoint.java, flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniCluster.java, flink-runtime/src/main/java/org/apache/flink/runtime/security/token/DelegationTokenManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/security/token/KerberosDelegationTokenManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/security/token/KerberosDelegationTokenManagerFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/security/token/KerberosRenewalPossibleProvider.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/FileUploadHandlerITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/security/token/KerberosDelegationTokenManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/security/token/KerberosRenewalPossibleProviderTest.java, flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java, pom.xml
`KerberosDelegationTokenManager` needs a valid TGT in order to obtain delegation tokens. In this PR I've added periodic kerberos relogin when configured properly.
* Added `security.kerberos.relogin.period` config with default 1 minute.
* Added TGT renew thread when user uses keytab.
* Updated Mockito version to 3.4.6 in order to use static method mocking in `testStartTGTRenewalShouldScheduleRenewal`.
* Updated Byte Buddy version to 1.10.14 to match with Mockito.
* Additional unit tests
* Manually on YARN and K8S cluster …
=> [FLINK-26043][runtime][security] Add periodic kerberos relogin to KerberosDelegationTokenManager

flink-core/src/main/java/org/apache/flink/api/common/functions/CoGroupFunction.java
Small change:  update the Javadoc of `CoGroupFunction` to use `DataStream` as code example and in the description.
=> [hotfix][doc] update javadoc to use DataStream, because DataSet is deprecated.

flink-examples/flink-examples-table/src/test/java/org/apache/flink/table/examples/java/basics/GettingStartedExampleITCase.java, flink-examples/flink-examples-table/src/test/java/org/apache/flink/table/examples/java/basics/StreamSQLExampleITCase.java, flink-examples/flink-examples-table/src/test/java/org/apache/flink/table/examples/java/basics/UpdatingTopCityExampleITCase.java, flink-examples/flink-examples-table/src/test/java/org/apache/flink/table/examples/java/basics/WordCountSQLExampleITCase.java, flink-examples/flink-examples-table/src/test/java/org/apache/flink/table/examples/java/functions/AdvancedFunctionsExampleITCase.java, flink-examples/flink-examples-table/src/test/java/org/apache/flink/table/examples/scala/basics/GettingStartedExampleITCase.java, flink-examples/flink-examples-table/src/test/java/org/apache/flink/table/examples/scala/basics/StreamSQLExampleITCase.java, flink-examples/flink-examples-table/src/test/java/org/apache/flink/table/examples/scala/basics/WordCountSQLExampleITCase.java, flink-examples/flink-examples-table/src/test/java/org/apache/flink/table/examples/utils/ExampleOutputTestBase.java, flink-examples/flink-examples-table/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Update flink-examples-table to AssertJ and JUnit 5 following the [JUnit 5 Migration Guide](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit) …
=> [FLINK-27732][tests] Migrate flink-examples-table to JUnit5

tools/azure-pipelines/uploading_watchdog.sh
The `secondsToKill` variable is executed as a command by mistake thus not effective, which makes the tests fail prematurely when the build takes 95% of the build time.
- Reference `secondsToKill` as a varialble. …
=> [hotfix][tests] Azure tests fail prematurely because timeout watchdog fails to sleep

flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaSinkBuilder.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaSinkBuilderTest.java
This is a backport PR for #19628
=> [BP-1.14][FLINK-27174][connector/kafka] Fix checking of bootstrapServers when already provided in producer Properties

flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaSinkBuilder.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaSinkBuilderTest.java
This is a backport PR for #19628
=> [BP-1.15][FLINK-27174][connector/kafka] Fix checking of bootstrapServers when already provided in producer Properties

flink-end-to-end-tests/flink-streaming-kinesis-test/pom.xml
flink-streaming-kinesis-tests bundles and relocates netty (and no other dependency). We can safely remove this because no class within this module references netty, nor any other module relies on the relocated versions.
=> [FLINK-27763][kinesis][tests] Remove netty bundling&relocation

flink-runtime/src/main/java/org/apache/flink/runtime/messages/TaskThreadInfoResponse.java, flink-runtime/src/main/java/org/apache/flink/runtime/messages/ThreadInfoSample.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutorGatewayDecoratorBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutorThreadInfoGateway.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/ThreadInfoSampleService.java, flink-runtime/src/main/java/org/apache/flink/runtime/util/JvmUtils.java, flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/stats/TaskStatsRequestCoordinator.java, flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/threadinfo/JobVertexFlameGraphFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/threadinfo/JobVertexThreadInfoStats.java, flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/threadinfo/JobVertexThreadInfoTracker.java, flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/threadinfo/ThreadInfoRequestCoordinator.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/IdleTestTask.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TestingTaskExecutorGateway.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/ThreadInfoSampleServiceTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/threadinfo/JobVertexThreadInfoTrackerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/threadinfo/ThreadInfoRequestCoordinatorTest.java
The FlameGraph feature added in FLINK-13550 issues 1 RPC call per subtask. This may cause performance problems for jobs with high paralleism and a lot of subtasks. This PR improves sampling by grouping thread sampling request and issuing only one call per TaskManager for all the relevant threads at once.
Verified manually and by the existing tests. …
=> [FLINK-26074] Improve FlameGraphs scalability for high parallelism jobs

flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/core/testutils/OneShotLatchTest.java, flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/RetryOnExceptionExtensionTest.java, flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/RetryOnExceptionTest.java, flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/RetryOnFailureExtensionTest.java, flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/RetryOnFailureTest.java, flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/RetryRuleTest.java, flink-test-utils-parent/flink-test-utils-junit/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Migrate `flink-test-utils-junit` to AssertJ and JUnit 5 following the [JUnit 5 Migration Guide](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit) …
=> [FLINK-27740][tests] Migrate flink-test-utils-junit to JUnit5

flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogStorageFactory.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/BoundedSourceITCase.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/PartiallyFinishedSourcesITCase.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/StopWithSavepointITCase.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/lifecycle/TestJobExecutor.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/ChangelogPeriodicMaterializationTestBase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/EventTimeWindowCheckpointingITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/IncrementalStateReuseAfterFailureITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/ResumeCheckpointManuallyITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/StreamFaultToleranceTestBase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointStressITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java, flink-tests/src/test/java/org/apache/flink/test/state/ChangelogCompatibilityITCase.java, flink-tests/src/test/java/org/apache/flink/test/state/ChangelogRescalingITCase.java
Fix test instability caused by changelog write timeouts.
=> [FLINK-27169][tests] Set timeout for operator lifecycle tests and increase changelog upload timeout

flink-python/pyflink/table/tests/test_table_environment_api.py
Run `python -m flake8 --config=tox.ini` in `flink-python` dir.
It will throw the following error message.
`./pyflink/table/tests/test_table_environment_api.py:558:29: F523 '...'.format(...) has unused arguments at position(s): 0, 1`
=> [hotfix][python] Fix flake8 check E523 error for format method has used arguments

flink-python/pyflink/table/tests/test_udf.py
I execute `python -m flake8 --config=tox.ini` in `flink-python` dir
It will throw the following error message.
`./pyflink/table/tests/test_udf.py:805:1: E302 expected 2 blank lines, found 1`
=> [hotfix][python] Fix flake8 check E302 error for blank lines

flink-connectors/flink-connector-aws-kinesis-firehose/pom.xml, flink-connectors/flink-connector-aws-kinesis-streams/pom.xml, flink-connectors/flink-connector-cassandra/pom.xml, flink-connectors/flink-connector-kafka/pom.xml, flink-connectors/flink-connector-kinesis/pom.xml
We found out that the connectors rely heavily on the `flink-table-planner` test dependency (for running the DynamicTableFactory ITCases). This is not the way to go anymore and they should rather use `flink-table-test-utils`. 
Adjusted dependencies for most connectors relying on `flink-table-planner`
This change is already covered by existing tests, such as ITCases
- The public API, i.e., is any changed class annotated with `@PublicEvolving)`: (yes / **no**) …
=> [FLINK-27779][connectors] Connectors should not depend on `flink-table-planner`

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPool.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPoolTest.java
Ignore max buffers per channel when allocate buffer
Ignore max buffers per channel when allocate buffer
This change is already covered by existing tests, such as `LocalBufferPoolTest#testMaxBuffersPerChannelAndAvailability`.
=> [FLINK-27522][network] Ignore max buffers per channel when allocate buffer

docs/content/docs/deployment/overview.md
the deployment modes image is too small to read the text. 
-  enlarge the image
-  fix typo
=> [hotfix][doc] fix typo and enlarge image

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/aggregate/window/buffers/WindowBuffer.java
Fix an embarrassing typo in the comment of org.apache.flink.table.runtime.operators.aggregate.window.buffers.WindowBuffer class.
=> [hotfix] Fix typo in comment of WindowBuffer

flink-end-to-end-tests/flink-end-to-end-tests-elasticsearch6/pom.xml, flink-end-to-end-tests/flink-end-to-end-tests-elasticsearch6/src/test/java/org/apache/flink/streaming/tests/Elasticsearch6SinkE2ECase.java, flink-end-to-end-tests/flink-end-to-end-tests-elasticsearch7/pom.xml, flink-end-to-end-tests/flink-end-to-end-tests-elasticsearch7/src/test/java/org/apache/flink/streaming/tests/Elasticsearch7SinkE2ECase.java
No longer bundled log4j (as it is provided by Flink) nor transitive dependencies from flink-end-to-end-tests-common-elasticsearch (as they are necessary).
We still need flink-end-to-end-tests-common-elasticsearch itself for some utility classes though.
=> [FLINK-27810][es][tests] Reduce number of bundled dependencies

flink-core/src/main/java/org/apache/flink/api/java/typeutils/PojoTypeInfo.java
Fix typo in the comment of PojoTypeInfo class.
=> [hotfix][docs] Fix typo in comment of PojoTypeInfo

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CastFunctionITCase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/MapFunctionITCase.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/MapTypeTest.scala
The PR makes use of maps in `MAP` values constructors to make keys unique
In case there are several same keys in map functions, the latest will be taken
e.g.
```sql
SELECT MAP[1, 2, 1, 3, 1, 4];
```
returns `{1=4}`
- Added usage of map in constructors
- move `MAP` function tests to `flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/MapFunctionITCase.java`
There are tests in `flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/MapFunctionITCase.java`
- The runtime per-record code paths (performance sensitive):(no) …
=> [FLINK-25699][table] Use HashMap for MAP value constructors

flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/batch/connectors/cassandra/CassandraColumnarOutputFormatBase.java, flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/batch/connectors/cassandra/CassandraOutputFormatBase.java, flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/batch/connectors/cassandra/CassandraPojoOutputFormat.java, flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/batch/connectors/cassandra/CassandraRowOutputFormat.java, flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/batch/connectors/cassandra/CassandraTupleOutputFormat.java, flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/batch/connectors/cassandra/OutputFormatBase.java, flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/connectors/cassandra/utils/SinkUtils.java, flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/streaming/connectors/cassandra/CassandraSinkBase.java, flink-connectors/flink-connector-cassandra/src/test/java/org/apache/flink/batch/connectors/cassandra/OutputFormatBaseTest.java, flink-connectors/flink-connector-cassandra/src/test/java/org/apache/flink/connectors/cassandra/utils/ResultSetFutures.java, flink-connectors/flink-connector-cassandra/src/test/java/org/apache/flink/streaming/connectors/cassandra/CassandraSinkBaseTest.java, flink-core/src/main/java/org/apache/flink/api/common/io/OutputFormat.java, tools/maven/suppressions.xml
When migrating to Cassandra 4.x in [this PR](https://github.com/apache/flink/pull/19586) a race condition in the tests between the asynchronous writes and the junit assertions was uncovered. So it was decided to introduce the flush mechanism to asynchronous writes in the Cassandra output formats similarly to what was done in Cassandra sinks.
The existing class `CassandraOutputFormatBase` that was previously used as a base class only for Tuple and Row outputFormats is now used as a base class for the 3 output formats including Pojo. the base class for column based output formats (tuple and row) is now a new class called CassandraColumnarOutputFormatBase.
Regarding configuration of the flush I preferred using simple setters to a configuration object as there was no builders for the output …
=> [FLINK-27457] Implement flush() logic in Cassandra output formats

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/RetractableTopNFunction.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/rank/RetractableTopNFunctionTest.java
This is a cherry-pick back to the release-1.15 branch.
=> [BP-1.15][FLINK-27418][table-planner] Fix topN retraction for previously deleted record

flink-runtime/src/test/java/org/apache/flink/runtime/security/token/KerberosDelegationTokenManagerITCase.java
Marks the KerberosDelegationTokenManagerTest as an ITCase so that it runs in a dedicated JVM to ensure it's static mock doesn't leak into other tests.
=> [FLINK-27791][tests] Prevent mocked UGI bleeding into other tests

flink-end-to-end-tests/flink-end-to-end-tests-sql/pom.xml, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/codegen/PlannerScalaFreeITCase.java
*Fix failed end-to-end-tests-sql CI test*
- *Fix failed end-to-end-tests-sql CI test*
=> [FLINK-27968][E2E] Fix failed end-to-end-tests-sql CI test

flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/async/OperationResult.java
Quick fix to allow the operation result to be serialized, which is required for the savepoint rest endpoints to be usable from a standby dispatcher.
This PR is just to ensure this fix gets into 1.15.1; I'm still working on adding some further safeguards from this slipping through _yet again_.
=> [FLINK-27933][rest] OperationResult implements Serializable

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/typeutils/ArrayDataSerializer.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/typeutils/ArrayDataSerializerTest.java
Unchanged backport of https://github.com/apache/flink/commit/0046a1c9170d1602ec973ea5242904ba875f8b0a on release-1.14
=> [BP-1.14][hotfix][table-runtime] Fix ArrayDataSerializer null fields writing

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/casting/RawToBinaryCastRule.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/casting/RawToStringCastRule.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/casting/StringToBinaryCastRule.java
Fix an issue where the planner was using a method from the wrong class. This is important because the previously used method comes from flink-table-code-splitter which is more or less an implementation detail of the runtime.
=> [FLINK-27778][table][planner] Use correct 'newName()' method

flink-runtime/src/main/java/org/apache/flink/runtime/security/SecurityConfiguration.java, flink-runtime/src/test/java/org/apache/flink/runtime/security/SecurityConfigurationTest.java
`security.kerberos.login.principal` can be set in the configuration without `security.kerberos.login.keytab` which is wrong configuration. The principal is always bound to a keytab file, please see the official documentation snippet:
In this PR I've added a code to throw exception such cases.
* Exception thrown when wrong config provided
* Added unit tests to cover `SecurityConfiguration`
* Minor fixes
Additional unit tests.
- The S3 file …
=> [FLINK-28000][runtime][security] Throw exception when principal is set in the configuration without keytab

flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/polling/AdaptivePollingRecordPublisher.java, flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogOptions.java, flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogWriter.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/NetworkBufferPool.java
- I think "Mb" in it should be "MB". Because Mb and MB are not the same,in terms of memory, a byte is the smallest storage slot. Your hard drives, SSDs, USB sticks, and system memory are always measured in bytes.
Please see "https://www.lifewire.com/what-is-a-megabit-2483412" for detailed differences.
According to experience, they have the following relationship:
- 8 Mb = 1 MB
- 1Mb = 1/8 MB = 0.125 MB
- Changed "Mb" in the documentation to "MB".
- Dependencies (does it add or upgrade a dependency):  **no** …
=> [hotfix][docs] Update memory unit Mb.

docs/content.zh/docs/ops/debugging/flame_graphs.md
- **This is the English document：**
- **This is the Chinese document：**
- According to the above two figures, it can be seen that the flame_graphs.md file is missing in the debugging Chinese document.
- Add missing the flame_graphs.md file to debugging.
- Does this pull request introduce a new feature? **no** …
=> [hotfix][docs-zh] Add missing the flame_graphs.md file to debugging.

flink-core/src/main/java/org/apache/flink/configuration/NettyShuffleEnvironmentOptions.java
Fix the typo about subpartition
Fix the typo about subpartition
=> [hotfix][network] Fix the typo about subpartition

docs/content/docs/dev/datastream/fault-tolerance/state.md
* Corrected type in state page
* Updated ... which is **atucally** already deprecated... to ...which is **actually** already deprecated...
=> [hotfix][fault-tolerance][docs] Corrected typo in state page

flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReader.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceITCase.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReaderTest.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/testutils/KafkaSourceTestEnv.java
This pull request fixes a bug that `KafkaSource` would throw exception and fail if `SourceReader` is assigned with empty splits. 
- Catch IllegalStateException in KafkaPartitionSplitReader.fetch() to handle no valid partition case
- Add case to test consuming empty partitions
- Add unit and integration test cases for consuming empty Kafka topic and partitions …
=> [FLINK-27041][connector/kafka] Catch IllegalStateException in KafkaPartitionSplitReader.fetch() to handle no valid partition case

flink-scala/src/test/scala/org/apache/flink/api/scala/typeutils/EnumValueSerializerCompatibilityTest.scala
`ConsoleReporter#printSummary` was removed in 2.12.13 and 2.13.0. We can use `#finish` instead which is equivalent and available in all versions.
https://www.scala-lang.org/api/2.12.7/scala-compiler/scala/tools/nsc/reporters/ConsoleReporter.html#finish():Unit
https://www.scala-lang.org/api/2.12.12/scala-compiler/scala/tools/nsc/reporters/ConsoleReporter.html#finish():Unit
https://www.scala-lang.org/api/2.13.7/scala-compiler/scala/tools/nsc/reporters/ConsoleReporter.html#finish():Unit
Additionally the test now fails if the compiler reports a warning or error, so we actually get some benefit from the summary.
Alternatively, we could also just remove it, but I can't really decide that.
=> [FLINK-24995][tests] EnumValueSerializerCompatibilityTest doesn't compile on later Scala versions

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserBaseSemanticAnalyzer.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/catalog/hive/HiveTestUtils.java
Fix  test failure for Hive when using profile Hive3.1.1
- Reset `setHiveSiteLocation` [HiveTestUtils.java](https://github.com/apache/flink/pull/19931/files#diff-9f020c7a155c5719d5830c1dacd49f54f62f94e1e70360252d379f357f533b99)#createHiveConf
- No to use `VirtualColumn.VIRTUAL_COLUMN_NAMES`, but use `VirtualColumn.isVirtualColumnBasedOnAlias` to avoid `java.lang.NoSuchFieldError: VIRTUAL_COLUMN_NAMES` exception.
Successful test is in [here](https://github.com/apache/flink/pull/19929) which have a statge for Hive 3.1.1 in CI build. …
=> [FLINK-27999][hive] Fix test failure for Hive when using profile Hive3.1.1

flink-yarn/src/main/java/org/apache/flink/yarn/cli/FlinkYarnSessionCli.java
see https://github.com/apache/flink/pull/19852
=> [BP-1.15][FLINK-24960][yarn-tests] backport 1.15: reorder statements to fix instability with yarn properties file

flink-yarn/src/main/java/org/apache/flink/yarn/cli/FlinkYarnSessionCli.java
see https://github.com/apache/flink/pull/19852
=> [BP-1.14][FLINK-24960][yarn-tests] backport 1.14: reorder statements to fix instability with yarn properties file

flink-core/src/main/java/org/apache/flink/api/common/io/BinaryInputFormat.java, flink-core/src/test/java/org/apache/flink/api/common/io/BinaryInputFormatTest.java
- correct the start index for creating empty splits in BinaryInputFormat#createInputSplits.
- Covered by unit test.
=> [FLINK-28018][core] correct the start index for creating empty splits in BinaryInputFormat#createInputSplits

docs/static/generated/rest_v1_dispatcher.yml, flink-docs/src/main/java/org/apache/flink/docs/rest/OpenApiSpecGenerator.java, flink-docs/src/test/java/org/apache/flink/docs/rest/OpenApiSpecGeneratorTest.java, flink-docs/src/test/java/org/apache/flink/docs/rest/data/TestEmptyMessageHeaders.java, flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/handlers/AbstractJarPlanHeaders.java, flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/handlers/JarDeleteHeaders.java, flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/handlers/JarPlanGetHeaders.java, flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/handlers/JarRunHeaders.java, flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/handlers/JarUploadHeaders.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/rescaling/RescalingTriggerHeaders.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/JobCancellationHeaders.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/MessageHeaders.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/cluster/ShutdownHeaders.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/dataset/ClusterDataSetDeleteTriggerHeaders.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/JobSubmitHeaders.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/savepoints/SavepointDisposalTriggerHeaders.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/savepoints/SavepointTriggerHeaders.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/savepoints/stop/StopWithSavepointTriggerHeaders.java
Adds some simple generation logic and covers a few edge-cases to have proper operationIds in the OpenAPI spec. These are used for the generated method names.
The naming pattern is similar to what we'd use in Java.
=> [FLINK-27819][rest][docs] Use proper operationIds

flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java
Sets the network memory to 32mb (down from 64mb), halving the memory usage. Some tests spawn a large number of task managers (up to 25) eating up the majority of the memory budged with network buffers.
I had a successful run with 12mb, so I figured 32mb should be sufficient.
=> [FLINK-28005][tests] Reduce network memory in UnalignedCheckpointTestBase

flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
The RunFailedJobListener had rather obscure semantics.
It considered a job to be terminal after it was restarted. This is awfully specific to a particular test case.
A cleaner approach is just to just cancel the job and wait for it to terminate.
Additionally it considered a job as running purely based on the job status, whereas, in particular when checkpointing is involved, waiting for the tasks to be submitted is a better measure.
In fact, testExceptionHistoryWithTaskFailureFromStopWithSavepoint was a broken since a savepoint was never triggered, as not all tasks were running.
This PR also contains a few cleanup commits.
=> [FLINK-28052][tests] Remove RunFailedJobListener 

flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReader.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReaderTest.java
This pull request improves the logic of `KafkaPartitionSplitReader` that `wakeup()` should only wake up the blocking `KafkaConsumer#poll` operation, otherwise the wake-up might be delayed to the next `ConsumerNetworkClient#poll` call when handling new splits, which will throw a `WakeupException`.
- Add a volatile variable `isPolling` to make sure the wakeup method only unblocks KafkaConsumer#poll
- Add new unit test for `KafkaPartitionSplitReader`
This change is covered by the new `KafkaPartitionSplitReaderTest#testWakeupThenAssign` case. …
=> [FLINK-27762][connector/kafka] Catch WakeupException and retry KafkaConsumer invocations in split assignment

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/RetractableTopNFunction.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/rank/RetractableTopNFunctionTest.java
We found an error occurred when retract a staled record when enable state ttl in RetractableTopNFunction, the reason is the uncomplete path when deal with staled records. This should be fixed.
update the staled record error handling logic in retractRecordWithRowNumber and processElement of the RetractableTopNFunction.
add new tests for RetractableTopNFunctionTest …
=> [FLINK-28019][table] fix error when retract a staled record if state ttl enabled in RetractableTopNFunction

flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReader.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReaderTest.java
Unchanged back port of #19828 on release-1.15
=> [BP-1.15][FLINK-27762][connector/kafka] Catch WakeupException and retry KafkaConsumer invocations in split assignment

flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReader.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReaderTest.java
Unchanged back port of #19828 on release-1.14
=> [BP-1.14][FLINK-27762][connector/kafka] Catch WakeupException and retry KafkaConsumer invocations in split assignment

flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReader.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceITCase.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReaderTest.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/testutils/KafkaSourceTestEnv.java
Unchanged back port of #19456 on release-1.15
=> [BP-1.15][FLINK-27041][connector/kafka] Catch IllegalStateException in KafkaPartitionSplitReader.fetch() to handle no valid partition case

flink-filesystems/flink-oss-fs-hadoop/src/main/java/org/apache/flink/fs/osshadoop/writer/OSSRecoverableFsDataOutputStream.java
The oss fs has a dependency on `commons-io` which is sneakily provided by `flink-fs-hadoop-shaded`. To support Maven 3.3+ we either need to remove this dependency or declare it explicitly, as modules will no longer be able to readily use dependencies that are bundled by others.
I opted for replacing it with the Flink IOUtils because it's less of a hassle.
=> [FLINK-28095][oss] Replace commons-io IOUtils dependency

flink-formats/flink-orc/pom.xml, flink-formats/flink-parquet/pom.xml
Fix the bug which can't run ITcase in IDE in flink-orc and flink-parquet module .
- *Exclude guava dependency for hadoop-xxx dependencies in module flink-parquet and flink-orc*
=> [FLINK-22920][formats] Fix guava version conflict in `flink-orc` and `flink-parquet` module

flink-connectors/flink-connector-kafka/pom.xml, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaConsumerTestBase.java, flink-connectors/flink-sql-connector-kafka/src/main/resources/META-INF/NOTICE, flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/pom.xml, flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SQLClientKafkaITCase.java, flink-end-to-end-tests/test-scripts/kafka-common.sh, flink-end-to-end-tests/test-scripts/test_confluent_schema_registry.sh, flink-end-to-end-tests/test-scripts/test_pyflink.sh, flink-end-to-end-tests/test-scripts/test_sql_client.sh, flink-examples/flink-examples-build-helper/flink-examples-streaming-state-machine/src/main/resources/META-INF/NOTICE, flink-formats/flink-avro-confluent-registry/pom.xml
Updated Kafka Clients to resolve the issue where Flink is unable to commit its offset back to Kafka in case of Kafka Broker becoming unavailable. This should be resolved when the broker comes back up, but due to KAFKA-13563 that doesn't work. Since that fix has only become available with Kafka Clients 3.1.1, this commit updates the Kafka Clients dependency from 2.8.4 to 3.1.1.
No interfaces needed to be adjusted.
It was necessary to change some of our Bash e2e tests since they still relied on the Zookeeper parameter which has been removed in this version.
The other necessary change was adjusting the `KafkaConsumerTestBase` class since the level of exception is changed in the new Kafka Clients so exception.getCause().getMessage()  throws an NPE in the test case.
* Updated Kafka Clients …
=> [FLINK-28060][Connector/Kafka] Updated Kafka Clients to 3.1.1 

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/RetractableTopNFunction.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/rank/RetractableTopNFunctionTest.java
=> [BP-1.14][FLINK-28019][table] fix error when retract a staled record if state ttl enabled in RetractableTopNFunction

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/RetractableTopNFunction.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/rank/RetractableTopNFunctionTest.java
This is a backport of [#19942](https://github.com/apache/flink/pull/19942)
=> [BP-1.15][FLINK-28019][table] fix error when retract a staled record if state ttl enabled in RetractableTopNFunction

flink-core/src/test/java/org/apache/flink/api/common/io/GlobFilePathFilterTest.java
- test the serialized object in GlobFilePathFilterTest#testGlobFilterSerializable
- Rework GlobFilePathFilterTest to be based on AssertJ
- covered by existed ut
- If yes, how is the feature documented? (**not applicable** …
=> [FLINK-28105][Tests] test the copied object in GlobFilePathFilterTest#testGlobFilterSerializable

flink-python/dev/dev-requirements.txt, flink-python/setup.py
* Updating httplib2 to at least 0.19.0 to address CVE-2021-21240 and avoid false flags about Flink being vulnerable.
* Updated Python dev requirements for httplib2
=> [FLINK-28147][Python] Update httplib2 to at least 0.19.0

docs/content.zh/docs/ops/metrics.md, docs/content/docs/ops/metrics.md, docs/layouts/shortcodes/generated/all_taskmanager_network_section.html, docs/layouts/shortcodes/generated/netty_shuffle_environment_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/NettyShuffleEnvironmentOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/NettyShuffleServiceFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/BufferPoolFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPool.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/NetworkBufferPool.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/ResultPartitionFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/NettyShuffleEnvironmentConfiguration.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/NettyShuffleEnvironmentBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/writer/RecordWriterDelegateTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/writer/RecordWriterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPoolTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/ResultPartitionBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/ResultPartitionFactoryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/ResultPartitionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/LocalInputChannelTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/ChannelPersistenceITCase.java
Add the overdraft buffer in ResultPartition to reduce unaligned checkpoint being blocked
- Add overdraft buffer in LocalBufferPool
- Add configuration : taskmanager.network.memory.max-overdraft-buffers-per-gate
- Added testOverdraftBuffer in LocalBufferPoolTest …
=> [FLINK-26762][network] Add the overdraft buffer in ResultPartition

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestExecutorImplTest.java
Fix the bug that tasks get stuck during cancellation in ChannelStateWriteRequestExecutorImpl
Currently, just call the `writer.fail(e);` and don't throw InterruptedException when caught the InterruptedException in ChannelStateWriterThread. So ChannelStateWriterThread cannot exit when meet InterruptedException. We should throw InterruptedException, and the ChannelStateWriterThread will be finished.
Catch InterruptedException and throw it when caught the InterruptedException in ChannelStateWriterThread.
- Anything …
=> [FLINK-28077][checkpoint] Fix the bug that tasks get stuck during cancellation in ChannelStateWriteRequestExecutorImpl

docs/content.zh/docs/deployment/memory/network_mem_tuning.md, docs/content/docs/deployment/memory/network_mem_tuning.md
This documents a change added by https://github.com/apache/flink/pull/19499 . No testing coverage is necessary.
- The S3 file system connector: (yes / no ****/ don't know)
=> [FLINK-26762][docs] Document overdraft buffers

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StopWithSavepoint.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StopWithSavepointTest.java
The `StopWithSavepoint` state of the adaptive scheduler has to account for a number of failure scenarios.
One of these failure cases is a task failure with the savepoint going through. This for example happens when an exception is thrown in `notifyCheckpointComplete()`. In FLINK-26923 the code was changed to not trigger a restart in this case, and instead hard-fail the job, on the grounds that continuing a job despite a savepoint being created could lead to duplicate data.
This change was done incorrectly, because it assumed the savepoint future to always complete first. There is however no such guarantee that this is actually the case.
Primarily because the checkpoint coordinator does not run in the main thread it can happen that _any_ failure happening around the time the CC completes …
=> [FLINK-27972][coordination] Wait until savepoint operation is complete 

flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNHighAvailabilityITCase.java, flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNITCase.java, flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNSessionCapacitySchedulerITCase.java
Stabilizing YARN IT test cases. Currently, they tend to fail, because of a concurrent temp folder cleanup.
Added separate JUnit temp dirs for test cases to avoid concurrent cleanup under the same root dir.
_in progress_
=> [FLINK-27667][yarn-tests] Stabilize flaky YARN integration tests

docs/layouts/shortcodes/generated/yarn_config_configuration.html, flink-yarn/src/main/java/org/apache/flink/yarn/configuration/YarnConfigOptions.java
- The https://hortonworks.com/blog/apache-hadoop-yarn-hdp-2-2-fault-tolerance-features-long-running-services/ link inaccessible.
- The correct link should be https://hadoop.apache.org/docs/stable/hadoop-yarn/hadoop-yarn-site/ResourceManagerRest.html#Cluster_Application_Attempts_API.
- Update the  inaccessible documentation link. …
=> [hotfix][docs] Fix the inaccessible documentation link.

flink-examples/flink-examples-table/pom.xml, pom.xml
- I think the Intellij should be changed to IntelliJ IDEA. For details, please refer to the official website https://www.jetbrains.com/idea/ and https://en.wikipedia.org/wiki/IntelliJ_IDEA.
- Modify Intellij to IntelliJ IDEA.
=> [hotfix][docs] Fix the Intellij key nouns.

flink-core/src/main/java/org/apache/flink/core/fs/FileSystem.java, flink-core/src/test/java/org/apache/flink/core/fs/FileSystemTest.java
The error message is wrong when a directly supported filesystem is not able to be handled.
In this PR I've fixed it.
* Split the error message to 2 parts, directly supported and not directly supported cases
* Adapted the existing unit tests
* Made the unit tests junit5 compliant
=> [FLINK-28112][filesystems] Fix error message when directly supported file system is not able to be handled

azure-pipelines.yml, flink-connectors/flink-connector-hbase-1.4/pom.xml, flink-connectors/flink-connector-hbase-2.2/pom.xml, flink-end-to-end-tests/flink-end-to-end-tests-hbase/pom.xml, flink-filesystems/flink-hadoop-fs/pom.xml, flink-formats/flink-hadoop-bulk/pom.xml, flink-formats/flink-orc-nohive/pom.xml, flink-formats/flink-orc/pom.xml, flink-fs-tests/pom.xml, flink-yarn-tests/pom.xml, flink-yarn/pom.xml, pom.xml, tools/azure-pipelines/build-apache-repo.yml
Prevent conflicts with the `hadoop.version` property in the Hadoop parent pom, when using Maven 3.8.5+.
This lead to our modules that use Hadoop 3 to partially bundle Hadoop 2.8.5 when `-Dhadoop.version=2.8.5` was set on the command-line (which we do on CI).
=> [FLINK-28196][build] Rename hadoop.version property

docs/content.zh/docs/ops/upgrading.md
Translate `upgrading.md` into chinese [FLINK-27926](https://issues.apache.org/jira/browse/FLINK-27926). The documentation is about upgrading existing flink cluster. 
NOTE: wrong issue number attached in previous edit of the issue and commit message
- *Duplicate upgrading.md from current master to content.zh*
- *Translate the documentation with automatic translation*
- *Manually inspect translation and calibrate with translation table*
- Rebuild doc and visually inspect the new page …
=> [FLINK-27926][Docs] Translating the `Upgrading Applications and Flink versions` page to Chinese

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/Table.java
fix and unified the example JavaDoc for most DSL methods of Table class
- *fix some misunstanding typo of Scala  to Java*
- *add Java before Example against Scala Example* …
=> [hotfix][table-api-java][javadoc]fix and unified the example JavaDoc for most DSL methods of Table class

flink-core/src/main/java/org/apache/flink/configuration/AkkaOptions.java, flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaRpcActor.java, flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaRpcService.java, flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/FencedAkkaRpcActor.java, flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/AkkaRpcActorOversizedResponseMessageTest.java, flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/ContextClassLoadingSettingTest.java, flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/async/AbstractAsynchronousOperationHandlers.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/async/CompletedOperationCache.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/async/OperationResult.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/dataset/ClusterDataSetDeleteHandlers.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/TestingDispatcher.java, flink-tests/src/test/java/org/apache/flink/test/classloading/ClassLoaderITCase.java
Based on #19968 because this PR changes some timings that trigger FLINK-27972.
With this PR the OperationResult is serializable, as well as the contained result.
Additionally the switch to force serialization, introduced in FLINK-26780, now also applies to return values (and not just method arguments). Several problematic cases, mostly in tests, were also fixed.
=>  [FLINK-27933][coordination] OperationResult is serializable 

flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/catalog/AbstractJdbcCatalog.java, flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/catalog/MySqlCatalog.java, flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/catalog/MySqlCatalogITCase.java, flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/catalog/MySqlCatalogTestBase.java, flink-connectors/flink-connector-jdbc/src/test/resources/mysql-scripts/catalog-init-for-test.sql
Use MysqlCatalog to get the primary key of the table when there are tables with same name in different databases.
Pass the database name as catalog parameter for retrieving primary keys by full table identifier in `metaData.getPrimaryKeys(database, schema, table)`
=> [FLINK-27794][connectors/jdbc] Fix the wrong primary key for MysqlCatalog when there are tables with same name in different databases

flink-end-to-end-tests/test-scripts/docker-hadoop-secure-cluster/Dockerfile, flink-end-to-end-tests/test-scripts/test_kubernetes_pyflink_application.sh, flink-end-to-end-tests/test-scripts/test_pyflink.sh, flink-end-to-end-tests/test-scripts/test_pyflink_yarn.sh, flink-python/dev/dev-requirements.txt
*This pull request will limit grpcio<1.47*
- *Limit grpcio<1.47*
=> [FLINK-28226][python] Limit grpcio<1.47

flink-formats/flink-orc/pom.xml, flink-formats/flink-parquet/pom.xml
Multiple Parquet format tests are failing with `NoSuchMethodError` in hadoop cron builds.
- * Specify guava version explicitly in flink-orc and flink-parquet *
=> [FLINK-28173][formats] Specify guava version explicitly in flink-orc and flink-parquet

flink-end-to-end-tests/test-scripts/test_tpcds.sh
* The TPCDS tests generated folders/files, but doesn't clean them up afterwards. This causes out of diskspace errors further downstream. This change cleans up those files/folders
* Remove the folders/files that are generated by TPCDS tests …
=> [FLINK-28263][TPCDS][Tests] Clean-up generated data folder by TPCDS test

flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/converter/AbstractJdbcRowConverter.java, flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/converter/PostgresRowConverter.java, flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/internal/converter/PostgresRowConverterTest.java
Add support for reading and writing postgres UUID types via Flink SQL STRING type
- modified AbstractJdbcRowConverter.createInternalConverter to use toString() for CHAR and VARCHAR types instead of casting to string. Previously the cast would fail for postgres UUIDs
- add createExternalConverter override to PostgresRowConverter for CHAR and VARCHAR types. It will check if the string is a UUID and pass the UUID to the PreparedSatement via setObject if so …
=> [FLINK-19869][connectors/jdbc] Add support for postgres UUID type

flink-end-to-end-tests/test-scripts/common_kubernetes.sh
* All Kubernetes Bash tests are currently failing because Kubernetes 1.24+ has dropped support for Dockershim. If we want to continue using the combination of the none Driver, Kubernetes 1.24+ and the Docker container runtime, we'll need to install cri-dockerd. This also requires crictl. This is listed in the requirements at https://minikube.sigs.k8s.io/docs/drivers/none/#requirements
* Install cri-dockerd and crictl during the setup of Kubernetes …
=> [FLINK-28269][Kubernetes] Install cri-dockerd and crictl so we can continue using driver `none` when running Kubernetes tests

flink-core/src/main/java/org/apache/flink/util/FlinkUserCodeClassLoader.java, flink-core/src/main/java/org/apache/flink/util/FlinkUserCodeClassLoaders.java, flink-core/src/main/java/org/apache/flink/util/MutableURLClassLoader.java, flink-core/src/test/java/org/apache/flink/util/FlinkUserCodeClassLoadersTest.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/resource/ResourceManager.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/resource/ResourceManagerTest.java
In table module, we need an `URLClassLoader` which exposes the `addURL` method because we need to load jar dynamically in sql job. Although the SafetyNetWrapperClassLoader has exposed `addURL` method, but we can't ensure the  classloader created by `FlinkUserCodeClassLoaders` is `SafetyNetWrapperClassLoader`, because the returned classloader might not be `SafetyNetWrapperClassLoader` if checkClassLoaderLeak is false. So we need introduce a `MutableURLClassLoader` that exposes the `addURL`, and the `SafetyNetWrapperClassLoader` and `FlinkUserCodeClassLoader` both extends it, we only need refer to this class in table module.
- *Introduce MutableURLClassLoader as parent class of FlinkUserClassLoader and SafetyNetWrapperClassLoader* …
=> [FLINK-28080][runtime] Introduce MutableURLClassLoader as parent class of FlinkUserClassLoader and SafetyNetWrapperClassLoader

flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/iteration/IterateExample.java, flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/sideoutput/SideOutputExample.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java
This is a trivial change that deprecates StreamExecutionEnvironment#readFile()/readTextFile() methods.
=> [FLINK-28047][api] Deprecate StreamExecutionEnvironment#readFile()/readTextFile() methods

docs/data/sql_functions_zh.yml
There is an unuseful space in `sql_functions_zh.yml` in the Chinese docs.
=> [hotfix][docs] Remove an unuseful space

flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/session/Session.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/result/ResultFetcherTest.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/session/SessionManagerTest.java
*The current tests in the `SessionManagerTest` are unstable. After reading the logs, I find the created session is immediately removed, which causes the test fails. The reason causes the phenomenon is we don't assign the last access time when we create the session. The timer may check the idleness before users send the request to the Session, which causes the test fails.*
- *Set the last access time in the constructor.* …
=> [FLINK-28290][sql-gateway] Set lastAccessTime when create the Session

docs/content.zh/docs/ops/state/state_backends.md, docs/content/docs/ops/state/state_backends.md, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/AbstractCompleteCheckpointStore.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointsCleaner.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/DefaultCompletedCheckpointStore.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/EmbeddedCompletedCheckpointStore.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/OperatorSubtaskState.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/StandaloneCompletedCheckpointStore.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/SharedStateRegistry.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/SharedStateRegistryImpl.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/ChangelogStateBackendHandle.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorFailureTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointsCleanerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CompletedCheckpointStoreTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/SharedStateRegistryTest.java, flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/AbstractChangelogStateBackend.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/ChangelogPeriodicMaterializationSwitchEnvTestBase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/ChangelogPeriodicMaterializationSwitchStateBackendITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/LegacyStatefulJobSavepointMigrationITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/StatefulJobWBroadcastStateMigrationITCase.java, flink-tests/src/test/java/org/apache/flink/test/migration/TypeSerializerSnapshotMigrationITCase.java, flink-tests/src/test/java/org/apache/flink/test/state/ChangelogCompatibilityITCase.java, flink-tests/src/test/java/org/apache/flink/test/state/operator/restore/AbstractOperatorRestoreTestBase.java, flink-tests/src/test/scala/org/apache/flink/api/scala/migration/StatefulJobSavepointMigrationITCase.scala, flink-tests/src/test/scala/org/apache/flink/api/scala/migration/StatefulJobWBroadcastStateMigrationITCase.scala
*Nowadays, recovering from non-changelog checkpoints is disallowed. Because when restoring from a non-changelog checkpoint with changelog state-backend enabled in CLAIM mode, the restored checkpoint may be discarded on subsuming. And the subsumed checkpoint might cause materialized artifacts to be dropped. This PR wants to support restore from non-changelog checkpoint with changelog enabled in CLAIM mode.*
- *Revert https://github.com/apache/flink/pull/18735*
- *Cast `keyedStateHandle` to `ChangelogStateBackendHandle` on JM when changelog is enabled*
This change added one test and can be verified as follows:
- *`ChangelogRestoreITCase#testSwitchFromDisablingToEnablingInClaimMode()`* …
=> [FLINK-25872][state] Support restore from non-changelog checkpoint with changelog enabled in CLAIM mode

docs/data/sql_functions.yml, docs/data/sql_functions_zh.yml, flink-python/pyflink/table/expression.py, flink-python/pyflink/table/tests/test_expression.py, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/expressions/converter/DirectConvertRule.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/ScalarFunctionsTest.scala
Support decode and encode built-in functions in Table API.
- *Support decode and encode built-in functions in Table API.*
- *Support decode and encode built-in functions in Python Table API.*
- *Added test that validates that decode and encode in Table API work*
- *Added test that validates that decode and encode in Python Table API work*
- The runtime per-record code paths (performance sensitive)no)
- …
=> [FLINK-28288][table][python] Support decode and encode in Table API

flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/SqlGatewayServiceITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/result/ResultFetcherTest.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/utils/IgnoreErrorThreadFactory.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/utils/IgnoreExceptionHandler.java
…sultInParallel
*Fix the unstable test case.  The root cause is the fetcher thread and another thread is in parallel. There are two cases:*
*1. The fetcher gets the Operation and then another thread closes the Operation. Then the fetcher gets the error message "Can not fetch results in closed operation."*
*2. The closing thread closes the Operation and removes the Operation from the Operation Manager, then the fetcher tries to fetch the results. In this case, the fetcher will get the message "Can not find the operation".*
- *Matches the expected error message in the test.*
- *In the concurrent test, the thread print the error msg to the terminal when getting exceptions. Introduce an `IgnoreErrorThreadFactory` to swallow the useless message.*
This change is a trivial rework / code cleanup …
=> [FLINK-28238][sql-gateway] Fix unstable testCancelOperationAndFetchResultInParallel

docs/data/sql_functions.yml, docs/data/sql_functions_zh.yml, flink-python/pyflink/table/expression.py, flink-python/pyflink/table/tests/test_expression.py, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/expressions/converter/DirectConvertRule.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/ScalarFunctionsTest.scala
Support decode and encode built-in functions in Table API.
- *Support left and right built-in functions in Table API.*
- *Support left and right built-in functions in Python Table API.*
- *Added test that validates that left and right in Table API work*
- *Added test that validates that left and right in Python Table API work*
- Does this …
=> [FLINK-28298][table][python] Support left and right in Table API

flink-end-to-end-tests/test-scripts/test-runner-common.sh, tools/ci/controller_utils.sh
We are having the situation where a lot of disk space gets used by both Bash and Java E2E tests. In order to identify which tests aren't properly cleaning up, it would be good if we output the top 15 directories which are the biggest in used disk space
* Output top 15 directories with that are using the most disk space in Bash E2E tests …
=> [FLINK-28329][Tests] Output the top 15 directories in terms of used disk space

flink-end-to-end-tests/flink-sql-client-test/pom.xml, flink-formats/flink-csv/pom.xml, flink-formats/flink-json/pom.xml, flink-formats/flink-sql-csv/pom.xml, flink-formats/flink-sql-json/pom.xml, flink-formats/pom.xml
Use the same module structure for csv/json as for other formats for consistency, and remove a shade-plugin special case.
=> [FLINK-28222][formats] Add sql modules for csv/json formats

docs/content.zh/docs/connectors/table/datagen.md, docs/content/docs/connectors/table/datagen.md, flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/connector/datagen/table/RandomGeneratorVisitor.java, flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/connector/datagen/table/SequenceGeneratorVisitor.java, flink-table/flink-table-api-java-bridge/src/test/java/org/apache/flink/table/factories/DataGenTableSourceFactoryTest.java
Add BYTES type `binary `& `varbinary` support for datagen connector to refine datagen using.  
Add binary & varbinary type support for datagen connector. 
Add case in `DataGenTableSourceFactoryTest`.
- If yes, how is the feature documented? yes
=> [FLINK-27806][table] Support binary & varbinary types in datagen connector

flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/FileSystemTableSink.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveTableSink.java, flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/table/KafkaDynamicSink.java, flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/connector/sink/DataStreamSinkProvider.java, flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/connector/source/DataStreamScanProvider.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/connectors/CollectDynamicSink.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecSinkITCase.java
In [FLINK-25990](https://issues.apache.org/jira/browse/FLINK-25990) ,
Add a method "DataStream<RowData> produceDataStream(ProviderContext providerContext, StreamExecutionEnvironment execEnv)" in DataStreamScanProvider.
But this method has no default implementation, this is not compatible when users upgrade their DataStreamScanProvider implementation from 1.14 to 1.15. (The old method will not be called)
DataStreamSinkProvider is the same.
DataStreamScanProvider's new method should be:
```
default DataStream<RowData> produceDataStream(
ProviderContext providerContext, StreamExecutionEnvironment execEnv) {
return produceDataStream(execEnv);
}
```
Impact on DataStreamSinkProvider:
DataStreamSinkProvider is no longer a functional interface and requires the use of an anonymous internal class. …
=> [FLINK-28322][table-api] DataStreamScan(Sink)Provider's new method is not compatible

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java, flink-tests/src/test/java/org/apache/flink/test/scheduling/ReactiveModeITCase.java
set the max parallelism of ContinuousFileMonitoringFunction explicitly in case AdaptiveScheduler changes the parallelism of this function.
- covered by existed ut. …
=> [FLINK-28274][runtime] set the max parallelism of ContinuousFileMonitoringFunction explicitly

flink-clients/src/test/java/org/apache/flink/client/program/PerJobMiniClusterFactoryTest.java
The test makes a generally incorrect assumption that the job is in a RUNNING state when the job submission returns, but we only guarantee that it is not in an initializing state.
=> [FLINK-26323][tests] Allow CREATED state

flink-clients/src/test/java/org/apache/flink/client/program/PerJobMiniClusterFactoryTest.java
It only makes sense to trigger savepoints when the job is actually RUNNING. Triggering a savepoint while the job is in the CREATED state is tolerated in the default scheduler (even though the checkpoint will immediately fail), but the adaptive scheduler rejects it eagerly.
Ideally we'd align the behavior in a follow-up.
Ideally ideally the clients would take care of that, but there are quite a few of them and so far they are pretty dumb in that they just forward the request as is. This is possible to change, but it's a larger effort.
=> [FLINK-26600][tests] Wait with savepoint until job is running

flink-end-to-end-tests/test-scripts/test-runner-common.sh, tools/ci/controller_utils.sh
(cherry picked from commit a33970455712b9d5a67cc66bb049d94ad4c4b543)
Unchanged backport of https://github.com/apache/flink/pull/20114
=> [FLINK-28329][BP 1.14][Tests] Output the top 15 directories in terms of used disk space

flink-end-to-end-tests/test-scripts/test-runner-common.sh, tools/ci/controller_utils.sh
(cherry picked from commit a33970455712b9d5a67cc66bb049d94ad4c4b543)
Unchanged backport of https://github.com/apache/flink/pull/20114
=> [FLINK-28329][BP 1.15][Tests] Output the top 15 directories in terms of used disk space

docs/data/sql_functions.yml, docs/data/sql_functions_zh.yml, flink-python/pyflink/table/expression.py, flink-python/pyflink/table/tests/test_expression.py, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/expressions/converter/DirectConvertRule.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/ScalarFunctionsTest.scala
Support instr and locate built-in functions in Table API.
- *Support PARSE_URL built-in functions in Table API.*
- *Support PARSE_URL built-in functions in Python Table API.*
- *Added test that validates that PARSE_URL in Table API work*
- *Added test that validates that PARSE_URL in Python Table API work* …
=> [FLINK-28369][table][python] Support PARSE_URL in Table API

flink-table/flink-sql-gateway-api/pom.xml, flink-table/flink-sql-gateway-api/src/main/java/org/apache/flink/table/gateway/api/endpoint/SqlGatewayEndpoint.java, flink-table/flink-sql-gateway-api/src/main/java/org/apache/flink/table/gateway/api/endpoint/SqlGatewayEndpointFactory.java, flink-table/flink-sql-gateway-api/src/main/java/org/apache/flink/table/gateway/api/endpoint/SqlGatewayEndpointFactoryUtils.java, flink-table/flink-sql-gateway-api/src/test/java/org/apache/flink/table/gateway/api/endpoint/SqlGatewayEndpointFactoryUtilsTest.java, flink-table/flink-sql-gateway-api/src/test/java/org/apache/flink/table/gateway/api/utils/FakeSqlGatewayEndpoint.java, flink-table/flink-sql-gateway-api/src/test/java/org/apache/flink/table/gateway/api/utils/FakeSqlGatewayEndpointFactory.java, flink-table/flink-sql-gateway-api/src/test/java/org/apache/flink/table/gateway/api/utils/MockedSqlGatewayEndpoint.java, flink-table/flink-sql-gateway-api/src/test/java/org/apache/flink/table/gateway/api/utils/MockedSqlGatewayEndpointFactory.java, flink-table/flink-sql-gateway-api/src/test/java/org/apache/flink/table/gateway/api/utils/MockedSqlGatewayService.java, flink-table/flink-sql-gateway-api/src/test/resources/META-INF/services/org.apache.flink.table.factories.Factory, flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/FactoryUtil.java
*Introdue Endpoint API and utils to create endpoint.*
- *Introduce the Endpoint API*
- *Introduce the Factory to create the endpoint*
- *Introduce the FactoryUtils to find the EndpointFactory.*
- *Added tests to create the Mocked endpoint.*
- *Added negative tests to create the endpoint.* …
=> [FLINK-27767][sql-gateway] Introduce Endpoint API and utils

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraph.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamNode.java, flink-tests/src/test/java/org/apache/flink/test/streaming/api/datastream/FinishedSourcesWatermarkITCase.java
Otherwise tasks can not correctly determine number of inputs. This was causing an
issue where restored as finished OneInputStreamTask was waiting for MAX_WATERMARK
from two inputs, where the second one was null.
- The S3 file system connector: (yes / no ****/ don't know)
- If yes, …
=> [FLINK-28357][datastream] Disallow null elements in StreamNode#typeSerializersIn     

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/functions/hive/HiveFunctionWrapper.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParser.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserDDLSemanticAnalyzer.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectITCase.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/planner/delegation/hive/HiveASTParserTest.java
Hive dialect supports macro.
-  Support parse `create/drop macro`
-  Convert calling `macro` to invoking Hive's GenericUDFMacro
Added test in [...link-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectITCase.java](https://github.com/apache/flink/pull/19561/files#diff-748a9fa63f15b3bd3ea5426a5b42179cadee77ecf3359c83f846aedb27d96871)#testMacro …
=> [FLINK-26414][hive] Hive dialect supports macro

tools/ci/java-ci-tools/src/main/java/org/apache/flink/tools/ci/licensecheck/NoticeFileChecker.java, tools/ci/java-ci-tools/src/main/java/org/apache/flink/tools/ci/suffixcheck/ScalaSuffixChecker.java, tools/ci/java-ci-tools/src/main/java/org/apache/flink/tools/ci/utils/dependency/Dependency.java, tools/ci/java-ci-tools/src/main/java/org/apache/flink/tools/ci/utils/dependency/DependencyParser.java, tools/ci/java-ci-tools/src/test/java/org/apache/flink/tools/ci/utils/dependency/DependencyParserCopyTest.java, tools/ci/java-ci-tools/src/test/java/org/apache/flink/tools/ci/utils/dependency/DependencyParserTreeTest.java
This PR reworks the parsing of the output from the dependency-plugin to make it more generic and re-usable for other checks.
The scala suffix and notice checkers, the only current users, were migrated as part of this PR.
=> [FLINK-28201][ci] Generalize utils around dependency plugin 

docs/data/sql_functions.yml, docs/data/sql_functions_zh.yml, flink-python/pyflink/table/expression.py, flink-python/pyflink/table/tests/test_expression.py, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/expressions/converter/DirectConvertRule.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/ScalarFunctionsTest.scala
Support instr and locate built-in functions in Table API.
- *Support  SUBSTR and REGEXP built-in functions in Table API.*
- *Support  SUBSTR and REGEXP built-in functions in Python Table API.*
- *Added test that validates that SUBSTR and REGEXP in Table API work*
- *Added test that validates that SUBSTR and REGEXP in Python Table API work* …
=> [FLINK-28439][table][python] Support SUBSTR and REGEXP built-in function in Table API

tools/ci/java-ci-tools/src/main/java/org/apache/flink/tools/ci/licensecheck/NoticeFileChecker.java, tools/ci/java-ci-tools/src/main/java/org/apache/flink/tools/ci/suffixcheck/ScalaSuffixChecker.java, tools/ci/java-ci-tools/src/main/java/org/apache/flink/tools/ci/utils/dependency/DependencyParser.java, tools/ci/java-ci-tools/src/main/java/org/apache/flink/tools/ci/utils/shared/Dependency.java, tools/ci/java-ci-tools/src/test/java/org/apache/flink/tools/ci/utils/dependency/DependencyParserCopyTest.java, tools/ci/java-ci-tools/src/test/java/org/apache/flink/tools/ci/utils/dependency/DependencyParserTreeTest.java
Based on #20053.
Deduplicates the Dependency classes from the NoticeFileChecker and the one introduced in #20053. The goal is to ease interoperability between plugins/parser results, as most checks use 2 sources to parse dependencies.
=> [FLINK-28230][ci] Unify Dependency class 

flink-runtime/src/main/java/org/apache/flink/runtime/util/config/memory/ProcessMemoryUtils.java
Fix log information typo in sanityCheckJvmOverhead method of ProcessMemoryUtils Class
modified the case of a string word in sanityCheckJvmOverhead method of ProcessMemoryUtils Class
=> [hotfix][Runtime/Configuration] Fix typo in ProcessMemoryUtils Class

flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FileStateHandle.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/memory/ByteStreamStateHandle.java
...  to avoid unnecessary overhead when it's not used.
Original benchmark results (good): http://codespeed.dak8s.net:8080/job/flink-benchmark-request/165/
Current  benchmark results (bad): http://codespeed.dak8s.net:8080/job/flink-master-benchmarks-java8/468/
Benchmark results with this change (good): http://codespeed.dak8s.net:8080/job/flink-benchmark-request/170/
(the benchmark is somewhat unstable so I ran it twice)
=> [FLINK-27556][state] Inline state handle id generation

docs/content.zh/docs/connectors/datastream/kafka.md, docs/content/docs/connectors/datastream/kafka.md, flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/OffsetsInitializer.java
Fix the wrong timestamp unit of KafkaSource.
Fix the wrong timestamp unit of KafkaSource.
=> [FLINK-28454][kafka][docs] Fix the wrong timestamp unit of KafkaSource

pom.xml
This is a trivial PR updating version of assertj to 3.23.1
assertj version in pom
=> [FLINK-28466][Tests] Bump assertj to 3.23.1

flink-dist/src/main/resources/flink-conf.yaml
Fixes small typo in flink-conf.yaml. file.
=> [hotfix] [docs] Fix small typo in flink-conf.yaml file

flink-runtime/src/test/java/org/apache/flink/runtime/security/token/KerberosLoginProviderITCase.java
Similar to https://github.com/apache/flink/pull/19910; extended to all classes that mock the `UserGroupInformation`.
=> [FLINK-28379][security] Run all UGI mocking tests in separate JVM

docs/content.zh/docs/concepts/glossary.md
- Translate Glossary page into Chinese: https://nightlies.apache.org/flink/flink-docs-master/zh/docs/concepts/glossary/.
- The markdown file is located in docs/concepts/glossary.md.
- In https://nightlies.apache.org/flink/flink-docs-master/zh/docs/concepts/glossary/, most of them have been translated, but a small part has not been translated into Chinese. Details See [FLINK-13037](https://issues.apache.org/jira/browse/FLINK-13037) for information.
- Translate "Concepts -> Glossary" page into Chinese.
- The public API, i.e., is any changed class annotated with @Public(Evolving): **no**
- The serializers:  **no** …
=> [FLINK-27205][docs-zh] Translate "Concepts -> Glossary" page into Chinese.

flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/batch/connectors/cassandra/CassandraColumnarOutputFormatBase.java, flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/batch/connectors/cassandra/CassandraOutputFormatBase.java, flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/batch/connectors/cassandra/CassandraPojoOutputFormat.java, flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/streaming/connectors/cassandra/CassandraSinkBase.java, flink-core/src/main/java/org/apache/flink/api/common/io/OutputFormatBase.java, flink-core/src/main/java/org/apache/flink/api/common/io/SinkUtils.java, flink-core/src/test/java/org/apache/flink/api/common/io/OutputFormatBaseTest.java
Move OutputFormatBase to flink-core to offer flush mechanism to all output formats
Move OutputFormatBase from connectors-cassandra module to flink-core to offer flush mechanism to all output formats.
Main change was to change (not yet public) send method signature so that it returns a `CompletionStage` and not a guava `ListenableFuture`. Implementers can chose their `CompletionStage` implementation as long as it implements `CompletionStage#toCompletableFuture()`
This change is already covered by existing tests, such as OutputFormatBaseTest and CassandraConnectorITCase (for first implementation) …
=> [FLINK-27884] Move OutputFormatBase to flink-core to offer flush mechanism to all output formats

docs/content.zh/docs/deployment/config.md, docs/content/docs/deployment/config.md, docs/layouts/shortcodes/generated/rocksdb_native_metric_configuration.html, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/EmbeddedRocksDBStateBackend.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackendBuilder.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBNativeMetricMonitor.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBNativeMetricOptions.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBResourceContainer.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBHandle.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBNativeMetricMonitorTest.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBResource.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateBackendConfigTest.java
Introduce and expose RocksDB statistics as metrics.
- Introduce RocksDB statistics based metrics.
- Expose these native metrics via `RocksDBNativeMetricMonitor`.
This change added tests and can be verified as follows: `RocksDBNativeMetricMonitorTest`.
=> [FLINK-24786][state] Introduce and expose RocksDB statistics as metrics

docs/data/sql_functions.yml, docs/data/sql_functions_zh.yml, flink-python/pyflink/table/expression.py, flink-python/pyflink/table/tests/test_expression.py, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/expressions/converter/DirectConvertRule.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/ScalarFunctionsTest.scala
Support SPLIT_INDEX and STR_TO_MAP built-in functions in Table API.
- *Support SPLIT_INDEX and STR_TO_MAP built-in functions in Table API.*
- *Support SPLIT_INDEX and STR_TO_MAP built-in functions in Python Table API.*
- *Added test that validates that SPLIT_INDEX and STR_TO_MAP in Table API work*
- *Added test that validates that SPLIT_INDEX and STR_TO_MAP in Python Table API work* …
=> [FLINK-28508][table][python] Support SPLIT_INDEX and STR_TO_MAP built-in functions in Table API

docs/content.zh/docs/deployment/resource-providers/standalone/working_directory.md
- **This is the English document：**
- **This is the Chinese document：**
- **According to the above two figures, it can be seen that the  working_directory.md file  is missing in the  standalone  Chinese document.**
-  **Add missing the working_directory.md file to the standalone part.**
- **This change is a trivial rework / code cleanup without any test coverage.**
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't …
=> [hotfix][docs-zh] Add missing the working_directory.md file to the standalone part.

docs/data/sql_functions.yml, docs/data/sql_functions_zh.yml, flink-python/pyflink/table/expression.py, flink-python/pyflink/table/tests/test_expression.py, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/expressions/converter/DirectConvertRule.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/ScalarFunctionsTest.scala
Support REVERSE built-in functions in Table API.
- *Support REVERSE built-in functions in Table API.*
- *Support REVERSE built-in functions in Python Table API.*
- *Added test that validates that REVERSE in Table API work*
- *Added test that validates that REVERSE in Python Table API work* …
=> [FLINK-28509][table][python] Support REVERSE built-in function in Table API

flink-connectors/flink-connector-cassandra/src/test/java/org/apache/flink/streaming/connectors/cassandra/CassandraConnectorITCase.java
Raise driver timeouts per session request and raise it higher than cluster side timetouts
Change in the CassandraITCase
This change is already covered by existing tests, such as *CassandraITCase*
R: @MartijnVisser
=> [FLINK-28198][connectors][cassandra] raise driver timeouts per session request and raise it higher than cluster side timetouts

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserCalcitePlanner.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserUtils.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java
Make Hive dialect support `TABLESAMPLE (N rows)`.
-  When it's table sample for N rows, add a limit node(actually calcite `LogicalSort` with offset and fetch). The behavior follows `Hive` and `Spark`.  For other sample cases, throw `UnsupportedOperationException` directly.
UT
=> [FLINK-28089][hive] Hive dialect support "TABLESAMPLE (N rows)"

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/NettyShuffleServiceFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/ShuffleEnvironmentContext.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerServices.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/NettyShuffleEnvironmentBuilder.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/SharedPoolNettyShuffleServiceFactory.java
*Currently, the number of IO threads for shuffle data reading is relevant to the size of reading memory and the number of CPU cores. We should also consider the number of slots and the number of disks.*
- *Restrict the number of threads for sort-shuffle data read*
This change is already covered by existing tests, such as *SharedPoolNettyShuffleServiceFactory*. …
=> [FLINK-28376][network] Restrict the number of threads for sort-shuffle data read

flink-runtime/src/test/java/org/apache/flink/runtime/operators/testutils/MockEnvironment.java
I believe `com.sun.istack.NotNull` was accidentally used in testuils
```
$ grep -rw . -e 'import com.sun.istack.NotNull;'
./flink-runtime/src/test/java/org/apache/flink/runtime/operators/testutils/MockEnvironment.java:import com.sun.istack.NotNull;
```
Removed `com.sun.istack.NotNull` from testutils …
=> [hotfix][runtime] Remove com.sun.istack.NotNull from testutils

docs/layouts/shortcodes/generated/yarn_config_configuration.html, flink-yarn/src/main/java/org/apache/flink/yarn/Utils.java, flink-yarn/src/main/java/org/apache/flink/yarn/YarnApplicationFileUploader.java, flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java, flink-yarn/src/main/java/org/apache/flink/yarn/configuration/YarnConfigOptions.java, flink-yarn/src/test/java/org/apache/flink/yarn/UtilsTest.java
Support using `usrlib` in HDFS for jobs submitted in YARN application mode.
- Introduce new config option `YarnConfigOption.PROVIDED_USRLIB_DIR` to specify `usrlib` in HDFS for application mode.
- Refactor some utils function to reuse codes for parsing and validating remote `usrlib`.
- Add unit/integration tests for using `usrlib` in hdfs.
- Added integration tests for deploying a job in YARN with remote `usrlib`.
- Added unit tests for validation of specified remote `usrlib` path.
- …
=> [FLINK-26047][yarn] Support remote usrlib in HDFS for YARN deployment

flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcher.java, flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriber.java, flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisITCase.java, flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcherTest.java, flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriberTest.java, flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/FakeKinesisBehavioursFactory.java, flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/TestableKinesisDataFetcher.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectSinkOperator.java
Make necessary changes for KDS connector to survive stop-with-savepoint workflow. Based on:
https://github.com/apache/flink/pull/17189/ 
*   Reenable and harden FlinkKinesisITCase
*   Fix DataStream#executeAndCollect for stop with savepoint without drain
*   Avoid another source of interruptions during shutdown of Kinesis consumer
*   Ensure EFO version of the connector stops gracefully 
* All covered by the newly expanded FlinkKinesisITCase
* EFO scenarios verified locally against custom AWS account and real Kinesis stream
- Dependencies (does it add or upgrade a dependency): (~yes~ / *no*)
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (~yes~ / *no*)
- The serializers: (~yes~ / *no* / ~don't know~) …
=> [FLINK-23528][connectors/kinesis] Kinesis Consumer stop-with-savepoint support including EFO

flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcher.java, flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriber.java, flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisITCase.java, flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcherTest.java, flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutShardSubscriberTest.java, flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/FakeKinesisBehavioursFactory.java, flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/TestableKinesisDataFetcher.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectSinkOperator.java
Make necessary changes for KDS connector to survive stop-with-savepoint workflow. Based on:
https://github.com/apache/flink/pull/17189/ 
*   Reenable and harden FlinkKinesisITCase
*   Fix DataStream#executeAndCollect for stop with savepoint without drain
*   Avoid another source of interruptions during shutdown of Kinesis consumer
*   Ensure EFO version of the connector stops gracefully 
* All covered by the newly expanded FlinkKinesisITCase
* EFO scenarios verified locally against custom AWS account and real Kinesis stream
- Dependencies (does it add or upgrade a dependency): (~yes~ / *no*)
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (~yes~ / *no*)
- The serializers: (~yes~ / *no* / ~don't know~) …
=> Flink 23528 fix master

flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/services/LoadBalancerService.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/services/NodePortService.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/KubernetesClientTestBase.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/Fabric8FlinkKubeClientTest.java
when the job is submitted to the k8s cluster and the parameter `-Dkubernetes.rest-service.exposed.type=NodePort` is used, the web ui address of the job obtained at this time is the IP of any machine in the k8s cluster.
but client will throw connect refuse exception when the node's schedule status is unschedulable. We should exclude those node IPs to choose web ui address
- `ServiceType#getRestEndpoint` search node exclude unschedulable node (spec.unschedulable = true)
update unit tests for the change. `Fabric8FlinkKubeClientTest#testNodePortServiceWithInternalIP` …
=> [FLINK-28353][k8s] Exclude unschedulable nodes using IP addresses of kubernetes nodes

docs/content.zh/docs/connectors/datastream/filesystem.md, docs/content.zh/docs/connectors/datastream/formats/csv.md, docs/content/docs/connectors/datastream/filesystem.md, docs/content/docs/connectors/datastream/formats/csv.md, flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/CsvFileFormatFactory.java, flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/CsvReaderFormat.java, flink-formats/flink-csv/src/test/java/org/apache/flink/formats/csv/CsvReaderFormatTest.java, flink-formats/flink-csv/src/test/java/org/apache/flink/formats/csv/DataStreamCsvITCase.java, flink-python/pom.xml, flink-python/pyflink/datastream/formats/csv.py, flink-python/src/main/java/org/apache/flink/formats/csv/CsvReaderFormatFactory.java
Adjusts the CsvReaderFormat API to accept a factory/generator for the mapper/schema respectively, to support mappers that are using non-serializable extensions (like the `JavaTimeModule`).
=> [FLINK-28624][csv] Accept mapper/schema factories

tools/azure-pipelines/free_disk_space.sh
Tests are running out of disk space. With this PR we'll have 53 instead of 24GB available.
=> [FLINK-28680] Revisit 'free_disk_space.sh' to free up more space

flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniCluster.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/ChangelogTaskLocalStateStore.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/TaskExecutorLocalStateStoresManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/TaskLocalStateStoreImpl.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/ChangelogStateBackendLocalHandle.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/ChangelogTaskLocalStateStoreTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/TaskExecutorLocalStateStoresManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/TaskLocalStateStoreImplTest.java, flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackendTest.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/ChangelogLocalRecoveryITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/ChangelogPeriodicMaterializationTestBase.java
*Support local recovery for the materialized part of changelog.*
- *When doing snapshot, let `ChangelogKeyedStateBackend` return local materialized part from delegate backend.*
- *Modify `TaskLocalStateStoreImpl` to maintain the relationship between local checkpoints.*
- *Modify the logic of `confirmCheckpoint()` in `TaskLocalStateStoreImpl` to prevent the materialized part from being discarded.*
-  *Modify `MiniCluster` to support working-dir.*
- *Added `ChangelogLocalRecoveryITCase`.*
- *Extended `TaskLocalStateStoreImplTest` for …
=> [FLINK-27692][state] Support local recovery for materialized part of changelog

flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/source/AsyncTableFunctionProvider.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/source/LookupTableSource.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/source/TableFunctionProvider.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/source/lookup/AsyncLookupFunctionProvider.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/source/lookup/LookupFunctionProvider.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/AsyncLookupFunction.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/LookupFunction.java
This pull request introduces new interfaces in replace of the original TableFunction and its provider for lookup table, including:
- `LookupFunction`
- `AsyncLookupFunction`
- `LookupFunctionProvider`
- `AsyncLookupFunctionProvider`
Also mark `TableFunctionProvider` and `AsyncTableFunctionProvider` as deprecated.
- Add (Async)LookupFunction interface and provider interfaces
- Mark (Async)TableFunctionProvider as deprecated
This PR only creates new and marks deprecated interfaces, which does not require test cases. …
=> [FLINK-28416][table] Add (Async)LookupFunction and providers in replace of (Async)TableFunction as the API for lookup table

flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/itcases/HAQueryableStateFsBackendITCase.java, flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/itcases/HAQueryableStateRocksDBBackendITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/LeaderElectionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/leaderretrieval/ZooKeeperLeaderRetrievalTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/testutils/ZooKeeperTestUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/ZooKeeperUtilsTreeCacheTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/zookeeper/ZooKeeperExtension.java, flink-runtime/src/test/java/org/apache/flink/runtime/zookeeper/ZooKeeperResource.java, flink-runtime/src/test/java/org/apache/flink/runtime/zookeeper/ZooKeeperTestEnvironment.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/EventTimeWindowCheckpointingITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/ResumeCheckpointManuallyITCase.java, flink-tests/src/test/java/org/apache/flink/test/runtime/leaderelection/ZooKeeperLeaderElectionITCase.java, flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNHighAvailabilityITCase.java
Resolves a class of test instabilities where ZK is unavailable for longer than the default session timeout (which seemingly gets reduced to 13-20 seconds) allows. Examples are GC pauses or writes to disk (which may be impaired by other tests running on the machine)
All usages of the curator `TestingServer` were migrated to a new utility factory method that increases the server-side max session timeout to 60 seconds.
=> [FLINK-28523][tests] Increase Zookeeper session timeouts

docs/content.zh/docs/connectors/datastream/formats/json.md, docs/content/docs/connectors/datastream/formats/json.md, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/deserializer/KafkaRecordDeserializationSchemaTest.java, flink-formats/flink-json/pom.xml, flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonDeserializationSchema.java, flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonNodeDeserializationSchema.java, flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonSerializationSchema.java, flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/JsonNodeDeserializationSchemaTest.java, flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/JsonSerDeSchemaTest.java, flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testutils/formats/DummyInitializationContext.java
Add a basic JSON (de)serialization scheme for reading/writing any jackson-supported type.
Also deprecates the `JsonNodeDeserializationSchema` because it's now kinda redundant.
=> [FLINK-28634][json] Add simple JsonSerDeSchema 

flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/StateChangeFsUploader.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/StateChangeFsUploaderTest.java
This pull request makes output stream of StateChangeFsUploader could be closed normally while enbaling compression.
- Always call close in StateChangeFsUploader#upload while enabling compression
- Added StateChangeFsUploaderTest#testCompress
- The serializers: no)
=> [FLINK-28602][state/changelog] Close stream of StateChangeFsUploader normally while enabling compression

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PartitionedFileReader.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionReadScheduler.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionReadSchedulerTest.java
Currently, the SortMergeResultPartitionReadScheduler always gets all active subpartition readers and read at most one data region for them. It is common that some subpartitions are requested before others and their region indexes are ahead of others. 
If all region data of a subpartition can be read in one round, some subpartition readers will always be ahead of others which will cause random IO. 
This patch fixes this case by polling one subpartition reader at a time.
- *Fix the bug that SortMergeResultPartitionReadScheduler may not read data sequentially.*
This change is already covered by existing tests, such as *SortMergeResultPartitionReadSchedulerTest*. …
=> [FLINK-28519][network] Fix the bug that SortMergeResultPartitionReadScheduler may not read data sequentially

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParser.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java, flink-connectors/flink-connector-hive/src/test/resources/explain/testMultiInsert.out
To support multi-insert statement for Hive dialect.
- Construct `ModifyOperation` separately for each insert fragment in one single multi-insert statement.
- Compose these `ModifyOperation`s  to `StatementSetOperation`.
The addition test in [...connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java](https://github.com/apache/flink/compare/master...luoyuxia:FLINK-27387?expand=1#diff-fb5fc4106e27e27f9968e59b643003444fd40af58aa2f147ac301009b53a47ca)#testMultiInsert …
=> [FLINK-27387][hive] Hive dialect supports multi-insert statement

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserCalcitePlanner.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserDMLHelper.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserScriptTransformHelper.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserUtils.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserBaseSemanticAnalyzer.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserDDLSemanticAnalyzer.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/runtime/operators/hive/script/CircularBuffer.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/runtime/operators/hive/script/HiveScriptTransformOperator.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/runtime/operators/hive/script/HiveScriptTransformOutReadThread.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/runtime/operators/hive/script/RedirectStreamThread.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/runtime/operators/hive/script/ScriptProcessBuilder.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java, flink-connectors/flink-connector-hive/src/test/resources/explain/testScriptTransform.out, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/RelTimeIndicatorConverter.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecScriptTransform.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/hive/LogicalScriptTransform.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/logical/FlinkLogicalScriptTransform.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/batch/BatchPhysicalScriptTransformationExec.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/FlinkBatchRuleSets.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/physical/batch/BatchPhysicalScriptTransformRule.scala, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/script/ScriptTransformIOInfo.java
To make Hive dialect support `transform using 'xx'`, see more detail about it in [LanguageManual+Transform](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Transform)
-  Translate `select transform` to [LogicalScriptTransform.java](https://github.com/apache/flink/pull/19818/files#diff-8ae0f92844c7a81333149d173c0d6310dfaae68c59965aff954147fe607840e5)
- Add rule [FlinkLogicalScriptTransformBatchConverter](https://github.com/apache/flink/pull/19818/files#diff-e8b366f45f734a938207ecf2731137427648e4670ed2e960d707572768cb7f93R58) to translate `LogicalScriptTransform` to [FlinkLogicalScriptTransform](https://github.com/apache/flink/pull/19818/files#diff-e8b366f45f734a938207ecf2731137427648e4670ed2e960d707572768cb7f93R32),  rule …
=> [FLINK-26410][hive] Hive dialect supports "transform using 'script'"

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveInternalOptions.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/operations/HiveSetOperation.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveDialectFactory.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveOperationExecutor.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParser.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveSetProcessor.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectITCase.java
To make Hive dialect support set variables.
- When it's for set command, extract the key and value, and then set the value according what kind of variable it belongs.
UT
=> [FLINK-28096][hive] Hive dialect support set variables

docs/content.zh/docs/dev/table/sql/queries/select-distinct.md
- Translate "SELECT DISTINCT" page into Chinese: https://nightlies.apache.org/flink/flink-docs-master/zh/docs/dev/table/sql/queries/select-distinct/.
- The markdown file's location: flink/docs/content.zh/docs/dev/table/sql/queries/select-distinct.md, most of them have been translated, but some part has not been translated into Chinese. See FLINK-28748 for information.
Translate "SELECT DISTINCT" page into Chinese …
=> [FLINK-28748][docs-zh] Translate "SELECT DISTINCT" page into Chinese.

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserCalcitePlanner.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserRowResolver.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java, flink-connectors/flink-connector-hive/src/test/resources/query-test/join.q, flink-connectors/flink-connector-hive/src/test/resources/query-test/set_op.q
To fix the issue that it'll throw "schema of both sides of union should match" exception when one side of union select multiple same coulmns  in `UNION ALL` statement with Hive dialect.
- use method `HiveParserRowResolver#putWithCheck` to put ColumnInfo, it will try to use internal name to duplicate again after finding a duplicate.
- add check for ambiguous columns .
The added SQL statement `select x,y from foo union all select i,i from bar;`  which will fail before this fix in set_op.q …
=> [FLINK-26542][hive] Hive dialect supports queries with multiple same columns in select

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/CompositeBuffer.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/ReadOnlySlicedNetworkBuffer.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/NettyMessage.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PartitionedFileReader.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeSubpartitionReader.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/LocalInputChannel.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/ReadOnlySlicedBufferTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionReadSchedulerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/SortMergeSubpartitionReaderTest.java
Currently, for sort blocking shuffle, the corresponding data readers read shuffle data in buffer granularity. Before compression, each buffer is 32K by default, after compression the size will become smaller (may less than 10K). For file IO, this is pretty smaller. 
To achieve better performance and reduce IOPS, we can read more data per IO read request and parse buffer header and data in memory.
- *Read a full buffer of data per file IO read request for sort-shuffle*
This change is already covered by existing tests, such as *SortMergeResultPartitionTest*. …
=> [FLINK-28373][network] Read a full buffer of data per file IO read request for sort-shuffle

flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/metrics/groups/CacheMetricGroup.java, flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/metrics/groups/UnregisteredMetricsGroup.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricNames.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/InternalCacheMetricGroup.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/source/lookup/LookupOptions.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/source/lookup/cache/DefaultLookupCache.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/source/lookup/cache/LookupCache.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/connector/source/lookup/cache/DefaultLookupCacheTest.java
This pull request introduces interfaces for LookupCache and CacheMetricGroup, also a default implementation of LookupCache.
- Add new interfaces `LookupCache` and `CacheMetricGroup`
- Add default implementation for `LookupCache` as `DefaultLookupCache`
- Add an internal implementation for `CacheMetricGroup` as `InternalCacheMetricGroup`
This change added unit tests for the newly added `DefaultLookupCache` and `InternalCacheMetricGroup` …
=> [FLINK-28417][table] Add interfaces for LookupCache and default implementation

flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/source/lookup/PartialCachingAsyncLookupProvider.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/source/lookup/PartialCachingLookupProvider.java
This pull request introduces 2 new interfaces, `PartialCachingLookupProvider` and `PartialCachingAsyncLookupProvider` for supporting partial caching lookup table.
- Add runtime provider interfaces for partial caching lookup
This change only introduces two new interfaces so no tests are required. …
=> [FLINK-28418][table] Add runtime provider interfaces for partial caching lookup

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserCalcitePlanner.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserProjectWindowTrimmer.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java
To fix the `IndexOutOfBoundsException` for window expression  while using Hive dialect
- Introduce [HiveParserProjectWindowTrimmer.java](https://github.com/apache/flink/pull/20060/files#diff-09ef2ea6987c9f1680d63436dcb84ffa32dab53724f2e31f2c4ec07525b1a475), and in parse phase, when there exists windowing expression, use it to trim the project node to only keep needed field.
Added test in [...connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java](https://github.com/apache/flink/pull/20060/files#diff-fb5fc4106e27e27f9968e59b643003444fd40af58aa2f147ac301009b53a47ca)
- The serializers: (yes / …
=> [FLINK-28212][hive] Trim the project node with window expressions to fix IndexOutOfBoundsException when using Hive dialect.

flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SQLClientKafkaITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SmokeKafkaITCase.java
* Re-enable Kafka tests for Java 11
* Removed code that disables tests for Java 11
This change is already covered by existing tests. You will need to run this on JDK11 to verify that they can be run successfully.
=> [FLINK-25252][Connector/Kafka] Re-enabling Kafka tests for Java 11

flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/DeserializationSchemaAdapter.java, flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/SerializationSchemaAdapter.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaRecordSerializationSchemaBuilderTest.java
Resolve a few cases of undesired behavior when a schema attempts to access the metric group.
We shouldn't fail in that case but silently ignore it if we have to, as we do in other areas of Flink (because a lack of metrics should never fail a job).
=> [FLINK-28804][formats] Use proper stand-ins for missing metric groups

docs/content/docs/ops/state/savepoints.md, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/Checkpoints.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointMetadataLoadingTest.java
Please see ticket description (FLINK-28647).
- update the docs (checkpoint folder **is** deleted but with a delay)
- remove additional error handling (just fail in case of folder deletion failure)
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: yes
=> [FLINK-28647] Remove separate error handling and adjust documentation for CLAIM mode + RocksDB native savepoint

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserDMLHelper.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserRexNodeConverter.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java, flink-connectors/flink-connector-hive/src/test/resources/query-test/sub_query.q
To fix the issue that the IndexOutOfBoundsException will be thrown when do type conversion for sub-query in Hive dialect.
When do type conversion, if it's for subquery, add a project node  in the case that it's needed to do type conversion instead of finding project node in the parent recursively for we may well not find any project node.
Add sub_query.q that contains the sql statements that will throw exception before this fix.
- The S3 …
=> [FLINK-26362][hive] fix IndexOutOfBoundsException when sub-query selects all fields  when using Hive dialect

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/factories/HiveFunctionDefinitionFactory.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/functions/hive/HiveGenericUDAF.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/functions/hive/HiveGenericUDAFTest.java
To support these Hive UDAFs that implement  GenericUDAFResolver interface.
-  Add a branch to check if the function is only the instance of `GenericUDAFResolver` when create function definition. 
- If the function is instance of GenericUDAFResolver, call `GenericUDAFResolver#getEvaluator(TypeInfo[] parameters)` to create `GenericUDAFEvaluator`  in [HiveGenericUDAF.java](https://github.com/apache/flink/compare/master...luoyuxia:flink:FLINK-28296?expand=1#diff-fb0d46645c48e1c7b406addf9b31274625882afc69ad0cdf7700d2d67d699473)
Added test to test call the Hive's function that implements `GenericUDAFResolve`.
- If yes, how is the feature documented?  N/A
=> [FLINK-28296][hive] Support the Hive UDAF which implement GenericUDAFResolver interface

flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/CsvFileFormatFactory.java, flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/RowDataToCsvConverters.java, flink-python/pom.xml, flink-python/pyflink/datastream/formats/csv.py, flink-python/src/main/java/org/apache/flink/formats/csv/PythonCsvUtils.java
Since we shouldn't assume that jackson mappers are serializable (due to non-serializable extension) the RowDataToCsvFormatConverterContext also shouldn't be serializable.
With that in mind the CsvFileFormatFactory should create the context when the writer is created, not beforehand.
=> [FLINK-28808][csv] Create mapper on server-side

flink-end-to-end-tests/flink-end-to-end-tests-common-elasticsearch/pom.xml, flink-table/flink-sql-client/pom.xml, flink-test-utils-parent/flink-test-utils/pom.xml
Removes an unused dependency.
`end-to-end-tests-common-elasticsearch` now has a direct compile dependency on `junit-jupiter`, which previously got pulled in by `curator-test`.
`sql-client` no longer excludes `guava` from `hadoop-common`, because `guava` was previously pulled in by `curator-test` and is still required by the annoying `KerberosDelegationTokenManager` which automatically activates when `hadoop-common` is on the classpath.
Core benefit is one less dependency being pulled into user projects (which also pulls in log4j1).
=> [FLINK-28713][tests] Remove unused curator-test dependency

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/CodeGenUtils.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/GenerateUtils.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/HashCodeGenerator.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/AggregateUtil.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/codegen/HashCodeGeneratorTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CalcITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/AggregateITCaseBase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/AggregateITCase.scala, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/generated/HashFunction.java
Support complex shuffle hash key type
- *Support complex shuffle hash key type*
- *Added unit tests in HashCodeGeneratorTest*
=> [FLINK-25645][table-runtime] UnsupportedOperationException would thrown out when hash shuffle by a field with array type

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/HiveCatalog.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserDDLSemanticAnalyzer.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectITCase.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableSourceITCase.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ShowPartitionsOperation.java
To fix the partition filter push down issue when there exsits default partition in Hive soruce.
- *When the partition value is equal to `HiveConf.ConfVars.DEFAULTPARTITIONNAME`, convert it to null in method HiveCatalog#listPartitions*
- *To make `show partitions` also works for default partition in Hive , add a field `defaultPartitionName` in `ShowPartitionsOperation`. Then when the partition value is null, `ShowPartitionsOperation` should use the `defaultPartitionName`.
- Added [test](https://github.com/apache/flink/pull/19450/files#diff-e7e74972bb3dbbd76ce12f31dd2315433102943a1bf6ae15deac4f648cfc228aR222) for the issue of partition filter push down when there exists default partition.
- Added [test](https://github.com/apache/flink/pull/19450/files#diff-748a9fa63f15b3bd3ea5426a5b42179cade …
=> [FLINK-27217][hive] Fix partition filter push down issue when there exists default partition in Hive source

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParser.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectITCase.java, flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientITCase.java, flink-table/flink-sql-client/src/test/resources/sql/set.q
To make Hive dialect supports `ADD JAR`
-  Parse add jar command in HiveDialect and convert it to `AddJarOperation`
The test in `Hivedialect#testAddCommand`in to make sure the "ADD JAR" can be converted to AddJarOperation.  …
=> [FLINK-28772][hive] Hive dialect supports "ADD JAR"

flink-examples/flink-examples-table/src/main/java/org/apache/flink/table/examples/java/basics/TemporalJoinSQLExample.java, flink-examples/flink-examples-table/src/test/java/org/apache/flink/table/examples/java/basics/TemporalJoinSQLExampleITCase.java
This pull request adds a temporal join example and the corresponding ITCase to the flink-examples-table package. It shows to use how to use temporal join, how it works, and how to do IT tests.
- Add temporal join example and ITCase
- Added integration tests  …
=> [FLINK-28834][examples-table] Add temporal join example and IT test

flink-runtime/src/main/java/org/apache/flink/runtime/io/disk/BatchShuffleReadBufferPool.java
When recycling buffers in BatchShuffleReadBufferPool, the number of buffers may be larger than numBuffersPerRequest, which may cause too frequent notifications that the buffers are already available.
So we should modify the condition of notifications that the buffer is available to solve this problem.
- *Modify the condition of notifications that the buffer is available in BatchShuffleReadBufferPool*
This change is already covered by existing tests, such as *BatchShuffleReadBufferPoolTest*.
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes /  **no**)
- The serializers: (yes /  **no** / don't know)
- The runtime per-record code paths (performance sensitive): (yes /  **no** / don't know) …
=> [FLINK-28826][network] Avoid notifying too frequently when recycling buffers for BatchShuffleReadBufferPool

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionReadScheduler.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeSubpartitionReader.java
Currently, when reading data in SortMergeResultPartitionReadScheduler, the reader is added to the priority queue immediately. However, the data read from this reader may not have been consumed, which will cause this reader to be ranked later in the queue, which is unfavorable to sequential reading.
To solve the issue, After reading the data, we should sort all unfinished readers in batches at one time, that is, add all unfinished readers to the priority queue, which is more conducive to sequential reading.
- *Sorting all unfinished readers in batches at one time in SortMergeResultPartitionReadScheduler*
This change is already covered by existing tests, such as *SortMergeResultPartitionReadSchedulerTest*.
- The public …
=> [FLINK-28828][network] Sorting all unfinished readers in batches at one time in SortMergeResultPartitionReadScheduler

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartition.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionReadScheduler.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionReadSchedulerTest.java
The num of the max requested buffers in SortMergeResultPartitionReadScheduler is determined by the num of subpartitions, which may be insufficient in some scenarios, such as speculative execution and partition reuse.
Therefore, we should increase the max requested buffers to make full use of available memory when TM memory is sufficient.
- *Enlarge the max requested buffers for SortMergeResultPartitionReadScheduler*
This change is already covered by existing tests, such as *SortMergeResultPartitionReadSchedulerTest*.
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes /  **no**)
- The serializers: (yes /  **no** / don't know) …
=> [FLINK-28823][network] Enlarge the max requested buffers for SortMergeResultPartitionReadScheduler

flink-python/pyflink/common/types.py, flink-python/pyflink/datastream/connectors/tests/test_kafka.py, flink-python/pyflink/fn_execution/coder_impl_fast.pxd, flink-python/pyflink/fn_execution/coder_impl_fast.pyx, flink-python/pyflink/fn_execution/coder_impl_slow.py, flink-python/pyflink/fn_execution/coders.py, flink-python/pyflink/fn_execution/flink_fn_execution_pb2.py, flink-python/pyflink/proto/flink-fn-execution.proto, flink-python/pyflink/testing/test_case_utils.py, flink-python/src/main/java/org/apache/flink/streaming/api/utils/PythonTypeUtils.java
This PR completes DataType support when using DataStream API in PyFlink, e.g. using FileSource format originated from Table API, which produces `RowData` records, or using `to_data_stream(Table)`.
=> [FLINK-28827][python] Complete DataType support in DataStream API

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/ResultPartitionType.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/NonChainedOutput.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamConfig.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGenerator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/partitioner/CustomPartitionerWrapper.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/OperatorChain.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGeneratorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/partitioner/ForwardForConsecutiveHashPartitionerTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/partitioner/ForwardForUnspecifiedPartitionerTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamConfigChainer.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskMailboxTestHarnessBuilder.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTestHarness.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/util/MockStreamConfig.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/partitioner/BinaryHashPartitioner.java
Currently, if one output of an upstream job vertex is consumed by multiple downstream job vertices, the upstream vertex will produce multiple dataset. For blocking shuffle, it means serialize and persist the same data multiple times. This ticket aims to optimize this behavior and make the upstream job vertex produce one dataset which will be read by multiple downstream vertex.
- Produce one intermediate dataset for multiple consumer job vertices consuming the same data.
- The runtime per-record code paths (performance sensitive): (yes / **no** / don't …
=> [FLINK-28380][runtime] Produce one intermediate dataset for multiple consumer job vertices consuming the same data

flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/ChangelogStateBackendHandle.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/ChangelogPeriodicMaterializationSwitchStateBackendITCase.java
During restore from changelog state backend , the native checkpoint could contain the relative file state handles (which size is greater than `state.storage.fs.memory-threshold`), file path in these file state handles would be resolve as relative which leads to FileNotFoundException.
File path in IncrementalKeyedStateHandle should be cast to absolute path during restore, so that the correct file path will be read.
cast file path to absolute path in IncrementalRemoteKeyedStateHandle during restore in changelog state backend.
This change is already covered by existing tests, such as *org.apache.flink.test.checkpointing.ChangelogPeriodicMaterializationSwitchStateBackendITCase*.  (`state.storage.fs.memory-threshold` is reduced)
- Dependencies (does it add or upgrade a dependency): (yes / …
=> [FLINK-28843][StateBackend] Fix restore from incremental checkpoint with changelog checkpoint in claim mode

flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/dialect/JdbcDialect.java, flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/dialect/mysql/MySqlDialect.java, flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/options/JdbcConnectorOptions.java, flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/dialect/mysql/MySqlDialectTest.java
When we directly use buffer-flush options of the mysql sink (sink.buffer-flush.max-rows and sink.buffer-flush.interval) can not increase throughput.
We must set 'rewriteBatchedStatements=true' into mysql jdbc url, for 'sink.buffer-flush' to take effect.
Such as: 'jdbc:mysql://ip:3306/dbname?rewriteBatchedStatements=true'
- *Added a method appendUrlSuffix in MySQLDialect to append 'rewriteBatchedStatements=true'.*
- *Added appendUrlSuffix default method in JdbcDialect interface to do nothing.*
- *use appendUrlSuffix in JdbcConnectionOptions#Builder#build() method*
*(example:)*
- *Added a test case in MySqlDialect to test appendUrlSuffix*
- The …
=> [FLINK-25485][connector/jdbc] Append default JDBC URL option of batch writing in MySQL.

flink-connectors/flink-connector-hbase-2.2/pom.xml
Successful Java 11 build: https://dev.azure.com/chesnay/flink/_build/results?buildId=2899&view=results
=> [FLINK-25244][hbase] Enable Java 11 tests for HBase 2.2

docs/layouts/shortcodes/generated/all_jobmanager_section.html, docs/layouts/shortcodes/generated/expert_scheduling_section.html, docs/layouts/shortcodes/generated/job_manager_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/JobManagerOptions.java, flink-core/src/test/java/org/apache/flink/api/common/ExecutionConfigTest.java, flink-end-to-end-tests/test-scripts/test_tpcds.sh, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/DefaultSlotPoolServiceSchedulerFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultSchedulerFactory.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/DefaultSlotPoolServiceSchedulerFactoryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterSchedulerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/TestingSchedulerNGFactory.java
Make jobmanager.scheduler visible in documentation
This is a documentation change without any test coverage.
=> [FLINK-28873][configuration] Make jobmanager.scheduler visible in documentation

flink-core/src/main/java/org/apache/flink/configuration/GlobalConfiguration.java
This is mostly to ease discovery; while the dynamic properties are logged as part of the program args my impression is that this isn't the place that users would look at.
=> [FLINK-28731][conf] Log dynamic properties

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecLookupJoin.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/KeySelectorUtil.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/LookupJoinUtil.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/ProjectionCodeGenerator.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/common/CommonPhysicalLookupJoin.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestValuesTableFactory.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/join/LookupJoinITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/LookupJoinITCase.scala, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/CachingLookupFunction.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/fullcache/CacheLoader.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/fullcache/LookupFullCache.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/fullcache/ReloadTriggerContext.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/fullcache/inputformat/InputFormatCacheLoader.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/fullcache/inputformat/InputSplitCacheLoadTask.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/keyselector/GenericRowDataKeySelector.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/functions/table/fullcache/FullCacheTestInputFormat.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/functions/table/fullcache/TestManualCacheReloadTrigger.java
This pull request introduces support of lookup join using FullCachingLookupProvider that uses InputFormats for data loading.
- Add `LookupFullCache` as an implementation of interface `LookupCache`, therefore full caching logic is located in the same place as partial caching logic (CachingLookupFunction)
- There are 2 copies of full caches (old and new) at the process of reloading, so no blocking is required, but on the other hand, it requires twice more memory.
- Reloading happens in another thread. If exception will be thrown from this thread, main thread will also stop.
- If there are more than one InputSplit from InputFormat, reloading will be performed in parallel. Total number of threads for reloading = min(numOfSplit, numOfCores).
This change added tests and can be verified as …
=> [FLINK-28532][table] Support full caching in lookup join runner using InputFormats as scan runtime provider

flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/RecreateOnResetOperatorCoordinatorTest.java
This PR fixes the compilation failure thrown in RecreateOnResetOperatorCoordinatorTest.
=> [FLINK-28900] Fix RecreateOnResetOperatorCoordinatorTest compilation failure

docs/content.zh/docs/dev/datastream/fault-tolerance/broadcast_state.md, docs/content/docs/dev/datastream/fault-tolerance/broadcast_state.md
This PR adds missing broadcast state doc for PyFlink.
=> [FLINK-27588][python][docs] Update broadcast state related docs

flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/KubernetesUtils.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/KubernetesPodTemplateTestUtils.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/utils/KubernetesUtilsTest.java, flink-kubernetes/src/test/resources/testing-nospec-pod-template.yaml
This pull request fix the NPE error of TM pod template file without spec field.
Add validation for TM pod template file spec field.
- Added test that validates TM pod template without spec field: `KubernetesUtilsTest.testLoadPodFromNoSpecTemplate` …
=> [FLINK-27856][flink-kubernetes]solve the NPE error of no spec field in taskmanager pod template.

flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/KubernetesUtils.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/KubernetesPodTemplateTestUtils.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/utils/KubernetesUtilsTest.java, flink-kubernetes/src/test/resources/testing-nospec-pod-template.yaml
This pull request fix the NPE error of pod template file without spec field.
Add validation for pod template file spec field.
- Added test that validates pod template without spec field: `KubernetesUtilsTest.testLoadPodFromNoSpecTemplate` …
=> [BP-1.15]FLINK-27856][k8s] Fix the NPE when no spec is configured in pod template

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartition.java
After adding the logic of recycling buffers in CompositeBuffer in https://issues.apache.org/jira/browse/FLINK-28373, when reading data and recycling buffers simultaneously, the deadlock between the lock of SortMergeResultPartition and the lock of SingleInputGate may occur.
In short, the deadlock may occur as follows.
1. SingleInputGate.getNextBufferOrEvent (SingleInputGate lock)
CompositeBuffer.getFullBufferData -> CompositeBuffer.recycleBuffer -> waiting for 
SortMergeResultPartition lock;
2. ResultPartitionManager.releasePartition (SortMergeResultPartition lock) -> 
SortMergeSubpartitionReader.notifyDataAvailable -> 
SingleInputGate.notifyChannelNonEmpty -> waiting for SingleInputGate lock.
This change is to fix the deadlock bug.
- *Fix the deadlock bug when recycling readers for …
=> [FLINK-28942][network] Fix the deadlock bug when recycling readers for SortMergeResultPartition

flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/context/SessionContext.java
The PR makes use of `Builder#withConfiguration(Configuration)` instead of deprecated `org.apache.flink.table.api.EnvironmentSettings#fromConfiguration`
`flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/context/SessionContext.java`
- …
=> [FLINK-28932][Table/SQL] Use Builder#withConfiguration instead of deprecated EnvironmentSettings#fromConfiguration

flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumerator.java, flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/SwitchedSources.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumeratorTest.java
This pull request fix NullPointerException in HybridSource when restoring from checkpoint.
After the recovery action is triggered, only the source with sourceIndex = 1 is loaded in the switchedSources in the HybridSourceSplitEnumerator
For the new SourceReaderFinishedEvent that triggers the load of a new source, the default is to get the source with sourceIndex = 0, which triggers the NPE.
Please correct me if there is a mistake.
For the new SourceReaderFinishedEvent, get an available source.
- Added testRestoreEnumeratorWith2ndSource in HybridSourceSplitEnumeratorTest …
=> [FLINK-28817] NullPointerException in HybridSource when restoring from checkpoint

flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumerator.java, flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/hybrid/SwitchedSources.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumeratorTest.java
This is a backport of #20530
For the new SourceReaderFinishedEvent, get an available source.
- Added testRestoreEnumeratorWith2ndSource in HybridSourceSplitEnumeratorTest
=> [FLINK-28817][connector/common] NullPointerException in HybridSource when restoring from checkpoint

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveTableSink.java, flink-connectors/flink-connector-hive/src/test/resources/explain/testHiveTableSinkWithParallelismInBatch.out
*Set parallelism for map operator in class HiveTableSink's method createBatchSink in order to keep consistent with HiveTableSink. If not so, the operators in sink can not be chained togather.*
- *Set parallelism for map operator in class HiveTableSink's method createBatchSink* …
=> [FLINK-28208][Connectors/Hive] Set parallelism for map operator in class HiveTableSink's method createBatchSink

flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/codegen/UsingRemoteJarITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/resources/create_function_using_remote_jar_e2e.sql
Add e2e test for create function using jar syntax that using remote hdfs jar
- *Add e2e test for create function using jar syntax that using remote hdfs jar*
- *Added e2e tests in UsingRemoteJarITCase*
=> [FLINK-28916][e2e] Add e2e test for create function using jar syntax

flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliClient.java, flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientTest.java, flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/utils/SqlParserHelper.java
*When starting job using hive sql file in SQL client, the sql may be modified by SqlCompleter, for example, 'pos' field is changed to 'POSITION'. So it is better to disable SqlCompleter when using -f {file} in SQL client.*
- *Disable SqlCompleter when using sql file.*
- *Add test testExecuteSqlFileWithoutSqlCompleter and testExecuteSqlInteractiveWithSqlCompleter in class CliClientTest* …
=> [FLINK-28003][Table SQL / Client] Disable SqlCompleter when using -f {file}

flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/PartitionTempFileManager.java, flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/table/FileSystemCommitterTest.java
*The commit partition base path is not created when no data is sent which may cause FileNotFoundException. Just fix it.*
- *Check whether the base path exists before listStatus for the path.*
- *Added test testPartitionPathNotExist in FileSystemCommitterTest*
=> [FLINK-28548][Connectors / FileSystem] Fix the exception FileNotFoundException when the commit partition base path is not created

flink-yarn-tests/pom.xml
This should've always been a direct dependency. We previously relied on Hadoop pulling it in, but this isn't the case in Hadoop 3.x
=> [FLINK-28955][yarn] Add direct curator-test dependency

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserCalcitePlanner.java, flink-connectors/flink-connector-hive/src/test/resources/query-test/join.q
The pr is try to fix the `IndexOutOfBoundsException` that when there's only `1 = 1` in semi join cluster like the sql: `select * from a left semi join b on 1 = 1`.
Also, with this fix, we are also enabled to support non equality condition for left semi join which is supported in Hive [HIVE-17766](https://issues.apache.org/jira/browse/HIVE-17766).
-  Replace the method `RelOptUtil.splitJoinCondition` with `HiveRelOptUtil.splitHiveJoinCondition` for there're some bugs in `RelOptUtil.splitJoinCondition`
-  Not to throw exception when there're some non-equality conditions for semi join.
-  Constuct join condition with equality conditions and non-equality conditions. 
Added two sql statements involved with semijoin which are to fail before this fix in  join.q.
`select count(1) from (select x …
=> [FLINK-26505][hive] Fix IndexOutOfBoundsException for non equality condition exists in left semi join in Hive dialect

flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarPartitionSplitReaderTestBase.java
Pulsar's client provides a `Consumer.seek()` method for setting the start position. This method would cause the race condition sometimes, which may lead to duplicated messages in consuming results. This is unacceptable and we have to use Pulsar admin API instead.
* Drop `Consumer.seek()` in `PulsarPartitionSplitReaderTestBase`
- Does …
=> [FLINK-27917][Connector/Pulsar] Fix message assert error in PulsarUnorderedPartitionSplitReaderTest

docs/content.zh/docs/dev/table/sql/queries/orderby.md
- Translate "ORDER BY clause" page into Chinese:  https://nightlies.apache.org/flink/flink-docs-master/zh/docs/dev/table/sql/queries/orderby/.
- The markdown file is located in "docs/content.zh/docs/dev/table/sql/queries/orderby.md". 
- Details See [FLINK-28922](https://issues.apache.org/jira/browse/FLINK-28922) for information.
-  Translate "ORDER BY clause" page into Chinese. …
=> [FLINK-28922][docs-zh] Translate "ORDER BY clause" page into Chinese.

docs/content.zh/docs/dev/table/sql/queries/limit.md
- Translate "LIMIT clause" page into Chinese: https://nightlies.apache.org/flink/flink-docs-master/zh/docs/dev/table/sql/queries/limit/.
- The markdown file is located in "docs/content.zh/docs/dev/table/sql/queries/limit.md".
- Details See [FLINK-28924](https://issues.apache.org/jira/browse/FLINK-28924) for information.
- Translate "LIMIT clause" page into Chinese. …
=> [FLINK-28924][docs-zh] Translate "LIMIT clause" page into Chinese.

flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internals/metrics/KafkaMetricWrapper.java, flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/internals/metrics/KafkaMetricMutableWrapperTest.java
Backport of https://github.com/apache/flink/pull/19649 for the deprecated producer/consumer.
=> [FLINK-28488][kafka] Only forward measurable Kafka metrics and ignore others

docs/content.zh/docs/deployment/metric_reporters.md, docs/content/docs/deployment/metric_reporters.md, flink-metrics/flink-metrics-datadog/src/main/java/org/apache/flink/metrics/datadog/DatadogHttpReporter.java, flink-metrics/flink-metrics-datadog/src/main/java/org/apache/flink/metrics/datadog/DatadogHttpReporterFactory.java
Adds a switch to the datadog reporter to use a logical identifier, so that variables aren't reported in a redundant fashion both as tags and as part of the metric identifier.
Before:
`job.MyJobName.task.MyTask.metric:[job_name=MyJobName;task_name=MyTask]`
After:
`job.task.metric:[job_name=MyJobName;task_name=MyTask]`
This was manually verified since we can't test the actual datadog integration offline.
=> [FLINK-28997][datadog] Add switch to use logical identifier 

flink-end-to-end-tests/flink-end-to-end-tests-sql/pom.xml
Fix UsingRemoteJarITCase failed in hadoop3, test passed in local machine.
This change aim to address the ClassNotFoundException of `HdfsConfiguration` when run test with hadoop3, the reason is that hadoop-hdfs module doesn't include transitive dependency of hadoop-hdfs-client, hadoop-hdfs-client is not in classpath, so we need to introduce this dependency explicitly in maven.
This change is already covered by existing tests in `UsingRemoteJarITCase`.
=> [FLINK-29007][e2e] Fix UsingRemoteJarITCase failed with NPE in hadoop3

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/LongHashJoinGenerator.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/batch/sql/join/AdaptiveHashJoinITCase.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/hashtable/BaseHybridHashTable.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/hashtable/BinaryHashBucketArea.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/hashtable/BinaryHashPartition.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/HashJoinOperator.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/SortMergeJoinFunction.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/SortMergeJoinOperator.java
Add sql test for adaptive hash join and fix bug of memory segment insufficient when fallback to sort merge join.
- Add sql test for adaptive hash join
- *fix bug of memory segment insufficient when fallback to sort merge join*
- *Added ITCase in  AdaptiveHashJoinITCase*
- The serializers: (now)
- If yes, how …
=> [FLINK-28917][table-runtime] Add sql test for adaptive hash join

docs/content.zh/docs/connectors/datastream/cassandra.md, docs/content.zh/docs/connectors/datastream/formats/parquet.md, docs/content.zh/docs/dev/datastream/sources.md, docs/content.zh/docs/dev/table/sourcesSinks.md, docs/content.zh/docs/ops/state/state_backends.md, docs/content/docs/connectors/datastream/cassandra.md, docs/content/docs/connectors/datastream/formats/parquet.md, docs/content/docs/dev/datastream/sources.md, docs/content/docs/dev/table/sourcesSinks.md, docs/content/docs/ops/state/state_backends.md
Update the markdown links in the documentation to use the `gh_link` shortcode so that they point to the correct github branch for each release.
Excuse the ham-fisted regular expressions:
```
find docs/content docs/content.zh/ -path ./.git -prune -o -type f -print0 | xargs -0 perl -pi -e $'s#\[([^\]]+)\]\(https://github.com/apache/flink/blob/master/([^\)]+)\)#{{< gh_link file="$2" name="$1" >}}#g' &&
find docs/content docs/content.zh/ -path ./.git -prune -o -type f -print0 | xargs -0 perl -pi -e $'s#<a href="https://github.com/apache/flink/blob/master/([^"]+)">(.+?)</a>#{{< gh_link file="$1" name="$2" >}}#g' &&
find docs/content docs/content.zh/ -path ./.git -prune -o -type f -print0 | xargs -0 perl -pi -e "s#<a href='https://github.com/apache/flink/blob/master/([^']+)'>(.+?)</a>"$'#{{< …
```
=> [FLINK-29017][docs] Replace all links to github master with shortcode

flink-docs/pom.xml, flink-runtime/pom.xml
This is a trivial PR making using of `${flink.shaded.version}` in flink-docs and flink-runtime pom files instead of version.
_flink-docs/pom.xml_
_flink-runtime/pom/xml_
=> [hotfix][build] Use ${flink.shaded.version} for flink-docs and flink-runtime

flink-streaming-java/pom.xml, pom.xml
Remove temporary scala suffix settings for 1.15 in japicmp.
Remove temporary scala suffix settings for 1.15 in japicmp.
- The …
=> [Hotfix][Build] Remove scala suffix in japicmp

flink-quickstart/flink-quickstart-java/src/main/resources/archetype-resources/pom.xml, flink-quickstart/flink-quickstart-scala/src/main/resources/archetype-resources/pom.xml
This is a trivial PR to ~~move~~ not create dependecy-reduced poms ~~to target folder~~ to avoid it's appearance in `git diff `
quickstart pom files
=> [FLINK-29051[Quickstarts] Do not create dependency-reduced-pom for quick start

docs/content.zh/docs/dev/datastream/fault-tolerance/serialization/types_serialization.md, docs/content/docs/dev/datastream/fault-tolerance/serialization/types_serialization.md, flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/types/PojoTestUtils.java, flink-test-utils-parent/flink-test-utils/src/test/java/org/apache/flink/types/PojoTestUtilsTest.java
Kryo usages can sneak into the pojo serializer, and we should offer a convenient tool to guard against that.
=> [FLINK-29041][tests] Add utility to test POJO compliance without any Kryo usage

docs/content.zh/docs/dev/datastream/fault-tolerance/serialization/schema_evolution.md, docs/content/docs/dev/datastream/fault-tolerance/serialization/schema_evolution.md, flink-core/src/main/java/org/apache/flink/api/java/typeutils/TypeExtractor.java
The type extractors will now _always_ log a message if a tuple/pojo contains a generic type. Additionally we now also give a hint that schema evolution may be affected, and finally clarify the schema evolution docs about Kryo blocking it for types contained in serialized data structures.
=> [FLINK-29030][core] Improve messaging around Kryo & schema evolution

flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStore.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStoreTest.java
If something is temporarily wrong with the JobManager network, `Fabric8FlinkKubeClient#checkAndUpdateConfigMap` failed with `KubernetesException` in the first run and retried again. However, the http request is actually sent successfully and handled by the K8s APIServer, which means the entry was added to the ConfigMap. This will cause the second retry fails with `AlreadyExistException` and then discard the state. If the JobManager crashed exactly, it will throw the `FileNotFoundException: No such file or directory: s3://xxx/flink-ha/xxx/completedCheckpoint72e30229420c` in the following attempts since added entry is not cleaned up.
By make the `AlreadyExistException` in `KubernetesStateHandleStore#addAndLock` caused by `PossibleInconsistentStateException` we could avoid discarding the …
=> [FLINK-28265][k8s] Do not discard state when the AlreadyExistException is caused by retries

flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java, flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogStateBackend.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackendTest.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogMetricGroupTest.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogStateBackendTestUtils.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogStateDiscardTest.java, flink-state-backends/flink-statebackend-common/pom.xml, flink-state-backends/flink-statebackend-common/src/main/java/org/apache/flink/state/common/ChangelogMaterializationMetricGroup.java, flink-state-backends/flink-statebackend-common/src/main/java/org/apache/flink/state/common/PeriodicMaterializationManager.java, flink-state-backends/flink-statebackend-common/src/test/java/org/apache/flink/state/common/PeriodicMaterializationManagerTest.java, flink-state-backends/pom.xml, flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/streaming/util/TestStreamEnvironment.java, flink-tests/src/test/java/org/apache/flink/test/state/ChangelogRecoveryCachingITCase.java
Spread changelog materialization and consequently deletion, more evenly in time.
To ease the creation of `PeriodicMaterializationManager` in test, this PR includes c7865f9663ffec5ca668a7781e2dc274ff7a35c9 from #19312.
- added `PeriodicMaterializationManagerTest.testInitialDelay`
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: yes
=> [FLINK-28976][state/changelog] Don't add extra delay to the 1st materialization

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/functions/hive/HiveGenericUDAF.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/functions/hive/HiveGenericUDTF.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/functions/hive/HiveScalarFunction.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/functions/hive/util/HiveFunctionUtil.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/functions/hive/HiveGenericUDAFTest.java, flink-connectors/flink-connector-hive/src/test/resources/query-test/udaf.q
To fix fail to call Hive UDAF when the UDAF accepts one parameter with array type
When  the parameter is a single array, wrap it to an array.
Added test method `testUDAFCollectList`  in  [HiveGenericUDAFTest.java](https://github.com/apache/flink/compare/master...luoyuxia:fix-call-hive-collect-list-issue?expand=1#diff-347c8a1c08423da764ef8547e503d5772bf26cbdc72e281ed2cf7959085104be) …
=> [FLINK-27175][hive] Fix fail to call Hive UDAF when the UDAF accepts one parameter with array type

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/ExpressionReducer.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/batch/sql/FunctionITCase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/FunctionITCase.java
Fix bug of ExpressionReducer does not work with jar resources
- *Fix bug of ExpressionReducer does not work with jar resources*
- *Added integration tests in FunctionITCase*
=> [FLINK-29035][table-planner] Fix bug of ExpressionReducer does not work with jar resources

docs/content.zh/docs/connectors/table/hive/hive_read_write.md, docs/content/docs/connectors/table/hive/hive_read_write.md, flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/PartitionLoader.java, flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/TableMetaStoreFactory.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveOptions.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveTableMetaStoreFactory.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveTableSink.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/HiveCatalog.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/util/HiveStatsUtil.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableSinkITCase.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableSourceStatisticsReportTest.java
To fix the issue that HiveTableSInk fails to report [statistic](https://cwiki.apache.org/confluence/display/hive/statsdev) to Hive metastore.
-  When commit non-partition table/partition, try to collect statistic from files in non-partition table/partition, and then put these statistic to metastore.
- When collect statistic from files, try to get `RecordReader` according to table's input format. If the `RecordReader` is intance of `StatsProvidingRecordReader`, which means it's orc or parquet format,  we collect the statistic `numRows`, `fileSize`, `numFiles`, `rawDataSize`.  If not, we only collect `fileSize` and `numFiles` since other statistic is hard to collect efficiently.
- While commit partition, put these statistic collected to partition properties.
Added UT.
- Dependencies (does …
=> [FLINK-28883][hive] Fix HiveTableSink failed to report statistic to hive metastore in batch mode

flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java
This PR is meant to add the tm id in the exception message to make it clear in the exception history.
=> [hotfix] Add TaskManager id in the exception message

flink-rpc/flink-rpc-core/src/main/java/org/apache/flink/runtime/rpc/RpcEndpoint.java, flink-runtime/src/test/java/org/apache/flink/runtime/rpc/RpcEndpointTest.java
The test could fail if the FutureTask was running during the cancellation trigger&assertion. Use a manual executor service instead to prevent this from happening.
=> [FLINK-27030][tests] Prevent race-condition 

flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/schema/PulsarSchema.java, flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/common/schema/PulsarSchemaTest.java
PulsarSchema uses readObject and writeObject for customized serialization. But the ObjectInputStream only accepts the first 1018 bytes. We had to remove the custom logic and didn't override the default mechanism.
1. Add a test for reproducing the bug (Big schema serialization issue)
2. Change the serialization logic in `PulsarSchema`
- `PulsarSchemaTest.largeAvroSchemaSerialization` …
=> [FLINK-28609][Connector/Pulsar] PulsarSchema didn't get properly serialized

flink-connectors/flink-connector-jdbc/pom.xml
This a simple update of postgres jdbc driver to cope with CVE-2022-31197
https://github.com/pgjdbc/pgjdbc/security/advisories/GHSA-r38f-c4h4-hqq2
pom file
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no )
=> [FLINK-28814][Connectors][JDBC] Update org.postgresql:postgresql to 42.4.1

docs/layouts/shortcodes/generated/kubernetes_config_configuration.html, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/configuration/KubernetesConfigOptions.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/CmdJobManagerDecorator.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/CmdTaskManagerDecorator.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesJobManagerParameters.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesTaskManagerParameters.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/KubernetesJobManagerTestBase.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/KubernetesTaskManagerTestBase.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/CmdJobManagerDecoratorTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/CmdTaskManagerDecoratorTest.java
Provide the possibility to push dynamic arguments for the kubernetes Job/TaskManager.
Added a new configuration key for both Job/TaskManager which is used when creating them
Updated the unit tests which cover the relevant code
- If yes, how is the feature documented? Default config descriptions are present
=> [FLINK-29123][k8s] Dynamic paramters are not pushed to working with kubernetes

flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableSourceITCase.java, flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/reader/RowColumnReader.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/data/columnar/vector/heap/HeapRowVector.java
This patch fixes the bug that the parquet row type reader returns null value when some child fields is null.
Add a Unit Test of testReadParquetWithNullableComplexType() in HiveTableSourceITCase to verify this.
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / …
=> [FLINK-29005][Connectors/Parquet] Parquet row type reader should not return null value when some child fields is null

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserCalcitePlanner.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserRexNodeConverter.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserTypeCheckProcFactory.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java, flink-connectors/flink-connector-hive/src/test/resources/query-test/udf.q
The change is to enable  ExprNode  folding  and to fold UDFOPNegative.
It's mainly to fix the issue that it'll throw the exception `BROUND second argument only takes constant` when call some hive udf requiring constant parameter with implicit constant like `-1` or `cast(null as int) `.
-   enable ExprNode  fold
-  when the ExprNodeDesc is negative operator, try to fold it to ExprNodeConstantDesc
-  modify the logic for `convertConstant` in `HiveParserRexNodeConverter`  for the value for the data type of `IntervalYearMonth`/`IntervalDayTimeType` will be class of `HiveIntervalYearMonth`, `HiveIntervalDayTime`.
Added `udf.q` contains the sql statements that'll fail before this fix. …
=> [FLINK-26474][hive] Fold exprNode to fix the issue of failing to call some hive udf required constant parameters with implicit constant passed

docs/content.zh/docs/connectors/table/formats/parquet.md, docs/content/docs/connectors/table/formats/parquet.md
Updating parquet format document that support read complex type
Updating parquet format document that support read complex type
=> [FLINK-29019][doc][parquet] Updating parquet format document that support read complex type

docs/content.zh/docs/ops/state/large_state_tuning.md, docs/layouts/shortcodes/generated/checkpointing_configuration.html, docs/layouts/shortcodes/generated/common_state_backends_section.html, flink-core/src/main/java/org/apache/flink/configuration/CheckpointingOptions.java
Currently, the docs of configuration state.backend.local-recovery said wrongly on the active scope of this configuration. MemoryStateBackend and HashMapStateBackend actually support this feature.
Change the related docs to the correct descriptions. …
=> [FLINK-29130][state] Correct the description of state.backend.local-recovery

flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/pom.xml, flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/typeutils/AvroTypeExtractionTest.java, flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE, flink-formats/flink-sql-avro/src/main/resources/META-INF/NOTICE, pom.xml
* Update AVRO dependency to the latest version
(Continuing on the work of https://github.com/apache/flink/pull/17623)
- Updated org.apache.avro:avro:1.10.0 to org.apache.avro:avro:1.11.0
This change is already covered by existing tests, such as *flink-avro/*. …
=> [FLINK-24718][avro] update AVRO dependency to latest version

flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/AsyncSinkBaseITCase.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDynamicTableFactoryTest.java, flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/table/JdbcOutputFormatTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/runner/SessionDispatcherLeaderProcessTest.java
This a trivial PR replacing deprecated `AbstractThrowableAssert#getRootCause` with `AbstractThrowableAssert#rootCause`
=> [hotfix][Tests] Replace deprecated AbstractThrowableAssert#getRootCause with AbstractThrowableAssert#rootCause

flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/table/JdbcDynamicTableSourceITCase.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/ProjectSnapshotTransposeRule.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/FlinkBatchRuleSets.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/FlinkStreamRuleSets.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestValuesRuntimeFunctions.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestValuesTableFactory.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/rules/logical/ProjectSnapshotTransposeRuleTest.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/join/LookupJoinTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/LookupJoinJsonPlanTest_jsonplan/testJoinTemporalTableWithProjectionPushDown.out, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/ProjectSnapshotTransposeRuleTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/NonDeterministicDagTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/join/TemporalJoinTest.xml, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/functions/table/fullcache/FullCacheTestInputFormat.java
Projected pushdown is a basic optimization for table source , but actually not work for lookup source (which implments `SupportsProjectionPushDown`), this is unexpected, we should fix this.
Add a new rule `ProjectSnapshotTransposeRule` for both batch and stream rule sets
- newly added `ProjectSnapshotTransposeRuleTest` to cover both batch and streaming mode
- existing LookupJoinTest
- Does this …
=> [FLINK-29138][table-planner] fix project can not be pushed into lookup source

flink-formats/flink-csv/src/test/java/org/apache/flink/formats/csv/CsvFilesystemBatchITCase.java, flink-formats/flink-csv/src/test/java/org/apache/flink/formats/csv/CsvFilesystemStreamITCase.java, flink-formats/flink-csv/src/test/java/org/apache/flink/formats/csv/CsvFilesystemStreamSinkITCase.java
At https://github.com/apache/flink/pull/17598 `CsvFileSystemFormatFactory`  was renamed to `CsvFileFormatFactory` however in javadoc there is still invalid name. The PR fixes that
=> [hotfix][connectors][csv][javadoc] Rename invalid CsvFileSystemFormatFactory to CsvFileFormatFactory

flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperMultipleComponentLeaderElectionDriverTest.java
This is a 1.15 backport of PR #20709 (no conflicts detected during cherry-pick)
[CURATOR-645](https://issues.apache.org/jira/browse/CURATOR-645) covers a bug in the LeaderLatch implementation that causes a race condition if a child node, participating in the leader election, is removed too fast. This results in a different code branch being executed which triggers a reset of the LeaderLatch instead of re-collecting the children to determine the next leader.
The issue occurs because LeaderLatch#checkLeadership is not executed transactionally, i.e. retrieving the children and setting up the watcher for the predecessor is not done atomically. This leads to the race condition where a children (the previous leader's node) is removed before setting up the watcher which results in an invalid …
=> [BP-1.15][tests] Mitigate likelihood to run into test stability issues caused by CURATOR-645

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/runtime/operators/hive/script/HiveScriptTransformOperator.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/runtime/operators/hive/script/HiveScriptTransformOutReadThread.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java
To fix fail to use  BinaryRecordReader in "transform using" syntax with Hive dialect.
-  While reading the data with `BinaryRecordReader`, first to call `BinaryRecordReader#createRow` to get the reused WritableObject  just like what [Hive does](https://github.com/apache/hive/blob/a6ef9dc903f1e7c4ec53f925ab823f20f9331db8/ql/src/java/org/apache/hadoop/hive/ql/exec/ScriptOperator.java#L696).
Added sql in `HiveDialectQueryITCase#testScriptTransform`. …
=> [FLINK-29013][hive] Fix fail to use BinaryRecordReader in "transform using" syntax with Hive dialect

flink-libraries/flink-cep-scala/src/test/scala/org/apache/flink/cep/scala/CEPScalaAPICompletenessTest.scala, flink-libraries/flink-cep-scala/src/test/scala/org/apache/flink/cep/scala/pattern/PatternScalaAPICompletenessTest.scala, flink-libraries/flink-gelly-scala/src/test/scala/org/apache/flink/graph/scala/test/GellyScalaAPICompletenessTest.scala, flink-scala/src/test/scala/org/apache/flink/api/scala/completeness/BatchScalaAPICompletenessTest.scala, flink-scala/src/test/scala/org/apache/flink/api/scala/completeness/ScalaAPICompletenessTestBase.scala, flink-streaming-scala/src/test/scala/org/apache/flink/streaming/api/scala/StreamingScalaAPICompletenessTest.scala
Update the `ScalaAPICompletenessTestBase` class and its successors to AssertJ and JUnit 5 following the [JUnit 5 Migration Guide](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit)
Use JUnit5 and AssertJ in tests instead of JUnit4  …
=> [FLINK-28070][tests] Migrate ScalaAPICompletenessTestBase to Junit5

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/functions/hive/HiveGenericUDAF.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/module/hive/HiveModule.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserUtils.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/module/hive/HiveModuleTest.java
To fix fail to count mutiple fields excpetion in Hive dialect
-  Remove the `count` from the backlist of `HiveModule` , so that it'll use Hive's `count` function instead of Flink's `count` when `HiveModule` is loaded
- Do some adaption for Hive's `count` function
Added UT in [...connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java](https://github.com/apache/flink/pull/19406/files#diff-fb5fc4106e27e27f9968e59b643003444fd40af58aa2f147ac301009b53a47ca)#testCount …
=> [FLINK-27718][hive] Fix fail to count mutiple fields excpetion in Hive dialect

flink-connectors/flink-connector-cassandra/src/test/java/org/apache/flink/streaming/connectors/cassandra/CassandraConnectorITCase.java
`CassandraOutputFormat` is deprecated and in javadoc [1] it is mentioned that it's better to use `CassandraTupleOutputFormat`.
The PR replaces usages of `CassandraOutputFormat` with `CassandraTupleOutputFormat`
[1] https://github.com/apache/flink/blob/master/flink-connectors/flink-connector-cassandra/src/main/java/org/apache/flink/batch/connectors/cassandra/CassandraOutputFormat.java#L24-L27
_org.apache.flink.streaming.connectors.cassandra.CassandraConnectorITCase_ …
=> [hotfix][tests][cassandra-connectors] Use CassandraTupleOutputFormat instead of deprecated CassandraOutputFormat

flink-clients/src/main/java/org/apache/flink/client/FlinkPipelineTranslationUtil.java, flink-clients/src/main/java/org/apache/flink/client/StreamGraphTranslator.java, flink-clients/src/main/java/org/apache/flink/client/cli/CliFrontend.java, flink-clients/src/main/java/org/apache/flink/client/deployment/application/executors/EmbeddedExecutor.java, flink-clients/src/main/java/org/apache/flink/client/deployment/executors/AbstractJobClusterExecutor.java, flink-clients/src/main/java/org/apache/flink/client/deployment/executors/AbstractSessionClusterExecutor.java, flink-clients/src/main/java/org/apache/flink/client/deployment/executors/LocalExecutor.java, flink-clients/src/main/java/org/apache/flink/client/deployment/executors/PipelineExecutorUtils.java, flink-clients/src/test/java/org/apache/flink/client/cli/CliFrontendPackageProgramTest.java, flink-clients/src/test/java/org/apache/flink/client/program/ClientTest.java, flink-clients/src/test/java/org/apache/flink/client/program/DefaultPackagedProgramRetrieverTest.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/codegen/UsingRemoteJarITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/resources/scalar_udf_e2e.sql, flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/runtime/OperatorIDGeneratorTest.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraph.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGenerator.java, flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/test/util/MiniClusterPipelineExecutorServiceLoader.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/ChangelogRecoveryITCaseBase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/RescaleCheckpointManuallyITCase.java
When enabling checkpoint, if using scalar UDF, the UDF  class will be loaded during generating JobGraph. But the UDF class is in the user classloader, we can't load it from thread context classloader, so we should use the user classloader to compile JobGraph when needed.
Fix the bug of failing to generate Jobgraph when using scalar udf and enabling checkpoint
*(example:)*
- *Added e2e tests in UsingRemoteJarITCase* …
=> [FLINK-28897][runtime] Fix bug of failing to generate Jobgraph when using scalar udf and enable checkpoint

flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinatorHolder.java, flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/SubtaskGatewayImpl.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/CoordinatorEventsExactlyOnceITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinatorHolderTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/SubtaskGatewayImplTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/CoordinatorEventsToStreamOperatorRecipientExactlyOnceITCase.java
#20275 has improved the checkpoint behavior of `OperatorCoordinator`, guaranteeing the distributed consistency of operator events sent from the coordinator to its subtasks. However, while the previous implementation only requires that there is no concurrent "triggering phase" of checkpoints, the implementation in #20275 requires that before the previous checkpoint is fully completed or aborted, the next checkpoint should not be started. This has limited the usage of coordinators in cases when savepoints are triggered or the maximum allowed concurrent checkpoints is larger than 1.
This PR solves the problem above by adding concurrent checkpoint support in the coordinator's implementation.
- The subtask gateway can cache events for multiple ongoing checkpoints.
This change added tests and …
=> [FLINK-28941][Runtime/Checkpointing] Add concurrent checkpoint support in Operator Coordinator

flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/catalog/AbstractJdbcCatalog.java, flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/catalog/JdbcCatalog.java, flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/catalog/JdbcCatalogUtils.java, flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/catalog/MySqlCatalog.java, flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/catalog/PostgresCatalog.java, flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/catalog/factory/JdbcCatalogFactory.java, flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/dialect/JdbcDialectLoader.java, flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/options/JdbcConnectorOptions.java, flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/table/JdbcDynamicTableFactory.java, flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/table/JdbcRowDataLookupFunction.java, flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/catalog/MySqlCatalogTestBase.java, flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/catalog/PostgresCatalogTestBase.java, flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/catalog/factory/JdbcCatalogFactoryTest.java, flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/dialect/oracle/OraclePreparedStatementTest.java, flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/statement/FieldNamedPreparedStatementImplTest.java, flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/table/JdbcAppendOnlyWriterTest.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecPythonGroupAggregate.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecPythonGroupWindowAggregate.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecPythonOverAggregate.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecPythonCalc.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecPythonCorrelate.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecPythonGroupAggregate.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecPythonGroupTableAggregate.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecPythonGroupWindowAggregate.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecPythonOverAggregate.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/utils/CommonPythonUtil.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/physical/common/CommonPhysicalMatchRule.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/delegation/PlannerBase.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/physical/batch/BatchPhysicalSortRule.scala
*Since [FLINK-15635](https://issues.apache.org/jira/browse/FLINK-15635), in order to solve the class conflict problem, we introduce a user classloader in the table module, this classloader focus on loading the user class. So if the connector is added to TableEnvironment by add jar syntax, the class load behavior in the connector should also use the user classloader, otherwise, maybe occur ClassNotFound exception.*
Using the user classloader load some classes in JDBC connector.
Manually verified the changes. …
=> [FLINK-29074][Connectors/JDBC] Fix ClassNotFound exception when using jdbc connector by add jar syntax

docs/content.zh/docs/deployment/resource-providers/standalone/docker.md, docs/content/docs/deployment/resource-providers/standalone/docker.md
* Add required parameter to documentation when running SQL Client via Docker Compose
* Sync the Chinese documentation for Docker by copying the English content to the Chinese version
* Update docs
=> [FLINK-29210][Docs][SQL Client] Add required parameter when running SQL Client via Docker Compose

flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/writer/PulsarWriter.java
We'd better judge that the `timestamp` is greater than 0, we should skip setting eventTime when timestamp less than or equal to 0, otherwise the pulsar client will throw an exception.
check the `timestamp` is greater than 0 …
=> [FLINK-29207][connector/pulsar] Fix Pulsar message eventTime may be incorrectly set to a negative number

flink-kubernetes/pom.xml
Shade the fabric8 kubernetes deps with `org.apache.flink.shaded` prefix in flink-kubernetes
For supporting stepDecorators SPI(pluginable decorators), we propose to package the implementation class and associated dependencies into a plugin jar.
So we need to load the said dependencies from parent class loader, as the most part / all of plugin decorators depend on the fabric8 kubernetes dependency, such as replies on the kubernetes models/client from fabric8.
So we need to shade all the said classes in flink-kubernetes and flink-dist.
- Shade the `io.fabric.kubernetes` with `org.apache.flink.shaded` prefix.
- Exclude the original left dependencies / classes / SPI files in flink-dist.
Build the all flink packages, and verify the flink-kubernetes jar and flink-dist jar had re-leverage the …
=> [FLINK-29047][k8s] Shade fabric8 kubernetes with org.apache.flink.shaded prefix in flink-kubernetes

flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/writer/PulsarWriter.java
We'd better judge that the `timestamp` is greater than 0, we should skip setting eventTime when timestamp less than or equal to 0, otherwise the pulsar client will throw an exception.
check the `timestamp` is greater than 0 …
=> [FLINK-29207][connector/pulsar] release-1.15 Fix Pulsar message eventTime may be incorrectly set to a negative number

flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/writer/PulsarWriter.java
We'd better judge that the `timestamp` is greater than 0, we should skip setting eventTime when timestamp less than or equal to 0, otherwise the pulsar client will throw an exception.
check the `timestamp` is greater than 0 …
=> [FLINK-29207][connector/pulsar] release-1.16 Fix Pulsar message eventTime may be incorrectly set to a negative number

flink-connectors/flink-sql-connector-hive-2.3.9/src/main/resources/META-INF/NOTICE
This got rather complicated because hive-exec bundles parquet-hadoop-bundle which again bundles stuff, like another version of thrift/jackson.
There's also a bunch of missing dependencies bundled directly by hive-exec.
The changes are derived from the pom contents and the original hive-exec pom.
=> [FLINK-29211][hive][legal] Update 2.3.9 NOTICE

flink-table/flink-sql-parser-hive/src/main/java/org/apache/flink/sql/parser/hive/package-info.java, flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/package-info.java, flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/CreateTableLikeTest.java, flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkDDLDataTypeTest.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/delegation/PlannerContext.java
Since `SqlParser#configBuilder` is deprecated and probably will be removed in future versions. It is better to replace it with `SqlParser#config` This PR makes this change
=> [FLINK-29067][Table SQL/API] Replace deprecated SqlParser#configBuilder with SqlParser#config

flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/CoordinatorEventsToStreamOperatorRecipientExactlyOnceITCase.java
#20752 and #20754 have added test cases to verify that the operator coordinator can work correctly in case of concurrent checkpoints. However, when the checkpoint coordinator receives the completion message of checkpoint 1 and 2 at the same time, checkpoint 2 might be completed in advance due to the async mechanism in the checkpointing process, causing the accidental abortion of checkpoint 1 and failure of the added test case. This PR resolves the problem by further guaranteeing the completion order of the checkpoints received by test operators and coordinators. …
=> [FLINK-29217][tests] Guarantee checkpoint order in OC test

flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/runner/JobDispatcherLeaderProcessFactoryFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/runner/SessionDispatcherLeaderProcess.java
The PR adds logging for jobs already reached their terminal state
_flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/runner/SessionDispatcherLeaderProcess.java_
=> [FLINK-29223][coordination] Add missing output info for jobs already reached terminal state

flink-connectors/flink-connector-gcp-pubsub/src/test/java/org/apache/flink/streaming/connectors/gcp/pubsub/DeserializationSchemaWrapperTest.java, flink-connectors/flink-connector-gcp-pubsub/src/test/java/org/apache/flink/streaming/connectors/gcp/pubsub/PubSubConsumingTest.java, flink-connectors/flink-connector-gcp-pubsub/src/test/java/org/apache/flink/streaming/connectors/gcp/pubsub/PubSubSourceTest.java, flink-connectors/flink-connector-gcp-pubsub/src/test/java/org/apache/flink/streaming/connectors/gcp/pubsub/common/AcknowledgeOnCheckpointTest.java, pom.xml
Migrate flink-connectors-gcp-pubsub module to AssertJ and JUnit 5 following the [JUnit 5 Migration Guide](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit)
1. Use JUnit5 and AssertJ in tests instead of JUnit4 and Hamcrest
2. Add dependency on `mockito-junit-jupiter` since pubsub connector requires it …
=> [FLINK-27937][tests][pubsub] Migrate flink-connectors-gcp-pubsub to JUnit 5

flink-connectors/flink-connector-cassandra/src/test/java/org/apache/flink/streaming/connectors/cassandra/CassandraConnectorITCase.java, flink-connectors/flink-connector-cassandra/src/test/java/org/apache/flink/streaming/connectors/cassandra/CassandraSinkBaseTest.java, flink-connectors/flink-connector-cassandra/src/test/java/org/apache/flink/streaming/connectors/cassandra/CassandraTupleWriteAheadSinkTest.java, flink-connectors/flink-connector-cassandra/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/GenericWriteAheadSinkTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/WriteAheadSinkTestBase.java
Migrate `WriteAheadSinkTestBase` and flink-connector-cassandra module to AssertJ and JUnit 5 following the [JUnit 5 Migration Guide](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit)
- Does this pull request introduce a new feature? (no )
- …
=> [FLINK-27936][tests] Migrate flink-connector-cassandra to JUnit5

flink-core/src/main/java/org/apache/flink/api/common/eventtime/WatermarksWithIdleness.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/source/ProgressiveTimestampsAndWatermarks.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/source/SourceOperatorEventTimeTest.java
This pull request adds IdlenessManager for main and per-split output in source operator to mark idleness only if both output are idle
- Add IdlenessManager for main and per-split output in source operator to mark idleness only if both output are idle
- Improve WatermarksWithIdleness to avoid sending idleness event repeatedly on idle
- Migrate SourceOperatorEventTimeTest to JUnit 5 style
- SourceOperatorEventTimeTest#testMainAndPerSplitWatermarkIdleness, that validates the reader output is marked as idle only if both main and per-split source are idle …
=> [FLINK-28975][connector/base] Add IdlenessManager for main and per-split output in source operator to mark idleness only if both output are idle

flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/DefaultJobManagerRunnerRegistry.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DefaultJobManagerRunnerRegistryTest.java
`localCleanupAsync` is meant to be called from the `Dispatcher`'s main thread. Any blocking calls should be avoided here. Instead, we could use `closeAsync` which is implemented by `JobManagerRunner`.
* Replaced `close` call by the corresponding `closeAsync` call
* Adds test for checking the non-blocking behavior
* Adapted two other tests in `DefaultJobManagerRunnerRegistry` since the previously used `close` call resulted in an additional `FlinkException` being added to the Stacktrace in case of failure through `AutoCloseableAsync#close` …
=> [FLINK-29253][runtime] Removes synchronous close call from DefaultJobManagerRunnerRegistry#localCleanupAsync

flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/DefaultJobManagerRunnerRegistry.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DefaultJobManagerRunnerRegistryTest.java
=> [BP-1.16][FLINK-29253][runtime] Removes synchronous close call from DefaultJobManagerRunnerRegistry#localCleanupAsync

flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/DefaultJobManagerRunnerRegistry.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DefaultJobManagerRunnerRegistryTest.java
1.15 backport for PR https://github.com/apache/flink/pull/20811
=> [BP-1.15][FLINK-29253][runtime] Removes synchronous close call from DefaultJobManagerRunnerRegistry#localCleanupAsync

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/TableEnvironment.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/FunctionCatalog.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/utils/TableEnvironmentMock.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/FunctionITCase.java
Add table api for registering function with remote resource, so that we the advance function creation can be supported in DDL.
1. Change on Table API with new create function with resources
2. Add test case in TableEnvironmentImplTest
The PR is tested in the new test function in TableEnvironmentImplTest. …
=> [FLINK-27660][table] add table api for registering function with resource

pom.xml, tools/releasing/update_japicmp_configuration.sh
Japicmp exclusion denote changes that break source/binary compatibility which we have concluded to accept.
Since we always compare one from version to the immediately next version these exclusions are only required for a single release.
They will now be discarded automatically as part of the release process, when:
* the master branch is updated to compare against the new minor version
* the release branch is updated to compare against the new patch version
=> [FLINK-29260][release] Wipe exclusion list when updating reference version

flink-runtime-web/web-dashboard/src/app/share/customize/job-list/job-list.component.html, flink-runtime-web/web-dashboard/src/app/share/customize/job-list/job-list.component.ts
Allow to order jobs in webui
- add nzSortFn in job name column
=> [FLINK-27976][WebUi] Allow order jobs by name

flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaRpcService.java, flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/AkkaRpcServiceTest.java, flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/ContextClassLoadingSettingTest.java, flink-rpc/flink-rpc-core/src/main/java/org/apache/flink/runtime/rpc/RpcService.java, flink-runtime/src/main/java/org/apache/flink/runtime/registration/RetryingRegistration.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/util/MetricUtilsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/registration/RetryingRegistrationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rpc/TestingRpcService.java, flink-tests/src/test/java/org/apache/flink/runtime/operators/coordination/OperatorEventSendingCheckpointITCase.java
These make new implementations more complicated then it needs to be, since `getScheduledExecutor` subsumes all of them.
=> [FLINK-29249][rpc] Drop RpcService#execute/scheduleRunnable

flink-core/src/main/java/org/apache/flink/api/common/eventtime/WatermarksWithIdleness.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/source/ProgressiveTimestampsAndWatermarks.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/source/SourceOperatorEventTimeTest.java
Unchanged backport of #20760 on release-1.16
=> [FLINK-28975][connector/base] Add IdlenessManager for main and per-split output in source operator to mark idleness only if both outputs are idle
