apache/flink

- flink-end-to-end-tests/flink-end-to-end-tests-aws-kinesis-firehose/src/test/java/org/apache/flink/connector/firehose/table/test/KinesisFirehoseTableITTest.java
- flink-end-to-end-tests/flink-end-to-end-tests-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/table/test/KinesisStreamsTableApiIT.java
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/KafkaSinkE2ECase.java
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/KafkaSourceE2ECase.java
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SQLClientKafkaITCase.java
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SQLClientSchemaRegistryITCase.java
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SmokeKafkaITCase.java
- flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/TestUtils.java
- flink-end-to-end-tests/flink-end-to-end-tests-elasticsearch6/src/test/java/org/apache/flink/streaming/tests/Elasticsearch6SinkE2ECase.java
- flink-end-to-end-tests/flink-end-to-end-tests-elasticsearch7/src/test/java/org/apache/flink/streaming/tests/Elasticsearch7SinkE2ECase.java
- flink-end-to-end-tests/flink-end-to-end-tests-hbase/src/test/java/org/apache/flink/tests/util/hbase/SQLClientHBaseITCase.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/common/FlinkContainerWithPulsarEnvironment.java
- flink-end-to-end-tests/flink-end-to-end-tests-scala/src/test/java/org/apache/flink/tests/scala/ScalaFreeITCase.java
- flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/codegen/SqlITCaseBase.java
- flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/codegen/UsingRemoteJarITCase.java
- flink-end-to-end-tests/flink-sql-gateway-test/src/test/java/org/apache/flink/table/gateway/SqlGatewayE2ECase.java
- flink-end-to-end-tests/flink-streaming-kinesis-test/src/test/java/org/apache/flink/streaming/kinesis/test/KinesisTableApiITCase.java
- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/test/resources/ResourceTestUtils.java
This method is very common in e2e tests and required to be accessible to external connector repos.
Move the class to flink-test-utils which we actually publish (compared to flink-end-to-tests-common which is not because its internal).
> [FLINK-29285][tests] Move TestUtils#getResource

- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SsgNetworkMemoryCalculationUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/NettyShuffleMaster.java
- flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/TaskInputsOutputsDescriptor.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/SsgNetworkMemoryCalculationUtilsTest.java
After [FLINK-28663](https://issues.apache.org/jira/browse/FLINK-28663), one intermediate dataset can be consumed by multiple consumers, there is a case where one vertex can consume one intermediate dataset multiple times. However, currently in fine-grained resource mode, when computing the required network buffer size, the intermediate dataset is used as key to record the size of network buffer per input gate, which means it may allocate less network buffers than needed if two input gate of the same vertex consumes the same intermediate dataset. This patch tries to fix the issue.
- Fix the network memory size calculation issue in fine-grained resource mode
- Add test case to cover the scenario
- …
> [FLINK-29299][network] Fix the network memory size calculation issue in fine-grained resource mode

- flink-connectors/flink-sql-connector-kafka/pom.xml
- flink-connectors/flink-sql-connector-kafka/src/test/java/org/apache/flink/connectors/kafka/PackagingITCase.java
- flink-connectors/flink-sql-connector-kinesis/pom.xml
- flink-connectors/flink-sql-connector-kinesis/src/test/java/org/apache/flink/connectors/kinesis/PackagingITCase.java
- flink-end-to-end-tests/test-scripts/test_sql_client.sh
- flink-formats/flink-sql-avro/pom.xml
- flink-formats/flink-sql-avro/src/test/java/org/apache/flink/formats/avro/PackagingITCase.java
- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/packaging/PackagingTestUtils.java
- flink-test-utils-parent/flink-test-utils/src/test/java/org/apache/flink/packaging/PackagingTestUtilsTest.java
~~Based on #20828.~~
Decouples sql-jar packaging tests from the sql-client e2e tests. The added java utils make it easy to instead write tests directly in the respective module.
> [FLINK-29287][tests] Rewrite sql-client packaging tests 

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/KeyedStream.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/co/IntervalJoinOperator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/co/IntervalJoinOperatorTest.java
- flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/IntervalJoinITCase.java
This pull requst makes interval-join support side out late data.
Add `OutputTag` for left and right stream in `org.apache.flink.streaming.api.operators.co.IntervalJoinOperator`, and emit late data  when `isLate(ourTimestamp) = true`
`IntervalJoinITCase.testIntervalJoinSideOutputLeftLateData`
`IntervalJoinITCase.testIntervalJoinSideOutputRightLateData`
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (**yes**/ no) …
> [FLINK-24907] Support side out late data for interval join

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveOperationExecutor.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java
To fix the wrong behavior for Hive's load data inpath
- Call method `HiveCatalog#loadTable(..., isOverWrite, isSourceLocal)` with `HiveCatalog#loadTable(..., hiveLoadDataOperation.isOverwrite(),  hiveLoadDataOperation.isSrcLocal())` instead of `HiveCatalog#loadTable(..., hiveLoadDataOperation.isSrcLocal(),  hiveLoadDataOperation.isOverwrite())`.
The modified test in `HiveDialectQueryITCase#testLoadData`. …
> [FLINK-29222][hive] fix wrong behavior for Hive's load data inpath

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumer.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumerTest.java
*Fix the NPE issue when calling Kinesis connector close method before subtask starts running results*
- *Check object is null or not before calling*
This change is already covered by added unit test case
> [FLINK-29324] [Connectors/Kinesis] Fix NPE for Kinesis connector when closing

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/HiveCatalog.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveOperationExecutor.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveShowTableUtils.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/operations/HiveLoadDataOperation.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/operations/HiveShowCreateTableOperation.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserDDLSemanticAnalyzer.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserLoadSemanticAnalyzer.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectITCase.java
To fix `SHOW CREATE TABLE` doesn't work for Hive dialect.
-  Add a `HiveShowCreateTableOperation` and when it's for `Show create table` statement, convert it to `HiveShowCreateTableOperation`
- Execute `HiveShowCreateTableOperation` in [HiveOperationExecutor.java](https://github.com/apache/flink/pull/20795/files#diff-52329b629087f71c6286fc43c0c0f3e652a2e25c3e26b59519d2b7b1d02b492b)
Added test `HiveDialectITCase#testShowCreateTable` …
> [FLINK-29152][hive] fix SHOW CREATE TABLE doesn't work for Hive dialect

- flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaInvocationHandler.java
- flink-rpc/flink-rpc-core/src/main/java/org/apache/flink/runtime/rpc/RpcGatewayUtils.java
The extraction of RpcTimeouts is independent of the underlying implementation.
> [FLINK-29377][rpc] Reusable timeout extraction

- flink-runtime/src/test/java/org/apache/flink/runtime/rpc/RpcConnectionTest.java
The test now uses a URL that is actually compliant with the format constraints imposed by the RPC implementation.
> [FLINK-29374][rpc][tests] Use proper RPC url

- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/Execution.java
Before:
`Concurrent unexpected state transition of task HelloWorld_1 to DEPLOYING while deployment was in progress.`
After:
`Concurrent unexpected state transition of task abc_def_1 from DEPLOYING (expected INITIALIZING) to RUNNING while deployment was in progress.`
> [FLINK-29378][coordination] Improve logging of failed execution state transitions

- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/CachingAsyncLookupFunction.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/CachingLookupFunction.java
This PR fixes the semantic of latestLoadTime in caching lookup function
- Fix semantic of latestLoadTime in caching lookup function
- If yes, how …
> [FLINK-28890][table] Fix semantic of latestLoadTime in caching lookup function

- flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaRpcService.java
- flink-rpc/flink-rpc-core/src/main/java/org/apache/flink/runtime/rpc/RpcEndpoint.java
- flink-rpc/flink-rpc-core/src/main/java/org/apache/flink/runtime/rpc/RpcService.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rpc/TestingRpcService.java
- flink-tests/src/test/java/org/apache/flink/runtime/operators/coordination/OperatorEventSendingCheckpointITCase.java
Give RpcServices control over how self gateways are implemented.
(Note that we don't really have a definition of what a self-gateway even _is_. Right now it's a sort of local gateway that skips serialization; but generally speaking that isn't required and more-or-less a performance optimization).
This is particularly interesting because how we implement it for Akka is rather strange, with the AkkaInvocationHandler impklementing both the `RpcGateway` _and_ `RpcServer` interface, despite never actually acting as an rpc server, making it difficult to wrap your head around what this handler actually does.
I don't think we should replicate that for other rpc implementations.
> [FLINK-29375][rpc] Move getSelfGateway() into RpcService

- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/CachingAsyncLookupFunction.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/CachingLookupFunction.java
> [BP-1.16][FLINK-28890][table] Fix semantic of latestLoadTime in caching lookup function

- docs/content.zh/docs/connectors/table/hbase.md
- docs/content.zh/docs/connectors/table/jdbc.md
- docs/content/docs/connectors/table/hbase.md
- docs/content/docs/connectors/table/jdbc.md
This pull request updates documentation of JDBC and HBase lookup table for new caching options.
- Update documentation of JDBC and HBase lookup table for new caching options …
> [FLINK-29389][docs] Update documentation of JDBC and HBase lookup table for new caching options

- docs/content.zh/docs/connectors/table/kinesis.md
- docs/content/docs/connectors/datastream/kinesis.md
- docs/content/docs/connectors/table/kinesis.md
> [hotfix][docs] Fix typos in Kinesis Connector docs.

- docs/content.zh/docs/deployment/overview.md
- docs/content.zh/release-notes/flink-1.6.md
- docs/content/docs/connectors/table/hive/overview.md
- docs/content/docs/deployment/overview.md
- docs/content/release-notes/flink-1.6.md
FLINK-24476 This pull request renames all documentation and code instances of ElasticSearch to Elasticsearch to align with their brand guidelines.
- There are no file names with an internal S
- All documentation, javadoc and private methods were renamed without an internal S.
- [This commit](https://github.com/RyanSkraba/flink/commit/55bbb7e7f747599b91a2926e47af4ea299a728e4) changes a class name that is technically exposed as API, but not `@Public` and clearly documented in comments for internal use only.
`grep -r lasticSearch .` returns no results after this commit.
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: **yes**
- The …
> [FLINK-24476][docs] Rename Elasticsearch to remove CamelCase

- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecOverAggregate.java
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/harness/OverAggregateHarnessTest.scala
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/over/ProcTimeUnboundedPrecedingFunction.java
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/over/ProcTimeUnboundedPrecedingFunctionTest.java
Currently we rely on the timer based state cleaning in proctime unbounded over aggregate, this can be optimized to use state ttl for a more efficienct way
use ttl to replace timer for ProcTimeUnboundedPrecedingFunction
ProcTimeUnboundedPrecedingFunctionTest
> [FLINK-29349][table-runtime] Use state ttl instead of timer to clean up state in proctime unbounded over aggregate

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveShowTableUtils.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserDDLSemanticAnalyzer.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectITCase.java
To fix fail to  compile flink-connector-hive for hive3
-  remove the usable of `TableType.INDEX_TABLE` and `ErrorMsg.SHOW_CREATETABLE_INDEX` since they have been removed in Hive3.
- Port `DEFAULT_SERIALIZATION_FORMAT` into our own code since `DEFAULT_SERIALIZATION_FORMAT` exist in different class between Hive2 and Hive3.
- Fix the test for show create table in Hive3 …
> [FLINK-29386][hive] Fix failed to compile flink-connector-hive in hive3 profile

- docs/content.zh/docs/deployment/finegrained_resource.md
- Translate "Fine-Grained Resource Management" page into Chinese:https://nightlies.apache.org/flink/flink-docs-master/zh/docs/deployment/finegrained_resource/
- The markdown file location: flink/docs/content.zh/docs/deployment/finegrained_resource.md, most of them have been translated, but some part has not been translated into Chinese.
- …
> [FLINK-28998] Translate'Fine-Grained Resource Management' page into Chinese

- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PartitionTestUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/ResultPartitionTest.java
fix unstable test ResultPartitionTest.testIdleAndBackPressuredTime: Due to the race condition, the main thread may recycle buffer before the request thread requests from bufferPool, causing the test to fail.
- *Migrate ResultPartitionTest and PartitionTestUtils to junit5 and assertJ.*
- *fix unstable test ResultPartitionTest.testIdleAndBackPressuredTime.*
- …
> [FLINK-28326][runtime] fix unstable test ResultPartitionTest.testIdleAndBackPressuredTime.

- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/EvictingWindowSavepointReader.java
- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/OperatorIdentifier.java
- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/SavepointReader.java
- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/SavepointWriter.java
- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/WindowSavepointReader.java
- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/runtime/metadata/SavepointMetadataV2.java
- flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/OperatorIdentifierTest.java
This PR introduces an `OperatorIdentifier`, an abstraction over uid (hashes), and integrates it into the internal state-processing APIs.
In a follow-up PR we'll adjust the user-facing APIs to allow the user to pass a uid hash.
> [FLINK-29455] Introduce OperatorIdentifier

- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSinkTest.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceITCase.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/RMQSourceTest.java
- flink-connectors/flink-connector-rabbitmq/src/test/java/org/apache/flink/streaming/connectors/rabbitmq/common/RMQConnectionConfigTest.java
- flink-connectors/flink-connector-rabbitmq/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
1. Migrate flink-connectors-rabbitmq module to AssertJ and JUnit 5 following the [JUnit 5 Migration Guide](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit)
2. Fix RestClusterClient injection …
> [FLINK-27942][tests] Migrate flink-connectors-rabbitmq to JUnit5

- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/jsonplan/JsonPlanGenerator.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/CreatingExecutionGraph.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StateTrackingMockExecutionGraph.java
- flink-tests/src/test/java/org/apache/flink/test/scheduling/ReactiveModeITCase.java
Update the JsonPlan of ExecutionGraph with the correct parallelism instead of using the original one from the JobGraph.
Added a test in `ReactiveModeITCase` …
> [FLINK-22243] Reactive Mode parallelism changes are not shown in the job graph visualization in the UI

- flink-connectors/flink-connector-kafka/pom.xml
- flink-connectors/flink-sql-connector-kafka/src/main/resources/META-INF/NOTICE
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/pom.xml
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SQLClientKafkaITCase.java
- flink-end-to-end-tests/flink-sql-client-test/pom.xml
- flink-end-to-end-tests/test-scripts/test_confluent_schema_registry.sh
- flink-end-to-end-tests/test-scripts/test_pyflink.sh
- flink-examples/flink-examples-build-helper/flink-examples-streaming-state-machine/src/main/resources/META-INF/NOTICE
- flink-formats/flink-avro-confluent-registry/pom.xml
* Update Kafka dependency to version 3.2.3 to take advantage of the security fixes in there
* Updated all references to the new Kafka version
> [FLINK-29513][Connector/Kafka] Update Kafka to version 3.2.3 

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriterImpl.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriterImplTest.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamConfig.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGenerator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorImpl.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorTest.java
Simplify the ChannelStateWriterImpl due to concurrent unaligned checkpoint isn't supported.
- Simplify the ChannelStateWriterImpl due to concurrent unaligned checkpoint isn't supported.
- If the checkpointId is aborted, the checkpoint will be ignored within `ChannelStateWriter#start`.
- *ChannelStateWriterImplTest#testStartMultipleTimes()*
- *ChannelStateWriterImplTest#testBuffersRecycledOnAbortedCheckpoint()*
- *ChannelStateWriterImplTest#testOldCheckpointIsAborted()* …
> [FLINK-28474][checkpoint] Fix the bug ChannelStateWriteResult might not fail after checkpoint abort

- flink-end-to-end-tests/flink-glue-schema-registry-avro-test/pom.xml
- flink-end-to-end-tests/flink-glue-schema-registry-json-test/pom.xml
- flink-formats/flink-avro-glue-schema-registry/pom.xml
- flink-formats/flink-json-glue-schema-registry/pom.xml
- flink-formats/flink-sql-protobuf/src/main/resources/META-INF/NOTICE
- flink-python/dev/dev-requirements.txt
- flink-python/src/main/resources/META-INF/NOTICE
- pom.xml
* Bump protoc and protobuf-java dependencies to at least 3.21.7 to avoid false positive scans on Protobuf vulnerabilities
* Updated version on POM/requirements 
* Updated NOTICE files
> [FLINK-29531][Formats][Protobuf] Bump protoc and protobuf-java dependencies to 3.21.7

- flink-end-to-end-tests/flink-end-to-end-tests-hbase/pom.xml
- flink-test-utils-parent/flink-test-utils/pom.xml
- flink-yarn-tests/pom.xml
- pom.xml
* Bump Minikdc to v3.2.4 to avoid getting falsely flagged as vulnerable for CVEs which don't impact Flink
* Updated dependency in POM
> [FLINK-29514][Deployment/YARN] Bump Minikdc to v3.2.4 

- flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/TableFunction.java
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/CodeGeneratorContext.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/OperatorCodeGenerator.scala
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/table/TemporalTableFunctionJoinTest.xml
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CorrelateITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/UserDefinedTableFunctions.scala
The task lifecycle was changed in FLINK-22972: a new finish() phase was introduced (extracted the ‘finish’ part out of the ‘close’) and the behavior  changed in `close` method. This was some kind of 'break change' for TableFunction users who did some flush work in previous `close` method(< 1.14). This pr aims to provide a possible migration path to support it again. If necessary, we can also consider backporting it to the corresponding older versions, including 1.14~1.16.
However, as a method that is not recommended for most users, I tend not to add it to the user documentation (just as  we didn't actively prompt users to do flush data in the close method before), so it is only been described in the method comments of the TableFunction, users who used this 'advanced' usage in previous …
> [FLINK-29406][table] Expose finish method for TableFunction

- docs/content.zh/release-notes/flink-1.14.md
- docs/content/release-notes/flink-1.14.md
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackend.java
- Fix typo in rocksdb.
- Fix typo in rocksdb.
- No need to test.
> [hotfix][docs] Fix typo in rocksdb.

- docs/data/sql_functions.yml
- docs/data/sql_functions_zh.yml
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/TemporalTypesTest.scala
> [FLINK-29517][doc]Support DATE_FORMAT built-in function in Table API

- flink-connectors/flink-connector-pulsar/pom.xml
- flink-connectors/flink-sql-connector-pulsar/src/main/resources/META-INF/NOTICE
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/pom.xml
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/util/DockerImageVersions.java
Unchanged backport of https://github.com/apache/flink/pull/20980
> [FLINK-29532][BP 1.16][Connector/Pulsar] Update Pulsar dependency to 2.10.1. 

- flink-docs/src/main/java/org/apache/flink/docs/rest/OpenApiSpecGenerator.java
- flink-docs/src/main/java/org/apache/flink/docs/rest/RuntimeOpenApiSpecGenerator.java
- flink-docs/src/main/java/org/apache/flink/docs/rest/SqlGatewayOpenApiSpecGenerator.java
- flink-docs/src/test/java/org/apache/flink/docs/rest/OpenApiSpecGeneratorTest.java
Separate titles so the title+version tuple is actually distinct between the 2 APIs.
Current specs aren't updated in this PR because I already applied the changes in a hotfix a while back (don't ask what made me think that wouldn't be overridden the next time they are generated...).
> [FLINK-29562][rest][docs] Distinct titles for JM/SQL gateway specs

- flink-connectors/flink-connector-kinesis/src/main/resources/META-INF/NOTICE
- flink-end-to-end-tests/flink-end-to-end-tests-aws-kinesis-firehose/pom.xml
- flink-filesystems/flink-azure-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-gs-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE
- flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE
- flink-formats/flink-sql-avro/src/main/resources/META-INF/NOTICE
- flink-kubernetes/src/main/resources/META-INF/NOTICE
- flink-python/src/main/resources/META-INF/NOTICE
- pom.xml
Update multiple Jackson dependencies to 2.13.4
Remove Jackson version from _flink-end-to-end-tests/flink-end-to-end-tests-aws-kinesis-firehose/pom.xml_ to be sync with Jackson BOM
- Updated POM file
- Updated NOTICE files
- The runtime per-record code paths (performance sensitive): (yes / no / **don't know**) …
> [FLINK-29468][connectors][filesystems][formats] Update Jackson-BOM to 2.13.4

- flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/src/FileSourceTextLinesITCase.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/sink/PulsarSinkITCase.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/PulsarSourceITCase.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/PulsarUnorderedSourceITCase.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/PulsarSinkE2ECase.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/PulsarSourceOrderedE2ECase.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/PulsarSourceUnorderedE2ECase.java
* There are known issues with Pulsar on Java 11, which is why we want to disable test runs on Java 11. However, the tests still use the JUnit4 annotation for disabling a test on Java 11, which doesn't work. This PR changes that annotation to the JUnit5 equivalent. 
* Change `@Category` to `@Tag` …
> [FLINK-29495][Connector/Pulsar] Refactor Pulsar tests to disable them on Java 11

- flink-connectors/flink-connector-kafka/pom.xml
- flink-connectors/flink-sql-connector-kafka/src/main/resources/META-INF/NOTICE
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/pom.xml
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SQLClientKafkaITCase.java
- flink-end-to-end-tests/test-scripts/test_confluent_schema_registry.sh
- flink-end-to-end-tests/test-scripts/test_pyflink.sh
- flink-examples/flink-examples-build-helper/flink-examples-streaming-state-machine/src/main/resources/META-INF/NOTICE
- flink-formats/flink-avro-confluent-registry/pom.xml
Unchanged backport of https://github.com/apache/flink/pull/20972
> [FLINK-29513][BP 1.16][Connector/Kafka] Update Kafka to version 3.2.3

- docs/static/generated/rest_v1_dispatcher.yml
- flink-docs/src/main/java/org/apache/flink/docs/rest/OpenApiSpecGenerator.java
Fixes an issue where no schema was defined for the jar upload content.
> [FLINK-29504][rest] Add schema to jar upload content 

- docs/layouts/shortcodes/generated/rest_v1_dispatcher.html
- docs/static/generated/rest_v1_dispatcher.yml
- flink-runtime-web/src/test/resources/rest_api_v1.snapshot
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/JobVertexBackPressureInfo.java
Enum fields have naming restrictions in some languages, rejecting hyphens. Duplicate the field in responses, while hiding the deprecated field in the openapi spec.
> [FLINK-29503][rest] Add backpressureLevel field 

- docs/content.zh/docs/libs/state_processor_api.md
- docs/content/docs/libs/state_processor_api.md
- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/OperatorIdentifier.java
- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/SavepointWriter.java
- flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/SavepointWriterUidModificationITCase.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/OperatorState.java
Adds the final piece for supporting UID hashes: a cheap way to map a uid hash to a UID.
This was implemented as a generic UID(hash) -> UID(hash) replacement, so you can also just replace a hash with another hash, or just change UID from one to another.
All without having to read the actual savepoint data.
> [FLINK-29457][state-processor] Add UID (hash) remapping fuction

- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java
To fix the HiveCatalogITCase fail with NPE
-  Changes statement `load data inpath` to  statement `load data local inpath` in `HiveDialectQueryITCase` for `load data inpath` will **move**  `/csv/test.csv`, which will result in other test can't find the file `/csv/test.csv`.
The pr https://github.com/apache/flink/pull/20905.
Without this commit, the misc test will failure https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=41778&view=results.
With this commit, the misc test will pass again https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=41820&view=results.
- The serializers: (yes / …
> [FLINK-29408][hive] fix HiveCatalogITCase fail with NPE

- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/sink/PulsarSinkITCase.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/PulsarSourceITCase.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/PulsarUnorderedSourceITCase.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/PulsarSinkE2ECase.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/PulsarSourceOrderedE2ECase.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/PulsarSourceUnorderedE2ECase.java
Unchanged backport of https://github.com/apache/flink/pull/21005
> [FLINK-29495][BP 1.15][Connector/Pulsar] Refactor Pulsar tests for disabling tests on Java 11

- flink-table/flink-sql-client/pom.xml
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliClient.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/parser/ClientParser.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/parser/SqlCommandParser.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/parser/SqlCommandParserImpl.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/parser/SqlMultiLineParser.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/parser/StatementType.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientTest.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/parser/ClientParserTest.java
The current `SqlCommandParserImpl` for SQL client use the paser of embedded `TableEnvironment`, which cannot be fetched in remote mode. So this PR introduce a new parser.
- Adjust the package structure for parsers.
- Modify `SqlCommandParser` for convenience: 
- extends `FlinkSqlParserImplConstants` to use defined token kinds
- add `parseStatement` method.
- implement `ClientParser` and add corresponding test.
This change added test: `ClientParserTest`. …
> [FLINK-29486][sql-client] Implement ClientParser for implementing remote SQL client later

- tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/licensecheck/NoticeFileChecker.java
- tools/ci/flink-ci-tools/src/test/java/org/apache/flink/tools/ci/licensecheck/NoticeFileCheckerTest.java
Fix for `flink-fs-hadoop-shaded`, `flink-s3-fs-base` and `flink-table-planner-loader-bundle` not being covered by license checks as they got auto-ignored due to not being deployed.
The checker now only ignores non-deployed modules if they are not bundled by another deployed module.
Note that this approach will not work if a non-deployed module is bundled by another non-deployed module which is then bundled by a deployed module.
This is currently not a problem though. 
I noticed this problem when I saw this in the CI output of a build, despite the NOTICE being correct:
```
flink-table-planner-loader-bundle:
These issues are mistakes that aren't legally problematic. They SHOULD be fixed at some point, but we don't have to: 
Dependency org.scala-lang:scala-compiler:2.12.7 is not bundled, but …
```
> [FLINK-29508][legal] Improve detection of non-deployed modules that need a NOTICE

- flink-clients/src/test/java/org/apache/flink/client/cli/CliFrontendSavepointTest.java
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SmokeKafkaITCase.java
- flink-end-to-end-tests/flink-end-to-end-tests-common/src/test/java/org/apache/flink/dist/DynamicParameterITCase.java
- flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/handlers/JarDeleteHandlerTest.java
- flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/handlers/JarHandlerParameterTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/RestExternalHandlersITCase.java
- pom.xml
*   Update JUnit5 dependency to the latest available version (5.9.1)
*   Remove `private` modifiers from methods annotated with `BeforeAll`, `AfterAll`, `BeforeEach`, `AfterEach` since now it fails (also mentioned in junit's release notes https://junit.org/junit5/docs/current/release-notes/#deprecations-and-breaking-changes-2)
* Updated reference in POM
* Updated test classes (modofiers)
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no ) …
> [FLINK-28768][tests][testinfrastructure] Update junit to 5.9.1

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParser.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserCalcitePlanner.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserDMLHelper.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserQBMetaData.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserUtils.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserBaseSemanticAnalyzer.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserQB.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserQBParseInfo.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserSemanticAnalyzer.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserUnparseTranslator.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/FromClauseASTParser.g
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserDDLSemanticAnalyzer.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserLoadSemanticAnalyzer.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java
Ti fix the failure for the query with non-hive table in Hive dialect.
- Modify [FromClauseASTParser.g](https://github.com/apache/flink/pull/20855/files#diff-2c1c44e0dd96a52613a64a23d27f68596207577457d5a0d2cbc9f1447daeba0f) to make table can be `catalog.db.table`.
- Parse table name user specified to `catalog.db.table` intead of `db.table`.
- Replace the Hive's `Table` which only represents `db.table` with Flink's `CatalogTable` which can  represents `catalog.db.table`.
Added test in [HiveDialectQueryITCase.java](https://github.com/apache/flink/pull/20855/files#diff-fb5fc4106e27e27f9968e59b643003444fd40af58aa2f147ac301009b53a47ca).
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / …
> [FLINK-29337][hive] Fix fail to query non-hive table in Hive dialect 

- flink-connectors/flink-connector-hive/pom.xml
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/ContinuousHiveSplitEnumerator.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/ContinuousHiveSplitEnumeratorTest.java
Let hive-enumerators do not assign splits to unregistered (failed) readers.
- add filter logic in ContinuousHiveSplitEnumerator#assignSplits
- add test for ContinuousHiveSplitEnumerator
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery …
> [FLINK-26726][connector][hive]Hive enumerators do not assign splits to unregistered (failed) readers.

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManagerImpl.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorSerializer.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/connector/sink2/CommittableSummaryAssert.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperatorTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManagerImplTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorSerializerTest.java
Fixing FLINK-29509 by setting the correct `subtaskId` and `numberOfSubtasks`  for `CheckpointCommittableManagerImpl` during recovery of committables for Sink V2 architecture.
- Remove constructor from `CheckpointCommittableManagerImpl` that was previously used only during deserialization and replace it with a new one that accepts `Map<Integer, SubtaskCommittableManager<CommT>> subtasksCommittableManagers` along with `subtaskId` and  `numberOfSubtasks`.
- Use new `CheckpointCommittableManagerImpl` constructor in `CommittableCollectorSerializer` deserialize method for  `CheckpointCommittableManagerImpl` passing `subtaskId` and `numberOfSubtasks` from serializer instance.
This changed enhanced existing `CommittableCollectorSerializerTest::testCommittableCollectorV2SerDe()` test by verifying …
> [FLINK-29509] Set proper subtaskId and numberOfSubtasks on CheckpointCommittableManagerImpl during recovery/deserialization.

- flink-filesystems/flink-azure-fs-hadoop/pom.xml
- flink-filesystems/flink-azure-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-fs-hadoop-shaded/pom.xml
- flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-gs-fs-hadoop/pom.xml
- flink-filesystems/flink-oss-fs-hadoop/pom.xml
- flink-filesystems/flink-oss-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-base/pom.xml
- flink-filesystems/flink-s3-fs-hadoop/pom.xml
- flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-presto/pom.xml
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE
- flink-filesystems/pom.xml
* Bump Hadoop dependencies for filesystems implementations
* Updated POM
* Updated NOTICE files
> [FLINK-29502][Filesystem][S3] Update the Hadoop implementation for filesystems to 3.3.4

- flink-connectors/flink-connector-hive/pom.xml
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/ContinuousHiveSplitEnumerator.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/ContinuousHiveSplitEnumeratorTest.java
backport of https://github.com/apache/flink/pull/19250
*(or)*
*(or)*
*(example:)*
- *Added integration tests …
> [FLINK-26726][bp-1.16][connector][hive]Hive enumerators do not assign splits to unregistered (failed) readers

- flink-connectors/flink-connector-hive/pom.xml
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/ContinuousHiveSplitEnumerator.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/ContinuousHiveSplitEnumeratorTest.java
backport of https://github.com/apache/flink/pull/19250
> [FLINK-26726][bp-1.14][connector][hive]Hive enumerators do not assign splits to unregistered (failed) readers 

- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/JobVertex.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGenerator.java
Concurrent serialization for `OperatorCoordinators` was added in FLINK-26675. These are added concurrently to `JobVertex` which uses `ArrayList` internally to collect them. `ArrayList` isn't thread-safe and, therefore, might cause issues where `OperatorCoordinator.Provider` instances are actually dropped during runtime.
* Replaces `ArrayList` type by `List`
* ~Synchronizes adding the `OperatorCoordinator.Provider` instances~ Collect all serialized OperatorCoordinator instances before adding them in a single for loop sequentially to `JobVertex`
Repeating run of `SourceNAryInputChainingITCase#testDirectSourcesOnlyExecution` with and without the change:
* 5000 test runs including the PR's fix without any error
* repeated test runs without fix: 9 failures out of 5000 …
> [FLINK-29576][runtime] Adds concurrency support to JobVertex#addOperatorCoordinator

- flink-connectors/flink-connector-hbase-2.2/src/test/java/org/apache/flink/connector/hbase2/HBaseConnectorITCase.java
According to the Jira, we still have a flaky HBase test case that rarely breaks the CI runs, although with the current implementation it does not says much about what exactly goes wrong, so I changed the logic a bit for future debugging, when the test breaks again.
Removed the count check, because right after that we are comparing the actual records, so next time the test will fail with a more meaningful message with the actual records, like:
```
[ERROR] Failures:
[ERROR]   HBaseConnectorITCase.testTableSourceSinkWithDDL:391 expected:<[+I[1, 10, Hello-1, 100, 1.01, false, Welt-1, 2019-08-18T19:00, 2019-08-18, 19:00, 12345678.0001], +I[2, 20, Hello-2, 200, 2.02, true, Welt-2, 2019-08-18T19:01, 2019-08-18, 19:01, 12345678.0002], +I[3, 30, Hello-3, 300, 3.03, false, Welt-3, 2019-08-18T19:02, …
```
> [FLINK-25343][hbase-tests] Remove count check from "testTableSourceSinkWithDDL"

- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumerTest.java
- flink-core/src/main/java/org/apache/flink/api/java/typeutils/TypeExtractor.java
- flink-core/src/main/java/org/apache/flink/util/InstantiationUtil.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/ExtractionUtils.java
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/expressions/TreeNode.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/functions/utils/ScalarSqlFunction.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/functions/utils/TableSqlFunction.scala
Since jdk1.8+ there is `Method#getParameterCount` which allows to get number of parameters. 
In several places `Method#getParametersTypes` is used for that like `getParameterTypes().length`
The issue with `Method#getParametersTypes` is that during each invocation it creates a new array by cloning an existing one.
The PR is replacing  `getParameterTypes().length` with  `Method#getParameterCount` 
Replacement of  `getParameterTypes().length` with  `Method#getParameterCount` 
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes )
- …
> [hotfix] Use getParameterCount rather than getParameterTypes().length

- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/benchmark/StateBackendBenchmarkUtils.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionKeyedStateBackend.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionStateBackend.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionInternalTimeServiceTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionStateBackendTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionStateBackendVerificationTest.java
Use correct `ExecutionConfig` in `BatchExecutionKeyedStateBackend`
- If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / …
> [FLINK-29645] BatchExecutionKeyedStateBackend is using incorrect ExecutionConfig when creating serializer

- docs/layouts/shortcodes/generated/pulsar_consumer_configuration.html
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/PulsarSourceOptions.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/config/PulsarSourceConfigUtils.java
The config option `pulsar.consumer.autoUpdatePartitionsIntervalSeconds` in Pulsar connector is conflict with Flink's split discovery logic and useless. We should remove it.
Remove the `PulsarSourceOptions.PULSAR_AUTO_UPDATE_PARTITIONS_INTERVAL_SECONDS` field. …
> [FLINK-29580][Connector/Pulsar] Remove pulsar.consumer.autoUpdatePartitionsIntervalSeconds option.

- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/PulsarSinkBuilder.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/PulsarSourceBuilder.java
Authentication is a common used function in consuming/producing message between Pulsar and Flink. We didn't expose it to Builder method, and use the common config options instead. Exposing the auth setting to a new `setAuthentication` method will simplify the development for end-user.
Add two new `setAuthentication` method for both `PulsarSinkBuilder` and `PulsarSourceBuilder`. …
> [FLINK-29433][Connector/Pulsar] Support Auth through the builder pattern in Pulsar connector.

- flink-connectors/flink-connector-pulsar/pom.xml
`pulsar-client-all` requires `jaxb-api` to serialize some Admin API. We shouldn't exclude it in current dependency list. So we just add it back to `flink-connector-pulsar`.
Same above.
> [FLINK-28960][Connector/Pulsar] Add jaxb-api back to pulsar-client-all dependencies.

- flink-fs-tests/src/test/java/org/apache/flink/hdfstests/DistributedCacheDfsTest.java
`DistributedCacheDfsTest.testSubmittingJobViaRestClusterClient` failed again on `master`. Removing the test timeout might give us more clues on where the test stalled to get a better understanding.
Removed the timeout configuration. …
> [FLINK-25554][test] Remove timeout to enable a thread dump in case the test times out again.

- flink-fs-tests/src/test/java/org/apache/flink/hdfstests/DistributedCacheDfsTest.java
1.16 backport PR for PR #21066
> [BP-1.16][FLINK-25554][test] Remove timeout to enable a thread dump in case the test times out again.

- flink-fs-tests/src/test/java/org/apache/flink/hdfstests/DistributedCacheDfsTest.java
1.15 backport PR for PR #21066
> [BP-1.15][FLINK-25554][test] Remove timeout to enable a thread dump in case the test times out again.

- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/cursor/MessageIdUtils.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/cursor/start/MessageIdStartCursor.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/cursor/stop/MessageIdStopCursor.java
Pulsar did a wrong batch message size assertion in code. We require every batch message should have size 1. But sometimes the message size could be 0 due to the serialization and deserialization. So we should change the assertion logic.
Change the implementation in `MessageIdUtils.unwrapMessageId(MessageId)`.
This change is a trivial fix without any test coverage. …
> [FLINK-29613][Connector/Pulsar] Fix wrong batch size assertion.

- docs/layouts/shortcodes/generated/pulsar_sink_configuration.html
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/PulsarSinkOptions.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/config/PulsarSinkConfigUtils.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/config/SinkConfiguration.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/writer/PulsarWriter.java
PulsarSink is slow when we use the `At-Least-Once` or `Exactly-Once`. This is because PulsarSink uses `MailboxExecutor` to write messages. A lot of useless context switches and locks acquire happened when using this writing policy. We should drop `MailboxExecutor` and send messages directly for better performance.
- Deprecated useless `PulsarSinkOptions.PULSAR_MAX_PENDING_MESSAGES_ON_PARALLELISM` option since Pulsar client has its own send rate limit by memory.
- Remove the use of `MailboxExecutor` in `PulsarWriter`.
This change is already covered by existing tests, such as *PulsarWriterTest*. …
> [FLINK-28820][Connector/Pulsar] Improve the writing performance for PulsarSink

- flink-connectors/flink-connector-kafka/pom.xml
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/pom.xml
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SQLClientSchemaRegistryITCase.java
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/containers/SchemaRegistryContainer.java
- flink-end-to-end-tests/test-scripts/kafka-common.sh
- flink-end-to-end-tests/test-scripts/test_confluent_schema_registry.sh
- flink-end-to-end-tests/test-scripts/test_pyflink.sh
- flink-formats/flink-avro-confluent-registry/pom.xml
- flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/util/DockerImageVersions.java
- tools/azure-pipelines/cache_docker_images.sh
We have updated the used Kafka Clients to v3.1.1 via [FLINK-28060](https://issues.apache.org/jira/browse/FLINK-28060) and then to v3.2.1 via [FLINK-28060](https://issues.apache.org/jira/browse/FLINK-28060) and finally to v3.2.3 via [FLINK-29513](https://issues.apache.org/jira/browse/FLINK-29513), but we are using Confluent Platform 6.2.2 which supports up to Kafka 2.8.0.
We should update to Confluent Platform v7.2.2 (latest version of 7.2), which includes support for Kafka 3.2.3.
* Updated all references to Confluent Platform versions (6.2.2) to 7.2.2
* Reset Zookeeper to match with the general Zookeeper version we use in Flink
* Refactored Schema Registry container to be included in `DockerImageVersions`
- …
> [FLINK-28405][Connector/Kafka] Update Confluent Platform images used for testing to v7.2.2

- docs/.gitignore
Add hugo_build.lock to .gitignore
the same way it is done in hugo itself [1]
[1] https://github.com/gohugoio/hugoDocs/blob/master/.gitignore
- If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / …
> [hotfix][docs][git] Add hugo_build.lock to .gitignore

- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/KerberosDelegationTokenManagerFactory.java
Kerberos delegation token manager starts even if the user not provided valid credentials. This is simply wrong behavior.
Load kerberos delegation token manager only if the user provided valid credentials.
* Executed `EventTimeWindowCheckpointingITCase` and double checked that exception is not thrown
> [FLINK-29622][runtime][security] Start kerberos delegation token provider only if the user provided valid credentials

- docs/content/docs/deployment/resource-providers/native_kubernetes.md
- docs/content/docs/deployment/resource-providers/standalone/kubernetes.md
*Flink docs don't have any documentation link related to Flink Kubernetes operator. This change lets us see the Flink Kubernetes operator and how to use it.*
- *Added documentation links for Flink Kubernetes operator.*
This change is a trivial rework/code cleanup without any test coverage. I added new documentation links.
- Does this pull request introduces a new feature? no …
> [FLINK-29644] [docs] Adding flink k8s operator documentation link

- flink-connectors/flink-connector-kinesis/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE
- flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE
- flink-formats/flink-sql-avro/src/main/resources/META-INF/NOTICE
- flink-kubernetes/src/main/resources/META-INF/NOTICE
- flink-python/src/main/resources/META-INF/NOTICE
- pom.xml
Update multiple Jackson dependencies to 2.13.4.2 to fix CVE-2022-42003 
> [FLINK-29638][connectors][filesystems][formats] Update Jackson-BOM to 2.13.4.2 because of CVE-2022-42003

- flink-connectors/flink-sql-connector-elasticsearch6/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-elasticsearch7/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-kinesis/src/main/resources/META-INF/NOTICE
- flink-end-to-end-tests/flink-end-to-end-tests-aws-kinesis-firehose/pom.xml
- flink-filesystems/flink-azure-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-gs-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE
- flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE
- flink-formats/flink-sql-avro/src/main/resources/META-INF/NOTICE
- flink-kubernetes/src/main/resources/META-INF/NOTICE
- flink-python/src/main/resources/META-INF/NOTICE
- pom.xml
This PR is a backport of PR #21064 including also the changes related to [FLINK-29468](https://issues.apache.org/jira/browse/FLINK-29468) to make backporting of jackson version bumps easier.
> [BP-1.15][FLINK-29638][connectors][filesystems][formats] Update Jackson-BOM to 2.13.4.2 because of CVE-2022-42003

- flink-connectors/flink-connector-kinesis/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-elasticsearch6/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-elasticsearch7/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-kinesis/src/main/resources/META-INF/NOTICE
- flink-end-to-end-tests/flink-end-to-end-tests-aws-kinesis-firehose/pom.xml
- flink-filesystems/flink-azure-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-gs-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE
- flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE
- flink-formats/flink-sql-avro/src/main/resources/META-INF/NOTICE
- flink-kubernetes/src/main/resources/META-INF/NOTICE
- flink-python/src/main/resources/META-INF/NOTICE
- pom.xml
This PR is a backport of PR #21064 including also the changes related to FLINK-29468 to make backporting of jackson version bumps easier.
> [BP-1.16][FLINK-29638][connectors][filesystems][formats] Update Jackson-BOM to 2.13.4.2 because of CVE-2022-42003

- docs/content.zh/docs/ops/metrics.md
- docs/content/docs/ops/metrics.md
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointStatsTracker.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointStatsTrackerTest.java
*Expose the lastCheckpointId metric.*
- *Register  `LatestCompletedCheckpointIdGauge` named "lastCheckpointId"  to `CheckpointStatsTracker`*
This change is already covered by existing tests, such as *CheckpointStatsTrackerTest*.
> [FLINK-29195] Expose lastCompletedCheckpointId metric

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorSerializer.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperatorTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorSerializerTest.java
Fixing [FLINK-29627](https://issues.apache.org/jira/browse/FLINK-29627) where recovery more than one Committable causesed `IllegalStateException` and prevents cluster to start. 
Implemented fix is based on merging committables from same subtaskId during recovery for Sink V2 architecture.
- Enhance `CheckpointSimpleVersionedSerializer::deserialize` by calling `SubtaskCommittableManager::merge` for committables for same subtaskId.
- Add new test `Committablecollectorserializertest::testCommittablesForSameSubtaskIdV2SerDe` to verify deserialization of multiple committables for the same subtaskId.
- Enhanced `CommitterOperatorTest::testStateRestore` to include committables for same subtaskId. …
> [Flink 29627][streaming] Fix duplicate key exception during recovery more than 1 committable.

- docs/content.zh/docs/libs/state_processor_api.md
- docs/content/docs/libs/state_processor_api.md
- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/SavepointWriter.java
- flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/SavepointDeepCopyTest.java
- flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/SavepointWriterITCase.java
- flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/SavepointWriterTest.java
- flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/SavepointWriterUidModificationITCase.java
- flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/SavepointWriterWindowITCase.java
Based on #21085.
The SavepointWriter previously had to enforce that the user provides at least 1 operator because we used them to get access to the execution environment. No operator -> no environment -> can't setup remaining operations.
This PR adds new factory methods that have the user explicitly pass the environment. With that we can define any operation we like internally without requiring another operator.
The existing factory methods were deprecated. They will continue to work, but it they are used the program is still subject to the old requirement of having at least 1 operator.
> [FLINK-29582][state-processor] Relax 1+ operator requirement 

- pom.xml
No longer required. In fact they shouldn't have any effect at all because the dependencies have changed to the jakarta namespace :)
https://github.com/siom79/japicmp/blob/master/pom.xml#L188
> [FLINK-29706][build] Remove japicmp dependency bumps

- flink-table/flink-sql-client/src/test/resources/sql/catalog_database.q
- flink-table/flink-sql-gateway/src/test/resources/sql/catalog_database.q
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/catalog/CatalogITCase.java
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/TableEnvironmentTest.scala
This pull request fixes the issue that when dropping a catalog in use, the following SHOW CURRENT CATALOG still displays the dropped catalog by preventing users from dropping a catalog in use.
Let CatalogManager#unregisterCatalog throws CatalogException when dropping a catalog in use.
This change is a trivial rework and can be verified as follows:
- `CatalogITCase#testDropCatalog`
- `TableEnvironmentTest#testExecuteSqlWithCreateUseDropCatalog`
- `catalog_database.q` which executed by `ClientITCase` …
> [FLINK-29677] Prevent dropping the current catalog

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliClient.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/local/LocalExecutorITCase.java
There are unused methods 
`LocalExecutorITCase#executeAndVerifySinkResult`, 
`LocalExecutorITCase#verifySinkResult`
`LocalExecutorITCase#executeSql`
`CliClient#printWarning`
and the PR removes it
_flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/local/LocalExecutorITCase.java_
_flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliClient.java_ …
> [hotfix] Remove unused private method LocalExecutorITCase#executeAndVerifySinkResult

- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/reader/RunLengthDecoder.java
The PR uses byte array api instead of ByteBuffer api to improve performance  and compatible with DirectByteBuffer which does not have byte array backed  when reading parquet DataPage V2
- Use the byte array api instead of ByteBuffer api.
I have done a test to compare byte array api and ByteBuffer api on parquet-mr project.
The result is:
[Unpack8ValuesByteArray spent time] 80 ms
[Unpack8ValuesByteBuffer spent time] 133 ms
The test code is:
package org.apache.parquet.column.values.bitpacking;
import java.nio.ByteBuffer;
public class ByteBufferTest {
private static final BytePacker bytePacker = Packer.LITTLE_ENDIAN.newBytePacker(7);
private static final int COUNT = 100000;
public static void main(String[] args) {
byte  [] in  = new byte[1008];
int [] out = new int[1152];
int [] out1 = new …
> [FLINK-29271]Change to byte array from bytebuffer to improve performance and compatible direct byte buffers

- flink-runtime/src/main/java/org/apache/flink/runtime/state/memory/ByteStreamStateHandle.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/memory/ByteStreamStateHandleTest.java
When protobuf serializer serializes an object, which is built directly with builder without assign any value to field, the serializer will generate a zero length byte[] and then write it into state with content '\0'（indicates zero length data).
When recovered from checkpoint, protobuf seralizer deserialize the data. It get length 0, and call InputStream#read(byte[] bytes, int offset, int count) with count = 0.
The underlying Input implementation is [NoFetchingInput](https://github.com/apache/flink/blob/9d2ae5572897f3e2d9089414261a250cfc2a2ab8/flink-core/src/main/java/org/apache/flink/api/java/typeutils/runtime/NoFetchingInput.java). It will call Inputsteam#read(byte[] bytes, int offset, int count) with count = 0.
The InputStream implementation is …
> [FLINK-29347] [runtime] Fix ByteStreamStateHandle#read return -1 when read count is 0

- flink-dist/src/main/flink-bin/bin/config.sh
The following shell command always make FLINK_DIST_COUNT=1 
`FLINK_DIST_COUNT="$(echo "$FLINK_DIST" | wc -l)" `
and the following condition will always be false, so fail to check multiple flink-dist*.jar。
`[[ "$FLINK_DIST_COUNT" -gt 1 ]] `
for example:
```
1
```
- fix the check logic when more than one file matching flink-dist*.jar exists in /lib
- create a fake flink-dist*.jar in lib, `touch lib/flink-dist-fake.jar`
- run flink shell command, `./bin/flink`
ERROR message should print
`[ERROR] Multiple flink-dist*.jar found in ...` …
> [FLINK-29306][shell] Fix the error detection of multiple flink-dist-*.jar for config.sh

- docs/content.zh/docs/connectors/datastream/kafka.md
- docs/content/docs/connectors/datastream/kafka.md
Doc should be updated: `FlinkKafkaConsumer` is deprecated and will be removed with Flink 1.17 instead of 1.15 since Flink 1.16 has code freeze and will be released soon.
- kafka.md
- zh kafka.md
This change is a trivial doc update without any test coverage. …
> [hotfix][doc] `FlinkKafkaConsumer` is deprecated and will be removed with Flink 1.17 instead of 1.15

- docs/content.zh/docs/connectors/datastream/kafka.md
- docs/content/docs/connectors/datastream/kafka.md
Change the docs: FlinkKafkaConsumer is deprecated and will be removed with Flink 1.17 instead of 1.15 since Flink 1.16 has code freeze and will be released soon.
- kafka.md
- zh kafka.md
This change is a trivial doc update without any test coverage. …
> [hotfix][doc] `FlinkKafkaConsumer` will be removed with Flink 1.17 instead of 1.15 

- flink-formats/flink-orc-nohive/src/test/java/org/apache/flink/architecture/TestCodeArchitectureTest.java
- flink-formats/flink-orc-nohive/src/test/java/org/apache/flink/orc/nohive/OrcColumnarRowSplitReaderNoHiveTest.java
- flink-formats/flink-orc-nohive/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
- flink-formats/flink-orc/src/test/java/org/apache/flink/architecture/TestCodeArchitectureTest.java
- flink-formats/flink-orc/src/test/java/org/apache/flink/orc/OrcColumnarRowInputFormatTest.java
- flink-formats/flink-orc/src/test/java/org/apache/flink/orc/OrcColumnarRowSplitReaderTest.java
- flink-formats/flink-orc/src/test/java/org/apache/flink/orc/OrcFileSystemFilterTest.java
- flink-formats/flink-orc/src/test/java/org/apache/flink/orc/OrcSplitReaderUtilTest.java
- flink-formats/flink-orc/src/test/java/org/apache/flink/orc/util/OrcBulkWriterTestUtil.java
- flink-formats/flink-orc/src/test/java/org/apache/flink/orc/writer/OrcBulkRowDataWriterTest.java
- flink-formats/flink-orc/src/test/java/org/apache/flink/orc/writer/OrcBulkWriterFactoryTest.java
- flink-formats/flink-orc/src/test/java/org/apache/flink/orc/writer/OrcBulkWriterITCase.java
- flink-formats/flink-orc/src/test/java/org/apache/flink/orc/writer/OrcBulkWriterTest.java
- flink-formats/flink-orc/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Update the `flink-formats/flink-orc` module to AssertJ and JUnit 5 following the [JUnit 5 Migration Guide](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit)
I've verified that there are 62 tests run in this module before and after the refactoring.
- The …
> [FLINK-27971][tests][JUnit5 migration] flink-orc

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/InitJobManagerDecorator.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/InitTaskManagerDecorator.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/Constants.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/KubernetesUtils.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/DecoratorWithPodTemplateTestBase.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/InitJobManagerDecoratorTest.java
- flink-kubernetes/src/test/resources/testing-pod-template.yaml
With this PR https://github.com/apache/flink/pull/18119 , `dnsPolicy` in the FlinkPod is no longer possible to override to other values than the default ones. This change add back the possibility to override it. 
- Check if `dnsPolicy` value is being passed in the PodTemplate.
- Fix `DNS_POLICY_DEFAULT` and  `DNS_POLICY_HOSTNETWORK`  typo.
- Added test that validates dnsPolicy before and after override. …
> [FLINK-29539] [Deployment/Kubernetes] dnsPolicy in FlinkPod is not overridable

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/InitJobManagerDecorator.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/InitTaskManagerDecorator.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/Constants.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/KubernetesUtils.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/DecoratorWithPodTemplateTestBase.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/InitJobManagerDecoratorTest.java
- flink-kubernetes/src/test/resources/testing-pod-template.yaml
This PR is a backport of PR https://github.com/apache/flink/pull/20982 that relates to [FLINK-29539](https://issues.apache.org/jira/browse/FLINK-29539)
> [BP-1.16][FLINK-29539][Deployment/Kubernetes] dnsPolicy in FlinkPod is not overridable

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliClient.java
The PR makes use of try resources for `CliClient#executeFile` and skip creation of `Completer` object in case of `CliClient#executeFile` since `Completer` makes sense only in interactive mode
> [FLINK-26390] Use try resourses for CliClient#executeFile

- pom.xml
- tools/releasing/update_japicmp_configuration.sh
`org.apache.flink.api.connector.source.SourceReader` declared a new default function `pauseOrResumeSplits()`, japicmp plugin failed during ci running, we should configure the plugin to make it compatible.
* configure overrideCompatibilityChangeParameter
> [FLINK-29787][ci] fix ci METHOD_NEW_DEFAULT issue

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/InitJobManagerDecorator.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/InitTaskManagerDecorator.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/Constants.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/KubernetesUtils.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/DecoratorWithPodTemplateTestBase.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/InitJobManagerDecoratorTest.java
- flink-kubernetes/src/test/resources/testing-pod-template.yaml
This PR is a backport of PR https://github.com/apache/flink/pull/20982 that relates to [FLINK-29539](https://issues.apache.org/jira/browse/FLINK-29539)
> [BP-1.15][FLINK-29539][Deployment/Kubernetes] dnsPolicy in FlinkPod is not overridable

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/testutils/KafkaUtil.java
Resolving test instability
* set offsets.topic.replication.factor to 1 in Kafka container
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **no** …
> [FLINK-24119] [Connectors/Kafka] set offsets.topic.replication.factor to 1

- tools/releasing/update_japicmp_configuration.sh
PR #21184 updated the documentation a bit leaving it in a kind of inconsistent state. This hotfix PR fixes this issue. Reading the previous version of the comment was confusing because of the snapshot version being used for specifying the reference version but also for refering to the snapshot branch. I tried to make this more explicit now with that PR.
* Updates docs in script …
> [hotfix][docs] Makes the japicmp script documentation more consistent after the change in cb442936.

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaSinkITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/enumerator/KafkaEnumeratorTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaProducerTestBase.java
Remove unused private method/classes
_org.apache.flink.connector.kafka.sink.KafkaSinkITCase#createTestConsumer_ became unused after
https://github.com/apache/flink/commit/ade011ec139f8258db356abd65e6e83601cd22e1
_org.apache.flink.connector.kafka.source.enumerator.KafkaEnumeratorTest.BlockingClosingContext_ is unused since beginning
_org.apache.flink.streaming.connectors.kafka.KafkaProducerTestBase.BrokerRestartingMapper_ became unused after https://github.com/apache/flink/commit/5f5cab2f9a1175fa396833299c313c2de6d1dae3 …
> [hotfix][connectors][kafka] Remove unused private classes and methods

- docs/content.zh/docs/connectors/table/kinesis.md
- docs/content/docs/connectors/table/kinesis.md
- flink-connectors/flink-connector-aws-base/src/main/java/org/apache/flink/connector/aws/config/AWSConfigConstants.java
- flink-connectors/flink-connector-aws-base/src/main/java/org/apache/flink/connector/aws/util/AWSGeneralUtil.java
- flink-connectors/flink-connector-aws-base/src/test/java/org/apache/flink/connector/aws/util/AWSGeneralUtilTest.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/util/AWSUtil.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/TestUtils.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/util/AWSUtilTest.java
When using `ASSUME_ROLE` credentials provider option for AWS connectors, STS endpoint is chosen by AWS SDK. In some use cases default endpoint may be unreachable, for example global endpoint is not reachable when job is running inside VPC without internet connection.
Adding configuration option to set STS service endpoint when using `ASSUME_ROLE` credentials provider.
- Unit tests …
> [FLINK-29496] [Connector/Kinesis] Add configuration option for setting STS endpoint for AWS connectors

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaRecordSerializationSchema.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaWriter.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaWriterITCase.java
Make `KafkaWriter` skip null records since sending them is meaningless in the first place. The proposed behaviour has two main advantages:
1. It prevents a `NullPointerException`
2. It is more consistent with the _reading case_, where one can skip the null records returned by the deserializer
Add simple if statement in `KafkaWriter#serialize` for skipping them.
This change is already covered by the existing test `KafkaWriterITCase#testIncreasingRecordBasedCounters`, which has been slightly modified to account for null records. …
> [FLINK-29480][Connectors/Kafka] Skip null records when writing

- flink-connectors/flink-hadoop-compatibility/pom.xml
- flink-end-to-end-tests/flink-end-to-end-tests-scala/pom.xml
- flink-examples/flink-examples-batch/pom.xml
- flink-examples/flink-examples-streaming/pom.xml
- flink-libraries/flink-cep-scala/pom.xml
- flink-scala/pom.xml
- flink-streaming-scala/pom.xml
- flink-table/flink-table-api-scala-bridge/pom.xml
- flink-table/flink-table-api-scala/pom.xml
- flink-tests/pom.xml
- flink-yarn-tests/pom.xml
Fixes an issue where the source jars of the Table Scala APIs did not contain anything. We have to jump register the source directory with the build-helper-maven-plugin for them to be picked up by the jar plugin.
Additionally this PR clarifies this requirement in other usages, which made it seem that we only use the plugin for eclipse compatibility.
> [FLINK-29803][table] Populate Scala API source jars 

- flink-connectors/flink-connector-pulsar/pom.xml
- flink-connectors/flink-sql-connector-hbase-2.2/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-hive-3.1.3/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-kinesis/src/main/resources/META-INF/NOTICE
- flink-core/pom.xml
- flink-dist/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE
- flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/CsvCommons.java
- flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/CsvFileFormatFactory.java
- flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/CsvFormatFactory.java
- flink-optimizer/src/main/java/org/apache/flink/optimizer/plandump/PlanJSONDumpGenerator.java
- flink-runtime/pom.xml
- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/jsonplan/JsonPlanGenerator.java
- flink-table/flink-sql-parser-hive/src/main/java/org/apache/flink/sql/parser/hive/ddl/HiveDDLUtils.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointRescaleITCase.java
- pom.xml
* Upgrade org.apache.commons:commons-lang3 from 3.3.2 to 3.12.0 to avoid being falsely flagged for CVEs CVE-2021-29425 and CVE-2020-15250
* Update POM file and NOTICE files
> [FLINK-29624][Common][Connector][Filesystem] Upgrade commons-lang3 to 3.12.0

- docs/content.zh/docs/connectors/datastream/kafka.md
- docs/content/docs/connectors/datastream/kafka.md
Back port #21172  to master: Change the docs: FlinkKafkaConsumer is deprecated and will be removed with Flink 1.17 instead of 1.15 since Flink 1.16 has code freeze and will be released soon.
- kafka.md
- zh kafka.md
This change is a trivial doc update without any test coverage.
> [hotfix][doc] `FlinkKafkaConsumer` will be removed with Flink 1.17 instead of 1.15

- flink-rpc/flink-rpc-akka/pom.xml
- flink-rpc/flink-rpc-akka/src/main/resources/META-INF/NOTICE
* Update Akka to the latest 2.6 patch version, which is still under Apache license
* Updated POM and NOTICE files
> [FLINK-29626][Runtime] Update Akka to 2.6.20

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/proxy/DynamoDBStreamsProxy.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/proxy/DynamoDBStreamsProxyTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/FakeKinesisClientFactory.java
This pull request makes the Kinesis DynamoDB Streams Consumer close shards that are no longer valid rather than throwing an irrecoverable exceptions. This is because the `DescribeStream` API can return shards that are no longer valid and expects the client to handle them.
- `ResourceNotFoundException` thrown in `getShardIterator` for DynamoDB streams consumer is now swallowed
- A `null` `shardIterator` is returned which is an existing signal to close a shard
- Added  an `INFO` log to explain that the shard has been closed
- Added a unit test that validates that a `ResourceNotFoundException` thrown in `getShardIterator` is caught and a `null` is returned
- Manually verified the change by running the ConsumeFromDyanamoDB example, …
> [FLINK-26890][Connector/Kinesis] Handle invalid shards in DynamoDB

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateCheckpointWriter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestDispatcherImpl.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestDispatcherImplTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriterImplTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/CheckpointInProgressRequestTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorTest.java
Simplify the ChannelStateWriteRequestDispatcherImpl due to not supported concurrent unaligned checkpoint
The `Map<Long, ChannelStateCheckpointWriter> writers;` can be simplified to `long ongoingCheckpointId` and `ChannelStateCheckpointWriter writer`.
- *ChannelStateWriteRequestDispatcherImplTest.testConcurrentUnalignedCheckpoint()*
- *ChannelStateWriterImplTest.testAbortOldAndStartNewCheckpoint()* …
> [FLINK-29730][checkpoint] Do not support concurrent unaligned checkpoints in the ChannelStateWriteRequestDispatcherImpl

- pom.xml
Updating `maven-enforcer-plugin` to its latest version  3.1.0
- Update maven-enforcer-plugin to 3.1.0
CI takes care of this change.
Currently CI is failing due to FLINK-29868
- Dependencies (does it add or upgrade a dependency): **yes** (but only a build-time dependency)
- Does this pull request introduce a new feature? **no**
- If yes, how is the feature documented? **not applicable**
> [FLINK-29867][build] Update maven-enforcer-plugin to 3.1.0

- tools/azure-pipelines/build-apache-repo.yml
- tools/azure-pipelines/build-nightly-dist.yml
`build-nightly-dist.yml` currently uses the default JDK from https://github.com/flink-ci/flink-ci-docker which happens to be Java 1.8 that we use for releases. We should
1. not rely on this default being set to 1.8 and
2. be able to configure this in the workflows themselves
- extend `build-nightly-dist.yml`with capabilities to set the JDK just like `jobs-template.yml`
This change is a CI-only change that is verified by it as well.
> [FLINK-29865][CI] Allow setting the JDK in build-nightly-dist.yml

- pom.xml
Javadocs won't build when building for Java 11, e.g. like this:
```
./mvnw clean package javadoc:jar -Pjava11 -Pjava11-target -pl flink-dist -am -Drat.skip=true -Dcheckstyle.skip=true -Dspotless.apply.skip -DskipTests
```
- add missing `add-exports` for `java.rmi/sun.rmi.registry` to make it work
Verified with the build command from above …
> [FLINK-15633][build] Fix building Javadocs on JDK 11

- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/extensions/retry/strategy/RetryOnExceptionStrategy.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/extensions/retry/strategy/RetryStrategy.java
- flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/RetryOnExceptionExtensionTest.java
- flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/RetryOnExceptionTest.java
- flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/RetryOnFailureExtensionTest.java
- flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/RetryOnFailureTest.java
This pull request causes tests annotated with `@RetryOnException` to fail after the given number of retries when used with the JUnit5 `RetryExtension`.  This is the old behaviour we saw with the JUnit4 `RetryRule`.
Currently, the test is retried for the maximum number of executions, but the "expected" exception is never thrown even on the last try.  This causes the test to appear skipped instead of failed.
- If the test doesn't succeed on the last possible retry, the exception is propagated as a test failure.
- I reverted some overeager JUnit5 migration on test cases for the JUnit4 `RetryRule`.  This code is appropriately duplicated for `RetryExtension`.
This change is already covered by existing tests, such as `RetryOnExceptionExtensionTest`.
I've manually tested that the following test …
> [FLINK-29198][test] Fail after maximum RetryOnException

- flink-formats/flink-compress/src/test/java/org/apache/flink/formats/compress/CompressionFactoryITCase.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/architecture/TestCodeArchitectureTest.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/ParquetColumnarRowInputFormatTest.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/ParquetFileSystemITCase.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/ParquetFormatStatisticsReportTest.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/avro/AvroParquetFileReadITCase.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/avro/AvroParquetStreamingFileSinkITCase.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/protobuf/ParquetProtoStreamingFileSinkITCase.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/row/ParquetRowDataWriterTest.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/utils/SerializableConfigurationTest.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/vector/ParquetColumnarRowSplitReaderTest.java
- flink-formats/flink-parquet/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Update the `flink-formats/flink-parquet` module to AssertJ and JUnit 5 following the [JUnit 5 Migration Guide](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit)
I've verified that there are 94 tests run in this module before and after the refactoring.
- …
> [FLINK-28449][tests][JUnit5 migration] flink-parquet

- flink-connectors/flink-connector-pulsar/pom.xml
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/schema/PulsarSchema.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/schema/PulsarSchemaUtils.java
- flink-connectors/flink-sql-connector-pulsar/src/main/resources/META-INF/NOTICE
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/pom.xml
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/util/DockerImageVersions.java
Update the Pulsar dependency to 2.10.2 to benefit of the fixes highlighted at [apache/pulsar@v2.10.2 (release)](https://github.com/apache/pulsar/releases/tag/v2.10.2)
Update dependencies
> [FLINK-29709][Connector/Pulsar] Bump the Pulsar to latest 2.10.2

- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriter.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterTest.java
This is a bug fix, where `AsyncSinkWriter` doesn't register callback on state restoration causing records to reside in buffer more than assigned `maxTimeInBufferMS`
- Added callback registration on state restoration for async sink writer if needed.
- Added unit tests for respective change
- Added unit tests in `AsyncSinkWriterTest` …
> [FLINK-29827][Connectors/Base] Registering callback for AsyncWriter on restore from state

- flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/AsyncTableFunction.java
the example uses the same parameter name in the outer method  `eval(CompletableFuture<Collection<Row>> result, String rowkey)` and in the inner  `public void onSuccess(Result result) {` so the example isn't actually valid functioning code
- renamed the parameter in the inner method
> [JavaDoc Typo] Fix the example for HBaseAsyncTableFunction

- flink-runtime/src/main/java/org/apache/flink/runtime/state/SharedStateRegistryImpl.java
Improve logging in SharedStateRegistry
and make the conditional logic more clear.
This PR is copied from https://github.com/apache/flink/pull/20722 and address comment.
This change is a trivial rework without any (new) test coverage.
> [FLINK-29095][state] Improve logging in SharedStateRegistry

- flink-connectors/flink-connector-pulsar/pom.xml
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/schema/PulsarSchema.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/schema/PulsarSchemaUtils.java
- flink-connectors/flink-sql-connector-pulsar/src/main/resources/META-INF/NOTICE
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/pom.xml
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/util/DockerImageVersions.java
Bump the pulsar-client-all to 2.10.2 which fixes the `NullPointerException`. This issue cause the test hang in Flink CI.
> [FLINK-29495][Connector/Pulsar] Bump the Pulsar to latest 2.10.2

- flink-connectors/flink-sql-connector-hive-3.1.3/pom.xml
- flink-connectors/flink-sql-connector-hive-3.1.3/src/main/resources/META-INF/NOTICE
Fix dependencies error 
- The serializers:  no 
- The S3 file system connector:  no 
> [FLINK-29878][hive] Fix flink-sql-connector hive error

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/CheckpointConfig.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/ExecutionCheckpointingOptions.java
This PR refactors `CheckpointConfig` to use `Configuration` class
Please check individual commits.
This is only a refactor that's covered by existing tests.
- The S3 file system connector: (yes / no ****/ don't know) …
> [FLINK-29379][streaming] Migrate CheckpointConfig to use Configuration field and ConfigOption

- docs/layouts/shortcodes/generated/deployment_configuration.html
- flink-clients/src/main/java/org/apache/flink/client/program/StreamContextEnvironment.java
- flink-clients/src/test/java/org/apache/flink/client/program/StreamContextEnvironmentTest.java
- flink-core/src/main/java/org/apache/flink/configuration/Configuration.java
- flink-core/src/main/java/org/apache/flink/configuration/DelegatingConfiguration.java
- flink-core/src/main/java/org/apache/flink/configuration/DeploymentOptions.java
- flink-core/src/test/java/org/apache/flink/configuration/ConfigurationTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/ConfigurationNotAllowedMessage.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/storage/ExternalizedSnapshotLocation.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/storage/FileSystemCheckpointStorage.java
This PR depends on FLINK-29379, so please ignore a couple of first commits that are being reviewed in https://github.com/apache/flink/pull/21245
After FLINK-29379 we can re-implement checkNotAllowedConfigurations to produce better exception messages.
Instead of a generic "Configuration object ExecutionConfig changed", without a hint of what has been modified,
we can report what ConfigOption has been changed.
This change is partially covered by existing tests but also expands `StreamContextEnvironmentTest`.
- The runtime per-record code paths (performance sensitive): (yes / **no** …
> [FLINK-29888][streaming] Reimplement checkNotAllowedConfigurations using refactored CheckpointConfig and ExecutionConfig

- flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaUtils.java
- flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/RemoteAddressExtension.java
Fixes an issue where we're registering a new `ExtensionId` on every call to `RpcUtils#getAddress`, slowly increasing memory usage.
We now use a singleton instance of the `RemoteAddressExtension` to prevent this.
(ExtensionId is basically a factory for Extensions that also identifies extensions via object-identity.)
> [FLINK-29927][akka] Use singleton ExtensionId

- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/HBaseDelegationTokenProvider.java
- flink-runtime/src/main/resources/META-INF/services/org.apache.flink.runtime.security.token.DelegationTokenProvider
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/KerberosDelegationTokenManagerITCase.java
- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnTestBase.java
Basically this is a revamp of #20206 (seems like it's discontinued) with minor modifications and additional testing so copy-pasting the description.
This PR adds `HBaseDelegationTokenProvider` to obtain HBase delegation tokens using the new delegation token framework.
* Add `HBaseDelegationTokenProvider`
* Add `HBaseDelegationTokenProvider` into the `META-INFO` service registration
This provider functionality will be covered by some existing tests. But We don't have dedicated tests to test the HBase delegation token obtaining. I think we may need to add new end-to-end tests to cover it.
Manually tests on Yarn, detailed: [Test Gist](https://gist.github.com/JackWangCS/3019355b9fc4746024fe72b3bbad839b) …
> [FLINK-25909][runtime][security] Add HBaseDelegationTokenProvider

- docs/layouts/shortcodes/connector_artifact.html
Adds a new shortcode that allows connectors to render a maven dependency declaration while controlling the version.
Intentionally less powerful then the `artifact` shortcode because we likely won't need all that fancy stuff for a while.
> [FLINK-29958][docs] Add connector_artifact shortcode

- docs/config.toml
- docs/setup_docs.sh
- docs/themes/.gitignore
Rework the connector integration to not rely on go modules.
Instead we clone the relevant repos at the right branch/tag and merge the content directories into a pseudo hugo module that we put into the /themes directory.
On the connector side we can then remove the go.mod and config.toml.
> [FLINK-29957][docs] Rework connector docs integration

- docs/layouts/shortcodes/connector_artifact.html
Flink side needs to inject the Flink minor version since branches are not Flink version-specific.
This does mean that the master branch docs references dependencies that don't exist, but I can live with that. It's snapshot docs after all.
> [FLINK-29973][docs] connector_artifact appends Minor version

- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/writer/router/MessageKeyHash.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/writer/router/TopicRoutingMode.java
- flink-connectors/flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/config/CursorVerification.java
Serialisation failure on InlineElement field of CursorVerification class
Marked the InlineElement as transient to bypass serialisation process
*(Please pick either of the following …
> [FLINK-29860][Connectors / Pulsar] Pulsar connector bug when using Hybrid.Builder 

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaSinkITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/testutils/KafkaSinkExternalContext.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReaderTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/testutils/KafkaSourceExternalContext.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaInternalProducerITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaConsumerTestBase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaProducerTestBase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaShortRetentionTestBase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestEnvironmentImpl.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/shuffle/KafkaShuffleExactlyOnceITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/shuffle/KafkaShuffleITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableTestBase.java
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/main/java/org/apache/flink/tests/util/kafka/KafkaContainerClient.java
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SmokeKafkaITCase.java
- flink-end-to-end-tests/flink-sql-client-test/src/test/java/SqlClientITCase.java
Kafka creation/deletion is an async operation. The API gives back future(s) which must be waited in order to be on the safe side. Additionally the APIs can throw exceptions while waiting to finish. In this PR I've added a more or less consistent Kafka topic creation/deletion behavior to the tests. Namely future wait to all the places where it was missing. This may or may not fix the issue (Kafka itself can be buggy) but I'm pretty sure w/o consistent topic creation/deletion API usage we're in trouble.
* Wait for Kafka topic creation/deletion.
* Add random to test topic names …
> [FLINK-29914][tests] Wait for Kafka topic creation/deletion

- docs/README.md
- docs/setup_docs.sh
Based on #21282.
Switches the docs away from main to `v3.0.0`. Also adds some docs for previous changes.
> [FLINK-29972][docs] Use Elasticsearch 3.0.0 docs 

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaSinkITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/testutils/KafkaSinkExternalContext.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReaderTest.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/testutils/KafkaSourceExternalContext.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaInternalProducerITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaConsumerTestBase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaProducerTestBase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaShortRetentionTestBase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestEnvironmentImpl.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/shuffle/KafkaShuffleExactlyOnceITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/shuffle/KafkaShuffleITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableTestBase.java
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/main/java/org/apache/flink/tests/util/kafka/KafkaContainerClient.java
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SmokeKafkaITCase.java
Kafka creation/deletion is an async operation. The API gives back future(s) which must be waited in order to be on the safe side. Additionally the APIs can throw exceptions while waiting to finish. In this PR I've added a more or less consistent Kafka topic creation/deletion behavior to the tests. Namely future wait to all the places where it was missing. This may or may not fix the issue (Kafka itself can be buggy) but I'm pretty sure w/o consistent topic creation/deletion API usage we're in trouble.
* Wait for Kafka topic creation/deletion.
* Add random to test topic names …
> [FLINK-29914][tests][backport] Wait for Kafka topic creation/deletion

- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/sink/PulsarSinkITCase.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/function/ControlSource.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/PulsarRuntimeOperator.java
The tests in `PulsarSinkITCase` may failed with some error logs like below. This is caused by we may consume messages on a blank topic with no schema. Pulsar topic's schema is define by the first message sent to it. Or you can create schema on topic manually.
```
Failed to subscribe for topic [persistent://public/default/bCQuHnEp] in topics consumer, subscribe error: org.apache.pulsar.client.api.PulsarClientException$IncompatibleSchemaException: {"errorMsg":"Topic does not have schema to check","reqId":2052942634743575747, "remote":"localhost/127.0.0.1:44835", "local":"/127.0.0.1:41334"}
```
In this test, we will manually create the topic schema before the test which fixes this race condition.
- Create schema in `PulsarSinkITCase`.
- Log all the exceptions in `ControlSource` for better …
> [FLINK-29830][Connector/Pulsar] Create the topic with schema before consuming messages in PulsarSinkITCase

- docs/content/docs/deployment/resource-providers/native_kubernetes.md
- docs/content/docs/deployment/resource-providers/standalone/kubernetes.md
*Flink docs don't have any documentation link related to Flink Kubernetes operator. This change lets us see the Flink Kubernetes operator and how to use it.*
- *Added documentation links for Flink Kubernetes operator.*
This change is a trivial rework / code cleanup without any test coverage. This is Cherry-picked from commit 8f3eab244ee00f832b999b5899d206f5de08f373 …
> [FLINK-29644][docs] Added flink kubernetes operator documentation links

- flink-runtime/src/test/java/org/apache/flink/runtime/testutils/MiniClusterResource.java
Allow the user to hard-code a specific port. This can for example be useful for demos.
> [FLINK-28427][tests] MiniClusterResource respect explicit rest port configurations

- flink-connectors/flink-connector-hive/pom.xml
- flink-end-to-end-tests/flink-sql-gateway-test/pom.xml
This pull request removes a transitive dependency on `jamon-runtime:2.3.1`, which has a malformed pom.xml file. Flink already has a transitive dependency on `jamon-runtime:2.4.1`, which has a valid pom, so we just wind up using that one instead.
This fixes the build for me, since my Maven mirror rejects jamon-runtime:2.3.1 (due to the malformed pom). Note that this transitive dependency is via Hive, and we already exclude a bunch of other problematic transitive dependencies from the hive dependencies.
- exclude jamon-runtime from the direct dependencies that transitively import 2.3.1
- Run `./mvnw dependency:tree -Dincludes=org.jamon`
- Examine the results to verify …
> [FLINK-29962] Exclude jamon 2.3.1 from dependencies

- docs/content/docs/dev/table/concepts/versioned_tables.md
The line "+(UPDATE_AFTER)  10:45:00      Euro       116" is redundant here, and it's better to add more 'update_after' lines (not just one) for better understanding
> [hotfix][docs][table] Fix versioned table example

- tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/licensecheck/NoticeFileChecker.java
- tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/utils/dependency/DependencyParser.java
- tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/utils/notice/NoticeParser.java
- tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/utils/shared/Dependency.java
- tools/ci/flink-ci-tools/src/test/java/org/apache/flink/tools/ci/licensecheck/NoticeFileCheckerTest.java
- tools/ci/flink-ci-tools/src/test/java/org/apache/flink/tools/ci/utils/dependency/DependencyParserCopyTest.java
- tools/ci/flink-ci-tools/src/test/java/org/apache/flink/tools/ci/utils/dependency/DependencyParserTreeTest.java
- tools/ci/flink-ci-tools/src/test/java/org/apache/flink/tools/ci/utils/notice/NoticeParserTest.java
~~Based on #20067.~~
Store the classifier (e.g., "test-jar") in the `Dependency`. This is required to properly distinguish between multiple artifacts with the same (groupId, artifactId, version) triplet.
> [FLINK-28246][ci] Store classifier in Dependency 

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/serialization/EventSerializer.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/checkpointing/AbstractAlignedBarrierHandlerState.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/checkpointing/AbstractAlternatingAlignedBarrierHandlerState.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/checkpointing/AlternatingCollectingBarriers.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/checkpointing/AlternatingCollectingBarriersUnaligned.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/checkpointing/AlternatingWaitingForFirstBarrier.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/checkpointing/AlternatingWaitingForFirstBarrierUnaligned.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/checkpointing/BarrierHandlerState.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/checkpointing/SingleCheckpointBarrierHandler.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/checkpointing/AlternatingCheckpointsTest.java
The alignmentTimeout has been changed to alignedCheckpointTimeout in #16227 [FLINK-23041](https://issues.apache.org/jira/browse/FLINK-23041) .
But some fields or methods still use alignmentTimeout. They should be renamed to alignedCheckpointTimeout.
Change the alignmentTimeout to alignedCheckpointTimeout …
> [FLINK-30002][checkpoint] Change the alignmentTimeout to alignedCheckpointTimeout

- .github/workflows/docs.sh
- pom.xml
- tools/ci/compile.sh
Back when we used buildbot we had to keep the set of profiles constant across releases. Now that the docs are build via GHA we no longer need this legacy profile.
> [FLINK-30017][build] Remove aggregate-scaladoc profile

- tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/suffixcheck/ScalaSuffixChecker.java
- tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/utils/dependency/DependencyParser.java
- tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/utils/shared/DependencyTree.java
- tools/ci/flink-ci-tools/src/test/java/org/apache/flink/tools/ci/utils/dependency/DependencyParserTreeTest.java
- tools/ci/java-ci-tools/src/test/java/org/apache/flink/tools/ci/utils/shared/DependencyTreeTest.java
- tools/maven/suppressions.xml
~~Based on #20067.~~
Modifies the `DependencyParser` to return an actual tree structure.
This will be used later on to infer certain properties of transitive dependencies (e.g., if the direct dependency is optional, so are the transitive dependencies). This is usually already done by Maven, but there are some edge-cases where this is not the case.
> [FLINK-28245][ci] Parse actual Tree structure 

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraph.java
Fix syntax errors in  org.apache.flink.streaming.api.graph.StreamGraph.
The past participle is required after "must be". 
> [hotfix] fix syntax errors 

- flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/metrics/reporter/InstantiateViaFactory.java
- flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/metrics/reporter/InterceptInstantiationViaReflection.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/ReporterSetup.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/ReporterSetupTest.java
- flink-tests/src/test/java/org/apache/flink/runtime/metrics/JobManagerMetricsITCase.java
- flink-tests/src/test/java/org/apache/flink/runtime/metrics/SystemResourcesMetricsITCase.java
Following the deprecation in 1.16 this PR removes the reflection-based code path for instantiating reporters.
> [FLINK-24235][metrics] Only support reporters via factories

- docs/content.zh/docs/learn-flink/fault_tolerance.md
- docs/content/docs/learn-flink/fault_tolerance.md
- Update the missing parts of this fault_tolerance Chinese documentation.
- Update the missing parts of this fault_tolerance Chinese documentation.
- No need to test. …
> [hotfix][docs] Update the missing parts of this fault_tolerance Chinese documentation.

- flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/ContextClassLoadingSettingTest.java
CI fails due to main thread didn't wait the future is done. The contextClassLoaders may be empty when checking.
https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=43092&view=logs&j=0da23115-68bb-5dcd-192c-bd4c8adebde1&t=24c3384f-1bcb-57b3-224f-51bf973bbee8&s=ae4f8708-9994-57d3-c2d7-b892156e7812
Wait the scheduler future is done before check
- The S3 …
> [FLINK-30003][rpc] Wait the scheduler future is done before check

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveLookupTableSource.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveTableSource.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveLookupJoinITCase.java
… Hive lookup table source
This closes ##21302.
Backport for #21302.
> [FLINK-29992][hive] fix lookup join fail with Hive table as lookup table source

- flink-end-to-end-tests/test-scripts/common_yarn_docker.sh
- flink-end-to-end-tests/test-scripts/test_yarn_application_kerberos_docker.sh
- flink-end-to-end-tests/test-scripts/test_yarn_job_kerberos_docker.sh
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/DelegationTokenUpdater.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java
At the moment there is no e2e test which would test whether delegation token is working fine. In this PR I've added it.
* Added e2e delegation token framework test
* Removed all bash warnings
* Changed some Flink debug logs to info level
Existing e2e tests.
> [FLINK-29704][runtime][security] E2E test for delegation token framework

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointFailureManager.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/CheckpointFailureManagerITCase.java
Add the root cause when exceeded checkpoint tolerable failure threshold, it's helpful during troubleshooting.
After change:
Add the root cause when exceeded checkpoint tolerable failure threshold.
> [FLINK-29969][checkpoint] Show the root cause when exceeded checkpoint tolerable failure threshold

- flink-core/src/main/java/org/apache/flink/configuration/DelegatingConfiguration.java
- flink-core/src/test/java/org/apache/flink/configuration/DelegatingConfigurationTest.java
Configuration#set is meant to allow setting multiple options in a row, but this doesn't really work for the delegating configuration.
A surprising trap I fell into in FLINK-29993.
> [FLINK-30067][conf] DelegatingConfiguration#set returns itself

- flink-clients/src/main/java/org/apache/flink/client/deployment/application/FromClasspathEntryClassInformationProvider.java
- flink-clients/src/test/java/org/apache/flink/client/deployment/application/FromClasspathEntryClassInformationProviderTest.java
- flink-clients/src/test/java/org/apache/flink/client/program/DefaultPackagedProgramRetrieverTest.java
Remove a too eager main class check in `StandaloneApplicationClusterEntryPoint` (this is already covered by `PackagedProgram`).
- remove main class check from `FromClasspathEntryClassInformationProvider` 
This change is already covered by existing tests, such as `DefaultPackagedProgramRetrieverTest` which I adapted to get the `PackagedProgram` and fail through that since this is what an EntryPoint has to do.
- The S3 file …
> [FLINK-30045][flink-clients] fix too eager check for main class existence

- flink-connectors/flink-connector-kinesis/pom.xml
- flink-connectors/flink-sql-connector-kinesis/pom.xml
Remove a special case in our shading setup.
This shouldn't change the contents of the sql-connector-kinesis jar or the total set of dependencies visible to users of flink-connector-kinesis..
@dannycranmer It would be great if you could take a look.
> [FLINK-30089][kinesis] Remove dependency promotion

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/CreditBasedPartitionRequestClientHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/NettyPartitionRequestClient.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/PartitionRequestClientFactoryTest.java
Fix the bug of old netty client isn't closed when netty server closes channel and no input channel.
`CreditBasedPartitionRequestClientHandler#channelInactive`  doesn't call the `notifyAllChannelsOfErrorAndClose` when  the `inputChannels.isEmpty()`.
https://github.com/apache/flink/blob/d745f5b3f7a64445854c735668afa9b72edb3fee/flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/CreditBasedPartitionRequestClientHandler.java#L126
FLINK-15455 enables TCP connection reuse across multiple jobs. That means `CreditBasedPartitionRequestClientHandler#channelInactive` doesn't call the `notifyAllChannelsOfErrorAndClose` when  after old job stop and before new job start. If the tcp connection is disconnected during this period, the new job should create a new tcp connection. However, …
> [FLINK-28695][network] Fix the bug of old netty client isn't closed when netty server closes channel and no input channel

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestBase.java
- flink-core/src/main/java/org/apache/flink/configuration/MetricOptions.java
- flink-core/src/test/java/org/apache/flink/configuration/MetricOptionsTest.java
- flink-end-to-end-tests/flink-metrics-reporter-prometheus-test/src/test/java/org/apache/flink/metrics/prometheus/tests/PrometheusReporterEndToEndITCase.java
- flink-metrics/flink-metrics-jmx/src/test/java/org/apache/flink/runtime/jobmanager/JMXJobManagerMetricTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/ReporterSetupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/testutils/InMemoryReporter.java
- flink-tests/src/test/java/org/apache/flink/runtime/metrics/JobManagerMetricsITCase.java
- flink-tests/src/test/java/org/apache/flink/runtime/metrics/SystemResourcesMetricsITCase.java
Based on #21340.
The goal is to provide a means to set reporter options without having to manually assemble the right configuration key.
`MetricsOptions#forReporter` provides a view over a configuration that sets the right prefix (including the given reporter name), and the existing `MetricOptions` can then be used as-is to set particular settings.
> [FLINK-29993][conf] Add MetricOptions#forReporter

- flink-core/src/main/java/org/apache/flink/configuration/Configuration.java
- flink-core/src/main/java/org/apache/flink/configuration/ConfigurationUtils.java
- flink-core/src/main/java/org/apache/flink/configuration/GlobalConfiguration.java
- flink-core/src/test/java/org/apache/flink/configuration/ConfigurationTest.java
* if a map/list was malformed we logged the entire value
* if a line in the config was malformed we logged the entire line
Note: When some numeric/boolean/enum option fails being parsed we still log the entire value. I'm _assuming_ there won't be secrets of that type.
> [FLINK-24679][conf] Hide secret values from parser error messages

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internals/KafkaTopicPartitionAssigner.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/shuffle/FlinkKafkaShuffle.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/shuffle/FlinkKafkaShuffleProducer.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/shuffle/KafkaShuffleTestBase.java
Currently, the key group range in consumer side of Kafka Shuffle is not aligned with the producer side, there are two problems:
- The data partitioning of the sink(producer) is exactly the same way as a keyed stream that as the same maximum parallelism as the number of kafka partitions does, but in consumer side the number of partitions and key groups are not the same.
- There is a distribution of assigning kafka partitions to consumer subtasks (See KafkaTopicPartitionAssigner#assign), but the producer of Kafka Shuffle simply assume the partition index equals the subtask index.
For more details, please check [FLINK-29437](https://issues.apache.org/jira/browse/FLINK-29437).
- Set the max parallelism of the key stream in consumer side as the number of kafka partitions. 
- Use the same …
> [FLINK-29437] Align the partition of data before and after the Kafka Shuffle

- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnTestBase.java
Tests like `YARNSessionCapacitySchedulerITCase.testNonexistingQueueWARNmessage` are negative tests in a way that they try to test error handling. This is fine but YARN installs a shutdown hook for all failed to submit applications. The mentioned hook tries to kill the application and do some cleanup at JVM exit time. Since in tests the YARN cluster is already shut down the application kill is timing out which is 15 minutes by default. All in all we're wasting 15 minutes for each JVM stop when we execute such negative tests. In this PR I've lowered the timeout to 5 seconds with 1 second retry to speedup CI and spare our nerves.
Lowered YARN client timeout. …
> [FLINK-30085][tests] Lower YARN client timeout to speed-up negative tests

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/CreditBasedPartitionRequestClientHandler.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/PartitionRequestClientFactoryTest.java
> [BP-1.16][FLINK-28695][network] Fix the bug of old netty client isn't closed when netty server closes channel and no input channel

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/CreditBasedPartitionRequestClientHandler.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/PartitionRequestClientFactoryTest.java
> [BP-1.15][FLINK-28695][network] Fix the bug of old netty client isn't closed when netty server closes channel and no input channel

- docs/content.zh/docs/dev/table/sqlClient.md
- docs/content/docs/dev/table/sqlClient.md
The PR adds info about key-strokes in SQL client to docs
> [FLINK-24742][table][docs] Add info about SQL client key strokes to docs

- flink-connectors/flink-connector-aws-kinesis-firehose/src/main/java/org/apache/flink/connector/firehose/sink/KinesisFirehoseSinkElementConverter.java
- flink-connectors/flink-connector-aws-kinesis-streams/src/main/java/org/apache/flink/connector/kinesis/sink/KinesisStreamsSinkElementConverter.java
- flink-connectors/flink-connector-aws-kinesis-streams/src/test/java/org/apache/flink/connector/kinesis/sink/KinesisStreamsSinkElementConverterTest.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriter.java
- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/sink/writer/ElementConverter.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterTest.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/TestElementConverter.java
Add an `open()` method to the `ElementConverter` used with `AsyncSink`. This gives element converters a hook to use for construction on TM without serializing the local fields
- Add `open()` to `ElementConverter`
- Invoke `open()` from `AsyncSinkWriter` constructor 
- Update Kinesis Data Streams/Firehose element converter to use the new mechanism
- Added unit test
- Added test to `AsyncSinkWriterTest` …
> [FLINK-29938][Connectors/Base] Add open() Method to AsyncSink ElementConverter

- flink-clients/src/main/java/org/apache/flink/client/program/MutatedConfigurationException.java
The new message will look like:
```
org.apache.flink.client.program.MutatedConfigurationException: Not allowed configuration change(s) were detected:
- Configuration execution.sorted-inputs.enabled:true not allowed.
- Configuration execution.runtime-mode was changed from STREAMING to BATCH.
- Configuration execution.checkpointing.interval:500 ms not allowed in the configuration object CheckpointConfig.
- Configuration execution.checkpointing.mode:EXACTLY_ONCE not allowed in the configuration object CheckpointConfig.
- Configuration pipeline.max-parallelism:1024 not allowed in the configuration object ExecutionConfig.
- Configuration parallelism.default:25 not allowed in the configuration object ExecutionConfig.
at org.apache.flink.client.program.StreamContextEnvironment.checkNotAllowedConf …
```
> [FLINK-30155][streaming] Pretty print MutatedConfigurationException

- pom.xml
Upgrade to a newer version, containing some fixes that should unblock #20757.
Note: The version in the pom is 0.17.1.1 because I messed up the release. It is equivalent to the original 0.17.1.
> [FLINK-30167][build] Upgrade japicmp to 0.17.1

- docs/layouts/shortcodes/generated/pipeline_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/PipelineOptions.java
- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
This allows to change the job vertex parallelism of a JobGraph during job submission time without having to modify the JobGraph upfront.
The initial idea was to add a new field to the payload of the job submit Rest endpoint. However, it is probably more practical to handle the overrides in the same way as other PipelineOptions already do it, i.e. via the configuration.
The implementation is deliberately lenient with respect to the presence of job vertices. If vertices have been removed or new ones have been added, only the ones found will have their parallelism overrides. The verification should be performed by the caller, not by Flink. In particular, we want to support scenarios where users modify the deployment and we might not yet have overrides for all vertices.
Based on feedback in …
> [FLINK-29501] Add option to override job vertex parallelisms during job submission

- flink-connectors/flink-connector-hive/src/main/resources/META-INF/NOTICE
- flink-formats/flink-orc/pom.xml
- flink-formats/flink-parquet/pom.xml
- flink-formats/flink-sql-parquet/src/main/resources/META-INF/NOTICE
- flink-formats/pom.xml
* Update used Parquet dependency
* Updated reference in POM file
* Removed not-used Guava test dependency
> [FLINK-30170][Parquet] Update Parquet version to 1.12.3

- flink-connectors/flink-connector-jdbc/pom.xml
The PR upgrades postgres jdbc version to 42.5.1 to cope with CVE-2022-41946 as it is also mentioned in release notes https://jdbc.postgresql.org/changelogs/2022-11-23-42.5.1-release/
*flink-connectors/flink-connector-jdbc/pom.xml*
trivial rework / code cleanup without any test coverage. …
> [FLINK-30177][Connectors/JDBC] Update pgjdbc to avoid CVE-2022-41946

- docs/content.zh/docs/dev/table/sql/queries/joins.md
- docs/content/docs/dev/table/sql/queries/joins.md
*When two tables have the same field, do not specify the table name,Exception will be thrown：SqlValidatorException :Column 'currency' is ambiguous.
The page url is https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/dev/table/sql/queries/joins/*
- *The table name is added before the query field，“ orders.currency”*
- Does …
> [FLINK-29458][docs-zh]Update "Table API sql queries joins module case

- flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniCluster.java
- flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniClusterConfiguration.java
- flink-runtime/src/test/java/org/apache/flink/runtime/minicluster/TestingMiniClusterConfiguration.java
Currently, using MiniCluster with a metric reporter loaded as a plugin is not supported, because the ReporterSetup.fromConfiguration(config, null)); gets passed null for the PluginManager.
I think it is generally valuable to allow passing a PluginManager to the MiniCluster.
This change is a trivial extension without any test coverage.
> [FLINK-29779] Pass PluginManager into MiniCluster

- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/DelegationTokenConverter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/DelegationTokenListener.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/DelegationTokenManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/DelegationTokenUpdater.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/HBaseDelegationTokenProvider.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/KerberosDelegationTokenManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/KerberosDelegationTokenManagerFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/KerberosLoginProvider.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/NoOpDelegationTokenManager.java
On the discussion thread of the [delegation token framework generalization](https://lists.apache.org/thread/vgg5hbf5jljcxopfhb32w3l0wjoyko4o) popped up that annotations for public classes are missing on several places. In this PR I've added the appropriate annotations for all public delegation token framework classes.
Added annotations.
Trivial rework, not tests needed. …
> [FLINK-30134][runtime][security] Annotate all the public classes for the delegation token framework

- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
Stop stringifying exception for logging
In org.apache.flink.runtime.taskmanager.Task there are multiple places where we stringify an exception before logging. According to Slf4j logging, we can just leave the last argument as exception (or throwable) without fitting them into log message string with placeholders.
I wrote following code and the two print the same exception:
```java
Exception e =  new CompletionException("a", new FlinkException("b", new Exception("c")));
Task.LOG.error("luck number {}", 2022, e); // 1
e.printStackTrace(); // 2
```
- The …
> [FLINK-30179][runtime] Stop stringifying exception for logging

- flink-runtime/src/main/java/org/apache/flink/runtime/security/modules/HadoopModuleFactory.java
Lowers the log level to warning since Flink continues to work properly.
> [FLINK-30133][hadoop] Changes log level and make log message more descriptive.

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/KafkaSourceEnumerator.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/OffsetsInitializer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/TimestampOffsetsInitializer.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/enumerator/initializer/OffsetsInitializerTest.java
This change improves the TimestampOffsetsInitializer to be initialized with a configured offset reset strategy. The default behavior (LATEST) is preserved. This also fixes a bug for when the timestamp does not correspond to an offset in Kafka and clarifies the exception message that is thrown.
- Handles EARLIEST/LATEST/NONE
- For timestamps that do not correspond to an offset in Kafka and if configured with NONE, the initializer will throw an explicit exception.
- Added unit test to test the various offset reset strategies and the edge case where timestamp does not correspond to an offset in Kafka …
> [FLINK-28185][Connector/Kafka] handle missing timestamps when there are empty partitions for the TimestampOffsetsInitializer

- flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/legacy/DefaultExecutionGraphCacheTest.java
The stacktrace printout must have been accidentally added with PR #14804. It ends up in the regular CI Maven log output for the tests and confuses developers who analyze the logs.
Removes printout.
> [FLINK-29899][runtime][test] Removes obsolete printStackTrace()

- flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/legacy/DefaultExecutionGraphCacheTest.java
1.16 backport PR for parent PR #21395
> [BP-1.16][FLINK-29899][runtime][test] Removes obsolete printStackTrace()

- flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/legacy/DefaultExecutionGraphCacheTest.java
1.15 backport PR for parent PR https://github.com/apache/flink/pull/21395
> [BP-1.15][FLINK-29899][runtime][test] Removes obsolete printStackTrace()

- pom.xml
Update japicmp configuration for 1.15.3, as part of finalizing the release
> Update japicmp configuration for 1.15.3

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointFailureManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointFailureReason.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/PendingCheckpoint.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorFailureTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorMasterHooksTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorRestoringTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTriggeringTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointFailureManagerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointIDCounterTestBase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointStateRestoreTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/SchedulerTestingUtils.java
Some CheckpointFailureReasons have not been used for a long time and should be removed. E.g: 
- TOO_MANY_CONCURRENT_CHECKPOINTS
- CHECKPOINT_DECLINED_TASK_NOT_CHECKPOINTING
- CHECKPOINT_DECLINED_ALIGNMENT_LIMIT_EXCEEDED
- JOB_FAILURE
- The first commit: Remove some unused exceptions and refactor some code of CheckpointCoordinatorTest
- The second commit: Remove deprecated getCheckpointId of PendingCheckpoint
- The third commit: Migrate checkpoint coordinator related tests to junit5
- The fourth commit: Remove the unused CheckpointFailureReason
- The …
> [FLINK-30100][checkpointing] Remove the unused CheckpointFailureReason

- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/ReporterSetup.java
There's already a log message stating that reflection-based reporter instantiation is deprecated. Instead, the user should use switch to the factory-based instantiation method. Some reporters might still work. In other cases (where the default constructor is not implemented), the reflection-based approach would fail with a `NoSuchMethodException` which might be confusing for the user. This PR add a more descriptive error in that case.
* Wraps `NoSuchMethodException` in a `IllegalConfigurationException`. …
> [FLINK-30183][metrics] Adds more descriptive error in case no default constructor is present.

- flink-tests/src/test/java/org/apache/flink/api/connector/source/lib/util/RateLimitedSourceReaderITCase.java
Haven't reproduced it yet locally because my IDE is throwing up due to Scala, but this is the only possible explanation that I could come up with anyway.
> [FLINK-30228][test] Use thread-safe list

- flink-formats/flink-hadoop-bulk/src/test/java/org/apache/flink/formats/hadoop/bulk/HadoopPathBasedPartFileWriterTest.java
Fix FLINK-29092 in unit test 
Use BasePathBucketAssigner
Test case passed
No
No
> [FLINK-29092][tests] Use base path bucket assigner

- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/TimerGauge.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/TimerGaugeTest.java
Allow TimerGauges to define a time window similar to how MeterViews work in Flink. This allows us to collect more relevant metrics without losing information based on the metrics collection interval
* Change logic to support custom timespan in TimerGauge
* Add unit tests
Extended existing unit tests to cover different timespan. …
> [FLINK-30090] Support timespan for TimerGauges

- docs/content.zh/docs/dev/configuration/overview.md
- docs/content/docs/dev/configuration/overview.md
- flink-dist/src/main/resources/META-INF/NOTICE
- pom.xml
* Update slf4j from 1.7.32 to 1.7.36
* Update POM, documentation and NOTICE files
> [FLINK-30197][Logging] Update slf4j from 1.7.32 to 1.7.36

- flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobServerCleanupTest.java
The tests run the cleanup logic in a separate thread. The assert requires a timeout which was not necessarily long enough for the exception to be caught.
* Increases the timeout to a day to simulate "waiting forever"
> [FLINK-30138][runtime][test] Increases timeout to essentially wait forever for an expected Exception to be thrown

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/NettyShuffleEnvironment.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateFactory.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/NettyShuffleEnvironmentTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/benchmark/StreamNetworkBenchmarkEnvironment.java
*If a task has multiple input gates, It will create as many `InputChannelMetrics` as the number of gates, so the corresponding metrics are registered repeatedly. This pull request aimed to fix this problem.*
- *Create `InputChannelMetrics` in `NettyShuffleEnvironment#createInputGates`.*
This change added unit test in `NettyShuffleEnvironmentTest`.
> [FLINK-27944] Input channel metric will no longer be registered multiple times

- docs/content.zh/docs/connectors/table/kinesis.md
- docs/content/docs/connectors/table/kinesis.md
… configurations and synced chinese docs with non-chinese docs
hotfix for Kinesis Table API docs.
Cherry pick of commits from https://github.com/apache/flink/pull/21370
- Added missing "forwarded" columns for a couple of configs
- Synced non-chinese docs with chinese docs
- Added missing config for `sink.fail-on-error` in Table API docs …
> [hotfix][docs] Add missing columns for Kinesis Data Streams Table API

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/NettyShuffleEnvironment.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateFactory.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/NettyShuffleEnvironmentTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/benchmark/StreamNetworkBenchmarkEnvironment.java
*If a task has multiple input gates, It will create as many `InputChannelMetrics` as the number of gates, so the corresponding metrics are registered repeatedly. This pull request aimed to fix this problem.*
- *Create `InputChannelMetrics` in `NettyShuffleEnvironment#createInputGates`.*
This change added unit test in `NettyShuffleEnvironmentTest`.
> [BP-1.15][FLINK-27944] Input channel metric will no longer be registered multiple times

- flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/Catalog.java
Fix the improper reference to TableKind
Remove non existing doc link 
- Dependencies (does it add or upgrade a dependency): (yes / no) no 
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't know) no 
- The S3 file system connector: (yes / no / don't know) no 
- Does this pull request introduce a new feature? (yes / no) no  
> [FLINK-30240][table]Fix doc error reference to TableKind#MANAGED

- flink-connectors/flink-connector-datagen/src/test/java/org/apache/flink/connector/datagen/source/DataGeneratorSourceITCase.java
- flink-connectors/flink-connector-datagen/src/test/java/org/apache/flink/connector/datagen/source/DataGeneratorSourceTest.java
- flink-core/src/main/java/org/apache/flink/api/connector/source/util/ratelimit/RateLimitedSourceReader.java
Capturing the checkpointId for a generated record in a subsequent map function is impossible since the notifyCheckpointComplete notification may arrive at any time (or not at all). Instead just assert that each subtask got exactly as many records as expected, which can only happen (reliably) if the rate-limiting works as expected.
> [FLINK-30202][tests] Do not assert on checkpointId

- docs/content.zh/docs/connectors/datastream/guarantees.md
- docs/content.zh/docs/connectors/datastream/overview.md
- docs/content.zh/docs/connectors/table/overview.md
- docs/content/docs/connectors/datastream/guarantees.md
- docs/content/docs/connectors/datastream/overview.md
- docs/content/docs/connectors/table/overview.md
- docs/data/sql_connectors.yml
- docs/layouts/shortcodes/sql_connector_download_table.html
- docs/setup_docs.sh
Integrate flink-connector-aws into Flink docs
Related https://github.com/apache/flink/pull/21449
- Add a new short_code (`sql_connector_download_table`) to render SQL connector info for externalized connectors
- Integrate AWS connectors, flink-connector-dynamodb
Rendered web pages locally
> [FLINK-30291][Connector/DynamoDB] Update docs to render DynamoDB conn… (1.17)

- docs/content.zh/docs/connectors/datastream/guarantees.md
- docs/content.zh/docs/connectors/datastream/overview.md
- docs/content.zh/docs/connectors/table/overview.md
- docs/content/docs/connectors/datastream/guarantees.md
- docs/content/docs/connectors/datastream/overview.md
- docs/content/docs/connectors/table/overview.md
- docs/data/sql_connectors.yml
- docs/layouts/shortcodes/sql_connector_download_table.html
- docs/setup_docs.sh
Integrate flink-connector-aws into Flink docs
Related https://github.com/apache/flink/pull/21450
- Add a new short_code (`sql_connector_download_table`) to render SQL connector info for externalized connectors
- Integrate AWS connectors, flink-connector-dynamodb
Rendered web pages locally
> [FLINK-30291][Connector/DynamoDB] Update docs to render DynamoDB conn… (1.16)

- .github/workflows/docs.sh
- azure-pipelines.yml
- docs/build_docs.sh
- docs/config.toml
- docs/content.zh/docs/connectors/datastream/guarantees.md
- docs/content.zh/docs/connectors/datastream/overview.md
- docs/content.zh/docs/connectors/table/overview.md
- docs/content/docs/connectors/datastream/guarantees.md
- docs/content/docs/connectors/datastream/overview.md
- docs/content/docs/connectors/table/overview.md
- docs/data/sql_connectors.yml
- docs/layouts/shortcodes/connector_artifact.html
- docs/layouts/shortcodes/sql_connector_download_table.html
- docs/setup_docs.sh
- tools/azure-pipelines/build-apache-repo.yml
Integrate flink-connector-aws into Flink docs
Related https://github.com/apache/flink/pull/21450
https://github.com/apache/flink/pull/21449
- Add a new short_code (`sql_connector_download_table`) to render SQL connector info for externalized connectors
- Integrate AWS connectors, flink-connector-dynamodb
- Sync changes from 1.16 to build mounted connector docs
Rendered web pages locally …
> [FLINK-30291][Connector/DynamoDB] Update docs to render DynamoDB conn… (1.15)

- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/data/DecimalDataUtils.java
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/data/DecimalDataTest.java
*This pull request fixes the NPE thrown when filtering decimal(18, x) values after calling DecimalDataUtils.subtract method.*
- *Check the result precision before calculating the compacted decimal values.*
This change is already covered by existing tests, such as *org.apache.flink.table.data.DecimalDataTest.testNotCompact()*.
- The runtime per-record code paths (performance sensitive): (DecimalData subtract/add only) …
> [FLINK-30245][table-runtime] Fix the NPE thrown when filtering decimal(18, x) values after calling DecimalDataUtils.subtract method.

- flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/container/FlinkTestcontainersConfigurator.java
- pom.xml
Upgrade to the latest stable Zookeeper release. This client is compatible with 3.5 onwards.
> [FLINK-29420][build] Upgrade Zookeeper to 3.7.1

- pom.xml
- tools/ci/compile.sh
Run the plugin before the shade-plugin to not be affected by the shade-plugin changing the basedir, breaking relative paths in exclusions.
Additionally skips the rat plugin when building the javadocs on CI. This previously happened implicitly (since we never reached the verify stage), but it would fail now because of the javadoc plugin output.
> [FLINK-30286][build] Run rat-plugin in validate phase

- flink-state-backends/flink-statebackend-common/pom.xml
- flink-state-backends/flink-statebackend-common/src/test/java/org/apache/flink/state/common/PeriodicMaterializationManagerTest.java
- flink-state-backends/flink-statebackend-common/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Move tests to junit5 and assertj
> [FLINK-30316][statebackend] Migrate tests to JUnit5

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserCalcitePlanner.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserDMLHelper.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserUtils.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserBaseSemanticAnalyzer.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserSqlCountAggFunction.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserSqlSumAggFunction.java
- flink-table/flink-sql-parser-hive/src/main/java/org/apache/flink/sql/parser/hive/ddl/HiveDDLUtils.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/RelTimeIndicatorConverter.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/expressions/converter/OverConvertRule.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlCreateTableConverter.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlToOperationConverter.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/AggregateCallJsonDeserializer.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/FlinkAggregateExpandDistinctAggregatesRule.java
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/MatchCodeGenerator.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/metadata/AggCallSelectivityEstimator.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/metadata/SelectivityEstimator.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/calcite/WindowAggregate.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/logical/AggregateReduceGroupingRule.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/logical/SplitAggregateRule.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/AggregateUtil.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/FlinkRexUtil.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/metadata/AggCallSelectivityEstimatorTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdHandlerTestBase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdRowCountTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdSelectivityTest.scala
1. `org.apache.calcite.sql.SqlCharStringLiteral#getNlsString` was made deprecated at
https://github.com/apache/calcite/commit/a1bdba6d79ac05ef227cdb15b7c044c6e0e54dfa#diff-de2027de5bcb4bbe94314c3414b63166ecd9537b437e08d39f6424c0f903c8fbR48
and as suggested in the same place
```
* @deprecated Use {@link #getValueAs getValueAs(NlsString.class)}
```
2. `org.apache.calcite.rex.RexSimplify#RexSimplify(RexBuilder, RelOptPredicateList, boolean, RexExecutor)` was made deprecated at https://issues.apache.org/jira/browse/CALCITE-2604
and it is recommended
```
* @deprecated Use methods with a {@link RexUnknownAs} argument, such as
* {@link #simplify(RexNode, RexUnknownAs)}. */
```
3. `org.apache.calcite.rel.core.AggregateCall#create(SqlAggFunction, boolean, boolean, boolean, List<Integer>, int, …
> [hotfix] Replace deprecated Calcite's APIs

- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateCheckpointWriterTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateChunkReaderTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateSerializerImplTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestDispatcherImplTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestDispatcherTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestExecutorImplTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriterImplTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/CheckpointInProgressRequestTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/InputChannelRecoveredStateHandlerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/RecordingChannelStateWriter.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/RecoveredChannelStateHandlerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/ResultSubpartitionRecoveredStateHandlerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/SequentialChannelStateReaderImplTest.java
Migrate unaligned checkpoint related tests under flink-runtime module to junit5
Migrate unaligned checkpoint related tests under flink-runtime module to junit5
> [FLINK-30165][runtime][JUnit5 Migration] Migrate unaligned checkpoint related tests under flink-runtime module to junit5

- flink-table/flink-sql-gateway-api/src/main/java/org/apache/flink/table/gateway/api/SqlGatewayService.java
- flink-table/flink-sql-gateway-api/src/test/java/org/apache/flink/table/gateway/api/utils/MockedSqlGatewayService.java
- flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/SqlGatewayServiceImpl.java
- flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/operation/OperationExecutor.java
- flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/utils/Constants.java
- flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/SqlGatewayServiceITCase.java
Implement `SqlGatewayService#completeStatement` described in [FLIP-91](https://cwiki.apache.org/confluence/display/FLINK/FLIP-91%3A+Support+SQL+Gateway).
- Implement `SqlGatewayService#completeStatement`.
- Add test `testCompleteStatement` in `SqlGatewayServiceITCase`.
- `testCompleteStatement` in `SqlGatewayServiceITCase`.
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: **yes** …
> [FLINK-29742][sql-gateway] Support completing statement in SqlGatewayService.

- flink-runtime-web/web-dashboard/src/app/components/flame-graph/flame-graph.component.ts
- flink-runtime-web/web-dashboard/src/app/interfaces/job-flamegraph.ts
- flink-runtime-web/web-dashboard/src/app/pages/job/overview/flamegraph/job-overview-drawer-flamegraph.component.html
- flink-runtime-web/web-dashboard/src/app/pages/job/overview/flamegraph/job-overview-drawer-flamegraph.component.ts
When the flame graph type is switched from On-CPU to Mixed. It still show the graph of On-CPU.
Root cause:
When click the other types, the web frontend will call the requestFlameGraph and update the graphType. However, the graphType is the old type during requestFlameGraph. So the graph type show the new type, but the flame graph is the result of old type.
https://github.com/apache/flink/blob/8bbf52688758bbede45df060a4c11e5fa228b6f0/flink-runtime-web/web-dashboard/src/app/pages/job/overview/flamegraph/job-overview-drawer-flamegraph.component.ts#L82
- The first commit: Using the enum to manage the graphType instead of string
- The second commit: Using the new graph type when request the flameGraph.
- Dependencies …
> [FLINK-30250][web][flame-graph] Fix the bug that show the flame graph of old type

- docs/layouts/shortcodes/generated/rest_v1_dispatcher.html
- docs/static/generated/rest_v1_dispatcher.yml
- flink-runtime-web/src/test/resources/rest_api_v1.snapshot
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/EnvironmentInfo.java
Remove REST APIs for the environmental information.
- remove JobManagerEnvironmentHandler Env Vars
remove jobmanager env handlers
- The public API, i.e., is any changed class annotated with @Public(Evolving): yes
> [FLINK-30116][rest] Don't Show Env Vars in Web UI

- flink-kubernetes/src/main/resources/META-INF/NOTICE
- pom.xml
* Bump snakeyaml
* Updated POM
> [FLINK-30175][Build] Bump snakeyaml from 1.31 to 1.33

- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/HBaseDelegationTokenProvider.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/HadoopDelegationTokenProvider.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/HadoopFSDelegationTokenProvider.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/KerberosDelegationTokenManager.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/ExceptionThrowingHadoopDelegationTokenProvider.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/KerberosDelegationTokenManagerITCase.java
In order to make a generic delegation token manager all authentication specific things must be extracted. This is such a step. In this PR I've moved Kerberos authentication to the provider side.
Moved Kerberos authentication to the provider side.
Existing unit/integration tests + manually on [minikube](https://gist.github.com/gaborgsomogyi/ac4f71ead8494da2f5c35265bcb1e885). …
> [FLINK-30370][runtime][security] Move existing delegation token framework authentication to providers

- docs/content.zh/docs/dev/table/sql/describe.md
- docs/content/docs/dev/table/sql/describe.md
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveTableFactory.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserBaseSemanticAnalyzer.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserSemanticAnalyzer.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserDDLSemanticAnalyzer.java
- flink-table/flink-sql-client/src/test/resources/sql/table.q
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java
- flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/api/TableEnvironmentTest.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/api/TableSchema.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/typeutils/TimeIndicatorTypeInfo.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/catalog/CatalogSchemaTable.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlCreateTableConverter.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlToOperationConverter.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/FlinkCalciteCatalogReader.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/PushPartitionIntoTableSourceScanRule.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/utils/DynamicPartitionPruningUtils.java
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/delegation/PlannerBase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/TableEnvironmentTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/TableSourceTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/table/TableSourceTest.scala
Migrate created table to new schema framework,  so we can make all flink tables including hive table to have new version schema, would bring a lot of benefits like get column comments which make results user-friendly, such as help analysts write sql adaptive to corresponding business logics.
* Migrate to new schema framework then get comment from ResolvedSchema.
flink-table/flink-sql-client/src/test/resources/sql/table.q
TableEnvironmentTest#testDescribeTableWithComment() …
> [FLINK-29679][table] Migrate to new schema framework & show column comment

- flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/ClusterEntrypoint.java
- flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniCluster.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/modules/HadoopModule.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/hadoop/HBaseDelegationTokenProvider.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/hadoop/HadoopDelegationTokenConverter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/hadoop/HadoopDelegationTokenProvider.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/hadoop/HadoopDelegationTokenUpdater.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/hadoop/HadoopFSDelegationTokenProvider.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/hadoop/KerberosDelegationTokenManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/hadoop/KerberosDelegationTokenManagerFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/hadoop/KerberosLoginProvider.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java
- flink-runtime/src/main/resources/META-INF/services/org.apache.flink.runtime.security.token.hadoop.HadoopDelegationTokenProvider
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/hadoop/ExceptionThrowingHadoopDelegationTokenProvider.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/hadoop/HadoopDelegationTokenConverterTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/hadoop/HadoopDelegationTokenUpdaterITCase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/hadoop/HadoopFSDelegationTokenProviderITCase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/hadoop/KerberosDelegationTokenManagerITCase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/hadoop/KerberosLoginProviderITCase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/hadoop/TestHadoopDelegationTokenIdentifier.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/hadoop/TestHadoopDelegationTokenProvider.java
- flink-runtime/src/test/resources/META-INF/services/org.apache.flink.runtime.security.token.hadoop.HadoopDelegationTokenProvider
- flink-runtime/src/test/resources/META-INF/services/org.apache.hadoop.security.token.TokenIdentifier
- flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
At the moment generic and Hadoop parts of the delegation token framework is not separated. In this PR I've separated them both in naming and in package.
Separate token framework generic and hadoop specific parts.
Existing unit/integration tests + manually on [minikube](https://gist.github.com/gaborgsomogyi/ac4f71ead8494da2f5c35265bcb1e885).
- If yes, how …
> [FLINK-30402][security][runtime] Separate token framework generic and hadoop specific parts

- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogWriter.java
- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/StateChangeFormat.java
- flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/BatchingStateChangeUploadSchedulerTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/metadata/MetadataV2V3SerializerBase.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/StateChange.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/StateChangelogWriter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/inmemory/InMemoryStateChangelogWriter.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/AbstractStateChangeLogger.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/StateChangeLoggerTestBase.java
Add explicit append() to StateChangelogWriter to write metadata.
- Add explicit `StateChange(byte[] value)`
- Add explicit `append(byte[] value)`
> [FLINK-23035][state/changelog] Add explicit append() to StateChangelogWriter to write metadata

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java
If source recover from state, we can not distinguish the newPartitions is from timed discover thread or from reader task state.  So add recover log to help to debug and confirm this scenario.  it's very useful for troubleshooting
Add restore split log for SourceOperator.
Not add new cases. Just add log. …
> [FLINK-30424][DataStream API] Add source operator addSplits log when restore from state

- flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/operation/OperationExecutor.java
- flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/utils/Constants.java
- flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/SqlGatewayServiceITCase.java
- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/test/util/TestUtils.java
Support stop job statement in SqlGatewayService. Subtask of FLIP-222.
- *Support stop job statement in SqlGatewayService*
- *Extend SqlGatewayServiceExtension to include a mini cluster for statement execution*
*(example:)*
- *Added integration tests for stop job statements.* …
> [FLINK-28617][SQL Gateway] Support stop job statement in SqlGatewayService

- flink-metrics/flink-metrics-datadog/src/main/java/org/apache/flink/metrics/datadog/DatadogHttpReporter.java
DataDog only considers metrics as coming from Flink if the metric name has "flink" prefix. Otherwise they are considered as custom metrics, governed by different billing rules.
This was so far achieved by the users configuring scope formats as [instructed by DataDog](https://docs.datadoghq.com/integrations/flink/#metric-collection).
Scope formats however don't work for logical identifiers, breaking this behavior.
I manually verified that this prefix results in all metrics being considered as coming from Flink.
> [FLINK-30383][datadog] Add "flink." prefix to logical identifier

- flink-end-to-end-tests/test-scripts/common_kubernetes.sh
```
2022-12-09T08:27:01.3438980Z Dec 09 08:27:01 crictl
2022-12-09T08:27:01.6120044Z fatal: destination path 'cri-dockerd' already exists and is not an empty directory.
2022-12-09T08:27:01.6151912Z fatal: a branch named 'v0.2.3' already exists
2022-12-09T08:27:01.6169151Z mkdir: cannot create directory ‘bin’: File exists
```
This happens when `cri-dockerd` is cloned, but the directory already exists/has been cloned before. This change checks if the directory exists and removes it, before starting the cloning process
* Little bash script that checks if folder already exists
- …
> [FLINK-30355][Kubernetes][Tests] Remove `cri-dockerd` if already cloned earlier

- flink-core/src/main/java/org/apache/flink/util/FatalExitExceptionHandler.java
- flink-core/src/main/java/org/apache/flink/util/concurrent/ThreadUtils.java
It's hard to investigate FLINK-30299. Adding the thread dump might help us identlifying the cause or at least having a pointer what to focus on.
* Introduced new utility class `ThreadUtils` providing a method for generating the thread dump based on Java's MXBean framework 
* Executed (in a unit test) the `FataExitExceptionHandler` and verified the output …
> [FLINK-30299][core] Adds thread dump creation to FatalExitExceptionHandler

- docs/content.zh/docs/dev/configuration/overview.md
- docs/content.zh/docs/dev/datastream/overview.md
- docs/content.zh/docs/dev/datastream/scala_api_extensions.md
- docs/content.zh/docs/dev/table/common.md
- docs/content.zh/docs/learn-flink/datastream_api.md
- docs/content/docs/dev/configuration/overview.md
- docs/content/docs/dev/datastream/overview.md
- docs/content/docs/dev/datastream/scala_api_extensions.md
- docs/content/docs/dev/table/common.md
- docs/content/docs/learn-flink/datastream_api.md
- flink-scala/src/main/scala/org/apache/flink/api/scala/ExecutionEnvironment.scala
- flink-scala/src/main/scala/org/apache/flink/api/scala/package.scala
There is a duplicate `version` in a phrase `All Flink Scala APIs are deprecated and will be removed in a future Flink version version.` The PR removes one extra word.
> [hotfix][misprint] Remove duplicate word `version`

- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/TemporalJoinITCase.scala
This is a minor fix for test data of temporal join, the delete('-D') message should have the same value with corresponding insert('+I') message:
```
changelogRow("+I", "RMB", "no1", 702L, "2020-08-15T00:00:04")
- changelogRow("-D", "RMB", "no1", 708L, "2020-08-16T00:02:00")
+ changelogRow("-D", "RMB", "no1", 702L, "2020-08-16T00:02:00")
```
> [hotfix][table-planner] Fix inconsistent test data for temporal join

- docs/content.zh/docs/connectors/table/jdbc.md
- docs/content/docs/connectors/table/jdbc.md
For flink 1.16 doc.
Link https://issues.apache.org/jira/browse/FLINK-30357.
> [FLINK-30357][doc] Wrong link in connector/jdbc doc. 

- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/PulsarUnorderedSourceITCase.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarUnorderedPartitionSplitReaderTest.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/PulsarSourceUnorderedE2ECase.java
1.15 backport PR for parent PR https://github.com/apache/flink/pull/21478
> [BP-1.15][FLINK-28352][tests] Disable PulsarSourceUnorderedE2ECase, PulsarUnorderedPartitionSplitReaderTest and PulsarUnorderedSourceITCase

- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/PulsarUnorderedSourceITCase.java
- flink-connectors/flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/split/PulsarUnorderedPartitionSplitReaderTest.java
- flink-end-to-end-tests/flink-end-to-end-tests-pulsar/src/test/java/org/apache/flink/tests/util/pulsar/PulsarSourceUnorderedE2ECase.java
1.16 backport PR for parent PR #21478
> [BP-1.16][FLINK-28352][tests] Disable PulsarSourceUnorderedE2ECase, PulsarUnorderedPartitionSplitReaderTest and PulsarUnorderedSourceITCase

- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/snapshot/RocksIncrementalSnapshotStrategy.java
This pull request adds some comments about why snapshot result fo rocksdb native savepoint doesn't have emtry shared-state.
- Add some comments in RocksDBIncrementalSnapshotOperation#get(CloseableRegistry snapshotCloseableRegistry)
> [FLINK-28863][state]Add comments about why snapshot result of RocksDB native savepoint doesn't have empty shared-state

- flink-core/src/main/java/org/apache/flink/configuration/GlobalConfiguration.java
- flink-core/src/test/java/org/apache/flink/configuration/GlobalConfigurationTest.java
https://issues.apache.org/jira/browse/FLINK-30443
Making sure certain sensitive configuration keys don't appear in logs.
Added more sensitive keys to `GlobalConfiguration.SENSITIVE_KEYS`. I acknowledge that those are somewhat specific, OTOH there is precedence with the Azure account key, and things like "token" or "service-key" should generally be not logged. The alternative would be to create an SPI of sorts which would allow to customize the masked keys for specific Flink deployments; I don't think it's worth the effort really, but I'm curious what others here think.
Expanded `GlobalConfigurationTest` accordingly.
- The …
> FLINK-30443 Ensuring more sensitive keys are masked in log output

- flink-runtime-web/src/test/resources/rest_api_v1.snapshot
- flink-runtime-web/web-dashboard/src/app/pages/job/exceptions/job-exceptions.component.html
- flink-runtime-web/web-dashboard/src/app/pages/job/exceptions/job-exceptions.component.ts
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/JobExceptionsHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/JobExceptionsInfo.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/JobExceptionsInfoWithHistory.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/job/JobExceptionsHandlerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/messages/JobExceptionsInfoWithHistoryNoRootTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/messages/JobExceptionsInfoWithHistoryTest.java
At present, the web UI exception history page only displays the TM host and port. However, we generally need to search for problems according to the pod name or container ID.
Therefore, it is more convenient to add resource id (pod name on k8s, container id on yarn) to the location column and a link to the task manager id to jump to the task manager page.
- Exception location contains tm resource id.
- Exception location links to taskManagers UI pages.
This change is already covered by existing tests, such as JobExceptionsHandlerTest. …
> [FLINK-30358][rest] Exception location contains TM resource id and link to TM pages.

- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/harness/RankHarnessTest.scala
Try to fix the long stand unstable test case RankHarnessTest. testUpdateRankWithRowNumberSortKeyDropsToNotLast.
Most probably caused by the unnecessary state ttl of RankHarnessTest which will lead unstable result when execution gets slow (and I checked recent failures, all of their execution duration is greater than 2 second while state ttl in the test is 1 second).
remove unnecessary state ttl of RankHarnessTest
existing tests
- …
> [FLINK-27691][table-planner] Remove unnecessary state ttl to avoid unstable results of RankHarnessTest

- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/harness/RankHarnessTest.scala
this is a back port pr to 1.16 branch for fixing FLINK-27691
> [bp-1.16][FLINK-27691][table-planner] Remove unnecessary state ttl to avoid unstable results of RankHarnessTest

- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/AbstractStateChangeLogger.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogMapState.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/KvStateChangeLoggerImpl.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/PriorityQueueStateChangeLoggerImpl.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/StateChangeLogger.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/StateChangeLoggingIterator.java
- flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/restore/ChangelogMigrationRestoreTarget.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogPqStateTest.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/TestChangeLoggerKv.java
Currently, AbstractStateChangeLogger use sync 
DataOutputViewStreamWrapper to serialize state change which is unnecessary because it will always be executed in single thread.
So replace it with a unsync one could improve the performance of serialization.
In my simple stateful WordCount case, it could improve TPS by 10% at least.
Furthermore, because the serialization and deserialization of key and value have been executed in some delegaed state backend, maybe we could avoid double serialization. It may improve the performance if the serialization logic is complex and even is the bottleneck.
This pr focuses on the sync serializer problem.
The second problem about double serialization could also be disscussed, and I will create a new pr if necessary.
- Replace DataOutputViewStreamWrapper …
> [FLINK-30345][state/changelog] Avoid using sync DataOutputViewStreamWrapper to serialize records to changelog

- flink-runtime-web/web-dashboard/src/app/pages/job/overview/backpressure/job-overview-drawer-backpressure.component.html
- flink-runtime-web/web-dashboard/src/app/pages/job/overview/backpressure/job-overview-drawer-backpressure.component.ts
Currently, the sort order is ascend by default, it should be descend.
The most busy subtask should be displayed on top.
- Change the SortOrder of BusyRatio to descend by default.
- Don't change the order of `listOfSubTaskBackpressure`, it will sort by subtask when the user chooses not to sort. …
> [FLINK-30468][web] Change the SortOrder of BusyRatio to descend by default

- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/writer/ChannelSelectorRecordWriter.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/NonChainedOutput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamConfigChainer.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskFinalCheckpointsTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskMailboxTestHarnessBuilder.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
In case of parallelism changes to the JobGraph, as done via the AdaptiveScheduler or through providing JobVertexId overrides in PipelineOptions#PARALLELISM_OVERRIDES, the inner serialized PartitionStrategy of a StreamTask may not be suitable anymore.
This is the case for the ForwardPartitioner strategy which uses a fixed local channel for transmitting data. Whenever the consumer parallelism doesn't match the local parallelism, we should be replacing it with the RebalancePartitioner.
> [FLINK-30213] Change ForwardPartitioner to RebalancePartitioner on parallelism changes

- flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinatorHolder.java
- flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/SubtaskGatewayImpl.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinatorHolderTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/CoordinatorEventsToStreamOperatorRecipientExactlyOnceITCase.java
This pull request removes the guarantee of the consistency of OperatorEvents sent from OperatorCoordinator to its subtasks in case of concurrent checkpoints. This pull request provides a quick fix for the mismatch between OperatorCoordinator's description and its actual behavior. The background information can be found at FLINK-29217.
- Modify the JavaDoc and remove the tests about OperatorCoordinator's behavior in case of concurrent checkpoints.
This change is already covered by existing tests. The test cases related to the OperatorCoordinator's behavior in face of concurrent checkpoints have been removed to match with the expected behavior.
- The …
> [FLINK-29217][Runtime/Checkpointing] Remove OC's guarantee for OperatorEvent on concurrent checkpoints

- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNSessionCapacitySchedulerITCase.java
Removes timeout configuration for `YARNSessionCapacitySchedulerITCase` to enable thread dump creation by watchdog process.
* Removes timeout information
> [FLINK-30539][tests] Removes timeout from YARNSessionCapacitySchedulerITCase

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserDDLSemanticAnalyzer.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/AlterTableChangeOperation.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/TableChange.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/expressions/ColumnReferenceFinder.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/AlterSchemaConverter.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlToOperationConverter.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/utils/OperationConverterUtils.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/expressions/ColumnReferenceFinderTest.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlToOperationConverterTest.java
*Introduce TableChange to represent DROP syntax.*
This change is already covered by existing tests, such as *SqlToOperationConverterTest*.
- If yes, how is the feature documented? (not applicable / docs / **JavaDocs** / …
> [FLINK-30497][table-api] Introduce TableChange to represent DROP change

- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java
Fix metric override each other. The method SchedulerBase#registerJobMetrics register metrics 'numRestarts' and 'fullRestarts' with the same metric object, which will result in the loss of the metric 'numRestarts'. 
avoid metric 'numRestarts' being overridden by 'fullRestarts'  …
> [FLINK-30558][runtime] Use different metric object to avoid metric 'numRestarts' being overridden by 'fullRestarts' in SchedulerBase

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/watermarkstatus/StatusWatermarkValve.java
Currently, every time a task receives a watermark, it tries to update the minimum watermark. In current implementation, we use the traversal algorithm to find the minimum watermark across all channels(see `StatusWatermarkValue#findAndOutputNewMinWatermarkAcrossAlignedChannels` for details), and the time complexity is `O(N)`, where `N` is the number of channels.
In this pr, we optimize it by introducing a heap-based algorthim, reducing the time complexity to `O(log(N))`
This change is already covered by the `StatusWatermarkValveTest`
- …
> [FLINK-30544][runtime] Speed up finding minimum watermark across channels by introducing heap-based algorithm

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperatorV2.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/CountingOutput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/ChainingOutput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/CopyingChainingOutput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/OperatorChain.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/OperatorChainTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorTest.java
This PR reduces the Flink runtime overhead by reducing the call stack depth needed to produce a record. This is achieved by adding a Counter in the ChainingOutput instead of adding a CountingOutput that wraps around ChainingOutput.
- Updated `AbstractStreamOperator` so that it no longer adds a `CountingOutput` that wraps around the given output.
- Updated `AbstractStreamOperatorV2` so that it no longer adds a `CountingOutput` that wraps around the given output.
- Updated `OperatorChain` and `ChainingOutput` so that ChainingOutput would create a Counter that maintains the number of records emitted from the operator on the operator chain.
```
DataStream<Long> stream = env.fromSequence(1, 500000000L);
for (int i = 0; i < 10; i++) {
stream = stream.map(x -> x);
}
stream.addSink(new …
```
> [FLINK-30536][runtime] Remove CountingOutput from per-record code path for most operators

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/SqlClient.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliChangelogResultView.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliClient.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliResultView.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliTableResultView.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliTableauResultView.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/SqlCompleter.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/parser/SqlCommandParserImpl.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/Executor.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/local/LocalExecutor.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientITCase.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientTest.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliResultViewTest.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliTableauResultViewTest.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/TestingExecutor.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/local/DependencyTest.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/local/LocalExecutorITCase.java
*Remove useless sessionId in the Executor. The SQL Gateway uses the `SessionHandle` to identify each Session and the `SessionHandle` is assigned by the Gateway only. The `Executor` in the SqlClient is the client to submit messages to the 
Gateway and it is only used by the current Session. We don't need to use the sessionId everywhere.* …
> [FLINK-30554][sql-client] Remove useless sessionId in the Executor

- flink-connectors/flink-connector-files/archunit-violations/f5e3e868-8d92-4258-9654-a605dc9c550f
- flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/sink/writer/FileSinkMigrationITCase.java
- flink-end-to-end-tests/flink-file-sink-test/src/main/java/org/apache/flink/connector/file/sink/FileSinkProgram.java
- flink-end-to-end-tests/flink-stream-sql-test/pom.xml
- flink-end-to-end-tests/flink-stream-sql-test/src/main/java/org/apache/flink/sql/tests/StreamSQLTestProgram.java
- flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroStreamingFileSinkITCase.java
- flink-formats/flink-compress/pom.xml
- flink-formats/flink-compress/src/test/java/org/apache/flink/formats/compress/CompressionFactoryITCase.java
- flink-formats/flink-orc/src/test/java/org/apache/flink/orc/writer/OrcBulkWriterITCase.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/avro/AvroParquetStreamingFileSinkITCase.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/protobuf/ParquetProtoStreamingFileSinkITCase.java
- flink-formats/flink-sequence-file/pom.xml
- flink-formats/flink-sequence-file/src/test/java/org/apache/flink/formats/sequencefile/SequenceStreamingFileSinkITCase.java
Reverts apache/flink#21371 due to [FLINK-30605](https://issues.apache.org/jira/browse/FLINK-30605)
> Revert "[FLINK-30166][Connector/FileSystem] Refactor tests that use the deprecated StreamingFileSink instead of FileSink"

- pom.xml
This PR aims to publish SBOM artifacts.
Here is an article to give some context.
- https://www.activestate.com/blog/why-the-us-government-is-mandating-software-bill-of-materials-sbom/
Software Bill of Materials (SBOM) are additional artifacts containing the aggregate of all direct and transitive dependencies of a project. The US Government (based on NIST recommendations) currently accepts only the three most popular SBOM standards as valid, namely: [CycloneDX](https://cyclonedx.org/), [Software Identification (SWID) tag](https://csrc.nist.gov/projects/Software-Identification-SWID), [Software Package Data Exchange® (SPDX)](https://spdx.dev/).
This PR uses [CycloneDX maven plugin](https://github.com/CycloneDX/cyclonedx-maven-plugin), a lightweight software bill of materials (SBOM) standard …
> [FLINK-30578][build] Publish SBOM artifacts

- flink-connectors/flink-connector-hive/pom.xml
- flink-table/flink-sql-client/pom.xml
* Exclude `org.pentaho:pentaho-aggdesigner-algorithm` from the Hive dependencies to avoid users with newer Maven versions having issues to build Flink locally. 
* Excluded `org.pentaho:pentaho-aggdesigner-algorithm` in Hive connector pom.xml …
> [FLINK-27640][Connector/Hive] Exclude Pentaho dependency from Hive

- flink-table/flink-table-planner-loader/src/main/java/org/apache/flink/table/planner/loader/PlannerModule.java
- flink-table/flink-table-planner-loader/src/test/java/org/apache/flink/table/planner/loader/LoaderITCase.java
sql-client leaks flink-table-planner jar in /tmp. Fix the leak by removing on exists 
without patch 
```
[root@ip-172-1-1-3 lib]# ls -lrt /tmp/flink-table-planner_*
-rw-rw-r-- 1 hadoop hadoop 39138893 Dec 12 10:08 /tmp/flink-table-planner_acada33f-a10b-4a4a-ad16-6bca25a67e10.jar
-rw-rw-r-- 1 hadoop hadoop 39138893 Dec 12 10:17 /tmp/flink-table-planner_fb2f6e31-48a0-4c1e-ab7b-16129e776125.jar
-rw-rw-r-- 1 hadoop hadoop 39138893 Dec 12 10:22 /tmp/flink-table-planner_83499393-1621-43de-953c-2000bc6967ce.jar
-rw-rw-r-- 1 hadoop hadoop 39138893 Dec 12 10:24 /tmp/flink-table-planner_3aa798da-e794-4c6c-ad9f-49b4574da64b.jar
-rw-rw-r-- 1 hadoop hadoop 39138893 Dec 12 10:36 /tmp/flink-table-planner_ea52d9ea-3148-4fc3-8a58-f83063bb14d5.jar
-rw-rw-r-- 1 hadoop hadoop 39138893 Dec 12 10:44 …
```
> [FLINK-30375][hotfix]sql-client leaks flink-table-planner jar in /tmp

- flink-connectors/flink-connector-hive/pom.xml
- exclude unused package causing maven 3.8.6 build failure
- exclude unused package causing maven 3.8.6 build failure
> [FLINK-27640][Connector/Hive][SQL Client] Exclude Pentaho dependency

- flink-end-to-end-tests/test-scripts/common.sh
- flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniCluster.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/DefaultDelegationTokenManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/DelegationTokenProvider.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/DelegationTokenReceiver.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/DelegationTokenReceiverRepository.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/hadoop/HBaseDelegationTokenProvider.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/hadoop/HBaseDelegationTokenReceiver.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/hadoop/HadoopDelegationTokenReceiver.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/hadoop/HadoopFSDelegationTokenProvider.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/hadoop/HadoopFSDelegationTokenReceiver.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerRunner.java
- flink-runtime/src/main/resources/META-INF/services/org.apache.flink.runtime.security.token.DelegationTokenReceiver
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/DefaultDelegationTokenManagerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/DelegationTokenReceiverRepositoryTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/ExceptionThrowingDelegationTokenReceiver.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/TestDelegationTokenReceiver.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/hadoop/HadoopDelegationTokenReceiverITCase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorBuilder.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorExecutionDeploymentReconciliationTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorPartitionLifecycleTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorSlotLifetimeTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskManagerRunnerStartupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskManagerRunnerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskSubmissionTestEnvironment.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TestingTaskExecutor.java
- flink-runtime/src/test/resources/META-INF/services/org.apache.flink.runtime.security.token.DelegationTokenReceiver
- flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
Flink delegation token obtain side is generic already but on the receiver side there is still an assumption that only Hadoop tokens can come. In this PR I've introduced `DelegationTokenReceiver` interface which can be implemented by every.
* Added `DelegationTokenReceiver` interface
* Added `HadoopFSDelegationTokenReceiver` for Hadoop FS
* Added `HBaseDelegationTokenReceiver` for HBase
* Added `DelegationTokenReceiverRepository` which loads all receivers, and propagates new tokens to them
* New/updated automated tests
Existing/new unit/integration tests + manually on [minikube](https://gist.github.com/gaborgsomogyi/ac4f71ead8494da2f5c35265bcb1e885). …
> [FLINK-30425][runtime][security] Generalize token receive side

- flink-connectors/flink-connector-aws-base/pom.xml
- flink-end-to-end-tests/flink-glue-schema-registry-avro-test/pom.xml
- flink-end-to-end-tests/flink-glue-schema-registry-json-test/pom.xml
- flink-formats/flink-avro-glue-schema-registry/pom.xml
- flink-formats/flink-json-glue-schema-registry/pom.xml
Update AWS SDKv2 to v2.19.14
- Update AWS SDKv2 to v2.19.14
> [FLINK-30633][Connectors/AWS] Update AWS SDKv2 to v2.19.14 for Flink 1.17

- docs/README.md
- docs/setup_docs.sh
Remove all the Hugo Modules integration
Clean-up
> [FLINK-27731][Documentation][Build] Remove Hugo Modules integration

- pom.xml
[FLINK-24273](https://issues.apache.org/jira/browse/FLINK-24273) proposes to relocate the io.fabric8 dependencies of flink-kubernetes.
This is not possible because of a problem with the maven shade plugin ("mvn install" doesn't work, it needs to be "mvn clean install").
[MSHADE-425](https://issues.apache.org/jira/browse/MSHADE-425) solves this issue, and has been released with maven-shade-plugin 3.4.0.
Upgrading the shade plugin will solve the problem, unblocking the K8s relocation.
- bump the version.
Covered by CI
- The runtime per-record code paths (performance sensitive): (yes / no / …
> [FLINK-30083] Bump maven-shade-plugin version

- docs/content/docs/dev/table/concepts/determinism.md
This is a trivial change to fix the broken link in page [determinism/#3-determinism-in-streaming-processing](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/concepts/determinism/#3-determinism-in-streaming-processing)
- Fix broken links in determinism.md
This change is a trivial fix and can be verified by building the docs locally at http://localhost:1313/ …
> [hotfix][docs][table] Fix broken links in determinism.md

- flink-connectors/flink-sql-connector-elasticsearch6/pom.xml
- flink-connectors/flink-sql-connector-elasticsearch6/src/main/resources/META-INF/NOTICE
*flink-sql-connector-elasticsearch6's jar should include the dependency of com.carrotsearch:hppc*
- *Remove the exclude of hppc and shade it.*
> [BP-1.16][FLINK-30359][es] flink-sql-connector-elasticsearch6's jar should include the dependency of com.carrotsearch:hppc

- pom.xml
Minor quality of life improvement. Enabling the fast profile now yields e.g. the following in the log:
```
[INFO] --- cyclonedx-maven-plugin:2.7.3:makeBom (default) @ flink-metrics-core ---
[INFO] Skipping CycloneDX
```
> [FLINK-30704][build] Skip SBOM creation in fast profile

- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionTest.java
*Fix flaky test `SortMergeResultPartitionTest#testRelease`*
- *Fix flaky test SortMergeResultPartitionTest.testRelease.*
This change is a fix for flaky test.
> [FLINK-29884][test] Fix flaky test SortMergeResultPartitionTest.testRelease

- docs/content.zh/docs/dev/datastream/event-time/generating_watermarks.md
- docs/content/docs/dev/datastream/event-time/generating_watermarks.md
Update the doc of kafka-per-partition watermark to the new source.
Update the doc of kafka-per-partition watermark to the new source.
> [FLINK-30724][docs] Update kafka-per-partition watermark to new source

- docs/content/docs/deployment/security/security-kerberos.md
Delegation token providers can be turned off with [`security.delegation.token.provider.{serviceName}.enabled`](https://github.com/apache/flink/blob/b35cef5997568d75611307d11fca0dec415f99b4/flink-runtime/src/main/java/org/apache/flink/runtime/security/token/DefaultDelegationTokenManager.java#L151-L154). The documentation however still contains the old config. In this PR I've fixed the doc.
Doc fix.
No need any test. …
> [FLINK-30749][security][runtime] Fix delegation token provider enabled flag documentation

- docs/config.toml
- docs/layouts/shortcodes/sql_connector_download_table.html
- docs/setup_docs.sh
Adds a new shortcode for generating the sql download table for externalized connectors.
Further decouples the Flink/connector docs by no longer relying on docs/data/sql_connectors.yml.
Usage:
```
some_document.md:
{{< sql_connector_download_table_v2 "elasticsearch" 3.0.0 >}}
docs/data/elasticsearch.yml:
variants:
- maven: flink-connector-elasticsearch6
sql_url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-elasticsearch6/$full_version/flink-sql-connector-elasticsearch6-$full_version.jar
- maven: flink-connector-elasticsearch7
sql_url: https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-elasticsearch7/$full_version/flink-sql-connector-elasticsearch7-$full_version.jar
```
@dannycranmer You may be interested in this one.
> [FLINK-30378][docs] Add v2 sql_connector_download_table shortcode 

- docs/content.zh/docs/deployment/config.md
- docs/content.zh/docs/deployment/security/security-delegation-token.md
- docs/content/docs/deployment/config.md
- docs/content/docs/deployment/security/security-kerberos.md
- docs/layouts/shortcodes/generated/optimizer_config_configuration.html
- docs/layouts/shortcodes/generated/security_configuration.html
- docs/layouts/shortcodes/generated/security_delegation_token_section.html
- flink-core/src/main/java/org/apache/flink/configuration/SecurityOptions.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/DefaultDelegationTokenManager.java
Until now the generic delegation token params are not shown on the main config page. In this PR I've added them.
Included generic delegation token params in the main config page.
Existing tests + manually checked the generated page.
> [FLINK-30764][docs] Include generic delegation token params in the main config page

- docs/layouts/shortcodes/generated/kubernetes_config_configuration.html
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/configuration/KubernetesConfigOptions.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/factory/KubernetesJobManagerFactory.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/factory/KubernetesTaskManagerFactory.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/factory/KubernetesJobManagerFactoryTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/factory/KubernetesTaskManagerFactoryTest.java
Hadoop related k8s decorators are making a lot of assumptions. There are some users who mount Hadoop specific things (like Hadoop config, Kerberos config/keytab) in a custom way and not depending on Flink. In this PR I've added Hadoop related k8s decorators exclude possibility not to fail those use-cases.
* Added Hadoop related k8s decorators exclude possibility
* Added automated tests
New unit tests.
- …
> [FLINK-30713][k8s] Add Hadoop related k8s decorators exclude possibility

- flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/TableFactoryService.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/logical/utils/LogicalTypeCasts.java
The PR removes 2 private unused methods from `flink-table-common`
`org.apache.flink.table.factories.TableFactoryService#filterSupportedPropertiesFactorySpecific` The usage was removed at https://github.com/apache/flink/commit/8212230414f0c49a9f5b636bfc5101417e921a66#diff-b95578386c94cdc85a50a5514cbf34e3a5964eac6b9c71c2e22a810bf142bc9aL392-L393
`explicitNotFromFamily` from `org.apache.flink.table.types.logical.utils.LogicalTypeCasts` The usage was removed at 
https://github.com/apache/flink/commit/7dc419342779d08f6c1ae6adf42e58bdc6056971
- The …
> [hotfix][table-common] Remove unused private methods

- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionService.java
The @GuardedBy annotations were assigned to some public methods which are not called under the specified lock. @GuardedBy should be used by methods that are only allowed to be called within the context of the lock that is specified in the annotation.
This is a preparation task for FLINK-26522/FLIP-285 where introduce new internal methods that actually need to be properly annotated by the `@GuardedBy` annotation.
* removes the annotations in methods that are called outside of the lock
- …
> [FLINK-30760][runtime] Fixes wrongly used @GuardedBy annotation

- flink-clients/src/test/java/org/apache/flink/client/program/StreamContextEnvironmentTest.java
- flink-core/src/main/java/org/apache/flink/api/common/ExecutionConfig.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/translators/SinkTransformationTranslator.java
> [FLINK-30278][streaming] Unset parallelism in the SinkTransformationTranslator if it wasn't set before

- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/DescriptiveStatisticsHistogramStatistics.java
- flink-tests/src/test/java/org/apache/flink/test/state/TaskManagerWideRocksDbMemorySharingITCase.java
Fix unstable `TaskManagerWideRocksDbMemorySharingITCase` by using standard deviation of memory usage
instead of `max-min` of each iteration.
`TaskManagerWideRocksDbMemorySharingITCase` uses RocksDB metrics per task to verify that they are actually using the same underlying RocksDB shared resources (block cache and write buffer manager):
despite of (intentionally) varying speed of state size change, the metrics should report the same.
However, metric collection isn't synchronous across tasks, and also doesn't guarantee cross-thread visibility (for performance reasons). This causes the test to fail sometimes.
This PR tries to fix the test by collecting standard deviation across multiple rounds (100) and then verifying that percentiles are withing the bounds (found empirically).
> [FLINK-30328][tests] Assert memory usage deviation is within bounds instead of min/max

- flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/Catalog.java
Fix typo in Catalog interface
Fix typo in javadocs 
- Dependencies (does it add or upgrade a dependency):  no 
- Does this pull request introduce a new feature? (yes / no) no 
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) no
> [hotfix][javadocs]Fix javadoc in Catalog Interface

- flink-python/pom.xml
* Since there are no SNAPSHOTs created for connectors, lookup to SNAPSHOT versions of connector in Flink itself should not be present
* Changed Python reference to Pulsar connector to release version …
> [FLINK-30618][Python] Remove SNAPSHOT reference to Pulsar connector

- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/DefaultDelegationTokenManagerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/DelegationTokenReceiverRepositoryTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/ExceptionThrowingDelegationTokenProvider.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/ExceptionThrowingDelegationTokenReceiver.java
At the moment tests using `ExceptionThrowingDelegationTokenProvider` and `ExceptionThrowingDelegationTokenReceiver` are not thread safe because of the static variables. In this PR I've fixed them.
Fixed ExceptionThrowingDelegationTokenProvider/Receiver multi-threaded test issues.
Existing unit tests are working fine with maven multi-threaded run.
- If …
> [FLINK-30754][tests] Fix ExceptionThrowingDelegationTokenProvider/Receiver multi-threaded test issues

- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/ClientTransportErrorHandlingTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyTestUtil.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/ServerTransportErrorHandlingTest.java
This fix initializes test netty server in the loop in order to decrease probability of `Address already in use` problem.
- *Initializing test netty server and client in the loop to avoid the probability of `Address already in use` problem.*
It is a test itself …
> [FLINK-26082][runtime] Initializing test netty server and client in the loop to avoid the probability of `Address already in use` problem.

- flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskTest.java
This change fixes the bug in a test which trigger the latch for the current test from the remaining thread of the previous test.
- *The static latches in TaskTest were replaced by latches from invokable objects in order to avoid accidental sharing latches between multiple tests*
It is a test …
> [FLINK-15550][runtime] The static latches in TaskTest were replaced by latches from invokable objects. 

- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecSink.java
* modifies `applySinkProvider` function to accept clssloader 
* use the classloader to set context for current thread in `applySinkProvider`
```
/usr/lib/flink/bin/sql-client.sh -j /usr/lib/hudi/hudi-flink-bundle.jar
Setting HBASE_CONF_DIR=/etc/hbase/conf because no HBASE_CONF_DIR was set.
Using the result of 'hadoop classpath' to augment the Hadoop classpath: /etc/hadoop/conf:/usr/lib/hadoop/lib/*:/usr/lib/hadoop/.//*:/usr/lib/hadoop-hdfs/./:/usr/lib/hadoop-hdfs/lib/*:/usr/lib/hadoop-hdfs/.//*:/usr/lib/hadoop-mapreduce/.//*:/usr/lib/hadoop-yarn/lib/*:/usr/lib/hadoop-yarn/.//*:/etc/tez/conf:/usr/lib/tez/hadoop-shim-0.10.2-amzn-0.jar:/usr/lib/tez/hadoop-shim-2.8-0.10.2-amzn-0.jar:/usr/lib/tez/lib:/usr/lib/tez/LICENSE:/usr/lib/tez/LICENSE-BSD-3clause:/usr/lib/tez/LICENSE-CDDLv1.1-GPLv2_withC …
```
> [FLINK-30377][table-planner] applySinkProvider use ClientWrapperClassLoader while extracting Type from KeyedStream

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveLookupTableSource.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveLookupJoinITCase.java
Can not load the data of hive dim table when project-push-down is introduced.
IndexOutOfBoundsException for Hive lookup join when column pushdown to Hive lookup table source.
> [FLINK-30679][hive]Fix IndexOutOfBoundsException for Hive lookup join when column pushdown to Hive lookup table source

- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/PushProjectIntoTableSourceScanRule.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/rules/logical/PushProjectIntoTableSourceScanRuleTest.java
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/TableSourceTest.xml
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/agg/HashAggregateTest.xml
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/agg/SortAggregateTest.xml
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/PushProjectIntoTableSourceScanRuleTest.xml
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/TableScanTest.xml
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/TableSourceTest.xml
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/agg/AggregateTest.xml
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/agg/AggregateTestBase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/agg/AggregateTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/AggregateITCaseBase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/AggregateITCase.scala
Current `PushProjectIntoTableSourceScanRule` doesn't process the case properly when no column is needed from source logically, it will generagte a plan that selects nothing from a source (which supports projection push down) , this will not work with real connectors.
In this pr we will always choose the first (physical) column from the source in such a case (Note that `LegacyTableSource` is not fixed since it is deprecated so long)
Fix PushProjectIntoTableSourceScanRule to always choose the first (physical) column from the source when no column is needed from source logically
newly added countStar related cases in AggregateTest、AggregateITCase (both streaming and batch modes covered) …
> [FLINK-29558][table-planner] Fix projection pushdown rule select nothing from source when no column is needed logically

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveLookupTableSource.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveLookupJoinITCase.java
Can not load the data of hive dim table when project-push-down is introduced.
IndexOutOfBoundsException for Hive lookup join when column pushdown to Hive lookup table source.
> [BP-1.15][FLINK-30679][connectors/hive] Fix IndexOutOfBoundsException for Hive lookup join when column pushdown to Hive lookup table source

- flink-end-to-end-tests/run-nightly-tests.sh
- tools/ci/maven-utils.sh
This draft adds dmesg to the `test_controller.sh` to check whether it would work on Alibaba instances to determine whether FLINK-13978 is the cause for the error in the e2e tests.
> [FLINK-30787][ci] Removes dmesg code since it's failing constantly

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperatorTest.java
There's an issue in AsyncWaitOperator that it not properly blocking retries when timeout occurs, reported by user ml https://lists.apache.org/thread/n1rqml8h9j8zkhxwc48rdvj7jrw2rjcy. This happens when a retry timer is unfired and then the user function timeout was triggered first, the current RetryableResultHandlerDelegator doesn't take the timeout process properly and will cause more unexpected retries. This pr aims to fix it.
Overwrite the timeout logic in RetryableResultHandlerDelegator and add guard for retryAwaiting flag to prevent unexpected retries.
add case to current AsyncWaitOperatorTest …
> [FLINK-30477][datastream] Fix AsyncWaitOperator that not properly blocking retries when timeout occurs

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveLookupTableSource.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveLookupJoinITCase.java
Can not load the data of hive dim table when project-push-down is introduced.
IndexOutOfBoundsException for Hive lookup join when column pushdown to Hive lookup table source.
> [BP-1.14][FLINK-30679][connectors/hive] Fix IndexOutOfBoundsException for Hive lookup join when column pushdown to Hive lookup table source

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveLookupTableSource.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveLookupJoinITCase.java
Can not load the data of hive dim table when project-push-down is introduced.
IndexOutOfBoundsException for Hive lookup join when column pushdown to Hive lookup table source.
> [BP-1.16][FLINK-30679][connectors/hive] Fix IndexOutOfBoundsException for Hive lookup join when column pushdown to Hive lookup table source

- docs/content.zh/docs/connectors/table/hive/hive_read_write.md
- docs/content/docs/connectors/table/hive/hive_read_write.md
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/FileSystemConnectorOptions.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/batch/BatchSink.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/batch/compact/BatchCompactCoordinator.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/batch/compact/BatchCompactOperator.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/stream/compact/CompactOperator.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/utils/CompactFileUtils.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveDynamicTableFactory.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveOptions.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveTableSink.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableCompactSinkITCase.java
Introduce auto compaction for Hive sink in batch mode
- Introduce options `compaction.small-files.avg-size`/`compaction.file-size`/`compaction.parallelism` for auto compaction 
- when autom compaction is enabled,  create a topology containing `BatchFileWriter` -> `BatchCompactCoordinator`  ->  `BatchCompactOperator` -> `BatchPartitionCommitter` which will support auto compaction.
- Extract the common logic of compact files from `BatchCompactOperator` and `CompactOperator` to `CompactFileUtils#doCompact`.
Added ITCase in `HiveTableCompactSinkITCase`. …
> [FLINK-29880][hive] Introduce auto compaction for Hive sink in batch mode

- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecLookupJoin.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecLookupJoin.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecLookupJoin.java
The `StreamExecLookupJoin` node adds support for `upsertMaterialize` since 1.16 and it should be a `MultipleTransformationTranslator`. For the `BatchExecLookupJoin`, it does not change because no `upsertMaterialize` support in batch mode.
This hotfix aims to correct the class signature.
> [hotfix][table-planner] Correct StreamExecLookupJoin from SingleTransformationTranslator to MultipleTransformationTranslator

- flink-metrics/flink-metrics-slf4j/src/main/java/org/apache/flink/metrics/slf4j/Slf4jReporter.java
- flink-metrics/flink-metrics-slf4j/src/test/java/org/apache/flink/metrics/slf4j/Slf4jReporterTest.java
The e2e logs are more noisy then they need to be because the slf4j reporter logs a lot of lines even if no metrics (of a particular type) are registered.
Full skip:
Before:
```
=========================== Starting metrics report ===========================
-- Counters -------------------------------------------------------------------
-- Gauges ---------------------------------------------------------------------
-- Meters ---------------------------------------------------------------------
-- Histograms -----------------------------------------------------------------
=========================== Finished metrics report ===========================
```
After:
```
Skipping metrics report because no metrics are registered.
```
Partial skip:
Before:
```
=========================== Starting …
```
> [FLINK-30796][metrics][slf4j] (Partially) skip metrics report

- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/catalog/CatalogTableITCase.scala
Enable `CatalogTableITCase#testAlterTable`.
Remove `@Ignore`.
- Does this pull request introduce a new feature? No
- If yes, how is the feature documented? Not Applicable
> [FLINK-30848][table-planner] Enable CatalogTableITCase#testAlterTable

- flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/operation/OperationExecutor.java
Currently, the stop-job operation produces some verbose error msg and doesn't handle exceptions in stop-without-savepoint gracefully.
This PR fixes the problem.
- Wrap simple cancel with try-catch.
- Wait for simple cancel Acknowledge before returning 'OK'.
- Simplify exception message for stop job operations. …
> [FLINK-30538][SQL gateway/client] Improve error handling of stop job operation

- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultMultipleComponentLeaderElectionService.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultMultipleComponentLeaderElectionServiceTest.java
Previous to this fix, different components could have used different session IDs even though they belonged to the same session. It still puzzles me that this never appeared in any bug report. Wrong session IDs should have caused messages being rejected.
* Fixed the bug in `DefaultMultipleComponentLeaderElectionService`
* Added test case to cover this issue …
> [FLINK-30462][runtime] The leader session ID is now saved properly

- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultMultipleComponentLeaderElectionService.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultMultipleComponentLeaderElectionServiceTest.java
Previous to this fix, different components could have used different session IDs even though they belonged to the same session.
1.16 backport PR of parent PR #21537
> [BP-1.16][FLINK-30462][runtime] The leader session ID is now saved properly

- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultMultipleComponentLeaderElectionService.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultMultipleComponentLeaderElectionServiceTest.java
Previous to this fix, different components could have used different session IDs even though they belonged to the same session.
1.15 backport PR of parent PR https://github.com/apache/flink/pull/21537
> [BP-1.15][FLINK-30462][runtime] The leader session ID is now saved properly

- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultMultipleComponentLeaderElectionService.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultMultipleComponentLeaderElectionServiceTest.java
LeaderElectionEventHandler.onLeaderInformationChange should only be called if the handler (i.e. DefaultLeaderElectionService) is actually the leader. This check is already implemented in the corresponding calling methods of the MultipleComponentLeaderElectionDriver implementations. But these methods only schedule the logic rather than executing it right away. The execution is handled in a separate thread (i.e. DefaultMultipleComponentLeaderElectionService#leadershipOperationExecutor). That might create a race condition if a leader change is queued up already but not performed, yet, before the leader information change event gets queued up as well.
1.15 backport PR of parent PR #21537
> [BP-1.15][FLINK-30474][runtime] Propagates leader information change only if the leadership is still acquired

- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultMultipleComponentLeaderElectionService.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultMultipleComponentLeaderElectionServiceTest.java
LeaderElectionEventHandler.onLeaderInformationChange should only be called if the handler (i.e. DefaultLeaderElectionService) is actually the leader. This check is already implemented in the corresponding calling methods of the MultipleComponentLeaderElectionDriver implementations. But these methods only schedule the logic rather than executing it right away. The execution is handled in a separate thread (i.e. DefaultMultipleComponentLeaderElectionService#leadershipOperationExecutor). That might create a race condition if a leader change is queued up already but not performed, yet, before the leader information change event gets queued up as well.
1.16 backport PR of parent PR #21537
> [BP-1.16][FLINK-30474][runtime] Propagates leader information change only if the leadership is still acquired

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperatorTest.java
This is a backport pr of FLINK-30477 to release-1.16
> [bp-1.16][FLINK-30477][datastream] Fix AsyncWaitOperator that not properly blocking retries when timeout occurs

- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultMultipleComponentLeaderElectionService.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultMultipleComponentLeaderElectionServiceTest.java
This reverts commit fd4f918bbaa6f3fb1876dc90d9528d190b98a2f7.
See FLINK-30878 for analysis. PR #21537 caused this.
Reverting the FLINK-30474 change.
- If yes, how is the feature documented?not applicable
> [FLINK-30878][runtime] Revert "[FLINK-30474][runtime] Propagates leader information change only if the leadership is still acquired"

- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultMultipleComponentLeaderElectionService.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultMultipleComponentLeaderElectionServiceTest.java
This reverts commit ce38381c15ee83fad782677d51b10941c843b82e. The correlated PR on `master` is #21830.
See FLINK-30878 for analysis. PR #21818 caused this.
Reverting the FLINK-30474 change.
- If yes, how is the feature documented?not applicable
> [BP-1.15][FLINK-30878][runtime] Revert "[FLINK-30474][runtime] Propagates leader information change only if the leadership is still acquired"

- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultMultipleComponentLeaderElectionService.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultMultipleComponentLeaderElectionServiceTest.java
This reverts commit edaa148fcfa6ae427af8d840032903817b8ea5ef. The correlated PR on `master` is #21830.
See [FLINK-30878](https://issues.apache.org/jira/browse/FLINK-30878) for analysis. PR #21819 caused this.
Reverting the [FLINK-30474](https://issues.apache.org/jira/browse/FLINK-30474) change. …
> [BP-1.16][FLINK-30878][runtime] Revert "[FLINK-30474][runtime] Propagates leader information change only if the leadership is still acquired"

- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/join/JoinReorderITCase.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/utils/JoinReorderITCaseBase.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/utils/StatisticsReportTestBase.java
…insufficient while the default parallelism don't set manually in test
This pr is aims to fix IOException due to network buffer insufficient for jira: [https://issues.apache.org/jira/projects/FLINK/issues/FLINK-30727?filter=allopenissues](url).  This error is caused by some ITCase neither extends `StreamingTestBase`/`BatchTestBase`  nor sets the default parallelism manually in ITCase.  
Modify ITCase  base `JoinReorderITCaseBase` and `StatisticsReportTestBase`.
I run `mvn verify` with this pr in a machine with high cpu cores many times. The result is stable.
- …
> [hotfix][table-planner] Fix ITCase IOException due to network buffer insufficient while the default parallelism don't set manually in test

- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/CachingLookupFunction.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/fullcache/CacheLoader.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/fullcache/LookupFullCache.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/fullcache/inputformat/InputFormatCacheLoader.java
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/functions/table/fullcache/LookupFullCacheTest.java
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/functions/table/fullcache/inputformat/InputFormatCacheLoaderTest.java
> The analysis below was initially made by @SmirAlex in #21365
This pull-request *tries to fix* unstable test `LookupJoinITCase` (error was not succeeded to be reproduced locally). An error contains the message 'Trying to access closed classloader'. However, test configured in the way that it loads cache only one time, and we wait until the end of this load in `LookupFullCache#open`. So `LookupFullCache#close` shouldn't somehow affect on cache load thread, if we assume that `close` is called only after `open`. 
During debugging it was found out that in `GenericRowDataKeySelector#open`, which executes inside separate reload thread, call of `Thread.currentThread().getContextClassLoader()` returns `SubmoduleClassLoader` rather than `FlinkUserCodeClassLoader`, which is being returned from the …
> [FLINK-29427][table] Fix unstable test LookupJoinITCase by compiling Projection class in advance and run reload task using userCodeClassLoader

- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/ResultPartitionTest.java
*Through the previous fix, we can ensure that the request thread must be blocked before the main thread recycle the buffer. However, there is still an extreme case where the request thread recovers from blocking very quickly, resulting in a calculated back-pressure time is equal to 0.*
- *fix unstable test testIdleAndBackPressuredTime.* …
> [FLINK-28326][test] fix unstable test testIdleAndBackPressuredTime.

- flink-end-to-end-tests/test-scripts/common_kubernetes.sh
The goal is to fix the Minikube version instead of relying on the Minikube version that's provided by the AzureCI Docker image.
* Removes any minikube version that's not matching the required version
* Installs the expected minikube version
* Normal ci run with k8s tests should pass
> [FLINK-30881] Fixes Minikube version

- flink-end-to-end-tests/test-scripts/common_kubernetes.sh
1.16 backport PR of parent PR #21834
The goal is to fix the Minikube version instead of relying on the Minikube version that's provided by the AzureCI Docker image.
* Removes any minikube version that's not matching the required version
* Installs the expected minikube version
* Normal ci run with k8s tests should pass …
> [BP-1.16][FLINK-30881][ci] Replaces optional minikube installation by mandatory removal

- flink-end-to-end-tests/test-scripts/common_kubernetes.sh
1.15 backport PR of parent PR #21834
The goal is to fix the Minikube version instead of relying on the Minikube version that's provided by the AzureCI Docker image.
* Removes any minikube version that's not matching the required version
* Installs the expected minikube version
* Normal ci run with k8s tests should pass …
> [BP-1.15][FLINK-30881][ci] Replaces optional minikube installation by mandatory removal

- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionDriver.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingLeaderElectionEventHandler.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionTest.java
1.17 "forwardport" PR for the 1.15 parent PR #19853
This change fixes a bug in dead code. The bug is not relevant because we deactiveated the legacy leader election completely with [FLINK-25806](https://issues.apache.org/jira/browse/FLINK-25806)
Why do we need this?
Refactoring the leader election for [FLIP-285](https://cwiki.apache.org/confluence/display/FLINK/FLIP-285%3A+Refactoring+LeaderElection+to+make+Flink+support+multi-component+leader+election+out-of-the-box)/[FLINK-26522](https://issues.apache.org/jira/browse/FLINK-26522) is kind of tricky. I'm trying to slice the code changes into meaningful commits (and ideally dedicated PRs) to make the review process easier.
I ran into this issue when refactoring the code and merging classes into one which also required adapting tests. This …
> [FLINK-27848][runtime] Fix the problem that ZooKeeperLeaderElectionDriver keeps writing leader information, using up zxid.

- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionDriver.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingLeaderElectionEventHandler.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionTest.java
1.16 "forwardport" PR for the 1.15 parent PR #19853
This change fixes a bug in dead code. The bug is not relevant right now because we deactivated the legacy leader election completely with FLINK-25806
Why do we need this?
Refactoring the leader election for [FLIP-285](https://cwiki.apache.org/confluence/display/FLINK/FLIP-285%3A+Refactoring+LeaderElection+to+make+Flink+support+multi-component+leader+election+out-of-the-box)/[FLINK-26522](https://issues.apache.org/jira/browse/FLINK-26522) is kind of tricky. I'm trying to slice the code changes into meaningful commits (and ideally dedicated PRs) to make the review process easier.
I ran into this issue when refactoring the code and merging classes into one which also required adapting tests. This revealed the inconsistency/bug in the …
> [BP-1.16][FLINK-27848][runtime] Fix the problem that ZooKeeperLeaderElectionDriver keeps writing leader information, using up zxid.

- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperatorTest.java
This pr aims to remove the local timeout in AsyncWaitOperatorTest which may cause instability for testing.
Make this a hotfix since it does not affect any process logic.
> [hotfix][FLINK-29038][datastream] Remove local timeout in AsyncWaitOperatorTest for testing guideline

- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/EmbeddedRocksDBStateBackend.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBMemoryControllerUtils.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBOperationUtils.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBSharedResourcesFactory.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBMemoryControllerUtilsTest.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBSharedResourcesFactoryTest.java
- flink-tests/src/test/java/org/apache/flink/test/state/TaskManagerWideRocksDbMemorySharingITCase.java
`TaskManagerWideRocksDbMemorySharingITCase` is unstable because it uses metrics to validate RocksDB cache/wbm sharing.
This PR extract an interface to create those shared objects (WBM/cache)  and configures state backend to use its test implementation.
As a side-effect, mocking is removed from `RocksDBMemoryControllerUtilsTest`.
cc: @Myasuka
> [FLINK-30328][tests] Fix unstable TaskManagerWideRocksDbMemorySharingITCase

- flink-runtime/src/main/java/org/apache/flink/runtime/state/StateUtil.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBStateUploader.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/snapshot/RocksDBSnapshotStrategyBase.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/snapshot/RocksIncrementalSnapshotStrategy.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/snapshot/RocksNativeFullSnapshotStrategy.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateUploaderTest.java
In rocksdb incremental checkpoint mode, during file upload, if some files have been uploaded and some files have not been uploaded, the checkpoint is canceled due to checkpoint timeout at this time, and the uploaded files will remain.
I did a detailed analysis in FLINK-30461, you can get more information from FLINK-30461.
Using the CloseableRegistry as the tmpResourcesRegistry. If the async phase is failed, the tmpResourcesRegistry will cleanup all temporary resources.
- *Added test: RocksDBStateUploaderTest#testUploadedSstCanBeCleanedUp* …
> [FLINK-30461][checkpoint] Fix the bug that the shared files will remain forever after the rocksdb incremental checkpoint exception

- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperatorTest.java
This is backport pr of  FLINK-29038 to 1.16, it aims to remove the local timeout in AsyncWaitOperatorTest which may cause instability for testing.
> [bp-1.16][FLINK-29038][datastream] Remove local timeout in AsyncWaitOperatorTest for testing guideline

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/SqlClient.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/Executor.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/ExecutorImpl.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientITCase.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientTest.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/ExecutorImplITCase.java
*We should shut down the executors when failed to creating the Executor. Shut down the ExecutorService can releases used system resources.*
> [FLINK-30840][sql-client] Fix resource leak when creating Executor

- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/CachingLookupFunction.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/fullcache/CacheLoader.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/fullcache/LookupFullCache.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/lookup/fullcache/inputformat/InputFormatCacheLoader.java
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/functions/table/fullcache/LookupFullCacheTest.java
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/functions/table/fullcache/inputformat/InputFormatCacheLoaderTest.java
Unchanged backport of #21806 on release-1.16
> [BP-1.16][FLINK-29427][table] Let reload task to always use user code classloader in full caching

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/SqlFunctionConverter.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/delegation/PlannerContext.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/expressions/converter/DirectConvertRule.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/expressions/converter/ExpressionConverter.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/sql/FlinkCurrentDateDynamicFunction.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/sql/FlinkCurrentRowTimestampFunction.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/sql/FlinkSqlOperatorTable.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/sql/FlinkTimestampDynamicFunction.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/sql/FlinkTimestampWithPrecisionDynamicFunction.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/optimize/StreamNonDeterministicUpdatePlanVisitor.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/FlinkFilterCalcMergeRule.java
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/FunctionGenerator.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdUpsertKeys.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/FlinkRexUtil.scala
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/batch/sql/DynamicFunctionPlanTest.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/common/CalcMergeTestBase.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/common/DynamicFunctionPlanTestBase.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/stream/sql/DynamicFunctionPlanTest.java
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/CalcMergeTest.xml
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/DynamicFunctionPlanTest.xml
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/CalcMergeTest.xml
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/DynamicFunctionPlanTest.xml
Make all pure dynamic functions non-deterministic in streaming mode to avoid wrong plans
* change all pure dynamic functions non-deterministic in streaming mode
TODO new tests to be added
> [FLINK-30006][table-planner] Make all pure dynamic functions non-deterministic in streaming mode to avoid wrong plans

- docs/content.zh/docs/dev/table/concepts/temporal_table_function.md
- docs/content/docs/dev/table/concepts/temporal_table_function.md
This pull requests corrects java documentation for the Temporal Table Function samples.
Modified documentation page covering the Temporal Table Function to specify the correct syntax.
This change is already covered by existing tests: 
- testLateralJoinWithScalarFunction
- Does this pull request introduce a new feature? No
- If yes, how is the feature documented? No
> [FLINK-30830][docs] Temporal Table Function Samples for Java Do Not Work As-Is, And Some Functions Are Deprecated

- flink-core/src/main/java/org/apache/flink/configuration/Configuration.java
Only added java doc to improve the readability. The code itself did tell enough information wrt the logic. I got understand it via long time debug. It is good to document it for helping developers understand the logic and also for me, since I might forget it after a few months.
No java logic has been changed.
> [hotfix][flink-core][doc] add javadoc to improve the code readability

- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateUploaderTest.java
Set the number of rocksdb uploader threads to 1 to solve the unstable bug of unit test.
Set the number of rocksdb uploader threads to 1 to solve the unstable bug of unit test.
> [FLINK-30916][checkpoint] Set the number of rocksdb uploader threads to 1 to solve the unstable bug of unit test

- flink-runtime/src/main/java/org/apache/flink/runtime/state/StateUtil.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBStateUploader.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/snapshot/RocksIncrementalSnapshotStrategy.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateUploaderTest.java
Backport the [FLINK-30461](https://issues.apache.org/jira/browse/FLINK-30461) to release-1.15
> [bp-1.15][FLINK-30461][checkpoint] Fix the bug that the shared files will remain forever after the rocksdb incremental checkpoint exception

- flink-connectors/flink-connector-hbase-1.4/src/test/java/org/apache/flink/connector/hbase1/HBaseConnectorITCase.java
- flink-connectors/flink-connector-hbase-2.2/src/test/java/org/apache/flink/connector/hbase2/HBaseConnectorITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/endpoint/hive/HiveServer2EndpointITCase.java
- flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/SqlConstraintValidator.java
- flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/AlterSchemaConverter.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlCreateTableConverter.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlToOperationConverter.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlDdlToOperationConverterTest.java
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/TableEnvironmentTest.scala
This pull request aims to fix the issue that the column constraint lacks the not enforced check.
```sql
CREATE TABLE foo (
a INT PRIMARY KEY, -- currently this passes the validation, but it should be `a INT PRIMARY KEY NOT ENFORCED`
b STRING
) WITH (...)
```
Currently, the constraint check(on the duplicate primary key, unique key, and enforced mode) spreads over the parse and conversion phase(see `SqlCreateTable#validate` and `SqlToOperatoinConverter#validateTableConstraint`).
To improve this, introduce a `SqlConstraintValidator` to perform the unified check for both column and table constraints. 
The logic of`SqlToOperatoinConverter#validateTableConstraint` is moved to `SqlConstraintValidator`.
- FlinkSqlParserImplTest
- …
> [FLINK-30386] Fix the issue that column constraint lacks primary key not enforced check

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesMultipleComponentLeaderElectionHaServices.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/AbstractHaServices.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/zookeeper/ZooKeeperMultipleComponentLeaderElectionHaServices.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/AbstractHaServicesTest.java
The HA-backend-specific code is actually only the `LeaderElectionDriverFactory` creation rather than instantiating the `LeaderElectionService`. This is meant as a prep PR to reduce the code diff of the actual FLINK-26522 changes.
* Introduces abstract method `createLeaderElectionDriverFactory(String)` that's called by `createLeaderElectionService(String)` 
- The S3 …
> [FLINK-30788][runtime] Refactors AbstractHaServices.createLeaderElectionService to return LeaderElectionDriverFactory

- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionServiceTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultMultipleComponentLeaderElectionServiceTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/LeaderChangeClusterComponentsTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/LeaderElectionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/StandaloneLeaderElectionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionConnectionHandlingTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperMultipleComponentLeaderElectionDriverTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderretrieval/DefaultLeaderRetrievalServiceTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderretrieval/SettableLeaderRetrievalServiceTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderretrieval/ZooKeeperLeaderRetrievalConnectionHandlingTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderretrieval/ZooKeeperLeaderRetrievalTest.java
Migrating the tests to JUnit5 makes it easier to merge the MultipleComponent-related tests with the legacy tests
* removed `public` modifiers
* replaced JUnit4 and hamcrest methods with JUnit5 and assertj
* The tests should still succeed
- Dependencies (does it add or upgrade a dependency):no
- If yes, how is the feature documented?not applicable
> [FLINK-30801][runtime] Migrating LeaderElection/Retrieval-related tests to JUnit5

- flink-clients/src/test/java/org/apache/flink/client/deployment/application/ApplicationDispatcherBootstrapTest.java
This change prevents a race condition where the bootstrap process finishes before the test calls stop which results in an outcome that's not expected in this test.
* Makes the getJobStatus method return an not-completed future which will halt the polling of the JobStatus until `stop` is called on the bootstrap process.
Adding `Thread.sleep(1000)` before the [stop call|https://github.com/apache/flink/blob/329848e953566d5e086bcd4fc72c2e926db84715/flink-clients/src/test/java/org/apache/flink/client/deployment/application/ApplicationDispatcherBootstrapTest.java#L351] in the test code will simulate the issue. 
- The runtime …
> [FLINK-30910][runtime] Making test wait for stop to be called before finishing the bootstrap operation

- flink-clients/src/test/java/org/apache/flink/client/deployment/application/ApplicationDispatcherBootstrapTest.java
1.17 backport for parent PR #21869
> [BP-1.17][FLINK-30910][runtime] Making test wait for stop to be called before finishing the bootstrap operation (#21869)

- flink-clients/src/test/java/org/apache/flink/client/deployment/application/ApplicationDispatcherBootstrapTest.java
1.16 backport for parent PR #21869
> [BP-1.16][FLINK-30910][runtime] Making test wait for stop to be called before finishing the bootstrap operation (#21869)

- flink-formats/flink-avro-glue-schema-registry/src/main/java/org/apache/flink/formats/avro/glue/schema/registry/GlueSchemaRegistryInputStreamDeserializer.java
Remove reference of MutableByteArrayInputStream from flink-avro-glue-schema-registry so that it can be made @Internal to flink-avro.
- Remove use of MutableByteArrayInputStream
This change is already covered by existing tests, such as end-to-end tests.
> [FLINK-30837] Remove use of MutableByteArrayInputStream

- flink-table/flink-sql-client/src/test/resources/sql/set.q
Fix the unstable ctas test in CliClientITCase, we should wait for the insert query to finish first, then query the table
> [FLINK-30640][SqlClient] Fix unstable ctas test in CliClientITCase

- flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ExecutionGraphPartitionReleaseTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/TestingComponentMainThreadExecutor.java
*`ExecutionGraphPartitionReleaseTest` leaks threads through `ExecutionGraphPartitionReleaseTest.scheduledExecutorService`. The `ScheduledExecutorService` is instantiated but never shut down.*
- *Fix the problem of thread leaking for `ExecutionGraphPartitionReleaseTest`*
> [FLINK-30944] ExecutionGraphPartitionReleaseTest leaks threads

- flink-end-to-end-tests/test-scripts/common.sh
Some stacktraces of passed tests may contain `completeExceptionally`, which might fail the e2e (bash) tests.
This PR adds `completeExceptionally` to the list of ignored patterns.
Please see https://issues.apache.org/jira/browse/FLINK-30785?focusedCommentId=17682143&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17682143 for more details
> [FLINK-30785][tests] Ignore completeExceptionally in e2e test logs

- flink-dstl/flink-dstl-dfs/pom.xml
- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/ChangelogStreamHandleReaderWithCache.java
- flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/ChangelogStreamHandleReaderWithCacheTest.java
Fix the changelog local cache file not found while restarting, described in [FLINK-30561](https://issues.apache.org/jira/browse/FLINK-30561).
- prevent  _StateChangelogHandleStreamHandleReader_  close current iterator twice.
> [FLINK-30561][state/changelog] fix changelog local cache file not found

- docs/content.zh/docs/deployment/elastic_scaling.md
- docs/content/docs/deployment/elastic_scaling.md
Minor documentation fix: `ALL_EXCHANGES_BLOCKING`  != `ALL-EXCHANGES-BLOCKING`
> [hotfix] Fix typo in elastic_scaling.md

- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/AbstractStateChangeFsUploader.java
- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogWriter.java
- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/TaskChangelogRegistry.java
- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/TaskChangelogRegistryImpl.java
- flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/DiscardRecordableStateChangeUploader.java
- flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/FsStateChangelogWriterTest.java
- flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/TaskChangelogRegistryImplTest.java
- flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/TestingBatchingUploadScheduler.java
- flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogStateDiscardTest.java
Fix state changelog file not found exception decripted in [FLINK-28440
](https://issues.apache.org/jira/browse/FLINK-28440)
- record reference count of *StreamStateHandle* in *TaskChangelogRegistry*
- when *UploadResult* not used, decrement the reference count of the corresponding *StreamStateHandle* by one
- delete the *StreamStateHandle* after the reference count is zeroed
- FsStateChangelogWriterTest#testChangelogFileAvailable
- FsStateChangelogWriterTest#testChangelogFileAvailableAgain
- Anything …
> [FLINK-28440][state/changelog] record reference count of StreamStateHandle in TaskChangelogRegistry

- flink-python/dev/dev-requirements.txt
- flink-python/setup.py
- flink-python/tox.ini
This PR removes deprecated "tests_require" from setup.py, which contains a old version of pytest requires python < 3.8.
> [FLINK-30961][Python] Remove deprecated "tests_require" in setup.py

- docs/content.zh/docs/dev/table/sql/explain.md
- docs/content/docs/dev/table/sql/explain.md
*Fix typo in explain.md.*
- *Fix typo(`OHE_PHASE` -> `ONE_PHASE`) in explain.md.*
> [hotfix] Fix typo in explain.md

- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/splitreader/SplitReader.java
SplitReader doesn't extend AutoCloseable but implements close method. We  need to let it extends AutoCloseable which could enable us to utilize Java's try close feature.
Let SplitReader interface extends AutoCloseable.
Because SplitReader#close override AutoCloseable#close with same signature and behavior. It has no effect on connector implementations. It can be tested by current ci test cases.
- Does this …
> [FLINK-31015][connectors/common] Fix SplitReader doesn't extends AutoCloseable but implements close method

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorImpl.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorTest.java
At present, the external IO during abort checkpoint is in the mailbox thread. When the external system fails, it will block the Task for a long time to process data, so consider moving the external IO to the asynchronous thread pool.
Add an asynchronous thread pool in `SubtaskCheckpointCoordinatorImpl` to handle external IO operations of abort checkpoint.
This change is already covered by existing tests, such as `SubtaskCheckpointCoordinatorTest#testNotifyCheckpointAbortedDuringAsyncPhase`.
- Dependencies (does it add or upgrade a dependency): (yes …
> [FLINK-30251] Move the IO with DFS during abort checkpoint to an asynchronous thread pool.

- docs/content.zh/docs/connectors/table/kafka.md
- docs/content/docs/connectors/table/blackhole.md
- docs/content/docs/connectors/table/kafka.md
Update connector label for kafka and blackhole.
Blackhole: sink:bounded unbounded
Kafka: source bounded
> [FLINK-31086][DOC]update connector lable for blackhole and kafka

- flink-end-to-end-tests/flink-sql-client-test/src/test/java/SqlClientITCase.java
*fix SqlClientITCase#testMatchRecognize*
- *make verifyNumberOfResultRecords wait until getting the expected number of records*
> [FLINK-30257] fix SqlClientITCase#testMatchRecognize

- flink-end-to-end-tests/test-scripts/docker-hadoop-secure-cluster/hadoop/Dockerfile
Migrate from OpenJDK which is announced to be deprecated [here](https://hub.docker.com/_/openjdk). In this PR I've migrated to temurin JRE like we have in `flink-docker`.
Compile docker images.
- The public API, i.e., is any changes to the `CustomResourceDescriptors`: no
- Core observer or reconciler logic that is regularly executed: no
> [FLINK-30928][tests] Change to eclipse-temurin due to openjdk deprecation

- docs/content.zh/docs/dev/datastream/overview.md
Fix typo in zh/docs/dev/datastream/overview.md
Fix typo(setp -> step) in overview.md
The public API, i.e., is any changed class annotated with @Public(Evolving): no
The runtime per-record code paths (performance sensitive): no
Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
The S3 file system connector: no
Does this pull request introduce a new feature? no
> [hotfix] [doc] Fix typo in zh/docs/dev/datastream/overview.md

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamNode.java
[FLINK-27800](https://issues.apache.org/jira/browse/FLINK-27800)
This pull request try to fix when addInEdge, if this edge is already in InEdge list, but can still be added, because the checkState function is to check outEdge list now.
- change addInEdge to check whether the new edge has already is exists.
> [FLINK-27800][streaming] Fix the error check in StreamNode#addInEdge

- docs/content.zh/docs/deployment/elastic_scaling.md
- docs/content/docs/deployment/elastic_scaling.md
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/JobGraphJobInformation.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/allocator/JobInformation.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/allocator/SlotSharingSlotAllocator.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/allocator/SlotSharingSlotAllocatorTest.java
Fixes an issue where the distribution of slots across slot-sharing groups did not take the max parallelism of that group into account, due to which some slots were potentially left unused.
We now update the number of slots assigned per group dynamically after each group was processed. Before slots are assigned the groups are sorted by the max parallelism in ascending order so we can assign all slots in one pass.
As a potential follow-up we could consider an alternative slot distribution pattern where slots are assigned proportional to the max parallelism of the groups.
> [FLINK-30895][coordination] Dynamically adjust slot distribution

- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/agg/batch/HashAggCodeGenerator.scala
In our test environment, we set the default parallelism to  1 and got the most appropriate default value of parameter `table.exec.local-hash-agg.adaptive.sampling-threshold`  is `5000000.` However, for these batch jobs with high parallelism in produce environment,  the amount of data in single parallelism is almost less than `5000000`. Therefore, after testing, we found that set to `500000` can get better results.
Modify the default value of `table.exec.local-hash-agg.adaptive.sampling-threshold`.
no test. …
> [FLINK-30971][table-runtime] Modify the default value of parameter 'table.exec.local-hash-agg.adaptive.sampling-threshold'

- flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskTest.java
Backport for #21763 
The static latches in TaskTest were replaced by latches from invokable objects in order to avoid accidental sharing latches between multiple tests
It's test …
> [FLINK-15550][runtime] The static latches in TaskTest were replaced by latches from invokable objects

- docs/content.zh/docs/connectors/table/hive/hive_functions.md
- docs/content/docs/connectors/table/hive/hive_functions.md
*Add document for option table.exec.hive.native-agg-function.enabled*
- *Add document for option table.exec.hive.native-agg-function.enabled*
> [FLINK-30824][hive] Add document for option table.exec.hive.native-agg-function.enabled

- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobRecoveryITCase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/TestingAbstractInvokables.java
The Sender/Receiver invokables assume that the receiver is run with parallelism greater or equal to the sender invokable.
If this is not satisfied than there is no input gate to read from, causing read operations to fail.
The test was using an uneven number of slots. This caused one invokable to run with p=5, the other with p=6.
Depending on who gets this 6th slot the test would fail or pass.
I don't think there's a well-defined order in which this should happen, so I attribute this to wrong assumptions in the test.
For clarity, with FLINK-30895 the adaptive scheduler assigns slots in order of maximum parallelism, and if 2 vertices have the same parallelism then by iteration order over a hash map. Previously it would assign them in whatever iteration order vertices were passed to the …
> [FLINK-31119][tests] Use even # of slots 

- flink-runtime/src/test/java/org/apache/flink/runtime/testutils/MiniClusterResource.java
FileSystemCheckpointStorage as the default for test, because the checkpoint size of JobManagerCheckpointStorage isn't enough in some tests.
FileSystemCheckpointStorage as the default for test.
- If yes, how is the feature documented? (not documented
> [FLINK-31036][test][checkpoint] FileSystemCheckpointStorage as the default for test

- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultScheduler.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinatorSchedulerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/TestingOperatorCoordinator.java
This pull request allows DefaultScheduler to skip the restoreState which is a heavy invocation when no task needs to be restarted.
- *DefaultScheduler#restartTasks return early when verticesToRestart is empty.*
- *Added test that validates that OperatorCoordinator#resetToCheckpoint will invoke once when fail global twice quickly*
- Does …
> [FLINK-31041][runtime] Fix multiple restoreState when GlobalFailure occurs in a short period.

- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/batch/BatchSink.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveTableSink.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableCompactSinkITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableCompactSinkParallelismTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableFactoryTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableSinkITCase.java
- flink-connectors/flink-connector-hive/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Backport FLINK-31132 to release-1.17.
> [BP-1.17][FLINK-31132] Let hive compact operator without setting parallelism subject to sink operator's configured parallelism.

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java
*This change mainly to add a concurrent access control for the static list `collectIterators` in `StreamExecutionEnvironment`. There are still chances to cause a ConcurrentModifyException, although most of time we are accessing StreamExecutionEnvironment in a single thread.*
- Made collectorIterators a synchronizedList in StreamExecutionEnvironment.
This change has test cases covered by ITCases which are executed in concurrent mode. It's a stability issue that might have a small probability to reproduce a failure case.  …
> [FLINK-31120] Add concurrent access control for collectorIterators in  StreamExecutionEnvironment

- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultScheduler.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinatorSchedulerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/TestingOperatorCoordinator.java
Backport [FLINK-31041](https://issues.apache.org/jira/browse/FLINK-31041) to release-1.15.
> [BP-1.15][FLINK-31041][runtime] Fix multiple restoreState when GlobalFailure occurs in a short period.

- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultScheduler.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinatorSchedulerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/TestingOperatorCoordinator.java
Backport [FLINK-31041](https://issues.apache.org/jira/browse/FLINK-31041) to release-1.16.
> [BP-1.16][FLINK-31041][runtime] Fix multiple restoreState when GlobalFailure occurs in a short period. 

- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultScheduler.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinatorSchedulerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/TestingOperatorCoordinator.java
Backport [FLINK-31041](https://issues.apache.org/jira/browse/FLINK-31041) to release-1.17.
> [BP-1.17][FLINK-31041][runtime] Fix multiple restoreState when GlobalFailure occurs in a short period. 

- flink-yarn/src/main/java/org/apache/flink/yarn/Utils.java
... to avoid including private tokens in AM container context
Avoid setting private tokens to AM container context when kerberos delegation token fetch is disabled and DTs are managed.
Currently while setting user credentials to the AM container context, `ugi.getTokens()` is used which also returns the private tokens along with UGI tokens. But it should not be passed to the AM container context. This causes the launch of YARN RM app to fail in some cases for example when [Consistent Reads from HDFS Observer NameNode](https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/ObserverNameNode.html) feature is enabled.  
Instead, change it to `ugi.getCredentials().getAllTokens()` to only get user credentials tokens. Spark uses similar way of setting the [user credentials to AM …
> [FLINK-31162][yarn] Use currUsr.getCredentials.getTokens instead of currUsr.getTokens

- flink-runtime/src/main/java/org/apache/flink/runtime/blob/BlobServerConnection.java
The error log of  executing BLOB connection failed does not shows client address. If there are some malicious attacks, it's hard to find the sources.  We should log the client address.
- Log the client address when BlobConnection in error.
- *Manually verified the change by send a `curl` to blob server. The client address will be log.*
- 
> [FLINK-27115][blob] Enrich the error log with remote address for blobServer

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/parser/SqlCommandParserImpl.java
- flink-table/flink-sql-client/src/test/resources/sql/select.q
After https://issues.apache.org/jira/browse/FLINK-29945 sql client started to close the session in case some invalid queries rather than just fail with error and allow user to enter another one. 
example of queries
```sql
SELECT /*;
```
```sql
SELECT @;
```
```sql
SELECT #;
```
It seems that before this change all the parser exceptions are handled via `org.apache.calcite.sql.parser.SqlAbstractParserImpl#normalizeException` which under the hood catches `TokenMgrError`. Now it works directly with `TokenIterator` that's why extra catch is required.
The test query reproducing the issue added to _flink-table/flink-sql-client/src/test/resources/sql/select.q_ …
> [FLINK-31142][Table SQL/Client] Catch TokenMgrError in SqlCommandParserImpl#scan

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/parser/SqlCommandParserImpl.java
- flink-table/flink-sql-client/src/test/resources/sql/select.q
This is 1.17 backport of https://github.com/apache/flink/pull/22007
> [BP-1.17][FLINK-31142][Table SQL/Client] Catch TokenMgrError in SqlCommandParserImpl#scan

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/DataBuffer.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PipelinedApproximateSubpartition.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PipelinedApproximateSubpartitionView.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PipelinedResultPartition.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PipelinedSubpartition.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PrioritizedDeque.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartition.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionReadScheduler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeSubpartitionReader.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/HsResultPartition.java
Add GuardedBy annotation and some clean up for result partition.
- *Add missing @GuardedBy annotation for SortMergeResultPartitionReadScheduler and PipelinedSubpartition.*
- *Fix some typo and syntax mistakes.*
- *Clean up code of HsResultPartition, PrioritizedDeque and SortMergeSubpartitionReader.* …
> [hotfix] Add GuardedBy annotation and some clean up for result partition.

- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/row/ParquetRowDataWriter.java
- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/utils/ParquetSchemaConverter.java
- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/ParquetSplitReaderUtil.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/vector/ParquetColumnarRowSplitReaderTest.java
Parquet format supports MULTISET type.
- The reader, writer and schema converter of parquet format supports MULTISET type.
- `ParquetColumnarRowSplitReaderTest` adds the MULTISET type test case. …
> [FLINK-31250][formats][parquet] Parquet format supports MULTISET type

- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/ParquetInputFile.java
- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/ParquetVectorizedInputFormat.java
- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/avro/AvroParquetRecordFormat.java
*As the issue description, currently we can't get Hadoop-related authentication information from flink-conf.yaml when create `ParquetReader` using S3AFileSystem in TM, but in JM, `SourceCoordinator` works well when getFileStatus from s3a. After taking a deep analysis of the source code, I found that on the JM side, we use Flink's own FileSystem to get `FileStatus`, which can get the authentication information from flink-conf.yaml; but on the TM side, we use Hadoop's own FileSystem to create footer, which can't get the authentication information, which is an inconsistent behavior and causes the problem of the issue description. So we should use Flink's FileSystem on both JM side and TM side.  This PR is a bugfix.*
- *Extracting the public class `ParquetInputFile`*
- *Using the Flink …
> [FLINK-29729][parquet] Fix credential info configured in flink-conf.yaml is lost during creating ParquetReader

- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/ParquetInputFile.java
- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/ParquetVectorizedInputFormat.java
- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/avro/AvroParquetRecordFormat.java
This is a cherry-pick back to release-1.16 branch.
> [BP-1.16][FLINK-29729][parquet] Fix credential info configured in flink-conf.yaml is lost during creating ParquetReader

- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/ParquetInputFile.java
- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/ParquetVectorizedInputFormat.java
- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/avro/AvroParquetRecordFormat.java
This is a cherry-pick back to release-1.17 branch.
> [BP-1.17][FLINK-29729][parquet] Fix credential info configured in flink-conf.yaml is lost during creating ParquetReader

- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/ParquetInputFile.java
- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/ParquetVectorizedInputFormat.java
- flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/avro/AvroParquetRecordFormat.java
This is a cherry-pick back to release-1.15 branch.
> [BP-1.15][FLINK-29729][parquet] Fix credential info configured in flink-conf.yaml is lost during creating ParquetReader

- flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterClientFactory.java
- flink-yarn/src/main/java/org/apache/flink/yarn/cli/FlinkYarnSessionCli.java
JIRA: FLINK-31222. Remove usage of deprecated ConverterUtils.toApplicationId.
When reading the code, I found that we use ConverterUtils.toApplicationId to convert applicationId, this method is deprecated, we should use ApplicationId.fromString
Remove usage of deprecated ConverterUtils.toApplicationId.
- The S3 file system connector: (yes / no / …
> [FLINK-31222] Remove usage of deprecated ConverterUtils.toApplicationId.

- docs/content.zh/docs/dev/table/sql/create.md
- docs/content/docs/dev/table/sql/create.md
Fix code example bug in the doc that will make user confused. 
- `order_time AS to_timestamp(order_time_string)` instead of `order_time AS to_timestamp(order_time)`
- update both content/ and content.zh/
> [hotfix][doc] to_timestamp() should use order_time_string column instead of order_time

- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/hadoop/KerberosLoginProviderITCase.java
There was a blocker fix which added some uncovered execution paths. In this PR I've added more coverage for stability.
Increases `KerberosLoginProvider` test coverage.
Extended unit tests.
> [FLINK-31284][tests] Increase KerberosLoginProvider test coverage

- docs/content.zh/docs/dev/configuration/gradle.md
- docs/content.zh/docs/dev/configuration/maven.md
- docs/content.zh/docs/flinkDev/building.md
- docs/content/docs/dev/configuration/gradle.md
- docs/content/docs/dev/configuration/maven.md
- docs/content/docs/flinkDev/building.md
Flink 1.15 and later versions require at least Java 11 to build from sources [1], whereas the pom.xml specifies the source/target is 1.8. This inconsistency confuses users.
As mentioned in the [FLINK-25247](https://issues.apache.org/jira/browse/FLINK-25247) title, the goal of that ticket is to "Inform users about deprecation". It will be better to inform users that "Java 8 is deprecated" instead of saying "Fink requires at least Java 11 to build", so that users have the right information to make the right choice for themselves.
Also note that Flink community is regularly running flink-ml benchmark for both Java 8 and Java 11 [2], which suggests that we are practically ensuring Java 8 is supported.
If we decide to official drop Java 8 support, Flink community probably should give explicit …
> [FLINK-30501] Update Flink build instruction to deprecate Java 8 instead of requiring Java 11 

- docs/content.zh/docs/dev/python/datastream/data_types.md
- docs/content/docs/dev/python/datastream/data_types.md
This is a trivial change replacing `serailize` with `serialize` in _data_types.md_
- Dependencies (does it add or upgrade a dependency): (/ no)
> [hotfix][docs] Replace `serailize` with `serialize` in data_types.md

- docs/content.zh/docs/dev/configuration/gradle.md
- docs/content.zh/docs/dev/configuration/maven.md
- docs/content.zh/docs/flinkDev/building.md
- docs/content/docs/dev/configuration/gradle.md
- docs/content/docs/dev/configuration/maven.md
- docs/content/docs/flinkDev/building.md
Flink 1.15 and later versions require at least Java 11 to build from sources [1], whereas the pom.xml specifies the source/target is 1.8. This inconsistency confuses users.
As mentioned in the [FLINK-25247](https://issues.apache.org/jira/browse/FLINK-25247) title, the goal of that ticket is to "Inform users about deprecation". It will be better to inform users that "Java 8 is deprecated" instead of saying "Fink requires at least Java 11 to build", so that users have the right information to make the right choice for themselves.
Also note that Flink community is regularly running flink-ml benchmark for both Java 8 and Java 11 [2], which suggests that we are practically ensuring Java 8 is supported.
If we decide to official drop Java 8 support, Flink community probably should give explicit …
> [FLINK-30501] Update Flink build instruction to deprecate Java 8 instead of requiring Java 11

- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/FineGrainedSlotManagerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/FineGrainedSlotManagerTestBase.java
We use TaskManagerTracker.addPendingTaskManager to allocate task manager in FineGrainedSlotManagerTest. This make the resource requirements different between FineGrainedSlotManager and TaskManagerTracker. And the FineGrainedSlotManager may trigger resource recycling after the requirementCheckDelay.
So we use processResourceRequirements to allocate task manager. And set the requirementCheckDelay to 0 to stabilize this test.
- *use processResourceRequirements to allocate task manager*
- *set the requirementCheckDelay to 0 to stabilize the test*
- this test ran successfully 200 times …
> [FLINK-31297][Runtime] Use processResourceRequirements to allocate sk manager in FineGrainedSlotManagerTest

- flink-table/flink-table-common/src/main/java/org/apache/flink/table/utils/TableSchemaUtils.java
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/calcite/FlinkTypeFactory.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/calcite/PreValidateReWriter.scala
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/common/PartialInsertTest.xml
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/common/PartialInsertTest.scala
Fix the bug that it excludes all metadata and computed columns when doing preValidateRewrite with partial insert.
- Added util to get persisted schema.
- Apply persisted columns as target row type when doing pre-validate rewrite for partial insert.
This change has test cases covered in PartialInsertTest. …
> [FLINK-30922][table-planner] Apply persisted columns when doing appendPartitionAndNullsProjects

- flink-table/flink-table-common/src/main/java/org/apache/flink/table/utils/TableSchemaUtils.java
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/calcite/FlinkTypeFactory.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/calcite/PreValidateReWriter.scala
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/common/PartialInsertTest.xml
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/common/PartialInsertTest.scala
*Fix the bug that it excludes all metadata and computed columns when doing preValidateRewrite with partial insert.*
- Added util to get persisted schema.
- Apply persisted columns as target row type when doing pre-validate rewrite for partial insert.
This change has test cases covered in PartialInsertTest. …
> [FLINK-30922][table-planner] Fix errors when reference metadata columns in column list of a partial-insert statement

- docs/content.zh/docs/flinkDev/building.md
- docs/content/docs/flinkDev/building.md
After [FLINK-20845](https://issues.apache.org/jira/browse/FLINK-20845), Flink dropped the support of Scala 2.11. However, the doc of "building from source" still has the description on scala-2.11. We should update this.
only to docs …
> [FLINK-31283][docs] Update the scala-2.11 related building doc

- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/HsResultPartitionTest.java
*After FLINK-31346, IO Scheduler will shutdown JVM If unexpected errors are encountered in `run` method. But for `HsResultPartitionTest`, IO executor will be shut down after each test class. The working IO thread has the probability to continue to submit the scheduled task to it, thus throw  `RejectedExecutionException`.*
- *Using an executor service which ignore `RejectedExecutionException` caused by shutdown for `HsResultPartitionTest`.* …
> [FLINK-31360][test] Using an executor service which ignore rejectException as shutdown for HsResultPartitionTest.

- flink-runtime-web/web-dashboard/src/app/pages/job/overview/backpressure/job-overview-drawer-backpressure.component.html
- flink-runtime-web/web-dashboard/src/app/pages/job/overview/backpressure/job-overview-drawer-backpressure.component.ts
- *Make the backpressure tab could be sort by busy/backpressure/idle seperately*
- The runtime per-record code paths (performance sensitive): (yes / no / don't)
> [FLINK-30829] Make the backpressure tab could be sort by busy/backpressure/idle seperately

- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/CodeGenUtils.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/ExprCodeGenerator.scala
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/MathFunctionsITCase.java
*fix builtin function of times wrong check.*
Flink SQL> select 2 * interval '3'  day;
[ERROR] Could not execute SQL statement. Reason:
org.apache.flink.table.planner.codegen.CodeGenException: Interval expression type expected. 
unit test
> [FLINK-31279][table] fix builtin function of times wrong check.

- flink-runtime/src/main/java/org/apache/flink/runtime/state/CompressibleFSDataInputStream.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/CompressibleFSDataOutputStream.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/DefaultOperatorStateBackendBuilder.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/DefaultOperatorStateBackendSnapshotStrategy.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/OperatorBackendSerializationProxy.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/OperatorStateRestoreOperation.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/metainfo/StateMetaInfoSnapshotReadersWriters.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/SerializationProxiesTest.java
Implement state compression for broadcast and regular operator states. Only the states themselves are compressed not the metadata.
-  Introduce FSData streams wrappers that add compression
- Use these wrappers while writing state (in the default operator snapshot strategy) and while reading state (in the operator state restore operation)
This change is already covered by existing tests, such as windowing ITCase tests ... in the flink-runtime module …
> [FLINK-30113] Implement state compression for broadcast and regular operator states

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionReadScheduler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/HsFileDataManager.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionReadSchedulerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/HsFileDataManagerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/HsResultPartitionTest.java
Backport FLINK-31346 to release-1.16.
> [BP-1.16][FLINK-31346][runtime] IO scheduler does not throw TimeoutException if numRequestedBuffers is greater than 0.

- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/casting/AbstractCastRule.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/casting/CastRule.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CastFunctionMiscITCase.java
Currently the queries
```sql
select try_cast(array['a'] as array<int>);
select try_cast(map['a', '1'] as map<int, int>);
```
are failing with `NumberFormatException`. The PR makes them returning `null` as it should be in case of `try_cast`
The main issue is that there is already implemented method `org.apache.flink.table.planner.functions.casting.ConstructedToConstructedCastRule` 
however in case of e.g. `org.apache.flink.table.planner.functions.casting.ArrayToArrayCastRule` it inherits from `AbstractCastRule` containing `canFail`. Since methods from classes have more priority than default from interfaces it will be called. The idea is to move `canFail`'s implementation from `AbstractCastRule` to parent's interface `CastRule`.
Specific tests for maps and arrays are added at …
> [FLINK-31300][table] TRY_CAST for constructed types

- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/AbstractHaServicesTest.java
After https://github.com/apache/flink/commit/593cc139ab30bb81ab38d94b7b697d00eaaecada there is an issue with spotless.
The PR is aiming to fix it
> [hotfix] Apply spotless for AbstractHaServicesTest

- flink-runtime/src/main/java/org/apache/flink/runtime/io/disk/BatchShuffleReadBufferPool.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartition.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionTest.java
Currently, the SortMergeResultPartition may allocate more network buffers than the guaranteed size of the LocalBufferPool. As a result, some result partitions may need to wait other result partitions to release the over-allocated network buffers to continue. However, the result partitions which have allocated more than guaranteed buffers relies on the processing of input data to trigger data spilling and buffer recycling. The input data further relies on batch reading buffers used by the SortMergeResultPartitionReadScheduler which may already taken by those blocked result partitions that are waiting for buffers. Then deadlock occurs. This patch fixes the deadlock issue by reserving the guaranteed buffers on initializing.
- Reserve the guaranteed buffers on initializing for …
> [FLINK-31386][network] Fix the potential deadlock issue of blocking shuffle

- flink-yarn/src/main/java/org/apache/flink/yarn/Utils.java
- flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
- flink-yarn/src/test/java/org/apache/flink/yarn/YarnFileStageTest.java
JIRA: FLINK-31402. Remove ConverterUtils Deprecated Method.
Many methods in ConverterUtils have been Deprecated, we can replace the Deprecated methods and remove this class(ConverterUtils).
1. replace the Deprecated methods 
2. remove this class(ConverterUtils) …
> [FLINK-31402][yarn] Remove usage of deprecated ConverterUtils method.

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/HybridShuffleConfiguration.java
Backport FLINK-31393 to release-1.17.
> [BP-1.17][FLINK-31393] Fix the bug that HsFileDataManager use an incorrect default timeout.

- flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogBaseTableResolutionTest.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogPropertiesUtil.java
Currently, `CatalogPropertiesUtil` doesn't de/serialize column comments which loses information when restoring from catalogs if the catalog uses this util to persist table information. 
- Serialize and deserialize column comments into properties with the `schema.${i}.comment` pattern. 
Added tests in `CatalogBaseTableResolutionTest` to verify the de/serialize logic for column comments.  …
> [FLINK-29743][table] CatalogPropertiesUtil supports de/serializing column comment

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/HybridShuffleConfiguration.java
Backport FLINK-31393 to release-1.16.
> [BP-1.16][FLINK-31393] Fix the bug that HsFileDataManager use an incorrect default timeout.

- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGeneratorTest.java
Minor improvement to the test, so that it does not fail on 10 core machines.
cc @JunRuiLee
> [FLINK-31401][streaming][tests] Make parallelism assumption explicit in StreamingJobGraphGeneratorTest

- docs/content.zh/docs/connectors/datastream/filesystem.md
- docs/content/docs/connectors/datastream/filesystem.md
Current artifacts for `flink-orc`, `flink-parquet` don't have scala version, but document guide includes it.
https://mvnrepository.com/artifact/org.apache.flink/flink-orc/1.16.0
https://mvnrepository.com/artifact/org.apache.flink/flink-parquet/1.16.0
Remove scala version for file system artifactId
> [FLINK-31227][docs] Remove scala version for file system artifactId

- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/endpoint/hive/HiveServer2EndpointStatementITCase.java
- flink-table/flink-sql-gateway/pom.xml
- flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/AbstractSqlGatewayStatementITCase.java
- flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/SqlGatewayTest.java
- flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/rest/OperationRelatedITCase.java
- flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/rest/SessionRelatedITCase.java
- flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/rest/SqlGatewayRestEndpointStatementITCase.java
- flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/rest/StatementRelatedITCase.java
- flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/SqlGatewayServiceITCase.java
- flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/SqlGatewayServiceStatementITCase.java
- flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/context/SessionContextTest.java
- flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/result/ResultFetcherTest.java
- flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/session/SessionManagerImplTest.java
- flink-table/flink-sql-gateway/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
The PR hardens modifiers for junit5 tests
as a follow up for https://github.com/apache/flink/pull/22127#discussion_r1129192778
- The runtime per-record code paths (performance sensitive):  (no)
> [FLINK-31369][sql-gateway] Harden modifiers in tests for sql-gateway module

- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionReadSchedulerTest.java
*Fix buffer request timeout for sort merge result partition read test*
- *Fix buffer request timeout for sort merge result partition read test*
This change is a test fixup without any test coverage.
- If …
> [FLINK-31418][network][tests] Fix buffer request timeout for sort merge result partition test

- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionReadSchedulerTest.java
*Fix buffer request timeout for sort merge result partition read test*
- *Fix buffer request timeout for sort merge result partition read test*
This change is a test fixup without any test coverage.
- If …
> [FLINK-31418][network][tests] Fix buffer request timeout for sort merge result partition read test

- flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/splitreader/SplitReader.java
After a discussion in https://github.com/apache/flink-connector-cassandra/pull/3#discussion_r1087830169
R: @zentol
> [FLINK-30802] Add details on SplitReader#fetch() interruption/resume

- flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/threadinfo/ThreadInfoRequestCoordinatorTest.java
Backport FLINK-31420 to release-1.17.
> [BP-1.17][FLINK-31420][test] Fix unstable test ThreadInfoRequestCoordinatorTest#testShutDown.

- flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/threadinfo/ThreadInfoRequestCoordinatorTest.java
Backport FLINK-31420 to release-1.16.
> [BP-1.16][FLINK-31420][test] Fix unstable test ThreadInfoRequestCoordinatorTest#testShutDown.

- docs/content.zh/docs/connectors/table/formats/avro-confluent.md
- docs/content.zh/docs/connectors/table/formats/debezium.md
- docs/content/docs/connectors/table/formats/avro-confluent.md
- docs/content/docs/connectors/table/formats/debezium.md
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaDynamicTableFactoryTest.java
- flink-formats/flink-avro-confluent-registry/src/main/java/org/apache/flink/formats/avro/registry/confluent/AvroConfluentFormatOptions.java
- flink-formats/flink-avro-confluent-registry/src/main/java/org/apache/flink/formats/avro/registry/confluent/RegistryAvroFormatFactory.java
- flink-formats/flink-avro-confluent-registry/src/main/java/org/apache/flink/formats/avro/registry/confluent/debezium/DebeziumAvroDeserializationSchema.java
- flink-formats/flink-avro-confluent-registry/src/main/java/org/apache/flink/formats/avro/registry/confluent/debezium/DebeziumAvroFormatFactory.java
- flink-formats/flink-avro-confluent-registry/src/main/java/org/apache/flink/formats/avro/registry/confluent/debezium/DebeziumAvroSerializationSchema.java
- flink-formats/flink-avro-confluent-registry/src/test/java/org/apache/flink/formats/avro/registry/confluent/RegistryAvroFormatFactoryTest.java
- flink-formats/flink-avro-confluent-registry/src/test/java/org/apache/flink/formats/avro/registry/confluent/debezium/DebeziumAvroFormatFactoryTest.java
- flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroRowDataSerializationSchema.java
- flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroSerializationSchema.java
- flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroRowDataDeSerializationSchemaTest.java
- flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroSerializationSchemaTest.java
When using `avro-confluent` and `debezium-avro-confluent` formats with schemas already defined in the Confluent Schema Registry, serialization fails, because Flink uses a default name `record` when converting row types to avro schemas. So if the predefined schema has a different name, the serialization schema will be incompatible with the registered schema due to name mismatch. Check [this description](https://lists.apache.org/thread/5xppmnqjqwfzxqo4gvd3lzz8wzs566zp) to reproduce the error.
- A new optional option `schema` can be defined for `avro-confluent` and `debezium-avro-confluent` formats to ensure that the proper schema is used for serialization and deserialization.
- When schema is defined, it is validated against the table schema and if valid it's used for serialization and …
> [FLINK-31085][formats] Add schema option to confluent registry avro formats

- flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/threadinfo/ThreadInfoRequestCoordinatorTest.java
*`ThreadInfoRequestCoordinatorTest#testShutDown` using two gateways contains a `timeout gateway` but expected all `request futures` not done before `shutdown`. If the timeout reached, this future will be failed, result in `request futures` to be done. This makes the test strongly dependent on the execution order of assertion and timeout, thus causing this test unstable.*
- *Let ThreadInfoRequestCoordinatorTest more comply with the specifications of Junit and AssertJ.*
- *Fix unstable test ThreadInfoRequestCoordinatorTest#testShutDown..*
This change is dedicated to fixing an unstable test. …
> [FLINK-31420][test] Fix unstable test ThreadInfoRequestCoordinatorTest.

- docs/data/sql_functions.yml
- docs/data/sql_functions_zh.yml
This pull request improves the documentation of UNIX_TIMESTAMP for different argument format
- Modify the system functions document
This change is a document change without any test coverage.
> [FLINK-30959][doc] Improve the documentation of UNIX_TIMESTAMP for different argument format

- docs/data/sql_functions.yml
- docs/data/sql_functions_zh.yml
This pull request improves the documentation of UNIX_TIMESTAMP function for different argument formats.
- Modify the system functions document
This change is a document change without any test coverage.
> [FLINK-30959][table][docs] Improve the documentation of UNIX_TIMESTAMP function for different argument formats

- flink-core/src/main/java/org/apache/flink/util/InstantiationUtil.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/JobResourceRequirements.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/JobVertexResourceRequirements.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobgraph/JobResourceRequirementsTest.java
https://issues.apache.org/jira/browse/FLINK-31317
We need to introduce new data structures - JobResourceRequirements and JobVertexResource requirements and the corresponding tooling, that we'll propagate throughout the stack in the upcoming issues.
This doesn't affect any existing code path.
> [FLINK-31317] Introduce JobResourceRequirements and JobVertexResourceRequirements data structures.

- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlToOperationConverter.java
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/TableEnvironmentTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/common/ViewsExpandingTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/hint/OptionsHintTest.scala
`CatalogViewImpl` is deprecated and it is suggested to use `CatalogView` in comments.
The PR replaces `CatalogViewImpl` usages in table-planner with `CatalogView`.
In fact most of the work has been already done within https://issues.apache.org/jira/browse/FLINK-21801
And this PR does replacement for probably missing
- …
> [FLINK-30896][table] Reduce usage of CatalogViewImpl in table-planner

- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/pom.xml
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SQLClientSchemaRegistryITCase.java
- flink-formats/flink-avro-confluent-registry/pom.xml
- flink-formats/flink-sql-avro-confluent-registry/pom.xml
- flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE
- flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/licenses/LICENSE.zstd-jni
* This fixes `ClassNotFoundException` when trying to connect with the SQL Client using Avro Confluent Schema Registry
* Changed the packaging of `flink-sql-avro-confluent-registry` to include all dependencies by default, instead of a case-by-case situation. This avoids that we accidentally miss a dependency when creating a fat JAR.
* Excluded all annotations and quality tools from the `kafka-schema-registry-client`
* Removed the manual inclusion of Guava in the Kafka E2E tests 
This change is already covered by existing tests, such as *SQLClientSchemaRegistryITCase*.
Also verified this locally by:
1. Building this PR
2. Copying the flink-sql-avro, flink-sql-avro-confluent-registry and flink-sql-connector-kafka to the lib folder
3. Running the SQL Client
4. Create a table which connects to …
> [FLINK-31485][Confluent Avro] Change packaging of Avro Confluent Schema Registry 

- flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/operation/OperationManagerTest.java
This is hotfix for the instable test `OperationManagerTest.testCloseOperation`, the reason is the concurrent closeOperation may finished before  awaitOperationTermination(operationHandle) which may encounter an expected error when do getOperation inside it.
move the awaitOperationTermination into the assert thrown block
existing testCloseOperation case …
> [FLINK-31489][sql-gateway] Fix instable OperationManagerTest.testCloseOperation

- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/delegation/ParserImpl.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlCreateTableConverter.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlNodeConvertContext.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlNodeToOperationConversion.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlCreateCatalogConverter.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlNodeConverter.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlNodeConverters.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlDdlToOperationConverterTest.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlDmlToOperationConverterTest.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlNodeToOperationConversionTestBase.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlOtherOperationConverterTest.java
Similar to [FLINK-31368](https://issues.apache.org/jira/browse/FLINK-31368), the  `SqlToOperationConverter` is a bit bloated. This PR is aiming to introduce `SqlNodeConverter` and move conversion logic from `SqlToOperationConverter` in the following PRs. 
- Rename `SqlToOperationConverter` into `SqlNodeToOperationConversion`, because the Converter name may confuse developers regarding the relationship with `SqlNodeConverter` 
- Introduce `SqlNodeConverter` interface and make `SqlToOperationConverter` supports it.
- Migrate the conversion logic of `SqlCreateCatalog` to verify the happy path.  …
> [FLINK-31494][table-planner] Introduce SqlNodeConverter for SqlToOperationConverter

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/KafkaSourceEnumerator.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/enumerator/KafkaEnumeratorTest.java
Backport [FLINK-31319](https://issues.apache.org/jira/browse/FLINK-31319) to release-1.16.
> [FLINK-31319][BP-1.16][connectors/kafka] Fix kafka new source partitionDiscoveryIntervalMs=0 cause bounded source can not quit

- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/ExecutableOperationContextImpl.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ExecutableOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/DropCatalogFunctionOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/DropCatalogOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/DropDatabaseOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/DropOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/DropTableOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/DropTempSystemFunctionOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/DropViewOperation.java
The PR continues the work started at https://github.com/apache/flink/pull/22175
This PR does this for `DropOperation`.
It also removes  methods became unused after merging of https://github.com/apache/flink/pull/22175
Migrate `DropOperation`s to extend ExecutableOperation and move it's execution logic  out from TableEnvironmentImpl.
Migrate `DropOperation`s to extend ExecutableOperation and move it's execution logic  out from TableEnvironmentImpl. …
> [FLINK-31505][table] Move execution logic of DropOperation out from TableEnvironmentImpl

- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/AddPartitionsOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/AlterCatalogFunctionOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/AlterDatabaseOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/AlterOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/AlterPartitionPropertiesOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/AlterTableChangeOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/AlterTableOptionsOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/AlterTableRenameOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/AlterTableSchemaOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/AlterViewAsOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/AlterViewPropertiesOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/AlterViewRenameOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/DropPartitionsOperation.java
The PR continues the work started at https://github.com/apache/flink/pull/22175
This PR does this for `AlterOperation`.
Migrate `AlterOperation`s to extend ExecutableOperation and move it's execution logic  out from TableEnvironmentImpl.
Migrate `AlterOperation`s to extend ExecutableOperation and move it's execution logic  out from TableEnvironmentImpl. …
> [FLINK-31506][table] Move execution logic of AlterOperation out from TableEnvironmentImpl

- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/BatchingStateChangeUploadScheduler.java
not upload empty state changelog file, described in [FLINK-31139](https://issues.apache.org/jira/browse/FLINK-31139).
> [FLINK-31139][state/changelog] not upload empty state changelog file

- docs/content.zh/docs/dev/table/sql/describe.md
- docs/content.zh/docs/dev/table/sql/show.md
- docs/content/docs/dev/table/sql/describe.md
- docs/content/docs/dev/table/sql/show.md
- flink-table/flink-sql-client/src/test/resources/sql/table.q
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/ShowCreateUtil.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlDdlToOperationConverterTest.java
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/catalog/CatalogTableITCase.scala
After a table with column comments created, we would find that the results generated by `show create table` statement lose column comments, and we could make outputs consistent with ddl and more user-friendly.
* get column comment in ShowCreateUtil#getColumnString.
flink-table/flink-sql-client/src/test/resources/sql/table.q …
> [FLINK-30435][table] `SHOW CREATE TABLE` statement shows column comment

- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/LoadModuleOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/UnloadModuleOperation.java
The PR continues the work started at https://github.com/apache/flink/pull/22175
This PR does this for `LoadModule` and `UnloadModule`.
Migrate `LoadModule` and `UnloadModule`s to extend ExecutableOperation and move it's execution logic  out from TableEnvironmentImpl.
Migrate `LoadModule` and `UnloadModule`s to extend ExecutableOperation and move it's execution logic  out from TableEnvironmentImpl. …
> [FLINK-31516][table] Move execution logic of LoadModule and UnloadModule operations out from TableEnvironmentImpl

- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdWindowProperties.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/stats/FlinkStatistic.scala
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/join/WindowJoinTest.xml
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdHandlerTestBase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdWindowPropertiesTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/metadata/MetadataTestUtil.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/join/WindowJoinTest.scala
This pull request fixes the NPE when getting `RelWindowProperties` for `StreamPhysicalGlobalWindowAggregate`.  This is caused by when optimized the following DAG, where the WindowJoin node is the breaking point.  
- Let `FlinkRelMdWindowProperties` support computing window properties for `StreamPhysicalGlobalWindowAggregate`. 
- Add `FlinkRelMdWindowPropertiesTest` to verify the window properties computation on different rel nodes. 
- Add test under`WindowJoinTest` to verify the case. …
> [FLINK-31424][table-planner] Fix NPE produced by multiple sink with local-global window aggregate

- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNSessionFIFOITCase.java
- flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
JIRA: [FLINK-31230] Improve YarnClusterDescriptor memory unit display.
When we use the yarn-session.sh -q command, the basic information of the NM will be printed, and the memory unit is MB. If we have 128GB of memory, it will display 131072 MB. At the same time, if we have multiple NMs, finally totalMemeory doesn't show units.
This jira will use hadoop's StringUtil to format unit output.
Improve memory unit display. …
> [FLINK-31230] Improve YarnClusterDescriptor memory unit display.

- flink-table/flink-sql-client/src/test/resources/sql/catalog_database.q
- flink-table/flink-sql-gateway/src/test/resources/sql/catalog_database.q
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ShowDatabasesOperation.java
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/TableEnvironmentTest.scala
let show databases return sorted results.
return sorted result for sql show databases
sql-client & sql-gateway:
catalog_database.q
> [FLINK-31452][table] Let show databases return sorted results

- docs/content.zh/docs/dev/table/sql-gateway/hiveserver2.md
This PR aims to translate "hiveserver2.md" page of "sql-gateway" into Chinese
- Translate hiveserver2.md of sql-gateway into Chinese …
> [FLINK-31555][docs-zh] Translate "hiveserver2" page of "sql-gateway" into Chinese

- pom.xml
Updating the japicmp base version. Verification of API changes happened in FLINK-31167
> [1.17][FLINK-31568][tests] Updates base version for japicmp check.

- docs/data/sql_functions.yml
- flink-python/docs/reference/pyflink.table/expressions.rst
- flink-python/pyflink/table/expression.py
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CollectionFunctionsITCase.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/ArrayRemoveFunction.java
This is an implementation of ARRAY_REMOVE
ARRAY_REMOVE for Table API and SQL
```
Syntax:
array_remove(array, needle)
Arguments:
Returns:
An ARRAY. If array is NULL, the result is NULL. 
Examples:
SELECT array_remove(array[1, 2, 3, null, 3], 3); 
-- [1,2,null]
```
See also
spark https://spark.apache.org/docs/latest/api/sql/index.html#array_remove
presto https://prestodb.io/docs/current/functions/array.html
postgresql https://www.postgresql.org/docs/12/functions-array.html#ARRAY-FUNCTIONS-TABLE
This change added tests in CollectionFunctionsITCase
Dependencies (does it add or upgrade a dependency): ( no)
The …
> [FLINK-31102][table] Add ARRAY_REMOVE function.

- docs/content.zh/docs/dev/table/sql-gateway/rest.md
This PR aims to translate "rest" page of "sql-gateway" into Chinese
- Translate "rest.md" page of "sql-gateway" into Chinese …
> [FLINK-31556][docs-zh] Translate "rest" page of "sql-gateway" into Chinese

- docs/content.zh/docs/dev/table/sql-gateway/overview.md
This PR aims to translate "Overview" page of "sql-gateway" into Chinese shammon FY A minute ago
- Translate overview.md of sql-gateway into chinese
- If …
> [FLINK-31554][docs-zh] Translate "Overview" page of "sql-gateway" into Chinese

- docs/content.zh/docs/dev/table/sql/explain.md
- docs/content/docs/dev/table/sql/explain.md
This is hotfix the Explain doc, the current syntax for explain statement set should be
```
EXPLAIN [([ExplainDetail[, ExplainDetail]*]) | PLAN FOR] <query_statement_or_insert_statement_or_statement_set>
statement_set:
STATEMENT SET
BEGIN
insert_statement;
...
insert_statement;
END;
```
Fix incorrect description.
This change is a trivial fix and can be verified by the current test. …
> [hotfix][doc][table] Fix the incorrect syntax description for explain statement set

- flink-filesystems/flink-azure-fs-hadoop/pom.xml
- flink-filesystems/flink-gs-fs-hadoop/pom.xml
- flink-filesystems/flink-oss-fs-hadoop/pom.xml
* Removes no longer needed Hadoop relocation rules for Azure/GS/OSS Filesystem implementations
* Updated shade relocation rules
- The S3 file system connector: **yes** 
> [FLINK-31612][Filesystems] Remove no longer necessary Hadoop relocation rules

- flink-filesystems/flink-azure-fs-hadoop/pom.xml
- flink-filesystems/flink-gs-fs-hadoop/pom.xml
- flink-filesystems/flink-oss-fs-hadoop/pom.xml
Unchanged backport of https://github.com/apache/flink/pull/22279
(cherry picked from commit 3924ba85e62f04a0a181007d573cb84e3c09a636)
> [FLINK-31612][BP 1.17][Filesystems] Remove no longer necessary Hadoop relocation

- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMasterGateway.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/utils/TestingJobMasterGateway.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/utils/TestingJobMasterGatewayBuilder.java
Extends the support of querying/updating resource requirements to the JobMaster layer.
> [FLINK-31590] Add mechanics to the JobMaster for handling job resource requirements.

- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/logical/FlinkLogicalOverAggregate.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/RankTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/RankTest.scala
This PR tries to improve the error message since `row_number()` without an order (or order by constants) does not make a lot of sense, and users are confused about it.
Improve the error message in `FlinkLogicalOverAggreate`
- `RankTest` to cover both streaming and batch scenarios. …
> [FLINK-31165][table-planner] Improve the error message for order by clause

- docs/static/generated/rest_v1_dispatcher.yml
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/ConfigurationInfo.java
Ensures the schema generator doesn't pick up List#isEmpty as a property.
This resulted in an invalid schema, as arrays cant have properties.
> [FLINK-31657][rest][docs] Exclude isEmpty property

- flink-table/flink-table-common/src/main/java/org/apache/flink/table/utils/TableSchemaUtils.java
- flink-table/flink-table-common/src/test/java/org/apache/flink/table/utils/TableSchemaUtilsTest.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/catalog/CatalogSchemaTable.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/FlinkCalciteCatalogReader.java
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/schema/LegacyCatalogSourceTable.scala
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/catalog/CatalogConstraintTest.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/catalog/CatalogStatisticsTest.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlNodeToOperationConversionTestBase.java
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/TableEnvironmentTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/rules/logical/PushPartitionIntoLegacyTableSourceScanRuleTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/PartitionableSinkITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/testTableSourceSinks.scala
`CatalogTableImpl` is deprecated and it is suggested to use `CatalogTable` in comments.
The PR replaces `CatalogTableImpl` usages in table-planner with `CatalogTable`.
> [FLINK-31604][table] Reduce usage of CatalogTableImpl in table-planner

- docs/data/sql_functions.yml
- flink-python/docs/reference/pyflink.table/expressions.rst
- flink-python/pyflink/table/expression.py
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CollectionFunctionsITCase.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/ArrayPositionFunction.java
This is an implementation of ARRAY_POSITION
ARRAY_POSITION for Table API and SQL
```
array_position(array, element) - Returns the (1-based) index of the first element of the array as long.
Syntax:
array_position(array, element)
Arguments:
Returns:
Returns the position of the first occurrence of element in the given array as long.
Returns 0 if the given value could not be found in the array.
Returns null if either of the arguments are null
> SELECT array_position(array(3, 2, 1), 1);
3 
```
See also
spark https://spark.apache.org/docs/latest/api/sql/index.html#array_position
postgresql https://www.postgresql.org/docs/12/functions-array.html#ARRAY-FUNCTIONS-TABLE
This change added …
> [FLINK-31602][table] Add built-in ARRAY_POSITION function.

- docs/content.zh/docs/deployment/filesystems/gcs.md
- docs/content/docs/deployment/filesystems/gcs.md
- flink-filesystems/flink-gs-fs-hadoop/pom.xml
- flink-filesystems/flink-gs-fs-hadoop/src/main/resources/META-INF/NOTICE
Upgrade GCS connector to 2.2.11.
Upgrade the [GCS Connector](https://github.com/GoogleCloudDataproc/hadoop-connectors/tree/v2.2.11/gcs) bundled in the Flink distro from version 2.2.3 to 2.2.11. The new release contains multiple bug fixes and enhancements discussed in the [Release Notes](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/v2.2.11/gcs/CHANGES.md). Notable changes include:
* Improved socket timeout handling.
* Trace logging capabilities.
* Fix bug that prevented usage of GCS as a [Hadoop Credential Provider](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/CredentialProviderAPI.html).
* Dependency upgrades.
* Support OAuth2 based client authentication.
This change is already covered by existing tests. These tests pass with the new version. …
> [FLINK-31631][FileSystems] Upgrade GCS connector to 2.2.11.

- docs/data/sql_functions.yml
- flink-python/docs/reference/pyflink.table/expressions.rst
- flink-python/pyflink/table/expression.py
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CollectionFunctionsITCase.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/ArrayDistinctFunction.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/ArrayRemoveFunction.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/ArrayReverseFunction.java
This is an implementation of ARRAY_REVERSE
ARRAY_REVERSE for Table API and SQL
```
array_reverse(array) - Returns an array in reverse order.
Syntax:
array_reverse(array)
Arguments:
Returns:
Returns an array in reverse order.
If the array itself is null, the function will return null.
> SELECT array_reverse(array(1, 2, 2, NULL));
NULL, 2, 2, 1
```
See also
bigquery https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#array_reverse
This change added tests in CollectionFunctionsITCase
Dependencies (does it add or upgrade a dependency): ( no)
The public API, i.e., is any changed …
> [FLINK-31621][table] Add built-in ARRAY_REVERSE function.

- docs/content.zh/docs/connectors/table/filesystem.md
Update the outdated Chinese filesystem connector docs.
Update the outdated Chinese filesystem connector docs.
> [FLINK-31683][docs-zh] Update the outdated Chinese filesystem connector docs

- flink-runtime/src/main/java/org/apache/flink/runtime/blob/FileSystemBlobStore.java
- flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/ClusterEntrypoint.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/FileSystemJobResultStore.java
- flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniCluster.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/DefaultDelegationTokenManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/DelegationTokenManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/NoOpDelegationTokenManager.java
- flink-runtime/src/test/java/org/apache/flink/runtime/blob/FileSystemBlobStoreTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/entrypoint/ClusterEntrypointTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/FileSystemJobResultStoreFileOperationsTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/ExceptionThrowingDelegationTokenReceiver.java
At the moment there are no delegation tokens available when HA services is starting. If the HA services uses an external file system where the authentication type is delegation token based (typically S3) then it throws and exception since there are no credentials.
In this PR I've moved the delegation token manager initialization before HA services and trigger a manual token obtain + local JVM receiver propagation. Additionally deferred base directory creation in `FileSystemBlobStore` and `FileSystemJobResultStore`.
* The delegation token manager initialization moved before HA services and trigger a manual token obtain + local JVM receiver propagation. This is the solution for the job manager side.
* Deferred base directory creation in `FileSystemBlobStore` and `FileSystemJobResultStore`. …
> [FLINK-31656][runtime][security] Obtain delegation tokens early to support external file system usage in HA services

- docs/README.md
- docs/content.zh/docs/connectors/datastream/overview.md
- docs/content.zh/docs/connectors/table/overview.md
- docs/content/docs/connectors/datastream/overview.md
- docs/content/docs/connectors/table/overview.md
- docs/data/sql_connectors.yml
- docs/setup_docs.sh
…to Flink website
Update Flink docs to include MongoDB connector for table/datastream/SQL.
- MongoDB Datastream and Table connector docs added
- Updated SQL download table
- Updated README to pull latest docker image
Run locally and viewed the web build in the browser.
- If yes, how …
> [FLINK-31692][Connectors/MongoDB] Integrate MongoDB connector docs into the Flink website (1.17)

- docs/README.md
- docs/content.zh/docs/connectors/datastream/overview.md
- docs/content.zh/docs/connectors/table/overview.md
- docs/content/docs/connectors/datastream/overview.md
- docs/content/docs/connectors/table/overview.md
- docs/data/sql_connectors.yml
- docs/setup_docs.sh
…to Flink website
Update Flink docs to include MongoDB connector for table/datastream/SQL.
- MongoDB Datastream and Table connector docs added
- Updated SQL download table
- Updated README to pull latest docker image
Run locally and viewed the web build in the browser.
- If yes, how …
> [FLINK-31692][Connectors/MongoDB] Integrate MongoDB connector docs into the Flink website (1.16)

- docs/data/sql_connectors.yml
- docs/setup_docs.sh
- Update AWS connectors docs build to pull from the 4.1.0 tag
- Update AWS connectors docs build to pull from the 4.1.0 tag
Built locally and verified in local browser
- If yes, how is the feature documented? n/a
> [FLINK-31703][Connectors/AWS][docs] Update AWS connector docs to v4.1.0 (1.17)

- docs/data/sql_connectors.yml
- docs/setup_docs.sh
- Update AWS connectors docs build to pull from the 4.1.0 tag
- Update AWS connectors docs build to pull from the 4.1.0 tag
Built locally and verified in local browser
- If yes, how is the feature documented? n/a
> [FLINK-31703][Connectors/AWS][docs] Update AWS connector docs to v4.1.0 (1.18)

- docs/data/sql_connectors.yml
- docs/setup_docs.sh
- Update AWS connectors docs build to pull from the 4.1.0 tag
- Update AWS connectors docs build to pull from the 4.1.0 tag
Built locally and verified in local browser
- If yes, how is the feature documented? n/a
> [FLINK-31703][Connectors/AWS][docs] Update AWS connector docs to v4.1.0 (1.16)

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPool.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPoolTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/TestingBufferListener.java
Backport FLINK-31293 to release-1.16.
> [BP-1.16][FLINK-31293] LocalBufferPool request overdraft buffer only when no available buffer and pool size is reached.

- tools/ci/alibaba-mirror-settings.xml
- tools/ci/google-mirror-settings.xml
* Conjars repository doesn't exist anymore and Flink doesn't need it, so let's remove all references from Conjars in the codebase
* Cleaned up Maven mirror for Azure and Alibaba CI
> [FLINK-31705][Build System] Remove Conjars as Maven mirror

- docs/layouts/shortcodes/generated/rest_v1_dispatcher.html
- docs/static/generated/rest_v1_dispatcher.yml
- flink-runtime-web/src/test/resources/rest_api_v1.snapshot
- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/DispatcherRestEndpoint.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/JobResourceRequirementsHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/JobResourceRequirementsUpdateHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/JobResourceRequirementsBody.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/JobResourceRequirementsHeaders.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/JobResourcesRequirementsUpdateHeaders.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/messages/job/JobResourceRequirementsBodyTest.java
https://issues.apache.org/jira/browse/FLINK-31469
This PR exposes JobResourceRequirements via REST API.
New endpoints are going to be covered by the integration tests that will be introduced at https://issues.apache.org/jira/browse/FLINK-31470.
> [FLINK-31469] Allow setting JobResourceRequirements through REST API.

- docs/layouts/shortcodes/generated/python_configuration.html
- flink-clients/src/main/java/org/apache/flink/client/cli/CliFrontendParser.java
- flink-clients/src/main/java/org/apache/flink/client/cli/ProgramOptionsUtils.java
- flink-python/src/main/java/org/apache/flink/python/PythonOptions.java
- flink-python/src/main/java/org/apache/flink/python/util/PythonDependencyUtils.java
- flink-python/src/test/java/org/apache/flink/client/cli/PythonProgramOptionsTest.java
- flink-python/src/test/java/org/apache/flink/python/PythonOptionsTest.java
- flink-python/src/test/java/org/apache/flink/python/util/PythonDependencyUtilsTest.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliOptionsParser.java
- flink-table/flink-sql-client/src/test/resources/cli/all-mode-help.out
- flink-table/flink-sql-client/src/test/resources/cli/embedded-mode-help.out
Add support for new cli option -py.pythonpath. this config will point to path on the instances where python is installed.
covered in UT
- `-pypythonPath` for command line option.
- Dependencies (does it add or upgrade a dependency): (yes / no) no 
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no) yes
- Does this pull request introduce a new feature? (yes / no) no  …
> [FLINK-31214][python] Add support for new cli option -py.pythonpath

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/sort/MultiInputSortingDataInput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/sort/SortingDataInput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/StreamMultipleInputProcessorFactory.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/StreamTwoInputProcessorFactory.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/OneInputStreamTask.java
Backport FLINK-30989 to release-1.16.
> [BP-1.16][FLINK-30989][runtime] Some config options related to sorting and spilling are not valid.

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/sort/MultiInputSortingDataInput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/sort/SortingDataInput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/StreamMultipleInputProcessorFactory.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/StreamTwoInputProcessorFactory.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/OneInputStreamTask.java
Backport FLINK-30989 to release-1.17.
> [BP-1.17][FLINK-30989][runtime] Some config options related to sorting and spilling are not valid.

- docs/data/sql_connectors.yml
- docs/setup_docs.sh
*In the [doc](https://nightlies.apache.org/flink/flink-docs-master/docs/connectors/datastream/elasticsearch/), It still use "flink-version" for flink-connector-elastiacsearch instead of the version in the external repository.*
- *Using v3.0.0-docs branch for es connector docs build.*
Manually test.
> [FLINK-31670][doc] Using v3.0.0-docs branch for es connector docs build.

- docs/data/sql_connectors.yml
- docs/setup_docs.sh
*Pulsar docs are pulled from the main [branch](https://github.com/apache/flink/blob/release-1.17/docs/setup_docs.sh#L49). This is dangerous for final versions since we may include features in the docs that are not supported. Update Pulsar to pull from a dedicated branch or tag.*
- *Bump pulsar doc to v3.0.0-docs branch.*
Manual verification locally.
> [FLINK-31704][Connectors/Pulsar] Pulsar docs should be pulled from dedicated branch

- docs/static/generated/rest_v1_dispatcher.yml
- flink-docs/src/main/java/org/apache/flink/docs/rest/OpenApiSpecGenerator.java
- flink-docs/src/test/java/org/apache/flink/docs/rest/OpenApiSpecGeneratorTest.java
- flink-docs/src/test/java/org/apache/flink/docs/rest/RestAPIDocGeneratorTest.java
- flink-docs/src/test/java/org/apache/flink/docs/rest/data/BaseTestMessageHeaders.java
- flink-docs/src/test/java/org/apache/flink/docs/rest/data/clash/inner/TestNameClashingMessageHeaders1.java
- flink-docs/src/test/java/org/apache/flink/docs/rest/data/clash/inner/TestNameClashingMessageHeaders2.java
- flink-docs/src/test/java/org/apache/flink/docs/rest/data/clash/top/pkg1/ClashingRequestBody.java
- flink-docs/src/test/java/org/apache/flink/docs/rest/data/clash/top/pkg1/TestTopLevelNameClashingMessageHeaders1.java
- flink-docs/src/test/java/org/apache/flink/docs/rest/data/clash/top/pkg2/ClashingRequestBody.java
- flink-docs/src/test/java/org/apache/flink/docs/rest/data/clash/top/pkg2/TestTopLevelNameClashingMessageHeaders2.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/JobVertexTaskManagersInfo.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/checkpoints/CheckpointingStatistics.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/checkpoints/TaskCheckpointStatisticsWithSubtaskDetails.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/JobDetailsInfo.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/util/DocumentingRestEndpoint.java
Fixes 5 cases where a name clash caused certain classes to not be documented properly. Name clashes were silently ignored by the generator.
The offending classes are now annotated to provide a unique name, and the generator was enhanced to detect such clashes.
> [FLINK-31733][docs] Fix/Detect OpenAPI model name clashes 

- flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskTest.java
Fixing testInterruptibleSharedLockInInvokeAndCancel test
- Increased TASK_CANCELLATION_TIMEOUT for testInterruptibleSharedLockInInvokeAndCancel since it looks that on the overloaded machine the current timeout is too small …
> [FLINK-30844][runtime] Increased TASK_CANCELLATION_TIMEOUT for testInterruptibleSharedLockInInvokeAndCancel

- docs/layouts/shortcodes/generated/rest_v1_dispatcher.html
- docs/static/generated/rest_v1_dispatcher.yml
- flink-runtime-web/src/test/resources/rest_api_v1.snapshot
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/JobDetailsHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/JobPlanInfo.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/JobDetailsInfo.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/messages/job/JobDetailsInfoTest.java
Fixes an issue where `plan` field of the JobDetailsInfo was documented as a string, when in fact we write the json plan as a raw object.
> [FLINK-31735][docs] Document 'plan' field as object

- docs/static/generated/rest_v1_dispatcher.yml
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/FlameGraphTypeQueryParameter.java
Generating a client with the openapi generators causes compile errors because the generated file imports java.reflect.Type, but also the generated "Type" model.
For convenience it would be neat to give this enum a slightly different name, because working around this issue is surprisingly annoying.
> [FLINK-31738] Prevent 'Type' name clash in generated clients

- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ArchivedExecutionGraph.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMasterGateway.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ArchivedExecutionGraphTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/utils/TestingJobMasterGateway.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/utils/TestingJobMasterGatewayBuilder.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
Include all JobVertex-level information in the sparse execution graph, created by the Adaptive Scheduler when in the WaitingForResources state, like the vertex id/name and the maxParallelism.
This reduces the difference in behavior between the schedulers.
This also removes the functional need for the recently introduced `JobMasterGaterway#getMaxParallelismPerVertex`.
I propose to remove this method.
We could keep it though if we are concerned that the creation of the sparse EG is too expensive.
> [FLINK-31744] Include JobVertex info in sparse EG 

- docs/data/sql_functions.yml
- docs/data/sql_functions_zh.yml
The function TO_TIMESTAMP is independent of timezone. Therefore, we need to remove the misleading description that refers to it being 'under the UTC+0'.
change the function description. 
*Yes*
>     [hotfix][doc] Fix the incorrect description for TO_TIMESTAMP function

- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedLeaderService.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionService.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/LeaderElectionEventHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/LeaderElectionService.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionServiceTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingLeaderElectionService.java
PR order:
This PR is about hardening the `LeaderElectionService.stop()` contract.
The current implementations of LeaderElectionService do not implement the stop() call consistently. Some (e.g. [StandaloneLeaderElectionService](https://github.com/apache/flink/blob/c6997c97c575d334679915c328792b8a3067cfb5/flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/StandaloneLeaderElectionService.java#L53) call revoke on the LeaderContender) whereas others don't (e.g. [DefaultLeaderElectionService](https://github.com/apache/flink/blob/6e1caa390882996bf2d602951b54e4bb2d9c90dc/flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionService.java#L96)). The [MultipleComponentLeaderElectionService](https://github.com/apache/flink/blob/0290715a57b8d243586ab7 …
> [FLINK-30765][runtime] Aligns the LeaderElectionService.stop() contract

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/StatefulJobSnapshotMigrationITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/StatefulJobWBroadcastStateMigrationITCase.java
- flink-tests/src/test/scala/org/apache/flink/api/scala/migration/StatefulJobSavepointMigrationITCase.scala
- flink-tests/src/test/scala/org/apache/flink/api/scala/migration/StatefulJobWBroadcastStateMigrationITCase.scala
FLINK-31593 revealed some non-determinism in the checkpoint generation for migration tests. The actual issue is covered in FLINK-31766. As a workaround, we're disabling changelog backend for now.
* Went through any still existing tests based on 369088f0 and disabled changelog backend for RocksDB backend-based tests only.
Test data can be generated and verified for those tests. …
> [FLINK-31765][runtime][test] Disable changelog backend for RocksDB migration tests

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStore.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStoreTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/persistence/StateHandleStore.java
- flink-runtime/src/main/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStore.java
- flink-runtime/src/test/java/org/apache/flink/runtime/persistence/TestingStateHandleStore.java
- flink-runtime/src/test/java/org/apache/flink/runtime/zookeeper/ZooKeeperStateHandleStoreTest.java
*Remove releaseAndTryRemoveAll in StateHandleStore.*
- *Remove releaseAndTryRemoveAll in StateHandleStore.*
> [FLINK-29334][runtime] Remove releaseAndTryRemoveAll in StateHandleStore

- docs/content.zh/docs/dev/table/types.md
- docs/content/docs/dev/table/types.md
Fixes typo in the documentation for declaring a `ROW` with the parethesis.
> [hotfix] [docs] Fix `ROW()` decleration syntax

- flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskTest.java
These changes fix the exception from TestInvokableCorrect#cancel which is 1) incorrect 2) doesn't really fail test
- *Explicit assert for the task cancelation in tests*
- *Removed the exception from TestInvokableCorrect#cancel since in some test it isn't correct*
- …
> [FLINK-30852][runtime] Checking task cancelation explicitly rather than failing the cancel method

- docs/setup_docs.sh
*Docs for externalized connectors should point to the branch where that version of the connector doc are published, otherwise documentation fixes are not visible until a new release is made. After this, we can safely delete all dedicated doc branches.*
- *Track stable branch of externalized connector instead of specific release tag.* …
> [FLINK-31779][docs] Track stable branch of externalized connector instead of specific release tag

- flink-annotations/src/main/java/org/apache/flink/FlinkVersion.java
This is a trivial fix for the `FlinkVersion` enum, which should start with lowercase.
Change `V1_18` to `v1_18`.
This change is a trivial fix without any test coverage.
> [hotfix][annotations] Fix the Flink version enum for v1.18

- docs/setup_docs.sh
Backport FLINK-31779 to release-1.17
> [BP-1.17][FLINK-31779][docs] Track stable branch of externalized connector instead of specific release tag

- docs/setup_docs.sh
Backport FLINK-31779 to release-1.16.
> [BP-1.16][FLINK-31779][docs] Track stable branch of externalized connector instead of specific release tag

- docs/content.zh/docs/deployment/ha/kubernetes_ha.md
- docs/content.zh/docs/deployment/ha/zookeeper_ha.md
- docs/content.zh/docs/deployment/resource-providers/native_kubernetes.md
- docs/content/docs/deployment/ha/kubernetes_ha.md
- docs/content/docs/deployment/ha/zookeeper_ha.md
- docs/content/docs/deployment/resource-providers/native_kubernetes.md
*After FLINK-29372, we add suffix for some config option key, this will cause the link point to configuration doc broken.*
- *Fix broken links caused by FLINK-29372.*
- *Using `kubernetes` instead of `KubernetesHaServicesFactory` as `high-availability.type` for `kubernetes_ha doc`.* …
> [hotfix][docs] Fix some broken links in docs

- docs/content.zh/docs/ops/monitoring/back_pressure.md
- docs/content/docs/ops/monitoring/back_pressure.md
This pull request fixes the incorrect metric name of `backPressuredTimeMsPerSecond ` for the doc .
Change incorrect metric name `backPressureTimeMsPerSecond ` to `backPressuredTimeMsPerSecond ` …
> [hotfix][doc] fix incorrect backPressure metric name

- flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/operation/OperationExecutor.java
*Currently, method OperationExecutor#executeStatement in sql client will wrap currently with `sessionContext.getSessionState().resourceManager.getUserClassLoader()`. Actually, it's not necessary.*
*It'll will cause the exception `Trying to access closed classloader. Please check if you store xxx` after quiting sql client. 
The reason is in `ShutdownHookManager`, it will register a hook after jvm shutdown. In `ShutdownHookManager`, it will
create `Configuration`. It will then access `Thread.currentThread().getContextClassLoader()` which is `FlinkUserClassLoader`, the `FlinkUserClassLoader` has been closed before. So, it'll then cause `Trying to access closed classloader` exception.*
- *OperationExecutor is no longer set context classloader when executing statement.*
This change is a …
> [FLINK-31398][sql-gateway] OperationExecutor is no longer set context classloader when executing statement.

- tools/azure-pipelines/e2e-template.yml
E2e CI builds on azure are sometimes complaining about lack of disk space while downloading cached resources.
- Run the script which frees up disk space before the caching step.
CI Output
> [FLINK-31834][Azure] Free up disk space before caching

- docs/content/docs/deployment/security/security-delegation-token.md
- flink-filesystems/flink-s3-fs-base/src/main/java/org/apache/flink/fs/s3/common/AbstractS3FileSystemFactory.java
- flink-filesystems/flink-s3-fs-base/src/main/java/org/apache/flink/fs/s3/common/token/AbstractS3DelegationTokenProvider.java
- flink-filesystems/flink-s3-fs-base/src/main/java/org/apache/flink/fs/s3/common/token/AbstractS3DelegationTokenReceiver.java
- flink-filesystems/flink-s3-fs-base/src/main/java/org/apache/flink/fs/s3/common/token/DynamicTemporaryAWSCredentialsProvider.java
- flink-filesystems/flink-s3-fs-base/src/test/java/org/apache/flink/fs/s3/common/token/AbstractS3DelegationTokenProviderTest.java
- flink-filesystems/flink-s3-fs-base/src/test/java/org/apache/flink/fs/s3/common/token/AbstractS3DelegationTokenReceiverTest.java
- flink-filesystems/flink-s3-fs-base/src/test/java/org/apache/flink/fs/s3/common/token/DynamicTemporaryAWSCredentialsProviderTest.java
- flink-filesystems/flink-s3-fs-hadoop/src/main/java/org/apache/flink/fs/s3hadoop/token/S3HadoopDelegationTokenProvider.java
- flink-filesystems/flink-s3-fs-hadoop/src/main/java/org/apache/flink/fs/s3hadoop/token/S3HadoopDelegationTokenReceiver.java
- flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/services/org.apache.flink.core.security.token.DelegationTokenProvider
- flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/services/org.apache.flink.core.security.token.DelegationTokenReceiver
- flink-filesystems/flink-s3-fs-presto/src/main/java/org/apache/flink/fs/s3presto/token/S3PrestoDelegationTokenProvider.java
- flink-filesystems/flink-s3-fs-presto/src/main/java/org/apache/flink/fs/s3presto/token/S3PrestoDelegationTokenReceiver.java
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/services/org.apache.flink.core.security.token.DelegationTokenProvider
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/services/org.apache.flink.core.security.token.DelegationTokenReceiver
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/DefaultDelegationTokenManager.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/DefaultDelegationTokenManagerTest.java
At the moment it's not possible to add `flink-s3-fs-hadoop` and `flink-s3-fs-presto` plugins at the same time.
* Now both the plugins are having a provider with a different name
* Fixed bad error message in the `DefaultDelegationTokenManager`
* Added a warning message when multiple providers are loaded with the same prefix.
Existing + additional unit tests. …
> [FLINK-31839][filesystems] Fix flink-s3-fs-hadoop and flink-s3-fs-presto plugin collision

- docs/content/docs/deployment/security/security-delegation-token.md
- flink-filesystems/flink-s3-fs-base/src/main/java/org/apache/flink/fs/s3/common/AbstractS3FileSystemFactory.java
- flink-filesystems/flink-s3-fs-base/src/main/java/org/apache/flink/fs/s3/common/token/AbstractS3DelegationTokenProvider.java
- flink-filesystems/flink-s3-fs-base/src/main/java/org/apache/flink/fs/s3/common/token/AbstractS3DelegationTokenReceiver.java
- flink-filesystems/flink-s3-fs-base/src/main/java/org/apache/flink/fs/s3/common/token/DynamicTemporaryAWSCredentialsProvider.java
- flink-filesystems/flink-s3-fs-base/src/test/java/org/apache/flink/fs/s3/common/token/AbstractS3DelegationTokenProviderTest.java
- flink-filesystems/flink-s3-fs-base/src/test/java/org/apache/flink/fs/s3/common/token/AbstractS3DelegationTokenReceiverTest.java
- flink-filesystems/flink-s3-fs-base/src/test/java/org/apache/flink/fs/s3/common/token/DynamicTemporaryAWSCredentialsProviderTest.java
- flink-filesystems/flink-s3-fs-hadoop/src/main/java/org/apache/flink/fs/s3hadoop/token/S3HadoopDelegationTokenProvider.java
- flink-filesystems/flink-s3-fs-hadoop/src/main/java/org/apache/flink/fs/s3hadoop/token/S3HadoopDelegationTokenReceiver.java
- flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/services/org.apache.flink.core.security.token.DelegationTokenProvider
- flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/services/org.apache.flink.core.security.token.DelegationTokenReceiver
- flink-filesystems/flink-s3-fs-presto/src/main/java/org/apache/flink/fs/s3presto/token/S3PrestoDelegationTokenProvider.java
- flink-filesystems/flink-s3-fs-presto/src/main/java/org/apache/flink/fs/s3presto/token/S3PrestoDelegationTokenReceiver.java
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/services/org.apache.flink.core.security.token.DelegationTokenProvider
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/services/org.apache.flink.core.security.token.DelegationTokenReceiver
- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/DefaultDelegationTokenManager.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/DefaultDelegationTokenManagerTest.java
At the moment it's not possible to add `flink-s3-fs-hadoop` and `flink-s3-fs-presto` plugins at the same time.
* Now both the plugins are having a provider with a different name
* Fixed bad error message in the `DefaultDelegationTokenManager`
* Added a warning message when multiple providers are loaded with the same prefix.
Existing + additional unit tests. …
> [BP-1.17][FLINK-31839][filesystems] Fix flink-s3-fs-hadoop and flink-s3-fs-presto plugin collision

- flink-architecture-tests/flink-architecture-tests-test/pom.xml
- flink-architecture-tests/flink-architecture-tests-test/src/main/java/org/apache/flink/architecture/rules/ITCaseRules.java
- flink-connectors/flink-connector-files/archunit-violations/f5e3e868-8d92-4258-9654-a605dc9c550f
- flink-connectors/flink-connector-hive/archunit-violations/26d337fc-45c4-4d03-a84a-6692c37fafbc
- flink-connectors/flink-connector-kafka/archunit-violations/97dda445-f6bc-43e2-8106-5876ca0cd052
- flink-formats/flink-avro/archunit-violations/337c411e-1885-4f85-8070-aabe3638eb43
- flink-formats/flink-csv/archunit-violations/41d59928-b3fa-4aa2-8b1b-221c1031bd0c
- flink-formats/flink-json/archunit-violations/62c5e4e5-2b0e-41ed-a268-ee33d5edd162
- flink-formats/flink-orc/archunit-violations/8a4ac4b1-94ba-4a1d-a639-b2bd22868374
- flink-formats/flink-parquet/archunit-violations/1b8e145e-3f0a-4415-b463-37a87dd0a998
Adjusts the ITCaseRules to treat the `MiniClusterEnvironment` like a mini cluster.
> [FLINK-31804] Allow MiniClusterTestEnvironment

- flink-tests/src/test/java/org/apache/flink/test/recovery/UpdateJobResourceRequirementsRecoveryITCase.java
This fixes a race condition where HA data might have been accidentally cleaned up due to job transition to the terminal state.
https://issues.apache.org/jira/browse/FLINK-31803
> [FLINK-31803] Harden UpdateJobResourceRequirementsRecoveryITCase.

- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/DefaultJobMasterServiceProcessTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/factories/TestingJobMasterServiceFactory.java
https://issues.apache.org/jira/browse/FLINK-31723
This test has never worked with the AdaptiveScheduler, because `initializeOnMaster` is run during a different job state.
This test's purpose is to test the behavior of `JobMasterServiceLeadershipRunner,` not of the underlying scheduler implementation, so the fix is to make the test scheduler independent.
> [FLINK-31723] Fix DispatcherTest#testCancellationDuringInitialization to not make assumptions about an underlying scheduler implementation.

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointMetricsBuilder.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointMetricsTest.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorImpl.java
Correct the unaligned checkpoint type after aligned barrier timeout to unaligned barrier on PipelinedSubpartition.
Correct the unaligned checkpoint type after aligned barrier timeout to unaligned barrier on PipelinedSubpartition.
This change improved old tests and can be verified as follows:
- PipelinedSubpartitionTest#testConsumeTimeoutableCheckpointBarrierQuickly
- PipelinedSubpartitionTest#testTimeoutAlignedToUnalignedBarrier
- The S3 …
> [FLINK-31588][checkpoint] Correct the unaligned checkpoint type after aligned barrier timeout to unaligned barrier on PipelinedSubpartition

- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/SourceMetricsITCase.java
- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/mocks/MockRecordEmitter.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceOperatorStreamTask.java
This pull request fixes the bug that the metric numRecordsOut is increased twice in `SourceOperatorStreamTask` and in `ChainingOutput`, which was introduced in #21579.
- Removes the process to increase numRecordsOut in `SourceOperatorStreamTask`.
- Modifies `SourceMetricsITCase` to verify the correctness of this metric on SourceOperator.
The correctness of the changes in this pull request is covered by the test class `SourceMetricsITCase`. …
> [FLINK-31752] Fix SourceOperator numRecordsOut duplicate bug

- docs/layouts/shortcodes/py_connector_download_link.html
- docs/layouts/shortcodes/py_download_link.html
Backport FLINK-31799 to release-1.16.
> [BP-1.16][FLINK-31799] [docs] Introduce py_connector_download_link shortcode for externalized connectors.

- docs/layouts/shortcodes/py_connector_download_link.html
- docs/layouts/shortcodes/py_download_link.html
Backport FLINK-31799 to release-1.17.
> [BP-1.17][FLINK-31799][docs] Introduce py_connector_download_link shortcode for externalized connectors.

- docs/layouts/shortcodes/py_connector_download_link.html
- docs/layouts/shortcodes/py_download_link.html
*Each externalized connector has its own yml file to manage the url of uber jar. We should introduce a new shortcode to support this.*
- *Introduce `py_connector_download_link shortcode` for externalized connectors.*
Manually verified
> [FLINK-31799][docs] Python connector download link should refer to the url defined in externalized repository

- flink-core/src/main/java/org/apache/flink/util/NetUtils.java
- flink-core/src/test/java/org/apache/flink/util/NetUtilsTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskManagerRunnerConfigurationTest.java
Increasing the usability of Flink with JDK 17: sun.net.util.IPAddressUtil is not exported by the JDK, i.e. --add-opens configuration is needed for making use of it.
- Replace usage of `sun.net.util.IPAddressUtil` with `com.google.common.net.InetAddresses` in production and testing code.
- Complement coverage of unit test case when `host` is `null`.
This change is already covered by existing tests, such as *NetUtilsTest* and `TaskManagerRunnerConfigurationTest`. …
> [FLINK-30478] [core] Avoiding dependence on JDK-internal code

- flink-runtime-web/web-dashboard/package-lock.json
* Update engine.io
* Updated package-lock.json
> [FLINK-30174][Web Frontend] Bump engine.io from 6.2.0 to 6.2.1

- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogWriter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/inmemory/InMemoryStateChangelogWriter.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/changelog/inmemory/StateChangelogStorageTest.java
Refactor checkState() to WARN of StateChangelogWriter to avoid confusing IllegalException.
- Replace `checkState()` with `LOG.warn()` when StateChangelogWriter is closed. …
> [FLINK-30729][state/changelog] Refactor checkState() to WARN of StateChangelogWriter to avoid confusing IllegalException

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointMetricsBuilder.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointMetricsTest.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorImpl.java
> [FLINK-31588][checkpoint] Correct the unaligned checkpoint type based on the bytesPersistedDuringAlignment

- flink-core/src/main/java/org/apache/flink/api/common/operators/SingleInputOperator.java
- flink-fs-tests/src/test/java/org/apache/flink/hdfstests/ContinuousFileProcessingTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/AbstractThreadsafeJobResultStore.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/KeyGroupRangeAssignment.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/StateBackend.java
Fix some typo in java doc, comments and assertion message
> [FLINK-31900] Fix some typo in java doc, comments and assertion message

- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/LocalInputPreferredSlotSharingStrategy.java
FLINK-22767 introduced `availableGroupsForJobVertex` to improve the performance during task to slot scheduler.
After FLINK-22767, the `executionSlotSharingGroups`[2] is unused, and it can be removed.
[1] https://github.com/apache/flink/blob/f9b3e0b7bc0432001b4a197539a0712b16e0b33b/flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/LocalInputPreferredSlotSharingStrategy.java#L153
[2] https://github.com/apache/flink/blob/f9b3e0b7bc0432001b4a197539a0712b16e0b33b/flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/LocalInputPreferredSlotSharingStrategy.java#L136
Remove the unused field inside ExecutionSlotSharingGroupBuilder.
- The public …
> [FLINK-31907][coordination] Remove the unused field inside ExecutionSlotSharingGroupBuilder

- docs/content.zh/docs/libs/cep.md
- docs/content/docs/libs/cep.md
fix the typo in docs/content/docs/libs/cep.md
fix the typo in docs/content.zh/docs/libs/cep.md
> [FLINK-31881][docs] Fix the confusion in the Chinese documentation page of Flink official CEP, and add the Scala code of timesOrMore.

- flink-python/pyflink/pyflink_gateway_server.py
Java options need to be passed as an array, not as a single string.
> [FLINK-31915][python] Pass java opts as array

- flink-end-to-end-tests/pom.xml
- pom.xml
> [FLINK-31912][build] Upgrade bytebuddy to 1.14.4

- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/SqlClientTest.java
Simplifies the construction of the rest address. On Java 17 this fails because the InetSocketAddress toString representation contained "\<host>/unresolved:\<port>" .
> [FLINK-31911][sql][tests] Fix address construction

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/DataStreamSink.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGeneratorTest.java
When turning on Flink reactive mode, it is suggested to convert all `setParallelism` calls to `setMaxParallelism`, [docs](https://nightlies.apache.org/flink/flink-docs-release-1.17/docs/deployment/elastic_scaling/#configuration).
With the current implementation of the `DataStreamSink`, only the [`setParallelism` function](https://github.com/apache/flink/blob/master/flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/DataStreamSink.java#L172-L181) of the [`Transformation` class is exposed - `Transformation` also has the `setMaxParallelism` function which is not exposed](https://github.com/apache/flink/blob/master/flink-core/src/main/java/org/apache/flink/api/dag/Transformation.java#L248-L285).
This PR exposes the `setMaxParallelism` function on any `DataStreamSink` …
> [FLINK-31873][API / DataStream] Add method setMaxParallelism to DataStreamSink.

- flink-core/src/main/java/org/apache/flink/api/common/operators/Keys.java
- flink-core/src/test/java/org/apache/flink/api/common/operators/ExpressionKeysTest.java
Remove an unnecessary powermock/reflection usage that would fail out-of-the-box on Java 17.
> [FLINK-31933][core][tests] Remove reflective access

- tools/azure-pipelines/e2e-template.yml
- tools/ci/ubuntu-mirror-list.txt
This is a 1.16 backport PR for parent PR https://github.com/apache/flink/pull/21873
> [BP-1.16][FLINK-30921][ci] Adds mirrors instead of relying on a single source or Ubuntu packages

- tools/azure-pipelines/e2e-template.yml
- tools/ci/ubuntu-mirror-list.txt
Trying to integrate mirrors in case the azure mirror is not available. Original source is https://github.com/actions/runner-images/issues/7048#issuecomment-1419426054
Creates `mirror.txt` and integrate it into the `/etc/apt/sources.list`
CI run succeeds
> [FLINK-30921][ci] Adds mirrors instead of relying on a single source for Ubuntu packages

- flink-runtime-web/web-dashboard/src/app/pages/job/configuration/job-configuration.component.less
From JIRA description:
>Currently one can use env.getConfig().setGlobalJobParameters(...) for setting user configurations. It will also show up in the Web UI > Running Jobs > Job Configuration > User Configuration section. This is nice so users can confirm the user configuration (key/value pair) gets populated.
>
>However, it prints the plain string which does not work well with values that contains whitespaces and line breaks. For example, we have some prettified JSON configuration and sometimes formatted SQL statements in those configurations, and it's showing in a compacted HTML format - not human readable.
>
>I propose we keep the whitespaces and lines for this "User Configuration" section in the Web UI. The implementation can be as simple as adding style="white-space: pre-wrap;" to …
> [FLINK-31110][web] Show "User Configuration" preserving lines and whitespaces

- flink-core/src/main/java/org/apache/flink/core/fs/EntropyInjector.java
- flink-core/src/test/java/org/apache/flink/core/fs/EntropyInjectorTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStreamFactory.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStreamFactoryTest.java
This reverts commit 5c0a53534edb34eeee4bbff09fc5ea4dcc5983c8.
API change causes [build failures](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=48655&view=logs&j=52b61abe-a3cc-5bde-cc35-1bbe89bb7df5&t=54421a62-0c80-5aad-3319-094ff69180bb&l=1316).
> [BP-1.17][FLINK-31984] Revert "[FLINK-31984][fs][checkpoint] Savepoint should be relocatable if entropy injection is not effective"

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPool.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/NetworkBufferPool.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/metrics/NettyShuffleMetricFactory.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPoolTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/NetworkBufferPoolTest.java
Backport FLINK-31764 to release-1.17.
> [BP-1.17][FLINK-31764][runtime] Get rid of numberOfRequestedOverdraftMemorySegments in LocalBufferPool.

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPool.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/NetworkBufferPool.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/metrics/NettyShuffleMetricFactory.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPoolTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/NetworkBufferPoolTest.java
*After [FLINK-31763](https://issues.apache.org/jira/browse/FLINK-31763), we don't need the specific field `numberOfRequestedOverdraftMemorySegments` to record the overdraft buffers has been requested anymore since we regard all buffers exceeding the `currentPoolSize` as overdraft.*
- *Introduce getNumberOfRequestedMemorySegments and rename the old one to a more appropriate name.*
- *Get rid of numberOfRequestedOverdraftMemorySegments in LocalBufferPool.*
This change is already covered by existing tests in `LocalBufferPoolTest`.
- The runtime per-record code paths (performance sensitive): per-buffer …
> [FLINK-31764][runtime] Get rid of numberOfRequestedOverdraftMemorySegments in LocalBufferPool

- flink-table/flink-sql-jdbc-driver/src/main/java/org/apache/flink/table/jdbc/FlinkConnection.java
- flink-table/flink-sql-jdbc-driver/src/main/java/org/apache/flink/table/jdbc/FlinkStatement.java
- flink-table/flink-sql-jdbc-driver/src/test/java/org/apache/flink/table/jdbc/FlinkStatementTest.java
This PR aims to close all statements when a specified connection is closed in jdbc driver.
- Add statement list in flink connection
- Remove the statement from connection when it is closed
- Close all statements when the connection is closed
- Added test case FlinkStatementTest.testCloseAllStatements
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no / don't …
> [FLINK-31546][jdbc-driver] Close all statements when connection is closed

- flink-core/src/main/java/org/apache/flink/util/concurrent/FutureUtils.java
- flink-core/src/test/java/org/apache/flink/util/concurrent/FutureUtilsTest.java
I ran into an issue in FLINK-31773 where a `NullPointerException` was thrown by the error handling code (because the contender wasn't set, anymore). That one went unnoticed the the corresponding unit tests because we don't handle errors in the error handling code. This PR adds this code path.
* Migrates `FutureUtilsTest` from JUnit4/Hamcrest to JUnit5/AssertJ (separate commit)
* Adds fallback error handling to `FutureUtils.handleUncaughtException`
* a helper method was added that allows configuring the fallback exception handler
* a test was added covering the scenario …
> [FLINK-32029][core] Adds fallback error handling to FutureUtils.handleUncaughtException

- docs/content.zh/docs/deployment/config.md
- docs/content/docs/deployment/config.md
- *fix the typo in docs/content/docs/deployment/config.md*
> [FLINK-29841] fix the typo in docs/content/docs/deployment/config.md

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/RecordWriterOutput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/BroadcastingOutputCollector.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/ChainingOutput.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/CopyingBroadcastingOutputCollector.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/OperatorChain.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/OutputWithChainingCheck.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/MultipleInputStreamTaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/OneInputStreamTaskTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/OperatorChainTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamConfigChainer.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/TwoInputStreamTaskTest.java
*If an operator has nonChainedOutputs, then its corresponding output should be counted in the task-level numRecordsOut metric.*
This pull request is borrowed from #13109. The copyright of the original author is reserved as co-author.
- *Include side outputs in numRecordsOut metric*
This change added unit tests.
> [FLINK-18808][runtime] Include side outputs in numRecordsOut metric

- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/EmbeddedRocksDBStateBackend.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBAsyncSnapshotTest.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBInitITCase.java
Remove mocking from the rocksdb tests, that would fail out-of-the-box on Java 17.
RocksDBInitTest was renamed to RocksDBInitITCase so it runs in a separate JVM, which ensures that rocksdb wasn't initialized beforehand by another test.
> [FLINK-31934][rocksdb][tests] Remove mocking

- flink-queryable-state/flink-queryable-state-runtime/pom.xml
- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/client/proxy/KvStateClientProxyImplTest.java
- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/itcases/AbstractQueryableStateTestBase.java
- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/itcases/HAQueryableStateFsBackendITCase.java
- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/itcases/HAQueryableStateRocksDBBackendITCase.java
- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/itcases/NonHAQueryableStateFsBackendITCase.java
- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/itcases/NonHAQueryableStateRocksDBBackendITCase.java
- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/network/AbstractServerTest.java
- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/network/KVStateRequestSerializerRocksDBTest.java
- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/network/KvStateClientHandlerTest.java
- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/network/KvStateRequestSerializerTest.java
- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/network/KvStateServerHandlerTest.java
- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/network/KvStateServerTest.java
- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/network/MessageSerializerTest.java
- flink-queryable-state/flink-queryable-state-runtime/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Migrate flink-queryable-state-runtime tests to JUnit5
> [FLINK-31876][QS] Migrate flink-queryable-state-runtime tests to JUnit5

- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientITCase.java
- flink-table/flink-sql-client/src/test/resources/sql/delete.q
- flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/operation/OperationExecutor.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/abilities/sink/RowLevelDeleteSpec.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/batch/sql/DeleteTableITCase.java
To fix sql client can't show result for DELETE statement when delete is pushed down
Check the `ModifyOperation` is `DeleteFromFilterOperation` or not  in `OperationExecutor#callModifyOperations`,
if it's `DeleteFromFilterOperation`, return the result directly without getting the `JobClient`.
Added test in `flink-table/flink-sql-client/src/test/resources/sql/delete.q`. …
> [FLINK-31882][sql-client] Fix sql client can't show result for DELETE statement when delete is pushed down

- docs/content/docs/try-flink/flink-operations-playground.md
With the addition of a docker volume, this step is no long needed.
https://github.com/apache/flink-playgrounds/pull/42
re:
mkdir -p /tmp/flink-checkpoints-directory
mkdir -p /tmp/flink-savepoints-directory
> Remove savepoint and checkpoint mount instructions from flink playground.

- docs/layouts/shortcodes/generated/expert_high_availability_zk_section.html
- docs/layouts/shortcodes/generated/high_availability_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/HighAvailabilityOptions.java
- flink-runtime/src/main/java/org/apache/flink/runtime/util/ZooKeeperUtils.java
Given PR adds a new configuration to disable EnsembleTracking feature for Apache Curator. It would make possible to actually configure HA for Zookeeper, which is living behind VIP.
Currently HA with ZooKeeper can even lead to the JobManager failure. The scenario of the failure is next:
1. Flink connects to ZooKeeper via configured URL.
2. Ensemble tracking gets a new URL of ensemble, which is not obligatory accessible for Flink, because Zookeeper is under VIP.
3. In case of reconnect Flink fails to Zookeeper, moreover due to "UnresolvedHostException" Flink's jobManager is killed.
- Adds a new configuration into HighAvailabilityOptions
- Use newly added ZOOKEEPER_ENSEMBLE_TRACKING flag to control Curator ensemble tracking
- Default value is enabling ensemble tracking for backward …
> [FLINK-31780][component=Runtime/Coordination] Allow users to disable 'Ensemble tracking' feature for ZooKeeper Curator framework

- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnTestBase.java
After test execution, during cluster shutdown there is a chance that Yarn AMRM gets an interruption during its heartbeat logic, which generates an exception and when that happens, tests will fail because that exact exception is not whitelisted at the moment.
Added a new exception to the `YarnTestBase` whitelist.
> [FLINK-31609][yarn][test] Extend log whitelist for expected AMRM heartbeat interrupt

- docs/data/sql_functions.yml
- flink-python/docs/reference/pyflink.table/expressions.rst
- flink-python/pyflink/table/expression.py
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/InputTypeStrategies.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/CommonArrayInputTypeStrategy.java
- flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/strategies/CommonArrayInputTypeStrategyTest.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CollectionFunctionsITCase.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/ArrayUnionFunction.java
This is an implementation of ARRAY_UNION
ARRAY_UNION for Table API and SQL
```
Returns an array of the elements in the union of array1 and array2, without duplicates. 
Syntax:
array_union(array1, array2)
Arguments:
Returns:
An ARRAY. If any of the array is null, the function will return null.
Examples:
> SELECT array_union(array(1, 2, 3), array(1, 3, 5));
[1,2,3,5] 
```
See also
spark https://spark.apache.org/docs/latest/api/sql/index.html#array_union
presto https://prestodb.io/docs/current/functions/array.html
This change added tests in CollectionFunctionsITCase.
Dependencies (does it add or upgrade a …
> [FLINK-31118][table] Add ARRAY_UNION function.

- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionReadSchedulerTest.java
Backport FLINK-31418 to `release-1.16` branch.
> [BP-1.16][FLINK-31418][network][tests] Fix unstable test case SortMergeResultPartitionReadSchedulerTest.testRequestBufferTimeout

- flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroFilesystemITCase.java
- flink-formats/flink-csv/src/test/java/org/apache/flink/formats/csv/CsvFilesystemBatchITCase.java
- flink-formats/flink-csv/src/test/java/org/apache/flink/formats/csv/CsvFilesystemStreamITCase.java
- flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/JsonBatchFileSystemITCase.java
- flink-formats/flink-orc/src/test/java/org/apache/flink/orc/OrcFileSystemITCase.java
- flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/ParquetFileSystemITCase.java
- flink-table/flink-table-common/src/test/java/org/apache/flink/table/utils/LegacyRowExtension.java
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/FileSystemITCaseBase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/BatchFileSystemITCaseBase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/FileSystemTestCsvITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/table/AggregationITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/table/CalcITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/table/CorrelateITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/table/GroupWindowITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/table/JoinITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/table/LegacyLimitITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/table/LegacyTableSinkITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/table/OverAggregateITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/table/SetOperatorsITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/table/SortITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/table/TableSinkITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/StreamFileSystemITCaseBase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/StreamFileSystemTestCsvITCase.scala
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/extensions/parameterized/NoOpTestExtension.java
*Migrate subclasses of BatchAbstractTestBase in table and other modules to JUnit5*
- *Migrate subclasses of BatchAbstractTestBase in table and other modules to JUnit5*
> [FLINK-32060][test] Migrate subclasses of BatchAbstractTestBase in table and other modules to JUnit5

- flink-core/src/main/java/org/apache/flink/util/NetUtils.java
- flink-core/src/test/java/org/apache/flink/util/NetUtilsTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/RestClient.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliOptions.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliOptionsParser.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/Executor.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/ExecutorImpl.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/SqlClientTest.java
- flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/header/util/UrlPrefixDecorator.java
This pull request adds support for URLs in SQL Client gateway mode. The changes are backwards compatible and still allow to pass `hostname:port` as the `--endpoint` parameter.
https://issues.apache.org/jira/browse/FLINK-32030
- Added integration tests using a URL as the new `--endpoint` parameter
- Manually verified connectivity and interactions with a SQL Gateway that is exposed using a proxy,  and includes a URL path (`foo.com:8083/some-path/v1/info`)
- The runtime per-record code paths (performance sensitive): (yes / …
> [FLINK-32030][sql-client] Add URLs support for SQL Client gateway mode

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/StateAssignmentOperation.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/TaskStateAssignment.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/StateAssignmentOperationTest.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointRescaleITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java
Backport of #22584 to 1.16.
This commit fixes problems in StateAssignmentOperation for unaligned checkpoints with stateless operators that have upstream operators with output partition state or downstream operators with input channel state.
(cherry picked from commit 354c0f455b92c083299d8028f161f0dd113ab614)
Please make sure both new and modified tests in this PR follows the …
> [FLINK-31963][state] Fix rescaling bug in recovery from unaligned checkpoints.

- flink-end-to-end-tests/test-scripts/kafka-common.sh
https://issues.apache.org/jira/browse/FLINK-32123
For the past few hours, E2E tests fail with: `Avro Confluent Schema Registry nightly end-to-end test failed after 9 minutes and 53 seconds! Test exited with exit code 1`
Looks like https://archive.apache.org/dist/kafka/  mirror is overloaded – download locally took more than 30min
This PR switches to  https://downloads.apache.org/ mirror (locally takes a few minutes)
> [FLINK-32123][e2e] Fix E2E kafka download timeout

- docs/content.zh/docs/ops/state/state_backends.md
This PR Fix the deprecated state backend sample config in Chinese document
update state backend sample config in Chinese document
before  -> state.backend: filesystem
after     -> state.backend: hashmap …
> [FLINK-32112][docs] Fix the deprecated state backend sample config in Chinese document

- flink-end-to-end-tests/test-scripts/kafka-common.sh
Reverts apache/flink#22603 now that https://issues.apache.org/jira/browse/INFRA-24607 is resolved
> Revert "[FLINK-32123][e2e] Fix E2E kafka download timeout"

- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/TaskExecutorManager.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/TaskExecutorManagerTest.java
We will request redundant task managers when there are no enough free slots. But if task manager start too slow or yarn/Kubernetes no resource to create new task manager.  This logic will request new task managers in each periodic check.
- *Only request new redundant task managers when there is no pending slots.*
*(example:)*
- *Tested manually with 2 required task managers and  2 redundant task managers. Kubernetes only could provide 2 pods, so the 2 redundant task manager will be pending, and no new task manager will be request*
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`:(no) …
> [FLINK-31498][runtime] Only request redundant task manager when all pending slots registered.

- docs/content/docs/dev/configuration/maven.md
update the doc to help developer use the feasible maven version. 
- pointed out that 3.8.6 is recommended according to https://lists.apache.org/thread/jbw3lzzoq5w16ckco3fc9xokycs3f22x. 
- Higher version could also be used. I personally tested with 3.9.1 …
> [hotfix][doc] mvn 3.8.6 is recommended or higher version could be used

- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyClientServerSslTest.java
We see the test occassionally fail due to slow CI machines (see further details in FLINK-31354). Increasing the timeouts should solve the issue.
* Increased the timeouts from 1s to 5s
> [FLINK-31354][tests] Increased timeout for NettyClientServerSslTest to improve test stability

- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyClientServerSslTest.java
> [BP-1.17][FLINK-31354][tests] Increased timeout for NettyClientServerSslTest to improve test stability

- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyClientServerSslTest.java
> [BP-1.16][FLINK-31354][tests] Increased timeout for NettyClientServerSslTest to improve test stability

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaConsumerBaseMigrationTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/PendingCheckpointTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/NettyShuffleEnvironmentTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/IncrementalRemoteKeyedStateHandleTest.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/EmbeddedRocksDBStateBackendTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/BackendRestorerProcedureTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/OperatorSnapshotFuturesTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/StateSnapshotContextSynchronousImplTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/TestSpyWrapperStateBackend.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/FlinkCalciteCatalogReaderTest.java
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/codegen/agg/AggTestBase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/codegen/agg/batch/HashAggCodeGeneratorTest.scala
- flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/window/WindowOperatorContractTest.java
Migrates most powermock usages to mockito. We mock a few static things with powermock that couldn't be migrated easily.
The goal is to reduce powermock usages to a minimum, and limit the powermock dependency to flink-core/runtime in a follow-up.
Note: This PR is not touching mocks that are being removed in #22616.
> [FLINK-32152][tests] Consolidate mocking library usage

- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StateWithExecutionGraph.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerBuilder.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/CancelingTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/ExecutingTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/FailingTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StateWithExecutionGraphTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StopWithSavepointTest.java
https://issues.apache.org/jira/browse/FLINK-31891
* Introduce async task failure as part of AdaptiveScheduler#updateTaskExecutionState
* Propagate labels as part of ExceptionHistoryEntry
* Extend AdaptiveSchedulerTests to validate functionality
> [FLINK-31891][runtime] Introduce AdaptiveScheduler per-task failure enrichment/labeling

- flink-core/pom.xml
- flink-runtime/pom.xml
- pom.xml
Based on #22616/#22617.
Narrows the powermock dependency to flink-core/flink-runtime, preventing other modules from using it.
> [FLINK-32153][build] Limit powermock to core/runtime 

- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveBatchScheduler.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveBatchSchedulerTest.java
https://issues.apache.org/jira/browse/FLINK-31893
* Label failures part of AdaptiveBatchScheduler#initializeVerticesIfPossible replacing failJob call with handleGlobalFailure on a unrecoverable error
* Extend AdaptiveBatchSchedulerTest to validate functionality
> [FLINK-31893][runtime] Introduce AdaptiveBatchScheduler failure enrichment/labeling

- docs/content.zh/docs/dev/table/sql/analyze.md
- docs/content/docs/dev/table/sql/analyze.md
Fixed the SQL sample syntax error in analyze.md for both English and Chinese documents, the comma in the sample SQL should be inside the double quotes.
> [hotfix][doc]Fix typo in analyze.md

- flink-end-to-end-tests/flink-streaming-kafka-test-base/src/main/java/org/apache/flink/streaming/kafka/test/base/KafkaExampleUtil.java
*`KafkaExampleUtils` incorrect check of the minimum number of parameters.*
- *Change the minimum number of parameters from `5` to `4`, aligning with error message.*
> [FLINK-32172][kafka] KafkaExampleUtils incorrect check of the minimum number of parameters

- tools/ci/maven-utils.sh
The idea is to use `https://repo.maven.apache.org` (same as `maven-wrapper.properties`) to download maven via `maven-utils.sh` since connection to `https://archive.apache.org` seems to be unstable sometimes like e.g. at https://issues.apache.org/jira/browse/FLINK-32106
`maven-utils.sh` …
> [hotfix] Use https://repo.maven.apache.org in maven-utils.sh

- flink-end-to-end-tests/flink-streaming-kafka-test-base/src/main/java/org/apache/flink/streaming/kafka/test/base/KafkaExampleUtil.java
Backport FLINK-32172 to release-1.17.
> [BP-1.17][FLINK-32172][kafka] KafkaExampleUtils incorrect check of the minimum number of parameters

- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/api/bridge/java/StreamTableEnvironment.java
- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/api/bridge/java/internal/StreamTableEnvironmentImpl.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/DataStreamJavaITCase.java
This pull request reduces the overhead of conversion between DataStream and Table in some cases.
- Checks if there are paired fromDataStream/toDataStream function call without any transformation, if so use the source datastream directly.
The performance of Flink ML's Bucketizer algorithm[1] is used to demonstrate the impact of this optimization. The execution time is obtained by taking the median execution time across 5 runs for each setup.
- Before optimization: 40746ms
- After optimization: 12972ms
Thus this optimization reduces the total execution time of Flink ML's Bucketizer algorithm to about 1/3. 
[1] https://github.com/apache/flink-ml/blob/master/flink-ml-benchmark/src/main/resources/bucketizer-benchmark.json
This change is verified by the newly added test cases in …
> [FLINK-31240][table] Reduce the overhead of conversion between DataStream and Table

- flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskTest.java
This is a cherry-pick backport of https://github.com/apache/flink/pull/22354
> [BP-1.16][FLINK-30844][runtime] Increased TASK_CANCELLATION_TIMEOUT for testInterruptibleSharedLockInInvokeAndCancel

- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/runner/DefaultDispatcherRunner.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedLeaderService.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMasterServiceLeadershipRunner.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/AbstractLeaderElectionService.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElection.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionService.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/LeaderElection.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/LeaderElectionService.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/StandaloneLeaderElectionService.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManagerServiceImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/WebMonitorEndpoint.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/runner/DefaultDispatcherRunnerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedLeaderServiceTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionServiceTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/LeaderElectionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/StandaloneLeaderElectionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingLeaderElection.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingLeaderElectionService.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionConnectionHandlingTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderretrieval/ZooKeeperLeaderRetrievalTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/ResourceManagerServiceImplTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/util/DocumentingDispatcherRestEndpoint.java
* === this PR === FLINK-31785
This PR moves the leader election deregistration from the `LeaderElectionService` interface into `LeaderElectionService.LeaderElection`.
* Introduced `AbstractLeaderElectionService.remove` method that is then used by …
> [FLINK-31785][runtime] Moves LeaderElectionService.stop into LeaderElection.close

- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Created.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/CreatingExecutionGraph.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Finished.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/LabeledGlobalFailureHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/State.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StateWithExecutionGraph.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StopWithSavepoint.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/WaitingForResources.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/exceptionhistory/ExceptionHistoryEntry.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/CancelingTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/CreatedTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/CreatingExecutionGraphTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/ExecutingTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/FailingTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/FinishedTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/RestartingTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StateWithExecutionGraphTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StopWithSavepointTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/WaitingForResourcesTest.java
https://issues.apache.org/jira/browse/FLINK-31892
* Introduce LabeledGlobalFailureHandler interface for handling and associating global failures with labels
* Introduce async task failure labeling as part of AdaptiveScheduler#handleGlobalFailure
* Extend AdaptiveSchedulerTest to validate functionality
> [FLINK-31892][runtime] Introduce AdaptiveScheduler global failure enrichment/labeling

- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/DispatcherServices.java
- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/JobManagerRunnerFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/JobMasterServiceLeadershipRunnerFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/PartialDispatcherServices.java
- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/PartialDispatcherServicesWithJobPersistenceComponents.java
- flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/ClusterEntrypoint.java
- flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/component/DefaultDispatcherResourceManagerComponentFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/component/DispatcherResourceManagerComponentFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/failure/FailureEnricherUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/factories/DefaultJobMasterServiceFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniCluster.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/ExecutionGraphInfoStoreTestUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/MiniDispatcherTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/TestingDispatcher.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/TestingJobMasterServiceLeadershipRunnerFactory.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/TestingPartialDispatcherServices.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/runner/ZooKeeperDefaultDispatcherRunnerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/minicluster/TestingMiniCluster.java
- flink-tests/src/test/java/org/apache/flink/test/recovery/ProcessFailureCancelingITCase.java
https://issues.apache.org/jira/browse/FLINK-31993
* Init FailureEnrichers as part of ClusterEntrypoint (to avoid performing the same task per JM initialization)
The set of Enrichers is then passed down to JM and Scheduler implementations as needed.
> [FLINK-31993][runtime] Initialize and pass down FailureEnrichers

- tools/azure-pipelines/e2e-template.yml
Update of libssl version required for E2E tests
> [FLINK-32231][Build System] Update libssl to 5.13, which is needed for all E2E tests

- docs/content/docs/dev/table/data_stream_api.md
- docs/layouts/shortcodes/github_repo.html
- docs/layouts/shortcodes/version.html
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/src/reader/FileRecordFormat.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaProducerTestBase.java
- flink-connectors/flink-sql-connector-hive-3.1.3/src/main/java/org/apache/hadoop/hive/conf/HiveConf.java
- flink-runtime/src/main/java/org/apache/flink/runtime/deployment/InputGateDeploymentDescriptor.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/FineGrainedSlotManagerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/AsyncSnapshotCallableTest.java
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/TemporalJoinUtil.scala
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/window/slicing/SliceAssigner.java
Trivial word deduplication: "and and" and "the the"
> trivial word dedup

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/KubernetesResourceManagerDriver.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/KubernetesResourceManagerDriverTest.java
Recent changes cause the jobmanager to fail on kubernetes client errors while requesting resources. This is undesirable in most prod settings and we should restore the old retrying behaviour like Flink 1.16 and before.
- *Retry KubernetesClientExceptions*
- *Add unit test*
New unit test added.
- Anything that affects deployment or recovery: Kubernetes
> [FLINK-31974] Do not crash jobmanager on Kubernetes client errors

- docs/layouts/shortcodes/generated/rest_v1_dispatcher.html
- docs/static/generated/rest_v1_dispatcher.yml
- flink-runtime-web/src/test/resources/rest_api_v1.snapshot
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/JobExceptionsHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/JobExceptionsInfoWithHistory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/FailureLabelFilterParameter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/JobExceptionsMessageParameters.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/job/JobExceptionsHandlerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/messages/JobExceptionsInfoWithHistoryNoRootTest.java
https://issues.apache.org/jira/browse/FLINK-31894
* Introduce FailureLabel class as a KV string container
* Add support for failure labels on JobExceptionsInfoWithHistory
* Extend JobExceptionsHandler to support `failureLabelFilter`
* Extend JobExceptionsHandlerTest to validate functionality
> [FLINK-31894][runtime] ExceptionHistory and REST API failure label integration

- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/NonDeterministicTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/utils/ExpressionTestBase.scala
This PR fixes the incorrect test initialization for `NonDeterministicTests` which uses `streamTableEnv` to test batch behavior, which fails of course but has not been revealed due to the JUnit cannot recognize test ends with "Tests".
- Rename `NonDeterministicTests` to `NonDeterministicTest` to make CI recognize the test.
- Fix the initialization way for `ExpressionTestBase` on how to init table env, which should be based on  streaming or batch mode.
- The runtime per-record code paths (performance sensitive): (yes / **no** / don't …
> [FLINK-32245][table-planner] Rename NonDeterministicTests to NonDeterministicTest and fix incorrect test initialization

- docs/content.zh/docs/connectors/table/datagen.md
- docs/content/docs/connectors/table/datagen.md
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/source/datagen/RandomGenerator.java
- flink-table/flink-sql-client/src/test/resources/sql/table.q
- flink-table/flink-sql-gateway/src/test/resources/sql/table.q
- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/connector/datagen/table/DataGenConnectorOptions.java
- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/connector/datagen/table/DataGenConnectorOptionsUtil.java
- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/connector/datagen/table/DataGenTableSource.java
- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/connector/datagen/table/DataGenTableSourceFactory.java
- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/connector/datagen/table/RandomGeneratorVisitor.java
- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/connector/datagen/table/types/DataGeneratorMapper.java
- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/connector/datagen/table/types/DecimalDataRandomGenerator.java
- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/connector/datagen/table/types/RowDataGenerator.java
- flink-table/flink-table-api-java-bridge/src/test/java/org/apache/flink/connector/datagen/table/types/DecimalDataRandomGeneratorTest.java
- flink-table/flink-table-api-java-bridge/src/test/java/org/apache/flink/table/factories/DataGenTableSourceFactoryTest.java
The PR allows to specify the proportion of null values to generate with DataGen per field,
like 
```sql
CREATE TABLE Orders (
order_number STRING,
price        DECIMAL(32,2),
buyer        ROW<id INT, last_name STRING>,
order_time   TIMESTAMP(3),
my_map       MAP<INT,STRING>,
my_array     ARRAY<STRING>
) WITH (
'connector' = 'datagen',
'fields.order_number.null-rate' = '0.7',
'fields.price.null-rate' = '1.0',
'fields.order_time.null-rate' = '0.5',
'fields.buyer.id.null-rate' = '0.5',
'fields.buyer.null-rate' = '0.5',
'fields.my_map.key.null-rate' = '0.5',
'fields.my_map.null-rate' = '0.5',
'fields.my_array.element.null-rate' = '0.1',
'fields.my_array.null-rate' = '0.5'
);
```
There have been added test cases to 
_flink-table/flink-table-api-java-bridge/src/test/java/org/apache/flink/connect …
> [FLINK-25284][Table SQL / API] Add proportion of null values to generate with datagen

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/shuffle/TieredResultPartition.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/TieredStorageProducerClient.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/TieredStorageProducerMetricUpdate.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/TierProducerAgent.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/TestingBufferAccumulator.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/TestingTierProducerAgent.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/TieredStorageTestUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/shuffle/TieredResultPartitionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/HashBufferAccumulatorTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/TieredStorageProducerClientTest.java
1. Write the accumulated buffers to the right storage tier
- * Firstly choose the storage tier, then write the accumulated buffers to the right storage tier.*
- *Added the test of `TieredStorageProducerClientTest` to verify the logic of choosing storage tiers.*
> [FLINK-31640][network] Write the accumulated buffers to the right storage tier

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/KafkaSourceEnumerator.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/OffsetsInitializer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/TimestampOffsetsInitializer.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/enumerator/initializer/OffsetsInitializerTest.java
Backport FLINK-28185 fix to 1.16. This is in this repo since 1.16 is still tracked by the main repo.
- Backport FLINK-28185 fix to 1.16
Backport FLINK-28185 fix to 1.16. CI passing should be sufficient coverage.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: yes, JobManager - enumerator
> [BP-1.16][FLINK-28185][Connector/Kafka] handle missing timestamps when there are empty partitions for the TimestampOffsetsInitializer 

- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlCreateTableConverter.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlDdlToOperationConverterTest.java
The current `SqlCreateTableConverter` does not use the correct toString method when constructing column comments for `CatalogTable`, which may cause sql-client users and catalog implementers to encounter problems with Chinese characters in column comments not being displayed as expected.
update the toString logic for column comments in `SqlCreateTableConverter`
Add Chinese characters in test cases of `SqlDdlToOperationConverterTest`  …
> [FLINK-32249][table-planner] Use proper toString conversion when constructing column comments for CatalogTable

- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/ProjectionCodeGenerator.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/agg/batch/HashAggCodeGenerator.scala
If the adaptive local hash agg is enabled, the generated code for value projection is evaluated repeatedly, the field access code can be reused to avoid accessing RowData twice, this optimization can improve the query performance.  
- *Improve the adaptive local hash agg value projection code*
This change is a trivial code improvement, already covered by existing tests in HashAggITCase.
- Does …
> [FLINK-32220][table-runtime] Improving the adaptive local hash agg code to avoid get value from RowData repeatedly

- flink-core/src/main/java/org/apache/flink/core/memory/MemorySegment.java
- flink-runtime/src/test/java/org/apache/flink/runtime/memory/MemorySegmentSimpleTest.java
This PR aims to add `getOffHeapBuffer` in `MemorySegment` and iceberg/paimon sink operator can create writer buffer with managed memory in Flink
- Add `getOffHeapBuffer` in `MemorySegment` …
> [FLINK-32213][core] Add get off heap buffer in segment

- flink-core/src/main/java/org/apache/flink/configuration/ExecutionOptions.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraphGenerator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/StreamExecutionEnvironmentTest.java
[FLINK-32023](https://issues.apache.org/jira/browse/FLINK-32023) changed the `ExecutionOptions.BUFFER_TIMEOUT` to `ExecutionOptions.BUFFER_TIMEOUT_INTERVAL`, the filed name should be reverted.
Because the `ExecutionOptions` is a public evolving API, some flink users are using the `ExecutionOptions.BUFFER_TIMEOUT` in their code. If we update it, the code cannot upgrade to 1.18 directly.
Revert the field name of BUFFER_TIMEOUT …
> [FLINK-32250][configuration] Revert the field name of BUFFER_TIMEOUT

- flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/operation/OperationExecutor.java
- flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/AbstractSqlGatewayStatementITCase.java
- flink-table/flink-sql-gateway/src/test/resources/sql/insert.q
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java
This PR fixes the issue that the `COMPILE AND EXECUTE PLAN` or `EXECUTE PLAN` statement causes the SQL client to hang forever. The reason is that `OperationExecutor` didn't take these two kinds of operation kind into account. Instead, they should be dealt with like `ModifyOperation`.
- Let`OperationExecutor` cope with `ExecutionPlanOperation` and `CompileAndExecutePlanOperation`.
- `TableEnvironmentImpl` should apply `TABLE_DML_SYNC` for both `ModifyOpeartion` and `ExecutePlanOperation`. Both of them are compiled from `insert into` queries.
- Add plan-related tests in the`insert.q` to verify that the `EXECUTE PLAN` and `COMPILE AND EXECUTE PLAN` statements work as expected after the fix. 
- Verify the SqlClient works normally after submitting `EXECUTE PLAN` statement.
- Dependencies (does …
> [FLINK-32219][sql-client] Fix SqlClient hangs when executing EXECUTE PLAN statement

- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotManagerConfiguration.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotManagerConfigurationTest.java
Backport FLINK-32254 to `release-1.17` branch.
> [BP-1.17][FLINK-32254][runtime] FineGrainedSlotManager may not allocate enough taskmanagers if maxSlotNum is configured

- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotManagerConfiguration.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotManagerConfigurationTest.java
Backport FLINK-32254 to `release-1.16` branch.
> [BP-1.16][FLINK-32254][runtime] FineGrainedSlotManager may not allocate enough taskmanagers if maxSlotNum is configured

- pom.xml
Bump `testcontainers` from 1.17.6 to 1.18.3
`pom.xml`
> [FLINK-32267] Upgrade tesctcontainers from 1.17.6 to 1.18.3

- flink-table/flink-sql-parser/src/main/codegen/data/Parser.tdd
- flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl
- flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/dml/SqlTruncateTable.java
- flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java
To make Flink SQL support parse truncate table statement.
Add a parse rule for  truncate table statement.
Add test in [FlinkSqlParserImplTest.java](https://github.com/apache/flink/pull/22691/files#diff-933f5a58803af35b4c8ee6fa318b0e585bc7f6d87bc60e13f2a76fc9c9e612aa) …
> [FLINK-32232][table] Supports parse truncate table statement

- docs/data/sql_functions.yml
- flink-python/docs/reference/pyflink.table/expressions.rst
- flink-python/pyflink/table/expression.py
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/SpecificInputTypeStrategies.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/SpecificTypeStrategies.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/MapFunctionITCase.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/MapEntriesFunction.java
This is an implementation of MAP_ENTRIES
MAP_ENTRIES for Table API and SQL
```
map_entries(map) - Returns an unordered array of all entries in the given map.
Syntax:
map_entries(map)
Arguments:
map: An MAP to be handled.
Returns:Returns an unordered array of all entries in the given map. Returns null if the argument is null
> SELECT map_entries(map[1, 'a', 2, 'b']);
[(1,"a"),(2,"b")] 
```
See also
presto https://prestodb.io/docs/current/functions/map.html
spark https://spark.apache.org/docs/latest/api/sql/index.html#map_entries
This change added tests in MapFunctionITCase.
Dependencies (does it add or upgrade a dependency): ( no)
The public …
> [FLINK-31677][table] Add built-in MAP_ENTRIES function.

- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/AggregateITCaseBase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/AggregateJoinTransposeITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/AggregateReduceGroupingITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/AggregateRemoveITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/DistinctAggregateITCaseBase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/GroupWindowITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/GroupingSetsITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/HashAggITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/PruneAggregateCallITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/SortAggITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/SortDistinctAggregateITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/join/InnerJoinITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/join/JoinConditionTypeCoerceITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/join/JoinITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/join/JoinWithoutKeyITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/join/LookupJoinITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/join/OuterJoinITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/join/ScalarQueryITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/join/SemiJoinITCase.scala
*Migrate subclasses of BatchAbstractTestBase in batch.sql.agg and batch.sql.join to JUnit5*
- *Migrate subclasses of BatchAbstractTestBase in batch.sql.agg and batch.sql.join to JUnit5*
> [FLINK-32059] Migrate subclasses of BatchAbstractTestBase in batch.sql.agg and batch.sql.join to JUnit5

- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnTestBase.java
II've seen this exception a few times without the address being null.
This could be due to difference in how Java 17 resolves addresses .
In any case I don't see any harm in relaxing this regex to accept any address.
> [FLINK-32236][yarn][tests] Ease allow-list regex

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/EndOfSegmentEvent.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/serialization/EventSerializer.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/Buffer.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/ResultSubpartitionView.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/InputChannel.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/LocalInputChannel.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/RecoveredInputChannel.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/RemoteInputChannel.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/NettyConnectionId.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/NettyConnectionReader.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/NettyConnectionReaderAvailabilityAndPriorityHelper.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/NettyConnectionReaderImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/NettyConnectionWriter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/NettyConnectionWriterImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/NettyPayload.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/NettyServiceProducer.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TieredStorageNettyService.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TieredStorageNettyServiceImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TieredStoreResultSubpartitionView.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/shuffle/TieredResultPartition.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/serialization/EventSerializerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/InputChannelTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/TestInputChannel.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/NettyConnectionReaderTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/NettyConnectionWriterTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/NettyPayloadTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TestingNettyConnectionReaderAvailabilityAndPriorityHelper.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TestingNettyServiceProducer.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TieredStoreResultSubpartitionViewTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/shuffle/TieredResultPartitionTest.java
To achieve this purpose, we could break down the implementation into 2 stages and achieve them sequentially.
> [FLINK-31636][network] Upstream supports reading buffers from tiered store

- tools/azure-pipelines/e2e-template.yml
This is a backport of https://github.com/snuyanzin/flink/commit/ed7ca22efc68203d4882887a3856434137e6980f and https://github.com/apache/flink/commit/cc552f970e2673f2895ca3c73a8150cdf720915a to 1.15
> [BP-1.15][FLINK-32231][Build System] Update libssl to 5.13, which is needed for all E2E tests

- docs/content.zh/docs/connectors/table/kafka.md
- docs/content/docs/connectors/table/kafka.md
This PR fixes incorrect metadata column type in Kafka connector docs and test cases.
- Changed timestamp metadata column type from `TIMESTAMP` to `TIMESTAMP_LTZ` (with local timezone) in [Kafka SQL connector examples](https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/connectors/table/kafka/#how-to-create-a-kafka-table) in both English and Chinese docs …
> [FLINK-32289][kafka] Fix incorrect metadata column type in docs

- flink-clients/src/test/java/org/apache/flink/client/ClientHeartbeatTest.java
*Increase clientHeartbeatTimeout to 1 second to avoid shutting down the job in ClientHeartbeatTest.*
- *Increase clientHeartbeatTimeout to 1 second*
> [FLINK-30629][Client/Job Submission] Increase clientHeartbeatTimeout to 1 second

- flink-core/src/main/java/org/apache/flink/util/concurrent/DirectExecutorService.java
- flink-core/src/main/java/org/apache/flink/util/concurrent/Executors.java
- flink-core/src/test/java/org/apache/flink/util/concurrent/DirectExecutorServiceTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/ZooKeeperMultipleComponentLeaderElectionDriver.java
- flink-runtime/src/main/java/org/apache/flink/runtime/util/ZooKeeperUtils.java
The `DirectExecutor` doesn't have to handle the shutdown state and, therefore, can be served as a singleton. The `DirectExecutorService`, instead, cannot be served as a singleton due to the shutdown state.
We still have to provide an `ExecutorService` implementation without proper task rejection after shutdown was called, though, due to a bug in the `TreeCache` implementation as described in FLINK-32204.
* Merges TreeCache instantiation of `ZooKeeperUtils` and `ZooKeeperMultipleComponentLeaderElectionDriver`
* reintroduced `Executor.DirectExecutor` after it was removed in 17082604
* Introduces new factory methods for the `DirectExecutorService` and made them available through the `Executors` interface
* The error couldn't be reproduced locally and is, therefore, hard to verify because …
> [FLINK-32204][runtime] Separates the DirectExecutorService from the DirectExecutor again.

- flink-connectors/flink-connector-hbase-2.2/pom.xml
Consistently fail on Java 17, probably because our dependencies are horrendously out-dated.
We can revert this later if someone looks into bumping our HBase dependency.
> [FLINK-32302][hbase] Disable tests on Java 17

- flink-end-to-end-tests/test-scripts/common.sh
By only modifying the config we can extend the configuration with required defaults without breaking tests relying on `create_ha_config()`.
> [FLINK-32301][test] Set options instead of replacing entire config

- pom.xml
This ensures that IntelliJ also picks up these settings.
This is important for Java 17 because the `baseArgLine` will contain module declarations, which we need IntelliJ to also import.
Even beyond that though this is a nice change because it brings IDE work closer to what runs on CI.
> [FLINK-32328][build] Set surefire base argLine in general settings

- flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/container/FlinkImageBuilder.java
Use the same base image as the prod docker images.
> [FLINK-32297][tests] FlinkImageBuilder uses Temurin images

- flink-core/src/test/java/org/apache/flink/util/concurrent/TestingUncaughtExceptionHandler.java
- flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/RobustActorSystem.java
- flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/RobustActorSystemTest.java
Stray threads in akka/netty can run into classloading errors because they aren't shut down (for some reason) despite the actor system having shut down.
Ignore errors in this specific situation.
This is primarily relevant for testing.
> [FLINK-32314][rpc] Ignore classloading errors after actorsystem shutdown 

- flink-end-to-end-tests/test-scripts/test_ha_datastream.sh
env.java.opts.all will soon become very important because it contains the Java 17 module declarations. Tests thus shouldn't just override this value.
(In the future we could add a utility bash method to append a value to an existing option)
> [FLINK-32329][tests] Do not override env.java.opts.all

- flink-formats/flink-csv/src/test/java/org/apache/flink/formats/csv/DataStreamCsvITCase.java
POJO classes should be public. This currently causes Kryo to be used for the entire pojo, requiring additional --add-opens on Java 17.
> [FLINK-31940] DataStreamCsvITCase#CityPojo serialized as POJO

- azure-pipelines.yml
- tools/azure-pipelines/build-apache-repo.yml
- switch to Temurin JDK 11 (latest)
- update Temurin JDK 17 to latest
JDK 17 update is the important bit, fixing the observed SIGSEGV.
> [FLINK-24998] Update CI image

- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBWriteBatchWrapper.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBWriteBatchWrapperTest.java
Disables WAL by default in RocksDBWriteBatchWrapper for the case that now explicit WriteOption is passed in. This is the case in all restore operations and can impact the performance.
- Creates default WriteOptions with WAL disabled in RocksDBWriteBatchWrapper.
- Unit tests in RocksDBWriteBatchWrapperTest
Run RocksDBWriteBatchWrapperTest. …
> [FLINK-32326][state] Disable WAL in RocksDBWriteBatchWrapper by default.

- flink-end-to-end-tests/flink-end-to-end-tests-jdbc-driver/pom.xml
- flink-end-to-end-tests/flink-end-to-end-tests-jdbc-driver/src/main/java/org/apache/flink/table/jdbc/driver/tests/FlinkDriverExample.java
- flink-end-to-end-tests/pom.xml
- flink-end-to-end-tests/run-nightly-tests.sh
- flink-end-to-end-tests/test-scripts/common.sh
- flink-end-to-end-tests/test-scripts/test_sql_jdbc_driver.sh
- flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/SqlGateway.java
Add e2e test for flink jdbc driver
- Add FlinkDriverE2eTest
> [FLINK-31673][jdbc-driver] Add e2e test for flink jdbc driver

- flink-tests/src/test/java/org/apache/flink/test/operators/PartitionITCase.java
POJOs should be public so they are serialized with the pojo serializer.
The modification to the `MinMaxSelector` is necessary because by being treated as a pojo the partitioning is being changed. Seemingly the `first` field of the `ComparablePojo` dominates the partitioning (ranging from 0-2), causing only 3 partitions to be created but the job runs with p=4.
I don't really know what the semantics for range partitioning of Kryo records are, and am somewhat confused that this test passed with Kryo in the first place because it does check for order of elements within partitions. :thinking: 
Anyhow, since this is a `DataSet` test I'm not too inclined to dig any deeper into the why's. The `hasNext` check is useful anyway because the test should pass with any parallelism, even one greater than …
> [FLINK-32336][tests] PartitionITCase#ComparablePojo now public

- flink-table/flink-sql-jdbc-driver/src/main/java/org/apache/flink/table/jdbc/BaseConnection.java
- flink-table/flink-sql-jdbc-driver/src/main/java/org/apache/flink/table/jdbc/BaseStatement.java
- flink-table/flink-sql-jdbc-driver/src/main/java/org/apache/flink/table/jdbc/FlinkConnection.java
- flink-table/flink-sql-jdbc-driver/src/main/java/org/apache/flink/table/jdbc/FlinkStatement.java
This PR aims to fix exception in jdbc driver for jdbc tools.
> [FLINK-32343][jdbc-driver] Fix exception in jdbc driver for jdbc tools

- flink-end-to-end-tests/flink-end-to-end-tests-hbase/src/test/java/org/apache/flink/tests/util/hbase/SQLClientHBaseITCase.java
- flink-end-to-end-tests/pom.xml
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/FailsOnJava17.java
- pom.xml
Adds an annotation for disabling tests on Java 17, similar to `FailsOnJava11`, and sets up the test exclusion in maven.
This annotation won't be used that much; probably only a 1 or 2 tests will use that once everything is done.
> [FLINK-32338][build] Add FailsOnJava17 annotation

- flink-scala/pom.xml
- flink-streaming-scala/pom.xml
- flink-tests/src/test/scala/org/apache/flink/api/scala/migration/ScalaSerializersMigrationTest.scala
- pom.xml
Based on #22780.
Since Scala 2.12.7 doesn't compile on Java 17 we will run the build with a later version of Scala when running on Java 17. This breaks various compatibility tests which are now disable in Java 17 builds, and I don't see a way around that.
Note that compiled 2.12.7 Scala code does appear to run on Java 17, so this really just about making CI work.
> [FLINK-25000][build] Java 17 uses Scala 2.12.15 

- flink-rpc/flink-rpc-akka-loader/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaRpcSystemLoader.java
- flink-rpc/flink-rpc-akka-loader/src/test/java/org/apache/flink/runtime/rpc/akka/FallbackAkkaRpcSystemLoader.java
- flink-rpc/flink-rpc-core/src/main/java/org/apache/flink/runtime/rpc/RpcSystem.java
- flink-rpc/flink-rpc-core/src/main/java/org/apache/flink/runtime/rpc/RpcSystemLoader.java
- flink-rpc/flink-rpc-core/src/test/java/org/apache/flink/runtime/rpc/RpcSystemTest.java
This PR ensures that, if the main and fallback akka rpc system loaders are both on the classpath, the main loader gets priority. This avoids cases on CI where the fallback loader was used just because it appeared first on the classpath.
> [FLINK-32358][rpc] Add rpc system loading priority

- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesCheckpointIDCounterTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionDriverTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStoreTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesTestFixture.java
[FlinkKubeClient.checkAndUpdateConfigMap](https://github.com/apache/flink/blob/ab3eb40d920fa609f49164a0bbb5fcbb3004a808/flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/FlinkKubeClient.java#L163) expects an error to be forwarded through the `CompletableFuture` instead of throwing a `RuntimeException`.
The actual implementation implements it accordingly in [Fabric8FlinkKubeClient:313](https://github.com/apache/flink/blob/025a95b627faf8ec8b725a7784d1279b41e10ba7/flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/Fabric8FlinkKubeClient.java#L313) where a `CompletionException` is thrown within the `CompletableFuture`'s `supplyAsync` call resulting in the future to fail.
`KubernetesTestFixture` doesn't make the returned future complete exceptionally but …
> [FLINK-32368][test] Fixes wrong interface implementation in KubernetesTestFixture

- flink-formats/flink-protobuf/pom.xml
- flink-formats/flink-protobuf/src/main/java/org/apache/flink/formats/protobuf/PbFileFormatFactory.java
- flink-formats/flink-protobuf/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
- flink-formats/flink-protobuf/src/test/java/org/apache/flink/formats/protobuf/ProtobufSQLITCaseTest.java
It's currently possible to use protobuf as a format to read/write files that store bulk records.  This is not actually supported by the [protobuf format](https://protobuf.dev/programming-guides/techniques/#streaming) itself.  Some techniques can be used to frame the data, but from the discussion on the [mailing list](https://lists.apache.org/thread/z9tqdqrhj12c17wqsdbm5fhzonqq5kp0), this doesn't seem like a useful thing to do.
The protobuf format is apt for serializing individual records framed inside other containers (like a Kafka message).  For bulk persistence, the parquet format using the protobuf-oriented API is a better standard than rolling our own.
The current state falls back to writing individual records as binaries delimited by newlines `0x0a`, and this may silently succeed but …
> [FLINK-32008][protobuf] Ensure bulk persistence is not supported

- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesCheckpointIDCounterTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionDriverTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStoreTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesTestFixture.java
1.17 backport PR for parent PR https://github.com/apache/flink/pull/22809
> [BP-1.17][FLINK-32368][test] Fixes wrong interface implementation in KubernetesTestFixture

- docs/data/sql_functions.yml
- docs/data/sql_functions_zh.yml
- flink-python/docs/reference/pyflink.table/expressions.rst
- flink-python/pyflink/table/expression.py
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/InputTypeStrategies.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CollectionFunctionsITCase.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/ArrayConcatFunction.java
This is an implementation of ARRAY_CONCAT
The array_concat() function concatenates at least one array, creating an array that contains all the elements in the first array followed by all the elements in the second array ... followed by all the elements in the n array.
ARRAY_CONCAT for Table API and SQL
Syntax:
`ARRAY_CONCAT(arr1, tail...)
`
Arguments:
array: at least one ARRAY to be handled.
Returns:
The function returns NULL if any input argument is NULL.
Examples:
`Flink SQL> SELECT array_concat(array[1, 2, 3, null, 3], array[3], array[5]);
[1, 2, 3, null, 3, 3, 5]`
see also:
Google Cloud BigQuery: https://cloud.google.com/bigquery/docs/reference/standard-sql/array_functions#array_concat
- This change added tests in CollectionFunctionsITCase. …
> [FLINK-31665] [table] Add ARRAY_CONCAT function

- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/ExecNodeGraphInternalPlan.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/CompiledPlanITCase.java
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/TableTestBase.scala
This PR fixes the issue that `COMPILED PLAN` statement may generate invalid JSON when overwriting the existing JSON with a shorter version.
-  Add `TRUNCATE_EXISTING` to `ExecNodeGraphInternalPlan#writeToFile`
This change is already covered by existing tests, such as `CompilePlanITCase#testCompilePlanOverwrite`.
- Roll back the changes made on src and run this case will reproduce the error. Apply the changes made on src and re-run the case to verify the fix. …
> [FLINK-32374][table-planner] Fix the issue that ExecNodeGraphInternalPlan#writeToFile should support TRUNCATE_EXISTING for overwriting

- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/ExecNodeGraphInternalPlan.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/CompiledPlanITCase.java
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/TableTestBase.scala
This pull request is cherry-picked from commit https://github.com/apache/flink/commit/f69ed3454f2ab200310edee230da292ee2408503
Please see https://github.com/apache/flink/pull/22820
Please see https://github.com/apache/flink/pull/22820
- Does this pull request introduce a new feature? No
- If yes, how is the feature documented? N.A.
> [FLINK-32374][table-planner] Fix the issue that ExecNodeGraphInternalPlan#writeToFile should support TRUNCATE_EXISTING for overwriting 

- flink-dist/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE
- pom.xml
1.16 backport for parent PR #22815
The backport caused some conflicts which I resolved:
* Snappy was only added to `flink-formats/flink-sql-avro-confluent-registry` (FLINK-31485) ~and `flink-filesystems/flink-s3-fs-presto` (FLINK-29502)~ in 1.17.
> [BP-1.16][FLINK-32371][build] Bump snappy-java to 1.1.10.1

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/parser/SqlClientParserState.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/parser/SqlClientSyntaxHighlighter.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/parser/SqlMultiLineParser.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/utils/SqlScriptReader.java
- flink-table/flink-sql-client/src/test/resources/sql/select.q
The PR is a part of FLIP-189 [1].
This PR fixes queries for corner cases mention at FLINK-24592 e.g.
```sql
select ';
';
select /*;
*/1;
select --;
1;
```
and others.
[1] https://cwiki.apache.org/confluence/display/FLINK/FLIP-189%3A+SQL+Client+Usability+Improvements#FLIP189:SQLClientUsabilityImprovements-Supportedprompthintvaluesinsqlclient
- Reworked SqlMultilineParser
There is _flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/SqlMultilineParserTest.java_
and updated _flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliStatementSplitterTest.java_
- Dependencies (does it add or upgrade a dependency): ( **no**)
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( **no**)
- The serializers: ( **no** )
- …
> [FLINK-24592][Table SQL/Client] FlinkSQL Client multiline parser improvements

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesMultipleComponentLeaderElectionHaServices.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesMultipleComponentLeaderRetrievalDriverFactory.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesCheckpointIDCounterTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesHighAvailabilityTestBase.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionDriverTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderRetrievalDriverTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesMultipleComponentLeaderElectionDriverTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesStateHandleStoreTest.java
* == THIS PR === FLINK-30344
Migrating the k8s-related tests that do not use the `DefaultLeaderElectionService` to the …
> [FLINK-30344][test] Migrates KubernetesHighAvailabilityTestBase-related tests to use the MultipleComponentLeaderElectionDriver interface

- flink-table/flink-sql-parser/src/main/codegen/data/Parser.tdd
- flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl
- flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/ddl/SqlDropPartitions.java
- flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlNodeToOperationConversion.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlAlterTableDropPartitionConverter.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlNodeConverters.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlDdlToOperationConverterTest.java
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/TableEnvironmentTest.scala
To make Flink support `DROP partition` statement for partitioned table.
- support to parse `alter table drop partition` syntax which will convert the sql statement to a SqlAddPartitions
- create a SqlAlterTableDropPartitionConverter to convert the SqlDropPartitions to DropPartitionsOperation.
UT …
> [FLINK-27241][table] Support DROP PARTITIONS statement for partitioned table

- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionAndRetrievalITCase.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/MultipleComponentLeaderElectionDriver.java
* == THIS PR === FLINK-30343
Migrating the `KubernetesLeaderElectionAndRetrievalITCase` tests that do not use the …
> [FLINK-30343][test] Migrates KubernetesLeaderElectionAndRetrievalITCase to use the MultipleComponentLeaderElectionDriver interface

- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/ZooKeeperMultipleComponentLeaderElectionDriver.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderretrieval/ZooKeeperLeaderRetrievalDriver.java
- flink-runtime/src/main/java/org/apache/flink/runtime/util/ZooKeeperUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/LeaderElectionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionTest.java
* == THIS PR === FLINK-30342
Migrating the `ZooKeeperLeaderElectionTest` tests that do not use the …
> [FLINK-30342][test] Migrates ZooKeeperLeaderElectionTest to use the MultipleComponentLeaderElectionDriver interface

- flink-core/src/main/java/org/apache/flink/util/CollectionUtil.java
- flink-core/src/test/java/org/apache/flink/util/CollectionUtilTest.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBIncrementalCheckpointUtils.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBStateDownloader.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/StateHandleDownloadSpec.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBIncrementalRestoreOperation.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateDownloaderTest.java
This commit improves RocksDBStateDownloader to support parallelized state download across multiple state types and across multiple state handles. This can improve our download times for scale-in.
- Introduced `StateHandleDownloadSpec` to combine incremental remote handles with their download paths.
- Modified `RocksDBStateDownloader` to accept a list of `StateHandleDownloadSpec` that can combine files from multiple handles and sub-states (shared, private).
- Modified `RocksDBIncrementalRestoreOperation` to first assemble a complete list of `StateHandleDownloadSpec` before invoking the download process.
- Adapted and added unit tests in `RocksDBStateDownloaderTest`.
This change is already covered by existing tests, such as 
- `RocksDBStateDownloaderTest`. I added more tests there.
- …
> [FLINK-32345][state] Improve parallel download of RocksDB incremental state.

- docs/layouts/shortcodes/generated/rest_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/RestOptions.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/RestClient.java
Introduce an option named "rest.url-prefix" to allow Flink clients to connect to the server behind Kubernetes ingress.
- Add the specified URL-prefix in front of the Flink origin URL.
- Manually verified that Flink client in the Kubernetes cluster could submit jobs without the "rest.url-prefix". 
* specified rest.address to JobManager Rest Service Name
- Manually verified that Flink client could submit jobs with the "rest.url-prefix" through an ingress proxy.
* specified rest.address to ingress host and rest.url-prefix to ingress path …
> [FLINK-32205][rest] Add the option "rest.url-prefix" to support connecting to the server through a proxy.

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerBase.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerBuilder.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/LogicalFile.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/PhysicalFile.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/WithinCheckpointFileMergingSnapshotManager.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerTest.java
As the first part of FLIP-306, which aims to provide an unified file merging mechanism for checkpoint files, this ticket/PR implements the basic file manager for merged files, providing file system directory layout and its initialization. It also provides the implementation of physical and logical files and the reference counting relationship between them.
- Add definition of FileMergingSnapshotManager and a base implementation.
- Add definition of PhysicalFile and LogicalFile.
This change added an UT class called FileMergingSnapshotManagerTest. …
> [FLINK-32071] Implement the snapshot manager for merged checkpoint files in TM

- flink-core/src/main/java/org/apache/flink/util/concurrent/IgnoreShutdownRejectedExecutionHandler.java
- flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/SchedulerFactory.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/HsResultPartitionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/shuffle/TieredResultPartitionTest.java
*`HsResultPartitionTest#testRelease` and `TieredResultPartitionTest#testRelease`  depend on local timeout, which will make the test unstable.*
- *Remove local timeout for Hybrid and Tiered result partition test.* …
> [hotfix] Remove local timeout for Hybrid and Tiered result partition test.

- azure-pipelines.yml
- tools/azure-pipelines/build-apache-repo.yml
- tools/azure-pipelines/build-nightly-dist.yml
- tools/azure-pipelines/e2e-template.yml
- tools/azure-pipelines/jobs-template.yml
This pull request adds year number before the cache key of local Maven repo on Azure Pipeline, so that the cache will be invalidated per year, in order to reduce the disk usage of Maven repo. 
- Invalidate Maven repo cache on Azure every year to reduce its disk usage
This change is already covered by existing tests.  …
> [FLINK-32392][ci] Invalidate Maven repo cache on Azure every year to reduce its disk usage

- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionService.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterServiceLeadershipRunnerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionServiceTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionConnectionHandlingTest.java
In production we should be fine ignoring those errors as long as no contender is added. But the default behavior limits our ability to identify errors in some test scenarios (e.g. [DefaultLeaderElectionServiceTest.testDelayedGrantCallAfterContenderBeingDeregisteredAgain](https://github.com/apache/flink/blob/bc18b8b1e23c557c74d4330ccc42f276f1bb7581/flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionServiceTest.java#L242)). Adding a fallback error handler resolves this issue. 
* Added new constructor allows the configuration of the fallback error handler.
* Added proper error handler in all affected test cases
* `DefaultLeaderElectionServiceTest.testErrorIsIgnoredAfterLeaderElectionBeingClosed` needed to be modified to succeed again (this one covers the …
> [FLINK-32413][runtime] Adds fallback error handler to DefaultLeaderElectionService

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTest.java
Currently if an error occurs while saving a completed checkpoint in the CompletedCheckpointStore, CheckpointCoordinator doesn't call CheckpointFailureManager to handle the error. Such behavior leads to the fact, that errors from CompletedCheckpointStore don't increase the failed checkpoints count and 'execution.checkpointing.tolerable-failed-checkpoints' option does not limit the number of errors of this kind in any way.
This PR corrects the behavior as follows:
- Only report checkpointSuccess AFTER the completed checkpoint is stored in the `CompletedCheckpointStore`.
- Calls handleCheckpointException for exceptions during the storing of the completed checkpoint. 
- Moved call to `checkpointSuccess` until after the checkpoint was stored.
- Replaced the stats tracking with proper reporting …
> [FLINK-32347][checkpoint] Exceptions from the CompletedCheckpointStore are not registered by the CheckpointFailureManager.

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorAlignmentTest.java
Watermark alignment will cause flink jobs to hang forever when any source subtask has no SourceSplit. You can get more background from FLINK-32414.
Don't emitLatestWatermark when lastEmittedWatermark is UNINITIALIZED
- *Added SourceOperatorAlignmentTest#testWatermarkAlignmentWithoutSplit*
> [FLINK-32414][connectors/common] Don't emitLatestWatermark when lastEmittedWatermark is UNINITIALIZED

- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlNodeConvertContext.java
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/hint/OptionsHintTest.xml
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/hint/OptionsHintTest.scala
Table hints will lost when they inside a view referenced by an external query, this is due to the upgrading of calcite-1.28 (affected by [CALCITE-4640](https://issues.apache.org/jira/browse/CALCITE-4640) which changed the default implementation of `SqlDialect` suppresses all table hints).  We should use `AnsiSqlDialect` instead to reserve table hints.
use `AnsiSqlDialect` instead to reserve table hints
add new case into existing `OptionsHintTest`  …
> [FLINK-32447][table-planner] Fix missing table hints when they inside a view referenced by an external query

- azure-pipelines.yml
- tools/azure-pipelines/build-apache-repo.yml
- tools/azure-pipelines/build-nightly-dist.yml
- tools/azure-pipelines/e2e-template.yml
- tools/azure-pipelines/jobs-template.yml
Unchanged back port of #22858 on release-1.16
> [BP-1.16][FLINK-32392][ci] Invalidate Maven repo cache on Azure every year to reduce its disk usage

- docs/layouts/shortcodes/generated/all_taskmanager_network_section.html
- docs/layouts/shortcodes/generated/netty_shuffle_environment_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/NettyShuffleEnvironmentOptions.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/NettyClient.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/NettyConfig.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyClientTest.java
Add keepalive options to NettyClient. refer to: https://issues.apache.org/jira/browse/FLINK-32191
- *Add tcp keepalive related options to Netty client..*
- *For transport type of Epoll, set these configuration to NettyClient#bootstrap directly*
- *For transport type of Nio, set these configuration through reflection. Because some old versions of Java don't support certain features.*
- *Added test that validates that NettyClient could set these configuration in NIO and Epoll*
- *Verified the change by manually dropping the TCP Ack Package through iptables.*
- JDK 11 with NIO, TCP Keepalive is in effect.
- JDK 11 with Epoll, TCP Keepalive is in effect.
- JDK8u131 with Epoll, TCP Keepalive is in effect.
- JDK8u322 with NIO, TCP …
> [FLINK-32191][netty] support set keepalive options to NettyClient.

- flink-runtime/src/main/java/org/apache/flink/runtime/security/token/hadoop/KerberosLoginProvider.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/token/hadoop/KerberosLoginProviderITCase.java
In `KerberosLoginProvider.isLoginPossible()` there is a call to `UserGroupInformation.getCurrentUser()` before principal check (keytab usage). This triggers an accidental login with either kerberos credentials if available, or as the local OS user, based on security settings. This is not problematic most of the time since `KerberosLoginProvider.doLogin()` overwrites the credentials with keytab. The problem hurts however when login in `KerberosLoginProvider.isLoginPossible()` fails for whatever reason. Such case the workload is just not starting.
Removed accidental login in `KerberosLoginProvider.isLoginPossible()`.
Added new automated test.
- The …
> [FLINK-32465][runtime][security] Fix KerberosLoginProvider.isLoginPossible accidental login with keytab

- docs/layouts/shortcodes/generated/sql_client_configuration.html
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliClient.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/config/SqlClientOptions.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientITCase.java
The PR allows to have line numbers in SQL Client for multiline SQL.
In fact line numbers are already implemented in JLine and the only thing the PR does is allowing to toggle line numbers via property.
- Does this pull request introduce a new feature? (yes )
- If yes, how is the feature documented? (docs )
> [FLINK-24911][table] Enable line numbers in SQL Client

- flink-architecture-tests/flink-architecture-tests-production/src/main/java/org/apache/flink/architecture/rules/ConnectorRules.java
Archunit generates different violation sets depending on bytecode.
The PR makes skipping of Archunit rule `CONNECTOR_CLASSES_ONLY_DEPEND_ON_PUBLIC_API` for JDK11, 17.
manually 
```
mvn clean install -DskipTests -Dfast -Pjava17-target
mvn verify -pl flink-architecture-tests/flink-architecture-tests-production/ -Darchunit.freeze.store.default.allowStoreUpdate=false
```
or 
```
mvn clean install -DskipTests -Dfast -Pjava11-target
mvn verify -pl flink-architecture-tests/flink-architecture-tests-production/ -Darchunit.freeze.store.default.allowStoreUpdate=false
```
Also there are a couple of nightly tests testing it …
> [FLINK-32379][build] Skip archunit tests in java1X-target profiles

- flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinator.java
- flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContext.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorTest.java
Fix the bug about SourceCoordinator thread leaks. You can get more detailed background from FLINK-32411.
Closing the SourceCoordinatorContext inside of the SourceCoordinator#close even if the SourceCoordinator isn't started.
- *Added the SourceCoordinatorTest#testClosedWithoutStart*
- *Improved the SourceCoordinatorTest#testClosed*
- The S3 file system connector:no …
> [FLINK-32411][connector/common] Fix the bug about SourceCoordinator thread leaks

- docs/content.zh/docs/connectors/table/filesystem.md
- docs/content/docs/connectors/table/filesystem.md
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/src/enumerate/BlockSplittingRecursiveAllDirEnumerator.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/src/enumerate/NonSplittingRecursiveAllDirEnumerator.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/src/enumerate/NonSplittingRecursiveEnumerator.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/src/enumerate/RegexFileFilter.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/FileSystemConnectorOptions.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/FileSystemTableFactory.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/FileSystemTableSource.java
- flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/src/enumerate/BlockSplittingRecursiveAllDirEnumeratorTest.java
- flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/src/enumerate/NonSplittingRecursiveAllDirEnumeratorTest.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/connector/file/table/FileSystemTableSourceStreamingITCase.java
This pull request makes filesystem sources support flexible path reading.
- Add two new FileEnumerator and a new file filter.
- Add new table option 'source.regex-pattern'
- use the new FileEnumerator if 'source.regex-pattern' is set
> [FLINK-17398][connector/filesystem] Filesystem sources support flexible path reading

- docs/layouts/shortcodes/generated/environment_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/CoreOptions.java
- flink-dist/src/main/flink-bin/bin/config.sh
- flink-dist/src/main/flink-bin/bin/flink-console.sh
- flink-dist/src/main/flink-bin/conf/log4j-console.properties
- flink-dist/src/main/flink-bin/conf/logback-console.xml
Add an option for redirecting stdout/stderr to files. When this is enabled.
1. flink-console.sh will redirect stdout/err to file.
2. flink-console.sh use log4j.properties as log4j configuration to avoid logs both in log file and stdout file.
Of course, this option is false by default.
- *introduce new option kubernetes.flink.std.redirect.enabled, default is false*
- *when enabled, use log4j.properties/logback.xml as log configuration to avoid output log duplicated*
- *when enabled, redirect stdout/stderr to log directory so that user can view these in Flink's web ui*
- *Added unit tests for FlinkConfMountDecoratorTest.java*
- *Manually verified the change with kubernetes.flink.std.redirect.enabled is true or false.*
- The public …
> [FLINK-31234][kubernetes] Add an option to redirect stdout to log dir.

- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/ProjectionCodeGenerator.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/agg/batch/HashAggCodeGenerator.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/HashAggITCase.scala
*Currently, we don't consider the auxGrouping condition when generating the value projection code of adaptive local hash agg. This is a bug, so we need to fix it.*
- *Fix adaptive local hash can't work when auxGrouping exist*
- *Added integration tests in HashAggITCase*
- If yes, how …
> [FLINK-32426][table-runtime] Fix adaptive local hash can't work when auxGrouping exist

- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorAlignmentTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorConcurrentAttemptsTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContextTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorTestBase.java
SourceCoordinatorAlignmentTest.testAnnounceCombinedWatermarkWithoutStart fails
Root cause: multiple sources share the same thread pool, and the second source cannot start due to the first source closes the shared thread pool.
Create new thread pool for each SourceCoordinatorContext.
- The S3 file system connector:no
> [FLINK-32478][connectors/common] Fix the bug that the shared thread pool causes the source alignment unit test to fail

- docs/data/sql_functions.yml
- flink-python/docs/reference/pyflink.table/expressions.rst
- flink-python/pyflink/table/expression.py
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/InputTypeStrategies.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/ArrayComparableElementTypeStrategy.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/ArrayElementOutputTypeStrategy.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/SpecificTypeStrategies.java
- flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/strategies/ArrayComparableElementTypeStrategyTest.java
- flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/strategies/ArrayElementOutputTypeStrategyTest.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CollectionFunctionsITCase.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/ArrayMaxFunction.java
This is an implementation of ARRAY_MAX
The array_max() function get the maximum element from input array.
The result matches the type of the elements. NULL elements are skipped. If array is empty, or contains only NULL elements, NULL is returned.
Arguments
array: Any ARRAY with elements for which order is supported.
Syntax
array_max(array)
Returns
The result matches the type of the elements. NULL elements are skipped. If array is empty, or contains only NULL elements, NULL is returned.
Examples
SQL
```
> SELECT array_max(array(1, 20, NULL, 3)); 20
// Fink SQL-> select array_max(array[1, 20, null, 3]) 20
```
See also
spark https://spark.apache.org/docs/latest/api/sql/index.html#array_max
presto https://prestodb.io/docs/current/functions/array.html
This change added tests in …
> [FLINK-32257]-table-Add-ARRAY_MAX-function

- flink-rpc/flink-rpc-akka-loader/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaRpcSystemLoader.java
- flink-rpc/flink-rpc-akka-loader/src/test/java/org/apache/flink/runtime/rpc/akka/FallbackAkkaRpcSystemLoader.java
- flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/concurrent/akka/ActorSystemScheduledExecutorAdapter.java
- flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaInvocationHandler.java
- flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaRpcActor.java
- flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/AkkaRpcService.java
- flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/concurrent/akka/ClassLoadingUtilsTest.java
- flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/ContextClassLoadingSettingTest.java
- flink-rpc/flink-rpc-core/src/main/java/org/apache/flink/runtime/concurrent/ClassLoadingUtils.java
- flink-rpc/flink-rpc-core/src/main/java/org/apache/flink/runtime/rpc/CleanupOnCloseRpcSystem.java
- flink-rpc/flink-rpc-core/src/test/java/org/apache/flink/runtime/concurrent/ClassLoadingUtilsTest.java
This class is useful for any rpc system implementation and should thus be shared.
> [FLINK-32467][rpc] Move common RPC utils to rpc-core

- flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorProvider.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContextTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorProviderTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorTestBase.java
SourceCoordinatorAlignmentTest.testWatermarkAlignmentWithTwoGroups fails.
I analyzed this CI :  https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=50668&view=logs&j=a57e0635-3fad-5b08-57c7-a4142d7d6fa9&t=2ef0effc-1da1-50e5-c2bd-aab434b1c5b7&l=9089
Root cause:
- The CoordinatorExecutorThreadFactory cannot new multiple threads. And too many callers will check `coordinatorThreadFactory.isCurrentThreadCoordinatorThread()`, such as: SourceCoordinatorContext.attemptReady.
- The CoordinatorExecutorThreadFactory is shared at [SourceCoordinatorTestBase](https://github.com/apache/flink/blob/21eba4ca4cb235a2189c94cdbf3abcec5cde1e6e/flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorTestBase.java#L68)
- It will be used at multiple source …
> [FLINK-32495][connectors/common] Fix the bug that the shared thread factory causes the source alignment unit test to fail

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/source/SourceFunction.java
This is a trivial change that marks SourceFunction API as @Deprecated.
> [FLINK-28046][connectors] Mark SourceFunction interface as @Deprecated

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/file/ProducerMergedPartitionFileWriter.java
Looks like the issue was caused by the introduction of FLINK-31644 and the concurrent upgrade of flink-shaded.
Fixes the compilation error
mvn compile succeeds
> [FLINK-32505][network] Fixed compilation error in ProducerMergedPartitionFileWriter.

- docs/data/sql_functions.yml
- flink-python/docs/reference/pyflink.table/expressions.rst
- flink-python/pyflink/table/expression.py
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/ArrayOfStringArgumentTypeStrategy.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CollectionFunctionsITCase.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/ArrayJoinFunction.java
This is an implementation of ARRAY_JOIN
Returns a string that represents the concatenation of the elements in the given array and the elements' data type in the given array is string. The delimiter is a string that separates each pair of consecutive elements of the array. The optional nullReplacement is a string that replaces null elements in the array. If nullReplacement is not specified, null elements in the array will be omitted from the resulting string. Returns null if the input array and delimiter are null.
- Syntax:
`array_join(array, delimiter, [, null_replacement])`
- Arguments:
delimiter: A STRING used to separate the concatenated array elements.
null_replacement: A STRING used to express a NULL value in the result. It is a optional
- Return: …
> [FLINK-32259][table] Add built-in ARRAY_JOIN function.

- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedHaServices.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedLeaderService.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionService.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/LeaderContender.java
- flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/WebMonitorEndpoint.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedLeaderServiceTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/nonha/embedded/TestingLeaderContender.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionServiceTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/LeaderElectionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingContender.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingGenericLeaderContender.java
`LeaderContender.getDescription()` was barely used (only for the log output in the ZK driver implementation). With the `contenderID` becoming a more fundamental property of the `DefaultLeaderElectionService` we can get rid of the `getDescription()` method.
* Removes method from interface and implementing classes
* Removes method from test classes (trivial change) …
> [FLINK-32436][runtime] Removes obsolete LeaderContender.getDescription() method

- docs/content.zh/docs/dev/table/sql/show.md
- docs/content/docs/dev/table/sql/show.md
- flink-table/flink-sql-client/src/test/resources/sql/function.q
- flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl
- flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/dql/SqlShowFunctions.java
- flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/FunctionCatalog.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/functions/SqlLikeUtils.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/LikeType.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ShowFunctionsOperation.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/utils/OperationLikeType.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlNodeToOperationConversion.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlNodeConverters.java
- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlShowFunctionsConverter.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlOtherOperationConverterTest.java
Support enhanced show functions syntax for [FLIP-297](https://cwiki.apache.org/confluence/display/FLINK/FLIP-297%3A+Improve+Auxiliary+Sql+Statements)
Support enhanced show functions syntax:
```sql
SHOW [USER] FUNCTIONS [ ( FROM | IN ) [catalog_name.]database_name ] [ [NOT] (LIKE | ILIKE) <sql_like_pattern> ]
```
Add cases in FlinkSqlParserImplTest:
- testShowFunctions
Add cases in SqlOtherOperationConverterTest:
- testShowFunctions
- The S3 …
> [FLINK-32310][table] Support enhanced show functions syntax

- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/CoordinatorTestUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorAlignmentBenchmark.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorAlignmentBenchmarkTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorAlignmentTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorTestBase.java
[FLINK-32420](https://issues.apache.org/jira/browse/FLINK-32420) is improving the watermark aggregation performance.
We want to add a benchmark for it first, and then we can see the official performance change.
Add the SourceCoordinatorAlignmentBenchmark.
- *Added the  SourceCoordinatorAlignmentBenchmarkTest* …
> [FLINK-32506][connectors/common] Add the benchmark for watermark aggregation when enabling the watermark alignment

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/file/ProducerMergedPartitionFileReader.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TieredStorageNettyServiceImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TieredStorageResultSubpartitionView.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/TierFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/disk/DiskIOScheduler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/disk/DiskTierConsumerAgent.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/disk/DiskTierFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/disk/DiskTierProducerAgent.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/memory/MemoryTierFactory.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/common/TieredStorageTestUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/file/DiskIOSchedulerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/file/ProducerMergedPartitionFileReaderTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/file/ProducerMergedPartitionFileWriterTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/file/TestingPartitionFileReader.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TieredStorageConsumerClientTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/TestingTierFactory.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/disk/DiskTierProducerAgentTest.java
1. Introduce the ProducerMergePartitionFileReader
2. Introduce the DiskIOScheduler and ScheduledSubpartitionReader
> [FLINK-31645][network] Introduce the PartitionFileReader and  DiskIOSchduler

- flink-connectors/flink-connector-hive/src/main/resources/META-INF/NOTICE
- flink-formats/flink-sql-parquet/src/main/resources/META-INF/NOTICE
- flink-formats/pom.xml
The PR bumping Apache Parquet dependency to 1.13.1
pom and NOTICE files
> [FLINK-32526] Bump Apache Parquet from 1.12.3 to 1.13.1

- flink-python/pyflink/datastream/connectors/kafka.py
*This pull request fixes PyFlink Kafka connector support to support JDK17*
This change is already covered by existing tests, such as *test_kafka.py*.
> [FLINK-32327][python] Fix PyFlink Kafka support to support JDK17

- flink-core/src/test/java/org/apache/flink/util/concurrent/TestingUncaughtExceptionHandler.java
- flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/akka/RobustActorSystem.java
- flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/akka/RobustActorSystemTest.java
This is a backport of  https://github.com/apache/flink/pull/22764
It contains cherry-pick of 2 commits since the required one depends on [[hotfix] Simplify ActorSystem construction](https://github.com/apache/flink/commit/625e4db143d9ca5041e7b2d7875e413cb5f6f612)
the main reason is that same issue is still actual for 1.16 and 1.17
> [BP-1.16][FLINK-32314][rpc] Ignore classloading errors after actorsystem shutdown 

- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/src/impl/StreamFormatAdapter.java
- flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/src/impl/StreamFormatAdapterTest.java
- flink-formats/flink-csv/src/test/java/org/apache/flink/formats/csv/CsvFilesystemBatchITCase.java
Read empty csv file throws exception in FileSystem table connector. 
- *Remove size check, so `StreamFormatAdapter` can read empty files *
- *Added integration tests for reading empty csv file*
- *Added test that validates that `StreamFormatAdapter` read empty file*
> [FLINK-27415][Connectors / FileSystem] Read empty csv file throws exception in FileSystem table connector

- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionService.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/LeaderElectionEventHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/LeaderInformationRegister.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionServiceTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/LeaderInformationRegisterTest.java
* === THIS PR === FLINK-31784
* https://github.com/apache/flink/pull/22848
* …
> [FLINK-31784][runtime] Adds multi-component support to DefaultLeaderElectionService

- flink-examples/flink-examples-table/src/main/java/org/apache/flink/table/examples/java/connectors/SocketDynamicTableSource.java
- flink-examples/flink-examples-table/src/main/java/org/apache/flink/table/examples/java/connectors/SocketSource.java
*`SocketSource` can only work with parallelism of 1, It is best to force set it when load it in `DynamicTableSource`.*
- *Force set the parallelism of `SocketTableSource` to `1`*
- *Check parallelism of `SocketSource` when createReader.*
> [FLINK-32459][connector] Force set the parallelism of SocketTableSource to 1

- docs/content.zh/docs/connectors/table/filesystem.md
- docs/content/docs/connectors/table/filesystem.md
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/FileSystemConnectorOptions.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/FileSystemTableFactory.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/FileSystemTableSink.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/PartitionCommitPolicyFactory.java
- flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/stream/PartitionCommitter.java
- flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/table/FileSystemCommitterTest.java
- flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/table/TestCustomCommitPolicy.java
- flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/table/batch/compact/BatchPartitionCommitterSinkTest.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveOptions.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveTableSink.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectQueryITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableCompactSinkITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableSinkITCase.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/connector/file/table/FileSystemTableSinkTest.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/connector/file/table/TestCustomCommitPolicy.java
By allowing the passing of parameters, the custom PartitionCommitPolicy becomes more flexible and customizable. This enables user to enhance their custom PartitionCommitPolicy by including additional functionality, such as passing monitoring parameters to track the files associated with each commit.
- `SINK_PARTITION_COMMIT_POLICY_CLASS_PARAMETERS` parameter added
- To create a custom commit policy through the PartitionCommitPolicyFactory, you have the option to include `SINK_PARTITION_COMMIT_POLICY_CLASS_PARAMETERS` as a parameter.
- The runtime …
> [FLINK-32388]Add the ability to pass parameters to CUSTOM PartitionCommitPolicy

- flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinator.java
- flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContext.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorAlignmentTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContextTest.java
see [Flink-32362](https://issues.apache.org/jira/browse/FLINK-32362) …
> [FLINK-32362] [connectors/common] increase the robustness of announceCombinedWatermark to cover the case task failover

- flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinator.java
- flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContext.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorAlignmentTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContextTest.java
backport to 1.17, see [Flink-32362](https://issues.apache.org/jira/browse/FLINK-32362)
This change is a trivial rework / code cleanup …
> FLINK-32362] [connectors/common] increase the robustness of announceCombinedWatermark to cover the case task failover 

- flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinator.java
- flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContext.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorAlignmentTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContextTest.java
backport to 1.16, see [Flink-32362](https://issues.apache.org/jira/browse/FLINK-32362)
This change is a trivial rework / code cleanup …
> FLINK-32362] [connectors/common] increase the robustness of announceCombinedWatermark to cover the case task failover

- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedLeaderServiceTest.java
The purpose of `EmbeddedLeaderServiceTest.testConcurrentRevokeLeadershipAndShutdown` is to check that there is no `NullPointerException` happening if the event processing happens after the shutdown of the `EmbeddedExecutorService` (see [FLINK-11855](https://issues.apache.org/jira/browse/FLINK-11855)).
The concurrent execution is not handled properly, though. The test also succeeds if the close call happened before the shutdown (due to the multi-threaded nature of the test) which leaves us without the actual test scenario being tested.
* Introduced `ManuallyTriggeredScheduledExecutorService`
* Added proper asserts
* hotfix: Migrated `EmbeddedLeaderServiceTest` to JUnit5/AssertJ
Trivial change: The refactored tests should pass.
- The …
> [FLINK-32421][test] EmbeddedLeaderServiceTest.testConcurrentRevokeLeadershipAndShutdown is not properly implemented

- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedLeaderServiceTest.java
1.16 backport PR for parent PR https://github.com/apache/flink/pull/22865
> [BP-1.16][FLINK-32421][test] EmbeddedLeaderServiceTest.testConcurrentRevokeLeadershipAndShutdown is not properly implemented

- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultVertexParallelismInfo.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultVertexParallelismStore.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/VertexParallelismInformation.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/JobGraphJobInformation.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/allocator/JobInformation.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/allocator/SlotSharingSlotAllocator.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/DefaultVertexParallelismStoreTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/allocator/SlotSharingSlotAllocatorTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/allocator/TestVertexInformation.java
based on #22795 for ease of testing.
The Adaptive Scheduler now supports a _minimum_ parallelism per vertex.
* a job is only run if the minimum required slots of all vertices is fulfilled
* if the minimum parallelism is being raised above the currently available number of slots (== implicitly above the current parallelism) the scheduler immediately cancels the job and tries to rescale it. It will either restart the job if it could acquire the additionally required slots, or fail the job once the stabilization timeout kicked in.
* We could consider adding some timeout here for the cancellation, to give us some time to acquire more slots.
* if the minimum parallelism is lowered, or raised below the current parallelism, the job just keeps running.
> [FLINK-31476] AdaptiveScheduler respects minimum parallelism 

- flink-python/pyflink/pyflink_gateway_server.py
- flink-python/pyflink/table/tests/test_sql.py
*This pull request fixes test_java_sql_ddl to works in JDK17*
*(or)*
*(or)*
*(example:)*
- *Added integration …
> [FLINK-32544][python] Fix test_java_sql_ddl to works in JDK17

- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdSelectivity.scala
- flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/agg/WindowAggregateTest.xml
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdSelectivityTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/agg/WindowAggregateTest.scala
Currently when uses window aggregation referring a windowing tvf with a filter condition, may encounter wrong plan which may hang forever in runtime(the window aggregate operator never output), because the plan which didn't combine the proctime `WindowTableFunction` into `WindowAggregate` (so when translate to execution plan the `WindowAggregate` will wrongly recognize the window as an event-time window, then the `WindowAggregateOperator` will not receive watermark nor setup timers to fire any windows in runtime).
The root cause is the incorrectly cost evaluation in such cases for streaming, we can fix this by simply adding a branch for calculating selectivity of `CommonPhysicalWindowTableFunction` node which is the base factor for row count.
Ideally, maybe we can do some more refactoring …
> [FLINK-32501][table-planner] Fix wrong plan of a proctime window aggregation generated due to incorrect cost evaluation

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/common/TieredStorageConfiguration.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/common/TieredStorageUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/file/ProducerMergedPartitionFile.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/file/SegmentPartitionFile.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/file/SegmentPartitionFileReader.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/file/SegmentPartitionFileWriter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/shuffle/TieredInternalShuffleMaster.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/TierFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/disk/DiskTierFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/disk/DiskTierProducerAgent.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/memory/MemoryTierFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/remote/RemoteCacheManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/remote/RemoteTierFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/remote/RemoteTierMasterAgent.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/remote/RemoteTierProducerAgent.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/remote/SubpartitionRemoteCacheManager.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/common/TieredStorageTestUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/file/SegmentPartitionFileTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/file/SegmentPartitionFileWriterTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/TestingTierFactory.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/disk/DiskTierProducerAgentTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/remote/RemoteCacheManagerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/remote/RemoteTierMasterAgentTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/remote/SubpartitionRemoteCacheManagerTest.java
*Implement the remote tier producer for the tiered storage*
- *【commit 1】 Implement HashPartitionFile for the tiered storage*
- *【commit 2】Implement the remote tier producer for the tiered storage*
This change will add tests.
> [FLINK-31646][network] Implement the remote tier producer for the tiered storage

- docs/layouts/shortcodes/generated/optimizer_config_configuration.html
- docs/layouts/shortcodes/generated/pipeline_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/PipelineOptions.java
- flink-python/pyflink/datastream/stream_execution_environment.py
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraph.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraphGenerator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGenerator.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGeneratorTest.java
- flink-streaming-scala/src/test/scala/org/apache/flink/streaming/api/scala/StreamingScalaAPICompletenessTest.scala
https://issues.apache.org/jira/browse/FLINK-31996
Introduce a new opt-in flag that can disable the chaining of operators with different max parallelism, which prevents rescaling in some cases when the AdaptiveScheduler is being used.
- We introduce the new `pipeline.operator-chaining.chain-operators-with-different-max-parallelism` flag to opt-in.
- We deprecate the `pipeline.operator-chaining` flag and surpass it with `pipeline.operator-chaining.enabled` to provide a more consistent configuration experience.
- The StreamingJobGraphGenerator and StreamGraphHasherV2 respect the new flag.
> [FLINK-31996] Chaining operators with different max parallelism prevents rescaling

- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnTestBase.java
in `YARNSessionFIFOSecuredITCase` test case teardown, it seems a new kind of Akka warning can happen, that actually logs an exception that we did not whitelist yet. The relevant log piece (last 2 lines) that triggers to fail the test exec:
```
Jun 20 01:30:32 2023-06-20 01:29:57,749 INFO  org.apache.flink.runtime.rpc.akka.AkkaRpcService             [] - Stopping Akka RPC service.
Jun 20 01:30:32 2023-06-20 01:29:57,767 WARN  akka.actor.CoordinatedShutdown                               [] - Could not addJvmShutdownHook, due to: Shutdown in progress
Jun 20 01:30:32 2023-06-20 01:29:57,767 INFO  akka.actor.CoordinatedShutdown                               [] - Running CoordinatedShutdown with reason [ActorSystemTerminateReason]
Jun 20 01:30:32 2023-06-20 01:29:57,768 WARN …
```
> [FLINK-32391][yarn][test] Extend log whitelist for expected Akka shutdown WARN exception

- flink-core/src/main/java/org/apache/flink/configuration/ConfigConstants.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/HttpHeader.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/RestClient.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/CustomHeadersDecorator.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/MessageHeaders.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/ExecutorImpl.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/ExecutorImplITCase.java
[FLINK-32030](https://issues.apache.org/jira/browse/FLINK-32030) and [FLINK-32035](https://issues.apache.org/jira/browse/FLINK-32035) enable communication from the SQL Client to the SQL Gateway placed behind a proxy (i.e. a K8S ingress). Such use cases typically require authentication. This PR enables authentication by adding the ability to supply custom headers to the underlying RestClient.
- Added a test that verifies that custom headers are read and parsed correctly …
> [FLINK-32373][sql-client] Support passing headers with SQL Client gateway requests

- docs/content.zh/docs/dev/table/sql/alter.md
- docs/content.zh/docs/dev/table/sql/show.md
- docs/content/docs/dev/table/sql/alter.md
- docs/content/docs/dev/table/sql/show.md
Add doc for add/drop/show partition.
Add doc for add/drop/show partition.
This change is about docs without any test coverage.
> [FLINK-32397][docs]Add doc for add/drop/show partition

- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionService.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionServiceTest.java
This Precondition can be enabled because the processing of revoke calls is not happening anymore during close. The event processing is protected by the running flag within DefaultLeaderElectionService which is set to false as part of the close mechanism.
* Enables the Precondition
I left the test case (with some refactoring) because it's a valid test to verify that we don't run into issues when an event is processed after the contender was already deregistered. …
> [FLINK-31814][runtime] Enables Precondition that checks that the issuedLeaderSessionID is set on revoke processing

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/HashSubpartitionBufferAccumulator.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/disk/SubpartitionDiskCacheManager.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/HashBufferAccumulatorTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/SortBufferAccumulatorTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/disk/SubpartitionDiskCacheManagerTest.java
*Fix the buffer leaking when buffer accumulator is released*
- *Fix the buffer leaking when buffer accumulators is released*
- *Added tests for in the `SortBufferAccumulatorTest` and `HashBufferAccumulatorTest`*
> [FLINK-32541][network] Fix the buffer leaking when buffer accumulator is released

- flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/source/TimestampsAndWatermarks.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/source/WatermarkToDataOutput.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorAlignmentTest.java
When one source is always active and other sources are idle (Either there is no data, or alignment causes idle.), these source won't resume.
For example, sourceA is always active, sourceB is idle due to there is no data. SourceB won't resume forever even if it can read more data.
- Step1: When source is idle, [WatermarkToDataOutput will update](https://github.com/apache/flink/blob/c1740861727d2614f9bbf154bcdd274d7990e133/flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/source/WatermarkToDataOutput.java#L95C12-L95C12) the `Long.MAX_VALUE` to [`SourceOperator#lastEmittedWatermark`](https://github.com/apache/flink/blob/c1740861727d2614f9bbf154bcdd274d7990e133/flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java#L605) as …
> [FLINK-32496][connectors/common] Fix the bug that source cannot resume after enabling the watermark alignment and idleness

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionDriver.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionDriverFactory.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/KubernetesUtils.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesHighAvailabilityTestBase.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionAndRetrievalITCase.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionDriverTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionService.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/LeaderElectionDriver.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/LeaderElectionDriverFactory.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionDriver.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionDriverFactory.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/AbstractHaServicesTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionServiceTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/LeaderElectionEvent.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingLeaderElectionDriver.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingLeaderElectionListener.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionDriverTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderretrieval/ZooKeeperLeaderRetrievalTest.java
* https://github.com/apache/flink/pull/22844
* …
> [FLINK-32381][runtime] Replaces FatalErrorHandler by Listener.onError

- flink-end-to-end-tests/flink-end-to-end-tests-restclient/pom.xml
- flink-end-to-end-tests/flink-end-to-end-tests-restclient/src/test/java/org/apache/flink/runtime/rest/RestClientITCase.java
- flink-end-to-end-tests/flink-end-to-end-tests-restclient/src/test/resources/log4j2-test.properties
- flink-end-to-end-tests/pom.xml
- flink-runtime/src/main/java/org/apache/flink/runtime/net/SSLUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/RestClient.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/RestClientTest.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/ExecutorImpl.java
SQL Client gateway mode allows to submit SQL queries to remote Flink clusters.The target clusters are often placed behind proxies, such as K8S ingresses. [FLINK-32030](https://issues.apache.org/jira/browse/FLINK-32030) expanded the capability to connect to SQL gateways using URLs. This PR addresses the limitation caused by the tight coupling between the underlying `RestClient` and internal cluster SSL configuration. It makes it possible to connect to HTTPS endpoints using built-in JDK keystores rather than forcing usage of user-supplied once. 
- Makes  user-supplied `TrustManager` configuration optional when enabling SSL
- Automatically enables SSL in RestClient for `https://` URLs
- Makes use of encrypted endpoints in SQL Client
- Added test to verify that a HTTPS connection using …
> [FLINK-32035][sql-client] Support HTTPS endpoints in SQL Client gateway mode

- docs/data/sql_functions.yml
- docs/data/sql_functions_zh.yml
- flink-python/docs/reference/pyflink.table/expressions.rst
- flink-python/pyflink/table/expression.py
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
- flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CollectionFunctionsITCase.java
- flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/ArraySliceFunction.java
Implement the array_slice function to extract a subset of elements from an array.
Returns a subarray of the input array between 'start_offset' and 'end_offset' inclusive. 
The offsets are 1-based however 0 is also treated as the beginning of the array. 
Positive values are counted from the beginning of the array while negative from the end. 
If 'end_offset' is omitted then this offset is treated as the length of the array. 
If 'start_offset' is after 'end_offset' or both are out of array bounds an empty array will be returned. 
Returns null if any input is null.
ARRAY_SLICE for Table API and SQL
Syntax:
`ARRAY_SLICE(array, start_offset[, end_offset])`
Arguments:
array: The array that contains the elements you want to slice.
start_offset: The inclusive starting offset.
end_offset: The …
> [FLINK-32260][table] Add built-in ARRAY_SLICE function.

- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/AbstractHaServices.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/HighAvailabilityServices.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElection.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionService.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterServiceLeadershipRunnerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionServiceTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/LeaderElectionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingLeaderElectionDriver.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionConnectionHandlingTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionTest.java
The driver doesn't need to be instantiated when the `DefaultLeaderElectionService` is instantiated. Instead, we can instantiated when the first contender is registered. This way we can avoid creating the `DefaultLeaderElectionService` lazily in the HaServices.
* Made `startLeaderElectionBackend` private
* Calls the method instead in `DefaultLeaderElectionService#register`
* Aligned Preconditions in `DefaultLeaderElectionService` accordingly
* Adds testcase for verifying the lazy driver instantiation
* Adds tests for proper close handling
* Removes `DefaultLeaderElectionServiceTest#testContenderRegistrationWithoutDriverBeingInstantiatedFails` because this case isn't possible anymore: The driver instantiation always happens when registering the first contender
- Dependencies (does it add or …
> [FLINK-31837][runtime] Makes LeaderElectionDriver instantiation happen lazily

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/DataStream.java
- flink-streaming-scala/src/main/scala/org/apache/flink/streaming/api/scala/DataStream.scala
*`TimestampAssigner#extractTimestamp` is used for element not event.*
- *Fix typo in `DataStream.java` and `DataStream.scala`.*
> [hotfix][streaming] Fix typo in DataStream.java and DataStream.scala.

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionDriver.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionHaServices.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderRetrievalDriverFactory.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/KubernetesUtils.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesHighAvailabilityTestBase.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionAndRetrievalITCase.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionDriverTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedLeaderService.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/zookeeper/ZooKeeperLeaderElectionHaServices.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElection.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionService.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/LeaderElectionDriver.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/LeaderElectionService.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/LeaderInformationRegister.java
- flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionDriver.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedLeaderServiceTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterServiceLeadershipRunnerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionServiceTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/LeaderElectionEvent.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/LeaderElectionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/LeaderInformationRegisterTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingLeaderElectionDriver.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingLeaderElectionListener.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionConnectionHandlingTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionDriverTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionTest.java
We introduced contenderID in a lot of places with [FLINK-26522](https://issues.apache.org/jira/browse/FLINK-26522). The original multi-component leader election classes of [FLINK-24038](https://issues.apache.org/jira/browse/FLINK-24038) used componentId.
Revisiting that naming made me realize that it's actually wrong. A contender is a specific instance of a component that participates in the leader election. A component, in this sense, is the more abstract concept. contenderID refers to an ID for the specific contender instance but the IDs we're sharing are actually referring to a Flink component and therefore, are the same between different contenders which compete for leadership for the same component. This contradicts the definition of an identifier.
Renames of all occurrences that …
> [FLINK-32556][runtime] Renames contenderID into componentId

- flink-runtime-web/web-dashboard/src/app/pages/job/overview/backpressure/job-overview-drawer-backpressure.component.html
Ensure that all subtasks are sorted by busy ratio at the backpressure tab by default
Remove the default `nzSortOrder`  for backpressure and idle at the backpressure tab.
> [FLINK-32568][web] Ensure that all subtasks are sorted by busy ratio at the backpressure tab by default

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/Buffer.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/CompositeBuffer.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/FileRegionBuffer.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/NetworkBuffer.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/ReadOnlySlicedNetworkBuffer.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/shuffle/TieredResultPartition.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/SortBufferAccumulator.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/TieredStorageMemoryManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/TieredStorageMemoryManagerImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/TieredStorageProducerClient.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/TierProducerAgent.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/disk/DiskCacheManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/disk/DiskTierProducerAgent.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/memory/MemoryTierProducerAgent.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/remote/RemoteTierProducerAgent.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/TestingTierProducerAgent.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/TestingTieredStorageMemoryManager.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/TieredStorageMemoryManagerImplTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/disk/DiskTierProducerAgentTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/memory/MemoryTierProducerAgentTest.java
Currently, the accumulator is responsible for requesting all buffers, leading to an inaccurate number of requested buffers for each tier.
To address this issue, buffer ownership must be transferred from the accumulator to the tiers when writing them, which will enable the memory manager to maintain a correct number of requested buffers for different owners.
- *Tiered storage memory manager supports ownership transfer for buffers*
**Version 1 (Deprecated. Do not use this way to fix anymore)**:
1. In order to transfer ownership, added a new API `TieredStorageMemoryManager#transferBufferOwnership`.
2. If `TierProducerAgent#tryWrite` returns `true` (indicating the write is successful), then 
the buffer has been written to the tier(once written, the buffer may be consumed or flushed …
> [FLINK-32549][network] Tiered storage memory manager supports ownership transfer for buffers
