flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinator.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/heap/AbstractHeapPriorityQueueElement.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorAlignmentTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/InternalPriorityQueueTestBase.java, flink-runtime/src/test/java/org/apache/flink/runtime/testutils/statemigration/TestType.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBCachingPriorityQueueSet.java
Watermark aggregation performance is poor when watermark alignment is enabled and parallelism is high. I have described the issue in detail in FLINK-32420, you can get more detailed background from FLINK-32420.
Based on the suggestion of @StefanRRichter  and @pnowojski .
Improve the watermark aggregation performance, the general idea of using some ordered data structure should be still applicable here.
We could use the already existing Map watermarks just as it is. And on top of that have an ordered structure of watermarks called fooBar. Now per each aggregate invocation
- we are using watermarks map to know what was the old value for the given key
- remove the old value from fooBar
- add new watermark value to fooBar
Giving us O(n*log n). We use the `HeapPriorityQueue` as the ordered …
=> [FLINK-32420][connectors/common] Improve the watermark aggregation performance

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestExecutorFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestExecutorImpl.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestExecutorFactoryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestExecutorImplTest.java
Fix thread-safe bug of channel state executor when some subtasks are closed while other subtasks are starting.
When one subtask is closing, it will call the `ChannelStateWriteRequestExecutorImpl#releaseSubtask`. The `releaseSubtask` [method](https://github.com/apache/flink/blob/2dfff436c09821fb658bf8d289206b9ef85bb25b/flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestExecutorImpl.java#L390) will hold 2 locks at the different time.
- The first one is `ChannelStateWriteRequestExecutorImpl#lock`, and update the `isRegistering` from true to false.
- The second one is `onRegistered.accept(this)` will hold `ChannelStateWriteRequestExecutorFactory#lock` and update the `ChannelStateWriteRequestExecutorFactory#executor`
However, these 2 locks are held …
=> [FLINK-32049][checkpoint] Fix thread-safe bug of channel state executor when some subtasks are closed while other subtasks are starting

flink-table/flink-table-common/src/main/java/org/apache/flink/table/procedures/ProcedureDefinition.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/BaseMappingExtractor.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/DataTypeExtractor.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/FunctionMappingExtractor.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/FunctionTemplate.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/ProcedureMappingExtractor.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/TemplateUtils.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/TypeInferenceExtractor.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/extraction/TypeInferenceExtractorTest.java
To support type inference for procedure
-  Consider the procedure as a special function in internal implementation since they are almost simlar in the concept and it make the procedure can share the infra has built for function
-  Extract some common logic from `FunctionMappingExtractor` used for function type inference to `BaseMappingExtractor` so that it can be shared by `ProcedureMappingExtractor` for type inference of procure
-  Create `ProcedureMappingExtractor` which extends `BaseMappingExtractor` to infer type for procedure as well as some adjustment for procedure
Added test in `TypeInferenceExtractorTest`.
- The …
=> [FLINK-32481][table] Support type inference for procedure

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/optimize/StreamNonDeterministicUpdatePlanVisitor.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/NonDeterministicDagTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/NonDeterministicDagTest.scala
This is an minor addition to the FLINK-27849 implementation to support the analysis of the `MatchRecognize` node.
Since the `MatchRecognize` will not support updating inputs in the foreseeable future, here we keep the analytic logic as a relatively simple one.
add the analytic logic of `MatchRecognize` node in `StreamNonDeterministicUpdatePlanVisitor`
added test cases into `NonDeterministicDagTest` …
=> [FLINK-28743][table-planner] Supports validating the determinism for StreamPhysicalMatchRecognize

flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/calcite/FlinkTypeFactoryTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/stream/sql/InsertIntoValuesTest.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/InsertIntoValuesTest.xml
The PR adds tsets confirming that the issue from previous versions (before Calcite 1.27.0) is fixed
2 tests from FLINK-26549
The PR itself adds only tests
=> [FLINK-26549][table][tests] Add tests for INSERT INTO with VALUES leads to wrong type inference with nested types

flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogBaseTableResolutionTest.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogPropertiesUtil.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/DefaultCatalogTable.java
Fix the incomplete serialization of ResolvedCatalogTable caused by the newly introduced time travel interface
In order to implement time travel, we added Snapshot information to DefaultCatalogTable, but Snapshot is not used when ResolvedCatalogTable is serialized and deserialized, we break the contract that ResolvedCatalogTable is fully serializable.
So, we should change CatalogPropertiesUtil to fix this.
-  Fix the de/serialization in CatalogPropertiesUtil::serializeCatalogTable and  CatalogPropertiesUtil:: deserializeCatalogTable
- Fix the equals and hashCode method of DefaultCatalogTable
This change is already covered by existing tests, such as *org.apache.flink.table.catalog.CatalogBaseTableResolutionTest#testPropertyDeSerialization*. …
=> [FLINK-32569][table] Fix the incomplete serialization of ResolvedCatalogTable caused by the newly introduced time travel interface

docs/content.zh/docs/dev/table/concepts/time_attributes.md, docs/content/docs/dev/table/concepts/time_attributes.md, flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/FactoryUtil.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/watermark/WatermarkEmitStrategy.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/watermark/WatermarkParams.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/factories/FactoryUtilTest.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/hint/FlinkHintStrategies.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/abilities/source/WatermarkPushDownSpec.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/PushWatermarkIntoTableSourceScanRuleBase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/serde/DynamicTableSourceSpecSerdeTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/rules/logical/PushWatermarkIntoTableSourceScanRuleTest.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/TableSourceJsonPlanTest_jsonplan/testWatermarkPushDown.out, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/PushWatermarkIntoTableSourceScanRuleTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/FilterableSourceTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/SourceWatermarkTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/TableScanTest.xml, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/generated/GeneratedWatermarkGeneratorSupplier.java
The PR proposes to extend watermark-related features in SQL layer, these fetures have been implemented on the datastream API, but not available in sql yet.
The extening features as follows:
1. configurable watermark emit strategy in sql
2. dealing with idle sources in sql
3. configurable watermark alignment in sql
- Added `org.apache.flink.table.watermark.WatermarkParams` to express the parameters of extended watermark-related features
- Added and validated releated params in `org.apache.flink.table.factories.FactoryUtil`
- Parse out the watermark-related configs from hint or table options in `org.apache.flink.table.planner.plan.rules.logical.PushWatermarkIntoTableSourceScanRuleBase`
- Handle watermark-related features in `org.apache.flink.table.planner.plan.abilities.source.WatermarkPushD …
=> [FLINK-31535][table] Extend watermark-related features for SQL

docs/content.zh/docs/ops/metrics.md, docs/content/docs/ops/metrics.md, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricNames.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/TaskIOMetricGroup.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/TaskIOMetricGroupTest.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
Currently, the task back-pressured by the changelog state backend is shown as busy, this PR adds `ioBackPressuredTimePerSecond` metric and accumulates it into total `BackPressuredTimePerSecond`.
- Add `ioBackPressuredTimePerSecond` metric
- Accumulates `ioBackPressuredTimePerSecond` into total `backPressuredTimePerSecond`
This change added tests and can be verified by `TaskIOMetricGroupTest#testTaskIOMetricGroup()`
- The S3 file …
=> [FLINK-24402][metric] Add a metric for back-pressure from the ChangelogStateBackend

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/TableEnvironment.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/Catalog.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/delegation/PlannerContext.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/delegation/PlannerBase.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/catalog/UnknownCatalogTest.java
Make it possible to unset the default catalog and/or database
* accept `null` in `useCatalog` and `useDatabase`
* adjust `CatalogReader` search paths
* throw an exception if we end up qualifying an identifier without a default catalog and/or database set.
- …
=> [FLINK-32584] Make it possible to unset default catalog and/or database

flink-formats/flink-protobuf/pom.xml, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/CodeGenUtils.scala, flink-table/flink-table-runtime/src/main/resources/META-INF/NOTICE, flink-table/pom.xml
The PR updates Janino to 3.1.10 and removed WA with explicit cast of nulls which was introduced at https://github.com/apache/flink/pull/21500 to cope with Janino issue https://github.com/janino-compiler/janino/issues/188.
Now the fix of this issue is in 3.1.10, so no need for WA anymore …
=> [FLINK-30984][table] Upgrade Janino to 3.1.10 and Remove explicit cast required by 3.1.9

docs/layouts/shortcodes/generated/execution_config_configuration.html, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/config/ExecutionConfigOptions.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecSink.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/table/TableSinkITCase.scala
This allows disabling the TimestampInserter and also avoids the error message of multiple rowtime attributes in the schema.
- Add ExecutionConfigOption `table.exec.sink.rowtime-inserter`.
- `TableSinkITCase`
=> [FLINK-32613] Add ConfigOption for disabling TimestampInserter

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/physical/stream/StreamPhysicalGroupAggregateRule.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/physical/stream/StreamPhysicalWindowAggregateRule.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/WindowUtil.scala, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/agg/WindowAggregateTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/agg/WindowAggregateTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/WindowAggregateITCase.scala
Currently when group by window time columns on a proctime window operator result will get a wrong plan which may result hang for ever in runtime(this only happens with informally supported forms, all standard forms cascaded window aggregation works fine). 
This is because an incorrectly translation that create an event-time window agg operator in such case, but actually there's no corresponding window assigner to trigger the window (no local timeservice neither).  For the fix, we convert these cases into a normal group aggregate to make it works and doesn't break anything.
fix the matching logic of `StreamPhysicalWindowAggregateRule` in proctime mode and related path
adds test cases to verify the plan changes in `WindowAggregateTest` …
=> [FLINK-32578][table-planner] Fix wrong plan which group by window time columns on a proctime window operator may result hang for ever

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/source/SourceFunction.java
This PR reverts commit 07bf511a32b525f94d258daec347cf777b31bebb, which marks SourceFunction interface as @deprecated.
We need to resolve all subtasks in FLINK-28045 and then deprecated SourceFunction interface.
reverts commit 07bf511a32b525f94d258daec347cf777b31bebb
This change is a revert without any test coverage. …
=> Revert "[FLINK-28046][connectors] Mark SourceFunction interface as @deprecated"

flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/environment/MiniClusterTestEnvironment.java
Connector tests can need to set a different configuration from the default one.
TRIVIAL. See the diff.
- If yes, how is the feature documented? (not applicable / …
=> [FLINK-32625][tests] MiniClusterTestEnvironment supports customized MiniClusterResourceConfiguration

flink-java/src/main/java/org/apache/flink/api/java/ExecutionEnvironment.java, flink-java/src/test/java/org/apache/flink/api/java/ExecutionEnvironmentTest.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironmentTest.java
If multiple threads call `initializeContextEnvironment` then they may interfere with the value stored in the thread local, because that is derived from a field in the environment, not the method argument.
=> [FLINK-32592] Fix (Stream)ExEnv#initializeContextEnvironment thread-safety

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
Return actual minimum parallelism bound instead of hardcoded 1.
Extended existing unit tests to cover this case.
- Anything that affects deployment or recovery: no
=> [FLINK-32623] Return correct vertex resource lower bound

docs/layouts/shortcodes/generated/expert_rest_section.html, docs/layouts/shortcodes/generated/rest_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/RestOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMasterGateway.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/RestHandlerConfiguration.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/checkpoints/AbstractCheckpointHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/checkpoints/AbstractCheckpointStatsHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/checkpoints/CheckpointStatisticDetailsHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/checkpoints/CheckpointingStatisticsHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/checkpoints/TaskCheckpointStatisticDetailsHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerNG.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java, flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/NonLeaderRetrievalRestfulGateway.java, flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/RestfulGateway.java, flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/WebMonitorEndpoint.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/TestingJobManagerRunner.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/utils/TestingJobMasterGateway.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/utils/TestingJobMasterGatewayBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/RestHandlerConfigurationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/job/checkpoints/AbstractCheckpointStatsHandlerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/TestingSchedulerNG.java, flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/TestingDispatcherGateway.java, flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/TestingRestfulGateway.java
Simplify the checkpoint handler API.
The checkpoint endpoints do not require the entire ExecutionGraph to produce their result. In fact, they only require the CheckpointStatsSnapshot. This change refactors the handlers to use only the CheckpointStatsSnapshot.
- Checkpoint REST handlers now consume from `AbstractCheckpointStatsHandler` that provides the `CheckpointStatsSnapshot`.
- `CheckpointsStatsSnapshot` is cached, to reduce call rate to underlying JobMaster. 
- Added unit tests
- Manually ran the Flink dashboard and tested the refresh rate on checkpoint API.
- The …
=> [FLINK-32469][REST] Improve checkpoint REST APIs for programmatic access

flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/windowing/WindowOperator.java
*Reactive sanity check for windowOperator's mergeable state.*
- *Remove todo in windowOperator.*
- *Reactive sanity check for windowOperator's mergeable state.*
=> [hotfix][streaming] Reactive sanity check for windowOperator's mergeable state.

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/AlterDatabaseOperation.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/CreateDatabaseOperation.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/DropDatabaseOperation.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlDdlToOperationConverterTest.java
This PR aims to add database operations in CatalogManager, then Create/Alter/DropDatabaseOperation can use catalog manager to do some operations for database and we can add a listener in catalog manager for them later.
- Add create/alter/drop database method in catalog manager
- Use catalog manager for database in Create/Alter/DropDatabaseOperation …
=> [FLINK-32403][table] Add database related operations in CatalogManager

docs/layouts/shortcodes/generated/table_config_configuration.html, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/context/SessionContext.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/context/SessionContextTest.java, flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/api/bridge/java/internal/StreamTableEnvironmentImpl.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/config/TableConfigOptions.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/listener/CatalogContext.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/listener/CatalogModificationEvent.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/listener/CatalogModificationListener.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/listener/CatalogModificationListenerFactory.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/factories/TableFactoryUtil.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/listener/CatalogFactory1.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/listener/CatalogFactory2.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/listener/CatalogListener1.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/listener/CatalogListener2.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/listener/CatalogListenerFactoryTest.java, flink-table/flink-table-api-java/src/test/resources/META-INF/services/org.apache.flink.table.factories.Factory, flink-table/flink-table-api-scala-bridge/src/main/scala/org/apache/flink/table/api/bridge/scala/internal/StreamTableEnvironmentImpl.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/EnvironmentTest.java, flink-table/flink-table-planner/src/test/resources/META-INF/services/org.apache.flink.table.factories.Factory, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/catalog/CatalogListenerTest.scala
This PR aims to add catalog modification listener interface and create the listeners for catalog manager from configuration
- Add catalog modification listener interface
- Create listeners for CatalogManager
- Added `EnvironmentTest.testCreateCatalogModificationListeners` to create specific listeners for `CatalogManager` from configuration …
=> [FLINK-32404][table] Add catalog modification listener interface and create listener for catalog manager

docs/content.zh/docs/ops/metrics.md, docs/content/docs/ops/metrics.md, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricNames.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/TaskIOMetricGroup.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/TaskIOMetricGroupTest.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
This PR wants to introduce restoring metric:
- Job level: The initializing stage is used to initialize the state of job, `initializingTime` can be treated as the restore time of the whole job when restoring from a checkpoint/savepoint. Since [FLINK-23976](https://issues.apache.org/jira/browse/FLINK-23976) added standardized metrics for capturing how much time we spend in each JobStatus, we can reuse `initializingTime/initializingTotalTime` directly. 
- Task level: This PR introduce `checkpointRestoreTime` for capturing how much time each task spends on restoring/initializing, returning 0 if task is not in initialization status. 
- Add `checkpointRestoreTime` metric.
Please make sure both new and modified tests in this PR follows the conventions defined in our code quality guide: …
=> [FLINK-19010][metric] Introduce subtask level restore metric

flink-runtime-web/web-dashboard/src/app/interfaces/task-manager.ts, flink-runtime-web/web-dashboard/src/app/pages/task-manager/metrics/task-manager-metrics.component.html
Adds an overview over allocated slots to the TM metrics page.
Now that I'm looking at the screenshot I wonder if the row could be misinterpreted as "job X has 0 slots allocated" :thinking: 
One problem we have is that the order of slots isn't deterministic, so slots may jump around in the table when more are dynamically allocated.
The REST API isn't exposing something right now based on which we could _easily_ sort slots to remedy this (like the allocation id).
=> [FLINK-32169][ui] Show slot allocations on TM page

docs/content.zh/docs/connectors/table/formats/json.md, docs/content/docs/connectors/table/formats/json.md, flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/AbstractJsonDeserializationSchema.java, flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonFormatFactory.java, flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonFormatOptions.java, flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonParseException.java, flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonParserRowDataDeserializationSchema.java, flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonParserToRowDataConverters.java, flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonRowDataDeserializationSchema.java, flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonRowDataSerializationSchema.java, flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonToRowDataConverters.java, flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/JsonFormatFactoryTest.java, flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/JsonParserRowDataDeSerSchemaTest.java, flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/JsonRowDataSerDeSchemaTest.java
*This PR mainly do two aspects of work, the first is the use of Jackson streamig api parsing json, which can improve the parsing efficiency; the second is to support nested types of projection pushdown*
- *Optimize JSON schema data deserialization using jackson streaming api*
- *JSON format supports nested type projection push down*
- *Added unit tests in JsonRowDataDeSerSchemaProjectedTest* …
=> [FLINK-32610][json] JSON format supports nested type projection pushdown

docs/data/sql_functions.yml, docs/data/sql_functions_zh.yml, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/WrapJsonAggFunctionArgumentsRule.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/JsonAggregationFunctionsITCase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/rules/logical/WrapJsonAggFunctionArgumentsRuleTest.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/WrapJsonAggFunctionArgumentsRuleTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/SortAggITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/AggregateITCase.scala
This pr is aims to support JSON_OBJECTAGG & JSON_ARRAYAGG use with other aggregate functions.
- Modify WrapJsonAggFunctionArgumentsRule
- Adding test cases
- Modify docs
Adding UT and ITCase
=> [FLINK-32456][table-planner] Support JSON_OBJECTAGG & JSON_ARRAYAGG use with other aggregate functions

flink-table/flink-sql-jdbc-driver/src/main/java/org/apache/flink/table/jdbc/FlinkConnection.java, flink-table/flink-sql-jdbc-driver/src/main/java/org/apache/flink/table/jdbc/FlinkStatement.java, flink-table/flink-sql-jdbc-driver/src/test/java/org/apache/flink/table/jdbc/FlinkStatementTest.java
This pr aims to close statement result in FlinkStatement.executeQuery when the statement is not a query sql.
- Close statement result when the sql is not query for FlinkStatement.executeQuery
- Added FlinkStatementTest.testCloseNonQuery to validate the statement result is closed.
- The S3 file …
=> [FLINK-32616][jdbc-driver] Close result for non-query in executeQuery

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/listener/AlterDatabaseEvent.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/listener/CatalogContext.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/listener/CreateDatabaseEvent.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/listener/DatabaseModificationEvent.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/listener/DropDatabaseEvent.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogManagerTest.java
This PR aims to create event for database ddl and notify customized listener.
- Create database modification event for database ddl
- Notify customized listener for the above events in CatalogManager
- Added CatalogManagerTest to check the listener is notified for database ddl
- The S3 file …
=> [FLINK-32406][table] Notify catalog modification listener for database ddl in CatalogManager

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecHashAggregate.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/processor/MultipleInputNodeCreationProcessor.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/CodeGenUtils.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/ProjectionCodeGenerator.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/agg/batch/AggCodeGenHelper.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/agg/batch/AggWithoutKeysCodeGenerator.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/agg/batch/HashAggCodeGenHelper.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/agg/batch/HashAggCodeGenerator.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/agg/batch/SortAggCodeGenerator.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/agg/batch/WindowCodeGenerator.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/fusion/FusionCodegenUtil.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/fusion/spec/HashAggFusionCodegenSpec.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/fusion/spec/HashJoinFusionCodegenSpec.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/codegen/agg/AggTestBase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/codegen/agg/batch/HashAggCodeGeneratorTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/OperatorFusionCodegenITCase.scala
*HashAgg support operator fusion code generator, include without key and with key case, also include one phase and two phase case. Please attention, we only support multiple input operator fusion codegen, so the hashagg must be fused with HashJoin operator.*
- *HashAgg support operator fusion codegen*
*(example:)*
- *Added related integration tests in OperatorFusionCodegenITCase* …
=> [FLINK-32280][table-runtime] HashAgg support operator fusion codegen

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/common/CommonPhysicalTableSourceScan.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestTimeTravelCatalog.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/batch/sql/TimeTravelTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/batch/sql/TimeTravelITCase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/utils/TimeTravelTestUtil.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/TimeTravelTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/DateTimeTestUtil.scala
The newly added `TestTimeTravelCatalog` didn't save the snapshot timestamp properly(which is used for testing the time travel feature). This is a bugfix pr and also add related plan tests.
save the snapshot timestamp in `TestTimeTravelCatalog`
newly added `TimeTravelTest`
=> [FLINK-32646][table-planner] Fix TestTimeTravelCatalog missing snapshot version properties and add version to source table's digest

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/util/HiveReflectionUtils.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParser.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/parse/HiveParserDDLSemanticAnalyzer.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/utils/HiveCatalogUtils.java, flink-connectors/flink-sql-connector-hive-3.1.3/pom.xml, flink-connectors/flink-sql-connector-hive-3.1.3/src/main/resources/META-INF/NOTICE, flink-end-to-end-tests/flink-end-to-end-tests-hive/src/test/java/org/apache/flink/tests/hive/HiveITCase.java, flink-table/flink-table-planner-loader/src/main/java/org/apache/flink/table/planner/loader/DelegatePlannerFactory.java, flink-table/flink-table-planner-loader/src/main/java/org/apache/flink/table/planner/loader/PlannerModule.java
…nner to use hive dialect
From 1.15, we have to swap table-planner and table-planner-loader to use Hive dialect which is not convenient for users. So this pr is to make it's possible to use  Hive dialect without doing such swapping.
The design is documented in https://docs.google.com/document/d/1VV88R1O1IN-zX3su6RCAgJPuZiymgh4xoL8OJrW-_00/edit
-  In `DelegatePlannerFactory`, if it's not default dialect, try to discover the class for the corresponding `ParserFactory`,  and get the jar url for the class.  Add the jar url to the classloader maintained in flink-table-planer-loader to enable the Hive dialect to use the class in flink-table-planner
-  Do some adjustment in Hive connector for HiveParser since its classloader has changed  and  we need to adjust some codes for calling methods of …
=> [FLINK-31575][hive] Avoid swapping table-planner-loader and table-planner to use hive dialect

flink-end-to-end-tests/test-scripts/common_kubernetes.sh, tools/ci/maven-utils.sh
Looking at the error message `error: Internal error occurred: error executing command in container: http: invalid Host header` pointed to several issues that indicated that the actual problem appears when building `cri-dockerd` with go-lang 1.20.6 (e.g. https://github.com/moby/moby/issues/45935 or https://github.com/kubernetes/minikube/issues/16909).
Instead of building `cri-dockerd` manually, we can rely on the binaries which are provided on github.
* `Run Kubernetes test` succeeds again.
* Verification that go 1.20.6 was installed in the CI machine …
=> [FLINK-32632][test] Fixes Minikube/cri-dockerd issue

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/fusion/spec/CalcFusionCodegenSpec.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/fusion/spec/HashJoinFusionCodegenSpec.scala, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/OperatorFusionCodegenTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/OperatorFusionCodegenTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/OperatorFusionCodegenITCase.scala, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/hashtable/LongHybridHashTable.java
*For shuffle hash join, we don't support spill to disk currently if operator fusion codegen, so this PR main purpose is to fix the problem.*
- *Shuffle hash join support spill to disk if operator fusion codegen enabled*
*(example:)*
- *Integration tests in OperatorFusionCodegenITCase can verify it* …
=> [FLINK-32279][table-runtime] Shuffle HashJoin support spill to disk when enable operator fusion codegen

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/listener/AlterTableEvent.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/listener/CatalogContext.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/listener/CreateTableEvent.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/listener/DropTableEvent.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/listener/TableModificationEvent.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogManagerTest.java
This PR aims to create event for table ddl and notify catalog modification listener in CatalogManager
- Create event for table and temporal table
- Notify listener in CatalogManager
- Added CatalogManagerTest to validate listener for table/view ddl
- The S3 file system connector: (yes / no / …
=> [FLINK-32407][table] Notify catalog modification listener for table ddl in CatalogManager

flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/types/ResourceBudgetManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotTableImpl.java
The logs currently don't contain any information about the used/free resource budget of a TM.
=> [FLINK-32167] Improved TM-side logging for fine-grained resource management

flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/TableSourceJsonPlanTest_jsonplan/testReuseSourceWithoutProjectionPushDown.out
The PR is aiming to fix  failing ci tests especially `TableSourceJsonPlanTest.testReuseSourceWithoutProjectionPushDown` which became broken after https://issues.apache.org/jira/browse/FLINK-32657
https://github.com/apache/flink/commit/6a3808213d334de614e162362d1583f3e5322358 
The change is change of tests …
=> [FLINK-32664][table] Fix TableSourceJsonPlanTest.testReuseSourceWithoutProjectionPushDown

flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/RecreateOnResetOperatorCoordinator.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/RecreateOnResetOperatorCoordinatorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/TestingOperatorCoordinator.java
… by RecreateOnResetOperatorCoordinator.
Fix checkpoint aborted message being swallowed by `RecreateOnResetOperatorCoordinator`
Let the `RecreateOnResetOperatorCoordinator` override `notifyCheckpointAborted` method and forward the checkpoint aborted message to the real `OperatorCoordinator` for processing. …
=> [FLINK-32655][runtime] Fix checkpoint aborted message being swallowed by RecreateOnResetOperatorCoordinator

flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/RecreateOnResetOperatorCoordinator.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/RecreateOnResetOperatorCoordinatorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/TestingOperatorCoordinator.java
Backporting #23059  to release-1.17
=> [FLINK-32655][runtime]  Fix checkpoint aborted message being swallowed by RecreateOnResetOperatorCoordinator.

docs/content.zh/docs/dev/table/sql/insert.md, docs/content/docs/dev/table/sql/insert.md
This is an addition to the documentation for the newly added interface in FLINK-31487. It may be beneficial for connector developers who want to avoid overwriting non-target columns with null values when processing partial column updates. 
Update the current sql doc dev/table/sql/insert.md
=> [FLINK-32674][doc] Add documentation for the new getTargetColumns in DynamicTableSink

flink-rpc/flink-rpc-akka/pom.xml, flink-rpc/flink-rpc-akka/src/main/resources/META-INF/NOTICE
This PR bumps Pekko from v1.0.0 to 1.0.1. The main and hence only significant change from Pekko 1.0.0 to Pekko 1.0.1 is https://github.com/apache/incubator-pekko/pull/492, see issue at https://github.com/apache/incubator-pekko/issues/491.
Just to provide some context, the core issue is that using `$` in any symbol name for user defined classes breaks the JVM spec (initially it was thought that it only broke the Scala spec but this was later clarified in https://github.com/lampepfl/dotty/issues/18234#issuecomment-1639861800 ).
While it is highly unlikely that using Pekko 1.0.0 will cause any problems, if there does happen to be an issue theoretically speaking it wouldn't be self contained to only Scala users. As such its recommend to update to Pekko 1.0.1 if its not a big deal to do so.
* …
=> [FLINK-32683][rpc] Update Pekko from 1.0.0 to 1.0.1

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/FunctionCatalog.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/catalog/UnknownCatalogTest.java
This commit addresses FLINK-32691 by having function lookup skip looking for functions in catalog / database specific locations when the catalog and/or database is unset.
- Added test cases to UnknownCatalogTest.java.
- Does this …
=> [FLINK-32691] SELECT fcn does not work with an unset catalog or database

flink-runtime/src/main/java/org/apache/flink/runtime/rest/RestClient.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/RestServerEndpoint.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/RestClientTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/RestExternalHandlersITCase.java
Fix the issue described in FLINK-32583 wherein a request made to a RestClient that has already been shutdown can deadlock due to the returned future never resolving.
- Add check if the Netty channel future has already failed after attempting to add a listener to it
- Added test for this behavior in RestClientTest, `testCloseClientBeforeRequest`
- This test calls `restClient.close()` and then attempts to make a request that would eventually fail with a connection timeout
- The test blocks on the future returned by the call with a timeout of 0 so it can test that the expected exception (and not TimeoutException) is thrown …
=> [FLINK-32583][rest] Fix deadlock in RestClient

flink-runtime/src/main/java/org/apache/flink/runtime/rest/RestClient.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/RestServerEndpoint.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/RestClientTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/RestExternalHandlersITCase.java
This is a backport of #22987 to 1.17.
=> [FLINK-32583][rest] Fix deadlock in RestClient (backport to 1.17)

flink-runtime/src/main/java/org/apache/flink/runtime/rest/RestClient.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/RestServerEndpoint.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/RestClientTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/RestExternalHandlersITCase.java
This is a backport of https://github.com/apache/flink/pull/22987 to 1.16.
=> [FLINK-32583][rest] Fix deadlock in RestClient (backport to 1.16)

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/common/TieredStorageIdMappingUtils.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/common/TieredStoragePartitionId.java, flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/NettyShuffleMaster.java
*Avoid creating tiered internal shuffle master before enabling the tiered storage.*
- *Avoid creating tiered internal shuffle master before enabling the tiered storage.*
=> [FLINK-32686][network] Avoid creating tiered internal shuffle master before enabling the tiered storage

docs/content.zh/docs/dev/table/catalogs.md, docs/content/docs/dev/table/catalogs.md
Add doc for catalog modification listener
- Add doc for catalog modification listener …
=> [FLINK-32676][doc] Add doc for catalog modification listener

flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/JobGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/tasks/CheckpointCoordinatorConfiguration.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StateWithExecutionGraph.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGenerator.java
Fix the bug that checkpoint should not be triggered after all tasks have received end-of-data when checkpoint is disabled.
- [FLINK-32663][checkpoint][refactor] Refactor the checkpoint interval value when checkpoint is disabled
- [FLINK-32663][checkpoint] Fix the bug that checkpoint should not be triggered after all tasks have received end-of-data when checkpoint is disabled …
=> [FLINK-32663][checkpoint] Fix the bug that checkpoint should not be triggered after all tasks have received end-of-data when checkpoint is disabled

flink-runtime/src/test/java/org/apache/flink/runtime/testutils/TestJvmProcess.java
`JobManagerHAProcessFailureRecoveryITCase` fails with JDK17 occassionally. This PR is about investigating and fixing the issue.
The issue was that the destruction of the process took occassionally longer (the `destroyForcibly` failed under JDK17 due to the restrictive module encapsulation). The JM process that was subject to destruction might have had the chance to finish the job because `TestJvmProcess.destroy` didn't block until the process was actually gone. The new JM process wouldn't have any job to recover as the consequence which caused the `FlinkJobNotFoundException`. 
* Replaced the `destroyForcibly` reflection logic that was introduced for JDK7 (which we don't support anymore) by the usual `destroy` call. `destroyForcibly` is also available through the `Process` interface. ~But …
=> [FLINK-31168] Fix JobManagerHAProcessFailureRecoveryITCase

flink-tests/src/test/java/org/apache/flink/test/recovery/ProcessFailureCancelingITCase.java
We introduced a Precondition checking whether the contenders deregistered themselves before closing the HA backend of the service. `ProcessFailureCancelingITCase` doesn't do that properly because it's not waiting for the `dispatcherResourceManagerComponent` application to stop. That might lead to test instabilities if stopping the application takes longer.
* Made the `stopApplication` call to block …
=> [FLINK-32715][test] Make test wait for application to stop before shutting down the other services

flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
*Do not touch the branch related to changelog writer if it is already available.*
- *Do not touch the branch related to changelog writer if it is already available.*
This change is already covered by existing tests*.
- The runtime per-record code paths (performance sensitive): per-buffer.
=> [FLINK-32685][streaming] Do not touch the branch related to changelog writer if it is already available.

.gitignore
This allows the checkout-specific customization of the Maven build (e.g. setting a different local repository).
* Added `.mvn/maven.config` to `.gitignore`
=> [FLINK-32734][build] Adds .mvn/maven.config to .gitignore

docs/content.zh/docs/dev/table/hive-compatibility/hive-dialect/insert.md, docs/content/docs/dev/table/hive-compatibility/hive-dialect/insert.md, flink-core/src/main/java/org/apache/flink/api/common/state/ListState.java, flink-python/pyflink/datastream/state.py, flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/testutils/HttpTestClient.java, flink-runtime/src/main/java/org/apache/flink/runtime/execution/Environment.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/TaskEventHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/iterative/task/IterationHeadTask.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/tasks/TaskOperatorEventGateway.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/internal/InternalListState.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/LocalInputChannelTest.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/snapshot/RocksDBFullSnapshotResources.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/source/ContinuousFileReaderOperator.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecLegacySink.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecSink.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecLegacySink.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecLegacySink.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecSink.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/batch/BatchPhysicalLegacySink.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/batch/BatchPhysicalSink.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalLegacySink.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalSink.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/RelShuttles.scala, flink-tests/src/test/java/org/apache/flink/test/checkpointing/ProcessingTimeWindowCheckpointingITCase.java
Just a fix of a surprisingly common typo in JavaDoc etc.
https://issues.apache.org/jira/browse/FLINK-30636
=> [FLINK-30636] [docs]: Typo fix; 'to to' -> 'to'

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/HiveCatalogLock.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/TableDescriptor.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/ManagedTableListener.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/Catalog.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogLock.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/RequireCatalogLock.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/ManagedTableFactory.java
This PR marks all `ManagedTable` related APIs as `@Deprecated`, according to [FLIP-346](https://cwiki.apache.org/confluence/display/FLINK/FLIP-346%3A+Deprecate+ManagedTable+related+APIs).
Mark all related methods/classes/interfaces as deprecated.
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (**yes** / no) Mark as deprecated
- The …
=> [FLINK-32656][table] Deprecate ManagedTable related APIs

docs/content.zh/docs/deployment/elastic_scaling.md, docs/content/docs/deployment/elastic_scaling.md
The cluster.declarative-resource-management.enabled was removed at [FLINK-21095](https://issues.apache.org/jira/browse/FLINK-21095)(https://github.com/apache/flink/pull/15838/files), so it doesn't work now.
However, the flink doc still have it.
[FLINK-32759][doc] Remove the `cluster.declarative-resource-management.enabled` in doc
=> [FLINK-32759][doc] Remove the `cluster.declarative-resource-management.enabled` in doc

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/file/SegmentPartitionFileWriter.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/remote/RemoteStorageScanner.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/remote/RemoteStorageScannerTest.java
*Fix the write logic in remote tier of hybrid shuffle.*
- *Fix the write logic in remote tier of hybrid shuffle.*
=> [FLINK-32708][network] Fix the write logic in remote tier of hybrid shuffle

flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/FileSystemTableFactory.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/TableConfig.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableConfigValidation.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/api/TableConfigTest.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/utils/TableConfigUtils.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/connector/file/table/FileSystemTableFactoryTest.java
This fixes the insufficient validation of ZoneId for setting local time zones.
- It ensures that no information is lost when converting between TimeZone and ZoneId
- Now time zones such as `UT-1` fail with an error.
- ZoneOffset is converted to GMT zone in order to avoid issues where the offset is lost when converting between TimeZone and ZoneId
- `TableConfigTest` …
=> [FLINK-32689] Improve validation of local time zone

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdDistribution.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/schema/IntermediateRelTable.scala, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/SubplanReuseTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/SubplanReuseTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdDistributionTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdHandlerTestBase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdRowCollationTest.scala
This PR is aims to fix cannot generate plan error when insert a sorted view into multi sinks. The  error is caused by the sort information in traitSet do not pass to `IntermediateRelTable` when block optimize.
So I override `getCollationList` method in `IntermediateRelTable` to get new traitSet include sort information.
- Override `getCollationList` method in `IntermediateRelTable` to get new traitSet include sort information.
- Adding UT test for this case.
- Adding ITCase for this case. …
=> [FLINK-25447][table-planner] Fix batch query cannot generate plan when a sorted view into multi sinks

docs/content.zh/docs/deployment/elastic_scaling.md, docs/content/docs/deployment/elastic_scaling.md
[FLINK-21450](https://issues.apache.org/jira/browse/FLINK-21450) has supported local recovery for adaptive scheduler, so this limitation can be removed.
[FLINK-32816][doc] Remove the local recovery limitation for adaptive scheduler
=> [FLINK-32816][doc] Remove the local recovery limitation for adaptive scheduler

docs/content.zh/docs/deployment/elastic_scaling.md, docs/content/docs/deployment/elastic_scaling.md
[FLINK-30846](https://issues.apache.org/jira/browse/FLINK-30846) [1] updated the fall back strategy from default Scheduler to AdaptiveBatch Scheduler when batch job enable `jobmanager.scheduler: adaptive`.
However, the doc[2] isn't updated.
[FLINK-32823][doc] Update the adaptive scheduler fall back strategy doc for batch jobs
[1] https://github.com/apache/flink/pull/21814/files
[2] https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/elastic_scaling/#limitations-1
=> [FLINK-32823][doc] Update the adaptive scheduler fall back strategy doc for batch jobs

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CompletedCheckpoint.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/OperatorState.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/UnknownInputChannel.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/StateObject.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/metadata/MetadataV3SerializerTest.java, flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java
As the title, fix some typo in java doc and comments.
=> [hotfix][javadocs] Fix some typo in java doc and comments

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/common/TieredStorageConfiguration.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/shuffle/TieredResultPartitionFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/SortBufferAccumulator.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/TieredStorageSortBuffer.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/disk/DiskIOScheduler.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/disk/DiskTierProducerAgent.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/memory/MemoryTierFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/memory/MemoryTierProducerAgent.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/memory/MemoryTierSubpartitionProducerAgent.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/TieredStorageSortBufferTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/memory/MemoryTierProducerAgentTest.java
*Currently, each subpartition in Disk/Remote has a segment size of 8M. When writing segments to the Disk tier with a parallelism of 1000, only shuffle data exceeding 1000 * 8M can be written to the Memory tier again. However, for most shuffles, the data volume size falls below this limit, significantly impacting Memory tier utilization.
For better performance, it is necessary to address this issue to improve the memory tier utilization.*
- *Modify segment size to improve memory utilization for Hybrid Shuffle*
This change is an internal option default value hotfix change without tests. …
=> [FLINK-32709][network] Fix the bug of low memory utilization for Hybrid Shuffle

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/FileCatalogStore.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/FileCatalogStoreFactory.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/FileCatalogStoreFactoryOptions.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/FileCatalogStoreFactoryTest.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/FileCatalogStoreTest.java
Introduces a file catalog store implementation that supports external file systems.
- Use `org.apache.flink.core.fs.Path` instead of standard Java local FS file utils.
- Use `FSDataOutputStream` and `FSDataInputStream` to read/write the catalog store file.
- Validate the given catalog store file exists in `FileCatalogStore#open()`, as automatic directory creation may fail on external file systems. (Permission problems or unsupported API)
This change is already covered by existing tests, such as:
- `FileCatalogStoreTest`
- `FileCatalogStoreFactoryTest`
Will add a test case with an external FS. …
=> [FLINK-32660][table] Introduce external FS compatible FileCatalogStore implementation

docs/content.zh/docs/dev/table/sqlClient.md, docs/content/docs/dev/table/sqlClient.md
Add missing style options for `sql-client.display.color-schema` in docs
Add missing style options for `sql-client.display.color-schema` in docs
This change is a docs change without any test coverage.
=> [hotfix][docs] Add missing style options for `sql-client.display.color-schema` in docs

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/reuse/ReplaceScanWithCalcShuttle.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/reuse/ReusableScanVisitor.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/reuse/ScanReuserUtils.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/optimize/program/DynamicPartitionPruningProgramTest.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/DynamicFilteringTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/optimize/program/DynamicPartitionPruningProgramTest.xml
*Fix the bug of Scan reuse after projection pushdown without considering the dpp pattern, this will cause the fact side of dpp to reuse with non-dpp scan which has the same table, the plan and result is wrong, so we need to fix it.*
- *Fix the bug of Scan reuse after projection pushdown without considering the dpp pattern*
- *Added plan tests in DynamicPartitionPruningProgramTest* …
=> [FLINK-32730][table-planner] Fix the bug of Scan reuse after projection pushdown without considering the dpp pattern

flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/PendingTaskManager.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/FineGrainedSlotManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/FineGrainedSlotManagerTestBase.java
Fix NPE when PendingTaskmanager clear pending allocations twice.
- check whether pending allocations already clear when PendingTaskManager#clearPendingAllocationsOfJob triggered
- Added test that validates that PendingTaskManager#clearPendingAllocationsOfJob triggered twice
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper:(no)
=> [FLINK-32882][SlotManager] Fix NPE when PendingTaskmanager clear pending allocations twice.

flink-runtime/src/main/java/org/apache/flink/runtime/blob/FileSystemBlobStore.java
[hotfix][runtime] Remove the repeated createBasePathIfNeeded in the FileSystemBlobStore
The `private boolean put(File fromFile, String toBlobPath)` has called `createBasePathIfNeeded`, so the `public boolean put(File localFile, JobID jobId, BlobKey blobKey)` doesn't need to call `createBasePathIfNeeded`.
=> [hotfix][runtime] Remove the repeated createBasePathIfNeeded in the FileSystemBlobStore

tools/azure-pipelines/e2e-template.yml, tools/azure-pipelines/jobs-template.yml, tools/ci/compile.sh, tools/ci/compile_ci.sh, tools/ci/license_check.sh, tools/ci/maven-utils.sh, tools/ci/shade.sh, tools/ci/verify_bundled_optional.sh, tools/ci/verify_scala_suffixes.sh
This PR allows devs to run this script locally, just like that. Lower-level scripts are also easier to use.
The commits are quite granular and all have a commit message explaining the change.
=> [FLINK-32834] Ease local use of tools/ci/compile.sh

flink-core/src/main/java/org/apache/flink/api/connector/source/lib/util/IteratorSourceEnumerator.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraphBuilder.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionJobVertex.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/SpeculativeExecutionJobVertex.java, flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinatorHolder.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultExecutionGraphFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultOperatorCoordinatorHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/OperatorCoordinatorHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/CreatingExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveBatchScheduler.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraphConstructionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/EdgeManagerBuildUtilTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ExecutionJobVertexTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/PointwisePatternTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/TestingDefaultExecutionGraphBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/VertexSlotSharingTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/OperatorCoordinatorHolderTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/DefaultOperatorCoordinatorHandlerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/SchedulerTestingUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/SsgNetworkMemoryCalculationUtilsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adapter/DefaultExecutionTopologyTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/ExecutingTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StateTrackingMockExecutionGraph.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/TestingOperatorCoordinatorHandler.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/benchmark/topology/BuildExecutionGraphBenchmark.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/partitioner/RescalePartitionerTest.java
This pull request makes operator coordinator metric group not to be initialized lazily.
- Pass the JobManagerJobMetricGroup when create execution graph
- Set metric group immediately when creating the operator coordinator context instead of lazy initialize
-  …
=> [FLINK-31268][metrics] Change not to initialize operator coordinator metric group lazily

flink-runtime/src/main/java/org/apache/flink/runtime/rest/FileUploadHandler.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/FileUploadHandlerITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/MultipartUploadExtension.java
HttpPostRequestDecoder#hasNext() throws an `EndOfDataDecoderException` when called if all attributes were already read. There is apparently an edge-case where the a non empty HttpContent is received, but we already retrieved all attributes (so I guess it's just multipart metadata).
We now assume that this isn't a problem; if it is the application layer should notice it (e.g., if a file/attribute is missing).
=> [FLINK-32888] Handle hasNext() throwing EndOfDataDecoderException 

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/ResultSubpartitionView.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/HsDataView.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/HsSubpartitionConsumerMemoryDataManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/HsSubpartitionFileReaderImpl.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/NettyConnectionWriterImpl.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/NettyPayloadManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TieredStorageNettyServiceImpl.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TieredStorageResultSubpartitionView.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/disk/DiskIOScheduler.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/file/DiskIOSchedulerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/NettyConnectionWriterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TieredStorageResultSubpartitionViewTest.java
*Fix the inaccurate backlog number of Hybrid Shuffle.*
- *Fix the inaccurate backlog number of Hybrid Shuffle.*
=> [FLINK-32770][network] Fix the inaccurate backlog number of Hybrid Shuffle

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectSinkOperatorCoordinator.java
1.16 backport PR of parent PR https://github.com/apache/flink/pull/23180. No conflicts encountered while backporting.
=> [BP-1.16][FLINK-32751][runtime] Refactors close handling to CollectSinkOperatorCoordinator

flink-runtime/src/test/java/org/apache/flink/runtime/rest/RestClientTest.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectSinkOperatorCoordinator.java
Making the close procedure of `CollectSinkOperatorCoordinator` more explicit and added log messages.
* Refactored the concurrent processing of requests to allow cancelling the case-specific logging
* Use `shutdownNow` instead of `shutdown` to trigger the cancellation of any on-goring tasks
I migrated `RestClientTest` as well because a first iteration of this PR required me to touch that test. I thought that it's still worth it to keep the migration commit.
* Existing tests should still succeed …
=> [FLINK-32751][runtime] Refactors close handling to CollectSinkOperatorCoordinator

flink-end-to-end-tests/test-scripts/common.sh
As showed in [FLINK-32668](https://issues.apache.org/jira/browse/FLINK-32668), an error occurs when watch dog thread exits before killed.
Check if watch dog thread exists before kill it
* Dependencies (does it add or upgrade a dependency): (no)
* The public API, i.e., is any changed class annotated with @Public(Evolving): (no)
* The serializers: (no)
* The runtime per-record code paths (performance sensitive): (no)
* Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, * ZooKeeper: (no)
* The S3 file system connector: (no)
* Does this pull request introduce a new feature? (no)
=> [FLINK-32668][e2e] fix up watchdog timeout error msg in common.sh

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/fusion/spec/CalcFusionCodegenSpec.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/fusion/spec/HashJoinFusionCodegenSpec.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/OperatorFusionCodegenITCase.scala, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/hashtable/BaseHybridHashTable.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/hashtable/BinaryHashTable.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/hashtable/LongHybridHashTable.java
In the predecessor PR, for the purpose of lazy computation, for Broadcast HashJoin, we strongly assume that the build side won' spill to disk because it less than 10MB. However, during the testing of TPC-DS, part of the query, due to the problem of the inaccurate derivation of statistics by the optimizer, although the optimizer chose Broadcast HashJoin, the spill behavior happened during actual runtime pahse, so we need to remove this assumption and make it support spill as well. For this fix, the gains obtained through TPC-DS are basically the same as expected
- *Fix the bug of broadcast hash join doesn't support spill to disk when enabling operator fusion codegen*
This change is already covered by existing tests in OperatorFusionCodegenITCase. …
=> [FLINK-32905][table-runtime] Fix the bug of broadcast hash join doesn't support spill to disk when enabling operator fusion codegen

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Created.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/CreatingExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StateWithoutExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/WaitingForResources.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/CreatedTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/CreatingExecutionGraphTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/MockStateWithoutExecutionGraphContext.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StateTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StateWithoutExecutionGraphTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/WaitingForResourcesTest.java
Currently, most of states of adaptive scheduler extends StateWithExecutionGraph, and it can reduce a lots of repeated code.
We can define the StateWithoutExecutionGraph and the corresponding Context as well, then the rest of states can extend the StateWithoutExecutionGraph, such as: Created, WaitingForResources, CreatingExecutionGraph.
This improvement can reduce a lot of code for these states, such as: cancel(), suspend(), getJob(), handleGlobalFailure() and getLogger().
These methods of Created, WaitingForResources and CreatingExecutionGraph are same.
[FLINK-32859][scheduler] Introduce the StateWithoutExecutionGraph.
Add the test later.
- The …
=> [FLINK-32859][scheduler] Introduce the StateWithoutExecutionGraph

flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/threadinfo/VertexFlameGraphFactory.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/ThreadInfoSampleServiceTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/threadinfo/VertexFlameGraphFactoryTest.java
Because lambda "class names" can be different across different JVMs, the flame graph in Flink UI is often unreadable, especially with high parallelism with large number of task managers (there are 5 task managers here and therefore 5 "columns", but if the application has 50+ task managers, this becomes completely unreadable):
This can happen in both Flink's internal logic which uses lambdas:
and in user code:
The subtask view does help partially, but it is bad for understanding of the big picture, when you want to check what happens within the task as a whole.
This PR adds filtering logic to the code which collects stack traces which are subsequently used to build flame graphs. This logic modifies the stack trace elements which correspond to lambda invocations by replacing unique parts …
=> [FLINK-32137] Added filtering of lambdas when building the flame graph

flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/extensions/parameterized/ParameterizedTestExtension.java, flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/ParameterizedTestExtensionTest.java
ParameterizedTestExtension's parameter provider can be private
ParameterizedTestExtension's parameter provider can be private to make test cases have better isolation.
ParameterizedTestExtension's parameter provider can be private.
Old
```java
@ExtendWith(ParameterizedTestExtension.class)
public class ParameterizedTestExtensionTest {
private static final List<Integer> PARAMETERS = Arrays.asList(1, 2);
@Parameters
public static List<Integer> parameters() {
return PARAMETERS;
}
@TestTemplate
void testWithParameters(int parameter) {
assertThat(parameter).isIn(PARAMETERS);
}
}
```
After change
```java
@ExtendWith(ParameterizedTestExtension.class)
class ParameterizedTestExtensionTest {
private static final List<Integer> PARAMETERS = Arrays.asList(1, 2);
@Parameters
private static List<Integer> …
```
=> [FLINK-32942][test-utils] ParameterizedTestExtension's parameter provider can be private

flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionHaServices.java, flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/zookeeper/ZooKeeperLeaderElectionHaServices.java
Only prefixed the component name of LeaderElection with `job-`, as the ticket described.
- EmbeddedHaServicesTest
- StandaloneHaServicesTest
- ZooKeeperLeaderRetrievalTest
- TestingHighAvailabilityServices …
=> [FLINK-32710][runtime/coordination]prefixed the component name of LeaderElection with `job-`

flink-runtime/src/test/java/org/apache/flink/runtime/client/ClientUtilsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/client/SerializedJobExecutionResultTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/clusterframework/ApplicationStatusTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/clusterframework/BootstrapToolsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/clusterframework/TaskExecutorProcessUtilsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/clusterframework/types/ResourceBudgetManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/clusterframework/types/ResourceProfileTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmanager/JobManagerProcessUtilsTest.java
[FLINK-32837][JUnit5 Migration] Migrate the client and clusterframework packages of flink-runtime module to junit5
=> [FLINK-32837][JUnit5 Migration] Migrate the client and clusterframework packages of flink-runtime module to junit5

flink-clients/src/test/java/org/apache/flink/client/deployment/application/ApplicationDispatcherBootstrapITCase.java, flink-core/src/main/java/org/apache/flink/util/concurrent/FutureUtils.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionHaServices.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java, flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/AbstractThreadsafeJobResultStore.java, flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/FileSystemJobResultStore.java, flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/JobResultStore.java, flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedJobResultStore.java, flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/zookeeper/ZooKeeperLeaderElectionHaServices.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMasterServiceLeadershipRunner.java, flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/LeadershipLostException.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherCleanupITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/FileSystemJobResultStoreFileOperationsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/JobResultStoreContractTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterServiceLeadershipRunnerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/testutils/TestingJobResultStore.java
*At present, FileSystemJobResultStore executes I/O operations through FileSystem directly. We should refract the interface of JobResultStore to make I/O operations be executed asynchronously. This would move the responsibility of I/O operation from the Dispatcher into the JobResultStore.*
- *Refract the JobResultStore interface.*
- *Refract all codes that calls JobResultStore.* …
=> [FLINK-27204][flink-runtime] Refract FileSystemJobResultStore to execute I/O operations on the ioExecutor

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/casting/RowToRowCastRule.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CastFunctionITCase.java
The PR addresses allows casting in correct way collections like `ARRAY` and `MAP` with `ROW` element types
e.g.
```sql
SELECT cast(array[row(1, 'one'), row(2, 'two')] as array<row<`f0` int, `f1` string>>);
SELECT cast(map[row(1), 'one', row(2), 'two'] as map<row<`f0` int>, string>);
```
add `copy` method usage to fix overriding of collection's values
Tests are added to `org.apache.flink.table.planner.functions.CastFunctionITCase`
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: ( …
=> [FLINK-32296][table] Support cast of collections with row element types

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/casting/RowToRowCastRule.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CastFunctionITCase.java
This is a cherry-pick backport of https://github.com/apache/flink/pull/22923
=> [BP-1.16][FLINK-32296][table] Support cast of collections with row element types

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/casting/RowToRowCastRule.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CastFunctionITCase.java
This is a cherry-pick of https://github.com/apache/flink/pull/22923 backport to 1.17
=> [BP-1.17][FLINK-32296][table] Support cast of collections with row element types

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/fusion/spec/CalcFusionCodegenSpec.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/fusion/spec/HashJoinFusionCodegenSpec.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/OperatorFusionCodegenITCase.scala, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/hashtable/BaseHybridHashTable.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/hashtable/BinaryHashTable.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/hashtable/LongHybridHashTable.java
This closes #23251
cherry picked from commit 2cf32e82773254b79af4dad7ee317db4878d6f8a
=> [BP-1.18][FLINK-32905][table-runtime] Fix the bug of broadcast hash join doesn't support spill to disk when enable operator fusion codegn

flink-connectors/flink-sql-connector-hive-2.3.9/pom.xml, flink-connectors/flink-sql-connector-hive-3.1.3/pom.xml
To fix thrift dependency conflict when ```flink-sql-connector-hive``` and ```flink-parquet``` both exist in the path.
Reshade dependencies that are already shaded in parquet. For naming I referred to [this](https://github.com/apache/flink/blob/fa61dd439ece9e2b9ef710ce2f7eed54c4d4403a/flink-connectors/flink-connector-hive/pom.xml#L1270C10-L1270C10)
This change is about dependency without code change, so I believe it should be covered by existing tests
- Dependencies (does it add or upgrade a dependency): yes, shade dependency …
=> [FLINK-32760][Connectors/Hive] Reshade parquet in flink-sql-connector-hive

flink-runtime/src/test/java/org/apache/flink/runtime/util/AddressResolutionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/BlockingShutdownTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/BoundedFIFOQueueTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/DualKeyLinkedMapTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/EnvironmentInformationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/FlinkSecurityManagerITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/HardwareTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/JvmExitOnFatalErrorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/NonReusingKeyGroupedIteratorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/ResourceCounterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/ResourceManagerUtilsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/ReusingKeyGroupedIteratorTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/RunnablesTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/SerializedThrowableTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/SlotSelectionStrategyUtilsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/StateHandleStoreUtilsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/ZooKeeperUtilsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/ZooKeeperUtilsTreeCacheTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/ZooKeeperUtilsWriteLeaderInformationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/bash/BashJavaUtilsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/bash/FlinkConfigLoaderTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/config/memory/JobManagerProcessSpecTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/config/memory/ManagedMemoryUtilsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/config/memory/ProcessMemoryUtilsTestBase.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/config/memory/TaskExecutorProcessSpecTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/event/TaskEventHandlerTest.java
Migrate flink-runtime/utils tests to JUnit5.
=> [FLINK-32858][tests][JUnit5 migration] Migrate flink-runtime/utils tests to JUnit5

flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/threadinfo/VertexFlameGraphFactoryTest.java
The problem of `VertexFlameGraphFactoryTest#testLambdaClassNamesCleanUp` is that it assumes that lambda's classnames end with `$Lambda$0` while in fact for jdk 11 and jdk 17 it ends with `$Lambda$0x0`.
That is the reason of build failure during nightly tests
The PR is aiming to fix that
-*org.apache.flink.runtime.webmonitor.threadinfo.VertexFlameGraphFactoryTest*
The change is a test itself
- The S3 file system connector: ( …
=> [FLINK-32951][tests] Make VertexFlameGraphFactoryTest#testLambdaClassNamesCleanUp working with jdk 11+

docs/content.zh/docs/dev/datastream/fault-tolerance/state.md, docs/content/docs/dev/datastream/fault-tolerance/state.md, flink-core/src/main/java/org/apache/flink/api/common/state/StateTtlConfig.java, flink-core/src/main/java/org/apache/flink/api/common/time/Time.java, flink-core/src/test/java/org/apache/flink/api/common/state/StateTtlConfigTest.java, flink-python/pyflink/datastream/state.py, flink-python/pyflink/fn_execution/embedded/java_utils.py, flink-python/src/test/java/org/apache/flink/streaming/api/utils/ProtoUtilsTest.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/ttl/RocksDbTtlCompactFiltersManager.java
In 6.20.3-ververica-2.0 rocksdb version flink uses from 1.17[1], we introduce periodic compaction option[2].
it deserves to expose this into RocksdbCompactFilterCleanupStrategy or some confs to make users use it conveniently.
[1] https://github.com/apache/flink/pull/21747
[2] https://github.com/ververica/frocksdb/pull/57
- *RocksdbCompactFilterCleanupStrategy supports to define periodicCompactionSeconds*
This change added a simple verify in test "StateTtlConfigTest". …
=> [FLINK-30854][state] Support periodic compaction for RocksdbCompactFilterCleanupStrategy

flink-end-to-end-tests/flink-end-to-end-tests-hive/src/test/java/org/apache/flink/tests/hive/containers/HiveContainer.java, flink-end-to-end-tests/flink-sql-gateway-test/src/test/java/org/apache/flink/table/gateway/containers/HiveContainer.java
Currently the SqlGatewayE2ECase uses Hive container to test the sql gateway behaviour. However, the container may fail to start the name node. It is caused by the docker will start the name node and then restart it. We can observe the following content in the log.
```
2018-09-24 19:35:28,571 ERROR [SIGTERM handler] namenode.NameNode (LogAdapter.java:error(71)) - RECEIVED SIGNAL 15: SIGTERM
2018-09-24 19:35:28,576 INFO  [pool-1-thread-1] namenode.NameNode (LogAdapter.java:info(47)) - SHUTDOWN_MSG: 
2023-08-11 17:53:43,364 INFO  [main] http.HttpServer2 (HttpServer2.java:start(937)) - HttpServer.start() threw a non Bind IOException
java.net.BindException: Port in use: 0.0.0.0:50070
at org.apache.hadoop.http.HttpServer2.constructBindException(HttpServer2.java:998)
at …
```
=> [FLINK-32731][e2e] Add retry mechanism when fails to start the namenode

.gitignore, flink-python/apache-flink-libraries/setup.py, flink-python/setup.py
The following doc describes the python version specification: https://peps.python.org/pep-0440/#developmental-releases
Extract:
```
Developmental releases are also permitted for pre-releases and post-releases:
X.YaN.devM       # Developmental release of an alpha release
X.YbN.devM       # Developmental release of a beta release
X.YrcN.devM      # Developmental release of a release candidate
X.Y.postN.devM   # Developmental release of a post-release
```
At the moment pyflink supports only `.dev0` development version. In this PR I've added `.devM` support.
Added `.devM` support.
Manually:
```
cd flink
conda env remove -n venv
conda create -y -n venv python=3.10
conda activate venv
pip3 install -r flink-python/dev/dev-requirements.txt
cd flink-python
python3 setup.py sdist bdist_wheel
cd …
```
=> [FLINK-32971][PYTHON] Add pyflink proper development version support

flink-python/apache-flink-libraries/setup.py, flink-python/setup.py
During `pyflink` library compilation Flink home is calculated from the provided `pyflink` version which is normally something like: `1.19.dev0`.  Such case `.dev0` is replaced to `-SNAPSHOT` which ends-up in hardcoded home directory: `../../flink-dist/target/flink-1.19-SNAPSHOT-bin/flink-1.19-SNAPSHOT`. This is fine as long as one uses the basic version types described [here](https://peps.python.org/pep-0440/#developmental-releases). In order to support any kind of `pyflink` version one can dynamically find out the Flink home directory through globbing. In this PR I've added this dynamic Flink home detection.
Dynamic Flink home detection through globbing.
Manually:
```
cd flink
mvn clean install -DskipTests
conda env remove -n venv
conda create -y -n venv python=3.10
conda activate venv …
```
=> [FLINK-32981][PYTHON] Add python dynamic Flink home detection

flink-runtime/src/main/java/org/apache/flink/runtime/operators/util/TaskConfig.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/drivers/GroupReduceDriverTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/drivers/TestTaskContext.java
[FLINK-1285](https://issues.apache.org/jira/browse/FLINK-1285) updated the MutableObjectMode to ObjectReuse. The TaskConfig#getMutableObjectMode() is not used for a long long time, and it's internal class, so it can be removed directly.
Also, we should update the GroupReduceDriverTest:
- Updating the testAllReduceDriverAccumulatingImmutable() from `context.setMutableObjectMode(false);` to `context.getExecutionConfig().disableObjectReuse();`.
- Updating the testAllReduceDriverIncorrectlyAccumulatingMutable() to `context.getExecutionConfig().disableObjectReuse();`, and fix the assert.
More details can be get from https://github.com/apache/flink/pull/23233#discussion_r1304595960
- [FLINK-32965][flink-runtime] Removing the deprecated MutableObjectMode and restore related tests
- …
=> [FLINK-32965][flink-runtime] Removing the deprecated MutableObjectMode and restore related tests

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/functions/SqlLikeUtils.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/calcite/FlinkSqlLikeUtilsTest.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/TableEnvironmentTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CalcITCase.scala
This pull request aims to port Calcite's fix for the sql like operator and relates to FLINK-32824.
Modified the JAVA_REGEX_SPECIALS in SqlLikeUtils class.
- *testSqlLike in ParserImplTest for validatation.*
- *testShowColumnsWithLike in TableEnvironmentTest in table layer for validation.* …
=> [FLINK-32824] Port Calcite's fix for the sql like operator.

flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/DuplicatingStateChangeFsUploader.java, flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogStorage.java, flink-dstl/flink-dstl-dfs/src/main/java/org/apache/flink/changelog/fs/FsStateChangelogWriter.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/ChangelogStorageMetricsTest.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/DiscardRecordableStateChangeUploader.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/FsStateChangelogWriterSqnTest.java, flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/FsStateChangelogWriterTest.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/LocalChangelogRegistry.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/LocalChangelogRegistryImpl.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/StateChangelogWriter.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/changelog/inmemory/InMemoryStateChangelogWriter.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/TestLocalRecoveryConfig.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/changelog/LocalChangelogRegistryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/changelog/inmemory/StateChangelogStorageTest.java, flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java, flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogTruncateHelper.java, flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/StateChangeLoggerTestBase.java
If TM is materialized before receiving confirm(), the previously uploaded queue in `FsStateChangelogWriter` will be cleared, so the local files of the completed checkpoint will not be registered again, while the JM owned files are registered before confirm(), and do not depend on the uploaded queue, so the local files are deleted, and the DFS files are still there. 
This PR makes the local recovery files registered before confirm() to avoid this problem. 
- Replace registering local files in confirm() with  registering local files in buildSnapshotResult().
This change is already covered by …
=> [FLINK-30863][state] Register local recovery files of changelog before notifyCheckpointComplete()

docs/layouts/shortcodes/generated/all_taskmanager_section.html, docs/layouts/shortcodes/generated/common_host_port_section.html, docs/layouts/shortcodes/generated/netty_shuffle_environment_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/NettyShuffleEnvironmentOptions.java, flink-core/src/main/java/org/apache/flink/util/NetUtils.java, flink-core/src/test/java/org/apache/flink/util/NetUtilsTest.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/NettyClient.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/NettyConfig.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/NettyServer.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerServices.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/NettyShuffleEnvironmentConfiguration.java, flink-runtime/src/main/java/org/apache/flink/runtime/util/PortRange.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyClientServerSslTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyServerFromPortRangeTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyTestUtil.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/PortRangeTest.java
Adds port range support for `taskmanager.data.bind-port`, which can be helpful in a restrictive network setup.
- Changed `taskmanager.data.bind-port` opion type from `Integer` to `String`.
- Introduced `PortRange` utility to be able to carry the port range string and its generated iterator together.
- Updated `NettyConfig` to handle a `PortRange` instead of a `port` as the port of the server.
- Updated `NettyServer` to be able to initialize itself from a `PortRange`.
- Adapted relevant code pieces and documentation.
- Added `NettyServerFromPortRangeTest` to test Netty server init from a port range.
- Manually verified by setting `taskmanager.data.bind-port` to a port range (e.g. 55000-55100) while `taskmanager.data.port` is set to …
=> [FLINK-32811][runtime] Add port range support for "taskmanager.data.bind-port"

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/VertexEndOfDataListener.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/DefaultSchedulerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/SchedulerTestingUtils.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/CheckpointAfterAllTasksFinishedITCase.java
Fix NullPointerException when executing TopSpeedWindowing example with checkpointing enabled. 
The bug happens when some vertices have reached the end of data but do not transform to FINISHED because their final checkpoint fails and causes a failover. The `VertexEndOfDataListener` would remove the end-of-data vertices from its state, however, in such case these vertices would be restarted and try to access the `VertexEndOfDataListener` again, which causes the NPE.
- Restore the state of VertexEndOfDataListener when some tasks are going to be restarted.
- Added test that validates that the state of VertexEndOfDataListener would be restored when failover happens.
- The public …
=> [FLINK-32945][runtime] Fix NPE when task reached end-of-data but checkpoint failed

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectSinkOperatorCoordinator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/SocketConnection.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/collect/CollectSinkOperatorCoordinatorTest.java
1.17 backport for parent PR https://github.com/apache/flink/pull/23296
=> [BP-1.17][FLINK-32751][collect] Fixes race condition between close and request handling processes in CollectSinkOperatorCoordinator

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectSinkOperatorCoordinator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/SocketConnection.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/collect/CollectSinkOperatorCoordinatorTest.java
1.16 backport for parent PR https://github.com/apache/flink/pull/23296
=> [BP-1.16][FLINK-32751][collect] Fixes race condition between close and request handling processes in CollectSinkOperatorCoordinator

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectSinkOperatorCoordinator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/SocketConnection.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/collect/CollectSinkOperatorCoordinatorTest.java
:warning: I sliced the PR into reasonable commits. It might make sense to review the commits individually rather than the entire PR at once.
The changes in https://github.com/apache/flink/pull/23180 caused more instabilities. Another investigation round revealed that we have, indeed, a race condition between the `CollectSinkOperatorCoordinator`'s close operation and the request handling. It can be that the `close()` call closes the socket while a request is handled. The request handler will only check whether a socket is null and reopen it if it's the case (see [CollectSinkOperatorCoordinator.java:160](https://github.com/apache/flink/blob/master/flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectSinkOperatorCoordinator.java#L160)).
This PR also …
=> [FLINK-32751][collect] Fixes race condition between close and request handling processes in CollectSinkOperatorCoordinator

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/NettyConnectionWriter.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/NettyConnectionWriterImpl.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TieredStorageResultSubpartitionView.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/disk/DiskIOScheduler.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/memory/MemoryTierSubpartitionProducerAgent.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/NettyConnectionWriterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TestingNettyConnectionWriter.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/memory/MemoryTierProducerAgentTest.java
*Fix the notification of inaccurate data availability in Hybrid Shuffle.*
- *Fix the notification of inaccurate data availability in Hybrid Shuffle.*
=> [hotfix][network] Fix the notification of inaccurate data availability in Hybrid Shuffle

docs/layouts/shortcodes/generated/yarn_config_configuration.html, flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNFileReplicationITCase.java, flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnConfigurationITCase.java, flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnTestBase.java, flink-yarn/src/main/java/org/apache/flink/yarn/Utils.java, flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java, flink-yarn/src/main/java/org/apache/flink/yarn/configuration/YarnConfigOptions.java, flink-yarn/src/test/java/org/apache/flink/yarn/FlinkYarnSessionCliTest.java, flink-yarn/src/test/java/org/apache/flink/yarn/YarnClusterDescriptorTest.java
*This pull request support specifying the HDFS path when ship archives or files.*
- *Support specifying the hdfs path when ship archives or files*
- *Added test that add HDFS file by parameter `yarn.ship-files`*
- *Added test that add HDFS archive file by parameter `yarn.ship-archives`* …
=> [FLINK-20681][yarn] Support specifying the hdfs path when ship archives or files

flink-tests/src/test/java/org/apache/flink/test/checkpointing/NotifyCheckpointAbortedITCase.java
This pr wants to fix assert error for NotifyCheckpointAbortedITCase#testNotifyCheckpointAborted
: All operators haven't snapshotState together strictly for marked decline checkpoint id in the teste case (This could be reproduced by adding Thread.sleep after first verifyAllOperatorsNotifyAborted() )
I think we could just make them snapshotState together strictly which I think the ITCase should guarantee.
- Guarantee all operators triggering marked decline checkpoint id together
This change just fix the error ITCase. …
=> [FLINK-32523][test] Guarantee all operators triggering decline checkpoint together for NotifyCheckpointAbortedITCase#testNotifyCheckpointAborted

flink-python/apache-flink-libraries/setup.py, flink-python/setup.py
https://github.com/apache/flink/pull/23306 introduced a blocker issue because the underneath directories to detect Flink home are not always exist. In this PR I've added better way to find out Flink version and home. Namely the version comes from the root `pom.xml` file which is an existing pattern in the code base.
The version comes from the root `pom.xml` file which is an existing pattern in the code base.
Manually.
Test to cover the original feature:
```
cd flink
mvn clean install -DskipTests
conda env remove -n venv
conda create -y -n venv python=3.10
conda activate venv
pip3 install -r flink-python/dev/dev-requirements.txt
cd flink-python
python3 setup.py sdist bdist_wheel
cd apache-flink-libraries
python3 setup.py sdist
```
Test which covers the broken feature:
```
cd …
```
=> [FLINK-32989][python] Fix version parsing issue

flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionDriver.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionDriverTest.java, flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionDriver.java, flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/ZooKeeperLeaderElectionDriverTest.java
FLINK-26522 replaced `LeaderElectionDriver` by `MultipleComponentLeaderElectionDriver`. The legacy classes had a proper (human-readable) `toString` implementation. The `MultipleComponentLeaderElectionDriver` didn't have that which is causing odd log messages. This PR brings the human-readable `toString` implementations back.
* Adds `toString` implementation to `KubernetesLeaderElectionDriver` and `ZooKeeperLeaderElectionDriver`
* Adds tests for the `toString` implementations …
=> [FLINK-32994][runtime] Adds human-readable toString implementations to the LeaderElectionDriver classes

flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/context/SessionContext.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/context/SessionContextTest.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogStoreHolder.java
This PR aims to support default catalog which is loaded by catalog store in sql-gateway
- Get default catalog from catalog store if it exists in sql-gateway
- If there's no default catalog in catalog store, create default memory catalog for sql-gateway
- Added SessionContextTest.testCreateDefaultCatalogFromStore for default catalog loaded by catalog store …
=> [FLINK-32749][gateway] Support config default catalog for catalog store in gateway

flink-dist/src/main/flink-bin/bin/jobmanager.sh
Pass arguments to the script jobmanager.sh dynamically failed due to reference a wrong variable name as mentioned in FLINK-32909.
change the wrong uppercase variable name ${ARGS[@]} to correct name: ${args[@]} at line 54 in the jobmanager.sh script.
This change is already covered by existing tests, such as org.apache.flink.dist.BashJavaUtilsITCase#testGetJmResourceParamsWithDynamicProperties.
- …
=> [FLINK-32909] [dist] fix the bug of Pass arguments to jobmanager.sh failed

flink-dist/src/main/flink-bin/bin/jobmanager.sh
See #23271 . This is a backport for 1.18.
=> [BP-1.18][FLINK-32909][dist]fix the bug of Pass arguments to jobmanager.sh failed

flink-dist/src/main/flink-bin/bin/jobmanager.sh
See #23271 . This is a backport for 1.17.
=> [BP-1.17][FLINK-32909][dist]fix the bug of Pass arguments to jobmanager.sh failed

flink-dist/src/main/flink-bin/bin/jobmanager.sh
See #23271 . This is a backport for 1.16
=> [BP-1.16][FLINK-32909][dist]fix the bug of Pass arguments to jobmanager.sh failed

flink-yarn/src/main/java/org/apache/flink/yarn/YarnApplicationFileUploader.java, flink-yarn/src/test/java/org/apache/flink/yarn/YarnApplicationFileUploaderTest.java
Hadoop versions starting from 3.3.2 have reworked copying local files to remote using S3AFileSystem. Now it requires the passed local Hadoop Path to have a `scheme` specified.
YarnApplicationFileUploader will append `file://` scheme for local path if none specified
I manually tested on a local single-node Hadoop 3.3.4 cluster with `fs.defaultFS` pointing to a local Minio S3 server. Creating a Flink YARN session failed before the fix, but worked after.
Also added new unit test in `YarnApplicationFileUploaderTest`.
- The runtime per-record code paths (performance sensitive): (yes / no …
=> [FLINK-30812][yarn] Fix uploading local files when using YARN with S3

docs/content.zh/docs/dev/table/olap_quickstart.md, docs/content.zh/docs/dev/table/overview.md, docs/content/docs/dev/table/olap_quickstart.md, docs/content/docs/dev/table/overview.md
Add quick-start docs for Flink OLAP
- added olap_quickstart.md in docs
- Anything that affects deployment or recovery: no
=> [FLINK-32755][docs] Add doc for OLAP quickstart

flink-filesystems/flink-s3-fs-base/src/main/java/org/apache/flink/fs/s3/common/writer/S3RecoverableFsDataOutputStream.java, flink-filesystems/flink-s3-fs-base/src/test/java/org/apache/flink/fs/s3/common/writer/S3RecoverableFsDataOutputStreamTest.java
CSVBulkWriter calls `sync()` function at the closing time. sync() works for all the file system that are syncable in nature like hdfs and others. S3 currently don't support any `sync()` function. 
This change modifies `sync()` method to flush all data in buffer and close file and commit the write.
1. Added unit test to test sync .
2. Verified in sample EMR cluster.
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no) no 
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no …
=> [FLINK-28513] Fix Flink Table API CSV streaming sink throws SerializedThrowable exception

flink-filesystems/flink-s3-fs-base/src/main/java/org/apache/flink/fs/s3/common/writer/S3RecoverableFsDataOutputStream.java, flink-filesystems/flink-s3-fs-base/src/test/java/org/apache/flink/fs/s3/common/writer/S3RecoverableFsDataOutputStreamTest.java
Backport https://github.com/apache/flink/pull/21458 for 1.17
=> [FLINK-28513][Backport][release-1.17] Fix Flink Table API CSV streaming sink throws

flink-filesystems/flink-s3-fs-base/src/main/java/org/apache/flink/fs/s3/common/writer/S3RecoverableFsDataOutputStream.java, flink-filesystems/flink-s3-fs-base/src/test/java/org/apache/flink/fs/s3/common/writer/S3RecoverableFsDataOutputStreamTest.java
Backport https://github.com/apache/flink/pull/21458 for 1.18 branch
=> [FLINK-28513][Backport][release-1.18] Fix Flink Table API CSV streaming sink throws

docs/content.zh/docs/dev/table/tuning.md
This is a minor fix for the page title, after fix, the preview page will be:
=> [FLINK-33026][doc] Fix the title of sql 'Performance Tuning' in the chinese index page

docs/content.zh/docs/dev/table/functions/systemFunctions.md, docs/content/docs/dev/table/functions/systemFunctions.md, docs/layouts/shortcodes/generated/table_config_configuration.html, flink-python/pyflink/table/expressions.py, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/Expressions.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/config/TableConfigOptions.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/expressions/resolver/lookups/FieldReferenceLookup.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/expressions/resolver/rules/ExpandColumnFunctionsRule.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/expressions/resolver/rules/StarReferenceFlatteningRule.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/FlinkCalciteSqlValidator.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/utils/ShortcutUtils.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/stream/sql/ColumnExpansionTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/stream/table/ColumnExpansionTest.java
This introduces a new `table.column-expansion-strategy` option according to FLIP-348. It updates all code locations in SQL and Table API where column expansion takes place. In other words: where `*` is a valid column selector.
For SQL this includes `SELECT *`. For Table API, includes `$(*)`, `withColumns` and `withoutColumns`.
Updated the resolution logic in SQL validator and Table API resolution rules.
This change added tests and can be verified as follows: `ColumnExpansionTest` …
=> [FLINK-33028][table] Make expanding behavior of virtual metadata columns configurable

flink-python/src/main/java/org/apache/flink/python/util/PythonEnvironmentManagerUtils.java
Removing `pip` version check when installing job python dependencies from requirements file.
This change is already covered by existing tests, such as *flink-python/pyflink/table/tests/test_dependency.py*.
- The serializers: ni
=> [FLINK-32962][python] Remove pip version check on installing dependencies.

docs/content.zh/docs/deployment/config.md, docs/content/docs/deployment/config.md
This pull request correct the error value about 'state.backend.type' in the document(config.md).
- Update the description about 'state.backend.type' in the document (config.md).
This change is a trivial work about document without any test coverage.
=> [FLINK-33055][doc]Correct the error value about 'state.backend.type' in the document

flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/utils/JavaUserDefinedAggFunctions.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/AggregateITCase.scala, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/typeutils/TypeCheckUtils.java
When user create an udaf while recore contains user define complex pojo object (like List<UserDefinedObject> or Map<UserDefinedObject>). The codegen will throw error while generating record equaliser, the error is:
`A method named "compareTo" is not declared in any enclosing class nor any subtype, nor through a static import.`
- Add a test to cover the user defined pojo object.
- Does …
=> [FLINK-33063][table-runtime] Fix udaf with complex user defined pojo object throw error while generate record equaliser

flink-runtime-web/web-dashboard/src/app/pages/job/overview/backpressure/job-overview-drawer-backpressure.component.html, flink-runtime-web/web-dashboard/src/app/pages/job/overview/flamegraph/job-overview-drawer-flamegraph.component.html, flink-runtime-web/web-dashboard/src/app/pages/job/overview/flamegraph/job-overview-drawer-flamegraph.component.ts, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/Execution.java, flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/threadinfo/VertexThreadInfoTracker.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ExecutionGraphRestartTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ExecutionGraphTestUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ExecutionPartitionLifecycleTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/threadinfo/VertexThreadInfoTrackerTest.java
Currently, the flamegraph can be triggered when task is running.
After [FLINK-17012](https://issues.apache.org/jira/browse/FLINK-17012) and [FLINK-22215](https://issues.apache.org/jira/browse/FLINK-22215), flink split the running to running and initializing. We should allow trigger flamegraph when task is initializing. For example, the initialization is very slow, we need to troubleshoot.
Here is a stack example, task is rebuilding the rocksdb after the parallelism is changed.
[FLINK-33042][flamegraph] Allow trigger flamegraph when task is initializing
Added the `@Parameter public ExecutionState executionState;` for the `VertexThreadInfoTrackerTest`. And all tests will run with running and initializing. …
=> [FLINK-33042][flamegraph] Allow trigger flamegraph when task is initializing

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/GreatestLeastFunctionsITCase.java
The issue is that `tmpResult` could refer to not initialised variable and this fact leads to compiliation issues. 
It could be reproduced with `GREATEST`/`LEAST` queries when input is a result of other functions like
```sql
SELECT GREATEST(IFNULL(1, 2), IFNULL(2, 1));
```
_ScalarOperatorGens.scala_ assign value to `tmpResult` after it is already initialised in `${element.code}` block
a test to _GreatestLeastFunctionsITCase.java_ was added
Please make sure both new and modified tests in this PR follows the conventions defined in our code quality g
- …
=> [FLINK-33010][table] GREATEST/LEAST should work with other functions as input

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/FileCatalogStore.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/FileCatalogStoreTest.java
Try to create dirs that does not exists when opening file catalog store. If an error is thrown in case the given path not exists, SQL client will fail to start, also SQL gateway won't operate, cause even basic API calls will fail.
It makes sense to at least try creating any missing folders, which can probably help allow some annoying errors and restart rounds.
Add `FileSystem.mkdirs(...)` to `FileCatalogstore.open()` to try creating dirs the given path does not exist.
Added unit test to verify a failing scenario. Every other existing unit test will now create the store root folder. …
=> [BP-1.18][FLINK-32796][table] Try to create catalog store path if not exists

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/FileCatalogStore.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/FileCatalogStoreTest.java
Try to create dirs that does not exists when opening file catalog store. If an error is thrown in case the given path not exists, SQL client will fail to start, also SQL gateway won't operate, cause even basic API calls will fail.
It makes sense to at least try creating any missing folders, which can probably help allow some annoying errors and restart rounds.
Add `FileSystem.mkdirs(...)` to `FileCatalogstore.open()` to try creating dirs the given path does not exist.
Added unit test to verify a failing scenario. Every other existing unit test will now create the store root folder. …
=> [FLINK-32796][table] Try to create catalog store path if not exists

flink-clients/src/main/java/org/apache/flink/client/program/PackagedProgramUtils.java
When the program plan could not be fetched, the root cause may be: the main method doesn't call the `env.execute()`. We can optimize the message to help user find this root cause.
[FLINK-33065][client] Add possible root cause to the exception message when the program plan could not be fetched
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper:no …
=> [FLINK-33065][client] Add possible root cause to the exception message when the program plan could not be fetched

docs/content.zh/docs/deployment/security/security-ssl.md, docs/content/docs/deployment/security/security-ssl.md
There are a couple of misprints in `security-ssl.md` (both englich and chinese versions)
`WHen` => `When`
`generatedd` => `generated`
`security-ssl.md`
=> [hotfix][docs] Misprints in security-ssl.md

flink-table/flink-table-common/src/test/java/org/apache/flink/table/factories/TestDynamicTableSourceOnlyFactory.java, flink-table/flink-table-planner/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/TemporalTableJoinUtil.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/common/CommonTemporalTableJoinRule.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/catalog/CatalogTableITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/TableScanTest.scala
Improve the error message when the lookup source is used as the scan source. Currently, if we use a source which only implement `LookupTableSource` but not implement `ScanTableSource` as a scan source, it cannot get a property plan and give a `Cannot generate a valid execution plan for the given query` which can be improved.
- optimize the erro message.
- adding test to cover it 
- adding test to cover it  …
=> [FLINK-33064][table-planner] Improve the error message when the lookup source is used as the scan source

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/BufferWritingResultPartition.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/ResultPartitionTest.java
```
Problem:
Buffer debloating sets buffer size to 256 bytes because of back-pressure. Such small buffers might not be enough to emit the processing results of a single record. The task thread would request new buffers, and often block. That results in significant checkpoint delays (up to minutes instead of seconds).
Adding more overdraft buffers helps, but depends on the job DoP Raising taskmanager.memory.min-segment-size from 256 helps, but depends on the multiplication factor of the operator.
Solution:
- Ignore Buffer Debloater hints and extend the buffer if possible - when this prevents emitting an output record fully AND this is the last available buffer.
- Prevent the subsequent flush of the buffer so that more output records can be emitted (flatMap-like and join operators)
```
- …
=> [FLINK-33077][runtime] Minimize the risk of hard back-pressure with buffer debloating enabled

flink-runtime/src/main/java/org/apache/flink/runtime/failure/FailureEnricherUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/failure/FailureEnricherUtilsTest.java
https://issues.apache.org/jira/browse/FLINK-33086
*(or)*
*(or)*
*(example:)*
- *Added integration tests for …
=> [FLINK-33086] Protect failure enrichment against unhandled exceptions

flink-python/pyproject.toml
Nightly wheel building job fails because it tries to build 3.7 still.
Fixed wheel build job.
Checked manually.
=> [FLINK-33029][python] fix drop python 3.7 wheel building

flink-runtime/src/main/java/org/apache/flink/runtime/failure/FailureEnricherUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/failure/FailureEnricherUtilsTest.java
Currently `jobmanager.failure-enrichers` is currently used as a filter to only allow loading enrichers that are defined, and not the other way around. However, we should also notify the users if there are enrichers defined that can not be found/loaded.
https://issues.apache.org/jira/browse/FLINK-33022 …
=> [FLINK-33022] Log an error when enrichers defined as part of the configuration can not be found/loaded

flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestValuesTableFactory.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/PartitionableSourceTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/PartitionableSourceTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/PartitionableSourceTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/PartitionableSourceTest.scala
This is a hotfix pr for `TestValuesTableFactory`. If we try to push down a none-existent partition for partitionable source, `TestValuesTableFactory` will throw `java.lang.ClassCastException: java.util.Collections$EmptyMap cannot be cast to java.util.List` error.
- Fix the error  `java.lang.ClassCastException: java.util.Collections$EmptyMap cannot be cast to java.util.List` and related NPE error
- Add test to cover `push down a none-existent partition for partitionable source`.
- Add test to cover `push down a none-existent partition for partitionable source`.
- …
=> [hotfix][test] Fix test value source throw ClassCastException while push down none-existent partition

flink-runtime/src/test/java/org/apache/flink/runtime/registration/RegisteredRpcConnectionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/registration/RetryingRegistrationConfigurationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/registration/RetryingRegistrationTest.java
Migrate flink-runtime/registration tests to JUnit5.
=> [FLINK-32848][tests][JUnit5 migration] Migrate flink-runtime/registration tests to JUnit5

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/FunctionCatalog.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/catalog/UnknownCatalogTest.java
Support listing functions with unset catalog
Added `org.apache.flink.table.planner.catalog.UnknownCatalogTest#testUnsetCatalogWithShowFunctions`
- If yes, how is the feature documented? (**not applicable** / docs / …
=> [FLINK-33093] Support listing functions with unset catalog

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/connectors/DynamicSinkUtils.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/connectors/DynamicSourceUtils.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/spec/DynamicTableSourceSpec.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/schema/TableSourceTable.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/jsonplan/TableSourceJsonPlanITCase.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/connector/file/table/FileSystemTableSourceTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/SubplanReuseTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/TableSourceTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/TableSourceJsonPlanTest_jsonplan/testReuseSourceWithoutProjectionPushDown.out, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/optimize/ScanReuseTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/PushProjectIntoTableSourceScanRuleTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/PushWatermarkIntoTableSourceScanRuleTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/physical/batch/PushLocalAggIntoTableSourceScanRuleTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/physical/stream/WatermarkAssignerChangelogNormalizeTransposeRuleTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/NonDeterministicDagTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/SourceWatermarkTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/SubplanReuseTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/TableScanTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/TableSinkTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/TableSourceTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/agg/AggregateTest.xml
The PR fixes creating a TableSourceScan to also include a proper ReadingMetadataSpec which has been applied on the source.
* revert the solution added in #22894 because it works around the outcome of the bug rather than fixes the bug
* create a ReadingMetadataSpec when applying it on the `TableSource` in a `TableSourceScan`
* tests added in #22894 should still pass
* added a dedicated test `TableSourceJsonPlanITCase#testReadingMetadataWithProjectionPushDownDisabled` …
=> [FLINK-33083] Properly apply ReadingMetadataSpec for a TableSourceScan

flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/expressions/ColumnReferenceFinderTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/expressions/TypeConversionsTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/expressions/converter/ExpressionConverterTest.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/ArrayTypeTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/CompositeAccessTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/DecimalTypeTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/LiteralTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/MapTypeTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/NonDeterministicTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/RowTypeTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/ScalarFunctionsTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/ScalarOperatorsTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/SqlExpressionTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/TemporalTypesTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/utils/CompositeTypeTestBase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/utils/ExpressionTestBase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/validation/ArrayTypeValidationTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/validation/CompositeAccessValidationTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/validation/MapTypeValidationTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/validation/RowTypeValidationTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/validation/ScalarFunctionsValidationTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/validation/ScalarOperatorsValidationTest.scala
[FLINK-33032][table-planner][JUnit5 Migration] Module: flink-table-planner (ExpressionTestBase)
JUnit5 Migration Module: flink-table-planner (ExpressionTestBase)
=> [FLINK-33032][table-planner][JUnit5 Migration] Module: flink-table-planner (ExpressionTestBase)

flink-runtime/src/test/java/org/apache/flink/runtime/rpc/AsyncCallsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rpc/FencedRpcEndpointTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rpc/RpcConnectionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rpc/RpcEndpointTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rpc/RpcSSLAuthITCase.java
Migrate flink-runtime/rpc tests to JUnit5.
=> [FLINK-32848][tests][JUnit5 migration] Migrate flink-runtime/rpc tests to JUnit5

flink-tests/src/test/java/org/apache/flink/test/checkpointing/EventTimeAllWindowCheckpointingITCase.java
Fix EventTimeAllWindowCheckpointingITCase jobName typo
Adjust the jobName of test in EventTimeAllWindowCheckpointingITCase
=> [FLINK-33126] Fix EventTimeAllWindowCheckpointingITCase jobName typo

docs/layouts/shortcodes/generated/common_host_port_section.html, docs/layouts/shortcodes/generated/rest_configuration.html, flink-clients/src/main/java/org/apache/flink/client/cli/DefaultCLI.java, flink-clients/src/main/java/org/apache/flink/client/program/rest/RestClusterClient.java, flink-clients/src/test/java/org/apache/flink/client/cli/DefaultCLITest.java, flink-clients/src/test/java/org/apache/flink/client/program/rest/RestClusterClientTest.java, flink-core/src/main/java/org/apache/flink/configuration/RestOptions.java, flink-core/src/main/java/org/apache/flink/util/NetUtils.java, flink-core/src/test/java/org/apache/flink/util/NetUtilsTest.java
[FLINK-32884](https://issues.apache.org/jira/browse/FLINK-32884) PyFlink remote execution should support URLs with paths and https scheme
Currently, the `SUBMIT_ARGS=remote -m http://<hostname>:<port>` format. For local execution it works fine `SUBMIT_ARGS=remote -m http://localhost:8081/`, but it does not support the placement of the JobManager behind a proxy or using an Ingress for routing to a specific Flink cluster based on the URL path. In the current scenario, it expects JobManager to access PyFlink jobs at `http://<hostname>:<port>/v1/jobs` endpoint. Mapping to a non-root location, `https://<hostname>:<port>/flink-clusters/namespace/flink_job_deployment/v1/jobs` is not supported.
This will use changes from [FLINK-32885](https://issues.apache.org/jira/browse/FLINK-32885)(https://issu …
=> [FLINK-32884] [flink-clients] PyFlink remote execution should support URLs with paths and https scheme

flink-runtime/src/main/java/org/apache/flink/runtime/security/token/hadoop/HadoopFSDelegationTokenProvider.java, flink-runtime/src/test/java/org/apache/flink/runtime/security/token/hadoop/HadoopFSDelegationTokenProviderITCase.java
*Fix NullPointException when starting flink cluster in standalone mode with hadoop configuration*
- Add default value when getting  `DeploymentOptions.TARGET`  options 
- In the HadoopFSDelegationTokenProviderITCase class, `obtainDelegationTokenWithStandaloneDeployment` has been added to test this modification.
- Does …
=> [FLINK-32976][runtime] Fix NullPointException when starting flink cluster in standalone mode

flink-table/flink-table-common/src/test/java/org/apache/flink/table/factories/TestDynamicTableSourceOnlyFactory.java, flink-table/flink-table-planner/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/TemporalTableJoinUtil.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/common/CommonTemporalTableJoinRule.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/catalog/CatalogTableITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/TableScanTest.scala
After testing different sql pattern, found that `FLINK-33064` can cause serious bugs in views and subquery scenarios. So this pr is aims to revert `FLINK-33064`
revert `FLINK-33064`
no tests.
- If yes, how is the feature documented? no docs
=> Revert "[FLINK-33064][table-planner] Improve the error message when the lookup source is used as the scan source"

flink-clients/src/main/java/org/apache/flink/client/program/rest/RestClusterClient.java, flink-clients/src/main/java/org/apache/flink/client/program/rest/UrlPrefixDecorator.java, flink-clients/src/test/java/org/apache/flink/client/program/rest/RestClusterClientTest.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/CustomHeadersDecorator.java
[FLINK-32884](https://issues.apache.org/jira/browse/FLINK-32884) PyFlink remote execution should support URLs with paths and https scheme
This PR handles including customHeaders in messageHeaders when a Python client is sending requests. This will allow sending auth tokens with the request.
- send messageHeaders which are decorated with customHeaders
This change is already covered by existing tests, such as `flink-clients/src/test/java/org/apache/flink/client/program/rest/RestClusterClientTest.java#testRESTManualConfigurationOverride`
- The runtime …
=> [FLINK-32884] [flink-clients] Sending messageHeaders with decorated customHeaders for PyFlink client

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/FlinkCalciteSqlValidator.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/stream/sql/ColumnExpansionTest.java
"TABLE t" is translated into an implicit "SELECT * FROM t". This would ignore columns
that are not expanded by default. However, the descriptor explicitly states the need
for this column.
Explicit table expressions (for window TVFs at most one)
are captured before rewriting and replaced with a "marker" SqlSelect that contains the
descriptor information. The "marker" SqlSelect is considered during column expansion.
This change added tests and can be verified as follows: `ColumnExpansionTest` …
=> [FLINK-33169] Consider descriptor information during system column expansion

flink-python/dev/dev-requirements.txt, flink-python/setup.py
`Numpy 1.21.4` was released on Nov 5, 2021 which is quite old. In this PR I've bumped it to `1.22.4`.
Bumped numpy version.
Built wheels with the following command:
`dev/build-wheels.sh`
=> [FLINK-33172][python] Bump numpy version

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecSort.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/ExecNodeMetadataUtil.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/SortJsonPlanTest.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/nodes/exec/stream/SortJsonPlanTest_jsonplan/testSort.out
Properly serialises `StreamExecSort` into JsonPlan. Even though `StreamExecSort` is not supported for production workloads, without the change it fails during plan deserialisation which gives a cryptic error message.
Added test in `org.apache.flink.table.planner.plan.nodes.exec.stream.SortJsonPlanTest#testSort` …
=> [FLINK-33158] Cryptic exception when there is a StreamExecSort in JsonPlan

flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/SqlGatewayServiceITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/operation/OperationManagerTest.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/result/ResultFetcherTest.java
[FLINK-33000][sql-gateway][release-1.18] SqlGatewayServiceITCase, ResultFetcherTest and OperationManagerTest should utilize TestExecutorExtension instead of using a ThreadFactory
SqlGatewayServiceITCase, ResultFetcherTest and OperationManagerTest should utilize TestExecutorExtension instead of using a ThreadFactory …
=> [FLINK-33000][sql-gateway][release-1.18] SqlGatewayServiceITCase should utilize TestExecutorExtension instead of using a ThreadFactory 

flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/SqlGatewayServiceITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/operation/OperationManagerTest.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/result/ResultFetcherTest.java
[FLINK-33000][sql-gateway][release-1.17] SqlGatewayServiceITCase, ResultFetcherTest and OperationManagerTest should utilize TestExecutorExtension instead of using a ThreadFactory
SqlGatewayServiceITCase, ResultFetcherTest and OperationManagerTest should utilize TestExecutorExtension instead of using a ThreadFactory …
=> [FLINK-33000][sql-gateway][release-1.17] SqlGatewayServiceITCase should utilize TestExecutorExtension instead of using a ThreadFactory

flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/SqlGatewayServiceITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/result/ResultFetcherTest.java
[FLINK-33000][sql-gateway][release-1.16] SqlGatewayServiceITCase and OperationManagerTest should utilize TestExecutorExtension instead of using a ThreadFactory
SqlGatewayServiceITCase and OperationManagerTest should utilize TestExecutorExtension instead of using a ThreadFactory
- If yes, how …
=> [FLINK-33000][sql-gateway][release-1.16] SqlGatewayServiceITCase should utilize TestExecutorExtension instead of using a ThreadFactory 

docs/layouts/shortcodes/generated/expert_scheduling_section.html, docs/layouts/shortcodes/generated/resource_manager_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/ResourceManagerOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManagerRuntimeServices.java, flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/StandaloneResourceManagerFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/DefaultResourceAllocationStrategy.java, flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotManagerConfiguration.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/DeclarativeSlotManagerBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/DefaultResourceAllocationStrategyTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/FineGrainedSlotManagerDefaultResourceAllocationStrategyITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotManagerConfigurationBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotManagerConfigurationTest.java, flink-tests/src/test/java/org/apache/flink/test/recovery/TaskManagerDisconnectOnShutdownITCase.java
Add min number of slots configuration to limit total number of slots
- Introduce "slotmanager.number-of-slots.min" configuration option with default value 0
- Introduce "slotmanager.min-total-resource.cpu" and "slotmanager.min-total-resource.memory" configuration option with default value derived from "slotmanager.number-of-slots.min"
- Make DefaultResourceAllocationStrategy respect the min number of cpu and memory. DefaultResourceAllocationStrategy will alway check the min resource requirement when reconciling cluster resources or fulfilling resource requirement.
- Added unit tests **SlotManagerConfigurationTest#testComputeMinTotalCpu**,  **SlotManagerConfigurationTest#testComputeMinTotalMemory**, …
=> [FLINK-15959][flink-runtime] Add min number of slots configuration to limit total number of slots

docs/content/docs/deployment/overview.md
- Add Decodable and Aiven
- Update the name of AWS's offering (it's now called Amazon Managed Service for Apache Flink)
There are more vendors offering Flink as a managed service, so adding them to the list. 
At the same time, reflect the change in name to AWS' offering. 
EDIT: 
disclaimer: I work for Decodable :)
=> [docs] Update Vendor Solutions

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/ExecNodeContext.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/UnsupportedNodesInPlanTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/serde/ExecNodeGraphJsonSerializerTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/utils/ExecNodeMetadataUtilTest.java, flink-table/flink-table-planner/src/test/resources/jsonplan/testInvalidTypeJsonPlan.json, pom.xml
The change prohibits serialising `ExecNode` with a wrong type. Previously it was possible to create a `null_null` type.
Moreover it gives a better exception when deserialising such a node.
* added checks in `ExecNodeContext`
Added a test for deserialising an `ExecNode` with `null_null` type.
Added a test for serialisation in `org.apache.flink.table.planner.plan.nodes.exec.serde.ExecNodeGraphJsonSerializerTest` …
=> [FLINK-33179] Throw exception when serialising or deserialising ExecNode with invalid type

flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/DefaultResourceAllocationStrategy.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/DefaultResourceAllocationStrategyTest.java
- Fix the total current resource calculation when fulfilling requirements in DefaultResourceAllocationStrategy
- Fix typos in DefaultResourceAllocationStrategy comments
- Makeing `tryFulfillRequirementsForJobWithPendingResources` return new added resource profile to track the total current resource profile
- Added UnitTests `DefaultResourceAllocationStrategyTest#testMinRequiredCPULimitInTryFulfillWithRequirement` and `DefaultResourceAllocationStrategyTest#testMinRequiredMemoryLimitInTryFulfillWithRequirement` …
=> [FLINK-33228][flink-runtime] Fix the total current resource calculation when fulfilling requirement

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserCalcitePlanner.java, flink-connectors/flink-connector-hive/src/test/resources/query-test/join.q
Fix NPE when non-native udf used in join condition in hive-parser
This problem caused by not set  UnparseTranslator when init HiveParserJoinTypeCheckCtx.
This change is verified by added test
=> [FLINK-33233][hive] Fix NPE when non-native udf is used in join condition with Hive dialect

flink-architecture-tests/flink-architecture-tests-base/src/main/java/org/apache/flink/architecture/common/JavaFieldPredicates.java, flink-architecture-tests/flink-architecture-tests-base/src/main/java/org/apache/flink/architecture/common/Predicates.java, flink-architecture-tests/flink-architecture-tests-base/src/test/java/PredicatesTest.java, flink-architecture-tests/flink-architecture-tests-production/src/main/java/org/apache/flink/architecture/rules/TableApiRules.java, flink-architecture-tests/flink-architecture-tests-test/pom.xml, flink-architecture-tests/flink-architecture-tests-test/src/main/java/org/apache/flink/architecture/rules/ITCaseRules.java
Currently architecture tests rely on importing such classes as `MiniClusterExtension`. This introduces a production scope dependency on `flink-test-utils` which in turn depends on `flink-streaming-java`. This is problematic because adding architecture tests to any direct or transitive dependency of `flink-streaming-java` creates a dependency cycle.
Example: https://github.com/apache/flink/pull/22850#discussion_r1243343382
In general, since architecture tests are supposed to be used freely in any submodule, it is desirable to reduce its dependency surface as much as possible to prevent such cycles. 
- Modifies methods to using  fully qualified type names checks instead of Class objects
- Removes production maven dependencies on `flink-test-utils`,  `flink-test-utils-junit` and …
=> [FLINK-33199][tests] Use fully qualified class names instead of Class objects in ArchitectureTests

docs/layouts/shortcodes/generated/expert_scheduling_section.html, docs/layouts/shortcodes/generated/resource_manager_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/ResourceManagerOptions.java
Remove the OverrideDefault annotation for option `slotmanager.number-of-slots.min`.
Remove the OverrideDefault annotation for option `slotmanager.number-of-slots.min`.
=> [hotfix][docs] Remove the OverrideDefault annotation for option slotmanager.number-of-slots.min

flink-test-utils-parent/flink-test-utils/pom.xml, pom.xml
This PR aims to add curator-test dependency in flink-test-utils project which will used in flink-benchmarks. Then we can use zookeeper testing server in flink-benchmarks and the version of curator-test can be consistent with flink version.
- Add curator-test in flink-test-utils …
=> [FLINK-33033][test] Add curator-test for flink-benchmarks

docs/layouts/shortcodes/generated/expert_high_availability_zk_section.html, docs/layouts/shortcodes/generated/high_availability_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/HighAvailabilityOptions.java
The running registry subcomponent of Flink HA has been removed in [FLINK-25430](https://issues.apache.org/jira/browse/FLINK-25430) and the "high-availability.zookeeper.path.running-registry" option is of no use after that. We should Deprecate the option and regenerate the config doc to remove the relevant descriptions to avoid user's confusion.
Deprecate the unused high-availability.zookeeper.pth.running-registry option and remove the relevant doc.
This change is a trivial code cleanup.
- …
=> [FLINK-33236][config] Deprecate the unused high-availability.zookeeper.path.running-registry option

flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveRunnerITCase.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableSinkITCase.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableSpeculativeSinkITCase.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/TableEnvExecutorUtil.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/TableEnvHiveConnectorITCase.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/catalog/hive/HiveCatalogITCase.java, flink-table/flink-sql-client/src/test/resources/sql/catalog_database.q, flink-table/flink-sql-gateway/src/test/resources/sql/catalog_database.q, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogManagerTest.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/catalog/CatalogTableITCase.scala
Forbid to drop the currently used database.
- `CatalogManager.dropDatabase(...)` now throws a `ValidationException` if it is called with `currentCatalogName` and `currentDatabaseName`.
- Added unit test in `CatalogManagerTest`.
- Adapted relevant IT cases.
- Introduced `TableEnvExecutorUtil` to `flink-hive-connector` tests to minimize test database management related code duplications.
Added new unit test to cover dropping current database. …
=> [FLINK-33226][table] Forbid to drop current database

flink-core/src/main/java/org/apache/flink/util/NetUtils.java, flink-core/src/test/java/org/apache/flink/util/NetUtilsTest.java
Fix the failure of creating a connection when the gateway address is an IPv6 address.
-  Fix `NetUtils.socketToUrl` to work properly if the hostString in the socketAddress is an IPv6 address.
- Add `testIpv6SocketToUrl` and `testIpv4SocketToUrl` in `NetUtilsTest`. …
=>  [FLINK-33289] Fix the conversion of InetSocketAddress to URL in Network utils to work with ipv6 address correctly

flink-core/src/main/java/org/apache/flink/util/ChildFirstClassLoader.java, flink-core/src/main/java/org/apache/flink/util/FlinkUserCodeClassLoader.java, flink-core/src/main/java/org/apache/flink/util/FlinkUserCodeClassLoaders.java, flink-core/src/main/java/org/apache/flink/util/MutableURLClassLoader.java, flink-core/src/test/java/org/apache/flink/util/FlinkUserCodeClassLoaderTest.java, flink-formats/flink-hadoop-bulk/src/test/java/org/apache/flink/streaming/api/functions/sink/filesystem/HadoopPathBasedBulkFormatBuilderTest.java, flink-table/flink-sql-client/src/test/resources/sql/function.q, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/FunctionCatalog.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/resource/ResourceManager.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/resource/ResourceManagerTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/FunctionITCase.java
When flink perform `create temporary function` or `create system function` with a jar file, it will register the jar file to `ResourceManager` and add it to the `ClassLoader`. This cause the `SHOW JARS` statement can list the jar files for these functions, and even when a job does not use these function, the jar file will be aded to the job's classpath.
This PR aims to address this issue with three steps:
1. Create temporary or system function
a> Download the jar file from remote as needed, which is the same as before for these functions.
b> Add jar files for temporary and system functions to a new class `FunctionResourceManager` in `ResourceManager` when they are created.
c> Create a new classloader with the added jar files and validate the function class
2. Job uses temporary or system …
=> [FLINK-32512] Don't register resource to user resource manager when creating temporary function

flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/threadinfo/VertexFlameGraphFactory.java, flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/threadinfo/VertexFlameGraphFactoryTest.java
in java 21 it was changed representation of lambda in stack trace which is used in current test
The PR makes the test aware of it
This change is a trivial rework + adapting test itself
=> [FLINK-33321] VertexFlameGraphFactoryTest#verifyRecursively fails on Java 21

pom.xml
1.16 backport of parent PR https://github.com/apache/flink/pull/23529
I left the Maven range as is because the Java version actually causing the problem and the branch is soon to be gone, anyway.
=> [BP-1.16][FLINK-33291][build] Sets the enforced range for Maven and JDK within the release profile

pom.xml
1.17 backport of parent PR https://github.com/apache/flink/pull/23529
I left the Maven range as is because the Java version actually causing the problem and the branch is soon to be gone, anyway.
=> [BP-1.17][FLINK-33291][build] Sets the enforced range for Maven and JDK within the release profile

pom.xml
We want to enforce the Maven and JDK version for releases based on the versions that are used in Flink's CI pipeline to ensure a certain level of quality control.
* Adds proper range for Maven and JDK
* For the JDK version, it looks like we cannot use `${target.java.version}` or `[1.8]` to cover any minor releases
Manual verification by running `./mvn -pl flink-annotations -DskipTests -Prelease validate` with different Java and Maven versions …
=> [FLINK-33291][build] Sets the enforced range for Maven and JDK within the release profile

flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientTest.java
[FLINK-33116][tests] Fix CliClientTest.testCancelExecutionInteractiveMode fails with NPE
```shell
Sep 18 02:26:15 02:26:15.743 [ERROR] org.apache.flink.table.client.cli.CliClientTest.testCancelExecutionInteractiveMode  Time elapsed: 0.1 s  <<< ERROR!
Sep 18 02:26:15 java.lang.NullPointerException
Sep 18 02:26:15 	at org.apache.flink.table.client.cli.CliClient.closeTerminal(CliClient.java:284)
Sep 18 02:26:15 	at org.apache.flink.table.client.cli.CliClient.close(CliClient.java:108)
Sep 18 02:26:15 	at org.apache.flink.table.client.cli.CliClientTest.testCancelExecutionInteractiveMode(CliClientTest.java:314)
Sep 18 02:26:15 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
```
The CliClient is not thread-safe: The close call fails with a NullPointerException …
=> [FLINK-33116][tests][release-1.17] Fix CliClientTest.testCancelExecutionInteractiveMode fails with NPE

flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientTest.java
[FLINK-33116][tests] Fix CliClientTest.testCancelExecutionInteractiveMode fails with NPE
```shell
Sep 18 02:26:15 02:26:15.743 [ERROR] org.apache.flink.table.client.cli.CliClientTest.testCancelExecutionInteractiveMode  Time elapsed: 0.1 s  <<< ERROR!
Sep 18 02:26:15 java.lang.NullPointerException
Sep 18 02:26:15 	at org.apache.flink.table.client.cli.CliClient.closeTerminal(CliClient.java:284)
Sep 18 02:26:15 	at org.apache.flink.table.client.cli.CliClient.close(CliClient.java:108)
Sep 18 02:26:15 	at org.apache.flink.table.client.cli.CliClientTest.testCancelExecutionInteractiveMode(CliClientTest.java:314)
Sep 18 02:26:15 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
```
The CliClient is not thread-safe: The close call fails with a NullPointerException …
=> [FLINK-33116][tests][release-1.16] Fix CliClientTest.testCancelExecutionInteractiveMode fails with NPE

flink-core/pom.xml
Since current version of lombok is incompatible with jdk21 the PR is aiming to upgrade lombok version as this issue has been fixed at https://github.com/projectlombok/lombok/issues/3393
pom.xml
=> [FLINK-33308] Upgrade lombok to 1.8.30

pom.xml
Since there is no spotless version which could be used together for java 8 and java21 the PR is going to skip spotless for java21
pom.xml
=> [FLINK-33307] Disable spotless on Java 21

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/FlinkCalciteSqlValidator.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/stream/sql/ColumnExpansionTest.java
Fixes expanding explicit columns if the `TableFunction` is resolved.
Added test: `org.apache.flink.table.planner.plan.stream.sql.ColumnExpansionTest#testExplicitTableWithinTableFunctionWithInsertIntoNamedColumns`
- If …
=> [FLINK-33327] Window TVF column expansion does not work with an INSERT INTO

docs/content/docs/ops/metrics.md, flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/metrics/MeterView.java, flink-runtime-web/web-dashboard/src/app/pages/job-manager/metrics/job-manager-metrics.component.ts, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/util/MetricUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/util/MetricUtilsTest.java
As discussed in https://cwiki.apache.org/confluence/display/FLINK/FLIP-361%3A+Improve+GC+Metrics. This commit adds the All collector group to measure time + count across collectors + adds the timeMsPerSecond metric for each collector group to measure time spent in GC over the last minute similar to other busy/idle etc metrics in Flink
- Add new metrics
- Add tests to cover existing and new metrics
- Updated docs
Unit tests + manual verification. …
=> [FLINK-33318] Expose aggregated collector metrics and measure timeMsPerSecond

pom.xml
based on release notes 2.12.18 - the first 2.12.x supporting jdk21
https://github.com/scala/scala/releases/tag/v2.12.18
the PR adds 2.12.18 for java 21
the PR is based on https://github.com/apache/flink/pull/23546 …
=> [FLINK-33310] Scala before 2.12.18 doesn't compile on Java 21

flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/RegistryAvroDeserializationSchemaTest.java, flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE, flink-formats/flink-sql-avro/src/main/resources/META-INF/NOTICE, pom.xml
Unchanged backport of https://github.com/apache/flink/pull/23508
=> [BP 1.18][FLINK-33238][Formats/Avro] Upgrade used AVRO version to 1.11.3

docs/content.zh/docs/dev/table/sql/queries/window-tvf.md, docs/content/docs/dev/table/sql/queries/window-tvf.md, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/WindowTableFunctionTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/WindowTableFunctionTest.scala
The current named params example with 'OFFSET' in window tvf is invalid, this pr aims to fix the doc and add some tests.
Add tests and update the documentation
Streaming sql's `WindowTableFunctionTest` newly added test cases
=> [FLINK-33314][table] Fix the named parameter example in window tvf

flink-dist/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE, flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE, flink-formats/flink-sql-avro/src/main/resources/META-INF/NOTICE, pom.xml
The PR is addressing CVE-2023-42503
=> [FLINK-33329] Upgrade commons-compress to 1.24.0

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/HsFileDataIndexImpl.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/HsSpillingStrategy.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/HsSpillingStrategyUtils.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/file/ProducerMergedPartitionFileIndex.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/TestingSpillingInfoProvider.java, flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorConcurrentAttemptsTest.java
The are multiple cases in the code which look like this:
`map.computeIfAbsent(..., ArrayList::new)`
Not only does this create a new collection (here an ArrayList), but computeIfAbsent also passes the map key as argument to the mapping function, so instead of calling the no-args constructor such as new ArrayList<>(), this actually calls the constructor with int initial capacity parameter, such as new ArrayList<>(initialCapacity).
This can lead either to runtime exceptions in case the map key is negative, since the collection constructors reject negative initial capacity values, or it can lead to bad performance if the key (which is misinterpreted as initial capacity) is pretty low, such as 0, or is pretty large and therefore pre-allocates a lot of memory for the collection.
it might be …
=> [FLINK-32896][Runtime/Coordination] Incorrect `Map.computeIfAbsent(..., ...::new)` usage which misinterprets key as initial capacity

flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerConfiguration.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/rpc/RpcInputSplitProvider.java
[FLINK-33344][rpc] Replace Time with Duration in RpcInputSplitProvider
[FLINK-33344][rpc] Replace Time with Duration in RpcInputSplitProvider
=> [FLINK-33344][rpc] Replace Time with Duration in RpcInputSplitProvider

tools/azure-pipelines/build-apache-repo.yml
@gyfora noticed in his [FLINK-32380 PR](https://github.com/apache/flink/pull/23490#issuecomment-1774559892) that we're not setting the target version profile to Java 17. This PR fixes the issue
* Adds `java17-target` profile
* Adds Maven output for printing the activated profiles (for debugging/verification purposes in the future)
This change is a trivial rework / code cleanup without any test coverage. Manual testing is done by checking whether the activated profiles are printed. …
=> [FLINK-33342][ci] Enables Java17 as a target version for the Java 17 CI jobs

docs/content.zh/_index.md, docs/content.zh/release-notes/flink-1.18.md, docs/content/_index.md, docs/content/release-notes/flink-1.18.md
This pull request adds release note for version 1.18.
- Add release note for 1.18
This change is a doc-only without test coverage. …
=> [FLINK-33274][release] Add release note for version 1.18

flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/threadinfo/VertexFlameGraphFactoryTest.java
looks like in the first PR https://github.com/apache/flink/pull/23556 there was a mistake, sorry for that
this PR is going to address it
i 've set java21 for my pipeline and here the results
Current version of test 
https://dev.azure.com/snuyanzin/flink/_build/results?buildId=2435&view=logs&j=9dc1b5dc-bcfa-5f83-eaa7-0cb181ddc267&t=511d2595-ec54-5ab7-86ce-92f328796f20&l=8087
and fixed version
Proof  link https://dev.azure.com/snuyanzin/flink/_build/results?buildId=2436&view=logs&j=9dc1b5dc-bcfa-5f83-eaa7-0cb181ddc267&t=511d2595-ec54-5ab7-86ce-92f328796f20&l=76 …
=> [FLINK-33321][hotfix] VertexFlameGraphFactoryTest#verifyRecursively doesn't work on java 21

flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java
1.16 backport for parent PR https://github.com/apache/flink/pull/23578
=> [BP-1.16][FLINK-33346][runtime][test] Removes timeout

flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java
The instability is caused by the timeout. The fatal error hides the actual cause (i.e. the TimeoutException). It can be reproduced by setting the timeout of the test to 0ms. The actual cause is revealed when disabling the fatal error handling or not throwing a AssertionError in case of the fatal error.
I checked the rest of the class: The other test methods that use timeouts need it.
* Removes timeout …
=> [FLINK-33346][runtime][test] Removes timeout

flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/TypeInferenceUtil.java, flink-table/flink-table-planner/src/main/java/org/apache/calcite/sql/validate/ExtraCalciteResource.java, flink-table/flink-table-planner/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/inference/TypeInferenceOperandInference.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CollectionFunctionsITCase.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/CalcITCase.scala
- Previously, TypeInferenceOperandInference was not validating argument counts which led to bugs like FLINK-33248
- This commit adds a check to validate argument count and throws an exception if the argument count doesn't match the expected number of arguments
Validate argument count during type inference to avoid bugs like [FLINK-33248]
- *Adds a check to validate argument count and throws an exception if the argument count doesn't match the expected number of arguments*
- *Also leads to better error messages*
- *Added test to verify a ValidationException message is seen when functions are invoked without arguments*
- *Updated existing function tests with improved error message* …
=> [FLINK-33255] [table] Validate argument count during type inference

docs/content/docs/deployment/elastic_scaling.md, docs/layouts/shortcodes/generated/all_jobmanager_section.html, docs/layouts/shortcodes/generated/expert_scheduling_section.html, docs/layouts/shortcodes/generated/job_manager_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/JobManagerOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Executing.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/scalingpolicy/EnforceParallelismChangeRescalingController.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/ExecutingTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/scalingpolicy/EnforceParallelismChangeRescalingControllerTest.java
Introduce the cooldown period in the adaptive scheduler ([FLIP-322](https://cwiki.apache.org/confluence/display/FLINK/FLIP-322+Cooldown+period+for+adaptive+scheduler))
Change Executing state, when new slots arrive:
-  schedule a rescale when last rescale was done less than interval-min seconds ago, rescale immediately otherwise.
-  Add the ability to force a rescale when last rescale was done more than interval-max seconds ago regardless if the requirements are met (context#shouldRescale)
Added 3 tests to ExecutingTest test case.
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: adding to parameters related to timing …
=> [FLINK-21883][scheduler] Implement cooldown period for adaptive scheduler

flink-runtime/src/test/java/org/apache/flink/runtime/io/disk/BatchShuffleReadBufferPoolTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/disk/ChannelViewsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/disk/FileChannelManagerImplTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/disk/FileChannelStreamsITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/disk/FileChannelStreamsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/disk/SeekableFileChannelInputViewTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/disk/SpillingBufferTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/disk/iomanager/AsynchronousBufferFileWriterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/disk/iomanager/AsynchronousFileIOChannelTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/disk/iomanager/BufferFileWriterFileSegmentReaderTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/disk/iomanager/BufferFileWriterReaderTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/disk/iomanager/IOManagerAsyncTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/disk/iomanager/IOManagerITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/disk/iomanager/IOManagerTest.java
[FLINK-32850][flink-runtime][JUnit5 Migration] The io.disk package of flink-runtime module
[FLINK-32850][flink-runtime][JUnit5 Migration] The io.disk package of flink-runtime module
=> [FLINK-32850][flink-runtime][JUnit5 Migration] The io.disk package of flink-runtime module

flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/test/program/ConfigOptionTestStep.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/test/program/FunctionTestStep.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/test/program/SinkTestStep.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/test/program/SourceTestStep.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/test/program/SqlTestStep.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/test/program/StatementSetTestStep.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/test/program/TableTestProgram.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/test/program/TableTestProgramRunner.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/test/program/TableTestStep.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/test/program/TestStep.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/test/program/TableTestProgramRunnerTest.java
This adds infrastructure for declaring table test programs once and use them for various purposes.
```
/**
* A generic declaration of a table program for testing.
*
* <p>A test program only defines the basic test pipeline (from source to sink) and required
* artifacts such as table sources and sinks, configuration options, and user-defined functions.
*
* <p>Tests programs are intended to reduce code duplication and test the same SQL statement though
* different layers of the stack. Different {@link TableTestProgramRunner}s can share the same
* program and enrich it with custom implementation and assertions.
*
* <p>For example, a SQL query such as {@code SELECT * FROM (VALUES (1), (2), (3))} can be declared
* once and can be shared among different tests for integration testing, optimizer …
```
=> [FLINK-25809][table-api-java] Add table test program infrastructure

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/source/StatefulSequenceSource.java, flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/connector/datagen/table/DataGenTableSource.java
This a simple fix for an erroneous reference to `StatefulSequenceSource` in `DataGenTableSource` and preparation for its removal in 2.0
=> [hotfix] Prepare StatefulSequenceSource for removal in 2.0

docs/content.zh/docs/dev/table/overview.md
Add SQL Gateway doc reference in the Chinese version of table overview
Add SQL Gateway doc reference in docs/content.zh/docs/dev/table/overview.md
=> [hotfix][docs] Add SQL Gateway doc reference in the Chinese version of table overview

flink-scala/pom.xml, flink-streaming-scala/pom.xml, flink-table/flink-sql-jdbc-driver-bundle/pom.xml, pom.xml
Based on https://github.com/apache/flink/pull/23609
Move us back to the original japicmp plugin.
=> [FLINK-32182][build] Use original japicmp plugin

flink-end-to-end-tests/test-scripts/common_ha.sh
1.18 backport for PR https://github.com/apache/flink/pull/23614
*(Running HA (hashmap, async) end-to-end test failed on azure due to unable to find master logs.)*
- *1.18 backport PR, modify  verify_num_occurences_in_logs.sh, Changed `uniq `to `sort -u`*
- *This change is already covered by existing test.* …
=> [FLINK-26624][Runtime] 1.18 backport Running HA (hashmap, async) end-to-end test failed on azu

flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/test/program/SinkTestStep.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/test/program/SourceTestStep.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/test/program/TableTestProgram.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/test/program/TableTestStep.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/testutils/CalcTestPrograms.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/test/program/TableTestProgramRunnerTest.java
From first feedback, this PR improves the readability of TableTestPrograms.
- Use a proper builder pattern for `SourceTestStep` and `SinkTestStep`
- Give builder methods a better name (indicate when it `add` or sets, indicate whether data is `produced` or `consumed`) …
=> [FLINK-25809][table] Improve readability of TableTestPrograms

flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/resource/ClientResourceManager.java, flink-table/flink-sql-client/src/test/resources/sql/function.q, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/operation/OperationExecutor.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/result/ResultFetcher.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/FunctionCatalog.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/resource/ResourceManager.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/resource/ResourceManagerTest.java
This PR aims to create new resource manager for table environment in sql gateway
- Create new resource manager which will share the classloader and local path with the previous manager
- Create table environment for each operation in gateway with the new resource manager
- Add jars and functions related operation in gateway which will be performed on the session resource manager.
- Updated `function.q` to test that previous job will not affect the jars in gateway
- The runtime per-record code paths (performance sensitive): (yes …
=> [FLINK-32309][sql-gateway] Use independent resource manager for table environment

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/ProjectionCodeGenerator.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/agg/batch/HashAggCodeGenerator.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/HashAggITCase.scala
*Fix adaptive local hash can't work when auxGrouping exists*
- *Fix adaptive local hash can't work when auxGrouping exists*
- *Added integration tests in HashAggITCase*
=> [BP-1.17][FLINK-32426][table-runtime] Fix adaptive local hash can't work when auxGrouping exists

.github/workflows/docs.yml
The docs CI build is failing because its using an old docker image that still uses maven 3.2.5. Upgrade to the current CI image.
=> [hotfix] Update docs build CI image

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/PartitionRequestQueue.java
Add the information of the remote address in the exception handling logs of the `PartitionRequestQueue`, so that network issues can be located through the network quintuple.
- Add exception log to print the remote address in `PartitionRequestQueue`.
- The modification only involves log, no additional testing is required.
*(or)*
*(or)* …
=> [FLINK-33160][network] Log the remote address when an exception occurs in the PartitionRequestQueue

docs/content.zh/docs/dev/table/sql/show.md, docs/content/docs/dev/table/sql/show.md
Fix en-doc SHOW CREATE TABLE usage.
=> [FLINK-32767][doc] Fix en-doc SHOW CREATE TABLE usage

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/ExecNodeGraphInternalPlan.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/delegation/StreamPlanner.scala
Avoids re-serializing of JSON during the load operation. The re-serialization makes still sense to retrieve a normalized JSON but this is a rather uncommon case.
- Introduce a supplier pattern
This change is already covered by existing tests, such as `CompiledPlanITCase`.
=> [FLINK-33447][table-planner] Avoid CompiledPlan recompilation during loading

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/ScalarOperatorsTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/utils/ExpressionTestBase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/utils/ScalarOperatorsTestBase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/MiscITCase.scala
…t for equal and non-equal comparisons for codegen
This closes #23478
1.18 backport for parent PR https://github.com/apache/flink/pull/23478
When executing the following SQL:
```
SELECT
time1,
time1 = '2023-09-30 18:22:42.123' AS eq1,
NOT (time1 = '2023-09-30 18:22:42.123') AS notEq1
FROM table1;
```
the result is as follows:
```
+----+-------------------------+--------+--------+
| op |                   time1 |    eq1 | notEq1 |
+----+-------------------------+--------+--------+
| +I | 2023-09-30 18:22:42.123 |   TRUE |   TRUE |
| +I | 2023-09-30 18:22:42.124 |  FALSE |   TRUE |
+----+-------------------------+--------+--------+
2 rows in set
```
The "notEq1" in the first row should be FALSE.
```
import org.apache.flink.api.common.functions.RichMapFunction;
import …
```
=> [FLINK-33171][table planner] Consistent implicit type coercion support for equal and non-equal comparisons for codegen

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamConfig.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/graph/StreamConfigTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/util/MockStreamConfig.java
This PR is FLINK-33317, it's a subtask of FLINK-33315. See FLINK-33315 and FLINK-33317 for details.
Clean up the StreamConfig#SERIALIZEDUDF after getStreamOperatorFactory.
- Added StreamConfigTest#cleanSerializedUDF
=>  [FLINK-33317][runtime] Add cleaning mechanism for initial configs to reduce the memory usage

flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/TestSinkInitContext.java, flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/sink/writer/FileWriterTest.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/InternalSinkWriterMetricGroup.java, flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/MetricsGroupTestUtils.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/datastream/DataStreamSinkTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/functions/PrintSinkTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SinkTransformationTranslatorITCaseBase.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SinkV1TransformationTranslatorITCase.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SinkV2TransformationTranslatorITCase.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperatorTestBase.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkTestUtil.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkV2CommitterOperatorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkV2SinkWriterOperatorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperatorTestBase.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/TestSink.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/TestSinkV2.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/WithAdapterCommitterOperatorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/WithAdapterSinkWriterOperatorTest.java, flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/SinkV2ITCase.java, flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/SinkV2MetricsITCase.java
Creating direct test for SinkV2
- Created TestSinkV2 which instantiates a SinkV2 directly
- Refactored tests where we want to keep both V1 and V2 test parallel to have a base class:
- SinkTransformationTranslatorITCaseBase
- CommitterOperatorTestBase
- SinkWriterOperatorTestBase
- Created new tests where it did not worth to create the base test case:
- SinkV2ITCase
- SinkV2MetricsITCase
- Moved the new tests to use TestSinkV2 where we do not want duplicated tests:
- DataStreamSinkTest
As a bit unrelated change moved  the `InternalSinkWriterMetricGroup.mock` methods a `MetricsGroupTestUtils` class, so we do not mix test and production code
This is a test change, so the CI will tell if it is correct, or not. …
=> [FLINK-33295] Separate SinkV2 and SinkV1Adapter tests

docs/content/docs/connectors/table/filesystem.md, flink-core/src/main/java/org/apache/flink/api/common/io/FileInputFormat.java, flink-core/src/test/java/org/apache/flink/api/common/io/FileInputFormatTest.java, flink-core/src/test/java/org/apache/flink/testutils/TestFileUtils.java
Support transparent compression for file-connector for all file input formats.
- Force reading the whole file split (like it is done for binary input formats) on compressed (unsplittable) files
- add FileInputFormatTest#testFileInputFormatWithCompressionFromFileSource
- generalize FileInputFormatTest#testFileInputFormatWithCompression to more that deflate format
FileInputFormatTest#testFileInputFormatWithCompressionFromFileSource
- The S3 …
=> [FLINK-33059] Support transparent compression for file-connector for all file input formats

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdModifiedMonotonicity.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdModifiedMonotonicityTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/AggregateITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/table/AggregateITCase.scala
Flink SqlMonotonicity doesn't calculated for Calc/FlinkLogicalCalc/StreamPhysicalCalc that leads of absent correct monotonicity for projects. GroupAggregate, based on the input data about the monotonicity of projections make a choice about the need to retract messages.
Changed logic of calculating SqlMonotonicty for Calc (base class for all Calc's) in class FlinkRelMdModifiedMonotonicity.
org.apache.flink.table.planner.runtime.stream.sql.AggregateITCase#testMinAggRetractWithCondition
org.apache.flink.table.planner.runtime.stream.sql.AggregateITCase#testMaxAggRetractWithCondition
org.apache.flink.table.planner.runtime.stream.table.AggregateITCase#testMinAggRetractWithCondition
org.apache.flink.table.planner.runtime.stream.table.AggregateITCase#testMaxAggRetractWithCondition …
=> [FLINK-33213][table] Flink SQL calculate SqlMonotonicity for Calc.

flink-python/src/main/java/org/apache/flink/client/python/PythonDriver.java
`PythonDriver` now collects the python process output in a `Stringbuilder` instead of streaming it. It can cause OOM when the python process is generating huge amount of output. In this PR I've changed the code not to collect the log but stream it into log line by line.
`PythonDriver` is collecting the python process output line by line and stream it into log.
Manually on local machine. …
=> [FLINK-33515][python] Stream python process output to log instead of collecting it in memory

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserCalcitePlanner.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/copy/HiveParserSemanticAnalyzer.java, flink-connectors/flink-connector-hive/src/test/resources/query-test/udf.q
Use foldExpr config as default to fix NPE problem when use unix_timestamp() in filter condition.
And it is already the default value in hive project.
Change foldExpr config default as true in filter condition
This change is verified by added test
=> [FLINK-33478][hive] Enable foldExpr by default in filter condition

flink-external-resources/flink-external-resource-gpu/src/test/java/org/apache/flink/externalresource/gpu/GPUDriverTest.java
This is a *very* minor change to avoid depending on the value of the `FLINK_HOME` environment variable when discovering the value of the gpu discovery test script (only used while testing).
Before this change, the following error occurs on the command line and IDE if the `FLINK_HOME` is set:
```
java.io.FileNotFoundException: The gpu discovery script does not exist in path /opt/asf/flink/src/test/resources/testing-gpu-discovery.sh.
at org.apache.flink.externalresource.gpu.GPUDriver.<init>(GPUDriver.java:98)
at org.apache.flink.externalresource.gpu.GPUDriverTest.testGPUDriverWithInvalidAmount(GPUDriverTest.java:64)
```
During unit tests, use an absolute path to the modules `src/test/resources` directory instead of a path relative to `FLINK_HOME` (if it exists).
This change is a trivial …
=> [FLINK-33520] Avoid using FLINK_HOME to find test scripts

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/AggregateUtil.scala, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/agg/DistinctAggregateTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/agg/IncrementalAggregateTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/agg/DistinctAggregateTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/SplitAggregateITCase.scala
Currently LISTAGG with splitting original agg to final-partial agg will cause wrong result. This pr is for a quick fix to avoid splitting with it.
- *Avoid splitting LISTAGG when SplitAggregateRule*
- *Add UT and IT*
Some tests are added.
=> [FLINK-33489][table-planner] forbid generating partial-final agg with LISTAGG to avoid wrong result

tools/azure-pipelines/jobs-template.yml, tools/ci/stage.sh
* Merged `connect_2` stage into `connect_1` and renamed it into `connect`
=> [FLINK-33276][ci] Merges connect_1 and connect_2 stages into a single one

.github/workflows/docs.yml, tools/azure-pipelines/build-apache-repo.yml
Based on https://github.com/zentol/flink-ci-docker/tree/3e5789ed4fb5558f364a45315bae752c272f7bd9.
=> [FLINK-18356] Update CI image

flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/agg/DistinctAggregateTest.scala
The PR is aiming to fix build failure 
https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=54581&view=logs&j=52b61abe-a3cc-5bde-cc35-1bbe89bb7df5&t=54421a62-0c80-5aad-3319-094ff69180bb
```
11:58:02.126 [ERROR] /__w/1/s/flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/agg/DistinctAggregateTest.scala:220: error: not found: type Test
11:58:02.126 [ERROR]   @Test
11:58:02.126 [ERROR]    ^
```
=> [hotfix] Add missing import to fix build

pom.xml
Updating the japicmp base version. Verification of API changes happened in FLINK-32927
=> [FLINK-32913][tests] Updates base version for japicmp check

docs/content.zh/docs/ops/upgrading.md, docs/content/docs/ops/upgrading.md
This pull requests updates the snapshot compatibility matrix for release 1.18. 
Please note that in case of 1.18 there is no snapshot compatibility before 1.8 (same as for 1.17), which has been [discussed](https://lists.apache.org/thread/v1q28zg5jhxcqrpq67pyv291nznd3n0w) in the mailing list. 
- Update compatibility matrix for release 1.18
This is a doc-only change. …
=> [FLINK-32922][docs] Update compatibility matrix for release 1.18

docs/content.zh/docs/ops/upgrading.md, docs/content/docs/ops/upgrading.md
This pull requests updates the snapshot compatibility matrix for release 1.18. 
This is the backport of https://github.com/apache/flink/pull/23701
=> [BP-1.18][FLINK-32922][docs] Update compatibility matrix for release 1.18

docs/layouts/shortcodes/generated/akka_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/AkkaOptions.java, flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/pekko/ActorSystemBootstrapTools.java, flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/pekko/PekkoUtils.java, flink-rpc/flink-rpc-akka/src/test/java/org/apache/flink/runtime/rpc/pekko/PekkoUtilsTest.java, flink-runtime/src/main/java/org/apache/flink/runtime/blob/BlobWriter.java, flink-runtime/src/main/java/org/apache/flink/runtime/deployment/CachedShuffleDescriptors.java, flink-runtime/src/main/java/org/apache/flink/runtime/deployment/InputGateDeploymentDescriptor.java, flink-runtime/src/main/java/org/apache/flink/runtime/deployment/TaskDeploymentDescriptor.java, flink-runtime/src/main/java/org/apache/flink/runtime/deployment/TaskDeploymentDescriptorFactory.java, flink-runtime/src/test/java/org/apache/flink/runtime/deployment/CachedShuffleDescriptorsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/deployment/TaskDeploymentDescriptorTestUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateTest.java
- Support configured akka remote dispatcher thread pool size.
- Move the serialization of ShuffleDescriptorGroup out of the RPC main thread
- Add config `akka.remote-fork-join-executor.parallelism-factor`,`akka.remote-fork-join-executor.parallelism-max` and `akka.remote-fork-join-executor.parallelism-min`
- Move the serialization logic of ShuffleDescriptorGroup to akka's default-remote-dispatcher thread instead of the default-dispatcher thread.
- Add `getConfigDefaultsToRemoteForkJoinExecutor` in `PekkoUtilsTest`.
- The tests related to `ShuffleDescriptorGroup` have already been covered by existing tests, such as `TaskDeploymentDescriptorFactoryTest`. …
=> [FLINK-33532][rpc] Support configured akka remote dispatcher thread pool size

docs/layouts/shortcodes/connector_artifact.html, docs/layouts/shortcodes/py_connector_download_link.html, docs/layouts/shortcodes/sql_connector_download_table.html
For all download displays, this performs an additional check if there's a connector release available for that specific Flink release. If not, it will display that there's no connector release yet available for that Flink version.
* Checks if value in connector's `flink_compatibility` exists (See https://github.com/apache/flink-connector-kafka/blob/v3.0/docs/data/kafka.yml#L20 as an example) and if that matches with the Flink main version. If yes, then display the download link. If not, then display a message that there's no connector version yet available
Can be verified locally by building the documentation locally
- The …
=> [FLINK-33567] Only display connector download links if its available

flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/CollectTypeStrategy.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/SpecificTypeStrategies.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/strategies/CollectTypeStrategyTest.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/expressions/PlannerExpressionConverter.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/expressions/aggregations.scala
Implement type inference for `DISTINCT` and `COLLECT`
Added tests for `COLLECT` output type strategy
=> [FLINK-33563] Implement type inference for Agg functions

azure-pipelines.yml, docs/content.zh/docs/flinkDev/building.md, docs/content/docs/flinkDev/building.md, pom.xml, tools/azure-pipelines/build-apache-repo.yml, tools/releasing/create_binary_release.sh, tools/releasing/deploy_staging_jars.sh
We're only relying on Scala 2.12 (and the plan is to drop it entirely for 2.x). The Scala prefix is still present in CI, though. This commit cleans it up entirely. 
This clean up step helps reduce the noise in the GHA workflow change (FLINK-27075). There's no need to label workflows with the scala version. Therefore, we can remove the scala version from the build parameters entirely.
* Removed `scala-2.12` system variable from release scripts and azure workflow
* The nightly deployment should still look the same (related to the `tools/releasing/deploy_staging_jars.sh` change)
* The binary release artifacts shouldn't have changed (related to the `tools/releasing/create_binary_release.sh` change) …
=> [FLINK-33578][ci] Removes scala-2.12 system property

flink-python/dev/dev-requirements.txt, flink-python/pyproject.toml
*This pull request will remove cython upper bounds*
- *remove cython upper bounds*
- *original tests*
=> [FLINK-33531][python] Remove cython upper bounds

flink-filesystems/flink-azure-fs-hadoop/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-gs-fs-hadoop/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE, flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE, flink-formats/flink-sql-avro/src/main/resources/META-INF/NOTICE, flink-kubernetes/src/main/resources/META-INF/NOTICE, flink-python/src/main/resources/META-INF/NOTICE, pom.xml
The PR is to bump jackson to 2.15.3 
pom and NOTICE files
=> [FLINK-33340] Upgrade jackson from 2.14.3 to 2.15.3

flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/SinkV2MetricsITCase.java
Fix the NullpointerException found by the tests: https://issues.apache.org/jira/browse/FLINK-33568?focusedCommentId=17786726&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17786726
Add Null checks
I was not able to repro the case, I think we might have an intermittent issue where the operator is not initialized when we try to fetch the metrics. This could happen when the specific task does not get any committables. …
=> [FLINK-33568] Fix NullpointerException in SinkV2MetricsITCase

pom.xml
The issue with current shade plugin is that it does not support jdk 20, 21
The support was added at 3.5.1 within https://issues.apache.org/jira/browse/MSHADE-454
The PR bumps to that version
pom.xml
=> [FLINK-33456] Upgrade maven-shade-plugin to 3.5.1 to support jdk20+

.github/workflows/docs.yml, tools/azure-pipelines/build-apache-repo.yml
1.18 backport PR for parent PR #23717
I also backport the change for the docs build for the sake of consistency even though it's not necessary to fix FLINK-18356.
CI should pass without problems.
=> [BP-1.18][FLINK-18356] Update CI image

docs/content/docs/connectors/table/formats/avro.md, flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroDeserializationSchema.java, flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroFormatFactory.java, flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroFormatOptions.java, flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroRowDataDeserializationSchema.java, flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroRowDataSerializationSchema.java, flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroSerializationSchema.java, flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/RegistryAvroDeserializationSchema.java, flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/RegistryAvroSerializationSchema.java, flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroDeserializationSchemaTest.java, flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroFormatFactoryTest.java, flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroRowDataDeSerializationSchemaTest.java, flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroSerializationSchemaTest.java, flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/RegistryAvroDeserializationSchemaTest.java, flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/typeutils/AvroSchemaConverterTest.java, flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/utils/AvroTestUtils.java
Initially proposed in https://issues.apache.org/jira/browse/FLINK-33058 
Avro supports two serialization encoding methods: binary and JSON (cf. [Avro docs](https://avro.apache.org/docs/1.11.1/specification/#encodings))
flink-avro currently has a hard-coded assumption that Avro data is binary-encoded (and cannot process Avro data that has been JSON-encoded).
This pull request introduces a new optional format option to flink-avro: `avro.encoding`
It supports two options: 'binary' and 'json'. 
It unset, it will default to 'binary' to maintain compatibility/consistency with current behaviour. 
Flink uses Avro [`Decoder`](https://avro.apache.org/docs/1.8.2/api/java/org/apache/avro/io/Decoder.html) and [`Encoder`](https://avro.apache.org/docs/1.8.2/api/java/org/apache/avro/io/Encoder.html) …
=> [FLINK-33058][formats] Add encoding option to Avro format

pom.xml
Add java21-target profile similar to existing java11 and java17 target profiles
pom.xml
=> [FLINK-33453][build] Add java21-target profile

flink-table/flink-table-planner/src/main/java/org/apache/calcite/sql/fun/SqlRowOperator.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/TableScanTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/TableScanTest.scala
When using row as a computed column and select the computed column as a query, an exception will be thrown by calcite because of the type mismatch about ROW.
The cause is that in Flink, we always treat the ROW as a struct type PEEK_FIELDS_NO_EXPAND (refs to LogicalRelDataTypeConverter and FlinkTypeFactory), but in calcite, the struct type about ROW is FULLY_QUALIFIED (refs to SqlRowOperator#inferReturnType). And when selecting the column, the difference causes this bug.
- *Modify the SqlRowOperator to return the true struct type about ROW*
- *Add tests about this pr*
Necessary tests have been added. …
=> [FLINK-20539][table-planner] fix type mismatch when using ROW in computed column

flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/extensions/retry/RetryTestExecutionExtension.java, flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/RetryOnExceptionExtensionTest.java, flink-test-utils-parent/flink-test-utils-junit/src/test/java/org/apache/flink/testutils/junit/RetryOnFailureExtensionTest.java
This is a minor clean up of the unit tests that check the functionality of `@RetryOnFailure` and `@RetryOnException`.  Currently, executing a single test method will fail; **_all_** unit tests in these two classes need to be executed in order for **_any_** to pass.
- The current strategy is to count the number of times a method was called in a static int variable, and checking that every test was run the expected number of times in an `@AfterAll` verification.
- The new strategy is to count the number of times any test method was called in a single hashmap (using the `@BeforeEach` and `TestInfo` from JUnit5), and verify the counts only if they exist in the `@AfterAll`
- Rename `NUMBER_OF_RUNS` to `NUMBER_OF_RETRIES` which is a bit clearer.
- Additional hotfix: I noticed a missing space …
=> [FLINK-29452] Allow unit tests to be executed independently

flink-runtime/src/test/java/org/apache/flink/runtime/entrypoint/ClusterUncaughtExceptionHandlerITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/disk/FileChannelManagerImplTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/testutils/DispatcherProcess.java, flink-runtime/src/test/java/org/apache/flink/runtime/testutils/TestJvmProcess.java, flink-runtime/src/test/java/org/apache/flink/runtime/testutils/TestingClusterEntrypointProcess.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/BlockingShutdownTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/FlinkSecurityManagerITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/JvmExitOnFatalErrorTest.java
The issue with `TestJvmProccess` is that properties from `surefire.module.config` are putting in a command line after entry point class name and as a result will be ignored that leads to `FlinkSecurityManagerITCase` failure for jdk21 for instance.
The PR moves these properties before the class name
Also there is a separate commit to rename `getJvmArg` to `getMainMethodArgs` since `getJvmArg` could lead to some misunderstandings.
The change is test itself
to reproduce the issue: compile code with java 21 and then execute test FlinkSecurityManagerITCase
without this fix it fails as mentioned in jira
- The runtime …
=> [FLINK-33311] `surefire.module.config` args should be before entry point classname to work with java 21

.mvn/wrapper/maven-wrapper.properties, mvnw, mvnw.cmd
Upgrading Maven Wrapper enables us to do binary checksum verification.
* Upgraded Maven wrapper to 3.2.0
* Added checksum for distribution
* Added checksum for wrapper but commented it out due to [MVRAPPER-103](https://issues.apache.org/jira/browse/MWRAPPER-103) for now (FLINK-33607 covers the fix) …
=> [FLINK-33503][build] Upgrades Maven Wrapper version and integrates checksum verification

flink-table/flink-table-planner/src/main/resources/META-INF/NOTICE, flink-table/pom.xml
=> [FLINK-33624][table] Bump Guava to 32.1.3-jre

flink-runtime/src/test/java/org/apache/flink/runtime/operators/CoGroupTaskTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/CombineTaskExternalITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/ReduceTaskExternalITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/ReduceTaskTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/operators/testutils/DriverTestBase.java
[FLINK-33610][runtime] Fix unstable test CoGroupTaskTest.testCancelCoGroupTaskWhileCoGrouping
https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=54741&view=logs&j=675bf62c-8558-587e-2555-dcad13acefb5&t=5878eed3-cc1e-5b12-1ed0-9e7139ce0992&l=7675
```
java.lang.NullPointerException: Cannot invoke "org.apache.flink.runtime.operators.util.CoGroupTaskIterator.close()" because "this.coGroupIterator" is null
at org.apache.flink.runtime.operators.CoGroupDriver.cleanup(CoGroupDriver.java:185)
at org.apache.flink.runtime.operators.testutils.DriverTestBase.testDriverInternal(DriverTestBase.java:270)
at org.apache.flink.runtime.operators.testutils.DriverTestBase.testDriver(DriverTestBase.java:195)
at org.apache.flink.runtime.operators.CoGroupTaskTest.access$200(CoGroupTaskTest.java …
```
=> [FLINK-33610][runtime] Fix unstable test CoGroupTaskTest.testCancelCoGroupTaskWhileCoGrouping

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/logical/FlinkSubQueryRemoveRule.scala, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/CalcPruneAggregateCallRuleTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/FlinkAggregateRemoveRuleTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/FlinkLimit0RemoveRuleTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/ProjectPruneAggregateCallRuleTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/rules/logical/FlinkAggregateRemoveRuleTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/rules/logical/FlinkLimit0RemoveRuleTest.scala
The idea is to look at metadata rowcount for `EXISTS` subqueries and based on this take a decision whether it could be optimized to `TRUE`/`FALSE`
FlinkSubQueryRemoveRule.java
adopted tests, since optimization changed execution plans
This change is already covered by existing tests, such as 
CalcPruneAggregateCallRuleTest
ProjectPruneAggregateCallRuleTest
FlinkAggregateRemoveRuleTest
FlinkLimit0RemoveRuleTest
ProjectPruneAggregateCallRuleTest …
=> [FLINK-33485][table] Optimize exists subqueries by looking at metadata rowcount

flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionHaServices.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/Fabric8FlinkKubeClient.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/FlinkKubeClient.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/resources/KubernetesConfigMapSharedInformer.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/Constants.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesHighAvailabilityTestBase.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionAndRetrievalITCase.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesTestFixture.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/Fabric8FlinkKubeClientTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/TestingFlinkKubeClient.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/resources/KubernetesSharedInformerITCase.java
As [FLINK-24819](https://issues.apache.org/jira/browse/FLINK-24819) described, the k8s API server would receive more pressure when HA is enabled, due to the configmap watching being achieved via filter with labels instead of just querying the configmap name. This could be done after [FLINK-24038](https://issues.apache.org/jira/browse/FLINK-24038), which reduced the number of configmaps to only one as `<clusterId>-cluster-config-map`.
This PR would not touch `<clusterId>-<jobId>-config-map`, which stores the checkpoint information, as that configmap is directly accessed by JM and not watched by taskmanagers.
- Introduce new API named `FlinkKubeClient#createConfigMapSharedWatcher(String)` and use this API to create watcher.
- Delete useless …
=> [FLINK-33598][k8s] Watch HA configmap via name instead of lables to reduce pressure on APIserver

.github/workflows/docs.yml, tools/azure-pipelines/build-apache-repo.yml
1.17 backport PR for parent PR #23717
I also backport the change for the docs build for the sake of consistency even though it's not necessary to fix FLINK-18356.
This backport required the upgrade of Maven to 3.8.6 (FLINK-28203).
CI should pass without problems and should include the optional check
=> [BP-1.17][FLINK-18356] Update CI image

flink-architecture-tests/flink-architecture-tests-test/src/main/java/org/apache/flink/architecture/rules/BanJunit4Rules.java
[FLINK-33629][test] Introduce ArchTest rules to ban Junit 4 for modules already completed the migration
Currently, many modules have already completed the migration to JUnit 5, and we need to prevent the introduction of JUnit 4 tests in new PRs.
However, completely removing the dependency on JUnit 4 is challenging. It requires defining JUnit 4 as optional in the flink-parent module and allowing sub-modules to selectively include it. However, this approach still cannot solve the issue of transitive dependencies.
Therefore, considering introducing new rules in ArchTest to prohibit the usage of JUnit 4 in modules that have already completed the migration. …
=> [FLINK-33629][test] Introduce ArchTest rules to ban Junit 4 for modules already completed the migration

docs/content/docs/dev/datastream/fault-tolerance/checkpointing.md
The link of externalized checkpoints in `checkpointing.md` is outdated.
Use the correct link instead.
=> [hotfix][doc] fix outdated link of externalized checkpoints

docs/content.zh/docs/deployment/config.md, docs/content.zh/docs/ops/state/task_failure_recovery.md, docs/content/docs/deployment/config.md
Exponential Delay doc is missed in 2 pages:
-  Configuration page missed Exponential Delay related options
-  https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/config/#fault-tolerance
-  EN and zh doc
-  task-failure-recovery missed Exponential Delay
- https://nightlies.apache.org/flink/flink-docs-master/docs/ops/state/task_failure_recovery/#task-failure-recovery
- Only zh version miss
=> [FLINK-33649][doc] Add the doc related to Exponential Delay

flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/connector/upserttest/sink/UpsertTestFileUtil.java, flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/connector/upserttest/table/UpsertTestDynamicTableSink.java, flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/connector/upserttest/table/UpsertTestDynamicTableSinkFactory.java, flink-tests/src/test/java/org/apache/flink/connector/upserttest/table/UpsertTestDynamicTableSinkITCase.java
[FLINK-33608][test-utils] UpsertTestDynamicTableSink's keySerializationSchama should extract and serialize the primary key fields from RowData
```sql
CREATE TABLE UpsertFileSinkTable (
user_id INT,
user_name STRING,
user_count BIGINT,
PRIMARY KEY (user_id) NOT ENFORCED
) WITH (
'connector' = 'upsert-files',
'key.format' = 'json',
'value.format' = 'json',
'output-filepath' = '..'
);
INSERT INTO UpsertFileSinkTable
SELECT user_id, user_name, COUNT(*) AS user_count
FROM (VALUES (1, 'Bob'), (22, 'Tom'), (42, 'Kim'), (42, 'Kim'), (42, 'Kim'), (1, 'Bob'))
AS UserCountTable(user_id, user_name)
GROUP BY user_id, user_name;
```
Results:
| Key | Value |
|:-:|:-:|
| {"user_id":1,"user_name":"Bob","user_count":2} | {"user_id":1,"user_name":"Bob","user_count":2} |
| …
=> [FLINK-33608][test-utils] UpsertTestDynamicTableSink's keySerializationSchama should extract and serialize the primary key fields from RowData

flink-python/pyflink/datastream/functions.py
This is a trivial documentation fix: there is no `Collector` in PyFlink, `yield` has to be used instead.
=> [hotfix][docs] Remove reference to obsolete Collector and refer to yield instead

.github/workflows/docs.yml, azure-pipelines.yml, tools/azure-pipelines/build-apache-repo.yml
Use image with jdk21 from 
https://github.com/zentol/flink-ci-docker/pull/2#issuecomment-1825532069
`.github/workflows/docs.yml`
`tools/azure-pipelines/build-apache-repo.yml`
`azure-pipelines.yml`
=> [FLINK-33642] Use docker image with jdk21 in CI

docs/content.zh/docs/dev/table/functions/udfs.md, docs/content.zh/docs/dev/table/tableApi.md, docs/content/docs/dev/table/tableApi.md, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/AggregatedTable.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/FlatAggregateTable.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/GroupedTable.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/harness/TableAggregateHarnessTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/AggregateITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/GroupWindowITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/MatchRecognizeITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/OverAggregateITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/utils/UserDefinedFunctionTestUtils.scala
This is the follow up task for https://github.com/apache/flink/pull/23751 to finish it in java/scala code and docs
=> [FLINK-33646][table] Cleanup the rest usage of deprecated TableEnvironment#registerFunction and in docs

README.md
Add the externalized connector repos into the doc to ease developer find the related connectors.
This change is a trivial doc update.
=> [hotfix][doc] add repo links of externalized connectors

docs/content.zh/docs/ops/state/checkpoints.md, docs/content/docs/ops/state/checkpoints.md
- [FLINK-33650][doc] Remove manage memory part in FileSystemCheckpointStorage due to it can be used for rocksdb state backend.
- [FLINK-33650][doc] Add the Checkpoint Storage part for Chinese Checkpoint page
=> [FLINK-33650][doc] Add the Checkpoint Storage part for Chinese Checkpoint page

docs/content.zh/docs/dev/table/functions/udfs.md, docs/content/docs/dev/table/functions/udfs.md
add hint to suggest using UserDefinedFunction class over instance
=> [hotfix][table][doc] add hint to suggest using UserDefinedFunction class over instance

flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/container/FlinkImageBuilder.java
The PR allows to pass `FlinkImageBuilder` to proceed with e2e tests
=> [FLINK-33457][tests] FlinkImageBuilder checks for Java 21

flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliTableauResultViewTest.java
remove duplicated code according the clean code concept.
=> [hotfix][table][test] remove duplicated code

flink-core/archunit-violations/0c7796e9-15d6-4c0d-9fe3-3846e1b5347c, flink-core/archunit-violations/stored.rules, flink-core/pom.xml, flink-core/src/test/java/org/apache/flink/architecture/TestCodeArchitectureTest.java, flink-core/src/test/resources/archunit.properties
add archunit tests for the test code of flink-core
This change adds archunit tests without any test coverage.
=> [FLINK-26013][flink-core][test] add archunit tests for the test code

pom.xml
The minimum ArchUnit supporting java 21 is 1.1.0 so need to bump ArchUnit to support java 21
to reproduce the problem (run with java 21)
```
mvn clean install -DskipTests -Dfast -Pjava21-target
mvn verify -pl flink-architecture-tests/flink-architecture-tests-production/ -Darchunit.freeze.store.default.allowStoreUpdate=false
```
same commands could be used to check that fix is working
- The S3 …
=> [FLINK-33655][tests] Upgrade ArchUnit to 1.2.0 to support java 21

flink-end-to-end-tests/flink-end-to-end-tests-hive/src/test/java/org/apache/flink/tests/hive/containers/HiveContainers.java, flink-end-to-end-tests/flink-sql-gateway-test/src/test/java/org/apache/flink/table/gateway/containers/HiveContainer.java
The experiments on Github actions (FLINK-27075) revealed that the e2e tests that use `HiveContainer` would fail on Github Runners. Using `getHost()` instead to access the container works.
* Utilize `getHost()` instead of `127.0.0.1` to access the container
* The two tests started to succeed in Github Actions
* [Github Action Run](https://github.com/XComp/flink/actions/runs/6727253349/job/18285012233#step:15:13613) with `HiveITCase` failure 
* [Github Action Run](https://github.com/XComp/flink/actions/runs/6719526710/job/18261920525#step:15:11508) with `SqlGatewayE2ECase` failure
* [Github Action Run](https://github.com/XComp/flink/actions/runs/6729006580/job/18289544587) with fix [45f4473](https://github.com/XComp/flink/commit/45f4473408a88bb1a36458f13662ea3623af0410)
* The tests should …
=> [FLINK-33418][test,ci] Uses getHost() to access HiveContainer (instead of hard-coded IP)

flink-end-to-end-tests/flink-end-to-end-tests-hive/src/test/java/org/apache/flink/tests/hive/containers/HiveContainers.java, flink-end-to-end-tests/flink-sql-gateway-test/src/test/java/org/apache/flink/table/gateway/containers/HiveContainer.java
1.18 backport for parent PR #23649
=> [BP-1.18][FLINK-33418][test] Uses getHost()

flink-end-to-end-tests/test-scripts/common_docker.sh, tools/azure-pipelines/build-apache-repo.yml, tools/ci/compile.sh
The PR enables cron build for java 21
I've also scheduled build for commits from this PR + with forced `java21-target` commit 
on my azure pipeline
https://dev.azure.com/snuyanzin/flink/_build/results?buildId=2624&view=results
=> [FLINK-33664][ci] Setup cron build for java 21

flink-connectors/flink-connector-hive/archunit-violations/26d337fc-45c4-4d03-a84a-6692c37fafbc, flink-formats/flink-avro/archunit-violations/337c411e-1885-4f85-8070-aabe3638eb43, flink-formats/flink-json/archunit-violations/62c5e4e5-2b0e-41ed-a268-ee33d5edd162, flink-formats/flink-orc/archunit-violations/8a4ac4b1-94ba-4a1d-a639-b2bd22868374, flink-formats/flink-parquet/archunit-violations/1b8e145e-3f0a-4415-b463-37a87dd0a998, flink-table/flink-table-planner/archunit-violations/stored.rules, flink-table/flink-table-planner/pom.xml, flink-table/flink-table-planner/src/test/java/org/apache/flink/architecture/TestCodeArchitectureTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/catalog/CatalogITCase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/BuiltInAggregateFunctionTestBase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/BuiltInFunctionTestBase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/batch/sql/MatchRecognizeITCase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/utils/AtomicCtasITCaseBase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/utils/AtomicRtasITCaseBase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/utils/JoinReorderITCaseBase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/utils/StreamAbstractTestBase.java, flink-table/flink-table-planner/src/test/resources/archunit.properties, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/utils/StreamingTestBase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/utils/StreamingWithStateTestBase.scala
[FLINK-33637][table-planner][JUnit5 Migration] Introduce ArchTest to ban Junit 4 for module table-planner
Currently, table-planner have already completed the migration to JUnit 5, and we need to prevent the introduction of JUnit 4 tests in new PRs. …
=> [FLINK-33637][table-planner][JUnit5 Migration] Introduce ArchTest to ban Junit 4 for module table-planner

docs/content.zh/docs/deployment/cli.md, docs/content/docs/deployment/cli.md, flink-clients/src/main/java/org/apache/flink/client/cli/CheckpointOptions.java, flink-clients/src/main/java/org/apache/flink/client/cli/CliFrontend.java, flink-clients/src/main/java/org/apache/flink/client/cli/CliFrontendParser.java, flink-clients/src/main/java/org/apache/flink/client/program/ClusterClient.java, flink-clients/src/main/java/org/apache/flink/client/program/MiniClusterClient.java, flink-clients/src/main/java/org/apache/flink/client/program/rest/RestClusterClient.java, flink-clients/src/test/java/org/apache/flink/client/cli/CliFrontendCheckpointTest.java, flink-clients/src/test/java/org/apache/flink/client/program/TestingClusterClient.java, flink-clients/src/test/java/org/apache/flink/client/program/rest/RestClusterClientCheckpointTriggerTest.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/DispatcherGateway.java, flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniCluster.java, flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/TestingDispatcherGateway.java, flink-tests/src/test/java/org/apache/flink/test/streaming/api/environment/RemoteStreamEnvironmentTest.java
Since FLINK-24280, we have supported manual checkpoint triggering from REST API. This PR wire command-line interface and rest endpoint, supporting manual checkpoints triggering from CLI.
- Add an action "checkpoint" in CLI, and related parameters parsing logic.
- Wire this action with rest endpoint.
- Documentation about this feature.
- Unit tests for newly added checkpoint cli action
- Manually verified triggering checkpoint using command line interface on sample wordcout job deployed on a yarn cluster. …
=> [FLINK-6755][CLI] Support manual checkpoints triggering

flink-formats/flink-avro-confluent-registry/pom.xml, flink-formats/flink-avro/pom.xml, flink-formats/flink-compress/pom.xml, flink-formats/flink-csv/pom.xml, flink-formats/flink-hadoop-bulk/pom.xml, flink-formats/flink-json/pom.xml, flink-formats/flink-orc-nohive/pom.xml, flink-formats/flink-orc/pom.xml, flink-formats/flink-parquet/pom.xml, flink-formats/flink-sequence-file/pom.xml
fix typo in the pom files for ArchUnit
This change is a trivial typo fix without any test coverage.
=> [hotfix] typo in the pom files of flink-format modules for archunit

flink-table/flink-table-common/src/main/java/org/apache/flink/table/expressions/ValueLiteralExpression.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/expressions/LiteralExpressionsSerializationITCase.java
This makes Expressions literals serialisable into SQL.
Added a test for all literals in `LiteralExpressionsSerialisationITCase` …
=> [FLINK-33675] Serialize ValueLiteralExpressions into SQL

docs/content.zh/docs/deployment/filesystems/gcs.md, docs/content/docs/deployment/filesystems/gcs.md, flink-filesystems/flink-gs-fs-hadoop/pom.xml, flink-filesystems/flink-gs-fs-hadoop/src/main/resources/META-INF/NOTICE
* Update GCS dependencies for filesystem to the latest versions
* Update POM files
* Update NOTICE files
* Moved one transitive dependency so that its consistent throughout the Flink codebase
=> [FLINK-33704][Filesytems] Update GCS filesystems to latest available versions

flink-core/src/main/java/org/apache/flink/util/concurrent/IncrementalDelayRetryStrategy.java, flink-core/src/test/java/org/apache/flink/util/concurrent/ExponentialBackoffRetryStrategyTest.java, flink-core/src/test/java/org/apache/flink/util/concurrent/FixedRetryStrategyTest.java, flink-core/src/test/java/org/apache/flink/util/concurrent/IncrementalDelayRetryStrategyTest.java
RetryStrategy now supports FixedRetryStrategy and ExponentialBackoffRetryStrategy. 
In certain scenarios, we also need IncrementalDelayRetryStrategy to reduce the retry count and perform the action more timely. 
- Add the `IncrementalDelayRetryStrategy` implementation of `RetryStrategy`
- `IncrementalDelayRetryStrategy` will increase the retry delay at a fixed rate for each attempt
- Added unit test `IncrementalDelayRetryStrategyTest` …
=> [FLINK-33702][core] Add the IncrementalDelayRetryStrategy implementation of RetryStrategy

flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/expressions/ExpressionSerializationTest.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/expressions/CallExpression.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/expressions/FieldReferenceExpression.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/expressions/TypeLiteralExpression.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinition.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/CallSyntaxUtils.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/JsonFunctionsCallSyntax.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/SqlCallSyntax.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/BuiltInAggregateFunctionTestBase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/BuiltInFunctionTestBase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/IfThenElseFunctionITCase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/JsonAggregationFunctionsITCase.java
This PR adds a `CallSyntax` as described in the FLIP and implementations for specific non standard builtin functions.
* adds CallSyntax interface and changes in BuiltinFunctionDefinitions
* implements call syntax for functions in BuiltinFunctionDefinitions
Added tests in org.apache.flink.table.expressions.ExpressionSerializationTest
- The S3 …
=> [FLINK-33663] Serialize CallExpressions into SQL

docs/content.zh/docs/dev/datastream/overview.md, docs/content/docs/dev/datastream/overview.md, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/DataStreamTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/TypeFillTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironmentTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SlotAllocationTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/graph/StreamGraphCoLocationConstraintTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/graph/TranslationTest.java, flink-streaming-scala/src/test/scala/org/apache/flink/streaming/api/scala/BroadcastStateITCase.scala, flink-streaming-scala/src/test/scala/org/apache/flink/streaming/api/scala/DataStreamTest.scala, flink-streaming-scala/src/test/scala/org/apache/flink/streaming/api/scala/SlotAllocationTest.scala, flink-streaming-scala/src/test/scala/org/apache/flink/streaming/api/scala/StateTestPrograms.scala, flink-tests/src/test/java/org/apache/flink/test/streaming/api/environment/LocalStreamEnvironmentITCase.java, flink-tests/src/test/java/org/apache/flink/test/streaming/experimental/CollectITCase.java, flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/BroadcastStateITCase.java
The PR to replace usages of `StreamExecutionEnvironment#generateSequence` with `StreamExecutionEnvironment#fromSequence` as mentioned in javadoc
=> [FLINK-33755] Cleanup usage of deprecated StreamExecutionEnvironment#generateSequence

docs/setup_docs.sh
- Update docs for AWS connector to point at v4.2 for Flink 1.17
- Update docs for AWS connector to point at v4.2
=> [docs][hotfix] Update AWS connector docs to v4.2 (Flink 1.17)

docs/setup_docs.sh
- Update docs for AWS connector to point at v4.2 for Flink 1.18
- Update docs for AWS connector to point at v4.2
=> [docs][hotfix] Update AWS connector docs to v4.2 (Flink 1.18)

docs/setup_docs.sh
- Update docs for AWS connector to point at v4.2 for Flink 1.19
- Update docs for AWS connector to point at v4.2
=> [docs][hotfix] Update AWS connector docs to v4.2 (Flink 1.19)

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/physical/batch/PushLocalAggIntoScanRuleBase.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/physical/batch/PushLocalHashAggIntoScanRule.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/physical/batch/PushLocalHashAggWithCalcIntoScanRule.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/physical/batch/PushLocalSortAggIntoScanRule.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/physical/batch/PushLocalSortAggWithCalcIntoScanRule.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/physical/batch/PushLocalSortAggWithSortAndCalcIntoScanRule.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/physical/batch/PushLocalSortAggWithSortIntoScanRule.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/rules/physical/batch/PushLocalAggIntoTableSourceScanRuleTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/batch/sql/agg/LocalAggregatePushDownITCase.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/agg/HashAggregateTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/agg/SortAggregateTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/physical/batch/PushLocalAggIntoTableSourceScanRuleTest.xml
This pr is aims to support agg push down for 'count(*)/count(1)/count(column not null)', like sql : `select count(*) from sourceTable`. 
Now,  PushLocalAggIntoScanRule cannot push down 'count( * )/count(1)/count(column not null)', but it can push down count(column nullable). The reason is that count( * ) and count( 1 ) will be optimized to a scan with calc as '0 AS $f0' to reduce read cost, which will not match the push down rule.
-  Support agg push down for 'count(*)/count(1)/count(column not null)'
- Add tests
This change is a trivial rework / …
=> [FLINK-33691] Support agg push down for 'count(*)/count(1)/count(column not null)'

docs/content.zh/docs/connectors/table/formats/parquet.md, docs/content/docs/connectors/table/formats/parquet.md, flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/ParquetFileFormatFactory.java, flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/ParquetVectorizedInputFormat.java, flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/row/ParquetRowDataBuilder.java, flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/row/ParquetRowDataWriter.java, flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/utils/ParquetSchemaConverter.java, flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/ParquetDictionary.java, flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/ParquetSplitReaderUtil.java, flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/reader/AbstractColumnReader.java, flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/reader/TimestampColumnReader.java, flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/ParquetTimestampITCase.java, flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/row/ParquetRowDataWriterTest.java, flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/vector/ParquetInt64TimestampReaderTest.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/FsStreamingSinkITCaseBase.scala
=> [FLINK-25565][Formats][Parquet] write and read parquet int64 timestamp

flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliTableauResultView.java, flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliTableauResultViewTest.java, flink-table/flink-sql-client/src/test/resources/sql/set.q
print time cost for streaming queries
New test cases have been added and are covered by CliTableauResultViewTest.
=> [FLINK-33726][sql-client] print time cost for streaming queries

flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/RecordWriterOutput.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/RecordWriterOutputTest.java
FLINK-21945 will convert the unaligned checkpoint barrier and timeoutable aligned checkpoint barrier to force aligned barrier. However, Force aligned barrier logic doesn't work for  timeoutable aligned checkpoint barrier.
Bug at org.apache.flink.streaming.runtime.io.RecordWriterOutput#broadcastEvent, we will call withUnalignedUnsupported to convert the unaligned checkpoint barrier to FORCED_ALIGNED barrier when the supportsUnalignedCheckpoints is false.
However, the if has one condition: isPriorityEvent. When  aligned checkpoint timeout is enabled, flink will emit one timeoutable barrier. It isn't PriorityEvent.
[FLINK-33693][checkpoint] Force aligned barrier works with timeoutable aligned checkpoint barrier
- Remove the condition: isPriorityEvent
This change added tests and can be …
=> [FLINK-33693][checkpoint] Force aligned barrier works with timeoutable aligned checkpoint barrier

flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/CollectionDataType.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/DataTypeTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CastFunctionITCase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/FunctionITCase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/table/ValuesITCase.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/data/DataStructureConvertersTest.java, flink-table/flink-table-test-utils/src/test/java/org/apache/flink/table/test/TableAssertionTest.java
This reverts https://github.com/apache/flink/pull/22485 as discussed in https://lists.apache.org/thread/m4c879y8mb7hbn2kkjh9h3d8g1jphh3j
The reversion for `release-1.18` can be found at https://github.com/apache/flink/pull/23891
* Revert FLINK-31835 to resolve FLINK-33523
* This reverts commit a6adbdda …
=> [FLINK-33523][table-planner] Revert [FLINK-31835] Fix the array type that can't be converted from the external primitive array

flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/CollectionDataType.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/DataTypeTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CastFunctionITCase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/FunctionITCase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/table/ValuesITCase.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/data/DataStructureConvertersTest.java, flink-table/flink-table-test-utils/src/test/java/org/apache/flink/table/test/TableAssertionTest.java
This reverts commit a6adbdda0cdf90635f0cd7a3427486bced301fbd.
This is the unchanged reversion of https://github.com/apache/flink/pull/22485/files - The equivalent for `master` can be found at https://github.com/apache/flink/pull/23890
=> [FLINK-33523][BP 1.18][table-planner] Revert [FLINK-31835] Fix the array type that can't be converted from the external primitive array

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/processor/utils/InputPriorityConflictResolver.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/utils/StreamExchangeModeUtils.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/batch/BatchPhysicalExchange.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/processor/utils/InputPriorityConflictResolverTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/optimize/ShuffleModePlanOptimizeTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/utils/StreamExchangeModeUtilsTest.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/optimize/ShuffleModePlanOptimizeTest.xml
*To enhance the performance of hybrid shuffle, it is imperative to address the inconsistency between hybrid shuffle mode and blocking shuffle mode in certain query plans of TPC-DS (such as q88.sql, q14a.sql, q14b.sql, etc).
In hybrid shuffle mode, these plans introduce additional blocking shuffle edges and result in increased shuffle times, potentially impacting overall efficiency.*
- *Hybrid shuffle mode avoids unnecessary blocking edges in the plan*
- *StreamExchangeModeUtilsTest and InputPriorityConflictResolverTest* …
=> [FLINK-33612][table-planner] Hybrid shuffle mode avoids unnecessary blocking edges in the plan

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/over/ProcTimeRangeBoundedPrecedingFunction.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/over/RowTimeRangeBoundedPrecedingFunction.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/over/RowTimeRowsBoundedPrecedingFunction.java
This PR replaces any combination of key iteration and getting the value for iterated key from MapState with a entry iteration followed by getKey() and getValue() of iterated entry. This could save the overhead of get() in MapState.
Equivalent transformation of code in package ```org.apache.flink.table.runtime.operators.over```.
This change is a trivial rework without any new test coverage.  …
=> [FLINK-33672] Use MapState.entries() instead of keys() and get() in over window

flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/JsonRowDeserializationSchemaTest.java, flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/JsonRowSerializationSchemaTest.java
When reading the code about json format, I found the test classes `JsonRowDeserializationSchemaTest` and `JsonRowSerializationSchemaTest` are missed to migrate to junit5.
- Does …
=> [hotfix][test] Migrate JsonRowDeserializationSchemaTest/JsonRowSerializationSchemaTest to Junit5 and Assertj

docs/content/docs/connectors/table/formats/parquet.md
Corrects error from https://github.com/apache/flink/pull/23900
=> [hotfix][docs] config key for parquet int64 option

docs/content/docs/ops/upgrading.md
update the Flink upgrade savepoint compatibility table doc to only include the current and previous releases according to the [Flink Update Policy for old releases ](https://flink.apache.org/downloads/#update-policy-for-old-releases)
- remove all `created with` versions older than 1.7
- remove all `Resumed with` versions older than 1.17
Current change only focus on the [English version](https://github.com/apache/flink/blob/master/docs/content/docs/ops/upgrading.md#compatibility-table). Once there is no objections of the modification, the change will be copied to the [Chinese version](https://github.com/apache/flink/blob/master/docs/content.zh/docs/ops/upgrading.md#compatibility-table).
This change is a trivial doc cleanup without any test coverage. …
=> [FLINK-33730][doc] update the Flink upgrade savepoint compatibility table doc

flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/table/DataGeneratorConnectorITCase.java
*Replace the usage of deprecated org.apache.flink.table.api.TableConfig#ctor()
with getDefault() *
*(or)*
*(or)*
This change added tests and can be verified as …
=> [FLINK-33781][table] Cleanup usage of deprecated TableConfig#ctor

flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/utils/StreamingWithStateTestBase.scala
The PR is to fix the ci by applying spotless
https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=55512&view=logs&j=52b61abe-a3cc-5bde-cc35-1bbe89bb7df5&t=54421a62-0c80-5aad-3319-094ff69180bb&l=11568
https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=55513&view=logs&j=52b61abe-a3cc-5bde-cc35-1bbe89bb7df5&t=54421a62-0c80-5aad-3319-094ff69180bb&l=11568
=> [hotfix] Apply spotless

docs/content.zh/docs/ops/state/task_failure_recovery.md, docs/content/docs/ops/state/task_failure_recovery.md, docs/layouts/shortcodes/generated/exponential_delay_restart_strategy_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/RestartStrategyOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/failover/ExponentialDelayRestartBackoffTimeStrategy.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/failover/RestartBackoffTimeStrategyFactoryLoader.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/failover/ExponentialDelayRestartBackoffTimeStrategyTest.java
See [FLIP-364: Improve the exponential-delay restart-strategy](https://cwiki.apache.org/confluence/x/uJqzDw) . This PR  includes the subtask2 of FLIP-364.
- [FLINK-32895][Scheduler][hotfix] Generate latest strategy string for ExponentialDelayRestartBackoffTimeStrategy due to some information will be updated, such as: `currentBackoffMS` and `lastFailureTimestamp`
- [FLINK-32895][Scheduler] Introduce the max attempts for Exponential Delay Restart Strategy
- Add the option: `restart-strategy.exponential-delay.attempts-before-reset-backoff`
- [FLINK-32895][Scheduler][refactor] Remove some unused throws
- Improve some tests in `ExponentialDelayRestartBackoffTimeStrategyTest`.
- Change the `testAlwaysRestart` to `testMaxAttempts` in `ExponentialDelayRestartBackoffTimeStrategyTest`.
- …
=> [FLINK-32895][Scheduler] Introduce the max attempts for Exponential Delay Restart Strategy

docs/content/docs/ops/upgrading.md
This PR update the ops doc to add the migration periods for deprecated APIs, which are specified in [FLIP-321](https://cwiki.apache.org/confluence/display/FLINK/FLIP-321%3A+Introduce+an+API+deprecation+process).
See the title.
Build the docs and check the website locally at the following address:
http://localhost:1313/docs/ops/upgrading/#deprecated-api-migration-period …
=> [FLIP-321] Update the docs to add migration periods for deprecated APIs.

flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/DeclarativeSlotPoolBridgePreferredAllocationsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/DeclarativeSlotPoolBridgeRequestCompletionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/DeclarativeSlotPoolBridgeResourceDeclarationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/DeclarativeSlotPoolBridgeTest.java
[FLINK-33853][runtime][JUnit5 Migration] Migrate Junit5 for DeclarativeSlotPoolBridge test classes of runtime module
- DeclarativeSlotPoolBridgeRequestCompletionTest
- DeclarativeSlotPoolBridgeResourceDeclarationTest
- DeclarativeSlotPoolBridgePreferredAllocationsTest
- DeclarativeSlotPoolBridgeTest
N.A …
=> [FLINK-33853][runtime][JUnit5 Migration] Migrate Junit5 for DeclarativeSlotPoolBridge test classes of runtime module

flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/utils/StreamingWithStateTestBase.scala, pom.xml
Bump junit to 5.10.1
This could improve error output for https://github.com/apache/flink/pull/23914#pullrequestreview-1777970575
since it was improved on JUnit level at https://github.com/junit-team/junit5/pull/3249/files#diff-722173375ef777095d4d3ba36f4e5063f25c21f23701ad4cbd470018c2888fa8
https://github.com/junit-team/junit5/issues/3236 …
=> [FLINK-33807] Update JUnit to 5.10.1

docs/content.zh/docs/deployment/filesystems/gcs.md, docs/content/docs/deployment/filesystems/gcs.md, flink-filesystems/flink-gs-fs-hadoop/pom.xml, flink-filesystems/flink-gs-fs-hadoop/src/main/resources/META-INF/NOTICE
Unchanged backport of https://github.com/apache/flink/pull/23837
Verified locally with `mvn clean package -DskipTests -Pfast -Pskip-webui-build -U -T4`, changing `flink-conf.yaml` to include:
```
state.backend.type: rocksdb
state.checkpoints.dir: gs://mvisser-flink-gcs-test/flink-snapshots
state.backend.incremental: true
```
And then run a job on this cluster
=> [FLINK-33704][BP 1.18][Filesytems] Update GCS filesystems to latest available versions

flink-runtime/src/main/java/org/apache/flink/runtime/metrics/DescriptiveStatisticsHistogramStatistics.java
Fix NullArgumentException of getQuantile method in DescriptiveStatisticsHistogramStatistics
This DescriptiveStatisticsHistogramStatistics class has added null initialization
1、DescriptiveStatisticsHistogramStatistics.java
During the verification process, the task was submitted to Yarn and run in Yarn cluster mode. After multiple stops and restarts, it was found that the NullArgumentException exception had disappeared. This fully verified the correctness of the modification, improved the stability of program operation, and also improved the accuracy of displaying statistical information in the web UI interface of the Flink task (as shown in the above figure).
The highlighted log section in the above figure is the log I printed to assist in troubleshooting, which can be ignored.
- …
=> [FLINK-33588][Flink-Runtime] Fix NullArgumentException of getQuantile method in DescriptiveStatisticsHistogramStatistics

docs/layouts/shortcodes/generated/all_taskmanager_section.html, docs/layouts/shortcodes/generated/common_host_port_section.html, docs/layouts/shortcodes/generated/task_manager_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/TaskManagerOptions.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectSinkFunction.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/collect/CollectSinkFunctionTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/collect/utils/CollectSinkFunctionTestWrapper.java
CollectSinkFunction$ServerThread uses configured port 
- Add new TaskManagerOptions#COLLECT_PORT
- CollectSinkFunction$ServerThread uses the port configured in TaskManagerOptions#COLLECT_PORT
- upgrade test to JUnit 5 and AssertJ
- Add new test
New test has been created in existing test `CollectSinkFunctionTest`. …
=> [FLINK-32949][core]collect tm port binding with TaskManagerOptions

flink-python/dev/dev-requirements.txt, flink-python/pyproject.toml
This is a cherry pick backport of https://github.com/apache/flink/pull/23755 to 1.18
=> [BP-1.18][FLINK-33531][python] Remove cython upper bounds

flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/AbstractByteBufTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/BufferBuilderAndConsumerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/BufferBuilderTestUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/BufferCompressionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/BufferConsumerWithPartialRecordLengthTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/BufferPoolFactoryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPoolDestroyTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPoolTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/NetworkBufferPoolTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/NetworkBufferTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/ReadOnlySlicedBufferTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PipelinedApproximateSubpartitionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/ResultPartitionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskCancelAsyncProducerConsumerITCase.java
[FLINK-32850][flink-runtime][JUnit5 Migration] The io.network.buffer package of flink-runtime module
[FLINK-32850][flink-runtime][JUnit5 Migration] The io.network.buffer package of flink-runtime module
=> [FLINK-32850][flink-runtime][JUnit5 Migration] The io.network.buffer package of flink-runtime module

flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/TableTestBase.scala
[FLINK-33876][table-planner][JUnit5 Migration] Introduce methodName method in TableTestBase
After completing the JUnit5 migration in the table planner, there is an incompatibility issue with JUnit TestName and TestInfo. Therefore, considering introducing the methodName method in TableTestBase. External connectors's TablePlanTest can override this method when performing JUnit 5 migration for TableTestBase to avoid compilation issues. …
=> [FLINK-33876][table-planner][JUnit5 Migration] Introduce methodName method in TableTestBase

flink-runtime/src/main/java/org/apache/flink/runtime/metrics/DescriptiveStatisticsHistogramStatistics.java
=> [BP-1.18][FLINK-33588]Fix NullArgumentException of getQuantile method in DescriptiveStatisticsHistogramStatistics

flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/legacy/utils/ArchivedExecutionGraphBuilder.java
* We fix the bug where checkpoint history does not show for completed jobs.
Backport of https://github.com/apache/flink/pull/23949
* If job is not found when retrieving checkpoint stats snapshot, we first check the execution graph store, before throwing exception.
* Add unit tests for:
* Retrieving checkpoint statistics for completed job
* Retrieving checkpoint statistics for non-existent job (verify exception is thrown)
- Added unit test to verify checkpoint statistics can be retrieved for FAILED job.
- Added unit test to verify non-existent job still throws `FlinkJobNotFoundException`
- Manually verified by spinning up local cluster.
Running job with checkpoint details:
Cancelled job with checkpoint details: …
=> [FLINK-33872] Retrieve checkpoint history for jobs in completed state

flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/collect/CollectSinkFunctionTest.java
[FLINK-33877][streaming] Fix unstable test of CollectSinkFunctionTest.testConfiguredPortIsUsed
https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=55646&view=logs&j=0da23115-68bb-5dcd-192c-bd4c8adebde1&t=24c3384f-1bcb-57b3-224f-51bf973bbee8&l=9482
```
Dec 18 17:49:57 17:49:57.241 [ERROR] org.apache.flink.streaming.api.operators.collect.CollectSinkFunctionTest.testConfiguredPortIsUsed -- Time elapsed: 0.021 s <<< ERROR!
Dec 18 17:49:57 java.net.BindException: Address already in use (Bind failed)
Dec 18 17:49:57 	at java.net.PlainSocketImpl.socketBind(Native Method)
Dec 18 17:49:57 	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
Dec 18 17:49:57 	at java.net.ServerSocket.bind(ServerSocket.java:390)
Dec 18 17:49:57 	at …
```
=> [FLINK-33877][streaming] Fix unstable test of CollectSinkFunctionTest.testConfiguredPortIsUsed

flink-runtime/src/main/java/org/apache/flink/runtime/state/OperatorStateRestoreOperation.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/OperatorStateRestoreOperationTest.java
This PR fixes an issue related to restoring multiple operator states with broadcast states when snapshot compression is enabled. see: https://issues.apache.org/jira/browse/FLINK-33863
- sort the operator states by offsets before restoring.
Added new test
- Anything that affects deployment or recovery: yes
=> [FLINK-33863][checkpoint] Fix restoring compressed operator state

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlNodeConvertUtils.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlDdlToOperationConverterTest.java
Many databases also throw exception while the column names in view conflicts when creating view, e.g. mysql, postgres. We should follow this behavior in Flink. For more details, please refer this jira(https://issues.apache.org/jira/browse/FLINK-33490)
- *validate the duplicated column name while creating view*
- *add tests*
The tests are added.
- If yes, …
=> [FLINK-33490][table-planner] Validate the column name conflicts in view when creating view

flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/collect/CollectSinkFunctionTest.java
[FLINK-33877][streaming] Adjusting CollectSinkFunctionTest.testConfiguredPortIsUsed's assertion message to work with JDK 17 & 21
https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=55700&view=logs&j=675bf62c-8558-587e-2555-dcad13acefb5&t=5878eed3-cc1e-5b12-1ed0-9e7139ce0992&l=9924
```
Dec 20 04:05:36 [Any cause is instance of class 'class java.net.BindException' and contains message 'Address already in use (Bind failed)'] 
Dec 20 04:05:36 Expecting any element of:
Dec 20 04:05:36   [java.net.BindException: Address already in use
Dec 20 04:05:36 	at java.base/sun.nio.ch.Net.bind0(Native Method)
Dec 20 04:05:36 	at java.base/sun.nio.ch.Net.bind(Net.java:555)
Dec 20 04:05:36 	at java.base/sun.nio.ch.Net.bind(Net.java:544)
Dec 20 04:05:36 	...(71 remaining lines not …
```
=> [FLINK-33877][streaming] Adjusting CollectSinkFunctionTest.testConfiguredPortIsUsed's assertion message to work with JDK 17 & 21

flink-end-to-end-tests/test-scripts/common_ssl.sh
See context of this change in FLINK-33902.
* Utilizes `-legacy` parameter to support OpenSSL 3.0.0+
Azure CI should still not cause any errors. The GitHub Actions workflow part was tested in the context of FLINK-33550. …
=> [FLINK-33902][ci] Adds -legacy to openssl command

flink-core/src/test/java/org/apache/flink/core/fs/local/LocalFileSystemTest.java, flink-core/src/test/java/org/apache/flink/util/FileUtilsTest.java, flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/handlers/JarDeleteHandlerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobCacheDeleteTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobCacheGetTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobCachePutTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobServerDeleteTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobServerGetTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobServerPutTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobUtilsNonWritableTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/execution/librarycache/BlobLibraryCacheManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/RestServerEndpointTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStateOutputStreamTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskManagerRunnerStartupTest.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateBackendConfigTest.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/FileCatalogStoreTest.java, flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/FailsInGHAContainerWithRootUser.java, flink-tests/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTriggerSavepointITCase.java, pom.xml
See FLINK-27082 and FLINK-33903 for context
* Disables/Ignores tests that rely on setting the file permissions to see that if the permissions are not granted will trigger error handling
Tests are disabled. No issue is expected. …
=> [FLINK-27082][ci] Disables tests that relies on disabling file permissions

flink-core/src/test/java/org/apache/flink/core/fs/local/LocalFileSystemTest.java, flink-core/src/test/java/org/apache/flink/util/FileUtilsTest.java, flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/handlers/JarDeleteHandlerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobCacheDeleteTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobCacheGetTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobCachePutTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobServerDeleteTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobServerGetTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobServerPutTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobUtilsNonWritableTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/execution/librarycache/BlobLibraryCacheManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/RestServerEndpointTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStateOutputStreamTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskManagerRunnerStartupTest.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateBackendConfigTest.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/FileCatalogStoreTest.java, flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/junit/FailsInGHAContainerWithRootUser.java, flink-tests/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTriggerSavepointITCase.java, pom.xml
1.18 backport PR for parent PR #23962
There were conflicts (which I resolved) due to tests that were only migrated to JUnit5 in 1.19 (i.e. `master`).
=> [BP-1.18][FLINK-27082][ci] Adds a github-actions profile that disables certain tests that do not run in GHA

flink-runtime/src/main/java/org/apache/flink/runtime/messages/webmonitor/JobDetails.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/legacy/metrics/MetricStore.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/legacy/metrics/MetricStoreTest.java
Cherry picked from commit dd028282e8ab19c0d1cd05fad02b63bbda6c1358 (MR: https://github.com/apache/flink/pull/23447)
Removes transient metrics (idle/busy/backpressured time) for terminal subtasks in `MetricStore`.
- Added UT to test that the busy time metric is removed for terminal subtasks. …
=> [FLINK-31650][metrics][rest][BP-1.17] Remove transient metrics for subtasks in terminal state

docs/content.zh/docs/ops/state/task_failure_recovery.md, docs/content/docs/ops/state/task_failure_recovery.md, docs/layouts/shortcodes/generated/exponential_delay_restart_strategy_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/RestartStrategyOptions.java
See [FLIP-364: Improve the exponential-delay restart-strategy](https://cwiki.apache.org/confluence/x/uJqzDw) . This PR  includes the subtask1 of FLIP-364.
- [FLINK-33736][Scheduler] Update default value of exponential-delay.max-backoff and exponential-delay.backoff-multiplier
- If yes, how is the feature documented? Java doc and config doc are updated.
=> [FLINK-33736][Scheduler] Update default value of exponential-delay.max-backoff and exponential-delay.backoff-multiplier

flink-test-utils-parent/flink-test-utils/src/test/java/org/apache/flink/state/benchmark/StateBackendBenchmarkUtils.java
In FLINK-30535, we provide benchmarks for ttl state. A customized `TtlTimeProvider` is needed for finely controlling a fixed size of expired keys per iteration. So in the `StateBackendBenchmarkUtils#createKeyedStateBackend`, a `TtlTimeProvider` should be added in parameters.
Also by the way, the `StateBackendBenchmarkUtils#prepareDirectory` is made public for the de-duplication of code in `RescalingBenchmarkBase` in state benchmarks.
- add `TtlTimeProvider` in parameters of `StateBackendBenchmarkUtils#createKeyedStateBackend`.
- make `StateBackendBenchmarkUtils#prepareDirectory` public …
=> [FLINK-30535][Test] Customize TtlTimeProvider in state benchmarks

flink-core/src/main/java/org/apache/flink/configuration/DelegatingConfiguration.java, flink-core/src/test/java/org/apache/flink/configuration/DelegatingConfigurationTest.java
DelegatingConfiguration misses the perfix for some methods, such as:
- DelegatingConfiguration#getInteger(org.apache.flink.configuration.ConfigOption<java.lang.Integer>, int)
- DelegatingConfiguration#getLong(org.apache.flink.configuration.ConfigOption<java.lang.Long>, long)
- DelegatingConfiguration#getBoolean(org.apache.flink.configuration.ConfigOption<java.lang.Boolean>, boolean)
- DelegatingConfiguration#getFloat(org.apache.flink.configuration.ConfigOption<java.lang.Float>, float)
- DelegatingConfiguration#getDouble(org.apache.flink.configuration.ConfigOption<java.lang.Double>, double)
- [FLINK-33942][configuration][junit5-migration] Migrate DelegatingConfigurationTest to Junit5 and Assertj
- [FLINK-33942][configuration] Fix the bug that DelegatingConfiguration misses the prefix in …
=> [FLINK-33942][configuration] Fix the bug that DelegatingConfiguration misses the prefix in some get methods

flink-core/src/main/java/org/apache/flink/configuration/DelegatingConfiguration.java, flink-core/src/test/java/org/apache/flink/configuration/DelegatingConfigurationTest.java
[FLINK-33947][configuration] Fix bugs about the prefix attribute in the DelegatingConfiguration class.  
It was resulted from https://github.com/apache/flink/pull/23994#issuecomment-1869905090   
-  Check and confirm other potential bug points  
-  Fix the bugs about prefix key mapping when operating.  
- Marked `prefix` as `@Nonnull` and adapted assignment about `prefix`
- Fixed bug about methods `removeKey` & `removeConfig`
- DelegatingConfigurationTest#testRemoveKeyOrConfig …
=> [FLINK-33947][configuration] Fix bugs about the prefix attribute in the DelegatingConfiguration class.

flink-runtime/src/main/java/org/apache/flink/runtime/state/OperatorStateRestoreOperation.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/OperatorStateRestoreOperationTest.java
This PR backports https://github.com/apache/flink/pull/23938 to Flink 1.18
=> [BP-1.18] [FLINK-33863][checkpoint] Fix restoring compressed operator state

flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/ExtractionUtils.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/FunctionITCase.java
Support Flink SQL lookup joins via a multi-level inheritance of TableFunction.
For example:
```
private static class LookupTableLevel0Function<T> extends TableFunction<T> {}
public static class LookupTableWithoutHintLevel1Function
extends LookupTableLevel0Function<RowData> {
public void eval(@DataTypeHint("STRING") StringData s) {...}
}
```
Lookup Joins could be runable when LookupTableSource return `TableFunctionProvider.of(LookupTableWithoutHintLevel1Function)`
follow up: #19124, and add some tests to cover the change
- *Using the `Class.isAssignableFrom` to detemine the baseClass(TableFunction) is superclass of clazz(user custom TableFunction)*
- *Add some tests to cover the change*
- *Added unit test …
=> [FLINK-26694][table] Support lookup join via a multi-level inheritance of TableFunction

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecGroupWindowAggregate.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecPythonGroupWindowAggregate.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/FlinkAggregateProjectMergeRule.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/physical/batch/BatchPhysicalPythonWindowAggregateRule.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/logical/groupWindows.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/calcite/LogicalWindowAggregate.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/physical/batch/BatchPhysicalWindowAggregateRule.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/AggregateUtil.scala
In some exec nodes like StreamExecGroupWindowAggregate and some rules like BatchPhysicalWindowAggregateRule, planner uses "AggregateUtil#timeFieldIndex" to access the actual time field index, instead of using the time field index in LogicalWindow#timeAttribute directly. However, it would be more formal to use the field index instead of the column field.
- *Deprecate AggregateUtil#timeFieldIndex*
- *Update the code using "AggregateUtil.timeFieldIndex(input.getRowType, call.builder(), window.timeAttribute)" before to use  "window.timeAttribute.getFieldIndex"*
- *Fix the rule that doesn't update the index in window before while optimizing plan*
All existent tests can cover this fix. …
=> [FLINK-33941][table-planner] use field index instead of field name about window time column

flink-runtime-web/web-dashboard/src/app/interfaces/job-exception.ts, flink-runtime-web/web-dashboard/src/app/pages/job/exceptions/job-exceptions.component.html, flink-runtime-web/web-dashboard/src/app/pages/job/exceptions/job-exceptions.component.less, flink-runtime-web/web-dashboard/src/app/pages/job/exceptions/job-exceptions.component.ts
https://issues.apache.org/jira/browse/FLINK-31896
* ExceptionInfo now includes failureLabels
* Exception History tab on JobExceptions page now exposes failure labels
=> [FLINK-31896][runtime] Extend web interface to support failure labels

flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/failover/ExponentialDelayRestartBackoffTimeStrategy.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/failover/ExponentialDelayRestartBackoffTimeStrategyTest.java
Merge multiple Exceptions into one attempt for exponential-delay restart-strategy. See [FLIP-364: Improve the exponential-delay restart-strategy](https://cwiki.apache.org/confluence/x/uJqzDw) get more details.
- [FLINK-33737][Scheduler][refactor] Replace currentBackoffMS and lastFailureTimestamp with nextRestartTimestamp
- [FLINK-33737][Scheduler] Merge multiple Exceptions into one attempt for exponential-delay restart-strategy
Note: this PR is useful for FLINK-33565 (Support concurrentExceptions), and I have submitted a POC [PR](https://github.com/apache/flink/pull/24003) for FLINK-33565, it works well. (That PR depend on the current PR.)
- Added some unit tests in ExponentialDelayRestartBackoffTimeStrategyTest
- The public API, …
=> [FLINK-33737][Scheduler] Merge multiple Exceptions into one attempt for exponential-delay restart-strategy

docs/content/docs/dev/table/concepts/overview.md
This is a trivial PR to eliminate the ambiguous description about the meaning of 0ms when configuring operator-level state TTL for SQL/TableAPI using compiled plan.
Change "state retention is not enabled" to "state never expires" …
=> [FLINK-34001][docs][table] Fix ambiguous document description towards the default value for configuring operator-level state TTL

flink-runtime/src/test/java/org/apache/flink/runtime/minicluster/MiniClusterITCase.java
Fix the unstable test MiniClusterITCase.testHandleStreamingJobsWhenNotEnoughSlot.
- Disable the resource requirements to make sure the job failed to acquire slots until timeout.
=> [FLINK-33414] Fix the unstable test MiniClusterITCase.testHandleStreamingJobsWhenNotEnoughSlot

flink-runtime/src/main/java/org/apache/flink/runtime/util/profiler/ProfilingService.java
Remove the duplicated `stopProfiling()` call in `ProfilingService` to avoid profiling instances stopped unexpectedly when repeating profiling quickly.
- Remove duplicate scheduled stopProfiling task.
This change is already covered by existing tests, such as `ProfilingServiceTest`
=> [FLINK-34013][runtime] Remove duplicated stopProfiling() in `ProfilingService`

flink-clients/pom.xml
See FLINK-33907 for further context.
* Makes generating test jars happen earlier …
=> [FLINK-33907][ci] Makes copying test jars being done later

flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/DefaultSchedulerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/exceptionhistory/ArchivedTaskManagerLocationMatcher.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/exceptionhistory/ExceptionHistoryEntryMatcher.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/exceptionhistory/ExceptionHistoryEntryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/exceptionhistory/RootExceptionHistoryEntryTest.java
-  [FLINK-32852][JUnit5 migration] Migrate ExceptionHistoryEntryTest and RootExceptionHistoryEntryTest to Junit5 and Assertj
I'm working on FLINK-33565, this is a pre-PR to migrate some tests. 
It will reduce the work load for code review of FLINK-33565.
=> [FLINK-32852][JUnit5 migration] Migrate ExceptionHistoryEntryTest and RootExceptionHistoryEntryTest to Junit5 and Assertj

flink-clients/pom.xml
1.18 backport PR for parent PR #23965 
No conflicts appeared during backport.
This fixes the following error when compiling the test artifacts of flink-clients: Error: 2.054 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.2.0:copy-dependencies (copy-dependencies) on project flink-clients: Artifact has not been packaged yet. When used on reactor artifact, copy should be executed after packaging: see MDEP-187. -> [Help 1]
=> [BP-1.18][FLINK-33907][ci] Makes copying test jars being done in the package phase

tools/azure-pipelines/debug_files_utils.sh, tools/azure-pipelines/uploading_watchdog.sh
Azure Pipelines (see [pre-defined env variables](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)) and GitHub (see [pre-defined env variables](https://docs.github.com/en/actions/learn-github-actions/variables)) use a different set of environment variables. The CI tools rely on some of the environment variables that are provided by Azure Pipelines. With the migration to GitHub Actions we need to make the scripts CI environment agnostic.
* Made `tools/azure-pipelines/debug_files_utils.sh` use parameters instead of relying on environment variables
* Made `tools/azure-pipelines/uploading_watchdog.sh` consider Azure Pipelines and GitHub Actions environments
* I checked for occurrences of the following substrings (based on [Azure Pipelines …
=> [FLINK-34047][ci] Make CI scripts agnostic to CI environment

flink-core/src/main/java/org/apache/flink/api/connector/sink2/CommitterInitContext.java, flink-core/src/main/java/org/apache/flink/api/connector/sink2/CommittingSinkWriter.java, flink-core/src/main/java/org/apache/flink/api/connector/sink2/Sink.java, flink-core/src/main/java/org/apache/flink/api/connector/sink2/StatefulSink.java, flink-core/src/main/java/org/apache/flink/api/connector/sink2/StatefulSinkWriter.java, flink-core/src/main/java/org/apache/flink/api/connector/sink2/SupportsCommitter.java, flink-core/src/main/java/org/apache/flink/api/connector/sink2/SupportsWriterState.java, flink-core/src/main/java/org/apache/flink/api/connector/sink2/TwoPhaseCommittingSink.java, flink-core/src/main/java/org/apache/flink/api/connector/sink2/WriterInitContext.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/CommittableSummary.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/CommittableWithLineage.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/SupportsPostCommitTopology.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/SupportsPreCommitTopology.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/SupportsPreWriteTopology.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/WithPostCommitTopology.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/WithPreCommitTopology.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/WithPreWriteTopology.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/transformations/SinkV1Adapter.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterStateHandler.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/StatefulSinkWriterStateHandler.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/StatelessSinkWriterStateHandler.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGeneratorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/util/TestExpandingSink.java, flink-tests/src/test/java/org/apache/flink/test/scheduling/SpeculativeSchedulerITCase.java
Add new SinkV2 API interfaces, set inheritance and deprecation for the old interfaces.
All the new API's defined in [FLIP-372](https://cwiki.apache.org/confluence/display/FLINK/FLIP-372%3A+Enhance+and+synchronize+Sink+API+to+match+the+Source+API)
One minor additional change:
- Added `map` to `CommittableSummary` and `CommittableWithLineage` so it will be easier to map when the types are changed.
The existing tests should run without issue, to verify the backward compatibility. …
=> [FLINK-33973] Add new interfaces for SinkV2 to synchronize the API with the SourceV2 API

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecGroupTableAggregate.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/agg/AggsHandlerCodeGenerator.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/agg/ImperativeAggCodeGen.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/utils/JavaUserDefinedTableAggFunctions.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/table/TableAggregateITCase.scala, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/aggregate/GroupTableAggFunction.java
This PR is cherry-picked from https://github.com/apache/flink/pull/24051
- Planning phase: Check whether the `emitUpdateWithRetract` method is implemented. If so, the `TableAggsHandleFunction#emitValue` method should invoke `TableAggregateFunction#emitUpdateWithRetract` instead of `TableAggregateFunction#emitValue`. Meanwhile, change the collector type to `RetractableCollector` and implement `RetractableCollector#retract`.
- Runtime phase: Do not invoke emitValue to retract previously sent unchanged data.
- `TableAggregateITCase#testFlagAggregateWithOrWithoutIncrementalUpdate` …
=> [FLINK-31788][table] TableAggregateFunction supports emitUpdateWithRetract

flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl
Address the two warnings in the build for the Flink SQL Parser:
```
[INFO] — javacc:2.4:javacc (javacc) @ flink-sql-parser ---                                                 
Java Compiler Compiler Version 4.0 (Parser Generator)                                                       
(type "javacc" with no arguments for help)                                                                                                 
Reading from file .../flink-table/flink-sql-parser/target/generated-sources/javacc/Parser.jj . . .               
Note: UNICODE_INPUT option is specified. Please make sure you create the parser/lexer using a Reader with the correct character encoding.  
Warning: Choice conflict involving two expansions at                                                           
line …
```
=> [FLINK-34067] Fix javacc warnings in flink-sql-parser

flink-runtime/src/main/java/org/apache/flink/runtime/rest/RestClient.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/util/RestMapperUtils.java, flink-runtime/src/test/java/org/apache/flink/runtime/messages/webmonitor/JobDetailsTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/RestClientTest.java
At the moment Flink is throwing exception on unknown fields when parsing REST responses. An example for such a class is `JobDetailsInfo` but this applies to all others. In this PR we ignore all unknown fields in case of REST response JSON deserialization.
This is implemented based on [FLIP-401](https://cwiki.apache.org/confluence/display/FLINK/FLIP-401%3A+REST+API+JSON+response+deserialization+unknown+field+tolerance).
Ignore all unknown fields in case of REST response JSON deserialization.
Added new unit test. …
=> [FLINK-33268][rest] Skip unknown fields in REST response deserialization

docs/content.zh/docs/dev/table/sql/show.md, docs/content/docs/dev/table/sql/show.md, flink-table/flink-sql-client/src/test/resources/sql/catalog_database.q, flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl, flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/dql/SqlShowDatabases.java, flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ShowDatabasesOperation.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlNodeToOperationConversion.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlNodeConverters.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlShowDatabasesConverter.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlOtherOperationConverterTest.java
Support enhanced show functions syntax described in [FLIP-297](https://cwiki.apache.org/confluence/display/FLINK/FLIP-297%3A+Improve+Auxiliary+Sql+Statements)
Changelog from:
```
SHOW DATABASES
```
to:
```
SHOW DATABASES [ ( FROM | IN ) catalog_name] [ [NOT] (LIKE | ILIKE) <sql_like_pattern> ]
```
- Extended integration tests `flink-table/flink-sql-client/src/test/resources/sql/catalog_database.q`
- Extended unit test `flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java -> testShowDataBases()`
- Added unit tests in `flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlOtherOperationConverterTest.java -> testShowDatabases()` …
=> [FLINK-31481][table] Support enhanced show databases syntax

flink-core/src/main/java/org/apache/flink/api/connector/sink2/CommitterInitContext.java, flink-core/src/main/java/org/apache/flink/api/connector/sink2/CommittingSinkWriter.java, flink-core/src/main/java/org/apache/flink/api/connector/sink2/Sink.java, flink-core/src/main/java/org/apache/flink/api/connector/sink2/StatefulSink.java, flink-core/src/main/java/org/apache/flink/api/connector/sink2/StatefulSinkWriter.java, flink-core/src/main/java/org/apache/flink/api/connector/sink2/SupportsCommitter.java, flink-core/src/main/java/org/apache/flink/api/connector/sink2/SupportsWriterState.java, flink-core/src/main/java/org/apache/flink/api/connector/sink2/TwoPhaseCommittingSink.java, flink-core/src/main/java/org/apache/flink/api/connector/sink2/WriterInitContext.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/CommittableSummary.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/CommittableWithLineage.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/SupportsPostCommitTopology.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/SupportsPreCommitTopology.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/SupportsPreWriteTopology.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/transformations/SinkV1Adapter.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterStateHandler.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/StatefulSinkWriterStateHandler.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/StatelessSinkWriterStateHandler.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGeneratorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/util/TestExpandingSink.java, flink-tests/src/test/java/org/apache/flink/test/scheduling/SpeculativeSchedulerITCase.java
Add new SinkV2 API interfaces, set inheritance and deprecation for the old interfaces.
Added fix for the concurrent commit
All the new API's defined in [FLIP-372](https://cwiki.apache.org/confluence/display/FLINK/FLIP-372%3A+Enhance+and+synchronize+Sink+API+to+match+the+Source+API)
One minor additional change:
- Added `map` to `CommittableSummary` and `CommittableWithLineage` so it will be easier to map when the types are changed.
The existing tests should run without issue, to verify the backward compatibility. …
=> [FLINK-33973] Add new interfaces for SinkV2 to synchronize the API with the SourceV2 API 

flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/AggregateITCase.scala, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/aggregate/LagAggFunction.java
Fix LagFunction throw NPE when input argument are not null.
This issue is related to https://issues.apache.org/jira/browse/FLINK-31967. In [FLINK-31967](https://issues.apache.org/jira/browse/FLINK-31967), the NPE error has not been thoroughly fixed. If the select value  LAG(len, 1, cast(null as int)) and  LAG(len, 1, 1) exists together in test case AggregateITCase.testLagAggFunction() as:
```
val sql =
s"""
|select
|  LAG(len, 1, cast(null as int)) OVER w AS nullable_prev_quantity,
|  LAG(len, 1, 1) OVER w AS prev_quantity,
|  LAG(len) OVER w AS prev_quantity
|from src
|WINDOW w AS (ORDER BY proctime)
|""".stripMargin 
```
before is:
```
val sql =
s"""
|select
|  LAG(len, 1, cast(null as int)) OVER w AS prev_quantity,
|  LAG(len) OVER w AS prev_quantity
|from src
|WINDOW w AS (ORDER BY …
```
=> [FLINK-34066][table-planner] Fix LagFunction throw NPE when input argument are not null

flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
Fix the invalid configuration when using initialized root logger level on yarn deployment mode
- Fill the containerized env values of root logger level before submiting  yarn application.
- *Manually verified the change by running a 4 nodes cluster. …
=> [FLINK-33988][configuration] Fix the invalid configuration when using initialized root logger level on yarn deployment mode

flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMasterGateway.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerNG.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/utils/TestingJobMasterGateway.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/utils/TestingJobMasterGatewayBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/TestingSchedulerNG.java
This method is unused; requestJob is used in it's place.
=> [FLINK-34097] Remove JobMasterGateway#requestJobDetails

flink-runtime/src/test/java/org/apache/flink/runtime/minicluster/MiniClusterITCase.java
See FLINK-34070 for more context on this change.
* Adds dedicated test for no-resource-available handling through timeout
* Adds dedicated test for no-resource-available handling a request from the ResourceManager (and disabled it for the AdaptiveScheduler since it's not supported)
* Two CI runs with DefaultScheduler and AdaptiveScheduler enabled
- If …
=> [FLINK-34070][test] Adds dedicated tests in MiniClusterITCase for scenarios where there are not enough slots available.

flink-dist/src/main/flink-bin/bin/config.sh
Replace the `java` command with `JAVA_RUN` in scripts.
- Replace `java` with `JAVA_RUN` in config.sh
=> [FLINK-34072][scripts] Replace java command to JAVA_RUN in config.sh

flink-runtime-web/web-dashboard/src/app/pages/task-manager/profiler/task-manager-profiler.component.html, flink-runtime-web/web-dashboard/src/app/pages/task-manager/profiler/task-manager-profiler.component.less, flink-runtime-web/web-dashboard/src/app/pages/task-manager/profiler/task-manager-profiler.component.ts, flink-runtime-web/web-dashboard/src/app/pages/task-manager/routes.ts, flink-runtime-web/web-dashboard/src/app/pages/task-manager/status/task-manager-status.component.ts, flink-runtime-web/web-dashboard/src/app/services/task-manager.service.ts, flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManagerGateway.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/LeaderRetrievalHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/taskmanager/TaskManagerCustomLogHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/taskmanager/TaskManagerProfilingFileHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/taskmanager/TaskManagerProfilingHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/taskmanager/TaskManagerProfilingListHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/taskmanager/TaskManagerProfilingFileHeaders.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/taskmanager/TaskManagerProfilingFileMessageParameters.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/taskmanager/TaskManagerProfilingHeaders.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/taskmanager/TaskManagerProfilingListHeaders.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutorGateway.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutorGatewayDecoratorBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/util/profiler/ProfilingService.java, flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/WebMonitorEndpoint.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/utils/TestingResourceManagerGateway.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/taskmanager/TaskManagerProfilingHandlerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/taskmanager/TaskManagerProfilingListHandlerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TestingTaskExecutorGateway.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TestingTaskExecutorGatewayBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/util/profiler/ProfilingServiceTest.java
This is a subtask of [FLIP-375](https://cwiki.apache.org/confluence/x/64lEE), which introduces the async-profiler for profiling Taskmanager. 
- Generalized file upload from TaskManager to support different `FileType` uploading (different `fileType` could have different `baseDir`)
- Introduce APIs for Creating Profiling Instances / Downloading Profiling Results / Retrieving Profiling List on TaskManager
- Provide a web page for profiling TaskManager on  Flink WEB
Added test that validates that `TaskManagerProfilingHandler` works fine.
Added test that validates that `TaskManagerProfilingListHandler` works fine.
- Dependencies (does it add or upgrade a dependency): **no**  …
=> [FLINK-33434][runtime-web] Support invoke async-profiler on TaskManager via REST API

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecMatch.java
Set the chaining strategy of CepOperator to ALWAYS so that it can be chained with StreamRecordInserter. This is important to keep those two operators as close as possible because CepOperator depends on the shuffling that is applied before the inserter.
- The S3 file …
=> [FLINK-27992] Set ALWAYS chaining strategy for CepOperator in ExecMatch

flink-filesystems/flink-gs-fs-hadoop/src/main/java/org/apache/flink/fs/gs/GSFileSystemFactory.java, flink-filesystems/flink-gs-fs-hadoop/src/main/java/org/apache/flink/fs/gs/utils/ConfigUtils.java, flink-filesystems/flink-gs-fs-hadoop/src/test/java/org/apache/flink/fs/gs/GSFileSystemFactoryTest.java
This change configures the the GCS client used by the GSFileSystem's RecoverableWriter codepath to use the same GCS root URL as used by Hadoop.
Without this change, the GSFileSystem behaves differently depending on context if this config option is set—for instance, FileSource will use the overridden URL while FileSink will not.
- Update GSFileSystemFactory/GSFileSystemOptions to look for the gs.storage.root.url Flink config option, overriding the GCS client's Host option if it is set
- Added one test to ensure the GCS SDK `Storage` client's `Host` option is overridden when the `gs.storage.root.url` Flink config option is set
- Built the plugin and used it with an otherwise-vanilla Flink deployment and successfully used FileSink to write to an instance of fake-gcs-server
- Dependencies …
=> [FLINK-33694][gs-fs-hadoop] Support overriding GCS root URL

flink-filesystems/flink-gs-fs-hadoop/src/main/java/org/apache/flink/fs/gs/GSFileSystemFactory.java, flink-filesystems/flink-gs-fs-hadoop/src/main/java/org/apache/flink/fs/gs/utils/ConfigUtils.java, flink-filesystems/flink-gs-fs-hadoop/src/test/java/org/apache/flink/fs/gs/GSFileSystemFactoryTest.java
This is a backport of #23836 to 1.17.
=> [FLINK-33694][gs-fs-hadoop] Support overriding GCS root URL (backport to 1.17)

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlNodeConvertUtils.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlDdlToOperationConverterTest.java
In issue FLINK-33490, the view name need to validate to check whether the name is conflict in new view. However, for syntax: `create view view1(a, b) as select t1.name, t2.name from t1 join t1 t2 on t1.score = t2.score; `. If user specify the column name, planner should not throw exception while creating view with specify field names even if the query conflicts in field names.
- support the syntax `create view view1(a, b) as select t1.name, t2.name from t1 join t1 t2 on t1.score = t2.score; ` not throw exception.
- add test to cover it. …
=> [FLINK-33928][table-planner] Should not throw exception while creating view with specify field names

flink-core/src/main/java/org/apache/flink/configuration/Configuration.java, flink-core/src/main/java/org/apache/flink/configuration/DelegatingConfiguration.java, flink-core/src/test/java/org/apache/flink/configuration/ConfigurationTest.java, flink-core/src/test/java/org/apache/flink/configuration/DelegatingConfigurationTest.java
See the part 2.2 of [FLIP-405](https://cwiki.apache.org/confluence/x/6Yr5E)
- [FLINK-34080][configuration] Add the `T get(ConfigOption<T> configOption, T overrideDefault)` for Configuration
- [FLINK-34080][configuration] Deprecate all getXxx and setXxx methods for Configuration
- [FLINK-34080][configuration] Remove the `@Deprecated` for `getString(String key, String defaultValue)` of Configuration
- Added `ConfigurationTest#testGetWithOverrideDefault`
- Improved the `DelegatingConfigurationTest#testGetWithOverrideDefault` …
=> [FLINK-34080][configuration] Simplify the Configuration

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java
Avoid the RPC failure from JM to TM causing JM exit.
Use try catch to protect the sending logic in async executor when sending checkpoint aborted messages.
- If …
=> [FLINK-20672] Catch throwable when sending checkpoint aborted messages from JM to TM

flink-clients/pom.xml, flink-clients/src/test/java/org/apache/flink/client/deployment/application/FromClasspathEntryClassInformationProviderITCase.java, flink-clients/src/test/java/org/apache/flink/client/program/DefaultPackagedProgramRetrieverITCase.java
backport PR of https://github.com/apache/flink/pull/24095
=> [BP-1.18][FLINK-33907][ci] Moves tests in flink-clients relying on jars into the integration-test phase

flink-clients/pom.xml, flink-clients/src/test/java/org/apache/flink/client/deployment/application/FromClasspathEntryClassInformationProviderITCase.java, flink-clients/src/test/java/org/apache/flink/client/program/DefaultPackagedProgramRetrieverITCase.java
follow-up for PR https://github.com/apache/flink/pull/23965
See discussion in FLINK-33907 for further context.
* Transforms `FromClasspathEntryClassInformationProviderTest` and `DefaultPackedProgramRetrieverTest` to integration tests because they rely on jars
* Makes moving the test jars from {{flinlk-clients-test-utils}} into the {{pre-integration-test}} phase
Tests should be executed in the {{integration-test}} phase now instead of the {{test}} phase. …
=> [FLINK-33907][ci] Moves tests in flink-clients relying on jars into the integration-test phase

flink-end-to-end-tests/test-scripts/test_file_sink.sh
See further details in FLINK-34150
Enables local tests in generic CI builds (w/o s3 setup)
The local file sink e2e tests should be executed in this PR's CI run:
| Test | This PR | PR #24130 for comparison w/o the fix |
| ----- | ----------- | --------------- |
| New File Sink end-to-end test | [enabled](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=56570&view=logs&j=af184cdd-c6d8-5084-0b69-7e9c67b35f7a&t=0f3adb59-eefa-51c6-2858-3654d9e0749d&l=2825) | [disabled](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=56566&view=logs&j=af184cdd-c6d8-5084-0b69-7e9c67b35f7a&t=0f3adb59-eefa-51c6-2858-3654d9e0749d&l=2591) |
| New File Sink s3 end-to-end test | [disabled](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=56570&view=logs …
=> [FLINK-34150][ci] Enables local file sink e2e tests in general CI setups

flink-runtime/src/main/java/org/apache/flink/runtime/state/CompressibleFSDataInputStream.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/CompressibleFSDataOutputStream.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/DefaultOperatorStateBackendSnapshotStrategy.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/OperatorStateRestoreOperation.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/CompressibleFSDataInputStreamTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/OperatorStateRestoreOperationTest.java, flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/streaming/util/TestStreamEnvironment.java
https://issues.apache.org/jira/browse/FLINK-34063
=> [FLINK-34063][runtime] Always flush compression buffers, when retrieving stream position during OperatorState snapshot.

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/RecoveredInputChannel.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TestingNettyConnectionReader.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/netty/TestingTierConsumerAgent.java
We shouldn't throw this `UnsupportedDataTypeException` here. If we really want, can also use generic `IOException` or `UnsupportedOperationException` instead.
=> [hotfix] peekNextBufferSubpartitionId shouldn't throw UnsupportedDataTypeException

flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperatorFactory.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/StatefulSinkWriterStateHandler.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/translators/SinkTransformationTranslator.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SinkV2TransformationTranslatorITCase.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/StreamGraphGeneratorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/util/TestExpandingSinkWithMixin.java
Implement the changes to the Sink transformation which should depend only on the new API interfaces. The tests should remain the same, to ensure backward compatibility.
- SinkTransformationTranslator.java, CommitterOperatorFactory.java, SinkWriterOperator.java, StatefulSinkWriterStateHandler.java - to depend on the new API interfaces instead of the old ones
- Idenpotent change in SinkV2TransformationTranslatorITCase.java - this left out during the test refactor
- StreamGraphGeneratorTest.java, TestExpandingSinkWithMixin.java - Single specific test for the mixin interfaces
Added a single test method to the new API.
Kept all of the tests unchanged to make sure that the change is backward compatible. …
=> [FLINK-33974] Implement the Sink transformation depending on the new SinkV2 interfaces

flink-runtime/src/main/java/org/apache/flink/runtime/state/CompressibleFSDataInputStream.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/CompressibleFSDataOutputStream.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/DefaultOperatorStateBackendSnapshotStrategy.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/OperatorStateRestoreOperation.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/CompressibleFSDataInputStreamTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/OperatorStateRestoreOperationTest.java, flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/streaming/util/TestStreamEnvironment.java
Backport of https://github.com/apache/flink/pull/24079
=> [BP-1.18][FLINK-34063][runtime] Always flush compression buffers, when retrieving stream position during OperatorState snapshot.

docs/layouts/shortcodes/generated/environment_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/CoreOptions.java, flink-dist/src/main/flink-bin/bin/config.sh, flink-python/pyflink/pyflink_gateway_server.py, flink-yarn/src/main/java/org/apache/flink/yarn/Utils.java, flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java, flink-yarn/src/test/java/org/apache/flink/yarn/UtilsTest.java, flink-yarn/src/test/java/org/apache/flink/yarn/YarnClusterDescriptorTest.java
Add config options for administrator JVM options.
1. Added three config options: `env.java.default-opts.all`, `env.java.default-opts.jobmanager` `env.java.default-opts.taskmanager` that prepends to the corresponding non-default options.
2. For non-YARN envs, directly assemble the JVM opts in shell command.
3. For YARN env, change BootstrapTools#getTaskManagerShellCommand & YarnClusterDescriptor acccordingly. 
- The non-YARN related change is tested by starting local standalone clusters & K8s clusters and manually verify the JVM opts.
- The YARN-related change is covered by UT.
- The …
=> [FLINK-33221][core][config] Add config options for administrator JVM options

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/lookup/KeyedLookupJoinWrapper.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/lookup/LookupJoinRunner.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/join/KeyedLookupJoinHarnessTest.java
KeyedLookupJoinWrapper(when 'table.optimizer.non-deterministic-update.strategy
' is set to 'TRY_RESOLVE' and the lookup join exists NDU problemns) incorrectly process delete message for inner join when previous lookup result is empty.
The reason is unaligned processing between retract (which access local state) and add (which do fetch via lookup function ) logic.
* sync the retract and add process logic
* update related tests
* KeyedLookupJoinHarnessTest …
=> [FLINK-34166][table] Fix KeyedLookupJoinWrapper incorrectly process delete message for inner join when previous lookup result is empty

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerBuilder.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/LogicalFile.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/SegmentFileStateHandle.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/WithinCheckpointFileMergingSnapshotManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FileMergingCheckpointStateOutputStream.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStorageAccess.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsMergingCheckpointStorageAccess.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsMergingCheckpointStorageLocation.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsSegmentDataInputStream.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/TaskExecutorFileMergingManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/filesystem/FileMergingCheckpointStateOutputStreamTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/filesystem/FsMergingCheckpointStorageLocationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/filesystem/FsSegmentDataInputStreamTest.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorImpl.java
As one part of FLIP-306, this PR enables file merging in snapshot by implementing the corresponding output&input streams for ```FileMergingSnapshotManager```
- *Add ```createCheckpointStateOutputStream``` in ```FileMergingSnapshotManager```.*
- *Add output&input streams for file merging checkpoints*
- *Add ```SegmentFileStateHandle``` to represent a state that is written into a file segment.*
This change added several UT tests in:
- ```FileMergingSnapshotManagerTest```
- ```FileMergingCheckpointStateOutputStreamTest```
- ```FsSegmentDataInputStreamTest```. …
=> [FLINK-32073][checkpoint] Implement file merging in snapshot

flink-runtime-web/web-dashboard/src/app/pages/job-manager/profiler/job-manager-profiler.component.html, flink-runtime-web/web-dashboard/src/app/pages/job-manager/profiler/job-manager-profiler.component.ts, flink-runtime-web/web-dashboard/src/app/pages/task-manager/profiler/task-manager-profiler.component.html, flink-runtime-web/web-dashboard/src/app/pages/task-manager/profiler/task-manager-profiler.component.ts
This is a subtask of [FLIP-375](https://cwiki.apache.org/confluence/x/64lEE), which introduces the different profiling modes on the Flink Web for profiling Taskmanager & Jobmanager. 
- Provide profiling mode selector and hint on Flink Web
- If …
=> [FLINK-34029][runtime-web] Support different profiling mode on Flink WEB

flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/failover/ExecutionFailureHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/failover/ExponentialDelayRestartBackoffTimeStrategy.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/failover/FailureHandlingResult.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/failover/FailureRateRestartBackoffTimeStrategy.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/failover/FixedDelayRestartBackoffTimeStrategy.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/failover/NoRestartBackoffTimeStrategy.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/failover/RestartBackoffTimeStrategy.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultScheduler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/exceptionhistory/FailureHandlingResultSnapshot.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/exceptionhistory/RootExceptionHistoryEntry.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/failover/ExecutionFailureHandlerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/failover/ExponentialDelayRestartBackoffTimeStrategyTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/failover/FailureHandlingResultTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/failover/TestRestartBackoffTimeStrategy.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/DefaultSchedulerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/exceptionhistory/FailureHandlingResultSnapshotTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/exceptionhistory/RootExceptionHistoryEntryTest.java
The concurrent exceptions doesn't work.
- [FLINK-33565][Exception] Archive exceptions into the exception history immediately when they occur, instead of archiving them when restarting
- The first commit is refactoring. 
- Currently, archiving exception when restarting task instead of immediately. It means, when one task failure, we can see the exception history after flink restart this task. 
- So the first commit is only a refactoring. It archives exceptions into the exception history immediately when they occur, instead of archiving them when restarting.
- [FLINK-33565][Exception] Restart strategy checks whether current failure is a new attempt
- The second commit is related to restart strategy, adding a return value indicates whether current failure is a new attempt.
- …
=> [FLINK-33565][Scheduler] ConcurrentExceptions works with exception merging

flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroFileFormatFactory.java, flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroFormatFactory.java, flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroFormatOptions.java, flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroRowDataDeserializationSchema.java, flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroRowDataSerializationSchema.java, flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroRowDeserializationSchema.java, flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroRowSerializationSchema.java, flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/AvroToRowDataConverters.java, flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/RowDataToAvroConverters.java, flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/typeutils/AvroSchemaConverter.java, flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroFormatFactoryTest.java, flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroRowDataDeSerializationSchemaTest.java, flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroRowDeSerializationSchemaTest.java, flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/typeutils/AvroSchemaConverterTest.java, flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/typeutils/AvroTypeExtractionTest.java, flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/utils/AvroTestUtils.java, flink-formats/flink-avro/src/test/resources/avro/user.avsc
From the latest Avro Spec, local-timestamp-millis and local-timestamp-micros logical types are added. This PR is to support Local timezone logic type in Avro related classes. 
- Add logic to handle TIMESTAMP_WITH_LOCAL_TIME_ZONE in AvroToRowDataConverters
- Add logic to handle TIMESTAMP_WITH_LOCAL_TIME_ZONE in RowDataToAvroConverters
- Add logic to handle TIMESTAMP_WITH_LOCAL_TIME_ZONE in legacy AvroRow Ser and Des Schema
- Add new fields for test cases
Extended existing test cases for Avro …
=> [FLINK-33198][Format/Avro] support local timezone timestamp logic type in AVRO

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserCalcitePlanner.java, flink-connectors/flink-connector-hive/src/test/resources/query-test/join.q
Fix NPE when non-native udf used in join condition in hive-parser
This problem caused by not set  UnparseTranslator when init HiveParserJoinTypeCheckCtx.
This change is verified by added test
=> [FLINK-33233][hive] Fix NPE when non-native udf is used in join condition with Hive dialect, back port to 1.17

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/delegation/hive/HiveParserCalcitePlanner.java, flink-connectors/flink-connector-hive/src/test/resources/query-test/join.q
Fix NPE when non-native udf used in join condition in hive-parser
This problem caused by not set  UnparseTranslator when init HiveParserJoinTypeCheckCtx.
This change is verified by added test
=> [FLINK-33233][hive] Fix NPE when non-native udf is used in join condition with Hive dialect, back port to 1.18

flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/stream/compact/CompactCoordinator.java, flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/table/stream/compact/CompactCoordinatorTest.java
`CompactCoordinator` accumulates data in `currentInputFiles` and only rolls them into `inputFiles` when `snapshotState()` gets called. At the same time it relies on separately receiving checkpoint indications from the upstream operator via `processElement()` (`EndCheckpoint`). If the job terminates, the final `EndCheckpoint` can arrive before the `snapshotState()` gets called. This leads to data loss (all events in `currentInputFiles` get discarded).
=> [FLINK-34117][bugfix][table] Fix CompactCoordinator data loss upon termination

flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/BootstrapTools.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/transformations/SinkV1Adapter.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/transformations/SinkV1AdapterTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/WithAdapterCommitterOperatorTest.java
Migrate SinkV1Adapter to the new FLIP-372 SinkV2 API 
Changed the interfaces
Tests are updated where needed. The other tests should cover the existing code
=> [FLINK-34208] Migrate SinkV1Adapter to the new SinkV2 API

flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/table/TableAggregateITCase.scala
See  #24172 for more details.
(cherry picked from commit ecd7efc2522b7640ec8d561ee8607c971cd714e7)
Split test cases and fix typo.
The CI should pass and no more unstable cases occur.
- The serializer: no
=> [FLINK-34115][table-planner] Fix unstable TableAggregateITCase.testFlagAggregateWithOrWithoutIncrementalUpdate

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/lookup/KeyedLookupJoinWrapper.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/lookup/LookupJoinRunner.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/join/KeyedLookupJoinHarnessTest.java
This is a backport pr of FLINK-34166 into release-1.18 branch.
=>  [FLINK-34166][table] Fix KeyedLookupJoinWrapper incorrectly process delete message for inner join when previous lookup result is empty

flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/SingleThreadMultiplexSourceReaderBase.java, flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/SourceReaderBase.java, flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/fetcher/SingleThreadFetcherManager.java, flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcher.java, flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherManager.java, flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherTask.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceReaderTest.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/SourceReaderBaseTest.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherManagerTest.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherPauseResumeSplitReaderTest.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/mocks/MockBaseSource.java, flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/mocks/MockSourceReader.java
As shown in [FLIP-389](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=278465498), this PR has 2 goals:
- To expose the SplitFetcherManager / SingleThreadFetcheManager as Public, allowing connector developers to easily create their own threading models in the SourceReaderBase.
- To hide the element queue from the connector developers and make SplitFetcherManager the only owner class of the queue
- By exposing the SplitFetcherManager / SingleThreadFetcheManager, connector developers can easily create their own threading models in the SourceReaderBase, by implementing addSplits(), removeSplits() and maybeShutdownFinishedFetchers() functions.
- Note that the SplitFetcher constructor is package private, so users can only create SplitFetchers via …
=> [FLINK-34196][Connectors][FLIP-389] Annotate SingleThreadFetcherManager as PublicEvolving.

flink-tests-java17/src/test/java/org/apache/flink/api/java/typeutils/runtime/PojoRecordSerializerTest.java, flink-tests-java17/src/test/java/org/apache/flink/api/java/typeutils/runtime/PojoRecordSerializerUpgradeTestSpecifications.java
Compilation error fix that was introduced with https://github.com/apache/flink/commit/84444d50 in the JDK17 profile (parent PR #24187)
[Related CI failure](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=57007&view=logs&j=f693abc3-390c-511e-7162-44da4abb3b05&t=0150d857-6b31-59f6-0d5b-ddbf998e32ad)
=> [FLINK-34204][core] spotless:apply

docs/content.zh/docs/dev/table/concepts/overview.md, docs/content.zh/docs/dev/table/sql/queries/hints.md, docs/content/docs/dev/table/concepts/overview.md, docs/content/docs/dev/table/sql/queries/hints.md
This PR adds a doc to the `STATE_TTL` hint.
Add doc.
- Does this pull request introduce a new feature? Yes
=> [FLINK-34059][docs][table] Add documentation on STATE_TTL hint

flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/table/TableAggregateITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/utils/TestData.scala
This PR tries to fix the unstable ITCase `TableAggregateITCase`. 
Replace table source.
- Plan before fix
```sql
Calc(select=[f0 AS top_price, f1 AS rank], changelogMode=[I,UA,D])
+- GroupTableAggregate(select=[incrementalTop2(price) AS (f0, f1)], changelogMode=[I,UA,D])
+- Exchange(distribution=[single], changelogMode=[I])
+- Union(all=[true], union=[id, name, price], changelogMode=[I])
:- Calc(select=[CAST(1 AS INTEGER) AS id, CAST(_UTF-16LE'Latte':VARCHAR(2147483647) CHARACTER SET "UTF-16LE" AS VARCHAR(2147483647) CHARACTER SET "UTF-16LE") AS name, CAST(6 AS INTEGER) AS price], changelogMode=[I])
:  +- Values(type=[RecordType(INTEGER ZERO)], tuples=[[{ 0 }]], changelogMode=[I])
:- Calc(select=[CAST(2 AS INTEGER) AS id, CAST(_UTF-16LE'Milk':VARCHAR(2147483647) CHARACTER SET "UTF-16LE" …
```
=> [FLINK-34115][table-planner] Fix TableAggregateITCase unstable test

flink-kubernetes/src/main/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionDriver.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/resources/KubernetesLeaderElector.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/highavailability/KubernetesLeaderElectionDriverTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/resources/KubernetesLeaderElectorITCase.java
Move the attachment of config map labels for cluster config maps to the leader elector, which causes them to be set at creation time, instead of when the JM acquires leadership for the first time.
=> [FLINK-34286][k8s] Attach cluster config map labels at creation time

.github/actions/job_init/action.yml, .github/actions/run_mvn/action.yml, .github/workflows/ci.yml, .github/workflows/template.flink-ci.yml, .github/workflows/template.pre-compile-checks.yml, pom.xml, tools/azure-pipelines/create_build_artifact.sh, tools/azure-pipelines/debug_files_utils.sh, tools/azure-pipelines/unpack_build_artifact.sh, tools/azure-pipelines/uploading_watchdog.sh, tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/licensecheck/NoticeFileChecker.java, tools/ci/maven-utils.sh
* https://github.com/apache/flink/pull/24061
Creates CI workflow that runs on Flink's default setup in branches.
* Adds custom actions for selecting the Java version
* Adds custom action for moving data within the container
* Adds template for pre-compile checks
* Adds template for executing Flink's test suite
* Adds basic CI workflow
- The public …
=> [FLINK-33914][ci] Adds basic Flink CI workflow

.github/actions/job_init/action.yml, .github/actions/run_mvn/action.yml, .github/workflows/ci.yml, .github/workflows/template.flink-ci.yml, .github/workflows/template.pre-compile-checks.yml, pom.xml, tools/azure-pipelines/create_build_artifact.sh, tools/azure-pipelines/debug_files_utils.sh, tools/azure-pipelines/unpack_build_artifact.sh, tools/azure-pipelines/uploading_watchdog.sh, tools/ci/flink-ci-tools/src/main/java/org/apache/flink/tools/ci/licensecheck/NoticeFileChecker.java, tools/ci/maven-utils.sh
Backport of FLINK-33914 to enable GHA workflows also in `release-1.18`
* Cherry-picked FLINK-33914 changes
* Conflict resolution for JDK21 related changes
* Azure Pipelines should succeed.
* GHA workflow should succeed.
=> [BP-1.18][FLINK-33914][ci] Adds basic Flink CI workflow

.github/workflows/nightly.yml
* https://github.com/apache/flink/pull/24061
Creates an extended CI workflow that runs on master
* Adds custom actions for selecting the release branch and commit hash
* Adds custom action for selecting the workflow configuration
* Adds fallback workflow configuration
* Adds workflow for utilizing the workflow configuration …
=> [FLINK-33915][ci] Adds nightly workflow for the master branch

.github/workflows/nightly.yml
1.18 backport of FLINK-33915 excluding the JDK 21 workflow
* Cherry-pick of FLINK-33915 excluding the JDK 21 workflow
* Azure Pipelines should succeed.
* GHA workflow should succeed.
=> [BP-1.18][FLINK-33915][ci] Adds nightly workflow for the releae-1.18 branch

.github/workflows/nightly-trigger.yml, .github/workflows/nightly.yml
* https://github.com/apache/flink/pull/24061
Creates an extended CI workflow that runs on master
* Adds release-1.18 workflow configuration
* Adds release-1.18 workflow
- Anything …
=> [FLINK-33916][ci] Adds nightly workflow for most-recently published Flink version

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/connectors/DynamicSourceUtils.java
Avoids the creation of ScanRuntimeProvider in streaming mode.
Trivial
=> [FLINK-34316] Reduce instantiation of ScanRuntimeProvider in streaming mode

flink-table/flink-sql-client/bin/sql-client.sh
Moves the flink sql client jar precedence before the Hadoop classpath to avoid conflicts with the older jline version from the Hadoop classpath.
1. Changed the order of sql client jar and hadoop classpath in sql-client.sh
Launched the Flink SQL Session and verified with Flink sql examples. …
=> [FLINK-33358][sql] Fix Flink SQL Client fail to start in Flink on YARN

docs/content.zh/docs/dev/table/functions/udfs.md, docs/content/docs/dev/table/functions/udfs.md
This PR corrects the Retract Example in [TableAggregateFunction](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/functions/udfs/#retraction-example).
This is because `GroupTableAggFuction` will not reinvoke `getAccumulators` after `emitValue` is called.
See GroupTableAggFuction L#142~ L#146
```java
// get accumulator
accumulators = function.getAccumulators(); // function
if (!recordCounter.recordCountIsZero(accumulators)) {
function.emitValue(out, currentKey, false); 
// update the state
accState.update(accumulators);
}
```
Update doc
The old example cannot generate the expected results. After correcting the example, it works.
- …
=> [FLINK-34258][docs][table] Fix incorrect retract example for TableAggregateFunction

flink-runtime/src/main/java/org/apache/flink/runtime/state/TaskExecutorLocalStateStoresManager.java
When using MiniCluster mode, file descriptors like /tmp/minicluster_6e62ab17ab058e0d5df56b97e9ccef71/tm_0/localState are not released after a Job completes. Executing multiple Jobs in the same JVM might result in leftover file descriptors, potentially leading to problems.
After executing the reproducing code provided below (after entering the sleep), running lsof -p 18162 reveals:
```
...
java    18162 sa_cluster   30r   DIR              253,1         0    1311962 /tmp/minicluster_79186ba3856bb18fd21c20d9adbaa3da/tm_0/localState (deleted)
java    18162 sa_cluster   31r   DIR              253,1         0    1311962 /tmp/minicluster_79186ba3856bb18fd21c20d9adbaa3da/tm_0/localState (deleted)
java    18162 sa_cluster   32r   DIR              253,1         0    1310787 …
```
=> [FLINK-33981][runtime] Fix not closing DirectoryStream after listing local state files

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/sql/SqlSessionTableFunction.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/sql/SqlWindowTableFunction.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/WindowTableFunctionTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/WindowTableFunctionTest.scala
Currently, when user uses session window tvf by named params, an exception will be thrown.
This pr is try to align the param name in Flip-145 about session window tvf. 
- *align the param name from calcite `SIZE` to `GAP` in Flip-145 about session window tvf*
- *Add tests to verify it*
Some tests are added to verify it. …
=> [FLINK-34323][table-planner] Fix param name in session window tvf when using named params

flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/pekko/PekkoRpcActor.java
Prevent an issue where an NPE can occur when an RpcEndpoint is under construction, the rpcServer isnt set yet, but the underlying infrastructure is already set up (aka, the RpcServer already exists) and receives a message.
Here it was possible to access the address of the RpcEndpoint, which would fail if the rpcServer field is still null.
Fix by not relying on the endpoint address but the actor path, which by and large is similar in terms of information (lacks host/port, but we still know which actor was the target).
No test because we cant reasonably test this race condition.
=> [FLINK-34343][rpc] Use actor path when rejecting early messages

flink-runtime-web/web-dashboard/src/app/pages/task-manager/profiler/task-manager-profiler.component.html
A hotfix to correct the profilling options name.
=> [hotfix][web] Correct the hint of options name of rest.profiling.enabled

docs/content.zh/docs/ops/state/task_failure_recovery.md, docs/content/docs/ops/state/task_failure_recovery.md
[FLINK-33739][doc] Document FLIP-364: Improve the exponential-delay restart-strategy
Here are some screenshots:
=> [FLINK-33739][doc] Document FLIP-364: Improve the exponential-delay restart-strategy

.github/workflows/nightly-trigger.yml
https://github.com/apache/flink/commit/b8b2596a updated the release branch to monitor from `release-1.18` to `release-1.19` because of the 1.19 release branch cut. We still want to monitor `release-1.18` as part of the nightlies, though.
* Adds `release-1.18` to the branch list for the GHA nightly trigger workflow …
=> [FLINK-34282][ci] Adds release-1.18 back to GHA nightly trigger workflow

.github/actions/job_init/action.yml, flink-end-to-end-tests/test-scripts/test-runner-common.sh
There was a drop in disk space some time between Feb 2 (see [84G example workflow](https://github.com/apache/flink/actions/runs/7750406652/job/21136823036#step:14:11726)) and Feb 3 (see [73G example workflow](https://github.com/apache/flink/actions/runs/7763815214/job/21176570116#step:14:11074)). Previously, the runners had a disk size of ~84G. That dropped to ~73G. Instead of 24G free space, the e2e tests were only able to use 14G.
This seems to be a GHA runner specific issue. The Azure Pipeline runners have a disk size of 73G as well, but come with less disk being used from the start. That is why we're not seeing the issue in Azure Pipelines.
There are some binaries which we're not really using. Removing those would already free quite some disk space:
* Andoid: ~9G
* CodeQL: ~5G
* .NET: …
=> [FLINK-34360][ci] Adds cleanup to job_init action

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/allocator/SlotSharingSlotAllocator.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/allocator/SlotSharingSlotAllocatorTest.java
[FLINK-33960][Scheduler] Fix the bug that Adaptive Scheduler doesn't respect the lowerBound when one flink job has more than 1 tasks
When we using the adaptive scheduler and the rescale api, users will set the lowerBound and upperBound for each job vertices. And users expect the parallelism of all vertices between lowerBound and upperBound.
But when one flink job  has more than 1 vertex, and resource isn't enough. Some of lowerBound won't be respect.
How to reproduce this bug:
One job has 2 job vertices, we set the resource requirements are:
Vertex1: lowerBound=2, upperBound=2
Vertex2: lowerBound=8, upperBound=8
They are same slotSharingGroup, and we only 5 available slots. This job shouldn't run due to the slots cannot meets the resource requiremnt for vertex2.
But the job can runs, and …
=> [FLINK-33960][Scheduler] Fix the bug that Adaptive Scheduler doesn't respect the lowerBound when one flink job has more than 1 tasks

flink-runtime/src/test/java/org/apache/flink/runtime/testutils/CommonTestUtils.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/AutoRescalingITCase.java
see https://github.com/1996fanrui/flink/commit/420fdf3cfec4e2ec6d1f600fa0c87a3fc131b5fe#r138161972
Wait for 2 checkpoint to ensure the latest checkpoint start after waitForTwoOrMoreCheckpoint is called.
=> [FLINK-34200][test] Fix the bug that AutoRescalingITCase.testCheckpointRescalingInKeyedState fails occasionally

flink-formats/flink-avro-confluent-registry/pom.xml, flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE, flink-python/pom.xml
* Decrease tech debt 
* Update used Confluent Platform version for Avro Schema Registry format
=> [FLINK-34244] Upgrade Confluent Platform Avro Schema Registry

.github/workflows/nightly-trigger.yml
Disables the nightly trigger for the forks. The nightly builds can be still triggered manually through the [`workflow_dispatch` trigger of the nightly workflow](https://github.com/apache/flink/blob/master/.github/workflows/nightly.yml#L22)
* Added repo check to trigger workflow
* [Test run](https://github.com/XComp/flink/actions/runs/7826269858) in `XComp/flink` fork …
=> [FLINK-34410][ci] Disables the nightly trigger workflow for forks

flink-end-to-end-tests/test-scripts/common_yarn_docker.sh
Switch to https from http to download hadoop.tar.gz
(otherwise download fails)
*(or)*
*(or)*
*(example:)*
- …
=> [FLINK-34410] Correct hadoop.tar.gz download url

flink-end-to-end-tests/test-scripts/common_yarn_docker.sh
=> [BP-1.18][FLINK-34410] Correct hadoop.tar.gz download url

flink-end-to-end-tests/test-scripts/common_yarn_docker.sh
=> [BP-1.19][FLINK-34410] Correct hadoop.tar.gz download url

flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/SqlCompleter.java, flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/util/ClientClassloaderUtil.java
This is a small fix, we used slf4j but not placeholders, this PR improves the situation.
*(or)*
*(or)* …
=> [hotfix][sql-client] Improve logging using placeholders

pom.xml
Our version of the plugin has a plugin configuration option, but it's not honored when specified on the command-line. Manually wire up a property that takes care of this.
Can be removed once we upgrade post to 2.38+
=> [hotfix][build] Wire up spotless.skip property

flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/batch/sql/CompactManagedTableITCase.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/utils/BatchTestBase.scala
1.18 BP of #24298. Mostly the same but with an added `@Before` for backwards-compatibility with jUnit4 tests.
=> [1.18][FLINK-34422][test] BatchTestBase uses MiniClusterExtension

flink-formats/flink-protobuf/src/test/java/org/apache/flink/formats/protobuf/ProtobufSQLITCase.java, flink-formats/flink-protobuf/src/test/java/org/apache/flink/formats/protobuf/ProtobufSQLITCaseTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/batch/sql/CompactManagedTableITCase.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/utils/BatchTestBase.scala
The setup of the table environment in this class ran before the MiniClusterExtension was set up and beforeEach was called, causing jobs to spawn separate mini clusters. Certain tests cases try running ~200 test cases in parallel, which overloaded the system.
=> [FLINK-34422][test] BatchTestBase uses MiniClusterExtension

flink-formats/flink-protobuf/src/test/java/org/apache/flink/formats/protobuf/VeryBigPbRowToProtoITCase.java
Follow-up on https://github.com/apache/flink/pull/24302. I missed renaming one test.
* Renames `VeryBigPbRowToProtoTest` into `VeryBigPbRowToProtoITCase` to utilize the bigger heap size of the integration test execution
* Renames the test
* Verified that the causing PR https://github.com/apache/flink/pull/23937 didn't touch any other tests
- If yes, how …
=> [FLINK-34403][ci] Transforms VeryBigPbRowToProtoTest into an integration test

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/QueryOperationSqlSerializationTest.java
when submitting DQL jobs, the job name should not always be 'collect'. Using sql as the job name will improve the usability.
- use 'QueryOperation#asSerializableString()' as the JobName for DQL jobs submitted by sql-gateway
- Added unit test 'QueryOperationSqlSerializationTest#testSqlAsJobNameForQueryOperation' to verify the logic using sql as job name
- Test manually by submitting queries SQL Client, the jobName changes to sql
- The S3 file …
=> [FLINK-25015][Table SQL] Use SQL string as jobName for DQL jobs submitted by sql-gateway

.github/actions/job_init/action.yml, .github/workflows/template.flink-ci.yml
* Adds disk space by mounting `/mnt` to the Docker container
* GitHub runners come with an additional disk mounted to `/mnt` which we can utilize (code snippet below was copied from the [e2e1 stage of this build](https://github.com/XComp/flink/actions/runs/7934542890/job/21666101915#step:3:100)):
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        73G   54G   19G  74% /
tmpfs           7.9G  172K  7.9G   1% /dev/shm
tmpfs           3.2G  1.1M  3.2G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sdb15      105M  6.1M   /boot/efi
/dev/sda1        74G  4.1G   66G   6% /mnt
tmpfs           1.6G   12K  1.6G   1% /run/user/1001
```
* Adds an additional mount point `/mnt` that points to the container's `/root` folder overwriting the existing one
* I run the CI …
=> [FLINK-34418][ci] Adds volume mount to gain more disk space

flink-core/src/test/java/org/apache/flink/testutils/ClassLoaderUtils.java, flink-tests/src/test/java/org/apache/flink/runtime/util/ExceptionUtilsITCase.java, flink-tests/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
1.19 backport for parent PR #24315 
The hotfix improvement and the JUnit5 migration was not backported.
=> [BP-1.19][FLINK-22765][test] Fixes test instability in ExceptionUtilsITCase#testIsMetaspaceOutOfMemoryError

flink-core/src/test/java/org/apache/flink/testutils/ClassLoaderUtils.java, flink-tests/src/test/java/org/apache/flink/runtime/util/ExceptionUtilsITCase.java, flink-tests/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
1.18 backport for parent PR https://github.com/apache/flink/pull/24315
The hotfix improvement and the JUnit5 migration was not backported.
=> [BP-1.18][FLINK-22765][test] Fixes test instability in ExceptionUtilsITCase#testIsMetaspaceOutOfMemoryError

docs/data/sql_functions.yml, docs/data/sql_functions_zh.yml, flink-python/pyflink/table/expression.py, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/ArrayAppendPrependTypeStrategy.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/SpecificTypeStrategies.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/strategies/ArrayAppendPrependTypeStrategyTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CollectionFunctionsITCase.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/ArrayAppendFunction.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/ArrayPrependFunction.java
This is an implementation of `ARRAY_APPEND` and `ARRAY_PREPEND` inspired by https://github.com/apache/flink/pull/19543
- ARRAY_APPEND for Table API and SQL
- ARRAY_PREPEND for Table API and SQL
This change added tests in `CollectionFunctionsITCase` 
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes )
=> [FLINK-27891][Table] Add ARRAY_APPEND and ARRAY_PREPEND functions

flink-tests/src/test/java/org/apache/flink/test/checkpointing/AutoRescalingITCase.java
[FLINK-34336][test] Fix the bug that AutoRescalingITCase may hang sometimes
AutoRescalingITCase#testCheckpointRescalingWithKeyedAndNonPartitionedState may hang in waitForRunningTasks(restClusterClient, jobID, parallelism2);
The job has 2 tasks(vertices), after calling updateJobResourceRequirements. The source parallelism isn't changed (It's parallelism) , and the FlatMapper+Sink is changed from  parallelism to parallelism2.
So we expect the task number should be parallelism + parallelism2 instead of parallelism2.
Flink 1.19 supports the scaling cooldown, and the cooldown time is 30s by default. It means, flink job will rescale job 30 seconds after updateJobResourceRequirements is called.
So the running tasks are old parallelism when we call waitForRunningTasks(restClusterClient, jobID, …
=> [FLINK-34336][test] Fix the bug that AutoRescalingITCase may hang sometimes

flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBIncrementalRestoreOperation.java
Code was removing a handle from a list twice, so the second call to remove has no effect and can be deleted.
=> [hotfix] Remove redundant call to remove().

docs/layouts/shortcodes/generated/rocksdb_native_metric_configuration.html, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBNativeMetricOptions.java
Add RocksDB bloom filter metrics.
Get RocksDB bloom filter metrics via RocksDB Statistics, and report it via Metrics reporter.
- Does this …
=> [FLINK-34386][state] Add RocksDB bloom filter metrics

flink-python/dev/lint-python.sh
*This pull request will select random python version to run to optimize Python nightly CI time*
- *select random python version to run*
*nightly tests*
=> [FLINK-34202][python] Optimize Python nightly CI time

.github/workflows/template.flink-ci.yml, .github/workflows/template.pre-compile-checks.yml, .github/workflows/template.workflow-init.yml
1.18 backport PR for parent PR #24347
=> [BP-1.18][FLINK-34331][ci] Adds reusable workflow that is used to load the runner configuration based on the projects owner

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/FlinkCalciteSqlValidator.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/stream/sql/ColumnExpansionTest.java
Considers the assignment operator `=>` when performing metadata virtual column expansion. 
Enabling e.g. the following query:
```
TUMBLE(DATA => TABLE t3, TIMECOL => DESCRIPTOR(t3_m_virtual), SIZE => INTERVAL '1' MINUTE))
```
- Additional checks for `SqlKind.ARGUMENT_ASSIGNMENT` in the SQL validator.
`ColumnExpansionTest#testExplicitTableWithinTableFunctionWithNamedArgs`
- The S3 file …
=> [FLINK-34476][table-planner] Consider assignment operator during TVF column expansion

docs/content.zh/docs/deployment/filesystems/s3.md, docs/content.zh/docs/deployment/overview.md, docs/content.zh/docs/deployment/resource-providers/standalone/overview.md, docs/content/docs/deployment/filesystems/s3.md, docs/content/docs/deployment/overview.md, flink-filesystems/flink-s3-fs-base/src/main/java/org/apache/flink/fs/s3/common/token/DynamicTemporaryAWSCredentialsProvider.java, flink-filesystems/flink-s3-fs-presto/src/test/java/org/apache/flink/fs/s3presto/PrestoS3FileSystemTest.java
Required such that this provider can be used with the presto S3 filesystem.
=> [FLINK-34485] Add URI/Configuration constructor to DynamicTemporaryAWSCredentialsProvider

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/ExecNodeMetadataUtil.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/utils/ExecNodeMetadataUtilTest.java
`ExecNodeMetadataUtil` and `JsonSerdeUtil` have a circular dependency in their static initialization, which can cause a classloading lockup when 2 threads are running the class initialization of each class at the same time because during class initialization they hold a lock.
Break this dependency by moving `hasJsonCreatorAnnotation` to `ExecNodeMetadataUtil`.
=> [FLINK-34496] Break circular dependency in static initializatio

docs/README.md, docs/build_docs.sh, docs/setup_docs.sh
The current build process of Flink's documentation involves the `setup_docs.sh` script, which re-clones connector repositories every time the documentation is built. This operation is time-consuming, particularly for developers in regions with slower internet connections or facing network restrictions (like the Great Firewall in China). This results in a build process that can take an excessive amount of time, hindering developer productivity.
So, this pr is aims to add an arg to skip integrate connector docs in setup_docs.sh to improve build times. This arg `--skip-integrate-connector-docs` default is false, which mean we will default to integrate connector docs. If user want to disable integrate connector docs, he/she can run `./build_docs.sh --skip-integrate-connector-docs` in console. …
=> [FLINK-34362][docs] Add argument to skip integrate connector docs in setup_docs.sh to improve build times

flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Restarting.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StateWithExecutionGraph.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/RestartingTest.java
See [comment in FLINK-34518](https://issues.apache.org/jira/browse/FLINK-34518?focusedCommentId=17820679&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17820679) for more details.
* Overwrites the `ExecutionGraph`'s state when suspending the job in the `Restarting` phase: The actually state might be `CANCELLED` which can result in a HA data cleanup because it's a globally-terminal state which we don't want when restarting the job. The cancellation of the `ExecutionGraph` is more like an implementation detail of the `Restarting` state and shouldn't be exposed.
* Added unit test to cover this scenario …
=> [FLINK-34518][runtime] Fixes AdaptiveScheduler#suspend bug when the job is suspended during Restarting phase

flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Restarting.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StateWithExecutionGraph.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/RestartingTest.java
1.19 backport for parent PR #24382
=> [BP-1.19][FLINK-34518][runtime] Fixes AdaptiveScheduler#suspend bug when the job is suspended during Restarting phase

flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Restarting.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StateWithExecutionGraph.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/RestartingTest.java
1.18 backport for parent PR #24382
=> [BP-1.18][FLINK-34518][runtime] Fixes AdaptiveScheduler#suspend bug when the job is suspended during Restarting phase

docs/layouts/shortcodes/generated/rocksdb_configurable_configuration.html, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/EmbeddedRocksDBStateBackend.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBConfigurableOptions.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBIncrementalCheckpointUtils.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackendBuilder.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBIncrementalRestoreOperation.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBIncrementalCheckpointUtilsTest.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBRecoveryTest.java
This pull request cleans up useless sst files within rocksdb during rescaling, which reclaims local disk space, reducing the space amplification problem caused by deleteRange.
- Invoke Rocksdb.deleteFilesInRanges api to delele useless files during rescaling
This change is already covered by existing tests, such as RocksDBIncrementalCheckpointUtilsTest and RocksIncrementalCheckpointRescalingTest.
- Does …
=> [FLINK-34050][state] Clean up useless files in deleted ranges during rescaling for RocksdbStateBackend

flink-end-to-end-tests/test-scripts/common_yarn_docker.sh, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Restarting.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StateWithExecutionGraph.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/RestartingTest.java
1.17 backport for parent PR #24382
=> [BP-1.17][FLINK-34518][runtime] Fixes AdaptiveScheduler#suspend bug when the job is suspended during Restarting phase

flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
1.19 backport for parent PR #24238
=> [BP-1.19][FLINK-34274][runtime] Implicitly disable resource wait timeout for AdaptiveSchedulerTest

flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
1.18 backport for parent PR #24238
=> [BP-1.18][FLINK-34274][runtime] Implicitly disable resource wait timeout for AdaptiveSchedulerTest

docs/content/docs/connectors/table/formats/debezium.md
Add missing required option `'debezium-avro-confluent.url'` to Debezium AVRO documentation.
Updated the docs to include the above.  
As I result, I splitted JSON and AVRO in 2 sub-sections.
=> [FLINK-34509] [docs] add missing "url" option for Debezium Avro

flink-filesystems/flink-gs-fs-hadoop/src/main/java/org/apache/flink/fs/gs/GSFileSystemFactory.java
Avoid GSFileSystemFactory to log sensitive configurations
- Hide sensitive values and add test
Test: `org.apache.flink.fs.gs.GSFileSystemFactoryTest::testSkipSensitiveConf()`
=> [FLINK-34498][filesystem] GSFileSystemFactory should not log full Flink log

flink-filesystems/flink-gs-fs-hadoop/src/main/java/org/apache/flink/fs/gs/GSFileSystemFactory.java
This is 1.19 backport for parent PR https://github.com/apache/flink/pull/24372
=> [BP-1.19][FLINK-34498] GSFileSystemFactory should not log full Flink config

flink-core/src/main/java/org/apache/flink/configuration/Configuration.java, flink-core/src/test/java/org/apache/flink/configuration/ConfigurationTest.java
1.19 backport for parent PR #24370
=> [BP-1.19][FLINK-34499] Configuration#toString hides sensitive values

flink-core/src/main/java/org/apache/flink/configuration/Configuration.java, flink-core/src/test/java/org/apache/flink/configuration/ConfigurationTest.java
1.18 backport for parent PR #24370
=> [BP-1.18][FLINK-34499] Configuration#toString hides sensitive values

flink-core/src/main/java/org/apache/flink/configuration/Configuration.java, flink-core/src/test/java/org/apache/flink/configuration/ConfigurationTest.java
1.17 backport for parent PR #24370
=> [BP-1.17][FLINK-34499] Configuration#toString hides sensitive values

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/TableDescriptor.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/ShowCreateUtil.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/test/program/TableTestStep.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/TableDistribution.java
Implement TableDistribution toString
=> [FLINK-34469][table] Implement TableDistribution toString

flink-end-to-end-tests/flink-end-to-end-tests-jdbc-driver/pom.xml
This PR fixes IntelliJ errors when trying to compile `flink-end-to-end-tests-jdbc-driver` due to not declared dependencies to `flink-core` for example. …
=> [hotfix] Fix missing flink-end-to-end-tests-jdbc-driver dependency

flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManagerGateway.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/utils/TestingResourceManagerGateway.java
ResourceManagerGateway is internal class, so the deprecated method can be removed directly.
[hotfix][runtime] Remove unneeded requestTaskManagerFileUploadByName
=> [hotfix][runtime] Remove unneeded requestTaskManagerFileUploadByName

flink-table/flink-sql-jdbc-driver-bundle/pom.xml
Fix typo in <includes> configuration of maven-shade plugin for  flink-table/flink-sql-jdbc-driver-bundle pom
- update `<include>` in place of  `<incldue>`
=> [hotfix][table] Fix typo in maven shade configuration

flink-core/src/main/java/org/apache/flink/configuration/TraceOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/failover/ExecutionFailureHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultScheduler.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/failover/ExecutionFailureHandlerTest.java
To improve observability, we emit a span with the labels from our failure classification for each failure.
Added test coverage in `ExecutionFailureHandlerTest`.
- If yes, how is the feature documented? (docs )
=> [FLINK-34546] Emit span with failure labels on failure.

docs/content.zh/docs/dev/datastream/fault-tolerance/state.md, docs/content/docs/dev/datastream/fault-tolerance/state.md, flink-core/src/main/java/org/apache/flink/api/common/state/StateTtlConfig.java, flink-core/src/test/java/org/apache/flink/api/common/state/StateTtlConfigTest.java, flink-python/pyflink/datastream/state.py, flink-python/src/test/java/org/apache/flink/streaming/api/utils/ProtoUtilsTest.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/ttl/RocksDbTtlCompactFiltersManager.java
[FLINK-32570](https://issues.apache.org/jira/browse/FLINK-32570) deprecated the Time class and refactor all Public or PublicEvolving apis to use the Java's Duration.
StateTtlConfig.Builder#cleanupInRocksdbCompactFilter is still using the Time class. In general, we expect:
Mark cleanupInRocksdbCompactFilter(long, Time) as @Deprecated
Provide a new cleanupInRocksdbCompactFilter(long, Duration)
But I found this method is introduced in 1.19 ([FLINK-30854](https://issues.apache.org/jira/browse/FLINK-30854)), so a better solution may be: only provide cleanupInRocksdbCompactFilter(long, Duration) and don't use Time.
The deprecated Api should be keep for 2 minor version. IIUC, we cannot remove Time related class in Flink 2.0 if we don't deprecate it in 1.19. If …
=> [FLINK-34522][core] Changing the Time to Duration for StateTtlConfig.Builder.cleanupInRocksdbCompactFilter

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/PlannerCallProcedureOperation.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestProcedureCatalogFactory.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/ProcedureITCase.java
fix [FLINK-34517](https://issues.apache.org/jira/browse/FLINK-34517)
when passing StreamExecutionEnvironment in PlannerCallProcedureOperation.java , the env only contains the application-specific conf,  environment-specific config not included. 
As a result ,  environment-specific config doesn't work when executing procedure operation, which is not expected, the test case illustrates the problem.
A new test method was added to ProcedureITCase.
The public API, i.e., is any changed class annotated with @Public(Evolving): no
The runtime per-record code paths (performance sensitive): no
Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
The S3 …
=> [FLINK-34517][table]fix environment configs ignored when calling procedure operation

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/lineage/DatasetConfigFacet.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/lineage/DatasetSchemaFacet.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/lineage/DatasetSchemaField.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/lineage/DefaultLineageGraph.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/lineage/LineageDataset.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/lineage/LineageDatasetFacet.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/lineage/LineageEdge.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/lineage/LineageGraph.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/lineage/LineageVertex.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/lineage/SourceLineageVertex.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/lineage/DefaultLineageGraphTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/lineage/LineageGraphTest.java
This PR aims to add lineage graph relevant interfaces such as `LineageGraph`, `LineageVertex`, `SourceLineageVertex` and `LineageEdge`
- Add lineage graph relevant interfaces
- Add default lineage graph implementation
- Added test `LineageGraphTest`
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no) yes
- The S3 file system connector: (yes / no / …
=> [FLINK-33210] Introduce lineage graph relevant interfaces

flink-clients/src/main/java/org/apache/flink/client/program/PackagedProgram.java, flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/handlers/utils/JarHandlerUtils.java, flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/handlers/utils/JarHandlerUtilsTest.java
Fixes a bug when during REST job deploy the `pipeline.classpaths` config value gets erased.
- Write back the original `pipeline.classpaths` value during `applyToConfiguration`.
- Add a getter for the classpath field in `PackagedProgram.Builder` to make changes testable with a reasonable effort.
Added unit tests to cover the changed logic.
- If yes, how …
=> [FLINK-34580][rest] Do not erase "pipeline.classpaths" config during REST job deploy

docs/content.zh/docs/dev/datastream/execution_mode.md
fix typo in execution_mode.md
- Replace `execute.runtime-mode` with `execution.runtime-mode` in Chinese documents
=> [FLINK-34622][docs] fix typo in execution_mode.md

flink-core/src/main/java/org/apache/flink/api/common/time/Time.java
Correct the Javadoc of `org.apache.flink.api.common.time.Time`
Correct the Javadoc of `org.apache.flink.api.common.time.Time`
=> [FLINK-34617][docs] Correct the Javadoc of org.apache.flink.api.common.time.Time

flink-end-to-end-tests/test-scripts/common.sh, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/StateHandleDownloadSpec.java
Fixing a couple of smaller issues.
Please check individual commit messages. …
=> [hotfix] A couple of hotfixes related to e2e tests

flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/streaming/util/TestStreamEnvironment.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/AutoRescalingITCase.java, flink-tests/src/test/java/org/apache/flink/test/state/ChangelogRescalingITCase.java
Enable local recovery in ChangelogRescalingITCase, since the local recovery of changelog state backend was supported by [FLINK-27693](https://issues.apache.org/jira/browse/FLINK-27693) and [FLINK-27692](https://issues.apache.org/jira/browse/FLINK-27692).
- Enable local recovery in ChangelogRescalingITCase
- Remove the changelog configuration check from TestStreamEnvironment …
=> [FLINK-34624][state/changelog] Enable local recovery in ChangelogRescalingITCase

flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBResourceContainer.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateBackendConfigTest.java
[FLINK-33798][statebackend/rocksdb] automatically clean up rocksdb logs when the task exited.
When the task exits, delete all rocksdb log files with the same prefix in the relocated directory.
- org.apache.flink.contrib.streaming.state.RocksDBStateBackendConfigTest#testCleanRelocatedDbLogs …
=>  [FLINK-33798][statebackend/rocksdb] automatically clean up rocksdb logs when the task exited.

flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/streaming/util/TestStreamEnvironment.java
AutoRescalingITCase#testCheckpointRescalingInKeyedState AssertionError:
```
expected:<[(0,8000), (0,32000), (0,48000), (0,72000), (1,78000), (1,30000), (1,54000), (0,2000), (0,10000), (0,50000), (0,66000), (0,74000), (0,82000), (1,80000), (1,0), (1,16000), (1,24000), (1,40000), (1,56000), (1,64000), (0,12000), (0,28000), (0,52000), (0,60000), (0,68000), (0,76000), (1,18000), (1,26000), (1,34000), (1,42000), (1,58000), (0,6000), (0,14000), (0,22000), (0,38000), (0,46000), (0,62000), (0,70000), (1,4000), (1,20000), (1,36000), (1,44000)]> but was:<[(0,8000), (0,32000), (0,48000), (0,72000), (1,78000), (1,30000), (1,54000), (0,2000), (0,10000), (0,50000), (0,66000), (0,74000), (0,82000), (0,23000), (0,31000), (1,80000), (1,0), (1,16000), (1,24000), (1,40000), (1,56000), (1,64000), (0,12000), …
```
=> [FLINK-34660][checkpoint] Avoid randomizing changelog-related config when it's pre-defined

flink-core/src/test/java/org/apache/flink/api/common/eventtime/WatermarkStrategyTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorMasterHooksTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTestingUtils.java
Replace DummyMetricGroup usage with UnregisteredMetricsGroup
- Remove DummyMetricGroup and replace it with UnregisteredMetricsGroup
=> [FLINK-34640][metrics] Replace DummyMetricGroup usage with UnregisteredMetricsGroup

flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/failover/ExecutionFailureHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Canceling.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Executing.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Failing.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/JobFailureMetricReporter.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Restarting.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StateWithExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StopWithSavepoint.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/failover/ExecutionFailureHandlerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/ExecutingTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StateWithExecutionGraphTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StopWithSavepointTest.java
Adding span for job failure with failure label to adaptive scheduler as well.
- If yes, how is the feature documented? (already documented)
=> [FLINK-34546] Emit span with failure labels on failure in AdaptiveScheduler.

.github/workflows/docs.yml, azure-pipelines.yml, tools/azure-pipelines/build-apache-repo.yml
The GitHub Actions workflow (FLINK-33901) requires us to upgrade to Ubuntu 22.04 (or 20.04) (see further details in sub-issue FLINK-33923). The Azure Pipeline's Docker image is currently relying on 16.04. The e2e tests in the Azure Pipeline are actually relying on 20.04.
This PR is about aligning all these workflow with what we're planning to use for GitHub Actions.
The corresponding Dockerfile changes can be reviewed https://github.com/zentol/flink-ci-docker/pull/4.
We might want to wait with this change till after 1.19 was released to avoid running into suprises during the release. :thinking: 
* Updates Docker container to use `mapohl/flink-ci:FLINK-34914`
* Updates test pool vmImage from 20.04 to 22.04
* CI should pass
- The …
=> [FLINK-34194][ci] Updates test CI container to be based on Ubuntu 22.04

flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/streamrecord/StreamRecordTest.java
[FLINK-34719][streaming] Fix unstable test StreamRecordTest.testWithTimestamp above jdk8
Fix unstable test StreamRecordTest.testWithTimestamp above jdk8
use jdk11
mvn test -Dtest=oorg.apache.flink.streaming.runtime.streamrecord.StreamRecordTest
=> [FLINK-34719][streaming] Fix unstable test StreamRecordTest.testWithTimestamp above jdk8

flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/FileSystemOutputFormat.java, flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/FileSystemTableSink.java, flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/table/FileSystemOutputFormatTest.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveTableSink.java
This PR is cherry-picked from https://github.com/apache/flink/pull/24390
- Fix unstable TableSourceITCase#testTableHintWithLogicalTableScanReuse
- Moves the staging dir configuration into builder for easier testing
FileSystemOutputFormatTest#testGetUniqueStagingDirectory
=> [FLINK-29114][connector][filesystem] Fix issue of file overwriting caused by multiple writes to the same sink table and shared staging directory 

flink-core/src/main/java/org/apache/flink/core/memory/DataInputDeserializer.java, flink-core/src/main/java/org/apache/flink/core/memory/DataOutputSerializer.java, flink-core/src/test/java/org/apache/flink/core/memory/DataInputOutputSerializerTest.java
Add a way to serialize UTF8 strings where the resulting byte array is longer than 64k
- Added DataOutputSerializer.writeLongUTF
- Added DataInputDeserializer.readLongUTF
- Added DataInputOutputSerializerTest.testLongUTFWriteRead unit test
=> [FLINK-34228] Add long UTF serializer/deserializer

flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/KeyedPartitionWindowedStreamITCase.java, flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/NonKeyedPartitionWindowedStreamITCase.java
* Some of the new tests for the unit tests introduced in FLINK-34543 are failing in the **adaptive scheduler** stage.  These operators are not suitable for the adaptive scheduler and should be excluded.
Add `@Tag` to exclude the `KeyedPartitionWindowedStreamITCase` and `NonKeyedPartitionWindowedStreamITCase`.
This change can be verified in the Azure and GitHub Actions pipeline by verifying the execution of a full build: they should be run in stages that don't have the system property "flink.tests.enable-adaptive-scheduler" set to true (and definitely excluded from the **adaptive scheduler** stage)
- The runtime …
=> [FLINK-34718][tests] Exclude operators not meant for adaptive scheduler

pom.xml
There's a missing brace in the root `pom.xml` that would ignore any tests that should be excluded on a specific JDK version (`FailsOnJavaXxx`) when the `enable-adaptive-scheduler` profile is enabled.  There currently aren't any, but this should be corrected (and maybe backported)?
Add the missing brace. …
=> [hotfix] Fix maven property typo in root pom.xml

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/FlinkCalciteSqlValidator.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/join/TemporalJoinTest.scala
The provided SQLs are invalid, however the current code base fails on unexpected locations giving unhelpful messages. This PR improves the validation which results in proper error messages.
Added tests. …
=> [FLINK-34745] Improve validations for a period in Time Travel

flink-libraries/flink-cep/src/main/java/org/apache/flink/cep/nfa/sharedbuffer/SharedBuffer.java, flink-libraries/flink-cep/src/main/java/org/apache/flink/cep/operator/CepOperator.java, flink-libraries/flink-cep/src/test/java/org/apache/flink/cep/nfa/NFAStateAccessTest.java
Resolve memory leak issue of CEP operator caused by NFA State and SharedBuffer.eventsCount. Details have been added to [32701](https://issues.apache.org/jira/browse/FLINK-32701)
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.flink.cep.nfa.DeweyNumberTest
[INFO] Running org.apache.flink.cep.nfa.NFAStateAccessTest
[INFO] Running org.apache.flink.cep.nfa.NFATest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.017 s -- in org.apache.flink.cep.nfa.DeweyNumberTest
[INFO] Running org.apache.flink.cep.nfa.NFAIterativeConditionTimeContextTest
[INFO] Running …
```
=> [Flink 32701] [cep] Fix CEP Operator Memory Leak Issue 

docs/config.toml
=> [FLINK-34706][docs] Deprecates 1.17 docs.

docs/content.zh/docs/flinkDev/ide_setup.md, docs/content/docs/flinkDev/ide_setup.md, flink-core/src/main/java/org/apache/flink/api/common/operators/util/ListKeyGroupedIterator.java, flink-core/src/main/java/org/apache/flink/core/memory/ByteArrayOutputStreamWithPos.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/SequentialChannelStateReader.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/JobPlanHandler.java, flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogState.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/operation/OperationExecutor.java, pom.xml, tools/maven/checkstyle.xml
The issue with current checkstyle is that there is checkstyle IntellijIdea plugin
And recently it dropped checkstyle 8 support [1]
At the same time we can not move to Checkstyle 10 since 10.x requires java 11+
Also it moves version to properties to allow build with different checkstyle versions
for instance after this PR it would be possible to build with checkstyle 10 as well (leveraging jdk11+)
like `mvn clean install -DskipTests -Dcheckstyle.version=10.14.2`
[1] https://github.com/jshiell/checkstyle-idea/blob/main/CHANGELOG.md …
=>  [FLINK-34893] Bump checkstyle to 9.3 

.github/workflows/docs.yml
Sync the docs build changes with 1.19  https://github.com/apache/flink/pull/24518
=> [FLINK-34716][release] Build 1.19 docs in GitHub Action and mark 1.19 as stable in docs

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/JoinTableFunctionScanToCorrelateRule.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/join/WindowJoinTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/join/WindowJoinTest.scala
Fix support for 
```
SELECT * FROM
TABLE(TUMBLE....)
JOIN
TABLE(TUMBLE...) 
```
without enclosing the tables with a `SELECT * FROM`
Make the `JoinTableFunctionScanToCorrelateRule` stricter so that it converts Joins that have a chance to pass the corresponding `StreamPhysicalConstantTableFunctionScanRule` rule.
Added a test …
=> [FLINK-34910] Fix optimizing window join

pom.xml
This japicmp configuration update is one step for `Promote the release` https://cwiki.apache.org/confluence/display/FLINK/Creating+a+Flink+Release
=> [FLINK-34707] Update japicmp configuration for 1.19

flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/testutils/logging/LoggerAuditingExtension.java, flink-tests/src/test/java/org/apache/flink/test/misc/JobIDLoggingITCase.java
=> [FLINK-34643] Fix concurrency issue in LoggerAuditingExtension

flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java, flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManager.java, flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/ResourceManagerJobMasterTest.java
* This pull request makes job restart more quickly by `disconnectTaskManager` actively in ResourceManager.
- *Disconnect TaskManager in ResourceManager actively*
- Add new unit test `testDisconnectTaskManagerInResourceManager()`
- *Manually verified the change by running a datagen print job, verifying that recovery is faster than before.*  
- ![image](https://github.com/apache/flink/assets/1277293/6128b07b-f988-4958-a515-e57fbe20ec89)
- parallelism = 100 && taskmanager.numberOfTaskSlots = 2 && disable checkpoint
- Dependencies (does it add …
=> [FLINK-34526][runtime] Actively disconnect the TM in RM to reduce restart time

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/SubTaskInitializationMetricsBuilder.java, flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/streaming/util/TestStreamEnvironment.java
This change is currently not tested, as the code path is permanently disabled waiting for FRocksDB release. In the future that will be covered by existing ITCases. …
=> [FLINK-34913][metrics][state] Fix ConcurrentModificationException in SubTaskInitializationMetricsBuilder.addDurationMetric

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/calcite/PreValidateReWriter.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/calcite/FlinkCalciteSqlValidatorTest.java
Column mismatch validation error should not throw IndexOutOfBoundsException
- Check column mismatch for SELECT and VALUES clauses
-  Add tests
`org.apache.flink.table.planner.calcite. FlinkCalciteSqlValidatorTest`
- The serializers: (no
=> [FLINK-34902][table] Fix column mismatch IndexOutOfBoundsException

flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/src/FileSourceTextLinesITCase.java, flink-end-to-end-tests/run-nightly-tests.sh, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java, flink-tests/src/test/java/org/apache/flink/test/runtime/DefaultSchedulerLocalRecoveryITCase.java
1.19 backport for parent PR #24285
=> [BP-1.19][FLINK-34409][ci] Enables (most) tests that were disabled for the AdaptiveScheduler due to missing features

flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/src/FileSourceTextLinesITCase.java, flink-end-to-end-tests/run-nightly-tests.sh, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java, flink-tests/src/test/java/org/apache/flink/test/runtime/DefaultSchedulerLocalRecoveryITCase.java
1.18 backport for parent PR #24285
=> [BP-1.18][FLINK-34409][ci] Enables (most) tests that were disabled for the AdaptiveScheduler due to missing features

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/DefaultOperatorStateBackendSnapshotStrategy.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/filemerging/DirectoryStreamStateHandle.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/filemerging/EmptyFileMergingOperatorStreamStateHandle.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/filemerging/EmptySegmentFileStateHandle.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/filemerging/FileMergingOperatorStreamStateHandle.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/filemerging/SegmentFileStateHandle.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FileMergingCheckpointStateOutputStream.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsMergingCheckpointStorageLocation.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/AcrossCheckpointFileMergingSnapshotManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerTestBase.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/WithinCheckpointFileMergingSnapshotManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/OperatorStateBackendTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/SharedStateRegistryTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/filesystem/FileMergingCheckpointStateOutputStreamTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/filesystem/FsMergingCheckpointStorageLocationTest.java
Operator states are stored in `taskownd/` dir when file merging is enabled, this PR reports the operator state handle of file merging directory to JM `SharedStateRegistry`. 
- Introduce `FileMergingOperatorStreamStateHandle` , `EmptyFileMergingOperatorStreamStateHandle` and `DirectoryStreamStateHandle`.
- Still report file merging directory to JM even if operator state is empty.
- `OperatorStateBackendTest#testFileMergingSnapshotEmpty` …
=> [FLINK-34668][checkpoint] Report state handle of file merging directory to JM

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/CheckpointingMode.java, flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/testsuites/SinkTestSuiteBase.java, flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/utils/CollectIteratorAssert.java
The PR introduces `CollectIteratorAssert#matchesRecordsFromSource` and `SinkTestSuiteBase#checkResultWithSemantic` with former signature to make downstream projects (e.g. flink-connector-elasticsearch compilable)
- Dependencies (does it add or upgrade a dependency): (/ no)
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes )
=> [FLINK-34941][checkpoint] Add `CollectIteratorAssert#matchesRecordsFromSource` and `SinkTestSuiteBase#checkResultWithSemantic` with former signature

flink-table/flink-table-planner/src/main/java/org/apache/calcite/sql/type/SqlTypeFactoryImpl.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/ComparisonFunctionITCase.java
Fixes how SQL comparison functions work for TIMESTAMP types.
Added tests in `ComparisonFunctionsITCase`.
=> [FLINK-34938] Fix incorrect behaviour for comparison functions

flink-dstl/flink-dstl-dfs/src/test/java/org/apache/flink/changelog/fs/RetryingExecutorTest.java
backport of https://github.com/apache/flink/pull/24569 to 1.19
=> [BP-1.19][FLINK-26515][tests] Fix RetryingExecutorTest

flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterServiceLeadershipRunnerTest.java
It seems like I disabled the test accidentally with FLINK-31783. This PR re-enables the test (and fixes it).
* Enables test again
* Makes the test wait for the leadership being confirmed by polling the leader information in the HA backend rather than relying on `hasLeadership`
- If …
=> [FLINK-34897][test] Enables JobMasterServiceLeadershipRunnerTest#testJobMasterServiceLeadershipRunnerCloseWhenElectionServiceGrantLeaderShip again.

docs/layouts/shortcodes/config_file.html, docs/layouts/shortcodes/config_file_zh.html
The Config type is Boolean, but it should be Duration.
https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/config/
- [FLINK-34956][doc] Fix the config type wrong of Duration
=> [FLINK-34956][doc] Fix the config type wrong of Duration

docs/layouts/shortcodes/generated/high_availability_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/HighAvailabilityOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/util/ZooKeeperUtils.java
This PR introduces new configuration options for Flink and Curator configurations, such as:
* authorization - option which expose to allow additional AuthInfo records as part of the connect
* maxCloseWaitMs - Ability that would enable the user to adjust to different network speeds.
* simulatedSessionExpirationPercent - Additional checking for Session expiration above what is provided by ZooKeeper.
Such configuration has been proposed as part of [FLIP-402](https://cwiki.apache.org/confluence/display/FLINK/FLIP-402%3A+Extend+ZooKeeper+Curator+configurations).
* Adds a new configurations into HighAvailabilityOptions
* In case if newly added configs are configured, they are invoking appropriate builder method during Curator connection creation
* If no configuration are passed, no new …
=> [FLINK-33376][coordination] Extend ZooKeeper Curator configurations

flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/JobExceptionsHandler.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/job/JobExceptionsHandlerTest.java, flink-tests/src/test/java/org/apache/flink/test/scheduling/AdaptiveSchedulerITCase.java
The REST API was incorrectly asserting that no concurrent global failures can occur in the exception history
=> [FLINK-34922][rest] Support concurrent global failure

flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterServiceLeadershipRunnerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/TestingJobMasterServiceProcess.java
1.19 backport PR for parent PR #24562
=> [BP-1.19][FLINK-34933][test] Fixes JobMasterServiceLeadershipRunnerTest#testResultFutureCompletionOfOutdatedLeaderIsIgnored

flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterServiceLeadershipRunnerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/TestingJobMasterServiceProcess.java
1.18 backport PR for parent PR #24562
=> [BP-1.18][FLINK-34933][test] Fixes JobMasterServiceLeadershipRunnerTest#testResultFutureCompletionOfOutdatedLeaderIsIgnored

docs/content.zh/docs/connectors/table/formats/debezium.md
Translate the new addition on "Debezium Format" page into Chinese, the new addition mainly adds missing required option 'debezium-avro-confluent.url' to Debezium AVRO documentation (See [Flink-34509](https://issues.apache.org/jira/browse/FLINK-34509) for details).
The page url is https://nightlies.apache.org/flink/flink-docs-master/docs/connectors/table/formats/debezium/
The markdown file is located in `flink/docs/content.zh/docs/connectors/table/formats/debezium.md`
- Translate the new addition in `flink/docs/content.zh/docs/connectors/table/formats/debezium.md`, in which the cases of both JSON and AVRO formats are described separately.
- The public API, …
=> [FLINK-34562][docs-zh] Port Debezium Avro Confluent changes (FLINK-34509) to Chinese

flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/CompileAndExecuteRemotePlanITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/CreateTableAsITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/HdfsITCaseBase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/PlannerScalaFreeITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/SqlITCaseBase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/UsingRemoteJarITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/resources/watermark_push_down_e2e.sql, flink-end-to-end-tests/flink-sql-client-test/pom.xml, flink-end-to-end-tests/flink-sql-client-test/src/main/java/org/apache/flink/table/toolbox/TestScanTableSourceWithWatermarkPushDown.java, flink-end-to-end-tests/flink-sql-client-test/src/main/java/org/apache/flink/table/toolbox/TestScanTableSourceWithWatermarkPushDownFactory.java, flink-end-to-end-tests/flink-sql-client-test/src/main/java/org/apache/flink/table/toolbox/TestSourceFunction.java, flink-end-to-end-tests/flink-sql-client-test/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/WatermarkGeneratorCodeGenerator.scala, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/generated/WatermarkGeneratorCodeGeneratorFunctionContextWrapper.java
The code generated by codegen references the class in the table-planner package, but the class in the table-planner package is hidden by table-planner-loader, so classloader cannot find it. 
This pr moves the referred class `WatermarkGeneratorCodeGeneratorFunctionContextWrapper` from table-planner to table-runtime. 
- *Moves the class `WatermarkGeneratorCodeGeneratorFunctionContextWrapper` from table-planner to table-runtime*
This pr can't be verified by IT cases or UT cases because the bug only can be -reproduced without jar `table-planner`.
So we need to verify this pr manually. The following steps can verify it.
1. run a kafka and prepare some data
You can start …
=> [FLINK-28693][table] Fix janino compile failed because the code generated refers the class in table-planner

flink-dist/src/main/resources/META-INF/NOTICE, flink-end-to-end-tests/flink-sql-client-test/pom.xml, flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE, flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE, flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE, flink-formats/flink-sql-avro/src/main/resources/META-INF/NOTICE, flink-python/pom.xml, flink-table/flink-table-planner/src/main/resources/META-INF/NOTICE, pom.xml
Backporting https://github.com/apache/flink/pull/24580 to 1.19.
cc @slfan1989
=> [BP-1.19][FLINK-34955] Upgrade commons-compress to 1.26.0.

.github/PULL_REQUEST_TEMPLATE.md
The website update changed the anchor format causing the PullRequest template link to not point to the right location.
* Updates link in PR template
=> [FLINK-35000][build] Updates link to test code convention in pull request template

flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java, flink-tests/src/test/java/org/apache/flink/test/misc/JobIDLoggingITCase.java
=> [FLINK-34994][tests] Ignore unknown task checkpoint confirmation log in JobIDLoggingITCase

flink-table/flink-sql-jdbc-driver-bundle/pom.xml
=> [backport][hotfix][table] Fix typo in maven shade configuration

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/AggregateQueryOperation.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/QueryOperationSqlExecutionTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/QueryOperationSqlSerializationTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/QueryOperationTestPrograms.java
Fixes the bug that `AggregateQueryOperation` produces a wrong SQL if there were no explicit groupings provided
Added tests
=> [FLINK-35021] AggregateQueryOperations produces wrong asSerializableString representation

flink-runtime-web/web-dashboard/src/app/components/dagre/components/node/node.component.html, flink-runtime-web/web-dashboard/src/app/components/dagre/components/node/node.component.ts, flink-runtime-web/web-dashboard/src/app/interfaces/job-detail.ts, flink-runtime-web/web-dashboard/src/app/interfaces/job-metrics.ts, flink-runtime-web/web-dashboard/src/app/pages/job/dataskew/data-skew.component.html, flink-runtime-web/web-dashboard/src/app/pages/job/dataskew/data-skew.component.less, flink-runtime-web/web-dashboard/src/app/pages/job/dataskew/data-skew.component.ts, flink-runtime-web/web-dashboard/src/app/pages/job/modules/completed-job/routes.ts, flink-runtime-web/web-dashboard/src/app/pages/job/modules/running-job/routes.ts, flink-runtime-web/web-dashboard/src/app/pages/job/overview/job-overview.component.ts, flink-runtime-web/web-dashboard/src/app/services/metrics.service.ts, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/metrics/AbstractAggregatingMetricsHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/metrics/DoubleAccumulator.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/metrics/AggregatedMetric.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/metrics/MetricsAggregationParameter.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/job/metrics/AggregatingMetricsHandlerTestBase.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/job/metrics/DoubleAccumulatorTest.java
This PR implements the discussed and accepted FLIP [FLIP-418](https://cwiki.apache.org/confluence/display/FLINK/FLIP-418%3A+Show+data+skew+score+on+Flink+Dashboard): i) it shows a live data skew percentage on the vertices under "Overview" tab on the Flink Dashboard, ii) it also adds a new Data Skew tab that shows the accumulated data skew percentage for each vertex since the beginning of job. This will help users find inefficient/skewed operators/vertices faster. As it is, users have to click on each and every vertex, check how much data each subtask is processing and compare it to the other subtasks. This is cumbersome and indeed error-prone.
- Add a new aggregation type (Data Skew) to `AbstractAggregatingMetricsHandler`. 
- Use the new aggregation type with the `numRecordsInPerSecond` …
=> [FLINK-34025][runtime / web frontend] Add data skew metric endpoint and UI

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/lineage/LineageVertexProvider.java
Add lineage provider interface for flink connector to expose lineage info.
- Add LineageVertexProvider interface
This change is a trivial new interface, no test.
=> [FLINK-34657] add lineage provider API

flink-streaming-java/src/test/java/org/apache/flink/streaming/util/MockDeserializationSchema.java
[FLINK-35011][tests] Change MockDeserializationSchema's visibility to public to prevent compilation failure in kafka connector
https://github.com/apache/flink-connector-kafka/actions/runs/8553981349/job/23438292087?pr=90#step:15:165
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:testCompile (default-testCompile) on project flink-connector-kafka: Compilation failure
Error:  /home/runner/work/flink-connector-kafka/flink-connector-kafka/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaConsumerBaseTest.java:[60,39] org.apache.flink.streaming.util.MockDeserializationSchema is not public in org.apache.flink.streaming.util; cannot be accessed from outside package
```
This problem was introduced by #24432.
Rollback …
=> [FLINK-35011][tests] Change MockDeserializationSchema's visibility to public to prevent compilation failure in kafka connector

flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/CompileAndExecuteRemotePlanITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/CreateTableAsITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/HdfsITCaseBase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/PlannerScalaFreeITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/SqlITCaseBase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/UsingRemoteJarITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/resources/watermark_push_down_e2e.sql, flink-end-to-end-tests/flink-sql-client-test/pom.xml, flink-end-to-end-tests/flink-sql-client-test/src/main/java/org/apache/flink/table/toolbox/TestScanTableSourceWithWatermarkPushDown.java, flink-end-to-end-tests/flink-sql-client-test/src/main/java/org/apache/flink/table/toolbox/TestScanTableSourceWithWatermarkPushDownFactory.java, flink-end-to-end-tests/flink-sql-client-test/src/main/java/org/apache/flink/table/toolbox/TestSourceFunction.java, flink-end-to-end-tests/flink-sql-client-test/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/WatermarkGeneratorCodeGenerator.scala, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/generated/WatermarkGeneratorCodeGeneratorFunctionContextWrapper.java
This is a cherry-pick backport of https://github.com/apache/flink/pull/24280 to 1.18
=> [BP-1.18][FLINK-28693][table] Janino compile failed because of the generated code refers a class in table-planner

docs/content.zh/docs/ops/metrics.md, docs/content/docs/ops/metrics.md, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricNames.java, flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/TaskIOMetricGroup.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/InternalTimeServiceManager.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/InternalTimeServiceManagerImpl.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/InternalTimerServiceImpl.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/StreamTaskStateInitializerImpl.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionInternalTimeServiceManager.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/InternalTimerServiceImplTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/StateInitializationContextImplTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/StreamTaskStateInitializerImplTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionInternalTimeServiceTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/util/AbstractStreamOperatorTestHarness.java, flink-tests/src/test/java/org/apache/flink/test/state/operator/restore/StreamOperatorSnapshotRestoreTest.java
This PR adds numFiredTimers and numFiredTimersPerSecond metrics
-
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / **n**o / don't know)
=> [FLINK-35065][metrics] Add numFiredTimers and numFiredTimersPerSecond

flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/CompileAndExecuteRemotePlanITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/CreateTableAsITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/HdfsITCaseBase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/PlannerScalaFreeITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/SqlITCaseBase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/UsingRemoteJarITCase.java, flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/resources/watermark_push_down_e2e.sql, flink-end-to-end-tests/flink-sql-client-test/pom.xml, flink-end-to-end-tests/flink-sql-client-test/src/main/java/org/apache/flink/table/toolbox/TestScanTableSourceWithWatermarkPushDown.java, flink-end-to-end-tests/flink-sql-client-test/src/main/java/org/apache/flink/table/toolbox/TestScanTableSourceWithWatermarkPushDownFactory.java, flink-end-to-end-tests/flink-sql-client-test/src/main/java/org/apache/flink/table/toolbox/TestSourceFunction.java, flink-end-to-end-tests/flink-sql-client-test/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/WatermarkGeneratorCodeGenerator.scala, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/generated/WatermarkGeneratorCodeGeneratorFunctionContextWrapper.java
This is a cherry-pick backport of https://github.com/apache/flink/pull/24280 to 1.19
=> [BP-1.19][FLINK-28693][table] Janino compile failed because of the generated code refers a class in table-planner

flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNApplicationITCase.java
For JDK 17+, some configuration is necessary to use the Datastream V2 (FLINK-34548 and FLIP-409).  This was added to `surefire.module.config` for most of the necessary tests.  The `flink-yarn-tests` spawn new processes (notably JobManager) which should take into account the same configuration as other surefire tests.
* Copy the `surefire.module.config` property into the `env.java.opts.all` Flink configuration when running a new test cluster.
This change fixes an existing test: `YARNApplicationITCase`. …
=> [FLINK-35023][tests] Use surefire.module.config in yarn-test

flink-formats/flink-parquet/pom.xml, flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/avro/AvroParquetRecordFormat.java
Allow passing hadoop config into parquet reader
- Change AvroParquetRecordFormat to take hadoop config in AvroParquetReader builder.
=> [FLINK-35015][formats] allow passing hadoop config into parquet reader

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/CheckpointingMode.java, flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/external/sink/TestingSinkSettings.java, flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/external/source/TestingSourceSettings.java, flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/junit/annotations/TestSemantics.java, flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/junit/extensions/ConnectorTestingExtension.java, flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/utils/UnorderedCollectIteratorAssert.java
After FLINK-34516, the `org.apache.flink.streaming.api.CheckpointingMode` has been moved to `org.apache.flink.core.execution.CheckpointingMode`. It introduced a breaking change to connector testing framework as well as to externalized connector repos by mistake. This PR fix this by providing methods with old signatures.
- Provide methods with old signatures in `TestingSinkSettings` and `TestingSourceSettings`
- Support old `CheckpointingMode` in annotation `TestSemantics`, add fallback logic in `ConnectorTestingExtension`.
This change can be verified manually in downstream projects, such as the kafka connector.
- The runtime …
=> [FLINK-35060][Test/Connector] Provide compatibility of old CheckpointMode for connector testing framework

docs/content.zh/docs/connectors/table/formats/avro.md, docs/content/docs/connectors/table/formats/avro.md
Add the missing new Avro option in corresponding doc.
- Add new option in avro.md
This change is a trivial doc change without any test coverage.
=> [FLINK-34250][docs] add new option for avro format docs

flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterThrottlingTest.java
Refactor `AsyncSinkWriterThrottlingTest` to flush when reaching batch sizes without changing processing time. The changes of processing time are in fact not needed for this test and are causing flakiness due to reference of timer call back from external thread.
- refactored `AsyncSinkWriterThrottlingTest` to send all batch data without change in timer service.
- The serializers:no …
=> [FLINK-31472] Remove external timer service reference from AsyncSinkThrottling Test

flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterThrottlingTest.java
Refactor `AsyncSinkWriterThrottlingTest` to flush when reaching batch sizes without changing processing time. The changes of processing time are in fact not needed for this test and are causing flakiness due to reference of timer call back from external thread.
- refactored `AsyncSinkWriterThrottlingTest` to send all batch data without change in timer service.
- The serializers:no …
=> [FLINK-31472][connectors/base] Remove external timer service reference from AsyncSinkThrottling Test

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/ContextStateFutureImpl.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/KeyAccountingUnit.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/RecordContext.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateFutureFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateRequest.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateRequestBuffer.java, flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionControllerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/ContextStateFutureImplTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/KeyAccountingUnitTest.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractInput.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperatorV2.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/RecordProcessorUtils.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperatorV2.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AsyncStateProcessing.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AsyncStateProcessingOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/ElementOrder.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperatorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperatorV2Test.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/multipleinput/input/FirstInputOfTwoInput.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/multipleinput/input/OneInput.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/multipleinput/input/SecondInputOfTwoInput.java
As part of the async execution model of disaggregated state management, this PR gives the basic definition of `StreamingOperator` integrated with async execution.
The philosophy behind this PR is **we are trying NOT to invade the previous code path**. The most strict thing is that **it MUST NOT affect any _hot path_ without this feature**.
By the way, the type parameter of record around `AsyncExecutionController` is erased, since the stream operator does not have the knowledge of record type, and the `AEC` does not need it.
- Erase the type parameter of record around `AsyncExecutionController` 
- Define the `AbstractAsyncStateStreamOperator` and `AbstractAsyncStateStreamOperatorV2` corresponding to the `AbstracStreamOperator` and `AbstracStreamOperatorV2` respectively.
- Wire the record …
=> [FLINK-35025][Runtime/State] Abstract stream operators for async state processing

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/CreatingExecutionGraph.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/CreatingExecutionGraphTest.java
Transitioning the ExecutionGraph to running implicitly starts periodic checkpoint triggering. This should only occur after the all initialization steps have occurred.
The existing code could leak the CheckpointCoordinator if '#handleExecutionGraphCreation' fails to 'tryToAssignSlots'; this eventually leads to a checkpoint being triggered for old ExecutionGraph for which the operator holders were not initialized yet, which causes an exception that crashes the JM.
~~We now force this to happen in the `Executing` constructor, at which point all the initialization steps must already be complete, and we can be sure that the EG gets transitioned into a terminal state when an error occurs (implicitly disabling checkpointing again).~~
We now do this only after slots have been assigned, right …
=> [FLINK-35159] Transition ExecutionGraph to RUNNING after slot assignment

flink-core/src/main/java/org/apache/flink/api/java/typeutils/runtime/NoFetchingInput.java
Handle edge case of zero length serialized bytes correctly.
Bug fix in kryo (NoFetching)Input implementation to handle properly zero length serialized bytes, eg the serialization of a protobuf message with default values.
- Fix while loop for `NoFetchingInput#read(byte[], int, int)` and `NoFetchingInput#require(int)`
- Does this …
=> [FLINK-34954][core] Kryo Input bug fix

docs/content.zh/docs/deployment/config.md, docs/content.zh/docs/deployment/resource-providers/native_kubernetes.md, docs/content/docs/deployment/config.md, docs/content/docs/deployment/resource-providers/native_kubernetes.md, docs/layouts/shortcodes/generated/kubernetes_config_configuration.html, flink-clients/src/main/java/org/apache/flink/client/program/artifact/ArtifactFetchManager.java, flink-clients/src/test/java/org/apache/flink/client/program/artifact/ArtifactFetchManagerTest.java, flink-core/src/test/java/org/apache/flink/testutils/TestingUtils.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/KubernetesClusterClientFactory.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/KubernetesClusterDescriptor.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/artifact/DefaultKubernetesArtifactUploader.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/artifact/KubernetesArtifactUploader.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/configuration/KubernetesConfigOptions.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/KubernetesClusterDescriptorTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/artifact/DefaultKubernetesArtifactUploaderTest.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/artifact/DummyFs.java, flink-kubernetes/src/test/java/org/apache/flink/kubernetes/artifact/DummyFsFactory.java, flink-kubernetes/src/test/resources/META-INF/services/org.apache.flink.core.fs.FileSystemFactory
Makes it possible to upload `local://` artifacts in K8s Application Mode to remote DFS, so combined with `Artifact Fetching`, it is not necessary to bundle all Flink job deps to the Docker image.
Upload handles the job JAR and any additional local artifact that is present in the `user.artifacts.artifact-list` config. The `user.artifacts.artifact-list` can contain both local and remote artifact mixed, former will be uploaded, latter will remain unchanged and everything will be fetched on the JM pod.
```bash
$ ./bin/flink run-application \
--target kubernetes-application \
-Dkubernetes.cluster-id=my-first-application-cluster \
-Dkubernetes.container.image=custom-image-name \
-Dkubernetes.artifacts.local-upload-enabled=true \
-Dkubernetes.artifacts.local-upload-target=s3://my-bucket/ \ …
```
=> [FLINK-32315][k8s] Support uploading "local://" artifacts in Kubernetes Application Mode

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateRequest.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperatorV2.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperatorV2.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperatorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperatorV2Test.java
This PR implements checkpoint drain in `AsyncExecutionController`, and wires it to `AbstractAsyncStateStreamOperator/AbstractAsyncStateStreamOperatorV2`. 
- Add `AsyncExecutionController#drainInflightRecords`
- Override `AbstractAsyncStateStreamOperator/AbstractAsyncStateStreamOperatorV2#snapshotState()`. 
- `AsyncExecutionControllerTest#testInFlightRecordControl()` …
=> [FLINK-35027][runtime/checkpoint] Implement checkpoint drain in AsyncExecutionController

flink-table/flink-table-runtime/src/main/java/org/apache/flink/formats/raw/RawFormatDeserializationSchema.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/formats/raw/RawFormatSerDeSchemaTest.java
Fixes broken deserialization of the `raw` format.
The existing `reuse` attribute is returned by the `deserialize()` method in `RawFormatDeserializationSchema`. The attribute is successively modified during deserialization but since it's returned by reference in the method, all the returned deserializations refer to a single value. This change removes the attributes and instead constructs the returned value in the `deserialize()` method inside the method itself, thus avoiding overwrites.
**Existing Behavior**
1. Create a test file with the content:
```
line 1
line 2
line3
```
2. Run
```SQL
CREATE TABLE MyRawTable (
`doc` string,
) WITH (
'path' = 'file:///path/to/data',
'format' = 'raw',
'connector' = 'filesystem'
); …
```
=> [FLINK-35097][table] Fix 'raw' format deserialization

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/KeyAccountingUnit.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/RecordContext.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperatorV2.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/InternalTimeServiceManager.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/InternalTimeServiceManagerImpl.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/InternalTimerServiceAsyncImpl.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/InternalTimerServiceImpl.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionInternalTimeServiceManager.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperatorV2.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/InternalTimerServiceAsyncImplTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperatorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperatorV2Test.java
This PR adapts timer firing to async state execution. The entrances are `AbstractAsyncStateStreamOperator ` and `AbstractAsyncStateStreamOperatorV2`,  the hot path without this feature is not affected.
- Introduce `InternalTimerServiceAsyncImpl`.
- Add `InternalTimeServiceManager#getAsyncInternalTimerService` method.
- Override `getInternalTimerService` of `AbstractAsyncStateStreamOperator ` and `AbstractAsyncStateStreamOperatorV2`
- `InternalTimerServiceAsyncImplTest`
- `AbstractAsyncStateStreamOperatorTest#testTimerServiceIsAsync`
- - `AbstractAsyncStateStreamOperatorV2Test#testTimerServiceIsAsync` …
=> [FLINK-35028][runtime] Timer firing under async execution model

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/endpoint/hive/util/OperationExecutorFactory.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogBaseTableResolutionTest.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/Catalog.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogBaseTable.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogMaterializedTable.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/DefaultCatalogMaterializedTable.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/ResolvedCatalogMaterializedTable.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/refresh/RefreshHandler.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/refresh/RefreshHandlerSerializer.java
Introduce CatalogMaterializedTable and related interface to support materialized table, see https://issues.apache.org/jira/browse/FLINK-35188 for more detail.
- *Introduce CatalogMaterializedTable interface*
- *Introduce RefreshHandler interface*
- *Added unit test CatalogBaseTableResolutionTest#testCatalogMaterializedTableResolution*
- …
=> [FLINK-35188][table-api] Introduce CatalogMaterializedTable and related interface to support materialized table

flink-datastream/src/main/java/org/apache/flink/datastream/impl/operators/ProcessOperator.java, flink-datastream/src/main/java/org/apache/flink/datastream/impl/operators/TwoInputBroadcastProcessOperator.java, flink-datastream/src/main/java/org/apache/flink/datastream/impl/operators/TwoInputNonBroadcastProcessOperator.java, flink-datastream/src/main/java/org/apache/flink/datastream/impl/operators/TwoOutputProcessOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateUdfStreamOperator.java
This is a simple PR that wire the new introduced operators of DataStream V2 with the `AbstractAsyncStateStreamOperator`.
- Introduce `AbstractAsyncStateUdfStreamOperator` that is nearly identical with `AbstractUdfStreamOperator`, but extends from `AbstractAsyncStateStreamOperator`
- Replace base class of `ProcessOperator` (v2) from `AbstractUdfStreamOperator` to `AbstractAsyncStateUdfStreamOperator`.
This change is a trivial rework without any test coverage. More will be added when the whole state processing works. …
=> [FLINK-35156][Runtime] Make operators of DataStream V2 integrate with async state processing framework

flink-core/src/main/java/org/apache/flink/core/state/StateFutureImpl.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/ContextStateFutureImpl.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/RecordContext.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/ReferenceCounted.java, flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/ReferenceCountedTest.java
This is a internal hotfix within development of async state execution (see: FLIP-425).
- add a ReleaseHelper parameter to ReferenceCounted
- RecordContext use disposer runner as release helper, when ref-count reach 0, it will be used run disposer
- add a 'inCallbackRunner' parameter to StateFutureImpl#postComplete()
- ContextStateFutureImpl#postComplete() pass director runner or callbackRunner to RecordContext#release() depends on 'inCallbackRunner' …
=> [hotfix] make sure run RecordContext#release() in Task thread.

docs/config.toml
1.19 is our current stable release. Therefore, we should not show an outdated warning message.
It looks like we accidentally changed this with https://github.com/apache/flink/pull/24547 as part of the 1.19 release.
- *Set ShowOutDatedWarning = false*
=> [FLINK-35239] [docs] Unset outdated warning

docs/content.zh/docs/dev/table/sql/describe.md, docs/content/docs/dev/table/sql/describe.md, flink-table/flink-sql-client/src/test/resources/sql/catalog_database.q, flink-table/flink-sql-gateway/src/test/resources/sql/catalog_database.q, flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl, flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/dql/SqlDescribeCatalog.java, flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/DescribeCatalogOperation.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlDescribeCatalogConverter.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlNodeConverters.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlOtherOperationConverterTest.java
Describe the metadata of an existing catalog. The metadata information includes the catalog’s name, type, and comment. If the optional EXTENDED option is specified, catalog properties are also returned.
* { DESCRIBE | DESC } CATALOG [EXTENDED] catalog_name
flink-table/flink-sql-client/src/test/resources/sql/catalog_database.q
flink-table/flink-sql-gateway/src/test/resources/sql/catalog_database.q …
=> [FLINK-34915][table] Complete `DESCRIBE CATALOG` syntax

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/optimize/StreamCommonSubGraphBasedOptimizer.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/FlinkRexUtil.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/optimize/MiniBatchOptimizationTest.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/TableTestBase.scala
The pull request detects unnecessary mini-batch assignments and ignores them in the query plan
- Search query plan if it contains aggregate or join operators
- If none of them exists in query plan, then we ignore the mini-batch assignment
- With that, we avoid generating useless events and causing performance issues
This change added tests and can be verified as unit tests that I added as part of this PR …
=> [FLINK-32622][table-planner] Optimize mini-batch assignment

docs/content.zh/docs/deployment/resource-providers/standalone/kubernetes.md, docs/content/docs/deployment/resource-providers/standalone/kubernetes.md
`jobmanager-session-deployment.yaml` -> `jobmanager-session-deployment-non-ha.yaml`.
`jobmanager-deployment.yaml` -> `jobmanager-application-non-ha.yaml`.
*(or)*
This change is already covered by existing tests, such as *(please describe …
=> [hotfix][docs] Fix file reference

flink-clients/src/test/java/org/apache/flink/client/program/rest/RestClusterClientTest.java, flink-runtime-web/src/test/resources/rest_api_v1.snapshot, flink-runtime-web/web-dashboard/src/app/interfaces/job-detail.ts, flink-runtime-web/web-dashboard/src/app/pages/job/job-detail/status/job-status.component.html, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/JobMasterServiceLeadershipRunnerFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/cleanup/CheckpointResourcesCleanupRunner.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/AccessExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ArchivedExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraphBuilder.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/factories/DefaultJobMasterServiceProcessFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/JobDetailsHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/JobDetailsInfo.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ArchivedExecutionGraphTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/DefaultJobMasterServiceProcessTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterServiceLeadershipRunnerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/TestingJobManagerRunner.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/factories/TestingJobMasterServiceProcessFactory.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/factories/TestingJobMasterServiceProcessFactoryOld.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/legacy/utils/ArchivedExecutionGraphBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/messages/job/JobDetailsInfoTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/ExecutionGraphInfoTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StateTrackingMockExecutionGraph.java
- See [FLIP-441](https://cwiki.apache.org/confluence/display/FLINK/FLIP-441%3A+Show+the+JobType+and+remove+Execution+Mode+on+Flink+WebUI) get more details.
- Currently, the jobType has 2 types in Flink: STREAMING and BATCH. They work on completely different principles, such as: scheduler, shuffle, join, etc. These differences lead to different troubleshooting processes, so when users are maintaining a job or troubleshooting, it's needed to know whether the current job is a STREAMING or BATCH job. Unfortunately, Flink WebUI doesn't expose it to the users so far.
- [FLINK-35222][rest] Add getJobType for AccessExecutionGraph
- [FLINK-35223][rest] Add jobType in JobDetailsInfo related rest api
- [FLINK-35224][web] Show the JobType on Flink WebUI
Test manually for running job : 
Test manually …
=> [FLINK-35223][rest] Add jobType in JobDetailsInfo related rest api

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/calcite/PreValidateReWriter.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/calcite/FlinkCalciteSqlValidatorTest.java
The purpose of this PR is to avoid wrong `IndexOutOfBoundsException` with Values.
For example, a query `INSERT INTO t_3_columns (id, name, num) VALUES ('id_0', 'name_0', 5);` should not throw an exception.
-  Fix the exception catching conditions with VALUES expression
-  Add tests
`org.apache.flink.table.planner.calcite. FlinkCalciteSqlValidatorTest` …
=> [FLINK-34902][table] Fix IndexOutOfBoundsException for VALUES

flink-core/src/main/java/org/apache/flink/core/fs/CommitterFromPersistRecoverableFsDataOutputStream.java, flink-core/src/main/java/org/apache/flink/core/fs/local/LocalRecoverableFsDataOutputStream.java, flink-core/src/test/java/org/apache/flink/core/fs/local/AbstractRecoverableFsDataOutputStreamTest.java, flink-core/src/test/java/org/apache/flink/core/fs/local/LocalRecoverableFsDataOutputStreamTest.java, flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AzureBlobFsRecoverableDataOutputStream.java, flink-filesystems/flink-azure-fs-hadoop/src/test/java/org/apache/flink/fs/azurefs/AzureBlobFsRecoverableDataOutputStreamTest.java, flink-filesystems/flink-hadoop-fs/src/main/java/org/apache/flink/runtime/fs/hdfs/BaseHadoopFsRecoverableFsDataOutputStream.java, flink-filesystems/flink-hadoop-fs/src/main/java/org/apache/flink/runtime/fs/hdfs/HadoopRecoverableFsDataOutputStream.java, flink-filesystems/flink-hadoop-fs/src/test/java/org/apache/flink/runtime/fs/hdfs/HadoopRecoverableFsDataOutputStreamTest.java
Sync'ing back written data to disk is seemingly missing from some implementation of RecoverableFsDataOutputStream. This PR adds sync, typically by calling #persist() inside #closeForCommit.
=> [FLINK-35217] Add missing fsync to #closeForCommit in some subclasses of RecoverableFsDataOutputStream.

flink-core/src/main/java/org/apache/flink/core/fs/CommitterFromPersistRecoverableFsDataOutputStream.java, flink-core/src/main/java/org/apache/flink/core/fs/local/LocalRecoverableFsDataOutputStream.java, flink-core/src/test/java/org/apache/flink/core/fs/local/AbstractRecoverableFsDataOutputStreamTest.java, flink-core/src/test/java/org/apache/flink/core/fs/local/LocalRecoverableFsDataOutputStreamTest.java, flink-filesystems/flink-azure-fs-hadoop/src/main/java/org/apache/flink/fs/azurefs/AzureBlobFsRecoverableDataOutputStream.java, flink-filesystems/flink-azure-fs-hadoop/src/test/java/org/apache/flink/fs/azurefs/AzureBlobFsRecoverableDataOutputStreamTest.java, flink-filesystems/flink-hadoop-fs/src/main/java/org/apache/flink/runtime/fs/hdfs/BaseHadoopFsRecoverableFsDataOutputStream.java, flink-filesystems/flink-hadoop-fs/src/main/java/org/apache/flink/runtime/fs/hdfs/HadoopRecoverableFsDataOutputStream.java, flink-filesystems/flink-hadoop-fs/src/test/java/org/apache/flink/runtime/fs/hdfs/HadoopRecoverableFsDataOutputStreamTest.java
Backport of FLINK-35217 for 1.19
(cherry picked from commit 80af4d502318348ba15a8f75a2a622ce9dbdc968)
=> Backport: [FLINK-35217] Add missing fsync to #closeForCommit in some subclasses of RecoverableFsDataOutputStream. (#24722)

flink-table/flink-table-common/src/main/java/org/apache/flink/table/api/TableRuntimeException.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/casting/AbstractCodeGeneratorCastRule.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/ExprCodeGenerator.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/BuiltInAggregateFunctionTestBase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/BuiltInFunctionTestBase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/JsonFunctionsITCase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/MiscAggFunctionITCase.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/casting/CastRulesTest.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/SqlJsonUtils.java
Introduce `TableRuntimeException` to better classify intentional exceptions thrown from SQL runtime.
Added tests
=> [FLINK-35155] Introduce TableRuntimeException

flink-tests-java17/src/test/java/org/apache/flink/api/java/typeutils/runtime/PojoRecordSerializerUpgradeTestSpecifications.java
Flink cannot compile with jdk17
https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=59380&view=results fails and benchmark with 17 fails as well
Reason: TypeSerializerUpgradeTestBase.UpgradeVerifier updates the schemaCompatibilityMatcher method name to schemaCompatibilityCondition, but some subclasses didn't change it, such as: PojoRecordSerializerUpgradeTestSpecifications.PojoToRecordVerifier.
It belongs to flink-tests-java17 module, and it doesn't compile by default.
it's related to https://github.com/apache/flink/pull/24603
[FLINK-35306][test] Update some methods in flink-tests-java17 to solve jdk17 compile fails
=>  [FLINK-35306][test] Migrate flink-tests-java17 module to JUnit5 and assertj to solve jdk17 compile fails

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/bundle/InputSideHasNoUniqueKeyBundle.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/join/stream/StreamingJoinOperatorTestBase.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/join/stream/StreamingMiniBatchJoinOperatorTest.java
This change fixes the possible error because of hash collision in MiniBatchStreamingJoinOperator
Currently for InputSideHasNoUniqueKeyBundle the data is stored inside HashMap where the hashCode is used as key. But there is no additional check after comparing the hash codes of different records. So this PR brings additional check for equals before folding the records.
Added testInnerJoinWithNoUniqueKeyHashCollision to StreamingMiniBatchJoinOperatorTest which fails before change and success after …
=> [FLINK-35184][table-runtime] fix minibatch join hash collision release-1.19

flink-end-to-end-tests/test-scripts/common_s3_minio.sh, flink-end-to-end-tests/test-scripts/common_ssl.sh, flink-end-to-end-tests/test-scripts/test_file_sink.sh
* Fixes error message in test execution
* unifies S3-related code in one location
* Replaces AWS-backed S3 filesink e2e test with Minio backend
* Moves the entire s3-related logic into the if block
=> [FLINK-34324][ci] Replaces AWS-based S3 e2e tests with Minio-backed version

flink-python/pyflink/common/types.py
This pull request adds support for a membership check for field names in a Row in PyFlink. If field names are not defined, it will check membership in the values. For example:
```
user_row = Row(name="Alice", age=22)
print("name" in user_row)
user_row = Row("Alice", 22)
print("Alice" in user_row)
```
This change is more in line with how dictionaries behave in Python. 
- Change `in` behaviour for `Row` class.
- If field names are defined, `KEY in row` will check if  `KEY` exists in field names.
- If field names do not exist, `KEY in row` will check if `KEY` exists in field values (current behaviour). …
=> [FLINK-35112][python] Fix membership for Row class PyFlink

flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/metadata/CheckpointTestUtils.java
IncrementalRemoteKeyedStateHandleTest.testSharedStateReRegistration failed
Reason:
TestingSegmentFileStateHandle.EMPTY_INSTANCE is static, it means other test can update disposed field. IncrementalRemoteKeyedStateHandleTest.testSharedStateReRegistration will check the disposed of this static TestingSegmentFileStateHandle.EMPTY_INSTANCE.
So disposed is unexpected.
- [FLINK-35041][test] Fix the IncrementalRemoteKeyedStateHandleTest.testSharedStateReRegistration failed
- TestingSegmentFileStateHandle object shouldn't be shared in global scope.
=> [FLINK-35041][test] Fix the IncrementalRemoteKeyedStateHandleTest.testSharedStateReRegistration failed

flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/materializedtable/MaterializedTableManager.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/MaterializedTableStatementITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/SqlGatewayServiceITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/materializedtable/MaterializedTableManagerTest.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/utils/SqlGatewayServiceTestUtil.java, flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/ddl/SqlAlterMaterializedTable.java, flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/ddl/SqlAlterMaterializedTableRefresh.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/OperationUtils.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/materializedtable/AlterMaterializedTableRefreshOperation.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlAlterMaterializedTableRefreshConverter.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlNodeConverters.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlMaterializedTableNodeToOperationConverterTest.java, flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/test/junit5/MiniClusterExtension.java
Support the execution of refresh materialized table.
- *Add execution in sql gateway*
- *Add operation in table-api&table-planner*
- *Add tests*
Some tests are added.
=> [FLINK-35198][table] Support the execution of refresh materialized table

flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/AbstractHandler.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/FileUploadHandlerITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/AbstractHandlerTest.java
This PR makes REST server ignoring unknown fields when deserializing request body, which is helpful in some senarios where a centralized REST client of newer version (contains additional fields in request) communicates with REST servers of various versions, potentially an old version that doesn't recognize additional fields.
Related to #23930 , in which compatibility between old version client and new version server was solved.
- change ObjectMapper for AbstractHandler to flexible ObjectMapper ignoring unknown fields
- unit test AbstractHandlerTest#testIgnoringUnknownFields
- The …
=> [FLINK-35302][rest] Ignore unknown fields in REST request deserialization

flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java, flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/ShuffleServiceOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutorGateway.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorPartitionLifecycleTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorSubmissionTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TestingTaskExecutorGateway.java
[FLINK-34661][runtime] TaskExecutor supports retain partitions after JM crashed.
TaskExecutor supports retain partitions after JM crashed.
This change added tests in TaskExecutorPartitionLifecycleTest …
=> [FLINK-34661][runtime] TaskExecutor supports retain partitions after JM crashed.

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AbstractStateIterator.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateRequestType.java, flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AbstractStateIteratorTest.java
This PR ship the basic logic of state iterator, only leave the necessary part abstract for subclass to implement. Most of the code is future-related.
- Introduce `AbstractStateIterator` and corresponding tests.
- Run newly added `AbstractStateIteratorTest`.
=> [FLINK-35168][State] Basic State Iterator for async processing

docs/content.zh/docs/connectors/table/hive/hive_read_write.md, docs/content/docs/connectors/table/hive/hive_read_write.md, flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/src/AbstractFileSource.java, flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/LimitableBulkFormat.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveDynamicParallelismInferenceFactory.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveOptions.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveParallelismInference.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveSource.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveSourceBuilder.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveSourceDynamicFileEnumerator.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveSourceFileEnumerator.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveStaticParallelismInferenceFactory.java, flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveTableSource.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveSourceDynamicFileEnumeratorTest.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveSourceITCase.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveSourceTest.java, flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/catalog/hive/HiveTestUtils.java
[FLIP-379](https://cwiki.apache.org/confluence/display/FLINK/FLIP-379%3A+Dynamic+source+parallelism+inference+for+batch+jobs) introduces dynamic source parallelism inference, which, compared to static inference, utilizes runtime information to more accurately determine the source parallelism. The FileSource already possesses the capability for dynamic parallelism inference. As a follow-up task to FLIP-379, this FLIP plans to implement the dynamic parallelism inference interface for HiveSource, and also switches the default static parallelism inference to dynamic parallelism inference.
- *Enable HiveSource with dynamic parallelism inference capability.*
- *Switch the default parallelism inference mode of HiveSource to dynamic inference and introduce a new configuration …
=> [FLINK-35293][hive] Hive source supports dynamic parallelism inference

flink-formats/flink-orc/src/main/java/org/apache/flink/orc/OrcFilters.java, flink-formats/flink-orc/src/test/java/org/apache/flink/orc/OrcFileSystemFilterTest.java, flink-formats/flink-orc/src/test/java/org/apache/flink/orc/OrcFileSystemITCase.java
Fixes an issue with SQL queries containing expressions like **10 >= y** when using Filesystem connector and ORC format.
- In OrcFilters fixed filters push down of GREATER_THAN, GREATER_THAN_OR_EQUAL, LESS_THAN, LESS_THAN_OR_EQUAL functions 
Added tests:
- `OrcFileSystemITCase::testOrcFilterPushDownLiteralFirst` verifies a query result.
- `OrcFileSystemFilterTest::testApplyPredicateReverse` verifies expression conversions to ORC filter predicates. …
=> [FLINK-35098][ORC] Fix incorrect results with literal first expressions

flink-formats/flink-orc/src/main/java/org/apache/flink/orc/OrcFilters.java, flink-formats/flink-orc/src/test/java/org/apache/flink/orc/OrcFileSystemFilterTest.java, flink-formats/flink-orc/src/test/java/org/apache/flink/orc/OrcFileSystemITCase.java
This is 1.19 backport of https://github.com/apache/flink/pull/24659 that solves https://issues.apache.org/jira/browse/FLINK-35098 bug.
=> [BP-1.19][FLINK-35098][ORC] Fix incorrect results with literal first expressions

flink-formats/flink-orc/src/main/java/org/apache/flink/orc/OrcFilters.java, flink-formats/flink-orc/src/test/java/org/apache/flink/orc/OrcFileSystemFilterTest.java, flink-formats/flink-orc/src/test/java/org/apache/flink/orc/OrcFileSystemITCase.java
This is 1.18 backport of https://github.com/apache/flink/pull/24659 that solves https://issues.apache.org/jira/browse/FLINK-35098 bug.
=> [BP-1.18][FLINK-35098][ORC] Fix incorrect results with literal first expressions

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/LogicalFile.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/PhysicalFile.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/AcrossCheckpointFileMergingSnapshotManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerTestBase.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/WithinCheckpointFileMergingSnapshotManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/filesystem/FileMergingCheckpointStateOutputStreamTest.java
This PR introduces space amplification statistics of file merging.
- Add `SpaceStat` class in `FileMergingSnapshotManager`.
- Update `SpaceStat` on physical/logical files's creation/deletion
- Add `FileMergingSnapshotManagerTestBase#testSpaceStat`
- Update `FileMergingSnapshotManagerTestBase#testRestore`
- Update `testCreateAndReuseFiles/testCheckpointNotification` …
=> [FLINK-32087][checkpoint] Introduce space amplification statistics of file merging

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/aggfunctions/RankLikeAggFunctionBase.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/AggFunctionFactory.scala, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/agg/OverAggregateTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/agg/OverAggregateTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/OverAggregateITCase.scala
This is a backport of https://github.com/apache/flink/pull/19797 to 1.19
=> [BP-1.19][FLINK-27741][table-planner] Fix NPE when use dense_rank() and rank()

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/aggfunctions/RankLikeAggFunctionBase.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/AggFunctionFactory.scala, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/agg/OverAggregateTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/agg/OverAggregateTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/OverAggregateITCase.scala
This is a backport of https://github.com/apache/flink/pull/19797 to 1.18
=> [BP-1.18][FLINK-27741][table-planner] Fix NPE when use dense_rank() and rank()

docs/content.zh/docs/dev/datastream/fault-tolerance/checkpointing.md, docs/content/docs/dev/datastream/fault-tolerance/checkpointing.md
This PR adds documentation of checkpoint file-merging.
- add documentation of checkpoint file-merging
=> [FLINK-32082][docs] Documentation of checkpoint file-merging

flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/JobConfigInfo.java
See [FLIP-441](https://cwiki.apache.org/confluence/display/FLINK/FLIP-441%3A+Show+the+JobType+and+remove+Execution+Mode+on+Flink+WebUI)
- [FLINK-35226][rest] Deprecate execution-mode in ExecutionConfigInfo related rest api
=> [FLINK-35226][rest] Deprecate execution-mode in ExecutionConfigInfo related rest api

flink-runtime-web/web-dashboard/src/app/pages/job/configuration/job-configuration.component.html
See [FLIP-441](https://cwiki.apache.org/confluence/display/FLINK/FLIP-441%3A+Show+the+JobType+and+remove+Execution+Mode+on+Flink+WebUI
)
- [FLINK-35225][Web] Remove Execution mode in Flink WebUI
Before this PR, the web UI still show the Execution mode.
After this PR, Execution mode is removed in web UI.
=> [FLINK-35225][Web] Remove Execution mode in Flink WebUI

flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/FactoryUtil.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/WorkflowSchedulerFactory.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/WorkflowSchedulerFactoryUtil.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/workflow/CreateRefreshWorkflow.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/workflow/DeleteRefreshWorkflow.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/workflow/ModifyRefreshWorkflow.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/workflow/RefreshWorkflow.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/workflow/WorkflowException.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/workflow/WorkflowScheduler.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/factories/workflow/TestWorkflowSchedulerFactory.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/factories/workflow/WorkflowSchedulerFactoryUtilTest.java, flink-table/flink-table-common/src/test/resources/META-INF/services/org.apache.flink.table.factories.Factory
*Introduce workflow scheduler interface for materialized table*
- *Introduce workflow scheduler interface for materialized table*
- *Added unit tests in WorkflowSchedulerFactoryUtilTest*
- The serializers: (don't know)
=> [FLINK-35346][table-common] Introduce workflow scheduler interface for materialized table

flink-core/src/test/java/org/apache/flink/api/connector/source/mocks/MockSourceReader.java, flink-core/src/test/java/org/apache/flink/api/connector/source/mocks/MockSourceSplit.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorAlignmentTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorTestContext.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorWatermarksTest.java
Properly initialize initial splits in WatermarkOutputMultiplexer
Without this fix, initial splits were registered in the multiplexer only
when first record from that split has been emitted. This was leading to
incorrectly emitted watermarks, as resulting watermark was not properly
combined from the initial splits, but only from the splits that have
already emitted at least one record.
Please check individual commit messages 
This bugfix is covered against future regressions by a new test.
- …
=> [FLINK-32828] Partition aware watermark not handled correctly shortly after job start up from checkpoint or savepoint

flink-core-api/src/main/java/org/apache/flink/api/common/state/v2/ReducingState.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateRequestType.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/DefaultKeyedStateStoreV2.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/InternalReducingState.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/KeyedStateStoreV2.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/ReducingStateDescriptor.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/StateDescriptor.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/InternalReducingStateTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/ReducingStateDescriptorTest.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/StreamingRuntimeContext.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/StreamingRuntimeContextTest.java
This PR provides the definition of `StateDescriptor` and simple implementation for `ReducingState` in `State V2`.
- Definition and tests for `ReducingState` and `ReducingStateDescriptor`
Added UT for each new introduced class.
=> [FLINK-35356][State] State descriptor and implementation for async reducing state

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/EpochManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/RecordContext.java, flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionControllerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/ContextStateFutureImplTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/EpochManagerTest.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStDBOperationTestBase.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateExecutorTest.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperatorV2.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperatorV2.java
This PR introduces Epoch Manager to handle watermark and watermark status processing under async execution.
Epoch manager segments inputs into distinct epochs, marked by the arrival of non-records(e.g.watermark, record attributes). Records are assigned to a unique epoch based on their arrival, records within an epoch are allowed to be parallelized, while the non-record of an epoch can only be executed when all records in this epoch have finished.
- Add `SerialEpochManager` and `ParallelEpochManager`
- Wire `SerialEpochManager` to AEC
- Leverage EpochManager to process watermark/watermark status
- `EpochManagerTest`
- `AsyncExecutionControllerTest#testSerialEpochManager`
- …
=> [FLINK-35030][runtime] Introduce Epoch Manager under async execution

flink-core/src/test/java/org/apache/flink/api/connector/source/mocks/MockSourceReader.java, flink-core/src/test/java/org/apache/flink/api/connector/source/mocks/MockSourceSplit.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorAlignmentTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorTestContext.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorWatermarksTest.java
This is a backport of https://github.com/apache/flink/pull/24794 to 1.19
Properly initialize initial splits in WatermarkOutputMultiplexer
Without this fix, initial splits were registered in the multiplexer only
when first record from that split has been emitted. This was leading to
incorrectly emitted watermarks, as resulting watermark was not properly
combined from the initial splits, but only from the splits that have
already emitted at least one record.
Please check individual commit messages 
This bugfix is covered against future regressions by a new test.
- The runtime …
=> [FLINK-32828][1.19] Partition aware watermark not handled correctly shortly after job start up from checkpoint or savepoint

flink-core/src/test/java/org/apache/flink/api/connector/source/mocks/MockSourceReader.java, flink-core/src/test/java/org/apache/flink/api/connector/source/mocks/MockSourceSplit.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorAlignmentTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorTestContext.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorWatermarksTest.java
This is a backport of https://github.com/apache/flink/pull/24794 to 1.18
Properly initialize initial splits in WatermarkOutputMultiplexer
Without this fix, initial splits were registered in the multiplexer only
when first record from that split has been emitted. This was leading to
incorrectly emitted watermarks, as resulting watermark was not properly
combined from the initial splits, but only from the splits that have
already emitted at least one record.
Please check individual commit messages 
This bugfix is covered against future regressions by a new test.
- The runtime …
=> [FLINK-32828][1.18] Partition aware watermark not handled correctly shortly after job start up from checkpoint or savepoint

flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionVertexInputInfo.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/JobVertexInputInfo.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/event/ExecutionJobVertexInitializedEvent.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/event/ExecutionVertexFinishedEvent.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/event/ExecutionVertexResetEvent.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/event/FileSystemJobEventStore.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/event/FsBatchFlushOutputStream.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/event/GenericJobEventSerializer.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/event/JobEvent.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/event/JobEventManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/event/JobEventReplayHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/event/JobEventStore.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/event/JobEvents.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/event/DummyJobEventStore.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/event/ExecutionJobVertexInitializedEventTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/event/ExecutionVertexFinishedEventTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/event/ExecutionVertexResetEventTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/event/FileSystemJobEventStoreTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/event/FsBatchFlushOutputStreamTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/event/JobEventManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/event/TestingJobEvent.java
[FLINK-33983][runtime] Introduce JobEvent and JobEventStore
Introduce JobEvent and JobEventStore
- ExecutionJobVertexInitializedEventTest
- ExecutionVertexFinishedEventTest
- ExecutionVertexResetEventTest
- FileSystemJobEventStoreTest
- FsBatchFlushOutputStreamTest
- JobEventManagerTest
- TestingJobEvent …
=> [FLINK-33983][runtime] Introduce JobEvent and JobEventStore

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/LogicalFile.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/SubtaskFileMergingManagerRestoreOperation.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/filemerging/SegmentFileStateHandle.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsMergingCheckpointStorageAccess.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/AcrossCheckpointFileMergingSnapshotManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerTestBase.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/WithinCheckpointFileMergingSnapshotManagerTest.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
This PR fix several issues with file merging mechanism, see `Brief change log`.
Fix following issues:
- Checkpoint notification is not handled by the file merging manager.
- File manager propagate the discard of one checkpoint incorrectly.
- File manager cannot recognize the `PlaceholderStreamStateHandle`
- Fail to filter `EmptySegmentFileStateHandle` out during recovery
UT modified. …
=> [FLINK-35379][Checkpoint] Fix incorrect checkpoint notification handling in file merging

flink-tests/src/test/java/org/apache/flink/test/state/ChangelogCompatibilityITCase.java
This pull request disable snapshot-file-merging config in  ChangelogCompabilityITCase.
-  Disable the FILE_MERGING_ENABLED config in ChangelogCompabilityITCase
This change is already covered by existing tests (ChangelogCompabilityITCase).
=> [FLINK-35382][test] Disable snapshot-file-merging in ChangelogCompabilityITCase

flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/recovery/RescalingStreamTaskNetworkInput.java
Fix copying StreamPartitioner in rescale case
=> [hotfix] [streaming] Correct copying StreamPartitioner in rescale case

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackendBuilder.java
This is a internal hotfix within development of ForStStateBackend (see: FLIP-427).
- As title, create new copy for each SerializedCompositeKeyBuilder in ForStStateBackend.
=> [hotfix][ForStStateBackend] Create new copy for each SerializedCompositeKeyBuilder in ForStStateBackend

flink-core/src/main/java/org/apache/flink/api/java/typeutils/runtime/NoFetchingInput.java
The performance of [serializerKryo](http://flink-speed.xyz/timeline/#/?exe=1,6,12&ben=serializerKryo&extr=on&quarts=on&equid=off&env=3&revs=50) and [serializerKryoWithoutRegistration](http://flink-speed.xyz/timeline/#/?exe=12&ben=serializerKryoWithoutRegistration&extr=on&quarts=on&equid=off&env=3&revs=50) are regressed, I checked recent commits, and found [FLINK-34954](https://issues.apache.org/jira/browse/FLINK-34954) changed related logic.
- The first commit: Revert "[FLINK-34954][core] Kryo Input bug fix" 
- The second commit: [FLINK-35215][core] Fix the bug when Kryo serialize length is 0
- This PR reverts the FLINK-34954, and try to re-implement to avoid the performance regression.
=> [FLINK-35215][core] Fix the bug when Kryo serialize length is 0

docs/data/sql_functions.yml, flink-python/docs/reference/pyflink.table/expressions.rst, flink-python/pyflink/table/expression.py, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CollectionFunctionsITCase.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/SplitFunction.java
This is an implementation of SPLIT
Splits a string into an array of substrings based on a delimiter. If the delimiter is not found, then the original string is returned as the only element in the array. If the delimiter is empty, then all characters in the string are split. If either, string or delimiter, are NULL, then a NULL value is returned.
If the delimiter is found at the beginning or end of the string, or there are contiguous delimiters, then an empty space is added to the array.
- Syntax
`SPLIT(string, delimiter)`
- Arguments
string: The string need to be split
delimiter: Splits a string into an array of substrings based on a delimiter
- Returns
If the delimiter is not found, then the original string is returned as the only element in the array. If the delimiter is empty, then all …
=> [FLINK-32706][table] Add built-in SPLIT_STRING function

flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/SubtasksTimesInfo.java
FLINK-34907 needs to get when all subtask are switched to RUNNING from `SubtasksTimesInfo` class, but `SubtasksTimesInfo` doesn't provide the getter method.
- [hotfix][rest] Add getter methods for SubtasksTimesInfo to get all values easily
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no …
=> [hotfix][rest] Add getter methods for SubtasksTimesInfo to get all values easily

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateExecutor.java, flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateExecutorTest.java
Currently, the coordinator thread of ForSt executor will sync wait the state access result. This PR fixes that.
- remove the `FutureUtils.waitForAll` in `ForStStateExecutor`
This change is a trivial rework. The behavior of `ForStStateExecutor` is covered by existing tests.
=> [FLINK-35410][state] Avoid sync waiting in coordinator thread of ForSt executor

docs/data/sql_functions.yml, flink-python/pyflink/table/tests/test_expression.py, flink-table/flink-sql-parser/pom.xml, flink-table/flink-sql-parser/src/main/codegen/templates/Parser.jj, flink-table/flink-sql-parser/src/main/java/org/apache/calcite/sql/fun/SqlJsonQueryFunction.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/expressions/ExpressionSerializationTest.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/JsonFunctionsCallSyntax.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/JsonQueryOnErrorEmptyArgumentTypeStrategy.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/SpecificInputTypeStrategies.java, flink-table/flink-table-planner/src/main/java/org/apache/calcite/sql2rel/StandardConvertletTable.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/expressions/converter/converters/JsonQueryConverter.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/sql/SqlJsonQueryFunctionWrapper.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/CodeGenUtils.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/ExprCodeGenerator.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/BuiltInMethods.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/JsonQueryCallGen.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/JsonFunctionsITCase.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/SqlJsonUtils.java
This PR adds support for `RETURNING` clause in `JSON_QUERY` function.
Added tests in `JsonFunctionsITCase`
=> [FLINK-35216] Support for RETURNING clause of JSON_QUERY

flink-table/flink-table-code-splitter/src/main/java/org/apache/flink/table/codesplit/BlockStatementGrouper.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CaseFunctionsITCase.java
Make the `BlockStatementGrouper` work with less memory for complex `CASE WHEN` statements.
1. All existing tests pass
2. If you run the added test with complex `CASE WHEN` with `-Xmx128mb` the test quickly fails with:
```
java.lang.RuntimeException: JavaCodeSplitter failed. This is a bug. Please file an issue.
at org.apache.flink.table.codesplit.JavaCodeSplitter.split(JavaCodeSplitter.java:37)
at org.apache.flink.table.runtime.generated.GeneratedClass.<init>(GeneratedClass.java:58)
at org.apache.flink.table.runtime.generated.GeneratedOperator.<init>(GeneratedOperator.java:43)
at org.apache.flink.table.planner.codegen.OperatorCodeGenerator$.generateOneInputStreamOperator(OperatorCodeGenerator.scala:130)
at org.apache.flink.table.planner.codegen.CalcCodeGenerator$.generateCalcOperator(CalcCo …
```
=> [FLINK-35437] Rewrite BlockStatementGrouper so that it uses less memory

flink-core/src/test/java/org/apache/flink/testutils/runtime/NoFetchingInputTest.java
Add the demo from [FLINK-34954](https://issues.apache.org/jira/browse/FLINK-34954) as a test to prevent this bug happens in the future.
- [FLINK-35215][core] Add a test for deserializing an object whose serialization result is an empty byte array
- Added the NoFetchingInputTest#testDeserializeEmptyObject
This test will be failed when I remove following code inside of `NoFetchingInput#readBytes`:
```
if (count == 0) {
return;
}
```
The failed reason is totally same with FLINK-34954:
```
java.lang.RuntimeException: Could not create class java.lang.Object
at org.apache.flink.testutils.runtime.NoFetchingInputTest$EmptyObjectSerializer.read(NoFetchingInputTest.java:76)
at org.apache.flink.testutils.runtime.NoFetchingInputTest.testDeserializeEmptyObject(NoFetchingInputTest.java:49)
at …
```
=> [FLINK-35215][core] Add a test for deserializing an object whose serialization result is an empty byte array

flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/MaterializedTableStatementITCase.java
Fix unstable test of MaterializedTableStatementITCase. 
=> [FLINK-35342][table] Fix MaterializedTableStatementITCase test can check for wrong status

docs/content/docs/dev/table/functions/udfs.md, flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/FunctionDefinition.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/ConstantFoldingUtil.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/ReducerUtil.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/ExpressionReducer.scala, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/ExpressionReductionRulesTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/utils/userDefinedScalarFunctions.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/rules/logical/ExpressionReductionRulesTest.scala
This PR adds a new method to `FunctionDefinition`, `supportsConstantFolding` which indicates of a function call should have constant expression reduction done during planning time.  For example, `AddOne(10)` could be reduced to `11` by invoking `AddOne` during planning time.  This is the default and current Flink functionality.  
This addition allows overriding the default behavior and returning false, which would keep the expression intact, to be invoked at runtime instead.
This functionality and motivation is covered in more detail in [FLIP 452](https://cwiki.apache.org/confluence/display/FLINK/FLIP-452%3A+Allow+Skipping+Invocation+of+Function+Calls+While+Constant-folding).
- Added new test cases to `ExpressionReductionRulesTest`.
- These test that existing plans are unchanged
- New …
=> [FLINK-35403] Allow Skipping Invocation of Function Calls While Constant-folding

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/utils/DynamicPartitionPruningUtils.java
- Fix the catalog table adding logic
=> [FLINK-34379][table] Fix adding catalogtable logic

flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/row/ParquetRowDataWriter.java, flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/row/ParquetRowDataWriterTest.java
This Pull request adds commits from https://github.com/apache/flink/pull/24029 and https://github.com/apache/flink/pull/23881 to fully resolve issue https://issues.apache.org/jira/browse/FLINK-33759
Adds support for ParquetWriter nested Array, Map and Row Types. Previously the writer just wrote nothing. Silently failing.
- Added test to parquet writer using compression with all nested possible types. …
=> [FLINK-33759] [flink-parquet] Add support for nested array with row/map/array type

flink-core/src/test/java/org/apache/flink/api/connector/source/mocks/MockSplitEnumerator.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/Execution.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/JobVertex.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java, flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMasterGateway.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultScheduler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveBatchScheduler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveBatchSchedulerFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/BatchJobRecoveryContext.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/BatchJobRecoveryHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/DefaultBatchJobRecoveryHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/DummyBatchJobRecoveryHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/strategy/SchedulingStrategy.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/strategy/VertexwiseSchedulingStrategy.java, flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/JobShuffleContext.java, flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/JobShuffleContextImpl.java, flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/NettyShuffleMaster.java, flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/ShuffleMaster.java, flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinator.java, flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContext.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/utils/TestingJobMasterGateway.java, flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/utils/TestingJobMasterGatewayBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/DefaultSchedulerBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveBatchSchedulerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptivebatch/BatchJobRecoveryTest.java, flink-tests/src/test/java/org/apache/flink/test/scheduling/JMFailoverITCase.java
Support Job Recovery from JobMaster Failures for Batch Jobs.
This change added tests and can be verified by BatchJobRecoveryTest and JMFailoverITCase.
- The S3 …
=> [FLINK-35465][runtime] Introduce BatchJobRecoveryHandler for recovery of batch jobs from JobMaster failures.

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/PhysicalFile.java
1. The `PhysicalFile#outputStream` may be closed by both `innerClose` and `deleteIfNecessary`, we need to ensure that it is only closed once.
2. Stream tasks on one Task Manager may be initialized at the same time. It is necessary to ensure that `FileMergingSnapshotManager#fileSystem` on a Task Manager is only initialized once.
- Acquire lock before `PhysicalFile#innerClose`
- Acquire lock when `FileMergingSnapshotManagerBase#initFileSystem` …
=> [FLINK-35457][checkpoint] Hotfix! close physical file under the protection of lock

flink-tests/src/test/java/org/apache/flink/test/scheduling/JMFailoverITCase.java
As title said, fix the compile error cause by modification conflict between FLINK-35465 and FLINK-35359.
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`:(no)
- Does this pull request introduce a new feature?  (no)
=> [hotfix] Fix modification conflict between FLINK-35465 and FLINK-35359

flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogBaseTableResolutionTest.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogMaterializedTable.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogPropertiesUtil.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/DefaultCatalogMaterializedTable.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/IntervalFreshness.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/ResolvedCatalogMaterializedTable.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/utils/IntervalFreshnessUtils.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/utils/IntervalFreshnessUtilsTest.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlCreateMaterializedTableConverter.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/utils/MaterializedTableUtils.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlMaterializedTableNodeToOperationConverterTest.java, flink-test-utils-parent/flink-table-filesystem-test-utils/src/test/java/org/apache/flink/table/file/testutils/catalog/TestFileSystemCatalogTest.java
Support convert freshness to cron expression in full refresh mode
- *Support convert freshness to cron expression in full refresh mode*
- *Added unit tests in IntervalFreshnessUtilsTest*
- If yes, how is the feature documented? ( JavaDocs)
=> [FLINK-35425][table-common] Support convert freshness to cron expression in full refresh mode

flink-runtime/src/main/java/org/apache/flink/runtime/rest/FileUploadHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/RestServerEndpoint.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/router/MultipartRoutes.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/router/PathPattern.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/router/Router.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/RestServerEndpointITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/router/MultipartRoutesTest.java
The purpose of this change is to limit multipart requests to POST endpoints and file upload endpoint. Prior to this change, any request could be a multipart request (and upload a file).
With this change, the behavior of `FileUploadHandler` will be as follows:
1. Only accept a multipart request if the endpoint handler accepts POST requests.
2. Only accept a file upload if the endpoint handler accept file uploads.
Note that there multipart requests can mix file uploads with regular requests.
- Add `MultipartRoutes` in the `*.router` package for re-use of existing path patterns utilities.
- Factor out `RestServerEndpoint#getHandlerUrls(RestHandlerSpecification)` in order to ensure that we have a consistent way of getting the registered endpoint URLs.
- Add `MultipartRoutes` to …
=> [FLINK-26808] Limit FileUploadHandler to multipart routes

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/StateAssignmentOperation.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/StateAssignmentOperationTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/StateHandleDummyUtil.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointRescaleITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java
The same as https://github.com/apache/flink/pull/24784 but with reworked testing code
To fix [FLINK-35351](https://issues.apache.org/jira/browse/FLINK-35351)
UnalignedCheckpointRescaleITCase Topology.CUSTOM_PARTITIONER
=> [FLINK-35351][checkpoint] Fix fail during restore from unaligned checkpoint with custom partitioner

flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/FileSystemTableFactory.java, flink-table/flink-sql-gateway-api/src/main/java/org/apache/flink/table/gateway/api/SqlGatewayService.java, flink-table/flink-sql-gateway-api/src/test/java/org/apache/flink/table/gateway/api/utils/MockedSqlGatewayService.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/SqlGatewayRestEndpoint.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/handler/materializedtable/RefreshMaterializedTableHandler.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/header/materializedtable/RefreshMaterializedTableHeaders.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/message/materializedtable/MaterializedTableIdentifierPathParameter.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/message/materializedtable/RefreshMaterializedTableParameters.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/message/materializedtable/RefreshMaterializedTableRequestBody.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/message/materializedtable/RefreshMaterializedTableResponseBody.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/SqlGatewayServiceImpl.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/materializedtable/MaterializedTableManager.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/operation/OperationExecutor.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/AbstractMaterializedTableStatementITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/rest/SqlGatewayRestEndpointMaterializedTableITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/MaterializedTableStatementITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/materializedtable/MaterializedTableManagerTest.java, flink-table/flink-sql-gateway/src/test/resources/sql_gateway_rest_api_v3.snapshot, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/config/MaterializedTableConfigOptions.java, flink-test-utils-parent/flink-table-filesystem-test-utils/src/main/java/org/apache/flink/table/file/testutils/TestFileSystemTableFactory.java, flink-test-utils-parent/flink-table-filesystem-test-utils/src/test/java/org/apache/flink/table/file/testutils/TestFileSystemTableFactoryTest.java
*Introduce refresh materialized table rest api*
- *test-filesystem support partition.fields option*
- *Introduce refresh materialized table rest api*
* Add test case in MaterializedTableITCase to verify refresh materialzied table.
* Add test class SqlGatewayRestEndpointMaterializedTableITCase to verify refresh materialized table rest api.
- …
=>  [FLINK-35348][table] Introduce refresh materialized table rest api

docs/layouts/shortcodes/generated/checkpoint_file_merging_section.html, docs/layouts/shortcodes/generated/checkpointing_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/CheckpointingOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/AcrossCheckpointFileMergingSnapshotManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerBase.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerBuilder.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/LogicalFile.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/PhysicalFile.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/WithinCheckpointFileMergingSnapshotManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/CheckpointStreamFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/TaskExecutorFileMergingManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsMergingCheckpointStorageLocation.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/AcrossCheckpointFileMergingSnapshotManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerTestBase.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/WithinCheckpointFileMergingSnapshotManagerTest.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/snapshot/RocksIncrementalSnapshotStrategy.java
As we know, the checkpoint file merging will introduce space amplification. This PR introduce a space control in file merging, by rewriting old files and eliminate the empty slot on underlying files.
- Space accounting and flags in file merging manager and physical files.
- Rewrite in RocksdbStateBackend
Added UTs for file merging manager.
- If yes, how …
=> [FLINK-32088][checkpoint] Space control in file merging

.github/workflows/docs.yml
Changes:
- add `--delete` to delete target dir's file which source not exist
=> [FLINK-35484][doc-ci] Flink document file had removed but website can access

flink-runtime/src/main/java/org/apache/flink/runtime/rest/FileUploadHandler.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/RestServerEndpoint.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/router/MultipartRoutes.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/router/PathPattern.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/router/Router.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/RestServerEndpointITCase.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/router/MultipartRoutesTest.java
See https://github.com/apache/flink/pull/24856 for the PR description.
This is a backport for 1.19. The commits applied cleanly.
=> [FLINK-26808][1.19] Limit FileUploadHandler to multipart routes

flink-clients/src/main/java/org/apache/flink/client/program/DefaultPackagedProgramRetriever.java, flink-clients/src/test/java/org/apache/flink/client/program/DefaultPackagedProgramRetrieverITCase.java
With https://github.com/apache/flink/commit/e63aa12252843d0098a56f3091b28d48aff5b5af in Flink 1.19 an unintentional change were introduced, that now the `DefaultPackagedProgramRetriever` only loads JARs from the root level of the `usrlib` directory.
This change reverts that behavior to search directories in a recursive manner, and adds a test case to cover such scenario.
- `Flies#list` -> `Files#walk` in `DefaultPackagedProgramRetriever`.
- Add test case in `DefaultPackagedProgramRetrieverITCase`.
Added relevant IT case. …
=> [FLINK-35358][clients] Reintroduce recursive JAR listing in classpath load from "usrlib"

flink-clients/src/main/java/org/apache/flink/client/program/DefaultPackagedProgramRetriever.java, flink-clients/src/test/java/org/apache/flink/client/program/DefaultPackagedProgramRetrieverITCase.java
1.19 backport of https://github.com/apache/flink/pull/24791.
=> [BP-1.19][FLINK-35358][clients] Reintroduce recursive JAR listing in classpath load from "usrlib"

flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/SingleSessionManager.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/SqlGatewayRestEndpoint.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/handler/materializedtable/scheduler/CreateEmbeddedSchedulerWorkflowHandler.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/message/materializedtable/scheduler/CreateEmbeddedSchedulerWorkflowRequestBody.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/context/SessionContext.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/materializedtable/MaterializedTableManager.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/operation/OperationExecutor.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/session/Session.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/session/SessionManagerImpl.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/workflow/EmbeddedWorkflowScheduler.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/workflow/WorkflowInfo.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/workflow/scheduler/EmbeddedQuartzScheduler.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/AbstractMaterializedTableStatementITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/rest/SqlGatewayRestEndpointMaterializedTableITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/rest/util/SqlGatewayRestEndpointExtension.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/MaterializedTableStatementITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/workflow/QuartzSchedulerUtilsTest.java, flink-table/flink-sql-gateway/src/test/resources/sql_gateway_rest_api_v3.snapshot, flink-table/flink-table-common/src/main/java/org/apache/flink/table/workflow/CreatePeriodicRefreshWorkflow.java
*Support the execution of create materialized table in full refresh mode*
- *Support the execution of create materialized table in full refresh mode*
- *Add test testCreateMaterializedTableInFullMode in MaterializedTableStatementITCase *
- If yes, how is the feature documented? (Will be added in a separated pr.)
=> [FLINK-35199][table] Support the execution of create materialized table in full refresh mode

flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/runtime/SavepointEnvironment.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/disk/iomanager/IOManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/io/disk/iomanager/IOManagerAsync.java, flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerServices.java, flink-runtime/src/test/java/org/apache/flink/runtime/io/disk/iomanager/IOManagerTest.java, flink-state-backends/flink-statebackend-rocksdb/pom.xml, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/EmbeddedRocksDBStateBackend.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackend.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackendBuilder.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBPriorityQueueSetFactory.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/sstmerge/ColumnFamilyLookup.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/sstmerge/CompactionScheduler.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/sstmerge/CompactionTask.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/sstmerge/CompactionTaskProducer.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/sstmerge/CompactionTracker.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/sstmerge/Compactor.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/sstmerge/RocksDBManualCompactionConfig.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/sstmerge/RocksDBManualCompactionManager.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/sstmerge/RocksDBManualCompactionManagerImpl.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/sstmerge/RocksDBManualCompactionOptions.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/EmbeddedRocksDBStateBackendTest.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/sstmerge/CompactionSchedulerTest.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/sstmerge/CompactionTaskProducerTest.java, flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/core/testutils/ManuallyTriggeredScheduledExecutorService.java
In some cases, the number of files produced by RocksDB state backend grows indefinitely.
This might cause task state info (TDD and checkpoint ACK) to exceed RPC message size and fail recovery/checkpoint in addition to having lots of small files.
With this change, such files are merged in the background using RocksDB API.
Added tests:
- `CompactionSchedulerTest`
- `CompactionTaskProducerTest`
- `EmbeddedRocksDBStateBackendTest#testSmallFilesCompaction`
Verified manually, deployed to Production internally.
=> [FLINK-26050] Manually compact small SST files

flink-end-to-end-tests/test-scripts/common_s3_operations.sh
This pull request aims to make end-to-end test scripts that source `common_s3_operations.sh` fail fast if the aws cli container fails to start. It also adds a single naive retry aiming to recover from a transient network failure.
[FLINK-34569](https://issues.apache.org/jira/browse/FLINK-34569) describes an issue where an end-to-end test run took 15 minutes to fail after the aws cli container failed to start. From the test logs:
```
2024-03-02T04:10:55.5496990Z Unable to find image 'banst/awscli:latest' locally 2024-03-02T04:10:56.3857380Z docker: Error response from daemon: Head "https://registry-1.docker.io/v2/banst/awscli/manifests/latest": read tcp 10.1.0.97:33016->54.236.113.205:443: read: connection reset by peer. 2024-03-02T04:10:56.3857877Z See 'docker run --help'. …
```
=> [Flink 34569][e2e] fail fast if AWS cli container fails to start

flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContext.java, flink-tests/src/test/java/org/apache/flink/test/scheduling/SpeculativeExecutionITCase.java
If the source task does not get assigned a split because the SplitEnumerator has no more splits, and a failover occurs during the closing process, the SourceCoordinatorContext will not resend the NoMoreSplit event to the newly started source task, causing the source vertex to remain stuck indefinitely. 
This case may only occur in batch jobs where speculative execution has been enabled.
- fix the issue that the source task may get stuck in speculative execution mode.
- *Added it case to verify the issue.* …
=> [FLINK-35522][runtime] Fix the issue that the source task may get stuck in speculative execution mode.

flink-end-to-end-tests/test-scripts/common_s3_operations.sh
Our CI logs contain this warning: https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=60060&view=logs&j=af184cdd-c6d8-5084-0b69-7e9c67b35f7a&t=0f3adb59-eefa-51c6-2858-3654d9e0749d&l=3828
```
latest: Pulling from stedolan/jq
[DEPRECATION NOTICE] Docker Image Format v1, and Docker Image manifest version 2, schema 1 support will be removed in an upcoming release. Suggest the author of docker.io/stedolan/jq:latest to upgrade the image to the OCI Format, or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
```
=> [FLINK-35526] Use more up to date jq docker image for Flink e2e tests

flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/materializedtable/MaterializedTableManager.java, flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/workflow/scheduler/EmbeddedQuartzScheduler.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/AbstractMaterializedTableStatementITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/MaterializedTableStatementITCase.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/workflow/EmbeddedSchedulerRelatedITCase.java
*Support the execution of drop materialized table in full refresh mode*
* Support the execution of drop materialized table in full refresh mode
* Add test case `testDropMaterializedTableInFullMode` to verify the execution of drop materialized table in full mode. 
- If yes, how is the feature documented? (Will be added in a separate pr)
=> [FLINK-35201][table] Support the execution of drop materialized table in full refresh mode

docs/data/sql_functions.yml, flink-python/docs/reference/pyflink.table/expressions.rst, flink-python/pyflink/table/expression.py, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CollectionFunctionsITCase.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/ArrayIntersectFunction.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/util/ObjectContainer.java
This is an implementation of ARRAY_INTERSECT
ARRAY_INTERSECT for Table API and SQL
```
Returns an array of the elements in the intersection of array1 and array2, with duplicates.
Syntax:
array_intersect(array1, array2)
Arguments:
Returns:
An ARRAY. If any of the array is null, the function will return null.
Examples:
> SELECT array_intersect(array(1, 1, 3), array(1, 3, 5));
[1,1,3]
```
This change added tests in CollectionFunctionsITCase.
Dependencies (does it add or upgrade a dependency): ( no)
The public API, i.e., is any changed class annotated with @Public(Evolving): (yes )
The serializers: (no)
The …
=> [FLINK-31664] Implement ARRAY_INTERSECT function

flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/EmbeddedRocksDBStateBackend.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateBackendConfigTest.java
See FLINK-35537, an exception thrown when setting 'state.backend.rocksdb.compression.per.level' in flink 1.19.0. I have confirmed that the problem comes from the `EmbeddedRocksDBStateBackend#mergeConfigurableOptions`, which merges two configuration map into one. It uses `toString` of each already parsed value and insert the value string into a new raw map. The `toString` gives the string format of enum list, not the legacy yaml form of the value. The new raw map get parsed later, that's when the error happens.
This PR fixes `EmbeddedRocksDBStateBackend#mergeConfigurableOptions`.
- `EmbeddedRocksDBStateBackend#mergeConfigurableOptions`.
- Added test `testConfigureRocksDBCompressionPerLevel`
Newly added test `testConfigureRocksDBCompressionPerLevel`. …
=> [FLINK-35537] Fix exception when setting 'state.backend.rocksdb.compression.per.level' in yaml

flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/EmbeddedRocksDBStateBackend.java, flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBStateBackendConfigTest.java
See FLINK-35537, an exception thrown when setting 'state.backend.rocksdb.compression.per.level' in flink 1.19.0. I have confirmed that the problem comes from the `EmbeddedRocksDBStateBackend#mergeConfigurableOptions`, which merges two configuration map into one. It uses `toString` of each already parsed value and insert the value string into a new raw map. The `toString` gives the string format of enum list, not the legacy yaml form of the value. The new raw map get parsed later, that's when the error happens.
This PR fixes `EmbeddedRocksDBStateBackend#mergeConfigurableOptions`.
- `EmbeddedRocksDBStateBackend#mergeConfigurableOptions`.
- Added test `testConfigureRocksDBCompressionPerLevel`
Newly added test `testConfigureRocksDBCompressionPerLevel`. …
=> [FLINK-35537][BP-1.19] Fix exception when setting 'state.backend.rocksdb.compression.per.level' in yaml

docs/content.zh/docs/dev/table/sql/alter.md, docs/content/docs/dev/table/sql/alter.md, flink-table/flink-sql-client/src/test/resources/sql/catalog_database.q, flink-table/flink-sql-gateway/src/test/resources/sql/catalog_database.q, flink-table/flink-sql-parser/src/main/codegen/data/Parser.tdd, flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl, flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/ddl/SqlAlterCatalogReset.java, flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/AlterCatalogOptionsOperation.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/AlterCatalogResetOperation.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlAlterCatalogResetConverter.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlNodeConverters.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlDdlToOperationConverterTest.java
Reset one or more properties to its default value in the specified catalog.
* ALTER CATALOG catalog_name RESET (key1, ...)
flink-table/flink-sql-client/src/test/resources/sql/catalog_database.q
flink-table/flink-sql-gateway/src/test/resources/sql/catalog_database.q …
=> [FLINK-35164][table] Support `ALTER CATALOG RESET` syntax

flink-core/src/test/java/org/apache/flink/core/io/LocatableSplitAssignerTest.java
* To ensure at least one fraction of hosts to be local, it should be `ia.getNumberOfLocalAssignments()` as before.
=> [FLINK-35597][test] Fix unstable LocatableSplitAssignerTest#testConcurrentSplitAssignmentForMultipleHosts

docs/content.zh/docs/dev/table/sql/create.md, docs/content/docs/dev/table/sql/create.md, flink-table/flink-sql-client/src/test/resources/sql/catalog_database.q, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/session/SessionManagerImplTest.java, flink-table/flink-sql-gateway/src/test/resources/sql/catalog_database.q, flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl, flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/ddl/SqlCreateCatalog.java, flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/ShowCreateUtil.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/DescribeCatalogOperation.java, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/CreateCatalogOperation.java, flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogManagerTest.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogDescriptor.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlCreateCatalogConverter.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/utils/OperationConverterUtils.java
Introduce comment for CatalogStore and Support enhanced `CREATE CATALOG` syntax
* add comment instance in `CatalogDescriptor` and expose setter/getter function
* CREATE CATALOG [IF NOT EXISTS] catalog_name [COMMENT 'comment_value'] [WITH (property_name=property_value, ...)]
flink-table/flink-sql-client/src/test/resources/sql/catalog_database.q
flink-table/flink-sql-gateway/src/test/resources/sql/catalog_database.q
flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogManagerTest#testCatalogStore
flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest#testAlterCatalog …
=> [FLINK-34917][table] Introduce comment for CatalogStore & Support enhanced `CREATE CATALOG` syntax

flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorAlignmentTest.java, flink-tests/src/test/java/org/apache/flink/test/streaming/api/datastream/WatermarkAlignmentITCase.java
Sources with watermark alignment get stuck once some subtasks finish, this PR solves this problem.
while some subtasks have been finished, the SourceOperator send Long.MAX_VALUE to SourceCoordinator, and SourceCoordinator checks whether subtasks have been finished before sending the event.
- *org.apache.flink.streaming.api.operators.SourceOperatorAlignmentTest::testWatermarkAlignmentWhileSubtaskFinished()*
- *org.apache.flink.test.streaming.api.datastream.WatermarkAlignmentITCase::testTaskFinishedWithWatermarkAlignmentExecution()* …
=> [FLINK-35157][runtime] Sources with watermark alignment get stuck once some subtasks finish

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/wmassigners/WatermarkAssignerOperator.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/wmassigners/WatermarkAssignerOperatorTest.java, flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/wmassigners/WatermarkAssignerOperatorTestBase.java
This is an optimised version of https://github.com/apache/flink/pull/24211 that supersedes it. This newer version avoids having to check current time per each record, as syscalls are quite expensive.
In the current implementation, the lastRecordTime variable, which tracks the time of the last received data element, is updated only when the WatermarkStatus transitions from IDLE to ACTIVE. However, it is not updated when WatermarkStatus is ACTIVE, which means even under continuous data flow, the condition `(currentTime - lastRecordTime > idleTimeout)` will eventually always become true, and the WatermarkStatus will erroneously be marked IDLE.
I believe this bug technically causes incorrect outputs since downstream watermarks advance earlier than they otherwise would. The incorrect state …
=> [optimised][FLINK-34252][table] Fix lastRecordTime tracking in WatermarkAssignerOperator

docs/config.toml, pom.xml
I see that `1.19.1` has been announced but these were not updated for now.
cc @hlteoh37 In case you forget it :)
=> [hotfix] update doc version and japicmp for 1.19.1

flink-table/flink-table-planner/src/main/java/org/apache/calcite/sql/validate/ProcedureNamespace.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/sql/SqlWindowTableFunction.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/MiscTests.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/WindowRankTestPrograms.java
Fix the bug that it is not possible to name arguments in a windowed rank query if the results are inserted into explicit columns of the sink.
Added a test in `MiscTests` …
=> [FLINK-35619] Window rank query fails with 'must call validate first'

docs/content.zh/docs/dev/table/sourcesSinks.md, docs/content.zh/docs/dev/table/sql/alter.md, docs/content.zh/docs/dev/table/sql/create.md, docs/content/docs/dev/table/sourcesSinks.md, docs/content/docs/dev/table/sql/alter.md, docs/content/docs/dev/table/sql/create.md
Add documentation to cover FLIP-376.
=> [FLINK-35585] Add documentation for distribution

flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/JsonFunctionsITCase.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/SqlJsonUtils.java
Fix a bug that objects and arrays were incorrectly formatted for `JSON QUERY` with `RETURNING ARRAY<STRING>` clause.
Added tests in `JsonFunctionsITCase`
- If yes, how is the feature documented? (**not applicable** / docs …
=> [FLINK-35687] JSON_QUERY should return a well formatted nested objects/arrays for ARRAY<STRING>

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/DefaultRescaleManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Executing.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/RescaleManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/scalingpolicy/EnforceMinimalIncreaseRescalingController.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/DefaultRescaleManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/ExecutingTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/TestingRescaleManager.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/scalingpolicy/EnforceMinimalIncreaseRescalingControllerTest.java
* ⭐ FLINK-35550: https://github.com/apache/flink/pull/24909
* FLINK-35551: https://github.com/apache/flink/pull/24910
* FLINK-35552: https://github.com/apache/flink/pull/24911
* FLINK-35553: https://github.com/apache/flink/pull/24912
The purpose of this PR is the reorganization of responsibilities for rescaling.
[Class diagrams](https://app.diagrams.net/#G13IwZnJrZ_NBxkDYdAUz2IydP3A5qv8uH#%7B%22pageId%22%3A%22C5RBs43oDa-KdzZeNtuy%22%7D)
* Introduction of new interfaces `RescaleManager`, `RescaleManager.Context` and `RescaleManager.Factory`
* Responsibilities:
* `AdaptiveScheduler` only provides the available parallelism (through the `SlotManager`). The rescalingControllers moved into `RescaleManager`
* `Executing` is only in charge of state transitition and savepoints
* `RescaleManager` …
=> [FLINK-35550][runtime] Move rescaling functionality into dedicated class RescaleManager

docs/layouts/shortcodes/generated/all_jobmanager_section.html, docs/layouts/shortcodes/generated/expert_scheduling_section.html, docs/layouts/shortcodes/generated/job_manager_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/JobManagerOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/DefaultRescaleManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Executing.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/RescaleManager.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/DefaultRescaleManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/ExecutingTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/TestingRescaleManager.java
* FLINK-35550: https://github.com/apache/flink/pull/24909
* ⭐ FLINK-35551: https://github.com/apache/flink/pull/24910
* FLINK-35552: https://github.com/apache/flink/pull/24911
* FLINK-35553: https://github.com/apache/flink/pull/24912
Introduces new `RescaleManager#onTrigger` endpoint that can be used to initiate a possible rescaling.
* Introduces `RescaleManager#onTrigger` as a new interface method
* Adds `DefaultRescaleManager#onTrigger` implementation
* Makes `Executing` call the new `onTrigger` method subsequently to `onChange` to simulate the old behavior
* Adapted `DefaultRescaleManagerTest` to run `onTrigger` subsequently to `onChange` for now
* Adds new test for checking noop behaviour if only on `onTrigger` is called (i.e. for AUTO-649 this means that a checkpoint is completed w/o …
=> [FLINK-35551][runtime] Introduces RescaleManager#onTrigger endpoint

flink-kubernetes/pom.xml
The `flink-kubernetes` artifact shades Jackson classes coming through fabric8, but since Jackson 2.15, Jackson is a [multi-release JAR](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15#jar-changes), which requires some additional relocations for correct shading.
What Jackson does itself can be checked [here](https://github.com/FasterXML/jackson-core/blob/80e6c424ef876f31f07d3ce12c68ecd5294fe004/pom.xml#L192).
- Added exclusions for Jackson related meta files, which otherwise overwrites the Flink ones.
- Added relocations for JDK-specific code. …
=> [FLINK-35699][k8s] Fix shading Jackson through fabric8

flink-kubernetes/pom.xml
The `flink-kubernetes` artifact shades Jackson classes coming through fabric8, but since Jackson 2.15, Jackson is a [multi-release JAR](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15#jar-changes), which requires some additional relocations for correct shading.
What Jackson does itself can be checked [here](https://github.com/FasterXML/jackson-core/blob/80e6c424ef876f31f07d3ce12c68ecd5294fe004/pom.xml#L192).
- Added exclusions for Jackson related meta files, which otherwise overwrites the Flink ones.
- Added relocations for JDK-specific code. …
=> [1.20][FLINK-35699][k8s] Fix shading Jackson through fabric8

flink-kubernetes/pom.xml
The `flink-kubernetes` artifact shades Jackson classes coming through fabric8, but since Jackson 2.15, Jackson is a [multi-release JAR](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15#jar-changes), which requires some additional relocations for correct shading.
What Jackson does itself can be checked [here](https://github.com/FasterXML/jackson-core/blob/80e6c424ef876f31f07d3ce12c68ecd5294fe004/pom.xml#L192).
- Added exclusions for Jackson related meta files, which otherwise overwrites the Flink ones.
- Added relocations for JDK-specific code. …
=> [BP-1.19][FLINK-35699][k8s] Fix shading Jackson through fabric8

flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/ParquetVectorizedInputFormat.java, flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/ParquetColumnarRowSplitReader.java, flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/ParquetFileSystemITCase.java
In `ParquetVectorizedInputFormat.java` the row group filter is set
```
FilterCompat.Filter filter = getFilter(hadoopConfig.conf());
ParquetReadOptions parquetReadOptions =
ParquetReadOptions.builder()
.withRange(splitOffset, splitOffset + splitLength)
.withRecordFilter(filter)
.build();
```
But the row groups are read incorrectly using `readNextRowGroup` instead of `readNextFilteredRowGroup`. This affects the performance (filters are not working because all row groups are read) and also could lead to incorrect result because eventually returning here (totalRowCount are calculated with filters applied):
```
if (rowsReturned >= totalRowCount) {
return false;
}
```
- *Changed `readNextRowGroup` to `readNextFilteredRowGroup` in `ParquetColumnarRowSplitReader::readNextRowGroup`*
- *Changed …
=>  [hotfix][parquet] fix row group filter support issue

flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/materializedtable/MaterializedTableManager.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/MaterializedTableStatementITCase.java
Currently, in continuous mode, the checkpoint interval is set based on freshness by default. However, if the user explicitly sets a checkpoint interval, we should follow the user's setting.
* Fix periodic refresh job naming.
* Do not override the user-defined checkpoint interval in continuous mode
* Add test `testCreateMaterializedTableInContinuousModeWithCustomCheckpointInterval` in MaterializedTableStatementITCase to verify that we don't over write the user custom checkpoint interval. …
=> [FLINK-35734][table] Do not override the user-defined checkpoint interval in continuous mode.

flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/ExtractionUtils.java, flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/extraction/ExtractionUtilsTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/FunctionITCase.java
Currently, we depend on asm to extract method parameter names. We custom a MethodVisitor to visit local variable tables in  file `.class`, and then cut the first `N` local variable names as the method parameter names. 
However, if there are multi blocks about one local variable, the first `N` local variable names could be same, and then wrongly be extracted, and crashed when validating the conflict of them(the new logic added in FLINK-1.19).
This pr will use the slot index in `.class` file to extract the method parameter names, because method parameter names are always at the head in the 'slot index' list(https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-3.html)
Take the test function `ExtractionUtilsTest#MultiLocalVariableBlocksWithoutInitializationClass` as an example:
- Before …
=> [FLINK-35498][table] Fix unexpected argument name conflicts when extracting method parameter names from UDF

flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/materializedtable/MaterializedTableManager.java, flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/MaterializedTableStatementITCase.java
BP 1.20 for https://github.com/apache/flink/pull/25002
Currently, in continuous mode, the checkpoint interval is set based on freshness by default. However, if the user explicitly sets a checkpoint interval, we should follow the user's setting.
* Fix periodic refresh job naming.
* Do not override the user-defined checkpoint interval in continuous mode
* Add test `testCreateMaterializedTableInContinuousModeWithCustomCheckpointInterval` in MaterializedTableStatementITCase to verify that we don't over write the user custom checkpoint interval. …
=> [BP-1.20][FLINK-35734][table] Do not override the user-defined checkpoint interval in continuous mode

docs/content/docs/deployment/advanced/job_status_listener.md, docs/layouts/shortcodes/generated/deployment_configuration.html, flink-clients/src/main/java/org/apache/flink/client/deployment/application/executors/EmbeddedExecutor.java, flink-clients/src/main/java/org/apache/flink/client/deployment/application/executors/EmbeddedExecutorFactory.java, flink-clients/src/main/java/org/apache/flink/client/deployment/application/executors/WebSubmissionExecutorFactory.java, flink-clients/src/main/java/org/apache/flink/client/deployment/executors/AbstractSessionClusterExecutor.java, flink-clients/src/main/java/org/apache/flink/client/deployment/executors/LocalExecutor.java, flink-clients/src/main/java/org/apache/flink/client/deployment/executors/PipelineExecutorUtils.java, flink-clients/src/main/java/org/apache/flink/client/deployment/executors/RemoteExecutorFactory.java, flink-core/src/main/java/org/apache/flink/configuration/DeploymentOptions.java, flink-core/src/main/java/org/apache/flink/core/execution/DefaultJobExecutionStatusEvent.java, flink-core/src/main/java/org/apache/flink/core/execution/JobExecutionStatusEvent.java, flink-core/src/main/java/org/apache/flink/core/execution/JobStatusChangedEvent.java, flink-core/src/main/java/org/apache/flink/core/execution/JobStatusChangedListener.java, flink-core/src/main/java/org/apache/flink/core/execution/JobStatusChangedListenerFactory.java, flink-core/src/main/java/org/apache/flink/core/execution/JobStatusChangedListenerUtils.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/executors/KubernetesSessionClusterExecutor.java, flink-kubernetes/src/main/java/org/apache/flink/kubernetes/executors/KubernetesSessionClusterExecutorFactory.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java, flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraphBuilder.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraph.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/execution/DefaultJobCreatedEvent.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/execution/JobCreatedEvent.java, flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/test/util/MiniClusterPipelineExecutorServiceLoader.java, flink-tests/src/test/java/org/apache/flink/test/execution/JobStatusChangedListenerITCase.java, flink-yarn/src/main/java/org/apache/flink/yarn/executors/YarnSessionClusterExecutor.java, flink-yarn/src/main/java/org/apache/flink/yarn/executors/YarnSessionClusterExecutorFactory.java
This PR is to implement the job status changed listener for lineage in FLIP-314. This PR use class loader to load listeners in pipeline executors, including LocalExecutor, EmbeddedExecutor for application mode and AbstractSessionClusterExecutor for session cluster. When job graph submission is successfully, the JobCreatedEvent with lineage info will be published to listeners. During the runtime, job status change info will also be published to listeners.
-  Add interfaces for job status change listener  
-  Add Events and configs for job status listener.
- Add logic pipeline executors for notifying the job created event for local, application mode, and session cluster.
- The end to end test is covered by JobStatusListenerITCase 
- …
=> [FLINK-33212][runtime] add job status changed listener for lineage

flink-python/dev/lint-python.sh
Update the Conda endpoint URL following the Conda community's decision to deprecate repo.continuum.io and migrate to the new endpoint repo.anaconda.com.
Replaced all instances of repo.continuum.io with repo.anaconda.com.
Reference:
For more details, see the discussion in the Conda issue: [conda/conda#6886](https://github.com/conda/conda/issues/6886).
- Build tests are getting succeeded . 
- Verified PyFlink end-to-end test is executed and succeeded properly. …
=> [FLINK-35728][python] Move conda url from repo.continuum.io to repo.anaconda.com

docs/layouts/shortcodes/generated/deployment_configuration.html, flink-clients/src/main/java/org/apache/flink/client/cli/CliFrontend.java, flink-clients/src/main/java/org/apache/flink/client/cli/CliFrontendParser.java, flink-clients/src/main/java/org/apache/flink/client/cli/GenericCLI.java, flink-clients/src/test/java/org/apache/flink/client/cli/CliFrontendRunTest.java, flink-clients/src/test/java/org/apache/flink/client/cli/util/DummyClusterDescriptor.java, flink-core/src/main/java/org/apache/flink/configuration/DeploymentOptions.java
Merge the functionality of "flink run" and "flink run-application" under the "run" command to make job deployment more consistent. Also deprecate "run-application" so it can be removed together with "yarn-per-job" in the future.
- Introduced `isApplication(...)` check method in `FrontendCli` to determine necessary deployment steps.
- Handle application mode deployment in `FrontendCli#run`.
- In `FrontendCli#runApplication`, simply call `FrontendCli#run` after argument check.
- Added unit tests to cover the introduced code flow changes in `CliFrontendRunTests`.
- Updated, adapted CLI help/usage messages, and relevant config option documentation.
- Marked `run-application` deprecated in code, config docs, and help/usage messages. 
Unit tests were added to cover the introduced changes.
Also …
=> [FLINK-35625][cli] Merge "flink run" and "flink run-application" functionality, deprecate "run-application"

.github/actions/stringify/action.yml, .github/workflows/nightly.yml, .github/workflows/template.flink-ci.yml, flink-python/pyproject.toml
Integrates Python Wheels build into the GitHub Actions (GHA) nightly workflow.
- Adds Python Wheels GHA workflow, `template.python-wheels-ci.yml`
- Integrates the Python Wheels workflow to the nightly GHA workflow
This changes does not change code. 
But the successful nightly GHA run should verify the change.
=> [FLINK-34487][ci] Adds Python Wheels nightly GHA workflow

flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/context/SessionContext.java
*Use CatalogManager#close when closing the session instead of listing all catalogs and then closing each of them. *
- *Close the catalog manager when closing the session*
No tests need be added.
=> [FLINK-35735][sql-gateway] Don't list all catalogs when closing session

flink-core/src/main/java/org/apache/flink/core/fs/CloseableRegistry.java, flink-core/src/main/java/org/apache/flink/core/fs/ICloseableRegistry.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackend.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackendBuilder.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBOperationUtils.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBPriorityQueueSetFactory.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBFullRestoreOperation.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBHandle.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBHeapTimersFullRestoreOperation.java, flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBIncrementalRestoreOperation.java
We observe a lot of TMs stuck for > 30s in RocksDBHandle.registerStateColumnFamilyHandleWithImport which boil down to native calls to create Column Family. This change registers prevents CF creation if task cancellation is in progress.
Please make sure both new and modified tests in this PR follow [the conventions for tests defined in our code quality …
=> [FLINK-35742] Don't create RocksDB Column Family if task cancellation is in progress

docs/layouts/shortcodes/generated/all_jobmanager_section.html, docs/layouts/shortcodes/generated/expert_scheduling_section.html, docs/layouts/shortcodes/generated/job_manager_configuration.html, flink-core/src/main/java/org/apache/flink/configuration/JobManagerOptions.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointStatsListener.java, flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/DefaultCheckpointStatsTracker.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/DefaultRescaleManager.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Executing.java, flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/State.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/DefaultCheckpointStatsTrackerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerBuilder.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/DefaultRescaleManagerTest.java, flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/ExecutingTest.java, flink-tests/src/test/java/org/apache/flink/test/scheduling/RescaleOnCheckpointITCase.java
* FLINK-35550: https://github.com/apache/flink/pull/24909
* FLINK-35551: https://github.com/apache/flink/pull/24910
* FLINK-35552: https://github.com/apache/flink/pull/24911
* ⭐ FLINK-35553: https://github.com/apache/flink/pull/24912
Make rescale be synchronized with the checkpoint creation for faster recovery.
* Introduced new `CheckpointLifecyclListener` that allows the `AdaptiveScheduler` to monitor checkpoint completion
* `RescaleManager.Context.onTrigger` will be called if a checkpoint was completed or if a configured amount of subsequent failed checkpoints appeared (new configuration parameter: `jobmanager.adaptive-scheduler.rescale-on-failed-checkpoints-count`)  
Additional tests were added to check the trigger behavior in `ExecutingTest`. …
=> [FLINK-35553][runtime] Wires up the RescaleManager with the CheckpointLifecycleListener interface

flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/testutils/RestoreTestCompleteness.java
When FLINK-34268 was initially implemented, FLINK-33676 and FLINK-33805 had not landed.
Given that, there were exclusions hard-coded.  This PR removes those.
=> [FLINK-34268] Removing exclusions for FLINK-33676 33805

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/JsonValueCallGen.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/JsonFunctionsITCase.java, flink-table/flink-table-planner/src/test/resources/json/json-value.json, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/SqlJsonUtils.java
This PR fixes how floating numbers are parsed and then converted to STRING in `JSON_QUERY/JSON_VALUE` functions.
Added tests in `JsonFunctionsITCase`
- If yes, how is the feature documented? (**not applicable** / docs / …
=> [FLINK-35696] JSON_VALUE/QUERY functions incorrectly map floating numbers

flink-core/src/main/java/org/apache/flink/configuration/Configuration.java, pom.xml
[FLINK-34130][core] Mark setBytes and getBytes of Configuration as @Internal
[FLINK-34130][core] Mark setBytes and getBytes of Configuration as @Internal
=> [FLINK-34130][core] Mark setBytes and getBytes of Configuration as @Internal

flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/InternalOperatorMetricGroup.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperator.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperatorV2.java
Fix that the latency marker metrics aren't updated after failover.
Change the latency metric into the TaskMetricsGroup.
Verified locally.  
before the exception:  
after the exception:    …
=> [FLINK-35750][runtime/metrics] Fix that the latency marker metrics aren't updated after failover.

flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/windowing/WindowOperator.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/windowing/WindowOperatorTest.java
1.18 backport for parent PR https://github.com/apache/flink/pull/24917
---
* This Pull Request addresses an important state memory leak issue identified within the default window operator of Apache Flink. 
* After this change, the cleanup timer should be registered for every window that's added to the window state regardless of it emitting a result after it’s fired.
* This change is associated to the following bug: [FLINK-33192
](https://issues.apache.org/jira/projects/FLINK/issues/FLINK-33192)
Modified `org.apache.flink.streaming.runtime.operators.windowing.WindowOperator` to register clean up timer for window states regardless of whether emits a result or not. 
- WindowOperatorTest is working for functional correctness.
- Written a new test …
=> [BP-1.18] [FLINK-33192] Fix Memory Leak in WindowOperator due to Improper Timer Cleanup

flink-runtime-web/web-dashboard/src/app/services/job-manager.service.ts, flink-runtime-web/web-dashboard/src/app/services/metrics.service.ts, flink-runtime-web/web-dashboard/src/app/services/task-manager.service.ts
Flink UI always shows float metric value as int/long. For example, `outPoolUsage`/`inPoolUsage` are always 0 or 1 at UI. That's not helpful when troubleshooting from UI. 
After investigation, I found it's because we always parse the metric value via `parseInt` method. We should use `parseFloat` for it. The `parseFloat` can achieve what we expect because when the provided string is a integer, it'll also parsed as an integer, not float. Like this:
Before this change, the UI is displayed like this:
After this change, the UI can display float value like this:
Replacing `parseInt` with `parseFloat` to parse metric value. …
=> [FLINK-35657][runtime-web] use parseFloat for metric value

flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/windowing/WindowOperator.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/windowing/WindowOperatorTest.java
1.19 backport for parent PR https://github.com/apache/flink/pull/24917
---
* This Pull Request addresses an important state memory leak issue identified within the default window operator of Apache Flink. 
* After this change, the cleanup timer should be registered for every window that's added to the window state regardless of it emitting a result after it’s fired.
* This change is associated to the following bug: [FLINK-33192
](https://issues.apache.org/jira/projects/FLINK/issues/FLINK-33192)
Modified `org.apache.flink.streaming.runtime.operators.windowing.WindowOperator` to register clean up timer for window states regardless of whether emits a result or not. 
- WindowOperatorTest is working for functional correctness.
- Written a new test …
=> [BP-1.19] [FLINK-33192] Fix Memory Leak in WindowOperator due to Improper Timer Cleanup 

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerBase.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerTestBase.java
Currently, the file-merging manager for checkpoint files will create directories based on tm resource id, job id and operator ids. While in some cases, these ids include some characters that are reserved in URI scheme. This PR does a simple escape for those ids.
- Add a tool method `uriEscape` in file-merging manager.
- New UT `FileMergingSnapshotManagerTestBase#testSpecialCharactersInPath`.
- Does this …
=> [FLINK-35778] Escape URI reserved characters when creating file-merging directories

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerBase.java, flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerTestBase.java
Currently, the file-merging manager for checkpoint files will create directories based on tm resource id, job id and operator ids. While in some cases, these ids include some characters that are reserved in URI scheme. This PR does a simple escape for those ids.
- Add a tool method `uriEscape` in file-merging manager.
- New UT `FileMergingSnapshotManagerTestBase#testSpecialCharactersInPath`.
- Does this …
=> [BP-1.20][FLINK-35778] Escape URI reserved characters when creating file-merging directories

flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/ddl/SqlCreateTableAs.java, flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/MergeTableAsUtil.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/MergeTableLikeUtil.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SchemaBuilderUtil.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlCreateTableConverter.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/calcite/PreValidateReWriter.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/calcite/SqlRewriterUtils.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlDdlToOperationConverterTest.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/TableSinkITCase.scala
Allow defining new columns and/or overriding source column types in the `CREATE` clause on CTAS statements.
Syntax supported:
```
CREATE TABLE table_name [( <column_definition>[, ...n] )]
AS SELECT query_expression;
```
- *Added support for column definition in the CREATE clause*
This change added tests and can be verified as follows: 
- *Added unit tests to validation and converter classes*
- *Manually verified the change by running a single node cluster and sql client*
Quick test using a compute column to check the expression is evaluated using source columns:
```
Flink SQL> create table t1(id int, name string) with ('connector'='filesystem', 'format'='json', 'path'='/tmp/t1');
[INFO] Execute statement succeeded.
Flink SQL> insert into t1 values (1, 's1');
[INFO] Submitting SQL update …
```
=> [FLINK-35707][Table SQL / API] Allow column definition in CREATE TABLE AS (CTAS)

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/OperatorSubtaskState.java, flink-runtime/src/main/java/org/apache/flink/runtime/state/filemerging/FileMergingOperatorStreamStateHandle.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/ResumeCheckpointManuallyITCase.java, flink-tests/src/test/java/org/apache/flink/test/checkpointing/SnapshotFileMergingCompatibilityITCase.java
The `OperatorSubtaskState` only make keyed state register with `SharedStateRegistry`. However, the file-merging directories's handle are wrapped in `FileMergingOperatorStreamStateHandle}` which is an `OperatorStreamStateHandle`. That means the `#registerSharedStates` is never called, so the registry(JM) will never know and delete the directories.
- In `OperatorSubtaskState`, we register `FileMergingOperatorStreamStateHandle`.
Modified tests in `SnapshotFileMergingCompatibilityITCase`. …
=> [FLINK-35784][checkpoint] Fix the missing shared state registration of file-merging directories

flink-core/src/main/java/org/apache/flink/api/common/operators/MailboxExecutor.java, flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperator.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/MailboxOperatorTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamOperatorWrapperTest.java, flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
FLINK-34470 showed that MailboxExecutor.submit may result in unexpected exception handling: while execute will bubble up the exception in the task thread and result in some fault, submit can hide the exception because the API assumes that the returned Future is checked for it explicitly or implicitly.
This commit improves the doc of MailboxExecutor and replaces incorrect internal usages.
This change is already covered by existing tests, such as MailboxOperatorTest, StreamOperatorWrapperTest.
- …
=> [FLINK-35796] Replace Mailbox#submit where needed

docs/data/sql_functions.yml, docs/data/sql_functions_zh.yml, flink-python/docs/reference/pyflink.table/expressions.rst, flink-python/pyflink/table/expression.py, flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java, flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/UrlFunctionsITCase.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/UrlDecodeFunction.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/UrlEncodeFunction.java
issue: https://issues.apache.org/jira/browse/FLINK-34108
This is an implementation of URL_ENCODE and URL_DECODE
1. URL_ENCODE: Translates a string into 'application/x-www-form-urlencoded' format using a specific encoding scheme(UTF-8).
2. URL_DECODE: Decodes a string in 'application/x-www-form-urlencoded' format using a specific encoding scheme(UTF-8).
1. **URL_ENCODE**
- Syntax: 
url_encode(url)
- Arguments: 
url: a string represents a URL
- Returns: 
translates a string into 'application/x-www-form-urlencoded' format using a specific encoding scheme(UTF-8), will be null if the input is null or encode failed.
- Examples:
```
url = 'https://flink.apache.org/'
SQL: url_encode(url)
TableAPI: url.urlEncode()
output: 'https%3A%2F%2Fflink.apache.org%2F'
```
2. **URL_DECODE**
- Syntax: …
=> [FLINK-34108][table] Add built-in URL_ENCODE and URL_DECODE function.

flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/ddl/SqlCreateTableAs.java, flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/MergeTableAsUtil.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/MergeTableLikeUtil.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SchemaBuilderUtil.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlCreateTableConverter.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlDdlToOperationConverterTest.java
Allows defining the WATERMARK and PRIMARY KEY in the CTAS statement. 
PRIMARY KEY example:
```
CREATE TABLE table_name (PRIMARY KEY (person) NOT ENFORCED)
AS SELECT person, age FROM people;
```
WATERMARK example example:
```
CREATE TABLE table_name (WATERMARK FOR ts AS ts - INTERVAL '3' SECOND)
AS SELECT f0, f1, ts FROM people;
```
- Added support for WATERMARK and PRIMARY KEY syntax in CTAS
- Added unit tests to validation and converter classes
- Added integration tests …
=> [FLINK-35789][table] Allow defining watermarks & PRIMARY KEY in CREATE TABLE AS (CTAS)

docs/content.zh/docs/dev/table/materialized-table/statements.md, docs/content/docs/dev/table/materialized-table/overview.md, docs/content/docs/dev/table/materialized-table/statements.md, flink-end-to-end-tests/flink-sql-gateway-test/src/test/java/org/apache/flink/table/gateway/SqlGatewayE2ECase.java, flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/core/testutils/CommonTestUtils.java
*Fix unstable testMaterializedTableInFullMode test case*
- *Fix SqlGatewayE2ECase.testMaterializedTableInFullMode failed *
*It's a test fix* 
=> [FLINK-35754][e2e] Fix SqlGatewayE2ECase.testMaterializedTableInFullMode failed due to Internal Server Error

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/PhysicalFile.java
There is an issue of reusing wrong restored files in following cp when enabling file-merging. All the files from previous job should not be reused afterwards. This PR fixes that.
- When creating/referencing a `PhysicalFile` during recovery, mark it unable to reuse.
This change is already covered by existing IT tests, such as `ResumeCheckpointManuallyITCase`. …
=> [FLINK-35803][checkpoint] Fix the wrong file reuse in cp file-merging

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/PhysicalFile.java
There is an issue of reusing wrong restored files in following cp when enabling file-merging. All the files from previous job should not be reused afterwards. This PR fixes that.
- When creating/referencing a `PhysicalFile` during recovery, mark it unable to reuse.
This change is already covered by existing IT tests, such as `ResumeCheckpointManuallyITCase`. …
=> [BP-1.20][FLINK-35803][checkpoint] Fix the wrong file reuse in cp file-merging

flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/ddl/SqlCreateTableAs.java, flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlCreateTableConverter.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlDdlToOperationConverterTest.java
*Allows defining PARTITIONED BY and DISTRIBUTED BY in the CTAS statement.*
Syntax supported:
```
CREATE TABLE table_name
[PARTITIONED BY (cols)]
[DISTRIBUTED BY [HASH|RANGE|RANDOM](cols) [INTO n BUCKETS]]
AS SELECT query_expression;
```
- *Added support for DISTRIBUTED BY syntax in CTAS*
- - *Added support for PARTITIONED BY syntax in CTAS*
- Added unit tests to validation and converter classes
- Manually verified the change by running a single node cluster and sql client …
=> [FLINK-35717][table] Allow defining partition keys and table distribution in CREATE TABLE AS (CTAS)

flink-tests/src/test/java/org/apache/flink/test/checkpointing/SnapshotFileMergingCompatibilityITCase.java
This PR fixes the unstable test `SnapshotFileMergingCompatibilityITCase`. There is a problem with the test code itself. The test verifies the cp files are cleaned as expected, which depends on an async cleaner (the job io thread). While the mini-cluster quit, the async threads may not have finished their jobs before termination.
It is better to try multiple rounds AZP to verify this fix.
Only `SnapshotFileMergingCompatibilityITCase`. Make it wait for file deletion before cluster termination. …
=> [FLINK-35801] Fix SnapshotFileMergingCompatibilityITCase, wait for file deletion before quit

flink-tests/src/test/java/org/apache/flink/test/checkpointing/SnapshotFileMergingCompatibilityITCase.java
This PR fixes the unstable test `SnapshotFileMergingCompatibilityITCase`. There is a problem with the test code itself. The test verifies the cp files are cleaned as expected, which depends on an async cleaner (the job io thread). While the mini-cluster quit, the async threads may not have finished their jobs before termination.
It is better to try multiple rounds AZP to verify this fix.
Only `SnapshotFileMergingCompatibilityITCase`. Make it wait for file deletion before cluster termination. …
=> [BP-1.20][FLINK-35801] Fix SnapshotFileMergingCompatibilityITCase, wait for file deletion before quit

flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/UrlDecodeFunction.java, flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/UrlEncodeFunction.java
1. Use uppercase for function names 
2. remove logging since in function classes it could lead to disk space issue while being used in streaming for huge amount of events per time unit
- Does this pull request introduce a new feature? (/no)
=> [hotfix][table] Apply uppercase for URL_ENCODE/URL_DECODE remove logging from function class

docs/content.zh/docs/dev/table/materialized-table/statements.md, docs/content/docs/dev/table/materialized-table/overview.md, docs/content/docs/dev/table/materialized-table/statements.md, flink-end-to-end-tests/flink-sql-gateway-test/src/test/java/org/apache/flink/table/gateway/SqlGatewayE2ECase.java, flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/core/testutils/CommonTestUtils.java
BP https://github.com/apache/flink/pull/25029
*Fix unstable testMaterializedTableInFullMode test case*
- *Fix SqlGatewayE2ECase.testMaterializedTableInFullMode failed *
*It's a test fix* 
=> [BP-1.20][FLINK-35754][e2e] Fix SqlGatewayE2ECase.testMaterializedTableInFullMode failed due to Internal Server Error

flink-core/src/main/java/org/apache/flink/util/TimeUtils.java, flink-core/src/test/java/org/apache/flink/util/TimeUtilsPrettyPrintingTest.java, flink-core/src/test/java/org/apache/flink/util/TimeUtilsTest.java
Supports converting all values of Duration to/from String.
Added tests.
=> [FLINK-35820] Converting Duration to String fails for big values

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalWindowTableFunction.scala, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/WindowTableFunctionTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/WindowTableFunctionTest.scala
*Fix that `StreamPhysicalWindowTableFunction` always requires watermark*.
- *Change `StreamPhysicalWindowTableFunction#requireWatermark`*
- *Add tests*
Some tests are added to verify it.
=> [FLINK-35829][table-planner] Fix StreamPhysicalWindowTableFunction always requires watermark

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/DeletePushDownUtils.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/abilities/source/FilterPushDownSpec.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/PushFilterIntoLegacyTableSourceScanRule.java, flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/PushPartitionIntoTableSourceScanRule.java, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/logical/PushPartitionIntoLegacyTableSourceScanRule.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/FlinkRexUtil.scala, flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/RexNodeExtractor.scala, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/DeletePushDownUtilsTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/rules/logical/PushFilterInCalcIntoTableSourceRuleTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/rules/logical/PushFilterIntoTableSourceScanRuleTest.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/rules/logical/PushFilterIntoTableSourceScanRuleTestBase.java, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/PushFilterInCalcIntoTableSourceRuleTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/PushFilterIntoLegacyTableSourceScanRuleTest.xml, flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/PushFilterIntoTableSourceScanRuleTest.xml, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/rules/logical/PushFilterIntoLegacyTableSourceScanRuleTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/utils/RexNodeExtractorTest.scala
RexNodeToExpressionConverter#visitLiteral should not convert the literal to UTC using specified timezone again since this has been done before at the SQL to Rel phase.
=> [FLINK-35318][table-planner] use UTC timezone to handle TIMESTAMP_WITHOUT_TIME_ZONE type in RexNodeToExpressionConverter

flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStreamFactory.java, flink-runtime/src/test/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStateOutputStreamTest.java
Fix the concurrency issue between `close` and `flushToFile` of `FsCheckpointStateOutputStream`, which cause a file leak. 
Co-authored-by: Zakelly <zakelly.lan@gmail.com>
1. Add `synchronized` in `close`, `closeAndGetHandle`, and `flushToFile` methods in `FsCheckpointStateOutputStream`.
2. For `write` method, we only add lock when manipulating outStream, to avoid the additional overhead for the hot path `write` method. 
I think it can fix the issue as well as keep the best checkpointing performance.  
3. Add test to verify the concurrency issue is protected well.
This change added a test to verify the concurrency issue is fixed. …
=> [FLINK-28984][checkpoint] Fix concurrency issue between close and flushToFile in FsCheckpointStateOutputStream

docs/static/generated/rest_v1_dispatcher.yml, flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/WebFrontendITCase.java, flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/JobConfigInfo.java, flink-runtime/src/test/java/org/apache/flink/runtime/rest/messages/JobConfigInfoTest.java
[FLINK-35227][rest] Remove execution-mode in ExecutionConfigInfo
[FLINK-35227][rest] Remove execution-mode in ExecutionConfigInfo
=> [FLINK-35227][rest] Remove execution-mode in ExecutionConfigInfo

flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/IfNullTypeStrategy.java, flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/MiscFunctionsITCase.java, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/ScalarFunctionsTest.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CalcITCase.scala, flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/CalcITCase.scala
Fix the incorrect output datatype of `IFNULL`.
The `IfNullTypeStrategy` previously takes the datatype of nullReplacement as the output datatype when the first arg is nullable, which is incorrect and conflicted with doc description. 
We change the output datatype to the common type of both args and overwrite the nullability if needed.
`MiscFunctionsITCase` …
=> [FLINK-35832][Table SQL / Planner] Fix IFNULL outputTypeStrategy
