apache/flink

flink-filesystems/flink-s3-fs-base/src/test/java/org/apache/flink/fs/s3/common/S5CmdOnMinioITCase.java

Fix S5CmdOnMinioITCase failed due to IllegalAccessError in JDK17/21
This is change in tests.

[FLINK-35860][test] Fix S5CmdOnMinioITCase failed due to IllegalAccessError in JDK17/21

---

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CompletedCheckpointStore.java
flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/DeactivatedCheckpointCompletedCheckpointStore.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/allocator/JobAllocationsInformation.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/allocator/StateLocalitySlotAssigner.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/allocator/StateSizeEstimates.java
flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorFailureTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/allocator/SlotSharingSlotAllocatorTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/allocator/StateLocalitySlotAssignerTest.java

FLINK-21450 / #21981 made Adaptive Scheduler aware of Local State.
This PR improves on that by estimating state size (instead of number of key groups).
- Added unit test: `StateLocalitySlotAssignerTest.testDownScaleWithUnevenStateSize` …

[FLINK-31261][runtime] Make AdaptiveScheduler aware of local state size

---

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/DataStreamSink.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/lineage/DefaultLineageVertex.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/lineage/DefaultSourceLineageVertex.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/transformations/LegacySourceTransformation.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/transformations/SourceTransformation.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/lineage/LineageGraphUtilsTest.java
flink-tests/src/test/java/org/apache/flink/test/execution/JobStatusChangedListenerITCase.java

Support Lineage info extraction for Stream API use cases.
- Add LineageVertexInfo into transformation when user use DataStream API to add source and sink
- Add Test cases in LineageGraphUtilsTest for source and sink.
- Add test cases in LineageGraphUtils
- Add test cases in JobStatusChangedListenerITCase …

[FLINK-34657] extract lineage info for stream API

---

docs/content.zh/docs/ops/upgrading.md
docs/content/docs/ops/upgrading.md

[FLINK-35678][doc] Update compatibility matrix for 1.20 release
[FLINK-35678][doc] Update compatibility matrix for 1.20 release
As I know, flink 1.20 doesn't break the compatibility.

[FLINK-35678][doc] Update compatibility matrix for 1.20 release

---

flink-table/flink-sql-parser/pom.xml
flink-table/flink-sql-parser/src/main/codegen/templates/Parser.jj
flink-table/flink-sql-parser/src/main/java/org/apache/calcite/sql/SqlJoin.java
flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/CorrelateITCase.scala

~~The PR applies WA to fix [CALCITE-6266](https://issues.apache.org/jira/browse/CALCITE-6266)~~
~~It applieas similar fix as for [CALCITE-6266](https://issues.apache.org/jira/browse/CALCITE-6266)~~
~~However since there is no way to override generated methods then the whole `Parser.jj` (based on version from~~ ~~https://github.com/apache/calcite/releases/tag/calcite-1.32.0) is replaced.~~
~~It should be removed together with Calcite upgrade which will bring the fix for [CALCITE-6266](https://issues.apache.org/jira/browse/CALCITE-6266)~~
It ports fix from Calcite
https://github.com/apache/calcite/pull/3871
There is a test
_flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/CorrelateITCase.scala_ …

[FLINK-34446][table] Port parser's fix of cross join with lateral from Calcite

---

flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinator.java

[FLINK-35933] Skip distributing maxAllowedWatermark if there are no subtasks

---

docs/data/sql_functions.yml
docs/data/sql_functions_zh.yml
flink-python/docs/reference/pyflink.table/expressions.rst
flink-python/pyflink/table/expression.py
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/StringFunctionsITCase.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/data/binary/BinaryStringDataUtil.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/TranslateFunction.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/data/BinaryStringDataTest.java

Add TRANSLATE function.
Examples:
```SQL
> SELECT TRANSLATE('AaBbCc', 'abc', '123');
A1B2C3
```
[FLINK-26939](https://issues.apache.org/jira/browse/FLINK-26939)
`StringFunctionsITCase#translateTestCases`

[FLINK-26939][table] Add TRANSLATE supported in SQL & Table API

---

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/physical/batch/BatchPhysicalOverAggregateRule.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/physical/stream/StreamPhysicalOverAggregateRule.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/OverAggregateUtil.scala
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/agg/OverAggregateTest.xml
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/agg/OverAggregateTest.xml
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/agg/OverAggregateTest.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/agg/OverAggregateTest.scala

[FLINK-22121](https://issues.apache.org/jira/browse/FLINK-22121) fixed a similar column name confliction both for rank and batch over agg scenarios, but lost the `StreamPhysicalOverAggregate`, this pr aims to fix it.
Consistent output rowtype of `StreamPhysicalOverAggregate` with `BatchPhysicalOverAggregate`
Reuse related utility methods
Both stream and batch sql's `OverAggregateTest` added new test cases …

[FLINK-35976][table-planner] Fix column name conflicts in StreamPhysicalOverAggregate

---

flink-formats/flink-sql-orc/pom.xml
flink-formats/flink-sql-protobuf/pom.xml
flink-python/pom.xml

Shade the classes in protobuf to avoid class conflict.
*(or)*
*(or)*
*(example:)*
- *Added …

[FLINK-35877] Shade protobuf in flink

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecExchange.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecSort.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecExchange.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/RequiredDistributionJsonDeserializer.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/RequiredDistributionJsonSerializer.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecExchange.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/ExecNodeMetadataUtil.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/batch/SortBatchRestoreTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/batch/TableSinkBatchRestoreTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/common/SortTestPrograms.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/common/TableSinkTestPrograms.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/SortRestoreTest.java
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-sink_1/sink-bucketing_hash-with-keys-with-count/plan/sink-bucketing_hash-with-keys-with-count.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-sink_1/sink-bucketing_range_with_keys_without_count/plan/sink-bucketing_range_with_keys_without_count.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-sink_1/sink-bucketing_with-count/plan/sink-bucketing_with-count.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-sink_1/sink-bucketing_with-keys-and-count/plan/sink-bucketing_with-keys-and-count.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-sink_1/sink-overwrite/plan/sink-overwrite.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-sink_1/sink-partial-insert/plan/sink-partial-insert.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-sink_1/sink-partition/plan/sink-partition.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-sink_1/sink-writing-metadata/plan/sink-writing-metadata.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-sort_1/sort-asc/plan/sort-asc.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-sort_1/sort-desc/plan/sort-desc.json

* Adds Compiled Plan annotations to BatchExecSort and BatchExecExchange.
* Tests the new annotations with the existing SortTestPrograms.

[FLINK-35923] Add CompiledPlan annotations to BatchExecSort

---

docs/content/docs/dev/datastream/fault-tolerance/checkpointing.md

Typo here:
https://nightlies.apache.org/flink/flink-docs-release-1.19/docs/dev/datastream/fault-tolerance/checkpointing/#related-config-options

[hotfix][doc] Fix typo in checkpointing docs

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecValues.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/ExecNodeMetadataUtil.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/batch/ValuesBatchRestoreTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/common/ValuesTestPrograms.java
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-values_1/values-test/plan/values-test.json

* In addition to the annotations, implement a BatchRestoreTest for this operator.
* Moves the ValuesTestPrograms to a common package for re-use between streaming and batch.  …

[FLINK-35934] Add CompiledPlan annotations to BatchExecValues

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecWindowRank.java
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/harness/WindowAggregateHarnessTest.scala
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/aggregate/window/WindowAggOperatorBuilder.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/window/RowTimeWindowDeduplicateOperatorBuilder.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/window/WindowRankOperatorBuilder.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/window/tvf/common/WindowAggOperator.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/rank/window/WindowRankOperatorTest.java

This pr tries to ignore the advancement of the window processor caused by watermark in proctime window agg.
- *Ignore the advancement of the window processor caused by watermark in proctime window agg*
- *Add harness test for this bugfix*
A harness test has been added to verify this pr.

[FLINK-35885][table] Ignore advancing window processor by watermark in window agg based on proctime

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecCorrelate.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/ExecNodeMetadataUtil.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/batch/CorrelateBatchRestoreTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/common/CorrelateTestPrograms.java
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-correlate_1/correlate-catalog-func/plan/correlate-catalog-func.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-correlate_1/correlate-cross-join-unnest/plan/correlate-cross-join-unnest.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-correlate_1/correlate-join-filter/plan/correlate-join-filter.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-correlate_1/correlate-left-join/plan/correlate-left-join.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-correlate_1/correlate-system-func/plan/correlate-system-func.json

* Adds Compiled Plan annotations to BatchExecCorrelate.
* Tests the new annotations with the existing SortTestPrograms.

[FLINK-35942] Add CompiledPlan annotations to BatchExecCorrelate

---

docs/data/sql_functions.yml
docs/data/sql_functions_zh.yml
flink-python/docs/reference/pyflink.table/expressions.rst
flink-python/pyflink/table/expression.py
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/StringFunctionsITCase.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/BTrimFunction.java

Add BTRIM function.
Examples:
```SQL
> SELECT BTRIM('  test  ');
test
> SELECT BTRIM('test', 't');
es
```
[FLINK-35910](https://issues.apache.org/jira/browse/FLINK-35910)
`StringFunctionsITCase#bTrimTestCases`

[FLINK-35910][table] Add the built-in function BTRIM

---

flink-core/src/main/java/org/apache/flink/api/java/typeutils/TypeExtractor.java
flink-test-utils-parent/flink-test-utils/src/test/java/org/apache/flink/types/PojoTestUtilsTest.java

Fix NPE reported in [FLINK-35887](https://issues.apache.org/jira/browse/FLINK-35887).
Add null checking for the result of getSuperclass on an interface.
none
- If yes, how is the feature documented? ()

[FLINK-35887][core] Fix the issue where the getSuperclass of an interface returns null without checking

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecLimit.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/ExecNodeMetadataUtil.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/batch/LimitBatchRestoreTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/batch/TableSourceScanBatchRestoreTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/common/LimitTestPrograms.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/common/TableSourceScanTestPrograms.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/TableSourceScanRestoreTest.java
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-limit_1/limit/plan/limit.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-table-source-scan_1/table-source-scan-filter-pushdown/plan/table-source-scan-filter-pushdown.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-table-source-scan_1/table-source-scan-limit-pushdown/plan/table-source-scan-limit-pushdown.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-table-source-scan_1/table-source-scan-partition-pushdown/plan/table-source-scan-partition-pushdown.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-table-source-scan_1/table-source-scan-project-push-down-disabled/plan/table-source-scan-project-push-down-disabled.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-table-source-scan_1/table-source-scan-project-pushdown/plan/table-source-scan-project-pushdown.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-table-source-scan_1/table-source-scan-reading-metadata/plan/table-source-scan-reading-metadata.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-table-source-scan_1/table-source-scan-reuse-source/plan/table-source-scan-reuse-source.json

* Adds Compiled Plan annotations to BatchExecLimit.

[FLINK-35941] Add CompiledPlan annotations to BatchExecLimit

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecHashAggregate.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecUnion.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/ExecNodeMetadataUtil.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/batch/UnionBatchRestoreTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/common/UnionTestPrograms.java
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-union_1/union-all-two-sources/plan/union-all-two-sources.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-union_1/union-all-with-filter/plan/union-all-with-filter.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-union_1/union-two-sources/plan/union-two-sources.json

* Adds Compiled Plan annotations to BatchExecUnion and BatchExecHashAggregate (which is needed for the UnionTestPrograms). …

[FLINK-35944] Add CompiledPlan annotations to BatchExecUnion

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecWindowRank.java
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/harness/WindowAggregateHarnessTest.scala
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/aggregate/window/WindowAggOperatorBuilder.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/window/RowTimeWindowDeduplicateOperatorBuilder.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/window/WindowRankOperatorBuilder.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/window/tvf/common/WindowAggOperator.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/rank/window/WindowRankOperatorTest.java

*BP https://github.com/apache/flink/pull/25119 to 1.20*
- Ignore the advancement of the window processor caused by watermark in proctime window agg
- Add harness test for this bugfix
A harness test has been added to verify this pr. …

[FLINK-35885][table] Prohibit advancing the progress of processing time window through watermark

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/optimize/StreamNonDeterministicUpdatePlanVisitor.java
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/join/LookupJoinTest.scala

This is minor refactor pr to address the comments in #24121 without any logic changes
and also fix the incorrectly not enabled test case.

    [refactor][table-planner] Separate specific node logic from visit block for StreamNonDeterministicUpdatePlanVisitor to improve readability

---

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/FastTop1Function.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/TopNBufferCacheRemovalListener.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/UpdatableTopNFunction.java

Currently the FastTop1Function and UpdatableTopNFunction created a private CacheRemovalListener which can be general. So do a minor refactor that add a new TopNBufferCacheRemovalListener instead.
add a new TopNBufferCacheRemovalListener  to replace the private one in FastTop1Function and UpdatableTopNFunction
existing cases can conver it

[FLINK-26840][table-runtime] minor refactor for topN function: add a general TopNBufferCacheRemovalListener

---

flink-tests/src/test/java/org/apache/flink/test/checkpointing/ChangelogRecoveryITCaseBase.java

FLINK-34030 introduced a new option that allows to explicitly disable materialization instead of using a negative values.
Negative values might cause parsing exceptions, for example when using adaptive scheduler with Changelog Switch IT Case …

[FLINK-36030][state / changelog] Don't use negative values in changelog recovery tests

---

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraph.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGenerator.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGeneratorTest.java

Fix hang issue in JobGraph generation when StreamGraph contains many YieldingOperatorFactory.
Add a cache to store the mapping between StreamNode and its head operator
This change added tests and can be verified by StreamingJobGraphGeneratorTest#testJobGraphGenerationWithManyYieldingOperatorsDoesNotHang. …

[FLINK-35766][streaming] Fix hang issue in JobGraph generation when StreamGraph contains many YieldingOperatorFactory.

---

flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/test/program/SinkTestStep.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecExpand.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecSortAggregate.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/ExecNodeMetadataUtil.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/batch/ExpandBatchRestoreTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/common/ExpandTestPrograms.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/testutils/BatchRestoreTestBase.java
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-expand_1/expand/plan/expand.json

* Adds override for batch expected rows/sinks in SinkTestStep.
* Adds annotations for BatchExecExpand and BatchExecSortAggregate.

[FLINK-36003] Add CompiledPlan annotations to BatchExecExpand and BatchExecSortAggregate

---

flink-runtime/src/main/java/org/apache/flink/runtime/state/AsyncKeyedStateBackend.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/DefaultKeyedStateStoreV2.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionControllerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendTestUtils.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/InternalKeyedStateTestBase.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStValueState.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStDBOperationTestBase.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStGeneralMultiGetOperationTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateExecutorTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStWriteBatchOperationTest.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/StreamOperatorStateHandler.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperator.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperatorV2.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/StreamingRuntimeContextTest.java

Add default namespace in async state. Thus the namespace semantic is aligned between async state and original state apis.
- Add param of default namespace in creation method of async state
- Forst implementation
This change is a trivial rework covered by existing tests.

[FLINK-35858][State] Default namespace in async state

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlReplaceTableAsConverter.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlRTASNodeToOperationConverterTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/batch/sql/RTASITCase.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/RTASITCase.java
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/TableSinkITCase.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/TableSinkITCase.scala

*When using `SqlReplaceTableAsConverter` to convert SqlNode,  `SqlReplaceTableAsConverter` wrongly used the original query `asQuerySqlNode`. Actually it should use the validated SqlNode.*
- *Use validated SqlNode when converting RTAS*
- *Add full tests*
Many tests (including UT and IT) have been added to verify this pr. …

[FLINK-35935][table] Fix RTAS not supporting LIMIT

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlReplaceTableAsConverter.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlRTASNodeToOperationConverterTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/batch/sql/RTASITCase.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/RTASITCase.java
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/TableSinkITCase.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/TableSinkITCase.scala

BP for https://github.com/apache/flink/pull/25185.
*When using `SqlReplaceTableAsConverter` to convert SqlNode,  `SqlReplaceTableAsConverter` wrongly used the original query `asQuerySqlNode`. Actually it should use the validated SqlNode.*
- *Use validated SqlNode when converting RTAS*
- *Add full tests*
Many tests (including UT and IT) have been added to verify this pr. …

[FLINK-35935][table-planner] Fix RTAS not supporting LIMIT

---

docs/data/sql_functions.yml
docs/data/sql_functions_zh.yml
flink-python/docs/reference/pyflink.table/expressions.rst
flink-python/pyflink/table/expression.py
flink-python/pyflink/table/tests/test_expression.py
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/StringFunctionsITCase.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/PrintfFunction.java

Add PRINTF function.
Examples:
```SQL
> SELECT PRINTF('Hello World %d %s', 100, 'days');
Hello World 100 days
```
[FLINK-35920](https://issues.apache.org/jira/browse/FLINK-35920)
`StringFunctionsITCase#printfTestCases`

[FLINK-35920][table] Add the built-in function PRINTF

---

docs/data/sql_functions.yml
docs/data/sql_functions_zh.yml
flink-python/docs/reference/pyflink.table/expressions.rst
flink-python/pyflink/table/expression.py
flink-python/pyflink/table/tests/test_expression.py
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/utils/EncodingUtils.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/utils/EncodingUtilsTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/MathFunctionsITCase.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/UnhexFunction.java

Add the built-in function UNHEX.
Examples:
```SQL
> SELECT DECODE(UNHEX('466C696E6B'), 'UTF-8');
Flink
```
[FLINK-35993](https://issues.apache.org/jira/browse/FLINK-35993)
`MathFunctionsITCase#unhexTestCases`

[FLINK-35993][table] Add the built-in function UNHEX

---

flink-core/src/test/java/org/apache/flink/api/common/typeutils/SerializerTestBase.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/typeutils/ArrayDataSerializer.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/typeutils/MapDataSerializer.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/typeutils/ArrayDataSerializerTest.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/typeutils/MapDataSerializerTest.java

*The method `copy` in Flink’s `ArrayDataSerializer` does not return the expected copied data for the custom `ArrayData`, but instead reuses its internal data. This pr tries to fix it.*
- *copy the result in ArrayDataSerializer#copy while using custom ArrayData*
- *add tests*
Tests are added to verify this change.

[FLINK-36004] Deep copy the BinaryArrayData in ArrayDataSerializer#copy while using custom ArrayData

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecSortLimit.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/ExecNodeMetadataUtil.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/batch/SortLimitBatchRestoreTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/common/SortTestPrograms.java
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-sort-limit_1/sort-limit-asc/plan/sort-limit-asc.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-sort-limit_1/sort-limit-desc/plan/sort-limit-desc.json

* Adds Compiled Plan annotations to BatchExecSortLimit.

[FLINK-36049] Add CompiledPlan annotations to BatchExecSortLimit

---

flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/ParquetDictionary.java
flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/reader/BytesColumnReader.java
flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/reader/FixedLenBytesColumnReader.java

Optimze parquet binary getBytes with getBytesUnsafe to avoid copy cost
Binary##getBytes() need copy all the internal bytes and getBytesUnsafe not need with more quick performence.
```
/**
* Variant of getBytes() that avoids copying backing data structure by returning
* backing byte[] of the Binary. Do not modify backing byte[] unless you know what
* you are doing.
*
* @return backing byte[] of correct size, with an offset of 0, if possible, else returns result of getBytes()
*/
public abstract byte[] getBytesUnsafe();
```
- *The TaskInfo is stored in the blob store on job creation time as …

[FLINK-36084] Optimze parquet binary getBytes with getBytesUnsafe to avoid copy cost

---

flink-core/src/main/java/org/apache/flink/configuration/ConfigUtils.java
flink-core/src/test/java/org/apache/flink/configuration/ConfigUtilsTest.java
flink-table/flink-sql-client/src/test/resources/sql/set.q
flink-table/flink-sql-gateway/src/test/resources/sql/set.q

Avoid setting empty config values in `ConfigUtils#encodeCollectionToConfig`.  I think this could cause unintentional overwrites and I believe setting an empty collection as a config options in general should mean the same as if that config was not set at all.
Right now this behavior causes to have `pipeline.classpaths` and `pipeline.jars` have an empty list value by default.
- Skip setting if the encoded values are empty.
- Adapt unit tests. …

[FLINK-35939] Do not set empty config values via ConfigUtils#encodeCollectionToConfig

---

flink-core/src/main/java/org/apache/flink/core/fs/DuplicatingFileSystem.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStateToolset.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStorageAccess.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStreamFactory.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStateToolsetTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStorageAccessTest.java

As described in https://cwiki.apache.org/confluence/display/FLINK/FLIP-444%3A+Native+file+copy+support, `PathsCopyingFileSystem` supersedes `DuplicatingFileSystem`.
N/A
Covered by existing tests.
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no / **kind of**) (arguably `DuplicatingFileSystem` should have been marked as `PublicEvolving`, but wasn't) …

[FLINK-35772][filesystem] Drop DuplicatingFileSystem in favour of the newer PathsCopyingFileSystem

---

flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorImpl.java

*Fix the wrong log info for the var syncDurationMillis.*
- *Move the set function before the log so that the var syncDurationMillis is set.*

[hotfix][API/DataStream] Log the right syncDurationMillis time

---

docs/data/sql_functions.yml
docs/data/sql_functions_zh.yml
flink-python/docs/reference/pyflink.table/expressions.rst
flink-python/pyflink/table/expression.py
flink-python/pyflink/table/tests/test_expression.py
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/RegexpFunctionsITCase.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/StringFunctionsITCase.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/SqlFunctionUtils.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/RegexpCountFunction.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/RegexpExtractAllFunction.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/RegexpInstrFunction.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/RegexpSubstrFunction.java

Add the built-in functions REGEXP_COUNT & REGEXP_EXTRACT_ALL & REGEXP_INSTR & REGEXP_SUBSTR.
Examples:
```SQL
> SELECT REGEXP_COUNT('Steven Jones and Stephen Smith are the best players', 'Ste(v|ph)en');
2
> SELECT REGEXP_COUNT('Mary had a little lamb', 'Ste(v|ph)en');
0
> SELECT REGEXP_EXTRACT_ALL('100-200, 300-400', '(\\d+)-(\\d+)', 1);
[100, 300]
> SELECT REGEXP_INSTR('Steven Jones and Stephen Smith are the best players', 'Ste(v|ph)en');
1
> SELECT REGEXP_INSTR('Mary had a little lamb', 'Ste(v|ph)en');
0
> SELECT REGEXP_SUBSTR('Steven Jones and Stephen Smith are the best players', 'Ste(v|ph)en');
Steven
> SELECT REGEXP_SUBSTR('Mary had a little lamb', 'Ste(v|ph)en');
NULL
```
- [FLINK-35931](https://issues.apache.org/jira/browse/FLINK-35931)
- …

[FLINK-35931][table] Add the built-in functions REGEXP_COUNT & REGEXP_EXTRACT_ALL & REGEXP_INSTR & REGEXP_SUBSTR

---

flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/dql/SqlShowCall.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/AbstractShowOperation.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ShowColumnsOperation.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ShowDatabasesOperation.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ShowFunctionsOperation.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ShowProceduresOperation.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ShowTablesOperation.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ShowViewsOperation.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/AbstractSqlShowConverter.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlShowDatabasesConverter.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlShowFunctionsConverter.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlShowProcedureConverter.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlShowTablesConverter.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlShowViewsConverter.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlShowToOperationConverterTest.java

The behavior was changed in FLINK-36085 while refactoring
this PR makes the behavior as before and adds some tests for it
Also adds some missing javadocs and getters
SqlShowToOperationConverterTest.java

[FLINK-36126] Qualification of current catalog and current database should happen during execution, not parsing

---

flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/SourceMetricsITCase.java
flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/InternalOperatorIOMetricGroup.java
flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/TaskIOMetricGroup.java
flink-runtime/src/test/java/org/apache/flink/runtime/testutils/InMemoryReporter.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperator.java
flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/SinkMetricsITCase.java
flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/SinkV2MetricsITCase.java

Currently, the numRecordsIn & numBytesIn metrics for sources and the numRecordsOut & numBytesOut metrics for sinks are always 0 on the Flink web dashboard.
[FLINK-11576](https://issues.apache.org/jira/browse/FLINK-11576) brings us these metrics on the opeartor level, but it does not integrate them on the task level. On the other hand, the summay metrics on the job overview page is based on the task level I/O metrics. As a result, even though new connectors supporting FLIP-33 metrics will report operator-level I/O metrics, we still cannot see the metrics on dashboard.
This MR attempts to reuse the operator-level source/sink I/O metrics for task so that they can be viewed on Flink web dashboard. 
Reuse input/output metrics of SourceOperator/SinkWriterOperator for task. 
Since Flink only …

[FLINK-33681] Reuse input/output metrics of SourceOperator/SinkWriterOperator for task

---

flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/vector/ParquetInt64TimestampReaderTest.java

This pull request fixes the `ParquetInt64TimestampReaderTest` unit tests.
- By using `ZonedDateTime` with `ZoneOffset.systemDefault()`, the correct offset is used when converting to epoch.
This change is already covered by existing tests, `ParquetInt64TimestampReaderTest`.

[FLINK-35482] ParquetInt64TimestampReaderTest unit tests fail due to system timezone

---

flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/vector/ParquetInt64TimestampReaderTest.java

This pull request fixes the `ParquetInt64TimestampReaderTest` unit tests.
- By using `ZonedDateTime` with `ZoneOffset.systemDefault()`, the correct offset is used when converting to epoch.
This change is already covered by existing tests, `ParquetInt64TimestampReaderTest`.

[BP-1.20][FLINK-35482] ParquetInt64TimestampReaderTest unit tests fail due to system timezone

---

flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/vector/ParquetInt64TimestampReaderTest.java

This pull request fixes the `ParquetInt64TimestampReaderTest` unit tests.
- By using `ZonedDateTime` with `ZoneOffset.systemDefault()`, the correct offset is used when converting to epoch.
This change is already covered by existing tests, `ParquetInt64TimestampReaderTest`.

[BP-1.19][FLINK-35482] ParquetInt64TimestampReaderTest unit tests fail due to system timezone

---

flink-runtime/src/main/java/org/apache/flink/runtime/util/SignalHandler.java

Scheduled maintenance or buggy nodes on Kubernetes can result random pod termination and eventually a series of job restarts due to rolling restart of the Kubernetes cluster nodes. The larger the job is the higher the chance it is affected. The jobs should be able to auto-recover from these issues, but can cause unwanted turbulence in large scale pipeline.
In this case, it is very difficult to identify what is causing the restarts without knowing the issue at Kubernetes layer and the keyword to search with because it is logged at INFO level.
We need to log this at higher level. If changing it from INFO to ERROR breaks monitoring we should at least log as warning. 
- Change the log level from INFO to WARN
- Manually verified the …

[FLINK-36140] Log a warning when pods are terminated by kubernetes

---

docs/data/sql_functions.yml
docs/data/sql_functions_zh.yml
flink-python/docs/reference/pyflink.table/expressions.rst
flink-python/pyflink/table/expression.py
flink-python/pyflink/table/tests/test_expression.py
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/StringFunctionsITCase.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/EndsWithFunction.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/StartsWithFunction.java

Add the built-in function STARTSWITH & ENDSWITH.
Examples:
```SQL
> SELECT STARTSWITH('SparkSQL', 'Spark');
TRUE
> SELECT STARTSWITH('SparkSQL', 'spark');
FALSE
> SELECT ENDSWITH('SparkSQL', 'SQL');
TRUE
> SELECT ENDSWITH('SparkSQL', 'sql');
FALSE
```
[FLINK-35964](https://issues.apache.org/jira/browse/FLINK-35964)
[FLINK-35965](https://issues.apache.org/jira/browse/FLINK-35965)
`StringFunctionsITCase#startsWithTestCases`
`StringFunctionsITCase#endsWithTestCases` …

[FLINK-35964][table] Add the built-in function STARTSWITH & ENDSWITH

---

flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/ddl/SqlReplaceTableAs.java
flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/MergeTableAsUtil.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlCreateTableConverter.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlNodeConvertContext.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlNodeConverter.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlReplaceTableAsConverter.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlRTASNodeToOperationConverterTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/RTASITCase.java

Allow defining new columns and/or overriding source column types in the CREATE clause on RTAS statements.
Syntax supported:
```
CREATE OR REPLACE TABLE  table_name 
[( <column_definition>[, ...n], [<watermark_definition>], [<table_constraint>])]
[DISTRIBUTED BY [HASH|RANGE|RANDOM](cols) [INTO n BUCKETS]]
AS SELECT query_expression;
```
Column definition supports adding new columns and/or defining columns already existing in the SELECT clause. Also, allows to pass PRIMARY KEY and WATERMARK columns.
- Added support for column definition, watermarks, primary keys and distribution in the RTAS statement
- Added unit tests to validation and converter classes
- Added IT tests that verify data is written and read correctly
- Dependencies …

[FLINK-35709][Table SQL / API] Allow defining a schema in REPLACE TABLE AS (RTAS)

---

flink-core/src/main/java/org/apache/flink/api/common/eventtime/WatermarkGeneratorSupplier.java

this fixes https://github.com/apache/flink/pull/25222 due to https://github.com/apache/flink/pull/25223#discussion_r1728928197

fixup! (1.20 backport) [FLINK-35886][task] Fix watermark idleness timeout accounting when subtask is backpressured/blocked

---

flink-dist/src/main/resources/META-INF/NOTICE
flink-end-to-end-tests/test-scripts/common.sh
flink-state-backends/flink-statebackend-rocksdb/pom.xml
flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBResourceContainerTest.java

[FLINK-35579] update frocksdb version to v8.10.0

---

flink-core/src/main/java/org/apache/flink/api/common/eventtime/WatermarkGeneratorSupplier.java
pom.xml

this fixes https://github.com/apache/flink/pull/25223 due to https://github.com/apache/flink/pull/25223#discussion_r1728928197

fixup! (1.19 backport) [FLINK-35886][task] Fix watermark idleness timeout accounting when subtask is backpressured/blocked

---

.github/workflows/docs.sh
pom.xml

The Javadoc needs to be updated since Javadoc generation fails with a failed cast (com.sun.tools.javadoc.ClassDocImpl cannot be cast to com.sun.javadoc.AnnotationTypeDoc)
* Update Maven Javadoc plugin
Running ```docker run --rm --volume "$PWD:/root/flink" chesnay/flink-ci:java_8_11_17_21_maven_386 bash -c "cd /root/flink && ./.github/workflows/docs.sh"```  locally now correctly generates Javadocs …

[FLINK-36116] Update Javadoc plugin

---

flink-runtime/src/test/java/org/apache/flink/runtime/concurrent/ComponentMainThreadExecutorServiceAdapter.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java

This ensures that the `AdaptiveSchedulerTest` follows the correct production lifecycle. Specifically, the change aims to address the issue where the executor representing the main thread is shutting down before the `AdaptiveScheduler` is appropriately closed. This can lead to problems with scheduled tasks when the executor is shut down prematurely. By fixing the test, the change ensures that the `AdaptiveScheduler` is closed correctly in all tests, preventing potential issues during shutdown and improving the reliability and accuracy of the test.
- `AdaptiveScheduler` is closed properly after every test execution. 
- The `AdaptiveScheduler` instance is started in the `singleThreadMainThread`
- This change affects only testing classes.  …

[FLINK-36168] [runtime] AdaptiveSchedulerTest doesn't follow the production lifecycle

---

flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/StateDescriptorUtils.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/adaptor/AsyncKeyedStateBackendAdaptor.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/adaptor/ValueStateWrapper.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamTaskStateInitializerImpl.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AsyncKeyedStateBackendAdaptorTest.java

This pull request implements the AsyncKeyedStateBackend interface for RocksDBKeyedStateBackend and HeapKeyedStateBackend, enabling both RocksDBStateBackend and HeapStateBackend to create V2 states.
1.Introduce the new `ValueStateWrapper` class, which implements the `v2.ValueState` interface and can be constructed from a `ValueState`.
2.Introduce the new `StateDescriptorTransformer` class, which can convert a `v2.StateDescriptor` to a `StateDescriptor`.
3.Implement `AsyncKeyedStateBackend` interface for `RocksDBKeyedStateBackend`.
4.Implement `AsyncKeyedStateBackend` interface for `HeapKeyedStateBackend`.
This change is a simple interface implementation without any test coverage. …

[FLINK-36117] Add an adaptor to convert KeyedStateBackend into AsyncKeyedStateBackend.

---

flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBIncrementalCheckpointUtils.java
flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBOperationUtils.java
flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBHandle.java
flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBIncrementalRestoreOperation.java

Revert commit 268a3080 "[FLINK-31238] Deactivate parts of the code until new FRocksDB release is available."
This change is …

[FLINK-35581] Remove comments from the code related to ingestDB

---

docs/layouts/shortcodes/generated/checkpointing_configuration.html
flink-core/src/main/java/org/apache/flink/configuration/CheckpointingOptions.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/environment/ExecutionCheckpointingOptions.java

Some of the places we still have `checkpointing-with-parts-of-the-graph-finished-beta` link instead of `checkpointing-with-parts-of-the-graph-finished` which doesn't lead anywhere. In this PR I've fixed it.
Fixed `checkpointing-with-parts-of-the-graph-finished` link in checkpoint documentation.
* `docker run -v $(pwd):/src -p 1313:1313 jakejarvis/hugo-extended:latest server --buildDrafts --buildFuture --bind 0.0.0.0`
* Manually visited locally generated page …

[FLINK-36173][docs] Fix invalid link in checkpoint documentation

---

flink-runtime/src/test/java/org/apache/flink/runtime/state/filesystem/FsMergingCheckpointStorageLocationTest.java

The issue is that execution of `FsMergingCheckpointStorageLocationTest` generates files and folders outside of tmp folders which appear in git change
easy way to reproduce
```bash
cd flink-runtime && ./../mvnw -Dtest=FsMergingCheckpointStorageLocationTest test && git status
```
The change makes generated files/folder appearing into tmp
also, since this test is touched it is migrated to junit5
```bash
cd flink-runtime && ./../mvnw -Dtest=FsMergingCheckpointStorageLocationTest test && git status
```
this shouldn't returned any changed file …

[FLINK-36191][tests] FsMergingCheckpointStorageLocationTest generates test data not in tmp folder

---

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/LogicalFile.java
flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerTestBase.java

There might be a duplicate discard of logical file in cp file-merging when cp abortion + io exception + two threads happen to release the file at the same time.
- Make the `LogicalFile` can only be discarded once.
It is not easy to verify this, since it is a rare concurrent issue.

[FLINK-36125][checkpoint] Fix concurrent duplicate discard of logical file in cp file-merging

---

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/LogicalFile.java
flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerTestBase.java

There might be a duplicate discard of logical file in cp file-merging when cp abortion + io exception + two threads happen to release the file at the same time.
- Make the `LogicalFile` can only be discarded once.
It is not easy to verify this, since it is a rare concurrent issue.

[BP-1.20][FLINK-36125][checkpoint] Fix concurrent duplicated discard of logical file in cp file-merging

---

flink-core-api/src/main/java/org/apache/flink/api/common/state/v2/StateFuture.java
flink-core/src/main/java/org/apache/flink/core/state/CompletedStateFuture.java
flink-core/src/main/java/org/apache/flink/core/state/StateFutureImpl.java
flink-core/src/test/java/org/apache/flink/core/state/StateFutureTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStDBOperationTestBase.java

As described in FLIP-455, this PR provides some interface for conditional branchings under `StateFuture`
- Add interface in `StateFuture`
- Added UT under `StateFutureTest`

[FLINK-36119][state] Conditional interfaces for StateFuture

---

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerFactory.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/allocator/SlotSharingSlotAllocator.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerBuilder.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/allocator/SlotSharingSlotAllocatorTest.java

The local recovery doesn't take effect if flink doesn't backup state on the TM local disk. So StateLocalitySlotAssigner should be only used when local recovery is enabled.
- [FLINK-36201][Coordination] Don't use StateLocalitySlotAssigner when local recovery is disabled
This change is already covered by existing tests, such as : `SlotSharingSlotAllocatorTest#testStickyAllocation` …

[FLINK-36201][Coordination] Don't use StateLocalitySlotAssigner when local recovery is disabled

---

flink-runtime/src/test/java/org/apache/flink/runtime/state/filesystem/FsMergingCheckpointStorageLocationTest.java

This is a cherry-pick backport of https://github.com/apache/flink/pull/25274

[BP-1.19][FLINK-36191][tests] FsMergingCheckpointStorageLocationTest generates test data not in tmp folder

---

flink-runtime/src/test/java/org/apache/flink/runtime/state/filesystem/FsMergingCheckpointStorageLocationTest.java

This is a cherry-pick backport of https://github.com/apache/flink/pull/25274

[BP-1.20][FLINK-36191][tests] FsMergingCheckpointStorageLocationTest generates test data not in tmp folder

---

docs/layouts/shortcodes/generated/rocksdb_configurable_configuration.html
flink-core/src/main/java/org/apache/flink/api/common/state/StateTtlConfig.java
flink-core/src/test/java/org/apache/flink/api/common/state/StateTtlConfigTest.java
flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBConfigurableOptions.java
flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackendBuilder.java
flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBResourceContainer.java
flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/ttl/RocksDbTtlCompactFiltersManager.java

*In Rank operators, add the cleanupInRocksdbCompactFilter(queryTimeAfterNumEntries) parameter setting, allowing adjustment based on the size of user state to enhance performance.*
- *Add a configuration parameter, TABLE_EXEC_RANK_ROCKSDB_CLEANUP_QUERY_TIME_AFTER_NUM_ENTRIES, in StreamExecRank.*
- *Update StateConfigUtil to support creating StateTtlConfig using retentionTime and queryTimeAfterNumEntries.*
- *Support configuration of cleanupFullSnapshot and cleanupInRocksdbCompactFilter.*
*This change is already covered by existing tests, such as AppendOnlyFirstNFunctionTest、TopNFunctionTestBase.* …

[FLINK-36149][state] Make the RocksdbCompactFilter parameters take effect directly at the statebackend level

---

flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/InternalKeyedState.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ContextKey.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBBunchPutRequest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBGetRequest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBIterRequest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBListGetRequest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBMapCheckRequest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBMapEntryIterRequest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBMapKeyIterRequest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBMapValueIterRequest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBPutRequest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBWriteBatchWrapper.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStIterateOperation.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackendBuilder.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStMapIterator.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStMapState.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateExecutor.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateRequestClassifier.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStWriteBatchOperation.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStDBIterateOperationTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStDBOperationTestBase.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStGeneralMultiGetOperationTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateExecutorTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStWriteBatchOperationTest.java

This PR implements Map Async State API for ForStStateBackend.
- Introduce `ForStDBIterRequest` and `ForStIterateOperation` for `Map#iterator`
- Introduce `ForStDBBunchPutRequest` for `Map#putAll` and `Map#clear`
- Utilize `ForStDBPutRequest` for `Map#put`, and `ForStDBGetRequest` for `Map#value`
- `ForStDBIterateOperationTest`
-  Othe map related tests are located in subclasses of `ForStDBOperationTestBase`. …

[FLINK-35049][state] Implement Map Async State API for ForStStateBackend

---

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/DefaultStateTransitionManager.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Executing.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StateTransitionManager.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/WaitingForResources.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerBuilder.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/DefaultStateTransitionManagerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/ExecutingTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/TestingStateTransitionManager.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/WaitingForResourcesTest.java

This PR aims to unify the logic of handling state transitions and timeouts for the `WaitingForResources` and `Executing` states. To achieve that, we integrate the existing component `StateTransitionManager` into the `WaitingForResources` state. 
- The factory `StateTransitionManager.Factory` was removed. 
- The `AdaptiveScheduler` component is now responsible for creating a correctly configured `StateTransitionManager` instance for a specific state.  
- The `WaitingForResources` state integrates the `StateTransitionManager`. 
This change is already covered by the existing tests, such as `WaitingForResourcesTest`, `DefaultStateTransitionManagerTest`,  `AdaptiveSchedulerTest` and `AdaptiveSchedulerSimpleITCase`.
Some existing tests from the class `WaitingForResourcesTest` were removed …

[FLINK-36012] [runtime] Integrate StateTransitionManager into WaitingForResources state

---

flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AsyncStateProcessingOperator.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperator.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperatorV2.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperatorTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AbstractAsyncStateStreamOperatorV2Test.java

An internal interface for executing a runnable with a specific key. This PR enables the async keyed processing operators, where the key is managed by the framework, the equivalent capabilities of following code:
```
setCurrentKey(anotherKey);
valueState.update(newValue);
setCurrentKey(back);
```
This is mainly for the ease of sql implementation.
- A new interface `asyncProcessWithKey` in `AsyncStateProcessingOperator` and two implementation.
- Corresponding tests in `AbstractAsyncStateStreamOperatorTest` and `AbstractAsyncStateStreamOperatorV2Test` …

[FLINK-35972][state/runtime] Async process a runnable with a key provided

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateUdfStreamOperator.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/AbstractAsyncStateStreamOperatorV2Test.java

After [FLINK-36063](https://issues.apache.org/jira/browse/FLINK-36063), all operators are moved to flink-runtime. This PR moves the async state related ones as well.
- Move all operators to `flink-runtime`
- The `AbstractAsyncStateStreamOperatorV2Test` is left in `flink-streaming-java` next to `AbstractStreamOperatorV2Test`, since the depended `AbstractInput` is still under `flink-streaming-java`.
This change is a trivial code cleanup without any test coverage. …

[FLINK-36246] Move async state related operators to flink-runtime

---

docs/data/sql_functions.yml
docs/data/sql_functions_zh.yml
flink-python/docs/reference/pyflink.table/expressions.rst
flink-python/pyflink/table/expression.py
flink-python/pyflink/table/tests/test_expression.py
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/PercentageArgumentTypeStrategy.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/PercentageArrayArgumentTypeStrategy.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/SpecificInputTypeStrategies.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/SpecificTypeStrategies.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/InputTypeStrategiesTest.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/TypeStrategiesTest.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/AggFunctionFactory.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/AggregateUtil.scala
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/BuiltInAggregateFunctionTestBase.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/PercentileAggFunctionITCase.java
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/OverAggregateITCase.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/AggregateITCase.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/OverAggregateITCase.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/WindowAggregateITCase.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/table/AggregateITCase.scala
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/aggregate/PercentileAggFunction.java

Add the built-in function PERCENTILE.
Examples:
```SQL
> SELECT PERCENTILE(col, 0.3) FROM VALUES (0), (10), (10) AS tab(col);
6.0
> SELECT PERCENTILE(col, 0.3, freq) FROM VALUES (0, 1), (10, 2) AS tab(col, freq);
6.0
> SELECT PERCENTILE(col, array(0.25, 0.75)) FROM VALUES (0), (10) AS tab(col);
[2.5,7.5]
```
- Add `ArgumentTypeStrategy` for percentage (array) value with literal value checking
- Refactor error test for built-in agg functions
- Support creating `AggregateInfo` through `BuiltInFunctionDefinition` directly to avoid an extra `SqlAggFunction` conversion
- [FLINK-36123](https://issues.apache.org/jira/browse/FLINK-36123)
For the two `ArgumentTypestrategy`: `InputTypeStrategiesTest`
For the `PercentileTypestrategy`: `TypeStrategiesTest`
For the function PERCENTILE:
- …

[FLINK-36123][table] Add the built-in function PERCENTILE

---

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/EqualiserCodeGenerator.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/CalcTest.xml
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/table/CalcTest.xml
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/RowTypeTest.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/CalcTest.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/table/CalcTest.scala

The first commit tries to remove the redundant cast in row type with PEEK_FIELDS_NO_EXPAND.
The second commit tries to fix the wrong equality comparison result between rowType fields and constants.
- *When trying to find the least restrictive StructuredType between row types with PEEK_FIELDS_NO_EXPAND, it should not return row types with FULLY_QUALIFIED.*
- *The classes with two RowData may be different. When we check the equality of row types, we should check the type of RowData first, just like checking array, map and other types.*
- *Add tests to verify these two commits.*
Tests are added to verify these two commits.
- The …

[FLINK-35827][table-planner] Correcting equality comparisons between rowType fields and constants

---

flink-table/flink-table-planner/src/main/java/org/apache/calcite/rex/RexFieldAccess.java

In case of tables with deeply nested structures this issue with unnecessary String concatenations in the RexFieldAccess constructor started to play significant role
and we faced it already.
Since the fix ([CALCITE-5965](https://issues.apache.org/jira/browse/CALCITE-5965)) is only in Calcite 1.36.0 it can take a long time before it comes with Calcite upgrade (currently there are 1.33 and 1.34 in ready for review only)
There are 2 commits:
1. Copy paste of `RexFieldAccess` from (1.32.0)
2. Port fix from CALCITE-5965
to test it need to create a table with deeply nested columns and execute select. …

[FLINK-36262][table] Avoid unnecessary String concatenations in the RexFieldAccess constructor: port fix for CALCITE-5965

---

flink-python/pyflink/table/expression.py
flink-python/pyflink/table/tests/test_expression.py

Fix REGEXP_EXTRACT Python Table API.
[FLINK-36230](https://issues.apache.org/jira/browse/FLINK-36230)
`test_expression.py#test_expression`

[FLINK-36230][pyflink-table] Fix the incorrect calling of REGEXP_EXTRACT Python Table API

---

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Executing.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/FailureResultUtil.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Restarting.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StateTransitions.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/ExecutingTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/RestartingTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StopWithSavepointTest.java

The `AdaptiveScheduler` omits the `WaitingForResources` state when rescaling to avoid an additional waiting in that state. 
- Pass the `forcedRestart` flag into the `Restarting` state 
- Directs the state transition to the `CreatingExecutingGraph` instead of `WaitingForResources` if flag `forcedRestart` is set
- Added test to verify final state transition if the flag is set or not
- The …

[FLINK-36013] [runtime] Introduce the transition from Restarting to CreatingExecutionGraph state

---

pom.xml

The japicmp plugin doesn't seem to work well with Scala annotations (more specifically @scala.deprecated). But we're planning to remove the Scala code as part of the 2.0 release, anyway. Hence, excluding all *scala files should be good enough.
* Adds @java.lang.Deprecated and *scala to the exclusion list
* [Test run](https://github.com/XComp/flink/actions/runs/10690860484/job/29636625406) with no API changes but the new exclusions
* [Test run](https://github.com/XComp/flink/actions/runs/10690878791/job/29636748572#step:7:737) containing @Public API changes that are identified
* [Test run](https://github.com/XComp/flink/actions/runs/10690871294/job/29636697081) containing deprecated @Public API changes that should be ignored
Check the corresponding branches the workflows ran on to see the …

[FLINK-36207][build] Disables deprecated API from japicmp

---

flink-runtime-web/src/test/resources/rest_api_v1.snapshot
flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/JobExceptionsHandler.java
flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/JobExceptionsInfoWithHistory.java
flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/job/JobExceptionsHandlerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/rest/messages/JobExceptionsInfoWithHistoryNoRootTest.java

Removes deprecated field "location". It was replaced by the "endpoint" field in 1.19.

[FLINK-36147][runtime] Removes deprecated location field

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/AbstractAsyncStateStreamOperatorV2Test.java

Async state needs to be drained before the snapshot barrier being broadcast to downstream. However, there is an issue that we do drain during snapshot. This PR fixes this.
- Move draining logic from `snapshotState` to `prepareSnapshotPreBarrier`.
It's not easy to implement a UT for this. We test this in IT. Future IT for SQL operators will also cover this. …

[FLINK-35027] Drain async state request before snapshot barrier

---

flink-core/src/main/java/org/apache/flink/core/fs/Path.java
pom.xml

*We have already deprecated related read and write method in 1.19, and should be remove it in 2.0-preview.*
- *Remove IOReadableWritable from Path*

[FLINK-5336][core] Remove IOReadableWritable from Path

---

docs/content.zh/docs/dev/datastream/dataset_migration.md
docs/content/docs/dev/datastream/dataset_migration.md
flink-core/src/main/java/org/apache/flink/api/common/functions/RuntimeContext.java
flink-core/src/main/java/org/apache/flink/api/connector/sink2/InitContext.java
flink-core/src/main/java/org/apache/flink/api/connector/sink2/Sink.java
flink-core/src/main/java/org/apache/flink/core/failure/FailureEnricher.java
flink-end-to-end-tests/run-nightly-tests.sh
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/LongHashJoinGenerator.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/fusion/spec/HashJoinFusionCodegenSpec.scala
flink-tests/src/test/java/org/apache/flink/test/scheduling/JMFailoverITCase.java
pom.xml

*Remove deprecated method marked in FLIP-382*
- *Remove deprecated method marked in FLIP-382*

[FLINK-36225][core] Remove deprecated method marked in FLIP-382

---

flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/AbstractMaterializedTableStatementITCase.java
flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/rest/SqlGatewayRestEndpointMaterializedTableITCase.java
flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/MaterializedTableStatementITCase.java
flink-test-utils-parent/flink-table-filesystem-test-utils/src/main/java/org/apache/flink/table/file/testutils/catalog/TestFileSystemCatalog.java
flink-test-utils-parent/flink-table-filesystem-test-utils/src/test/java/org/apache/flink/table/file/testutils/catalog/TestFileSystemCatalogTest.java
flink-test-utils-parent/flink-table-filesystem-test-utils/src/test/java/org/apache/flink/table/file/testutils/catalog/TestFileSystemCatalogTestBase.java

Problem:
As shown in the error message above, in the test method afterEach, we will list all materialized tables and then drop them to prevent any remaining refresh tasks.
However, since the Drop Materialized Table has already been deleted, it causes the error mentioned above.
* Why does listing tables show they exist when dropping tables results in an error stating they do not exist?
1. In the test dropMaterializedTableWithDeletedRefreshWorkflowInFullMode, we manually dropped the Materialized Table.
2. Despite manual deletion, background refresh tasks are still being submitted. This leads to data continuing to be written into the corresponding table data directory.
3. TestFileSystemCatalog lists all directories for existing tables during listTable. If a directory exists, it returns true. …

[FLINK-36242][table] Fix unstable test in MaterializedTableITCase

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateRequestType.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/InternalMergingState.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/InternalReducingState.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/InternalAggregatingStateTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/InternalKeyedStateTestBase.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/InternalListStateTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/InternalMapStateTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/InternalReducingStateTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/InternalValueStateTest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStReducingState.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateRequestClassifier.java

This PR implements Reducing Async State API for ForStStateBackend.
- Introduce `InternalMergingState` and  `ForStReducingState`
- Implement `asyncMergeNamespaces` and `mergeNamespaces`
- `InternalReducingStateTest#testMergeNamespace` …

[FLINK-35667][state/forst] Implement Reducing Async State API for ForStStateBackend

---

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
flink-tests/src/test/java/org/apache/flink/test/scheduling/RescaleOnCheckpointITCase.java
flink-tests/src/test/resources/log4j2-test.properties

FLINK-36014 aligned the triggering of the execution graph creation in `WaitingForResources` and rescaling in `Executing` state. Before that change, only `WaitingForResources` relied on this method. Relying on free slots was good enough because in `WaitingForResources` state, there are no slots allocated, yet.
Using this method for `Executing` state now as well changes this premise because there are slots allocated while checking the slot availability that would become available after the restart. Hence, considering these slots in the slot availability check is good enough. This will not break the premise for the `WaitingForResources` state.
* Make the `AdaptiveScheduler#hasDesiredResources` check rely on all available slots rather than only the free slots to support this metric even in …

[FLINK-36279][runtime] Making desired resources being calculated based on all available slots for the job

---

flink-runtime/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java

…ractResourceSpec(slotSharingGroup)
*(or)*
This …

[FLINK-36281][runtime] resourceSpec replace SlotSharingGroupUtils.extractResourceSpec(slotSharingGroup)

---

flink-core/src/main/java/org/apache/flink/util/AbstractID.java

to improve performance of AbstractID by using ThreadLocalRandom
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ThreadLocalRandom.html
- use ThreadLocalRandom in AbstractID …

[FLINK-36208][core] use ThreadLocalRandom in AbstractID

---

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/AggFunctionFactory.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/AggregateITCase.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/utils/UserDefinedFunctionTestUtils.scala

Fix an issue where a UDAF incorrectly accessed the implementation of a built-in function with the same name.
[FLINK-36283](https://issues.apache.org/jira/browse/FLINK-36283)
UDAFs may have function names that are the same as built-in agg functions. Considering the resolving priority, we can't rely solely on names to match functions; instead, we should use something unique, like their definitions.
`sql/AggregateITCase#testAggFunctionPriority()` …

[FLINK-36283][table-planner] Fix an issue where a UDAF incorrectly accessed the implementation of a built-in function with the same name

---

docs/content/docs/deployment/java_compatibility.md

Updates docs to match current state. In practice we already see usage with Java 17.

[docs] Update Java 17 compatibility docs

---

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/DefaultStateTransitionManager.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Executing.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/DefaultStateTransitionManagerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/ExecutingTest.java

StateTransitionManager's initialization time is based on the same time coming from the AdaptiveScheduler
- `AdaptiveScheduler` holds a time supplier and propagates it to states,
- `DefaultStateTransitionManager` sets the initialization time in a constructor from the provided time supplier
- The serializer:  no …

[FLINK-36016] [runtime] Synchronize initialization time and clock usage in DefaultStateTransitionManager

---

docs/layouts/shortcodes/generated/all_jobmanager_section.html
docs/layouts/shortcodes/generated/expert_scheduling_section.html
docs/layouts/shortcodes/generated/job_manager_configuration.html
flink-core/src/main/java/org/apache/flink/configuration/JobManagerOptions.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/WaitingForResources.java
flink-runtime/src/test/java/org/apache/flink/runtime/minicluster/MiniClusterITCase.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerClusterITCase.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerSimpleITCase.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
flink-tests/src/test/java/org/apache/flink/test/checkpointing/AutoRescalingITCase.java
flink-tests/src/test/java/org/apache/flink/test/recovery/AbstractTaskManagerProcessFailureRecoveryTest.java
flink-tests/src/test/java/org/apache/flink/test/recovery/TaskManagerDisconnectOnShutdownITCase.java
flink-tests/src/test/java/org/apache/flink/test/scheduling/RescaleOnCheckpointITCase.java
flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnTestBase.java

This PR aligns the configuration naming for parameters used in the Adaptive Scheduler in different states.  
- Parameter `jobmanager.adaptive-scheduler.resource-wait-timeout` was renamed to the `jobmanager.adaptive-scheduler.submission.resource-wait-timeout`
- Parameter `jobmanager.adaptive-scheduler.resource-stabilization-timeout`   was renamed to the `jobmanager.adaptive-scheduler.submission.resource-stabilization-timeout`
- Parameter `jobmanager.adaptive-scheduler.scaling-interval.min`  was renamed to the `jobmanager.adaptive-scheduler.executing.cooldown-after-rescaling`
- Parameter `jobmanager.adaptive-scheduler.scaling-interval.max` was renamed to the `jobmanager.adaptive-scheduler.executing.resource-stabilization-timeout` with a default value of 60s. 
- Parameter …

[FLINK-36015] [runtime] Align rescale parameters

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/BatchCallbackRunner.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateFutureFactory.java

Currently, when there is a state request finished, a callback will be wrapped into a mail and inserted into the `Mailbox`. This PR put a batch of consecutive callbacks into one mail and execute them in batch, which reduce the interaction with the queue of mailbox. Additionally, the new introduced runner propagate the flag `hasMail`, which is essential for fine-grained scheduling of `AsyncExecutionController` (will exposed in later PR).
- Introduce `BatchCallbackRunner` that receives single callbacks and run them in batch.
This change is already covered by existing tests on `AEC`. …

[FLINK-35412][State/Runtime] Batch execution of async state request callback

---

flink-core/src/main/java/org/apache/flink/util/PortRange.java
flink-core/src/test/java/org/apache/flink/util/PortRangeTest.java
flink-metrics/flink-metrics-prometheus/src/main/java/org/apache/flink/metrics/prometheus/PrometheusReporter.java
flink-metrics/flink-metrics-prometheus/src/main/java/org/apache/flink/metrics/prometheus/PrometheusReporterFactory.java
flink-metrics/flink-metrics-prometheus/src/test/java/org/apache/flink/metrics/prometheus/PrometheusReporterTaskScopeTest.java
flink-metrics/flink-metrics-prometheus/src/test/java/org/apache/flink/metrics/prometheus/PrometheusReporterTest.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/NettyConfig.java
flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/NettyShuffleEnvironmentConfiguration.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyServerFromPortRangeTest.java

* Fixes incorrect Ports display in the PrometheusReporter constructor in case of the httpServer creation failure. Instead of printing the port numbers, the error message currently displays an Iterator object reference, which is not useful for debugging.
* Moved the `PortsRange` from the runtime module to the core module
* Use `PortsRange` utility class from the core module instead of the `iterator`. This ensures that the actual ports are printed in the exception message instead of the Iterator reference.
* Update the tests to rely one on the `PortsRange` as the `PrometheusReposter` only constructor parameter instead of the Iterator
- Extends the existing cannotStartTwoReportersOnSamePort test by checking the exception message thrown to verify that the log message contains the actual ports …

 [FLINK-36240][runtime/metrics] Fix incorrect Ports display in the PrometheusReporter constructor in case of the httpServer creation failure

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/FlinkCalciteSqlValidator.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/stream/sql/ColumnExpansionTest.java

* Adds column expansion for Session Windows in FlinkCalciteSqlValidator.
*(example:)*
- Added tests in ColumnExpansionTest.
- Existing tests verify compiled plans for SESSION Windows.

[FLINK-36330] Session Window TVFs with named parameters don't support column expansion

---

docs/content.zh/docs/dev/python/table/table_environment.md
docs/content/docs/dev/python/table/table_environment.md
flink-python/docs/reference/pyflink.table/table_environment.rst
flink-python/pyflink/table/table_environment.py

Remove apis about `register_table_source` and `register_table_sink` in python module
- *Remove `register_table_source` and `register_table_sink` in python module*
- *Update document in python*

[FLINK-36175][python] Remove `register_table_source` and `register_table_sink` in python module

---

flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl
flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/utils/ParserResource.java
flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/CreateTableASOperation.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/connectors/DynamicSinkUtils.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlNodeToOperationConversion.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/delegation/PlannerBase.scala
flink-table/flink-table-planner/src/test/resources/explain/testExplainCtas.out
flink-table/flink-table-planner/src/test/resources/explain/testExplainCtasWithColumnsInCreateAndQueryParts.out
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/TableSinkTest.scala

Add `EXPLAIN` support for CTAS and RTAS statements.
i.e.
```
EXPLAIN CREATE TABLE t2 
WITH ('format'='csv', 'connector'='filesystem', 'path'='/tmp/t2.dat') 
AS SELECT * FROM t1;
```
Result:
```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  result …
```

[FLINK-28770][table-planner] CREATE TABLE AS SELECT supports explain

---

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/DefaultStateTransitionManager.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/State.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerClusterITCase.java

Flaky test fix and additional logging in Adaptive Scheduler.
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no
- The S3 file system connector:no

[FLINK-36295] [runtime] Test `testCheckpointStatsPersistedAcrossRescale` waits until the desired parallelism is reached

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/AbstractKeyedStateBackend.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/AsyncKeyedStateBackend.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/KeyedStateBackend.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/StateBackend.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/DefaultKeyedStateStoreV2.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/adaptor/AsyncKeyedStateBackendAdaptor.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamOperatorStateHandler.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionKeyedStateBackend.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AbstractStateIteratorTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionControllerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendTestUtils.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractKeyedStateTestBase.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractReducingStateTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/InternalTimerServiceAsyncImplTest.java
flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java
flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/restore/ChangelogMigrationRestoreTarget.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/sync/ForStSyncKeyedStateBackend.java
flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackend.java

After [FLINK-36117](https://issues.apache.org/jira/browse/FLINK-36117), we port old state backends implementation to new api using AsyncKeyedStateBackendAdaptor, but it cannot work because the KeyContext is not properly handled. This PR fixes this.
- Add a listener for state context switch, make all `AsyncKeyedStateBackend` implement it.
- For `AsyncKeyedStateBackendAdaptor`, set current key when a context switched.
This change is without any test coverage, since it is difficult to be covered by a UT. …

[FLINK-36338] Properly handle KeyContext when using AsyncKeyedStateBackendAdaptor

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/BatchCallbackRunner.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateExecutor.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateFutureFactory.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateRequestBuffer.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AbstractStateIteratorTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionControllerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/MockStateExecutor.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractKeyedStateTestBase.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractReducingStateTest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStConfigurableOptions.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBOperation.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStGeneralMultiGetOperation.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStIterateOperation.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStOptions.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateExecutor.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateRequestClassifier.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStWriteBatchOperation.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateExecutorTest.java

This PR optimize the trigger logic of `AEC`. Including draining and timeout trigger.

[FLINK-35411] Optimize buffer triggering of async state requests

---

flink-runtime/src/test/java/org/apache/flink/runtime/concurrent/ComponentMainThreadExecutorServiceAdapter.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java

Using different main threads can cause concurrency issues. That might be the case as well for what we've observed in FLINK-36299 where the sufficient resources didn't become available fast enough causing the main thread to fail and the test to wait forever for the job submission to succeed.
* Sets the main thread executor for the `DefaultDeclarativeSlotPool` to the one that's used in the test method …

[FLINK-36299][runtime] Fixes bug in AdaptiveSchedulerTest that might cause concurrency issues

---

flink-tests/src/test/java/org/apache/flink/api/functions/ClosureCleanerITCase.java

Fix the `org.apache.flink.api.functions.ClosureCleanerITCase` failed in the AdaptiveScheduler test profile. 
In pull request #25324, the `ClosureCleanerITCase` was updated to use Java language and the DataStream API. This test case employs the `fullWindowPartition` operator while running in streaming job mode. 
The `fullWindowPartition` operator will sets jobEdge blocking, which leads the AdaptiveScheduler fail to check whether the job edge can be pipelined (`org.apache.flink.runtime.scheduler.adaptive.AdaptiveScheduler#assertPreconditions`).
- modify the test case in `org.apache.flink.api.functions.ClosureCleanerITCase` to run in batch mode …

[FLINK-36349][tests] Fix ClosureCleanerITCase fail in the AdaptiveScheduler test profile

---

docs/layouts/shortcodes/generated/execution_config_configuration.html
flink-runtime/src/test/java/org/apache/flink/streaming/util/AbstractStreamOperatorTestHarness.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/config/ExecutionConfigOptions.java
flink-table/flink-table-planner/pom.xml
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecJoin.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/optimize/StreamNonDeterministicUpdatePlanVisitor.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/JoinUtil.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/JoinITCase.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/table/JoinITCase.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/utils/StreamingWithStateTestBase.scala
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/MiniBatchStreamingJoinOperator.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/StreamingSemiAntiJoinOperator.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/asyncprocessing/AbstractAsyncStateStreamingJoinOperator.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/asyncprocessing/AsyncStateStreamingJoinOperator.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/asyncprocessing/state/JoinRecordAsyncStateView.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/asyncprocessing/state/JoinRecordAsyncStateViews.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/asyncprocessing/state/OuterJoinRecordAsyncStateView.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/asyncprocessing/state/OuterJoinRecordAsyncStateViews.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/bundle/BufferBundle.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/state/JoinRecordStateView.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/state/JoinRecordStateViews.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/state/OuterJoinRecordStateViews.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/utils/AssociatedRecords.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/utils/JoinHelper.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/utils/JoinInputSideSpec.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/utils/OuterRecord.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/join/stream/BufferBundleTest.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/join/stream/StreamingJoinOperatorTest.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/join/stream/StreamingJoinOperatorTestBase.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/join/stream/StreamingMiniBatchJoinOperatorTest.java

*Introduce new join operator with async state api.*
- *Introduce new join operator with async state api*
- *ITCases and harness tests are added to verity this pr*
ITCases and harness tests are added to verity this pr.
- Does this pull request introduce a new feature? Yes
- If yes, how is the feature documented? A independent doc pr about this feature will be added later.

[FLINK-36248][table] Introduce new Join Operator with Async State API

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/utils/DateTimeUtils.java
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/TemporalTypesTest.scala

Fix incorrect timestamp to string behavior.

[FLINK-36358][table] Fix incorrect timestamp to string behavior.

---

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ContextKey.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBMapCheckRequest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStListState.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStMapState.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStReducingState.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStSerializerUtils.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStValueState.java

Currently, the forst reuse serialized key in any state with any namespaces, which is problematic in parallel state execution. This PR fixes this by limiting the key reuse within the most common case, where there is no user key (not map state) and no customized namespace specified (only void namespace).
- Extract the common part of key reuse in Value/List/Reducing State.
- Determine key reuse in constructor in those states.
- Disable key reuse in MapState. …

[FLINK-36364][state/forst] Do not reuse serialized key in Forst map state and/or other namespaces

---

flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/StreamGraphGenerator.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/partitioner/ForwardForConsecutiveHashPartitioner.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/partitioner/StreamPartitioner.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/translators/SinkTransformationTranslator.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/graph/SinkTransformationTranslatorITCaseBase.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SinkV1TransformationTranslatorITCase.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperatorTestBase.java
flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/SinkITCase.java

Between sink writer, the committer, and any pre/post commit topology (including global committer), we don't send actual payload but just committables. These committables must be committed on notifyCheckpointCompleted. However, if a barrier overtakes these committables, they may only be read after the RPC call has been made leading to violations. In particular, we could even have these issues during a final checkpoint.
This commit generalizes the way, we disable UC for broadcast and pointwise connections, such that the SinkTransformationTranslator can also disable it for other distribution pattern.
* Migrate SinkITCase to AssertJ
* Disallow UC for inner sink channels <- main commit
Added assertion on existing SinkITCase, which looks at different topologies already. …

[FLINK-36287] Disallow UC for inner sink channels 

---

flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherManagerTest.java

Removed timeouts setting in `testCloseCleansUpPreviouslyClosedFetcher` tests. If a test runs into a deadlock, Flink's CI would produce a thread dump in the end that might help with the root cause analysis.
Removed timeouts setting in `testCloseCleansUpPreviouslyClosedFetcher` tests.
This change is already covered by existing tests, such as testCloseCleansUpPreviouslyClosedFetcher. …

[FLINK-36292][Connectors/Common]: remove timeout to avoid timeout exception

---

flink-core/src/main/java/org/apache/flink/types/DoubleValue.java
flink-core/src/main/java/org/apache/flink/types/FloatValue.java
flink-core/src/main/java/org/apache/flink/types/NormalizableKey.java
pom.xml

*Remove deprecated Key interface*

[FLINK-3992][core] Do not implement deprecated Key interface

---

flink-runtime/src/main/java/org/apache/flink/streaming/api/datastream/CoGroupedStreams.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/datastream/JoinedStreams.java

Remove deprecated xxxStreams#with

[FLINK-36355][runtime] Remove deprecated xxxStreams#with

---

flink-runtime/src/main/java/org/apache/flink/runtime/security/token/DelegationTokenReceiverRepository.java
flink-runtime/src/test/java/org/apache/flink/runtime/security/token/DelegationTokenReceiverRepositoryTest.java

[FLINK-36389](https://issues.apache.org/jira/browse/FLINK-36389)
This PR fixes an issue where the `DelegationTokenReceiverRepository` does not check the `DELEGATION_TOKENS_ENABLED` flag before initializing delegation token receivers, leading to the following error in nearline Flink jobs:
> `java.lang.IllegalStateException: Delegation token receiver with service name {} has multiple implementations [hadoopfs]
`
When the `DELEGATION_TOKENS_ENABLED` config is disabled, receiver is not expected to load external services.
Added unit test to verify if the `DELEGATION_TOKENS_ENABLED` config is set to false, none of the services got loaded by the receiver.
- …

[FLINK-36389][security] Add check in DelegationTokenReceiverRepository for DT enabled flag

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateBackend.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateExecutor.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystem.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStInitITCase.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStMultiClassLoaderTest.java

There are many threads in forst statebackends. This PR makes them quit gracefully when task stop.
- Change the order of thread quit to avoid error
- Use async thread to load library and allow interrupt in task thread.

[FLINK-36395][state/forst] Graceful quit for Forst StateBackend

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/BatchCallbackRunner.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/BatchCallbackRunnerTest.java

Fix concurrency issue by introducing a synchronized lock.
- Add synchronized in `BatchCallbackRunner`.
- Add tests.
This change is covered by new introduced tests, `BatchCallbackRunnerTest`. But the concurrency issue can only be verified by manual triggered jobs.

[hotfix][runtime] Fix concurrency issue in callback runner of async state processing

---

docs/content.zh/docs/ops/metrics.md
docs/content/docs/ops/metrics.md
flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/DefaultCheckpointStatsTracker.java
flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/DefaultCheckpointStatsTrackerTest.java

Introduce the lastCheckpointCompletedTimestamp metric
Register `LatestCompletedCheckpointTimestampGauge` named "lastCheckpointCompletedTimestamp" to `CheckpointStatsTracker`
This change is already covered by existing tests, such as CheckpointStatsTrackerTest.

[FLINK-36344][runtime/metrics] Introduce lastCheckpointCompletedTimestamp metric

---

docs/content.zh/docs/ops/metrics.md
docs/content/docs/ops/metrics.md
flink-end-to-end-tests/flink-metrics-availability-test/src/test/java/org/apache/flink/metrics/tests/MetricsAvailabilityITCase.java
flink-end-to-end-tests/flink-metrics-reporter-prometheus-test/src/test/java/org/apache/flink/metrics/prometheus/tests/PrometheusReporterEndToEndITCase.java
flink-end-to-end-tests/test-scripts/common.sh
flink-metrics/flink-metrics-datadog/src/main/java/org/apache/flink/metrics/datadog/DatadogHttpReporter.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/NettyShuffleEnvironment.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/metrics/NettyShuffleMetricFactory.java
flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricNames.java
flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/FrontMetricGroup.java
flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/legacy/metrics/MetricStore.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java
flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/tasks/AbstractTwoInputStreamTask.java
flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/AbstractMetricGroupTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/job/metrics/AbstractMetricsHandlerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/legacy/metrics/MetricStoreTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskManagerRunnerStartupTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/TwoInputStreamTaskTest.java
flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNHighAvailabilityITCase.java

[FLINK-36355][runtime] Remove deprecated metrics

---

flink-runtime/src/main/java/org/apache/flink/runtime/metrics/TimerGauge.java
flink-runtime/src/test/java/org/apache/flink/runtime/metrics/TimerGaugeTest.java

This pull request fixes a problem where the `TimerGauge` produces incorrect results when updated during a measurement. For details, see [FLINK-35764](https://issues.apache.org/jira/browse/FLINK-35764).
- In `TimerGauge`, only add the time since `currentUpdateTS` to `currentCount` in `markEnd()`.
- Add the test case above to `TimerGaugeTest`, and adjust other test cases.
- Added unit test case where `TimerGauge` is updated during a measurement …

  [FLINK-35764][runtime/metrics] Fix TimerGauge producing incorrect results when updating during a measurement

---

docs/content.zh/docs/deployment/resource-providers/standalone/overview.md
flink-container/src/main/java/org/apache/flink/container/entrypoint/StandaloneApplicationClusterConfiguration.java
flink-container/src/main/java/org/apache/flink/container/entrypoint/StandaloneApplicationClusterConfigurationParserFactory.java
flink-container/src/test/java/org/apache/flink/container/entrypoint/StandaloneApplicationClusterConfigurationParserFactoryTest.java
flink-dist/src/main/flink-bin/bin/jobmanager.sh
flink-end-to-end-tests/flink-end-to-end-tests-common/src/test/java/org/apache/flink/dist/DynamicParameterITCase.java
flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/ClusterEntrypoint.java
flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/EntrypointClusterConfiguration.java
flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/EntrypointClusterConfigurationParserFactory.java
flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/parser/CommandLineOptions.java
flink-runtime/src/test/java/org/apache/flink/runtime/entrypoint/EntrypointClusterConfigurationParserFactoryTest.java

[FLINK-36355][runtime] Remove deprecated CLI options

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/RegisteredKeyValueStateBackendMetaInfo.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperatorV2.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamOperatorStateHandler.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/StateBackendTestV2Base.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/StreamOperatorStateHandlerTest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackendBuilder.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStOperationUtils.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateBackend.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateDataTransfer.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/StateHandleTransferSpec.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/restore/ForStHandle.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/restore/ForStIncrementalRestoreOperation.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/restore/ForStNoneRestoreOperation.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/restore/ForStRestoreResult.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/snapshot/ForStIncrementalSnapshotStrategy.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/snapshot/ForStSnapshotStrategyBase.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/sync/ForStSyncKeyedStateBackend.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/sync/ForStSyncKeyedStateBackendBuilder.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateBackendTestV2.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateDataTransferTest.java

Impletement basic restore from checkpoint in `ForStStateBackend`, the checkpoint implement in [FLINK-35510](https://issues.apache.org/jira/browse/FLINK-35510).
Note that `ForStStateBackend` now support sync and async two kind keyed state backend, we make async one support checkpoint and restore first.
- Introduce `ForStIncrementalRestoreOperation`
- Implement restore from checkpoint in `ForStKeyedStateBackendBuilder`
- Add new test case in `ForStStateDataTransferTest`
- Add `StateBackendTestV2Base` & `ForStStateBackendTestV2` to verify the snapshot & restore of `ForStKeyedStatebackend`
- The …

[FLINK-36325][statebackend] Implement basic restore from checkpoint for ForStStateBackend

---

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/UnknownInputChannel.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/UnknownInputChannelTest.java

[FLINK-36260][metrics] Fix numBytesInLocal and numBuffersInLocal being reported as remote
I've tried to find a way how to implement a test, but couldn't find an easy way.
- If yes, how is the feature documented? **(not …

[FLINK-36260][metrics] Fix numBytesInLocal and numBuffersInLocal being reported as remote

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/FlinkRexBuilder.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/NestedProjectionUtil.scala
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/rules/logical/PushProjectIntoTableSourceScanRuleTest.java
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/PushProjectIntoTableSourceScanRuleTest.xml

Do not generate not required casts while `ProjectWatermarkAssignerTransposeRule`
Introduce `NestedSchemaRewriter#copyFieldAccess` which should copy existing field accesses
There is a test in `PushProjectIntoTableSourceScanRuleTest`

[FLINK-36415][table] ProjectWatermarkAssignerTransposeRule can generate extra casts which do not make sense

---

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/temporal/BaseTwoInputStreamOperatorWithStateRetention.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/sort/BaseTemporalSortOperator.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/window/groupwindow/operator/WindowOperator.java

This is a follow up for https://cwiki.apache.org/confluence/display/FLINK/FLIP-443%3A+Interruptible+timers+firing . Temporal join, temporal sort and both windowed and table windowed aggregations in Table API/SQL can have large amount of registered/fired time, while at the same time enabling splittable timers shouldn't cause any side effects for those operators.
N/A
N/A …

[FLINK-36416][table][runtime] Enable splittable timers for temporal join, temporal sort and windowed aggregation in SQL/Table API

---

docs/content.zh/docs/dev/table/sql/create.md
docs/content/docs/dev/table/sql/create.md
flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl
flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/ddl/SqlCreateTable.java
flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/ddl/SqlCreateTableAs.java
flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/ddl/SqlReplaceTableAs.java
flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/utils/ParserResource.java
flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/MergeTableAsUtil.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlCreateTableConverter.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlReplaceTableAsConverter.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/calcite/PreValidateReWriter.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/calcite/SqlRewriterUtils.scala
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlDdlToOperationConverterTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlRTASNodeToOperationConverterTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/RTASITCase.java
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/TableSinkITCase.scala

This PR allows you to use CTAS to reorder the columns defined in the `SELECT` part by specifying all column names without data types in the `CREATE` part. This feature is equivalent to the `INSERT INTO` statement.
Example:
```sql
CREATE TABLE my_ctas_table (
order_time, price, quantity, id
) WITH (
'connector' = 'kafka',
...
) AS SELECT id, price, quantity, order_time FROM source_table;
```
The resulting table `my_ctas_table` will be equivalent to create the following table and insert the data with the following statement:
```
CREATE TABLE my_ctas_table (
order_time TIMESTAMP(3),
price DOUBLE,
quantity DOUBLE,
id BIGINT
) WITH (
'connector' = 'kafka',
...
);
INSERT INTO my_ctas_table (order_time, price, quantity, id)
SELECT id, price, quantity, order_time FROM source_table;
```
This …

[FLINK-35709][table-planner] Allow reordering source columns in CTAS and RTAS

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/FlinkRelBuilder.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/hint/FlinkHints.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/EventTimeTemporalJoinRewriteRule.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/physical/stream/WatermarkAssignerChangelogNormalizeTransposeRule.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/calcite/LogicalWatermarkAssigner.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/calcite/WatermarkAssigner.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/logical/FlinkLogicalWatermarkAssigner.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalWatermarkAssigner.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/physical/stream/StreamPhysicalWatermarkAssignerRule.scala
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/hints/stream/StateTtlHintTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/rules/logical/ProjectWatermarkAssignerTransposeRuleTest.java
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/hints/stream/StateTtlHintTest.xml
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/ProjectWatermarkAssignerTransposeRuleTest.xml
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/TableTestBase.scala

The change is intended to make it possible to run queries like
```sql
SELECT /*+ STATE_TTL('st'='1d', 'vt' = '3d') */ st.* FROM SimpleTable st 
LEFT JOIN(SELECT DISTINCT b FROM VirtualTable) vt 
ON st.b = vt.b WHERE vt.b IS NOT NULL
```
Introduce support for hints for WatermarkAssigner
ProjectWatermarkAssignerTransposeRuleTest.java
- …

[FLINK-36417][table] Add support for hints in WatermarkAssigner

---

.github/workflows/docs.sh

Use Java 11 for documentation build to fix failing workflow: https://github.com/apache/flink/actions/runs/11168786218/job/31047996276
- Override environment in `.github/workflows/docs.sh` to use JDK 11
Running docker command from workflow locally:
```
~ docker run --rm --volume "$PWD:/root/flink" chesnay/flink-ci:java_8_11_17_21_maven_386 bash -c "cd /root/flink && JAVA_HOME=$JAVA_HOME_11_X64 ./.github/workflows/docs.sh"
```
Output before change
```
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /usr/share/maven
Java version: 1.8.0_292, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.8.0-1014-azure", arch: "amd64", family: "unix"
openjdk version "1.8.0_292" …
```

[FLINK-36181][ci] Use Java 11 to run documentation build

---

flink-runtime/src/main/java/org/apache/flink/streaming/api/functions/source/ContinuousFileReaderOperatorFactory.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGenerator.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperatorFactory.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamOperatorFactoryUtil.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/legacy/YieldingOperatorFactory.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperatorFactory.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperatorFactory.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGeneratorTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/StreamTaskOperatorTimerTest.java

Mark deprecated YieldingOperatorFactory as internal legacy

[FLINK-36355][runtime] Mark deprecated YieldingOperatorFactory as internal legacy

---

tools/releasing/create_preview_branch.sh

[FLINK-36360] Introduce scripts for cutting branch for a preview release

---

flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/PartitionReduceOperator.java

Non-keyed fullWindowPartition#reduce may throw NPE, this pr is try to check StreamRecord status to avoid NPE in PartitionReduceOperator.
Non-keyed fullWindowPartition#reduce may throw a NullPointerException, so this pull request tries to check the StreamRecord status in order to avoid a NullPointerException in the PartitionReduceOperator.
Non-keyed fullWindowPartition#reduce may throw a NullPointerException, this pull request tries to check the StreamRecord status to avoid NPE in the PartitionReduceOperator.
- check StreamRecord status in `PartitionReduceOperator#endInput`
- The …

[FLINK-36433][hotfix] Check StreamRecord status to avoid NPE in PartitionReduceOperator

---

pom.xml

The issue is that sometimes `./mvnw clean install -DskipTests -Dscala-2.12 -Pfast -Pskip-webui-build -U -T4`
is hanging while maven-shade-plugin or maven-remote-resource-plugin
there are some concurrency related fixes in maven-shade-plugin like https://issues.apache.org/jira/browse/MSHADE-467
After bumping dependencies the problem disappears 
pom.xml
`./mvnw clean install -DskipTests -Dscala-2.12 -Pfast -Pskip-webui-build -U -T4`
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: ( …

[FLINK-20092] Bump maven-shade-plugin to 3.5.3 and maven-remote-resource-plugin to 3.2.0

---

flink-end-to-end-tests/test-scripts/common_s3_operations.sh
flink-end-to-end-tests/test-scripts/test_batch_wordcount.sh
flink-end-to-end-tests/test-scripts/test_file_sink.sh

Fix shaded hadoop S3A with credentials provider end-to-end test failed
This change is already covered by existing tests, such as *flink-end-to-end-tests/test-scripts/test_batch_wordcount.sh hadoop_with_provider*.

[FLINK-36435] Fix shaded hadoop S3A with credentials provider end-to-end test failed

---

flink-connectors/pom.xml
flink-end-to-end-tests/pom.xml
flink-end-to-end-tests/run-nightly-tests.sh

Currently, hive connector doesn't support Java 11. Thus, we have to exclude Hive connector for Flink 2.0 preview as we dropped the support for Java 8 and Hive doesn't support Java 11 at the moment. We will discuss further how to do with the Hive connector later.
- Exclude hive connector from pom. …

[FLINK-36437][hive] Exclude hive connector

---

flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStreamFactory.java

The `FsCheckpointStreamFactory` returns handles to files containing larger serialized data for checkpoint creation. However, these files are not synced persistently to disk via `fsync` before their handles are incorporated into completed checkpoints. Upon e.g. power loss this can cause corruption of a checkpoint as it references files that may now be lost due to missing persistence.  
This PR adds a #sync() call to the `FsCheckpointStreamFactory`'s #closeAndGetHandle() function. This makes sure that the returned handle always points to a file that has been safely persisted. 
- *Files written by `FsCheckpointStreamFactory` are now synced before their handle is referenced in checkpoints*
There is no easy way to unit- or integration-test these changes. OS tools are required. Correctness has …

[FLINK-36421] [fs] [checkpoint] Sync outputStream before returning handle in FsCheckpointStreamFactory

---

flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/table/FileSystemTableSource.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/connector/file/table/FileSystemTableSourceWithPartitionsITCase.java

When querying data from a partitioned filesystem table and filtering for one of the partition fields with a constant value we will get incorrect data back. This PR aims to fix that.
- Change `FileSystemTableSource` to create a projection of the partition keys using all partition fields in the table, not just the projected ones. This is needed to pass the correct physical layout of the file to the file format factory.
Added `FileSystemTableSourceWithPartitionsITCase` …

[FLINK-30899][connector/filesystem] Fix FileSystemTableSource incorrectly selecting fields on partitioned tables

---

flink-connectors/flink-connector-base/pom.xml
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/AsyncSinkBaseITCase.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/throwable/FatalExceptionClassifierTest.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterStateSerializerTest.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterTest.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterThrottlingTest.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/AsyncSinkWriterTimeoutTest.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/config/AsyncSinkWriterConfigurationBuilderTest.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/sink/writer/strategy/NoOpScalingStrategyTest.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceITCase.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceReaderTest.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitEnumeratorTest.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceSplitSerializerTest.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/hybrid/HybridSourceTest.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/AlignedWatermarksITCase.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/CoordinatedSourceITCase.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/CoordinatedSourceRescaleITCase.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/SourceMetricsITCase.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/SourceReaderBaseTest.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherManagerTest.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherPauseResumeSplitReaderTest.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherTest.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/synchronization/FutureCompletingBlockingQueueTest.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/utils/SerdeUtilsTest.java
flink-connectors/flink-connector-base/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension 

Migrate flink-connector-base module to AssertJ and JUnit 5 following the [JUnit 5 Migration Guide](https://docs.google.com/document/d/1514Wa_aNB9bJUen4xm5uiuXOooOJTtXqS_Jqk9KJitU/edit)
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper:  no) …

[FLINK-25546][flink-connector-base][JUnit5 Migration] Module: flink-connector-base

---

flink-connectors/flink-hadoop-compatibility/src/test/java/org/apache/flink/test/hadoopcompatibility/mapred/HadoopIOFormatsITCase.java
flink-connectors/flink-hadoop-compatibility/src/test/java/org/apache/flink/test/hadoopcompatibility/mapred/HadoopMapredITCase.java
flink-connectors/flink-hadoop-compatibility/src/test/java/org/apache/flink/test/hadoopcompatibility/mapred/WordCountMapredITCase.java
flink-connectors/flink-hadoop-compatibility/src/test/java/org/apache/flink/test/hadoopcompatibility/mapreduce/HadoopInputOutputITCase.java
flink-connectors/flink-hadoop-compatibility/src/test/java/org/apache/flink/test/hadoopcompatibility/mapreduce/WordCountMapreduceITCase.java

HadoopInputFormat related test cases have been updated from dataset to a datastream.
There are essentially batch jobs, but the HadoopInputFormat is an unbounded source.
As a result, the test cases cannot be set to batch runtime mode and should not run with the
adaptive scheduler. …

[hotfix] Ingore hadoopInputFormat related test case in adaptive scheduler

---

flink-runtime/src/main/java/org/apache/flink/streaming/api/datastream/KeyedPartitionWindowedStream.java
flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/KeyedPartitionWindowedStreamITCase.java

Fix RichMapPartitionFunction not call open method in KeyedPartitionWindowedStream.
- Fix RichMapPartitionFunction not call open method in KeyedPartitionWindowedStream
This change added an integration test case: org.apache.flink.test.streaming.runtime.KeyedPartitionWindowedStreamITCase#testRichMapPartitionFunctionHasOpen …

[FLINK-36423] Fix RichMapPartitionFunction does not invoke open method in KeyedPartitionWindowedStream

---

flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/PositionOutputStreamAdapter.java
flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/utils/ParquetFormatStatisticsReportUtil.java
flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/ParquetDecimalVector.java
flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/ParquetSplitReaderUtil.java
flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/reader/AbstractColumnReader.java
flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/reader/RunLengthDecoder.java
flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/reader/TimestampColumnReader.java

Use Flink Preconditions util instead of Parquet
`org.apache.parquet.Preconditions` -> `org.apache.flink.util.Preconditions`

[FLINK-36468][parquet] Use Flink Preconditions util instead of Parquet

---

flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/PositionOutputStreamAdapter.java
flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/utils/ParquetFormatStatisticsReportUtil.java
flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/ParquetDecimalVector.java
flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/ParquetSplitReaderUtil.java
flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/reader/AbstractColumnReader.java
flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/reader/RunLengthDecoder.java
flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/vector/reader/TimestampColumnReader.java

1.20 Backport of https://github.com/apache/flink/pull/25488
Use Flink Preconditions util instead of Parquet
`org.apache.parquet.Preconditions` -> `org.apache.flink.util.Preconditions`

[BP-1.20][FLINK-36468][parquet] Use Flink Preconditions util instead of Parquet

---

docs/content.zh/docs/dev/configuration/overview.md
docs/content/docs/dev/configuration/overview.md
pom.xml
tools/releasing/NOTICE-binary_PREAMBLE.txt

Bump log4j from 2.17.1 to 2.24.1
Bump log4j version from 2.17.1 to 2.24.1 in pom

[FLINK-36440] Bump log4j from 2.17.1 to 2.24.1

---

flink-tests/src/test/java/org/apache/flink/test/operators/TypeHintITCase.java

*Fix TypeHintITCase if adaptive scheduler enabled*

[hotfix][test] Fix TypeHintITCase if adaptive scheduler enabled

---

flink-yarn/src/main/java/org/apache/flink/yarn/DefaultYarnNodeManagerClientFactory.java
flink-yarn/src/main/java/org/apache/flink/yarn/DefaultYarnResourceManagerClientFactory.java
flink-yarn/src/main/java/org/apache/flink/yarn/YarnNodeManagerClientFactory.java
flink-yarn/src/main/java/org/apache/flink/yarn/YarnResourceManagerClientFactory.java
flink-yarn/src/main/java/org/apache/flink/yarn/YarnResourceManagerDriver.java
flink-yarn/src/test/java/org/apache/flink/yarn/TestingYarnNodeManagerClientFactory.java
flink-yarn/src/test/java/org/apache/flink/yarn/TestingYarnResourceManagerClientFactory.java
flink-yarn/src/test/java/org/apache/flink/yarn/YarnResourceManagerDriverTest.java

- Create `AMRMCallbackHandler` that extends `AMRMClientAsync.AbstractCallbackHandler`, keeping the already existing logic from `YarnContainerEventHandler`.
- Create `NMCallbackHandler` that extends `NMClientAsync.AbstractCallbackHandler`, keeping the already existing logic from `YarnContainerEventHandler`.
- Adapt the related code to handle the new separate classes.
- The …

[FLINK-36424][yarn] Update deprecated YARN RM/NM callback handlers in YarnResourceManagerDriver

---

flink-filesystems/flink-s3-fs-base/src/main/java/org/apache/flink/fs/s3/common/writer/S3RecoverableFsDataOutputStream.java
flink-filesystems/flink-s3-fs-base/src/test/java/org/apache/flink/fs/s3/common/writer/S3RecoverableFsDataOutputStreamTest.java

At the moment `S3RecoverableFsDataOutputStream.sync` closing the stream and all upcoming `write` operations fail consistently with the following exception:
```
java.io.IOException: Stream closed.
at org.apache.flink.core.fs.RefCountedFileWithStream.requireOpened(RefCountedFileWithStream.java:72)
at org.apache.flink.core.fs.RefCountedFileWithStream.write(RefCountedFileWithStream.java:52)
at org.apache.flink.core.fs.RefCountedBufferingFileStream.flush(RefCountedBufferingFileStream.java:104)
at org.apache.flink.core.fs.RefCountedBufferingFileStream.write(RefCountedBufferingFileStream.java:87)
at org.apache.flink.fs.s3.common.writer.S3RecoverableFsDataOutputStream.write(S3RecoverableFsDataOutputStream.java:112)
at java.base/java.io.OutputStream.write(OutputStream.java:122)
```
In this PR …

[FLINK-36124][filesystem][s3]Make S3RecoverableFsDataOutputStream.sync not to close the stream

---

docs/content.zh/docs/dev/table/sql/show.md
docs/content/docs/dev/table/sql/show.md
flink-table/flink-sql-client/src/test/resources/sql/catalog_database.q
flink-table/flink-sql-gateway/src/test/resources/sql/catalog_database.q
flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl
flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/dql/SqlShowCatalogs.java
flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ShowCatalogsOperation.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlNodeToOperationConversion.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlNodeConverters.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlShowCatalogsConverter.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlOtherOperationConverterTest.java

Support enhanced show catalogs syntax for [FLIP-297](https://cwiki.apache.org/confluence/display/FLINK/FLIP-297%3A+Improve+Auxiliary+Sql+Statements)
Support enhanced show catalogs syntax:
```sql
SHOW CATALOGS [ [NOT] (LIKE | ILIKE) <sql_like_pattern> ]
```
Add cases in FlinkSqlParserImplTest:
- testShowCatalogs
Add cases in SqlOtherOperationConverterTest:
- testShowCatalogs
sql-client & sql-client-gateway:
catalog_databases.q
- The S3 file …

[FLINK-31380][table] Support enhanced show catalogs syntax

---

flink-clients/src/main/java/org/apache/flink/client/program/artifact/ArtifactFetchManager.java
flink-clients/src/main/java/org/apache/flink/client/program/artifact/FsArtifactFetcher.java
flink-clients/src/main/java/org/apache/flink/client/program/artifact/HttpArtifactFetcher.java
flink-clients/src/test/java/org/apache/flink/client/program/artifact/ArtifactFetchManagerTest.java

Fixing the default behavior of the artifact fetcher in case of a read-only K8s FS and `local://` artifacts. Currently, the artifact fetcher always try to create the base parent dirs before actually trying to fetch any artifact, and fail in such scenario.
- Move the `ArtifactUtils#createMissingParents` calls to the specific fetchers where it makes sense.
Added unit test to validate `ArtifactUtils#createMissingParents` is not called if we fetch `local://` artifacts. …

[FLINK-35833][clients] Skip trying to create parents for "user.artifacts.base-dir" when fetching a "local://" artifact(s)

---

flink-clients/src/main/java/org/apache/flink/client/program/artifact/ArtifactFetchManager.java
flink-clients/src/main/java/org/apache/flink/client/program/artifact/FsArtifactFetcher.java
flink-clients/src/main/java/org/apache/flink/client/program/artifact/HttpArtifactFetcher.java
flink-clients/src/test/java/org/apache/flink/client/program/artifact/ArtifactFetchManagerTest.java

1.20 backport of https://github.com/apache/flink/pull/25487

[BP-1.20][FLINK-35833][clients] Skip trying to create parents for "user.artifacts.base-dir" when fetching a "local://" artifact

---

flink-clients/src/main/java/org/apache/flink/client/program/artifact/ArtifactFetchManager.java
flink-clients/src/main/java/org/apache/flink/client/program/artifact/FsArtifactFetcher.java
flink-clients/src/main/java/org/apache/flink/client/program/artifact/HttpArtifactFetcher.java
flink-clients/src/test/java/org/apache/flink/client/program/artifact/ArtifactFetchManagerTest.java

1.19 backport of https://github.com/apache/flink/pull/25487

[BP-1.19][FLINK-35833][clients] Skip trying to create parents for "user.artifacts.base-dir" when fetching a "local://" artifact

---

flink-runtime/src/main/java/org/apache/flink/streaming/api/lineage/DefaultLineageGraph.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/lineage/LineageGraphUtils.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/lineage/LineageGraphUtilsTest.java

To support complete lineage info collection, we need to make sure every connector used in a Flink application has the lineage provider interface implemented. As the feature adding and release of each connector takes time, we want to support participial lineage info collection. So that even some subset of connector with lineage support used in Flink, we can still see the source/ sink Lineage Node in reporter.
- Change the LineageGraphUtils to support partial lineage info collection
- *Added new test cases for LineageGraphUtilsTest* …

[FLINK-36510][runtime] Support partial lineage info collection

---

flink-python/pyflink/table/expression.py
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/SqlCallSyntax.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/StringFunctionsITCase.java

This PR improves handling of `+` operator in more cases.
Added tests.

[FLINK-36241] Table API .plus should support string concatenation

---

flink-core/src/main/java/org/apache/flink/core/memory/MemoryUtils.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ByteBufferWritableFSDataOutputStream.java

Currently, the ForSt gives a direct buffer to `ByteBufferWritableFSDataOutputStream`, where the data will be written one byte by byte. According our perf, the statistics of hadoop based fs will be updated once for each byte, which takes a lot of CPU. Below is a flamegraph, where the statistics part is marked as purple (taking 8.14% of the overall CPU).
This PR copies the data to a heap buffer before invoking `write` to optimize this.
- Writing logic in `ByteBufferWritableFSDataOutputStream` …

[FLINK-36526][state/forst] Optimize the overhead of writing with direct buffer

---

flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/security/token/HiveServer2DelegationTokenProvider.java
flink-connectors/flink-connector-hive/src/main/resources/META-INF/services/org.apache.hadoop.security.token.TokenIdentifier

Backport https://github.com/apache/flink/pull/25428 against the release-1.19.

[FLINK-36405][runtime] Fix startup issues on kerberos clusters.

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/CallSyntaxUtils.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/SqlCallSyntax.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/QueryOperationSqlExecutionTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/QueryOperationSqlSerializationTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/QueryOperationTestPrograms.java

Fix string serialization of `OVER` window
added tests

[FLINK-36543] Fix string serialization for OVER windows

---

flink-core/src/main/java/org/apache/flink/core/security/FlinkSecurityManager.java

The halt() call in checkExit() will again cause checkExit() to be called since we don't null the security manager, in contrast to how forceProcessExit is implemented.
This is only an issue during the process startup, as at later times we typically initiate the shutdown for forceProcessExit.

[FLINK-36511] Prevent StackOverflow in FlinkSecurityManager

---

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/NettyServer.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyServerTest.java

When Netty Epoll transport is enabled, Netty will throw a different bind exception if the given address is already in use. In case of a port range, or multiple ports are given, this will cause process termination after the first non-free port, even if there are more that could be tried.
Introduce `NettyServer#isBindFailure` method to make bind exception detection more robust. The applied logic takes inspiration from https://github.com/apache/spark/pull/15830.
Added unit tests to `NettyServerTest`. I do not assert for `Errors.NativeIoException` because to instantiate such object, it requires proper JNI links, as its ctor always try to call out to native code.
Also verified with a Standalone job on a RedHat8 VM via setting `taskmanager.data.bind-port` to `8081, 55000`, as `8081` will be …

[FLINK-36533][runtime] Fix detecting bind failure in case of Netty EPOLL transport

---

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/NettyServer.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyServerTest.java

1.20 backport of https://github.com/apache/flink/pull/25518

[BP-1.20][FLINK-36533][runtime] Fix detecting bind failure in case of Netty EPOLL transport

---

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/NettyServer.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyServerTest.java

1.19 backport of https://github.com/apache/flink/pull/25518

[BP-1.19][FLINK-36533][runtime] Fix detecting bind failure in case of Netty EPOLL transport

---

flink-runtime/src/main/java/org/apache/flink/runtime/state/CompressibleFSDataInputStream.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/CompressibleFSDataInputStreamTest.java

Flink state restore from S3 is super slow because `skip` function is consuming ~15 seconds for ~6Mb of data. This operation is called for each and every list state element for `CompactCoordinator` state (all similar operator list states are effected). The list of this is several thousands during normal operation which ends up in multiple days of restore time.
In this PR the `skip` going to be called only in case of compression because otherwise a stream is seekable.
Do not call `skip` operation in case of uncompressed state.
Manually on cluster + changed unit test. …

[FLINK-36530][state] Fix S3 performance issue with uncompressed state restore

---

flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStreamFactory.java

Backport of FLINK-36421 for 1.18
Cherry-pick of commit dfb9bfeabac8d3ac289e46a3017ed68c50ba3777 from original PR #25468

[BP-1.18][FLINK-36421] [fs] [checkpoint] Sync outputStream before returning handle in FsCheckpointStreamFactory

---

flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStreamFactory.java

Backport of FLINK-36421 for 1.19
Cherry-pick of commit dfb9bfeabac8d3ac289e46a3017ed68c50ba3777 from original PR #25468

[BP-1.19][FLINK-36421] [fs] [checkpoint] Sync outputStream before returning handle in FsCheckpointStreamFactory

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/AsyncKeyedStateBackend.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/adaptor/AsyncKeyedStateBackendAdaptor.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/InternalTimeServiceManager.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/InternalTimeServiceManagerImpl.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamOperatorStateContext.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamOperatorStateHandler.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamTaskStateInitializerImpl.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionInternalTimeServiceManager.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendTestUtils.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractKeyedStateTestBase.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/StateBackendTestV2Base.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/StateInitializationContextImplTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/StreamTaskStateInitializerImplTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionInternalTimeServiceTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/util/AbstractStreamOperatorTestHarness.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackendBuilder.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateBackend.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/restore/ForStHeapTimersFullRestoreOperation.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/AbstractAsyncStateStreamOperatorV2Test.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
flink-tests/src/test/java/org/apache/flink/test/state/operator/restore/StreamOperatorSnapshotRestoreTest.java

This PR supports storing timer in JVM heap when use async state backend. 
Note: Timers are stored as raw keyed state instead of managed keyed state now, the snapshot/restore of jvm timer is managed by `InternalTimeServiceManager`.
- Implement `ForStKeyedStateBackend#create() -> KeyGroupedInternalPriorityQueue`
- Support using async keyed state backend initializing `timeServiceManager` in `StreamTaskStateInitializerImpl`
- `StateBackendTestV2Base#testKeyGroupedInternalPriorityQueue` …

[FLINK-35029][state/forst] Store timer in JVM heap when use async state backend

---

flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/sink/compactor/CompactorOperatorTest.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/connector/sink2/GlobalCommitterOperator.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/connector/sink2/StandardSinkTopologies.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/connector/sink2/SupportsPreCommitTopology.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/StreamGraphGenerator.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/transformations/GlobalCommitterTransform.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManager.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManagerImpl.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollector.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/translators/GlobalCommitterTransformationTranslator.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/connector/sink2/CommittableSummaryAssert.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/connector/sink2/CommittableWithLineageAssert.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/connector/sink2/GlobalCommitterOperatorTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/connector/sink2/SinkV2Assertions.java
flink-runtime/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManagerImplTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorSerializerTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/SubtaskCommittableManagerTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperatorTestBase.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkTestUtil.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperatorTestBase.java

[FLINK-36287](https://issues.apache.org/jira/browse/FLINK-36287) disabled UC for all inter-sink connections to adhere to the contract of notifyCheckpointCompleted. This allows us to remove some special casing and improve global committer.
* Refactor sink test assertions 
* Optimize global committers 
* Optimize committers with UC disabled
See commit messages for more details.
Covered by tests in
* org.apache.flink.streaming.runtime.operators.sink
* org.apache.flink.streaming.api.connector.sink2
* Various IT cases and E2E tests
I modified / extended the former two suites.
- The …

[FLINK-36379] Improve (Global)Committer with UC disabled

---

flink-runtime/pom.xml
flink-runtime/src/main/resources/META-INF/NOTICE

Addresses [CVE-2024-36114](https://nvd.nist.gov/vuln/detail/CVE-2024-36114) which concerns a vulnerability in the aircompressor library.
Upgrade the `io.airlift:aircompressor` version used by `flink-runtime` from 0.21 to 0.27. 

[FLINK-36593][flink-runtime] Update io.airlift:aircompressor to 0.27

---

docs/layouts/shortcodes/generated/all_taskmanager_section.html
docs/layouts/shortcodes/generated/task_manager_memory_configuration.html
flink-core/src/main/java/org/apache/flink/configuration/TaskManagerOptions.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/NettyShuffleServiceFactory.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PipelinedApproximateSubpartition.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PipelinedSubpartition.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/ResultPartitionFactory.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateFactory.java
flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/NettyShuffleEnvironmentConfiguration.java
flink-runtime/src/main/java/org/apache/flink/runtime/throughput/BufferDebloatConfiguration.java
flink-runtime/src/main/java/org/apache/flink/runtime/throughput/BufferDebloater.java
flink-runtime/src/main/java/org/apache/flink/runtime/throughput/BufferSizeEMA.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/NettyShuffleEnvironmentBuilder.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/NettyShuffleEnvironmentTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PipelinedApproximateSubpartitionWithReadViewTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PipelinedSubpartitionTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PipelinedSubpartitionWithReadViewTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/ResultPartitionBuilder.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/ResultPartitionFactoryTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/throughput/BufferDebloaterTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/throughput/BufferSizeEMATest.java

This PR intends to improve the behaviour of buffer debloating.
[FLINK-36555] Guarantee buffer grows even with very small alpha
[FLINK-36556] Add starting buffer size config option
This PR adds new unit tests or is cover by existing ones  …

[FLINK-36556][FLINK-36555] Improve buffer debloating

---

docs/content/docs/deployment/java_compatibility.md

Trivial docs backport of https://github.com/apache/flink/pull/25342 to `release-1.19`.

[BP-1.19][docs] Update Java 17 compatibility docs

---

docs/content/docs/deployment/java_compatibility.md

Trivial docs backport of https://github.com/apache/flink/pull/25342 to `release-1.20`.

[BP-1.20][docs] Update Java 17 compatibility docs

---

docs/content.zh/docs/flinkDev/ide_setup.md
docs/content/docs/flinkDev/ide_setup.md
pom.xml

Bumping checkstyle to 10+
- The serializers: (yes )

[FLINK-36470][build] Bump checkstyle to 10+

---

flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/input/StreamOperatorContextBuilder.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperatorV2.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamOperatorStateContext.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamOperatorStateHandler.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamTaskStateInitializer.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamTaskStateInitializerImpl.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamingRuntimeContext.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/StateInitializationContextImplTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/StreamOperatorStateHandlerTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/StreamTaskStateInitializerImplTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java

Currently, the operator will create both `AsyncKeyedStateBackend` and `KeyedStateBackend` and pick one for use. This PR only creates one depending on whether the operator performs async state processing or not.
- Introduce internal method `isAsyncStateProcessingEnabled` in `AbstractStreamOperator`.
- Determine `isAsyncStateProcessingEnabled` in state initialization (including timerservice).
- Remove redundant override methods. …

[FLINK-36589][state/runtime] Decouple the initialization of sync and async keyed statebackend

---

flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/TimestampITCase.java

The problem of  `TimestampITCase` is that it generates `test` folder outside of temp folder and it appears in git diff
steps to reproduce
```
cd flink-tests && ../mvnw -Dtest=TimestampITCase test && git status
```
TimestampITCase
The change is change of tests itself
also could be verified with 
```
cd flink-tests && ../mvnw -Dtest=TimestampITCase test && git status
``` …

[FLINK-36606][tests] TimestampITCase generates test artifacts outside of tmp folder

---

flink-test-utils-parent/flink-test-utils/src/test/java/org/apache/flink/state/benchmark/StateBackendBenchmarkUtils.java

Currently, flink-benchmarks relies on non-public APIs in Flink. For example, in StateBackendBenchmarkUtils.java, the function compactState takes RocksDBKeyedStateBackend as its first argument.
This requires explicit type conversion in flink-benchmark(from KeyedStateBackend to RocksDBKeyedStateBackend). Moreover, this means that once the signature of RocksDBKeyedStateBackend changes, we need to modify flink-benchmark correspondingly.
Therefore, we should avoid exposing non-public APIs in StateBackendBenchmarkUtils.
Change the 1st argument of `StateBackendBenchmarkUtils#compactState` from RocksDBKeyedStateBackend to KeyedStateBackend. …

[FLINK-36622] Remove the dependency of StateBenchmark on RocksDBKeyedStateBackend APIs.

---

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/AggregateQueryOperation.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/CalculatedQueryOperation.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/DistinctQueryOperation.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/FilterQueryOperation.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/JoinQueryOperation.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/OperationUtils.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ProjectQueryOperation.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/SetQueryOperation.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/SortQueryOperation.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/SourceQueryOperation.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ValuesQueryOperation.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/WindowAggregateQueryOperation.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/utils/OperationExpressionsUtils.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/expressions/FieldReferenceExpression.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/QueryOperationSqlExecutionTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/QueryOperationSqlSerializationTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/QueryOperationTestPrograms.java

Scope all references in Table API when converting to a SQL string.
This change adapted tests in `org.apache.flink.table.api.QueryOperationSqlSerializationTest`.
Moreover tests in `org.apache.flink.table.api.QueryOperationSqlExecutionTest` should still work (all other as well of course, but those are particularly interesting).
Additionally, added `QueryOperationTestPrograms.ACCESSING_NESTED_COLUMN` which does not work without the changes. …

[FLINK-36639] Use table aliases in Table API asSerializableString

---

flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/expressions/ExpressionSerializationTest.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java

Make it possible to string serialize `TIMESTAMPDIFF`
Added tests in `ExpressionSerializationTest`

[FLINK-36644] TIMESTAMPDIFF can not be string serialized

---

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/DefaultStateTransitionManager.java

This PR fixes the log-level regression introduced in https://github.com/apache/flink/pull/25280#discussion_r1818949028
- The log level reverted back to the INFO in the StateTransitionManager
- Added a few more log lines  in the StateTransitionManager …

[FLINK-36011][runtime] Improved logging in StateTransitionManager

---

flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/expressions/ExpressionSerializationTest.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java

Fix the SQL names of several built-in functions. 
The names are used to serialize Table API expressions to SQL. Using wrong function names results in SQL statements that cannot be executed.
* add `sqlName()` to several `BuiltInFunctionDefinition` in `BuiltInFunctionDefinitions`
* add test cases to `ExpressionSerializationTest`
* run `ExpressionSerializationTest` unit test
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes (`BuiltInFunctionDefinitions` is `@PublicEvolving`) …

[FLINK-36642][table] Fix SQL names of built-in functions

---

flink-rpc/flink-rpc-akka/pom.xml
flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/pekko/ActorSystemBootstrapTools.java
flink-rpc/flink-rpc-akka/src/main/java/org/apache/flink/runtime/rpc/pekko/PekkoUtils.java
flink-rpc/flink-rpc-akka/src/main/resources/META-INF/NOTICE

Updates Pekko dependency to 1.1.2 which in turn upgrades Netty 3 to 4 (addressing [FLINK-29065](https://issues.apache.org/jira/browse/FLINK-29065) and removing several CVEs from Flink). Pekko 1.1 also upgrades other dependencies such as slf4j and Jackson. For more details see the [Pekko 1.1 release notes](https://pekko.apache.org/docs/pekko/current/release-notes/releases-1.1.html). CC @uce and @ferenc-csaky :smile:
- Update Pekko version from 1.0.1 to 1.1.2
- Replace Pekko Netty 3 dependency with flink-shaded Netty 4 (and test-scoped direct Netty 4 dependency) - _Note [Flink 1.19 uses flink-shaded 17.0](https://github.com/apache/flink/blob/release-1.19/pom.xml#L124), which [bundles Netty 4.1.91.Final](https://github.com/apache/flink-shaded/blob/release-17.0/pom.xml#L65)_
- Update Netty …

[FLINK-36510][rpc] bump pekko to 1.1.2, remove netty 3 (backport to release-1.19)

---

flink-python/pyflink/table/expressions.py
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/Expressions.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/OverWindow.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/OverWindowPartitionedOrdered.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/OverWindowPartitionedOrderedPreceding.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/expressions/resolver/ExpressionResolver.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/expressions/resolver/LocalOverWindow.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/expressions/resolver/rules/OverWindowResolverRule.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/CallSyntaxUtils.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/SqlCallSyntax.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/LeadLagInputTypeStrategy.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/OverTypeStrategy.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/SpecificInputTypeStrategies.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/SpecificTypeStrategies.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/TypeStrategiesTest.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/strategies/LeadLagInputTypeStrategyTest.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/expressions/SqlAggFunctionVisitor.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/expressions/converter/OverConvertRule.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/QueryOperationSqlExecutionTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/QueryOperationSqlSerializationTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/QueryOperationTestPrograms.java

Support `LEAD/LAG` functions natively in Table API.
Added tests for input, output strategies and e2e test for serializing and executing table API programs as SQL.
- If yes, how is the feature documented? (not applicable / …

[FLINK-36615] Support LEAD/LAG functions in Table API

---

docs/data/sql_functions.yml
docs/data/sql_functions_zh.yml

Update the docs to include the Table API aggregation functions `lead()` and `lag()` (added with #25582)
Adds syntax for Table API `lead()` and `lag()` functions to English and Chinese docs. 
The functions already have a description because they've been available for SQL.
n/a
Docs-only change to describe recently added functionality.

[hotfix] [docs] Add lead()/lag() Table API agg functions to docs

---

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/DefaultStateTransitionManager.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Finished.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/State.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StateTransitionManager.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StateWithExecutionGraph.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StateWithoutExecutionGraph.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/DefaultStateTransitionManagerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/ExecutingTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/MockStateWithoutExecutionGraphContext.java

- Exposed the JobID in `Adaptive Scheduler` states
- Added JobID to logs in `DefaultStateTransitionManager`

[FLINK-36623] Improve logging in DefaultStateTransitionManager

---

docs/layouts/shortcodes/generated/common_miscellaneous_section.html
flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/sink/compactor/operator/CompactorOperatorStateHandler.java
flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/sink/compactor/CompactorOperatorTest.java
flink-core/src/main/java/org/apache/flink/configuration/SinkOptions.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/connector/sink2/CommittableSummary.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/connector/sink2/GlobalCommitterOperator.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManager.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManagerImpl.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollector.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorSerializer.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/SubtaskCommittableManager.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/connector/sink2/CommittableMessageSerializerTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/connector/sink2/CommittableSummaryAssert.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/connector/sink2/GlobalCommitterOperatorTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/connector/sink2/GlobalCommitterSerializerTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManagerImplTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorSerializerTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/SubtaskCommittableManagerTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperatorTestBase.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperatorTestBase.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/TestSinkV2.java

Sinks so far retried asynchronously to increase commit throughput in case of temporary issues. However, the contract of notifyCheckpointCompleted states that checkpoints must be side-effect free meaning all transactions have to be committed on return of the PRC call.
* This commit retries a fixed number of times and then fails in notifyCheckpointCompleted.
* Simplifies parts of committable handling now that all committables of a subtask either succeed or fail
* Already covered by many tests
* Adjusted and changed tests in
api/connector/sink2
runtime/operators/sink/committables
- …

[FLINK-36455] Sinks retry synchronously

---

flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/traces/SpanBuilder.java
flink-metrics/flink-metrics-core/src/test/java/org/apache/flink/traces/SpanBuilderTest.java

*Fix the default value of endTsMillisToBuild in SpanBuilder*
*fix default value of endTsMillis in SpanBuilder*

[hotfix][metrics] Fix default value of endTsMillis in SpanBuilder

---

flink-table/flink-table-planner/src/main/java/org/apache/calcite/rel/metadata/RelMdPredicates.java
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/agg/GroupingSetsTest.xml
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/agg/GroupingSetsTest.scala

This pr port the bugfix of CALCITE-6317 to fix the incorrectly constant pullup when group keys in aggregate are NULL
Before upgraded corresponding calcite version(1.37), we can have the fix that copy the related `RelMdPredicates` to flink and remove it after calcite version upgrading done.
Copy the `RelMdPredicates` based on 1.32.0 and add the fix of  CALCITE-6317 
Add new case for `GroupingSetsTest` …

[FLINK-36662][table-planner] Port CALCITE-6317 to fix the incorrectly constant pullup when group keys in aggregate are NULL

---

flink-core/src/main/java/org/apache/flink/core/fs/local/LocalDataInputStream.java
flink-dist/src/main/resources/META-INF/NOTICE
flink-state-backends/flink-statebackend-forst/pom.xml
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStConfigurableOptions.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStOptions.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystem.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/BundledCacheLimitPolicy.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/CacheLimitPolicy.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/CachedDataInputStream.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/CachedDataOutputStream.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/FileBasedCache.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/FileCacheEntry.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/LruCache.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/SizeBasedCacheLimitPolicy.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/SpaceBasedCacheLimitPolicy.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStResourceContainerTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystemTest.java

This PR supports file cache for ForStStateBackend, the cache is file-granularity. Only newly generated SSTs are written to the cache, the file reading from the remote will not. Newly generated SSTs are written to the original file system and cache simultaneously, so, the cached file can be directly deleted with persisting when evicting.
- Add `FileBasedCache`.
- Integrate `FileBasedCache` to `ForStFlinkFileSystem`
- `ForStFlinkFileSystemTest#testSstFileInCache` …

[FLINK-36592][state/forst] Support file cache for ForStStateBackend

---

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/SqlExpressionTest.scala

This pull request aims to fix the codegen bug in table planner triggered by decimal type divide Integer type and relates to FLINK-36654.
Modified the cast rule in generateDecimalBinaryArithmeticOperator method.
- *testDivideFunctions in SqlExpressionTest for validatation.*

[FLINK-36654] [table] Fix wrong cast when decimal divide integer

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/FactoryUtil.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/factories/utils/FactoryMocks.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/schema/CatalogSourceTable.java

[[FLINK-36476](https://issues.apache.org/jira/browse/FLINK-36476)](https://issues.apache.org/jira/browse/FLINK-36476) Remove all deprecated methods under public APIs in table modules
subtask:
[FLINK-36502](https://issues.apache.org/jira/browse/FLINK-36502) Remove all deprecated methods in `FactoryUtil`
Remove deprecated methods
This change is already covered by existing tests, see *org.apache.flink.table.factories.FactoryUtilTest*. …

[FLINK-36502] [TABLE-SQL] Remove deprecated methods in FactoryUtil.

---

docs/setup_docs.sh

Update docs for AWS connector to point to v5.0 branch
Update docs for AWS connector to point to v5.0 branch

[FLINK-36668][docs] Update AWS docs for v5.0

---

flink-tests/src/test/java/org/apache/flink/test/checkpointing/RescaleCheckpointManuallyITCase.java

This PR fixes two issues about RescaleCheckpointManuallyITCase:
- The `RescaleCheckpointManuallyITCase#CollectionSink` collects elements into a single static collection, which might be a problem when multiple tests run in parallel.
- The `RescaleCheckpointManuallyITCase`  does not ensure all the data from the first job has being processed and snapshotted before it performs a rescale, resulting in some data loss in the final aggregation result. This can be easily reproduced by setting the param `checkpointingInterval` of `createJobGraphWithKeyedState` as 20 or less.
- Refactor `RescaleCheckpointManuallyITCase#CollectionSink`, decouple the data from different jobs.
- Change `RescaleCheckpointManuallyITCase$NotifyingDefiniteKeySource#waitCheckpointCompleted` and its related logic, making it …

[FLINK-36613] Fix unstable RescaleCheckpointManuallyITCase

---

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackendBuilder.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateBackend.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystem.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/restore/ForStHandle.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/restore/ForStHeapTimersFullRestoreOperation.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/restore/ForStIncrementalRestoreOperation.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/restore/ForStNoneRestoreOperation.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/sync/ForStSyncKeyedStateBackend.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/sync/ForStSyncKeyedStateBackendBuilder.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStExtension.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStResourceContainerTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateBackendConfigTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystemTest.java

Currently, the `ForSt` needs a `FileSystem` instance from `Flink` side, but it is created by a JNI call from `ForSt`. It is more reasonable to create it in `Flink` side and provide it to `ForSt`.
- Use `Path` instead `File` everywhere in `ForSt`
- Create `ForStFlinkFileSystem` instance and provide it to `ForSt` during initialization. …

[FLINK-36598][state/ForSt] Provide FileSystem instance in initialization

---

flink-formats/flink-parquet/src/main/java/org/apache/flink/formats/parquet/utils/NestedPositionUtil.java
flink-formats/flink-parquet/src/test/java/org/apache/flink/formats/parquet/vector/ParquetColumnarRowSplitReaderTest.java

Fix parquet can not read row with last column is array.
- fix a corner condition.
*(or)*
*(or)*
- modify unit test case …

[FLINK-36709][parquet] fix parquet can not read row with last column is array.

---

docs/content.zh/docs/dev/datastream/operators/process_function.md

---
Translate Process Function page into Chinese
---
Does this pull request potentially affect one of the following parts:
---
Documentation
--- …

[FLINK-16155][docs] Translate "Operator/Process Function" into Chinese

---

flink-connectors/flink-hadoop-compatibility/src/test/java/org/apache/flink/test/hadoopcompatibility/mapred/HadoopIOFormatsITCase.java
flink-connectors/flink-hadoop-compatibility/src/test/java/org/apache/flink/test/hadoopcompatibility/mapred/HadoopMapredITCase.java
flink-connectors/flink-hadoop-compatibility/src/test/java/org/apache/flink/test/hadoopcompatibility/mapred/WordCountMapredITCase.java
flink-connectors/flink-hadoop-compatibility/src/test/java/org/apache/flink/test/hadoopcompatibility/mapreduce/HadoopInputOutputITCase.java
flink-connectors/flink-hadoop-compatibility/src/test/java/org/apache/flink/test/hadoopcompatibility/mapreduce/WordCountMapreduceITCase.java

*We wanted to skip some batch related tests for adaptive-scheduler in ccb9bc27. Unfortunately, these test classes are based on Junit5, and using `Category` does not take effect. This can be fixed via using `Tag` in Juint5.*
Use Tag to replace some incorrectly used Category annotation for skipping adaptvie-scheduler test
- Does this …

[hotfix] Use Tag to replace some incorrectly used Category annotation for skipping adaptvie-scheduler test

---

flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/RecreateOnResetOperatorCoordinator.java
flink-tests/src/test/java/org/apache/flink/test/misc/JobIDLoggingITCase.java

This PR fixes `JobIDLoggingITCase` test failures by 
1. Logging job ID from `RecreateOnResetOperatorCoordinator`
2. Removing assertions about optional messages

[FLINK-36710] Log job ID in RecreateOnResetOperatorCoordinator

---

flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/state/rocksdb/sstmerge/CompactionScheduler.java

[FLINK-36714][state] Ignore interrupted in sstmerge.CompactionScheduler#stop

---

docs/content.zh/docs/dev/datastream/operators/process_function.md
docs/content.zh/docs/dev/table/data_stream_api.md
docs/content.zh/docs/dev/table/sourcesSinks.md
docs/content.zh/docs/try-flink/datastream.md
docs/content/docs/dev/datastream/operators/process_function.md
docs/content/docs/dev/table/data_stream_api.md
docs/content/docs/dev/table/sourcesSinks.md
docs/content/docs/try-flink/datastream.md

This PR fix  [FLINK-35977](https://issues.apache.org/jira/browse/FLINK-35977) that misssing an import about OpenContext.
- Adding an import about `OpenContext` in doc datastream.md
- Removing an import about `Configuration` in doc datastream.md

[FLINK-35977][doc] Missing an import in datastream.md

---

flink-clients/src/main/java/org/apache/flink/client/program/artifact/ArtifactFetchManager.java
flink-clients/src/test/java/org/apache/flink/client/program/artifact/ArtifactFetchManagerTest.java
flink-kubernetes/src/main/java/org/apache/flink/kubernetes/KubernetesClusterDescriptor.java
flink-kubernetes/src/main/java/org/apache/flink/kubernetes/entrypoint/KubernetesApplicationClusterEntrypoint.java
flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/KubernetesUtils.java
flink-kubernetes/src/test/java/org/apache/flink/kubernetes/KubernetesClusterDescriptorTest.java
flink-kubernetes/src/test/java/org/apache/flink/kubernetes/entrypoint/KubernetesApplicationClusterEntrypointTest.java
flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
flink-yarn/src/main/java/org/apache/flink/yarn/entrypoint/YarnApplicationClusterEntryPoint.java
flink-yarn/src/test/java/org/apache/flink/yarn/YarnClusterDescriptorTest.java
flink-yarn/src/test/java/org/apache/flink/yarn/entrypoint/YarnApplicationClusterEntryPointTest.java

*Relax the limitation that application mode requires a main jar.*
- *Remove the check that `pipeline.jar` must have one jar*
- *Add tests to get packaged program if `pipeline.jar` is empty*
- *Add tests to deploy a cluster if `pipeline.jar` is empty* …

[FLINK-36755][yarn][k8s] Relax the limit about the pipeline.jar must have one in application mode

---

flink-table/flink-sql-client/src/test/resources/sql/function.q
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinition.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/StateTypeStrategy.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/StateTypeStrategyWrapper.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/StaticArgument.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/StaticArgumentTrait.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/TypeInference.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/extraction/TypeInferenceExtractorTest.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/InputTypeStrategiesTest.java

Update TypeInference and introduce StateTypeStrategy, StaticArgument, StaticArgumentTraits and related declarations.
According to FLIP-440.
- Generalize typedArguments/namedArguments to StaticArgument
- Generalize accumulatorStrategy to StateTypeStrategy
This change is already covered by existing tests, such as TypeInferenceExtractorTest. …

[FLINK-36704] Update TypeInference with StaticArgument and StateTypeStrategy

---

flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorSplitWatermarkAlignmentTest.java

Fix PausableRelativeClock does not pause when the source only has one split.
- Pause the mainInputActivityClock when SourceOperator is waiting for alignment
- Pause the split even if the sourceOperator only has one split
This adds a new test case. …

[FLINK-36751] Fix PausableRelativeClock does not pause when the source only has one split

---

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorSplitWatermarkAlignmentTest.java

this is a backport of https://github.com/apache/flink/pull/25678

(1.20 backport)[FLINK-36751] Fix PausableRelativeClock does not pause when the source only has one split

---

docs/content.zh/docs/dev/table/functions/udfs.md
docs/content.zh/docs/dev/table/procedures.md
docs/content/docs/dev/table/functions/udfs.md
docs/content/docs/dev/table/procedures.md
flink-table/flink-table-common/src/main/java/org/apache/flink/table/annotation/ArgumentHint.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/annotation/ArgumentTrait.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/annotation/FunctionHint.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/annotation/ProcedureHint.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/BaseMappingExtractor.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/ExtractionUtils.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/FunctionTemplate.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/extraction/TypeInferenceExtractorTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestProcedureCatalogFactory.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/FunctionITCase.java

Cleans up `@FunctionHint` and `@ProcedureHint` to comply with FLIP-387. It adds the modification for `@ArgumentHint` required for FLIP-440.
- Deprecation of `FunctionHint.argumentNames`
- Deprecation of `FunctionHint.argument`
- Deprecation of `ProcedureHint.argumentNames`
- Deprecation of `ProcedureHint.argument`
- Adding of `ArgumentHint.value` with `ArgumentTraits`
This change added tests and can be verified as follows: `TypeInferenceExtractorTest`
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes  …

[FLINK-36789][table-common] Update FunctionHint and ArgumentHint with traits

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecWindowTableFunction.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/ExecNodeMetadataUtil.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/batch/WindowTableFunctionEventTimeBatchRestoreTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/common/WindowTableFunctionTestPrograms.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/WindowTableFunctionProcTimeRestoreTest.java
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-window-table-function_1/window-table-function-cumulate-tvf-agg/plan/window-table-function-cumulate-tvf-agg.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-window-table-function_1/window-table-function-cumulate-tvf/plan/window-table-function-cumulate-tvf.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-window-table-function_1/window-table-function-hop-tvf-agg/plan/window-table-function-hop-tvf-agg.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-window-table-function_1/window-table-function-hop-tvf/plan/window-table-function-hop-tvf.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-window-table-function_1/window-table-function-tumble-tvf-agg/plan/window-table-function-tumble-tvf-agg.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-window-table-function_1/window-table-function-tumble-tvf-negative-offset/plan/window-table-function-tumble-tvf-negative-offset.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-window-table-function_1/window-table-function-tumble-tvf-positive-offset/plan/window-table-function-tumble-tvf-positive-offset.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-window-table-function_1/window-table-function-tumble-tvf/plan/window-table-function-tumble-tvf.json

* Adds Compiled Plan annotations to BatchExecWindowTableFunction.

[FLINK-36720] Add CompiledPlan annotations to BatchExecWindowTableFunction

---

flink-table/flink-table-calcite-bridge/pom.xml
flink-table/flink-table-runtime/src/main/resources/META-INF/NOTICE
flink-table/pom.xml

Currently, the `flink-table` modules uses `json-path` 2.7.0. This is vulnerable to CVE-2023-1370 and CVE-2023-51074. This also effects the `json-path` version used by Calcite 1.32 in the `flink-table-calcite-bridge` module.
Newer versions of Calcite update to newer versions of `json-path`. However, updating Calcite to the latest version ([FLINK-36602](https://issues.apache.org/jira/browse/FLINK-36602)) is not straightforward and involves changes to the SQL parsing logic. Following [discussion](https://lists.apache.org/thread/7ogwvj5z3o176dw95145dzvlolrkyps4) on the dev mailing list, an incremental Calcite upgrade process is preferred. Therefore, this PR simply patches the transitive dependency. 
- Upgrade the `com.jayway.jsonpath:json-path` version used in `flink-table` from `2.7.0` to …

[FLINK-33571][table] Backport json-path upgrades to deal with CVE

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecRank.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/ExecNodeMetadataUtil.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/batch/RankBatchRestoreTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/common/RankTestPrograms.java
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-rank_1/rank-2-test/plan/rank-2-test.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-rank_1/rank-n-test/plan/rank-n-test.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-rank_1/rank-test-append-fast-strategy/plan/rank-test-append-fast-strategy.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-rank_1/rank-test-update-fast-strategy/plan/rank-test-update-fast-strategy.json

* Adds Compiled Plan annotations to BatchExecRank.

[FLINK-36048] Add CompiledPlan annotations to BatchExecRank

---

flink-table/flink-table-code-splitter/src/main/java/org/apache/flink/table/codesplit/DeclarationRewriter.java
flink-table/flink-table-code-splitter/src/main/java/org/apache/flink/table/codesplit/FunctionSplitter.java
flink-table/flink-table-code-splitter/src/test/resources/splitter/code/TestSplitJavaCode.java
flink-table/flink-table-code-splitter/src/test/resources/splitter/expected/TestSplitJavaCode.java

This pull request aims to split constructor of generated code if it is too large to be compiled.
- Override visitConstructorDeclaration to split it into multiple void functions.
This change is already covered by existing tests, such as *org.apache.flink.table.codesplit.JavaCodeSplitterTest#testSplitJavaCode*. …

[FLINK-35334][flink-table] Split constructor of generated code if it is too large.

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecLookupJoin.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/ExecNodeMetadataUtil.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/batch/LookupJoinBatchRestoreTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/common/LookupJoinTestPrograms.java
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-lookup-join_1/lookup-join-filter-pushdown/plan/lookup-join-filter-pushdown.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-lookup-join_1/lookup-join-left-join/plan/lookup-join-left-join.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-lookup-join_1/lookup-join-pre-filter/plan/lookup-join-pre-filter.json

* Adds Compiled Plan annotations to BatchExecLookupJoin.

[FLINK-36718] Add CompiledPlan annotations to BatchExecLookupJoin

---

docs/layouts/shortcodes/generated/kubernetes_config_configuration.html
flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/planner/utils/TableSchemaUtils.java
flink-kubernetes/src/main/java/org/apache/flink/kubernetes/configuration/KubernetesConfigOptions.java

[hotfix][javadocs] Remove duplicated word 'the' in Javadocs

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/annotation/ArgumentHint.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/annotation/ArgumentTrait.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/annotation/DataTypeHint.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/annotation/FunctionHint.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/annotation/StateHint.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/FunctionKind.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/ProcessTableFunction.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/TableFunction.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/TableSemantics.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/BaseMappingExtractor.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/FunctionTemplate.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/extraction/TypeInferenceExtractorTest.java

Adds the initial interfaces of `ProcessTableFunction` and `StateHint` mentioned in FLIP-440 to the code base. This is a requirement to continue with the `TypeInferenceExtractor` extractor work. 
- Introduce `ProcessTableFunction` and `StateHint`
- Add `FunctionHint.state()`
- Add `TableSementics` for powering the context of PTFs
- …

[FLINK-36705] Add initial ProcessTableFunction class and annotations

---

flink-python/pyflink/table/table_environment.py
flink-python/pyflink/table/tests/test_table_environment_api.py
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/TableEnvironment.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java
flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/api/TableEnvironmentTest.java

Support ignoreIfExists for createTable. Works exactly the same way for other resources, like createFunction. Similar to SQL's `IF NOT EXISTS`.
- Added one more signature for TableEnvironment's createTable supporting ignoreIfExists
- Added testCreateTableIfNotExistsFromDescriptor
- Added test that validates that running createTable, with ignoreIfExists set to true, for an existing table leads to a no op. Also checks it doing the same ignoreIfExists set to false throws an exception. …

[FLINK-36809][table] Support ignoreIfExists param for createTable

---

flink-filesystems/flink-s3-fs-base/pom.xml
flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE
flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE
flink-yarn/pom.xml

The current version of `aws-java-sdk-core`, used in the `flink-s3-fs-base` module, has a high severity vulnerability ([CVE-2024-21634](https://nvd.nist.gov/vuln/detail/CVE-2024-21634)).
To address this we need to update to version 1.12.773 or higher, 1.12.779 is the current latest version.
Update the `aws-java-sdk-core` version used in `flink-s3-fs-base` to 1.12.779. 
This change is already covered by existing tests in the `flink-s3-fs-base` module. …

[FLINK-36643][filesystems] Update aws-java-sdk-core to 1.12.779

---

flink-filesystems/flink-s3-fs-base/pom.xml
flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE
flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE
flink-yarn/pom.xml

This is backport of #25600. 
The current version of `aws-java-sdk-core`, used in the `flink-s3-fs-base` module, has a high severity vulnerability ([CVE-2024-21634](https://nvd.nist.gov/vuln/detail/CVE-2024-21634)).
To address this we need to update to version 1.12.773 or higher, 1.12.779 is the current latest version.
Update the `aws-java-sdk-core` version used in `flink-s3-fs-base` to 1.12.779. 
This change is already covered by existing tests in the `flink-s3-fs-base` module. …

[FLINK-36643][filesystems] Update aws-java-sdk-core to 1.12.779 [1.20]

---

flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/FileExecutionGraphInfoStore.java
flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/MemoryExecutionGraphInfoStore.java
flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/ClusterEntrypoint.java

This fixes the race-condition of writing to a closed file in the cluster shutdown is triggered 
- removing the shutdown hook from `ExecutionGraphInfoStore` and waiting for the `ClusterEntrypoint` ( which holds an instance of  `ExecutionGraphInfoStore` ) to close it …

[FLINK-36194][Runtime] Handle the Graceful close of ExecutionGraphInfoStore from ClusterEntrypoint

---

docs/content.zh/docs/dev/table/sql/queries/window-agg.md
docs/content.zh/docs/dev/table/sql/queries/window-topn.md
docs/content.zh/docs/dev/table/sql/queries/window-tvf.md
docs/content/docs/dev/table/sql/queries/window-agg.md
docs/content/docs/dev/table/sql/queries/window-topn.md
docs/content/docs/dev/table/sql/queries/window-tvf.md
flink-table/flink-sql-parser/src/main/codegen/templates/Parser.jj
flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/FunctionITCase.java
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/WindowTableFunctionITCase.scala

The PR ports feature from Calcite 1.37 https://issues.apache.org/jira/browse/CALCITE-6254
Some existing tests were changed (`TABLE` wrapper was removed for some tests for windows also one more test was added to `flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/FunctionITCase.java`)
- Does …

[FLINK-36824][table] Backport from Calcite 1.37.0 support table function calls in FROM clause without TABLE() wrapper

---

flink-datastream-api/src/main/java/org/apache/flink/datastream/api/ExecutionEnvironment.java
flink-datastream-api/src/main/java/org/apache/flink/datastream/api/context/TaskInfo.java
flink-datastream-api/src/main/java/org/apache/flink/datastream/api/function/OneInputStreamProcessFunction.java
flink-datastream-api/src/main/java/org/apache/flink/datastream/api/function/ProcessFunction.java
flink-datastream-api/src/main/java/org/apache/flink/datastream/api/function/TwoInputBroadcastStreamProcessFunction.java
flink-datastream-api/src/main/java/org/apache/flink/datastream/api/function/TwoInputNonBroadcastStreamProcessFunction.java
flink-datastream-api/src/main/java/org/apache/flink/datastream/api/function/TwoOutputStreamProcessFunction.java
flink-datastream/src/main/java/org/apache/flink/datastream/impl/ExecutionEnvironmentImpl.java
flink-datastream/src/main/java/org/apache/flink/datastream/impl/context/DefaultRuntimeContext.java
flink-datastream/src/main/java/org/apache/flink/datastream/impl/context/DefaultTaskInfo.java
flink-datastream/src/main/java/org/apache/flink/datastream/impl/operators/ProcessOperator.java
flink-datastream/src/main/java/org/apache/flink/datastream/impl/operators/TwoInputBroadcastProcessOperator.java
flink-datastream/src/main/java/org/apache/flink/datastream/impl/operators/TwoInputNonBroadcastProcessOperator.java
flink-datastream/src/main/java/org/apache/flink/datastream/impl/operators/TwoOutputProcessOperator.java
flink-datastream/src/test/java/org/apache/flink/datastream/impl/context/DefaultNonPartitionedContextTest.java
flink-datastream/src/test/java/org/apache/flink/datastream/impl/context/DefaultTaskInfoTest.java
flink-datastream/src/test/java/org/apache/flink/datastream/impl/context/DefaultTwoOutputNonPartitionedContextTest.java
flink-datastream/src/test/java/org/apache/flink/datastream/impl/functions/ProcessFunctionTest.java

Fix series bugs of DSv2.
1. The DSv2 org.apache.flink.datastream.api.ExecutionEnvironment#fromSource method return a 
NonKeyedPartitionStream, which does not allow users to set source configurations, such as operator name or parallelism.
2. The org.apache.flink.datastream.api.context.TaskInfo lack subtaskIndex and attemptNumber.
3. The open and close methods of org.apache.flink.datastream.api.function.ProcessFunction are not being called.
4. The open method of org.apache.flink.datastream.api.function.ProcessFunction lacks relevant information, such as the current TaskInfo.
- Make ExecutionEnvironment#fromSource return ProcessConfigurableAndNonKeyedPartitionStream
- Introduce subtask index and attempt id in TaskInfo for DSv2
- Open and close user function in DSv2 ProcessOperator
- …

[FLINK-36815][API] Fix series bugs of DSv2

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlCreateTableConverter.java
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/TableSinkTest.xml
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/TableSinkTest.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/TableSinkITCase.scala

When `SqlOrderBy` and `SqlSelect` are validated together, `SqlSelect` gets rewritten and updated in place (as seen in `SqlValidatorImpl#performUnconditionalRewrites`). 
This bug was caused by validation of `SqlOrderBy` and `SqlSelect` multi times, which led to `SqlSelect` being incorrectly updated to a pattern like:
```
SELECT `V`.`b`, `V`.`c`, `V`.`d`
FROM (VALUES ROW(1, 1, 2, 'd1'),
ROW(2, 2, 4, 'd2')) AS `V` (`a`, `b`, `c`, `d`)
ORDER BY `V`.`a`
ORDER BY `a`
``` 
This pull request aims to prevent the multiple validations of `SqlOrderBy` and `SqlSelect`.
- *Update logic in SqlCreateTableConverter to avoid validating SqlOrderBy and SqlSelect multi times*
- *Add tests to verify this bug*
Some tests in batch mode are added to verify this fix. (Sort in streaming mode is not supported yet). …

[FLINK-36783][table-planner] Use validated SqlNode in 'asQuery' while converting SqlCreateTableAS to CreateTableASOperation

---

flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/sink/compactor/CompactorOperatorTest.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/GlobalCommitterOperator.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/StandardSinkTopologies.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/SupportsPreCommitTopology.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraphGenerator.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/transformations/GlobalCommitterTransform.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManager.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManagerImpl.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollector.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/translators/GlobalCommitterTransformationTranslator.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/translators/SinkTransformationTranslator.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/connector/sink2/CommittableSummaryAssert.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/connector/sink2/CommittableWithLineageAssert.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/connector/sink2/GlobalCommitterOperatorTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/connector/sink2/SinkV2Assertions.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SinkTransformationTranslatorITCaseBase.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SinkV1TransformationTranslatorITCase.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SinkV2TransformationTranslatorDeprecatedITCase.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/SinkV2TransformationTranslatorITCase.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperatorTestBase.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkTestUtil.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperatorTestBase.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/TestSinkV2.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManagerImplTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorSerializerTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/SubtaskCommittableManagerTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/deprecated/TestSinkV2.java

Backport of #25456 with some adjustments in `GlobalCommitterOperater` (main doesn't have `GlobalCommitter` code anymore).

[FLINK-36379] Improve (Global)Committer with UC disabled [1.20]

---

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateBackendV2Test.java

Currently there is an issue in the forst db core, where the background cannot properly quit when db close. Thus we manually join those threads in backend side. This is a temporary solution until the forst db fix the bug.
- Set background threads count to 0 when quit.
- A minor hotfix for Forst tests which could verify this change. …

[FLINK-36838][state] Join background threads when ForSt state backend quit

---

flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/expressions/ExpressionSerializationTest.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/SqlCallSyntax.java

For Table API, there are 5 time-related functions that can't be called right now. This maps these the function calls for CURRENT_DATE, LOCALTIMESTAMP, LOCALTIME, CURRENT_TIMESTAMP, CURRENT_TIME currectly. These function do not support parenthesis when being called.
- Add NO_PARENTHESIS call syntax
- Use it for CURRENT_DATE, LOCALTIMESTAMP, LOCALTIME, CURRENT_TIMESTAMP, CURRENT_TIME 
- Update serialization tests
- Added serialization tests to make sure the table api call get's mapped to the proper SQL Function …

[FLINK-36840][table] Add correct call syntax for functions without ()

---

flink-filesystems/flink-s3-fs-base/pom.xml
flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE
flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE
flink-yarn/pom.xml

This is backport of #25600. 
The current version of `aws-java-sdk-core`, used in the `flink-s3-fs-base` module, has a high severity vulnerability ([CVE-2024-21634](https://nvd.nist.gov/vuln/detail/CVE-2024-21634)).
To address this we need to update to version 1.12.773 or higher, 1.12.779 is the current latest version.
Update the `aws-java-sdk-core` version used in `flink-s3-fs-base` to 1.12.779. 
This change is already covered by existing tests in the `flink-s3-fs-base` module. …

[FLINK-36643][filesystems] Update aws-java-sdk-core to 1.12.779 [1.19]

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/connectors/DynamicSourceUtils.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/reuse/ScanReuser.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/reuse/ScanReuserUtils.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/optimize/ScanReuseTest.java
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/optimize/ScanReuseTest.xml

Sort the metadata keys when reusing source.
- *Sort metadata keys in `ScanReuser`*
- *Add tests to verity this pr*
New tests are added to verify this fix.

[FLINK-36688][table-planner] Sort metadata keys when reusing source

---

flink-runtime/pom.xml
flink-runtime/src/main/resources/META-INF/NOTICE

Addresses [CVE-2024-36114](https://nvd.nist.gov/vuln/detail/CVE-2024-36114) which concerns a vulnerability in the aircompressor library.
This is a backport of #25567.
Upgrade the `io.airlift:aircompressor` version used by flink-runtime from `0.21` to `0.27`.
This change is already covered by existing tests in the `flink-runtime` module.

[FLINK-36593][runtime] Upgrade io.airlift:aircompressor to 0.27 [1.20]

---

flink-dist/src/main/resources/META-INF/NOTICE
flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE
flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE
flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE
flink-formats/flink-sql-avro-confluent-registry/src/main/resources/META-INF/NOTICE
pom.xml

Bump snappy-java from 1.1.10.4 to 1.1.10.7
The current version has vulnerability in the dependant package, bumping it to the latest version will remediate.
Vulnerabilities from dependencies:
[CVE-2024-23454](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-23454)
[CVE-2022-26612](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-26612)
Package details:
https://mvnrepository.com/artifact/org.xerial.snappy/snappy-java/1.1.10.7 …

[FLINK-36537] Bump snappy-java from 1.1.10.4 to 1.1.10.7

---

docs/layouts/shortcodes/generated/common_miscellaneous_section.html
flink-core/src/main/java/org/apache/flink/configuration/SinkOptions.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/GlobalCommitterOperator.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManager.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManagerImpl.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollector.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/SubtaskCommittableManager.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/connector/sink2/GlobalCommitterOperatorTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperatorTestBase.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManagerImplTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorSerializerTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/deprecated/TestSinkV2.java

Backport of #25547 without last commit that deprecates API and with some adjustments in GlobalCommitterOperater (main doesn't have GlobalCommitter code anymore).

[FLINK-36455] Sinks retry synchronously [1.20]

---

docs/layouts/shortcodes/generated/common_miscellaneous_section.html
flink-core/src/main/java/org/apache/flink/configuration/SinkOptions.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/GlobalCommitterOperator.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManager.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManagerImpl.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollector.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/SubtaskCommittableManager.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/connector/sink2/GlobalCommitterOperatorTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperatorTestBase.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManagerImplTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorSerializerTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/deprecated/TestSinkV2.java

Unchanged backport of #25661 based on #25746 (needs to be reviewed/merged first).

[FLINK-36455] Sinks retry synchronously [1.19]

---

flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/expressions/ExpressionSerializationTest.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/SqlCallSyntax.java

Backport of https://github.com/apache/flink/pull/25733
For Table API, there are 5 time-related functions that can't be called right now. This maps these the function calls for CURRENT_DATE, LOCALTIMESTAMP, LOCALTIME, CURRENT_TIMESTAMP, CURRENT_TIME currectly. These function do not support parenthesis when being called.
- Add NO_PARENTHESIS call syntax
- Use it for CURRENT_DATE, LOCALTIMESTAMP, LOCALTIME, CURRENT_TIMESTAMP, CURRENT_TIME 
- Update serialization tests
- Added serialization tests to make sure the table api call get's mapped to the proper SQL Function
- …

[FLINK-36840][table] Add correct call syntax for functions without `()`

---

flink-table/flink-table-calcite-bridge/pom.xml

There is a high severity CVE ([CVE-2023-1370](https://nvd.nist.gov/vuln/detail/CVE-2023-1370)) in the json-path version used by the Calcite library (currently version 1.34) used in the `flink-table-calcite-bridge` module.
Newer versions of Calcite update to newer versions of `json-path`. However, updating Calcite to the latest 1.38 version ([FLINK-36602](https://issues.apache.org/jira/browse/FLINK-36602)) is not straightforward and involves changes to the SQL parsing logic. Following [discussion](https://lists.apache.org/thread/7ogwvj5z3o176dw95145dzvlolrkyps4) on the dev mailing list, an incremental Calcite upgrade process is preferred. Therefore, this PR simply patches the transitive dependency.
Note: The `flink-table-runtime` directly depends on `json-path` and is also effected by this …

[FLINK-36830][table] Override json-path version in Calcite to deal with CVE

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/EpochManager.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/EpochManagerTest.java

Currently, we use `EpochManager` to manage the watermark in async state processing. We found an issue when a watermark reached and no further input reach for a while, the epoch/watermark will be triggered twice. Current PR fix this.
- Stricter conditions to ensure no recursive call of triggering.
This change modified test `EpochManagerTest` that can verify this. …

[FLINK-36859][Runtime] Fix wrong epoch/watermark firing in async state processing

---

flink-core/src/main/java/org/apache/flink/api/java/typeutils/TypeExtractor.java
flink-core/src/test/java/org/apache/flink/api/java/typeutils/PojoTypeExtractionTest.java

At the moment Flink not detecting Lombok generated setter correctly. For example `boolean isHealthy` field is generating `boolean isHealthy()` function and not `boolean isIsHealthy()`. In this PR I've added support for that.
Fix TypeSerializer to detect lombok boolean with `is` prefix.
Modified existing automated test.
- Does this pull request introduce a new feature?no …

[FLINK-36612][core] Fix TypeSerializer to detect lombok boolean with is prefix

---

flink-runtime/src/main/java/org/apache/flink/streaming/api/datastream/DataStream.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectSinkFunction.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectSinkOperatorFactory.java
flink-tests/src/test/java/org/apache/flink/api/datastream/DataStreamCollectTestITCase.java

`CollectSinkOperatorFactory` is not respecting `collect-sink.batch-size.max` and `collect-sink.socket-timeout` configuration but only the default value used. As a result state reading can blow up. In this PR I've changed `CollectSinkOperatorFactory` to read the mentioned 2 parameters.
`CollectSinkOperatorFactory` is now reading the mentioned 2 parameters.
Trivial change + manual with state reading.
- Does …

[FLINK-36856][runtime] CollectSinkOperatorFactory batch size and socket timeout config fix

---

flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/testsuites/SinkTestSuiteBase.java
flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/testsuites/SourceTestSuiteBase.java
flink-test-utils-parent/flink-connector-test-utils/src/test/java/org/apache/flink/connector/testframe/testsuites/DataStreamSinkV2ExternalContextImpl.java
flink-test-utils-parent/flink-connector-test-utils/src/test/java/org/apache/flink/connector/testframe/testsuites/SinkTestSuiteBaseTest.java

Fix test cases
- Set operatorUid to CollectStreamSink in TestBase
- Make operatorUid fixed to recover from state
Test cases that implemented in kafka connector

[FLINK-36845][flink-connector-test-utils] Set operatorUid to CollectStreamSink in SinkTestSuiteBase/SourceTestSuiteBase.

---

docs/content.zh/docs/flinkDev/ide_setup.md
docs/content/docs/flinkDev/ide_setup.md

After  [https://github.com/apache/flink/pull/25714](https://github.com/apache/flink/pull/25714) the level of google-java-format required changed. The documentation refers to this level in the IDE setup. This is a hotfix to amend the documentation so it refers to the correct version in line with 25714.

[hotfix] [docs] Fix the google-java-format level in docs in line with PR 25714

---

flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/runner/DefaultDispatcherRunner.java
flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedLeaderService.java
flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMasterServiceLeadershipRunner.java
flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElection.java
flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionService.java
flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/LeaderElection.java
flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/LeaderElectionService.java
flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/StandaloneLeaderElection.java
flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManagerServiceImpl.java
flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/WebMonitorEndpoint.java
flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/runner/DefaultDispatcherRunnerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedHaServicesTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionServiceTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/LeaderElectionTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/StandaloneLeaderElectionTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingContender.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingGenericLeaderContender.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingLeaderElection.java
flink-runtime/src/test/java/org/apache/flink/runtime/rest/util/DocumentingDispatcherRestEndpoint.java

See reasoning in [FLINK-36451 comment](https://issues.apache.org/jira/browse/FLINK-36451?focusedCommentId=17895936&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17895936)
* Adds `runAsLeader` method that executes callbacks on the leadership main thread
* Replaces `hasLeadership` calls with `runAsLeader`
* Adds confirmLeadershipAsLeader which runs the `confirmLeadership` method on the `leaderOperationExecutor`
* Adds unit tests
* Rewrites `hasLeadership` tests in unit test classes …

[FLINK-36451][runtime] Replaces LeaderElection#hasLeadership with LeaderElection#runAsLeader

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateRequestType.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/AbstractListState.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/adaptor/CompleteStateIterator.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/adaptor/ListStateAdaptor.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/internal/InternalAggregatingState.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/internal/InternalAppendingState.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/internal/InternalReducingState.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/internal/InternalStateAccessible.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/ttl/TtlListState.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBMultiRawMergePutRequest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBRawGetRequest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStListState.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateRequestClassifier.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateRequestType.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStListStateTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateTestBase.java

There is a internal state interface hierarchy for state v2, which is pretty much like the one for state v1. Currently the `InternalListState` does not extend from `InternalMergingState` for convenience of class type parameter signature. However, the table implementation depends on the inheritance, so this PR adds it back.
- Extract a `InternalStateAccessible` interface from `InternalAppendingState`
- Make `InternalListState` inherit `InternalMergingState`
- Implement necessary methods from `InternalMergingState` for existing List States.
- Also, a hotfix fixing the state adaptor
This change added tests `ForStListStateTest`.
- …

[FLINK-36860][State/v2] Make internal list state inherit the internal merging state

---

flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/runner/DefaultDispatcherRunner.java
flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedLeaderService.java
flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMasterServiceLeadershipRunner.java
flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElection.java
flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionService.java
flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/LeaderElection.java
flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/LeaderElectionService.java
flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/StandaloneLeaderElection.java
flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManagerServiceImpl.java
flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/WebMonitorEndpoint.java
flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/runner/DefaultDispatcherRunnerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedHaServicesTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionServiceTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/LeaderElectionTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/StandaloneLeaderElectionTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingContender.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingGenericLeaderContender.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingLeaderElection.java
flink-runtime/src/test/java/org/apache/flink/runtime/rest/util/DocumentingDispatcherRestEndpoint.java

This is the 1.20 backport of parent PR #25679

[BP-1.20][FLINK-36451][runtime] Replaces LeaderElection#hasLeadership with LeaderElection#runAsLeader

---

docs/content.zh/docs/dev/datastream/sources.md
docs/content/docs/dev/datastream/sources.md

Examples on documentation page [Data Sources](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/datastream/sources/) have been using the APIs that do not exist anymore in Flink 2.0-preview.
- FixedSizeSplitFetcherManager uses a SplitFetcherManager constructor that accepts elements queue and was removed in Flink 2.0-preview https://issues.apache.org/jira/browse/FLINK-36245
- FixedFetcherSizeSourceReader uses  uses a SourceReaderBase constructor that accepts elements queue and was removed in Flink 2.0-preview https://issues.apache.org/jira/browse/FLINK-36245
- FixedFetcherSizeSourceReader uses getInteger method of Configuration that was removed in in Flink 2.0-preview https://issues.apache.org/jira/browse/FLINK-34082
- switch FixedSizeSplitFetcherManager, …

[FLINK-36745][docs] Make FixedSizeSplitFetcherManager and FixedFetcherSizeSourceReader examples match Flink 2.0-preview API

---

flink-runtime/src/main/java/org/apache/flink/runtime/state/AsyncKeyedStateBackend.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/DefaultKeyedStateStore.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/adaptor/AsyncKeyedStateBackendAdaptor.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamOperatorStateHandler.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionControllerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendTestUtils.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractKeyedStateTestBase.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AsyncKeyedStateBackendAdaptorTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/StateBackendTestV2Base.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/StreamingRuntimeContextTest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java

Support `getOrCreateKeyedState()` and  `isSafeToReuseKVState()` for AsyncKeyedStateBackend.
- Add `getOrCreateKeyedState()` and `isSafeToReuseKVState()`  to `AsyncKeyedStateBackend`
- Implement `getOrCreateKeyedState()` and `isSafeToReuseKVState()`  in subclasses.
- `AbstractKeyedStateTestBase` …

[FLINK-34974][state] Support getOrCreateKeyedState for AsyncKeyedStateBackend

---

flink-dist/src/main/resources/META-INF/NOTICE
flink-state-backends/flink-statebackend-forst/pom.xml
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFileStatus.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystem.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/StringifiedForStFileSystem.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStResourceContainerTest.java

Currently, the ForSt core use `ForStFlinkFileSystem` via JNI to manipulate files. However, the parameter and return value contains `Path`, which introduces redundant JNI call to convert from/to std::string. This PR provides methods with string directly.
- Introduce proxy classes with string input and output. 
- Bump ForSt version to 0.1.4-beta which uses the stringified methods.
- The S3 …

[FLINK-36868][State] Provide file system methods with string parameters for ForSt JNI

---

docs/content.zh/docs/dev/configuration/gradle.md
docs/content.zh/docs/dev/configuration/maven.md
docs/content.zh/docs/flinkDev/building.md
docs/content/docs/dev/configuration/maven.md
docs/content/docs/flinkDev/building.md

This is a follow up for the commit under https://github.com/apache/flink/pull/25775

[hotfix] Remove requiremenet for java 8 in docs

---

flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/runner/DefaultDispatcherRunner.java
flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedLeaderService.java
flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMasterServiceLeadershipRunner.java
flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElection.java
flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionService.java
flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/LeaderElection.java
flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/LeaderElectionService.java
flink-runtime/src/main/java/org/apache/flink/runtime/leaderelection/StandaloneLeaderElection.java
flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManagerServiceImpl.java
flink-runtime/src/main/java/org/apache/flink/runtime/webmonitor/WebMonitorEndpoint.java
flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/runner/DefaultDispatcherRunnerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedHaServicesTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionServiceTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/DefaultLeaderElectionTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/LeaderElectionTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/StandaloneLeaderElectionTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingContender.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingGenericLeaderContender.java
flink-runtime/src/test/java/org/apache/flink/runtime/leaderelection/TestingLeaderElection.java
flink-runtime/src/test/java/org/apache/flink/runtime/rest/util/DocumentingDispatcherRestEndpoint.java

This is the 1.19 backport of parent PR https://github.com/apache/flink/pull/25679

[BP-1.19][FLINK-36451][runtime] Replaces LeaderElection#hasLeadership with LeaderElection#runAsLeader

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/InternalTimeServiceManager.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/InternalTimeServiceManagerImpl.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/InternalTimerServiceAsyncImpl.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/InternalTimerServiceImpl.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionInternalTimeServiceManager.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/InternalTimerServiceAsyncImplTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/MailboxWatermarkProcessorTest.java

This PR makes timers completed before emitting watermark.
- Let `advanceWatermark` return `CompletableFuture`.
- `InternalTimerServiceAsyncImplTest#testSameKeyEventTimerFireOrder`

[FLINK-36875][runtime] Complete timer before emitting watermark

---

flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/expressions/ExpressionSerializationTest.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/SqlCallSyntax.java

While translation of `trim()` to SQL parenthesis are missed
`SqlCallSyntax`
`ExpressionSerializationTest.java`

[FLINK-36896][table] Table API trim expression incorrectly translated to SQL

---

.gitignore

If you use VS code on the Flink folder then it generates a folder called .vscode. This folder should not be checked into Flink. At some later stage we may want to enforce some vscode formatting or the like. But for now we should make sure it dos not get checked into Git.

[hotfix] [gitignore] ignore .vscode folder in .gitignore

---

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/AbstractCompositeBuffer.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/FullyFilledBuffer.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/BufferResponseDecoder.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/CreditBasedPartitionRequestClientHandler.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/NettyMessage.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/PartitionRequestQueue.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PartitionedFileReader.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartition.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionReadScheduler.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeSubpartitionReader.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/LocalInputChannel.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateFactory.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/CreditBasedPartitionRequestClientHandlerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyMessageClientDecoderDelegateTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/netty/NettyMessageClientSideSerializationTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/DataBufferTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PartitionedFileWriteReadTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionReadSchedulerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartitionTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/SortMergeSubpartitionReaderTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateTest.java

https://issues.apache.org/jira/browse/FLINK-36072
Optimizing the Overhead of the Network Layer in Adaptive Execution Scenarios
- On the downstream side, enable a single input gate to support a single input channel consuming multiple subpartitions.
- On the upstream side, enable sort-merge shuffle could use single partition reader to read multiple subpartitions
- On the upstream side, enable sort-merge shuffle supports accumulating small buffers to reduce network overhead.
This change added tests and can be verified such as CreditBasedPartitionRequestClientHandlerTest.
- The …

[FLINK-36072][runtime] Sort-merge shuffle supports accumulating small buffers to reduce network overhead.

---

flink-core/src/main/java/org/apache/flink/api/java/typeutils/TypeExtractor.java
flink-test-utils-parent/flink-test-utils/src/test/java/org/apache/flink/types/PojoTestUtilsTest.java

Fix NPE reported in [FLINK-35887](https://issues.apache.org/jira/browse/FLINK-35887).
Add null checking for the result of getSuperclass on an interface.
`PojoTestUtilsTest#testPojoTypeInfoOnInterface `
- If yes, how is the feature documented? ()

[BP-1.19][FLINK-35887][core] Fix NPE in TypeExtractor where getSuperclass from an interface returns null

---

docs/content.zh/docs/ops/production_ready.md
docs/content/docs/ops/production_ready.md

Add a note section in `Production Readiness Checklist` on flink security 
just a doc update 
validate markdown file is rendered properly
N/A

[FLINK-36889] Mention locking down a Flink cluster in the 'Production Readiness Checklist'

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/utils/DateTimeUtils.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/FloorCeilCallGen.scala
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/TimeFunctionsITCase.java

We need a fix for both SECOND and MINUTE.
The following query doesn't work:
```
SELECT
  FLOOR(
      CAST(TIMESTAMP '2024-04-25 17:19:42.654' AS TIMESTAMP_LTZ(3))
  TO MINUTE) 
```
These two queries work:
```
SELECT
  FLOOR(
      CAST(TIMESTAMP '2024-04-25 17:19:42.654' AS TIMESTAMP_LTZ(3))
  TO HOUR) 
```
```
SELECT
  FLOOR(
      TIMESTAMP '2024-04-25 17:19:42.654'
  TO MINUTE) 
```
Stack trace for the first not working query from above:
```
Caused by: io.confluent.flink.table.utils.CleanedException: org.codehaus.commons.compiler.CompileException: Line 41, Column 69: No applicable constructor/method found for actual parameters "org.apache.flink.table.data.TimestampData, org.apache.flink.table.data.TimestampData"; candidates are: "public static long …
```

[FLINK-35241][table]Support SQL FLOOR and CEIL functions with SECOND and MINUTE for TIMESTAMP_TLZ

---

flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/util/asyncprocessing/AsyncKeyedMultiInputStreamOperatorTestHarness.java
flink-runtime/src/test/java/org/apache/flink/streaming/util/asyncprocessing/AsyncKeyedOneInputStreamOperatorTestHarness.java
flink-runtime/src/test/java/org/apache/flink/streaming/util/asyncprocessing/AsyncKeyedTwoInputStreamOperatorTestHarness.java
flink-runtime/src/test/java/org/apache/flink/streaming/util/asyncprocessing/AsyncProcessingTestUtil.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/AbstractAsyncStateStreamOperatorV2Test.java

This PR introduces some test harnesses for async state processing operators.
- Add `AsyncKeyedMultiInputStreamOperatorTestHarness`
- Add `AsyncKeyedOneInputStreamOperatorTestHarness`
- Add `AsyncKeyedTwoInputStreamOperatorTestHarness`
- Make `AbstractAsyncStateStreamOperatorTest`/`AbstractAsyncStateStreamOperatorV2Test` use those test harnesses.
- `AbstractAsyncStateStreamOperatorTest`
- `AbstractAsyncStateStreamOperatorV2Test`
- The public …

[FLINK-35904][test] Test harness for async state processing operators

---

flink-table/flink-table-api-scala/src/test/scala/org/apache/flink/table/types/extraction/TypeInferenceExtractorScalaTest.scala
flink-table/flink-table-common/src/main/java/org/apache/flink/table/annotation/ArgumentTrait.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/ProcessTableFunction.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/UserDefinedFunctionHelper.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/BaseMappingExtractor.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/DataTypeExtractor.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/ExtractionUtils.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/FunctionArgumentTemplate.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/FunctionMappingExtractor.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/FunctionResultTemplate.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/FunctionSignatureTemplate.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/FunctionTemplate.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/ProcedureMappingExtractor.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/TypeInferenceExtractor.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/StaticArgument.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/StaticArgumentTrait.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/TypeInference.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/extraction/DataTypeExtractorTest.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/extraction/ExtractionUtilsTest.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/extraction/TypeInferenceExtractorTest.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/inference/TypeInferenceOperandChecker.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/PlannerCallProcedureOperation.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlNodeToCallOperationTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/table/ValuesITCase.java
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/utils/userDefinedScalarFunctions.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/SortAggITCase.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/utils/UserDefinedFunctionTestUtils.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/CountAggFunction.scala

This refactors the TypeInferenceExtractor to support ProcessTableFunction as defined in FLIP-440.
The extractor tries its best to extract list of `StaticArgument` of both scalar and table kind. Table kind can be both typed (structured type) or untyped (Row). `@StateHint` allows defining state entries.
Some simple examples:
```
public class StateProcessTableFunction extends ProcessTableFunction<Integer> {
public void eval(@StateHint MyState s, Integer i) {}
}
public class NamedStateProcessTableFunction extends ProcessTableFunction<Integer> {
public void eval(
@StateHint(name = "myState") MyState s, @ArgumentHint(name = "myArg") Integer i) {}
}
public class MultiStateProcessTableFunction extends ProcessTableFunction<Integer> {
public void eval(@StateHint MyFirstState s1, @StateHint …
```

[FLINK-36706] Refactor TypeInferenceExtractor for PTFs

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/EpochManager.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/InternalTimeServiceManager.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/InternalTimeServiceManagerImpl.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/InternalTimerServiceAsyncImpl.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/InternalTimerServiceImpl.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionInternalTimeServiceManager.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionControllerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/EpochManagerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/InternalTimerServiceAsyncImplTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/MailboxWatermarkProcessorTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/AbstractAsyncStateStreamOperatorV2Test.java

We have introduced the `EpochManager` to handle the watermark during async state processing. The inputs are divided into several epochs where a action is attached and triggered after all the inputs finished their async processing. However, the action itself may trigger more async procedures which blocks some synchronous action. Thus this PR introduces two types of action, one is for triggered right after all the inputs finished, while another is for being triggered after all the async processing including the ones from the action finished.
This is a complete solution & abstraction of watermark handling. I'll revert some change from FLINK-36875, removing the unnecessary use of `CompletableFuture`.
- Remove `CompletableFuture` in signatures of `advanceWatermark`.
- Introduce `triggerAction` …

[FLINK-36928][Runtime] Split the action of Epoch into two parts (trigger & final)

---

flink-table/flink-table-api-scala/src/test/scala/org/apache/flink/table/types/extraction/DataTypeExtractorScalaTest.scala

There is nothing wrong with current code if run it with maven
however scala's plugin of IntelliJIdea is not happy about it and constantly complaining if try to run scala tests from there (flink-table-planner module e.g `TableEnvironmentTest`)
Also if just open this class in IntelliJIdea it will highlight the error in this place
I tried to ask JetBrains to fix it however still not done (after about 2 years)
https://youtrack.jetbrains.com/issue/SCL-20679/Scala-plugin-becomes-broken-if-there-is-AssertJ-usage
DataTypeExtractorScalaTest.scala
The change is in tests …

[hotfix][tests] Use scala's instanceOf in DataTypeExtractorScalaTest

---

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/shuffle/TieredInternalShuffleMaster.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/TieredStorageMasterClient.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/NoOpMasterAgent.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/TierMasterAgent.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/remote/RemoteTierMasterAgent.java
flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/NettyShuffleMaster.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/remote/RemoteTierMasterAgentTest.java

*Tier master agent missing the number of subpartitions to record paritition metric in remote shuffle service.*
- *Expose `numSubpartitions` to `TierMasterAgent#addPartitionAndGetShuffleDescriptor`*

[FLINK-36934][network] Enrich numSubpartitions to TierMasterAgent#addPartitionAndGetShuffleDescriptor

---

docs/content.zh/docs/connectors/datastream/formats/parquet.md
docs/content.zh/docs/connectors/table/formats/avro-confluent.md
docs/content.zh/docs/connectors/table/formats/avro.md
docs/content.zh/docs/dev/datastream/fault-tolerance/serialization/schema_evolution.md
docs/content/docs/connectors/datastream/formats/parquet.md
docs/content/docs/connectors/table/formats/avro-confluent.md
docs/content/docs/connectors/table/formats/avro.md
flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/typeutils/AvroSerializerSnapshot.java
flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroRecordInputFormatTest.java
flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroSplittableInputFormatTest.java

Just correcting the url reference to access the Avro specification.

[hotfix][docs] Fix Apache Avro Specification Link.

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/AbstractAsyncStateStreamOperatorV2Test.java

We have rewrite the `processWatermark` in abstract operators for async state processing. The sub-classes need a proper hook for doing something right before the watermark processing and right after the watermark emit.
- Add `preProcessWatermark` and `postProcessWatermark` in abstract operators for async state processing.
- Added `testWatermarkHooks` in corresponding test classes. …

[FLINK-36938] Provide hooks before and after the watermark processing

---

docs/content.zh/docs/dev/python/table/table_environment.md
docs/content/docs/dev/python/table/table_environment.md
flink-python/docs/reference/pyflink.table/table_environment.rst
flink-python/pyflink/table/table_environment.py
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/TableEnvironment.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/TableEnvironmentTest.scala

FLIP-489 [1] adds missing dropTable/dropView methods to TableEnvironment
[1] https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=332499781
TableEnvironmentImpl.java
- The S3 file system connector: (yes)
- If yes, how is the feature documented? ( JavaDocs)

[FLINK-36919][table] Add missing dropTable/dropView methods to TableEnvironment

---

docs/layouts/shortcodes/generated/common_state_backends_section.html
docs/layouts/shortcodes/generated/state_backend_configuration.html
flink-core/src/main/java/org/apache/flink/api/dag/Transformation.java
flink-core/src/main/java/org/apache/flink/configuration/StateBackendOptions.java
flink-examples/flink-examples-streaming/pom.xml
flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/wordcount/WordCount.java
flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/wordcount/util/CLI.java
flink-examples/flink-examples-streaming/src/test/java/org/apache/flink/streaming/test/StreamingExamplesITCase.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/AggregatingStateDescriptor.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/ListStateDescriptor.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/MapStateDescriptor.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/ReducingStateDescriptor.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/StateDescriptor.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/ValueStateDescriptor.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/ttl/TtlStateFactory.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/datastream/KeyedStream.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/datastream/SingleOutputStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/datastream/WindowedStream.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamGroupedReduceAsyncStateOperator.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/transformations/ReduceTransformation.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/translators/ReduceTransformationTranslator.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/AggregationFunctionTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/StreamGroupedReduceAsyncStateOperatorTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/util/MockContext.java
flink-runtime/src/test/java/org/apache/flink/streaming/util/asyncprocessing/AsyncKeyedOneInputStreamOperatorTestHarness.java
flink-tests/src/test/java/org/apache/flink/test/completeness/TypeInfoTestCoverageTest.java

As first part of FLIP-488, this PR introduces `enableAsycState` in KeyedStream and its related interface classes. Also it provides a basic implementation of async reduce operator.
Please check each commit.
- Introduce `enableAsyncState` API
- Introduce serializer based state descriptor constructors
- Implement async reduce operator
- Introduce async state version of wordcount example
This PR adds a IT test on the wordcount example, which can be a IT test of new APIs and reduce operator. …

[FLINK-36944][DataStream/API] Introduce 'enableAsycState' in KeyedStream interfaces and implement reduce operator

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/AbstractAsyncStateStreamOperatorV2Test.java

Currently, the abstract operators will cache the current context, and the `getCurrentKey()` will return the key of this context. However, this context may not be the context of current processing callback. It is for the convenience of releasing record reference counting. This PR fixes that in case some user logic may call `getCurrentKey()` by returning the ground truth of context in `AEC` directly.
- Change the `getCurrentKey` in both two abstract operators. …

[FLINK-36949] Make getCurrentKey of async state operators return the ground truth

---

flink-runtime/src/main/java/org/apache/flink/runtime/deployment/ConsumedSubpartitionContext.java
flink-runtime/src/main/java/org/apache/flink/runtime/deployment/InputGateDeploymentDescriptor.java
flink-runtime/src/main/java/org/apache/flink/runtime/deployment/TaskDeploymentDescriptorFactory.java
flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/EdgeManagerBuildUtil.java
flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionVertexInputInfo.java
flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/IndexRangeUtil.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateFactory.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SsgNetworkMemoryCalculationUtils.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveBatchScheduler.java
flink-runtime/src/test/java/org/apache/flink/runtime/deployment/ConsumedSubpartitionContextTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/IndexRangeUtilTest.java

Currently, the ExecutionVertexInputInfo describes the task's input through a combination of a PartitionRange and a SubpartitionRange. However, in the case of skewed join optimization, we need to split a group of data corresponding to the specific key, which may result in a downstream task subscribing to multiple combinations of PartitionRanges and SubpartitionRanges.
Therefore, we need to modify the ExecutionVertexInputInfo to describe the input data as multiple combinations of PartitionRanges and SubpartitionRanges to meet the requirements of the aforementioned scenario and improve Flink's flexibility in describing the task's inputs.
- Modify the description of the input in ExecutionVertexInputInfo.
- Modify the connect function for edges.
- Modify the InputGate creation logic of the …

[FLINK-36575][runtime] ExecutionVertexInputInfo supports consuming subpartition groups

---

flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PartitionedFileReader.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PartitionedFileWriter.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/SortMergeResultPartition.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PartitionTestUtils.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PartitionedFileWriteReadTest.java

[FLINK-36959][runtime] Fix the logic for computing readable buffer offsets and sizes when including empty buffers.
[FLINK-36959][runtime] Fix the logic for computing readable buffer offsets and sizes when including empty buffers.
Added test testWriteAndReadWithEmptySubpartitionForMultipleSubpartitions. …

[FLINK-36959][runtime] Fix the logic for computing readable buffer offsets and sizes when including empty buffers.

---

flink-runtime/src/test/java/org/apache/flink/streaming/util/MultiInputStreamOperatorTestHarness.java
flink-runtime/src/test/java/org/apache/flink/streaming/util/asyncprocessing/AsyncKeyedMultiInputStreamOperatorTestHarness.java
flink-runtime/src/test/java/org/apache/flink/streaming/util/asyncprocessing/AsyncKeyedOneInputStreamOperatorTestHarness.java
flink-runtime/src/test/java/org/apache/flink/streaming/util/asyncprocessing/AsyncKeyedTwoInputStreamOperatorTestHarness.java
flink-runtime/src/test/java/org/apache/flink/streaming/util/asyncprocessing/AsyncProcessingTestUtil.java

Make the async test harness extend existing test harnesses.
- Make `AsyncKeyedOneInputStreamOperatorTestHarness` extend `OneInputStreamOperatorTestHarness`
- Make `AsyncKeyedTwoInputStreamOperatorTestHarness` extend `TwoInputStreamOperatorTestHarness`
- Make `AsyncKeyedMultiInputStreamOperatorTestHarness` extend `MultiInputStreamOperatorTestHarness`
- The S3 …

[FLINK-35904][test] Make async test harnesses extend existing harnesses

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/AsyncKeyedStateBackend.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/adaptor/AsyncKeyedStateBackendAdaptor.java

Within `asyncProcessWithKey`, the key/record context is switched to the one for asynchronous procedure then switched back. However we picked the wrong old context and switched back with the wrong one. This PR fixes that.
- The `asyncProcessWithKey` of both related operators. …

[FLINK-36963][Runtime] Fix wrong context maintain around `asyncProcessWithKey`

---

flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/IntermediateResult.java
flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/IntermediateResultInfo.java
flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/IntermediateResultPartition.java
flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/VertexInputInfoComputationUtils.java
flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/IntermediateDataSet.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/AbstractBlockingResultInfo.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveBatchScheduler.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveExecutionHandlerFactory.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/AllToAllBlockingResultInfo.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/BlockingResultInfo.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/DefaultAdaptiveExecutionHandler.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/DefaultVertexParallelismAndInputInfosDecider.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/OperatorsFinished.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/PointwiseBlockingResultInfo.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/StreamGraphOptimizationStrategy.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/StreamGraphOptimizer.java
flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/PartitionDescriptor.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/AdaptiveGraphManager.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/DefaultStreamGraphContext.java
flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/VertexInputInfoComputationUtilsTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveExecutionPlanSchedulingContextTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptivebatch/AllToAllBlockingResultInfoTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptivebatch/DefaultAdaptiveExecutionHandlerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptivebatch/DefaultVertexParallelismAndInputInfosDeciderTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptivebatch/StreamGraphOptimizerTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/DefaultStreamGraphContextTest.java
flink-tests/src/test/java/org/apache/flink/test/scheduling/AdaptiveBatchSchedulerITCase.java

[FLINK-36067][runtime] Support optimize stream graph based on input info.
-  Introduce StreamGraphOptimizer and StreamGraphOptimizationStrategy
- Support optimize stream graph based on input info. …

[FLINK-36067][runtime] Support optimize stream graph based on input info.

---

flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ResultPartitionBytes.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/shuffle/AllTieredShuffleMasterSnapshots.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/shuffle/EmptyTieredShuffleMasterSnapshot.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/shuffle/ShuffleDescriptorRetriever.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/shuffle/TieredInternalShuffleMaster.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/shuffle/TieredInternalShuffleMasterSnapshot.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/shuffle/TieredShuffleMasterSnapshot.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/TieredStorageMasterClient.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/TierFactory.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/TierMasterAgent.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/disk/DiskTierFactory.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/remote/RemoteTierFactory.java
flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/tier/remote/RemoteTierMasterAgent.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/strategy/AllFinishedInputConsumableDecider.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/strategy/DefaultInputConsumableDecider.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/strategy/InputConsumableDecider.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/strategy/PartialFinishedInputConsumableDecider.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/strategy/VertexwiseSchedulingStrategy.java
flink-runtime/src/main/java/org/apache/flink/runtime/shuffle/NettyShuffleMaster.java
flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/hybrid/tiered/storage/TestingTierFactory.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptivebatch/BatchJobRecoveryTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptivebatch/DummyTierFactory.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/strategy/DefaultInputConsumableDeciderTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/strategy/VertexwiseSchedulingStrategyTest.java

*Hybrid shuffle supports job master failover if only external tier used.*
UT & Manually test.

[FLINK-36880][network] Hybrid shuffle supports job master failover if only external tier used

---

flink-runtime/pom.xml
flink-runtime/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
pom.xml

The PR bumps mockito to 5.14.2
Bump mockito to 5.14.2, adapt dependencies
the change is about changes in tests 

[FLINK-36966][tests] Bump mockito to 5.14.2

---

docs/content.zh/docs/deployment/filesystems/s3.md
docs/content/docs/deployment/filesystems/s3.md

In case of `flink-s3-fs-presto`, credentials provider config should be `presto.s3.credentials-provider`. ([Reference](https://prestodb.io/docs/current/connector/hive.html#custom-s3-credentials-provider))

[hotfix][docs] Fix typo in Amazon S3 Access Credential

---

docs/content.zh/docs/dev/table/functions/udfs.md
docs/content/docs/dev/table/functions/udfs.md

This is a follow up for the comment https://github.com/apache/flink/pull/25833#issuecomment-2558457046
udfs docs example for `NamedParameterClass`
just docs examples (paste to scala)
- If yes, how is the feature documented? (docs )

[FLINK-33117][docs] Fix scala example for `NamedParameterClass`

---

flink-clients/src/test/java/org/apache/flink/client/program/rest/RestClusterClientTest.java
flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/WebFrontendITCase.java
flink-runtime-web/src/test/resources/rest_api_v1.snapshot
flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/AccessExecutionGraph.java
flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ArchivedExecutionGraph.java
flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java
flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/jsonplan/JsonPlanGenerator.java
flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/JobDetailsHandler.java
flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/JobDetailsInfo.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveExecutionPlanSchedulingContext.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/ExecutionPlanSchedulingContext.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/NonAdaptiveExecutionPlanSchedulingContext.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/AdaptiveGraphManager.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/DefaultStreamGraphContext.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/StreamGraphContext.java
flink-runtime/src/test/java/org/apache/flink/runtime/jobgraph/jsonplan/JsonGeneratorTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/jobgraph/jsonplan/StreamGraphJsonSchema.java
flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/job/JobDetailsHandlerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/legacy/utils/ArchivedExecutionGraphBuilder.java
flink-runtime/src/test/java/org/apache/flink/runtime/rest/messages/job/JobDetailsInfoTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adapter/DefaultExecutionTopologyTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StateTrackingMockExecutionGraph.java

- Extending job detail rest API to adapt to Incremental JobGraph Generation in batch mode. 
- Modify web ui to support job graph auto-refresh for Incremental JobGraph Generation.
- Modify `JobDetailHandler `to return the incrementally updated job graphs.
- Modify the web ui to display the incremental job graph and the unconverted stream node.
- Add a new checkbox in the webui to select whether to display the unconverted stream node or not.
- Added test that validates that `JsonPlanGenerator ` generates `JsonStreamGraph` works well
- Added test that validates that `JobDetailHandler` returns Incremental JobGraph as expected …

[FLINK-36069][runtime/rest] Extending job detail rest API to expose json stream graph

---

docs/content.zh/docs/dev/python/table/table_environment.md
docs/content/docs/dev/python/table/table_environment.md
flink-python/pyflink/table/table_environment.py
flink-python/src/main/java/org/apache/flink/table/runtime/arrow/ArrowUtils.java
flink-python/src/main/java/org/apache/flink/table/runtime/arrow/ByteArrayUtils.java
flink-python/src/main/java/org/apache/flink/table/runtime/arrow/sources/ArrowTableSource.java
flink-python/src/main/java/org/apache/flink/table/runtime/arrow/sources/ArrowTableSourceFactory.java
flink-python/src/main/java/org/apache/flink/table/runtime/arrow/sources/ArrowTableSourceOptions.java
flink-python/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory

Remove apis about `fromTableSource` in python module
- *Add a new ArrowTableSource for python*
- *Remove `fromTableSource` in python module*
- *Update document in python*

[FLINK-36269][python] Remove usage about TableEnvironmentInternal#fromTableSource in python module

---

docs/layouts/shortcodes/generated/optimizer_config_configuration.html
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/config/OptimizerConfigOptions.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/AdaptiveJoinExecNode.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecAdaptiveJoin.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecHashJoin.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecSortMergeJoin.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/processor/AdaptiveJoinProcessor.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/delegation/BatchPlanner.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/batch/BatchPhysicalHashJoin.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/batch/BatchPhysicalSortMergeJoin.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/physical/batch/BatchPhysicalHashJoinRule.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/physical/batch/BatchPhysicalJoinRuleBase.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/physical/batch/BatchPhysicalSortMergeJoinRule.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/JoinUtil.scala
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/adaptive/AdaptiveJoinTest.xml
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-join_1/join-inner-join-with-duplicate-key/plan/join-inner-join-with-duplicate-key.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-join_1/join-inner-join-with-non-equi-join/plan/join-inner-join-with-non-equi-join.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-join_1/join-left-join/plan/join-left-join.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-join_1/join-non-window-inner-join-with-null-cond/plan/join-non-window-inner-join-with-null-cond.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-join_1/join-non-window-inner-join/plan/join-non-window-inner-join.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-join_1/join-outer-join/plan/join-outer-join.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-join_1/join-right-join/plan/join-right-join.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-join_1/join-semi-join/plan/join-semi-join.json
flink-table/flink-table-planner/src/test/resources/restore-tests/batch-exec-join_1/join-with-filter/plan/join-with-filter.json
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/adaptive/AdaptiveJoinTest.scala

To implement the Adaptive Broadcast Join capability proposed by FLIP-470, while enabling Adaptive Broadcast Join, the compatible join operators will be replaced with Adaptive Broadcast Join operators in the table-planner phase, and the corresponding OperatorFactory is introduced.
- *Introduce configuration options for adaptive broadcast join.*
- *Introduce Exec node for adaptive broadcast join.*
- *Introduce AdaptiveBroadcastJoinOperatorFactory.*
- *Introduce AdaptiveBroadcastJoinProcessor to inject adaptive broadcast join.*
- *Add IT and UT cases to verify the correctness of injecting the Adaptive Broadcast Join operator and generating dynamic join operators.*
- *The proposed changes will be tested for correctness and stability in a …

[FLINK-36607][table-planner] Introduce AdaptiveBroadcastJoinProcessor to inject adaptive broadcast join.

---

docs/content.zh/docs/dev/table/sql/queries/match_recognize.md
docs/content/docs/dev/table/sql/queries/match_recognize.md

When the MATCH_ROWTIME() function was added to MATCH_RECOGNIZE, the docs were updated to explain the feature, but the list of limitations still includes an item incorrectly stating that there is "no possibility to get a time attribute for
subsequent time-based operations," which is no longer true.
Removed the obsolete list item from both the English and Chinese language docs.
n/a
n/a

[hotfix][docs] In match_recognize docs, remove extracting time attributes from list of limitations

---

.github/workflows/docs.yml
.github/workflows/template.flink-ci.yml
.github/workflows/template.pre-compile-checks.yml
azure-pipelines.yml
tools/azure-pipelines/build-apache-repo.yml
tools/azure-pipelines/build-nightly-dist.yml
tools/azure-pipelines/build-python-wheels.yml

This PR backport the changes done of the PR made by @zentol (https://github.com/apache/flink/pull/25708) in master for version 1.20.X to be used in dependencies upgrade.
- Ubuntu CI image version is no more v18 but v22 …

[BP-1.20][FLINK-34194] Update CI to Ubuntu 22.04 (Jammy)

---

flink-clients/src/main/java/org/apache/flink/client/cli/ApplicationDeployer.java
flink-clients/src/main/java/org/apache/flink/client/deployment/application/cli/ApplicationClusterDeployer.java
flink-clients/src/test/java/org/apache/flink/client/program/TestingClusterClient.java
flink-end-to-end-tests/run-nightly-tests.sh
flink-end-to-end-tests/test-scripts/common.sh
flink-end-to-end-tests/test-scripts/test_kubernetes_sql_application.sh
flink-table/flink-sql-client/src/test/resources/sql/set.q
flink-table/flink-sql-gateway-api/src/main/java/org/apache/flink/table/gateway/api/SqlGatewayService.java
flink-table/flink-sql-gateway-api/src/test/java/org/apache/flink/table/gateway/api/utils/MockedSqlGatewayService.java
flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/SqlGatewayRestEndpoint.java
flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/handler/application/DeployScriptHandler.java
flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/header/application/DeployScriptHeaders.java
flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/message/application/DeployScriptRequestBody.java
flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/rest/message/application/DeployScriptResponseBody.java
flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/SqlGatewayServiceImpl.java
flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/context/DefaultContext.java
flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/rest/DeployScriptITCase.java
flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/application/ScriptRunnerITCase.java
flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/utils/SqlGatewayServiceExtension.java
flink-table/flink-sql-gateway/src/test/resources/META-INF/services/org.apache.flink.client.deployment.ClusterClientFactory
flink-table/flink-sql-gateway/src/test/resources/sql/set.q
flink-table/flink-sql-gateway/src/test/resources/sql_gateway_rest_api_v4.snapshot
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/application/SqlDriver.java

*Add REST API to deploy script into application cluster.*
- *Add deployScript method in service to deploy cluster.*
- *Add REST API to deploy script.* …

[FLINK-36759][sql-gateway] Add REST API to deploy script in application mode

---

flink-runtime/pom.xml
flink-runtime/src/main/resources/META-INF/NOTICE

Unmodified backport of https://github.com/apache/flink/pull/25567 to 1.19

[FLINK-36593][runtime] Backport io.airlift:aircompressor upgrade to 0.27

---

flink-table/flink-table-calcite-bridge/pom.xml
flink-table/flink-table-runtime/src/main/resources/META-INF/NOTICE
flink-table/pom.xml

Unmodified backport of https://github.com/apache/flink/pull/25573 to 1.19

[FLINK-33571][table] Upgrade json-path from 2.7.0 to 2.9.0

---

flink-runtime/src/main/java/org/apache/flink/runtime/deployment/ConsumedSubpartitionContext.java
flink-runtime/src/main/java/org/apache/flink/runtime/deployment/TaskDeploymentDescriptorFactory.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/strategy/ConsumedPartitionGroup.java
flink-runtime/src/test/java/org/apache/flink/runtime/deployment/ConsumedSubpartitionContextTest.java

Fix scheduler benchmark regression since Dec.25th.
Reduce the time complexity of ConsumedSubpartitionContext.buildConsumedSubpartitionContext from O(2n) to O(k) (where n is the parallelism of upstream tasks and k is a constant). …

[FLINK-36989][runtime] Fix scheduler benchmark regression caused by ConsumedSubpartitionContext

---

flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/cleanup/CheckpointResourcesCleanupRunnerTest.java

I still cannot fully explain why the `ForkJoinPool` causes issues. But we've seen a failure in `CheckpointResourcesCleanupRunnerTest#testCloseAsyncAfterStartAndErrorInCompletedCheckpointStoreShutdown` in a Flink fork where a thread got leaked and the run timed out.
The reasoning is here that the `ForkJoinPool` is a resource that's used by JUnit for parallel test execution and in this regard might be subject to unexpected shutdown behavior. Instead, we should switch to the `TestExecutorExtension` as we're doing in all the other tests to have independent resource lifecycle handling.
* Replaces `ForkJoinPool` with `TestExecutorExtension`
* Test code is still succeeded
* Error wasn't reproducible …

[FLINK-28091][tests] Replaces ForkJoinPool by TestExecutorExtension

---

flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/cleanup/CheckpointResourcesCleanupRunnerTest.java

1.20 backport of parent PR https://github.com/apache/flink/pull/25868

[BP-1.20][FLINK-28091][tests] Replaces ForkJoinPool by TestExecutorExtension

---

flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/cleanup/CheckpointResourcesCleanupRunnerTest.java

1.19 backport of parent PR https://github.com/apache/flink/pull/25868

[BP-1.19][FLINK-28091][tests] Replaces ForkJoinPool by TestExecutorExtension

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/CatalogFactory.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/FactoryUtil.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/catalog/CatalogITCase.java

*Remove all deprecated methods in `CatalogFactory`* 
*Remove all deprecated methods in `CatalogFactory`* 

[FLINK-36501][table] Remove all deprecated methods in `CatalogFactory`

---

flink-clients/src/main/java/org/apache/flink/client/program/PackagedProgramUtils.java
flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/CreateTableAsITCase.java
flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/HdfsITCaseBase.java
flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/PlannerScalaFreeITCase.java
flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/SqlITCaseBase.java
flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/java/org/apache/flink/table/sql/UsingRemoteJarITCase.java
flink-end-to-end-tests/flink-end-to-end-tests-sql/src/test/resources/sql_client_remote_jar_e2e.sql
flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/SqlClient.java
flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliClient.java
flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliOptions.java
flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliOptionsParser.java
flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliStrings.java
flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliUtils.java
flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/DefaultContextUtils.java
flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/Executor.java
flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/ExecutorImpl.java
flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/SingleSessionManager.java
flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/SqlClientTest.java
flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientTest.java
flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/ExecutorImplITCase.java
flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/context/DefaultContext.java
flink-table/flink-sql-jdbc-driver/src/test/java/org/apache/flink/table/jdbc/FlinkStatementTest.java
flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/test/util/SQLJobSubmission.java
flink-yarn-tests/src/test/java/org/apache/flink/yarn/SqlYARNApplicationITCase.java
flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnTestBase.java
flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterClientFactory.java
flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java

*Support to deploy script via SQL Client.*
- *Support to deploy script*
- *Support to deploy script with remote jar*
- *Relax the limitation that script exists in local*
- *Added integration tests to check deploy script with fake target*
- *Added E2E case to fetch resources from the remote jar* …

[FLINK-36760][sql-client] Supports to deploy script via sql client

---

flink-runtime-web/src/test/resources/rest_api_v1.snapshot
flink-runtime-web/web-dashboard/src/app/components/dagre/components/node/node.component.html
flink-runtime-web/web-dashboard/src/app/components/dagre/components/node/node.component.less
flink-runtime-web/web-dashboard/src/app/components/dagre/components/node/node.component.ts
flink-runtime-web/web-dashboard/src/app/components/dagre/dagre.component.html
flink-runtime-web/web-dashboard/src/app/components/dagre/dagre.component.less
flink-runtime-web/web-dashboard/src/app/components/dagre/dagre.component.ts
flink-runtime-web/web-dashboard/src/app/components/dagre/graph.ts
flink-runtime-web/web-dashboard/src/app/interfaces/job-detail.ts
flink-runtime-web/web-dashboard/src/app/interfaces/job-overview.ts
flink-runtime-web/web-dashboard/src/app/interfaces/job-vertex.ts
flink-runtime-web/web-dashboard/src/app/pages/job/overview/job-overview.component.html
flink-runtime-web/web-dashboard/src/app/pages/job/overview/job-overview.component.ts
flink-runtime-web/web-dashboard/src/app/services/config.service.ts
flink-runtime-web/web-dashboard/src/app/services/job.service.ts
flink-runtime/src/main/java/org/apache/flink/runtime/messages/webmonitor/JobDetails.java
flink-runtime/src/test/java/org/apache/flink/runtime/messages/webmonitor/JobDetailsTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/job/JobsOverviewHandlerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/legacy/utils/ArchivedExecutionGraphBuilder.java

- Modify web ui to support job graph auto-refresh for Incremental JobGraph Generation.
- Modify the web ui to display the incremental job graph and the unconverted stream node.
- Add a new checkbox in the webui to select whether to display the unconverted stream node or not.
This change is a frontend(UI) work and are not covered by tests.
- The …

[FLINK-36070][flink-runtime-web] Modifying web UI to adapt to Incremental JobGraph Generation

---

flink-runtime-web/pom.xml

Unmodified backport of https://github.com/apache/flink/pull/25670 to 1.20
Contribute-to: https://issues.apache.org/jira/browse/FLINK-36901
This pull request raises the version of the NodeJS module which is a pre-requisite to upgrade dependencies in order to address vulnerabilities in Runtime/WebFrontend component. 
There will be another PR to fix vulnerabilities once this is merged.
NodeJS is v22.11.0/Npm is 10.9.0
The Flink UI should be accessible without any difference …

[BP-1.20][FLINK-36739] Update the NodeJS to v22.11.0 (LTS)

---

flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestValuesTableFactory.java
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/LookupJoinITCase.scala

*This pr tries to fix the 'values' connector only used for testing!*
Currently, the "values" lookup table used for testing does not deduplicate data with the same pk.
- *Deduplicate the data with same pk in values lookup table*
- *Add tests*
A test is added to verify this fix.

[FLINK-36968][table-planner] Deduplicate data with the same pk in values lookup table used for testing

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/descriptors/DescriptorProperties.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/legacy/descriptors/Schema.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/logical/utils/LogicalTypeParser.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/LogicalTypeParserTest.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/utils/DataTypeFactoryMock.java

*Remove the deprecated method LogicalTypeParser#parse*
- *Remove the deprecated method LogicalTypeParser#parse*
- *Adapt the related code and tests*

[FLINK-36507][table-common] Remove the deprecated method LogicalTypeParser#parse

---

flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/ClusterEntrypoint.java
flink-runtime/src/test/java/org/apache/flink/runtime/entrypoint/ClusterEntrypointTest.java

Fix an NPE that would occur when a ClusterEntrypoint is shut down before it was fully initialized.

[FLINK-37016] ClusterEntrypoint can be closed before initialization

---

docs/data/sql_functions.yml
docs/data/sql_functions_zh.yml
flink-python/pyflink/table/expressions.py
flink-python/pyflink/table/tests/test_expression.py

To update the documentation for `DATE_FORMAT`, which is not accurate now. The current function behaviors are:
- `DATE_FORMAT(timestamp, string)` eventually calls `formatTimestamp(TimestampData ts, String format, ZoneId zoneId)` in `DateTimeUtils.java`, which uses [DateTimeFormatter](https://issues.apache.org/jira/browse/FLINK-36941#L724). 
-  `DATE_FORMAT(string, string) `eventually calls `formatTimestampStringWithOffset(String dateStr, String fromFormat, String toFormat, TimeZone tz, long offsetMills)` in `DateTimeUtils.java`, which uses  [SimpleDateFormat](https://github.com/apache/flink/blob/1523f2c2062b860a2abfe75f8ead276bb161d64a/flink-table/flink-table-common/src/main/java/org/apache/flink/table/utils/DateTimeUtils.java#L743).
- Per this comment, we will fix documentation in Flink …

[FLINK-36941][docs] Update DATE_FORMAT Doc and Python Tests in 1.19

---

docs/data/sql_functions.yml
docs/data/sql_functions_zh.yml
flink-python/pyflink/table/expressions.py
flink-python/pyflink/table/tests/test_expression.py

To update the documentation for `DATE_FORMAT`, which is not accurate now. The current function behaviors are:
- `DATE_FORMAT(timestamp, string)` eventually calls `formatTimestamp(TimestampData ts, String format, ZoneId zoneId)` in `DateTimeUtils.java`, which uses [DateTimeFormatter](https://issues.apache.org/jira/browse/FLINK-36941#L724). 
-  `DATE_FORMAT(string, string) `eventually calls `formatTimestampStringWithOffset(String dateStr, String fromFormat, String toFormat, TimeZone tz, long offsetMills)` in `DateTimeUtils.java`, which uses  [SimpleDateFormat](https://github.com/apache/flink/blob/1523f2c2062b860a2abfe75f8ead276bb161d64a/flink-table/flink-table-common/src/main/java/org/apache/flink/table/utils/DateTimeUtils.java#L743).
- Per this comment, we will fix documentation in Flink …

[FLINK-36941][docs] Update DATE_FORMAT Doc and Python Tests in 1.20

---

flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/materializedtable/MaterializedTableManager.java
flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/MaterializedTableStatementITCase.java
flink-table/flink-sql-parser/src/main/codegen/data/Parser.tdd
flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl
flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/ddl/SqlAlterMaterializedTableAsQuery.java
flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/MaterializedTableStatementParserTest.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/materializedtable/AlterMaterializedTableAsQueryOperation.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/materializedtable/AlterMaterializedTableChangeOperation.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/TableChange.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlAlterMaterializedTableAsQueryConverter.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlCreateMaterializedTableConverter.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlNodeConverters.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlMaterializedTableNodeToOperationConverterTest.java

*Add support query modification for materialized table*
**
- *Add support parse materialized table query modification statements*
- *Add support convert materialized table node to operation*
- *Add support execution of query modification of materialized table*
Some unit test and ITCase will be added in MaterializedTableStatementITCase to verify these changes. …

[FLINK-36994][table] Support ALTER MATERIALIZED TABLE As <Query> statement

---

flink-python/pyflink/table/table_config.py
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/EnvironmentSettings.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/TableConfig.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/TableResult.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java

This PR is based on the previous one (https://github.com/apache/flink/pull/25514), and I have included @corgy-w (corgy-w@qq.com) as a co-author in the commit message.
This PR includes multi removal work for deprecated public methods as below:
- [[FLINK-36477](https://issues.apache.org/jira/browse/FLINK-36477)](https://issues.apache.org/jira/browse/FLINK-36477) Remove deprecated method BaseExpressions#cast in table-api-java
- [[FLINK-36478](https://issues.apache.org/jira/browse/FLINK-36478)](https://issues.apache.org/jira/browse/FLINK-36478) Remove deprecated methods EnvironmentSettings#fromConfiguration and EnvironmentSettings#toConfiguration
- [[FLINK-36480](https://issues.apache.org/jira/browse/FLINK-36480)](https://issues.apache.org/jira/browse/FLINK-36480) Remove all deprecated …

[FLINK-36477][table] Remove deprecated method BaseExpressions#cast

---

docs/content.zh/docs/ops/metrics.md
docs/content/docs/ops/metrics.md
flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricNames.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultScheduler.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/MockRestartingContext.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/RestartingTest.java

Add numRescales metrics in Scheduler to distinguish the restart caused by auto scaler.
- add numRescales metrics in Scheduler
- change the interfaces in Context to distinguish whether a goToRestarting is trigged due to failure
- Add test cases for the new metrics.
- The S3 file system connector: (o)

[FLINK-36871][runtime] add rescale metrics in scheduler

---

flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/AggregatingStateDescriptor.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/DefaultKeyedStateStore.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/ListStateDescriptor.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/MapStateDescriptor.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/ReducingStateDescriptor.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/StateDescriptor.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/StateDescriptorUtils.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/StateSerializerReference.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/ValueStateDescriptor.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamOperatorStateHandler.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamingRuntimeContext.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendTestUtils.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/StateDescriptorTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/StreamingRuntimeContextTest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackendBuilder.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateBackend.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStDBOperationTestBase.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStListStateTest.java

This PR enables the lazy-initialization for state serializer in state v2. This is useful for datastream api, and is also a pre-work for exposing state v2 api to user. 
The code is very similar with those in state v1 descriptors.
- Implement constructor with `TypeInformation` for `StateDescriptor`s.
- Invoke `initializeSerializerUnlessSet` wherever necessary.
This change is already covered by existing tests `StreamingRuntimeContextTest`.
- …

[FLINK-37030] Support lazy initialization for state serializer in State V2

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/processor/AdaptiveJoinProcessor.java
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/adaptive/AdaptiveJoinTest.xml
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/adaptive/AdaptiveJoinTest.scala

Enabling Batch job progress recovery and adaptive batch execution to work together will be supported in future versions.
To prevent issues with job recovery when users configure Batch job progress recovery, we will temporarily disable adaptive join optimization in scenarios where Batch job progress recovery is enabled.
- *Disable adaptive join optimization when enable batch job progress recovery.*
- *Test with ut AdaptiveJoinTest::testAdaptiveJoinWithBatchJobRecovery.*
- *Enable the config option `execution.batch.job-recovery.enabled` and check whether adaptive join optimization is disabled.* …

[FLINK-37082][table-planner] Disable adaptive join optimization when enable batch job progress recovery.

---

flink-core/src/main/java/org/apache/flink/configuration/ConfigConstants.java
flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/JobManagerJobMetricGroup.java
flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/TaskMetricGroup.java
flink-runtime/src/main/java/org/apache/flink/runtime/metrics/util/MetricUtils.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/translators/SinkTransformationTranslator.java
flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/TaskMetricGroupTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/metrics/util/MetricUtilsTest.java
flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/SinkMetricsITCase.java

Avoid truncation of the Writer/Committer keyword.
- add MetricUtil#truncateOperatorName to optimize Operator name
- SinkMetricsITCase#testMetrics

[FLINK-36946][Metrics] Optimize sink operator name truncate

---

flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/adaptive/AdaptiveJoinTest.xml

*fix ut in AdaptiveJoinTest.testAdaptiveJoinWithBatchJobRecovery.*
- *fix ut in AdaptiveJoinTest.testAdaptiveJoinWithBatchJobRecovery.*
- *check ut in AdaptiveJoinTest.testAdaptiveJoinWithBatchJobRecovery run success.*

[FLINK-37085][table-planner] fix ut in AdaptiveJoinTest.testAdaptiveJoinWithBatchJobRecovery.

---

flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskTest.java

Fix the issue that task can be stuck in deploying state forever when canceling job/failover.
Make cancel watchdog cover tasks stuck in DEPLOYING state.
Added UT, mocking an invokable stuck in the constructor forever.
- If …

[FLINK-37024][task] Make cancel watchdog cover tasks stuck in DEPLOYING state

---

docs/layouts/shortcodes/generated/optimizer_config_configuration.html
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/DefaultAdaptiveExecutionHandler.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/StreamGraphOptimizationStrategy.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/StreamGraphOptimizer.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/AdaptiveGraphManager.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/DefaultStreamGraphContext.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/StreamEdge.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/StreamGraphContext.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/util/ImmutableStreamGraph.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/util/ImmutableStreamNode.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/util/StreamEdgeUpdateRequestInfo.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/util/StreamNodeUpdateRequestInfo.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptivebatch/DefaultAdaptiveExecutionHandlerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptivebatch/StreamGraphOptimizerTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/DefaultStreamGraphContextTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/util/ImmutableStreamGraphTest.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/config/OptimizerConfigOptions.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/adaptive/AdaptiveJoinOperatorGenerator.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/delegation/BatchPlanner.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/adaptive/AdaptiveBroadcastJoinITCase.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/join/JoinITCase.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/TableTestBase.scala
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/adaptive/AdaptiveJoin.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/adaptive/AdaptiveJoinOperatorFactory.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/strategy/AdaptiveBroadcastJoinOptimizationStrategy.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/strategy/BaseAdaptiveJoinOperatorOptimizationStrategy.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/strategy/PostProcessAdaptiveJoinStrategy.java
flink-tests/src/test/java/org/apache/flink/test/scheduling/AdaptiveBatchSchedulerITCase.java

Since the adaptive join requires determining the actual join operator at runtime, we introduced the AdaptiveBatchSchedulerFactory to implement this functionality.
- *Introduce AdaptiveBatchSchedulerFactory to support dynamic generate join operator at runtime*
- *Add IT case for adaptive broadcast join.*
- *Verify end-to-end correctness through the IT case AdaptiveBroadcastJoinITCase.*
- *Use TPC-DS to verify the effect of enabling adaptive broadcast join optimization.* …

[FLINK-36608][table-runtime] Support dynamic StreamGraph optimization for AdaptiveBroadcastJoinOperator

---

flink-core/src/main/java/org/apache/flink/util/MdcUtils.java
flink-core/src/test/java/org/apache/flink/util/MdcLogbackCompatibilityTest.java

Restores compatibility with Logback 1.2, fixes issues [FLINK-36104](https://issues.apache.org/jira/browse/FLINK-36104) and [FLINK-36227](https://issues.apache.org/jira/browse/FLINK-36227).
Same as #25813, but targeting master.

[FLINK-36227] Restore compatibility with Logback 1.2 - Flink 2.0

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/RecordContext.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateRequestBuffer.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorTest.java

Currently, there is a limit for in-flight records in async state processing. However, we allow developers to initialize a new processing in-middle of another. These derived processings are treated as normal ones for timers or upstreaming records, which is problematic:
- The new derived processing may increase the number of in-flight requests and cause force draining when it reaches the limit. But the draining may require the current processing also finish. This is a deadlock.
- The derived processing will queue behind normal processing, which is not the behavior the user wants. The derived ones should be fired right after the current processing or ASAP.
Thus, This PR changes the behavior in `AsyncExecutionController` and its related buffer:
- Avoid drain when creating derived processing. …

[FLINK-37089][Runtime] Advanced scheduling for derived async state processing

---

flink-runtime/pom.xml
flink-table/flink-sql-gateway/pom.xml
flink-table/flink-sql-parser/pom.xml
flink-table/flink-table-planner/pom.xml
flink-yarn-tests/pom.xml
pom.xml

Among others there is now support of parameterized tests with @FieldSource
https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-sources-FieldSource
pom files

[FLINK-37019][tests] Bump junit5 to 5.11.4

---

docs/data/sql_functions.yml
docs/data/sql_functions_zh.yml
flink-python/pyflink/table/expressions.py
flink-python/pyflink/table/tests/test_expression.py
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/Expressions.java
flink-table/flink-table-api-scala/src/main/scala/org/apache/flink/table/api/ImplicitExpressionConversions.scala
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/ToTimestampLtzTypeStrategy.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/utils/DateTimeUtils.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/strategies/ToTimestampLtzTypeStrategyTest.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/expressions/converter/DirectConvertRule.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/sql/FlinkSqlOperatorTable.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/BuiltInMethods.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/FunctionGenerator.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/StringCallGen.scala
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/TimeFunctionsITCase.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/batch/sql/TimeTravelTest.java
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/TemporalTypesTest.scala
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/ToTimestampLtzFunction.java

The Flink TO_TIMESTAMP_LTZ is lacking some behaviors, compared with other vendors. eg. https://docs.snowflake.com/en/sql-reference/functions/to_timestamp
This PR adds the following additional functions for TO_TIMESTAMP_LTZ. 
```
TO_TIMESTAMP_LTZ(string1) -- Parse timestamp with default format 
TO_TIMESTAMP_LTZ(string1, string2) -- Parse timestamp with custom format 
TO_TIMESTAMP_LTZ(string1, string2, string3) -- Parse timestamp with format and timezone 
TO_TIMESTAMP_LTZ(numeric) -- For epoch milliseconds
```
- Add the additional overloading functions for TO_TIMESTAMP_LTZ.
- Add java test cases. 
- Make sure the current scala tests pass.
This change is already covered by existing tests, `TemporalTypesTest.scala`.
Added additional tests in `TimeFunctionsITCase.java`. 
- Dependencies (does …

[FLINK-36862][table] Implement additional TO_TIMESTAMP_LTZ() functions

---

flink-yarn-tests/src/test/java/org/apache/flink/yarn/SqlYARNApplicationITCase.java

*Fix failed test. It seems the path is not legal.*

[FLINK-37083][e2e] Fix failed SqlYARNApplicationITCase on AZP

---

docs/content.zh/docs/dev/table/sql-gateway/overview.md
docs/content.zh/docs/dev/table/sql-gateway/rest.md
docs/content.zh/docs/dev/table/sqlClient.md
docs/content/docs/dev/table/sql-gateway/overview.md
docs/content/docs/dev/table/sql-gateway/rest.md
docs/content/docs/dev/table/sqlClient.md
docs/layouts/shortcodes/generated/rest_v1_dispatcher.html
docs/layouts/shortcodes/generated/rest_v4_sql_gateway.html
docs/static/generated/rest_v1_dispatcher.yml
docs/static/generated/rest_v4_sql_gateway.yml

*Add document about how to use sql client and sql gateway to deploy script.*

[FLINK-36761][docs] Add document about how to use SQL Gateway and SQL Client to deploy script

---

.github/workflows/docs.yml
.github/workflows/template.flink-ci.yml
.github/workflows/template.pre-compile-checks.yml
azure-pipelines.yml
tools/azure-pipelines/build-apache-repo.yml
tools/azure-pipelines/build-nightly-dist.yml
tools/azure-pipelines/build-python-wheels.yml

Unmodified backport of https://github.com/apache/flink/pull/25827 to 1.19.
Required for backporting UI vulnerability fixes https://issues.apache.org/jira/browse/FLINK-36716.

[1.19][FLINK-34194][ci] Updates test CI container to be based on Ubuntu 22.04

---

flink-clients/src/test/java/org/apache/flink/client/program/artifact/ArtifactFetchManagerTest.java
flink-core/src/test/java/org/apache/flink/testutils/TestingUtils.java

Added the requested changes in https://github.com/apache/flink/pull/24931, keeping the original author.

[FLINK-35512][tests] Do not depend on the `flink-clients` jar in `ArtifactFetchManagerTest`

---

flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/table/stream/PartitionCommitInfoTest.java
flink-core/src/main/java/org/apache/flink/api/common/serialization/SerializerConfig.java
flink-core/src/main/java/org/apache/flink/api/common/serialization/SerializerConfigImpl.java
flink-core/src/test/java/org/apache/flink/api/common/ExecutionConfigFromConfigurationTest.java
flink-core/src/test/java/org/apache/flink/api/common/ExecutionConfigTest.java
flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroKryoSerializerRegistrationsTest.java
flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/typeutils/AvroTypeExtractionTest.java
flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/types/PojoTestUtils.java

There're a few @internal "set" methods in the SerializerConfig interface that can change serializer behavior, which remained there waiting for all their deprecated caller methods to be removed. Now that the caller methods are removed in Flink 2.0, we should remove these "set" methods now.
Remove legacy internal methods for changing serializer behavior in SerializerConfig. …

[FLINK-37101] Remove legacy internal methods for changing serializer behavior in SerializerConfig

---

flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/input/KeyedStateInputFormatTest.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AsyncStreamFlatMap.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/datastream/KeyedStream.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamFlatMapAsync.java

This PR  implements the asyc state version of stream flatmap.
- Introduce `StreamFlatMapAsync`
- Update the behavior of `KeyedStream#flatmap`
- `KeyedStateInputFormatTest`

[FLINK-36957][Datastream] Implement asyc state version of stream flatmap

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/plan/stats/ColumnStats.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/metadata/FlinkRelMdColumnInterval.scala

Remove all deprecated methods in ColumnStats
- Remove all deprecated methods in ColumnStats

[FLINK-36506][table] Remove all deprecated methods in ColumnStats

---

flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/testsuites/SinkTestSuiteBase.java
flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/testsuites/SourceTestSuiteBase.java

The source and sink test suites have a couple of tests that take a snapshot and then recover from it with lower or higher parallelism. However, while taking the snapshot they use the `–drain` version (advanceToEndOfEventTime=true), which should only be used when terminating the pipeline for good. In particular, all operators receive `endInput()` so they should finalize their state. The tests, however, add more records to the inputs, such that the `endInput` contract is violated.
The solution is simple: just use advanceToEndOfEventTime=false.
- Change flag for source/sink test.
Manually verified but it should fix the connector repos that build against SNAPSHOTs. …

[FLINK-37108] Use-non terminal savepoint in source/sink suite

---

flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/testsuites/SinkTestSuiteBase.java
flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/testsuites/SourceTestSuiteBase.java

[FLINK-37108] Use-non terminal savepoint in source/sink suite [1.20]

---

.github/workflows/stale.yml

This is the implementation of the [Stale PR GitHub Action Proposal](https://cwiki.apache.org/confluence/display/FLINK/Stale+PR+Cleanup).  This was [voted through](https://lists.apache.org/thread/kc90254wvo5q934doh8o4sbj1fgwvy76) on the dev mailing list.
The initial setting is for 6 months of inactivity to be marked as stale with 3 month to respond before the PR is closed. Ideally, once the initial backlog is cleared, we will reduces these down to 3 months and 1 month respectively, to match other Apache projects. 
There is also configuration for when the action is run and how many PRs it will process in one run. Initially I have set this to every 6 hours and 200 PRs per run, this will allow us to process the backlog in a few days. After which these can be reduced to daily, with a lower …

[FLINK-37026] Add Stale PR GitHub Action workflow

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/annotation/ArgumentTrait.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/StaticArgumentTrait.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/SystemTypeInference.java
flink-table/flink-table-planner/src/main/java/org/apache/calcite/sql/validate/ProcedureNamespace.java
flink-table/flink-table-planner/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/FlinkSqlCallBinding.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/bridging/BridgingSqlFunction.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/inference/TypeInferenceReturnInference.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/sql/SqlDefaultOperator.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/stream/sql/ProcessTableFunctionTest.java

The previous PR for FLINK-36707 forgot to update the system output type strategy. This PR adds support for passing columns through.
- Allow partition columns pass through and explicit column pass through.
- Fix bug in the stack that called type inference two times.
This change added tests and can be verified as follows: `ProcessTableFunctionTest`
*More tests will follow, this is just the initial skeleton.* …

[FLINK-36707][table] Add output strategy to SystemTypeInference

---

flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/testsuites/SinkTestSuiteBase.java
flink-test-utils-parent/flink-connector-test-utils/src/main/java/org/apache/flink/connector/testframe/testsuites/SourceTestSuiteBase.java

Unchanged backport of https://github.com/apache/flink/pull/25973.

[FLINK-37108] Use-non terminal savepoint in source/sink suite [1.19]

---

flink-python/docs/reference/pyflink.table/catalog.rst
flink-python/pyflink/table/catalog.py
flink-python/pyflink/table/tests/test_catalog.py
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogFunctionImpl.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/FunctionCatalog.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogFunction.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/catalog/CatalogTest.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/functions/UserDefinedFunctionHelperTest.java

Remove deprecated method CatalogFunction#isGeneric
- Remove deprecated method CatalogFunction#isGeneric

[FLINK-36496][table] Remove deprecated method CatalogFunction#isGeneric

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/FunctionDefinitionFactory.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestFunctionDefinitionFactory.java

Remove deprecated method FunctionDefinitionFactory#createFunctionDefinition.
Note: I also delete the default implement in the new stack. You can see the previous discuss in https://lists.apache.org/thread/tlk64byvxtbkox3wyv2jfoqfdtf523bf
- Remove deprecated method FunctionDefinitionFactory#createFunctionDefinition …

[FLINK-36503][table] Remove deprecated method FunctionDefinitionFactory#createFunctionDefinition

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
.github/workflows/template.flink-ci.yml
.github/workflows/template.pre-compile-checks.yml
README.md
azure-pipelines.yml
flink-dist-scala/src/main/resources/META-INF/NOTICE
flink-end-to-end-tests/test-scripts/common_docker.sh
flink-rpc/flink-rpc-akka/pom.xml
flink-table/flink-table-planner-loader-bundle/src/main/resources/META-INF/NOTICE
pom.xml
tools/azure-pipelines/build-apache-repo.yml

This PR changes Flink CI to run on Java 17 by default, effectively dropping support for Java 8. Since Java 11 is officially not deprecated, there's a separate Java profile to run JDK11 tests during the nightly cron builds. 
* Changes CI to run on Java 17 by default, and removes Java 8 in the CI runs
* Bumps Scala to 2.12.20, since we're already in Flink 2.0 land and we can safely break this for the upgrade to Java 17. 
* Updates README …

[FLINK-36181] Use Java 17 by default

---

flink-core/src/main/java/org/apache/flink/core/state/InternalStateIterator.java
flink-core/src/main/java/org/apache/flink/core/state/StateFutureUtils.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AbstractStateIterator.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/adaptor/CompleteStateIterator.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AbstractStateIteratorTest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStListIterator.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStMapIterator.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/window/asyncprocessing/AsyncStateWindowJoinOperator.java

We have identified a need to process full data from an iterator, but the current async partial loading interface is not user-friendly. Therefore, this PR provides a utility to convert the future of `StateIterator` to `Iterable` for the convenience of the user.
- Add `StateFutureUtils#toIterable`.
- Change `AsyncStateWindowJoinOperator`  to apply the optimization.
This change added tests `AbstractStateIteratorTest#testPartialLoadingWithConversionToIterable` …

[FLINK-37130] Provide a util converting future of StateIterator to Iterable

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/SqlCallSyntax.java

This is a follow up for https://github.com/apache/flink/pull/25791
where SqlCallSyntax was fixed for `trim` however 
javadoc example was not

[hotfix][javadoc] Use correct syntax for `TRIM` in `SqlCallSyntax` javadoc

---

.github/workflows/stale.yml

This fixes an issue with the formatting of the Stale PR messages introduced in #25953. 
- Remove HTML tags from Stale PR message

[FLINK-37026] Fix the stale pr message formatting

---

flink-runtime/src/test/java/org/apache/flink/runtime/jobgraph/jsonplan/JsonGeneratorTest.java

This pull request try to fix unstable test `org.apache.flink.runtime.jobgraph.jsonplan.JsonGeneratorTest#testGenerateStreamGraphJson`.
- Replace the hard-coded stream node ID with one retrieved from the stream graph in the test.
This change is already covered by existing tests `org.apache.flink.runtime.jobgraph.jsonplan.JsonGeneratorTest#testGenerateStreamGraphJson`. …

[FLINK-37137][runtime] Fix unstable test testGenerateStreamGraphJson

---

flink-end-to-end-tests/test-scripts/test_tpcds.sh

Add adaptive broadcast join to e2e tpc-ds tests.
In this case, we will set the AdaptiveBroadcastJoinStrategy to RUNTIME_ONLY, significantly increasing the likelihood of triggering adaptive broadcast join.
- *Add adaptive broadcast join to e2e tpc-ds tests.*
This change is already covered by existing tests, such as *test_tpcds.sh*.
- …

[FLINK-37090][e2e] Add adaptive broadcast join to e2e tpc-ds tests.

---

flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/AdaptiveGraphManager.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/StreamEdge.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/util/ImmutableStreamEdge.java
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/adaptive/AdaptiveSkewedJoinITCase.scala
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/strategy/AdaptiveSkewedJoinOptimizationStrategy.java

Currently, the scenarios in which the AdaptiveSkewedJoinOptimizationStrategy is effective are too limited. For example, when there is an output edge of the forward for unspecified type, the optimization cannot be applied. However, this optimization wouldn't break the data correctness of this kind output edges. Therefore, we will optimize this scenario to enable the optimization to be effective in more scenarios.
Improve AdaptiveSkewedJoinOptimizationStrategy to make it effective in more scenarios.
- The runtime per-record code paths (performance sensitive): (yes / **no** / don't …

[FLINK-37139][table-planner] Improve AdaptiveSkewedJoinOptimizationStrategy to make it effective in more scenarios

---

.asf.yaml

TRIVIAL AS IS. I want to click this URL at the right top corner today and noticed that it's missing.

[hotfix] Add homepage link to .asf.yaml

---

flink-python/docs/reference/pyflink.table/catalog.rst
flink-python/docs/reference/pyflink.table/table_environment.rst
flink-python/pyflink/table/__init__.py
flink-python/pyflink/table/catalog.py
flink-python/pyflink/table/table_environment.py
flink-python/pyflink/table/tests/test_environment_completeness.py
flink-python/pyflink/table/tests/test_table_environment_api.py

Support create catalog in pyflink table environment.
Note, the doc is not updated because I want to update it util the legacy `register_catalog` is removed in https://issues.apache.org/jira/browse/FLINK-36482.
- Support create catalog in pyflink table environment
This change added tests to verify it.
- If yes, how is the feature documented? later

[FLINK-32647][pyflink] Support create catalog in pyflink table environment

---

flink-core/src/main/java/org/apache/flink/util/AbstractAutoCloseableRegistry.java
flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/state/rocksdb/RocksDBWriteBatchWrapperTest.java

Saw this flaky `testAsyncCancellation` test failed with
```
org.apache.flink.contrib.streaming.state.RocksDBWriteBatchWrapperTest.testAsyncCancellation -- Time elapsed: 0.121 s <<< ERROR!
Sep 16 02:20:08 java.lang.Exception: Unexpected exception, expected<org.apache.flink.runtime.execution.CancelTaskException> but was<java.lang.AssertionError>
Sep 16 02:20:08 Caused by: java.lang.AssertionError: 
Sep 16 02:20:08 Expecting actual:
Sep 16 02:20:08   2
Sep 16 02:20:08 to be less than:
Sep 16 02:20:08   2 
Sep 16 02:20:08 	at org.apache.flink.contrib.streaming.state.RocksDBWriteBatchWrapperTest.testAsyncCancellation(RocksDBWriteBatchWrapperTest.java:98)
```
After investigation, I found this is because the slow async `register.close()` causes the main verification failure. Because the …

[FLINK-36293][state] make sure register is closed before verification in testAsyncCancellation

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/AbstractStreamOperatorV2.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/InternalTimeServiceManager.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/InternalTimeServiceManagerImpl.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/InternalTimerServiceAsyncImpl.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/InternalTimerServiceSerializationProxy.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionInternalTimeServiceManager.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/InternalTimerServiceAsyncImplTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/MailboxWatermarkProcessorTest.java

Create an async timer service when restoring async operator.
- Add `restoreTimeService` for `InternalTimeServiceManagerImpl`.
- Allow setup `AEC` after `InternalTimerServiceAsyncImpl` initialization.
- InternalTimerServiceAsyncImplTest#testSnapshotAndRestore …

[FLINK-37140][runtime] Create async timer service when restore async operator

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecDeduplicate.java
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/DeduplicateITCase.scala
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/ProcTimeDeduplicateKeepFirstRowFunction.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/ProcTimeDeduplicateKeepLastRowFunction.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/ProcTimeMiniBatchDeduplicateKeepFirstRowFunction.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/ProcTimeMiniBatchDeduplicateKeepLastRowFunction.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/RowTimeMiniBatchDeduplicateFunction.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/RowTimeMiniBatchLatestChangeDeduplicateFunction.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/SyncStateDeduplicateFunctionBase.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/asyncprocessing/AsyncStateDeduplicateFunctionBase.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/asyncprocessing/AsyncStateRowTimeDeduplicateFunction.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/utils/DeduplicateFunctionHelper.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/utils/RowTimeDeduplicateFunctionHelper.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/window/combines/RowTimeDeduplicateRecordsCombiner.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/deduplicate/RowTimeDeduplicateFunctionTest.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/deduplicate/RowTimeDeduplicateFunctionTestBase.java

Introduce RowTimeDeduplicateFunction with Async State API.
- *Add AsyncStateRowTimeDeduplicateFunction and RowTimeDeduplicateFunctionHelper*
- *Add ITs and HarnessTests*
Existent tests and new added tests can verify this change.
- If yes, how is the feature documented?  A independent pr will be introduced later.

[FLINK-36837][table] Introduce RowTimeDeduplicateFunction with Async State API

---

docs/content/docs/learn-flink/overview.md

[hotfix] [docs] Fix typo in Flink Overview

---

flink-connectors/flink-connector-hive/src/main/resources/META-INF/NOTICE
flink-formats/flink-sql-parquet/src/main/resources/META-INF/NOTICE
flink-formats/pom.xml
flink-python/pom.xml
flink-python/src/main/resources/META-INF/NOTICE

* Bump Parquet dependency
* Update POM and NOTICE files

[FLINK-36695][Formats] Bump Parquet dependency to 1.14.4

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateExecutor.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateRequest.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/StateRequestBuffer.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AbstractStateIteratorTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionControllerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/MockStateExecutor.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractAggregatingStateTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractKeyedStateTestBase.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractReducingStateTest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateExecutor.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateRequestClassifier.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateExecutorTest.java

Currently, if user enables the async state processing, and use one state backends supporting async state access (e.g. ForSt State Backend), but invokes synchronous methods (e.g. `get()`, `add()`), there is performance issue for state access. The default implementation of synchronous methods for the case above is submitting a async state access and wait. This PR applies an optimization that bypass all the async executions and just access the state in synchronous way.
- Provide `sync` flag in `StateRequest` and if it is ready to execute, fire it synchronously.
- The runtime …

[FLINK-37164][Runtime] Speed up state v2 synchronous methods execution

---

flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsCheckpointStorageAccess.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStOptions.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateBackend.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateBackendV2Test.java

This PR makes Forst remote dir share with checkpoint.
- Add `checkpoint-dir` shortcut for forst remote dir
- Expose `FsCheckpointStorageAccess#sharedStateDirectory`
- `ForStStateBackendV2Test#testRemoteDirShareCheckpointDir`
- If yes, how is the feature documented? (not applicable / …

[FLINK-37021][state/forst] Make Forst remote dir share with checkpoint

---

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/aggregate/async/AsyncStateGroupAggFunction.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/aggregate/asyncwindow/processors/AbstractAsyncStateSliceWindowAggProcessor.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/asyncprocessing/AsyncStateDeduplicateFunctionBase.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/asyncprocessing/AsyncStateStreamingJoinOperator.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/window/asyncprocessing/AsyncStateWindowJoinOperator.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/async/AbstractAsyncStateTopNFunction.java

Add logs in all existing async state ops to check if they are under async state when running
- Add logs in all existing async state ops to check if they are under async state when running

[FLINK-37172][table-runtime] Add logs in all existing async state ops to check if they are under async state when running

---

flink-table/flink-sql-client/src/test/resources/cli/all-mode-help.out
flink-table/flink-sql-client/src/test/resources/cli/embedded-mode-help.out

Fix failed tests about SqlClientTest#testPrintAllModeHelp and #testPrintEmbeddedModeHelp
- *Fix failed tests about SqlClientTest#testPrintAllModeHelp and #testPrintEmbeddedModeHelp* …

[FLINK-37174][sql-client] Fix failed tests about SqlClientTest#testPrintAllModeHelp and #testPrintEmbeddedModeHelp

---

flink-clients/src/main/java/org/apache/flink/client/deployment/StandaloneClusterId.java
flink-end-to-end-tests/run-nightly-tests.sh
flink-end-to-end-tests/test-scripts/test_kubernetes_materialized_table.sh
flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/application/ScriptExecutor.java
flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/materializedtable/MaterializedTableManager.java
flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/operation/OperationExecutor.java
flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/workflow/EmbeddedWorkflowScheduler.java
flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/application/ScriptExecutorITCase.java
flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/workflow/EmbeddedSchedulerRelatedITCase.java
flink-table/flink-sql-gateway/src/test/resources/application/no_semicolon.q
flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogBaseTableResolutionTest.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/refresh/ContinuousRefreshHandler.java
flink-test-utils-parent/flink-table-filesystem-test-utils/src/main/java/org/apache/flink/table/file/testutils/catalog/TestFileSystemCatalog.java
flink-test-utils-parent/flink-table-filesystem-test-utils/src/test/java/org/apache/flink/table/file/testutils/catalog/TestFileSystemCatalogTest.java
flink-test-utils-parent/flink-table-filesystem-test-utils/src/test/java/org/apache/flink/table/file/testutils/catalog/TestFileSystemCatalogTestBase.java

*Support submitting refresh task of materialized table to yarn/k8s*
Support submitting refresh task of materialized table to yarn/k8s
*Some e2e test case is added to verify this feature.*

[FLINK-37133][table] Support Submitting Refresh Job of Materialized Table to Yarn/K8s

---

.github/workflows/nightly-trigger.yml

Disables 1.18 nightly builds for GHA after it being discussed in [this dev ML thread](https://lists.apache.org/thread/5onl01vt98452vyj4x6flvdq8601fdo7).
* Removes 1.18 release branch …

[FLINK-37170][ci] Removes 1.18 version from GHA nightly builds

---

flink-rpc/flink-rpc-akka/src/main/resources/META-INF/NOTICE

*Fix license check issue in JDK11 build*
- *upgrade scala version in NOTICE file*

[FLINK-37173][build] Fix license check issue in JDK11 build

---

flink-end-to-end-tests/test-scripts/test_netty_shuffle_memory_control.sh

Unmodified backport of https://github.com/apache/flink/commit/338d0246eccd66fbc5e20d433c8cdd090e91574e to release-1.19
Required to move ahead with Netty 4 upgrade, as discussed in the ML (Option 2):
https://lists.apache.org/thread/6lj5lbg18hz4n9zckn0b89p9mv9nz14g

[BP-1.19][FLINK-36348][test] Fix the Netty shuffle direct memory test by increase the direct memory of TM

---

flink-end-to-end-tests/test-scripts/test_netty_shuffle_memory_control.sh

Unmodified backport of https://github.com/apache/flink/commit/338d0246eccd66fbc5e20d433c8cdd090e91574e to release-1.19
Required to move ahead with Netty 4 upgrade, as discussed in the ML (Option 2):
https://lists.apache.org/thread/6lj5lbg18hz4n9zckn0b89p9mv9nz14g

[BP-1.20][FLINK-36348][test] Fix the Netty shuffle direct memory test by increase the direct memory of TM

---

flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PartitionedFileWriteReadTest.java

This PR improves the `PartitionedFileWriteReadTest`. The test now removes partition files after it finishes. 
- Call `partitionedFile.deleteQuietly();` after test finishes. 
With the patch I confirm that the partition files are removed. 
This PR only contains test changes.

[FLINK-37182][tests] Remove temp partition files created during test. 

---

flink-clients/src/main/java/org/apache/flink/client/program/DefaultPackagedProgramRetriever.java
flink-clients/src/test/java/org/apache/flink/client/program/DefaultPackagedProgramRetrieverITCase.java
flink-clients/src/test/java/org/apache/flink/client/testjar/ClasspathProviderExtension.java

When we switched from using Files.list to Files.walk to determine the classpath for usrlib, we stopped following symbolic links automatically. By adding an option to the Files.walk method we once again follow symbolic links.
- Symbolic links are once again being followed in usrlib
- *Added red-green test for an usrlib with symlinks* …

[FLINK-37183][clients] Fix symbolic links not being followed in "usrlib"

---

flink-dist/src/main/resources/META-INF/NOTICE
flink-state-backends/flink-statebackend-forst/pom.xml
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java

In #25732 we join the async background threads of ForSt to avoid deadlock when JVM quit. That is an incomplete solution which is also problematic. The background threads are shared among multiple ForSt instances, meaning that simply join those threads may cause background job unfinished in other instances.
The ForSt project has investigated the root cause and gave a solution (https://github.com/ververica/ForSt/pull/30). Thus we should bump the depended ForSt version and revert the thread joining in Flink.
- Bump ForSt version to 0.1.6
- Revert the change of background thread joining
This change is already covered by IT case `ForStStateBackendV2Test`. If it can normally exit then the problem solved. …

[FLINK-36838][state/forst] Fix the deadlock when quit forst state backend

---

flink-dist/src/main/resources/META-INF/NOTICE
flink-state-backends/flink-statebackend-forst/pom.xml
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java

This is a backport PR to 2.0 for #26053 
In #25732 we join the async background threads of ForSt to avoid deadlock when JVM quit. That is an incomplete solution which is also problematic. The background threads are shared among multiple ForSt instances, meaning that simply join those threads may cause background job unfinished in other instances.
The ForSt project has investigated the root cause and gave a solution (https://github.com/ververica/ForSt/pull/30). Thus we should bump the depended ForSt version and revert the thread joining in Flink.
- Bump ForSt version to 0.1.6
- Revert the change of background thread joining
This change is already covered by IT case `ForStStateBackendV2Test`. If it can normally exit then the problem solved. …

[BP-2.0][FLINK-36838][state/forst] Fix the deadlock when quit forst state backend

---

docs/content/docs/deployment/memory/mem_tuning.md

Add some guidance in the Flink docs about Netty4 memory and performance configs.
Doc change

[FLINK-37099][docs] Document memory/performance considerations and config possibilities for Netty4

---

flink-end-to-end-tests/test-scripts/test_netty_shuffle_memory_control.sh

Fixes the test executed by `test_netty_shuffle_memory_control.sh` that can possibly fail the CI in case Netty4 cannot reserve enough memory, hence Pekko is not able to start up.
- Reverted the commit backported from the 2.0 branch, which I believe invalidates the purpose of this test case.
- Increased the off-heap memory from 7BM to 12MB, which according to local testing has to be enough to stabilize the CI execution.
Existing test should succeed consistently in CI. …

[1.19][FLINK-37100][tests] Fix `test_netty_shuffle_memory_control.sh` with Netty4 RPC

---

flink-end-to-end-tests/test-scripts/test_netty_shuffle_memory_control.sh

Fixes the test executed by `test_netty_shuffle_memory_control.sh` that can possibly fail the CI in case Netty4 cannot reserve enough memory, hence Pekko is not able to start up.
- Reverted the commit backported from the 2.0 branch, which I believe invalidates the purpose of this test case.
- Increased the off-heap memory from 7BM to 12MB, which according to local testing has to be enough to stabilize the CI execution.
Existing test should succeed consistently in CI. …

[1.20][FLINK-37100][tests] Fix `test_netty_shuffle_memory_control.sh` with Netty4 RPC

---

flink-datastream/src/main/java/org/apache/flink/datastream/impl/operators/BaseKeyedProcessOperator.java
flink-datastream/src/main/java/org/apache/flink/datastream/impl/operators/BaseKeyedTwoInputNonBroadcastProcessOperator.java
flink-datastream/src/main/java/org/apache/flink/datastream/impl/operators/BaseKeyedTwoOutputProcessOperator.java
flink-datastream/src/main/java/org/apache/flink/datastream/impl/operators/KeyedTwoInputBroadcastProcessOperator.java
flink-datastream/src/test/java/org/apache/flink/datastream/impl/context/DefaultStateManagerTest.java
flink-datastream/src/test/java/org/apache/flink/datastream/impl/operators/KeyedProcessOperatorTest.java
flink-datastream/src/test/java/org/apache/flink/datastream/impl/operators/KeyedTwoInputBroadcastProcessOperatorTest.java
flink-datastream/src/test/java/org/apache/flink/datastream/impl/operators/KeyedTwoInputNonBroadcastProcessOperatorTest.java
flink-datastream/src/test/java/org/apache/flink/datastream/impl/operators/KeyedTwoOutputProcessOperatorTest.java
flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/input/KeyedStateInputFormatTest.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AsyncStateProcessing.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/operators/AsyncIntervalJoinOperatorTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/util/asyncprocessing/AsyncKeyedTwoInputStreamOperatorTestHarness.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/join/stream/StreamingJoinOperatorTestBase.java

There lacks a hook to notify a new key is selected in async state operators. Thus the Datastream V2 keyed operators cannot work properly. This PR provides a `newKeySelected` and ensures this is properly implemented in Datastream V2 operators.
- Add `newKeySelected` in both `AbstractAsyncStateStreamOperator` and `AbstractAsyncStateStreamOperatorV2`
- Implement `newKeySelected` in Datastream V2 operators.
- Change related operator tests. …

[FLINK-37208][Runtime] Properly notify a new key is selected for async state operators

---

docs/setup_docs.sh

*Fix the build documentation pipeline issue*
Use `cp` to replace `rsync` for local docs coping. 
If we persist in using rsync, should update the https://github.com/zentol/flink-ci-docker repo to install rsync. But I think there's nothing wrong with cp for this scenario. Feel free to revert this If you updated the `flink-ci-docker` image.
- * Use cp to sync local docs* …

[FLINK-37196][docs] Use cp to sync local docs

---

.github/workflows/docs.sh

Fix the build issue: https://github.com/apache/flink/actions/runs/12942648074/job/36100724287#step:5:3199
Should also updated for `release-2.0` branch.

[FLINK-37196][docs] Use JDK17 to run documentation build

---

mvnw

The maven command is failing in the following way due to a wrongly working MacOS tool called sha256sum:
```
Running `/Users/gaborsomogyi/flink/mvnw`...
Error: Failed to validate Maven wrapper SHA-256, your Maven wrapper might be compromised.
Investigate or delete /Users/gaborsomogyi/flink/.mvn/wrapper/maven-wrapper.jar to attempt a clean download.
If you updated your Maven version, you need to update the specified wrapperSha256Sum property.
```
The issue is that `sha256sum` is not working as described in the manual:
```
In all cases, each file listed on the command line is processed separately.  If no files are listed on the command line, or a file name is given as -, input is taken from stdin instead.
```
Manual test:
```
$ echo …
```

[FLINK-37181][build] Fix MacOS sha256sum tool compile error

---

flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/application/ScriptRunner.java
pom.xml

*YARN deployment doesn't the directories as flink-dist does. Actually, it uses the following structures*
```
.
└── ohmeatball
├── appcache
│   └── application_1737534562065_0001
│       ├── container_1737534562065_0001_01_000001
│       │   ├── lib
│       │   ├── opt
│       │   ├── plugins
│       │   │   ├── external-resource-gpu
│       │   │   ├── metrics-datadog
│       │   │   ├── metrics-graphite
│       │   │   ├── metrics-influx
│       │   │   ├── metrics-jmx
│       │   │   ├── metrics-otel
│       │   │   ├── metrics-prometheus
│       │   │   ├── metrics-slf4j
│       │   │   └── metrics-statsd
│       │   └── tmp
│       └── filecache
│           ├── 10
└── filecache
```
Actually the config.yaml is at the working directory(container_1737534562065_0001_01_000001). So …

[FLINK-37138][sql-gateway] Fix failed SqlYARNApplicationITCase in hadoop3 profile

---

flink-datastream/src/main/java/org/apache/flink/datastream/impl/operators/BaseKeyedProcessOperator.java
flink-datastream/src/main/java/org/apache/flink/datastream/impl/operators/BaseKeyedTwoInputNonBroadcastProcessOperator.java
flink-datastream/src/main/java/org/apache/flink/datastream/impl/operators/BaseKeyedTwoOutputProcessOperator.java
flink-datastream/src/main/java/org/apache/flink/datastream/impl/operators/KeyedTwoInputBroadcastProcessOperator.java
flink-datastream/src/test/java/org/apache/flink/datastream/impl/context/DefaultStateManagerTest.java
flink-datastream/src/test/java/org/apache/flink/datastream/impl/operators/KeyedProcessOperatorTest.java
flink-datastream/src/test/java/org/apache/flink/datastream/impl/operators/KeyedTwoInputBroadcastProcessOperatorTest.java
flink-datastream/src/test/java/org/apache/flink/datastream/impl/operators/KeyedTwoInputNonBroadcastProcessOperatorTest.java
flink-datastream/src/test/java/org/apache/flink/datastream/impl/operators/KeyedTwoOutputProcessOperatorTest.java
flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/input/KeyedStateInputFormatTest.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/asyncprocessing/AsyncStateProcessing.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/operators/AsyncIntervalJoinOperatorTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/util/asyncprocessing/AsyncKeyedTwoInputStreamOperatorTestHarness.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/join/stream/StreamingJoinOperatorTestBase.java

This is a backport PR to 2.0 for #26063 
There lacks a hook to notify a new key is selected in async state operators. Thus the Datastream V2 keyed operators cannot work properly. This PR provides a `newKeySelected` and ensures this is properly implemented in Datastream V2 operators.
- Add `newKeySelected` in both `AbstractAsyncStateStreamOperator` and `AbstractAsyncStateStreamOperatorV2`
- Implement `newKeySelected` in Datastream V2 operators.
- Change related operator tests. …

[BP-2.0][FLINK-37208][Runtime] Properly notify a new key is selected for async state operators

---

flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java
flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotTable.java
flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotTableImpl.java
flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotTableImplTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/slot/TestingTaskSlotTable.java
flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/slot/ThreadSafeTaskSlotTable.java

Minor refactoring to connect the reason of the `SlotAllocationException` with the exception itself (rather than having a generic error message and the actual reason somewhere else in the logs).
* Moves `SlotAllocationException` throwing into `TaskSlotTableImpl#allocateSlot`
* Adjusted available tests accordingly …

[FLINK-37215][runtime] Moves SlotAllocationException into TaskSlotTableImpl

---

docs/content.zh/docs/ops/state/state_backends.md
docs/content/docs/ops/state/state_backends.md

The default state backend on Flink is `HashMapStateBackend`. However, in the related chapter on the doc, it was stated as `jobmanager`.
**Expected** keyword as the default state backend: `HashMapStateBackend`
**Actual** keyword given as the default state backend: `jobmanager`
The Chinese doc version has not been updated in order not to make a mistake. It also needed to be updated.

[hotfix] [docs] Fix typo on the default state backend name on 'Configuring a State Backend' section.

---

docs/content.zh/docs/ops/state/state_backends.md
docs/content/docs/ops/state/state_backends.md

Revert "[hotfix] [docs] Fix typo on the default state backend name on 'Configuring a State Backend' section."

---

pom.xml

`@PublicEvolving` checks are supposed to be kept enabled on release-x.y branches. The fact that it was disabled on `release-1.20` led to PRs CI skipping the check and two commits that break binary compatibility being merged:
https://issues.apache.org/jira/browse/FLINK-37098?focusedCommentId=17921143&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17921143
https://issues.apache.org/jira/browse/FLINK-35886?focusedCommentId=17916974&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17916974
The japicmp reference version has also not been properly updated after the 1.20.0 release.

[hotfix] Enable @PublicEvolving japicmp checks

---

flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotTableImplTest.java

Refactors test to use proper Executor (rather than `directExecutor`). This allows for callbacks to be scheduled on the main thread in production code.
* Introduces single-thread executor as the main thread

[FLINK-37214][runtime] Refactors test to use proper Executor service for the main thread

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/adaptor/AsyncKeyedStateBackendAdaptor.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionInternalTimeService.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionInternalTimeServiceManager.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionInternalTimeServiceWithAsyncState.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionInternalTimeServiceWithAsyncStateTest.java

We have ship two abstract stream operators for async state processing, where a async timer service (manager) is introduced. Actually these operators can run in sync mode, this is especially the case for batch execution mode. Currently there is an issue when initializing batching timer service in those operators. This PR fixes this to enable batch execution for operators with async state.
- Introduce `BatchExecutionInternalTimeServiceWithAsyncState` and properly create this in async state operators.
This change added test `BatchExecutionInternalTimeServiceWithAsyncStateTest`. …

[FLINK-37206][Runtime] Fix initialization of batching timer service in async state operators

---

docs/data/sql_functions.yml
docs/data/sql_functions_zh.yml

We currently have no examples for some functions in the documentation. 5 examples of these are unhex, btrim, percentile, translate and ETL. This PR adds examples to these.
Upon merging, I'll create another ticket for the chinese translation. 
- Added one example for each of the functions
- Checked docs locally

[FLINK-37239][docs] Add examples for unhex, btrim, translate, elt and percentile

---

flink-runtime/src/test/java/org/apache/flink/runtime/state/TestTaskStateManager.java
tools/maven/checkstyle.xml

Add this to checkstyle conf 
it was tere before, however for some reason absolute names appeared in code (not in imports)

[hotfix] Do not use `org.jetbrains.annotations.Nullable`

---

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Executing.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/FailureResultUtil.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Restarting.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StateTransitions.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/ExecutingTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/MockRestartingContext.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/RestartingTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StopWithSavepointTest.java
flink-tests/src/test/java/org/apache/flink/test/scheduling/UpdateJobResourceRequirementsITCase.java

The PR fixes the issue with the rescale state transition short cut that was introduced in [FLIP-472](https://cwiki.apache.org/confluence/display/FLINK/FLIP-472%3A+Aligning+timeout+logic+in+the+AdaptiveScheduler%27s+WaitingForResources+and+Executing+states) where the `WaitingForRequirements` state is omitted and the transition goes directly from the Restarting state to the `CreatingExecutionGraph` state.
- Pass the available VertexParallelism that lead to the rescale decision to the `Restarting` state and check when the job is cancelled whether that parallelism has changed. …

[FLINK-37232][runtime] Fix for broken synchronization assumption on the AdaptiveScheduler's side introduced by FLIP-272

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/adaptor/AsyncKeyedStateBackendAdaptor.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionInternalTimeService.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionInternalTimeServiceManager.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionInternalTimeServiceWithAsyncState.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionInternalTimeServiceWithAsyncStateTest.java

This is a backport PR to 2.0 for #26071
We have ship two abstract stream operators for async state processing, where a async timer service (manager) is introduced. Actually these operators can run in sync mode, this is especially the case for batch execution mode. Currently there is an issue when initializing batching timer service in those operators. This PR fixes this to enable batch execution for operators with async state.
- Introduce `BatchExecutionInternalTimeServiceWithAsyncState` and properly create this in async state operators.
This change added test `BatchExecutionInternalTimeServiceWithAsyncStateTest`.
- The runtime …

[BP-2.0][FLINK-37206][Runtime] Fix initialization of batching timer service in async state operators

---

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Executing.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/FailureResultUtil.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/Restarting.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/StateTransitions.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/ExecutingTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/MockRestartingContext.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/RestartingTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StopWithSavepointTest.java
flink-tests/src/test/java/org/apache/flink/test/scheduling/UpdateJobResourceRequirementsITCase.java

This is a 2.0 backport of parent PR #26088

[BP-2.0][FLINK-37232][runtime] Fix for broken synchronization assumption on the AdaptiveScheduler's side introduced by FLIP-272

---

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/datatransfer/CopyDataTransferStrategy.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/datatransfer/DataTransferStrategyBuilder.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/datatransfer/ForStStateDataTransfer.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/datatransfer/ReusableDataTransferStrategy.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystem.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/FileMappingManager.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/FileOwnershipDecider.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/restore/ForStIncrementalRestoreOperation.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/snapshot/ForStIncrementalSnapshotStrategy.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/snapshot/ForStNativeFullSnapshotStrategy.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStResourceContainerTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/datatransfer/DataTransferStrategyTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/datatransfer/ForStStateDataTransferTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/FileMappingManagerTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystemTest.java

This pull request addresses several bugs in ForSt that may prevent proper file reuse, leading to slower or failed snapshot and restoration operations.
- Make ```DataTransferStrategyBuilder``` function properly.
- Use ```URI``` to tell whether two ```FileSystem``` are the same.
- Use 'Reuse' strategy for Restoration only in CLAIM mode
- Use 'Reuse' strategy for Snapshot only when ```SharingFilesStrategy``` is 'FORWARD_BACKWARD'
- Ensure we correctly distinguish between ```dbFilePath``` and ```realSourcePath```.
- During Snapshots: do not copy file if it is already owned by JM. …

[FLINK-37021][state/forst] Fix incorrect paths when reusing files for checkpoints.

---

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/datatransfer/CopyDataTransferStrategy.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/datatransfer/DataTransferStrategyBuilder.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/datatransfer/ForStStateDataTransfer.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/datatransfer/ReusableDataTransferStrategy.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystem.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/FileMappingManager.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/FileOwnershipDecider.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/restore/ForStIncrementalRestoreOperation.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/snapshot/ForStIncrementalSnapshotStrategy.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/snapshot/ForStNativeFullSnapshotStrategy.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStResourceContainerTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/datatransfer/DataTransferStrategyTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/datatransfer/ForStStateDataTransferTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/FileMappingManagerTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystemTest.java

This pull request addresses several bugs in ForSt that may prevent proper file reuse, leading to slower or failed snapshot and restoration operations.
- Make ```DataTransferStrategyBuilder``` function properly.
- Use ```URI``` to tell whether two ```FileSystem``` are the same.
- Use 'Reuse' strategy for Restoration only in CLAIM mode
- Use 'Reuse' strategy for Snapshot only when ```SharingFilesStrategy``` is 'FORWARD_BACKWARD'
- Ensure we correctly distinguish between ```dbFilePath``` and ```realSourcePath```.
- During Snapshots: do not copy file if it is already owned by JM. …

[BP-2.0][FLINK-37021][state/forst] Fix incorrect paths when reusing and creating files.

---

flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/SqlClientTest.java
flink-table/flink-sql-client/src/test/resources/nexmark.sql
flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/context/EnvironmentReusableInMemoryCatalog.java
flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/context/SessionContext.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/QueryOperationCatalogView.java

After FLINK-37098, there is a bug when submitting jobs via sql client. This PR fixes this.
- A test verifying the sql client with complex sql job.
- A fix that not reuse views across TableEnvironments in SQL client
This change has added test named `testExecuteNexmark`

[FLINK-37222] Do not reuse views across TableEnvironments in SQL client

---

flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/SqlClientTest.java
flink-table/flink-sql-client/src/test/resources/nexmark.sql
flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/context/EnvironmentReusableInMemoryCatalog.java
flink-table/flink-sql-gateway/src/main/java/org/apache/flink/table/gateway/service/context/SessionContext.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/QueryOperationCatalogView.java

After FLINK-37098, there is a bug when submitting jobs via sql client. This PR fixes this.
- A test verifying the sql client with complex sql job.
- A fix that not reuse views across TableEnvironments in SQL client
This change has added test named `testExecuteNexmark`

[BP-2.0][FLINK-37222] Do not reuse views across TableEnvironments in SQL client

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/FlinkCalcMergeRule.java

This is a trivial fix for string comparison in `FlinkCalcMergeRule`.  
However it doesn't actually affect the optimization results, so no new cases were added to the fix.
But we can verify this detail by debugging `FlinkCalcMergeRule`'s optimization process with the following case(add to `FlinkCalcMergeRuleTest`):
```scala
@Test
def testCalcMergeWithTrivialCalc(): Unit = {
val testTable = "MyTable"
val relBuilder = util.getPlanner.plannerContext.createRelBuilder()
val flinkLogicalTraits = relBuilder.getCluster.traitSetOf(FlinkConventions.LOGICAL)
val table = relBuilder.getRelOptSchema
.asInstanceOf[CalciteCatalogReader]
.getTable(ImmutableList.of(testTable))
.asInstanceOf[FlinkPreparingTableBase]
val flinkLogicalTableScan = new FlinkLogicalDataStreamTableScan(
relBuilder.getCluster, …
```

[hotfix][table-planner] Use equals instead of '==' to compare digests in FlinkCalcMergeRule

---

flink-python/pyflink/fn_execution/beam/beam_sdk_worker_main.py

*This pull request fixes the state cache behavior during bump beam version. It has changed the state cache strategy from size based to bytes based since Beam 2.42.0 (See https://github.com/apache/beam/pull/22924 for more details). We should also support memory based state cache in the long term. Before that, we should correct the behavior which seems broken after bumping the Beam version. It may cause the state cache continuously increase and finally cause the job OOM.*
Please make sure both new and modified tests in this PR follow [the conventions for tests …

[FLINK-37205][python] Correct the state cache behavior during bump beam version

---

flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/JsonFunctionsITCase.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/SqlJsonUtils.java

backport of https://github.com/apache/flink/commit/90508a00bb310d26f9be245098cda9192647ab14

[FLINK-35687] JSON_QUERY should return a well formatted nested objects/arrays for ARRAY<STRING> (#24976)

---

flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java
flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/TestingSlotPoolServiceBuilder.java

The `SchedulerNG#closeAsync` might return a future that's completed in a IO thread because both, the [AdaptiveScheduler:581](https://github.com/apache/flink/blob/d4e0084649c019c536ee1e44bab15c8eca01bf13/flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java#L581) and the [SchedulerBase:674](https://github.com/apache/flink/blob/d4e0084649c019c536ee1e44bab15c8eca01bf13/flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java#L674) compose the result future of the checkpointsCleaner. This can result in the connection close operation being executed concurrently while the `JobMaster` is shut down. There's a race condition where the `ResourceManager` might be able to sent a `JobMaster#disconnectResourceManager` back to the …

[FLINK-34227][runtime] Fixes concurrency issue in JobMaster shutdown

---

flink-datastream/src/main/java/org/apache/flink/datastream/impl/stream/KeyedPartitionStreamImpl.java
flink-datastream/src/main/java/org/apache/flink/datastream/impl/utils/StreamUtils.java
flink-datastream/src/main/java/org/apache/flink/streaming/runtime/translators/DataStreamV2SinkTransformationTranslator.java
flink-tests/src/test/java/org/apache/flink/test/streaming/api/datastream/extension/join/JoinITCase.java

Fix two bugs of DataStream V2:
1. When joining two tuple DataStreams using JoinExtension, an exception is thrown "Tuple needs to be parameterized by using generics".
2. DSv2 does not support adding a FileSink, even when the FileSink does not include committing topology.
1. Correct usage of TypeExtractor in JoinExtension 
2. Support FileSink in DSv2 if the FileSink does not add committing topology
3. Add a IT test case
Added a test case: org.apache.flink.test.streaming.api.datastream.extension.join.JoinITCase#testJoinWithTuple …

[FLINK-37264][datastream] Fix bugs of DataStream V2

---

flink-core/src/main/java/org/apache/flink/util/concurrent/FutureUtils.java
flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/TestingSlotPoolServiceBuilder.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/DefaultSchedulerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveBatchSchedulerTest.java

This is a combined PR of the two parent PRs https://github.com/apache/flink/pull/24489 and https://github.com/apache/flink/pull/26095
There was one minor conflict in `DefaultSchedulerBuilder` that needed to be resolved. It was caused by the fact that `AdaptiveBatchSchedulerFactory#createInstance` was overloaded with a testing implementation in 1.20 which is not present in 1.19.
Additionally, the rpcTimeout issue from the 1.20 backport needed to be resolved.

[BP-1.19][FLINK-34227][runtime] Makes the JobMaster close procedure more robust to IO thread leaks from the scheduler side

---

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ByteBufferReadableFSDataInputStream.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ByteBufferWritableFSDataOutputStream.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystem.java

Remove the `@Experimental` annotation for inner classes. Since 2.0 has not been released and this PR will backport to 2.0 before the release, we are safe to remove directly.

[hotfix] Remove inappropriate annotation in `flink-statebackend-forst`

---

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ByteBufferReadableFSDataInputStream.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ByteBufferWritableFSDataOutputStream.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystem.java

Remove the `@Experimental` annotation for inner classes. Since 2.0 has not been released and this PR will backport to 2.0 before the release, we are safe to remove directly.

[BP-2.0][hotfix] Remove inappropriate annotation in `flink-statebackend-forst`

---

docs/content.zh/docs/dev/table/materialized-table/statements.md
docs/content/docs/dev/table/materialized-table/statements.md

*Add docs for alter materialized table as query*
- *Add docs for alter materialized table as query*
This change only contains document change. 

[FLINK-37087][doc] Add docs for alter materialized table as query

---

flink-core/src/main/java/org/apache/flink/api/common/functions/RuntimeContext.java
flink-core/src/main/java/org/apache/flink/api/common/functions/util/AbstractRuntimeUDFContext.java
flink-core/src/main/java/org/apache/flink/api/common/state/v2/AggregatingStateDescriptor.java
flink-core/src/main/java/org/apache/flink/api/common/state/v2/ListStateDescriptor.java
flink-core/src/main/java/org/apache/flink/api/common/state/v2/MapStateDescriptor.java
flink-core/src/main/java/org/apache/flink/api/common/state/v2/ReducingStateDescriptor.java
flink-core/src/main/java/org/apache/flink/api/common/state/v2/StateDescriptor.java
flink-core/src/main/java/org/apache/flink/api/common/state/v2/StateSerializerReference.java
flink-core/src/main/java/org/apache/flink/api/common/state/v2/ValueStateDescriptor.java
flink-libraries/flink-cep/src/main/java/org/apache/flink/cep/operator/CepRuntimeContext.java
flink-libraries/flink-cep/src/test/java/org/apache/flink/cep/operator/CepRuntimeContextTest.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/runtime/SavepointRuntimeContext.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamingRuntimeContext.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/async/RichAsyncFunction.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/functions/async/RichAsyncFunctionTest.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/aggregate/async/AsyncStateGroupAggFunction.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/asyncprocessing/AsyncStateDeduplicateFunctionBase.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/async/AbstractAsyncStateTopNFunction.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/async/AsyncStateAppendOnlyTopNFunction.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/async/AsyncStateFastTop1Function.java

We have introduced the state v2 creating methods in `StreamingRuntimeContext`, but these methods have not exposed to `RuntimeContext`. Thus user may not be able to access the state via `getRuntimeContext().getState`. 
- Add Add constructors for state v2 descriptors that accept type class
- Add state access interfaces in `RuntimeContext`
- Does this …

[FLINK-37276] Add missing state v2 access interfaces in `RuntimeContext`

---

flink-core/src/main/java/org/apache/flink/api/common/functions/RuntimeContext.java
flink-core/src/main/java/org/apache/flink/api/common/functions/util/AbstractRuntimeUDFContext.java
flink-core/src/main/java/org/apache/flink/api/common/state/v2/AggregatingStateDescriptor.java
flink-core/src/main/java/org/apache/flink/api/common/state/v2/ListStateDescriptor.java
flink-core/src/main/java/org/apache/flink/api/common/state/v2/MapStateDescriptor.java
flink-core/src/main/java/org/apache/flink/api/common/state/v2/ReducingStateDescriptor.java
flink-core/src/main/java/org/apache/flink/api/common/state/v2/StateDescriptor.java
flink-core/src/main/java/org/apache/flink/api/common/state/v2/StateSerializerReference.java
flink-core/src/main/java/org/apache/flink/api/common/state/v2/ValueStateDescriptor.java
flink-libraries/flink-cep/src/main/java/org/apache/flink/cep/operator/CepRuntimeContext.java
flink-libraries/flink-cep/src/test/java/org/apache/flink/cep/operator/CepRuntimeContextTest.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/runtime/SavepointRuntimeContext.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamingRuntimeContext.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/async/RichAsyncFunction.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/functions/async/RichAsyncFunctionTest.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/aggregate/async/AsyncStateGroupAggFunction.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/deduplicate/asyncprocessing/AsyncStateDeduplicateFunctionBase.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/async/AbstractAsyncStateTopNFunction.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/async/AsyncStateAppendOnlyTopNFunction.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/rank/async/AsyncStateFastTop1Function.java

Backport to 2.0 for #26120 
We have introduced the state v2 creating methods in `StreamingRuntimeContext`, but these methods have not exposed to `RuntimeContext`. Thus user may not be able to access the state via `getRuntimeContext().getState`. 
- Add Add constructors for state v2 descriptors that accept type class
- Add state access interfaces in `RuntimeContext` …

[BP-2.0][FLINK-37276] Add missing state v2 access interfaces in `RuntimeContext`

---

docs/content.zh/docs/dev/table/materialized-table/statements.md
docs/content/docs/dev/table/materialized-table/statements.md

BP https://github.com/apache/flink/pull/26064
*Add docs for alter materialized table as query*
- *Add docs for alter materialized table as query*
This change only contains document change. 

[BP-2.0][FLINK-37087][doc] Add docs for alter materialized table as query

---

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java
flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogManagerTest.java

This pull request fix a bug which a catalog that failed validation due to no type still exists in catalogStoreHolder.
And this catalog you cannot USE, ALTER.
- fix a bug which a catalog that failed validation due to no type still exists in catalogStoreHolder. …

[FLINK-37093][table] Fix catalog that failed validation due to no type still exists in catalogStoreHolder

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/annotation/StateHint.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/ProcessTableFunction.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/UserDefinedFunctionHelper.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/BaseMappingExtractor.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/ExtractionUtils.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/FunctionResultTemplate.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/FunctionTemplate.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/DefaultStateTypeStrategy.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/StateTypeStrategy.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/TypeInference.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/TypeInferenceUtil.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/extraction/TypeInferenceExtractorTest.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecProcessTableFunction.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/EqualiserCodeGenerator.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/ProcessTableRunnerGenerator.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/BridgingFunctionGenUtil.scala
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/ProcessTableFunctionSemanticTests.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/ProcessTableFunctionTestPrograms.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/ProcessTableFunctionTestUtils.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/data/conversion/RowRowConverter.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/generated/ProcessTableRunner.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/process/ProcessTableOperator.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/process/ProcessTableOperatorFactory.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/process/RuntimeStateInfo.java

This adds support for value state and thus enables stateful PTFs.
For each function call:
- the state is read from Flink
- converted into external data structure
- evaluated
- converted into internal data structure (if not cleared)
- the state is written into Flink
State TTL is considered per-state or globally.
- `TypeInferenceUtil` refactored to fully support state entries
- `ProcessTableOperator` (including code generation) updated
This change added tests and can be verified as follows: `ProcessTableFunctionSemanticTests` …

[FLINK-37219][table] Support value state in PTFs

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecLegacyTableSourceScan.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/wmassigners/PunctuatedWatermarkAssignerWrapper.java

This PR propose to rename `PunctuatedWatermarkStrategyWrapper` with `PunctuatedWatermarkAssignerWrapper`.
Currently, `PeriodicWatermarkAssignerWrapper` wrappers `PeriodicWatermarkAssigner` and `PunctuatedWatermarkStrategyWrapper` wrappers `PunctuatedWatermarkAssigner`.
I think we should unify the naming specification.
Rename PunctuatedWatermarkStrategyWrapper with PunctuatedWatermarkAssignerWrapper
This change is a trivial code cleanup without any test coverage. …

[MINOR] Rename PunctuatedWatermarkStrategyWrapper with PunctuatedWatermarkAssignerWrapper

---

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/datatransfer/DataTransferStrategyBuilder.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/datatransfer/DataTransferStrategyTest.java

To support ForStDB reusing files when restoring in LEGACY mode.
- Make ```DataTransferStrategyBuilder``` create ```ReusableDataTransferStrategy``` when ```recoveryClaimMode == RecoveryClaimMode.LEGACY```
This change is already covered by existing tests, such as ```DataTransferStrategyTest#testBuildingStrategyAsExpected```.

[FLINK-37021][state/forst] Support reusing files in LEGACY recovery mode

---

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateBackend.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateBackendConfigTest.java

The `ForStStateBackend` did not override the `supportsSavepointFormat`, which means it gives the wrong flag. We should fix this.
- Return true in `supportsSavepointFormat` when it is `NATIVE` format
This change is a trivial rework, a simple test is added.

[FLINK-37301][state/forst] Fix wrong flag returned by `ForStStateBackend#supportsSavepointFormat`

---

docs/content.zh/docs/deployment/resource-providers/standalone/docker.md
docs/content/docs/deployment/resource-providers/standalone/docker.md
docs/content/docs/dev/python/faq.md
docs/static/downloads/setup-pyflink-virtual-env.sh
flink-end-to-end-tests/test-scripts/test_kubernetes_pyflink_application.sh
flink-end-to-end-tests/test-scripts/test_pyflink.sh
flink-end-to-end-tests/test-scripts/test_pyflink_yarn.sh
flink-python/README.md
flink-python/dev/build-wheels.sh
flink-python/dev/dev-requirements.txt
flink-python/dev/lint-python.sh
flink-python/pyproject.toml
tools/azure-pipelines/build-python-wheels.yml
tools/azure-pipelines/e2e-template.yml
tools/releasing/create_binary_release.sh

Given the issues raised in https://issues.apache.org/jira/browse/LEGAL-688, we've decided to move away from using conda. `conda` is being used in Flink in the following ways:
- Setting up PyFlink developer environments.
- Setting up a range of environments with different Python versions (3.8, 3.9, 3.10, 3.11) to both validate the Flink apis over those versions, and to build Python wheels for those versions.
- Setting up a Python environment for use in building the binary releases.
- Setting up a Python environment or the PyFlink, PyFlink Yarn and PyFlink Kubernetes end-to-end tests.
To summarise, conda is largely being used for the creation of Python virtual environments for both developers and CI. This PR replaces conda with [uv](https://docs.astral.sh/uv/), a fast Python package and …

[FLINK-36900][python] Migrate from conda to uv for managing Python environments for PyFlink

---

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/datatransfer/DataTransferStrategyBuilder.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/datatransfer/DataTransferStrategyTest.java

To support ForStDB reusing files when restoring in LEGACY mode.
- Make ```DataTransferStrategyBuilder``` create ```ReusableDataTransferStrategy``` when ```recoveryClaimMode == RecoveryClaimMode.LEGACY```
This change is already covered by existing tests, such as ```DataTransferStrategyTest#testBuildingStrategyAsExpected```.

[BP-2.0][FLINK-37021][state/forst] Support reusing files in LEGACY recovery mode

---

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateBackend.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateBackendConfigTest.java

The `ForStStateBackend` did not override the `supportsSavepointFormat`, which means it gives the wrong flag. We should fix this.
- Return true in `supportsSavepointFormat` when it is `NATIVE` format
This change is a trivial rework, a simple test is added.

[BP-2.0][FLINK-37301][state/forst] Fix wrong flag returned by `ForStStateBackend#supportsSavepointFormat`

---

docs/layouts/shortcodes/generated/forst_configuration.html
docs/layouts/shortcodes/generated/state_backend_forst_section.html
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStOptions.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java

Currently, the file cache options `state.backend.forst.cache.reserve-size` and `state.backend.forst.cache.size-based-limit` are long type, which are not readable to users. This PR changes those two options to `MemorySize`.
- Change the option type of those two options to `MemorySize`. …

[hotfix][state/forst] Make file cache options recognize size type

---

docs/content.zh/docs/dev/datastream/fault-tolerance/state_v2.md
docs/content/docs/dev/datastream/fault-tolerance/state_v2.md

Documentation build fails with the following error:
```
Error: error building site: process: readAndProcessContent: "/Users/gaborsomogyi/flink/docs/content.zh/docs/dev/datastream/fault-tolerance/state_v2.md:63:1": failed to extract shortcode: shortcode "tabs" must be closed or self-closed
```
Added missing tab closing.
`./build_docs.sh` …

[FLINK-37312][doc] Add missing closing tab in state_v2.md

---

docs/layouts/shortcodes/generated/forst_configuration.html
docs/layouts/shortcodes/generated/state_backend_forst_section.html
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStOptions.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java

Backport of #26148
Currently, the file cache options `state.backend.forst.cache.reserve-size` and `state.backend.forst.cache.size-based-limit` are long type, which are not readable to users. This PR changes those two options to `MemorySize`.
- Change the option type of those two options to `MemorySize`.
- …

[BP-2.0][hotfix][state/forst] Make file cache options recognize size type

---

flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendTestBase.java

This removes mockito dependency for downstream implementations.

[FLINK-37241][runtime] Remove Mockito usage from StateBackendTestBase.

---

flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/input/KeyedStateInputFormat.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/input/MultiStateKeyIterator.java
flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/input/MultiStateKeyIteratorTest.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/KeyedStateBackend.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/heap/HeapKeyedStateBackend.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendTestUtils.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/ttl/mock/MockKeyedStateBackend.java
flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java
flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/restore/ChangelogMigrationRestoreTarget.java
flink-state-backends/flink-statebackend-common/src/test/java/org/apache/flink/state/common/PeriodicMaterializationManagerTest.java
flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackend.java
flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/iterator/AbstractRocksStateKeysIterator.java
flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/iterator/RocksMultiStateKeysIterator.java
flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/iterator/RocksStateKeysIterator.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionKeyedStateBackend.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/TestStateBackend.java

This is backport of https://github.com/apache/flink/pull/26134.
State processor API with RocksDB is extremely slow because it does the following for key deduplication:
* Get keys from `columnFamility1`
* Get keys from `columnFamility2`
* Iterate over the keys
* Calls `KeyedStateReaderFunction.readKey`
* Removes the key from both column families
Since key removal is slow compared to other operations the overall performance is unacceptable.
Instead of the mentioned method we've migrated to the following:
* Get keys from `columnFamility1`
* Get keys from `columnFamility2`
* Added `RocksMultiStateKeysIterator` which iterates on all column families at the same time in an ordered way
As a result key deduplication happens on iteration time in a streaming manner.
Important note that this change …

[FLINK-37109][state] Improve state processor API key iteration speed

---

docs/content/docs/libs/state_processor_api.md

[FLIP-496](https://cwiki.apache.org/confluence/display/FLINK/FLIP-496%3A+SQL+connector+for+keyed+savepoint+data) has described the SQL connector for keyed savepoint data feature in-depth. In this PR I've added documentation for this functionality.
Add SQL connector documentation for keyed savepoint data.
Built docs locally. …

[FLINK-37310][doc] SQL connector for keyed savepoint data documentation

---

flink-tests/src/test/java/org/apache/flink/test/streaming/api/datastream/WatermarkITCase.java

Fix NPE issue in WatermarkITCase. 
The NPE is because [here](https://github.com/apache/flink/blob/52d6691d2ef98d3a43c611c19e1eb9cc45da834d/flink-tests/src/test/java/org/apache/flink/test/streaming/api/datastream/WatermarkITCase.java#L711-L721), the latter operation (i.e. `receivedWatermarks.computeIfAbsent`) might not be run immediately after the former operation (i.e. `attemptIds.compute`). 
And during the main testing thread, we only wait for [attemptIds size is expected](https://github.com/apache/flink/blob/52d6691d2ef98d3a43c611c19e1eb9cc45da834d/flink-tests/src/test/java/org/apache/flink/test/streaming/api/datastream/WatermarkITCase.java#L156C9-L156C31). So, after the attemptIds size is expected, when we try to verify `assertOperatorReceivedWatermarkValues`, we might get `null` value …

[FLINK-37194][tests] Fix NPE issue in WatermarkITCase

---

flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/canal/CanalJsonDeserializationSchema.java
flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/debezium/DebeziumJsonDeserializationSchema.java
flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/maxwell/MaxwellJsonDeserializationSchema.java
flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/ogg/OggJsonDeserializationSchema.java
flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/canal/CanalJsonSerDeSchemaTest.java
flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/debezium/DebeziumJsonSerDeSchemaTest.java
flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/maxwell/MaxwellJsonSerDerTest.java
flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/ogg/OggJsonSerDeSchemaTest.java

Enabling the ignore-parse-errors parameter does not skip exceptions caused by the format of the emitted data.
- Enabling the ignore-parse-errors parameter does not skip exceptions caused by the format of the emitted data.
- `CanalJsonSerDeSchemaTest#testIgnoreParseErrors`
- `DebeziumJsonSerDeSchemaTest#testIgnoreParseErrors`
- `MaxwellJsonSerDerTest#testIgnoreParseErrors`
- `OggJsonSerDeSchemaTest#testIgnoreParseErrors` …

[FLINK-36549]Fix using the ignore-parse-errors parameter in Debezium/Canal/Maxwell/Ogg JSON results in unexpected data loss

---

docs/setup_hugo.sh

This is a tiny change. `setup_hugo.sh` now installs everything inside the `tar.gz` file into `/usr/local/bin`, but hugo executable is enough. In this PR I've added that filter.
Added a filter to install only hugo executable.
Manually on MacOS and Linux.

[FLINK-37344][doc] setup_hugo.sh now installs the binary only

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecWindowAggregateBase.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/WindowUtil.scala
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/agg/WindowAggregateTest.xml
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/WindowTableFunctionTest.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/agg/WindowAggregateTest.scala
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/window/tvf/slicing/SliceAssigners.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/window/tvf/slicing/TumblingSliceAssignerTest.java

Queries with wrongly defined descriptors should fail during planning, like
```sql
SELECT *
FROM TABLE(
CUMULATE(TABLE MyTable, DESCRIPTOR(rowtime), INTERVAL '0' MINUTE, INTERVAL '0' HOUR));
SELECT *
FROM TABLE(
HOP(TABLE MyTable, DESCRIPTOR(rowtime), INTERVAL '0' MINUTE, INTERVAL '0' MINUTE));
SELECT *
FROM TABLE(TUMBLE(TABLE MyTable, DESCRIPTOR(rowtime), INTERVAL '0' MINUTE));
SELECT *
FROM TABLE(SESSION(TABLE MyTable, DESCRIPTOR(rowtime), INTERVAL '0' MINUTE));
```
`WindowUtil`
`WindowTableFunctionTest.scala` …

[FLINK-37321][table] Make window functions with wrong descriptors fail during planning rather than runtime 

---

flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherManager.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherManagerTest.java

This patch fixes an issue introduced in #25130. In `SplitFetcherManager.close()`, the element queue draining thread was chaining the runnables to the element queue availability future in a tight loop. This causes problem (e.g. OOM, high CPU util) when the fetcher threads do not shutdown quickly.
This patch changes the tight async loop to a blocking loop.
This patch changes the tight async loop to a blocking loop.
This change added a unit test. However, that unit test is kind of testing against the implementation instead of the behavior. But given we are fixing an interal impl issue, this might be necessary.
- The runtime …

[FLINK-36585][connector / common] SplitFetcherManager.close() should not chain runnables to the element queue future in a tight loop.

---

pom.xml

I download the heap dump file in failed build. But don't find any suspicious leak objects.
Slightly increase the memory limit to help troubleshoot this problem.

[FLINK-35810][test] increase unittest Xmx to debug FLINK-35810

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/adaptive/AdaptiveJoinOperatorGenerator.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/strategy/AdaptiveBroadcastJoinOptimizationStrategy.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/strategy/PostProcessAdaptiveJoinStrategy.java

According to the design, we need to change the original forward partitioner to a rescale partitioner after the adaptive broadcast join takes effect. Accordingly, we need to use ForwardForUnspecifiedPartitioner to achieve this purpose.
- *Use ForwardForUnspecifiedPartitioner when adaptive broadcast join takes effect*
This change is already covered by existing tests, such as DefaultStreamGraphContextTest#testModifyStreamEdge.
- The …

[FLINK-37333][runtime] Use ForwardForUnspecifiedPartitioner when adaptive broadcast join takes effect.

---

flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/JobGraph.java
flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/JobVertex.java

Remove the redundant JobVertex#hasNoConnectedInputs and use JobVertex#isInputVertex instead.
Remove the redundant JobVertex#hasNoConnectedInputs and use JobVertex#isInputVertex instead. …

[hotfix][runtime] Remove the redundant JobVertex#hasNoConnectedInputs and use JobVertex#isInputVertex instead.

---

tools/releasing/update_japicmp_configuration.sh

Mac uses BSD sed that requires an explicit extension for `-i` option. This works universally for both GNU and BSD sed. 
I believe it previously caused issues with `@PublicEvolving` javacmp exclusions not being correctly removed after the release which led to incompatible changes being merged. Without the fix, the pom file gets modified incompletely, with an error message that is easy to miss
`sed: 1: "../pom.xml": invalid command code . `
Note: to reproduce current erroneous behavior, put a couple of lines between the `MARKER:` comments in pom.xml

[hotfix] Fix post-release japicmp update script for macOS

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/adaptive/AdaptiveJoinOperatorGenerator.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/strategy/AdaptiveBroadcastJoinOptimizationStrategy.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/strategy/PostProcessAdaptiveJoinStrategy.java

According to the design, we need to change the original forward partitioner to a rescale partitioner after the adaptive broadcast join takes effect. Accordingly, we need to use ForwardForUnspecifiedPartitioner to achieve this purpose.
- *Use ForwardForUnspecifiedPartitioner when adaptive broadcast join takes effect*
This change is already covered by existing tests, such as DefaultStreamGraphContextTest#testModifyStreamEdge.
- The …

[FLINK-37333][runtime] Use ForwardForUnspecifiedPartitioner when adaptive broadcast join takes effect

---

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/CoordinatorNotExistException.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/DefaultOperatorCoordinatorHandler.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectResultFetcher.java

When running large-scale flink batch jobs with the collect sink(e.g. running tpc-ds tests), the Flink JobManager frequently logs "Coordinator of operator xxxx does not exist or the job vertex this operator belongs to is not initialized." exceptions when using the collect() method.
This exception is caused by the collect sink attempting to fetch data from the corresponding operator coordinator on the JM based on the operator ID. However, batch jobs do not initialize all job vertices at the beginning, and instead, initialize them in a sequential manner. As a result, when a job vertex has not been initialized yet, the corresponding coordinator cannot be found, leading to the printing of this message.
- Add `CoordinatorNotExistException` that extends `FlinkException`
- Use …

[FLINK-35622][runtime] Filter out noisy 'Coordinator of operator xxx does not exist' exceptions in CollectResultFetcher

---

docs/content/docs/dev/table/sql/queries/joins.md
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/LogicalUnnestRule.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/UncollectToTableFunctionScanRule.java
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/UnnestTest.xml
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/LogicalUnnestRuleTest.xml
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/UnnestTest.xml
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/common/UnnestTestBase.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/UnnestITCase.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/UnnestITCase.scala
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/UnnestRowsFunction.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/UnnestRowsFunctionBase.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/table/UnnestRowsWithOrdinalityFunction.java

The SQL standard specifies a WITH ORDINALITY clause that can be appended to any UNNEST function call, which returns a new row for each element and its position in the data structure being unnested.
Examples:
```sql
– Returns a new row for each element in a constant array and its position in the array
SELECT *
FROM (VALUES('order_1'))
CROSS JOIN UNNEST(ARRAY["shirt", "pants", "hat"])
WITH ORDINALITY AS t(product_name, index)
id       product_name  index
=======  ============  =====
order_1  shirt             1
order_1  pants             2
order_1  hat               3
– Returns a new row for each element and its position in the array assuming a Orders table with an array column `product_names`
SELECT order_id, product_name, product_index
FROM Orders
CROSS JOIN UNNEST(product_names)
WITH …
```

[FLINK-37267][table] Add support for UNNEST WITH ORDINALITY

---

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java
flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogManagerTest.java

BP #25946 
This pull request fix a bug which a catalog that failed validation due to no type still exists in catalogStoreHolder.
And this catalog you cannot USE, ALTER.
- fix a bug which a catalog that failed validation due to no type still exists in catalogStoreHolder. …

[BP-2.0][FLINK-37093][table] Fix catalog that failed validation due to no type still exists in catalogStoreHolder

---

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogManager.java
flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogManagerTest.java

BP #25946 
This pull request fix a bug which a catalog that failed validation due to no type still exists in catalogStoreHolder.
And this catalog you cannot USE, ALTER.
- fix a bug which a catalog that failed validation due to no type still exists in catalogStoreHolder. …

[BP-1.20][FLINK-37093][table] Fix catalog that failed validation due to no type still exists in catalogStoreHolder

---

flink-runtime-web/pom.xml

There was a fix on frontend-maven-plugin https://github.com/eirslett/frontend-maven-plugin/commit/e2d0445fd3dd055bc576e37d89a907efa5435cb9
which should help with corrupted file issue FLINK-30719
pom.xml
- If yes, how is the feature documented? (not applicable …

[FLINK-30719] Update frontend-maven-plugin from 1.12.1 to 1.15.1

---

docs/content.zh/docs/deployment/java_compatibility.md
docs/content/docs/deployment/java_compatibility.md

*Update java_compatibility doc*
- *Update java_compatibility doc for jdk17 & jdk21*

[FLINK-37339][doc] Update java_compatibility doc

---

flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/DefaultStreamGraphContext.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/StreamGraphContext.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptivebatch/StreamGraphOptimizerTest.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/strategy/AdaptiveBroadcastJoinOptimizationStrategy.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/strategy/AdaptiveSkewedJoinOptimizationStrategy.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/strategy/BaseAdaptiveJoinOperatorOptimizationStrategy.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/strategy/PostProcessAdaptiveJoinStrategy.java

When the large table side has not yet initialized, if the small table side finishes early and the output data volume is smaller than the broadcast threshold, the adaptive join operator can be optimized to a broadcast hash join in advance. This can help reduce network shuffle overhead.
- *The adaptive broadcast join optimization is triggered in advance when any input of the join node meets the broadcast condition.*
This change is already covered by existing tests, such as (please describe tests). …

[FLINK-37382][runtime] Early optimization for adaptive join when either input is below broadcast threshold.

---

flink-table/flink-table-planner/src/main/resources/META-INF/NOTICE

The PR is to fix licensecheck in jdk11
I also created a follow up task to make the behavior across different jdk's same FLINK-37387
an example of a failed build https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=66272&view=logs&j=946871de-358d-5815-3994-8175615bc253&t=e0240c62-4570-5d1c-51af-dd63d2093da1&l=41112
NOTICE
- …

[hotfix] Update failureaccess in order to fix java 11 license check

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/FlinkJoinReorderRule.java

Creates a FlinkJoinReorderRule and not SparkJoinReorderRule

[hotfix] Rename SparkJoinReorderRule to FlinkJoinReorderRule

---

flink-filesystems/flink-oss-fs-hadoop/src/main/resources/META-INF/NOTICE

The PR is to fix licensecheck in jdk11
I also created a follow up task to make the behavior across different jdk's same [FLINK-37387](https://issues.apache.org/jira/browse/FLINK-37387)
an example of a failed build https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=66304&view=logs&j=946871de-358d-5815-3994-8175615bc253&t=e0240c62-4570-5d1c-51af-dd63d2093da1&l=41059
NOTICE …

[hotfix] fix NOTICE file in order to fix java 11 license check

---

flink-python/docs/reference/pyflink.table/catalog.rst
flink-python/docs/reference/pyflink.table/descriptors.rst
flink-python/pyflink/table/catalog.py
flink-python/pyflink/table/statement_set.py
flink-python/pyflink/table/table.py
flink-python/pyflink/table/table_pipeline.py
flink-python/pyflink/table/tests/test_catalog_completeness.py
flink-python/pyflink/table/tests/test_table_completeness.py
flink-python/pyflink/table/tests/test_table_pipeline.py
flink-python/pyflink/table/tests/test_table_pipeline_completeness.py

Currently, the TablePipeline descriptor is not supported in the Pyflink Table API, so API methods such as `insert_into` on a table environment are subsequently not supported. This PR introduces the `TablePipeline` descriptor so that users can setup a table pipeline, explain it, execute it, etc.
- Introduced `TablePipeline` descriptor.
- Introduced the `ObjectIdentifier` catalog entity.
- Adds `StatementSet.add` to add a `TablePipeline` to the `StatementSet`.
- Adds `Table.insert_into` to declare a `TablePipeline` with a given table path or table descriptor.
This change is already covered by existing tests, such as *(please describe tests)*:
- Catalog and Table API completeness tests …

[FLINK-37336][python] Introduce TablePipeline descriptor to Python Table API

---

flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/runtime/SavepointTaskStateManager.java
flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/restore/ChangelogBackendRestoreOperation.java

At the moment state processor API blows up with cryptic error when changelog used.
```
Caused by: java.io.IOException: Failed to restore state backend
at org.apache.flink.state.api.input.StreamOperatorContextBuilder.build(StreamOperatorContextBuilder.java:140)
at org.apache.flink.state.api.input.KeyedStateInputFormat.open(KeyedStateInputFormat.java:176)
at org.apache.flink.state.api.input.KeyedStateInputFormat.open(KeyedStateInputFormat.java:66)
at org.apache.flink.streaming.api.functions.source.InputFormatSourceFunction.run(InputFormatSourceFunction.java:92)
at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:181)
at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:78)
at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$Legacy …
```

[FLINK-37398][state] Add proper message when state processor API is used with changelog

---

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/CompiledPlan.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/PlanReference.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/CompiledPlanImpl.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/delegation/InternalPlan.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/ExecNodeGraphInternalPlan.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/ColumnJsonDeserializer.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/ColumnJsonSerializer.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/CompiledPlanSerdeUtil.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/ContextResolvedTableJsonDeserializer.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/DataTypeJsonDeserializer.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/JsonSmileSerdeUtil.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/LogicalTypeJsonDeserializer.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/LogicalWindowJsonDeserializer.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/ResolvedCatalogTableJsonDeserializer.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/ResolvedSchemaJsonDeserializer.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/ResolvedSchemaJsonSerializer.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/RexNodeJsonDeserializer.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/TableDistributionJsonDeserializer.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/TableDistributionJsonSerializer.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/delegation/PlannerBase.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/delegation/StreamPlanner.scala
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/serde/ContextResolvedTableSerdeTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/serde/ExecNodeGraphJsonSerializerTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/serde/FlinkVersionJsonSerdeTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/serde/JsonSerdeTestUtil.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/serde/LookupKeySerdeTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/serde/ResolvedCatalogTableSerdeTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/serde/RexNodeJsonSerdeTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/serde/RexWindowBoundSerdeTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/testutils/RestoreTestBase.java

Implementation of FLIP-508: add support for Smile format
During restore tests we extract compiled plans as Smile, load from it again and continue
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: ( yes)
- Does this pull request introduce a new feature? (yes )
- If yes, how is the feature documented? (JavaDocs )

[FLINK-37385][table] Add support for smile format

---

flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/AbstractKeyedState.java

When serializing values in ForSt states, the serializer is duplicated every time, which introduces unnecessary overhead. This PR optimize it out.
- Introduce a threadlocal in `AbstractKeyedState` to store value serializer and reuse within one thread.
This change is a trivial rework that is already covered by existing tests.
- The runtime per-record code paths (performance sensitive): **yes** …

[FLINK-37400] Remove redundant serializer duplication during value serialization of ForSt states

---

flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/AbstractKeyedState.java

When serializing values in ForSt states, the serializer is duplicated every time, which introduces unnecessary overhead. This PR optimize it out.
- Introduce a threadlocal in `AbstractKeyedState` to store value serializer and reuse within one thread.
This change is a trivial rework that is already covered by existing tests.
- The runtime per-record code paths (performance sensitive): **yes** …

[BP-2.0][FLINK-37400] Remove redundant serializer duplication during value serialization of ForSt states

---

docs/content.zh/docs/deployment/advanced/logging.md
docs/content/docs/deployment/advanced/logging.md
flink-dist/pom.xml
flink-dist/src/main/assemblies/bin.xml
pom.xml

Flink Jira Issue: https://issues.apache.org/jira/browse/FLINK-36997
By default, threads add this contextmap
```
{
"event": {
"timestamp": "2024-12-16T14:38:00.458Z",
"message": "Starting up...",
"application": "xyz",
"contextMap": "{\"environment\":\"Production\",\"is_backfill\":\"false\"}",
"endOfBatch": "false",
...
}
```
We want to be able to do
```
"context_map_environment": "Production",
"context_map_is_backfill": "false",
```
However, for that we need log4j-layout-template-json. We could maintain it in our private fork but the log4j json template is deprecated and we should slowly move to json-template as a community. This can be the first step which unblocks users so they don't need to manually maintain log4j version compatibility.
Add log4j JSON Template Layout into the …

[FLINK-36997] Add Log4j JSONTemplateLayout to flink-dist

---

flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/BuiltInAggregateFunctionTestBase.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/BuiltInFunctionTestBase.java

To stabilize tests checking for runtime exceptions for SQL builtin functions.
It seems, depending on timing `tableResult.await()` does not always return a runtime exception. The safest way is to request the runtime exception directly from the cluster.
The tests should pass
- Does this …

[FLINK-36324] Harden runtime error cases for table builtin functions

---

flink-connectors/flink-connector-base/src/main/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherManager.java
flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/fetcher/SplitFetcherManagerTest.java

This is a re-commit of the patch ( #25569 ) after fixing the accidentally changed timeout unit of the SplitFetcherManager close timeout.
Changes in the Original Fix:
This patch fixes an issue introduced in https://github.com/apache/flink/pull/25130. In SplitFetcherManager.close(), the element queue draining thread was chaining the runnables to the element queue availability future in a tight loop. This causes problem (e.g. OOM, high CPU util) when the fetcher threads do not shutdown quickly.
This patch changes the tight async loop to a blocking loop.
Changes in the followup patch fixes the accidentally changed timeout unit of the SplitFetcherManager close timeout.
Unit tests have been added. …

[FLINK-36585][connector/common] SplitFetcherManager.close() should not chain runnables to the element queue future in a tight loop

---

flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/legacy/metrics/MetricStore.java

This PR addresses a performance regression in the MetricStore that impacts clients fetching metrics, such as the autoscaler or web UI. The issue occurs when the /metrics endpoint becomes unresponsive due to delays in removing transient metrics for completed subtasks. This cleanup process is executed synchronously during metric retrieval, leading to significant slowdowns—particularly when the JM has multiple jobs or subtasks in a terminal state. These delays prevent timely metric fetching, disrupting latency-sensitive systems like the autoscaler. The root cause, identified via flamegraph analysis, is the inefficient synchronous execution of the cleanup routine introduced with FLINK-31650.
- Optimized the metrics cleanup process in `MetricStore` by caching the names of transient metrics …

[FLINK-36172][metrics][rest] Optimize transient metric cleanup

---

docs/content.zh/docs/dev/datastream-v2/context_and_state_processing.md
docs/content/docs/dev/datastream-v2/context_and_state_processing.md

The PR [#26057](https://github.com/apache/flink/pull/26057) adds documentation for DataStream V2. 
While writing DataStream V2 examples, we found that the StateManager#getState method was inconvenient for users. To address this, we distinguished between the StateManager#getState and StateManager#getStateOptional methods in [#26118](https://github.com/apache/flink/pull/26118).
The documentation also needs to be updated to reflect these changes.
- Update DataStream V2 documents for StateManager#getState and StateManager#getStateOptional methods
- The runtime …

[FLINK-37148][docs] Update DataStream V2 documents for StateManager#getState and StateManager#getStateOptional methods

---

tools/ci/compile.sh

As it was highlighted at https://github.com/apache/flink/pull/26217 and https://github.com/apache/flink/pull/26214 the issue is present for jdk17 and jdk21
The PR enables back license check for jdk17 and jdk21 since now for all java versions (11, 17, 21) the same scala is used
this seems to be a missing step after bumping scala version
license_check.sh …

[FLINK-37387][build] Enable license check for jdk17 and jdk21

---

flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperatorTest.java

This PR fixes the bug that AsyncWaitOperator might be triggering mailboxExecutor.execute() after the mailbox has been quiesced in AsyncWaitOperatorTest.testProcessingTimeRepeatedCompleteUnorderedWithRetry().
The cause of this bug is that AsyncWaitOperatorTest forgot to invoke AsyncWaitOperator#endInput before closing the wrapping testHarness, causing the scheduled processing time timers in AsyncWaitOperator not being cancelled.
FLINK-35810 mentioned that there is always an OOM before this test failure, but these two errors should be independent from each other. In the following CIs, OOM still exists while AsyncWaitOperatorTest has passed.
* https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=66387&view=logs&j=77a9d8e1-d610-59b3-fc2a-4766541e0e33&t=125e07e7-8de0-5c6c-a541 …

[FLINK-35810][BP-2.0] Fix AsyncWaitOperatorTest missing endInput bug

---

flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperatorTest.java

This PR fixes the bug that AsyncWaitOperator might be triggering mailboxExecutor.execute() after the mailbox has been quiesced in AsyncWaitOperatorTest.testProcessingTimeRepeatedCompleteUnorderedWithRetry().
The cause of this bug is that AsyncWaitOperatorTest forgot to invoke AsyncWaitOperator#endInput before closing the wrapping testHarness, causing the scheduled processing time timers in AsyncWaitOperator not being cancelled.
FLINK-35810 mentioned that there is always an OOM before this test failure, but these two errors should be independent from each other. In the following CIs, OOM still exists while AsyncWaitOperatorTest has passed.
* https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=66387&view=logs&j=77a9d8e1-d610-59b3-fc2a-4766541e0e33&t=125e07e7-8de0-5c6c-a541 …

[FLINK-35810] Fix AsyncWaitOperatorTest missing endInput bug

---

flink-filesystems/flink-oss-fs-hadoop/src/main/resources/META-INF/NOTICE
tools/ci/compile.sh

[BP-2.0][FLINK-37387][build] Enable license check for jdk17 and jdk21
[BP-2.0][hotfix] fix NOTICE file in order to fix java 11 license check

[BP-2.0][FLINK-37387][build] Enable license check for jdk17 and jdk21

---

flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/AbstractAggregatingState.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractAggregatingStateTest.java

fix AbstractAggregatingState add may return wrong result
When calling add() in AbstractAggregatingState , if the acc is empty, the value of updateInternal will only be this.aggregateFunction.createAccumulator() , but it should actually be this.aggregateFunction.add(value, this.aggregateFunction.createAccumulator())
this change is covered by `AbstractAggregatingStateTest. testAggregatingStateAddWithSyncAPI` …

[FLINK-37420] fix AbstractAggregatingState add may return wrong result

---

pom.xml

We should use JDK11 instead of JDK17(in release profile now) for the binary release. Otherwise :
- We can not provide the docker image of jdk11, because it package flink from binary convenience release not compile from source.
- Users cannot use the flink dist downloaded from the official website directly in the setup of jdk11. But we still claim to support jdk11 in 2.0.

[FLINK-37424][release] Using JDK11 for the binary convenience release

---

tools/azure-pipelines/build-apache-repo.yml

*We should put the nightly binary release build from the minimum supported jdk version. Otherwise, some ci(e.g. ci of flink-docker dev-2.0 branch) can not run in jdk11 setup(but we still want to provide the jdk11 flink image).*

[FLINK-37424][release] Using JDK11 for the nightly binary release

---

docs/layouts/shortcodes/generated/forst_configuration.html
docs/layouts/shortcodes/generated/state_backend_forst_section.html
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStOptions.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystem.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/SpaceBasedCacheLimitPolicy.java

There is a chance that the space based cache limit policy in ForStStateBackend could not work on the specified cache path, resulting in the whole cache fail to store anything. This PR fixes this.
- Create cache path before policy created.
- Sanity check before the policy created.
This change is a trivial work without any test coverage. I have tested it manually via a job in specific env. …

[FLINK-37425] Sanity check before ForSt cache created

---

docs/layouts/shortcodes/generated/forst_configuration.html
docs/layouts/shortcodes/generated/state_backend_forst_section.html
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStOptions.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystem.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/SpaceBasedCacheLimitPolicy.java

There is a chance that the space based cache limit policy in ForStStateBackend could not work on the specified cache path, resulting in the whole cache fail to store anything. This PR fixes this.
- Create cache path before policy created.
- Sanity check before the policy created.
This change is a trivial work without any test coverage. I have tested it manually via a job in specific env. …

[BP-2.0][FLINK-37425] Sanity check before ForSt cache created

---

flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java
flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManager.java
flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/DefaultSlotStatusSyncer.java
flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/FineGrainedSlotManager.java
flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/util/JobIDLoggingUtil.java
flink-tests/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTriggerSavepointITCase.java
flink-tests/src/test/java/org/apache/flink/test/misc/JobIDLoggingITCase.java

These changes add JobID to MDC, making analyzing problems more convenient. 
- *An existing method that checks JobID existence in MDC has been extracted to a new UtilityClass*
- *Existing ITCase test was migrated from JUnit4 to JUnit5+Jupiter*
- *JobID has been added to MDC in several classes that are commonly used to analyze logs*
- *Each class that now has JobID in MDC got additional assertions that verify JobID existence in LogEvents* …

[FLINK-37401] Add Job ID to logging context

---

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystem.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/FSDataOutputStreamWithEntry.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/FileMappingManager.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/MappingEntry.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystemTest.java

We leverage `disableFileDeletions` and `enableFileDeletions` of ForSt to keep files alive during checkpoint. When checkpoint finished, the `enableFileDeletions` will be invoked, while ForSt will list all the files and check status. These files, however, include the writing ones, which is not visible in some DFS (e.g. oss or s3) yet. Although the checkpoints are actually not missing, the thrown exception make the finalization of checkpoint failed, resulting in consecutive cp failures.
The root cause would be the `ForStFlinkFileSystem` does not give correct information of files which are being written. This PR fixes this.
- Fixes `#exist` and `getFileStatus` to give information of writing files.
- Enrich `MappingEntry` and introduce `FSDataOutputStreamWithEntry` to maintain …

[FLINK-37437][state/forst] Fix #exist and #getFileStatus to give the information of writing files

---

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystem.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/FSDataOutputStreamWithEntry.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/FileMappingManager.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/MappingEntry.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystemTest.java

We leverage `disableFileDeletions` and `enableFileDeletions` of ForSt to keep files alive during checkpoint. When checkpoint finished, the `enableFileDeletions` will be invoked, while ForSt will list all the files and check status. These files, however, include the writing ones, which is not visible in some DFS (e.g. oss or s3) yet. Although the checkpoints are actually not missing, the thrown exception make the finalization of checkpoint failed, resulting in consecutive cp failures.
The root cause would be the `ForStFlinkFileSystem` does not give correct information of files which are being written. This PR fixes this.
- Fixes `#exist` and `getFileStatus` to give information of writing files.
- Enrich `MappingEntry` and introduce `FSDataOutputStreamWithEntry` to maintain …

[BP-2.0][FLINK-37437][state/forst] Fix #exist and #getFileStatus to give the information of writing files

---

flink-runtime/src/main/java/org/apache/flink/streaming/api/graph/JSONGenerator.java

Follow up for https://github.com/apache/flink/pull/26220

[FLINK-36402] edgeRemapings typo fixed to edgeRemappings

---

flink-dist/src/main/resources/META-INF/NOTICE
flink-state-backends/flink-statebackend-forst/pom.xml
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackendBuilder.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystem.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/FileMappingManager.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/MappingEntry.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStResourceContainerTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/FileMappingManagerTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystemTest.java

ForSt may create LOG files twice with overwrite, however, the ForSt wrapped file system does not support overwriting files. Exception thrown in this case.
This PR fixes the bug above, as well as some file ownership problem that may cause a ForSt coredump.
Please check each commit for code changes:
- Support file override in wrapped file system, modified the `FileMappingManager`
- Unguarded file system to enable stream sharing between threads
- Avoid the deletion of primary directory in ForSt
Multiple UTs added. …

[FLINK-37439][state/forst] Support file override in wrapped file system

---

flink-dist/src/main/resources/META-INF/NOTICE
flink-state-backends/flink-statebackend-forst/pom.xml
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackendBuilder.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStResourceContainer.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystem.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/FileMappingManager.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/MappingEntry.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStResourceContainerTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/FileMappingManagerTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystemTest.java

ForSt may create LOG files twice with overwrite, however, the ForSt wrapped file system does not support overwriting files. Exception thrown in this case.
This PR fixes the bug above, as well as some file ownership problem that may cause a ForSt coredump.
Please check each commit for code changes:
- Support file override in wrapped file system, modified the `FileMappingManager`
- Unguarded file system to enable stream sharing between threads
- Avoid the deletion of primary directory in ForSt
Multiple UTs added. …

[BP-2.0][FLINK-37439][state/forst] Support file override in wrapped file system

---

flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/test/program/FailingSqlTestStep.java
flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/test/program/TableTestProgram.java
flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/test/program/TestStep.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/annotation/ArgumentTrait.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/ProcessTableFunction.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/UserDefinedFunctionHelper.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/StaticArgumentTrait.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/SystemTypeInference.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecProcessTableFunction.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalProcessTableFunction.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/ProcessTableRunnerGenerator.scala
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/ProcessTableFunctionSemanticTests.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/ProcessTableFunctionTestPrograms.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/ProcessTableFunctionTestUtils.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/testutils/SemanticTestBase.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/stream/sql/ProcessTableFunctionTest.java
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/ProcessTableFunctionTest.xml
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/generated/ProcessTableRunner.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/process/ExternalTimeContext.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/process/PassAllCollector.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/process/PassPartitionKeysCollector.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/process/PassThroughCollectorBase.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/process/ProcessTableOperator.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/process/ReadableInternalTimeContext.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/process/RuntimeTableSemantics.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/process/TimeConverter.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/process/WritableInternalTimeContext.java

This introduces time and timer support for PTFs according to section 5.2.1 in [FLIP-440]([url](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=298781093#FLIP440:UserdefinedSQLoperators/ProcessTableFunction(PTF)-TimeSemantics)).
In a nutshell:
- Every PTF takes an `on_time` DESCRIPTOR argument.
- The `on_time` is optional by default but can be made mandatory (esp. useful for built-in functions).
- If `on_time` is declared, the PTFs output contains a `rowtime` column for subsequent time-based operations.
- A `TimeContext` is available in the `Context` of a PTF's `eval()` method.
- Timers can be created, replaced, deleted and fired.
- An `onTimer()` can be implemented for reacting to timer firings.
- Timers can named or unnamed.
- Late events are dropped.
- Adapt …

[FLINK-37302][table] Support PTFs with time and timer services

---

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/sync/ForStSyncKeyedStateBackend.java
flink-tests/src/test/java/org/apache/flink/test/checkpointing/AutoRescalingITCase.java
flink-tests/src/test/java/org/apache/flink/test/checkpointing/EventTimeWindowCheckpointingITCase.java
flink-tests/src/test/java/org/apache/flink/test/checkpointing/KeyedStateCheckpointingITCase.java
flink-tests/src/test/java/org/apache/flink/test/checkpointing/RescaleCheckpointManuallyITCase.java

Introduce ForSt to existing IT Cases.
- Enable Async State in `OneInputTransformation`
- Introduce forst to `AutoRescalingITCase`, `EventTimeWindowCheckpointingITCase`, `KeyedStateCheckpointingITCase`
, `RescaleCheckpointManuallyITCase`.
This change is a trivial rework , which is already covered by existing tests. …

[FLINK-37158][tests] Introduce ForSt to existing ITCases

---

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/expressions/resolver/rules/ResolveCallByArgumentsRule.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/StaticArgument.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/extraction/TypeInferenceExtractorTest.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/expressions/converter/converters/CustomizedConverters.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/expressions/converter/converters/DefaultConverter.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/ProcessTableFunctionTestUtils.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/stream/sql/ProcessTableFunctionTest.java

Followup PR of #26282 that improves the PTF behavior. A prerequisite of FLINK-37423.
- Convert missing optional args to the DEFAULT operator.
This change is already covered by existing tests: `MiscFunctionITCase`
More sophisticated tests will follow as part of FLINK-37423.

[FLINK-37466][table-api-java] Make DEFAULT explicit from Table API to planner

---

flink-python/docs/reference/pyflink.table/expressions.rst
flink-python/pyflink/table/expression.py
flink-python/pyflink/table/tests/test_expression.py
flink-python/pyflink/table/tests/test_expression_completeness.py

https://github.com/apache/flink/pull/26282 introduces the `asArgument` expression in the Java table API. This PR adds a corresponding expression to the Python table API.
- *Added `as_argument` expression to Python table API.*
- *Added tests for `as_argument` to existing expressions test suite.*
- If …

[FLINK-37457][python] Support asArgument in Python Table API

---

flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/KeyedStateTransformation.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/OneInputStateTransformation.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/OperatorTransformation.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/SavepointReader.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/SavepointWriter.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/WindowedStateTransformation.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/output/MergeOperatorStates.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/output/SnapshotUtils.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/output/operators/BroadcastStateBootstrapOperator.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/output/operators/KeyedStateBootstrapOperator.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/output/operators/StateBootstrapOperator.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/output/operators/StateBootstrapWrapperOperator.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/output/operators/StateBootstrapWrapperOperatorFactory.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/runtime/metadata/SavepointMetadataV2.java
flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/SavepointWriterITCase.java
flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/output/KeyedStateBootstrapOperatorTest.java
flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/output/SnapshotUtilsTest.java

At the moment the state processor API is using hardcoded `0` as checkpoint ID.
In this PR I've made it configurable and savepoint modification keeps the original checkpoint ID.
Made state processor API checkpoint ID configurable and savepoint modification keeps the original ID.
Changed automated tests. …

[FLINK-37460][state] Make state processor API checkpoint ID configurable

---

flink-python/docs/reference/pyflink.table/compiled_plans.rst
flink-python/docs/reference/pyflink.table/descriptors.rst
flink-python/docs/reference/pyflink.table/index.rst
flink-python/docs/reference/pyflink.table/plans.rst
flink-python/docs/reference/pyflink.table/statement_set.rst
flink-python/docs/reference/pyflink.table/table.rst
flink-python/docs/reference/pyflink.table/table_environment.rst
flink-python/pyflink/table/__init__.py
flink-python/pyflink/table/compiled_plan.py
flink-python/pyflink/table/plan_reference.py
flink-python/pyflink/table/resolved_expression.py
flink-python/pyflink/table/schema.py
flink-python/pyflink/table/statement_set.py
flink-python/pyflink/table/table.py
flink-python/pyflink/table/table_environment.py
flink-python/pyflink/table/table_pipeline.py
flink-python/pyflink/table/tests/jsonplan/testGetJsonPlan.out
flink-python/pyflink/table/tests/test_compiled_plan.py
flink-python/pyflink/table/tests/test_compiled_plan_completeness.py
flink-python/pyflink/table/tests/test_plan_reference_completeness.py
flink-python/pyflink/table/tests/test_statement_set_completeness.py
flink-python/pyflink/table/tests/test_table_completeness.py
flink-python/pyflink/table/tests/test_table_environment_completeness.py
flink-python/pyflink/table/tests/test_table_pipeline.py
flink-python/pyflink/table/tests/test_table_pipeline_completeness.py
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/Compilable.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/CompiledPlan.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/PlanReference.java
pom.xml

There are still some API objects and methods from [FLIP-190 ](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=191336489#FLIP190:SupportVersionUpgradesforTableAPI&SQLPrograms-TableAPI) that are missing from the Python Table API. These are:
- `CompiledPlan` and `PlanReference`
- `TablePipeline.compile_plan`
- `StatementSet.compile_plan`
- `TableEnvironment.compile_plan_sql/execute_plan/load_plan`
When assembling the Python side representations of `PlanReference`, I opted not to include `from_resource` as I don't think it makes sense to do so in a python context. I also added some missing completeness tests for `TableEnvironment` and `StatementSet`, as well as tweaking some documentation to fix some missing autodoc links.
- `CompiledPlan` and `PlanReference`
- …

[FLINK-25986][python] Add remaining FLIP-190 API methods to Python Table API

---

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/agg/AggsHandlerCodeGenerator.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/codegen/agg/AggTestBase.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/AggregateITCaseBase.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/AggregateITCase.scala

Currently under the stream mode when an global agg with filter arg which actually references the first input column, then the corresponding agg column result will be incorrect(this issue doesn't exist in batch mode).
Add new agg cases 
`AggregateITCase`

[FLINK-30687][table] Fix wrong result of agg with fiter which references first input column

---

flink-runtime/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java

This PR proposes to improve the `createLocalEnvironment` by reduce duplicate operation on `Configuration`.
Improve the `createLocalEnvironment` by reduce duplicate operation on `Configuration`
Currently, `StreamExecutionEnvironment` provides a `createLocalEnvironment` with one parameter parallelism.
```
public static LocalStreamEnvironment createLocalEnvironment(int parallelism) {
return createLocalEnvironment(parallelism, new Configuration());
}
```
Above method will create a new instance of `Configuration` and then calling the below override one.
```
public static LocalStreamEnvironment createLocalEnvironment(
int parallelism, Configuration configuration) {
Configuration copyOfConfiguration = new Configuration();
copyOfConfiguration.addAll(configuration); …
```

[FLINK-37438] Improve the createLocalEnvironment by reduce duplicate operation on Configuration

---

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/async/CollectionSupplier.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/async/ResultFuture.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperator.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/async/queue/StreamElementQueueEntry.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperatorTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskMailboxTestHarness.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/codegen/AsyncCodeGeneratorTest.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/collector/TableFunctionResultFuture.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/calc/async/DelegatingAsyncResultFuture.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/lookup/AsyncLookupJoinRunner.java

Fixes [a bug](https://issues.apache.org/jira/browse/FLINK-37243) where the data converter was being invoked from a user callback thread. With this change, you can callback into AsyncWaitOperator and have it invoke a callback from the Mailbox thread.
Specifically, this is done by exposing on `ResultFuture` a variation of `callback`:
```
void complete(SupplierWithException<Collection<OUT>, Exception> supplier);
```
Rather than requiring the client to return the result directly, it can give a supplier which will be executed on the mailbox thread for consistency (i.e. in our case use of the converter).

[FLINK-37243] Adds main thread callback to AsyncWaitOperator

---

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBBunchPutRequest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStMapState.java

Now, when using ForStMapState for asynchronous state reading and writing,  userValueSerializer in ForStMapState will be used to serialize and deserialize the data. However, in asynchronous execution mode, multiple threads may use the same userValueSerializer instance for serialization and deserialization at the same time, which may cause some multi-thread conflicts in Serializer (eg: Kryo), so we need to make the userValueSerializer and userKeySerializer in ForStMapState ThreadLocal to avoid these problems.
make the userValueSerializer and userKeySerializer in ForStMapState ThreadLocal 
- The …

[FLINK-37463] make serialzer in ForStMapState Threadlocal

---

docs/content.zh/docs/deployment/overview.md
docs/content/docs/deployment/overview.md

fix the content in doc: Flink can execute applications in two modes instead of three after the Per-Job Mode has been removed.

[hotfix][doc] two modes instead of three

---

docs/layouts/shortcodes/generated/all_taskmanager_section.html
docs/layouts/shortcodes/generated/expert_scheduling_section.html
docs/layouts/shortcodes/generated/task_manager_configuration.html
flink-core/src/main/java/org/apache/flink/configuration/TaskManagerOptions.java
flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/DefaultResourceAllocationStrategy.java
flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/DefaultResourceAllocationStrategyTest.java

- Add `RESOURCES` allocation strategy to maximize usage of allocated TMs before using another one.
- Added new configuration value `RESOURCES` for `TaskManagerLoadBalanceMode`.
- Added `mostUtilization` allocation strategy to `DefaultResourceAllocationStrategy`
- Added relevant UTs

[FLINK-37412] Add MIN_RESOURCES TaskManagerLoadBalanceMode to maximize TM usage

---

flink-runtime/src/main/java/org/apache/flink/runtime/state/heap/KeyGroupPartitionedPriorityQueue.java

This PR proposes to remove unnecessary `InternalPriorityQueue`.
Since `KeyGroupedInternalPriorityQueue` already extends `InternalPriorityQueue`.
Remove unnecessary `InternalPriorityQueue`

[hotfix] Remove unnecessary InternalPriorityQueue

---

flink-python/pyflink/common/configuration.py
flink-python/pyflink/common/tests/test_configuration.py
flink-python/pyflink/datastream/stream_execution_environment.py
flink-python/pyflink/datastream/tests/test_stream_execution_environment.py
flink-python/pyflink/table/table_config.py
flink-python/pyflink/table/table_environment.py

Pyflink is not able to handle the new YAML based configs.
Steps to repro:
* pipeline.jars = ['file:/flink/opt/flink-python-2.0.0.jar']
* In python env.add_jars('file:/my-feature.jar')
Then it blows up with the following error:
```
2025-03-18 15:43:36,699 INFO  org.apache.flink.client.python.PythonDriver                  [] - : java.net.MalformedURLException: no protocol: ['file:/flink/opt/flink-python-2.0.0.jar']
```
In this PR I've added support for it.
Add pyflink YAML based config support.
Automated python tests. …

[FLINK-37505][python] Add pyflink YAML based config support

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/ChangelogMode.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/optimize/ChangelogNormalizeRequirementResolver.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/optimize/StreamNonDeterministicUpdatePlanVisitor.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/trait/DeleteKind.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/FlinkRelUtil.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/optimize/program/FlinkChangelogModeInferenceProgram.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/trait/DeleteKindTrait.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/trait/DeleteKindTraitDef.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/ChangelogPlanUtils.scala
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestValuesTableFactory.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/DeletesByKeyPrograms.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/DeletesByKeySemanticTests.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/stream/sql/ChangelogNormalizeOptimizationTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/sql/DataStreamJavaITCase.java
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/ChangelogNormalizeOptimizationTest.xml
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/TableScanTest.xml
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/NonDeterministicDagTest.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/TableScanTest.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/TableTestBase.scala

Remove ChangelogNormalize if possible for `INSERT INTO SELECT * FROM`
Added plan and semantic tests
- If yes, how is the feature documented? (not applicable / docs / **JavaDocs** / not documented)

[FLINK-37475] Drop ChangelogNormalize for piping from upsert source to sink

---

flink-core/src/main/java/org/apache/flink/core/memory/MemoryUtils.java

This PR aims to make `Preconditions.checkState` follows the Flink code style.
Please refer to https://flink.apache.org/how-to-contribute/code-style-and-quality-java/#collections
`Preconditions.checkState` should follows the Flink code style.

[hotfix] Preconditions.checkState should follows the Flink code style

---

flink-filesystems/flink-hadoop-fs/src/main/java/org/apache/flink/runtime/util/HadoopUtils.java

This PR aims to rename the variable `result` to `config`.
Rename the variable `result` to `config`

[hotfix] Rename the variable `result` to `config`

---

flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/SchemaResolutionTest.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/ResolvedSchema.java

Fixes the `getPrimaryKeyIndexes` method to return indexes in the `physicalRowDataType`
All existing tests pass. Added a specific test.
- If yes, how is the feature documented? (n**ot applicable** / docs / JavaDocs / not …

[FLINK-37557] Fix ResolvedSchema#getPrimaryKeyIndexes

---

flink-clients/src/main/java/org/apache/flink/client/deployment/application/ApplicationClusterEntryPoint.java
flink-clients/src/test/java/org/apache/flink/client/deployment/application/ApplicationDispatcherBootstrapITCase.java
flink-runtime/src/main/java/org/apache/flink/runtime/rest/ApplicationRestEndpointFactory.java
flink-table/flink-sql-gateway/src/test/java/org/apache/flink/table/gateway/service/application/ScriptRunnerITCase.java

This PR aims to rename `JobRestEndpointFactory` to `ApplicationRestEndpointFactory`.
AFAIK, Flink already removed `Job-Cluster` or renamed it with `Application-Cluster`. There are many classes renamed from `Job*` to `Application*`. I guess we missing the `JobRestEndpointFactory`.
Rename `JobRestEndpointFactory` to `ApplicationRestEndpointFactory`.
- The S3 …

[hotfix] Rename JobRestEndpointFactory to ApplicationRestEndpointFactory

---

flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/RestHandlerConfiguration.java
flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/RestHandlerConfigurationTest.java

This PR aims to simplify the variable `checkpointStatsSnapshotCacheExpireAfterWrite`.
The `checkpointStatsSnapshotCacheExpireAfterWrite` comes from `RestOptions.CACHE_CHECKPOINT_STATISTICS_TIMEOUT` that have the default value reference the `WebOptions.REFRESH_INTERVAL` as show below.
```
public static final ConfigOption<Duration> CACHE_CHECKPOINT_STATISTICS_TIMEOUT =
key("rest.cache.checkpoint-statistics.timeout")
.durationType()
.defaultValue(WebOptions.REFRESH_INTERVAL.defaultValue())
.withFallbackKeys(WebOptions.REFRESH_INTERVAL.key())
.withDescription(
Description.builder()
.text(
"Duration from write after which cached checkpoints statistics are cleaned up. For backwards compatibility, if no value is configured, %s will be used instead.",
code(WebOptions.REFRESH_INTERVAL.key())) …
```

[hotfix] Simplify the variable checkpointStatsSnapshotCacheExpireAfterWrite

---

flink-core/src/main/java/org/apache/flink/api/common/functions/util/PrintSinkOutputWriter.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/functions/sink/legacy/PrintSinkFunction.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/sink/PrintSink.java

This PR aim to improve the code for `PrintSinkOutputWriter`, `PrintSinkFunction` and `PrintSink`.
1.  Rename the variable `target` with a meaning name.
2. Simplify the code like `stream = target == STD_OUT ? System.out : System.err;`.
Simplify the code for `PrintSink`

[FLINK-37482] Improve the code for PrintSinkOutputWriter, PrintSinkFunction and PrintSink

---

flink-clients/src/main/java/org/apache/flink/client/program/PackagedProgram.java

[hotfix][clients] Refactor PackagedProgram#getJobJarAndDependencies to reduce some redundant lines.
[hotfix][clients] Refactor PackagedProgram#getJobJarAndDependencies to reduce some redundant lines.
- Does this …

[hotfix][clients] Refactor PackagedProgram#getJobJarAndDependencies to reduce some redundant lines.

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/abilities/source/PartitionPushDownSpec.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/utils/PartitionUtils.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/abilities/source/PartitionPushDownSpecTest.java
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/testTableSourceSinks.scala

Improves flaky tests for partitionable table source in the tests that is compared using the explain plan.
- Sort the partitions map pairs on the keys so that explained plan have them in sorted order (e.g, `part1`, `part2`)

[FLINK-36443][table][test] Improve flaky table source sink tests

---

docs/content/docs/ops/metrics.md
flink-core/src/main/java/org/apache/flink/api/common/eventtime/CombinedWatermarkStatus.java
flink-core/src/main/java/org/apache/flink/api/common/eventtime/IndexedCombinedWatermarkStatus.java
flink-core/src/main/java/org/apache/flink/api/common/eventtime/WatermarkOutputMultiplexer.java
flink-core/src/test/java/org/apache/flink/api/common/eventtime/WatermarkOutputMultiplexerTest.java
flink-metrics/flink-metrics-core/src/main/java/org/apache/flink/metrics/groups/SourceSplitMetricGroup.java
flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricNames.java
flink-runtime/src/main/java/org/apache/flink/runtime/metrics/TimerGauge.java
flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/InternalSourceSplitMetricGroup.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/source/ProgressiveTimestampsAndWatermarks.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/source/TimestampsAndWatermarks.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/source/WatermarkToDataOutput.java
flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/InternalSourceSplitMetricGroupTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorSplitWatermarkAlignmentTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorTest.java

This pull request adds split level watermark metrics, covering watermark progress and per-split state gauges (active, idle and paused)
The change is widely described in [FLIP-513: Split-level Watermark Metrics](https://cwiki.apache.org/confluence/display/FLINK/FLIP-513%3A+Split-level+Watermark+Metrics)
- A new metric group `InternalSourceSplitMetricGroup` introduced as a sub-group of [OperatorMetricGroup](https://github.com/apache/flink/blob/4091e85b62845680c450b7db6301903de10877e4/flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/InternalOperatorMetricGroup.java#L37), containing a watermark reference and pauseable timers for states.
- The MG is initialized per split by [SourceOperator](https://github.com/apache/flink/blob/master/flink-runtime/src/main/java/org/apache/fli …

[FLINK-37410][runtime/metrics] Split level Watermark metrics

---

.github/workflows/stale.yml

[FLINK-37026](https://issues.apache.org/jira/browse/FLINK-37026) enabled the Stale PR GitHub Action and this has been running successfully for several months, [labelling PRs older than 6 months as "stale"](https://github.com/apache/flink/labels/stale).
The initial time-outs for the Stale PR action were 6 months inactive with 3 further months of no action before closing. This was done to give time for PR authors to react to the new action. However, during the [discussion](https://lists.apache.org/thread/6yoclzmvymxors8vlpt4nn9r7t3stcsz) it was suggested that 3 months inactive with 1 month to respond was the typical configuration used on other Apache projects and should also be used for Flink. It was decided to start with longer time-outs and move to the standard ones once the stability of …

[FLINK-37533][CI] Reduce the stale PR github action timeouts

---

flink-core/src/main/java/org/apache/flink/configuration/GlobalConfiguration.java

This PR aims to improve the method `flatten` of class `GlobalConfiguration`.
Currently, the method `flatten` of class `GlobalConfiguration` adopts the recursion to flatten the nested or multi-level map to flattened, 1 level deep map.
Every time method `flatten` is entered, a new map is created.
We can avoid the duplication of create map.
Improve the method `flatten` of class `GlobalConfiguration`.
This change is already covered by existing tests, such as *(YamlParserUtilsTest)*. …

[FLINK-37568] Improve the method flatten of class GlobalConfiguration

---

.github/workflows/template.flink-ci.yml
docs/content.zh/docs/deployment/resource-providers/standalone/docker.md
docs/content.zh/docs/try-flink/flink-operations-playground.md
docs/content.zh/docs/try-flink/table_api.md
docs/content/docs/deployment/resource-providers/standalone/docker.md
docs/content/docs/try-flink/flink-operations-playground.md
docs/content/docs/try-flink/table_api.md

Replace all instances of "docker-compose" with "docker compose" throughout the Flink documentation to align with Docker's current CLI naming convention.
https://issues.apache.org/jira/browse/FLINK-37408
Replace all instances of "docker-compose" with "docker compose" throughout the Flink documentation …

[FLINK-37408] Update all docker-compose references to docker compose

---

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/AllToAllBlockingResultInfo.java
flink-tests/src/test/java/org/apache/flink/test/scheduling/AdaptiveBatchSchedulerITCase.java

[FLINK-37576][runtime] Fix the incorrect status of the isBroadcast field in AllToAllBlockingResultInfo when submitting a job graph.
This issue has minimal impact on users because RestClusterClient is annotated with @Internal, and users can only submit stream graphs.
[FLINK-37576][runtime] Fix the incorrect status of the isBroadcast field in AllToAllBlockingResultInfo when submitting a job graph.
Set the original value for isBroadcast field.
This change added tests and can be verified by AdaptiveBatchSchedulerITCase#testSubmitJobGraphWithBroadcastEdge …

[FLINK-37576][runtime] Fix the incorrect status of the isBroadcast field in AllToAllBlockingResultInfo when submitting a job graph.

---

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/AllToAllBlockingResultInfo.java
flink-tests/src/test/java/org/apache/flink/test/scheduling/AdaptiveBatchSchedulerITCase.java

[BP-2.0][FLINK-37576][runtime] Fix the incorrect status of the isBroadcast field in AllToAllBlockingResultInfo when submitting a job graph.

[BP-2.0][FLINK-37576][runtime] Fix the incorrect status of the isBroadcast field in AllToAllBlockingResultInfo when submitting a job graph.

---

flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/InternalSourceSplitMetricGroup.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorTest.java

Following up on https://github.com/apache/flink/pull/26276
Accounting for splits that have no watermarks assigned to them

[FLINK-37570][metrics] Export default watermark if split doesn't have any

---

flink-end-to-end-tests/flink-end-to-end-tests-table-api/pom.xml
flink-end-to-end-tests/flink-end-to-end-tests-table-api/src/main/java/org/apache/flink/table/test/async/AsyncScalarFunctionExample.java
flink-end-to-end-tests/flink-end-to-end-tests-table-api/src/test/java/org/apache/flink/table/test/async/AsyncScalarFunctionTest.java
flink-end-to-end-tests/pom.xml
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/planner/loader/PlannerModule.java

* Add missing dependency to table classloader
* Add `commons-text` to the allowed classloader list

[FLINK-35117][Table SQL/Planner] Add commons-text to allowed classloader list

---

flink-formats/flink-sql-parquet/src/main/resources/META-INF/NOTICE
flink-formats/pom.xml

The PR bumps dependency from 1.14.4 to 1.15.1
to mitigate https://nvd.nist.gov/vuln/detail/CVE-2025-30065
pom and NOTICE files
- Dependencies (does it add or upgrade a dependency): ( yes)

[FLINK-37609][format] Bump parquet from 1.14.4 to 1.15.1

---

flink-python/pyflink/common/configuration.py
flink-python/pyflink/common/tests/test_configuration.py
flink-python/pyflink/datastream/stream_execution_environment.py
flink-python/pyflink/datastream/tests/test_stream_execution_environment.py
flink-python/pyflink/table/table_config.py
flink-python/pyflink/table/table_environment.py

1.20 backport of https://github.com/apache/flink/pull/26327
Original desc below.
Pyflink is not able to handle the new YAML based configs.
Steps to repro:
* pipeline.jars = ['file:/flink/opt/flink-python-2.0.0.jar']
* In python env.add_jars('file:/my-feature.jar')
Then it blows up with the following error:
```
2025-03-18 15:43:36,699 INFO  org.apache.flink.client.python.PythonDriver                  [] - : java.net.MalformedURLException: no protocol: ['file:/flink/opt/flink-python-2.0.0.jar']
```
In this PR I've added support for it.
Add pyflink YAML based config support.
Automated python tests. …

[BP-1.20][FLINK-37505][python] Add pyflink YAML based config support

---

flink-python/pyflink/common/configuration.py
flink-python/pyflink/common/tests/test_configuration.py
flink-python/pyflink/datastream/stream_execution_environment.py
flink-python/pyflink/datastream/tests/test_stream_execution_environment.py
flink-python/pyflink/table/table_config.py
flink-python/pyflink/table/table_environment.py

1.19 backport of https://github.com/apache/flink/pull/26327
Original desc below.
Pyflink is not able to handle the new YAML based configs.
Steps to repro:
* pipeline.jars = ['file:/flink/opt/flink-python-2.0.0.jar']
* In python env.add_jars('file:/my-feature.jar')
Then it blows up with the following error:
```
2025-03-18 15:43:36,699 INFO  org.apache.flink.client.python.PythonDriver                  [] - : java.net.MalformedURLException: no protocol: ['file:/flink/opt/flink-python-2.0.0.jar']
```
In this PR I've added support for it.
Add pyflink YAML based config support.
Automated python tests. …

[BP-1.19][FLINK-37505][python] Add pyflink YAML based config support

---

flink-connectors/flink-connector-hive/src/main/resources/META-INF/NOTICE
flink-formats/flink-sql-parquet/src/main/resources/META-INF/NOTICE
flink-formats/pom.xml
flink-python/pom.xml
pom.xml

1.19 backport of https://github.com/apache/flink/commit/986f89ac120fdff0d3b9bd738e06e39c28617785, 
https://github.com/apache/flink/commit/5aaff07fe925b289a2cabe9269a015ebc2255223
and https://github.com/apache/flink/commit/d8cd5591d3136187695727202dc16bc96ce2caae

 [BP-1.19][FLINK-37609][format]  Bump parquet to 1.15.1

---

flink-connectors/flink-connector-hive/src/main/resources/META-INF/NOTICE
flink-formats/flink-sql-parquet/src/main/resources/META-INF/NOTICE
flink-formats/pom.xml
flink-python/pom.xml
pom.xml

1.20 backport of https://github.com/apache/flink/commit/986f89ac120fdff0d3b9bd738e06e39c28617785, 
https://github.com/apache/flink/commit/5aaff07fe925b289a2cabe9269a015ebc2255223
and https://github.com/apache/flink/commit/d8cd5591d3136187695727202dc16bc96ce2caae

[BP-1.20][FLINK-37609][format]  Bump parquet to 1.15.1

---

flink-formats/flink-sql-parquet/src/main/resources/META-INF/NOTICE
flink-formats/pom.xml

2.0 backport of https://github.com/apache/flink/pull/26398

[BP-2.0][FLINK-37609][format] Bump parquet to 1.15.1

---

flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/AbstractAggregatingState.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/AbstractKeyedState.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/AbstractListState.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/AbstractMapState.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/AbstractReducingState.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/AbstractValueState.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionControllerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractAggregatingStateTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractListStateTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractMapStateTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractReducingStateTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractValueStateTest.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStAggregatingState.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStListState.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStMapState.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStReducingState.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStValueState.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStDBOperationTestBase.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateMigrationTest.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateTestBase.java

Make ForStState Restore from previous StateMetaInfo
Currently, when creating using ForStKeyedStateBackend create a new State , AbstractKeyedState will directly use the serializer in StateDescriptor regardless of whether it is restored from a Checkpoint.
However, this may cause data to be unable to be restored when the last serializer changes (for example, the class registration order in KryoSerializer has changed, for specific cases, please refer to StateBackendTestBase#testKryoRestoreResilienceWithDifferentRegistrationOrder). Therefore, when creating a State from a Checkpoint, oldStateInfo should be used as the new State's Serializer.
1. Add TypeSerializer to the constructor of AbstractKeyedState
2. ForStKeyedStateBackend uses oldStateMetaInfo as Serializer when creating State
This …

[FLINK-37524] Make ForStState Restore from previous StateMetaInfo

---

flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/NettyShuffleEnvironmentConfiguration.java

This PR aims to avoid duplicate fetch the size of memory segment.
Currently, we fetch pageSize at `NettyShuffleEnvironmentConfiguration.fromConfiguration` and then we fetch the pageSize at `NettyShuffleEnvironmentConfiguration.createNettyConfig` again.
To fetch pageSize, we call `ConfigurationParserUtils.getPageSize(configuration)` which have a lot of overhead.
```
public static int getPageSize(Configuration configuration) {
final int pageSize =
checkedDownCast(
configuration.get(TaskManagerOptions.MEMORY_SEGMENT_SIZE).getBytes());
// check page size of for minimum size
checkConfigParameter(
pageSize >= MemoryManager.MIN_PAGE_SIZE,
pageSize,
TaskManagerOptions.MEMORY_SEGMENT_SIZE.key(),
"Minimum memory segment size is " + MemoryManager.MIN_PAGE_SIZE);
// check page size for power of two …
```

[hotfix] Avoid duplicate fetch the size of memory segment

---

docs/content.zh/docs/dev/table/functions/ptfs.md
docs/content.zh/docs/dev/table/types.md
docs/content/docs/dev/table/functions/ptfs.md
docs/content/docs/dev/table/types.md

*Fix broken tabs and Process table function(PTF) time example `PingLaterFunction` param err*
- `DESCRIPTOR` tabs id is same with `BOOLEAN`.
-  `PingLaterFunction` param err:
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery …

[hotfix][docs] Fix broken tabs and PTF example argument errors

---

docs/content/docs/libs/state_processor_api.md
flink-libraries/flink-state-processing-api/pom.xml
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/table/SavepointConnectorOptions.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/table/SavepointDataStreamScanProvider.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/table/SavepointDynamicTableSource.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/table/SavepointMetadataTableFunction.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/table/module/StateModule.java
flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/table/module/StateModuleFactory.java
flink-libraries/flink-state-processing-api/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/table/SavepointDynamicTableSourceTest.java
flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/table/SavepointMetadataDynamicTableSourceTest.java

Savepoint metadata is useful information from user perspective but it's not yet available from SQL perspective. In this PR I've added support for this, please see [FLIP512](https://cwiki.apache.org/confluence/display/FLINK/FLIP-512%3A+Add+meta+information+to+SQL+state+connector) for further details.
I've also added some tiny name rationalization in comments.
Added savepoint metadata SQL built-in process function.
New automated test.
- The S3 …

[FLINK-37407][state] Add savepoint metadata SQL built-in process function

---

flink-metrics/flink-metrics-prometheus/pom.xml
flink-metrics/flink-metrics-prometheus/src/test/java/org/apache/flink/metrics/prometheus/PrometheusReporterTaskScopeTest.java
flink-metrics/flink-metrics-prometheus/src/test/java/org/apache/flink/metrics/prometheus/PrometheusReporterTest.java

Remove Unirest dependency in PrometheusReporterTest
This change removes the dependency on the Unirest HTTP client library. Unirest was only used in PrometheusReporterTest for polling metrics. This commit replaces the single usage of Unirest.get() with the standard Java HttpClient, reducing external dependencies. …

[FLINK-37601] Remove Unirest dependency in PrometheusReporterTest

---

flink-runtime/src/main/java/org/apache/flink/streaming/api/transformations/OneInputTransformation.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/JobGraphGeneratorTestBase.java

Backport https://github.com/apache/flink/pull/26283 to release-2.0
Throw an exception when enableAsyncState() for synchronous operators.
- Override `OneInputTransformation#enableAsyncState()`
- `JobGraphGeneratorTestBase#testEnableAsyncStateForSyncOperatorThrowException` …

[BP-2.0][FLINK-37458][datastream] Forbid enableAsyncState() for synchronous operators

---

flink-python/pyflink/table/tests/test_table_environment_api.py
flink-python/pyflink/table/utils.py

If you call `TableEnvironment.from_elements` where one of the fields in the row contains a `Row`, for example where one of the values you pass in is:
```
[
Row("pyflink1A", "pyflink2A", "pyflink3A"),
Row("pyflink1B", "pyflink2B", "pyflink3B"),
Row("pyflink1C", "pyflink2C", "pyflink3C"),
],
```
where the schema for the field is:
```
DataTypes.ARRAY(
DataTypes.ROW(
[
DataTypes.FIELD("a", DataTypes.STRING()),
DataTypes.FIELD("b", DataTypes.STRING()),
DataTypes.FIELD("c", DataTypes.STRING()),
]
)
),
```
When you call `execute().collect()` on the table, the array is returned as:
```
[
Row(['pyflink1a', 'pyflink2a', 'pyflink3a']),
Row(['pyflink1b', 'pyflink2b', 'pyflink3b']),
Row(['pyflink1c', 'pyflink2c', 'pyflink3c'])
]
```
Instead of each `Row` having 3 values, the collected row only has 1 …

[FLINK-37616][python] Fix incorrect unpickling of Row fields

---

flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/InternalSourceSplitMetricGroup.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/SourceOperator.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/SourceOperatorSplitWatermarkAlignmentTest.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/source/TestingSourceOperator.java

Closing the metric group of a finished split
Added a test to verify the group is closed and metrics are deregistered.
For the test setup I removed a redundant initialization of `org.apache.flink.streaming.api.operators.AbstractStreamOperator#metrics` (since an `UnregisteredMetricGroup` is already passed to it via the `org.apache.flink.streaming.runtime.tasks.StreamMockEnvironment#taskMetricGroup`)

[FLINK-37596][metrics] Close metric group of a finished split

---

docs/content.zh/docs/ops/state/disaggregated_state.md
docs/content/docs/ops/state/disaggregated_state.md
docs/layouts/shortcodes/generated/forst_configuration.html
docs/layouts/shortcodes/generated/state_backend_forst_section.html
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackendBuilder.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStOptions.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStStateBackend.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/sync/ForStPriorityQueueConfig.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/sync/ForStSyncKeyedStateBackend.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/sync/ForStSyncKeyedStateBackendBuilder.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateBackendTest.java

This PR makes ForSt Sync mode support remote storage and provide `state.backend.forst.sync.enforce-local`.
- Add `state.backend.forst.sync.enforce-local` to `ForStOptions`.
- Set remote directory for `ForStSyncKeyedStateBackend` when configured.
- Remove some useless code in `ForStSyncKeyedStateBackend.java`
- ForStStateBackendTest#testCreateKeyedStateBackend
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (yes / no )
- The S3 …

[FLINK-37620][state/forst] ForSt Sync mode support remote storage

---

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/CachedDataInputStream.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/FileBasedCache.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystemTest.java

There is a concurrency issue for reference counting in ForSt file cache, which could lead to a read error in some special scenarios (e.g. extremely frequent cache thrashing)
Two problem:
- All the read interfaces in `CachedDataInputStream` should release the reference **only after** the stream is not the `originalStream`
- The stream retrieving methods in task threads should consider the latency of status switch.
This change is already covered by existing tests, such as `ForStFlinkFileSystemTest`. …

[FLINK-37628] Fix reference counting in ForSt file cache

---

flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/RegisteredKeyValueStateBackendMetaInfo.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStStateMigrationTest.java

…during restoring state
Make ForStKeyedStateBackend update NamespaceSerializer during restoring state
- add `updateNamespaceSerializer` in `RegisteredKeyValueStateBackendMetaInfo`
- invoke RegisteredKeyValueStateBackendMetaInfo#updateNamespaceSerializer when creating State
add unit test ForStStateMigrationTest#testStateNamespaceSerializerChanged …

[FLINK-37553] Make ForStKeyedStateBackend update NamespaceSerializer during restoring state

---

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/CachedDataInputStream.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/cache/FileBasedCache.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystemTest.java

Backport for #26415
There is a concurrency issue for reference counting in ForSt file cache, which could lead to a read error in some special scenarios (e.g. extremely frequent cache thrashing)
Two problem:
- All the read interfaces in `CachedDataInputStream` should release the reference **only after** the stream is not the `originalStream`
- The stream retrieving methods in task threads should consider the latency of status switch.
This change is already covered by existing tests, such as `ForStFlinkFileSystemTest`. …

[BP-2.0][FLINK-37628] Fix reference counting in ForSt file cache

---

docs/layouts/shortcodes/generated/rest_v1_dispatcher.html
docs/static/generated/rest_v1_dispatcher.yml
flink-clients/src/test/java/org/apache/flink/client/program/rest/RestClusterClientTest.java
flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/handlers/JarSubmissionITCase.java
flink-runtime-web/src/test/resources/rest_api_v1.snapshot
flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/AccessExecutionGraph.java
flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ArchivedExecutionGraph.java
flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraph.java
flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraphBuilder.java
flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionGraph.java
flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/jsonplan/JsonPlanGenerator.java
flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/JobDetailsHandler.java
flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/JobPlanHandler.java
flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/JobPlanInfo.java
flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/JobDetailsInfo.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/CreatingExecutionGraph.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptivebatch/AdaptiveBatchScheduler.java
flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/ExecutionGraphInfoStoreTestUtils.java
flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ArchivedExecutionGraphTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/jobgraph/jsonplan/JsonGeneratorTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/legacy/utils/ArchivedExecutionGraphBuilder.java
flink-runtime/src/test/java/org/apache/flink/runtime/rest/messages/job/JobDetailsInfoTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/StateTrackingMockExecutionGraph.java
flink-tests/src/test/java/org/apache/flink/test/scheduling/ReactiveModeITCase.java

The pr follows refactors done over time to transition rest object classes to use modern auto-serialization instead of implementing their own serializations.
Doing the same for `org.apache.flink.runtime.rest.messages.JobPlanInfo.Plan` improves error handling and makes the restAPI more informative about expected response.
- `org.apache.flink.runtime.rest.messages.JobPlanInfo.Plan` type refactored to object instead of a string
- References updated as well
- `org.apache.flink.runtime.jobgraph.jsonplan.JsonGeneratorTest#testGeneratorWithoutAnyAttachements`
- `org.apache.flink.runtime.rest.messages.JobPlanInfoTest#testJsonMarshalling`
We don't have any compatibility tests in place but there are no visible …

[FLINK-37511][rest] Use Jackson serialization in JobPlanInfo.Plan

---

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/optimize/program/FlinkChangelogModeInferenceProgram.scala
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/agg/OverAggregateTest.xml
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/agg/OverAggregateTest.scala

- Avoid IndexOutOfBoundsException when an OverAgg query is used without specifying an Order By clause
- If ORDER BY clause is not specified in an Over agg, it would lead to IndexOutOfBoundsException
- This commit adds a check to ensure orderby fields exists before accessing them
- Added test that validates OverAgg query can be used without an ORDER BY clause
- The S3 file …

[FLINK-37610] Check if orderBy keys exists before accessing

---

flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/AsyncExecutionController.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperator.java
flink-runtime/src/main/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorV2.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/tasks/mailbox/MailboxExecutorImpl.java
flink-runtime/src/test/java/org/apache/flink/runtime/asyncprocessing/operators/AbstractAsyncStateStreamOperatorTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/AbstractAsyncStateStreamOperatorV2Test.java

Use the mailboxExecutor with correct priority when creating `AsyncExecutionController` in Async state processing.
- Use the mailboxExecutor for operator in `AbstractAsyncStateStreamOperator` and `AbstractAsyncStateStreamOperatorV2`
- Add `MailboxExecutorImpl#getPriority` for testing
- `AbstractAsyncStateStreamOperatorTest#testCreateAsyncExecutionController`
- `AbstractAsyncStateStreamOperatorTestV2#testCreateAsyncExecutionController` …

[FLINK-37642][runtime] Use the mailboxExecutor for operator in Async state processing

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/data/ArrayData.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/data/RowData.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/data/DataStructureConvertersTest.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/typeutils/RowDataSerializerTest.java

This PR makes it possible to convert `RowData` that represents partial deletes with `NOT NULL` fields to `Row`.
Added tests in `DataStructureConvertersTest` …

[FLINK-37643] Support partial deletes when converting to external data structures

---

flink-clients/src/main/java/org/apache/flink/client/cli/CliFrontend.java

This PR aims to avoid duplicate call on `checkNotNull`. The method fromProgramOptions already contains the check show below.
```
public static <T> ExecutionConfigAccessor fromProgramOptions(
final ProgramOptions options, final List<T> jobJars) {
checkNotNull(options);
checkNotNull(jobJars);
// ignore others.
}
```
Avoid duplicate call on `checkNotNull` while calling `fromProgramOptions`. …

[hotfix] Avoid duplicate call on checkNotNull while calling fromProgramOptions

---

flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/connector/datagen/table/RandomGeneratorVisitor.java
flink-table/flink-table-api-java-bridge/src/test/java/org/apache/flink/table/factories/DataGenTableSourceFactoryTest.java

*Fix the bug that datagen connector cannot set length for collection type.*
- *Add `lenOption` to the legitimate set of options*.
Introduce a unit test case to cover this.

[FLINK-37649][datagen] Datagen connector cannot set length for collection type

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/ChangelogMode.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/connector/ChangelogModeTest.java

Fixes the `ChangelogMode#toString`.
Added a unit test

[FLINK-37671] Fix ChangelogMode#toString

---

flink-clients/src/main/java/org/apache/flink/client/cli/CliFrontend.java
flink-clients/src/test/java/org/apache/flink/client/cli/CliFrontendRunTest.java

This PR aims to avoid duplicate call on `getEffectiveConfiguration`.
The code of `getEffectiveConfiguration` show below, I think it has a lot of overhead.
```
private Configuration getEffectiveConfiguration(
final CustomCommandLine activeCustomCommandLine, final CommandLine commandLine)
throws FlinkException {
final Configuration effectiveConfiguration = new Configuration(configuration);
final Configuration commandLineConfiguration =
checkNotNull(activeCustomCommandLine).toConfiguration(commandLine);
effectiveConfiguration.addAll(commandLineConfiguration);
return effectiveConfiguration;
}
```
Avoid duplicate call on `getEffectiveConfiguration`.
- The public …

[FLINK-37638] Avoid duplicate call on getEffectiveConfiguration

---

flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/OperatorEvent.java
flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/SubtaskGatewayImpl.java
flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinator.java
flink-runtime/src/main/java/org/apache/flink/runtime/source/event/WatermarkAlignmentEvent.java
flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/EventReceivingTasks.java
flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/SubtaskGatewayImplTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/TestOperatorEvent.java
flink-tests/src/test/java/org/apache/flink/test/streaming/api/datastream/WatermarkAlignmentITCase.java

Previously WatermarkAlignmentEvent was incorrectly ignored and never
sent if source enumerator had no more splits to assign/send.
This was causing deadlocks, with watermark aligmnent not being
able to progress in such cases.
Added new unit test and modified a pre-existing ITCase to cover for the problematic situation. …

[FLINK-37670][runtime] Fix watermark alignment can deadlock job if there are no more splits to be assigned

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/sink/DynamicTableSink.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/sink/abilities/SupportsTargetColumnWriting.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/connectors/DynamicSinkUtils.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/abilities/sink/SinkAbilitySpec.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/abilities/sink/TargetColumnWritingSpec.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TestValuesTableFactory.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/serde/DynamicTableSinkSpecSerdeTest.java

Introduce new SupportsTargetColumnWriting sink ability and TargetColumnWritingSpec
- Introduce new SupportsTargetColumnWriting sink ability and TargetColumnWritingSpec
DynamicTableSinkSpecSerdeTest#testDynamicTableSinkSpecSerde …

[FLINK-37540][table-planner] Introduce SupportsTargetColumnWriting sink ability

---

flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/OperatorEvent.java
flink-runtime/src/main/java/org/apache/flink/runtime/operators/coordination/SubtaskGatewayImpl.java
flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinator.java
flink-runtime/src/main/java/org/apache/flink/runtime/source/event/WatermarkAlignmentEvent.java
flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/EventReceivingTasks.java
flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/SubtaskGatewayImplTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/operators/coordination/TestOperatorEvent.java
flink-tests/src/test/java/org/apache/flink/test/streaming/api/datastream/WatermarkAlignmentITCase.java

2.0 backport of https://github.com/apache/flink/pull/26453

[FLINK-37670][runtime] Fix watermark alignment can deadlock job if there are no more splits to be assigned (2.0) 

---

docs/content/docs/connectors/table/overview.md
docs/setup_docs.sh

Update MongoDB docs for 2.0.0 release
Update MongoDB docs for 2.0.0 release

[FLINK-37197][docs] Update MongoDB docs for 2.0.0 release

---

docs/content.zh/docs/dev/table/sql/queries/hints.md
docs/content/docs/dev/table/sql/queries/hints.md

This PR adds a document section to the lookup custom shuffle feature introduced in #25729.
Adds a document section to the lookup custom shuffle feature introduced in #25729.
This is a document change that does not require program correctness verification.

[FLINK-35652][doc] Add document for lookup custom shuffle

---

docs/content.zh/docs/connectors/table/datagen.md
docs/content/docs/connectors/table/datagen.md

Amend the DataGen connector docs as agreed in PR [26437](https://github.com/apache/flink/pull/26437).
I have added the example from the PR into the docs and have made small improvements to the text. I have added a Chinese version of the doc change. 
Include a length example for collections - which now works after  PR [26437](https://github.com/apache/flink/pull/26437).
Also make minor improvements to the test in this section.
Please make sure both new and modified tests in this PR follow [the conventions for tests defined in our code quality …

[FLINK-37658][docs] Improve the Datagen connector docs

---

docs/layouts/shortcodes/generated/optimizer_config_configuration.html
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/config/OptimizerConfigOptions.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/reuse/SinkReuser.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/delegation/PlannerBase.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/batch/BatchPhysicalSink.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/reuse/SubplanReuser.scala
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/batch/sql/BatchSinkReuseTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/common/SinkReuseTestBase.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/common/sql/SinkReuseITCase.java
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/batch/sql/BatchSinkReuseTest.xml

Support sink reuse in batch mode
- Introduce SinkReuser to reuse sink node in Batch mode
This change is covered by tests, such as *(please describe tests)*.
BatchSinkReuseTest
SinkReuseITCase
- If yes, how is the feature documented?  FLIP-506

[FLINK-37543][table-planner] Support sink reuse in batch mode

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/optimize/ChangelogNormalizeRequirementResolver.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/stream/sql/ChangelogNormalizeOptimizationTest.java
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/ChangelogNormalizeOptimizationTest.xml

Do not try removing `ChangelogNormalize` if `"table.exec.source.cdc-events-duplicate" = "true"`
Added a plan test

[FLINK-37691] Do not remove ChangelogNormalize if deduplication was requested

---

docs/layouts/shortcodes/generated/optimizer_config_configuration.html
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/config/OptimizerConfigOptions.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/reuse/SinkReuser.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalSink.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/reuse/SubplanReuser.scala
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/common/SinkReuseTestBase.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/stream/sql/StreamSinkReuseTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/common/sql/SinkReuseITCase.java
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/StreamSinkReuseTest.xml

Support sink reuse in streaming mode
- Introduce SinkReuser to reuse sink node in Batch mode
This change is covered by tests, such as *(please describe tests)*.
StreamSinkReuseTest
SinkReuseITCase
- If yes, how is the feature documented?  FLIP-506

[FLINK-37542][table-planner] Support sink reuse in streaming mode

---

docs/content.zh/docs/ops/metrics.md
docs/content/docs/ops/metrics.md
flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricNames.java
flink-runtime/src/main/java/org/apache/flink/runtime/metrics/util/MetricUtils.java
flink-runtime/src/test/java/org/apache/flink/runtime/metrics/util/MetricUtilsTest.java

Add file descriptor related JVM metrics
- Add the default registration in MetricUtils
- Added test in MetricUtilsTest
- Added test in MetricUtilsTest

[FLINK-37709][metrics] add file descriptor jvm metrics

---

docs/layouts/shortcodes/generated/yarn_config_configuration.html
flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
flink-yarn/src/main/java/org/apache/flink/yarn/configuration/YarnConfigOptions.java
flink-yarn/src/test/java/org/apache/flink/yarn/YarnClusterDescriptorTest.java

A long-running YARN app will eventually fill the local disk with logs, unless there is a rolling Log4J strategy is applied to limit the log files to X archive with Y size. But if there is a policy to store the logs for months or years, throwing away the logs too early is also problematic. YARN is able to aggregate specific files for running applications, so this way, it is possible to aggregate the rolled over logs to external storage and store it until the end of times if that's the reqquirement. :)
- Added new optional config options to define `include` and `exclude` regex patterns.
- Wired in these values into YARN's `LogAggregationContext` during cluster deployment.
- Updated docs.
- Added new unit test for the added logic.
- Existing unit tests guarantee that by default the …

[FLINK-26425][yarn] Support rolling log aggregation

---

flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystem.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/fs/filemapping/FileOwnershipDecider.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/fs/ForStFlinkFileSystemTest.java

When forst starts to restore from reused checkpoint, the mapping entries include:
1. remote uuid -> state handle (also remote uuid path in the state handle)
2. remote sst -> remote uuid
When restored, the file is existed, but fails because it always try to find a sst in the local filesystem.
We should avoid reading NOT_OWNED file by local file system when restoring.
- Judge whether the file is NOT_OWNED when trying to access local file system.
- *Added ForStFlinkFileSystemTest#testNotOwnedFileStatus*
- The runtime per-record code paths (performance sensitive): (yes / **no** / …

[FLINK-37693][state] Avoid reading NOT_OWNED file by local file system when restoring

---

flink-python/pyflink/datastream/data_stream.py
flink-python/pyflink/fn_execution/embedded/converters.py
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/window/GlobalWindow.java
flink-tests/src/test/java/org/apache/flink/test/completeness/TypeSerializerTestCoverageTest.java

add support for org.apache.flink.table.runtime.operators.window.GlobalWindow. In flink-python/src/main/java/org/apache/flink/streaming/api/operators/python/embedded/EmbeddedPythonWindowOperator.java, org.apache.flink.table.runtime.operators.window.Window is used, but we only have implementation for org.apache.flink.streaming.api.windowing.windows.GlobalWindow, which can't be cast to org.apache.flink.table.runtime.operators.window.Window. 
- add implementation for org.apache.flink.table.runtime.operators.window.GlobalWindow
- modify pyflink to use org.apache.flink.table.runtime.operators.window.GlobalWindow instead of org.apache.flink.streaming.api.windowing.windows.GlobalWindow.
- Dependencies (does it add or …

[FLINK-37728][python] add support org.apache.flink.table.runtime.operators.window.GlobalWindow

---

flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/sink/compactor/operator/CompactorOperator.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/CommittableMessage.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/BoundedOneInput.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperator.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManagerImpl.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollector.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/connector/sink2/GlobalCommitterOperatorTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperatorTestBase.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperatorTestBase.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/util/AbstractStreamOperatorTestHarness.java

Backport of #26433. Prod code unchanged. Test refactor skipped and new test moved to `SinkWriterOperatorTestBase`.

[FLINK-37605][runtime] Infer checkpoint id on endInput in sink [1.20]

---

flink-connectors/flink-connector-files/src/main/java/org/apache/flink/connector/file/sink/compactor/operator/CompactorOperator.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/connector/sink2/CommittableMessage.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/BoundedOneInput.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperator.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CheckpointCommittableManagerImpl.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollector.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/connector/sink2/GlobalCommitterOperatorTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperatorTestBase.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkWriterOperatorTestBase.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/committables/CommittableCollectorTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/util/AbstractStreamOperatorTestHarness.java

Backport of https://github.com/apache/flink/pull/26433. 
Unchanged compared to 1.20 backport. Prod code unchanged. Test refactor skipped and new test moved to SinkWriterOperatorTestBase.

[FLINK-37605][runtime] Infer checkpoint id on endInput in sink [1.19]

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/ChangelogMode.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/ChangelogModeJsonDeserializer.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/ChangelogModeJsonSerializer.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/serde/ChangelogModeJsonSerdeTest.java

Make it possible to serialize partial deletes into a compiled plan
Added a test in `ChangelogModeJsonSerdeTest`

[FLINK-37745] Serialize partial deletes in ChangelogMode to JSON

---

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/ExprCodeGenerator.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/JsonGenerateUtils.scala
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/JsonFunctionsITCase.java

Parsing for a JSON() function call fails if its position is not the first param of JSON_OBJECT.
`SELECT JSON_OBJECT('key' VALUE JSON('{}'), 'key_2' VALUE JSON('{}'));`
Outputs:
```
The JSON() function is currently only supported inside a JSON_OBJECT() or JSON_ARRAY() function. Example: JSON_OBJECT('a', JSON('{\"key\": \"value\"}')) or JSON_ARRAY(JSON('{\"key\": \"value\"}'))
```
This is incorrect, we were too strict with the limitations. We're strictly allowing json to be called only as the second param in the function, when it should be allowed for every second. 
- Check if the `JSON` call is for any of the VALUES param inside a `JSON_OBJECT` and not only the first one
- Added unit tests
- Dependencies (does it add …

[FLINK-37695][table] Fix parsing for built-in function JSON in JSON_OBJECT for all positions

---

flink-python/pyflink/common/types.py
flink-python/pyflink/table/tests/test_table_environment_api.py
flink-python/pyflink/table/types.py

When creating a table using `TableEnvironment.from_elements`, the Table API skips type validation on any Row elements that were created using positional arguments, rather than keyword arguments. 
For example, take a table with a single column, whose type is an array of Rows. These rows have 2 columns, `a VARCHAR` and `b BOOLEAN`. If we create a table with elements where one of these rows has columns with incorrect datatypes:
```python
schema = DataTypes.ROW(
[
DataTypes.FIELD(
"col",
DataTypes.ARRAY(
DataTypes.ROW(
[
DataTypes.FIELD("a", DataTypes.STRING()),
DataTypes.FIELD("b", DataTypes.BOOLEAN()),
]
)
),
),
]
) 
elements = [(
[("pyflink", True), ("pyflink", False), (True, "pyflink")],
)] 
table = self.t_env.from_elements(elements, schema)
table_result = list(table.execute().collect()) …
```

[FLINK-37625][python] Don't skip type validation for Rows made with positional arguments

---

flink-python/docs/Makefile

I noticed that building the Flink Python API docs by running `make html` in `flink-python/docs` can take longer than I expected - often well over 1 minute, which can be a little disruptive when working on the docs. This PR adds `-j auto` to the sphinx build options, which makes Sphinx distribute the build over N processes in parallel, where N is the number of CPUs available, which is better when building on multiprocessor machines. With this enabled fresh Sphinx builds take less than 20 seconds, on my personal machine.
Edit - Just to see in CI:
- [Before](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=67394&view=logs&j=9cada3cb-c1d3-5621-16da-0f718fb86602&t=c67e71ed-6451-5d26-8920-5a8cf9651901): 1m 32s
- [This …

[hotfix][python] Enable parallel builds for python API docs

---

.github/workflows/template.flink-ci.yml

After migrating the test infrastructure away from `conda` to `uv`, we ran into issues with missing `libpython` and `Python.h` headers in the tests. This is because while `conda` creates a fully portable python environment, `uv` does not.
This was [addressed](https://github.com/apache/flink/blob/master/tools/azure-pipelines/e2e-template.yml#L51:L53) in the initial migration in the azure pipelines, but was missing from the Github actions pipelines. This PR fixes this. An example of a GHA with this commit is fully green: https://github.com/autophagy/flink/actions/runs/14679294188/job/41200060044
(As a note - it might be better for the docker image used for the GHA pipelines to handle ensuring `libpython` etc is present instead of in the pipelines directly, but I figured this was the easiest …

[FLINK-37523][CI] Fix Python test/e2e tests missing libpython/python headers

---

flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/TableSinkITCase.scala

The reason for this test failure is the same as the `testSinkDisorderChangeLog` in [FLINK-36167](https://issues.apache.org/jira/browse/FLINK-36167). Since we have already fixed the root cause in [pr](https://github.com/apache/flink/pull/25892), we can safely remove the Disabled tag.
- *Remove the tag `Disabled` in this test*
Existent tests can cover this fix. …

[FLINK-36166][table-planner] Make the test 'testJoinDisorderChangeLog' work again

---

tools/azure-pipelines/jobs-template.yml

This change ensures that Python installation (Python.h headers, etc) are available during tests, regardless of whether the underlying CI machine has Python installed or not. We already do this in the [e2e template](https://github.com/apache/flink/blob/master/tools/azure-pipelines/e2e-template.yml#L51:L53) .
- *Added `UsePythonVersion` step for Azure Pipelines Python tests*

[FLINK-37702][ci] Ensure Python setup/headers for Python tests

---

flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkV2CommitterOperatorTest.java
flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/SinkV2ITCase.java

Fix the issue that GlobalCommitterOperator stuck when upstream operator - writer/committer is scaled up.
Use the old subtask count from restored state instead of new subtask count.
When writer/committer operator is restored after scaling up, new tasks without restored state won't send CommittableSummary to downstream GlobalCommitterOperator. So if writer/committer sends subtasks of new run, GlobalCommitterOperator will stuck forever as it is looking for CommittableSummary for new tasks.
More details are describe here: https://issues.apache.org/jira/projects/FLINK/issues/FLINK-37747
Update existed UT case to cover the code change. …

[FLINK-37747][runtime] Use old subtask count for restored committable objects

---

flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/TimestampsAndWatermarksOperator.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/TimestampsAndWatermarksOperatorTest.java

backport of https://github.com/apache/flink/pull/26539 to 2.0

[FLINK-37545][metrics] Fix StackOverflowError when using MetricGroup in custom WatermarkStrategy (1.20)

---

flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/TimestampsAndWatermarksOperator.java
flink-runtime/src/test/java/org/apache/flink/streaming/runtime/operators/TimestampsAndWatermarksOperatorTest.java

backport of https://github.com/apache/flink/pull/26539 to 2.0

[FLINK-37545][metrics] Fix StackOverflowError when using MetricGroup in custom WatermarkStrategy (2.0)

---

flink-clients/src/main/java/org/apache/flink/client/program/rest/RestClusterClient.java
flink-runtime/src/main/java/org/apache/flink/runtime/rest/RestClient.java
flink-runtime/src/test/java/org/apache/flink/runtime/rest/RestClientTest.java

Support external eventLoopGroup for RestClient
- *Support pass an external eventLoopGroup in the constructor of RestClient*
- *Close only for internal eventLoopGroup, not for external*
The change is tested by RestClientTest.testExternalEventGroup

[FLINK-36876] Support external eventLoopGroup for RestClient

---

flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/AbstractChangelogStateBackend.java

This PR proposes to remove unnecessary `StateBackend`.
Since `DelegatingStateBackend` already extends `StateBackend`.
Remove unnecessary `StateBackend`.

[hotfix] Remove unnecessary StateBackend

---

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/ShowCreateUtil.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ShowCreateModelOperation.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlNodeConverters.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlShowCreateModelConverter.java
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/TableEnvironmentTest.scala

support convert `show create model` sql to operation.
* Add converter to convert `show create model` sql to operation.
Unit test

[FLINK-35019] support convert show create model sql to operation

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/codegen/AsyncCodeGenerator.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/codegen/AsyncCodeGeneratorTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/table/AsyncCalcITCase.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/calc/async/DelegatingAsyncResultFuture.java

The bug comes from the fact that previously, we were creating an anonymous function callback within the janino generated code. This function was then referencing the local `DelegatingAsyncResultFuture`, effectively creating a closure. When the function was called back from different threads, they seemed to both reference the same `DelegatingAsyncResultFuture` rather than their own local ones. The result was returning incorrect "synchronous" results, so queries like the following might have issues:
```
SELECT f1, func(f1, f2, f3) FROM Table1;
```
Here, the f1 column returned was retrieved by asking for it from the local `DelegatingAsyncResultFuture`, and so getting the wrong instance meant getting the wrong result.
To fix it, I removed the inner anonymous function and just added the same …

[FLINK-37721] Fixes janino bug returning incorrect results

---

flink-table/flink-sql-parser/src/main/codegen/data/Parser.tdd
flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl
flink-table/flink-sql-parser/src/main/java/org/apache/calcite/sql/SqlExplicitModelCall.java
flink-table/flink-sql-parser/src/main/java/org/apache/calcite/sql/SqlExplicitModelOperator.java
flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java

Parse `MODEL` keyword in function argument and convert it to `SqlExplicitModelCall` with `SqlExplicitModelOperator`.
* Parser changes to support `MODEL` keyword in function argument.
* `SqlExplicitModelCall` sql node for model argument
* `SqlExplicitModelOperator` sql operator
Added unit test for parser changes …

[FLINK-37778][1/N] introduce MODEL keyword for model as argument

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/expressions/ValueLiteralExpression.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/QueryOperationTestPrograms.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/expressions/LiteralExpressionsSerializationITCase.java

When creating a literal from a LocalTime object without seconds, like `LocalTime.of(12, 12)`, the serialisable string form of the value literal is serialized into invalid SQL expression, in this case `TIME '12:12'` instead of `TIME '12:12:00'`, resulting in: 
```
org.apache.flink.table.api.ValidationException: SQL validation failed: Illegal TIME literal '12:12': not in format 'HH:mm:ss'
```
This also affects LocalDateTime objects used in the same way:
```
org.apache.flink.table.api.ValidationException: SQL validation failed: Illegal TIMESTAMP literal '2024-02-03 12:12': not in format 'yyyy-MM-dd HH:mm:ss'
```
This is because the default `LocalTime.toString()` elides the seconds if the `LocalTime`'s seconds are zero. This PR formats `LocalTime` to the ISO Local Time format, which is …

[FLINK-37803][table] Fix SQL serialization when using LocalTime value literal without seconds

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/AsyncCalcSplitRule.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/AsyncCorrelateSplitRule.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/RemoteCorrelateSplitRule.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/FlinkStreamRuleSets.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/logical/PythonCalcSplitRule.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/logical/RemoteCalcCallFinder.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/rules/logical/AsyncCalcSplitRuleTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/rules/logical/AsyncCorrelateSplitRuleTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/runtime/stream/table/AsyncCalcITCase.java
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/AsyncCorrelateSplitRuleTest.xml

Moves `PythonCorrelateSplitRule` to be common as `RemoteCorrelateSplitRule` so that we can move Async Scalars out of correlate queries.  Today an attempt to use an AsyncCalc in a correlate results in a codegen error:
```
@Test
public void testTableFuncWithAsyncCalc() {
Table t1 = tEnv.fromValues(1, 2).as("f1");
tEnv.createTemporaryView("t1", t1);
tEnv.createTemporarySystemFunction("func", new RandomTableFunction());
tEnv.createTemporarySystemFunction("addTen", new AsyncFuncAdd10());
final List<Row> results = executeSql("select * FROM t1, LATERAL TABLE(func(addTen(f1)))");
final List<Row> expectedRows =
Arrays.asList(
Row.of(1, "blah 11"),
Row.of(1, "foo 11"),
Row.of(2, "blah 12"),
Row.of(2, "foo 12"));
assertThat(results).containsSequence(expectedRows);
}
```
Results in error:
```
Caused …
```

[FLINK-37725] Makes Async calcs share correlate split rule with Python

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/expressions/ValueLiteralExpression.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/QueryOperationTestPrograms.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/expressions/LiteralExpressionsSerializationITCase.java

[BP-1.19][FLINK-37803][table] Fix SQL serialization when using LocalTime value literal without seconds

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/expressions/ValueLiteralExpression.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/QueryOperationTestPrograms.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/expressions/LiteralExpressionsSerializationITCase.java

[BP-1.20][FLINK-37803][table] Fix SQL serialization when using LocalTime value literal without seconds

---

flink-python/dev/dev-requirements.txt
flink-python/pyproject.toml

*This pull request will limit Cython upper bound*
- *Limit Cython upper bound to 3.1.0*
- *original tests*
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no=)

[FLINK-37804][python] Limit Cython upper bound

---

docs/content.zh/docs/dev/configuration/overview.md
docs/content/docs/dev/configuration/overview.md
pom.xml
tools/releasing/NOTICE-binary_PREAMBLE.txt

Jira  [FLINK-37810](https://issues.apache.org/jira/browse/FLINK-37810
Update log4j to 2.24.3 to fix vulnerabilities
- If yes, how is the feature documented? (the is mentioned in the docs - so that has been updated)

[FLINK-37810] Update log4j to 2.24.3

---

docs/content.zh/docs/dev/configuration/overview.md
docs/content/docs/dev/configuration/overview.md
pom.xml
tools/releasing/NOTICE-binary_PREAMBLE.txt

`release-2.0` backport of https://github.com/apache/flink/pull/26570

[BP-2.0][FLINK-37810] Update log4j to 2.24.3

---

flink-table/flink-table-planner/src/main/java/org/apache/calcite/jdbc/SimpleCalciteSchema.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/catalog/CatalogCalciteSchema.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/catalog/CatalogManagerCalciteSchema.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/catalog/CatalogSchemaModel.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/catalog/DatabaseCalciteSchema.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/catalog/FlinkSchema.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/FlinkCalciteCatalogReader.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/catalog/DatabaseCalciteSchemaTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/FlinkCalciteCatalogReaderTest.java

Support `getModel` in `FlinkCalciteCatalogReader`
* Introduce `CatalogSchemaModel`
* Add `getModel` in `FlinkSchema`
* Add `getModel` in `FlinkCalciteCatalogReader`
* Copy `SimpleCalciteSchema` from Calcite to support `getModel`
Unit test

[FLINK-37779][2/N] extend catalog schema reader to get model

---

flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/state/rocksdb/RocksDBIncrementalCheckpointUtils.java

Remove duplicate comparing about intersect group range in Score of state handle.
Fix the compareTo logic. …

[hotfix][state] Remove duplicate comparing about intersect group range.

---

flink-core/src/main/java/org/apache/flink/api/common/accumulators/DoubleMaximum.java

The purpose of this change is to simplify the implementation of the clone() method in the DoubleMaximum class by leveraging the existing constructor DoubleMaximum(double value) instead of manually setting the max field
Brief change log:
The current implementation of the clone() method in the DoubleMaximum class uses the default constructor and manually sets the max field:
// Some comments here
@Override
public DoubleMaximum clone() {
DoubleMaximum clone = new DoubleMaximum();
clone.max = this.max;
return clone;
}
This can be simplified by directly using the existing constructor DoubleMaximum(double value) to initialize the cloned object. The proposed change is:
@Override
public DoubleMaximum clone() {
return new DoubleMaximum(this.max);
}
Verifying this …

[FLINK-37665]: Simplify DoubleMaximum.clone() Implementation

---

flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/tasks/AbstractInvokable.java

This PR aims to remove unnecessary method override for method invoke.
The interface `TaskInvokable` provides a method invoke show below.
`void invoke() throws Exception;`
As an implementation, `AbstractInvokable` overrides it. We could remove it.
Remove unnecessary method override for method invoke. …

[hotfix] Remove unnecessary method override for method invoke

---

.github/workflows/template.flink-ci.yml

I saw that the Python tests on GHA are failing occasionally with `fatal error: Python.h: No such file or directory`. This might be due to an inconsistent state of the underlying runners, some having the headers or some not - in either case, this PR adds a step to ensure their presence in the container.
- Explicitly install Python.h headers when running Python tests in Github Actions.

[hotfix][ci] Ensure presence of Python.h headers in Github Actions runners

---

flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/ChainingStrategy.java

This hotfix corrects the default value of chaining strategy in the javadocs.
Correct the description of javadocs in `ChainingStrategy.java` …

[hotfix][javadoc] Correct the default value of chaining strategy

---

.github/workflows/nightly.yml
flink-python/dev/dev-requirements.txt
flink-python/pyproject.toml

*This pull request makes will fix build mac wheels error in GHA*

[FLINK-37804][python][build] Fix build mac wheels error in GHA

---

flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonFormatFactory.java
flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/JsonFormatFactoryTest.java

- Make configuration 'json.decode.json-parser.enabled' take effect. The configuration 'json.decode.json-parser.enabled'  will never take effect, because of this configuration has not been added in `org.apache.flink.formats.json.JsonFormatFactory#optionalOptions`.
- Make configuration 'json.decode.json-parser.enabled' take effect. 
- Added test `JsonFormatFactoryTest#testDecodeJsonParseEnabled` …

[FLINK-37752][json] Make configuration 'json.decode.json-parser.enabled' take effect

---

.github/workflows/nightly.yml
flink-python/pyproject.toml
tools/azure-pipelines/build-python-wheels.yml

*This pull request will fix build mac wheels error on Python3.8 in GHA*

[FLINK-37804][python][build] Fix build mac wheels error on Python3.8 in GHA

---

docs/content.zh/docs/connectors/datastream/formats/parquet.md
docs/content.zh/docs/connectors/table/formats/avro-confluent.md
docs/content.zh/docs/connectors/table/formats/avro.md
docs/content/docs/connectors/datastream/formats/parquet.md
docs/content/docs/connectors/table/formats/avro-confluent.md
docs/content/docs/connectors/table/formats/avro.md
flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/typeutils/AvroSerializerSnapshot.java

Recently Apache Avro changed the documentation website. Lovely as it is, some links are broken linked from Apache Flink documentation and comments in code. Let's simply fix them by updating to new working links.
- Find all existing links by `rg 'https://avro.apache.org/docs/'`
- Replace with new link prefix `https://avro.apache.org/docs/++version++/`
- Update the page-specific link etc
Manually checked those links are valid in the change. …

[FLINK-37812][doc] Fix broken links to Apache Avro in doc and code

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/calcite/FlinkRexBuilder.java
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/ConvertToNotInOrInRuleTest.xml

Removes `FlinkRexBuilder#makeIn` since CALCITE-4888 and CALCITE-4632 are done/closed with 1.33
existing tests and `ConvertToNotInOrInRuleTest`

[FLINK-37845][table] Remove FlinkRexBuilder#makeIn

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/RexNodeJsonDeserializer.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/serde/RexNodeJsonSerdeTest.java

2.0 backport of https://github.com/apache/flink/pull/26586

[BP-2.0][FLINK-37820][table-planner] Support `AsyncScalarFunction` registration via `CompiledPlan`

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/RexNodeJsonDeserializer.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/serde/RexNodeJsonSerdeTest.java

1.19 backport of https://github.com/apache/flink/pull/26586

[BP-1.19][FLINK-37820][table-planner] Support `AsyncScalarFunction` registration via `CompiledPlan`

---

flink-metrics/flink-metrics-otel/src/main/java/org/apache/flink/metrics/otel/OpenTelemetryMetricReporter.java
flink-metrics/flink-metrics-otel/src/test/java/org/apache/flink/metrics/otel/OpenTelemetryMetricReporterITCase.java

Address flakiness of the test: `OpenTelemetryMetricReporterITCase.testReport`
Adding `@VisibleForTesting OpenTelemetryMetricReporter#waitForLastReportToComplete` method to allow synchronous use of `OpenTelemetryMetricReporter#report` in tests.
This change is already covered by existing tests, such as `OpenTelemetryMetricReporterITCase`. 
To ensure it is not flaky, I have run it locally as `@RepeatedTest(100)` with no issues (previously, fail rate was around 30%). …

[FLINK-37822][tests] Fix flaky test: OpenTelemetryMetricReporterITCase.testReport

---

docs/content.zh/docs/dev/table/types.md
docs/content/docs/dev/table/types.md
flink-table/flink-sql-parser/src/main/codegen/data/Parser.tdd
flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl
flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/type/SqlRawTypeNameSpec.java
flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/type/SqlStructuredTypeNameSpec.java
flink-table/flink-sql-parser/src/main/java/org/apache/flink/table/calcite/ExtendedRelTypeFactory.java
flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/Fixture.java
flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkDDLDataTypeTest.java
flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/TestRelDataTypeFactory.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/api/DataTypes.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/SpecificInputTypeStrategies.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/logical/DistinctType.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/logical/StructuredType.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/logical/UserDefinedType.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/logical/utils/LogicalTypeParser.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/utils/DataTypeUtils.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/LogicalTypeParserTest.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/LogicalTypesTest.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/LogicalTypeJsonDeserializer.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/LogicalTypeJsonSerializer.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/schema/StructuredRelDataType.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/calcite/FlinkTypeFactory.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CastFunctionMiscITCase.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/StructuredFunctionsITCase.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlNodeToCallOperationTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/serde/LogicalTypeJsonSerdeTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/typeutils/LogicalRelDataTypeConverterTest.java

This adds support for inline structured types in Flink SQL. Inline structured types are not a completely new type. They have been added as part of FLIP-37 when reworking the Flink table type system. However, mostly Table API users were able to use them properly. For SQL, there was no type DDL to cast or declare the type.
This PR improves handling inline structured types by supporting the type declaration:
```
STRUCTURED<'c', n0 t0 'd0', n1 t1 'd1', ...>
```
where `c` is the class name, `n` is the unique name of a field, `t` is the logical type of a field, `d` is the description of a field.
- Support `STRUCTURED<>` in SQL parser and logical type parser
- Decouple structured types from the hard requirement of a class being present in the classpath
- Support equality between types for …

[FLINK-37862][table] Support inline structured types in SQL

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/optimize/StreamNonDeterministicUpdatePlanVisitor.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/physical/stream/DuplicateChangesInferRule.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/physical/stream/FlinkDuplicateChangesTraitInitProgram.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/trait/DuplicateChanges.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/trait/DuplicateChangesTrait.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/trait/DuplicateChangesTraitDef.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/utils/DuplicateChangesUtils.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/delegation/StreamPlanner.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/optimize/RelNodeBlock.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/optimize/StreamCommonSubGraphBasedOptimizer.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/optimize/program/FlinkStreamProgram.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/FlinkStreamRuleSets.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/FlinkRelOptUtil.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/utils/RelTreeWriterImpl.scala
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/analyze/GroupAggregationAnalyzerTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/analyze/NonDeterministicUpdateAnalyzerTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/hint/ClearQueryHintsWithInvalidPropagationShuttleTestBase.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/hints/batch/JoinHintTestBase.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/rules/physical/stream/DuplicateChangesInferRuleTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/utils/DuplicateChangesUtilsTest.java
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/physical/stream/DuplicateChangesInferRuleTest.xml
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/utils/TableTestBase.scala

Introduce a new trait derived from sink to source to check whether the downstream operators can accept duplicate data produced by upstream nodes.
- *Introduce a new trait and inference rules about it.*
- *Add tests for all stream physical nodes*
Tests are added to verify this pr.

[FLINK-37896][table-planner] Introduce a new trait derived from sink to source to check whether the downstream operators can accept duplicate data

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamPhysicalMultiJoin.java

Adds StreamPhysicalMultiJoin that creates a StreamExecMultiJoin
- Adds StreamPhysicalMultiJoin implementing StreamPhysicalRel
- Add necessary private methods to instantiate params
This change will be only adds StreamExecMultiJoin. Tests will be added as soon as we can use it/test it. 

[FLINK-37916][table] Add StreamPhysicalMultiJoin

---

docs/content.zh/docs/dev/table/sql-gateway/overview.md
docs/content.zh/docs/dev/table/sqlClient.md
docs/content/docs/dev/table/sql-gateway/overview.md
docs/content/docs/dev/table/sqlClient.md

This pull request if for improving the SQL gateway documentation
Updated the doc with details on submitting a job via gateway to a remote host.
- Dependencies (does it add or upgrade a dependency): (yes / no) - no
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no) - no
- The serializers: (yes / no / don't know) - no
- The runtime per-record code paths (performance sensitive): (yes / no / don't know) - no …

[FLINK-37536] [TABLE-SQL] Improve SQL Gateway documentation

---

flink-runtime/src/main/java/org/apache/flink/runtime/state/AbstractStateBackend.java

This PR proposes to remove unnecessary `java.io.Serializable`.
Since `StateBackend` already extends `java.io.Serializable`.
Remove unnecessary `java.io.Serializable`.

[hotfix] Remove unnecessary java.io.Serializable

---

flink-connectors/flink-connector-files/src/test/java/org/apache/flink/connector/file/sink/FileSinkTest.java

There is a minor issue where all tests in the module containing FileSinkTest are written using JUnit 5 syntax, but FileSinkTest uses JUnit 4 imports. In this PR, we will complete the upgrade of FileSinkTest to JUnit 5.
In this PR, we have improved the following:
1. The class descriptor, as JUnit 5 no longer requires classes/methods to be public.
2. Replaced the original assertEquals with AssertJ syntax.
This change is very minor, and I don't plan to create a Jira for it.
Junit Test & CI
no.
no.

[hotfix][tests] Use Junit5 import in FileSinkTest.

---

.github/workflows/nightly.yml

2.0 backport of https://github.com/apache/flink/pull/26675

[BP-2.0][FLINK-37952] Skip compressing built python wheels by hand in Nightly workflow

---

.github/workflows/nightly.yml

1.20 backport of https://github.com/apache/flink/pull/26675

[BP-1.20][FLINK-37952] Skip compressing built python wheels by hand in Nightly workflow

---

flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveScheduler.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/allocator/JobAllocationsInformation.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/allocator/StateLocalitySlotAssigner.java
flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/adaptive/allocator/StateSizeEstimates.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/SchedulerTestingUtils.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/AdaptiveSchedulerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/ExecutingTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/allocator/StateLocalitySlotAssignerTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/adaptive/allocator/TestingSlotAllocator.java
tools/maven/checkstyle.xml

Address local recovery issues when Adaptive scheduler is enabled. 
1. Pass latest completed checkpoint in addition to execution graph to `StateSizeEstimates` (that is needed because execution graph goes through cancelling/cancelled state and checkpoint coordinator is `nulled` by the time we run calculations).
2. Assign positive priority score to allocations that have overlapping key groups even when state size is zero (currently we would only give priority score if `managedKeyedState` is present, but local recovery semantics doesn't `require` state presence).
**Context**: When job can be recovered locally, we should keep slot allocation after restart to maintain 
`LocalRecoveryITCase#testRecoverLocallyFromProcessCrashWithWorkingDirectory` now passes when `AdaptiveScheduler` is enabled. 
- …

[FLINK-37701][flink-runtime] Fix AdaptiveScheduler ignoring checkpoint states sizes for local recovery adjustment.

---

flink-runtime/src/main/java/org/apache/flink/streaming/runtime/io/checkpointing/CheckpointBarrierTracker.java

This PR aims to reuse the final field `barrierId` in `CheckpointBarrierTracker`.
Because the `barrierId` is a final field, we can reuse it safely.
Reuse the final field `barrierId`.

[hotfix] Reuse the final field barrierId

---

docs/content.zh/docs/connectors/models/_index.md
docs/content.zh/docs/connectors/models/openai.md
docs/content/docs/connectors/models/_index.md
docs/content/docs/connectors/models/openai.md

This PR is a continuation to #26652, adding document for the introduced OpenAI Model Function.
- Adds document for the OpenAI Model Function.

[FLINK-37799][model][docs] Add document for OpenAI Model Function

---

flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/DeltaJoinITCase.scala
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/lookup/keyordered/Epoch.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/lookup/keyordered/EpochManager.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/lookup/keyordered/TableAsyncExecutionController.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/join/lookup/TableKeyedAsyncWaitOperatorTest.java

Fix the inconsistency between the number handled by the table async execution controller and the number in the epoch. This bug causes the delta join itcases to hang.
- *Fix the bug*
- *Adapt the origin test*
- *Add timeout for delta join itcases*
Original test is adapted to verify this bug.

[FLINK-37976][table-runtime] Fix the inconsistency between the number handled by the table async execution controller and the number in the epoch

---

flink-python/dev/dev-requirements.txt
flink-python/pom.xml
flink-python/setup.py
flink-python/src/main/resources/META-INF/NOTICE

*This pull request will upgrade pemja to 0.5.3*
- *Upgrade pemja to 0.5.3 to fix some problem*
- *Origional tests*

[FLINK-37991][python] Upgrade pemja to 0.5.3

---

.github/workflows/community-review.sh
.github/workflows/community-review.yml

Co-authored-by: Sebastien Pereira <spereira@fr.ibm.com>
This is the implementation for Flip-518 to add community review
notes 
- we have decided to write this in Bash in line with the other github actions. This means we do not need to setup a language environment in the action
- I have left in logging, if this proves to be non-performant we can reduce the logging
- Labels community-reviewed-LGTM and community-reviewed need to be created in the Flink repo
- this PR adds a github action and a script
- the github action is a cron type of job and runs regularly
- the script gets all open PRs looks at their reviews and sets appropriate labels each PR depending on the review state and whether the reviewers is a committer.  
Please make sure both new and modified tests in this PR follow [the …

[FLINK-37770][GithubAction] Community review Github Action.

---

flink-clients/src/main/java/org/apache/flink/client/program/PackagedProgramUtils.java
flink-kubernetes/src/main/java/org/apache/flink/kubernetes/KubernetesClusterDescriptor.java
flink-kubernetes/src/main/java/org/apache/flink/kubernetes/entrypoint/KubernetesApplicationClusterEntrypoint.java
flink-kubernetes/src/test/java/org/apache/flink/kubernetes/KubernetesClusterDescriptorTest.java

`release-2.1` backport of https://github.com/apache/flink/pull/25445

[BP-2.1][FLINK-33926][k8s] Allow using job JARs in the system classpath in native mode

---

flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/SavepointWriter.java
flink-runtime/src/main/java/org/apache/flink/api/connector/sink/lib/OutputFormatSink.java
flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/sink/InitContextBase.java

The state processor API is now depending on data sink v1 API and in the PR I've migrated it to data sink v2.
Migrated state processor API from DSV1 to DSV2.

[FLINK-38018][state] Migrate state processor API from sink API v1 to sink API v2

---

docs/content.zh/docs/deployment/resource-providers/standalone/docker.md
docs/content/docs/deployment/resource-providers/standalone/docker.md

Currently the [documentation](https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/resource-providers/standalone/docker/#flink-sql-client-with-session-cluster), the Dockerfile is broken due to stale links. Also it is unclear how to use the custom image with connectors in the cluster and client Docker compose file.
This fixes broken link and improves instructions for using SQL connectors in Docker mode.
https://issues.apache.org/jira/browse/FLINK-38039

[FLINK-38039][docs] Improve instructions for using SQL connectors in Docker mode

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/rules/logical/FlinkPruneEmptyRules.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/FlinkBatchRuleSets.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/rules/FlinkStreamRuleSets.scala
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/FlinkPruneEmptyRulesTest.xml
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/rules/logical/FlinkPruneEmptyRulesTest.scala

The PR Add some Calcite builtin PruneEmptyRules

[FLINK-37591][table] Add some PruneEmptyRules

---

flink-filesystems/flink-s3-fs-base/src/main/java/org/apache/flink/fs/s3/common/FlinkS3FileSystem.java

Fix for not waiting for s5cmd process to finish (`s5cmd` was being cancelled, Flink was just not waiting for it to happen and was incorrectly logging a warning).
N/A …

[FLINK-38056][s3] Improve interruption handling for s5cmd

---

flink-architecture-tests/flink-architecture-tests-production/src/main/java/org/apache/flink/architecture/rules/CheckpointingConfigurationAccessRules.java

It seems after it sopped being compiled with java 11
The PR fixes this

[hotfix] Do not use syntax requiring java higher than java 11

---

docs/content.zh/docs/dev/table/functions/systemFunctions.md
docs/content.zh/docs/dev/table/types.md
docs/content/docs/dev/table/functions/systemFunctions.md
docs/content/docs/dev/table/types.md
docs/data/sql_functions.yml
docs/data/sql_functions_zh.yml

This PR adds documentation for the `VARIANT` type and `PARSE_JSON` functions
- Add documentation for `VARIANT` type and `PARSE_JSON` functions

[FLINK-38040][doc] Add documentation for VARIANT type and PARSE_JSON

---

flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/InternalTimerService.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/InternalTimerServiceImpl.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionInternalTimeService.java
flink-runtime/src/test/java/org/apache/flink/streaming/api/operators/TestInternalTimerService.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/window/async/tvf/common/AsyncStateWindowAggOperator.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/window/tvf/common/WindowAggOperator.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/aggregate/window/SlicingWindowAggOperatorTest.java

Restore the currentWatermark of WindowTimerService. If not restored, the slidingWindow will output extra data.
Restore the currentWatermark of WindowTimerService.
- *Added test that validates whether the hopping window restores the output data consistently.* …

[FLINK-36663][Window]Fix the first processWatermark has extra data after restore by restore timeService's watermark.

---

docs/layouts/shortcodes/generated/kubernetes_config_configuration.html
flink-kubernetes/src/main/java/org/apache/flink/kubernetes/configuration/KubernetesConfigOptions.java
flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesJobManagerParameters.java
flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/services/HeadlessClusterIPService.java
flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/services/ServiceType.java
flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/KubernetesJobManagerTestBase.java
flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/ExternalServiceDecoratorTest.java
flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/InternalServiceDecoratorTest.java
flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/factory/KubernetesJobManagerFactoryTest.java
flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesJobManagerParametersTest.java

Provide ability to set labels on services created by flink on the flinkdeployment spec.
https://issues.apache.org/jira/browse/FLINK-37478
- updated config to include `kubernetes.rest-service.labels` and `kubernetes.internal-service.labels` to allow setting labels on services.
- Added unit tests for specifying label metadata on services.  …

[FLINK-37478] Adding service labels to flink config

---

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperator.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperatorTest.java

As discussed in https://lists.apache.org/thread/8gncfyy42cmj6xtyk4fqvpxwf22xk9x5, an issue that unexpected extra retries will be triggered when user async function invoke completeExceptionally in timeout.
We can fix this by adding a start timestamp for future handler to help check if a retry still within configured timeout.
* adding a start timestamp for future handler to help check if a retry still within configured timeout.
newly added test cases:
* testProcessingTimeWithAlwaysTimeoutFunctionUnorderedWithRetry
* testProcessingTimeWithAlwaysTimeoutFunctionOrderedWithRetry …

[FLINK-38082][datastream] Avoid unexpected retries when user async function invokes completeExceptionally

---

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/DataTypeFactoryImpl.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/api/DataTypes.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/DataTypeFactory.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/BaseMappingExtractor.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/DataTypeExtractor.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/extraction/DataTypeTemplate.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/TypeTransformations.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/transforms/ConversionClassTransformation.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/logical/StructuredType.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/utils/DataTypeUtils.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/utils/DataTypeUtilsTest.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/connectors/DynamicSinkUtils.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/DataTypeJsonSerializer.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/StructuredFunctionsITCase.java

This fixes issues with `TableResult.collect()` and inline structured types created from within SQL.
The collect sink will derive a data type that matches the specific conversion classes of the structured type's implementation class. This happens lazily to not require the classloader containing the users class inside the planner.
Since the data type utilities are quite messy, I cleaned up some classes for future code mantainability.
This change added tests and can be verified as follows: `StructuredFunctionsITCase` …

[FLINK-38090][table] Align data type of inline structured types for TableResult.collect()

---

flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/JobClientHeartbeatRequestBody.java
flink-runtime/src/test/java/org/apache/flink/runtime/rest/messages/JobClientHeartbeatRequestBodyTest.java

…ion error
When submitting a task with the flink run command, adding the -sae parameter will cause the task to be killed. This PR is to fix this bug.
Add a @JsonProperty annotation to the constructor of the JobClientHeartbeatRequestBody class
Added a unit test case to verify the changes …

[FLINK-38098][Runtime] Fix JobClientHeartbeatRequestBody deserialization error

---

.github/workflows/nightly.yml

The nightly build wheel jobs are failing because the version of `pip` the cibuildwheel container is using is not the latest, so doesnt have the `--group` flag for pip installing from groups.
This PR ensures that the pip version is updated during builds and before pip install dev dependencies.
- *Ensured pip version is latest in building python wheels GHA job.*

[FLINK-38121] Ensure latest pip version before building Python wheels

---

flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperator.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperatorTest.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskMailboxTestHarness.java

This is a backport pr to 2.0 branch

[BP-2.0][FLINK-38082][datastream] Avoid unexpected retries when user async function invokes completeExceptionally

---

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CollectionFunctionsITCase.java
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/expressions/ArrayTypeTest.scala

`RuntimeException` is too generic, we should throw a more specific `TableRuntimeException` here.

[hotfix] ELEMENT should throw TableRuntimeException

---

flink-core/src/test/java/org/apache/flink/testutils/TestingUtils.java
flink-runtime/src/main/java/org/apache/flink/runtime/deployment/TaskDeploymentDescriptor.java
flink-runtime/src/main/java/org/apache/flink/runtime/deployment/TaskDeploymentDescriptorFactory.java
flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/Execution.java
flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionVertex.java
flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java
flink-runtime/src/test/java/org/apache/flink/runtime/deployment/TaskDeploymentDescriptorBuilder.java
flink-runtime/src/test/java/org/apache/flink/runtime/deployment/TaskDeploymentDescriptorTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/DefaultExecutionGraphDeploymentWithSmallBlobCacheSizeLimitTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ExecutionGraphSuspendTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ExecutionTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/InteractionsCountingTaskManagerGateway.java
flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/utils/ExecutionUtils.java
flink-runtime/src/test/java/org/apache/flink/runtime/jobmanager/scheduler/UpdatePartitionConsumersTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/SchedulerTestingUtils.java

Reduces risks of pekko framesize exceeded errors during task deployment caused by large TaskRestore through asynchronous offloading to the BlobStore. 
* Modifies `Execution#deploy()` to offload large TaskRestore values using BlobWriter (BlobWriter decides on threshold). 
* Offloading of TaskRestore is done asynchronously to avoid blocks the main thread.
* As `deploy` method now returns earlier, additional `CompletableFuture<Void>` is exported from Execution for testing purposes.
* Existing impacted tests are adjusted for new behaviour of `Execution#deploy`. 
* Added new tests to verify new code path.
* Existing tests. 
* Additional unit test to verify new code path: `ExecutionTest#testExecutionCancelledDuringTaskRestoreOffload`
- Dependencies (does it add or upgrade a dependency): (yes / …

[FLINK-38114][runtime] Allow asynchronous offloading of TaskRestore

---

flink-python/pyflink/common/tests/test_configuration.py
flink-python/pyflink/datastream/stream_execution_environment.py
flink-python/pyflink/datastream/tests/test_stream_execution_environment.py

At the moment when Flink uses the legacy YAML format then `add_jars` and `add_classpaths` are behaving wrong (stores value in YAML format instead of `;` separated). In this PR I've fixed it in a way that when legacy YAML format used then the mentioned function not just reading the values according to this format but also storing it that way.
`add_jars` and `add_classpaths` with legacy YAML format.
Enhanced automated tests.
- The S3 file …

[FLINK-38143][python] Fix pyflink flat YAML based config support

---

flink-runtime/src/main/java/org/apache/flink/runtime/state/heap/AbstractHeapState.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/heap/HeapKeyedStateBackend.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/heap/HeapListState.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/heap/HeapMapState.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/heap/StateTable.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendMigrationTestBase.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/ttl/TtlStateTestBase.java
flink-state-backends/flink-statebackend-changelog/src/test/java/org/apache/flink/state/changelog/ChangelogStateBackendMigrationTest.java
flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/state/rocksdb/EmbeddedRocksDBStateBackendMigrationTest.java
flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/state/rocksdb/RocksDBStateBackendMigrationTest.java
flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/state/rocksdb/ttl/RocksDBTtlStateTestBase.java

[FLINK-37294][state] Support state migration between disabling and enabling ttl in HeapKeyedStateBackend
Support state migration between disabling and enabling ttl in HeapKeyedStateBackend
Add `migrateTtlValue ` in `AbstractHeapState`. When the state TTL switch changes, trigger the migration of state data.
This change is already covered by existing tests, such as `StateBackendMigrationTestBase#testStateMigrationAfterChangingTTLFromEnablingToDisabling` and `StateBackendMigrationTestBase#testStateMigrationAfterChangingTTLFromDisablingToEnabling`. …

[FLINK-37294][state] Support state migration between disabling and enabling ttl in HeapKeyedStateBackend

---

docs/data/sql_functions.yml
docs/data/sql_functions_zh.yml
flink-python/docs/reference/pyflink.table/expressions.rst
flink-python/pyflink/table/expression.py
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/BaseExpressions.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/BuiltInFunctionDefinitions.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/ObjectUpdateInputTypeStrategy.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/ObjectUpdateTypeStrategy.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/SpecificInputTypeStrategies.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/strategies/SpecificTypeStrategies.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/strategies/ObjectUpdateInputTypeStrategyTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/StructuredFunctionsITCase.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/functions/scalar/ObjectUpdateFunction.java

This pull request implements the `OBJECT_UPDATE` built-in function as part of [FLIP-520](https://cwiki.apache.org/confluence/display/FLINK/FLIP-520%3A+Simplify+StructuredType+handling): Simplify StructuredType handling. The function allows users to update existing fields in structured objects by providing key-value pairs, enabling mutation operations on structured types in both SQL and Table API without requiring custom UDFs.
- Added `ObjectUpdateInputTypeStrategy` for validating input arguments (structured object + key-value pairs)
- Added `ObjectUpdateTypeStrategy` for inferring return types (same as input structured type)
- Implemented `ObjectUpdateFunction` runtime function for performing field updates
- Added `OBJECT_UPDATE` to `BuiltInFunctionDefinitions` with proper type inference …

[FLINK-37914][table] Add built-in OBJECT_UPDATE function

---

docs/content.zh/docs/dev/table/functions/udfs.md
docs/content/docs/dev/table/functions/udfs.md

Adds documentation for AsyncScalarFunction.
*(or)*
*(or)*
*(example:)*
- *Added integration …

[FLINK-34094] Adds documentation for AsyncScalarFunction

---

pom.xml

Bump cyclonedx-maven-plugin from 2.7.7 to 2.9.1 to remediate the findings in the dependant packages.
Bump cyclonedx-maven-plugin from 2.7.7 to 2.9.1 to remediate the findings in the dependant packages.
**Vulnerabilities from dependencies:**
[CVE-2024-38374](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-38374)
**Package details:**
https://mvnrepository.com/artifact/org.cyclonedx/cyclonedx-maven-plugin/2.9.1 …

[FLINK-38064] bump cyclonedx-maven-plugin to 2.9.1

---

flink-formats/flink-parquet/pom.xml

This upgrade ensures that RISC-V architecture (riscv64) is supported, allowing builds on RISC-V processors.
Testing was performed on an SG2042-based board, and the upgrade was successful. The board functioned as expected, and all tests passed without issues.
For details, see the commit from trustin:
- commit: https://github.com/trustin/os-maven-plugin/commit/4df54948f9eae82c6e5d9e20cc1e4d82c9a83872
CC @trustin

[FLINK-38179] Upgrade os-maven-plugin for RISC-V riscv64 support

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/data/columnar/ColumnarArrayData.java
flink-table/flink-table-common/src/test/java/org/apache/flink/table/data/columnar/ColumnarArrayDataTest.java

We have noticed that an OOB error is being thrown when trying to invoke getBinary when the following conditions are met:
1. There are multiple elements in a HeapArrayVector
2. When trying to get an element from a non-zero offset of the array
3. When trying to convert this array that we have obtained to a binary
```
Caused by: java.lang.IllegalArgumentException: 72 > 36
at java.util.Arrays.copyOfRange(Arrays.java:3519)
at org.apache.flink.table.data.columnar.ColumnarArrayData.getBinary(ColumnarArrayData.java:138)
at org.apache.hudi.table.format.cow.vector.ColumnarGroupRowData.getBinary(ColumnarGroupRowData.java:121)
at org.apache.flink.table.data.RowData.lambda$createFieldGetter$245ca7d1$3(RowData.java:228)
at org.apache.flink.table.runtime.typeutils.RowDataSerializer.toBinaryRow(RowDataSer …
```

[FLINK-38138] Fix OOB error in ColumnarArrayData

---

flink-yarn-tests/src/test/java/org/apache/flink/yarn/testjob/YarnTestCacheJob.java

Removing SourceFunction Dependency from YarnTestCacheJob.
- Replaced custom GenericSourceFunction implementation with env.fromData() in YarnTestCacheJob
Existing tests already cover this change.

[FLINK-32695] [Tests] Removed SourceFunction Dependency from YarnTestCacheJob.

---

flink-core/src/main/java/org/apache/flink/api/java/typeutils/runtime/PojoSerializer.java
flink-core/src/main/java/org/apache/flink/api/java/typeutils/runtime/TupleSerializer.java

Lower PojoSerializer newInstance cost for higher deserialization performance.
Replace class.newInstance with constructor.newInstance for PojoSerializer and TupleSerializer. 
The performance gets boosted by ~5% on the Flink POJO benchmark (tested on my laptop with JDK17.0.14), and the boost is more significant on simpler structs. More detailed performance analysis could be found at [FLINK-37735](https://issues.apache.org/jira/browse/FLINK-37735).
​ 
This change is already covered by existing POJO serializer tests. …

[FLINK-37735][serializer] Replace class.newInstance with constructor.newInstance

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/utils/DateTimeUtils.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/casting/BinaryToBinaryCastRule.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/casting/StringToTimeCastRule.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/functions/casting/TimestampToTimeCastRule.java
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/CodeGenUtils.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/GenerateUtils.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/BuiltInMethods.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/JsonCallGen.scala
flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarOperatorGens.scala
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/BuiltInFunctionTestBase.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/CastFunctionITCase.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/RowFunctionITCase.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/casting/CastRulesTest.java
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/codegen/CodeGenUtilsTest.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/OverAggregateITCase.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/utils/TestData.scala
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/data/binary/BinaryStringDataUtil.java

This pull request fixes a critical code generation compilation error and addresses multiple casting inconsistencies discovered during the investigation. The initial issue occurred when using `ROW()` with `CAST()` to `SMALLINT`/`TINYINT` on non-literal expressions, but the fix exposed several deeper problems in Flink's casting behavior when comparing constant folding (compile-time) vs. runtime code generation paths.
* Fixed `primitiveDefaultValue()` in `CodeGenUtils.scala` to return properly typed literals:
- `TINYINT`: `"-1"` → `"((byte) -1)"`  
- `SMALLINT`: `"-1"` → `"((short) -1)"`
* Enhanced `BuiltInFunctionTestBase` with `disableConstantFolding()` capability to force runtime code generation paths
* Added comprehensive unit tests for `primitiveDefaultValue()` and …

[FLINK-38181] Fix code generation for primitive type casting and improve cast consistency across compile-time and runtime paths

---

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/codegen/CodeGenUtils.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CalcITCase.scala
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/runtime/utils/UserDefinedFunctionTestUtils.scala

Fix call to non-existent method for RAW type hashing.
Use `BinaryRawValueData#toObject`.
`CalcITCase#testRawHash`
- If yes, how is the feature documented? ()

[FLINK-38135][table] Fix call to non-existent method for RAW type hashing

---

docs/content.zh/docs/dev/table/sql/create.md
docs/content/docs/dev/table/sql/create.md
flink-python/pyflink/table/catalog.py
flink-table/flink-sql-parser/src/main/codegen/includes/parserImpls.ftl
flink-table/flink-sql-parser/src/main/java/org/apache/flink/sql/parser/ddl/SqlCreateFunction.java
flink-table/flink-sql-parser/src/test/java/org/apache/flink/sql/parser/FlinkSqlParserImplTest.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/FunctionDescriptor.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/TableEnvironment.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/CatalogFunctionImpl.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/ContextResolvedFunction.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/FunctionCatalog.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/ddl/CreateTempSystemFunctionOperation.java
flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/FunctionCatalogTest.java
flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/resource/ResourceManagerTest.java
flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogFunction.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlNodeToOperationConversion.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/serde/RexNodeJsonSerializer.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlDdlToOperationConverterTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlMaterializedTableNodeToOperationConverterTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/serde/RexNodeJsonSerdeTest.java

Adds support for `WITH` clause in `CREATE FUNCTION`
Extended existing tests
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) : todo

[FLINK-38198] Support WITH Clause in CREATE FUNCTION Statement

---

flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/plan/optimize/program/FlinkChangelogModeInferenceProgram.scala
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/SinkSemanticTests.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/SinkTestPrograms.java
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/rules/physical/stream/DuplicateChangesInferRuleTest.xml
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/DeltaJoinTest.xml
flink-table/flink-table-planner/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/TableSinkTest.xml
flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/TableSinkTest.scala

Fixes retract sinks by not adding an `SinkUpsertMaterializer`. Since Flink's primary keys are declared as NOT ENFORCED, it is the users responsibility to ensure uniqueness. Retract streams are directly passed through without modification.
- Consider retract mode in `FlinkChangelogModeInferenceProgram`
This change added tests and can be verified as follows: `SinkSemanticTests` …

[FLINK-38201] SinkUpsertMaterializer should not be inserted for retract sinks

---

flink-tests/src/test/java/org/apache/flink/test/streaming/api/StreamingOperatorsITCase.java

This pull request migrates NonSerializableTupleSource from the deprecated SourceFunction API to the new Source V2 API using DataGeneratorSource.
- Replaced NonSerializableTupleSource (SourceFunction) with DataGeneratorSource and GeneratorFunction
- Added explicit TypeInformation creation for Tuple2<Integer, NonSerializable>
- Removed obsolete NonSerializableTupleSource class
This change is already covered by existing tests, such as StreamingOperatorsITCase#testAsyncWaitOperator which verifies that async operators handle both ordered and unordered processing of non-serializable
data types correctly. …

[FLINK-32695] [Tests] Replace NonSerializableTupleSource with DataGeneratorSource V2 API

---

flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/QueryOperationSqlSerializationTest.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/api/QueryOperationTestPrograms.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/ProcessTableFunctionSemanticTests.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/testutils/SemanticTestBase.java

To raise awareness and make sure new operators aren't forgotten when added, we should enable 
'TABLE_OPTIMIZER_NONDETERMINISTIC_UPDATE_STRATEGY' [by default in SemanticTestBase](https://github.com/apache/flink/pull/26894/files).
Newly added operators using this test base can still override and disable it at first.
- Enabled it by default in SemanticTestBase
- Disable for tests that don't support it yet
- Tests with operators that support NDU check will continue to run …

[FLINK-38234][tests] Enable ndu strategy for semantic tests by default

---

docs/content.zh/docs/dev/table/sql/create.md
docs/content/docs/dev/table/sql/create.md

The PR is to fix docs description for `CREATE` `CATALOG`, `DATABASE`, `MODEL`  to show that `WITH` is optional there
create.md
just docs
- If yes, how is the feature documented? ( docs)

[hotfix][docs] `WITH` in `CREATE DATABASE` is optional

---

flink-test-utils-parent/flink-test-utils-connector/pom.xml
flink-test-utils-parent/flink-test-utils-connector/src/main/java/org/apache/flink/test/util/source/AbstractTestSource.java
flink-test-utils-parent/flink-test-utils-connector/src/main/java/org/apache/flink/test/util/source/AbstractTestSourceBase.java
flink-test-utils-parent/flink-test-utils-connector/src/main/java/org/apache/flink/test/util/source/SingleSplitEnumerator.java
flink-test-utils-parent/flink-test-utils-connector/src/main/java/org/apache/flink/test/util/source/TestReaderOutput.java
flink-test-utils-parent/flink-test-utils-connector/src/main/java/org/apache/flink/test/util/source/TestSourceReader.java
flink-test-utils-parent/flink-test-utils-connector/src/main/java/org/apache/flink/test/util/source/TestSplit.java
flink-test-utils-parent/flink-test-utils-connector/src/main/java/org/apache/flink/test/util/source/TestSplitEnumerator.java
flink-test-utils-parent/flink-test-utils-connector/src/main/java/org/apache/flink/test/util/source/VoidSerializer.java
flink-test-utils-parent/flink-test-utils-connector/src/test/java/org/apache/flink/test/util/source/SourcePatternExamplesTest.java

Added a minimal, test-only utility module for FLIP-27 (Source V2) tests to reduce boilerplate when using Source V2 in Test cases. This is being done as a part of FLINK-32695 to migrate all the legacy test sources.
While migrating legacy SourceFunction–based tests to FLIP-27 (Source V2), a recurring pattern was noticed: many tests only need a mostly no-op scaffold (e.g., a source/enumerator that does nothing) or just one component—most often the SourceReader—to exercise a specific behavior. Hence this change is being made so that those patterns can be captured and test authors can plug in a tiny override (reader/enumerator/serializer) without re-implementing boilerplate.
Module path: flink-test-utils-parent/flink-test-utils-source
- Add new module in flink-test-utils-parent (packaging: …

[FLINK-32695] [Tests] Add flink-test-utils-connectors module for Source V2 tests.

---

flink-table/flink-table-planner/pom.xml
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/factories/TableFactoryHarness.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/BuiltInAggregateFunctionTestBase.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/functions/HashcodeITCase.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecSinkITCase.java

This PR migrates legacy SourceFunction and SinkFunction implementations in table planner tests from the deprecated legacy APIs to the modern FLIP-27 Source API
- Migrated TableFactoryHarness.ScanSourceBase from SourceFunctionProvider to SourceProvider with DataGeneratorSource
- Migrated TableFactoryHarness.SinkBase from SinkFunctionProvider to SinkV2Provider with TestSinkV2
- Implemented custom Source V2 in CommonExecSinkITCase.TestSource to preserve timestamp ordering
- Updated BuiltInAggregateFunctionTestBase to use DataGeneratorSource instead of legacy SourceFunction
Existing tests already cover these changes:
- BuiltInAggregateFunctionTestBase: ModuleITCase, HashcodeITCase, MiscAggFunctionITCase, ArrayAggFunctionITCase, JsonAggregationFunctionsITCase, PercentileAggFunctionITCase
- …

[FLINK-32695] [Tests] Migrated TableFactoryHarness.ScanSourceBase to Source V2

---

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/over/NonTimeRangeUnboundedPrecedingFunction.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/over/NonTimeRangeUnboundedPrecedingFunctionTest.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/over/RowTimeOverWindowTestBase.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/over/SumLongAggsHandleFunction.java

- Fix NPE by setting accumulators after creation
- Sets the accumulator explicitly after creation to avoid NPE
- *Added test to verify if Long calculation can be done without NPE*

[FLINK-38020] Fix NPE in NonTimeRangeUnboundedFunction

---

flink-table/flink-table-common/src/main/java/org/apache/flink/table/utils/DateTimeUtils.java

Log SQL time/date parse errors on DEBUG (and exclude Exception) to avoid overloading logging system.

[FLINK-38308] Reduce logging of date parse errors in DateTimeUtils

---

flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/JobDetailsHandler.java
flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/JobVertexDetailsHandler.java
flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/JobVertexTaskManagersHandler.java
flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/SubtaskCurrentAttemptDetailsHandler.java
flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/SubtaskExecutionAttemptDetailsHandler.java
flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/metrics/AggregatingSubtasksMetricsHandler.java
flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/metrics/SubtaskMetricsHandler.java
flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/legacy/metrics/MetricStore.java
flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/util/MutableIOMetrics.java
flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/job/SubtaskExecutionAttemptDetailsInfo.java
flink-runtime/src/test/java/org/apache/flink/runtime/rest/handler/legacy/metrics/MetricStoreTest.java

This PR optimizes the latency of Flink REST handlers used to generate the DAG in Flink UI.
In the current implementation, REST handlers like `JobDetailsHandler` would iterate through all vertexes of a job, and invoke `MetricStore#getSubtaskAttemptMetricStore` during each iteration. Given that this is a synchronized method, invocations to this method could possibly be blocked until other threads finished invoking other synchronized methods. This blocking overhead is accumulated with the for loop, resulting in high latency  when Flink UI tries to render the status of a Flink job through `JobDetailsHandler`.
In order to solve this problem, this PR proposes to reduce the number of synchronized invocations in REST handlers. A snapshot of the MetricStore jobs is acquired for each handler (and …

[FLINK-38291][REST] Reduce thread lock overhead for REST handlers

---

.github/workflows/community-review.sh

Remove redundant label mutations. Only add labels when there is not one. Only delete labels if there is one to delete. 
Changed the shell script in the github action
I suspect the message we see relating the the bot adding a removing the same label - is accurately logging an add and remove but the log message inserts are not correct. With this change there should mostly be only and add or remove and rarely both. 
I manually verified the logic locally.  …

[FLINK-38328][GithubAction] Remove redundant label mutations in Flink community review Github action script

---

flink-clients/src/main/java/org/apache/flink/client/deployment/application/executors/EmbeddedExecutor.java
flink-runtime/src/main/java/org/apache/flink/runtime/blob/BlobCacheService.java
flink-runtime/src/main/java/org/apache/flink/runtime/blob/BlobServer.java
flink-runtime/src/main/java/org/apache/flink/runtime/blob/BlobService.java
flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/DispatcherGateway.java
flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniCluster.java
flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/JobSubmitHandler.java
flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobClientTest.java
flink-runtime/src/test/java/org/apache/flink/runtime/webmonitor/TestingDispatcherGateway.java

https://issues.apache.org/jira/browse/FLINK-38109
The current implementation of BlobServer is to inherit the JobManager bind-host, however theres implicit assumptions that the BlobClient can use the dispatcher gateway host name. 
This pull request surfaces the BlobServer hostname directly to the BlobClient, similar to how the BlobServer port works today.
- BlobClient uses the correct host name when the JobManager bind-host is set.
Updates the current BlobClientTest to use the BlobServer address instead of `localhost`.
Additional tests added for blobserver binding to a routable address and a configured address inherited by the JobManager bind-host. …

[FLINK-38109] [flink-runtime] Fix BlobClient address when bindhost is set

---

flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/lookup/KeyedLookupJoinWrapper.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/join/KeyedLookupJoinHarnessTest.java

This is a trivial bugfix for state ttl setting in KeyedLookupJoinWrapper, we should enable state ttl config before create state instance.
correct state ttl setting
Add new case into`KeyedLookupJoinHarnessTest`

[hotfix][table] Fix incorrect state ttl setting in KeyedLookupJoinWrapper

---

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManager.java
flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/SubtaskFileMergingManagerRestoreOperation.java
flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerTestBase.java
flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/StreamTaskStateInitializerImpl.java

Currently, the file-merging manager’s recovery logic uses the Operator ID to parse the destination directory, whereas the manager initialization uses the Job Vertex ID. This mismatch can lead to a NPE. This may happen for the recovery of operators which are not at the head of operator chain. Typically this kind of operator has no state to recovery in SQL jobs, but it's possible for Datastream jobs.
This PR fixes it by using Job Vertex ID everywhere.
- Use JobVertexID in Subtaskkey of file-merging.
This change modifies the existing tests `FileMergingSnapshotManagerTestBase` to cover this case. …

[BP-1.20][FLINK-38327] Use vertex id instead of operator id in checkpoint file-merging manager 

---

flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManager.java
flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/filemerging/SubtaskFileMergingManagerRestoreOperation.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/StreamTaskStateInitializerImpl.java
flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/filemerging/FileMergingSnapshotManagerTestBase.java

Currently, the file-merging manager’s recovery logic uses the Operator ID to parse the destination directory, whereas the manager initialization uses the Job Vertex ID. This mismatch can lead to a NPE. This may happen for the recovery of operators which are not at the head of operator chain. Typically this kind of operator has no state to recovery in SQL jobs, but it's possible for Datastream jobs.
This PR fixes it by using Job Vertex ID everywhere.
- Use JobVertexID in Subtaskkey of file-merging.
This change modifies the existing tests `FileMergingSnapshotManagerTestBase` to cover this case. …

[BP-2.1][FLINK-38327] Use vertex id instead of operator id in checkpoint file-merging manager

---

.github/workflows/docs.yml

* Repair docs pipeline
* Pin RSync by hash
* Hash number for v5.2 can be found at https://github.com/Burnett01/rsync-deployments/commit/0dc935cdecc5f5e571865e60d2a6cdc673704823 …

[hotfix] Pin rsync by hash to allow docs to be build

---

flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/TruncateTableOperation.java
flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/operations/utils/ValidationUtils.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/SqlNodeToOperationConversion.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlNodeConvertUtils.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/operations/converters/SqlTruncateTableConverter.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/operations/SqlDdlToOperationConverterTest.java

The PR makes sure invalid operations with `MATERIALIZED TABLE`s are not failing with ClassCastException, rather more concrete error message
example of operations
```sql
alter table my_materialized_table RENAME to new_name;
analyze table my_materialized_table compute statistics;
truncate table my_materialized_table;
```
Table and view operations
SqlDdlToOperationConverterTest.java
- Does …

[FLINK-38365][table] Make invalid operations with `MATERIALIZED TABLE`s returning more user friendly message

---

flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkV2CommitterOperatorTest.java

In #26433, we removed the EOI marker in the form of Long.MAX_VALUE as the checkpoint id. Since streaming pipelines can continue to checkpoint even after their respective operators have been shut down, it is not safe to use a constant as this can lead to duplicate commits.
However, in batch pipelines we only have one commit on job shutdown. Using any checkpoint id should suffice in this scenario. Any pending committables should be processed by the ComitterOperator when the operator shuts down. No further checkpoints will take place.
There are various connectors which rely on this behavior. I don't see any drawbacks from keeping this behavior for batch pipelines.

[FLINK-38370] Ensure CommitterOperator commits all pending committables in batch mode

---

flink-python/pyflink/table/expressions.py
flink-python/pyflink/table/tests/test_expression.py

This PR will fix the issue in PyFlink where to_timestamp_ltz only accepts literal values
- Remove lit expression within to_timestamp_ltz function
- Add tests
This change added tests
Dependencies (does it add or upgrade a dependency): (no)
The public API, i.e., is any changed class annotated with @Public(Evolving): (yes)
The serializers: (no)
The runtime per-record code paths (performance sensitive): (no)
Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
The S3 file system connector: (no)
Does this pull request introduce a new feature? (no)
If yes, how is the feature documented? (not applicable)

[FLINK-38319][python] Allow TO_TIMESTAMP_LTZ to accept expression in PyFlink

---

flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/abilities/source/AggregatePushDownSpec.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/abilities/source/FilterPushDownSpec.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/abilities/source/LimitPushDownSpec.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/abilities/source/PartitionPushDownSpec.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/abilities/source/ProjectPushDownSpec.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/abilities/source/ReadingMetadataSpec.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/abilities/source/SourceWatermarkSpec.java
flink-table/flink-table-planner/src/main/java/org/apache/flink/table/planner/plan/abilities/source/WatermarkPushDownSpec.java

For consistency reason, `WatermarkPushDownSpec` can be forward-compatible. While implementing this, I noticed that all sinks specs are forward compatible but not the source specs. This adds consistency. A general ignoring of unknown properties should be avoided, however, because this could lead to unintended side effects.
Add `@JsonIgnoreProperties(ignoreUnknown = true)` to all source specs …

[FLINK-38352][table-planner] Make source specs forward compatible (like sink specs)

---

flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperatorTestBase.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/TestSinkV2.java
flink-tests/src/test/java/org/apache/flink/test/streaming/runtime/SinkV2ITCase.java

Backport of https://github.com/apache/flink/pull/26518
A simple commit cherry pick did not work due to the changes introduced in Flink 2.0. The test `SinkV2ITCase` is what required most of the changes compared to the backport to 2.0 https://github.com/apache/flink/pull/26546.

[BP-1.20][FLINK-37747][runtime] Use old subtask count for restored committable… #26546

---

flink-runtime/src/main/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperator.java
flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/SinkV2CommitterOperatorTest.java

In #26433, we removed the EOI marker in the form of Long.MAX_VALUE as the checkpoint id. Since streaming pipelines can continue to checkpoint even after their respective operators have been shut down, it is not safe to use a constant as this can lead to duplicate commits.
However, in batch pipelines we only have one commit on job shutdown. Using any checkpoint id should suffice in this scenario. Any pending committables should be processed by the ComitterOperator when the operator shuts down. No further checkpoints will take place.
There are various connectors which rely on this behavior. I don't see any drawbacks from keeping this behavior for batch pipelines.
Backport of #27004.

[release-2.0][FLINK-38370] Ensure CommitterOperator commits all pending committables in batch mode

---

pom.xml

This is one of the first steps towards build with jdk25
this commit is going to fix failure of tests
```
Caused by: java.lang.IllegalArgumentException: Java 25 (69) is not supported by the current version of Byte Buddy which officially supports Java 24 (68) - update Byte Buddy or set net.bytebuddy.experimental as a VM property
at net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:120)
at net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:95)
at net.bytebuddy.utility.AsmClassReader$Factory$Default.make(AsmClassReader.java:82)
at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:4031)
at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2246)
at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$UsingTy …
```

[FLINK-38385][build] Bump mockito to 5.19.0 and byte-buddy to 1.17.6

---

pom.xml

bump maven-shade-plugin version
pom.xml
also could be verified by building with java25 target

[FLINK-38391][build] Bump maven-shade-plugin to 3.6.1 to support java 25

---

flink-kubernetes/src/test/java/org/apache/flink/kubernetes/artifact/DefaultKubernetesArtifactUploaderTest.java

It expects kubernetes jar being in target folder
so this commands will succeed (and this is how it is done in CI: first compile without tests and then execute tests, that's why it doesn't fail there)
```
./mvnw clean install -DskipTests -pl flink-kubernetes && ./mvnw install  -pl flink-kubernetes 
```
and this fails which is usually used locally
```
./mvnw clean install -pl flink-kubernetes
```
`DefaultKubernetesArtifactUploaderTest` 
`./mvnw clean install -pl flink-kubernetes` …

[FLINK-38396][tests] Make `DefaultKubernetesArtifactUploaderTest` more stable

---

flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/MultiJoinSemanticTests.java
flink-table/flink-table-planner/src/test/java/org/apache/flink/table/planner/plan/nodes/exec/stream/MultiJoinTestPrograms.java
flink-table/flink-table-runtime/src/main/java/org/apache/flink/table/runtime/operators/join/stream/keyselector/AttributeBasedJoinKeyExtractor.java
flink-table/flink-table-runtime/src/test/java/org/apache/flink/table/runtime/operators/join/stream/multijoin/StreamingFourWayMixedOuterJoinOperatorTest.java

The MultiJoin has a JoinKeyExtractor helper that derives keys from AttributeRef mappings in the joinAttributeMap. It describes how attributes from different inputs are equated via equi-join * conditions.
The methods present in the JoinKeyExtractor should always return rows for the join conditions and commonJoinKey in the same order so we have stable a joinKey for state access and key selector for routing. This adds a fix to make sure the order is maintained. 
To make the whole class easier to read, I've also refactored it, added comments and examples.
- Fix stable ordering issue
- Refactor JoinKeyExtractor for better readability + comments and examples
- Add multiple tests
- Added semantic tests …

[FLINK-38417] Ensure attribute ordering when managing join attributes in JoinKeyExtractor

---

flink-table/flink-sql-parser/pom.xml
flink-table/flink-table-calcite-bridge/pom.xml

Another step towards build with jdk25
pom.xml

[FLINK-38386][build] Fix attaching type annotations for jdk23+

---

flink-core/pom.xml
flink-table/flink-table-planner/pom.xml

After applying this change and
https://github.com/apache/flink/pull/27007
https://github.com/apache/flink/pull/27008
https://github.com/apache/flink/pull/27009
flink will be compilable (with jdk25) with a command 
```
./mvnw clean install -DskipTests -Pfast
```
pom.xml
- Does this pull request introduce a new feature? ( …

[FLINK-38390][table] Compiliation of flink-core and flink-table-planner fails because of annotation processors

---

flink-runtime/src/test/java/org/apache/flink/runtime/state/ttl/StateBackendTestContext.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/ttl/TtlListStateWithKryoTestContext.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/ttl/TtlStateTestBase.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStDBTtlCompactFiltersManager.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/sync/ForStSyncKeyedStateBackend.java
flink-state-backends/flink-statebackend-forst/src/test/java/org/apache/flink/state/forst/ForStSyncTtlStateTest.java
flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/state/rocksdb/ttl/RocksDbTtlCompactFiltersManager.java

The RocksDB/ForSt 's list state use the user serializer to deserialize the list elements and filter the expired ones during compation. But the compaction runs in background threads that the RocksDB/ForSt allocated. These native threads do not have the JVM context, which is problematic when invoking some serializers that require JVM capabilities, such as Kryo that uses the classloader. Multiple issues have been reported: https://stackoverflow.com/questions/67321286/flink-application-fails-when-rocksdb-list-state-is-cleaned-by-ttl
This PR captured the user classloader from the thread that uses to create the compaction filter factory, and pass that to the native threads, solving the problem above.
- Change the `ListElementFilterFactory` taking the current thread's classloader and pass it to …

[FLINK-16686][State] Set classloader for compaction filters

---

flink-runtime/src/test/java/org/apache/flink/runtime/util/profiler/ProfilingServiceTest.java

The PR make the test more stable by making prefix unique per test.
The problem with the test that all use same prefix and at some point it counts items in profiling list by prefix which is same for all in this test. The problem could be reproduced while running tests in parallel (usually happens while `./mvnw clean install`)
Make prefixes unique per test …

[FLINK-38442][test] Make ProfilingServiceTest.testRollingDeletion more stable

---

flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/state/rocksdb/RocksDBKeyedStateBackend.java
flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/state/rocksdb/restore/DistributeStateHandlerHelper.java
flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/state/rocksdb/restore/RestoredDBInstance.java
flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/state/rocksdb/restore/RocksDBIncrementalRestoreOperation.java
flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/state/rocksdb/RocksDBAutoCompactionIngestRestoreTest.java
flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/state/rocksdb/restore/DistributeStateHandlerHelperTest.java

IndexOutOfBoundsException occasionally occurs after rocksdb.use-ingest-db-restore-mode is enabled
See more from https://issues.apache.org/jira/browse/FLINK-38415
- [FLINK-38415][refactor] Extract single state handle processing logic for testability
- [FLINK-38415][checkpoint] Disable auto compaction to prevent Index OutOfBounds
- Added DistributeStateHandlerHelperTest
- Test whether sst files are exported when the key group all in range.
- The testAutoCompactionIsDisabled will be failed without disabling auto compaction …

[FLINK-38415][checkpoint] Disable auto compaction to prevent Index OutOfBounds Exception

---

flink-core/src/main/java/org/apache/flink/api/common/state/KeyedStateStore.java
flink-libraries/flink-cep/src/test/java/org/apache/flink/cep/utils/TestSharedBuffer.java
flink-libraries/flink-state-processing-api/src/test/java/org/apache/flink/state/api/input/MultiStateKeyIteratorTest.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/AsyncKeyedStateBackend.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/DefaultKeyedStateStore.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/KeyedStateBackend.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/heap/HeapKeyedStateBackend.java
flink-runtime/src/main/java/org/apache/flink/runtime/state/v2/adaptor/AsyncKeyedStateBackendAdaptor.java
flink-runtime/src/main/java/org/apache/flink/streaming/api/operators/sorted/state/BatchExecutionKeyedStateBackend.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendTestUtils.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/ttl/mock/MockKeyedStateBackend.java
flink-runtime/src/test/java/org/apache/flink/runtime/state/v2/AbstractKeyedStateTestBase.java
flink-runtime/src/test/java/org/apache/flink/streaming/runtime/tasks/TestStateBackend.java
flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/ChangelogKeyedStateBackend.java
flink-state-backends/flink-statebackend-changelog/src/main/java/org/apache/flink/state/changelog/restore/ChangelogMigrationRestoreTarget.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/ForStKeyedStateBackend.java
flink-state-backends/flink-statebackend-forst/src/main/java/org/apache/flink/state/forst/sync/ForStSyncKeyedStateBackend.java
flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/state/rocksdb/RocksDBKeyedStateBackend.java

Add State backend type identifier as proposed in FLIP-544 [discussion](https://lists.apache.org/thread/kq3c5d68gkh0rj55rtcp1n25h6n6opoq).
State backend type identifier can be used by Operators to optimize their execution logic.
For example, 
- choose different thresholds for heap vs rocksdb
- rely on orderliness when using rocksdb

[FLINK-38462] Introduce state backend type identifier
