apache/flink

- flink-clients/src/main/java/org/apache/flink/client/CliFrontend.java
- flink-clients/src/test/java/org/apache/flink/client/CliFrontendPackageProgramTest.java
https://issues.apache.org/jira/browse/FLINK-1436
The main changes are:
* improve the error messages
* remove the verbose flag and make it always verbose
* do not show the full help text on errors.
* check for incomplete arguments
> [FLINK-1436]  refactor CLiFrontend to provide more identifiable and meaningful error messages

- flink-clients/src/main/java/org/apache/flink/client/CliFrontend.java
- flink-clients/src/main/java/org/apache/flink/client/web/JobsInfoServlet.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmanager/web/JobManagerInfoServlet.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmanager/web/SetupInfoServlet.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/TaskInputSplitProvider.java
- flink-runtime/src/main/scala/org/apache/flink/runtime/akka/AkkaUtils.scala
- flink-runtime/src/main/scala/org/apache/flink/runtime/client/JobClient.scala
- flink-runtime/src/main/scala/org/apache/flink/runtime/jobmanager/JobManager.scala
- flink-runtime/src/main/scala/org/apache/flink/runtime/messages/RegistrationMessages.scala
- flink-runtime/src/main/scala/org/apache/flink/runtime/taskmanager/TaskManager.scala
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmanager/JobManagerStartupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskManagerTest.java
- flink-runtime/src/test/scala/org/apache/flink/runtime/jobmanager/JobManagerITCase.scala
- flink-runtime/src/test/scala/org/apache/flink/runtime/jobmanager/TaskManagerRegistrationITCase.scala
- flink-yarn/src/main/java/org/apache/flink/yarn/FlinkYarnCluster.java
- flink-yarn/src/main/scala/org/apache/flink/yarn/ApplicationClient.scala
- flink-yarn/src/main/scala/org/apache/flink/yarn/Messages.scala
This PR removes the AkkaUtil.ask method and replaces all existing occurrences by explicit future handling. Furthemore, it removes the explicit actor address resolution which also introduced a blocking call.
> [FLINK-1508] Removes AkkaUtil.ask

- flink-clients/src/main/java/org/apache/flink/client/CliFrontend.java
- flink-clients/src/main/java/org/apache/flink/client/web/JobsInfoServlet.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/Execution.java
- flink-runtime/src/main/java/org/apache/flink/runtime/instance/InstanceManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmanager/accumulators/AccumulatorManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmanager/web/JobManagerInfoServlet.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmanager/web/SetupInfoServlet.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/TaskInputSplitProvider.java
- flink-runtime/src/main/scala/org/apache/flink/runtime/ActorLogMessages.scala
- flink-runtime/src/main/scala/org/apache/flink/runtime/akka/AkkaUtils.scala
- flink-runtime/src/main/scala/org/apache/flink/runtime/client/JobClient.scala
- flink-runtime/src/main/scala/org/apache/flink/runtime/jobmanager/JobManager.scala
- flink-runtime/src/main/scala/org/apache/flink/runtime/messages/RegistrationMessages.scala
- flink-runtime/src/main/scala/org/apache/flink/runtime/taskmanager/TaskManager.scala
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmanager/JobManagerStartupTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskManagerTest.java
- flink-runtime/src/test/scala/org/apache/flink/runtime/jobmanager/JobManagerITCase.scala
- flink-runtime/src/test/scala/org/apache/flink/runtime/jobmanager/TaskManagerRegistrationITCase.scala
- flink-yarn/src/main/java/org/apache/flink/yarn/FlinkYarnCluster.java
- flink-yarn/src/main/scala/org/apache/flink/yarn/ApplicationClient.scala
- flink-yarn/src/main/scala/org/apache/flink/yarn/Messages.scala
Adds try and catch blocks around exception throwing methods in the JobManager and TaskManager. This PR is based on #384.
> [FLINK-1543] Adds better exception handling in actors

- stratosphere-dist/pom.xml
- stratosphere-runtime/pom.xml
https://github.com/ktoso/maven-git-commit-id-plugin/issues/61
> [FLINK-1624] fix failing build due to maven git-commit-id plugin issue

- flink-addons/flink-avro/src/test/java/org/apache/flink/api/io/avro/AvroPojoTest.java
- flink-java/src/main/java/org/apache/flink/api/java/typeutils/GenericAvroTypeInfo.java
- flink-java/src/main/java/org/apache/flink/api/java/typeutils/GenericTypeInfo.java
- flink-java/src/main/java/org/apache/flink/api/java/typeutils/PojoTypeInfo.java
- flink-java/src/main/java/org/apache/flink/api/java/typeutils/runtime/AvroSerializer.java
Note this is a fix for 0.8 only.
The fix for master is contained in #393
> [FLINK-1567] Add switch to use the AvroSerializer for GenericTypeInfo

- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionVertex.java
Fix validated on a cluster setup.
> [FLINK-1683] [jobmanager] Fix scheduling preference choice for non-unary execution tasks

- flink-runtime/src/main/java/org/apache/flink/runtime/jobgraph/tasks/BarrierTransceiver.java
- flink-runtime/src/main/scala/org/apache/flink/runtime/minicluster/LocalFlinkMiniCluster.scala
- flink-runtime/src/main/scala/org/apache/flink/runtime/taskmanager/TaskManager.scala
- flink-staging/flink-streaming/flink-streaming-core/src/main/java/org/apache/flink/streaming/api/streamvertex/StreamVertex.java
- flink-staging/flink-streaming/flink-streaming-core/src/main/java/org/apache/flink/streaming/io/BarrierBuffer.java
- flink-staging/flink-streaming/flink-streaming-core/src/main/java/org/apache/flink/streaming/io/SpillReader.java
- flink-staging/flink-streaming/flink-streaming-core/src/main/java/org/apache/flink/streaming/io/SpillingBufferOrEvent.java
- flink-staging/flink-streaming/flink-streaming-core/src/main/java/org/apache/flink/streaming/io/StreamRecordWriter.java
- flink-staging/flink-streaming/flink-streaming-core/src/main/java/org/apache/flink/streaming/io/StreamingAbstractRecordReader.java
- flink-staging/flink-streaming/flink-streaming-core/src/test/java/org/apache/flink/streaming/api/windowing/windowbuffer/TumblingGroupedPreReducerTest.java
- flink-staging/flink-streaming/flink-streaming-core/src/test/java/org/apache/flink/streaming/io/BarrierBufferTest.java
- flink-staging/flink-streaming/flink-streaming-core/src/test/java/org/apache/flink/streaming/io/SpillingBufferOrEventTest.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/StreamCheckpointingITCase.java
This fixes several corner-cases in the barrier buffer logic.
> [FLINK-1775] BarrierBuffer fix to avoid end of stream deadlock

- flink-staging/flink-gelly/src/test/java/org/apache/flink/graph/test/operations/DegreesWithExceptionITCase.java
I wrongly introduced exception type checks in the ```DegreesWithExceptionITCase``` which are corrected with this PR. See #475 for more details.
> [FLINK-1816] Fixes wrongly introduced exception checks in DegreesWithExceptionITCase

- flink-optimizer/src/main/java/org/apache/flink/optimizer/plantranslate/JobGraphGenerator.java
- flink-optimizer/src/test/java/org/apache/flink/optimizer/plantranslate/TempInIterationsTest.java
> [FLINK-1951] Fix NullPointerException in delta iteration due to missing input temp

- flink-java/src/main/java/org/apache/flink/api/java/operators/translation/PlanUnwrappingSortedReduceGroupOperator.java
- flink-tests/src/test/java/org/apache/flink/test/javaApiOperators/FirstNITCase.java
There seem to be two variants of that tuple unwrapping thing, one combinable, the other one non-combinable.
These unwrapping things use a helper class called `WrappingFunction`, which expects the type of the user function.
In this case, we need a combinable group reduce function. It seems that only RichGroupReduceFunction is combinable AND a GroupReduceFunction at the same time.
But users can also implement non-rich combinable group reduce functions (by implementing both interfaces).
The `PlanUnwrappingSortedReduceGroupOperator` was just casting the user function to a `RichGroupReduceFunction`, which will fail if the UDF is not a Rich one.
To avoid making the code uglier than it already is, I've decided to cast the wrapped function to a `GroupCombineFunction` for calling the combiner. The …
> [FLINK-2135] Fix faulty cast to GroupReduceFunction

- flink-core/src/main/java/org/apache/flink/api/common/accumulators/AccumulatorHelper.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionGraph.java
- flink-runtime/src/main/scala/org/apache/flink/runtime/jobmanager/JobManager.scala
- flink-runtime/src/main/scala/org/apache/flink/runtime/jobmanager/MemoryArchivist.scala
https://issues.apache.org/jira/browse/FLINK-2388
> [FLINK-2388] return AccumulatorResultsNotFound until archive is checked

- flink-staging/flink-streaming/flink-streaming-core/src/test/java/org/apache/flink/streaming/api/DataStreamTest.java
Adds a missing test for FLINK-2419
> [FLINK-2419] Add test for sinks after keyBy and groupBy

- docs/apis/streaming_guide.md
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/PartitionedStateCheckpointingITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/StateCheckpoinedITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/StreamCheckpointNotifierITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/StreamCheckpointingITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/StreamFaultToleranceTestBase.java
> [FLINK-2423] [streaming] ITCase for checkpoint notifications

- flink-runtime/src/main/java/org/apache/flink/runtime/state/AsynchronousStateHandle.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/AsynchronousException.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskAsyncCheckpointTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTestHarness.java
This also adds a test for asynchronous state handles.
> [FLINK-3071] Add asynchronous state materialization thread

- .travis.yml
- pom.xml
> [FLINK-4151] Split test execution on travis into two groups

- flink-contrib/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackend.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/DefaultOperatorStateBackend.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/DoneFuture.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/ManagedInitializationContext.java
- flink-runtime/src/main/java/org/apache/flink/runtime/state/Snapshotable.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/PendingCheckpointTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/OperatorStateBackendTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/StateBackendTestBase.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/StateUtilTest.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/OperatorSnapshotResult.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskTest.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/SavepointITCase.java
This PR is a backport of #3523 to Flink 1.2.
> [FLINK-5985] [Backport for 1.2] Report no task states for stateless tasks on checkpointing

- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/TaskManagerJobMetricGroup.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
> [backport] [FLINK-6183]/[FLINK-6184] Prevent some NPE and unclosed metric groups

- flink-libraries/flink-cep/pom.xml
- flink-libraries/flink-gelly-examples/pom.xml
- flink-libraries/flink-gelly/pom.xml
- flink-libraries/flink-python/pom.xml
- flink-libraries/flink-table/pom.xml
- flink-libraries/pom.xml
Move checkstyle plugin into flink-libraries pom.
> [FLINK-6723] Activate strict checkstyle for flink-libraries

- flink-libraries/flink-cep/src/main/java/org/apache/flink/cep/nfa/NFA.java
- flink-libraries/flink-cep/src/main/java/org/apache/flink/cep/nfa/SharedBuffer.java
- flink-libraries/flink-cep/src/main/java/org/apache/flink/cep/nfa/compiler/NFACompiler.java
- flink-libraries/flink-cep/src/main/java/org/apache/flink/cep/nfa/compiler/NFAStateNameHandler.java
- flink-libraries/flink-cep/src/test/java/org/apache/flink/cep/nfa/NFAITCase.java
- flink-libraries/flink-cep/src/test/java/org/apache/flink/cep/nfa/SharedBufferTest.java
- flink-libraries/flink-cep/src/test/java/org/apache/flink/cep/nfa/compiler/NFACompilerTest.java
> [FLINK-6772] [cep] Fix ordering (by timestamp) of matched events.

- flink-libraries/flink-table/src/main/scala/org/apache/flink/table/api/java/windows.scala
- flink-libraries/flink-table/src/main/scala/org/apache/flink/table/api/scala/windows.scala
- flink-libraries/flink-table/src/main/scala/org/apache/flink/table/api/windows.scala
Thanks for contributing to Apache Flink. Before you open your pull request, please take the following check list into consideration.
If your changes take all of the items into account, feel free to open your pull request. For more information and/or questions please refer to the [How To Contribute guide](http://flink.apache.org/how-to-contribute.html).
In addition to going through the list, please provide a meaningful description of your changes.
- The pull request references the related JIRA issue ("[FLINK-XXX] Jira title text")
- The pull request addresses only one issue
- Each commit in the PR has a meaningful commit message (including the JIRA id)
- Documentation has been added for new functionality
- Old documentation affected by the pull request has been updated
- JavaDoc for public …
> [FLINK-6817] [table] Fix NPE when preceding is not set in OVER window

- docs/dev/libs/cep.md
> [FLINK-6198] [cep] Update CEP documentation.

- .travis.yml
- pom.xml
> [FLINK-7004] Switch to Travis Trusty image

- flink-scala-shell/pom.xml
- flink-scala-shell/src/test/scala/org/apache/flink/api/scala/ScalaShellITCase.scala
> [FLINK-7111] [scala-shell] Disable external jar test

- tools/travis_mvn_watchdog.sh
1.4 version of #4329.
Additional changes:
- tests are only executed if the compilation was successful
- yarn tests log upload is only done in group that actually runs flink-yarn-tests
> [FLINK-7176] [travis] Improve error handling

- docs/internals/ide_setup.md
This PR modifies the checkstyle IDE setup guide to also cover tests, as they are also covered by checkstyle.
> [FLINK-7232] [docs] Update checkstyle docs regarding test inclusion

- flink-runtime/src/main/java/org/apache/flink/runtime/query/QueryableStateClient.java
- flink-tests/src/test/java/org/apache/flink/test/query/AbstractQueryableStateITCase.java
- flink-tests/src/test/java/org/apache/flink/test/query/HAAbstractQueryableStateITCase.java
- flink-tests/src/test/java/org/apache/flink/test/query/HAQueryableStateITCaseFsBackend.java
- flink-tests/src/test/java/org/apache/flink/test/query/HAQueryableStateITCaseRocksDBBackend.java
- flink-tests/src/test/java/org/apache/flink/test/query/NonHAAbstractQueryableStateITCase.java
- flink-tests/src/test/java/org/apache/flink/test/query/NonHAQueryableStateITCaseFsBackend.java
- flink-tests/src/test/java/org/apache/flink/test/query/NonHAQueryableStateITCaseRocksDBBackend.java
> [FLINK-7379] [qs] Remove HighAvailabilityServices from QS client constructor.

- flink-libraries/flink-cep/src/main/java/org/apache/flink/cep/NonDuplicatingTypeSerializer.java
- flink-libraries/flink-cep/src/main/java/org/apache/flink/cep/nfa/NFA.java
- flink-libraries/flink-cep/src/main/java/org/apache/flink/cep/nfa/SharedBuffer.java
- flink-libraries/flink-cep/src/test/java/org/apache/flink/cep/nfa/NFATest.java
- flink-libraries/flink-cep/src/test/java/org/apache/flink/cep/nfa/SharedBufferTest.java
- flink-libraries/flink-cep/src/test/java/org/apache/flink/cep/operator/CEPOperatorTest.java
> [FLINK-7835][cep] Fix duplicate() in NFASerializer.

- docs/dev/stream/state/queryable_state.md
- flink-core/src/main/java/org/apache/flink/configuration/QueryableStateOptions.java
- flink-queryable-state/flink-queryable-state-client-java/src/main/java/org/apache/flink/queryablestate/network/AbstractServerBase.java
- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/itcases/HAAbstractQueryableStateTestBase.java
- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/itcases/NonHAAbstractQueryableStateTestBase.java
- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/network/AbstractServerTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/NetworkEnvironment.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/QueryableStateConfiguration.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerServices.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerServicesConfiguration.java
- flink-runtime/src/main/scala/org/apache/flink/runtime/minicluster/LocalFlinkMiniCluster.scala
*This PR adds documentation for the new queryable state.
R @aljoscha
> [FLINK-7822][FLINK-7823] Adds documentation and fixes configuration of QS.

- flink-queryable-state/flink-queryable-state-client-java/src/main/java/org/apache/flink/queryablestate/client/QueryableStateClient.java
- flink-queryable-state/flink-queryable-state-client-java/src/main/java/org/apache/flink/queryablestate/network/AbstractServerBase.java
- flink-queryable-state/flink-queryable-state-client-java/src/main/java/org/apache/flink/queryablestate/network/Client.java
- flink-queryable-state/flink-queryable-state-runtime/src/main/java/org/apache/flink/queryablestate/server/KvStateServerImpl.java
- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/itcases/AbstractQueryableStateTestBase.java
- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/itcases/HAAbstractQueryableStateTestBase.java
- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/network/AbstractServerTest.java
- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/network/KvStateServerHandlerTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/NetworkEnvironment.java
- flink-runtime/src/main/java/org/apache/flink/runtime/query/KvStateRegistry.java
- flink-runtime/src/main/scala/org/apache/flink/runtime/jobmanager/JobManager.scala
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmanager/JobManagerTest.java
This PR simply fixes multiple minor issues, like error messages.
> [FLINK-8057][FLINK-8059][FLINK-8055][FLINK-8065][FLINK-8062]

- docs/dev/connectors/kinesis.md
- flink-connectors/flink-connector-kinesis/pom.xml
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumer.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/KinesisShardAssigner.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcher.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/proxy/KinesisProxy.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/util/AWSUtil.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumerMigrationTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcherTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/proxy/KinesisProxyTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/TestableKinesisDataFetcher.java
Backport of Kinesis connector changes from 1.5 release to 1.4.
R: @tzulitai @tillrohrmann
> Backport of Kinesis connector changes from 1.5 to release-1.4

- docs/ops/deployment/docker.md
Clarify the Docker-related docs for current releases.
> [FLINK-9914][docs] Update Docker docs

- docs/dev/stream/operators/windows.md
*(This pull request is aim to fix incorrect parameter order in document about windows)*
*(fix incorrect parameter order in document about windows)*
*(This change is a trivial rework / code cleanup without any test coverage.)*
> [FLINK-9985] Incorrect parameter order in document

- flink-clients/src/main/java/org/apache/flink/client/program/ClusterClient.java
Typo 'cocurred' in the comment of ClusterClient.java.
> [hotfix]Fix 'cocurred' typo

- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java
harden existing tests
wait CompletableFuture complete in JobMasterTest, this is also keep consistency
trivial work, verifying by itself
> [hotfix] [test] Wait CompletableFuture complete

- docs/dev/event_time.md
This PR is a simple documentation improvement
> [hotfix][docs] Specify operators behaviour on processing watermarks

- docs/dev/libs/cep.md
Fixed example in the documentation plus restructured it a bit to make it more straightforward.
> [FLINK-9576] Fixed documentation for contiguity within looping pattern.

- flink-container/kubernetes/README.md
Fix broken hyperlink.
@tillrohrmann
> [hotfix][kubernetes] Fix broken hyperlink in README.md

- docs/dev/execution_plans.md
- docs/monitoring/back_pressure.md
- docs/monitoring/checkpoint_monitoring.md
- docs/monitoring/rest_api.md
- flink-core/src/test/java/org/apache/flink/configuration/RestOptionsTest.java
- flink-dist/src/main/resources/flink-conf.yaml
- flink-jepsen/src/jepsen/flink/db.clj
- flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/handlers/legacy/JarAccessDeniedHandler.java
Update the deprecated parameters in the WebOptions
> [hotfix] Update deprecated parameters in WebOptions 

- flink-runtime/src/main/java/org/apache/flink/runtime/rest/AbstractHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/FileUploadHandler.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/MultipartUploadResource.java
> [1.6][FLINK-10115][rest] Ignore content-length limit for FileUploads 

- flink-runtime/src/main/java/org/apache/flink/runtime/rest/AbstractHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/FileUploadHandler.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/MultipartUploadResource.java
> [1.5][FLINK-10115][rest] Ignore content-length limit for FileUploads 

- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/TaskMetricGroup.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/chaining/ChainedOperatorsMetricTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/testutils/MockEnvironment.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/testutils/MockEnvironmentBuilder.java
> [1.5][FLINK-10150][metrics] Fix OperatorMetricGroup creation for Batch

- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/TaskMetricGroup.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/chaining/ChainedOperatorsMetricTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/testutils/MockEnvironment.java
- flink-runtime/src/test/java/org/apache/flink/runtime/operators/testutils/MockEnvironmentBuilder.java
> [1.6][FLINK-10150][metrics] Fix OperatorMetricGroup creation for Batch

- docs/dev/batch/index.md
Fix error html tag in batch index documentatition
- *Change `</br>` to `<br />`*
- *`<tr>` and `</tr>` appear in pairs*
> [hotfix][docs] Fix error html tag in batch index documentatition

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamContextEnvironment.java
Accidentally check error message, correct to check correct parameter
trivial work
cc @zentol
> [hotfix] check correct parameter

- .travis.yml
- tools/travis_controller.sh
This PR removes the Travis hadoop 2.4 profiles. My intention is to move these into daily cron jobs by adding another `cron-master-hdp2.4` branch, as seen here: https://github.com/zentol/flink/tree/cron-master-hdp24
Given that most contributions are largely independent of hadoop this is a good opportunity to reduce our travis usage.
> [FLINK-10453][travis] Move hdp 2.4 tests to cron jobs

- flink-runtime/src/test/java/org/apache/flink/runtime/testutils/DispatcherProcess.java
Fix typo in `DispatcherProcess.java`. In fact I find it when trying to remove dependency of `JobManagerProcess`, and I think it is a missing work on #6751 .
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (**no**)
- If yes, how is the feature documented? (**no**)
cc @zentol, @tillrohrmann
> [hotfix] [tests] JobManager -> Dispatcher in DispatcherProcess

- flink-core/src/main/java/org/apache/flink/api/common/ExecutionConfig.java
Fix comments in ExecutionConfig.java
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (**no**)
> [hotfix][docs] Fix comments in ExecutionConfig.java

- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNSessionFIFOITCase.java
*This pull request cleanups constant isNewMode in YarnTestBase*
- *Cleanup constant isNewMode in YarnTestBase* …
> [FLINK-10527] Cleanup constant isNewMode in YarnTestBase

- docs/dev/batch/hadoop_compatibility.md
- docs/dev/connectors/cassandra.md
- docs/dev/table/connect.md
- docs/dev/table/sqlClient.md
- docs/dev/table/streaming/temporal_tables.md
- docs/dev/table/tableApi.md
Fixed some small typos that I spotted in the documentation.
> [hotfix] [docs] Fixed small typos in the documentation.

- flink-end-to-end-tests/test-scripts/kafka-common.sh
Backport of #6940 to `release-1.6`
> [BP-1.6][FLINK-10692] Harden Confluent schema registry E2E test

- flink-scala-shell/src/main/scala/org/apache/flink/api/scala/FlinkShell.scala
This PR is trying to fix issue that yarn app is not killed when scala shell is terminated. 
It is a trivial change that just call `yarnCluster.shutDownCluster()` to kill the yarn app.
I also manually tested it.
> [FLINK-10702][scala-shell] Yarn app is not killed when scala shell is terminated

- flink-annotations/src/main/java/org/apache/flink/annotation/docs/ConfigGroups.java
*(or)*
*(or)*
*(example:)*
- *Extended …
> [hotfix] [docs] Fix typo in ConfigGroups

- flink-core/src/test/java/org/apache/flink/util/FileUtilsTest.java
- flink-end-to-end-tests/flink-distributed-cache-via-blob-test/src/main/java/org/apache/flink/streaming/tests/DistributedCacheViaBlobTestProgram.java
- flink-filesystems/flink-s3-fs-base/src/test/java/org/apache/flink/fs/s3/common/utils/RefCountedFileTest.java
- flink-filesystems/flink-s3-fs-hadoop/src/test/java/org/apache/flink/fs/s3hadoop/HadoopS3RecoverableWriterTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/MultipartUploadResource.java
- flink-tests/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTriggerSavepointIT.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/ResumeCheckpointManuallyITCase.java
- flink-yarn/src/test/java/org/apache/flink/yarn/UtilsTest.java
This PR resolves resource leaks caused by improper usage of `Files.list`.  The returned stream must be explicitly closed.
> [FLINK-10690][tests] Fix Files.list resource leaks

- flink-end-to-end-tests/run-nightly-tests.sh
- flink-end-to-end-tests/run-pre-commit-tests.sh
- flink-end-to-end-tests/run-single-test.sh
- flink-end-to-end-tests/test-scripts/test-runner-common.sh
- flink-end-to-end-tests/test-scripts/test_queryable_state_restart_tm.sh
- flink-end-to-end-tests/test-scripts/test_streaming_sql.sh
Added flag to disable logs/output files checking for errors/exceptions.
> [FLINK-10678][e2e] Introduced switch to disable log checking in e2e tests

- splits/split_ha.sh
> [FLINK-10632] Enabled running general purpose testing job with failure in per-job cluster

- flink-end-to-end-tests/test-scripts/test_streaming_file_sink.sh
*Previously, we relied on checkpoint statistics to decide when to re-check the number of files written by the sink under test. However, side effects are triggered asynchronously, i.e., it can happen that statistics are updated before side effects are triggered (rolling of files). This can lead to test failures due to hash mismatches. We now wait until the number of expected lines were written to the file system.*
- *It is fairly obvious. Also see the commits.*
- *I am changing a test. I ran the test, and it passes more often now. There are more things that need fixing. See ticket.*
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes …
> [BP-1.6][FLINK-10357][tests] Improve StreamingFileSink E2E test stability.

- tools/releasing/create_binary_release.sh
Backport of #7016 to `release-1.7`.
> [BP-1.7][FLINK-10772][release] Fix create_binary_release.sh

- README.md
- pom.xml
File `ide_setup.md` is moved. We do the redirect but not change links where hardcode.
- The public API, i.e., is any changed class annotated with `(Evolving)`: (**no**)
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (**no**)
cc @tillrohrmann @zentol
> [FLINK-10797] [README] Fix broken link

- flink-yarn/src/main/java/org/apache/flink/yarn/AbstractYarnClusterDescriptor.java
- flink-yarn/src/test/java/org/apache/flink/yarn/YarnClusterDescriptorTest.java
When start JobManager on Yarn mode, only set -Xmx parameter , add -Xms also to avoid high frequency full gc  at start up phase.
-  add -Xms when start up JobManager, the value equals -Xmx
Change unit test method testSetupApplicationMasterContainer in YarnClusterDescriptorTest …
> [FLINK-10799][yarn] YARN mode JobManager JVM memory args add -XmsXXXm

- flink-end-to-end-tests/test-scripts/test_resume_externalized_checkpoints.sh
This PR fixes the `test_resume_externalized_checkpoints.sh` script,
by providing the path to the externalized checkpoint taken.
-  `test_resume_externalized_checkpoints.sh` now passes the checkpoint path the the Flink cli.
This change is in the test code itself. …
> [FLINK-10821] Fix resume from externalized checkpoints E2E Test

- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/Execution.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionGraph.java
- flink-runtime/src/test/java/org/apache/flink/runtime/minicluster/MiniClusterITCase.java
Backport of #7115 to `release-1.7`.
> [BP-1.7][FLINK-10883] Failing batch jobs with NoResourceAvailableException when slot request times out

- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/Execution.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionGraph.java
Backport of #7115 to `release-1.6`.
> [BP-1.6][FLINK-10883] Failing batch jobs with NoResourceAvailableException when slot request times out

- flink-connectors/flink-connector-kafka-0.11/src/main/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaProducer011.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/sink/TwoPhaseCommitSinkFunction.java
1.6 back port of #6989
cc @pnowojski
> [FLINK-10455][Kafka Tx] Close transactional producers in case of failure and termination

- flink-container/docker/docker-entrypoint.sh
- flink-contrib/docker-flink/docker-entrypoint.sh
Backport of #7125 to `release-1.7`.
> [BP-1.7][FLINK-10906][docker] Don't print configuration in docker-entrypoint.sh

- flink-end-to-end-tests/test-scripts/common.sh
- flink-end-to-end-tests/test-scripts/test_docker_embedded_job.sh
Added retry logic around building docker job image.
> [FLINK-10481][e2e] Added retry logic for building docker image

- flink-end-to-end-tests/test-scripts/common.sh
- flink-end-to-end-tests/test-scripts/test_queryable_state_restart_tm.sh
- flink-end-to-end-tests/test-scripts/test_resume_externalized_checkpoints.sh
release 1.6 back porting of #7073
cc @twalthr
e2e travis: https://travis-ci.org/azagrebin/flink/builds/461823649
> [FLINK-10842][E2E tests] fix broken waiting loops in common.sh

- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java
release 1.5 back porting of #7216
cc @tillrohrmann
> [FLINK-11011][E2E][JM] Log error messages about null CheckpointCoordinator only if job is running

- docs/flinkDev/building.md
*(or)*
*(or)*
*(example:)*
- *Extended …
> Fixed comment about scala versions.

- flink-yarn/src/main/java/org/apache/flink/yarn/AbstractYarnClusterDescriptor.java
- flink-yarn/src/main/java/org/apache/flink/yarn/cli/FlinkYarnSessionCli.java
> [hotfix] [docs] fix typos

- flink-runtime/src/main/java/org/apache/flink/runtime/execution/librarycache/FlinkUserCodeClassLoaders.java
Fix ParentFirstClassLoader desc
Fix ParentFirstClassLoader desc
> [hotfix] fix ParentFirstClassLoader typo

- docs/_includes/generated/rest_v1_dispatcher.html
- docs/dev/java_lambdas.md
- docs/dev/libs/ml/index.md
- docs/dev/stream/experimental.md
- docs/dev/stream/operators/joining.md
- docs/dev/stream/operators/process_function.md
- docs/dev/stream/state/broadcast_state.md
- docs/dev/stream/state/schema_evolution.md
- docs/dev/table/streaming/index.md
- docs/dev/table/streaming/joins.md
- docs/dev/table/streaming/match_recognize.md
- docs/dev/table/streaming/temporal_tables.md
- docs/examples/index.md
- docs/ops/deployment/hadoop.md
Add missing back to button in docs.
- Add missing back to button in docs.
> [hotfix][docs] Add missing back to top button in docs

- docs/dev/connectors/kafka.md
> [hotfix][docs] Fix typos

- flink-connectors/flink-connector-filesystem/src/main/java/org/apache/flink/streaming/connectors/fs/AvroKeyValueSinkWriter.java
AvroSinkWriter should be AvroKeyValueSinkWriter
> [FLINK-11265][docs] AvroSinkWriter → AvroKeyValueSinkWriter

- flink-runtime/src/main/java/org/apache/flink/runtime/registration/RegisteredRpcConnection.java
Remove redundant suppression in `RegisteredRpcConnection.java`
- The serializers:(no)
- The runtime per-record code paths (performance sensitive):(no)
cc @twalthr @StefanRRichter
> [hotfix] [runtime] Remove redundant suppression

- flink-core/src/main/java/org/apache/flink/util/ShutdownHookUtil.java
Fix typo in ShutdownHookUtil#addShutdownHookThread Javadoc
Fix typo in ShutdownHookUtil#addShutdownHookThread Javadoc
> [hotfix][docs] fix typo in addShutdownHookThread Javadoc

- NOTICE-binary
- flink-libraries/flink-streaming-python/pom.xml
- flink-libraries/flink-streaming-python/src/main/resources/META-INF/NOTICE
Bump the jython depdendency because of a security issue.
https://ossindex.sonatype.org/vuln/7a4be7b3-74f5-4a9b-a24f-d1fd80ed6bbc
Bump minor version to patch the a security issue.
> [FLINK-11262] Bump jython-standalone to 2.7.1

- flink-connectors/flink-jdbc/pom.xml
Hi all,
Derby has two CVE's:
https://ossindex.sonatype.org/vuln/b01781a6-31db-4dbc-b091-d683aaeb98e6
https://ossindex.sonatype.org/vuln/bbe6594a-c255-41a7-a397-d762d1aa8b00
https://issues.apache.org/jira/browse/FLINK-11306
Although it is only a test dependency, updating would be nice.
This change is a trivial rework / code cleanup …
> [FLINK-11306] Bump derby from 10.10.1.1 to 10.14.2.0

- docs/monitoring/debugging_classloading.md
This PR fix typo in classloading doc
Remove redundant line.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / no / don't know)
> [hotfix][docs] Fix typo in classloading doc

- flink-runtime/src/main/scala/org/apache/flink/runtime/akka/AkkaUtils.scala
https://jira.apache.org/jira/browse/FLINK-11341
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end …
> [FLINK-11341][doc]Correct javadoc of AkkaUtils#getAkkaConfig

- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java
> [hotfix] [javadocs] fix typo in JobMaster

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestEnvironmentImpl.java
The purpose of this PR is to harden kafka ITCases. It targets probable kafka AdminClient connection issues.
Logs from failures show that even though the request never finishes,
kafka topics are actually deleted. Therefore this PR adds timeout on
delete request. If the request times out we check if the topic actually
exists. If not then we continue as if the delete request succeeded.
Current kafka ITCases still pass.
- The runtime per-record code paths (performance sensitive): (yes / **no /** don't know) …
> [FLINK-11293][kafka, test] Added timeout to delete topic request.

- docs/dev/stream/operators/windows.md
[hotfix][docs] Fix typo in windows.md.
> [hotfix][docs] Fix typo in windows.md.

- docs/monitoring/metrics.md
<!--
*Thank you very much for contributing to Apache Flink - we are happy that you want to help us improve Flink. To help the community review your contribution in the best possible way, please go through the checklist below, which will get the contribution into a shape in which it can be best reviewed.*
*Please understand that we do not do this to make contributions to Flink a hassle. In order to uphold a high standard of quality for code contributions, while at the same time managing a large number of contributions, we need contributors to prepare the contributions well, and give reviewers enough contextual information for the review. Please also understand that contributions that do not follow this guide will take longer to review and thus typically be picked up with lower priority by …
> FLINK-11473 [documentation][ Clarify documenation on Latency Tracking

- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/manualtests/ManualExactlyOnceTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/manualtests/ManualExactlyOnceWithStreamReshardingTest.java
Simple replacement of `LocalFlinkMiniCluster` with `MiniClusterResource`.
> [FLINK-11550][kinesis] Port manual tests

- flink-libraries/flink-python/src/main/java/org/apache/flink/python/api/streaming/plan/PythonPlanStreamer.java
- flink-libraries/flink-streaming-python/src/main/java/org/apache/flink/streaming/python/util/InterpreterUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/nonha/leaderelection/SingleLeaderElectionService.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobMaster.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDBResource.java
- Does this pull request introduce a new feature? (no) 
There are some possible copy and paste errors in the log messages (The logging statement was copied from an old place to a new place, but the message wasn't changed to adapt to the function of the new place).
So I modified some logging statements to make them record the run-time behaviors more accurately.
> [hotfix]Fix some logging statements which can not correctly record the behaviors

- docs/dev/connectors/filesystem_sink.md
*This pull request fix sample scala code according to scala syntax*
- *Changing the scala snippet according to scala syntax for bucketing sink
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: ( no )
> FLINK-11053 Documentation - update scala sample code for bucketing sink according

- docs/_includes/generated/metric_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/MetricOptions.java
Update documentation of metrics fetcher update interval.
Update documentation of metrics fetcher update interval
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yno)
> [hotfix] update documentation of metrics fetcher update interval

- flink-core/src/main/java/org/apache/flink/configuration/ConfigOption.java
- flink-core/src/test/java/org/apache/flink/configuration/ConfigOptionTest.java
- flink-core/src/test/java/org/apache/flink/configuration/ConfigurationTest.java
Modify `ConfigOption#withFallbackKeys` and `ConfigOption#withDeprecatedKeys` to take deprecated/fallback keys that were configured previously also into account.
* merge newly passed keys with existing keys in both methods
* setup ordering such that fallback keys are always at the front, and deprecated keys always at the end
see `ConfigurationTest#testFallbackAndDeprecatedKeys`
> [FLINK-11583][configuration] Support deprecated and fallback keys at once

- flink-filesystems/flink-oss-fs-hadoop/pom.xml
Upgrade oss sdk version to exclude org.json dependency
https://issues.apache.org/jira/browse/FLINK-11442
Upgrade oss sdk version from 3.1.0 to 3.4.1
This change does not add tests …
> [FLINK-11442] upgrade oss sdk version

- pom.xml
Bump flink-shaded to 6.0 . Pin netty to 5.0 as that bump is covered in #7445.
> [FLINK-11626][build] Bump flink-shaded to 6.0

- docs/dev/connectors/kafka.md
- flink-connectors/flink-connector-kafka-0.11/src/main/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaProducer011.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaProducer.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/model/StreamShardHandle.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/FakeKinesisBehavioursFactory.java
- flink-core/src/main/java/org/apache/flink/core/memory/MemorySegment.java
- flink-runtime/src/main/java/org/apache/flink/runtime/operators/hash/InPlaceMutableHashTable.java
Fix some typos.
Fix some typos.
> [hotfix] fix some typos

- flink-clients/src/test/java/org/apache/flink/client/program/PackagedProgramTest.java
[hotfix][tests] Fix typo in PackagedProgramTest.java.
> [hotfix][tests] Fix typo in PackagedProgramTest.java.

- docs/dev/table/sourceSinks.md
[hotfix][docs] Fix typo in sourceSinks.md.
> [hotfix][docs] Fix typo in sourceSinks.md.

- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/datastream/ReinterpretDataStreamAsKeyedStreamITCase.java
This PR fixes test instability in `ReinterpretDataStreamAsKeyedStreamITCase`. I have executed the tests a couple 100 times on travis without failure.
The underlying problem was that the last update to `position` in `FromPartitionFileSource` L 221 can be lost for the state if we are in the case that we run into EOF and the failing has still to happen. So we restore a position 1 before EOF and produce a duplicate.
The changes avoid the problem by ensuring that the update happens in all cases, avoid control flow through EOF exceptions and put the point of failing in a more well defined place that is also somewhere before the source emitted the last event.
> [FLINK-11041][tests] Fix ReinterpretDataStreamAsKeyedStreamITCase

- docs/dev/libs/cep.md
[hotfix][docs] Fix typo in cep.md.
> [hotfix][docs] Fix typo in cep.md.

- flink-core/src/main/java/org/apache/flink/api/common/typeutils/base/StringComparator.java
> [hotfix] Remove extra symbols

- docs/flinkDev/ide_setup.md
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/PipelinedSubpartitionTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/environment/RemoteStreamExecutionEnvironmentTest.java
- pom.xml
- tools/maven/checkstyle.xml
Our checkstyle EmptyLineSeparator configuration does not specify the STATIC_IMPORT. As a result multiple empty lines are allowed around static imports, which is rather inconsistent.
This requires bumping checkstyle to `8.12`.
> [FLINK-11684][checkstyle] Enforce single empty line around static imports

- docs/dev/batch/index.md
Fix example code of readSequenceFile in dev/batch/index.html.md.
> [hotfix][docs] Fix example code of readSequenceFile in dev/batch/index.html.md.

- flink-core/src/main/java/org/apache/flink/api/common/typeutils/TypeComparator.java
- flink-core/src/main/java/org/apache/flink/types/NormalizableKey.java
> [hotfix] fix typos in description

- flink-core/src/main/java/org/apache/flink/api/common/typeinfo/TypeInformation.java
*Fix typo*
- *Fix typo in TypeInformation*
> [hotfix][core] Fix typo in TypeInformation

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/StreamExecutionEnvironment.java
*Fix typo*
- *Fix typo in StreamExecutionEnvironment*
> [hotfix][datastream] Fix typo in StreamExecutionEnvironment

- docs/flinkDev/building.md
I think this might have to go away in the future but for now we still allow people to do this. Plus I want to link to this from the release post.
> [FLINK-11791] Describe how to build Flink with Hadoop in build guide

- flink-connectors/flink-connector-kafka-0.9/src/test/java/org/apache/flink/streaming/connectors/kafka/Kafka09ITCase.java
*(or)*
*(or)*
*(example:)*
- *Extended …
> [FLINK-11826] [hotfix] Ignore flaky testRateLimitedConsumer

- flink-core/src/main/java/org/apache/flink/core/memory/MemorySegment.java
Fix errors in MemorySegment description.
> [hotfix][flink-core] fix errors in MemorySegment description

- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackend.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBKeyedStateBackendBuilder.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBOperationUtils.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/RocksDBPriorityQueueSetFactory.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/AbstractRocksDBRestoreOperation.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBFullRestoreOperation.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBIncrementalRestoreOperation.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/restore/RocksDBNoneRestoreOperation.java
- flink-state-backends/flink-statebackend-rocksdb/src/main/java/org/apache/flink/contrib/streaming/state/ttl/RocksDbTtlCompactFiltersManager.java
This PR is a simple refactoring of some RocksDB state backend code.
existing tests
> [hotfix] Reduce and simplify code for column creation in RocksDB backend

- docs/_includes/generated/task_manager_configuration.html
- docs/_includes/generated/task_manager_memory_configuration.html
- docs/ops/config.md
- flink-core/src/main/java/org/apache/flink/configuration/TaskManagerOptions.java
Re-introduces lost advanced taskmanager memory documentation.
> [FLINK-11542][config][docs] Extend memory configuration descriptions 

- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java
This commit changes the cleanup logic of the Dispatcher to only clean up job HA files
if the job is not a duplicate (meaning that it is either running or has already been
executed by the same JobMaster).
- Added `DispatcherResourceCleanupTest#testDuplicateJobSubmissionDoesNotDeleteJobMetaData`
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes) …
> [FLINK-11846] Don't delete HA job files in case of duplicate job submission

- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java
Backport of #7918 to `release-1.8`.
> [BP-1.8][FLINK-11846] Don't delete HA job files in case of duplicate job submission

- docs/_includes/generated/cluster_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/ClusterOptions.java
- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
- flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/ClusterEntrypoint.java
- flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniCluster.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherResourceCleanupTest.java
Backport of #7924 for `release-1.8`.
> [BP-1.8][FLINK-11851] Introduce dedicated io executor for ClusterEntrypoint and MiniCluster

- docs/_includes/generated/cluster_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/ClusterOptions.java
- flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/ClusterEntrypoint.java
- flink-runtime/src/main/java/org/apache/flink/runtime/minicluster/MiniCluster.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/LocalRecoveryITCase.java
Backport of #7924 for `release-1.7`.
> [BP-1.7][FLINK-11851] Introduce dedicated io executor for ClusterEntrypoint and MiniCluster

- flink-runtime/src/main/java/org/apache/flink/runtime/io/disk/iomanager/AbstractChannelReaderInputView.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/disk/iomanager/AbstractChannelWriterOutputView.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/disk/iomanager/ChannelReaderInputView.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/disk/iomanager/HeaderlessChannelReaderInputView.java
- flink-runtime/src/main/java/org/apache/flink/runtime/memory/AbstractPagedInputView.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/io/ChannelWithMeta.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/io/CompressedBlockChannelReader.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/io/CompressedBlockChannelWriter.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/io/CompressedHeaderlessChannelReaderInputView.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/io/CompressedHeaderlessChannelWriterOutputView.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/io/HeaderlessChannelWriterOutputView.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/util/FileChannelUtil.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/io/CompressedHeaderlessChannelTest.java
Introduce compressed channel reader/writer, and compressed headerless channel reader/writer based on our `BlockCompressionFactory`
- Added unit test
> [FLINK-11863][table-runtime-blink] Introduce channel to read and write compressed data

- flink-core/src/main/java/org/apache/flink/core/memory/MemorySegment.java
- flink-runtime/src/main/java/org/apache/flink/runtime/memory/AbstractPagedOutputView.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/api/TableConfigOptions.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/dataformat/util/BinaryRowUtil.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/generated/JoinCondition.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/generated/Projection.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/hashtable/BaseHybridHashTable.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/hashtable/BinaryHashBucketArea.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/hashtable/BinaryHashPartition.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/hashtable/BinaryHashTable.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/hashtable/BinaryRowChannelInputViewIterator.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/hashtable/BuildSideIterator.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/hashtable/HashTableBloomFilter.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/hashtable/LookupBucketIterator.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/hashtable/ProbeIterator.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/hashtable/WrappedRowIterator.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/join/HashJoinType.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/join/NullAwareJoinHelper.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/sort/BinaryIndexedSortable.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/sort/BinaryKVInMemorySortBuffer.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/sort/ListMemorySegmentPool.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/util/MemorySegmentPool.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/util/RowIterator.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/typeutils/AbstractRowSerializer.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/typeutils/BaseRowSerializer.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/typeutils/BinaryRowSerializer.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/hashtable/BinaryHashTableTest.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/util/UniformBinaryRowGenerator.java
This PR introduce a binary hash table to batch table runtime, preparing for the hash join operator. 
- Introduced binary hash table and some related stuff
This change added some tests
- Does this …
> [FLINK-11856][table-runtime-blink] Introduce BinaryHashTable to batch table runtime

- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricNames.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/util/MetricUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/util/MetricUtilsTest.java
With this PR we properly re-calculate the memory usage metrics. Currently we access a single `MemoryUsage` object once and, but this is never updated.
> [FLINK-11183][metrics] Properly measure current memory usage

- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/compression/BlockCompressionTest.java
Fix BlockCompressionTest does not compile with Java 9
- remove unnecessary dependency of `sun.misc.Cleaner`.
all no
> [FLINK-11905][table-runtime-blink] Fix BlockCompressionTest does not compile with Java 9

- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/writer/RecordWriterTest.java
*Extract a common method in tests for easy reuse and maintenance.*
- *Extract common codes for two tests in `RecordWriterTest`* …
> [hotfix] Deduplicate the common codes in RecordWriterTest

- docs/dev/batch/dataset_transformations.md
*(or)*
*(or)*
*(example:)*
- *Extended …
> Minor example typo fix

- docs/dev/projectsetup/dependencies.md
https://ci.apache.org/projects/flink/flink-docs-release-1.7/dev/projectsetup/dependencies.html#appendix-template-for-building-a-jar-with-dependencies
> [hostfix][docs]replace tabs with spaces in template code

- flink-end-to-end-tests/flink-streaming-kinesis-test/pom.xml
- flink-end-to-end-tests/flink-streaming-kinesis-test/src/main/java/org/apache/flink/streaming/kinesis/test/KinesisExample.java
- flink-end-to-end-tests/flink-streaming-kinesis-test/src/main/java/org/apache/flink/streaming/kinesis/test/KinesisExampleTest.java
- flink-end-to-end-tests/flink-streaming-kinesis-test/src/main/java/org/apache/flink/streaming/kinesis/test/KinesisPubsubClient.java
- flink-end-to-end-tests/pom.xml
- flink-end-to-end-tests/run-pre-commit-tests.sh
- flink-end-to-end-tests/test-scripts/common.sh
- flink-end-to-end-tests/test-scripts/test_streaming_kinesis.sh
> [FLINK-9007] [kinesis] [e2e] Add Kinesis end-to-end test

- flink-runtime/src/main/java/org/apache/flink/runtime/concurrent/FutureUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedLeaderService.java
- flink-runtime/src/test/java/org/apache/flink/runtime/concurrent/ConjunctFutureTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ExecutionGraphDeploymentTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/TestingSlotProvider.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedHaServicesTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedLeaderServiceTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/nonha/embedded/TestingLeaderContender.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/LocalTaskManagerLocation.java
Backport of #8060 to `release-1.8`.
> [BP-1.8][FLINK-12021] Deploy execution in topological sorted order

- flink-runtime/src/main/java/org/apache/flink/runtime/concurrent/FutureUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedLeaderService.java
- flink-runtime/src/test/java/org/apache/flink/runtime/concurrent/ConjunctFutureTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ExecutionGraphDeploymentTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/TestingSlotProvider.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedHaServicesTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/nonha/embedded/EmbeddedLeaderServiceTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/highavailability/nonha/embedded/TestingLeaderContender.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/LocalTaskManagerLocation.java
Backport or #8060 to `release-1.7`.
> [BP-1.7][FLINK-12021] Deploy execution in topological sorted order

- flink-connectors/flink-connector-kafka-0.10/src/main/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaConsumer010.java
- flink-connectors/flink-connector-kafka-0.10/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/Kafka010Fetcher.java
- flink-connectors/flink-connector-kafka-0.10/src/test/java/org/apache/flink/streaming/connectors/kafka/internal/Kafka010FetcherTest.java
- flink-connectors/flink-connector-kafka-0.9/src/main/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaConsumer09.java
- flink-connectors/flink-connector-kafka-0.9/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/Kafka09Fetcher.java
- flink-connectors/flink-connector-kafka-0.9/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/KafkaConsumerThread.java
- flink-connectors/flink-connector-kafka-0.9/src/test/java/org/apache/flink/streaming/connectors/kafka/Kafka09ITCase.java
- flink-connectors/flink-connector-kafka-0.9/src/test/java/org/apache/flink/streaming/connectors/kafka/internal/Kafka09FetcherTest.java
- flink-connectors/flink-connector-kafka-0.9/src/test/java/org/apache/flink/streaming/connectors/kafka/internal/KafkaConsumerThreadTest.java
- flink-core/pom.xml
- flink-core/src/main/java/org/apache/flink/api/common/io/ratelimiting/FlinkConnectorRateLimiter.java
- flink-core/src/main/java/org/apache/flink/api/common/io/ratelimiting/GuavaFlinkConnectorRateLimiter.java
>  [FLINK-11501] [kafka] Add ratelimiting to Kafka consumer

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGate.java
Improve exception message in SingleInputGate.
> [hotfix][runtime] Improve exception message in SingleInputGate

- flink-runtime/src/main/java/org/apache/flink/runtime/entrypoint/ClusterEntrypoint.java
remove not used transientBlobCache 
*removed the transientBlobCache in ClusterEntrypoint class*
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (no )
> [FLINK-11929][runtime] remove not used transientBlobCache

- docs/monitoring/debugging_event_time.md
Fix typos in debugging_event_time.md
> [hotfix] [typo] fix typo in debugging_event_time

- docs/dev/best_practices.md
> [hotfix][docs] fix typo in best_practices doc

- flink-core/src/main/java/org/apache/flink/configuration/ResourceManagerOptions.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/PartitionRequestQueue.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/ResultPartition.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/ResultPartitionManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManagerRuntimeServices.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotManagerConfiguration.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutorGateway.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlot.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/slot/TaskSlotTable.java
- flink-runtime/src/test/java/org/apache/flink/runtime/concurrent/ManuallyTriggeredScheduledExecutor.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/ResultPartitionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/ResourceManagerHATest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/ResourceManagerTaskExecutorTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotManagerBuilder.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotManagerTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotProtocolTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TestingTaskExecutorGateway.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TestingTaskExecutorGatewayBuilder.java
- flink-yarn/src/test/java/org/apache/flink/yarn/YarnResourceManagerTest.java
> [FLINK-10941] Keep slots which contain unconsumed result partitions

- flink-runtime/src/main/java/org/apache/flink/runtime/rpc/exceptions/FencingTokenException.java
- flink-scala/src/main/scala/org/apache/flink/api/scala/utils/package.scala
Remove some unused import statements
> [hotfix] Remove some unused import statements

- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/GenericCatalogFunction.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/GenericInMemoryCatalog.java
- flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/CatalogTestUtil.java
- flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/catalog/GenericInMemoryCatalogTest.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogFunction.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/ReadableCatalog.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/ReadableWritableCatalog.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/exceptions/FunctionAlreadyExistException.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/exceptions/FunctionNotExistException.java
As a followup for FLINK-11474 and its PR#8007, this PR adds additional catalog APIs for functions (UDFs)
- Added APIs in ReadableCatalog and ReadableWritableCatalog
- Provided an implementation of the APIs for GenericInMemoryCatalog
- Supplied with corresponding tests
Manually tested and provided UTs …
> [FLINK-11519][table] Add function related catalog APIs

- flink-runtime/src/main/java/org/apache/flink/runtime/rpc/MainThreadValidatorUtil.java
A trivial improvement that changes the name of variable log into LOG to correspond to other class files.
log -> LOG
*(or)*
*(or)*
*(example:)*
- *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one …
> [FLINK-12306][Runtime] Change the name of log into LOG

- flink-tests/src/test/java/org/apache/flink/runtime/metrics/SystemResourcesMetricsITCase.java
Hardens the `SystemResourcesMetricsITCase` against
* slow starts of a TaskManager, in which case metrics could be registered later than the test expects
* the host portion of the metric identifier not being `localhost`
We now exclude the host from the identifier, and generate a future in the reporter that we wait on instead.
> [FLINK-12359][metrics][tests] Harden SystemResourcesMetricsITCase

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/JSONGenerator.java
Remove useless code in JSONGenerator for https://github.com/apache/flink/pull/8295
none
> [hotfix][runtime] Remove useless code in JSONGenerator

- docs/dev/stream/state/queryable_state.md
Queryable state, since 1.8, now need to be enable through configuration. This add the right documentation to help people using it.
- add reference to configuration parameter
- If yes, how is the feature documented? now, yes!
> [FLINK-12274] Fix documentation to enable Queryable State

- docs/ops/deployment/aws.md
Add reference to ensure Hadoop classpath is present before submitting jobs to EMR.
Added step to export hadoop classpath
> FLINK-12493 [docs] Add step to export Hadoop classpath

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGate.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/UnionInputGate.java
Because recursive calls reading from SingleInputGate or InputChannel can potentially trigger some
notifications to happen, it's better to not execute those calls under the locks in SingleInputGate
and UnionInputGate.
This change is covered by various existing ITCases. …
> [FLINK-12510][network] Fix deadlock in InputGates

- docs/dev/stream/testing.md
Expand the documentation on testing DataStream API pipelines
* extend section on unit testing Flink operators
* add documentation about MiniClusterWithClientResource
* build docs and proofread
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper:  no
> [FLINK-12508] Expand Testing Documentation

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/sink/filesystem/StreamingFileSink.java
*(or)*
*(or)*
*(example:)*
- *Extended …
> [FLINK-12539] [fs-connector] Make StreamingFileSink customizable (#8469)

- flink-clients/src/main/java/org/apache/flink/client/program/OptimizerPlanEnvironment.java
Fix issue 12586: In OptimizerPlanEnvironment#getOptimizedPlan method, it looks like that stdout is output as System.err and stderr is output as System.out.
- Change the method OptimizerPlanEnvironment#getOptimizedPlan …
> [FLINK-12586][Command Line Client]Stderr and stdout are reversed in OptimizerPlanEnvironment

- flink-clients/src/main/java/org/apache/flink/client/program/ClusterClient.java
This pull request fixes the bug where ClusterClient doesn't reset context class loader in two methods.
> [FLINK-12167] Reset context classloader in run and getOptimizedPlan methods

- flink-runtime/src/test/java/org/apache/flink/runtime/instance/SimpleSlotTest.java
*Get rid of Instance in SimpleSlotTest*
Return a new SimpleSlot in _getSlot_ instead of using Instance.
cc @GJL @zentol
> [FLINK-12267] Port SimpleSlotTest to new code base

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumer.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/config/ConsumerConfigConstants.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/DynamoDBStreamsDataFetcher.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcher.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/util/JobManagerWatermarkTracker.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/util/RecordEmitter.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/util/WatermarkTracker.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumerMigrationTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumerTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/ShardConsumerTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/testutils/TestableKinesisDataFetcher.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/util/JobManagerWatermarkTrackerTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/util/RecordEmitterTest.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/util/WatermarkTrackerTest.java
Backport https://github.com/apache/flink/pull/8517
> [FLINK-10921] [kinesis] Shard watermark synchronization in Kinesis consumer

- docs/ops/state/checkpoints.md
For `Configure for per job when constructing the state backend`, add ')'
> [DOC] add  ')'  for  the doc checkpoints.md

- docs/ops/security-ssl.md
- docs/ops/security-ssl.zh.md
The SSL setup examples were updated to rely on PKCS12 format in 6f9aa832f85447e38e265d413aff829daadcecc4 (instead of the old JKS keystore) but PKCS12 does not support separate passwords for the key store and the key itself.
```
Warning:  Different store and key passwords not supported for PKCS12 KeyStores. Ignoring user-specified -keypass value.
```
Also, some of the examples still rely on the old JKS keystore and are not using PKCS12 yet.
Once approved, this PR should also make it into the 1.7 and 1.8 docs.
- remove separate `keypass` entries from the examples
- add PKCS12 format to the internal key (store) generation
This change is a trivial rework / code cleanup without any test coverage. I manually tested the following variants:
- internal with PKCS12
- internal with JKS keystore
- …
> [FLINK-12871][docs] fix separate keypass not compatible with PKCS12 stores

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/windowing/WindowOperator.java
This is a trivial logging change without test coverage.
> [hotfix][streaming] Report correct value of currentProcessingTime in the exception

- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/plan/nodes/dataset/BatchTableSourceScan.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/plan/nodes/datastream/StreamTableSourceScan.scala
Trivial fix so that the error message outputs the correct types. 
> [hotfix] Fix error message in BatchTableSourceScan

- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
- flink-runtime/src/test/java/org/apache/flink/runtime/taskmanager/TaskTest.java
Introduces a termination future into the task, that is completed once `run()` exits.
Don't be afraid of the diff, I simply wrapped the entire `run()` method in try-finally block.
> [FLINK-12923][runtime] Introduce Task termination future

- docs/_includes/generated/task_manager_memory_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/TaskManagerOptions.java
> [DOC]update description for Key `taskmanager.memory.preallocate `

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/functions/utils/UserDefinedFunctionUtils.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/runtime/stream/sql/CorrelateITCase.scala
If user has a function overload two any parameters method, UserDefinedFunctionUtils can not distinguish them and throw an exception. We should fix it.
ut
> [FLINK-12975][table-planner-blink] UserDefinedFunctionUtils should distinguish overload any parameters methods in blink

- README.md
*Fix url error in README.md*
cc @zentol @fhueske
> [hotfix][readme] fix how to contribute to Apache Flink url

- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/expressions/RexNodeConverter.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/functions/aggfunctions/ConcatWithRetractAggFunction.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/functions/aggfunctions/ConcatWsWithRetractAggFunction.java
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/codegen/CodeGenUtils.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/codegen/ExpressionReducer.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/codegen/calls/ScalarOperatorGens.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/codegen/calls/StringCallGen.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/dataformat/BinaryFormat.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/dataformat/BinaryString.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/dataformat/BinaryStringUtil.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/dataformat/LazyBinaryFormat.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/functions/SqlFunctionUtils.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/sort/SortUtil.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/dataformat/BinaryStringTest.java
> [FLINK-12802][table-runtime-blink] Reducing the Code of BinaryString

- flink-table/flink-table-planner-blink/pom.xml
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/functions/sql/CalciteSqlFunction.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/functions/sql/FlinkSqlOperatorTable.java
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/calcite/RelTimeIndicatorConverter.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/codegen/MatchCodeGenerator.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/logical/MatchRecognize.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/logical/FlinkLogicalMatch.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/nodes/physical/stream/StreamExecMatch.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/rules/FlinkStreamRuleSets.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/rules/physical/stream/StreamExecMatchRule.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/util/MatchUtil.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/plan/util/RelExplainUtil.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/api/stream/sql/validation/MatchRecognizeValidationTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/match/PatternTranslatorTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/match/PatternTranslatorTestBase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/runtime/stream/sql/MatchRecognizeITCase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/runtime/utils/UserDefinedFunctionTestUtils.scala
- flink-table/flink-table-runtime-blink/pom.xml
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/match/BaseRowEventComparator.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/match/IterativeConditionRunner.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/match/PatternProcessFunctionRunner.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/match/RowtimeProcessFunction.java
This pull request support MATCH RECOGNIZE (i.e. CEP) in blink planner
This ports the functionality of CEP from flink-planner to blink-planner
This ports all the tests (incl. UT & IT) of MATCh RECOGNIZE from flink-planner to blink-planner. …
> [FLINK-13082][table-planner-blink] Support MatchRecognize in blink planner

- docs/flinkDev/ide_setup.md
- docs/flinkDev/ide_setup.zh.md
*This PR only add the docs for set IDE for Python.*
- *Add setup IDE for Python in ide_setup.md & ide_setup.zh.md*
This change is a docs changes without any test coverage.
1. Add setup IDE docs for Python.
> [FLINK-12723][docs] setup IDE for Python

- docs/dev/stream/operators/process_function.md
- docs/dev/stream/operators/process_function.zh.md
This pull request correct the import in Processing function example in process_function.md. 
Let the example import KeyedProcessFunction instead of ProcessFunction.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: ( no)
- If yes, how is the feature documented? (not applicable …
> [FLINK-12817][docs]Correct the import in Processing function example.

- docs/dev/table/common.md
- docs/dev/table/common.zh.md
- docs/dev/table/tableApi.md
- docs/dev/table/tableApi.zh.md
- docs/ops/python_shell.md
- docs/ops/python_shell.zh.md
*Fix wrong example code in Python REPL and wrong table plan in table/common page*
- *Correct example code in python_shell.md/python_shell.zh.md*
- *Correct table plan in common.md/common.zh.md*
> [hotfix][python][docs]Fix wrong example code in Python REPL and wrong table plan in table/common page

- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/api/internal/TableEnvImpl.scala
After FLINK-12951, table will always be registered into current catalog, this fix the behavior for ExecutionContextTest.
- Remove defaultCatalog and defaultDataBase totally from TableEnvironmentImpl
> [FLINK-13175] Fix ExecutionContextTest after FLINK-12951

- .travis.yml
- flink-connectors/flink-connector-hive/pom.xml
Disables hive tests for the hadoop 2.4.1 travis profiles.
> [FLINK-13219][hive] Disable tests for hadoop 2.4 profile

- docs/dev/connectors/pubsub.md
Correct the examples for PubSubSink and integration tests in pubsub docs
> [FLINK-13133] [docs] Fix small error in PubSub documentation

- flink-connectors/flink-jdbc/src/main/java/org/apache/flink/api/java/io/jdbc/JDBCUpsertOutputFormat.java
In close, it await the flush scheduler terminal, but it hold the lock of JDBCUpsertOutputFormat instance, maybe the async thread is waiting for this lock in the flush method, so there might be a deadlock here.
First, it should not await scheduler terminal, because it has flushed all data to jdbc, what we should do is let async thread quit.
Second, we should add lock outside the closed check in the flusher, in this way, we can ensure async thread secure exiting.
Manual test …
> [FLINK-13253][jdbc] Deadlock may occur in JDBCUpsertOutputFormat

- .travis.yml
- tools/travis/stage.sh
To add Hive-1.2.1 build to Travis.
- Added a Travis job to build and test against Hive-1.2.1
Existing tests
> [FLINK-12995][hive] Add Hive-1.2.1 build to Travis

- docs/ops/cli.md
- docs/ops/cli.zh.md
Fix syntax error in CLI documentation
Fix syntax error in CLI documentation
Build documentation
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no 
> [hotfix] [docs] Small fix in CLI documentation

- flink-runtime/src/test/java/org/apache/flink/runtime/taskexecutor/TaskExecutorPartitionLifecycleTest.java
This pull request targets at fixing the unstable cases in TaskExecutorPartitionLifecycleTest. As described in the corresponding [JIRA](https://issues.apache.org/jira/browse/FLINK-13487), the tests may submit task before TM has successfully registered to JM, which will cause the tests fail since the checking whether the corresponding job id exists in the TaskExecutor#jobManagerTables can not be passed.
The above issue does not exist for the real cases. For real cases, JM will not submit tasks before TM has offered slots, and the successful slot offering ensures TM has registered to JM. To fix the tests, we also simulate this process by ensuring slot has been offered to JM before the task gets submitted.
1. afd7ba4663e2298776c0e02a4fe56cc1d3cf63a3 fix the unstable tests by ensure TM has …
> [FLINK-13487][tests] Fix unstable partition lifecycle tests by ensuring TM has registered to JM before submitting task

- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/Execution.java
- flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ExecutionPartitionLifecycleTest.java
Based on #9250.
Only commits tagged for FLINK-13476 are relevant.
Re-introduces a partition release call for pipelined partitions in case `Execution#cancel` is called after a vertex has been FINISHED. Since a task producing a pipelined partition may finish before any consumer ever attempted to consume the partition, it can happen that said partition is never release until the TE shuts down.
That is because the partition lifecycle management only cares about blocking partitions.
Note that cancel() is not only called for actually canceling the execution, but _always_ when a job fails or if the containing failover region is being restarted. This covers all cases where a pipelined partition can be produced, but may never be consumed.
> [FLINK-13476][coordination] Release pipelined partitions on vertex restart / job failure

- flink-runtime/src/test/java/org/apache/flink/runtime/testutils/CommonTestUtils.java
> [FLINK-13508][1.8][tests] CommonTestUtils#waitUntilCondition() may attempt to sleep with negative time

- tools/travis/splits/split_misc.sh
- tools/travis/splits/split_misc_hadoopfree.sh
Included table modules dependencies checks in travis splits.
> [hotfix][e2e] Include dependency tests in travis splits

- flink-runtime/src/main/java/org/apache/flink/runtime/concurrent/FutureUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionGraph.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/failover/AdaptedRestartPipelinedRegionStrategyNG.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/restart/FailureRateRestartStrategy.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/restart/FixedDelayRestartStrategy.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/restart/NoRestartStrategy.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/restart/RestartStrategy.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/restart/ThrowingRestartStrategy.java
- flink-runtime/src/test/java/org/apache/flink/runtime/concurrent/FutureUtilsTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/AdaptedRestartPipelinedRegionStrategyNGFailoverTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/TestRestartStrategy.java
- flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/restart/FailingRestartStrategy.java
- flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/restart/InfiniteDelayRestartStrategy.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/RegionFailoverITCase.java
> [1.9][FLINK-13452][runtime] Ensure to fail global when exception happens during reseting tasks of regions

- flink-end-to-end-tests/test-scripts/test_high_parallelism_iterations.sh
> [1.8][FLINK-13488][tests] Harden ConnectedComponents E2E test

- README.md
uniform building paragraph format in readme.md
change `git` to `Git`
no need tests.
- The runtime per-record code paths (performance sensitive): (yno)
> [HOTFIX][doc] uniform building paragraph format in readme.md

- flink-connectors/flink-connector-kafka-0.11/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/TransactionalIdsGenerator.java
- flink-connectors/flink-connector-kafka-0.11/src/test/java/org/apache/flink/streaming/connectors/kafka/internal/TransactionalIdsGeneratorTest.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/TransactionalIdsGenerator.java
Fixing https://issues.apache.org/jira/browse/FLINK-13789 by moving `prefix` out of the format string.
- moving `prefix` out of the format string
This change is almost a trivial rework and we've been running such a version on our production environment and have verified the fix.
> [FLINK-13789] move prefix out of the format string

- flink-core/src/test/java/org/apache/flink/util/CoreMatchers.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/exceptions/ResourceManagerException.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotManagerException.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotManagerImpl.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotManagerImplTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/slotmanager/TestingSlotManager.java
Back port of #9550 to `release-1.9`
> [BP-1.9][FLINK-13805] Properly forward cause for slot removal in SlotManager

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/util/HiveStatsUtil.java
*Related to [FLINK-13147](https://issues.apache.org/jira/browse/FLINK-13147). Remove duplicated code in 'if' conditional statement*
> [FLINK-13147]:Duplicated code in 'if' conditional statement

- docs/dev/projectsetup/scala_api_quickstart.md
Hey,
I just noticed a small typo, so I thought I'd raise a PR.
> Typo in `scala_api_quickstart.md`

- docs/getting-started/index.zh.md
Translate [Getting Started](https://github.com/apache/flink/blob/master/docs/getting-started/index.zh.md) page to chinese
Translate [Getting Started](https://github.com/apache/flink/blob/master/docs/getting-started/index.zh.md) page to chinese
- Does this pull request introduce a new feature: no
> [FLINK-13994][docs-zh]Translate 'Getting Started' page to chinese

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/util/RecordEmitter.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/util/RecordEmitterTest.java
> [FLINK-14107][kinesis] Erroneous queue selection in record emitter may lead to deadlock

- docs/flinkDev/building.md
- docs/flinkDev/building.zh.md
* Fix the wrong characters in the document(building.md,building.zh.md)
*I modified the "docs/flinkDev/building.md" and  "docs/flinkDev/building.zh.md"  file .*
*I have verified the changes by starting the build script in preview mode.*
Hi, @wuchong @zentol Please take a look .Thank you …
> [hotfix][docs] Fix the wrong characters in the document(building.md,building.zh.md)

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/StreamTwoInputProcessor.java
This probably doesn't speed up the code, but it's how the isAvailable() was intended to be used.
- If yes, how is the feature documented? (**not applicable /** docs / JavaDocs / not documented)
> [FLINK-14214][runtime] Shortcut isAvailable().isDone() anti-starvation check in StreamTwoInputProcesso

- docs/dev/stream/state/broadcast_state.md
- docs/dev/stream/state/broadcast_state.zh.md
* Corrected example snippet  
* Corrected usage of KeySelector
This change is a trivial update to documentation
> [FLINK-13065][doc] Corrected example snippet using KeySelector

- docs/dev/connectors/kinesis.md
Documentation update for Kinesis consumer.
> [FLINK-14283][kinesis][docs] Update Kinesis consumer docs for recent feature additions

- docs/index.zh.md
Translate changes on documentation index page to Chinese
- Update docs/index.zh.md
> [FLINK-14117][docs-zh] Translate changes on index page to Chinese

- flink-scala-shell/start-script/start-scala-shell.sh
> [bp-1.9][FLINK-13827][script] shell variable should be escaped

- flink-table/flink-table-planner/pom.xml
Speeds up test execution, halving testing times.
> [FLINK-14353][table] Enable fork reuse for tests

- flink-queryable-state/flink-queryable-state-runtime/src/test/java/org/apache/flink/queryablestate/network/AbstractServerTest.java
The purpose of this pr is to fix the unstable test case AbstractServerTest. The test case failed on Travis. The failure reason is that the requestStats is shared by two instance of TestServer which relies on AutoCloseable interface for connection release. If one of the server has been shut down and the anther is not, the assertion in the close method can fail. This pr fix the problem by moving the assertion out of the close method.
- The unstable assertion statement was moved out of the close method of TestServer.
The change can be verified by the test case itself.
- The runtime …
> [FLINK-14185][tests]Move unstable assertion statement out of close method of QS test server.

- flink-runtime-web/web-dashboard/src/app/app.component.html
- flink-runtime-web/web-dashboard/src/app/app.component.ts
- flink-runtime-web/web-dashboard/src/app/interfaces/configuration.ts
fix https://issues.apache.org/jira/browse/FLINK-13818
when `configuration.features['web-submit']` is false, hide the `Submit New Job` menu
If you put web.submit.enable: false into the configuration, the `Submit New Job` will hide in the menu
> [FLINK-13818][web]: Check whether web submission are enabled

- flink-core/src/main/java/org/apache/flink/api/common/functions/RuntimeContext.java
> [hotfix][typo] fix typo in RuntimeContext

- docs/_includes/generated/history_server_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/HistoryServerOptions.java
- flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/history/HistoryServer.java
- flink-runtime-web/src/main/java/org/apache/flink/runtime/webmonitor/history/HistoryServerArchiveFetcher.java
- flink-runtime-web/src/test/java/org/apache/flink/runtime/webmonitor/history/HistoryServerTest.java
History server removes deleted job archives and doesn't show them in UI.
- Added logic for removing deleted job archives from history server
- Removed `CountDownLatch` which was used only for tests from production code.
- Extended existing test for archives deletion scenario
> [FLINK-14169][history-server] Cleanup expired jobs from history server

- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManagerGateway.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutorHeartbeatPayload.java
- flink-runtime/src/test/java/org/apache/flink/runtime/resourcemanager/utils/TestingResourceManagerGateway.java
Introduce an encapsulating class for the heartbeat payload to simplify future additions to the payload.
> [FLINK-14518][coordination] Generalize TE->RM heartbeat payload

- flink-runtime/src/main/java/org/apache/flink/runtime/memory/MemoryManager.java
Fix some bugs and typos in memory manager
- Fix the bugs and typos in class MemoryManager
- Add a test case to verify the change in MemoryManagerTest.testReleaseNull
- When the input argument is null, the method should throw a NullPointerException.
> [FLINK-12289][Runtime] Fix java doc inconsistencies and style issues in Memory manager

- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/factories/TableFactoryUtil.java
update the `TableFactoryUtil.findAndCreateTableSource` method's annotation.
> [FLINK-13756][Table] Update `findAndCreateTableSource` method's annotation in TableFactoryUtil class

- flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
This PR is to fix the bug when deploying on yarn in attach mode that flink client hangs after `Ctrl + C`. More information could be found at [FLINK-10435](https://issues.apache.org/jira/browse/FLINK-10435).
* remove the `yarnClient.close()` in `failSessionDuringDeployment` and use a new yarn client in `DeploymentFailureHook`
* Manually run a command to start flink cluster on yarn in attach mode. `./bin/flink run -m yarn-cluster examples/streaming/WindowJoin.jar`
* When the application is in ACCEPTED status, send the `Ctrl + C`.
* The flink client exits immediately.
- The runtime …
> [FLINK-10435][yarn]Client sporadically hangs after Ctrl + C

- flink-core/src/main/java/org/apache/flink/configuration/ConfigConstants.java
- flink-core/src/main/java/org/apache/flink/configuration/GlobalConfiguration.java
- flink-core/src/main/java/org/apache/flink/core/plugin/PluginConfig.java
- flink-core/src/test/java/org/apache/flink/core/plugin/PluginConfigTest.java
- flink-mesos/src/main/java/org/apache/flink/mesos/entrypoint/MesosJobClusterEntrypoint.java
- flink-mesos/src/main/java/org/apache/flink/mesos/entrypoint/MesosSessionClusterEntrypoint.java
- flink-mesos/src/main/java/org/apache/flink/mesos/entrypoint/MesosTaskExecutorRunner.java
- flink-mesos/src/main/java/org/apache/flink/mesos/runtime/clusterframework/LaunchableMesosWorker.java
- flink-mesos/src/main/java/org/apache/flink/mesos/runtime/clusterframework/MesosResourceManagerFactory.java
- flink-mesos/src/main/java/org/apache/flink/mesos/util/MesosUtils.java
- flink-mesos/src/test/java/org/apache/flink/mesos/runtime/clusterframework/LaunchableMesosWorkerTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/ContainerSpecification.java
- flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/overlays/FlinkDistributionOverlay.java
- flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/overlays/HadoopConfOverlay.java
- flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/overlays/KeytabOverlay.java
- flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/overlays/SSLStoreOverlay.java
- flink-runtime/src/test/java/org/apache/flink/runtime/clusterframework/overlays/FlinkDistributionOverlayTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/clusterframework/overlays/HadoopConfOverlayTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/clusterframework/overlays/KeytabOverlayTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/clusterframework/overlays/SSLStoreOverlayTest.java
- flink-yarn/src/main/java/org/apache/flink/yarn/AbstractYarnClusterDescriptor.java
Backport of #10002 to `release-1.9`.
> [BP-1.9][FLINK-14074][mesos] Forward configuration to Mesos TaskExecutor 

- docs/dev/stream/operators/index.md
- docs/dev/stream/operators/index.zh.md
* Fix some typos in stream opertaors docs(index.md,index.zh.md).
*I modified the "docs/dev/stream/operators/index.md" and  "docs/dev/stream/operators/index.zh.md"  file .*
*I have verified the changes by starting the build script in preview mode.*
Hi, @TisonKun Please take a look in your …
>  [hotfix][docs] Fix some typos in stream opertaors docs

- docs/getting-started/walkthroughs/datastream_api.zh.md
Translate DataStream Code Walkthrough to Chinese
Translate DataStream Code Walkthrough to Chinese
I verified this change by running cmd 'build_docs.sh -i' and it's worked
> [FLINK-14115][docs-zh] Translate DataStream Code Walkthrough to Chinese

- flink-runtime/src/test/java/org/apache/flink/runtime/jobmanager/scheduler/SchedulerTestBase.java
straightforward self-contained refactor.
cc @tillrohrmann
> [hotfix][tests] Refactor SchedulerTestBase for removing dead code

- flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonRowDeserializationSchema.java
Replace Java Stream in JsonRowDeserializationSchema due to performance reason according to  https://flink.apache.org/contributing/code-style-and-quality-java.html .
Replace Java Stream with Array operations.
Unit Testing.
> [FLINK-14608] [flink-json] Avoid using Java Streams in JsonRowDeserializationSchema

- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/Savepoint.java
*This pull request fixed word typo: environment and refactored load savepoint exception message*
- *Fixed word typo: environment and refactored load savepoint exception message* …
> [hotfix] Fixed word typo: environment and refactored load savepoint exception message

- flink-runtime/src/main/java/org/apache/flink/runtime/state/memory/MemoryStateBackend.java
*This pull request correct the word used in the javaDocs in class MemoryStateBackend...*
- *Correct phrase 'rather then' with 'rather than' in javaDocs in class MemoryStateBackend*
This change is a trivial rework cleanup without any test coverage.
> [hotfix][JavaDocs] Correct docs in MemoryStateBackend

- docs/ops/deployment/kubernetes.md
- use Deployment from apps/v1 instead of extensions/v1beta1
- run as unprivileged user
*This pull request updates the Kubernetes documentation to use the current `Deployment` resource and run unprivileged*
- *Docs update*
- The serializers:  no 
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: no 
- The S3 file system connector:  no 
> [FLINK-14468][docs] Update Kubernetes docs

- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/aggregate/BytesHashMap.java
Now BytesHashMap will warn invoking stack when it want to spill, this lead to a lot of messages in logs.
Remove the stack and just print warns.
Refactor other methods.
Without any test coverage.
> [FLINK-14714][table-runtime-blink] BytesHashMap should not warn invoking stack when it want to spill

- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/Execution.java
*(For example: This pull request removes ASSIGNED_SLOT_UPDATER in Execution.tryAssignResource* …
> [FLINK-12039] Remove ASSIGNED_SLOT_UPDATER in Execution.tryAssignResource

- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionVertex.java
*This pull request marks ExecutionVertex#deployToSlot with @VisibleForTesting annotation*
- *Mark ExecutionVertex#deployToSlot with @VisibleForTesting annotation*
- Does this pull request introduce a new feature? (yes …
> [FLINK-14720] Mark ExecutionVertex#deployToSlot with @VisibleForTesting annotation

- flink-table/flink-table-planner/src/main/java/org/apache/flink/table/sqlexec/SqlToOperationConverter.java
It's wrong "if" statement in SqlToOperationConverter, this should be "else if" not the "if"
Use "else if" instead of "if"
> [FLINK-14858][Table SQL / Planner] Wrong "if" statement in SqlToOperationConverter

- flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/BootstrapTools.java
- flink-runtime/src/test/java/org/apache/flink/runtime/clusterframework/BootstrapToolsTest.java
- flink-yarn-tests/src/test/java/org/apache/flink/yarn/UtilsTest.java
- flink-yarn/src/main/java/org/apache/flink/yarn/AbstractYarnClusterDescriptor.java
- flink-yarn/src/main/java/org/apache/flink/yarn/Utils.java
- flink-yarn/src/main/java/org/apache/flink/yarn/YarnResourceManager.java
- flink-yarn/src/main/java/org/apache/flink/yarn/YarnTaskExecutorRunner.java
- flink-yarn/src/test/java/org/apache/flink/yarn/UtilsTest.java
- flink-yarn/src/test/java/org/apache/flink/yarn/YarnResourceManagerTest.java
Backport #10143 to release-1.9
none
none
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes)
> [FLINK-13184]Starting a TaskExecutor blocks the YarnResourceManager's main thread(Backport to 1.9)

- flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/BootstrapTools.java
- flink-runtime/src/test/java/org/apache/flink/runtime/clusterframework/BootstrapToolsTest.java
- flink-yarn-tests/src/test/java/org/apache/flink/yarn/UtilsTest.java
- flink-yarn/src/main/java/org/apache/flink/yarn/AbstractYarnClusterDescriptor.java
- flink-yarn/src/main/java/org/apache/flink/yarn/Utils.java
- flink-yarn/src/main/java/org/apache/flink/yarn/YarnResourceManager.java
- flink-yarn/src/main/java/org/apache/flink/yarn/YarnTaskExecutorRunner.java
- flink-yarn/src/test/java/org/apache/flink/yarn/UtilsTest.java
- flink-yarn/src/test/java/org/apache/flink/yarn/YarnResourceManagerTest.java
Backport #10143 to release-1.8
none
none
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes)
> [FLINK-13184]Starting a TaskExecutor blocks the YarnResourceManager's main thread(Backport to 1.8)

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
This PR fuses the two distinct initialization and open passes done at `StreamTask#init`  into a single pass.
Previously `AbstractStreamOperator#initalizeState` and `AbstractStreamOperator#open` are called from two distinct loops (tail to head). Fusing these loops into a single loop allows operators chained together to emit down stream already on initalizeState.
- The serializers: (yes / no ****/ don't know) …
> [FLINK-14862][runtime] Fuse initializeState and open

- flink-runtime/src/main/java/org/apache/flink/runtime/clusterframework/ContaineredTaskManagerParameters.java
fix typo in ContaineredTaskManagerParameters
> [hotfix][typo] fix typo in ContaineredTaskManagerParameters

- flink-end-to-end-tests/test-scripts/elasticsearch-common.sh
- flink-end-to-end-tests/test-scripts/test_sql_client.sh
- flink-end-to-end-tests/test-scripts/test_streaming_elasticsearch.sh
Elasticsearch Xpack Machine Learning function is enabled by default if the version is >=6.0. But This feature doesn't support ARM arch. So that in some e2e tests, Elasticsearch is failed to start.
We should disable ML feature in this case on ARM.
Add a case check that if the platform is aarch64 and Elasticsearch is 6.0+ version, disble xpack.ml feature.
This change is already covered by existing tests, it will be ran in e2e tests. …
> [FLINK-14126][test] Disable Xpack.ml for elasticsearch 6.0+ on ARM

- flink-ml-parent/flink-ml-api/pom.xml
- pom.xml
Migrates 1.8 to flink-shaded-jackson:2.10.1-9.0 .
> [1.9][FLINK-14104][build] Use flink-shaded-jackson 9.0

- flink-dist/pom.xml
- flink-kubernetes/pom.xml
- pom.xml
This PR is part of FLINK-9953(Active Kubernetes integration). Add a new module and pom for flink-kubernetes.
* Create a new module named with flink-kubernetes
* Add flink-kubernetes module in flink and flink-dist pom
The kubernetes-client classes is in flink-dist.jar and all its dependencies have been shadded. …
> [FLINK-10932] Initialize flink-kubernetes module

- flink-connectors/flink-connector-kinesis/src/main/resources/META-INF/NOTICE
Fixes a typo, updates the amazon-kinesis-producer entry, and adds several missing entries.
> [1.8][FLINK-14995][kinesis][legal] Update NOTICE

- flink-connectors/flink-connector-kinesis/src/main/resources/META-INF/NOTICE
Fixes a typo, updates the amazon-kinesis-producer entry, and adds several missing entries.
> [1.9][FLINK-14995][kinesis][legal] Update NOTICE

- flink-runtime/src/main/java/org/apache/flink/runtime/state/filesystem/FsCompletedCheckpointStorageLocation.java
Fix location typo in FsCompletedCheckpointStorageLocation
> [hotfix][typo] Fix location typo in FsCompletedCheckpointStorageLocation

- docs/dev/table/index.md
- docs/dev/table/index.zh.md
Fix an error URL in Table API & SQL page, as 'Connect to External Systems' linked to 'System (Built-in) Functions' 
> [Doc] 'Connect to External Systems' links to an error URL in Table API & SQL page

- flink-end-to-end-tests/flink-tpcds-test/tpcds-tool/data_generator.sh
Add liunx aarch64 support for tpcds e2e test
Fetch the dsdgen linux aarch64 binary if the platform is aarch64 when running tpcds e2e test
This change is already covered by existing tpcds e2e tests. …
> [FLINK-15060][tests] Add aarch64 support for tpcds e2e test

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
This change is covered by existing tests
> [hotfix][task] Refactor StreamTask#disposed field

- flink-streaming-java/src/test/java/org/apache/flink/streaming/util/AbstractStreamOperatorTestHarness.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/util/ProcessFunctionTestHarnessesTest.java
Add utility method to test harnesses that simplifies testing for output values when StreamRecords are of no relevance (not timestamp-related testing)
Add a method to AbstractStreamOperatorTestHarness and uses it in ProcessFunctionTestHarnessesTest
- Does this pull request introduce a new feature? yes  …
> [FLINK-14890] Add utility method to extract values from test harnesses and use in ProcessFunctionTestHarnessesTest

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/HiveCatalog.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/client/HiveMetastoreClientWrapper.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/client/HiveShim.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/client/HiveShimV100.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/client/HiveShimV210.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/util/HiveTableUtil.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/TableEnvHiveConnectorTest.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/config/CatalogConfig.java
Get PK constraints for Hive tables.
- Add shim interface for retrieving PK constraints
- Add PK to TableSchema when getting a table from HiveCatalog
- Add test to verify.
New test case
> [FLINK-14847][hive] Support retrieving Hive PK constraints

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/GenerateUtils.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/codegen/CodeGenerator.scala
scala pattern matching can't handle "NaN","NegativeInfinity " etc.
in Flink planner module( GenerateUtils, CodeGenerator), some code logic fall into this issue.
the PR target to fix this. 
fix pattern matching issue in below classes:
org.apache.flink.table.planner.codegen.GenerateUtils
org.apache.flink.table.codegen.CodeGenerator
This change is  covered by UT
org.apache.flink.table.planner.codegen.GenerateUtilsTest
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: ( no)
- The S3 file …
> [FLINK-14970]Doomed test for equality to NaN

- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/entrypoint/KubernetesResourceManagerFactory.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/entrypoint/KubernetesSessionClusterEntrypoint.java
This PR is part of FLINK-9953(Active Kubernetes integration). Entrypoint for a Kubernetes session cluster is added.
* Add `KubernetesSessionClusterEntrypoint`
Just a entrypoint for Kubernetes and most functionality is in `ClusterEntrypoint`. Will test it manually.
> [FLINK-10933][kubernetes] Implement KubernetesSessionClusterEntrypoint.

- flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
We create temporary files for storing `flink-conf` & `JobGraph`. Although we ask for deleting them on exit, for a long running YarnClusterDescriptor it is possibly a resource leak. We can delete the file when they are no longer used. The delete hook will then silently fail on deletion but it is expected.
N/A
> [FLINK-15134][client] Delete temporary files created in YarnClusterDescriptor

- docs/_includes/generated/kubernetes_config_configuration.html
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/KubernetesClusterDescriptor.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/cli/FlinkKubernetesCustomCli.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/cli/KubernetesCliOptions.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/configuration/KubernetesConfigOptions.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/decorators/ServiceDecorator.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/Fabric8ClientTest.java
Backport #10496  to release-1.10.
none
none
> [FLINK-15153]Service selector needs to contain jobmanager component label(Backport to 1.10)

- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/TypeTransformations.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/transforms/DataTypeConversionClassTransformation.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/inference/transforms/TimeToSqlTypesTransformation.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/utils/DataTypeUtils.java
- flink-table/flink-table-common/src/test/java/org/apache/flink/table/types/inference/TypeTransformationsTest.java
Introduce `TypeTransformation` interface to transform one data type to another, and a basic transformation that transform time to sql types.
- Remove `CallContext` from the existing `TypeTransformation`.
- add a package `o.a.f.table.types.inference.transforms`
- add commonly used transform class there, `TimeToSqlTypesTransformation`.
- add a class `o.a.f.table.types.inference.TypeTransforms` for listing all available transforms
- add a util method `transform` in `DataTypeUtils` to transform a data type (can be nested) to antoher
using the given transformation recursively.
This change added a test which transforms a nested data type.
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / …
> [FLINK-15161][table-common] Introduce TypeTransformation interface and basic transformations

- docs/_includes/generated/netty_shuffle_environment_configuration.html
- docs/_includes/generated/rocks_db_configurable_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/NettyShuffleEnvironmentOptions.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/NettyShuffleEnvironmentConfiguration.java
- flink-tests/src/test/java/org/apache/flink/test/runtime/FileBufferReaderITCase.java
backport to release-1.10
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / no / don't know)
> [FLINK-14952][network] Solve the issue of exceeding memory limits when using mmap blocking partition

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/local/ExecutionContext.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/local/LocalExecutor.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/local/ExecutionContextTest.java
- flink-table/flink-sql-client/src/test/resources/META-INF/services/org.apache.flink.table.factories.TableFactory
To fix the issue that Hive connector doesn't work if the dependencies are specified via SQL CLI `library` option. The issue may apply to other connectors as well.
- Set user class loader as thread context class loader during creating and registering catalogs.
- Set dependent jars via Configuration so that the job graph carries the dependencies.
- Added test.
New tests …
> [FLINK-15167][sql-client] Catalogs should be created and registered with user class loader as context loader

- flink-dist/pom.xml
FLINK-14905 introduced a multi-release approach to bundle libraries
for different JDK versions. However, the multi-release flag was not
correctly set, which effectively disabled the mechanism and lead to
incomplete dependencies on Java 11. This commit fixes the setup, such
that the Java 11 libraries are correctly loaded.
- Fixes the Multi-Release flag in manifest creation of flink-dist.
- Existing hadoop-s3 e2e test already cover it. …
> [FLINK-15268][build] Correctly set Multi-Release in manifest.

- flink-end-to-end-tests/test-scripts/common.sh
This PR fix the parameter issue in `retry_times` function of common.sh.
Fix the parameter issue in `retry_times` function of common.sh.
Trigger container relevant e2e tests.
cc: @wangyang0918 @tillrohrmann 
Since it's a blocker issue for e2e test, I open this …
> [FLINK-15360][e2e] Fix the parameter issue in retry_times

- docs/_includes/generated/yarn_config_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/ConfigConstants.java
- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YARNSessionCapacitySchedulerITCase.java
- flink-yarn/src/main/java/org/apache/flink/yarn/configuration/YarnConfigOptions.java
This PR delete unused YarnConfigOptions code to avoid misunderstanding
Delete unused code from YarnConfigOptions, ConfigConstants and YARNSessionCapacitySchedulerITCase. Also regenerate the docs for unused options
> [FLINK-15359] Remove unused YarnConfigOptions, Tests, Docs

- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/generated/CompileUtils.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/generated/CompileUtilsTest.java
Fix the metaspace memory leak of TM.
- Use weak/soft references for keys and values of COMPILED_CACHE.
Verified by existing tests.
NA
> [FLINK-15239][table-planner-blink] CompileUtils::COMPILED_CACHE leaks class loaders

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcher.java
- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/util/RecordEmitter.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumerTest.java
backport of https://github.com/apache/flink/pull/10611
> [FLINK-15301] [kinesis] Exception propagation from record emitter to source thread

- docs/dev/table/connect.md
- docs/dev/table/connect.zh.md
*This pull request aims at fixing document of csv format usage in Filesystem connector section.*
- *update file docs/dev/table/connect.md*
- *update file docs/dev/table/connect.zh.md* …
> [FLINK-15425][docs] Fix csv format usage in Filesystem connector section

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/CheckpointedInputGate.java
*Remove invalid comment from CheckpointedInputGate*
- *Remove invalid comment from CheckpointedInputGate* …
> [hotfix][runtime] Remove invalid comment from CheckpointedInputGate

- docs/dev/stream/operators/asyncio.md
> [hotfix][docs] Fix typo in asyncio.md

- flink-runtime/src/test/java/org/apache/flink/runtime/jobmanager/BlobsCleanupITCase.java
Prints the root cause of the unexpected job failure for tests in `BlobsCleanupITCase` to help locate the unstable test failure.
- d95e12bdcb570c4cbe5a37a9670d7427e8c461a1 prints the cause when job execution result is detected to be not successful.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: **no** …
> [FLINK-14572][test] Print the root cause if job fails in BlobsCleanupITCase

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/calls/StringCallGen.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/expressions/ScalarFunctionsTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/CalcITCase.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/functions/SqlFunctionUtils.java
This pr fix FROM_BASE64 code gen result type.
This pr fix FROM_BASE64 code gen result type.
CalcITCase.testFromBase64 …
> [FLINK-15478][table-planner-blink] Fix FROM_BASE64 code gen result type

- docs/dev/table/catalogs.md
- docs/dev/table/catalogs.zh.md
*Correct catalog doc example mistake*
- 84b3810 Correct catalog doc example mistake
> [FLINK-15398][hotfix][doc]Correct catalog doc example mistake

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/functions/hive/HiveGenericUDAF.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/functions/hive/HiveScalarFunction.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/module/hive/HiveModuleTest.java
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/calls/ScalarFunctionCallGen.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/CalcITCase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/utils/UserDefinedFunctionTestUtils.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/dataformat/DataFormatConverters.java
Fix the issue of calling Hive functions that return decimals
- Call `TypeInfoDataTypeConverter` to convert data type to type info because it's the recommended way.
- Add test case
New test case
> [FLINK-15482][hive] Failed to call Hive functions returning decimal type

- docs/dev/table/sql/queries.zh.md
*(or)*
*(or)*
*(example:)*
- *Extended …
> [FLINK-15502] Correct minor mistake of the Chinese translation in 'Queries' page of Table API SQL

- flink-yarn/src/main/java/org/apache/flink/yarn/entrypoint/YarnEntrypointUtils.java
Remove the following TODO codes in `YarnEntrypointUtils`.
Rest port(rest.bind-port), blob port(blob.server.port) and rpc port(yarn.application-master.port) could both support a list of ports (“50100,50101”), ranges" + " (“50100-50200”) or a combination of both.
* Remove TODO codes and unused constants
* Do not need tests …
> [FLINK-15457][yarn] Remove finished TODO in YarnEntrypointUtils

- flink-core/src/main/java/org/apache/flink/configuration/CoreOptions.java
- flink-core/src/test/java/org/apache/flink/configuration/CoreOptionsTest.java
Unchanged forward port of https://github.com/apache/flink/pull/10816 .
> [FLINK-15355][plugins] Fixed parsing of plugin parent-first patterns.

- flink-end-to-end-tests/flink-metrics-reporter-prometheus-test/src/test/java/org/apache/flink/metrics/prometheus/tests/PrometheusReporterEndToEndITCase.java
Improves performance of the prometheus e2e test by using the `DownloadCache` for downloading/caching prometheus.
> [FLINK-15520][prometheus][tests] Use DownloadCache

- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java
- flink-tests/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterStopWithSavepointIT.java
Restart `CheckpointCoordinator` if `StopWithSavepoint` failed.
- `JobMasterStopWithSavepointIT#testRestartCheckpointCoordinatorIfStopWithSavepointFails`
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes)
> [FLINK-15152][checkpointing] Restatrt CheckpointCoordinator if StopWithSavepoint failed

- docs/_includes/generated/core_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/CoreOptions.java
- flink-core/src/main/java/org/apache/flink/core/plugin/PluginLoader.java
- flink-tests/src/test/java/org/apache/flink/test/plugin/PluginLoaderTest.java
- flink-tests/src/test/java/org/apache/flink/test/plugin/PluginManagerTest.java
Classloader restricts access to parent to whitelist.
No class/resource in the system class loader (everything in lib/) can be seen in the plugin except those starting with a whitelist prefix.
- Classloader restricts access to parent to whitelist.
- `Shaded Hadoop S3A with credentials provider end-to-end test`
- The S3 file system connector: (**yes** …
> [FLINK-15355][plugins]Classloader restricts access to parent to whitelist.

- flink-end-to-end-tests/test-scripts/test_datastream_walkthroughs.sh
- flink-end-to-end-tests/test-scripts/test_quickstarts.sh
- flink-end-to-end-tests/test-scripts/test_table_walkthroughs.sh
- flink-walkthroughs/flink-walkthrough-datastream-scala/src/main/resources/archetype-resources/pom.xml
- flink-walkthroughs/flink-walkthrough-table-scala/src/main/resources/archetype-resources/pom.xml
- tools/travis/nightly.sh
- tools/travis/splits/split_misc.sh
This PR fixes scala walkthrough archetype does not compile on Java 11.
- Fixing scala walkthrough archetype does not compile on Java 11.
- Activiating walkthrough e2e tests.
- Fixing e2e tests to actually test the archetype under test and not the previously published.
- Walkthrough e2e tests. …
> [Flink-15583] Fixing scala walkthrough archetype does not compile on Java 11

- flink-core/src/main/java/org/apache/flink/api/common/functions/AggregateFunction.java
*This pull request fix javadoc example error for AggregateFunction*
- *update javadoc exmaple  for AggregateFunction*
- *add comment  for return value of AggregateFunction.add* …
> [hotfix][javadoc] fix doc example error for AggregateFunction

- docs/dev/table/functions/udfs.md
- docs/dev/table/functions/udfs.zh.md
- docs/flinkDev/building.md
- docs/flinkDev/building.zh.md
- docs/getting-started/walkthroughs/python_table_api.md
- docs/getting-started/walkthroughs/python_table_api.zh.md
- docs/ops/cli.md
- docs/ops/cli.zh.md
- docs/ops/python_shell.md
- docs/ops/python_shell.zh.md
*This pull request improves the environment requirement documentation of the Python API.*
- *Improve the environment requirement documentation in Python API Tutorials.*
- *Improve the environment requirement documentation in `cli.md`.*
- *Improve the environment requirement documentation in `udfs.md`.*
- *Improve the environment requirement documentation in `python_shell.md`.*
- *Change the interpreter "python3" to "python" in `building.md`.* …
> [FLINK-15630][python][doc] Improve the environment requirement documentation of the Python API.

- flink-core/src/main/java/org/apache/flink/core/plugin/PluginLoader.java
- flink-filesystems/flink-s3-fs-hadoop/pom.xml
- flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/licenses/LICENSE.javax.activation
- flink-filesystems/flink-s3-fs-hadoop/src/main/resources/META-INF/licenses/LICENSE.jaxb
- flink-filesystems/flink-s3-fs-presto/pom.xml
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/licenses/LICENSE.javax.activation
- flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/licenses/LICENSE.jaxb
Because of the module system of Java 9, (s3) plugins cannot access different modules anymore. This patch fixes two issues: access to platform modules for authentication related classes and bundling of jaxb in a version shaded jar.
- Access to platform modules for authentication related classes and
- Bundling of jaxb in a version shaded jar.
- Existing e2e plugin tests under Java 11.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, …
> [Flink-15355][plugins]Enable s3 plugins under Java 11.

- flink-scala-shell/src/test/scala/org/apache/flink/api/scala/ScalaShellITCase.scala
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/local/LocalExecutor.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/factories/TableFactoryService.java
*This pull request use current classloader to load classes which fix parameters --library adn --jar in sqlClient can not play correctly .*
- *update file org/apache/flink/table/factories/TableFactoryService.java*
- If yes, how is the feature documented? (not applicable / docs / JavaDocs …
> [FLINK-15552][table api] parameters --library and --jar doesn't work for DDL in sqlClient

- docs/ops/filesystems/index.md
- docs/ops/filesystems/index.zh.md
- docs/ops/plugins.md
- docs/ops/plugins.zh.md
Plugin page will be expanded in the future for connectors and other types.
Central page to point someone who asks: what are plugins?
Adds a dedicated plugin page, which will be expanded in the future for connectors and other types.
Central page to point someone who asks: what are plugins?
- Adds plugin page
- Adds several links to the plugin page
Does not apply
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / **no** / …
> [FLINK-15274][docs]Added separate plugin page.

- flink-core/src/main/java/org/apache/flink/util/OutputTag.java
*the annotation in OutputTag  is incomplete.*
*the annotation in OutputTag  need remove right half brackets ’)‘*
*This change is a trivial rework / code cleanup without any test coverage.*
- Dependencies (does it add or upgrade a dependency):no
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper:no
> [hotfix] Fix confusing annotation in OutputTag

- pom.xml
> [FLINK-15738][build] Bump powermock to 2.0.4

- flink-clients/src/main/java/org/apache/flink/client/program/JobWithJars.java
*Expose JobWithJars.buildUserCodeClassLoader without Configuration to fix backwards compatibility*
Check API of previous version
Yes
It worked this way in previous versions so 'kind of'.
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes (it fixes it) …
> [FLINK-15844][client] Expose JobWithJars.buildUserCodeClassLoader without Configuration to fix backwards compatibility

- docs/ops/upgrading.md
- docs/ops/upgrading.zh.md
Fix documentation on savepoints pre-conditions, and clarify that savepoints are not relocatable for now
- Changes occur on savepointing in 1.3
- Documentation needs to be updated
- New changes are coming w.r.t savepoint relocation
> [FLINK-15863][docs] Fix docs stating that savepoints are relocatable

- flink-python/tox.ini
Add version range of grpcio.
- Add version range of grpcio in tox.ini.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: ( no)
> [FLINK-15921] Add version range of grpcio.

- flink-examples/flink-examples-table/pom.xml
- flink-examples/flink-examples-table/src/main/java/org/apache/flink/table/examples/java/StreamWindowSQLExample.java
We missed to add the new introduced StreamWindowSQLExample to dist. 
- This created a StreamWindowSQLExample.jar and add to dist. 
- Add a usage description in the javadoc of `StreamWindowSQLExample`.
build in local and run `./bin/flink run ./examples/table/StreamWindowSQLExample.java`.
- …
> [hotfix][example] Add StreamWindowSQLExample.jar to dist

- docs/dev/libs/state_processor_api.md
- docs/dev/libs/state_processor_api.zh.md
* Fix some typos in state_processor_api docs.
*I modified the "docs/dev/libs/state_processor_api.md" and  "docs/dev/libs/state_processor_api.zh.md"  file .*
*I have verified the changes by starting the build script in preview mode.*
Hi, @wuchong  @tillrohrmann  Please take a look,Thank you …
> [hotfix][docs]  Fix some typos in state_processor_api docs

- docs/dev/stream/state/state.zh.md
chinese translate of #10934
RocksDB compaction filter is always enabled by default after #10866 and we deprecated its disabling. The docs should not refer to its enabling/disabling. The Chinese translation still has to be adjusted separately. …
> [FLINK-15741][docs-zh][TTL] Fix TTL docs after enabling RocksDB compaction filter by default

- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionGraph.java
> [hotfix] Remove deadcode in ExecutionGraph#restart

- flink-core/src/test/java/org/apache/flink/testutils/migration/MigrationVersion.java
*This pull request adds MigrationVersion.v1_10*
- *Add MigrationVersion.v1_10* …
> [FLINK-15708] Add MigrationVersion.v1_10

- flink-connectors/flink-connector-elasticsearch-base/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/ElasticsearchUpsertTableSinkFactoryTestBase.java
- flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch6/Elasticsearch6UpsertTableSinkFactoryTest.java
- flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch7/Elasticsearch7UpsertTableSinkFactoryTest.java
- flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonRowSerializationSchema.java
- flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/JsonRowFormatFactoryTest.java
Change JsonRowSerializationSchema's constructor private, and force to use Builder to build JsonRowSerializationSchema.
- JsonRowSerializationSchema's constructor private
- Add static builder method for JsonRowSerializationSchema
- deprecate JsonRowSerializationSchema.Builder's public constructor
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / …
> [FLINK-15988][json] Make JsonRowSerializationSchema's constructor private

- flink-runtime/src/test/java/org/apache/flink/runtime/blob/BlobServerRangeTest.java
Provides the BlobServer with a port range instead of a single port.
> [FLINK-16169][tests] Harden BlobServerRangeTest

- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/expressions/resolver/rules/ExpandColumnFunctionsRule.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/expressions/resolver/rules/QualifyBuiltInFunctionsRule.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/expressions/resolver/rules/ReferenceResolverRule.java
> [hotfix][table-api] Fixed ExpressionResolver rules modifiers

- .github/PULL_REQUEST_TEMPLATE.md
Update pull request template to include Kubernetes as deployment candidates
cc @zentol
> [FLINK-15977][docs] Update pull request template to include Kubernetes as deployment candidates

- tools/azure-pipelines/jobs-template.yml
> [hotfix][build system] Do not trigger dependent jobs if predecessor fails

- flink-connectors/flink-connector-hive/pom.xml
Adds several missing log4j1 exclusions, that are only necessary for certain hive versions.
> [FLINK-16233][hive][build] Add additional log4j 1 exclusions

- docs/dev/table/index.zh.md
Translate /dev/table/streaming/index.zh.md
Translate /dev/table/streaming/index.zh.md …
> [FLINK-16081][docs] Translate /dev/table/index.zh.md

- flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/AutoClosableProcess.java
- flink-end-to-end-tests/flink-end-to-end-tests-common/src/main/java/org/apache/flink/tests/util/FlinkDistribution.java
Small refactoring to make existing usages more consistent now and in the future.
> [FLINK-16188][e2e] AutoClosableProcess constructor now private

- flink-python/README.md
*This pull request improves the description in the README file of PyFlink 1.9.x.*
- *Rewrite the content of `README.md`.*
> [FLINK-16031][python] Improve the description in the README file of PyFlink 1.9.x.

- flink-connectors/flink-connector-kafka-base/src/main/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaConsumerBase.java
Fix typo in FlinkKafkaConsumerBase
> [hotfix] Fix typo in FlinkKafkaConsumerBase

- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/typeutils/BaseRowSerializer.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/typeutils/BaseRowSerializerTest.java
> [FLINK-16242][table-runtime-blink] Duplicate field serializers in BaseRowSerializer

- flink-python/pyflink/fn_execution/operations.py
*This pull request will optimize the cost of function call in ScalarFunctionOpertation*
- *Remove the InputGetter, OffsetInputGetter, ScalarFunctionInputGetter, ScalarFunctionInvoker*
- *All related compute logic move to ScalarFunctionOpertation*
- *It is a perforce improvement without extra function test* …
> [FLINK-16251][python] Optimize the cost of function call in ScalarFunctionOpertation

- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/runtime/aggregate/GroupAggProcessFunction.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/runtime/aggregate/GroupTableAggProcessFunction.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/runtime/aggregate/ProcTimeBoundedRangeOver.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/runtime/aggregate/ProcTimeBoundedRowsOver.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/runtime/aggregate/ProcTimeUnboundedOver.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/runtime/aggregate/RowTimeBoundedRangeOver.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/runtime/aggregate/RowTimeBoundedRowsOver.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/runtime/aggregate/RowTimeUnboundedOver.scala
Fix potential NullPointerException when invoking close() on generated function in legacy planner.
- Check the generated function is not null before close it.
N/A …
> [FLINK-16283][table-planner] Fix potential NullPointerException when invoking close() on generated function

- flink-filesystems/flink-oss-fs-hadoop/pom.xml
From release-1.9, Flink suggest users to load all filesystem with plugin, including oss. However, it could not work for oss filesystem. The root cause is it does not shade the org.apache.flink.runtime.fs.hdfs and org.apache.flink.runtime.util. So they will always be loaded by system classloader.
What we need to do is shading the two packages `org.apache.flink.runtime.fs.hdfs` and `org.apache.flink.runtime.util`, just like s3 and azure.
* shading two packages `org.apache.flink.runtime.fs.hdfs` and `org.apache.flink.runtime.util`
* Configure the HA storage to oss and manually run a standalone Flink cluster 
- The runtime …
> [FLINK-16115][filesystem] Make aliyun oss filesystem could work with plugin mechanism

- flink-python/pyflink/fn_execution/operations.py
*This pull request will optimize the progress of the process_outputs in Python UDF*
- *Using value_coder to encode_stream directly in ScalarOperation*
- *It is a perforce improvement without extra function test* …
> [FLINK-16252][python] Optimize the progress of the process_outputs in Python UDF

- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/FlinkStandaloneHiveRunner.java
Make sure to kill HMS process if timed out waiting for it to start.
- Make sure to kill HMS process if timed out waiting for it to start.
Existing tests
NA
NA
> [FLINK-16196][hive] FlinkStandaloneHiveRunner leaks HMS process

- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/module/ModuleManager.java
The unknown functions in `ModuleManager` is logged in INFO level which is very verbose and useless for users.
- Change the log level to DEBUG for unknown functions. (maybe we can even remove it)
- Improve the messages to make the function name and module name more obvious.
This change added a test which transforms a nested data type.
- The S3 file …
> [FLINK-16301][table-api] Improve logging message in ModuleManager

- docs/dev/batch/connectors.md
- docs/dev/batch/connectors.zh.md
- docs/dev/batch/index.md
- docs/dev/batch/index.zh.md
- docs/dev/libs/cep.md
- docs/dev/libs/cep.zh.md
- docs/dev/stream/experimental.md
- docs/dev/stream/experimental.zh.md
- docs/dev/stream/operators/index.md
- docs/dev/stream/operators/index.zh.md
- docs/dev/table/functions/systemFunctions.md
- docs/dev/table/functions/systemFunctions.zh.md
- docs/dev/table/streaming/match_recognize.md
- docs/dev/table/streaming/match_recognize.zh.md
- docs/dev/table/tableApi.md
- docs/dev/table/tableApi.zh.md
- docs/getting-started/walkthroughs/datastream_api.md
- docs/getting-started/walkthroughs/datastream_api.zh.md
- docs/ops/deployment/local.md
- docs/ops/deployment/local.zh.md
- docs/ops/python_shell.md
- docs/ops/python_shell.zh.md
- docs/ops/scala_shell.md
- docs/ops/scala_shell.zh.md
- docs/ops/state/large_state_tuning.md
- docs/ops/state/large_state_tuning.zh.md
- docs/ops/state/state_backends.md
- docs/ops/state/state_backends.zh.md
Remove unnecessary indents and blank lines in code blocks.
Remove unnecessary indents and blank lines in code blocks
Build the doc and check the relevant code blocks.
cc @zentol
> [FLINK-16297] Remove unnecessary indents and blank lines in code blocks

- docs/_includes/generated/common_miscellaneous_section.html
- docs/_includes/generated/core_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/CoreOptions.java
- flink-core/src/main/java/org/apache/flink/core/fs/FileSystem.java
- flink-core/src/test/java/org/apache/flink/core/fs/FileSystemTest.java
- flink-filesystems/flink-hadoop-fs/src/main/java/org/apache/flink/runtime/fs/hdfs/HadoopRecoverableWriter.java
Throw an error when a plugin for a known scheme is missing.
The error also avoid Hadoop fallback being used for s3 or other directly supported schemes.
- Adding hard-coded list of known scheme/plugins.
- Use list for meaningful error messages when a scheme does not have a matching FileSystem.
Added two unit tests. …
>  [FLINK-16015][filesystems]Throw an error when a plugin for a known scheme is missing.

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamGraphHasherV2.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGenerator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperatorFactory.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGeneratorTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/operators/async/AsyncWaitOperatorTest.java
Made AsyncWaitOperator chainable to non-sources.
- Adding HEAD_AFTER_LEGACY_SOURCE ChainingStrategy.  Operators will be eagerly chained whenever possible, except after legacy sources.
- Made AsyncWaitOperator chainable to non-sources.
- Added AsyncWaitOperatorTest#testAsyncOperatorIsNotChainedToSources
- The S3 file system connector: (yes …
> [FLINK-16219][runtime] Made AsyncWaitOperator chainable to non-sources.

- flink-core/src/main/java/org/apache/flink/api/common/io/InputFormat.java
> [hotfix][javadoc] Fix typo in InputFormat

- docs/dev/libs/cep.zh.md
*This pull request translates the CEP page into Chinese.*
This change is a docs work without any test coverage.
> [FLINK-16140] [docs-zh] Translate Event Processing (CEP) page into Chinese

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/KinesisDataFetcher.java
* Don't start the emitter thread when watermark synchronization was not configured
> [FLINK-16393][kinesis] Skip record emitter thread creation w/o source sync

- docs/dev/table/streaming/time_attributes.zh.md
Translate /dev/table/streaming/time_attributes.zh.md
Translate /dev/table/streaming/time_attributes.zh.md …
> [FLINK-16084][docs] Translate /dev/table/streaming/time_attributes.zh.md

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/client/HiveShimV210.java
We can use hive 2.2 dependencies to support hive 2.0.0 metastore server.
Consider HiveShim2.2 and 2.1, only primary key is not compatible. We can catch this non-compatible invalid method name exception, and return none.
Return none instead of throwing exception when Invalid method name `HiveShimV210.getPrimaryKey`
Manually testing.
- The …
> [FLINK-16500][hive] Hive get primary key should not throw exception when Invalid method name

- docs/dev/table/sql/queries.md
- docs/dev/table/sql/queries.zh.md
Add documentation about "GROUPING SETS" and "CUBE" support in streaming mode. They are already 
supported since 1.9, but we missed to update the documentation. 
update the documentation.
N/A
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / no / don't know) …
> [FLINK-16530][docs] Add documentation about "GROUPING SETS" and "CUBE" support in streaming mode

- docs/ops/deployment/index.md
- docs/ops/deployment/index.zh.md
Add an overview of vendor offerings to help improve Flink adoption in the enterprise.
Include a table with a list of Enterprise Flink offerings and links to their respective documentation.
This change is a trivial rework/code cleanup without any test coverage.
> [FLINK-15337][docs] Add vendor table to documentation

- flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/async/AsyncIOExample.java
- flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/iteration/IterateExample.java
- flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/join/WindowJoin.java
- flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/sideoutput/SideOutputExample.java
- flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/statemachine/generator/EventsGeneratorSource.java
*Fix some typos in flink-examples-streaming*
*Fix some typos in flink-examples-streaming*
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: ( no )
> [hotfix] [flink-examples-streaming] Fix some typos

- flink-filesystems/flink-s3-fs-base/src/main/java/com/amazonaws/services/s3/model/transform/XmlResponsesSaxParser.java
This commit explicitly enables Sax' NAMESPACES_FEATURE (default true) in JAXP (default false), such that multi part uploads to S3 actually work.
Explicitly enables Sax' NAMESPACES_FEATURE (default true) in JAXP (default false).
Covered by e2e only executed on nightly.
- Does this …
> [FLINK-16550][s3] Force namespace parsing in XmlResponsesSaxParser.

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliClient.java
fix sql client set int param error
- Remove spaces before and after attribute value
> [FLINK-16539]fix sql client set int param error

- docs/dev/table/modules.md
- docs/dev/table/modules.zh.md
fix mistakes in module document from Catalogs to Modules.
> [hotfix][docs] fix mistakes in Modules document

- azure-pipelines.yml
- tools/azure-pipelines/build-apache-repo.yml
This PR is to mitigate the current outage / issue with AZP: https://status.dev.azure.com/_event/179641421
> [FLINK-16613] make build trigger on azp more reliable

- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/harness/GroupAggregateHarnessTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/SplitAggregateITCase.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/aggregate/GroupAggFunction.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/util/BaseRowHarnessAssertor.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/util/StreamRecordUtils.java
Before these changes, a new accumulator was created and invalid retraction messages were emitted. This change drops retraction messages for which no accumulator exists.
This picks the implementation and tests from FLINK-10674.
- drops retraction messages for which no accumulator exists.
- added an integration test for distinct with retraction (passed before this change)
- added a harness test to cover this change (failed before this change). …
> [FLINK-16047][table-planner-blink] Fix Blink planner produces wrong aggregate results with state clean up

- docs/getting-started/walkthroughs/datastream_api.md
> [hotfix] [docs] Fix typo in DataStream API walkthrough

- docs/dev/table/connect.md
- docs/dev/table/connect.zh.md
This pull request to fix the spelling mistakes
fix the spelling mistakes
This pull request do not need test
> [FLINK-16678][Document/HBase Connector]fix the word error

- flink-connectors/flink-sql-connector-elasticsearch7/pom.xml
- flink-connectors/pom.xml
- flink-end-to-end-tests/flink-sql-client-test/pom.xml
- flink-end-to-end-tests/run-nightly-tests.sh
- flink-end-to-end-tests/test-scripts/elasticsearch-common.sh
- flink-end-to-end-tests/test-scripts/test_sql_client.sh
- tools/travis/splits/split_misc.sh
[FLINK-16170][Connectors/elasticsearch]SearchTemplateRequest ClassNotFoundException when use flink-sql-connector-elasticsearch7
*This pull request fix the ClassNotFoundException  flink-sql-connector-elasticsearch7*
- *Correct the shade exclusions*
- *Remove relocation rule for log4j2*
This change is a trivial rework / code cleanup without any test coverage,
but I checked the flink-sql-connector-elasticsearch7_2.11-1.11-SNAPSHOT.jar in sql-client :
`
Flink SQL> CREATE TABLE es_table (
>   aggId varchar ,
>   pageId varchar ,
>   ts varchar ,
>   expoCnt int ,
>   clkCnt int
> ) WITH (
> 'connector.type' = 'elasticsearch',
> 'connector.version' = '7',
> 'connector.hosts' = 'http://localhost:9200',
> 'connector.index' = 'cli_test',
> 'connector.document-type' = '_doc',
> 'update-mode' = …
> [FLINK-16170][connectors/elasticsearch]SearchTemplateRequest ClassNotFoundException when use flink-sql-connector-elasticsearch7

- docs/_includes/generated/kubernetes_config_configuration.html
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/configuration/KubernetesConfigOptions.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/AbstractKubernetesParameters.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesJobManagerParameters.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesTaskManagerParameters.java
- flink-kubernetes/src/main/java/org/apache/flink/kubernetes/utils/KubernetesUtils.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/KubernetesTestBase.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/KubernetesJobManagerTestBase.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/KubernetesTaskManagerTestBase.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/ExternalServiceDecoratorTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/InitJobManagerDecoratorTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/InitTaskManagerDecoratorTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/decorators/InternalServiceDecoratorTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/factory/KubernetesJobManagerFactoryTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/factory/KubernetesTaskManagerFactoryTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesJobManagerParametersTest.java
- flink-kubernetes/src/test/java/org/apache/flink/kubernetes/kubeclient/parameters/KubernetesTaskManagerParametersTest.java
Introduce config options to support to set labels and node-selector for JM/TM pods. 
* The [labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) are key/value pairs that will be attached to the JM/TM pod.
* Support to set labels
* Unit tests
* Manually test in a real cluster
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes) …
> [FLINK-15640][k8s] Support to set labels for jobmanager and taskmanager pod

- azure-pipelines.yml
- tools/azure-pipelines/build-apache-repo.yml
Some profiles were not activated for the Java e2e tests.
- Enable missing profiles
> [FLINK-16778][e2e] Make sure all java e2e tests are running

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/KafkaPartitionDiscoverer.java
> [hotfix][connector] Correct exception message

- flink-dist/src/main/flink-bin/bin/taskmanager.sh
Fixes an issue where the logs from the BashJavaUtils were no longer forwarded.
/cc @xintongsong
> [FLINK-16798][scripts] Properly forward BashJavaUtils logging output

- flink-annotations/src/main/java/org/apache/flink/annotation/Internal.java
*(or)*
*(or)*
*(example:)*
- *Extended …
> [FLINK-16849] [docs] Comment is not reasonable

- licenses/LICENSE.jquery
Adds the jquery license since it is used for the documentation.
> [FLINK-16888][legal] Add jquery license

- flink-connectors/flink-connector-hive/pom.xml
The derby hive-metastore uses is vulnerable to CVE-2015-1832. Since derby is only needed in tests, we should explicitly move it to test scope.
- Exclude derby from hive-metastore
- Add derby dependency in test scope
- Update profiles to use proper derby versions according to hive versions
Manually run all hive tests for each profile.
- If yes, how …
> [FLINK-16772][hive] Move derby dependency to test scope

- flink-end-to-end-tests/test-scripts/elasticsearch-common.sh
- flink-end-to-end-tests/test-scripts/test_quickstarts.sh
- flink-end-to-end-tests/test-scripts/test_sql_client.sh
Elasticsearch Xpack Machine Learning function doesn't support ARM arch. We should disable it on ARM. Passing the Elasticsearch version to `setup_elasticsearch` can fix the problem.
Add `eleasticsearch_version` parameter to `setup_elasticsearch` function.
Remove the default value of `elasticsearch_version.
This change is already covered by existing end-to-end tests.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: …
> [FLINK-14126][test] Ensure elasticsearch version check

- docs/monitoring/metrics.md
- docs/monitoring/metrics.zh.md
- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/runtime/SavepointEnvironment.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/writer/BroadcastRecordWriter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/writer/ChannelSelectorRecordWriter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/writer/RecordWriter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/writer/ResultPartitionWriter.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/BufferProvider.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/buffer/LocalBufferPool.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/ResultPartition.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/MetricNames.java
- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/TaskIOMetricGroup.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/ConsumableNotifyingResultPartitionWriterDecorator.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/writer/AbstractCollectingResultPartitionWriter.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/writer/RecordWriterTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/buffer/NoOpBufferPool.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/MockResultPartitionWriter.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/util/TestPooledBufferProvider.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/TaskIOMetricGroupTest.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/mailbox/MailboxProcessor.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/mailbox/TaskMailboxProcessorTest.java
This pr adds an IdleTime metric which measures idle time of a task including the time cost for mail processor to wait for new mail and the time cost in record writer to waiting a new buffer.
1. when a job can not catch up with the speed of data generating, the vertex which idle time is near to zero is the bottle neck of the job.
2. when a job is not busy, idle time can be used to guide user how much he can scale down the job.
A meter metrics named idleTimeMsPerSecond is added in TaskIOMetricGroup:
- *idleTime contains time waiting mail and time waiting output buffer. *
- *waiting mail time is collected when mail processor is trying to process a new mail but no mail submitted.*
- *waiting output buffer time is collected when record writer is trying to request a new buffer from result …
> [FLINK-16864][metrics] Add IdleTime metric for task.

- docs/concepts/index.md
This PR fixes minor typos in the concepts part of the website
cf above
no, no side effect
R: @aljoscha
> [hotfix] [docs] Fix typo in concepts.

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/GenerateUtils.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/api/TableEnvironmentITCase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/expressions/DecimalTypeTest.scala
Fix NPE when comparing decimal column with null values.
- Fix `GenerateUtils::generateLiteral` for decimal type
- Add test case
Added test case
> [FLINK-16771][table-planner-blink] NPE when filtering by decimal column

- docs/dev/table/functions/udfs.md
- docs/dev/table/functions/udfs.zh.md
- docs/dev/table/python/python_udfs.md
- docs/dev/table/python/python_udfs.zh.md
*This pull request will add Python UDTF related doc*
- *Add doc description of Python UDTF in python_udfs.md and python_udfs.zh.md *
- *Add some Python UDTF content in udfs.md and python_udfs.zh.md*
- *Move the ussage of Java UDTF in Python from udfs.md to python_udfs.md*
> [FLINK-16748][python][doc] Add Python UDTF doc

- docs/dev/table/python/index.md
- docs/dev/table/python/index.zh.md
- docs/dev/table/python/vectorized_python_udfs.md
- docs/dev/table/python/vectorized_python_udfs.zh.md
*This pull request add documentation for vectorized Python UDF.*
- *Add documentation `vectorized_python_udfs.md` for vectorized Python UDF*
This change is a documentation rework without any test coverage.
> [FLINK-16486][python][docs] Add documentation for vectorized Python UDF

- docs/monitoring/metrics.md
- docs/monitoring/metrics.zh.md
- flink-metrics/flink-metrics-statsd/src/main/java/org/apache/flink/metrics/statsd/StatsDReporter.java
- flink-metrics/flink-metrics-statsd/src/main/java/org/apache/flink/metrics/statsd/StatsDReporterFactory.java
- flink-metrics/flink-metrics-statsd/src/main/resources/META-INF/services/org.apache.flink.metrics.reporter.MetricReporterFactory
Adds a new `MetricsReporterFactory` implementation to support loading `StatsDReporter` through a factory based approach.
- Does this pull request introduce a new feature? (**yes**)
- If yes, how is the feature documented? (**JavaDocs**)
> [FLINK-16968][stats][metrics] Add StatsDReporterFactory

- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/slotmanager/SlotManager.java
Fix typo of SlotManager JavaDoc
> [hotfix][doc] Fix typo of SlotManager javadoc

- pom.xml
Solve this problem: Use the flink-metrics-prometheus module to report the metric, pushgateway successfully received the data, but Jobmanager and TaskManager will print "Failed to push metrics to PushGateway" and throw "java.io.IOException: Response code from xxx was 200". [FLINK-17132](https://issues.apache.org/jira/browse/FLINK-17132)
- Upgrade <prometheus.version> from 0.3.0 to 0.8.0 in root pom.xml.
This change is already covered by existing tests, such as PrometheusPushGatewayReporterTest&PrometheusReporterTaskScopeTest&PrometheusReporterTest.
- Anything …
> [FLINK-17132][metrics] Use the latest version of simpleclient_pushgateway to solve the "Failed to push metrics to PushGateway" problem

- flink-connectors/flink-connector-hive/pom.xml
- flink-connectors/flink-sql-connector-hive-1.2.2/pom.xml
- flink-connectors/flink-sql-connector-hive-2.2.0/pom.xml
- flink-formats/flink-orc-nohive/pom.xml
- flink-formats/flink-orc-nohive/src/main/java/org/apache/flink/orc/nohive/vector/AbstractOrcNoHiveVector.java
- flink-formats/flink-orc/pom.xml
- pom.xml
Flink's ORC dependency is 1.4.3 which is little outdated so it makes sense to upgrade to a more latest stable version.
- Update `orc.version` to 1.5.6
- Fixed a failing test case.
- Added `org.apache.hadoop:hadoop-hdfs` to the exclusions in `flink-orc` and `flink-orc-nohive` module since `orc-core:1.5.6` has `hadoop-hdfs` as a compile time dependency
- Dependencies (does it add or upgrade a dependency): (**yes**) …
> FLINK-17142: Bump ORC dependency version to 1.5.6

- flink-python/pyflink/fn_execution/fast_coder_impl.pxd
- flink-python/pyflink/fn_execution/fast_coder_impl.pyx
- flink-python/pyflink/fn_execution/tests/test_fast_coders.py
*This pull request will support complex DataTypes in Cython*
- *Add the cython implementation of complex DataTypes*
- *Added ut test in test_fast_coders.py*
> [FLINK-17119][python] Add Cython support for composite types

- flink-end-to-end-tests/flink-connector-gcp-pubsub-emulator-tests/src/test/java/org/apache/flink/streaming/connectors/gcp/pubsub/CheckPubSubEmulatorTest.java
- flink-end-to-end-tests/flink-connector-gcp-pubsub-emulator-tests/src/test/java/org/apache/flink/streaming/connectors/gcp/pubsub/emulator/PubsubHelper.java
I was unable to consistently reproduce the failing test (see jira ticket for logs). This MR fixes a bug where it would try to send an acknowledge request without any acknowledge id. After that fix, I did not see the test failing anymore.
I do not think this should fix it entirely but I cannot see it failing anymore. I'd like to add this fix and see if the problem arises again and if so with what kind of exceptions.
> [FLINK-16572] [pubsub,e2e] CheckPubSubEmulatorTest is flaky on Azure

- flink-table/flink-table-planner-blink/src/main/resources/META-INF/NOTICE
- flink-table/flink-table-planner/src/main/resources/META-INF/NOTICE
*This pull request fix the icu license, move the icu being under the ICU license block in notice file.*
- *update file flink/flink-table/flink-table-planner-blink/src/main/resources/META-INF/NOTICE*
- *update file flink/flink-table/flink-table-planner/src/main/resources/META-INF/NOTICE*
This change is a hotfix for docs without any test coverage. …
> [hotfix][table sql planner/table sql legacy planner]fix icu license in NOTICE file.

- flink-end-to-end-tests/flink-tpcds-test/src/main/java/org/apache/flink/table/tpcds/TpcdsTestProgram.java
- flink-tests/src/test/java/org/apache/flink/test/optimizer/examples/RelationalQueryCompilerTest.java
*This pull request fix typo error that should be `TPC` rather than `TCP`.*
- *update file TpcdsTestProgram.java and RelationalQueryCompilerTest.java*
> [hotfix][typo]Fix typo in RelationalQueryCompilerTest and TpcdsTestProgram

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/local/ExecutionContext.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/local/LocalExecutor.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/local/ExecutionContextTest.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/local/LocalExecutorITCase.java
`HiveCatalog` may hold resources that need to be released after use. So we should close loaded catalogs when a session ends.
- Iterate and close each catalog in `LocalExecutor::closeSession`.
Existing tests.
> [FLINK-17138][sql-client] Close catalogs when close the session

- flink-metrics/flink-metrics-prometheus/pom.xml
*Now that we load the Prometheus reporters as plugins we should remove the shade-plugin configuration/relocations.*
> [FLINK-17226][metrics]Remove Prometheus shade-plugin relocations

- flink-metrics/flink-metrics-datadog/pom.xml
*Now that we load the Datadog reporters as plugins we should remove the shade-plugin configuration/relocations.*
> [FLINK-17227][metrics]Remove Datadog shade-plugin relocations

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/read/HiveTableInputFormat.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/TableEnvHiveConnectorTest.java
Some Hive readers rely on table schema for schema evolution, name mapping, etc. So we should set the schema in JobConf when creating the reader.
- Set schema info in JobConf for Hive readers.
- Add test cases.
Existing and added test cases. Also manually run tests for all Hive versions.
> [FLINK-16802][hive] Set schema info in JobConf for Hive readers

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/utils/SortUtil.scala
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/batch/table/stringexpr/SetOperatorsTest.xml
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/stream/table/TemporalTableJoinTest.xml
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/expressions/DecimalTypeTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/expressions/NonDeterministicTests.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/expressions/validation/ScalarFunctionsValidationTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/batch/table/JoinTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/batch/table/stringexpr/SetOperatorsTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/table/TemporalTableJoinTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/table/validation/TemporalTableJoinValidationTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/LimitITCase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/MiscITCase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/RankITCase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/DistinctAggregateITCaseBase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/agg/WindowAggregateITCase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/join/JoinConditionTypeCoerceITCase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/join/JoinWithoutKeyITCase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/batch/sql/join/SemiJoinITCase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/batch/table/AggregationITCase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/batch/table/CalcITCase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/SortITCase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/SplitAggregateITCase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/table/CalcITCase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/table/JoinITCase.scala
Most of the ignored tests are actually already supported.
> [FLINK-16935][table-planner-blink] Enable or delete most of the ignored test cases in blink planner.

- docs/monitoring/metrics.md
- docs/monitoring/metrics.zh.md
- flink-metrics/flink-metrics-graphite/src/main/java/org/apache/flink/metrics/graphite/GraphiteReporter.java
- flink-metrics/flink-metrics-graphite/src/main/java/org/apache/flink/metrics/graphite/GraphiteReporterFactory.java
- flink-metrics/flink-metrics-graphite/src/main/resources/META-INF/services/org.apache.flink.metrics.reporter.MetricReporterFactory
Convert Graphite reporter to plugin.
Convert Graphite reporter to plugin.
cc @zentol
> [FLINK-16965] Convert Graphite reporter to plugin

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointITCase.java
Increased timeouts of UnalignedCheckpointITCase.
- Increased timeouts of UnalignedCheckpointITCase. …
> [FLINK-17315][tests] Increased timeouts of UnalignedCheckpointITCase.

- docs/dev/libs/state_processor_api.md
- docs/dev/libs/state_processor_api.zh.md
There is some spelling mistakes in state_processor_api.md, E.g  ”getExecutionEnviornment“.
modify state_processor_api.md doc.
> [hotfix] [docs] fix state_processor_api doc, is spelling mistakes.

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/functions/hive/HiveSimpleUDF.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/functions/hive/conversion/HiveInspectors.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/functions/hive/HiveSimpleUDFTest.java
For more information, please check:
https://github.com/apache/flink/pull/11876
> [FLINK-17334][hive] Flink does not support HIVE UDFs with primitive return types

- docs/dev/table/connect.md
Correct properties typo in [Elasticsearch Connector](https://ci.apache.org/projects/flink/flink-docs-release-1.10/zh/dev/table/connect.html#elasticsearch-connector) documentation.
- Change "back-off" to "backoff" in `connect.md` docs. …
> [hotfix][docs] fix some typos in elasticsearch connector

- flink-formats/flink-json/pom.xml
- flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonRowDataDeserializationSchema.java
- flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonRowDataSerializationSchema.java
- flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/JsonRowDataSerDeSchemaTest.java
Add support JsonRowDataDeserializationSchema and JsonRowDataSerializationSchema for the new data structure RowData. This will be used by new TableSource and TableSink connectors.
The implemented JSON schema feature aligns with the exsiting ones. 
- `JsonRowDataDeserializationSchema` for deserialize `byte[]` into `RowData`.
- `JsonRowDataSerializationSchema` for serialize `RowData` into `byte[]`.
- Added `JsonRowDataSerDeSchemaTest` which covers original `JsonRowDeserializationSchemaTest` and `JsonRowSerializationSchemaTest. …
> [FLINK-17461][formats][json] Support JSON serialization and deseriazation schema for RowData type

- flink-core/src/main/java/org/apache/flink/api/common/io/ratelimiting/GuavaFlinkConnectorRateLimiter.java
> [hotfix][docs] Fix typo in GuavaFlinkConnectorRateLimiter

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointITCase.java
Temporary disable UnalignedCheckpointITCase.
- Temporary disables UnalignedCheckpointITCase. …
> [FLINK-17315][tests] Temporary disable UnalignedCheckpointITCase.

- docs/dev/table/common.md
- docs/dev/table/common.zh.md
- docs/dev/table/sql/queries.md
- docs/dev/table/sql/queries.zh.md
- docs/dev/table/streaming/temporal_tables.md
- docs/dev/table/streaming/temporal_tables.zh.md
- docs/dev/table/streaming/time_attributes.md
- docs/dev/table/streaming/time_attributes.zh.md
- docs/dev/table/tableApi.md
- docs/dev/table/tableApi.zh.md
Updated the documentation to refer only to the Expression based DSL methods instead of methods that accept expressions as a string.
Should be merged after  #11527 as it reflects changes from that PR.
- If yes, how …
> [FLINK-16034][table-api, docs] Updated documentation with new Java Expression DSL

- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/typeutils/FieldInfoUtils.java
- flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/typeutils/FieldInfoUtilsTest.java
*This pull request fix `byPosition` mode judgement in FieldInfoUtils to support reorder and reorder field properly.*
- *update file org/apache/flink/table/typeutils/FieldInfoUtils.java*
- Add related unit tests.
> [FLINK-17420][table sql / api]Cannot alias Tuple and Row fields when converting DataStream to Table

- flink-connectors/flink-connector-kinesis/pom.xml
- flink-connectors/flink-connector-kinesis/src/main/resources/META-INF/NOTICE
Backport of https://github.com/apache/flink/pull/11975
> [FLINK-17496][kinesis] Upgrade amazon-kinesis-producer to 0.14.0

- flink-formats/flink-csv/pom.xml
- flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/CsvRowDataDeserializationSchema.java
- flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/CsvRowDataSerializationSchema.java
- flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/CsvRowSchemaConverter.java
- flink-formats/flink-csv/src/test/java/org/apache/flink/formats/csv/CsvRowDataSerDeSchemaTest.java
Add support CsvRowDataDeserializationSchema and CsvRowDataSerializationSchema for the new data structure RowData. This will be used by new TableSource and TableSink connectors.
The implemented CSV schema feature aligns with the exsiting ones. 
- `CsvRowDataDeserializationSchema` for deserialize csv `byte[]` into `RowData`.
- `CsvRowDataSerializationSchema` for serialize `RowData` into csv `byte[]`.
- Ported tests from `CsvRowDeSerializationSchemaTest` to `CsvRowDataSerDeSchemaTest`. …
> [FLINK-17462][format][csv] Support CSV serialization and deseriazation schema for RowData type

- docs/dev/table/hive/scala_shell_hive.md
- docs/dev/table/hive/scala_shell_hive.zh.md
This pull request translates the scala_shell_hive.zh.md document into Chinese.
- Translate docs/dev/table/hive/scala_shell_hive.zh.md into Chinese 
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no 
> [FLINK-16102][docs-zh] Translate docs/dev/table/hive/scala_shell_hive.zh.md into Chinese

- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/typeutils/FieldInfoUtils.java
- flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/typeutils/FieldInfoUtilsTest.java
*This pull request fix `byPosition` mode judgement in FieldInfoUtils to support reorder and reorder field properly.*
- *update file org/apache/flink/table/typeutils/FieldInfoUtils.java*
- Add related unit tests.
> [FLINK-17420][table sql / api]Cannot alias Tuple and Row fields when  converting DataStream to Table

- flink-python/pyflink/datastream/tests/test_state_backend.py
- flink-python/pyflink/find_flink_home.py
- flink-python/pyflink/fn_execution/tests/test_process_mode_boot.py
- flink-python/pyflink/gen_protos.py
- flink-python/pyflink/java_gateway.py
- flink-python/pyflink/pyflink_callback_server.py
- flink-python/pyflink/pyflink_gateway_server.py
- flink-python/pyflink/table/tests/test_dependency.py
- flink-python/pyflink/table/tests/test_pandas_udf.py
- flink-python/pyflink/table/tests/test_types.py
- flink-python/src/main/java/org/apache/flink/client/python/PythonEnvUtils.java
- flink-python/src/main/java/org/apache/flink/client/python/PythonFunctionFactory.java
- flink-python/src/main/java/org/apache/flink/client/python/PythonGatewayServer.java
- flink-python/src/main/java/org/apache/flink/python/env/ProcessPythonEnvironmentManager.java
- flink-python/src/main/java/org/apache/flink/python/util/ResourceUtil.java
- flink-python/src/main/resources/pyflink-udf-runner.bat
- flink-python/src/main/resources/pyflink-udf-runner.sh
*This pull request support running PyFlink on Windows.*
- *Translate `pyflink-gateway-server.sh` to `pyflink_gateway_server.py`.*
- *Add the windows udf runner `pyflink-udf-runner.bat`.*
- *Fix the test failure when running on Windows.*
This change is already covered by existing tests, such as *all the pyflink tests*. …
> [FLINK-12717][python] Add windows support for PyFlink

- flink-python/pyflink/table/descriptors.py
…licate object description of pyflink.table.descriptors.FileSystem
Fixed the bug of docstring of pyflink.table.descriptors.FileSystem:1:duplicate object description of pyflink.table.descriptors.FileSystem
Deleted duplicated FileSystem in descriptors.py.
> [FLINK-17555][python] Remove duplicate FileSystem object in descriptors

- flink-python/pyflink/fn_execution/boot.py
…amPandasUDFITTests.
Fixed the unstable BlinkStreamDependencyTests that failed to install dependencies due to network issue.
Add 3 times retry for installing user requirements while booting the runner.
This change is already covered by existing tests, such as BlinkStreamDependencyTests.
> [FLINK-17092][python] Add retry when pip install dependencies

- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/api/internal/BatchTableEnvImpl.scala
*This pull request fixes the issue that  the BatchTableEnvImpl use an empty cached file list to create the job pipeline.*
- *The BatchTableEnvImpl now reads the cached files list in the execEnv and use it to create the job pipeline.*
- *prepare a flink-planner batch sql job that contains python udf.*
- *submit the job with `flink run` and python dependency management command line options.*
**NOTE:** This change can be verify automatically after adding the PyFlink e2e tests.
- The runtime per-record code paths (performance sensitive): no) …
> [FLINK-17586][table-planner] Let the BatchTableEnvImpl use the cached files registered in the ExecutionEnvironment to create the job pipeline.

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/HiveCatalog.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/client/HiveMetastoreClientWrapper.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/client/HiveShim.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/client/HiveShimV100.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/client/HiveShimV210.java
- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/client/HiveShimV310.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableFactoryTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/catalog/hive/HiveCatalogHiveMetadataTest.java
Support creating hive tables with constraints.
- Add shim method `createTableWithConstraints`.
- When creating a hive table, i.e. non-generic, get PK and NOT NULL from table schema and call `createTableWithConstraints`.
- Add test case.
Manually run the new test with hive-3.1.1 profile.
> [FLINK-17452][hive] Support creating Hive tables with constraints

- docs/training/etl.zh.md
Translate tutorials/etl.md to chinese.
- etl.zh.md is changed into Chinese version.
> [FLINK-17289][docs]Translate tutorials/etl.md to Chinese

- flink-python/pyflink/java_gateway.py
Currently the py4j will print the INFO level logging information to the console. It is unnecessary for users. We should set the level to WARN.
- changed the log level of java_gateway to WARN in java_gateway.py.
This pull request does not need to have test case coverage since it just simply change the log level.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: ( no )
- Does this …
> [FLINK-17628][python] Remove the unnecessary py4j log information.

- docs/dev/connectors/kinesis.md
- docs/dev/connectors/kinesis.zh.md
The docs refer to a non-existing method
> [hotfix][docs] Fix Kinesis consumer example

- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectTest.java
- flink-table/flink-sql-parser-hive/src/main/codegen/data/Parser.tdd
- flink-table/flink-sql-parser-hive/src/main/codegen/includes/parserImpls.ftl
- flink-table/flink-sql-parser-hive/src/test/java/org/apache/flink/sql/parser/hive/FlinkHiveSqlParserImplTest.java
To implement FUNCTION & CATALOG DDLs for Hive dialect.
- Implement the syntax
- Add test cases
Added test cases.
> [FLINK-17450][sql-parser][hive] Implement function & catalog DDLs for Hive dialect

- docs/dev/stream/state/broadcast_state.zh.md
Translate "The Broadcast State Pattern" page into Chinese
* Dependencies (does it add or upgrade a dependency): (no)
* The public API, i.e., is any changed class annotated with @Public(Evolving): (no)
* The serializers: (no)
* The runtime per-record code paths (performance sensitive): (no)
* Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no)
* The S3 file system connector: (no)
* Does this pull request introduce a new feature? (no)
* If yes, how is the feature documented? (not applicable)
CC @carp84 @klion26
> [FLINK-16075][docs-zh] Translate "The Broadcast State Pattern" page into Chinese

- docs/monitoring/metrics.md
- docs/monitoring/metrics.zh.md
- flink-metrics/flink-metrics-influxdb/pom.xml
- flink-metrics/flink-metrics-influxdb/src/main/java/org/apache/flink/metrics/influxdb/InfluxdbReporter.java
- flink-metrics/flink-metrics-influxdb/src/main/java/org/apache/flink/metrics/influxdb/InfluxdbReporterFactory.java
- flink-metrics/flink-metrics-influxdb/src/main/resources/META-INF/service/org.apache.flink.metrics.reporter.MetricReporterFactory
*Convert InfluxDB reporter to plugin,Set SPI configuration for reporter*
*(or)*
*(or)*
*(example:)*
- *Added test that validates that TaskInfo is …
> [FLINK-16966][metrics][infuxdb] Convert InfluxDB reporter to plugin

- flink-end-to-end-tests/test-scripts/common_docker.sh
- flink-end-to-end-tests/test-scripts/common_kubernetes.sh
- flink-end-to-end-tests/test-scripts/container-scripts/docker-compose.nat.yml
- flink-end-to-end-tests/test-scripts/container-scripts/docker-compose.test.yml
- flink-end-to-end-tests/test-scripts/container-scripts/job-cluster-service.yaml
- flink-end-to-end-tests/test-scripts/python2_fileserver.py
- flink-end-to-end-tests/test-scripts/python3_fileserver.py
- flink-end-to-end-tests/test-scripts/test_docker_embedded_job.sh
- flink-end-to-end-tests/test-scripts/test_kubernetes_application.sh
- flink-end-to-end-tests/test-scripts/test_kubernetes_embedded_job.sh
- flink-end-to-end-tests/test-scripts/test_kubernetes_session.sh
- flink-end-to-end-tests/test-scripts/test_nat.sh
Migrates e2e tests relying on flink-container/docker to [flink-docker|https://github.com/apache/flink-docker].
The changes mostly cover how the Docker image is built.
We now first create a custom Dockerfile, by checking out `flink-docker/dev-master` and using the `add-custom.sh` script. This requires the distribution to be accessible from some URL, so we tar the locally built distribution and server it with a local python webserver.
For job clusters, instead of backing in the job artifacts into the image we now use instead mount them into the `usrlib` directory, which is the new default approach.
Some arguments had to be modified, since `flink-docker` closely follows the existing CLI scripts, which flink-container/docker did not.
>  [FLINK-17656][tests] Migrate docker e2e tests to flink-docker 

- docs/ops/deployment/native_kubernetes.md
- docs/ops/deployment/native_kubernetes.zh.md
Fix the broken link in the native Kubernetes document.
The "its tags" link in the follow part is broken.
https://ci.apache.org/projects/flink/flink-docs-master/ops/deployment/native_kubernetes.html#custom-flink-docker-image
> [hotfix][doc] Fix broken link in the native Kubernetes document

- flink-connectors/flink-connector-kafka-base/src/main/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaConsumerBase.java
- flink-connectors/flink-connector-kafka-base/src/main/java/org/apache/flink/streaming/connectors/kafka/internals/AbstractFetcher.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaProducer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/KafkaFetcher.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internal/KafkaShuffleFetcher.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/shuffle/FlinkKafkaShuffle.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/shuffle/FlinkKafkaShuffleConsumer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/shuffle/FlinkKafkaShuffleProducer.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/shuffle/StreamKafkaShuffleSink.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/shuffle/KafkaShuffleExactlyOnceITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/shuffle/KafkaShuffleITCase.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/shuffle/KafkaShuffleTestBase.java
- flink-connectors/flink-connector-kafka/src/test/resources/log4j2-test.properties
- flink-core/src/main/java/org/apache/flink/util/PropertiesUtil.java
- flink-core/src/test/java/org/apache/flink/util/PropertiesUtilTest.java
This pull request is to provide a Kafka Source/Sink pair to simulate a KafkaShuffle that can:
1. Read topics that are already partitioned by key and process them without partitioning them again (avoid shuffles); and
2. Use this to decompose the job into smaller jobs and independent pipelined regions that failover independently.
- Extend Datastream API to allow user-defined SinkFunction to manipulate watermark
- Kafka Shuffle Producer change
- Write timestamp and watermark information together with a record in Kafka
- Use `KeyGroupRangeAssignment` to assign records to different Kafka partitions
- Kafka Shuffle Consumer change, Kafka Fechter Change
- Each consumer read partitions equal to the key group indices that it got assigned. For now, the number of partitions is enforced to equal to …
> [FLINK-15670][API] Provide a Kafka Source/Sink pair as KafkaShuffle

- flink-core/src/main/java/org/apache/flink/configuration/ConfigOption.java
- flink-core/src/main/java/org/apache/flink/configuration/ConfigOptions.java
- flink-core/src/main/java/org/apache/flink/configuration/Configuration.java
Trivial change removing some raw `Class` usage around Configuration/ConfigOptions.
> [hotfix] Remove raw class usages in Configuration.

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliClient.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliStrings.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/SqlCommandParser.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/Executor.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/local/LocalExecutor.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientTest.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliResultViewTest.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/SqlCommandParserTest.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/TestingExecutor.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/local/LocalExecutorITCase.java
This PR supports CREATE/DROP/ALTER functions in SQL-CLI.
Added ITs.
> [FLINK-17715][sql client] Supports function DDLs in SQL-CLI

- flink-dist/src/main/flink-bin/conf/log4j-console.properties
- flink-dist/src/main/flink-bin/conf/log4j.properties
When we upgrade the log4j to log4j2, there are some residual log4j logger configuration in the comments. Just like following,
log4j.properties and log4j-console.properties
```
#log4j.logger.org.apache.flink=INFO
```
We should update them to the log4j2 format.
```
logger.flink.name = org.apache.flink
logger.flink.level = INFO
```
> [FLINK-17618][flink-dist] Update the outdated comments in log4j2 configuration files

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestExecutorImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriterImpl.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequestExecutorImplTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriterImplTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/state/ChannelPersistenceITCase.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SubtaskCheckpointCoordinatorImpl.java
Add task name to the executor thread and to all method of ChannelStateWriter (as they can be called from any other thread), such that log statements can be connected to the respective task. …
> [FLINK-17780][checkpointing] Add task name to log statements of ChannelStateWriter.

- flink-table/flink-table-common/src/main/java/org/apache/flink/table/data/DecimalData.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/data/DecimalDataTest.java
When precision is compact, the returned `DecimalData.toUnscaledBytes()` is a 8-bytes length byte array which is incompatible with `BigDecimla.unscaledValue.toByteArray()`.
- Fix the implementation of  `DecimalData.toUnscaledBytes()` and `DecimalData.fromUnscaledBytes()`.
- added tests in `DecimalDataTest` …
> [FLINK-16922][table-common] Fix DecimalData.toUnscaledBytes() should be consistent with BigDecimla.unscaledValue.toByteArray()

- flink-core/src/main/java/org/apache/flink/core/fs/SafetyNetCloseableRegistry.java
- flink-core/src/test/java/org/apache/flink/core/fs/SafetyNetCloseableRegistryTest.java
This Pull Request is to fix the bug that REAPER_THREAD.start() failure in SafetyNetCloseableRegistry lead to the repeated failover, as described in [FLINK-17645](https://issues.apache.org/jira/browse/FLINK-17645)
Reset `SafetyNetCloseableRegistry#REAPER_THREAD` if it fails to start 
Add `testReaperThreadStartFailed` in `SafetyNetCloseableRegistryTest` for this case.
- Dependencies (does it add or upgrade a dependency):  **no**
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`:  **no**
- The serializers:  **no**
- The runtime per-record code paths (performance sensitive):  **no**
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: **no**
- Does …
> [FLINK-17645][runtime] Reset SafetyNetCloseableRegistry#REAPER_THREAD if it fails to start

- flink-jepsen/README.md
This adds documentation about our correctness model to flink-jepsen.
> [hotfix][tests] Document jepsen correctness model

- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/catalog/PostgresCatalog.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/catalog/PostgresCatalogITCase.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/catalog/PostgresCatalogTest.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/catalog/PostgresCatalogTestBase.java
This pull request allows to read and write serial fields
From types spec listed in https://www.postgresql.org/docs/12/datatype-numeric.html, handled serial types in  in PostgresCatalog.fromJDBCType:
- _serial_, _serial2_ , _serial4_  as **INT** 
- _bigserial_, _serial8_ as **BIGINT**
- _smallserial_ as **SMALLINT**
However serial type is auto-incremented: you can write a value into it but if you try to autogenerate a value you get duplicate values until you find a value that is not already in use. However Flink does not keep track of the original field type so there's no way to warn the user that is not using this field correctly (he/she should use DEFAULT or not specify any value for such columns).
- Dependencies …
> [FLINK-17284][jdbc][postgres] Support serial fields

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/serialization/NonSpanningWrapper.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/api/serialization/SpillingAdaptiveSpanningRecordDeserializer.java
This removes `NextRecordResponse` and inlines `NonSpanningWrapper#getNextRecord` to fix second performance regression that happened on May 19th. This second regression is visible as a difference between results from Mat 19th (before regression) and May 22nd - 29th (period after fixing the first performance regression):
http://codespeed.dak8s.net:8000/timeline/?ben=networkBroadcastThroughput&env=2
It was introduced by the following commit:
> [824100e1460dd2f78f689da72bc5d7b0c9dcbbde] [FLINK-17547][task][hotfix] Extract methods from RecordsDeserializer
`networkBroadcastThroughput` benchmark results are restored from ~1000 to ~1100 ops/ms on the Hetzner worker.
Change is covered by existing tests. …
> [FLINK-17842][network] Remove NextRecordResponse to improve deserialisation performance

- docs/concepts/flink-architecture.zh.md
- docs/dev/batch/hadoop_compatibility.zh.md
- docs/dev/batch/index.zh.md
- docs/dev/connectors/cassandra.zh.md
- docs/dev/stream/operators/index.zh.md
- docs/dev/stream/state/state.zh.md
- docs/dev/table/common.zh.md
Fix error when run build_docs.sh -p in docs dir with master 
Liquid Exception: Could not find document 'concepts/stateful-stream-processing.md' in tag 'link'. Make sure the document exists and the path is correct. in dev/stream/state/state.zh.md
List files also have same problem.
concepts/flink-architecture.zh.md
dev/batch/hadoop_compatibility.zh.md
dev/batch/index.zh.md
dev/connectors/cassandra.zh.md
dev/stream/operators/index.zh.md
dev/stream/operators/state.zh.md
dev/table/common.zh.md
- Fix error when run build_docs.sh -p in docs dir with master  …
> [FLINK-17967][Documentation]Could not find document *** in docs

- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDialectITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveLookupJoinITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveLookupJoinTest.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableSinkITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableSourceITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/TableEnvHiveConnectorITCase.java
Hive connector tests that use FlinkStandaloneHiveRunner should be IT cases. Besides, changing them to IT cases can avoid lib conflicts because we'll be using the shaded jars, e.g. guava.
- Change some tests to IT cases
- Fix `HiveTableSourceITCase` so that it runs with hive 1.x
- Update `HiveLookupJoinTest` so that it doesn't require the hive runner
Existing tests
N/A
N/A
> [FLINK-17937][hive] Change some hive connector tests to IT cases

- flink-python/pyflink/pyflink_gateway_server.py
Resolve CWE22 problems in pyflink_gateway_server.py.
For example, the code `if os.path.isfile(flink_conf_path):` contains CWE22 problem that calling "os.path.isfile" with the tainted value in argument 1. This constructs a path or URI using the tainted value and may thus allow an attacker to access, modify, or test the existence of critical or sensitive files.
More information about CWE22 here: https://cwe.mitre.org/data/definitions/22.html
- use the real path of the found path before joining the paths in pyflink_gateway_server.py
This pull request have been covered by previous test cases. …
> [FLINK-18151][python] Resolve CWE22 problems in pyflink_gateway_server.py

- docs/dev/table/hive/hive_dialect.md
- docs/dev/table/hive/hive_dialect.zh.md
- docs/dev/table/hive/index.md
Add doc for Hive dialect.
- Add a new page for Hive dialect
Manually built the page and everything looks fine.
NA
NA
> [FLINK-17776][hive][doc] Add documentation for DDL&DML in hive dialect

- docs/dev/table/config.md
- docs/dev/table/config.zh.md
- docs/dev/table/sql/hints.md
- docs/dev/table/sql/hints.zh.md
- docs/dev/table/sql/index.md
- docs/dev/table/sql/index.zh.md
- docs/dev/table/sql/queries.md
- docs/dev/table/sql/queries.zh.md
Add documentation for dynamic table options.
Here is a screenshot:
> [FLINK-17406][doc] Add documentation about dynamic table options

- .asf.yaml
- tools/releasing/create_source_release.sh
(I know it is already disabled, this is just for consistency and to introduce the asf.yaml concept to all repos)
> [FLINK-17287][github] Disable merge commit button

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/module/hive/HiveModule.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/module/hive/HiveModuleTest.java
Ban `count` in HiveModule to avoid the `count(*)` issue.
- Add `count` to HiveModule blacklist
Covered by `HiveModuleTest::testBlackList`
NA
NA
> [FLINK-16291][hive] Ban count from HiveModule

- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/TableEnvHiveConnectorITCase.java
Add tests for read/write avro tables.
- Add test case
Added test case
NA
> [FLINK-16559][hive] Add test for avro table

- docs/dev/table/connectors/filesystem.md
- docs/dev/table/connectors/filesystem.zh.md
*FLINK-18176 adds supplement for new file system connector document: 1) illustrate behaviour difference between old file system connector and new system connector; 2) explain how to observe the data immediately after inserting into table using rolling policy and checkpointing.interval parameter*
- *Update file system connector document* …
> [FLINK-18176][document] Add supplement for file system connector document

- flink-dist/src/main/assemblies/opt.xml
- flink-dist/src/main/assemblies/plugins.xml
Bundle GPU plugin in plugins/ directory
Bundle GPU plugin in plugins/ directory
> [FLINK-18018] Bundle GPU plugin in plugins/ directory

- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/main/java/org/apache/flink/tests/util/kafka/KafkaResource.java
Modify (**is** none is configured) to   (**if**  none is configured)
> [hotfix][javadocs]Fix typo in KafkaResource.java

- docs/dev/table/connectors/formats/avro.md
- docs/dev/table/connectors/formats/avro.zh.md
As discussed in #12523, we prefer to link https://ci.apache.org/projects/flink/flink-docs-master/ops/deployment/hadoop.html instead of giving the download link of hadoop uber jar. 
Besides, I updated the dependency table into tabs for better displaying.
> [hotfix][avro] Link to Hadoop Integration in Avro format documentation

- docs/dev/table/sqlClient.md
- docs/dev/table/sqlClient.zh.md
- flink-table/flink-sql-client/conf/sql-client-defaults.yaml
Add document about sql client's tableau result mode.
> [FLINK-18224][docs] Add document about sql client's tableau result mode

- docs/dev/table/connectors/formats/csv.md
- docs/dev/table/connectors/formats/csv.zh.md
- docs/dev/table/connectors/formats/index.md
- docs/dev/table/connectors/formats/index.zh.md
Add document for new CSV row data format.
- Add csv.md and csv.zh.md
Build locally and validate it works.
> [FLINK-18132][doc] Add documentation for the new CSV format

- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/TableEnvironment.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/LegacySinkTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/table/LegacyTableSourceTest.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/api/internal/TableEnvImpl.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/stream/table/TableSourceTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/runtime/batch/sql/TableEnvironmentITCase.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/utils/MockTableEnvironment.scala
Since we don't have a good alternative solution for easily register user defined source/sink/factory, we need these methods back, for now.
Add the deleted methods back to table env.
Update some tests to call these reintroduced API.
> [1.11][FLINK-16375][table] Reintroduce registerTable[Source/Sink] methods for table env

- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/RemoteInputChannelTest.java
**_(This change picks https://github.com/apache/flink/pull/11924 to release-1.11)_**
This PR fixes the unstable input channel test.
Currently some test might be unstable with specific thread concurrency when we simulating the cases that recycling exclusive and floating buffers in different threads. However, in realistic there should be no such cases. Therefore, we could change the recycling into the same thread.
- c9d0fc65ad8da1f3295d3fb608967ddb471bb370 fixes the unstable tests. …
> [FLINK-17182][network] Fix the unstable input channel test by recycling exclusive and floating buffer in the same thread

- docs/dev/table/connectors/formats/avro.md
- docs/dev/table/connectors/formats/avro.zh.md
Add filesystem option documentation for Avro
> [FLINK-18253][doc][avro] Add filesystem option documentation for Avro

- docs/dev/table/connectors/formats/index.md
- docs/dev/table/connectors/formats/index.zh.md
- docs/dev/table/connectors/formats/parquet.md
- docs/dev/table/connectors/formats/parquet.zh.md
- docs/dev/table/connectors/formats/parquet_zh.md
Add documentation for Parquet format for table file system connector.
> [FLINK-18141][doc][parquet] Add documentation for Parquet format

- flink-core/src/main/java/org/apache/flink/api/java/typeutils/TypeExtractor.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobManagerRunnerImpl.java
- flink-runtime/src/main/java/org/apache/flink/runtime/net/ConnectionUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/registration/RetryingRegistration.java
- flink-runtime/src/main/java/org/apache/flink/runtime/resourcemanager/ResourceManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/SchedulerBase.java
- flink-runtime/src/main/java/org/apache/flink/runtime/security/SecurityUtils.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerConfiguration.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskmanager/Task.java
Downgrades/silences various logging messages to debug to make the logs less noisy, modifies some messages to improve clarify, and even adds a few.
/cc @twalthr for the jank TypeExtractor changes
/cc @rmetzger for the new savepoint logging messages (and the unacceptable excessive dot)
> [FLINK-17977] Decrease log clutter

- docs/dev/table/hive/hive_streaming.md
- docs/dev/table/hive/hive_streaming.zh.md
Add doc for Hive table lookup join.
Add doc
NA
NA
NA
> [FLINK-17836][hive][doc] Add document for Hive dim join

- docs/dev/table/connectors/formats/index.md
- docs/dev/table/connectors/formats/index.zh.md
- docs/dev/table/connectors/formats/orc.md
- docs/dev/table/connectors/formats/orc.zh.md
- docs/dev/table/connectors/formats/parquet.md
- docs/dev/table/connectors/formats/parquet.zh.md
Add documentation for ORC format for filesystem connector.
> [FLINK-18140][doc][orc] Add documentation for ORC format

- flink-connectors/flink-connector-hive/pom.xml
(unchanged backport of https://github.com/apache/flink/pull/11316)
Get release-1.10 building again.
- Excluded javax.jms:jms and pentahoo dependencies.
- Build runs through. …
> [FLINK-16432][build] Fix dependencies in Hive Connector build.

- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/ExecutorNotifierTest.java
The ExecutorNotifierTest#testExceptionInHandler() fails intermittently because the UncaughtExceptionHandler may fire after the ExecutorService has  shutdown. The fix is to ensure only check the exception after the UncaughtExceptionHandler has fired.
918a6d4772d5db916a418daeb06cdbf0eb1bebf3 Wait on a `CountDownLatch` to ensure the `UncaughtExceptionHandler` has fired.
Ran `ExecutorNotifierTest#testExceptionInHandler` in a loop for 10K+ times and did not see failure anymore. Without the patch, the test will fail in less than 500 runs. …
> [FLINK-18322][connector/common][tests] Fix unstable ExecutorNotifierTest#testExceptionInHandler

- docs/ops/deployment/native_kubernetes.zh.md
Translate the native K8s document changes in #12558 to Chinese.
> [FLINK-17976][doc] Synchronize Chinese native Kubernetes document

- flink-end-to-end-tests/test-scripts/test_streaming_file_sink.sh
We observed a case where this test stalled, but no logs were available due to the stalling.
- Use `run_test_with_timeout`
CI
> [FLINK-18291][e2e] Introduce timeout into Streaming File Sink s3 test

- flink-connectors/flink-sql-connector-hive-1.2.2/src/main/resources/META-INF/NOTICE
- flink-connectors/flink-sql-connector-hive-2.2.0/src/main/resources/META-INF/NOTICE
- flink-dist/src/main/resources/META-INF/NOTICE
- flink-kubernetes/src/main/resources/META-INF/NOTICE
- flink-table/flink-table-planner-blink/src/main/resources/META-INF/NOTICE
These can all be verified by checking the shade-plugin output.
> [FLINK-18317][legal] Fix various licensing issues

- flink-end-to-end-tests/flink-metrics-availability-test/src/test/java/org/apache/flink/metrics/tests/MetricsAvailabilityITCase.java
Fixes a typo. I will fix the commit message when merging
> [hotfix][e2e] Fix package name in MetricsAvailabilityITCase

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java
Don't call `System.exit` on `CheckpointCoordinator` failure if it is shut down.
_backport to 1.11: #12698_
> [FLINK-18290][checkpointing] Fail job on checkpoint future failure instead of System.exit

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java
Backport of #12670 to 1.11.
Don't call `System.exit` on `CheckpointCoordinator` failure if it is shut down.
> [FLINK-18290][checkpointing] (Backport to 1.11) Don't System.exit on CheckpointCoordinator failure if it is shut down

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliClient.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliStrings.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/SqlCommandParser.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/SqlCommandParserTest.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/utils/SqlParserHelper.java
Fix the issue that ALTER VIEW operation is not supported in SQL client
- Support ALTER VIEW in SQL client
- Add test
Added test case
> [FLINK-18300][sql-client] SQL Client doesn't support ALTER VIEW

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointITCase.java
UnalignedCheckpointITCase was unstable before (~2 of 100 runs on Azure failed) and we investigated root causes. After FLINK-18238 and FLINK-18290 got merged, we could not observe any issues after 300 runs.
- Reenable ITCase.
Not applicable. …
> [FLINK-17768][tests] Reenable UnalignedCheckpointITCase.

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/CodeGeneratorContext.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/ExprCodeGenerator.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/GenerateUtils.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/ProjectionCodeGenerator.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/agg/AggsHandlerCodeGenerator.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/agg/DistinctAggCodeGen.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/agg/batch/HashAggCodeGenHelper.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/AggregateITCase.scala
Split code for AggsHandlerCodeGenerator
Split code for AggsHandlerCodeGenerator
* AggrateITCase.testSplitAggsHandler …
> [BP-1.11][FLINK-16589] Split code for AggsHandlerCodeGenerator

- flink-java/src/test/java/org/apache/flink/api/java/utils/CollectionExecutorTest.java
I think this is caused by "[FLINK-18352] Make DefaultClusterClientServiceLoader/DefaultExecutorServiceLoader thread-safe", commit id: eeeff7a5. 
- Use `new DefaultExecutorServiceLoader()` instead of `DefaultExecutorServiceLoader.INSTANCE` which has been removed in eeeff7a5.
N/A.
- Does this …
> [FLINK-18411][tests] Fix CollectionExecutorTest failed to compiled in release-1.11

- docs/dev/table/hive/hive_dialect.md
- docs/dev/table/hive/hive_dialect.zh.md
Update hive dialect doc to mention the views created in Flink cannot be queried in Hive, and ALTER VIEW not supported in SQL client.
- Update doc
NA
NA
NA
> [FLINK-18313][doc] Update Hive dialect doc about VIEW

- docs/index.md
- docs/index.zh.md
- docs/release-notes/flink-1.11.md
- docs/release-notes/flink-1.11.zh.md
Add release notes for Flink 1.11
> [FLINK-18349][docs] Add release notes for Flink 1.11

- docs/dev/table/connectors/formats/parquet.zh.md
Translate "Parquet Format" page into Chinese.
The page url is https://ci.apache.org/projects/flink/flink-docs-master/zh/dev/table/connectors/formats/parquet.html
The markdown file is located in flink/docs/dev/table/connectors/formats/parquet.zh.md
- Translate `flink/docs/dev/table/connectors/formats/parquet.zh.md`.
- Does this …
> [FLINK-18394][docs-zh] Translate "Parquet Format" page into Chinese

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointFailureManager.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointFailureManagerTest.java
Currently, if failureManager is notified about a failure that it has already seen after a successful checkpoint, it will count it again.
This PR introduces `lastSucceededCheckpointId` field to prevent it.
Added unit test: `CheckpointFailureManagerTest.testIgnoresPastCheckpoints`
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: yes
> [FLINK-18336][checkpointing] Ignore failures of past checkpoints in CheckpointFailureManager

- flink-table/flink-table-common/src/main/java/org/apache/flink/table/api/TableSchema.java
- flink-table/flink-table-common/src/test/java/org/apache/flink/table/api/TableSchemaTest.java
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/sinks/TableSinkUtils.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/TableScanTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/TableSinkTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/table/validation/LegacyTableSinkValidationTest.scala
Fix the confusing exception message when INSERT INTO mismatch types for empty char
- Use `LogicalType#asSummaryString` instead of `LogicalType#asSerializableString` when exception message and logging
- Added unit tests to verify the exception messages. …
> [FLINK-18462][table-planner-blink] Improve the exception message when INSERT INTO mismatch types for empty char

- docs/dev/table/streaming/match_recognize.md
*Fix invalid links in "Detecting Patterns" page of "Streaming Concepts"*
Fix invalid links in "Detecting Patterns" page of "Streaming Concepts" 
The page location is : `flink/docs/dev/table/streaming/match_recognize.md`.
The page url is: [Patterns in Tables](https://ci.apache.org/projects/flink/flink-docs-master/dev/table/streaming/match_recognize.html#time-attributes).
The Invalid link is [interval joins](https://ci.apache.org/projects/flink/flink-docs-master/dev/table/streaming/match_recognize.html#joins), however, the cerrect link target should be linked as  [interval joins](https://ci.apache.org/projects/flink/flink-docs-master/dev/table/streaming/joins.html#interval-joins)
The corresponding Chinese page will be repaired , which is  reported …
> [FLINK-18457][docs] Fix invalid links in "Detecting Patterns" page of "Streaming Concepts"

- docs/learn-flink/fault_tolerance.md
- docs/learn-flink/fault_tolerance.zh.md
Update Prefer tag in documentation 'Fault Tolerance training lesson' according to [Prefer Reminder](http://apache-flink-mailing-list-archive.1008284.n3.nabble.com/Reminder-Prefer-link-tag-in-documentation-td42362.html) .The markdown file location is:  flink/docs/learn-flink/fault_tolerance.md
- *Update Prefer tag in documentation 'flink/docs/learn-flink/fault_tolerance.md'* …
> [FLINK-18422][docs] Update Prefer tag in documentation 'Fault Tolerance training lesson'

- docs/release-notes/flink-1.11.md
- docs/release-notes/flink-1.11.zh.md
This is just a doc update to add missing release notes.
> [FLINK-18173][docs] Update missing release notes for flink-json and flink-csv packaging

- docs/dev/table/connectors/blackhole.zh.md
[FLINK-18387] Translate "BlackHole SQL Connector" page into Chinese
> [FLINK-18387] Translate "BlackHole SQL Connector" page into Chinese

- docs/dev/table/functions/systemFunctions.md
- docs/dev/table/functions/systemFunctions.zh.md
*Add doucument for '%' module function.*
> [FLINK-18486][docs]add document for '%' module function.

- pom.xml
Update japicmp configuration for 1.11.0
> Update japicmp configuration for 1.11.0

- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/runtime/batch/sql/TableEnvironmentITCase.scala
This PR fixes and reenables TableEnvironmentITCase#testStatementSetWithSameSinkTableNames. 
See commit message.
I run the test ~1000 times without a failure …
> [FLINK-18369] Fix instable TableEnvironmentITCase#testStatementSetWithSameSinkTableNames

- docs/monitoring/metrics.md
Fix the format issue for metrics web page in link https://ci.apache.org/projects/flink/flink-docs-release-1.11/monitoring/metrics.html#checkpointing
Fix the metrics.md for adjusting the format.
build the docs locally to verify the metrics web page.  …
> [FLINK-18591][metrics][documentation] Fix the format issue for metrics web page

- flink-connectors/flink-connector-elasticsearch6/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSink.java
- flink-connectors/flink-connector-elasticsearch6/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6DynamicSinkITCase.java
- flink-connectors/flink-connector-elasticsearch7/src/test/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch7DynamicSinkITCase.java
Fix index id in ElasticSearch6 DynamicTableSink
> [BP-1.11][FLINK-18583][elasticsearch] Fix index id in ElasticSearch6 DynamicTableSink

- docs/dev/batch/connectors.md
- docs/dev/batch/connectors.zh.md
Remove some obsolete doc of hive connector.
- Update doc
N/A
N/A
N/A
> [FLINK-18644][doc][hive] Remove obsolete hive connector docs

- docs/_includes/generated/core_configuration.html
- docs/_includes/generated/expert_class_loading_section.html
- flink-clients/src/main/java/org/apache/flink/client/ClientUtils.java
- flink-core/src/main/java/org/apache/flink/configuration/CoreOptions.java
- flink-core/src/main/java/org/apache/flink/util/ChildFirstClassLoader.java
- flink-core/src/main/java/org/apache/flink/util/FlinkUserCodeClassLoader.java
- flink-core/src/test/java/org/apache/flink/core/plugin/TemporaryClassLoaderContextTest.java
- flink-core/src/test/java/org/apache/flink/util/FlinkUserCodeClassLoaderTest.java
- flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/AvroKryoClassloadingTest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/dispatcher/Dispatcher.java
- flink-runtime/src/main/java/org/apache/flink/runtime/execution/librarycache/BlobLibraryCacheManager.java
- flink-runtime/src/main/java/org/apache/flink/runtime/execution/librarycache/FlinkUserCodeClassLoaders.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/NettyBufferPool.java
- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/JobManagerSharedServices.java
- flink-runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskExecutor.java
- flink-runtime/src/test/java/org/apache/flink/runtime/classloading/ClassLoaderTest.java
- flink-state-backends/flink-statebackend-rocksdb/src/test/java/org/apache/flink/contrib/streaming/state/RocksDbMultiClassLoaderTest.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/local/ExecutionContext.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/local/ExecutionContextTest.java
1.10 Port of #12446.
also ports #12563 to reduce netty overhead and direct memory allocation timeout in some tests
> [FLINK-16225] Implement user class loading exception handler

- docs/ops/upgrading.md
- docs/ops/upgrading.zh.md
This is a simple documentation update. The documented behaviour is ensured via all migration tests that we have in Flink.
- If yes, how is the feature documented? (not applicable / **docs** / JavaDocs / not …
> [FLINK-18671][docs] Update upgrade compatibility table for 1.11.0

- docs/dev/table/types.md
- docs/dev/table/types.zh.md
*Fix document error.*
- *Fix document error*
> [FLINK-18667][docs] Data types documentation misunderstand users

- flink-table/flink-table-api-java-bridge/pom.xml
Currently, adding `flink-table-api-java-bridge_2.11` to a Flink project kills the IDE logging. The root cause is that `flink-table-api-java-bridge_2.11` has a dependency to `org.apache.flink:flink-streaming-java_2.11:test-jar:tests`, which contains a "log4j2-test.properties" file. I think this is a mistake in commit 91557c83447444ecfbeba3e4c58297908940834a that the `flink-streaming-java_2.11:test-jar` is not in test scope. 
- Update pom.xml of `flink-table-api-java-bridge` to use test scope for `flink-streaming-java_2.11:test-jar`.
I don't know how to add a proper test for this. But I manually tests it and the logging works well now with this fix.  …
> [FLINK-18697][table-api] Add the missing test scope to the flink-streaming-java_2.11:test-jar dependency

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/serialization/DynamoDBStreamsSchema.java
This pull request resolves an exception while using the provided `DynamoDBStreamsSchema` class in the Flink Kinesis Connector.
- Replace `ObjectMapper` instance with `RecordObjectMapper` in `DynamoDBStreamsSchema`
> [FLINK-11547][flink-connector-kinesis] Fix JsonMappingException in DynamoDBStreamsSchema

- docs/learn-flink/event_driven.zh.md
fix some translated files without anchor titles causing the problems that links may not works.
fix some translated files without anchor titles causing the problems that links may not works.
Facing a title anchor issue when translating file streaming_analytics.zh.md, the link may always useless due to no anchor issue bundled to specified title.
- add anchor to streaming_analtics.zh.md file and title `Side Outputs`.
Docs, docs. So no tests should be impacted.
No
yes, fix the docs.
> [Hotfix] fix file event_driven.zh.md did't adding title anchor.

- docs/dev/table/sqlClient.md
- docs/dev/table/sqlClient.zh.md
Removes the beta tag from SQL Client page and updates the note to better reflect community priorities.
- Update docs
no
> [FLINK-18730][docs] Remove Beta tag from SQL Client docs

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/BufferManager.java
Assuming two remote channels with buffer managers as listeners in LocalBufferPool, the deadlock happens as follows:
1. While the Canceler thread calling ch1#releaseAllResources, it will occupy the bufferQueue lock of bm1 and try to call bm2#notifyBufferAvailable.
2. While the task thread recycling exclusive buffer for ch2, then it will occupy the bufferQueue lock of bm2 and try to call bm1#notifyBufferAvailable.
3. These two threads will both occupy the respective bm's bufferQueue lock and wait for other side's bufferQueue lock to cause deadlock.
Regarding the solution, we can check the released state outside of bufferQueue lock in BufferManager#notifyBufferAvailable to return immediately.
check the released state outside of bufferQueue lock in BufferManager#notifyBufferAvailable to …
> [FLINK-18595][network] Fix the deadlock of concurrently recycling buffer and releasing input channel

- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/aggregate/BytesHashMap.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/util/LazyMemorySegmentPool.java
In BytesHashMap#growAndRehash we have the following code.
```java
List<MemorySegment> newBucketSegments = new ArrayList<>(required);
try {
int numAllocatedSegments = required - memoryPool.freePages();
if (numAllocatedSegments > 0) {
throw new MemoryAllocationException();
}
int needNumFromFreeSegments = required - newBucketSegments.size();
for (int end = needNumFromFreeSegments; end > 0; end--) {
newBucketSegments.add(memoryPool.nextSegment());
}
setBucketVariables(newBucketSegments);
} catch (MemoryAllocationException e) {
LOG.warn("BytesHashMap can't allocate {} pages, and now used {} pages",
required, reservedNumBuffers);
throw new EOFException();
}
```
Newly allocated memory segments are temporarily stored in newBucketSegments before giving to the hash table. But if a …
> [FLINK-18668][table-runtime-blink] BytesHashMap#growAndRehash should release newly allocated segments before throwing the exception

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/BufferManager.java
Assuming two remote channels with buffer managers as listeners in LocalBufferPool, the deadlock happens as follows:
While the Canceler thread calling ch1#releaseAllResources, it will occupy the bufferQueue lock of bm1 and try to call bm2#notifyBufferAvailable.
While the task thread recycling exclusive buffer for ch2, then it will occupy the bufferQueue lock of bm2 and try to call bm1#notifyBufferAvailable.
These two threads will both occupy the respective bm's bufferQueue lock and wait for other side's bufferQueue lock to cause deadlock.
Regarding the solution, we can check the released state outside of bufferQueue lock in BufferManager#notifyBufferAvailable to return immediately.
check the released state outside of bufferQueue lock in BufferManager#notifyBufferAvailable to return …
> [FLINK-18595][network] Fix the deadlock of concurrently recycling buffer and releasing input channel 

- docs/monitoring/metrics.md
- docs/monitoring/metrics.zh.md
This is a simple documentation update.
> [hotfix][docs] Update currentInputNWatermark metrics docs including N-ary operator

- flink-core/src/main/java/org/apache/flink/api/common/typeinfo/TypeInfoFactory.java
- flink-core/src/main/java/org/apache/flink/api/java/typeutils/TypeExtractionUtils.java
- flink-core/src/main/java/org/apache/flink/api/java/typeutils/TypeExtractor.java
- flink-core/src/test/java/org/apache/flink/api/java/typeutils/PojoParametrizedTypeExtractionTest.java
- flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/typeutils/AvroTypeInfo.java
This PR is a continuation of #8357 See the other PR for comments and description.
>  [FLINK-12175] Change filling of typeHierarchy in analyzePojo, for correctly creating fields TypeInfo

- docs/dev/table/connectors/formats/csv.md
- docs/dev/table/connectors/formats/csv.zh.md
* This pull request Fix csv format option specification in docs.
- update file csv.md and csv.zh.md.
> [hotfix][csv][docs] Fix csv format option specification in docs.

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaChangelogTableITCase.java
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/rules/physical/stream/MiniBatchIntervalInferRule.scala
- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/factories/TestValuesRuntimeFunctions.java
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/MiniBatchIntervalInferTest.xml
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/MiniBatchIntervalInferTest.scala
Currently, the `MiniBatchIntervalInferRule` doesn't take FLIP-95 source into account, therefore there's no `MiniBatchAssigner` node generated, and the minibatch will never be triggered. 
- Add `MiniBatchAssigner` when matches `StreamExecTableSourceScan` in `MiniBatchIntervalInferRule`.
- Enable minibatch in `KafkaChangelogTableITCase#testKafkaDebeziumChangelogSource` to reproduce this problem. 
- Cover FLIP-95 sources in `MiniBatchIntervalInferTest`. …
> [FLINK-18769][table-planner-blink] Fix MiniBatch doesn't work with FLIP-95 source

- docs/monitoring/metrics.md
There's typo issue that Java code in Scala snippet, just replace with Scala code.
> [hotfix][docs]fix java code in scala snippet

- docs/dev/stream/side_output.md
*Fix the link-tags in the 'Side Outputs' page of 'DataStream API'*
*Fix the link-tags in the 'Side Outputs' page of 'DataStream API'*
*Fix the link-tags in the 'Side Outputs' page of 'DataStream API'*
> [hotfix][docs] Fix the link-tags in the 'Side Outputs' page of 'DataStream API'

- docs/dev/table/catalogs.md
- docs/dev/table/catalogs.zh.md
- docs/dev/table/hive/index.md
- docs/dev/table/hive/index.zh.md
Update doc and suggest not to manually set Hive version for HiveCatalog. Strange errors can happen if user sets an incorrect version.
- Update doc
NA
NA
NA
> [FLINK-18678][hive][doc] Update doc about setting hive version

- flink-python/pyflink/table/table_environment.py
- flink-python/pyflink/table/tests/test_table_environment_api.py
Support getting a Table from a DataStream, and converting a Table into DataStream.
- add from_data_stream()/ to_append_stream()/to_retract_stream() interface for StreamTableEnvironment.
This change has test case covered by test_from_data_stream() / test_to_append_stream()/ test_to_retract_stream() in test_table_environment_api.py.
- …
> [FLINK-18874][python] Support conversion between Table and DataStream.

- flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/maxwell/MaxwellJsonDeserializationSchema.java
- flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/maxwell/MaxwellJsonFormatFactory.java
- flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/maxwell/MaxwellJsonSerializationSchema.java
- flink-formats/flink-json/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
- flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/maxwell/MaxwellJsonFormatFactoryTest.java
- flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/maxwell/MaxwellJsonSerDerTest.java
- flink-formats/flink-json/src/test/resources/maxwell-data.txt
*support maxwell-json for Maxwell binlog collector*
- *add DeserializationSchema for deserialize byte[]*
- *add SerializationSchema for serialize data to byte[]*
- *add formatfactory for DeserializationSchema&SerializationSchema*
- *Added java tests for deserialize byte[] from table source & serialize data to byte[] into table sink*
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: ( no ) …
> [FLINK-18844][json][maxwell] Support maxwell-json format to read Maxwell changelogs

- flink-runtime/src/main/java/org/apache/flink/runtime/blob/BlobServer.java
Small adjustment to the `BlobServer` to not move a file while it has an open `FileInputStream`, so that tests like the `BlobServerPutTest` can succeed on Windows.
> [FLINK-18876][coordination] Move file after stream was closed

- flink-core/src/main/java/org/apache/flink/core/plugin/PluginLoader.java
- flink-core/src/main/java/org/apache/flink/util/ChildFirstClassLoader.java
- flink-core/src/main/java/org/apache/flink/util/FlinkUserCodeClassLoader.java
- flink-runtime/src/main/java/org/apache/flink/runtime/execution/librarycache/FlinkUserCodeClassLoaders.java
Enables parallel user-code and plugin class loader.
- Mark class loaders as parallel usable.
- Adjust locking in user class loaders (plugin already used the appropriate method). 
No new test (test ideas welcome), covered by all IT and e2e tests. …
> [FLINK-18773][runtime] Enables parallel user-code and plugin class loader.

- docs/concepts/timely-stream-processing.md
- docs/concepts/timely-stream-processing.zh.md
- docs/dev/connectors/jdbc.md
- docs/dev/connectors/jdbc.zh.md
- docs/dev/connectors/kafka.md
- docs/dev/stream/sources.md
- docs/dev/stream/sources.zh.md
- docs/dev/stream/state/custom_serialization.md
- docs/dev/stream/state/custom_serialization.zh.md
- docs/dev/table/common.md
- docs/dev/table/connect.md
- docs/dev/table/connect.zh.md
- docs/dev/table/hive/hive_catalog.md
- docs/dev/table/hive/hive_catalog.zh.md
- docs/dev/table/sourceSinks.md
- docs/dev/table/sourceSinks.zh.md
- docs/dev/table/types.md
- docs/dev/table/types.zh.md
- docs/ops/config.md
- docs/ops/config.zh.md
- docs/redirects/java-quickstart.md
- docs/redirects/scala-quickstart.md
Fix typo for multiple doc files
> [hotfix] [docs]  Fix typo for multiple doc files

- flink-annotations/src/main/java/org/apache/flink/annotation/docs/Documentation.java
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/ElasticsearchApiCallBridge.java
- flink-connectors/flink-connector-elasticsearch-base/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/ElasticsearchOptions.java
- flink-connectors/flink-connector-elasticsearch6/src/main/java/org/apache/flink/streaming/connectors/elasticsearch6/ElasticsearchSink.java
- flink-connectors/flink-connector-elasticsearch7/src/main/java/org/apache/flink/streaming/connectors/elasticsearch7/ElasticsearchSink.java
- flink-connectors/flink-sql-connector-hbase/src/main/resources/hbase-default.xml
- flink-core/src/main/java/org/apache/flink/api/common/typeinfo/Types.java
- flink-core/src/main/java/org/apache/flink/api/common/typeutils/TypeSerializerConfigSnapshot.java
- flink-core/src/main/java/org/apache/flink/api/common/typeutils/TypeSerializerSnapshot.java
- flink-core/src/main/java/org/apache/flink/api/java/typeutils/MissingTypeInfo.java
- flink-core/src/main/java/org/apache/flink/api/java/typeutils/runtime/PojoComparator.java
- flink-examples/flink-examples-batch/src/main/java/org/apache/flink/examples/java/distcp/DistCp.java
- flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/TimestampFormat.java
- flink-java/src/main/java/org/apache/flink/api/java/operators/DataSink.java
- flink-libraries/flink-gelly/src/main/java/org/apache/flink/graph/library/metric/directed/EdgeMetrics.java
- flink-ml-parent/flink-ml-lib/src/main/java/org/apache/flink/ml/common/linalg/DenseMatrix.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rpc/FencedRpcEndpoint.java
- flink-runtime/src/test/java/org/apache/flink/runtime/dispatcher/DispatcherTest.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/sink/WriteFormatAsCsv.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/functions/sink/WriteFormatAsText.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/TimerSerializer.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/types/logical/DistinctType.java
- flink-table/flink-table-common/src/test/java/org/apache/flink/table/catalog/CatalogTest.java
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/functions/utils/AggSqlFunction.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/batch/BatchExecGroupAggregateBase.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/batch/BatchExecWindowAggregateBase.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/window/internal/MergingWindowSet.java
- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/test/util/SecureTestEnvironment.java
- flink-yarn/src/main/java/org/apache/flink/yarn/YarnClusterDescriptor.java
Fixed multiple typos in log message and code comments in the codebase.
>  [hoxfix] [docs] Fix typo in log message and code comments 

- flink-python/pyflink/datastream/data_stream.py
- flink-python/pyflink/datastream/tests/test_data_stream.py
- flink-python/src/main/java/org/apache/flink/datastream/runtime/operators/python/DataStreamTwoInputPythonStatelessFunctionOperator.java
This pull request supports key_by on Python `ConnectedStreams`.
- Add key_by on Python `ConnectedStreams`.
- Refactor `DataStreamTwoInputPythonStatelessFunctionOperator` to support keyed `ConnectedStreams`.
- Added `test_key_by_on_connect_stream` integration tests in test_data_stream …
> [FLINK-18966][python] Support key_by() on ConnectedStreams for Python DataStream API

- flink-python/pyflink/datastream/connectors.py
- flink-python/pyflink/datastream/data_stream.py
- flink-python/pyflink/datastream/tests/test_connectors.py
Support JDBC connector for Python DataStream API.
Added a new SinkFunction named JdbcSink.
This pull request has test case covered by test_jdbc_sink() in FlinkJdbcSinkTest in test_connectors.py.
- If yes, how is the feature documented? ( not documented)
> [FLINK-18944][python] Support JDBC connector for Python DataStream API.

- docs/monitoring/checkpoint_monitoring.md
- docs/monitoring/checkpoint_monitoring.zh.md
fix typo in checkpoint_monitoring doc
> [hotfix] [docs] Fix typo in checkpoint monitoring doc

- flink-python/docs/index.rst
- flink-python/pyflink/datastream/__init__.py
- flink-python/pyflink/datastream/data_stream.py
- flink-python/pyflink/datastream/functions.py
This pull request update the Sphinx doc for Python DataStream API.
- Update the Sphinx doc for Python DataStream API.
- Fix python doc problems, e.g., fix Unexpected indentation problems.
This change is already covered by existing tests, such as sphinx checks.
> [FLINK-18985][python] Update the Sphinx doc for Python DataStream API.

- docs/dev/table/hive/hive_dialect.zh.md
Translate "Hive Dialect" page of "Hive Integration" into Chinese
- Translate "Hive Dialect" page of "Hive Integration" into Chinese
> [FLINK-18930][docs-zh] Translate "Hive Dialect" page of "Hive Integration" into Chinese

- docs/dev/migration.zh.md
*Translate the 'API Migration Guides' page of 'Application Development' into Chinese*
*Translate the 'API Migration Guides' page of 'Application Development' into Chinese*
- *The page url is: https://ci.apache.org/projects/flink/flink-docs-release-1.11/dev/migration.html*
- *The markdown file is located in flink/docs/dev/migration.zh.md*
This change is a pure translation work. …
> [FLINK-18854][docs-zh] Translate the 'API Migration Guides' page of 'Application Development' into Chinese

- flink-core/src/main/java/org/apache/flink/api/java/typeutils/runtime/PojoSerializer.java
Currently PojoSerializer.createInstance() uses reflection call to create a class instance. As this method is called on each stream element on deserialization, reflection overhead can become noticeable in serialization-bound cases when:
* Pojo class is small, so instantiation is noticeable.
* The job is not having heavy CPU-bound event processing.
See this flamegraph built for flink-benchmarks/SerializationFrameworkMiniBenchmarks.serializerPojo benchmark:
This Reflection.getCallerClass method consumes a lot of CPU, mostly doing a security check if we allowed to do this reflective call.
There is no true reason to perform this check on each deserializing event, so to speed things up we can just cache the constructor using MetaHandle, so this check will be performed only once. With this tiny …
> [FLINK-19052] [serialization] add constructor cache in PojoSerializer

- docs/monitoring/historyserver.zh.md
*Translate the 'History Server' page of 'Debugging & Monitoring' into Chinese*
*Translate the 'History Server' page of 'Debugging & Monitoring' into Chinese*
- The page url is https://ci.apache.org/projects/flink/flink-docs-release-1.11/zh/monitoring/historyserver.html
- The markdown file is located in flink/docs/monitoring/historyserver.zh.md
*This change is a pure documentation translation.*
- Does …
> [FLINK-18973][docs-zh] Translate the 'History Server' page of 'Debugging & Monitoring' into Chinese

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/table/catalog/hive/HiveCatalog.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/catalog/AbstractJdbcCatalog.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/catalog/GenericInMemoryCatalog.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/Catalog.java
Revert the modification of Catalog.listPartitions for version Compatibility.
> [FLINK-18900][table] Revert the modification of Catalog.listPartitions

- flink-runtime-web/web-dashboard/src/app/pages/job/configuration/job-configuration.component.ts
> [FLINK-18987][WebUI] Sort user configuration entries

- docs/dev/execution_plans.zh.md
Translate "Execution Plans" page of "Managing Execution" into Chinese.
The page url is https://ci.apache.org/projects/flink/flink-docs-master/zh/dev/execution_plans.html
The markdown file is located in `flink/docs/dev/execution_plans.zh.md`
Translate `flink/docs/dev/execution_plans.zh.md` …
> [FLINK-18860][docs-zh] Translate "Execution Plans" page of "Managing Execution" into Chinese

- flink-runtime-web/src/test/resources/rest_api_v1.snapshot
- flink-runtime-web/web-dashboard/src/app/pages/job/checkpoints/job-checkpoints.component.html
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/checkpoints/CheckpointConfigHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/checkpoints/CheckpointConfigInfo.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/messages/checkpoints/CheckpointConfigInfoTest.java
* Show in web ui if unaligned checkpoints are enabled.
* Adds unaligned checkpoint config to REST endpoint, and web ui.
- Dependencies (does it add or upgrade a dependency): (yes / no) No
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no) No
- The serializers: (yes / no / don't know) No
- The runtime per-record code paths (performance sensitive): (yes / no / don't know) No
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / no / don't know) No
- The S3 file system connector: (yes / no / don't know) No
- Does this pull request introduce a new feature? (yes / no) No …
> [FLINK-18694] Add unaligned checkpoint config to web ui

- docs/dev/table/connectors/formats/canal.md
- docs/dev/table/connectors/formats/canal.zh.md
- flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/canal/CanalJsonFormatFactory.java
- flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/canal/CanalJsonSerializationSchema.java
- flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/canal/CanalJsonFormatFactoryTest.java
- flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/canal/CanalJsonSerDeSchemaTest.java
*Support serialization for canal-json format*
- add SerializationSchema for serialize data to byte[]
- add formatfactory for SerializationSchema
- Added java tests for  serialize data to byte[] into table sink
> [FLINK-18824][format][canal] Support serialization for canal-json format

- flink-filesystems/flink-s3-fs-hadoop/src/test/java/org/apache/flink/fs/s3hadoop/HadoopS3RecoverableWriterITCase.java
Fix the unstable case HadoopS3RecoverableWriterITCase#testCleanupRecoverableState.
Try multi-times to verify that the file was deleted at last.
> [FLINK-17637][connector] Fix the unstable case HadoopS3RecoverableWriterITCase#testCleanupRecoverableState

- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/sinks/CsvTableSinkFactoryBase.java
fix parameter naming error
fix parameter naming error
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: ( no )
> [FLINK-19170] fix parameter naming error

- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/runtime/aggregate/ProcTimeBoundedRangeOver.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/over/ProcTimeRangeBoundedPrecedingFunction.java
fix typos in ProcTimeRangeBoundedPrecedingFunction & ProcTimeBoundedRangeOver
> [hotfix][typo] fix typos in ProcTimeRangeBoundedPrecedingFunction & ProcTimeBoundedRangeOver

- docs/_includes/generated/rest_v1_dispatcher.html
Update rest_v1_dispathcer.html
Update rest_v1_dispathcer.html by running 'mvn package -Dgenerate-rest-docs -pl flink-docs -am -nsu -DskipTests'
> [Hotfix][Docs] Update rest_v1_dispathcer.html

- docs/_config.yml
Update version to 1.10.2 for release-1.10.
> [FLINK-FLINK][docs] Update the version in docs/_config.yml to be the latest released minor version

- flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/CsvFileSystemFormatFactory.java
- flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/CsvRowDataDeserializationSchema.java
- flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/CsvRowDataSerializationSchema.java
- flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/CsvToRowDataConverters.java
- flink-formats/flink-csv/src/main/java/org/apache/flink/formats/csv/RowDataToCsvConverters.java
- flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonRowDataDeserializationSchema.java
- flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonRowDataSerializationSchema.java
- flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonToRowDataConverters.java
- flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/RowDataToJsonConverters.java
This pull request makes the rowdata converters public. That way third party projects can utilize the converter to serialize and deserialize between csv/json `JsonNode` and `Rowdata`.
- Refactor json/csv RowData runtime converters out to a class
- Make the rowdata converter public
- Add `static` to `RowDataToCsvConverter` 
This change is already covered by existing tests, such as `JsonRowDeserializationSchemaTest`, etc.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: …
> [FLINK-19098][format] Make row data converters public

- flink-end-to-end-tests/flink-tpcds-test/README.md
- flink-end-to-end-tests/flink-tpcds-test/tpcds-tool/README.md
- flink-end-to-end-tests/flink-tpcds-test/tpcds-tool/data_generator.sh
* This pull request adding readme.md for TPC-DS tools to help user understand the test better.
- Add readme.md in `tpcds-tool`
- Minor cleanup in `tpcds-tool/data_generator.sh `
> [FLINK-18759][tests] Add readme.md for TPC-DS tools

- docs/dev/table/functions/systemFunctions.md
- docs/dev/table/functions/systemFunctions.zh.md
Correct the example of FROM_UNIXTIME function in document
> [FLINK-19433] [docs] Correct example of FROM_UNIXTIME function in document

- flink-libraries/flink-state-processing-api/src/main/java/org/apache/flink/state/api/runtime/SavepointEnvironment.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/Execution.java
- flink-runtime/src/main/java/org/apache/flink/runtime/executiongraph/ExecutionAttemptID.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/NettyMessage.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTestingUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/AllVerticesIteratorTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/executiongraph/ExecutionGraphConstructionTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/JobMasterTest.java
Add JobID to ExecutionAttemptID
Add JobID to ExecutionAttemptID
> [FLINK-19264][runtime] Add JobID to ExecutionAttemptID

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointITCase.java
For yet unknown reason, a quick checkpoint during recovery of unaligned checkpoint causes the checkpoint to not progress. Since the checkpoint timeout is longer than the test timeout, the test timeout hit first.
This commit decreases checkpoint timeout to avoid livelocking in UnalignedCheckpointITCase.
- Decreases checkpoint timeout to avoid livelocking in UnalignedCheckpointITCase.
Fix for test. …
> [FLINK-19027][tests] Decrease checkpoint timeout to avoid livelocking in UnalignedCheckpointITCase.

- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/factories/datagen/RandomGeneratorVisitor.java
- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/factories/datagen/types/DecimalDataRandomGenerator.java
- flink-table/flink-table-api-java-bridge/src/test/java/org/apache/flink/table/factories/DataGenTableSourceFactoryTest.java
- flink-table/flink-table-api-java-bridge/src/test/java/org/apache/flink/table/factories/datagen/types/DecimalDataRandomGeneratorTest.java
DataGen source DECIMAL always returns null
Use longs as the base generator to avoid precision issues. 
UT
No
> [FLINK-19496][table] DataGen source DECIMAL always returns null

- flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/typeutils/AvroSchemaConverter.java
- flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/typeutils/AvroSchemaConverterTest.java
Fix a bug in `AvroSchemaConverter.convertToSchema`, it will throw `SchemaParseException` when there are multiple row type fields and the field names in each row type are different. the `rowTypeCounter` will be duplicate which causes this problem.
- Concating parant and child name as row name to replace `rowTypeCounter`.
- Set top name to `record` in `AvroSchemaConverter.convertToSchema`.
- Construct a logical type with multiple row type fields and the field names in each row type are different.
- Invoke method `AvroSchemaConverter.convertToSchema` and return `Schema`.
- No `SchemaParseException` should be thrown during execute `Schema.toString()` and check the result is as expected. …
> [FLINK-19291][Formats] Fix `SchemaParseException` when use `AvroSchemaConverter` converts flink logical type 

- flink-formats/flink-avro/src/main/java/org/apache/flink/formats/avro/typeutils/AvroSchemaConverter.java
- flink-formats/flink-avro/src/test/java/org/apache/flink/formats/avro/typeutils/AvroSchemaConverterTest.java
This is a cherry pick to release-1.11 branch.
> [BP-1.11][FLINK-19291][avro] Fix exception for AvroSchemaConverter#convertToSchema when RowType contains multiple row fields

- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/table/JdbcDynamicOutputFormatBuilder.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/table/UnsignedTypeConversionITCase.java
Fix ArrayIndexOutOfBoundsException when executing DELETE statement in JDBC upsert sink
- Fix `JdbcDynamicOutputFormatBuilder#createDeleteExecutor`
- Added a test which can reproduce this problem. …
> [FLINK-19423][jdbc] Fix ArrayIndexOutOfBoundsException when executing DELETE statement in JDBC upsert sink

- flink-runtime/src/main/java/org/apache/flink/runtime/util/EnvironmentInformation.java
Sensitive informations from configuration files are already masked. Port the same behaviour to the logging of program arguments.
*(or)*
*(or)*
This change added tests and can …
> FLINK-19523: Hide sensitive info from log

- flink-end-to-end-tests/run-nightly-tests.sh
The test is constantly failing.
> [FLINK-19619][e2e] Temporarily disable the pubsub test

- docs/dev/packaging.zh.md
Translate "Program Packaging" page into Chinese.
The page url is https://ci.apache.org/projects/flink/flink-docs-master/zh/dev/packaging.html
The markdown file is located in flink/docs/dev/packaging.zh.md
Translate "Program Packaging" page into Chinese.
- The S3 …
> [FLINK-19420][docs-zh] Translate "Program Packaging" page into Chinese

- docs/dev/table/sql/index.zh.md
- docs/dev/table/streaming/time_attributes.zh.md
Fix some typos in Chinese version of document.
Signed-off-by: Xiaoguang Sun <sunxiaoguang@zhihu.com>
> [hotfix][docs]Fix some typos in docs

- flink-runtime/src/test/java/org/apache/flink/runtime/testutils/CommonTestUtils.java
- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/test/util/MiniClusterPipelineExecutorServiceLoader.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointCompatibilityITCase.java
Fixes UnalignedCheckpointCompatibilityITCase.test:97->runAndTakeSavepoint: "Not all required tasks are currently running.", which may be caused when deploying takes longer than expected, such that stopWithSavepoint is called before everything is running.
- Allow savepoints to be used in MiniCluster.
- Use JobDetailsInfo to ensure that job and all tasks are running.
Fixes test failure. …
> [FLINK-19585][tests] Waiting for job to run before savepointing in UnalignedCheckpointCompatibilityITCase.

- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/FlinkStandaloneHiveRunner.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/FlinkStandaloneHiveServerContext.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/TableEnvHiveConnectorITCase.java
Fix `TableEnvHiveConnectorITCase` for Hive-3.x.
- Set ACID transaction manager for 3.x -- it's required for the transaction table tests.
- Configures the standalone HMS to prepare ACID tables for the test.
Manually verified tests for all hive versions.
NA
NA
> [FLINK-19368][hive] TableEnvHiveConnectorITCase fails with Hive-3.x

- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/factories/TestValuesTableFactory.java
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/table/TableSinkITCase.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/sink/SinkOperator.java
This is a cherry-pick to release-1.11 branch.
> [BP-1.11][FLINK-19695][table-runtime-blink] Fix ClassCastException when writing table with rowtime attribute

- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableSourceITCase.java
Here are some instances:
https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=7845&view=logs&j=fc5181b0-e452-5c8f-68de-1097947f6483&t=62110053-334f-5295-a0ab-80dd7e2babbf
https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=7875&view=logs&j=fc5181b0-e452-5c8f-68de-1097947f6483&t=62110053-334f-5295-a0ab-80dd7e2babbf
Use `TableResult.collect` to assert.
Previous `TestingAppendSink` has thread safe problem.
- The serializers: (no …
> [FLINK-19718][hive] HiveTableSourceITCase.testStreamPartitionRead is not stable

- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/factories/TestValuesTableFactory.java
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/join/TemporalJoinTest.xml
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/batch/sql/join/TemporalJoinTest.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/join/TemporalJoinTest.scala
The 'collection' connector is a legacy connector, we should use the 'values' connector which is based on FLIP-95 interfaces. 
- Replace 'collection' connector by 'values' connector in plan tests
- Decouple scan source and lookup source for values connector …
> [FLINK-19734][table-planner-blink] Replace 'collection' connector by 'values' connector for temporal join plan tests

- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/slotpool/AbstractSlotPoolFactory.java
Add an abstract slot pool factory class to reduce code duplication when we introduce the new slot pool implementation in FLINK-19314.
> [FLINK-19767] Add AbstractSlotPoolFactory

- docs/dev/table/types.md
- docs/dev/table/types.zh.md
*FLINK-19676 fix java package name error in types.md and types.zh.md . java Map in package java.util not in java.lang*
*(or)*
*(or)*
*(example:)*
- …
> [FLINK-19676][docs] java package name error in docs.

- docs/_config.yml
* Update shaded_version to the latest release.
*I modified the "docs/_config.yml"   file .*
*I have verified the changes by starting the build script in preview mode.*
@wuchong @zentol  Please take a look, thank you very much.
> [hotfix][docs] Update shaded_version to the latest release

- flink-mesos/pom.xml
- flink-mesos/src/main/resources/META-INF/NOTICE
This is necessary to fix a vulnerability in Mesos.
This change has only been covered by the e2e tests. I will try to find a user who could help with the testing.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (**yes** / no / don't know) …
> [FLINK-19783] Upgrade Mesos version to 1.7

- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/window/WindowOperator.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/operators/window/WindowOperatorTest.java
Fix NullPointException for WindowOperator.close().
> [FLINK-19777][table-runtime-blink] Fix NullPointException for WindowOperator.close()

- flink-runtime-web/web-dashboard/src/app/pages/job/checkpoints/detail/job-checkpoints-detail.component.html
- flink-runtime-web/web-dashboard/src/app/pages/job/checkpoints/job-checkpoints.component.html
- flink-runtime-web/web-dashboard/src/app/pages/job/checkpoints/subtask/job-checkpoints-subtask.component.html
The format of checkpoint Completion Time and Failure Time should be changed from HH:mm:ss to yyyy-MM-dd HH:mm:ss
change the following format from 'HH:mm:ss' to 'yyyy-MM-dd HH:mm:ss'
Latest Completed Checkpoint:Completion Time
Latest Failed Checkpoint:Failure Time
Latest Savepoint:Completion Time
Latest Restore:Restore Time
This change was tested in locally. …
> [FLINK-19553][web] Make timestamp of checkpoints shown with date format

- flink-runtime-web/web-dashboard/src/app/pages/job/checkpoints/subtask/job-checkpoints-subtask.component.html
- flink-runtime-web/web-dashboard/src/app/pages/job/overview/backpressure/job-overview-drawer-backpressure.component.html
- flink-runtime-web/web-dashboard/src/app/pages/job/overview/watermarks/job-overview-drawer-watermarks.component.ts
This pull request modified web ui subtasks starting index from 0, which can make consistent in the REST API.
Brief change log
*modify web ui subtasks starting index, remove +1 syntax
This pull request doesn't introduce a new feature.
> [FLINK-19594][web] Make subtask index start from zero

- flink-runtime/src/main/java/org/apache/flink/runtime/operators/sort/ExternalSorter.java
Revert the behaviour of logging an InterreputedException on debug level when closing working threads in ExternalSorter. …
> [hotfix] Log interrupted exception on debug when closing threads in ExternalSorter

- flink-runtime/src/main/java/org/apache/flink/runtime/security/modules/JaasModule.java
- flink-runtime/src/test/java/org/apache/flink/runtime/security/modules/JaasModuleTest.java
Create the working dir for Jaas conf proactively.
cc @zentol
> [FLINK-19252] Create the working dir for Jaas conf proactively.

- flink-dist/src/main/flink-bin/bin/config.sh
- flink-dist/src/main/flink-bin/bin/flink-daemon.sh
- flink-dist/src/main/flink-bin/conf/log4j-console.properties
- flink-dist/src/main/flink-bin/conf/log4j.properties
- flink-yarn-tests/src/test/java/org/apache/flink/yarn/YarnTestBase.java
This PR adds rolling logs to the default configuration.
- Rolling logs in log4j.properties
- Roll after 100MB 
This change is a trivial rework / code cleanup without any test coverage. I tested the change by running Flink on EMR (yarn) and local.
> [FLINK-8357] Use rolling logs as default

- docs/dev/table/connectors/formats/avro-confluent.zh.md
I will translate document avro-confluent.md under formats into document avro-confluent.zh.md.
We should update the Chinese documentation with the changes introduced in FLINK-18802
-translate  flink/docs/dev/table/connectors/formats/avro-confluent.zh.md
- If yes, …
> [FLINK-19213][docs-zh] Update the Chinese documentation

- flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonFileSystemFormatFactory.java
Add serialVersionUID to JsonInputFormat class
Add serialVersionUID to JsonInputFormat class
> [Hotfix][json] Add serialVersionUID to JsonInputFormat class

- docs/_includes/generated/rest_v1_dispatcher.html
- flink-runtime-web/src/test/resources/rest_api_v1.snapshot
- flink-runtime-web/web-dashboard/src/app/interfaces/job-checkpoint.ts
- flink-runtime-web/web-dashboard/src/app/pages/job/checkpoints/detail/job-checkpoints-detail.component.html
- flink-runtime-web/web-dashboard/src/app/pages/job/checkpoints/detail/job-checkpoints-detail.component.ts
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/checkpoints/CheckpointStatistics.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/messages/checkpoints/CheckpointingStatisticsTest.java
Add checkpoint type to checkpoint history entries in Web UI
Add checkpoint type to checkpoint history entries in Web UI
Also, we can deploy Flink job with savepoint or checkpoint enable, then you should be able to see checkpoint Type in the flink history tab.
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper:  no …
> FLINK-18851 [runtime] Add checkpoint type to checkpoint history entries in Web UI

- flink-libraries/flink-cep/src/test/java/org/apache/flink/cep/nfa/compiler/NFACompilerTest.java
*fix comments bug of cep test.*
> [FLINK-19915][cep] fix comments bug of cep test.

- docs/dev/table/functions/systemFunctions.md
- docs/dev/table/functions/systemFunctions.zh.md
Improve functions document which are not deterministic
Highlight the behavior of now function in /dev/table/functions/systemFunctions.md.
- The serializers: (no / don't know)
- The runtime per-record code paths (performance sensitive): (no / don't know)
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (no / don't know)
- The S3 file system connector: (no / don't know) …
> [FLINK-19861][document][table-planner/api] Improve functions document which are not deterministic

- flink-runtime/src/main/java/org/apache/flink/runtime/metrics/groups/AbstractMetricGroup.java
- flink-runtime/src/test/java/org/apache/flink/runtime/metrics/groups/AbstractMetricGroupTest.java
Fixes an issue where variables were not cached properly for the last reporter.
> [FLINK-19901][metrics] Fix caching offset for variables

- docs/monitoring/rest_api.zh.md
Translate "Monitoring REST API" page of "Debugging & Monitoring" into Chinese
*(or)*
*(or)*
*(example:)*
- *Added test that validates that TaskInfo …
> [FLINK-19431][docs]Translate "Monitoring REST API" page of "Debugging & Monitoring" into Chinese

- docs/dev/connectors/rabbitmq.zh.md
Add Chinese documentation for the new QoS settings in the RabbitMQ connector. The added English documentation can be found in the PR here: https://github.com/apache/flink/pull/12729/files#diff-6b432359b51642a8fad3050c4b73f47cR134-R167
- add Chinese documentation for the new QoS settings in the RabbitMQ connector into docs/dev/connectors/rabbitmq.zh.md
- The S3 …
> [FLINK-18755][docs-zh] RabbitMQ QoS Chinese Documentation

- docs/monitoring/checkpoint_monitoring.zh.md
*Translate the 'Monitoring Checkpointing' page of 'Debugging & Monitoring' into Chinese*
*Translate the 'Monitoring Checkpointing' page of 'Debugging & Monitoring' into Chinese*
- *page file location: docs/monitoring/checkpoint_monitoring.zh.md*
- *page url in documentation-web is : https://ci.apache.org/projects/flink/flink-docs-release-1.11/zh/monitoring/checkpoint_monitoring.html*
*A pure translation work .* …
> [FLINK-19394][docs-zh] Translate the 'Monitoring Checkpointing' page of 'Debugging & Monitoring' into Chinese

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointITCase.java
In FLINK-19681, `UnalignedCheckpointITCase` was updated to put more backpressure. 
This revealed a bug introduced in FLINK-19907: resultPartitions can be requested before the operator chain is initialized. 
If partitions are requested fast enough then the operator (chain) can receive data before being initialized. In particular, this can cause out-of-orderness: elements from the upstream followed by elements from operator state (not channel state).
A proper fix would be to initialize the chain after the outputs but before the inputs.
- pull the change to `UnalignedCheckpointITCase` from FLINK-19681
- fix initialization in `StreamTask`: inline `readRecoveredChannelState` and put `operatorChain` init between in and out
(the two commits can be squashed)
Updated `UnalignedCheckpointITCase`, …
> [FLINK-20079][task] Fix StreamTask initialization order

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/StreamTask.java
This is a backport of #14024 to 1.11
In FLINK-19681, `UnalignedCheckpointITCase` was updated to put more backpressure. 
This revealed a bug introduced in FLINK-19907: resultPartitions can be requested before the operator chain is initialized. 
If partitions are requested fast enough then the operator (chain) can receive data before being initialized. In particular, this can cause out-of-orderness: elements from the upstream followed by elements from operator state (not channel state).
A proper fix would be to initialize the chain after the outputs but before the inputs.
The bug can't be reproduced in 1.11 with a modified `UnalignedCheckpointITCase` so this change isn't ported. …
> (backport to 1.11) [FLINK-20079][task] Fix StreamTask initialization order 

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/stream/StreamExecJoin.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/optimize/program/FlinkChangelogModeInferenceProgram.scala
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/TableScanTest.xml
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/stream/sql/join/JoinTest.xml
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/stream/sql/TableScanTest.scala
This PR fixes the exception when get the plan of JOIN on changelog source which doesn't contain updates. 
```
[ERROR] testRegularJoin[Source=NO_UPDATE, StateBackend=MiniBatch=OFF](org.apache.flink.table.planner.runtime.stream.sql.ChangelogSourceITCase)  Time elapsed: 0.047 s  <<< ERROR!
2020-11-10T06:39:13.0856712Z org.apache.flink.table.api.TableException: 
2020-11-10T06:39:13.0857161Z UpdateKindTrait [ONLY_UPDATE_AFTER] conflicts with ModifyKindSetTrait [I,D]. This is a bug in planner, please file an issue. 
2020-11-10T06:39:13.0858003Z Current node is Join(joinType=[InnerJoin], where=[(currency = currency0)], select=[amount, currency, currency0, rate], leftInputSpec=[NoUniqueKey], rightInputSpec=[NoUniqueKey]).
```
- Fix `FlinkChangelogModeInferenceProgram`.
- Add …
> [FLINK-20074][table-planner-blink] Fix can't generate plan when joining on changelog source without updates

- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/stream/sql/TemporalJoinITCase.scala
* This pull request to fix the test TemporalJoinITCase.testEventTimeTemoralJoinChangelogUsingBeforeTime
- the test failed if the registered event timer is triggered late and the late delete event from versioned table has arrived,
we simply increase the watermark to ensure  all data from versioned table has been arrived before the event timer fires.
- The S3 file …
> [FLINK-19914][table-planner] fix unstable test TemporalJoinITCase.testEventTimeTemoralJoinChangelogUsingBeforeTime

- flink-dist/src/main/flink-bin/bin/flink-daemon.sh
There are situations where Flink's `JvmShutdownSafeguard` is unable to halt the JVM (if the JVM get's stuck during shutdown)
- The `flink-daemon.sh` will issue a SIGTERM, then wait for 10 seconds for the process to stop. If that is not successful, the script will issue SIGKILL.
I tested the change locally by blocking a shutdown hook and extending the JvmShutdownSafeguard delay to 15 seconds on Linux and Mac.
> [FLINK-17470] Send sigkill to hanging processes in standalone scripts

- docs/_data/sql-connectors.yml
- docs/dev/table/connectors/blackhole.md
- docs/dev/table/connectors/blackhole.zh.md
- docs/dev/table/connectors/datagen.md
- docs/dev/table/connectors/datagen.zh.md
- docs/dev/table/connectors/elasticsearch.md
- docs/dev/table/connectors/elasticsearch.zh.md
- docs/dev/table/connectors/filesystem.md
- docs/dev/table/connectors/filesystem.zh.md
- docs/dev/table/connectors/hbase.md
- docs/dev/table/connectors/hbase.zh.md
- docs/dev/table/connectors/jdbc.md
- docs/dev/table/connectors/jdbc.zh.md
- docs/dev/table/connectors/kafka.md
- docs/dev/table/connectors/kafka.zh.md
- docs/dev/table/connectors/kinesis.md
- docs/dev/table/connectors/kinesis.zh.md
- docs/dev/table/connectors/print.md
- docs/dev/table/connectors/print.zh.md
- docs/dev/table/connectors/upsert-kafka.md
- docs/dev/table/connectors/upsert-kafka.zh.md
*Added document for upsert-kafka.*
> [FLINK-19859][document] Add document for the upsert-kafka connector

- docs/dev/table/connectors/formats/raw.zh.md
Translate page "raw format" into Chinese.
the page url is https://ci.apache.org/projects/flink/flink-docs-master/dev/table/connectors/formats/raw.html.
The doc located in "flink/docs/dev/table/connectors/formats/raw.zh.md".
- translate "flink/docs/dev/table/connectors/formats/raw.zh.md". …
> [FLINK-20163][docs-zh] Translate page "raw format" into Chinese

- docs/dev/table/functions/udfs.md
- docs/dev/table/functions/udfs.zh.md
Fix some typos in udfs.zh.md and udfs.md
> [hotfix][docs]fix_docs_typo

- flink-table/flink-table-planner-blink/src/main/java/org/apache/calcite/sql/SqlTableRef.java
- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/operations/SqlToOperationConverterTest.java
This is a cherry-pick back to release-1.11 branch.
> [BP-1.11][FLINK-20200][table-planner] Fix SQL Hints is not allowed in CREATE VIEW syntax

- docs/ops/cli.md
- docs/ops/cli.zh.md
Remove useless words in [CLI documents](https://ci.apache.org/projects/flink/flink-docs-release-1.11/ops/cli.html).
*(or)*
*(or)*
*(example:)*
- …
> [FLINK-20243][docs]Remove useless words in documents

- docs/dev/table/functions/udfs.md
- docs/dev/table/functions/udfs.zh.md
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/AggregateFunction.java
In the java docs as well as the user docs, the merge method of an aggregation UDF is described as optional, e.g.
```
Merges a group of accumulator instances into one accumulator instance. This function must be implemented for data stream session window grouping aggregates and data set grouping aggregates.
```
However, it seems that nowadays this method is required in more cases (e.g. HOP window in streaming).
- Update the javadoc of "merge" method.
- Update documentations. …
> [FLINK-20059][table-common] Update Javadoc for "merge" method of AggregateFunction

- docs/_data/sql-connectors.yml
- docs/dev/table/connectors/formats/debezium.md
- docs/dev/table/connectors/formats/debezium.zh.md
- docs/dev/table/connectors/kinesis.md
Add documentation for the `debezium-avro-confluent` format.
- Update the existing `debezium.md` page. 
N/A
> [FLINK-20150][debezium-avro] Add documentation for the debezium-avro-confluent format

- docs/ops/security-kerberos.md
- docs/ops/security-kerberos.zh.md
remove ducplicate 'for'
*(or)*
*(or)*
*(example:)*
- …
> [FLINK-20229][docs]remove duplicate "for"

- flink-runtime/src/test/java/org/apache/flink/runtime/testutils/CommonTestUtils.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/TimestampedFileInputSplitTest.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointCompatibilityITCase.java
Backport of https://github.com/apache/flink/pull/13604 where JobClient is replaced by mini cluster client.
Fixes UnalignedCheckpointCompatibilityITCase.test:97->runAndTakeSavepoint: "Not all required tasks are currently running.", which may be caused when deploying takes longer than expected, such that stopWithSavepoint is called before everything is running.
- Allow savepoints to be used in MiniCluster.
- Use JobDetailsInfo to ensure that job and all tasks are running.
Fixes test failure.
- …
> [FLINK-19585][tests] Waiting for job to run before savepointing in UnalignedCheckpointCompatibilityITCase. [1.11]

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/metadata/MetadataV2V3SerializerBase.java
The extra flushing causes a performance degrade without any real benefit as partial checkpoints are neither defined nor usable.
Avoid flushing while writing metadata.
- Removed flush.
Already covered; the performance improvement is not easily testable. 
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (**yes** / no / don't know) …
> [FLINK-19325][checkpointing] Avoid flushing while writing metadata.

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveTableSource.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/FlinkEmbeddedHiveRunner.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/FlinkEmbeddedHiveServerContext.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/FlinkStandaloneHiveRunner.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveRunnerITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableSinkITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveTableSourceITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/TableEnvHiveConnectorITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/catalog/hive/HiveCatalogITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/catalog/hive/HiveCatalogUseBlinkITCase.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/table/catalog/hive/HiveTestUtils.java
Reduce dependency on hive runner for tests, so that tests will be more stable and faster. Besides, tests with hive runner are difficult to debug due to an IDEA issue. Therefore this change also makes debugging a little easier.
- Add `FlinkEmbeddedHiveRunner` to test with embedded metastore. `FlinkStandaloneHiveRunner` is not removed but not actually used any more.
- Add `HiveRunnerITCase` to run with `FlinkEmbeddedHiveRunner`. All other test classes are now hive-runner-free.
- Refactor and clean up of test code.
Existing test cases
NA
NA
> [FLINK-19653][hive] Reduce our dependency on hive runner for tests

- docs/dev/table/connectors/filesystem.md
- docs/dev/table/connectors/filesystem.zh.md
- docs/dev/table/connectors/formats/index.md
- docs/dev/table/connectors/formats/index.zh.md
Update format index and filesystem.
> [FLINK-20310][doc] Add documentation for Debezium, Canal, Raw support for Filesystem connector

- docs/dev/table/connectors/formats/index.md
- docs/dev/table/connectors/formats/index.zh.md
*Update format overview page.*
> [FLINK-20317][doc] Update format overview page

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java
Ignore splits that are re-added in UnalignedCheckpointITCase: Splits are only re-added when a particular task failed but has not been checkpointed yet. In this test setup, tasks are always checkpointed before. This avoids FLINK-20290, which may duplicate splits.
Also this commit increases NETWORK_REQUEST_BACKOFF_MAX to avoid PartitionNotFoundExceptions.
- Added more info messages in the test for easier debugging.
- Ignore splits that are re-added in UnalignedCheckpointITCase.
- Also increased NETWORK_REQUEST_BACKOFF_MAX to avoid PartitionNotFoundExceptions.
Fixing test instability.
- The serializers: (yes / **no** / don't …
> [FLINK-20309][tests] Stabilize UnalignedCheckpointITCase.

- docs/concepts/index.zh.md
- docs/concepts/stateful-stream-processing.md
- docs/concepts/stateful-stream-processing.zh.md
- docs/dev/java_lambdas.zh.md
- docs/dev/parallel.zh.md
- docs/learn-flink/etl.zh.md
In the docs/concepts/stateful-stream-processing.md file, under the first section (What is State), the following two links are broken:
1. Checkpoints: [checkpoints]({{ site.baseurl}}{% link dev/stream/state/checkpointing.md %})
2. Savepoints: [savepoints]({{ site.baseurl }}{%link ops/state/savepoints.md %})
This results in the target link as follows:
1. For Checkpoints: https://ci.apache.org/projects/flink/flink-docs-master//ci.apache.org/projects/flink/flink-docs-master/dev/stream/state/checkpointing.html
2. For Savepoints: https://ci.apache.org/projects/flink/flink-docs-master//ci.apache.org/projects/flink/flink-docs-master/ops/state/savepoints.html
removing {{ site.baseurl}} from both the links, keeping it in lines with the link templates in the doc. 
This change is a trivial code …
> [FLINK-19998] Fixing Invalid Links in docs

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/collect/CollectSinkFunction.java
- Change the log when CollectSinkFunction receives an invalid request from debug to info for future investigation of FLINK-19982.
> [FLINK-19982][test] Change the log when CollectSinkFunction receives an invalid request from debug to info for future investigation

- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PipelinedSubpartition.java
Notification of readView in PipelinedSubpartition happens outside of lock, so between non-null check and actual notification, readView could have been released.
- Cache readView before checking.
Covered by e2e tests. …
> [FLINK-20383][runtime] Fix race condition in notification.

- docs/learn-flink/streaming_analytics.md
- Dependencies (does it add or upgrade a dependency): (yes / no) No
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no) No
- The serializers: (yes / no / don't know) No
- The runtime per-record code paths (performance sensitive): (yes / no / don't know) No
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / no / don't know) No
- The S3 file system connector: (yes / no / don't know) No
- Does this pull request introduce a new feature? (yes / no) No
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) not applicable
> Correct minor typo in docs

- flink-connectors/flink-connector-hbase-base/src/main/java/org/apache/flink/connector/hbase/options/HBaseWriteOptions.java
fix HBaseWriteOptions setParallelism function description
update the HBaseWriteOptions setParallelism function description
> fix HBase setParallelism function description

- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SQLClientSchemaRegistryITCase.java
This PR aims at strengthening the E2E test. Submission of an `INSERT INTO` statement via sql-client is a non-blocking operation, therefore there is a slight chance that the query is not executed before we query the schema registry for a schema for a given subject. This PR adds a retry around the request with a deadline of 30s.
- The S3 …
> [FLINK-20410] Retry querying for schema in the schema registry e2e test.

- docs/dev/stream/testing.zh.md
Translate page "testing" into Chinese.
the page url is https://ci.apache.org/projects/flink/flink-docs-master/zh/dev/stream/testing.html.
The doc located in "flink/docs/dev/stream/testing.zh.md"
- translate "flink/docs/dev/stream/testing.zh.md" …
> [FLINK-20274][docs-zh] Translate page 'testing' into Chinese

- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGenerator.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/SimpleOperatorFactory.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/operators/StreamOperatorFactory.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/api/graph/StreamingJobGraphGeneratorTest.java
For legacy sources, we had to disable chaining because of incompatible threading models.
New sources are working fine however and it would give some users massive performance improvements.
- Added `isLegacySource` to operator factory.
- Only disable chaining for legacy sources.
Added new unit test. …
> [FLINK-20444][runtime] Chain YieldingOperatorFactory to new sources.

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveLookupTableSource.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDynamicTableFactoryTest.java
* Currently we limits the monitor interval should be at least 1 hour to avoid produce pressure to hive meta store, this should be safe in production, but it's inconvenient for demo or simple user case. This pull request to unlock the monitor interval limitation of hive temporal table.
- update file `org/apache/flink/connectors/hive/HiveLookupTableSource.java`
* Add unit test to check monitor interval can be set by users.
- The S3 file …
> [FLINK-20486][hive] Hive temporal join shouldn't require a minimal 1h monitor interval

- docs/_data/sql-connectors.yml
- docs/dev/table/connectors/formats/index.md
- docs/dev/table/connectors/formats/index.zh.md
- docs/dev/table/connectors/formats/maxwell.md
- docs/dev/table/connectors/formats/maxwell.zh.md
- docs/dev/table/connectors/formats/orc.md
- docs/dev/table/connectors/formats/orc.zh.md
- docs/dev/table/connectors/formats/parquet.md
- docs/dev/table/connectors/formats/parquet.zh.md
- docs/dev/table/connectors/formats/raw.md
- docs/dev/table/connectors/formats/raw.zh.md
*Add document for maxwell format*
> [FLINK-18897][doc] Add document for Maxwell format 

- flink-connectors/flink-connector-hive/src/main/java/org/apache/flink/connectors/hive/HiveLookupTableSource.java
- flink-connectors/flink-connector-hive/src/test/java/org/apache/flink/connectors/hive/HiveDynamicTableFactoryTest.java
* Currently we limits the monitor interval should be at least 1 hour to avoid produce pressure to hive meta store, this should be safe in production, but it's inconvenient for demo or simple user case. This pull request to unlock the monitor interval limitation of hive temporal table.
- update file `org/apache/flink/connectors/hive/HiveLookupTableSource.java`
* Add unit test to check monitor interval can be set by users.
- The S3 file …
> [FLINK-20486][hive] Hive temporal join should allow smaller monitor interval than 1 hour

- flink-runtime-web/web-dashboard/src/app/pages/task-manager/list/task-manager-list.component.html
- flink-runtime-web/web-dashboard/src/app/pages/task-manager/status/task-manager-status.component.html
*(or)*
*(or)*
*(example:)*
- *Extended …
> [hotfix][flink-runtime-web] Unified time format of Task Managers tab

- flink-connectors/flink-connector-elasticsearch6/src/main/java/org/apache/flink/streaming/connectors/elasticsearch/table/Elasticsearch6Configuration.java
> [hotfix][javadocs] Fix typo

- docs/dev/table/connectors/upsert-kafka.md
- docs/dev/table/connectors/upsert-kafka.zh.md
Fix typo in upsert kafka docs.
*(or)*
*(or)*
*(example:)*
- …
> [FLINK-20543][docs] Fix typo in upsert kafka docs.

- docs/ops/state/savepoints.zh.md
- docs/try-flink/flink-operations-playground.md
- docs/try-flink/flink-operations-playground.zh.md
*Fix config 'state.savepoint.dir' into 'state.savepoints.dir' in docs*
- *Fix wrong config in `savepoints.zh.md`*
- *Fix wrong config in `flink-operations-playground.md`*
- *Fix wrong config in `flink-operations-playground.zh.md`*
This change is a doc fix without any test coverage. …
> [FLINK-20550][doc] Fix wrong savepoint config in docs

- docs/dev/table/connectors/upsert-kafka.md
- docs/dev/table/connectors/upsert-kafka.zh.md
*fix typo in upsert-kafka docs*
fix typo in upsert-kafka docs
- Dependencies (does it add or upgrade a dependency): (yes / no)no
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)no
- The serializers: (yes / no / don't know)no
- The runtime per-record code paths (performance sensitive): (yes / no / don't know)no
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / no / don't know)no
- The S3 file system connector: (yes / no / don't know)no
- Does this pull request introduce a new feature? (yes / no)no …
> [hotfix][docs] fix typo in upsert-kafka docs

- docs/dev/table/sql/explain.md
- docs/dev/table/sql/explain.zh.md
Fix typo in [EXPLAIN Statements](https://ci.apache.org/projects/flink/flink-docs-release-1.12/dev/table/sql/explain.html) docs.
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after master (JobManager) …
> [FLINK-20565][docs] Fix typo in `EXPLAIN Statements` docs.

- docs/dev/stream/operators/process_function.md
- docs/dev/stream/operators/process_function.zh.md
Fix the `NOTE` tip style in process_function page:
in `/docs/stream/operators/process_function.md`, line 252.  The `NOTE` css style is different from the others.
1. Change the `**NOTE:**` to `<span class="label label-info">Note</span>`
2. remove the `{% top %}` 
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: ( no)
- Does …
> [FLINK-20570][docs] Fix the `NOTE` tip style in process_function page

- docs/_includes/generated/rest_v1_dispatcher.html
- flink-runtime-web/src/test/resources/rest_api_v1.snapshot
- flink-runtime-web/web-dashboard/src/app/interfaces/job-checkpoint.ts
- flink-runtime-web/web-dashboard/src/app/pages/job/checkpoints/job-checkpoints.component.html
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/handler/job/checkpoints/CheckpointConfigHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/rest/messages/checkpoints/CheckpointConfigInfo.java
- flink-runtime/src/test/java/org/apache/flink/runtime/rest/messages/checkpoints/CheckpointConfigInfoTest.java
- Add `Tolerable Failed Checkpoints` to checkpoint configuration in Flink UI.
- Add tolerableFailed config to REST endpoint, and web ui.
- Dependencies (does it add or upgrade a dependency): (yes / no) No
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no) No
- The serializers: (yes / no / don't know) No
- The runtime per-record code paths (performance sensitive): (yes / no / don't know) No
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: (yes / no / don't know) No
- The S3 file system connector: (yes / no / don't know) No
- Does this pull request introduce a new feature? (yes / no) No
- If yes, …
>  [FLINK-20209][web] Add tolerable failed checkpoints config to web ui

- docs/_layouts/404_base.html
- docs/concepts/stateful-stream-processing.zh.md
> [FLINK-20422][bp-1.12] Fix invalid links across languages

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisProducer.java
The Kinesis producer is loading some classes which register static final instance fields. These fields prevent the user code classloader from unloading, leading to pollution of the JVM Metaspace.
I manually verified the behavior by monitoring the metaspace of a TaskManager. The initial spikes are caused by a Kinesis Producer implementation with the new changes applied (= using the classloader shutdown hook). Later, the TM gets killed by running out of JVM metaspace, when running the old Kinesis Producer implementation.
> [FLINK-19259][Kinesis] Remove references to allow classloader unloading

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java
UnalignedCheckpointITCase may timeout because of some invalid assumptions and rare issues caused by overloading of the test machines.
Improves UnalignedCheckpointITCase in the following ways to avoid running into rare issues or better deal with them:
- Reduce load on test machine: Executing a test with p=10 may spawn up to 70 tasks that until backpressured can potentially lead to a full load on 70 cores. This may causes larger GC pauses and other JVM freezes that will trigger the rare PartitionNotFound exception. Now, sources are throttled until the sink backpressures.
- Keep track of restart attempts in split enumerator and sink with source instances. Only finish sources if the desired numbers of failures occurred to avoid finishing too quickly.
- Avoid relying completely on …
> [FLINK-20433][tests] Stabilizing UnalignedCheckpointITCase.

- docs/dev/table/connectors/filesystem.md
- docs/dev/table/connectors/filesystem.zh.md
improve the filesystem connector doc
> [hotfix][filesystem]improve the filesystem connector doc

- docs/dev/table/sql/create.md
- docs/dev/table/sql/create.zh.md
Fix typos in [CREATE Statements](https://ci.apache.org/projects/flink/flink-docs-release-1.12/dev/table/sql/create.html) docs.
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after master (JobManager) …
> [FLINK-20582][docs] Fix typos in `CREATE Statements` docs.

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java
Unmodified backport of #14348.
UnalignedCheckpointITCase may timeout because of some invalid assumptions and rare issues caused by overloading of the test machines.
Improves UnalignedCheckpointITCase in the following ways to avoid running into rare issues or better deal with them:
- Reduce load on test machine: Executing a test with p=10 may spawn up to 70 tasks that until backpressured can potentially lead to a full load on 70 cores. This may causes larger GC pauses and other JVM freezes that will trigger the rare PartitionNotFound exception. Now, sources are throttled until the sink backpressures.
- Avoid relying completely on notifyCheckpointComplete to finish test: notifyCheckpointComplete is not guaranteed to be called but the test completely relied on it. This may lead to indefinite …
> [FLINK-20433][tests] Stabilizing UnalignedCheckpointITCase. [1.12]

- flink-connectors/flink-connector-jdbc/pom.xml
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/JdbcInputFormat.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/internal/connection/SimpleJdbcConnectionProvider.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/table/JdbcLookupFunction.java
- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/table/JdbcRowDataLookupFunction.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/fakedb/FakeDBUtils.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/fakedb/driver/FakeConnection.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/fakedb/driver/FakeConnection1.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/fakedb/driver/FakeConnection2.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/fakedb/driver/FakeDriver1.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/fakedb/driver/FakeDriver2.java
- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/internal/connection/SimpleJdbcConnectionProviderDriverClassConcurrentLoadingTest.java
- flink-connectors/flink-connector-jdbc/src/test/resources/META-INF/services/java.sql.Driver
This is a cherry pick back to release-1.12 branch.
> [BP-1.12][FLINK-19435] Fix Deadlock when loading different driver classes concurrently using Class.forName

- docs/dev/table/connectors/jdbc.md
- docs/dev/table/connectors/jdbc.zh.md
…"lookup.cache.ttl" in jdbc.md/jdbc.zh.md
Correct the Type and Default value of "lookup.cache.ttl" in jdbc.md/jdbc.zh.md
> [FLINK-20697][Connector][jdbc] Correct the Type and Default value of "lookup.cache.ttl" in jdbc.md/jdbc.zh.md

- flink-python/pyflink/fn_execution/flink_fn_execution_pb2.py
- flink-python/pyflink/fn_execution/operation_utils.py
- flink-python/pyflink/java_gateway.py
- flink-python/pyflink/proto/flink-fn-execution.proto
- flink-python/pyflink/table/expressions.py
- flink-python/pyflink/table/table.py
- flink-python/pyflink/table/table_environment.py
- flink-python/pyflink/table/tests/test_row_based_operation.py
- flink-python/pyflink/table/udf.py
- flink-python/src/main/java/org/apache/flink/streaming/api/utils/PythonOperatorUtils.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/local/ExecutionContextTest.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/python/PythonAggregateFunction.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/python/PythonFunction.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/python/PythonScalarFunction.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/python/PythonTableAggregateFunction.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/functions/python/PythonTableFunction.java
*This pull request will support row-based operation to accept user-defined function directly*
- *IT test in `test_row_based_operation.py`*
> [FLINK-20616][python] Support row-based operation to accept user-defined function directly

- docs/_includes/generated/execution_checkpointing_configuration.html
- flink-streaming-java/src/main/java/org/apache/flink/streaming/api/environment/ExecutionCheckpointingOptions.java
*(or)*
*(or)*
*(example:)*
- *Extended …
> [hotfix][conf] Fix typo.

- docs/dev/table/sql/gettingStarted.md
fix the doc wrong word "docs/dev/table/sql/gettingStarted.md"
*(or)*
*(or)*
*(example:)*
- *Added integration tests for …
> [DOC]fix the wrong word

- flink-clients/src/main/java/org/apache/flink/client/cli/CliFrontend.java
Missing 'run-application' action in the CLI help message when user enters an unsupported action.
> Valid actions are "run", "list", "info", "savepoint", "stop", or "cancel".
- *Add 'run-application' action in the CLI help meassge.* …
> [FLINK-20686] CLI help message should include 'run-application' action

- docs/dev/connectors/file_sink.md
- docs/dev/connectors/file_sink.zh.md
- docs/dev/connectors/streamfile_sink.md
- docs/dev/connectors/streamfile_sink.zh.md
There  are some documents error.
> [DOC]fix to update file_sink & streamfile_sink doc for error code

- docs/dev/table/streaming/joins.md
- docs/dev/table/streaming/joins.zh.md
> [hotfix][docs] Fix typo

- docs/try-flink/flink-operations-playground.md
fix typo in "Flink Operation Playground": "are generate" => "are generated"
fix typo
> [hotfix][docs] Typo doc operation playground

- docs/dev/stream/state/checkpointing.md
- docs/dev/stream/state/checkpointing.zh.md
The demo code in doc missed one parenthesis.
Just one line small change.
> Fix java demo code

- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/rules/logical/PythonCorrelateSplitRule.java
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/rules/FlinkBatchRuleSets.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/rules/FlinkStreamRuleSets.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/rules/logical/PythonCalcSplitRule.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/utils/PythonUtil.scala
- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/runtime/utils/JavaUserDefinedScalarFunctions.java
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/PythonCalcSplitRuleTest.xml
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/plan/rules/logical/PythonCalcSplitRuleTest.scala
*This pull request Fix the bug that it doesn't support field access of expression containing Python UDF*
> [FLINK-20756][python] Fix the bug that it doesn't support field access of expression containing Python UDF

- docs/dev/table/sql/gettingStarted.md
- docs/dev/table/sql/gettingStarted.zh.md
[FLINK-20458](https://issues.apache.org/jira/browse/FLINK-20458?src=confmacro)
Translate the doc "docs/dev/table/sql/gettingStarted.zh.md"
- Translate the doc "docs/dev/table/sql/gettingStarted.zh.md"
- Correct spelling errors in "docs/dev/table/sql/gettingStarted.md"
- If …
> [FLINK-20458][docs] translate gettingStarted.zh.md and correct spelling errors in gettingStarted.md

- docs/dev/table/sql/queries.md
- docs/dev/table/sql/queries.zh.md
The ' Expanding arrays into a relation ' section is so simple. I can not understand the usage when I see this section.
It should be added more examples and explanations.
I add more examples and describe the array element type. …
> [FLINK-19962][docs]  Add examples and explanations for expanding arrays into a relation

- flink-examples/flink-examples-table/src/main/java/org/apache/flink/table/examples/java/basics/UpdatingTopCityExample.java
There is a minor bug in streaming sql example `UpdatingTopCityExample`
- `UpdatingTopCityExample`
- Covered by the example itself.
> [FLINK-20826][table] Fix minor bug in `UpdatingTopCityExample`

- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/agg/batch/HashAggCodeGenHelper.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/agg/batch/HashAggCodeGenerator.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/codegen/agg/batch/HashWindowCodeGenerator.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/batch/BatchExecHashWindowAggregateBase.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/aggregate/BytesHashMap.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/aggregate/BytesMap.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/aggregate/BytesMultiMap.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/util/KeyValueIterator.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/util/LazyMemorySegmentPool.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/operators/aggregate/BytesHashMapTest.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/operators/aggregate/BytesMapTestBase.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/operators/aggregate/BytesMultiMapTest.java
- flink-table/flink-table-runtime-blink/src/test/java/org/apache/flink/table/runtime/operators/aggregate/SumHashAggTestOperator.java
Introduce `BytesMultiMap` to support buffering records.
- Extract a common base class `BytesMap` for `BytesHashMap` and `BytesMultiMap`
- Update the code generation for the `BytesHashMap` refactoring 
- Introduce the class of `BytesMultiMap`
- the existing tests and added a `BytesMultiMapTest` …
> [FLINK-20854][table-runtime-blink] Introduce BytesMultiMap to support buffering records

- flink-formats/flink-json/src/main/java/org/apache/flink/formats/json/JsonRowDataDeserializationSchema.java
- flink-formats/flink-json/src/test/java/org/apache/flink/formats/json/JsonRowDataSerDeSchemaTest.java
Support allow-unescaped-control-chars option for JSON format.
*(or)*
*(or)*
*(example:)*
- *Added test that validates that TaskInfo is transferred …
> [FLINK-20773][json] Support to parse unescaped control chars in string node

- docs/dev/table/common.md
- docs/dev/table/common.zh.md
*replacement of deprecated syntax in Table API documentation*
* removes from documentation statements using this syntax: `tableEnv.connect(...).createTemporaryTable("table1");`, which is [marked as depracated](https://github.com/apache/flink/blob/97bfd049951f8d52a2e0aed14265074c4255ead0/flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/api/bridge/java/StreamTableEnvironment.java#L629)
* renames `Table` instance `tapiResult` into `table2`, since the "Result" suffix was introducing confusion with possible instances of `TableResult` , which are returned by other methods of `tableEnv` 
ran `./build_docs.sh -p` and checked the result visually …
> [FLINK-20907][docs] replaces deprecated syntax in Table API doc

- flink-python/src/main/java/org/apache/flink/streaming/api/runners/python/beam/BeamPythonFunctionRunner.java
*This pull request Optimize State with Cross Bundle State Cache In PyFlink*
- *Let StateRequestHandler for user state only use a single cache token*
- *Original Tests*
class MeanAggregateFunction(AggregateFunction):
def get_value(self, …
> [FLINK-20954][python] Support state cache between bundles

- docs/dev/table/connectors/hbase.md
- docs/dev/table/connectors/hbase.zh.md
> [FLINK-20967][docs] HBase properties 'properties.*' function Description

- docs/_includes/generated/execution_config_configuration.html
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/gateway/local/ExecutionContextTest.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/config/ExecutionConfigOptions.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecHashAggregate.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecHashJoin.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecHashWindowAggregate.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecNestedLoopJoin.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecOverAggregate.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecSort.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/batch/BatchExecSortMergeJoin.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/utils/ExecNodeUtil.java
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/plan/nodes/physical/batch/BatchPhysicalSortMergeJoin.scala
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/hashtable/BaseHybridHashTable.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/sort/BinaryExternalSorter.java
- flink-table/flink-table-runtime-blink/src/main/java/org/apache/flink/table/runtime/operators/sort/BufferedKVExternalSorter.java
Use MemorySize type instead of String type for memory ConfigOption in ExecutionConfigOptions
> [FLINK-20879][table-api] Use MemorySize type instead of String type for memory ConfigOption in ExecutionConfigOptions

- flink-runtime/src/main/java/org/apache/flink/runtime/jobmaster/slotpool/ResourceCounter.java
- flink-runtime/src/test/java/org/apache/flink/runtime/jobmaster/slotpool/ResourceCounterTest.java
Improves edge-case handling of `ResourceCounter#withResources`.
> [FLINK-20980][coordination] Improve edge-case handling

- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/MailboxOperatorTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/StreamTaskMailboxTestHarness.java
> [FLINK-20462][runtime] Port MailboxOperatorTest to StreamTaskMailboxTestHarness. [1.12]

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/ChannelStateWriteRequest.java
- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/RecoveredChannelStateHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/logger/NetworkActionsLogger.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/RemoteInputChannel.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGate.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java
> [FLINK-20309][tests] Make source split assignment in UnalignedCheckpointITCase stable. [1.12]

- docs/_includes/generated/expert_security_ssl_section.html
- docs/_includes/generated/security_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/SecurityOptions.java
The description of ConfigOption 'security.ssl.internal.session-cache-size' has a URL link, so a reasonable way is to use Text Description with Link to format.
- The ConfigOption 'security.ssl.internal.session-cache-size' use text with link to descript
- The S3 file …
> [FLINK-20914][core] Format the description of 'security.ssl.internal.session-cache-size' option

- docs/dev/table/legacy_planner.zh.md
change legacy_planner.zh.md some English links to Zh links
change legacy_planner.zh.md some English links to Zh links
> [FLINK-21039][doc] change legacy_planner.zh.md some English links to Zh links

- docs/dev/table/functions/udfs.md
- docs/dev/table/functions/udfs.zh.md
*(or)*
*(or)*
*(example:)*
- *Extended …
> [hotfix][docs] Fix typo in 'docs/dev/table/functions/udfs.md & udfs.zh.md'.

- flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/CatalogView.java
*(or)*
*(or)*
*(example:)*
- *Extended …
> [hotfix][javadoc] Correct the wrong spelling 'perserves' to 'preserves'.

- docs/dev/table/functions/udfs.md
*Correct the error in the code example in section 'aggregate-functions' of table-page 'udfs'.*
The markdown file location: flink/docs/dev/table/functions/udfs.md 
The target url : https://ci.apache.org/projects/flink/flink-docs-master/dev/table/functions/udfs.html#aggregate-functions
*Correct the error in the code example in section 'aggregate-functions' of table-page 'udfs'.*
- *The 'value' is a reserved keyword of the flink table module,So the correct usage should to execute in back quotes .*
*Pure documentation change.* …
> [FLINK-21042][docs] Correct the error in the code example in section 'aggregate-functions' of table-page 'udfs'.

- docs/_data/sql-connectors.yml
- docs/_includes/sql-connector-download-table.html
- docs/_includes/sql-connector-download-table.zh.html
- docs/dev/table/connectors/formats/raw.md
- docs/dev/table/connectors/formats/raw.zh.md
*fix documentation mistake: the raw format is a built-in format distributed with blink-table-planner but was documented as a separate jar.*
- *removed `flink-raw.jar` reference from `site-connector.yml`*
- *update the raw format documentation: no longer loads the `sql-connnector-download-table.html` snippet*
- *added maven xml format to connectors and format documentation for user convenience*
I manually ran `./build_docs.sh -p  `, the format seems ok now. …
> [FLINK-20998][docs] - flink-raw.jar no longer mentioned + prettier maven xml dependencies

- flink-connectors/flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/xa/SemanticXidGenerator.java
With only 4 random bytes, `testXidsUniqueAmongGenerators` fails
once per ~100 runs as it deliberately uses same checkpointId
and subtaskIdx.
This change makes Semantic`XidGenerator` use 8 random bytes
instead of 4 higher bytes of `checkpointId`.
Already covered by `testXidsUniqueAmongGenerators`.
> [FLINK-21044][connectors/jdbc] Use more random bytes in Xid

- flink-end-to-end-tests/test-scripts/common_docker.sh
> [FLINK-21071][docker][tests] Run docker tests against 1.11 images

- docs/_data/sql-connectors.yml
- docs/_includes/sql-connector-download-table.html
- docs/dev/table/connectors/formats/raw.md
- docs/dev/table/connectors/formats/raw.zh.md
Port of the documentation update of https://github.com/apache/flink/pull/14672
> [FLINK-20998][docs] - cherry pick: flink-raw.jar no longer mentioned + prettier maven deps

- docs/ops/state/checkpoints.md
- docs/release-notes/flink-1.12.md
- docs/release-notes/flink-1.12.zh.md
Add a warning that unaligned checkpoints are not working as expected.
> [FLINK-20654][docs] Adding unaligned checkpoint warning to release notes/docs.

- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableITCase.java
- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/rules/logical/PushWatermarkIntoTableSourceScanRuleBase.java
- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/plan/rules/logical/PushWatermarkIntoTableSourceScanRuleTest.java
- flink-table/flink-table-planner-blink/src/test/resources/org/apache/flink/table/planner/plan/rules/logical/PushWatermarkIntoTableSourceScanRuleTest.xml
*Fix idle source doesn't work when pushing watermark strategy into table source.*
- *Fix the bug.*
- *Idle source plan test.*
- *Idle source IT cases.*
> [FLINK-20947][planner] Fix idle source doesn't work when pushing watermark into the source

- docs/dev/table/sql/hints.zh.md
*Translate the 'SQL Hints' page of 'Table API & SQL' into Chinese*
*Translate the 'SQL Hints' page of 'Table API & SQL' into Chinese*
*Translate the 'SQL Hints' page of 'Table API & SQL' into Chinese*
- If yes, how …
> [FLINK-19393][docs-zh] Translate the 'SQL Hints' page of 'Table API & SQL' into Chinese

- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSource.java
- flink-connectors/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/KafkaSourceEnumerator.java
- flink-connectors/flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/enumerator/KafkaEnumeratorTest.java
1.12 backport of https://github.com/apache/flink/pull/14711
> [release-1.12][FLINK-21059][kafka] KafkaSourceEnumerator does not honor consumer properties

- docs/dev/table/connectors/formats/avro-confluent.md
- docs/dev/table/connectors/formats/avro-confluent.zh.md
* Provide additional examples of how to use the avro-confluent format. In particular, no example of how to serialize the kafka key or use the upsert connector are currently mentioned in the [avro confluent connector documentation](https://ci.apache.org/projects/flink/flink-docs-release-1.12/dev/table/connectors/formats/avro-confluent.html)
- Added an example of a table serializing the kafka value in an avro record registered in the schema registry, while keeping the key in raw format
- Added an example of how to write to that table
- Added an example of a table using the schema registry for both the key and value
- Added an example of using the schema registry together with the kafka upsert connector
Only the English version of the documentation has been updated so far. Once the  examples …
> [Flink-20999][docs] - adds usage examples to the Kafka Avro Confluent connector format

- flink-connectors/flink-connector-kinesis/src/main/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutRecordPublisher.java
- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/internals/publisher/fanout/FanOutRecordPublisherTest.java
Add missing letter in exception name. Instead of "reties", now it's "retries"
N/A
> [hotfix] [code] Fix typo in exception name

- docs/flinkDev/building.md
> [FLINK-13996][docs] Update instructions on building with Maven 3.3+

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/channel/RecoveredChannelStateHandler.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/logger/NetworkActionsLogger.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/PipelinedSubpartition.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/ChannelStatePersister.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/LocalInputChannel.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/RecoveredInputChannel.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/RemoteInputChannel.java
- flink-runtime/src/main/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGate.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/ChannelStatePersisterTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/SingleInputGateTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/partition/consumer/TestInputChannel.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/io/CheckpointedInputGate.java
- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/mailbox/TaskMailboxImpl.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/AlternatingControllerTest.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/io/CheckpointedInputGateTest.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointITCase.java
- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java
This is a backport of https://github.com/apache/flink/pull/14797 to release-1.12 branch
> backport [FLINK-20654][FLINK-21104][network] Fix couple bugs in the handling of unaligned checkpoints and cancellations.

- flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/source/ScanTableSource.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/source/abilities/SupportsAggregatePushDown.java
- flink-table/flink-table-common/src/main/java/org/apache/flink/table/expressions/AggregateExpression.java
- flink-table/flink-table-planner-blink/src/test/java/org/apache/flink/table/planner/factories/TestValuesTableFactory.java
*This pull request introduces a new TableSourceAbility interface for supporting aggregation push down.*
- *A new interface of SupportsAggregatePushDown*
- *A new implementation of ResolvedExpression which is AggregateExpression*
- *Implement the new SupportsAggregatePushDown interface for TestValuesScanTableSource*
This change is only introduced a few new interfaces, and implemented for a test class, which already covered by existing tests, such as *TableSourceITCase*. …
> [FLINK-20894][Table SQL / API] Introduce SupportsAggregatePushDown interface

- flink-connectors/flink-connector-elasticsearch6/pom.xml
- flink-connectors/flink-connector-elasticsearch7/pom.xml
- flink-end-to-end-tests/flink-end-to-end-tests-common-kafka/pom.xml
- flink-end-to-end-tests/flink-end-to-end-tests-common/pom.xml
It fixes https://github.com/testcontainers/testcontainers-java/issues/3574
> [FLINK-21277] Bump testcontainers version

- flink-connectors/flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/table/UnsignedTypeConversionITCase.java
Fix typo in `UnsignedTypeConversionITCase`
*(or)*
*(or)*
*(example:)*
- *Manually verified the change …
> [hotfix][typo]Fix typo in `UnsignedTypeConversionITCase`

- docs/learn-flink/etl.md
- docs/learn-flink/etl.zh.md
Changed the inconsistent variable names in `learn-flink` etl
> [hotfix][docs] Correct variable name

- flink-runtime/pom.xml
- flink-runtime/src/main/java/org/apache/flink/runtime/util/EnvironmentInformation.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/util/TestLogger.java
- flink-test-utils-parent/flink-test-utils-junit/src/main/java/org/apache/flink/util/TestNameProvider.java
- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/streaming/util/PseudoRandomValueSelector.java
- flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/streaming/util/TestStreamEnvironment.java
- flink-test-utils-parent/flink-test-utils/src/test/java/org/apache/flink/streaming/util/PseudoRandomValueSelectorTest.java
- pom.xml
With the larger refactoring of checkpoint alignment and the additional of more unaligned checkpoint settings, it becomes increasingly important to provide a large test coverage.
Unfortunately, adding sufficient test cases in a test matrix appears to be unrealistic: many of the encountered issues were subtle, sometimes caused by race conditions or unusual test configurations and often only visible in e2e tests.
Hence, we like to rely on all existing Flink tests to provide a sufficient coverage for checkpointing. However, as more and more options in unaligned checkpoint are going to be implemented in this and the upcoming release, running all Flink tests - especially e2e - in a test matrix is prohibitively expensive, even for nightly builds.
Thus, we want to introduce test randomization for …
> [FLINK-19520][configuration] Add randomization of checkpoint config.

- flink-runtime/src/main/java/org/apache/flink/runtime/state/AbstractKeyedStateBackend.java
A trivial change that slightly improves logging in `AbstractKeyedStateBackend`
(motivated by work on FLIP-151 PoC).
> [hotfix][state] Improve logging in AbstractKeyedStateBackend

- tools/ci/build_docs.sh
The destination argument is relative to the source
> [hotfix][ci] Fix hugo docs builds

- flink-runtime/src/main/java/org/apache/flink/runtime/concurrent/FutureUtils.java
Add an explanation why is the current solution working and also clean it up a little bit (dropping unecessary volatile and adding final keyword).
Please check the ticket for more detailed explanation and discussion.
This change should be covered by a variety of the existing tests.
> [FLINK-21365][runtime] Document and make the contract of FutureUtilsResultConjunctFuture more explicit

- docs/layouts/shortcodes/generated/all_jobmanager_section.html
- docs/layouts/shortcodes/generated/expert_scheduling_section.html
- docs/layouts/shortcodes/generated/job_manager_configuration.html
- flink-core/src/main/java/org/apache/flink/configuration/JobManagerOptions.java
- flink-runtime/src/main/java/org/apache/flink/runtime/scheduler/declarative/DeclarativeScheduler.java
- flink-runtime/src/test/java/org/apache/flink/runtime/scheduler/declarative/DeclarativeSchedulerTest.java
> [FLINK-21360][coordination] Make resource timeout configurable 

- docs/content.zh/docs/connectors/table/formats/avro-confluent.md
- docs/content/docs/connectors/table/formats/avro-confluent.md
[FLINK-21176](https://issues.apache.org/jira/browse/FLINK-21176)
Translate the updates of 'avro-confluent.zh.md' to Chinese
- Translate the updates to Chinese, doc location is 'docs/dev/table/connectors/formats/avro-confluent.zh.md' …
> [FLINK-21176][docs] translate the updates of 'avro-confluent.zh.md' to Chinese

- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/delegation/PlannerContext.java
Fix grammar error in code comment `flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/delegation/PlannerContext.java`: "be overwrite" => "be overwritten"
> [hotfix][javadoc] fix syntax error for PlannerContext.java: from "be overwrite" to "be overwritten" 

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTask.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTaskTest.java
This is a backport of https://github.com/apache/flink/pull/14968
> [FLINK-21028][task] Do not interrupt the source thread on stop with savepoint (1.11)

- flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTask.java
- flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/tasks/SourceStreamTaskTest.java
This is a backport of https://github.com/apache/flink/pull/14968
> [FLINK-21028][task] Do not interrupt the source thread on stop with savepoint (1.12)

- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/CoordinatedSourceRescaleITCase.java
- flink-core/src/main/java/org/apache/flink/api/connector/source/lib/util/IteratorSourceReader.java
- flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContext.java
- flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorSerdeUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContextTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorProviderTest.java
Unchanged backport of #14994.
Sources used to store their registered readers into the snapshot. However, when downscaling, they have unmatched readers that violate a couple of invariants.
The solution is to not store registered readers - they are re-registered on restart anyways.
To keep it backward compatible, the best option is to always store an empty list of readers while writing the snapshot and discard any recovered readers from the snapshot.
A respective ITCase will be added as part of #13845 (FLINK-19801).
- The runtime per-record code paths (performance sensitive): (yes / …
> [FLINK-21452][connector/common] Stop snapshotting registered readers in source coordinator. [1.12]

- flink-connectors/flink-connector-base/src/test/java/org/apache/flink/connector/base/source/reader/CoordinatedSourceRescaleITCase.java
- flink-core/src/main/java/org/apache/flink/api/connector/source/lib/util/IteratorSourceReader.java
- flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContext.java
- flink-runtime/src/main/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorSerdeUtils.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorContextTest.java
- flink-runtime/src/test/java/org/apache/flink/runtime/source/coordinator/SourceCoordinatorProviderTest.java
Sources used to store their registered readers into the snapshot. However, when downscaling, they have unmatched readers that violate a couple of invariants.
The solution is to not store registered readers - they are re-registered on restart anyways.
To keep it backward compatible, the best option is to always store an empty list of readers while writing the snapshot and discard any recovered readers from the snapshot.
A respective ITCase will be added as part of #13845 (FLINK-19801).
- …
> [FLINK-21452][connector/common] Stop snapshotting registered readers in source coordinator.

- flink-runtime/src/test/java/org/apache/flink/runtime/io/network/api/writer/RecordOrEventCollectingResultPartitionWriter.java
Since FLINK-19297 we accidentally removed a test coverage for event (de)serialization from a lot of the unit tests, that were/are using test harnesses. For example because of that I almost broke 1.12.2 release, since `stop-with-savepoint --drain` was never only tested using test harnesses (didn't have an ITCases and/or end to end test).
- …
> [FLINK-21517][tests] Test harnesses should not bypass serialization stack for events

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/ProcessingTimeWindowCheckpointingITCase.java
1. Prevent test from hanging if stream contains duplicates
2. Improve error reporting
> [hotfix][tests] Improve ProcessingTimeWindowCheckpointingITCase

- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTest.java
**Backport of #15037 to 1.12**
```
The instability is caused by last assertion depending on timing.
Solve by waiting on condition.
Another issue is that failure can cause RejectionExecutionException.
This is caused by shutting down executor (in tests finally block)
without shutting down CheckpointCoordinator.
Solve by shutting down CheckpointCoordinator first.
``` …
> [BP-1.12][FLINK-21518][tests] Fix testMinCheckpointPause instability 

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliClient.java
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/SqlCommandParser.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliClientTest.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/SqlCommandParserTest.java
This pull request added "SHOW VIEWS" to SQL client.
added callShowViews method that execute the 'SHOW VIEW' SqlCommand  to CliClient.
added 'SHOW VIEW' SqlCommand to SqlCommandParser.
added unit tests in CliClientTest and SqlCommandParserTest.
- If yes, how is the feature documented? Docs will …
> [FLINK-21231][sql-client] add "SHOW VIEWS" to SQL client

- docs/content.zh/docs/dev/table/tableApi.md
- docs/content/docs/dev/table/tableApi.md
Just a quick syntax fix for java code samples
> [hotfix][docs] adds missing semicolons in java code example

- flink-runtime/src/main/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinator.java
- flink-runtime/src/test/java/org/apache/flink/runtime/checkpoint/CheckpointCoordinatorTest.java
With FLINK-20222 fix, it brings the regression that the master hook's `reset()` is called only in global recovery case, which causes the test failure(details in https://github.com/pravega/flink-connectors/issues/441) in [Pravega Flink connector](https://github.com/pravega/flink-connectors)
- Always reset the master hooks at the restore.
This change is already covered by existing tests, such as the test case in Pravega Flink connector. …
> [FLINK-21178][Runtime/Checkpointing] Task failure should trigger master hook's reset()

- docs/content/docs/dev/table/sql/create.md
This PR fixes an error in the `CREATE VIEW` statement description where curly braces were used instead of normal ones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apache/flink/15077)
> [hotfix][docs] wrong brackets in CREATE VIEW statement

- docs/layouts/shortcodes/generated/table_config_configuration.html
- flink-python/pyflink/table/environment_settings.py
- flink-python/pyflink/table/tests/test_environment_settings.py
- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/gateway/local/ExecutionContext.java
- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/api/bridge/java/BatchTableEnvironment.java
- flink-table/flink-table-api-java-bridge/src/main/java/org/apache/flink/table/api/bridge/java/StreamTableEnvironment.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/EnvironmentSettings.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/PlannerType.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/TableConfig.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/TableEnvironment.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/config/TableConfigOptions.java
- flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentImpl.java
- flink-table/flink-table-api-java/src/test/java/org/apache/flink/table/api/EnvironmentSettingsTest.java
- flink-table/flink-table-api-scala-bridge/src/main/scala/org/apache/flink/table/api/bridge/scala/BatchTableEnvironment.scala
- flink-table/flink-table-api-scala-bridge/src/main/scala/org/apache/flink/table/api/bridge/scala/StreamTableEnvironment.scala
- flink-table/flink-table-api-scala-bridge/src/main/scala/org/apache/flink/table/api/bridge/scala/internal/StreamTableEnvironmentImpl.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/delegation/BatchPlanner.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/delegation/PlannerBase.scala
- flink-table/flink-table-planner-blink/src/main/scala/org/apache/flink/table/planner/delegation/StreamPlanner.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/api/TableEnvironmentITCase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/runtime/utils/BatchTestBase.scala
- flink-table/flink-table-planner-blink/src/test/scala/org/apache/flink/table/planner/utils/TableTestBase.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/api/internal/BatchTableEnvImpl.scala
- flink-table/flink-table-planner/src/main/scala/org/apache/flink/table/planner/StreamPlanner.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/batch/BatchTableEnvironmentTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/api/stream/StreamTableEnvironmentTest.scala
- flink-table/flink-table-planner/src/test/scala/org/apache/flink/table/utils/TableTestBase.scala
*Allow to create table environment from `Configuration`. However, it's not allowed to modify the planner type or execution mode when table environment is built.*
- *Add `TableEnvironment#create(Configuration)`*
- *Add method to convert between `Configuration` and `EnvironmentSettings`*
- *Add test about transform between `EnvironmentSetting` and `Configuration`*
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: …
> [FLINK-21460][table api] Use Configuration to create TableEnvironment

- flink-table/flink-table-planner-blink/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecDeduplicate.java
Fix a typo in the comment for RowtimeDeduplicateOperatorTranslator in StreamExecDeduplicate.java: "process time " => "row time"
Fix a typo in the comment for RowtimeDeduplicateOperatorTranslator in StreamExecDeduplicate.java: "process time " => "row time"
- Dependencies (does it add or upgrade a dependency): no 
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no 
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn/Mesos, ZooKeeper: no 
- Does this pull request introduce a new feature? no 
- If yes, how …
> [FLINK-21684][table-planner-blink] Fix typo in StreamExecDeduplicate

- flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/FlinkKinesisConsumerTest.java
Updating unit test to fail if timeout occurs while waiting for records.
This is a change to a test class only.
> [FLINK-17441][kinesis][test-stability] Updating test to assert if timeout occurs waiting for records

- flink-table/flink-sql-client/src/main/java/org/apache/flink/table/client/cli/CliTableauResultView.java
- flink-table/flink-sql-client/src/test/java/org/apache/flink/table/client/cli/CliTableauResultViewTest.java
*Before explain the reason why test fails, I will just describe the logic in the test. There are 3 parts in the test: `TestingExecutor`, `Terminal` and `CliTableauResultView`. The `CliTableauResultView` will requst the data from the `TestingExecutor` and send the data to `Terminal` to print. When `CliTableauResultView` request data from `TestingExecutor`, the `TestingExecutor` will memorize how many times `CliTableauResultView` reads. For simplicty, we call this variable as `numRetrieveResultChancesCalls`.*
*In the test, if `numRetrieveResultChancesCalls` is larger than 0, we will cancel the `CliTableauResultView`. It's possible `CliTableauResultView` read the data from the `TestingExecutor` but the terminal haven't printed.*
*Therefore, we just need to modify the logic to wait the …
> [FLINK-21740][sql client] Fix unstable CliTableauResultViewTest

- flink-tests/src/test/java/org/apache/flink/test/checkpointing/UnalignedCheckpointTestBase.java
> [FLINK-21535][tests] Improved the detection of the attempt number in UnalignedCheckpointITCase. [1.12]
